INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Carlos Mendes Gomes', 'Spain', 'player'),
	('Thomas Chacon', 'Uruguay', 'player'),
	('Maximilian Breunig', 'Germany', 'player'),
	('Ahmed Bani', 'Romania', 'player'),
	('Tiberiu Căpușă', 'Romania', 'player'),
	('Warren Burrell', 'England', 'player'),
	('Hatim Belal', 'Saudi Arabia', 'player'),
	('Emyl Leclercq', 'Singapore', 'player'),
	('Bryan Hein', 'Germany', 'player'),
	('Jérémy Corinus', 'France', 'player'),
	('Arquímedes Hernández', 'Venezuela', 'player'),
	('Joscha Wosz', 'Germany', 'player'),
	('Marco Burch', 'Switzerland', 'player'),
	('Tan Wangsong', 'China PR', 'player'),
	('Jacob Bergström', 'Sweden', 'player'),
	('Shin Won Ho', 'Korea Republic', 'player'),
	('Yang Qipeng', 'China PR', 'player'),
	('Lee Buchanan', 'England', 'player'),
	('Yanis Cimignani', 'France', 'player'),
	('Dani Plomer', 'Spain', 'player'),
	('Kim Da Sol', 'Korea Republic', 'player'),
	('Patrick Brough', 'England', 'player'),
	('Jonathan Lunney', 'Republic of Ireland', 'player'),
	('Maciej Żurawski', 'Poland', 'player'),
	('Armando Araque', 'Venezuela', 'player'),
	('Walid Jarmouni', 'France', 'player'),
	('Philipp Harant', 'Germany', 'player'),
	('Francois-Joseph Sollacaro', 'France', 'player'),
	('Max Watson', 'Sweden', 'player'),
	('Thomas van den Belt', 'Netherlands', 'player'),
	('Nathan Konstandopoulos', 'Australia', 'player'),
	('Kamal Miller', 'Canada', 'player'),
	('Damian Pawłowski', 'Poland', 'player'),
	('Florian Bianchini', 'France', 'player'),
	('Tolu Arokodare', 'Nigeria', 'player'),
	('Marios Ogkmpoe', 'Greece', 'player'),
	('Julián Illanes', 'Argentina', 'player'),
	('Malik Batmaz', 'Turkey', 'player'),
	('Taisei Miyashiro', 'Japan', 'player'),
	('Tim Siedschlag', 'Germany', 'player'),
	('Mathias Fischer', 'France', 'player'),
	('Leonel Nazareno', 'Ecuador', 'player'),
	('George Lapslie', 'England', 'player'),
	('Dan Happe', 'England', 'player'),
	('Milan Rundić', 'Serbia', 'player'),
	('Jason Lokilo', 'DR Congo', 'player'),
	('Josh Koroma', 'England', 'player'),
	('Fábio Fortes', 'Portugal', 'player'),
	('Yoel Juárez', 'Argentina', 'player'),
	('Roberto Meraz', 'Mexico', 'player'),
	('Matt LaGrassa', 'United States', 'player'),
	('Francisc Cristea', 'Romania', 'player'),
	('Jakub Kuzdra', 'Poland', 'player'),
	('Luke James', 'England', 'player'),
	('August Strömberg', 'Sweden', 'player'),
	('Aaron Bastiaans', 'Netherlands', 'player'),
	('Aref Al Haider', 'Saudi Arabia', 'player'),
	('Wesley Moustache', 'France', 'player'),
	('Lin Chuangyi', 'China PR', 'player'),
	('Victor Adeboyejo', 'Nigeria', 'player'),
	('Dan Jones', 'England', 'player'),
	('David Kabamba', 'DR Congo', 'player'),
	('Mert Kuyucu', 'Germany', 'player'),
	('Eñaut Mendia', 'Spain', 'player'),
	('Levent Mercan', 'Germany', 'player'),
	('Jony Álamo', 'Spain', 'player'),
	('Bastian Strietzel', 'Germany', 'player'),
	('Danny Johnson', 'England', 'player'),
	('Robbie Willmott', 'England', 'player'),
	('Joël Kiassumbua', 'DR Congo', 'player'),
	('Andrei Tîrcoveanu', 'Romania', 'player'),
	('Nassim Ahmed', 'France', 'player'),
	('Yang Yun', 'China PR', 'player'),
	('Muhannad Al Najai', 'Saudi Arabia', 'player'),
	('Regan Donelon', 'Republic of Ireland', 'player'),
	('Anthony Roczen', 'Germany', 'player'),
	('Michael Zant', 'Germany', 'player'),
	('Terence Vancooten', 'Guyana', 'player'),
	('Tomás Oneto', 'Argentina', 'player'),
	('Jarno Westerman', 'Netherlands', 'player'),
	('Bryce Hosannah', 'England', 'player'),
	('Saeed Al Hamsal', 'Saudi Arabia', 'player'),
	('Mohammed Naji', 'Saudi Arabia', 'player'),
	('Esteban Salles', 'France', 'player'),
	('Wang Dong', 'China PR', 'player'),
	('Cédric Gasser', 'Switzerland', 'player'),
	('Agustin Hausch', 'Argentina', 'player'),
	('Mateo Leš', 'Croatia', 'player'),
	('Eetu Vertainen', 'Finland', 'player'),
	('Peder Vogt', 'Norway', 'player'),
	('Abraham Cabrera', 'Bolivia', 'player'),
	('Daniel Maldini', 'Italy', 'player'),
	('Yan Dinghao', 'China PR', 'player'),
	('Kacper Gach', 'Poland', 'player'),
	('Luciano Carty', 'Netherlands', 'player'),
	('Radhi Al Radhi', 'Saudi Arabia', 'player'),
	('Tim Weißmann', 'Germany', 'player'),
	('Salinas', 'Spain', 'player'),
	('Andrew Tutte', 'England', 'player'),
	('Nader Al Muwallad', 'Saudi Arabia', 'player'),
	('Jeong Seong Min', 'Korea Republic', 'player'),
	('Dialy Ndiaye', 'Senegal', 'player'),
	('Osama Ashoor', 'Saudi Arabia', 'player'),
	('Sofiane Bouzian', 'Belgium', 'player'),
	('Israel Escalante', 'Argentina', 'player'),
	('Wang Peng', 'China PR', 'player'),
	('Leonel Rivas', 'Argentina', 'player'),
	('Wilfried Singo', 'Ivory Coast', 'player'),
	('Augustin Drakpe', 'Netherlands', 'player'),
	('Joris Moutachy', 'France', 'player'),
	('Endri Çekiçi', 'Albania', 'player'),
	('Ignacio Tapia', 'Chile', 'player'),
	('Daniel Hoyo-Kowalski', 'Poland', 'player'),
	('Marco Ballarini', 'Italy', 'player'),
	('Naouirou Ahamada', 'France', 'player'),
	('Henry Kessler', 'United States', 'player'),
	('Alexis Beka Beka', 'France', 'player'),
	('Daire O''Connor', 'Republic of Ireland', 'player'),
	('Petko Hristov', 'Bulgaria', 'player'),
	('Alan Winn', 'United States', 'player'),
	('Cherif Ndiaye', 'Senegal', 'player'),
	('Mark Halstead', 'England', 'player'),
	('Jason Taylor', 'England', 'player'),
	('Conor Coventry', 'Republic of Ireland', 'player'),
	('Jayden Richardson', 'England', 'player'),
	('Wu Qing', 'China PR', 'player'),
	('Connor Brown', 'England', 'player'),
	('Matthew Warburton', 'England', 'player'),
	('Josh Kay', 'England', 'player'),
	('Jetmir Topalli', 'Kosovo', 'player'),
	('Jack Iredale', 'Australia', 'player'),
	('Festus Arthur', 'Germany', 'player'),
	('Callum Burton', 'England', 'player'),
	('Sanasi Sy', 'France', 'player'),
	('Julian Stark', 'Germany', 'player'),
	('Beycker Velásquez', 'Venezuela', 'player'),
	('Kaan Caliskaner', 'Germany', 'player'),
	('Lucas Machado', 'Uruguay', 'player'),
	('Stephen Walker', 'England', 'player'),
	('Furkan Zorba', 'Turkey', 'player'),
	('Pierluigi Pinto', 'Italy', 'player'),
	('Walter Rioja', 'Bolivia', 'player'),
	('Alex Mighten', 'England', 'player'),
	('Erik Engelhardt', 'Germany', 'player'),
	('Mathieu Choinière', 'Canada', 'player'),
	('Dane Ingham', 'New Zealand', 'player'),
	('Liu Huan', 'China PR', 'player'),
	('Giuliano Galoppo', 'Argentina', 'player'),
	('Noah Fatar', 'France', 'player'),
	('David Fitzpatrick', 'England', 'player'),
	('Lombraña', 'Spain', 'player'),
	('Enzo Cornelisse', 'Netherlands', 'player'),
	('Mory Diaw', 'France', 'player'),
	('Kwame Poku', 'England', 'player'),
	('Freddy Mina', 'Ecuador', 'player'),
	('Ian Maatsen', 'Netherlands', 'player'),
	('Zhong Yihao', 'China PR', 'player'),
	('Niclas Thiede', 'Germany', 'player'),
	('Boris Cespedes', 'Switzerland', 'player'),
	('Eugenio Pizzuto', 'Mexico', 'player'),
	('Maxime Thiel', 'Belgium', 'player'),
	('Kalle Björklund', 'Sweden', 'player'),
	('Bram Verbong', 'Netherlands', 'player'),
	('Mamadou Diatta', 'Senegal', 'player'),
	('Kévin Boma', 'France', 'player'),
	('Philipp Sander', 'Germany', 'player'),
	('Adrian Małachowski', 'Poland', 'player'),
	('Lenny Vallier', 'France', 'player'),
	('Ali Maadi', 'Saudi Arabia', 'player'),
	('Tomasz Dejewski', 'Poland', 'player'),
	('Max Wright', 'England', 'player'),
	('Kieran Phillips', 'England', 'player'),
	('Sam Russell', 'England', 'player'),
	('Sun Bo', 'China PR', 'player'),
	('Conor Clifford', 'Republic of Ireland', 'player'),
	('Conor Levingston', 'Republic of Ireland', 'player'),
	('Ricardo Galindo', 'Mexico', 'player'),
	('Emircan Altıntaş', 'Turkey', 'player'),
	('Mirlind Kryeziu', 'Kosovo', 'player'),
	('Ayoub Ouhafsa', 'France', 'player'),
	('Lautaro Giaccone', 'Argentina', 'player'),
	('José Marulanda', 'Colombia', 'player'),
	('Thomas Hasal', 'Canada', 'player'),
	('Joiser Arias', 'Venezuela', 'player'),
	('Jesús Amarilla', 'Paraguay', 'player'),
	('Erdi Dikmen', 'Turkey', 'player'),
	('Adam King', 'Scotland', 'player'),
	('Brandon Goodship', 'England', 'player'),
	('Róger Manrique', 'Venezuela', 'player'),
	('Dilane Bakwa', 'France', 'player'),
	('Fawaz Fallatah', 'Saudi Arabia', 'player'),
	('Diant Ramaj', 'Germany', 'player'),
	('Estalin Segura', 'Ecuador', 'player'),
	('Edwin Pacheco', 'Bolivia', 'player'),
	('Tsubasa Shibuya', 'Japan', 'player'),
	('Juan David Mosquera', 'Colombia', 'player'),
	('Justin Johnson', 'Netherlands', 'player'),
	('Joachim Rothmann', 'Denmark', 'player'),
	('Felipe Zenobio', 'Argentina', 'player'),
	('Nikos Christogeorgos', 'Greece', 'player'),
	('Facundo Ospitaleche', 'Uruguay', 'player'),
	('Paweł Olszewski', 'Poland', 'player'),
	('Gabri Veiga', 'Spain', 'player'),
	('Erick Ferigra', 'Ecuador', 'player'),
	('Filip Bilbija', 'Germany', 'player'),
	('Sebastián Lomónaco', 'Argentina', 'player'),
	('Kim Jung Ho', 'Korea Republic', 'player'),
	('Luuk Wouters', 'Netherlands', 'player'),
	('Flavio Rojas', 'Chile', 'player'),
	('William Sell', 'Norway', 'player'),
	('Jan Bekkema', 'Netherlands', 'player'),
	('Alaa Bakir', 'Germany', 'player'),
	('Declan Drysdale', 'England', 'player'),
	('Will Collar', 'England', 'player'),
	('Andrea Badan', 'Italy', 'player'),
	('Simon Ngapandouetnbu', 'Cameroon', 'player'),
	('Maximilian Göppel', 'Liechtenstein', 'player'),
	('Cubero', 'Spain', 'player'),
	('Erik Sorga', 'Estonia', 'player'),
	('Youri Schoonderwaldt', 'Netherlands', 'player'),
	('Diedie Traore', 'France', 'player'),
	('Mathias Jørgensen', 'Denmark', 'player'),
	('Morad El Haddouti', 'Netherlands', 'player'),
	('Silas Zehnder', 'Germany', 'player'),
	('Eoin Toal', 'Northern Ireland', 'player'),
	('Kilian Senkbeil', 'Germany', 'player'),
	('Gime Touré', 'France', 'player'),
	('Scott Martin', 'Scotland', 'player'),
	('Ye Chongqiu', 'China PR', 'player'),
	('Anton Skipper', 'Denmark', 'player'),
	('Ben Scholte', 'Netherlands', 'player'),
	('Alfie Beestin', 'England', 'player'),
	('Rick Zuijderwijk', 'Netherlands', 'player'),
	('Andrei Ureche', 'Romania', 'player'),
	('Michel Ange Balikwisha', 'Belgium', 'player'),
	('Rolando Sánchez', 'Bolivia', 'player'),
	('Sebbe Augustijns', 'Belgium', 'player'),
	('Ken Nkuba', 'Belgium', 'player'),
	('Yosmel Gil', 'Venezuela', 'player'),
	('James Daly', 'England', 'player'),
	('Chadi Riad', 'Morocco', 'player'),
	('Ma Xingyu', 'China PR', 'player'),
	('Widen Rojas', 'Bolivia', 'player'),
	('Andrés Arroyo', 'Colombia', 'player'),
	('Italo Espinoza', 'Peru', 'player'),
	('Vlad Motroc', 'Romania', 'player'),
	('Kurtis Byrne', 'Republic of Ireland', 'player'),
	('Guillermo Orellana', 'Chile', 'player'),
	('Ahmad Al Najai', 'Saudi Arabia', 'player'),
	('Ren Shibamoto', 'Japan', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Carlos Mendes Gomes', 'Spain', 'carlos mendes gomes'),
	('Carlos Mendes Gomes', 'Spain', 'gomes'),
	('Thomas Chacon', 'Uruguay', 'thomas chacon'),
	('Thomas Chacon', 'Uruguay', 'chacon'),
	('Maximilian Breunig', 'Germany', 'breunig'),
	('Maximilian Breunig', 'Germany', 'maximilian breunig'),
	('Ahmed Bani', 'Romania', 'ahmed bani'),
	('Ahmed Bani', 'Romania', 'bani'),
	('Tiberiu Căpușă', 'Romania', 'tiberiu capusa'),
	('Tiberiu Căpușă', 'Romania', 'capusa'),
	('Warren Burrell', 'England', 'warren burrell'),
	('Warren Burrell', 'England', 'burrell'),
	('Hatim Belal', 'Saudi Arabia', 'belal'),
	('Hatim Belal', 'Saudi Arabia', 'hatim belal'),
	('Emyl Leclercq', 'Singapore', 'emyl leclercq'),
	('Emyl Leclercq', 'Singapore', 'leclercq'),
	('Bryan Hein', 'Germany', 'hein'),
	('Bryan Hein', 'Germany', 'bryan hein'),
	('Jérémy Corinus', 'France', 'jeremy corinus'),
	('Jérémy Corinus', 'France', 'corinus'),
	('Arquímedes Hernández', 'Venezuela', 'arquimedes hernandez'),
	('Arquímedes Hernández', 'Venezuela', 'hernandez'),
	('Joscha Wosz', 'Germany', 'joscha wosz'),
	('Joscha Wosz', 'Germany', 'wosz'),
	('Marco Burch', 'Switzerland', 'burch'),
	('Marco Burch', 'Switzerland', 'marco burch'),
	('Tan Wangsong', 'China PR', 'tan wangsong'),
	('Tan Wangsong', 'China PR', 'wangsong'),
	('Jacob Bergström', 'Sweden', 'jacob bergstrom'),
	('Jacob Bergström', 'Sweden', 'bergstrom'),
	('Shin Won Ho', 'Korea Republic', 'ho'),
	('Shin Won Ho', 'Korea Republic', 'shin won ho'),
	('Yang Qipeng', 'China PR', 'yang qipeng'),
	('Yang Qipeng', 'China PR', 'qipeng'),
	('Lee Buchanan', 'England', 'buchanan'),
	('Lee Buchanan', 'England', 'lee buchanan'),
	('Yanis Cimignani', 'France', 'yanis cimignani'),
	('Yanis Cimignani', 'France', 'cimignani'),
	('Dani Plomer', 'Spain', 'plomer'),
	('Dani Plomer', 'Spain', 'dani plomer'),
	('Kim Da Sol', 'Korea Republic', 'kim da sol'),
	('Kim Da Sol', 'Korea Republic', 'sol'),
	('Patrick Brough', 'England', 'patrick brough'),
	('Patrick Brough', 'England', 'brough'),
	('Jonathan Lunney', 'Republic of Ireland', 'jonathan lunney'),
	('Jonathan Lunney', 'Republic of Ireland', 'lunney'),
	('Maciej Żurawski', 'Poland', 'maciej zurawski'),
	('Maciej Żurawski', 'Poland', 'zurawski'),
	('Armando Araque', 'Venezuela', 'araque'),
	('Armando Araque', 'Venezuela', 'armando araque'),
	('Walid Jarmouni', 'France', 'jarmouni'),
	('Walid Jarmouni', 'France', 'walid jarmouni'),
	('Philipp Harant', 'Germany', 'harant'),
	('Philipp Harant', 'Germany', 'philipp harant'),
	('Francois-Joseph Sollacaro', 'France', 'sollacaro'),
	('Francois-Joseph Sollacaro', 'France', 'francoisjoseph sollacaro'),
	('Max Watson', 'Sweden', 'watson'),
	('Max Watson', 'Sweden', 'max watson'),
	('Thomas van den Belt', 'Netherlands', 'thomas van den belt'),
	('Thomas van den Belt', 'Netherlands', 'belt'),
	('Nathan Konstandopoulos', 'Australia', 'konstandopoulos'),
	('Nathan Konstandopoulos', 'Australia', 'nathan konstandopoulos'),
	('Kamal Miller', 'Canada', 'kamal miller'),
	('Kamal Miller', 'Canada', 'miller'),
	('Damian Pawłowski', 'Poland', 'damian pawowski'),
	('Damian Pawłowski', 'Poland', 'pawowski'),
	('Florian Bianchini', 'France', 'bianchini'),
	('Florian Bianchini', 'France', 'florian bianchini'),
	('Tolu Arokodare', 'Nigeria', 'arokodare'),
	('Tolu Arokodare', 'Nigeria', 'tolu arokodare'),
	('Marios Ogkmpoe', 'Greece', 'marios ogkmpoe'),
	('Marios Ogkmpoe', 'Greece', 'ogkmpoe'),
	('Julián Illanes', 'Argentina', 'illanes'),
	('Julián Illanes', 'Argentina', 'julian illanes'),
	('Malik Batmaz', 'Turkey', 'batmaz'),
	('Malik Batmaz', 'Turkey', 'malik batmaz'),
	('Taisei Miyashiro', 'Japan', 'miyashiro'),
	('Taisei Miyashiro', 'Japan', 'taisei miyashiro'),
	('Tim Siedschlag', 'Germany', 'siedschlag'),
	('Tim Siedschlag', 'Germany', 'tim siedschlag'),
	('Mathias Fischer', 'France', 'fischer'),
	('Mathias Fischer', 'France', 'mathias fischer'),
	('Leonel Nazareno', 'Ecuador', 'nazareno'),
	('Leonel Nazareno', 'Ecuador', 'leonel nazareno'),
	('George Lapslie', 'England', 'george lapslie'),
	('George Lapslie', 'England', 'lapslie'),
	('Dan Happe', 'England', 'happe'),
	('Dan Happe', 'England', 'dan happe'),
	('Milan Rundić', 'Serbia', 'milan rundic'),
	('Milan Rundić', 'Serbia', 'rundic'),
	('Jason Lokilo', 'DR Congo', 'lokilo'),
	('Jason Lokilo', 'DR Congo', 'jason lokilo'),
	('Josh Koroma', 'England', 'koroma'),
	('Josh Koroma', 'England', 'josh koroma'),
	('Fábio Fortes', 'Portugal', 'fortes'),
	('Fábio Fortes', 'Portugal', 'fabio fortes'),
	('Yoel Juárez', 'Argentina', 'juarez'),
	('Yoel Juárez', 'Argentina', 'yoel juarez'),
	('Roberto Meraz', 'Mexico', 'meraz'),
	('Roberto Meraz', 'Mexico', 'roberto meraz'),
	('Matt LaGrassa', 'United States', 'matt lagrassa'),
	('Matt LaGrassa', 'United States', 'lagrassa'),
	('Francisc Cristea', 'Romania', 'cristea'),
	('Francisc Cristea', 'Romania', 'francisc cristea'),
	('Jakub Kuzdra', 'Poland', 'kuzdra'),
	('Jakub Kuzdra', 'Poland', 'jakub kuzdra'),
	('Luke James', 'England', 'james'),
	('Luke James', 'England', 'luke james'),
	('August Strömberg', 'Sweden', 'august stromberg'),
	('August Strömberg', 'Sweden', 'stromberg'),
	('Aaron Bastiaans', 'Netherlands', 'aaron bastiaans'),
	('Aaron Bastiaans', 'Netherlands', 'bastiaans'),
	('Aref Al Haider', 'Saudi Arabia', 'aref al haider'),
	('Aref Al Haider', 'Saudi Arabia', 'haider'),
	('Wesley Moustache', 'France', 'moustache'),
	('Wesley Moustache', 'France', 'wesley moustache'),
	('Lin Chuangyi', 'China PR', 'lin chuangyi'),
	('Lin Chuangyi', 'China PR', 'chuangyi'),
	('Victor Adeboyejo', 'Nigeria', 'adeboyejo'),
	('Victor Adeboyejo', 'Nigeria', 'victor adeboyejo'),
	('Dan Jones', 'England', 'jones'),
	('Dan Jones', 'England', 'dan jones'),
	('David Kabamba', 'DR Congo', 'david kabamba'),
	('David Kabamba', 'DR Congo', 'kabamba'),
	('Mert Kuyucu', 'Germany', 'kuyucu'),
	('Mert Kuyucu', 'Germany', 'mert kuyucu'),
	('Eñaut Mendia', 'Spain', 'mendia'),
	('Eñaut Mendia', 'Spain', 'enaut mendia'),
	('Levent Mercan', 'Germany', 'levent mercan'),
	('Levent Mercan', 'Germany', 'mercan'),
	('Jony Álamo', 'Spain', 'alamo'),
	('Jony Álamo', 'Spain', 'jony alamo'),
	('Bastian Strietzel', 'Germany', 'strietzel'),
	('Bastian Strietzel', 'Germany', 'bastian strietzel'),
	('Danny Johnson', 'England', 'johnson'),
	('Danny Johnson', 'England', 'danny johnson'),
	('Robbie Willmott', 'England', 'willmott'),
	('Robbie Willmott', 'England', 'robbie willmott'),
	('Joël Kiassumbua', 'DR Congo', 'joel kiassumbua'),
	('Joël Kiassumbua', 'DR Congo', 'kiassumbua'),
	('Andrei Tîrcoveanu', 'Romania', 'tircoveanu'),
	('Andrei Tîrcoveanu', 'Romania', 'andrei tircoveanu'),
	('Nassim Ahmed', 'France', 'ahmed'),
	('Nassim Ahmed', 'France', 'nassim ahmed'),
	('Yang Yun', 'China PR', 'yang yun'),
	('Yang Yun', 'China PR', 'yun'),
	('Muhannad Al Najai', 'Saudi Arabia', 'muhannad al najai'),
	('Muhannad Al Najai', 'Saudi Arabia', 'najai'),
	('Regan Donelon', 'Republic of Ireland', 'donelon'),
	('Regan Donelon', 'Republic of Ireland', 'regan donelon'),
	('Anthony Roczen', 'Germany', 'anthony roczen'),
	('Anthony Roczen', 'Germany', 'roczen'),
	('Michael Zant', 'Germany', 'zant'),
	('Michael Zant', 'Germany', 'michael zant'),
	('Terence Vancooten', 'Guyana', 'terence vancooten'),
	('Terence Vancooten', 'Guyana', 'vancooten'),
	('Tomás Oneto', 'Argentina', 'oneto'),
	('Tomás Oneto', 'Argentina', 'tomas oneto'),
	('Jarno Westerman', 'Netherlands', 'jarno westerman'),
	('Jarno Westerman', 'Netherlands', 'westerman'),
	('Bryce Hosannah', 'England', 'hosannah'),
	('Bryce Hosannah', 'England', 'bryce hosannah'),
	('Saeed Al Hamsal', 'Saudi Arabia', 'hamsal'),
	('Saeed Al Hamsal', 'Saudi Arabia', 'saeed al hamsal'),
	('Mohammed Naji', 'Saudi Arabia', 'naji'),
	('Mohammed Naji', 'Saudi Arabia', 'mohammed naji'),
	('Esteban Salles', 'France', 'esteban salles'),
	('Esteban Salles', 'France', 'salles'),
	('Wang Dong', 'China PR', 'wang dong'),
	('Wang Dong', 'China PR', 'dong'),
	('Cédric Gasser', 'Switzerland', 'gasser'),
	('Cédric Gasser', 'Switzerland', 'cedric gasser'),
	('Agustin Hausch', 'Argentina', 'hausch'),
	('Agustin Hausch', 'Argentina', 'agustin hausch'),
	('Mateo Leš', 'Croatia', 'mateo les'),
	('Mateo Leš', 'Croatia', 'les'),
	('Eetu Vertainen', 'Finland', 'vertainen'),
	('Eetu Vertainen', 'Finland', 'eetu vertainen'),
	('Peder Vogt', 'Norway', 'vogt'),
	('Peder Vogt', 'Norway', 'peder vogt'),
	('Abraham Cabrera', 'Bolivia', 'abraham cabrera'),
	('Abraham Cabrera', 'Bolivia', 'cabrera'),
	('Daniel Maldini', 'Italy', 'maldini'),
	('Daniel Maldini', 'Italy', 'daniel maldini'),
	('Yan Dinghao', 'China PR', 'dinghao'),
	('Yan Dinghao', 'China PR', 'yan dinghao'),
	('Kacper Gach', 'Poland', 'gach'),
	('Kacper Gach', 'Poland', 'kacper gach'),
	('Luciano Carty', 'Netherlands', 'carty'),
	('Luciano Carty', 'Netherlands', 'luciano carty'),
	('Radhi Al Radhi', 'Saudi Arabia', 'radhi'),
	('Radhi Al Radhi', 'Saudi Arabia', 'radhi al radhi'),
	('Tim Weißmann', 'Germany', 'tim weimann'),
	('Tim Weißmann', 'Germany', 'weimann'),
	('Salinas', 'Spain', 'salinas'),
	('Andrew Tutte', 'England', 'andrew tutte'),
	('Andrew Tutte', 'England', 'tutte'),
	('Nader Al Muwallad', 'Saudi Arabia', 'muwallad'),
	('Nader Al Muwallad', 'Saudi Arabia', 'nader al muwallad'),
	('Jeong Seong Min', 'Korea Republic', 'jeong seong min'),
	('Jeong Seong Min', 'Korea Republic', 'min'),
	('Dialy Ndiaye', 'Senegal', 'dialy ndiaye'),
	('Dialy Ndiaye', 'Senegal', 'ndiaye'),
	('Osama Ashoor', 'Saudi Arabia', 'osama ashoor'),
	('Osama Ashoor', 'Saudi Arabia', 'ashoor'),
	('Sofiane Bouzian', 'Belgium', 'sofiane bouzian'),
	('Sofiane Bouzian', 'Belgium', 'bouzian'),
	('Israel Escalante', 'Argentina', 'israel escalante'),
	('Israel Escalante', 'Argentina', 'escalante'),
	('Wang Peng', 'China PR', 'peng'),
	('Wang Peng', 'China PR', 'wang peng'),
	('Leonel Rivas', 'Argentina', 'rivas'),
	('Leonel Rivas', 'Argentina', 'leonel rivas'),
	('Wilfried Singo', 'Ivory Coast', 'singo'),
	('Wilfried Singo', 'Ivory Coast', 'wilfried singo'),
	('Augustin Drakpe', 'Netherlands', 'augustin drakpe'),
	('Augustin Drakpe', 'Netherlands', 'drakpe'),
	('Joris Moutachy', 'France', 'joris moutachy'),
	('Joris Moutachy', 'France', 'moutachy'),
	('Endri Çekiçi', 'Albania', 'endri cekici'),
	('Endri Çekiçi', 'Albania', 'cekici'),
	('Ignacio Tapia', 'Chile', 'tapia'),
	('Ignacio Tapia', 'Chile', 'ignacio tapia'),
	('Daniel Hoyo-Kowalski', 'Poland', 'daniel hoyokowalski'),
	('Daniel Hoyo-Kowalski', 'Poland', 'hoyokowalski'),
	('Marco Ballarini', 'Italy', 'ballarini'),
	('Marco Ballarini', 'Italy', 'marco ballarini'),
	('Naouirou Ahamada', 'France', 'ahamada'),
	('Naouirou Ahamada', 'France', 'naouirou ahamada'),
	('Henry Kessler', 'United States', 'henry kessler'),
	('Henry Kessler', 'United States', 'kessler'),
	('Alexis Beka Beka', 'France', 'alexis beka beka'),
	('Alexis Beka Beka', 'France', 'beka'),
	('Daire O''Connor', 'Republic of Ireland', 'daire oconnor'),
	('Daire O''Connor', 'Republic of Ireland', 'oconnor'),
	('Petko Hristov', 'Bulgaria', 'petko hristov'),
	('Petko Hristov', 'Bulgaria', 'hristov'),
	('Alan Winn', 'United States', 'alan winn'),
	('Alan Winn', 'United States', 'winn'),
	('Cherif Ndiaye', 'Senegal', 'ndiaye'),
	('Cherif Ndiaye', 'Senegal', 'cherif ndiaye'),
	('Mark Halstead', 'England', 'mark halstead'),
	('Mark Halstead', 'England', 'halstead'),
	('Jason Taylor', 'England', 'taylor'),
	('Jason Taylor', 'England', 'jason taylor'),
	('Conor Coventry', 'Republic of Ireland', 'conor coventry'),
	('Conor Coventry', 'Republic of Ireland', 'coventry'),
	('Jayden Richardson', 'England', 'jayden richardson'),
	('Jayden Richardson', 'England', 'richardson'),
	('Wu Qing', 'China PR', 'wu qing'),
	('Wu Qing', 'China PR', 'qing'),
	('Connor Brown', 'England', 'brown'),
	('Connor Brown', 'England', 'connor brown'),
	('Matthew Warburton', 'England', 'matthew warburton'),
	('Matthew Warburton', 'England', 'warburton'),
	('Josh Kay', 'England', 'kay'),
	('Josh Kay', 'England', 'josh kay'),
	('Jetmir Topalli', 'Kosovo', 'topalli'),
	('Jetmir Topalli', 'Kosovo', 'jetmir topalli'),
	('Jack Iredale', 'Australia', 'jack iredale'),
	('Jack Iredale', 'Australia', 'iredale'),
	('Festus Arthur', 'Germany', 'festus arthur'),
	('Festus Arthur', 'Germany', 'arthur'),
	('Callum Burton', 'England', 'callum burton'),
	('Callum Burton', 'England', 'burton'),
	('Sanasi Sy', 'France', 'sanasi sy'),
	('Sanasi Sy', 'France', 'sy'),
	('Julian Stark', 'Germany', 'julian stark'),
	('Julian Stark', 'Germany', 'stark'),
	('Beycker Velásquez', 'Venezuela', 'velasquez'),
	('Beycker Velásquez', 'Venezuela', 'beycker velasquez'),
	('Kaan Caliskaner', 'Germany', 'kaan caliskaner'),
	('Kaan Caliskaner', 'Germany', 'caliskaner'),
	('Lucas Machado', 'Uruguay', 'machado'),
	('Lucas Machado', 'Uruguay', 'lucas machado'),
	('Stephen Walker', 'England', 'walker'),
	('Stephen Walker', 'England', 'stephen walker'),
	('Furkan Zorba', 'Turkey', 'zorba'),
	('Furkan Zorba', 'Turkey', 'furkan zorba'),
	('Pierluigi Pinto', 'Italy', 'pinto'),
	('Pierluigi Pinto', 'Italy', 'pierluigi pinto'),
	('Walter Rioja', 'Bolivia', 'walter rioja'),
	('Walter Rioja', 'Bolivia', 'rioja'),
	('Alex Mighten', 'England', 'mighten'),
	('Alex Mighten', 'England', 'alex mighten'),
	('Erik Engelhardt', 'Germany', 'erik engelhardt'),
	('Erik Engelhardt', 'Germany', 'engelhardt'),
	('Mathieu Choinière', 'Canada', 'choiniere'),
	('Mathieu Choinière', 'Canada', 'mathieu choiniere'),
	('Dane Ingham', 'New Zealand', 'dane ingham'),
	('Dane Ingham', 'New Zealand', 'ingham'),
	('Liu Huan', 'China PR', 'liu huan'),
	('Liu Huan', 'China PR', 'huan'),
	('Giuliano Galoppo', 'Argentina', 'galoppo'),
	('Giuliano Galoppo', 'Argentina', 'giuliano galoppo'),
	('Noah Fatar', 'France', 'noah fatar'),
	('Noah Fatar', 'France', 'fatar'),
	('David Fitzpatrick', 'England', 'david fitzpatrick'),
	('David Fitzpatrick', 'England', 'fitzpatrick'),
	('Lombraña', 'Spain', 'lombrana'),
	('Enzo Cornelisse', 'Netherlands', 'cornelisse'),
	('Enzo Cornelisse', 'Netherlands', 'enzo cornelisse'),
	('Mory Diaw', 'France', 'diaw'),
	('Mory Diaw', 'France', 'mory diaw'),
	('Kwame Poku', 'England', 'poku'),
	('Kwame Poku', 'England', 'kwame poku'),
	('Freddy Mina', 'Ecuador', 'freddy mina'),
	('Freddy Mina', 'Ecuador', 'mina'),
	('Ian Maatsen', 'Netherlands', 'maatsen'),
	('Ian Maatsen', 'Netherlands', 'ian maatsen'),
	('Zhong Yihao', 'China PR', 'zhong yihao'),
	('Zhong Yihao', 'China PR', 'yihao'),
	('Niclas Thiede', 'Germany', 'niclas thiede'),
	('Niclas Thiede', 'Germany', 'thiede'),
	('Boris Cespedes', 'Switzerland', 'cespedes'),
	('Boris Cespedes', 'Switzerland', 'boris cespedes'),
	('Eugenio Pizzuto', 'Mexico', 'eugenio pizzuto'),
	('Eugenio Pizzuto', 'Mexico', 'pizzuto'),
	('Maxime Thiel', 'Belgium', 'thiel'),
	('Maxime Thiel', 'Belgium', 'maxime thiel'),
	('Kalle Björklund', 'Sweden', 'bjorklund'),
	('Kalle Björklund', 'Sweden', 'kalle bjorklund'),
	('Bram Verbong', 'Netherlands', 'bram verbong'),
	('Bram Verbong', 'Netherlands', 'verbong'),
	('Mamadou Diatta', 'Senegal', 'mamadou diatta'),
	('Mamadou Diatta', 'Senegal', 'diatta'),
	('Kévin Boma', 'France', 'boma'),
	('Kévin Boma', 'France', 'kevin boma'),
	('Philipp Sander', 'Germany', 'sander'),
	('Philipp Sander', 'Germany', 'philipp sander'),
	('Adrian Małachowski', 'Poland', 'adrian maachowski'),
	('Adrian Małachowski', 'Poland', 'maachowski'),
	('Lenny Vallier', 'France', 'lenny vallier'),
	('Lenny Vallier', 'France', 'vallier'),
	('Ali Maadi', 'Saudi Arabia', 'ali maadi'),
	('Ali Maadi', 'Saudi Arabia', 'maadi'),
	('Tomasz Dejewski', 'Poland', 'tomasz dejewski'),
	('Tomasz Dejewski', 'Poland', 'dejewski'),
	('Max Wright', 'England', 'wright'),
	('Max Wright', 'England', 'max wright'),
	('Kieran Phillips', 'England', 'kieran phillips'),
	('Kieran Phillips', 'England', 'phillips'),
	('Sam Russell', 'England', 'sam russell'),
	('Sam Russell', 'England', 'russell'),
	('Sun Bo', 'China PR', 'bo'),
	('Sun Bo', 'China PR', 'sun bo'),
	('Conor Clifford', 'Republic of Ireland', 'clifford'),
	('Conor Clifford', 'Republic of Ireland', 'conor clifford'),
	('Conor Levingston', 'Republic of Ireland', 'levingston'),
	('Conor Levingston', 'Republic of Ireland', 'conor levingston'),
	('Ricardo Galindo', 'Mexico', 'galindo'),
	('Ricardo Galindo', 'Mexico', 'ricardo galindo'),
	('Emircan Altıntaş', 'Turkey', 'emircan altntas'),
	('Emircan Altıntaş', 'Turkey', 'altntas'),
	('Mirlind Kryeziu', 'Kosovo', 'mirlind kryeziu'),
	('Mirlind Kryeziu', 'Kosovo', 'kryeziu'),
	('Ayoub Ouhafsa', 'France', 'ouhafsa'),
	('Ayoub Ouhafsa', 'France', 'ayoub ouhafsa'),
	('Lautaro Giaccone', 'Argentina', 'lautaro giaccone'),
	('Lautaro Giaccone', 'Argentina', 'giaccone'),
	('José Marulanda', 'Colombia', 'jose marulanda'),
	('José Marulanda', 'Colombia', 'marulanda'),
	('Thomas Hasal', 'Canada', 'thomas hasal'),
	('Thomas Hasal', 'Canada', 'hasal'),
	('Joiser Arias', 'Venezuela', 'joiser arias'),
	('Joiser Arias', 'Venezuela', 'arias'),
	('Jesús Amarilla', 'Paraguay', 'jesus amarilla'),
	('Jesús Amarilla', 'Paraguay', 'amarilla'),
	('Erdi Dikmen', 'Turkey', 'erdi dikmen'),
	('Erdi Dikmen', 'Turkey', 'dikmen'),
	('Adam King', 'Scotland', 'adam king'),
	('Adam King', 'Scotland', 'king'),
	('Brandon Goodship', 'England', 'brandon goodship'),
	('Brandon Goodship', 'England', 'goodship'),
	('Róger Manrique', 'Venezuela', 'roger manrique'),
	('Róger Manrique', 'Venezuela', 'manrique'),
	('Dilane Bakwa', 'France', 'dilane bakwa'),
	('Dilane Bakwa', 'France', 'bakwa'),
	('Fawaz Fallatah', 'Saudi Arabia', 'fallatah'),
	('Fawaz Fallatah', 'Saudi Arabia', 'fawaz fallatah'),
	('Diant Ramaj', 'Germany', 'ramaj'),
	('Diant Ramaj', 'Germany', 'diant ramaj'),
	('Estalin Segura', 'Ecuador', 'segura'),
	('Estalin Segura', 'Ecuador', 'estalin segura'),
	('Edwin Pacheco', 'Bolivia', 'edwin pacheco'),
	('Edwin Pacheco', 'Bolivia', 'pacheco'),
	('Tsubasa Shibuya', 'Japan', 'tsubasa shibuya'),
	('Tsubasa Shibuya', 'Japan', 'shibuya'),
	('Juan David Mosquera', 'Colombia', 'mosquera'),
	('Juan David Mosquera', 'Colombia', 'juan david mosquera'),
	('Justin Johnson', 'Netherlands', 'johnson'),
	('Justin Johnson', 'Netherlands', 'justin johnson'),
	('Joachim Rothmann', 'Denmark', 'rothmann'),
	('Joachim Rothmann', 'Denmark', 'joachim rothmann'),
	('Felipe Zenobio', 'Argentina', 'felipe zenobio'),
	('Felipe Zenobio', 'Argentina', 'zenobio'),
	('Nikos Christogeorgos', 'Greece', 'nikos christogeorgos'),
	('Nikos Christogeorgos', 'Greece', 'christogeorgos'),
	('Facundo Ospitaleche', 'Uruguay', 'facundo ospitaleche'),
	('Facundo Ospitaleche', 'Uruguay', 'ospitaleche'),
	('Paweł Olszewski', 'Poland', 'olszewski'),
	('Paweł Olszewski', 'Poland', 'pawe olszewski'),
	('Gabri Veiga', 'Spain', 'gabri veiga'),
	('Gabri Veiga', 'Spain', 'veiga'),
	('Erick Ferigra', 'Ecuador', 'ferigra'),
	('Erick Ferigra', 'Ecuador', 'erick ferigra'),
	('Filip Bilbija', 'Germany', 'filip bilbija'),
	('Filip Bilbija', 'Germany', 'bilbija'),
	('Sebastián Lomónaco', 'Argentina', 'sebastian lomonaco'),
	('Sebastián Lomónaco', 'Argentina', 'lomonaco'),
	('Kim Jung Ho', 'Korea Republic', 'ho'),
	('Kim Jung Ho', 'Korea Republic', 'kim jung ho'),
	('Luuk Wouters', 'Netherlands', 'wouters'),
	('Luuk Wouters', 'Netherlands', 'luuk wouters'),
	('Flavio Rojas', 'Chile', 'rojas'),
	('Flavio Rojas', 'Chile', 'flavio rojas'),
	('William Sell', 'Norway', 'sell'),
	('William Sell', 'Norway', 'william sell'),
	('Jan Bekkema', 'Netherlands', 'jan bekkema'),
	('Jan Bekkema', 'Netherlands', 'bekkema'),
	('Alaa Bakir', 'Germany', 'alaa bakir'),
	('Alaa Bakir', 'Germany', 'bakir'),
	('Declan Drysdale', 'England', 'drysdale'),
	('Declan Drysdale', 'England', 'declan drysdale'),
	('Will Collar', 'England', 'will collar'),
	('Will Collar', 'England', 'collar'),
	('Andrea Badan', 'Italy', 'badan'),
	('Andrea Badan', 'Italy', 'andrea badan'),
	('Simon Ngapandouetnbu', 'Cameroon', 'simon ngapandouetnbu'),
	('Simon Ngapandouetnbu', 'Cameroon', 'ngapandouetnbu'),
	('Maximilian Göppel', 'Liechtenstein', 'goppel'),
	('Maximilian Göppel', 'Liechtenstein', 'maximilian goppel'),
	('Cubero', 'Spain', 'cubero'),
	('Erik Sorga', 'Estonia', 'sorga'),
	('Erik Sorga', 'Estonia', 'erik sorga'),
	('Youri Schoonderwaldt', 'Netherlands', 'schoonderwaldt'),
	('Youri Schoonderwaldt', 'Netherlands', 'youri schoonderwaldt'),
	('Diedie Traore', 'France', 'diedie traore'),
	('Diedie Traore', 'France', 'traore'),
	('Mathias Jørgensen', 'Denmark', 'jrgensen'),
	('Mathias Jørgensen', 'Denmark', 'mathias jrgensen'),
	('Morad El Haddouti', 'Netherlands', 'morad el haddouti'),
	('Morad El Haddouti', 'Netherlands', 'haddouti'),
	('Silas Zehnder', 'Germany', 'silas zehnder'),
	('Silas Zehnder', 'Germany', 'zehnder'),
	('Eoin Toal', 'Northern Ireland', 'eoin toal'),
	('Eoin Toal', 'Northern Ireland', 'toal'),
	('Kilian Senkbeil', 'Germany', 'kilian senkbeil'),
	('Kilian Senkbeil', 'Germany', 'senkbeil'),
	('Gime Touré', 'France', 'gime toure'),
	('Gime Touré', 'France', 'toure'),
	('Scott Martin', 'Scotland', 'scott martin'),
	('Scott Martin', 'Scotland', 'martin'),
	('Ye Chongqiu', 'China PR', 'chongqiu'),
	('Ye Chongqiu', 'China PR', 'ye chongqiu'),
	('Anton Skipper', 'Denmark', 'skipper'),
	('Anton Skipper', 'Denmark', 'anton skipper'),
	('Ben Scholte', 'Netherlands', 'scholte'),
	('Ben Scholte', 'Netherlands', 'ben scholte'),
	('Alfie Beestin', 'England', 'beestin'),
	('Alfie Beestin', 'England', 'alfie beestin'),
	('Rick Zuijderwijk', 'Netherlands', 'zuijderwijk'),
	('Rick Zuijderwijk', 'Netherlands', 'rick zuijderwijk'),
	('Andrei Ureche', 'Romania', 'andrei ureche'),
	('Andrei Ureche', 'Romania', 'ureche'),
	('Michel Ange Balikwisha', 'Belgium', 'balikwisha'),
	('Michel Ange Balikwisha', 'Belgium', 'michel ange balikwisha'),
	('Rolando Sánchez', 'Bolivia', 'rolando sanchez'),
	('Rolando Sánchez', 'Bolivia', 'sanchez'),
	('Sebbe Augustijns', 'Belgium', 'augustijns'),
	('Sebbe Augustijns', 'Belgium', 'sebbe augustijns'),
	('Ken Nkuba', 'Belgium', 'nkuba'),
	('Ken Nkuba', 'Belgium', 'ken nkuba'),
	('Yosmel Gil', 'Venezuela', 'gil'),
	('Yosmel Gil', 'Venezuela', 'yosmel gil'),
	('James Daly', 'England', 'james daly'),
	('James Daly', 'England', 'daly'),
	('Chadi Riad', 'Morocco', 'chadi riad'),
	('Chadi Riad', 'Morocco', 'riad'),
	('Ma Xingyu', 'China PR', 'ma xingyu'),
	('Ma Xingyu', 'China PR', 'xingyu'),
	('Widen Rojas', 'Bolivia', 'rojas'),
	('Widen Rojas', 'Bolivia', 'widen rojas'),
	('Andrés Arroyo', 'Colombia', 'arroyo'),
	('Andrés Arroyo', 'Colombia', 'andres arroyo'),
	('Italo Espinoza', 'Peru', 'espinoza'),
	('Italo Espinoza', 'Peru', 'italo espinoza'),
	('Vlad Motroc', 'Romania', 'vlad motroc'),
	('Vlad Motroc', 'Romania', 'motroc'),
	('Kurtis Byrne', 'Republic of Ireland', 'byrne'),
	('Kurtis Byrne', 'Republic of Ireland', 'kurtis byrne'),
	('Guillermo Orellana', 'Chile', 'orellana'),
	('Guillermo Orellana', 'Chile', 'guillermo orellana'),
	('Ahmad Al Najai', 'Saudi Arabia', 'najai'),
	('Ahmad Al Najai', 'Saudi Arabia', 'ahmad al najai'),
	('Ren Shibamoto', 'Japan', 'shibamoto'),
	('Ren Shibamoto', 'Japan', 'ren shibamoto')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';