INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Mario Müller', 'Germany', 'player'),
	('Lee Ji Min', 'Korea Republic', 'player'),
	('Denis Ciobotariu', 'Romania', 'player'),
	('Ariel Martínez', 'Chile', 'player'),
	('Morten Ågnes Konradsen', 'Norway', 'player'),
	('Andreja Prokić', 'Serbia', 'player'),
	('Kean Bryan', 'England', 'player'),
	('Song Seung Min', 'Korea Republic', 'player'),
	('Fidan Aliti', 'Kosovo', 'player'),
	('Takuya Matsuura', 'Japan', 'player'),
	('Endika', 'Spain', 'player'),
	('Timo Becker', 'Germany', 'player'),
	('Dustin Bomheuer', 'Germany', 'player'),
	('Mathias Hebo', 'Denmark', 'player'),
	('James Scott', 'Scotland', 'player'),
	('Peter Pawlett', 'Scotland', 'player'),
	('Denis Simani', 'Albania', 'player'),
	('Mirko Kos', 'Austria', 'player'),
	('Maciej Urbańczyk', 'Poland', 'player'),
	('Antonio Portales', 'Mexico', 'player'),
	('Steven Prieto', 'Spain', 'player'),
	('Ellis Simms', 'England', 'player'),
	('Timothée Dieng', 'France', 'player'),
	('Pape Habib Gueye', 'Senegal', 'player'),
	('Florian Riedel', 'Germany', 'player'),
	('Vlatko Stojanovski', 'North Macedonia', 'player'),
	('Paul Pîrvulescu', 'Romania', 'player'),
	('Jeison Medina', 'Colombia', 'player'),
	('Andre Dozzell', 'England', 'player'),
	('Kane Hemmings', 'England', 'player'),
	('Ante Bajic', 'Austria', 'player'),
	('Laurențiu Corbu', 'Romania', 'player'),
	('Léo Vieira', 'Brazil', 'player'),
	('Tyrhys Dolan', 'England', 'player'),
	('Ahmet Gülay', 'Turkey', 'player'),
	('Randi Goteni', 'Congo', 'player'),
	('Rıdvan Yılmaz', 'Turkey', 'player'),
	('Lukas Scepanik', 'Germany', 'player'),
	('Nesta Guinness-Walker', 'England', 'player'),
	('Théo Guivarch', 'France', 'player'),
	('Léo Leroy', 'France', 'player'),
	('Edward Bolaños', 'Colombia', 'player'),
	('Edi Sylisufaj', 'Sweden', 'player'),
	('Davinson Jama', 'Ecuador', 'player'),
	('Daniel O''Shaughnessy', 'Finland', 'player'),
	('Shani Tarashaj', 'Switzerland', 'player'),
	('Ayodeji Sotona', 'Republic of Ireland', 'player'),
	('Pedro Amador', 'Portugal', 'player'),
	('Jimmy Roca', 'Bolivia', 'player'),
	('Rong Hao', 'China PR', 'player'),
	('Haret Ortega', 'Mexico', 'player'),
	('Andrés Perea', 'Colombia', 'player'),
	('Callum Lang', 'England', 'player'),
	('Guillaume Faivre', 'Switzerland', 'player'),
	('Harry Burgoyne', 'England', 'player'),
	('Shaya Sharahili', 'Saudi Arabia', 'player'),
	('Graham Smith', 'United States', 'player'),
	('Jordan Bowery', 'England', 'player'),
	('Nama Fofana', 'France', 'player'),
	('Damián Fernández', 'Argentina', 'player'),
	('Patryk Tuszyński', 'Poland', 'player'),
	('Pierce Sweeney', 'Republic of Ireland', 'player'),
	('Mejías', 'Spain', 'player'),
	('Nicolás Sosa', 'Uruguay', 'player'),
	('Junior Kadile', 'France', 'player'),
	('Pablo Ruiz', 'Argentina', 'player'),
	('Sargon Abraham', 'Sweden', 'player'),
	('Chi Wenyi', 'China PR', 'player'),
	('Stuart O''Keefe', 'England', 'player'),
	('Ivar Furu', 'Norway', 'player'),
	('Sebastian Klaas', 'Germany', 'player'),
	('Alessandro Semprini', 'Italy', 'player'),
	('Kevin Agudelo', 'Colombia', 'player'),
	('Tomáš Smola', 'Czech Republic', 'player'),
	('Morgan Feeney', 'England', 'player'),
	('Ronaldo Rivas', 'Venezuela', 'player'),
	('Manuel Schwenk', 'Germany', 'player'),
	('Pål Erik Ulvestad', 'Norway', 'player'),
	('Aaron Calver', 'Australia', 'player'),
	('George Ganea', 'Romania', 'player'),
	('Egzon Binaku', 'Albania', 'player'),
	('Ryan Bowman', 'England', 'player'),
	('Derick Osei Yaw', 'France', 'player'),
	('Jean Jules Mvondo', 'Cameroon', 'player'),
	('Łukasz Poręba', 'Poland', 'player'),
	('Shane McLoughlin', 'Republic of Ireland', 'player'),
	('Mücahit Akçay', 'Turkey', 'player'),
	('Sherwin Seedorf', 'Netherlands', 'player'),
	('Jake Taylor', 'Wales', 'player'),
	('Leroy Kwadwo', 'Germany', 'player'),
	('Juan Pablo Vargas', 'Costa Rica', 'player'),
	('Alfons Amade', 'Germany', 'player'),
	('Juan Bautista Cascini', 'Argentina', 'player'),
	('Ronaldo Prieto', 'Mexico', 'player'),
	('Dion Donohue', 'Wales', 'player'),
	('Deklan Wynne', 'New Zealand', 'player'),
	('Joe Rankin-Costello', 'England', 'player'),
	('Steeve Beusnard', 'France', 'player'),
	('Tom Hamer', 'England', 'player'),
	('Louis D''Arrigo', 'Australia', 'player'),
	('Markus Mendler', 'Germany', 'player'),
	('Alistair McCann', 'Northern Ireland', 'player'),
	('Kim Moon Hwan', 'Korea Republic', 'player'),
	('Matko Miljevic', 'United States', 'player'),
	('Siemen Voet', 'Belgium', 'player'),
	('Aaron Taylor-Sinclair', 'Scotland', 'player'),
	('Erten Ersu', 'Turkey', 'player'),
	('Jeong Dong Yun', 'Korea Republic', 'player'),
	('Alexis Trouillet', 'France', 'player'),
	('Mamoudou Karamoko', 'France', 'player'),
	('Amar Dedić', 'Bosnia Herzegovina', 'player'),
	('Yi Teng', 'China PR', 'player'),
	('Kim Kyung Jung', 'Korea Republic', 'player'),
	('Vadim Karpov', 'Russia', 'player'),
	('Carlos Higuera', 'Mexico', 'player'),
	('Marc Pedersen', 'Denmark', 'player'),
	('Pépé Bonet', 'DR Congo', 'player'),
	('Jordan Tell', 'France', 'player'),
	('Taylor Washington', 'United States', 'player'),
	('Jannes Vollert', 'Germany', 'player'),
	('Hong Jeong Un', 'Korea Republic', 'player'),
	('Eric Lanini', 'Italy', 'player'),
	('Luka Slišković', 'Austria', 'player'),
	('Paul Nebel', 'Germany', 'player'),
	('Galileo Del Castillo', 'Venezuela', 'player'),
	('Tobias Karlsson', 'Sweden', 'player'),
	('José Manríquez', 'Venezuela', 'player'),
	('Cammy Smith', 'Scotland', 'player'),
	('Martin Angha', 'Switzerland', 'player'),
	('Willi Evseev', 'Germany', 'player'),
	('Shintaro Nago', 'Japan', 'player'),
	('Michael Salazar', 'Belize', 'player'),
	('Yehvann Diouf', 'France', 'player'),
	('Francisco Sierralta', 'Chile', 'player'),
	('Paulos Abraham', 'Sweden', 'player'),
	('Guillermo Firpo', 'Uruguay', 'player'),
	('Eduar Caicedo', 'Colombia', 'player'),
	('Ivo Kestler', 'Argentina', 'player'),
	('Julián López', 'Argentina', 'player'),
	('Tristan Dekker', 'Netherlands', 'player'),
	('Luka Tankulić', 'Germany', 'player'),
	('Matías Pérez', 'Argentina', 'player'),
	('Ryan Sweeney', 'Republic of Ireland', 'player'),
	('Oskar Zawada', 'Poland', 'player'),
	('Yang Cheng', 'China PR', 'player'),
	('Tino Casali', 'Austria', 'player'),
	('Yuzo Kobayashi', 'Japan', 'player'),
	('Przemyslaw Mystkowski', 'Poland', 'player'),
	('Oliver Steurer', 'Germany', 'player'),
	('Marcel Engelhardt', 'Germany', 'player'),
	('Muhammed Kiprit', 'Turkey', 'player'),
	('Virgiliu Postolachi', 'France', 'player'),
	('Douglas Bergqvist', 'Sweden', 'player'),
	('Alexander Nandzik', 'Germany', 'player'),
	('Michał Szromnik', 'Poland', 'player'),
	('Daniel Drescher', 'Austria', 'player'),
	('Robin Book', 'Sweden', 'player'),
	('Mateo Abeijón', 'Uruguay', 'player'),
	('Braian Martínez', 'Argentina', 'player'),
	('Rodrigo Contreras', 'Argentina', 'player'),
	('Zubimendi', 'Spain', 'player'),
	('Randall Leal', 'Costa Rica', 'player'),
	('Espen Børufsen', 'Norway', 'player'),
	('Brian Easton', 'Scotland', 'player'),
	('Canillas', 'Spain', 'player'),
	('Bassala Sambou', 'Germany', 'player'),
	('Leonel Caffaratti', 'Argentina', 'player'),
	('Florin Purece', 'Romania', 'player'),
	('Luis Vargas', 'Bolivia', 'player'),
	('Lee Hodson', 'Northern Ireland', 'player'),
	('Kevin Walker', 'Sweden', 'player'),
	('Heo Yong Joon', 'Korea Republic', 'player'),
	('Conor Thomas', 'England', 'player'),
	('Guille Rosas', 'Spain', 'player'),
	('Harmeet Singh', 'Norway', 'player'),
	('Frederik Winther', 'Denmark', 'player'),
	('Gökdeniz Bayrakdar', 'Turkey', 'player'),
	('Arnedo', 'Spain', 'player'),
	('Kenzo Goudmijn', 'Netherlands', 'player'),
	('Mat Sadler', 'England', 'player'),
	('Mario Hernández', 'Spain', 'player'),
	('Hilal Ben Moussa', 'Netherlands', 'player'),
	('Karim Aribi', 'Algeria', 'player'),
	('Jhonata Robert', 'Brazil', 'player'),
	('Sergio Gónzalez', 'Spain', 'player'),
	('Armin Gremsl', 'Austria', 'player'),
	('Héctor Pérez', 'Venezuela', 'player'),
	('Danny Mandroiu', 'Republic of Ireland', 'player'),
	('Youssef Maziz', 'France', 'player'),
	('Richard van der Venne', 'Netherlands', 'player'),
	('Arda Kızıldağ', 'Turkey', 'player'),
	('Sékou Mara', 'France', 'player'),
	('Renzo Bacchia', 'Uruguay', 'player'),
	('Hideki Ishige', 'Japan', 'player'),
	('Abdurrahman Canli', 'Turkey', 'player'),
	('Daniel Cleary', 'Republic of Ireland', 'player'),
	('Zé Eduardo', 'Brazil', 'player'),
	('Manuel De Luca', 'Italy', 'player'),
	('Chris Taylor', 'England', 'player'),
	('Tony Rocha', 'Belize', 'player'),
	('Peter Pokorný', 'Slovakia', 'player'),
	('Fran González', 'Spain', 'player'),
	('Oslimg Mora', 'Peru', 'player'),
	('Thomas Dähne', 'Germany', 'player'),
	('Thabiso Monyane', 'South Africa', 'player'),
	('Cheikh Niasse', 'Senegal', 'player'),
	('Nicolas Seiwald', 'Austria', 'player'),
	('Kasper Skaanes', 'Norway', 'player'),
	('Rosmel Villanueva', 'Venezuela', 'player'),
	('Joaquín Muñoz', 'Chile', 'player'),
	('Adalberto Carrasquilla', 'Panama', 'player'),
	('Kayacan Erdoğan', 'Turkey', 'player'),
	('José Cazares', 'Ecuador', 'player'),
	('Sebastián Prieto', 'Argentina', 'player'),
	('João Gonçalves', 'Portugal', 'player'),
	('Paul Caddis', 'Scotland', 'player'),
	('Sheriff Sinyan', 'Gambia', 'player'),
	('Eldor Shomurodov', 'Uzbekistan', 'player'),
	('Christian Kinsombi', 'Germany', 'player'),
	('Sido Jombati', 'Portugal', 'player'),
	('Zafer Görgen', 'Turkey', 'player'),
	('Takuma Ominami', 'Japan', 'player'),
	('Jajá', 'Brazil', 'player'),
	('Lorenzo Pirola', 'Italy', 'player'),
	('Facundo Lando', 'Argentina', 'player'),
	('Ronny Medina', 'Ecuador', 'player'),
	('Thomas Vollnhofer', 'Austria', 'player'),
	('Kelvin Mellor', 'England', 'player'),
	('Mark Connolly', 'Republic of Ireland', 'player'),
	('Samir Banjai', 'Portugal', 'player'),
	('Anthony Rouault', 'France', 'player'),
	('Ionuț Balaur', 'Romania', 'player'),
	('Adam Hammill', 'England', 'player'),
	('Thomas Rodríguez', 'Chile', 'player'),
	('Fran Navarro', 'Spain', 'player'),
	('Hernán Hinostroza', 'Peru', 'player'),
	('Andrea Dini', 'Italy', 'player'),
	('Davor Blažević', 'Sweden', 'player'),
	('Philipp Heerwagen', 'Germany', 'player'),
	('Diego Angles', 'Peru', 'player'),
	('Sven Müller', 'Germany', 'player'),
	('Sultan Ali Al Sawadi', 'Saudi Arabia', 'player'),
	('Lukas Raeder', 'Germany', 'player'),
	('Gary O''Neill', 'Republic of Ireland', 'player'),
	('Andrei Rațiu', 'Romania', 'player'),
	('Lanchi', 'Spain', 'player'),
	('Kike Hermoso', 'Spain', 'player'),
	('Andrea Colpani', 'Italy', 'player'),
	('Moussa Diarra', 'France', 'player'),
	('José Alberto Castillo', 'Mexico', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Mario Müller', 'Germany', 'muller'),
	('Mario Müller', 'Germany', 'mario muller'),
	('Lee Ji Min', 'Korea Republic', 'min'),
	('Lee Ji Min', 'Korea Republic', 'lee ji min'),
	('Denis Ciobotariu', 'Romania', 'denis ciobotariu'),
	('Denis Ciobotariu', 'Romania', 'ciobotariu'),
	('Ariel Martínez', 'Chile', 'martinez'),
	('Ariel Martínez', 'Chile', 'ariel martinez'),
	('Morten Ågnes Konradsen', 'Norway', 'konradsen'),
	('Morten Ågnes Konradsen', 'Norway', 'morten agnes konradsen'),
	('Andreja Prokić', 'Serbia', 'andreja prokic'),
	('Andreja Prokić', 'Serbia', 'prokic'),
	('Kean Bryan', 'England', 'bryan'),
	('Kean Bryan', 'England', 'kean bryan'),
	('Song Seung Min', 'Korea Republic', 'song seung min'),
	('Song Seung Min', 'Korea Republic', 'min'),
	('Fidan Aliti', 'Kosovo', 'aliti'),
	('Fidan Aliti', 'Kosovo', 'fidan aliti'),
	('Takuya Matsuura', 'Japan', 'matsuura'),
	('Takuya Matsuura', 'Japan', 'takuya matsuura'),
	('Endika', 'Spain', 'endika'),
	('Timo Becker', 'Germany', 'timo becker'),
	('Timo Becker', 'Germany', 'becker'),
	('Dustin Bomheuer', 'Germany', 'bomheuer'),
	('Dustin Bomheuer', 'Germany', 'dustin bomheuer'),
	('Mathias Hebo', 'Denmark', 'hebo'),
	('Mathias Hebo', 'Denmark', 'mathias hebo'),
	('James Scott', 'Scotland', 'james scott'),
	('James Scott', 'Scotland', 'scott'),
	('Peter Pawlett', 'Scotland', 'pawlett'),
	('Peter Pawlett', 'Scotland', 'peter pawlett'),
	('Denis Simani', 'Albania', 'denis simani'),
	('Denis Simani', 'Albania', 'simani'),
	('Mirko Kos', 'Austria', 'mirko kos'),
	('Mirko Kos', 'Austria', 'kos'),
	('Maciej Urbańczyk', 'Poland', 'urbanczyk'),
	('Maciej Urbańczyk', 'Poland', 'maciej urbanczyk'),
	('Antonio Portales', 'Mexico', 'portales'),
	('Antonio Portales', 'Mexico', 'antonio portales'),
	('Steven Prieto', 'Spain', 'prieto'),
	('Steven Prieto', 'Spain', 'steven prieto'),
	('Ellis Simms', 'England', 'simms'),
	('Ellis Simms', 'England', 'ellis simms'),
	('Timothée Dieng', 'France', 'timothee dieng'),
	('Timothée Dieng', 'France', 'dieng'),
	('Pape Habib Gueye', 'Senegal', 'pape habib gueye'),
	('Pape Habib Gueye', 'Senegal', 'gueye'),
	('Florian Riedel', 'Germany', 'florian riedel'),
	('Florian Riedel', 'Germany', 'riedel'),
	('Vlatko Stojanovski', 'North Macedonia', 'stojanovski'),
	('Vlatko Stojanovski', 'North Macedonia', 'vlatko stojanovski'),
	('Paul Pîrvulescu', 'Romania', 'paul pirvulescu'),
	('Paul Pîrvulescu', 'Romania', 'pirvulescu'),
	('Jeison Medina', 'Colombia', 'medina'),
	('Jeison Medina', 'Colombia', 'jeison medina'),
	('Andre Dozzell', 'England', 'dozzell'),
	('Andre Dozzell', 'England', 'andre dozzell'),
	('Kane Hemmings', 'England', 'hemmings'),
	('Kane Hemmings', 'England', 'kane hemmings'),
	('Ante Bajic', 'Austria', 'ante bajic'),
	('Ante Bajic', 'Austria', 'bajic'),
	('Laurențiu Corbu', 'Romania', 'laurentiu corbu'),
	('Laurențiu Corbu', 'Romania', 'corbu'),
	('Léo Vieira', 'Brazil', 'vieira'),
	('Léo Vieira', 'Brazil', 'leo vieira'),
	('Tyrhys Dolan', 'England', 'dolan'),
	('Tyrhys Dolan', 'England', 'tyrhys dolan'),
	('Ahmet Gülay', 'Turkey', 'gulay'),
	('Ahmet Gülay', 'Turkey', 'ahmet gulay'),
	('Randi Goteni', 'Congo', 'goteni'),
	('Randi Goteni', 'Congo', 'randi goteni'),
	('Rıdvan Yılmaz', 'Turkey', 'rdvan ylmaz'),
	('Rıdvan Yılmaz', 'Turkey', 'ylmaz'),
	('Lukas Scepanik', 'Germany', 'lukas scepanik'),
	('Lukas Scepanik', 'Germany', 'scepanik'),
	('Nesta Guinness-Walker', 'England', 'nesta guinnesswalker'),
	('Nesta Guinness-Walker', 'England', 'guinnesswalker'),
	('Théo Guivarch', 'France', 'guivarch'),
	('Théo Guivarch', 'France', 'theo guivarch'),
	('Léo Leroy', 'France', 'leroy'),
	('Léo Leroy', 'France', 'leo leroy'),
	('Edward Bolaños', 'Colombia', 'bolanos'),
	('Edward Bolaños', 'Colombia', 'edward bolanos'),
	('Edi Sylisufaj', 'Sweden', 'sylisufaj'),
	('Edi Sylisufaj', 'Sweden', 'edi sylisufaj'),
	('Davinson Jama', 'Ecuador', 'jama'),
	('Davinson Jama', 'Ecuador', 'davinson jama'),
	('Daniel O''Shaughnessy', 'Finland', 'daniel oshaughnessy'),
	('Daniel O''Shaughnessy', 'Finland', 'oshaughnessy'),
	('Shani Tarashaj', 'Switzerland', 'tarashaj'),
	('Shani Tarashaj', 'Switzerland', 'shani tarashaj'),
	('Ayodeji Sotona', 'Republic of Ireland', 'ayodeji sotona'),
	('Ayodeji Sotona', 'Republic of Ireland', 'sotona'),
	('Pedro Amador', 'Portugal', 'pedro amador'),
	('Pedro Amador', 'Portugal', 'amador'),
	('Jimmy Roca', 'Bolivia', 'jimmy roca'),
	('Jimmy Roca', 'Bolivia', 'roca'),
	('Rong Hao', 'China PR', 'rong hao'),
	('Rong Hao', 'China PR', 'hao'),
	('Haret Ortega', 'Mexico', 'haret ortega'),
	('Haret Ortega', 'Mexico', 'ortega'),
	('Andrés Perea', 'Colombia', 'andres perea'),
	('Andrés Perea', 'Colombia', 'perea'),
	('Callum Lang', 'England', 'callum lang'),
	('Callum Lang', 'England', 'lang'),
	('Guillaume Faivre', 'Switzerland', 'faivre'),
	('Guillaume Faivre', 'Switzerland', 'guillaume faivre'),
	('Harry Burgoyne', 'England', 'harry burgoyne'),
	('Harry Burgoyne', 'England', 'burgoyne'),
	('Shaya Sharahili', 'Saudi Arabia', 'sharahili'),
	('Shaya Sharahili', 'Saudi Arabia', 'shaya sharahili'),
	('Graham Smith', 'United States', 'smith'),
	('Graham Smith', 'United States', 'graham smith'),
	('Jordan Bowery', 'England', 'jordan bowery'),
	('Jordan Bowery', 'England', 'bowery'),
	('Nama Fofana', 'France', 'nama fofana'),
	('Nama Fofana', 'France', 'fofana'),
	('Damián Fernández', 'Argentina', 'fernandez'),
	('Damián Fernández', 'Argentina', 'damian fernandez'),
	('Patryk Tuszyński', 'Poland', 'tuszynski'),
	('Patryk Tuszyński', 'Poland', 'patryk tuszynski'),
	('Pierce Sweeney', 'Republic of Ireland', 'pierce sweeney'),
	('Pierce Sweeney', 'Republic of Ireland', 'sweeney'),
	('Mejías', 'Spain', 'mejias'),
	('Nicolás Sosa', 'Uruguay', 'sosa'),
	('Nicolás Sosa', 'Uruguay', 'nicolas sosa'),
	('Junior Kadile', 'France', 'kadile'),
	('Junior Kadile', 'France', 'junior kadile'),
	('Pablo Ruiz', 'Argentina', 'ruiz'),
	('Pablo Ruiz', 'Argentina', 'pablo ruiz'),
	('Sargon Abraham', 'Sweden', 'sargon abraham'),
	('Sargon Abraham', 'Sweden', 'abraham'),
	('Chi Wenyi', 'China PR', 'wenyi'),
	('Chi Wenyi', 'China PR', 'chi wenyi'),
	('Stuart O''Keefe', 'England', 'okeefe'),
	('Stuart O''Keefe', 'England', 'stuart okeefe'),
	('Ivar Furu', 'Norway', 'furu'),
	('Ivar Furu', 'Norway', 'ivar furu'),
	('Sebastian Klaas', 'Germany', 'sebastian klaas'),
	('Sebastian Klaas', 'Germany', 'klaas'),
	('Alessandro Semprini', 'Italy', 'semprini'),
	('Alessandro Semprini', 'Italy', 'alessandro semprini'),
	('Kevin Agudelo', 'Colombia', 'agudelo'),
	('Kevin Agudelo', 'Colombia', 'kevin agudelo'),
	('Tomáš Smola', 'Czech Republic', 'tomas smola'),
	('Tomáš Smola', 'Czech Republic', 'smola'),
	('Morgan Feeney', 'England', 'morgan feeney'),
	('Morgan Feeney', 'England', 'feeney'),
	('Ronaldo Rivas', 'Venezuela', 'ronaldo rivas'),
	('Ronaldo Rivas', 'Venezuela', 'rivas'),
	('Manuel Schwenk', 'Germany', 'manuel schwenk'),
	('Manuel Schwenk', 'Germany', 'schwenk'),
	('Pål Erik Ulvestad', 'Norway', 'ulvestad'),
	('Pål Erik Ulvestad', 'Norway', 'pal erik ulvestad'),
	('Aaron Calver', 'Australia', 'aaron calver'),
	('Aaron Calver', 'Australia', 'calver'),
	('George Ganea', 'Romania', 'george ganea'),
	('George Ganea', 'Romania', 'ganea'),
	('Egzon Binaku', 'Albania', 'egzon binaku'),
	('Egzon Binaku', 'Albania', 'binaku'),
	('Ryan Bowman', 'England', 'bowman'),
	('Ryan Bowman', 'England', 'ryan bowman'),
	('Derick Osei Yaw', 'France', 'yaw'),
	('Derick Osei Yaw', 'France', 'derick osei yaw'),
	('Jean Jules Mvondo', 'Cameroon', 'mvondo'),
	('Jean Jules Mvondo', 'Cameroon', 'jean jules mvondo'),
	('Łukasz Poręba', 'Poland', 'ukasz poreba'),
	('Łukasz Poręba', 'Poland', 'poreba'),
	('Shane McLoughlin', 'Republic of Ireland', 'mcloughlin'),
	('Shane McLoughlin', 'Republic of Ireland', 'shane mcloughlin'),
	('Mücahit Akçay', 'Turkey', 'akcay'),
	('Mücahit Akçay', 'Turkey', 'mucahit akcay'),
	('Sherwin Seedorf', 'Netherlands', 'seedorf'),
	('Sherwin Seedorf', 'Netherlands', 'sherwin seedorf'),
	('Jake Taylor', 'Wales', 'taylor'),
	('Jake Taylor', 'Wales', 'jake taylor'),
	('Leroy Kwadwo', 'Germany', 'leroy kwadwo'),
	('Leroy Kwadwo', 'Germany', 'kwadwo'),
	('Juan Pablo Vargas', 'Costa Rica', 'juan pablo vargas'),
	('Juan Pablo Vargas', 'Costa Rica', 'vargas'),
	('Alfons Amade', 'Germany', 'amade'),
	('Alfons Amade', 'Germany', 'alfons amade'),
	('Juan Bautista Cascini', 'Argentina', 'cascini'),
	('Juan Bautista Cascini', 'Argentina', 'juan bautista cascini'),
	('Ronaldo Prieto', 'Mexico', 'prieto'),
	('Ronaldo Prieto', 'Mexico', 'ronaldo prieto'),
	('Dion Donohue', 'Wales', 'donohue'),
	('Dion Donohue', 'Wales', 'dion donohue'),
	('Deklan Wynne', 'New Zealand', 'deklan wynne'),
	('Deklan Wynne', 'New Zealand', 'wynne'),
	('Joe Rankin-Costello', 'England', 'rankincostello'),
	('Joe Rankin-Costello', 'England', 'joe rankincostello'),
	('Steeve Beusnard', 'France', 'beusnard'),
	('Steeve Beusnard', 'France', 'steeve beusnard'),
	('Tom Hamer', 'England', 'hamer'),
	('Tom Hamer', 'England', 'tom hamer'),
	('Louis D''Arrigo', 'Australia', 'louis darrigo'),
	('Louis D''Arrigo', 'Australia', 'darrigo'),
	('Markus Mendler', 'Germany', 'markus mendler'),
	('Markus Mendler', 'Germany', 'mendler'),
	('Alistair McCann', 'Northern Ireland', 'alistair mccann'),
	('Alistair McCann', 'Northern Ireland', 'mccann'),
	('Kim Moon Hwan', 'Korea Republic', 'hwan'),
	('Kim Moon Hwan', 'Korea Republic', 'kim moon hwan'),
	('Matko Miljevic', 'United States', 'miljevic'),
	('Matko Miljevic', 'United States', 'matko miljevic'),
	('Siemen Voet', 'Belgium', 'voet'),
	('Siemen Voet', 'Belgium', 'siemen voet'),
	('Aaron Taylor-Sinclair', 'Scotland', 'aaron taylorsinclair'),
	('Aaron Taylor-Sinclair', 'Scotland', 'taylorsinclair'),
	('Erten Ersu', 'Turkey', 'ersu'),
	('Erten Ersu', 'Turkey', 'erten ersu'),
	('Jeong Dong Yun', 'Korea Republic', 'jeong dong yun'),
	('Jeong Dong Yun', 'Korea Republic', 'yun'),
	('Alexis Trouillet', 'France', 'alexis trouillet'),
	('Alexis Trouillet', 'France', 'trouillet'),
	('Mamoudou Karamoko', 'France', 'mamoudou karamoko'),
	('Mamoudou Karamoko', 'France', 'karamoko'),
	('Amar Dedić', 'Bosnia Herzegovina', 'amar dedic'),
	('Amar Dedić', 'Bosnia Herzegovina', 'dedic'),
	('Yi Teng', 'China PR', 'yi teng'),
	('Yi Teng', 'China PR', 'teng'),
	('Kim Kyung Jung', 'Korea Republic', 'jung'),
	('Kim Kyung Jung', 'Korea Republic', 'kim kyung jung'),
	('Vadim Karpov', 'Russia', 'karpov'),
	('Vadim Karpov', 'Russia', 'vadim karpov'),
	('Carlos Higuera', 'Mexico', 'carlos higuera'),
	('Carlos Higuera', 'Mexico', 'higuera'),
	('Marc Pedersen', 'Denmark', 'pedersen'),
	('Marc Pedersen', 'Denmark', 'marc pedersen'),
	('Pépé Bonet', 'DR Congo', 'bonet'),
	('Pépé Bonet', 'DR Congo', 'pepe bonet'),
	('Jordan Tell', 'France', 'tell'),
	('Jordan Tell', 'France', 'jordan tell'),
	('Taylor Washington', 'United States', 'taylor washington'),
	('Taylor Washington', 'United States', 'washington'),
	('Jannes Vollert', 'Germany', 'jannes vollert'),
	('Jannes Vollert', 'Germany', 'vollert'),
	('Hong Jeong Un', 'Korea Republic', 'un'),
	('Hong Jeong Un', 'Korea Republic', 'hong jeong un'),
	('Eric Lanini', 'Italy', 'lanini'),
	('Eric Lanini', 'Italy', 'eric lanini'),
	('Luka Slišković', 'Austria', 'sliskovic'),
	('Luka Slišković', 'Austria', 'luka sliskovic'),
	('Paul Nebel', 'Germany', 'paul nebel'),
	('Paul Nebel', 'Germany', 'nebel'),
	('Galileo Del Castillo', 'Venezuela', 'galileo del castillo'),
	('Galileo Del Castillo', 'Venezuela', 'castillo'),
	('Tobias Karlsson', 'Sweden', 'karlsson'),
	('Tobias Karlsson', 'Sweden', 'tobias karlsson'),
	('José Manríquez', 'Venezuela', 'manriquez'),
	('José Manríquez', 'Venezuela', 'jose manriquez'),
	('Cammy Smith', 'Scotland', 'smith'),
	('Cammy Smith', 'Scotland', 'cammy smith'),
	('Martin Angha', 'Switzerland', 'angha'),
	('Martin Angha', 'Switzerland', 'martin angha'),
	('Willi Evseev', 'Germany', 'evseev'),
	('Willi Evseev', 'Germany', 'willi evseev'),
	('Shintaro Nago', 'Japan', 'shintaro nago'),
	('Shintaro Nago', 'Japan', 'nago'),
	('Michael Salazar', 'Belize', 'michael salazar'),
	('Michael Salazar', 'Belize', 'salazar'),
	('Yehvann Diouf', 'France', 'yehvann diouf'),
	('Yehvann Diouf', 'France', 'diouf'),
	('Francisco Sierralta', 'Chile', 'francisco sierralta'),
	('Francisco Sierralta', 'Chile', 'sierralta'),
	('Paulos Abraham', 'Sweden', 'abraham'),
	('Paulos Abraham', 'Sweden', 'paulos abraham'),
	('Guillermo Firpo', 'Uruguay', 'firpo'),
	('Guillermo Firpo', 'Uruguay', 'guillermo firpo'),
	('Eduar Caicedo', 'Colombia', 'eduar caicedo'),
	('Eduar Caicedo', 'Colombia', 'caicedo'),
	('Ivo Kestler', 'Argentina', 'kestler'),
	('Ivo Kestler', 'Argentina', 'ivo kestler'),
	('Julián López', 'Argentina', 'lopez'),
	('Julián López', 'Argentina', 'julian lopez'),
	('Tristan Dekker', 'Netherlands', 'tristan dekker'),
	('Tristan Dekker', 'Netherlands', 'dekker'),
	('Luka Tankulić', 'Germany', 'tankulic'),
	('Luka Tankulić', 'Germany', 'luka tankulic'),
	('Matías Pérez', 'Argentina', 'matias perez'),
	('Matías Pérez', 'Argentina', 'perez'),
	('Ryan Sweeney', 'Republic of Ireland', 'sweeney'),
	('Ryan Sweeney', 'Republic of Ireland', 'ryan sweeney'),
	('Oskar Zawada', 'Poland', 'oskar zawada'),
	('Oskar Zawada', 'Poland', 'zawada'),
	('Yang Cheng', 'China PR', 'yang cheng'),
	('Yang Cheng', 'China PR', 'cheng'),
	('Tino Casali', 'Austria', 'tino casali'),
	('Tino Casali', 'Austria', 'casali'),
	('Yuzo Kobayashi', 'Japan', 'yuzo kobayashi'),
	('Yuzo Kobayashi', 'Japan', 'kobayashi'),
	('Przemyslaw Mystkowski', 'Poland', 'przemyslaw mystkowski'),
	('Przemyslaw Mystkowski', 'Poland', 'mystkowski'),
	('Oliver Steurer', 'Germany', 'oliver steurer'),
	('Oliver Steurer', 'Germany', 'steurer'),
	('Marcel Engelhardt', 'Germany', 'marcel engelhardt'),
	('Marcel Engelhardt', 'Germany', 'engelhardt'),
	('Muhammed Kiprit', 'Turkey', 'muhammed kiprit'),
	('Muhammed Kiprit', 'Turkey', 'kiprit'),
	('Virgiliu Postolachi', 'France', 'virgiliu postolachi'),
	('Virgiliu Postolachi', 'France', 'postolachi'),
	('Douglas Bergqvist', 'Sweden', 'douglas bergqvist'),
	('Douglas Bergqvist', 'Sweden', 'bergqvist'),
	('Alexander Nandzik', 'Germany', 'nandzik'),
	('Alexander Nandzik', 'Germany', 'alexander nandzik'),
	('Michał Szromnik', 'Poland', 'szromnik'),
	('Michał Szromnik', 'Poland', 'micha szromnik'),
	('Daniel Drescher', 'Austria', 'drescher'),
	('Daniel Drescher', 'Austria', 'daniel drescher'),
	('Robin Book', 'Sweden', 'book'),
	('Robin Book', 'Sweden', 'robin book'),
	('Mateo Abeijón', 'Uruguay', 'mateo abeijon'),
	('Mateo Abeijón', 'Uruguay', 'abeijon'),
	('Braian Martínez', 'Argentina', 'braian martinez'),
	('Braian Martínez', 'Argentina', 'martinez'),
	('Rodrigo Contreras', 'Argentina', 'contreras'),
	('Rodrigo Contreras', 'Argentina', 'rodrigo contreras'),
	('Zubimendi', 'Spain', 'zubimendi'),
	('Randall Leal', 'Costa Rica', 'leal'),
	('Randall Leal', 'Costa Rica', 'randall leal'),
	('Espen Børufsen', 'Norway', 'brufsen'),
	('Espen Børufsen', 'Norway', 'espen brufsen'),
	('Brian Easton', 'Scotland', 'brian easton'),
	('Brian Easton', 'Scotland', 'easton'),
	('Canillas', 'Spain', 'canillas'),
	('Bassala Sambou', 'Germany', 'bassala sambou'),
	('Bassala Sambou', 'Germany', 'sambou'),
	('Leonel Caffaratti', 'Argentina', 'caffaratti'),
	('Leonel Caffaratti', 'Argentina', 'leonel caffaratti'),
	('Florin Purece', 'Romania', 'purece'),
	('Florin Purece', 'Romania', 'florin purece'),
	('Luis Vargas', 'Bolivia', 'vargas'),
	('Luis Vargas', 'Bolivia', 'luis vargas'),
	('Lee Hodson', 'Northern Ireland', 'hodson'),
	('Lee Hodson', 'Northern Ireland', 'lee hodson'),
	('Kevin Walker', 'Sweden', 'kevin walker'),
	('Kevin Walker', 'Sweden', 'walker'),
	('Heo Yong Joon', 'Korea Republic', 'joon'),
	('Heo Yong Joon', 'Korea Republic', 'heo yong joon'),
	('Conor Thomas', 'England', 'conor thomas'),
	('Conor Thomas', 'England', 'thomas'),
	('Guille Rosas', 'Spain', 'rosas'),
	('Guille Rosas', 'Spain', 'guille rosas'),
	('Harmeet Singh', 'Norway', 'singh'),
	('Harmeet Singh', 'Norway', 'harmeet singh'),
	('Frederik Winther', 'Denmark', 'frederik winther'),
	('Frederik Winther', 'Denmark', 'winther'),
	('Gökdeniz Bayrakdar', 'Turkey', 'bayrakdar'),
	('Gökdeniz Bayrakdar', 'Turkey', 'gokdeniz bayrakdar'),
	('Arnedo', 'Spain', 'arnedo'),
	('Kenzo Goudmijn', 'Netherlands', 'kenzo goudmijn'),
	('Kenzo Goudmijn', 'Netherlands', 'goudmijn'),
	('Mat Sadler', 'England', 'mat sadler'),
	('Mat Sadler', 'England', 'sadler'),
	('Mario Hernández', 'Spain', 'mario hernandez'),
	('Mario Hernández', 'Spain', 'hernandez'),
	('Hilal Ben Moussa', 'Netherlands', 'moussa'),
	('Hilal Ben Moussa', 'Netherlands', 'hilal ben moussa'),
	('Karim Aribi', 'Algeria', 'karim aribi'),
	('Karim Aribi', 'Algeria', 'aribi'),
	('Jhonata Robert', 'Brazil', 'robert'),
	('Jhonata Robert', 'Brazil', 'jhonata robert'),
	('Sergio Gónzalez', 'Spain', 'sergio gonzalez'),
	('Sergio Gónzalez', 'Spain', 'gonzalez'),
	('Armin Gremsl', 'Austria', 'armin gremsl'),
	('Armin Gremsl', 'Austria', 'gremsl'),
	('Héctor Pérez', 'Venezuela', 'hector perez'),
	('Héctor Pérez', 'Venezuela', 'perez'),
	('Danny Mandroiu', 'Republic of Ireland', 'mandroiu'),
	('Danny Mandroiu', 'Republic of Ireland', 'danny mandroiu'),
	('Youssef Maziz', 'France', 'maziz'),
	('Youssef Maziz', 'France', 'youssef maziz'),
	('Richard van der Venne', 'Netherlands', 'venne'),
	('Richard van der Venne', 'Netherlands', 'richard van der venne'),
	('Arda Kızıldağ', 'Turkey', 'arda kzldag'),
	('Arda Kızıldağ', 'Turkey', 'kzldag'),
	('Sékou Mara', 'France', 'sekou mara'),
	('Sékou Mara', 'France', 'mara'),
	('Renzo Bacchia', 'Uruguay', 'renzo bacchia'),
	('Renzo Bacchia', 'Uruguay', 'bacchia'),
	('Hideki Ishige', 'Japan', 'hideki ishige'),
	('Hideki Ishige', 'Japan', 'ishige'),
	('Abdurrahman Canli', 'Turkey', 'abdurrahman canli'),
	('Abdurrahman Canli', 'Turkey', 'canli'),
	('Daniel Cleary', 'Republic of Ireland', 'daniel cleary'),
	('Daniel Cleary', 'Republic of Ireland', 'cleary'),
	('Zé Eduardo', 'Brazil', 'eduardo'),
	('Zé Eduardo', 'Brazil', 'ze eduardo'),
	('Manuel De Luca', 'Italy', 'luca'),
	('Manuel De Luca', 'Italy', 'manuel de luca'),
	('Chris Taylor', 'England', 'taylor'),
	('Chris Taylor', 'England', 'chris taylor'),
	('Tony Rocha', 'Belize', 'tony rocha'),
	('Tony Rocha', 'Belize', 'rocha'),
	('Peter Pokorný', 'Slovakia', 'pokorny'),
	('Peter Pokorný', 'Slovakia', 'peter pokorny'),
	('Fran González', 'Spain', 'fran gonzalez'),
	('Fran González', 'Spain', 'gonzalez'),
	('Oslimg Mora', 'Peru', 'mora'),
	('Oslimg Mora', 'Peru', 'oslimg mora'),
	('Thomas Dähne', 'Germany', 'dahne'),
	('Thomas Dähne', 'Germany', 'thomas dahne'),
	('Thabiso Monyane', 'South Africa', 'monyane'),
	('Thabiso Monyane', 'South Africa', 'thabiso monyane'),
	('Cheikh Niasse', 'Senegal', 'cheikh niasse'),
	('Cheikh Niasse', 'Senegal', 'niasse'),
	('Nicolas Seiwald', 'Austria', 'nicolas seiwald'),
	('Nicolas Seiwald', 'Austria', 'seiwald'),
	('Kasper Skaanes', 'Norway', 'kasper skaanes'),
	('Kasper Skaanes', 'Norway', 'skaanes'),
	('Rosmel Villanueva', 'Venezuela', 'rosmel villanueva'),
	('Rosmel Villanueva', 'Venezuela', 'villanueva'),
	('Joaquín Muñoz', 'Chile', 'munoz'),
	('Joaquín Muñoz', 'Chile', 'joaquin munoz'),
	('Adalberto Carrasquilla', 'Panama', 'adalberto carrasquilla'),
	('Adalberto Carrasquilla', 'Panama', 'carrasquilla'),
	('Kayacan Erdoğan', 'Turkey', 'kayacan erdogan'),
	('Kayacan Erdoğan', 'Turkey', 'erdogan'),
	('José Cazares', 'Ecuador', 'jose cazares'),
	('José Cazares', 'Ecuador', 'cazares'),
	('Sebastián Prieto', 'Argentina', 'prieto'),
	('Sebastián Prieto', 'Argentina', 'sebastian prieto'),
	('João Gonçalves', 'Portugal', 'joao goncalves'),
	('João Gonçalves', 'Portugal', 'goncalves'),
	('Paul Caddis', 'Scotland', 'paul caddis'),
	('Paul Caddis', 'Scotland', 'caddis'),
	('Sheriff Sinyan', 'Gambia', 'sinyan'),
	('Sheriff Sinyan', 'Gambia', 'sheriff sinyan'),
	('Eldor Shomurodov', 'Uzbekistan', 'shomurodov'),
	('Eldor Shomurodov', 'Uzbekistan', 'eldor shomurodov'),
	('Christian Kinsombi', 'Germany', 'kinsombi'),
	('Christian Kinsombi', 'Germany', 'christian kinsombi'),
	('Sido Jombati', 'Portugal', 'sido jombati'),
	('Sido Jombati', 'Portugal', 'jombati'),
	('Zafer Görgen', 'Turkey', 'zafer gorgen'),
	('Zafer Görgen', 'Turkey', 'gorgen'),
	('Takuma Ominami', 'Japan', 'takuma ominami'),
	('Takuma Ominami', 'Japan', 'ominami'),
	('Jajá', 'Brazil', 'jaja'),
	('Lorenzo Pirola', 'Italy', 'pirola'),
	('Lorenzo Pirola', 'Italy', 'lorenzo pirola'),
	('Facundo Lando', 'Argentina', 'lando'),
	('Facundo Lando', 'Argentina', 'facundo lando'),
	('Ronny Medina', 'Ecuador', 'medina'),
	('Ronny Medina', 'Ecuador', 'ronny medina'),
	('Thomas Vollnhofer', 'Austria', 'thomas vollnhofer'),
	('Thomas Vollnhofer', 'Austria', 'vollnhofer'),
	('Kelvin Mellor', 'England', 'mellor'),
	('Kelvin Mellor', 'England', 'kelvin mellor'),
	('Mark Connolly', 'Republic of Ireland', 'connolly'),
	('Mark Connolly', 'Republic of Ireland', 'mark connolly'),
	('Samir Banjai', 'Portugal', 'samir banjai'),
	('Samir Banjai', 'Portugal', 'banjai'),
	('Anthony Rouault', 'France', 'anthony rouault'),
	('Anthony Rouault', 'France', 'rouault'),
	('Ionuț Balaur', 'Romania', 'balaur'),
	('Ionuț Balaur', 'Romania', 'ionut balaur'),
	('Adam Hammill', 'England', 'adam hammill'),
	('Adam Hammill', 'England', 'hammill'),
	('Thomas Rodríguez', 'Chile', 'thomas rodriguez'),
	('Thomas Rodríguez', 'Chile', 'rodriguez'),
	('Fran Navarro', 'Spain', 'fran navarro'),
	('Fran Navarro', 'Spain', 'navarro'),
	('Hernán Hinostroza', 'Peru', 'hernan hinostroza'),
	('Hernán Hinostroza', 'Peru', 'hinostroza'),
	('Andrea Dini', 'Italy', 'andrea dini'),
	('Andrea Dini', 'Italy', 'dini'),
	('Davor Blažević', 'Sweden', 'blazevic'),
	('Davor Blažević', 'Sweden', 'davor blazevic'),
	('Philipp Heerwagen', 'Germany', 'heerwagen'),
	('Philipp Heerwagen', 'Germany', 'philipp heerwagen'),
	('Diego Angles', 'Peru', 'angles'),
	('Diego Angles', 'Peru', 'diego angles'),
	('Sven Müller', 'Germany', 'muller'),
	('Sven Müller', 'Germany', 'sven muller'),
	('Sultan Ali Al Sawadi', 'Saudi Arabia', 'sawadi'),
	('Sultan Ali Al Sawadi', 'Saudi Arabia', 'sultan ali al sawadi'),
	('Lukas Raeder', 'Germany', 'raeder'),
	('Lukas Raeder', 'Germany', 'lukas raeder'),
	('Gary O''Neill', 'Republic of Ireland', 'gary oneill'),
	('Gary O''Neill', 'Republic of Ireland', 'oneill'),
	('Andrei Rațiu', 'Romania', 'ratiu'),
	('Andrei Rațiu', 'Romania', 'andrei ratiu'),
	('Lanchi', 'Spain', 'lanchi'),
	('Kike Hermoso', 'Spain', 'kike hermoso'),
	('Kike Hermoso', 'Spain', 'hermoso'),
	('Andrea Colpani', 'Italy', 'colpani'),
	('Andrea Colpani', 'Italy', 'andrea colpani'),
	('Moussa Diarra', 'France', 'diarra'),
	('Moussa Diarra', 'France', 'moussa diarra'),
	('José Alberto Castillo', 'Mexico', 'jose alberto castillo'),
	('José Alberto Castillo', 'Mexico', 'castillo')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';