INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Cristóbal Muñoz', 'Chile', 'player'),
	('Macklin Freke', 'Australia', 'player'),
	('Brian McManus', 'Republic of Ireland', 'player'),
	('Mads Steenberg', 'Denmark', 'player'),
	('Niall O''Keeffe', 'Republic of Ireland', 'player'),
	('Lee Sung Yoon', 'Korea Republic', 'player'),
	('Ryan Law', 'England', 'player'),
	('Thomas Callens', 'France', 'player'),
	('Joe Neal', 'England', 'player'),
	('Daniel Retamal', 'Chile', 'player'),
	('Jairo Carreño', 'Ecuador', 'player'),
	('Oscar Taty Maritu', 'DR Congo', 'player'),
	('Joel Macias', 'Ecuador', 'player'),
	('Carl Johnston', 'Northern Ireland', 'player'),
	('Oskar van Hattum', 'New Zealand', 'player'),
	('Choi Jae Young', 'Korea Republic', 'player'),
	('Jonathan Sirois', 'Canada', 'player'),
	('Matheo Raab', 'Germany', 'player'),
	('Nico Jones', 'England', 'player'),
	('Scott Lynch', 'Republic of Ireland', 'player'),
	('Casey Walls', 'United States', 'player'),
	('Néicer Acosta', 'Ecuador', 'player'),
	('Sebastian Pop', 'Norway', 'player'),
	('Harrison Hopper', 'England', 'player'),
	('Alex Martillo', 'Ecuador', 'player'),
	('Sam Beckwith', 'England', 'player'),
	('Joseph Starbuck', 'England', 'player'),
	('Kent Malic Swaleh', 'Norway', 'player'),
	('Kyle Munro', 'Scotland', 'player'),
	('Matias Colossi', 'Chile', 'player'),
	('Rafiq Khaleel', 'Morocco', 'player'),
	('Maximilian Großer', 'Germany', 'player'),
	('Johan Campaña', 'Colombia', 'player'),
	('Saúl Guarirapa', 'Venezuela', 'player'),
	('Duncan Idehen', 'England', 'player'),
	('Tyreece Onyeka', 'England', 'player'),
	('Xie Zhiwei', 'China PR', 'player'),
	('Andrei Zaharia', 'Romania', 'player'),
	('Alessandro Pietrogiovanna', 'Switzerland', 'player'),
	('Hussain Al Quraish', 'Saudi Arabia', 'player'),
	('Joe Woodiwiss', 'Wales', 'player'),
	('Darragh Burns', 'Northern Ireland', 'player'),
	('Joshua Honohan', 'Republic of Ireland', 'player'),
	('Alexander Vogler', 'Germany', 'player'),
	('Jarrod Carluccio', 'Australia', 'player'),
	('Yang Yu min', 'Korea Republic', 'player'),
	('Darragh Power', 'Republic of Ireland', 'player'),
	('Aleksander Stawiarz', 'Poland', 'player'),
	('Issah Salou', 'Niger', 'player'),
	('Anthony Cheshire', 'England', 'player'),
	('Jamie Cleary', 'Republic of Ireland', 'player'),
	('Lee Seung Jae', 'Korea Republic', 'player'),
	('Gulab Al Enazi', 'Saudi Arabia', 'player'),
	('Ryan Rydel', 'England', 'player'),
	('Pan Ximing', 'China PR', 'player'),
	('Matthew Cox', 'England', 'player'),
	('Huang Zihao', 'China PR', 'player'),
	('Tariq Al Shahrani', 'Saudi Arabia', 'player'),
	('Jacob Ondrejka', 'Sweden', 'player'),
	('Noah Henchoz', 'Switzerland', 'player'),
	('Johandry Hidalgo', 'Venezuela', 'player'),
	('Dylan Boyle', 'Northern Ireland', 'player'),
	('Stephen Doherty', 'Republic of Ireland', 'player'),
	('Jack Madelin', 'Wales', 'player'),
	('Ma Defu', 'China PR', 'player'),
	('Wang Zhifeng', 'China PR', 'player'),
	('Junior Luamba', 'England', 'player'),
	('Calem Nieuwenhof', 'Australia', 'player'),
	('Roger Murillo', 'Colombia', 'player'),
	('Emil Hellman', 'Sweden', 'player'),
	('Ayoub Assal', 'England', 'player'),
	('Wen Yongjun', 'China PR', 'player'),
	('Yerson Mosquera', 'Colombia', 'player'),
	('Joaquín Gutiérrez', 'Chile', 'player'),
	('Shayden Morris', 'England', 'player'),
	('Jack Lemoignan', 'Northern Ireland', 'player'),
	('Wen Da', 'China PR', 'player'),
	('Massimo Giamattei', 'England', 'player'),
	('Cha Oh Yeon', 'Korea Republic', 'player'),
	('José Mulato', 'Colombia', 'player'),
	('Kim Ki Yeol', 'Korea Republic', 'player'),
	('Jake O''Brien', 'Republic of Ireland', 'player'),
	('Promise Omochere', 'Republic of Ireland', 'player'),
	('Jamie Armstrong', 'Scotland', 'player'),
	('Mackye Townsend-West', 'England', 'player'),
	('Samuel Cartwright', 'England', 'player'),
	('Lido Lotefa', 'DR Congo', 'player'),
	('Lewis Bell', 'England', 'player'),
	('Mike Nzongong', 'Republic of Ireland', 'player'),
	('Zhang Yu', 'China PR', 'player'),
	('Yhonatan Murgas', 'Colombia', 'player'),
	('Zang Yifeng', 'China PR', 'player'),
	('Zhu Jiahao', 'China PR', 'player'),
	('Danila Bokov', 'Russia', 'player'),
	('Kieran Farren', 'Republic of Ireland', 'player'),
	('Lewis Simper', 'England', 'player'),
	('Malcolm Stolt', 'Sweden', 'player'),
	('Félix Imanol Cárdenas', 'Bolivia', 'player'),
	('Raphael Borges Rodrigues', 'Australia', 'player'),
	('Morgan Roberts', 'England', 'player'),
	('Justin Haak', 'United States', 'player'),
	('Fabián Ángel', 'Colombia', 'player'),
	('Kyle Hayde', 'England', 'player'),
	('Sam Booth', 'England', 'player'),
	('Maxim Gresler', 'Germany', 'player'),
	('Marco Mannhardt', 'Germany', 'player'),
	('Jake Davidson', 'Scotland', 'player'),
	('Harrison Burrows', 'England', 'player'),
	('Mackenzie Chapman', 'England', 'player'),
	('Myung Se Jin', 'Korea Republic', 'player'),
	('Jeong Ji Yong', 'Korea Republic', 'player'),
	('Michael Harris', 'Republic of Ireland', 'player'),
	('Alou Kuol', 'South Sudan', 'player'),
	('Chen-Zeng Tailang', 'China PR', 'player'),
	('Memet Abdulla Ezmat', 'China PR', 'player'),
	('Gao Xiang', 'China PR', 'player'),
	('Liam Munther', 'Sweden', 'player'),
	('Hannes Sveijer', 'Sweden', 'player'),
	('Li Xuebo', 'China PR', 'player'),
	('Gian Marco Crespi', 'Italy', 'player'),
	('Nelson Iseguan', 'England', 'player'),
	('Cheng Hui', 'China PR', 'player'),
	('Ricardo Dinanga', 'Republic of Ireland', 'player'),
	('Sebastián Navarro', 'Colombia', 'player'),
	('Song Haiwang', 'China PR', 'player'),
	('Seo Min Woo', 'Korea Republic', 'player'),
	('Darren Collins', 'Republic of Ireland', 'player'),
	('Kevin Fernandez', 'Chile', 'player'),
	('Huang Jiahui', 'China PR', 'player'),
	('Dylan Aravena', 'Chile', 'player'),
	('Alex Cetiner', 'Republic of Ireland', 'player'),
	('Jack Smith', 'England', 'player'),
	('Ethan Espinoza', 'Chile', 'player'),
	('Jack Larkin', 'Republic of Ireland', 'player'),
	('Daniel Luna', 'Colombia', 'player'),
	('Alex Phelan', 'Republic of Ireland', 'player'),
	('Patrick McGarvey', 'Republic of Ireland', 'player'),
	('Mohammed Al Nakhilan', 'Saudi Arabia', 'player'),
	('Wang Haijian', 'China PR', 'player'),
	('Jack Arthur', 'England', 'player'),
	('Tan Chun Lok', 'Hong Kong', 'player'),
	('Lan Jingxuan', 'China PR', 'player'),
	('Guo Yunqi', 'China PR', 'player'),
	('Miloš Ćoćić', 'Serbia', 'player'),
	('James Akintunde', 'England', 'player'),
	('Lewys Twamley', 'Wales', 'player'),
	('Liu Chaoyang', 'China PR', 'player'),
	('Chen Chunxin', 'China PR', 'player'),
	('Jamie Browne', 'Republic of Ireland', 'player'),
	('Laurie Walker', 'England', 'player'),
	('Hanssel Delgado', 'Ecuador', 'player'),
	('Shan Huanhuan', 'China PR', 'player'),
	('Fu Yuncheng', 'China PR', 'player'),
	('Ma Zhen', 'China PR', 'player'),
	('Chen Kejiang', 'China PR', 'player'),
	('Wang Jianwen', 'China PR', 'player'),
	('Brendon Shabani', 'Albania', 'player'),
	('Jay Bird', 'England', 'player'),
	('Laurence Smith', 'England', 'player'),
	('Liam Waldock', 'England', 'player'),
	('Brayan Montaño', 'Colombia', 'player'),
	('Liam Ravenhill', 'England', 'player'),
	('Reinaldo Fontalvo', 'Colombia', 'player'),
	('Chen Zitong', 'China PR', 'player'),
	('Wang Zhenghao', 'China PR', 'player'),
	('Zhong Jiyu', 'China PR', 'player'),
	('Huang Wenzhou', 'China PR', 'player'),
	('Song Yue', 'China PR', 'player'),
	('Wang Huapeng', 'China PR', 'player'),
	('Mateo Flores', 'Bolivia', 'player'),
	('Zhang Mengxuan', 'China PR', 'player'),
	('Vani Da Silva', 'England', 'player'),
	('Xia Ao', 'China PR', 'player'),
	('Ben Hough', 'England', 'player'),
	('Ronan McKinley', 'England', 'player'),
	('Wang Zhen''ao', 'China PR', 'player'),
	('Zhou Xiao', 'China PR', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Cristóbal Muñoz', 'Chile', 'cristobal munoz'),
	('Cristóbal Muñoz', 'Chile', 'munoz'),
	('Macklin Freke', 'Australia', 'macklin freke'),
	('Macklin Freke', 'Australia', 'freke'),
	('Brian McManus', 'Republic of Ireland', 'brian mcmanus'),
	('Brian McManus', 'Republic of Ireland', 'mcmanus'),
	('Mads Steenberg', 'Denmark', 'mads steenberg'),
	('Mads Steenberg', 'Denmark', 'steenberg'),
	('Niall O''Keeffe', 'Republic of Ireland', 'okeeffe'),
	('Niall O''Keeffe', 'Republic of Ireland', 'niall okeeffe'),
	('Lee Sung Yoon', 'Korea Republic', 'yoon'),
	('Lee Sung Yoon', 'Korea Republic', 'lee sung yoon'),
	('Ryan Law', 'England', 'law'),
	('Ryan Law', 'England', 'ryan law'),
	('Thomas Callens', 'France', 'thomas callens'),
	('Thomas Callens', 'France', 'callens'),
	('Joe Neal', 'England', 'neal'),
	('Joe Neal', 'England', 'joe neal'),
	('Daniel Retamal', 'Chile', 'retamal'),
	('Daniel Retamal', 'Chile', 'daniel retamal'),
	('Jairo Carreño', 'Ecuador', 'carreno'),
	('Jairo Carreño', 'Ecuador', 'jairo carreno'),
	('Oscar Taty Maritu', 'DR Congo', 'oscar taty maritu'),
	('Oscar Taty Maritu', 'DR Congo', 'maritu'),
	('Joel Macias', 'Ecuador', 'macias'),
	('Joel Macias', 'Ecuador', 'joel macias'),
	('Carl Johnston', 'Northern Ireland', 'johnston'),
	('Carl Johnston', 'Northern Ireland', 'carl johnston'),
	('Oskar van Hattum', 'New Zealand', 'hattum'),
	('Oskar van Hattum', 'New Zealand', 'oskar van hattum'),
	('Choi Jae Young', 'Korea Republic', 'young'),
	('Choi Jae Young', 'Korea Republic', 'choi jae young'),
	('Jonathan Sirois', 'Canada', 'sirois'),
	('Jonathan Sirois', 'Canada', 'jonathan sirois'),
	('Matheo Raab', 'Germany', 'raab'),
	('Matheo Raab', 'Germany', 'matheo raab'),
	('Nico Jones', 'England', 'jones'),
	('Nico Jones', 'England', 'nico jones'),
	('Scott Lynch', 'Republic of Ireland', 'scott lynch'),
	('Scott Lynch', 'Republic of Ireland', 'lynch'),
	('Casey Walls', 'United States', 'walls'),
	('Casey Walls', 'United States', 'casey walls'),
	('Néicer Acosta', 'Ecuador', 'neicer acosta'),
	('Néicer Acosta', 'Ecuador', 'acosta'),
	('Sebastian Pop', 'Norway', 'pop'),
	('Sebastian Pop', 'Norway', 'sebastian pop'),
	('Harrison Hopper', 'England', 'harrison hopper'),
	('Harrison Hopper', 'England', 'hopper'),
	('Alex Martillo', 'Ecuador', 'alex martillo'),
	('Alex Martillo', 'Ecuador', 'martillo'),
	('Sam Beckwith', 'England', 'beckwith'),
	('Sam Beckwith', 'England', 'sam beckwith'),
	('Joseph Starbuck', 'England', 'joseph starbuck'),
	('Joseph Starbuck', 'England', 'starbuck'),
	('Kent Malic Swaleh', 'Norway', 'kent malic swaleh'),
	('Kent Malic Swaleh', 'Norway', 'swaleh'),
	('Kyle Munro', 'Scotland', 'munro'),
	('Kyle Munro', 'Scotland', 'kyle munro'),
	('Matias Colossi', 'Chile', 'colossi'),
	('Matias Colossi', 'Chile', 'matias colossi'),
	('Rafiq Khaleel', 'Morocco', 'rafiq khaleel'),
	('Rafiq Khaleel', 'Morocco', 'khaleel'),
	('Maximilian Großer', 'Germany', 'groer'),
	('Maximilian Großer', 'Germany', 'maximilian groer'),
	('Johan Campaña', 'Colombia', 'campana'),
	('Johan Campaña', 'Colombia', 'johan campana'),
	('Saúl Guarirapa', 'Venezuela', 'guarirapa'),
	('Saúl Guarirapa', 'Venezuela', 'saul guarirapa'),
	('Duncan Idehen', 'England', 'idehen'),
	('Duncan Idehen', 'England', 'duncan idehen'),
	('Tyreece Onyeka', 'England', 'tyreece onyeka'),
	('Tyreece Onyeka', 'England', 'onyeka'),
	('Xie Zhiwei', 'China PR', 'zhiwei'),
	('Xie Zhiwei', 'China PR', 'xie zhiwei'),
	('Andrei Zaharia', 'Romania', 'zaharia'),
	('Andrei Zaharia', 'Romania', 'andrei zaharia'),
	('Alessandro Pietrogiovanna', 'Switzerland', 'alessandro pietrogiovanna'),
	('Alessandro Pietrogiovanna', 'Switzerland', 'pietrogiovanna'),
	('Hussain Al Quraish', 'Saudi Arabia', 'hussain al quraish'),
	('Hussain Al Quraish', 'Saudi Arabia', 'quraish'),
	('Joe Woodiwiss', 'Wales', 'woodiwiss'),
	('Joe Woodiwiss', 'Wales', 'joe woodiwiss'),
	('Darragh Burns', 'Northern Ireland', 'burns'),
	('Darragh Burns', 'Northern Ireland', 'darragh burns'),
	('Joshua Honohan', 'Republic of Ireland', 'honohan'),
	('Joshua Honohan', 'Republic of Ireland', 'joshua honohan'),
	('Alexander Vogler', 'Germany', 'vogler'),
	('Alexander Vogler', 'Germany', 'alexander vogler'),
	('Jarrod Carluccio', 'Australia', 'carluccio'),
	('Jarrod Carluccio', 'Australia', 'jarrod carluccio'),
	('Yang Yu min', 'Korea Republic', 'yang yu min'),
	('Yang Yu min', 'Korea Republic', 'min'),
	('Darragh Power', 'Republic of Ireland', 'power'),
	('Darragh Power', 'Republic of Ireland', 'darragh power'),
	('Aleksander Stawiarz', 'Poland', 'stawiarz'),
	('Aleksander Stawiarz', 'Poland', 'aleksander stawiarz'),
	('Issah Salou', 'Niger', 'issah salou'),
	('Issah Salou', 'Niger', 'salou'),
	('Anthony Cheshire', 'England', 'cheshire'),
	('Anthony Cheshire', 'England', 'anthony cheshire'),
	('Jamie Cleary', 'Republic of Ireland', 'jamie cleary'),
	('Jamie Cleary', 'Republic of Ireland', 'cleary'),
	('Lee Seung Jae', 'Korea Republic', 'lee seung jae'),
	('Lee Seung Jae', 'Korea Republic', 'jae'),
	('Gulab Al Enazi', 'Saudi Arabia', 'gulab al enazi'),
	('Gulab Al Enazi', 'Saudi Arabia', 'enazi'),
	('Ryan Rydel', 'England', 'ryan rydel'),
	('Ryan Rydel', 'England', 'rydel'),
	('Pan Ximing', 'China PR', 'pan ximing'),
	('Pan Ximing', 'China PR', 'ximing'),
	('Matthew Cox', 'England', 'cox'),
	('Matthew Cox', 'England', 'matthew cox'),
	('Huang Zihao', 'China PR', 'zihao'),
	('Huang Zihao', 'China PR', 'huang zihao'),
	('Tariq Al Shahrani', 'Saudi Arabia', 'shahrani'),
	('Tariq Al Shahrani', 'Saudi Arabia', 'tariq al shahrani'),
	('Jacob Ondrejka', 'Sweden', 'ondrejka'),
	('Jacob Ondrejka', 'Sweden', 'jacob ondrejka'),
	('Noah Henchoz', 'Switzerland', 'noah henchoz'),
	('Noah Henchoz', 'Switzerland', 'henchoz'),
	('Johandry Hidalgo', 'Venezuela', 'johandry hidalgo'),
	('Johandry Hidalgo', 'Venezuela', 'hidalgo'),
	('Dylan Boyle', 'Northern Ireland', 'boyle'),
	('Dylan Boyle', 'Northern Ireland', 'dylan boyle'),
	('Stephen Doherty', 'Republic of Ireland', 'doherty'),
	('Stephen Doherty', 'Republic of Ireland', 'stephen doherty'),
	('Jack Madelin', 'Wales', 'jack madelin'),
	('Jack Madelin', 'Wales', 'madelin'),
	('Ma Defu', 'China PR', 'defu'),
	('Ma Defu', 'China PR', 'ma defu'),
	('Wang Zhifeng', 'China PR', 'wang zhifeng'),
	('Wang Zhifeng', 'China PR', 'zhifeng'),
	('Junior Luamba', 'England', 'luamba'),
	('Junior Luamba', 'England', 'junior luamba'),
	('Calem Nieuwenhof', 'Australia', 'nieuwenhof'),
	('Calem Nieuwenhof', 'Australia', 'calem nieuwenhof'),
	('Roger Murillo', 'Colombia', 'roger murillo'),
	('Roger Murillo', 'Colombia', 'murillo'),
	('Emil Hellman', 'Sweden', 'emil hellman'),
	('Emil Hellman', 'Sweden', 'hellman'),
	('Ayoub Assal', 'England', 'assal'),
	('Ayoub Assal', 'England', 'ayoub assal'),
	('Wen Yongjun', 'China PR', 'wen yongjun'),
	('Wen Yongjun', 'China PR', 'yongjun'),
	('Yerson Mosquera', 'Colombia', 'mosquera'),
	('Yerson Mosquera', 'Colombia', 'yerson mosquera'),
	('Joaquín Gutiérrez', 'Chile', 'joaquin gutierrez'),
	('Joaquín Gutiérrez', 'Chile', 'gutierrez'),
	('Shayden Morris', 'England', 'morris'),
	('Shayden Morris', 'England', 'shayden morris'),
	('Jack Lemoignan', 'Northern Ireland', 'lemoignan'),
	('Jack Lemoignan', 'Northern Ireland', 'jack lemoignan'),
	('Wen Da', 'China PR', 'wen da'),
	('Wen Da', 'China PR', 'da'),
	('Massimo Giamattei', 'England', 'massimo giamattei'),
	('Massimo Giamattei', 'England', 'giamattei'),
	('Cha Oh Yeon', 'Korea Republic', 'cha oh yeon'),
	('Cha Oh Yeon', 'Korea Republic', 'yeon'),
	('José Mulato', 'Colombia', 'mulato'),
	('José Mulato', 'Colombia', 'jose mulato'),
	('Kim Ki Yeol', 'Korea Republic', 'yeol'),
	('Kim Ki Yeol', 'Korea Republic', 'kim ki yeol'),
	('Jake O''Brien', 'Republic of Ireland', 'obrien'),
	('Jake O''Brien', 'Republic of Ireland', 'jake obrien'),
	('Promise Omochere', 'Republic of Ireland', 'promise omochere'),
	('Promise Omochere', 'Republic of Ireland', 'omochere'),
	('Jamie Armstrong', 'Scotland', 'jamie armstrong'),
	('Jamie Armstrong', 'Scotland', 'armstrong'),
	('Mackye Townsend-West', 'England', 'townsendwest'),
	('Mackye Townsend-West', 'England', 'mackye townsendwest'),
	('Samuel Cartwright', 'England', 'cartwright'),
	('Samuel Cartwright', 'England', 'samuel cartwright'),
	('Lido Lotefa', 'DR Congo', 'lido lotefa'),
	('Lido Lotefa', 'DR Congo', 'lotefa'),
	('Lewis Bell', 'England', 'lewis bell'),
	('Lewis Bell', 'England', 'bell'),
	('Mike Nzongong', 'Republic of Ireland', 'nzongong'),
	('Mike Nzongong', 'Republic of Ireland', 'mike nzongong'),
	('Zhang Yu', 'China PR', 'yu'),
	('Zhang Yu', 'China PR', 'zhang yu'),
	('Yhonatan Murgas', 'Colombia', 'murgas'),
	('Yhonatan Murgas', 'Colombia', 'yhonatan murgas'),
	('Zang Yifeng', 'China PR', 'yifeng'),
	('Zang Yifeng', 'China PR', 'zang yifeng'),
	('Zhu Jiahao', 'China PR', 'zhu jiahao'),
	('Zhu Jiahao', 'China PR', 'jiahao'),
	('Danila Bokov', 'Russia', 'bokov'),
	('Danila Bokov', 'Russia', 'danila bokov'),
	('Kieran Farren', 'Republic of Ireland', 'kieran farren'),
	('Kieran Farren', 'Republic of Ireland', 'farren'),
	('Lewis Simper', 'England', 'simper'),
	('Lewis Simper', 'England', 'lewis simper'),
	('Malcolm Stolt', 'Sweden', 'stolt'),
	('Malcolm Stolt', 'Sweden', 'malcolm stolt'),
	('Félix Imanol Cárdenas', 'Bolivia', 'felix imanol cardenas'),
	('Félix Imanol Cárdenas', 'Bolivia', 'cardenas'),
	('Raphael Borges Rodrigues', 'Australia', 'raphael borges rodrigues'),
	('Raphael Borges Rodrigues', 'Australia', 'rodrigues'),
	('Morgan Roberts', 'England', 'morgan roberts'),
	('Morgan Roberts', 'England', 'roberts'),
	('Justin Haak', 'United States', 'justin haak'),
	('Justin Haak', 'United States', 'haak'),
	('Fabián Ángel', 'Colombia', 'angel'),
	('Fabián Ángel', 'Colombia', 'fabian angel'),
	('Kyle Hayde', 'England', 'kyle hayde'),
	('Kyle Hayde', 'England', 'hayde'),
	('Sam Booth', 'England', 'booth'),
	('Sam Booth', 'England', 'sam booth'),
	('Maxim Gresler', 'Germany', 'maxim gresler'),
	('Maxim Gresler', 'Germany', 'gresler'),
	('Marco Mannhardt', 'Germany', 'mannhardt'),
	('Marco Mannhardt', 'Germany', 'marco mannhardt'),
	('Jake Davidson', 'Scotland', 'jake davidson'),
	('Jake Davidson', 'Scotland', 'davidson'),
	('Harrison Burrows', 'England', 'burrows'),
	('Harrison Burrows', 'England', 'harrison burrows'),
	('Mackenzie Chapman', 'England', 'mackenzie chapman'),
	('Mackenzie Chapman', 'England', 'chapman'),
	('Myung Se Jin', 'Korea Republic', 'jin'),
	('Myung Se Jin', 'Korea Republic', 'myung se jin'),
	('Jeong Ji Yong', 'Korea Republic', 'jeong ji yong'),
	('Jeong Ji Yong', 'Korea Republic', 'yong'),
	('Michael Harris', 'Republic of Ireland', 'harris'),
	('Michael Harris', 'Republic of Ireland', 'michael harris'),
	('Alou Kuol', 'South Sudan', 'alou kuol'),
	('Alou Kuol', 'South Sudan', 'kuol'),
	('Chen-Zeng Tailang', 'China PR', 'tailang'),
	('Chen-Zeng Tailang', 'China PR', 'chenzeng tailang'),
	('Memet Abdulla Ezmat', 'China PR', 'memet abdulla ezmat'),
	('Memet Abdulla Ezmat', 'China PR', 'ezmat'),
	('Gao Xiang', 'China PR', 'xiang'),
	('Gao Xiang', 'China PR', 'gao xiang'),
	('Liam Munther', 'Sweden', 'munther'),
	('Liam Munther', 'Sweden', 'liam munther'),
	('Hannes Sveijer', 'Sweden', 'hannes sveijer'),
	('Hannes Sveijer', 'Sweden', 'sveijer'),
	('Li Xuebo', 'China PR', 'xuebo'),
	('Li Xuebo', 'China PR', 'li xuebo'),
	('Gian Marco Crespi', 'Italy', 'gian marco crespi'),
	('Gian Marco Crespi', 'Italy', 'crespi'),
	('Nelson Iseguan', 'England', 'nelson iseguan'),
	('Nelson Iseguan', 'England', 'iseguan'),
	('Cheng Hui', 'China PR', 'cheng hui'),
	('Cheng Hui', 'China PR', 'hui'),
	('Ricardo Dinanga', 'Republic of Ireland', 'ricardo dinanga'),
	('Ricardo Dinanga', 'Republic of Ireland', 'dinanga'),
	('Sebastián Navarro', 'Colombia', 'navarro'),
	('Sebastián Navarro', 'Colombia', 'sebastian navarro'),
	('Song Haiwang', 'China PR', 'haiwang'),
	('Song Haiwang', 'China PR', 'song haiwang'),
	('Seo Min Woo', 'Korea Republic', 'woo'),
	('Seo Min Woo', 'Korea Republic', 'seo min woo'),
	('Darren Collins', 'Republic of Ireland', 'collins'),
	('Darren Collins', 'Republic of Ireland', 'darren collins'),
	('Kevin Fernandez', 'Chile', 'fernandez'),
	('Kevin Fernandez', 'Chile', 'kevin fernandez'),
	('Huang Jiahui', 'China PR', 'huang jiahui'),
	('Huang Jiahui', 'China PR', 'jiahui'),
	('Dylan Aravena', 'Chile', 'aravena'),
	('Dylan Aravena', 'Chile', 'dylan aravena'),
	('Alex Cetiner', 'Republic of Ireland', 'cetiner'),
	('Alex Cetiner', 'Republic of Ireland', 'alex cetiner'),
	('Jack Smith', 'England', 'smith'),
	('Jack Smith', 'England', 'jack smith'),
	('Ethan Espinoza', 'Chile', 'espinoza'),
	('Ethan Espinoza', 'Chile', 'ethan espinoza'),
	('Jack Larkin', 'Republic of Ireland', 'jack larkin'),
	('Jack Larkin', 'Republic of Ireland', 'larkin'),
	('Daniel Luna', 'Colombia', 'luna'),
	('Daniel Luna', 'Colombia', 'daniel luna'),
	('Alex Phelan', 'Republic of Ireland', 'phelan'),
	('Alex Phelan', 'Republic of Ireland', 'alex phelan'),
	('Patrick McGarvey', 'Republic of Ireland', 'patrick mcgarvey'),
	('Patrick McGarvey', 'Republic of Ireland', 'mcgarvey'),
	('Mohammed Al Nakhilan', 'Saudi Arabia', 'mohammed al nakhilan'),
	('Mohammed Al Nakhilan', 'Saudi Arabia', 'nakhilan'),
	('Wang Haijian', 'China PR', 'haijian'),
	('Wang Haijian', 'China PR', 'wang haijian'),
	('Jack Arthur', 'England', 'arthur'),
	('Jack Arthur', 'England', 'jack arthur'),
	('Tan Chun Lok', 'Hong Kong', 'lok'),
	('Tan Chun Lok', 'Hong Kong', 'tan chun lok'),
	('Lan Jingxuan', 'China PR', 'lan jingxuan'),
	('Lan Jingxuan', 'China PR', 'jingxuan'),
	('Guo Yunqi', 'China PR', 'guo yunqi'),
	('Guo Yunqi', 'China PR', 'yunqi'),
	('Miloš Ćoćić', 'Serbia', 'milos cocic'),
	('Miloš Ćoćić', 'Serbia', 'cocic'),
	('James Akintunde', 'England', 'james akintunde'),
	('James Akintunde', 'England', 'akintunde'),
	('Lewys Twamley', 'Wales', 'lewys twamley'),
	('Lewys Twamley', 'Wales', 'twamley'),
	('Liu Chaoyang', 'China PR', 'chaoyang'),
	('Liu Chaoyang', 'China PR', 'liu chaoyang'),
	('Chen Chunxin', 'China PR', 'chunxin'),
	('Chen Chunxin', 'China PR', 'chen chunxin'),
	('Jamie Browne', 'Republic of Ireland', 'jamie browne'),
	('Jamie Browne', 'Republic of Ireland', 'browne'),
	('Laurie Walker', 'England', 'laurie walker'),
	('Laurie Walker', 'England', 'walker'),
	('Hanssel Delgado', 'Ecuador', 'hanssel delgado'),
	('Hanssel Delgado', 'Ecuador', 'delgado'),
	('Shan Huanhuan', 'China PR', 'shan huanhuan'),
	('Shan Huanhuan', 'China PR', 'huanhuan'),
	('Fu Yuncheng', 'China PR', 'yuncheng'),
	('Fu Yuncheng', 'China PR', 'fu yuncheng'),
	('Ma Zhen', 'China PR', 'zhen'),
	('Ma Zhen', 'China PR', 'ma zhen'),
	('Chen Kejiang', 'China PR', 'kejiang'),
	('Chen Kejiang', 'China PR', 'chen kejiang'),
	('Wang Jianwen', 'China PR', 'jianwen'),
	('Wang Jianwen', 'China PR', 'wang jianwen'),
	('Brendon Shabani', 'Albania', 'brendon shabani'),
	('Brendon Shabani', 'Albania', 'shabani'),
	('Jay Bird', 'England', 'bird'),
	('Jay Bird', 'England', 'jay bird'),
	('Laurence Smith', 'England', 'smith'),
	('Laurence Smith', 'England', 'laurence smith'),
	('Liam Waldock', 'England', 'liam waldock'),
	('Liam Waldock', 'England', 'waldock'),
	('Brayan Montaño', 'Colombia', 'brayan montano'),
	('Brayan Montaño', 'Colombia', 'montano'),
	('Liam Ravenhill', 'England', 'ravenhill'),
	('Liam Ravenhill', 'England', 'liam ravenhill'),
	('Reinaldo Fontalvo', 'Colombia', 'reinaldo fontalvo'),
	('Reinaldo Fontalvo', 'Colombia', 'fontalvo'),
	('Chen Zitong', 'China PR', 'chen zitong'),
	('Chen Zitong', 'China PR', 'zitong'),
	('Wang Zhenghao', 'China PR', 'zhenghao'),
	('Wang Zhenghao', 'China PR', 'wang zhenghao'),
	('Zhong Jiyu', 'China PR', 'zhong jiyu'),
	('Zhong Jiyu', 'China PR', 'jiyu'),
	('Huang Wenzhou', 'China PR', 'huang wenzhou'),
	('Huang Wenzhou', 'China PR', 'wenzhou'),
	('Song Yue', 'China PR', 'song yue'),
	('Song Yue', 'China PR', 'yue'),
	('Wang Huapeng', 'China PR', 'huapeng'),
	('Wang Huapeng', 'China PR', 'wang huapeng'),
	('Mateo Flores', 'Bolivia', 'flores'),
	('Mateo Flores', 'Bolivia', 'mateo flores'),
	('Zhang Mengxuan', 'China PR', 'zhang mengxuan'),
	('Zhang Mengxuan', 'China PR', 'mengxuan'),
	('Vani Da Silva', 'England', 'silva'),
	('Vani Da Silva', 'England', 'vani da silva'),
	('Xia Ao', 'China PR', 'ao'),
	('Xia Ao', 'China PR', 'xia ao'),
	('Ben Hough', 'England', 'ben hough'),
	('Ben Hough', 'England', 'hough'),
	('Ronan McKinley', 'England', 'mckinley'),
	('Ronan McKinley', 'England', 'ronan mckinley'),
	('Wang Zhen''ao', 'China PR', 'zhenao'),
	('Wang Zhen''ao', 'China PR', 'wang zhenao'),
	('Zhou Xiao', 'China PR', 'xiao'),
	('Zhou Xiao', 'China PR', 'zhou xiao')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';