INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Miquel Scarlett', 'England', 'player'),
	('Liao Chengjian', 'China PR', 'player'),
	('Andy Winter', 'Scotland', 'player'),
	('Yutaro Oda', 'Japan', 'player'),
	('Ángel Azurín', 'Peru', 'player'),
	('Noah James', 'Australia', 'player'),
	('Stéphane Cueni', 'Switzerland', 'player'),
	('Warren Kamanzi', 'Norway', 'player'),
	('Edgardo Rondón', 'Venezuela', 'player'),
	('Douglas Julio', 'Venezuela', 'player'),
	('John Martin', 'Republic of Ireland', 'player'),
	('Prince Isaac Kouame', 'Sweden', 'player'),
	('Elliot Bonds', 'Guyana', 'player'),
	('José Martínez', 'Bolivia', 'player'),
	('Liu Le', 'China PR', 'player'),
	('Marcelo Suárez', 'Chile', 'player'),
	('Hassan Vergara', 'Colombia', 'player'),
	('David Barreto', 'Venezuela', 'player'),
	('Yang Fan', 'China PR', 'player'),
	('Daniel Dietze', 'Paraguay', 'player'),
	('Min Kyung Hyun', 'Korea Republic', 'player'),
	('Edgar José Silva', 'Venezuela', 'player'),
	('Magnus Anbo', 'Denmark', 'player'),
	('Ted Tattermusch', 'Germany', 'player'),
	('Davide Zappella', 'Italy', 'player'),
	('Atakan Çankaya', 'Turkey', 'player'),
	('Klaidi Lolos', 'Greece', 'player'),
	('Kevin Ibrahim', 'Germany', 'player'),
	('Ben Bischof', 'Germany', 'player'),
	('Kevin Ferreyra', 'Peru', 'player'),
	('Muhannad Al Qaydhi', 'Saudi Arabia', 'player'),
	('Teddy Jenks', 'England', 'player'),
	('Jasper Moon', 'England', 'player'),
	('Nelson Abbey', 'England', 'player'),
	('Rasmus Sandberg', 'Norway', 'player'),
	('Rasmus Cronvall', 'Sweden', 'player'),
	('Chen Jie', 'China PR', 'player'),
	('Jeriel De Santis', 'Venezuela', 'player'),
	('Hans Christian Bernat', 'Denmark', 'player'),
	('Javier Ajenjo Hyjek', 'Poland', 'player'),
	('Will Longbottom', 'England', 'player'),
	('Jack Malone', 'Northern Ireland', 'player'),
	('Alexander Höck', 'Germany', 'player'),
	('Ryan De Vries', 'New Zealand', 'player'),
	('Mads Hansen', 'Denmark', 'player'),
	('Luis Gamíz', 'Mexico', 'player'),
	('Johann Lepenant', 'France', 'player'),
	('Fernando Souza', 'Uruguay', 'player'),
	('Loup Hervieu', 'France', 'player'),
	('Lee Ki Woon', 'Korea Republic', 'player'),
	('Dylan Nealis', 'United States', 'player'),
	('Lorik Ademi', 'Sweden', 'player'),
	('John Pulskamp', 'United States', 'player'),
	('Abdulelah Al Shammari', 'Saudi Arabia', 'player'),
	('Noel Törnqvist', 'Sweden', 'player'),
	('Zhou Xin', 'China PR', 'player'),
	('Jake Turner', 'England', 'player'),
	('Niclas Bergmark', 'Sweden', 'player'),
	('Joe Cracknell', 'England', 'player'),
	('Will Vint', 'United States', 'player'),
	('Yamato Wakatsuki', 'Japan', 'player'),
	('Vladimir Prijović', 'Serbia', 'player'),
	('Luca Lombardi', 'Italy', 'player'),
	('Ye Chugui', 'China PR', 'player'),
	('Lucio Soldini', 'Switzerland', 'player'),
	('Niels Grevink', 'Netherlands', 'player'),
	('Scott Moloney', 'England', 'player'),
	('Brian Galach', 'Poland', 'player'),
	('Hamad Al Abdan', 'Saudi Arabia', 'player'),
	('Cameron Hargreaves', 'England', 'player'),
	('Aldo Mota', 'Mexico', 'player'),
	('Tyler Wolff', 'United States', 'player'),
	('Tyler French', 'England', 'player'),
	('Alejandro Andrade', 'Mexico', 'player'),
	('Joaquín Hass', 'Argentina', 'player'),
	('Junior Quiñonez', 'Paraguay', 'player'),
	('Dylan Dassy', 'Belgium', 'player'),
	('Cui Ming''an', 'China PR', 'player'),
	('Linus Tagesson', 'Sweden', 'player'),
	('Bryan García', 'Ecuador', 'player'),
	('Jesper Granlund', 'Norway', 'player'),
	('Yago Gomes', 'Brazil', 'player'),
	('Tom Kretzschmar', 'Germany', 'player'),
	('Liu Shibo', 'China PR', 'player'),
	('Abdullah Al Beladi', 'Saudi Arabia', 'player'),
	('Jhoanner Chávez', 'Ecuador', 'player'),
	('Eric Lopez', 'United States', 'player'),
	('Juan José Parra', 'Colombia', 'player'),
	('Chris Mochrie', 'Scotland', 'player'),
	('Hamad Hawsawi', 'Saudi Arabia', 'player'),
	('Malthe Højholt', 'Denmark', 'player'),
	('Sebastián Valenzuela', 'Colombia', 'player'),
	('Sam Fielding', 'England', 'player'),
	('Timothy Fayulu', 'DR Congo', 'player'),
	('Mattia Felici', 'Italy', 'player'),
	('Edgar André', 'Switzerland', 'player'),
	('Tim Linsbichler', 'Austria', 'player'),
	('James Waite', 'Wales', 'player'),
	('Denis Hrezdac', 'Romania', 'player'),
	('Pyry Hannola', 'Finland', 'player'),
	('Kane O''Connor', 'Scotland', 'player'),
	('Yared Abetew', 'Ethiopia', 'player'),
	('Jake Scrimshaw', 'England', 'player'),
	('Ronnie Edwards', 'England', 'player'),
	('Marius Köhl', 'Germany', 'player'),
	('Dan Ward', 'England', 'player'),
	('Tom Billson', 'England', 'player'),
	('Jeppe Pedersen', 'Denmark', 'player'),
	('Archie Davies', 'England', 'player'),
	('Zac Jones', 'New Zealand', 'player'),
	('Frank Bamenye', 'Norway', 'player'),
	('Kajetan Szmyt', 'Poland', 'player'),
	('Carlo Pignatiello', 'Scotland', 'player'),
	('Luis Sanchez', 'Colombia', 'player'),
	('Gustav Helling', 'Norway', 'player'),
	('Paul Oșan', 'Romania', 'player'),
	('Kristoffer Khazeni', 'Sweden', 'player'),
	('Albian Hajdari', 'Switzerland', 'player'),
	('Griffin Yow', 'United States', 'player'),
	('Gustavo Galindo', 'Mexico', 'player'),
	('Filston Mawana', 'Sweden', 'player'),
	('Brayan Córdoba', 'Colombia', 'player'),
	('Joe Bateman', 'England', 'player'),
	('Wen Tianpeng', 'China PR', 'player'),
	('Daniel Bowry', 'Antigua & Barbuda', 'player'),
	('Ryley Towler', 'England', 'player'),
	('Chris-Vianney Goteni', 'France', 'player'),
	('Tomson Minda', 'Ecuador', 'player'),
	('Mohamed Traore', 'Senegal', 'player'),
	('Mohammad Al Burayh', 'Saudi Arabia', 'player'),
	('Jack Newman', 'Scotland', 'player'),
	('Agustín Alfaro', 'Uruguay', 'player'),
	('Xu Jiamin', 'China PR', 'player'),
	('Morgan Penfold', 'England', 'player'),
	('Matthew Weaire', 'Denmark', 'player'),
	('Julian Dunn', 'Canada', 'player'),
	('Samuel Kasongo', 'Switzerland', 'player'),
	('Cristian Măgerușan', 'Romania', 'player'),
	('Kreshnik Krasniqi', 'Kosovo', 'player'),
	('Cole Turner', 'United States', 'player'),
	('Jorge Sikora', 'Poland', 'player'),
	('Kwon Jae Beom', 'Korea Republic', 'player'),
	('Wen Jiabao', 'China PR', 'player'),
	('Maximiliano Rodríguez Vejar', 'Chile', 'player'),
	('Bartosz Neugebauer', 'Poland', 'player'),
	('Paul Grave', 'Germany', 'player'),
	('Carlos Salomón', 'Chile', 'player'),
	('Oliver Bundgaard', 'Denmark', 'player'),
	('Tician Tushi', 'Switzerland', 'player'),
	('Szymon Lewkot', 'Poland', 'player'),
	('Arthur Lyska', 'Germany', 'player'),
	('James Vennings', 'England', 'player'),
	('Cameron Duke', 'United States', 'player'),
	('Hwang In Jae', 'Korea Republic', 'player'),
	('Teddy Sharman-Lowe', 'England', 'player'),
	('Sondre Auklend', 'Norway', 'player'),
	('Will Dean', 'England', 'player'),
	('Jesper Tolinsson', 'Sweden', 'player'),
	('Josh Gould', 'Wales', 'player'),
	('Jarvis Cleal', 'England', 'player'),
	('Ricardo Pepi', 'United States', 'player'),
	('Hubert Turski', 'Poland', 'player'),
	('Marcel Wędrychowski', 'Poland', 'player'),
	('Akira Yoshida', 'Japan', 'player'),
	('Melker Jonsson', 'Sweden', 'player'),
	('Malek Al Abdulmunem', 'Saudi Arabia', 'player'),
	('Essam Al Muwallad', 'Saudi Arabia', 'player'),
	('Thomas Oluwa', 'Republic of Ireland', 'player'),
	('Harry Kite', 'England', 'player'),
	('Juan Ferrufino', 'Bolivia', 'player'),
	('Mateusz Pieńczak', 'Poland', 'player'),
	('Mathias Nilsson', 'Sweden', 'player'),
	('Mark Gallagher', 'England', 'player'),
	('Joe Adams', 'Wales', 'player'),
	('Elliot Panicco', 'United States', 'player'),
	('Michael Elechi', 'England', 'player'),
	('Jalen Hawkins', 'United States', 'player'),
	('Marcus Andersen', 'Norway', 'player'),
	('Luke Haakenson', 'United States', 'player'),
	('Hidetoshi Takeda', 'Japan', 'player'),
	('Umut Ünlü', 'Germany', 'player'),
	('Danny Finlayson', 'Northern Ireland', 'player'),
	('Tom McGill', 'England', 'player'),
	('Joel Randall', 'England', 'player'),
	('Horenus Tadesse', 'Norway', 'player'),
	('Alec Byrne', 'Republic of Ireland', 'player'),
	('Guo Jing', 'China PR', 'player'),
	('Mikkel Lassen', 'Denmark', 'player'),
	('Yang Yiming', 'China PR', 'player'),
	('Florjan Seferaj', 'Switzerland', 'player'),
	('Gustavo Gutiérrez', 'Mexico', 'player'),
	('Kyle Gourlay', 'Scotland', 'player'),
	('Curtis Lyle', 'Scotland', 'player'),
	('Bradley Webb', 'England', 'player'),
	('Connor Malley', 'England', 'player'),
	('Rareș Pop', 'Romania', 'player'),
	('Moataz Al Baqawi', 'Saudi Arabia', 'player'),
	('Yao Jiangshan', 'China PR', 'player'),
	('Alexander Abrahamsson', 'Sweden', 'player'),
	('George Buliga', 'Romania', 'player'),
	('Haitham Asiri', 'Saudi Arabia', 'player'),
	('Gilbert Fuentes', 'United States', 'player'),
	('Fredrik Repstad Hansen', 'Norway', 'player'),
	('Sondre Skogen', 'Norway', 'player'),
	('Elies Mahmoud', 'France', 'player'),
	('Ardon Jashari', 'Switzerland', 'player'),
	('Grant Horton', 'England', 'player'),
	('Solomon Brynn', 'England', 'player'),
	('Dean Williams', 'Republic of Ireland', 'player'),
	('Owen Windsor', 'England', 'player'),
	('Chen Kerui', 'China PR', 'player'),
	('Reuben Duncan', 'England', 'player'),
	('Eirik Asante Gayi', 'Norway', 'player'),
	('Gareth Harkin', 'Republic of Ireland', 'player'),
	('Kim Yeon Soo', 'Korea Republic', 'player'),
	('Andreas Endresen', 'Norway', 'player'),
	('Denilson Ovando', 'Ecuador', 'player'),
	('Xie Weijun', 'China PR', 'player'),
	('Lee Ji Yong', 'Korea Republic', 'player'),
	('Luis Fernandez', 'England', 'player'),
	('Jin Bo', 'China PR', 'player'),
	('George Hornshaw', 'England', 'player'),
	('Leandro Finochietto', 'Argentina', 'player'),
	('Liu Jing', 'China PR', 'player'),
	('Nicolas Vouilloz', 'Switzerland', 'player'),
	('Lucas Cueva', 'Ecuador', 'player'),
	('Alexander Hjælmhof', 'Denmark', 'player'),
	('Kai Meriluoto', 'Finland', 'player'),
	('Paul Bourdelle', 'France', 'player'),
	('Juan José Uribe', 'Colombia', 'player'),
	('Tiago Galletto', 'Uruguay', 'player'),
	('Daniel Andersen', 'Denmark', 'player'),
	('Tristan Prendergast', 'Australia', 'player'),
	('Jiang Zilei', 'China PR', 'player'),
	('Adam Senior', 'England', 'player'),
	('Park Gwan Woo', 'Korea Republic', 'player'),
	('Thomas Christiansen', 'Denmark', 'player'),
	('Siriky Sanogo', 'Ivory Coast', 'player'),
	('Tommaso Fantacci', 'Italy', 'player'),
	('Monther Al Nakhli', 'Saudi Arabia', 'player'),
	('Tivonge Rushesha', 'Wales', 'player'),
	('Yan Zihao', 'China PR', 'player'),
	('Jiang Weipeng', 'China PR', 'player'),
	('Wilbert Hernández', 'Venezuela', 'player'),
	('Lewis Richards', 'Republic of Ireland', 'player'),
	('Rakan Al Najjar', 'Saudi Arabia', 'player'),
	('Kostandinos Grozos', 'Australia', 'player'),
	('Lino Lang', 'Switzerland', 'player'),
	('Díver Torres', 'Venezuela', 'player'),
	('Zhang Wentao', 'China PR', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Miquel Scarlett', 'England', 'miquel scarlett'),
	('Miquel Scarlett', 'England', 'scarlett'),
	('Liao Chengjian', 'China PR', 'chengjian'),
	('Liao Chengjian', 'China PR', 'liao chengjian'),
	('Andy Winter', 'Scotland', 'andy winter'),
	('Andy Winter', 'Scotland', 'winter'),
	('Yutaro Oda', 'Japan', 'yutaro oda'),
	('Yutaro Oda', 'Japan', 'oda'),
	('Ángel Azurín', 'Peru', 'angel azurin'),
	('Ángel Azurín', 'Peru', 'azurin'),
	('Noah James', 'Australia', 'noah james'),
	('Noah James', 'Australia', 'james'),
	('Stéphane Cueni', 'Switzerland', 'cueni'),
	('Stéphane Cueni', 'Switzerland', 'stephane cueni'),
	('Warren Kamanzi', 'Norway', 'warren kamanzi'),
	('Warren Kamanzi', 'Norway', 'kamanzi'),
	('Edgardo Rondón', 'Venezuela', 'rondon'),
	('Edgardo Rondón', 'Venezuela', 'edgardo rondon'),
	('Douglas Julio', 'Venezuela', 'julio'),
	('Douglas Julio', 'Venezuela', 'douglas julio'),
	('John Martin', 'Republic of Ireland', 'john martin'),
	('John Martin', 'Republic of Ireland', 'martin'),
	('Prince Isaac Kouame', 'Sweden', 'kouame'),
	('Prince Isaac Kouame', 'Sweden', 'prince isaac kouame'),
	('Elliot Bonds', 'Guyana', 'bonds'),
	('Elliot Bonds', 'Guyana', 'elliot bonds'),
	('José Martínez', 'Bolivia', 'jose martinez'),
	('José Martínez', 'Bolivia', 'martinez'),
	('Liu Le', 'China PR', 'liu le'),
	('Liu Le', 'China PR', 'le'),
	('Marcelo Suárez', 'Chile', 'suarez'),
	('Marcelo Suárez', 'Chile', 'marcelo suarez'),
	('Hassan Vergara', 'Colombia', 'hassan vergara'),
	('Hassan Vergara', 'Colombia', 'vergara'),
	('David Barreto', 'Venezuela', 'david barreto'),
	('David Barreto', 'Venezuela', 'barreto'),
	('Yang Fan', 'China PR', 'yang fan'),
	('Yang Fan', 'China PR', 'fan'),
	('Daniel Dietze', 'Paraguay', 'dietze'),
	('Daniel Dietze', 'Paraguay', 'daniel dietze'),
	('Min Kyung Hyun', 'Korea Republic', 'hyun'),
	('Min Kyung Hyun', 'Korea Republic', 'min kyung hyun'),
	('Edgar José Silva', 'Venezuela', 'edgar jose silva'),
	('Edgar José Silva', 'Venezuela', 'silva'),
	('Magnus Anbo', 'Denmark', 'anbo'),
	('Magnus Anbo', 'Denmark', 'magnus anbo'),
	('Ted Tattermusch', 'Germany', 'tattermusch'),
	('Ted Tattermusch', 'Germany', 'ted tattermusch'),
	('Davide Zappella', 'Italy', 'davide zappella'),
	('Davide Zappella', 'Italy', 'zappella'),
	('Atakan Çankaya', 'Turkey', 'cankaya'),
	('Atakan Çankaya', 'Turkey', 'atakan cankaya'),
	('Klaidi Lolos', 'Greece', 'lolos'),
	('Klaidi Lolos', 'Greece', 'klaidi lolos'),
	('Kevin Ibrahim', 'Germany', 'ibrahim'),
	('Kevin Ibrahim', 'Germany', 'kevin ibrahim'),
	('Ben Bischof', 'Germany', 'bischof'),
	('Ben Bischof', 'Germany', 'ben bischof'),
	('Kevin Ferreyra', 'Peru', 'ferreyra'),
	('Kevin Ferreyra', 'Peru', 'kevin ferreyra'),
	('Muhannad Al Qaydhi', 'Saudi Arabia', 'qaydhi'),
	('Muhannad Al Qaydhi', 'Saudi Arabia', 'muhannad al qaydhi'),
	('Teddy Jenks', 'England', 'teddy jenks'),
	('Teddy Jenks', 'England', 'jenks'),
	('Jasper Moon', 'England', 'jasper moon'),
	('Jasper Moon', 'England', 'moon'),
	('Nelson Abbey', 'England', 'nelson abbey'),
	('Nelson Abbey', 'England', 'abbey'),
	('Rasmus Sandberg', 'Norway', 'sandberg'),
	('Rasmus Sandberg', 'Norway', 'rasmus sandberg'),
	('Rasmus Cronvall', 'Sweden', 'cronvall'),
	('Rasmus Cronvall', 'Sweden', 'rasmus cronvall'),
	('Chen Jie', 'China PR', 'jie'),
	('Chen Jie', 'China PR', 'chen jie'),
	('Jeriel De Santis', 'Venezuela', 'santis'),
	('Jeriel De Santis', 'Venezuela', 'jeriel de santis'),
	('Hans Christian Bernat', 'Denmark', 'bernat'),
	('Hans Christian Bernat', 'Denmark', 'hans christian bernat'),
	('Javier Ajenjo Hyjek', 'Poland', 'javier ajenjo hyjek'),
	('Javier Ajenjo Hyjek', 'Poland', 'hyjek'),
	('Will Longbottom', 'England', 'will longbottom'),
	('Will Longbottom', 'England', 'longbottom'),
	('Jack Malone', 'Northern Ireland', 'jack malone'),
	('Jack Malone', 'Northern Ireland', 'malone'),
	('Alexander Höck', 'Germany', 'alexander hock'),
	('Alexander Höck', 'Germany', 'hock'),
	('Ryan De Vries', 'New Zealand', 'vries'),
	('Ryan De Vries', 'New Zealand', 'ryan de vries'),
	('Mads Hansen', 'Denmark', 'hansen'),
	('Mads Hansen', 'Denmark', 'mads hansen'),
	('Luis Gamíz', 'Mexico', 'gamiz'),
	('Luis Gamíz', 'Mexico', 'luis gamiz'),
	('Johann Lepenant', 'France', 'lepenant'),
	('Johann Lepenant', 'France', 'johann lepenant'),
	('Fernando Souza', 'Uruguay', 'souza'),
	('Fernando Souza', 'Uruguay', 'fernando souza'),
	('Loup Hervieu', 'France', 'loup hervieu'),
	('Loup Hervieu', 'France', 'hervieu'),
	('Lee Ki Woon', 'Korea Republic', 'woon'),
	('Lee Ki Woon', 'Korea Republic', 'lee ki woon'),
	('Dylan Nealis', 'United States', 'dylan nealis'),
	('Dylan Nealis', 'United States', 'nealis'),
	('Lorik Ademi', 'Sweden', 'lorik ademi'),
	('Lorik Ademi', 'Sweden', 'ademi'),
	('John Pulskamp', 'United States', 'pulskamp'),
	('John Pulskamp', 'United States', 'john pulskamp'),
	('Abdulelah Al Shammari', 'Saudi Arabia', 'abdulelah al shammari'),
	('Abdulelah Al Shammari', 'Saudi Arabia', 'shammari'),
	('Noel Törnqvist', 'Sweden', 'tornqvist'),
	('Noel Törnqvist', 'Sweden', 'noel tornqvist'),
	('Zhou Xin', 'China PR', 'xin'),
	('Zhou Xin', 'China PR', 'zhou xin'),
	('Jake Turner', 'England', 'turner'),
	('Jake Turner', 'England', 'jake turner'),
	('Niclas Bergmark', 'Sweden', 'niclas bergmark'),
	('Niclas Bergmark', 'Sweden', 'bergmark'),
	('Joe Cracknell', 'England', 'cracknell'),
	('Joe Cracknell', 'England', 'joe cracknell'),
	('Will Vint', 'United States', 'vint'),
	('Will Vint', 'United States', 'will vint'),
	('Yamato Wakatsuki', 'Japan', 'wakatsuki'),
	('Yamato Wakatsuki', 'Japan', 'yamato wakatsuki'),
	('Vladimir Prijović', 'Serbia', 'prijovic'),
	('Vladimir Prijović', 'Serbia', 'vladimir prijovic'),
	('Luca Lombardi', 'Italy', 'luca lombardi'),
	('Luca Lombardi', 'Italy', 'lombardi'),
	('Ye Chugui', 'China PR', 'ye chugui'),
	('Ye Chugui', 'China PR', 'chugui'),
	('Lucio Soldini', 'Switzerland', 'soldini'),
	('Lucio Soldini', 'Switzerland', 'lucio soldini'),
	('Niels Grevink', 'Netherlands', 'niels grevink'),
	('Niels Grevink', 'Netherlands', 'grevink'),
	('Scott Moloney', 'England', 'moloney'),
	('Scott Moloney', 'England', 'scott moloney'),
	('Brian Galach', 'Poland', 'galach'),
	('Brian Galach', 'Poland', 'brian galach'),
	('Hamad Al Abdan', 'Saudi Arabia', 'abdan'),
	('Hamad Al Abdan', 'Saudi Arabia', 'hamad al abdan'),
	('Cameron Hargreaves', 'England', 'hargreaves'),
	('Cameron Hargreaves', 'England', 'cameron hargreaves'),
	('Aldo Mota', 'Mexico', 'aldo mota'),
	('Aldo Mota', 'Mexico', 'mota'),
	('Tyler Wolff', 'United States', 'wolff'),
	('Tyler Wolff', 'United States', 'tyler wolff'),
	('Tyler French', 'England', 'french'),
	('Tyler French', 'England', 'tyler french'),
	('Alejandro Andrade', 'Mexico', 'andrade'),
	('Alejandro Andrade', 'Mexico', 'alejandro andrade'),
	('Joaquín Hass', 'Argentina', 'joaquin hass'),
	('Joaquín Hass', 'Argentina', 'hass'),
	('Junior Quiñonez', 'Paraguay', 'quinonez'),
	('Junior Quiñonez', 'Paraguay', 'junior quinonez'),
	('Dylan Dassy', 'Belgium', 'dylan dassy'),
	('Dylan Dassy', 'Belgium', 'dassy'),
	('Cui Ming''an', 'China PR', 'mingan'),
	('Cui Ming''an', 'China PR', 'cui mingan'),
	('Linus Tagesson', 'Sweden', 'linus tagesson'),
	('Linus Tagesson', 'Sweden', 'tagesson'),
	('Bryan García', 'Ecuador', 'garcia'),
	('Bryan García', 'Ecuador', 'bryan garcia'),
	('Jesper Granlund', 'Norway', 'jesper granlund'),
	('Jesper Granlund', 'Norway', 'granlund'),
	('Yago Gomes', 'Brazil', 'yago gomes'),
	('Yago Gomes', 'Brazil', 'gomes'),
	('Tom Kretzschmar', 'Germany', 'tom kretzschmar'),
	('Tom Kretzschmar', 'Germany', 'kretzschmar'),
	('Liu Shibo', 'China PR', 'shibo'),
	('Liu Shibo', 'China PR', 'liu shibo'),
	('Abdullah Al Beladi', 'Saudi Arabia', 'abdullah al beladi'),
	('Abdullah Al Beladi', 'Saudi Arabia', 'beladi'),
	('Jhoanner Chávez', 'Ecuador', 'jhoanner chavez'),
	('Jhoanner Chávez', 'Ecuador', 'chavez'),
	('Eric Lopez', 'United States', 'lopez'),
	('Eric Lopez', 'United States', 'eric lopez'),
	('Juan José Parra', 'Colombia', 'juan jose parra'),
	('Juan José Parra', 'Colombia', 'parra'),
	('Chris Mochrie', 'Scotland', 'chris mochrie'),
	('Chris Mochrie', 'Scotland', 'mochrie'),
	('Hamad Hawsawi', 'Saudi Arabia', 'hawsawi'),
	('Hamad Hawsawi', 'Saudi Arabia', 'hamad hawsawi'),
	('Malthe Højholt', 'Denmark', 'malthe hjholt'),
	('Malthe Højholt', 'Denmark', 'hjholt'),
	('Sebastián Valenzuela', 'Colombia', 'sebastian valenzuela'),
	('Sebastián Valenzuela', 'Colombia', 'valenzuela'),
	('Sam Fielding', 'England', 'sam fielding'),
	('Sam Fielding', 'England', 'fielding'),
	('Timothy Fayulu', 'DR Congo', 'fayulu'),
	('Timothy Fayulu', 'DR Congo', 'timothy fayulu'),
	('Mattia Felici', 'Italy', 'felici'),
	('Mattia Felici', 'Italy', 'mattia felici'),
	('Edgar André', 'Switzerland', 'andre'),
	('Edgar André', 'Switzerland', 'edgar andre'),
	('Tim Linsbichler', 'Austria', 'linsbichler'),
	('Tim Linsbichler', 'Austria', 'tim linsbichler'),
	('James Waite', 'Wales', 'waite'),
	('James Waite', 'Wales', 'james waite'),
	('Denis Hrezdac', 'Romania', 'denis hrezdac'),
	('Denis Hrezdac', 'Romania', 'hrezdac'),
	('Pyry Hannola', 'Finland', 'pyry hannola'),
	('Pyry Hannola', 'Finland', 'hannola'),
	('Kane O''Connor', 'Scotland', 'kane oconnor'),
	('Kane O''Connor', 'Scotland', 'oconnor'),
	('Yared Abetew', 'Ethiopia', 'yared abetew'),
	('Yared Abetew', 'Ethiopia', 'abetew'),
	('Jake Scrimshaw', 'England', 'scrimshaw'),
	('Jake Scrimshaw', 'England', 'jake scrimshaw'),
	('Ronnie Edwards', 'England', 'ronnie edwards'),
	('Ronnie Edwards', 'England', 'edwards'),
	('Marius Köhl', 'Germany', 'kohl'),
	('Marius Köhl', 'Germany', 'marius kohl'),
	('Dan Ward', 'England', 'ward'),
	('Dan Ward', 'England', 'dan ward'),
	('Tom Billson', 'England', 'billson'),
	('Tom Billson', 'England', 'tom billson'),
	('Jeppe Pedersen', 'Denmark', 'jeppe pedersen'),
	('Jeppe Pedersen', 'Denmark', 'pedersen'),
	('Archie Davies', 'England', 'davies'),
	('Archie Davies', 'England', 'archie davies'),
	('Zac Jones', 'New Zealand', 'jones'),
	('Zac Jones', 'New Zealand', 'zac jones'),
	('Frank Bamenye', 'Norway', 'bamenye'),
	('Frank Bamenye', 'Norway', 'frank bamenye'),
	('Kajetan Szmyt', 'Poland', 'szmyt'),
	('Kajetan Szmyt', 'Poland', 'kajetan szmyt'),
	('Carlo Pignatiello', 'Scotland', 'pignatiello'),
	('Carlo Pignatiello', 'Scotland', 'carlo pignatiello'),
	('Luis Sanchez', 'Colombia', 'sanchez'),
	('Luis Sanchez', 'Colombia', 'luis sanchez'),
	('Gustav Helling', 'Norway', 'helling'),
	('Gustav Helling', 'Norway', 'gustav helling'),
	('Paul Oșan', 'Romania', 'paul osan'),
	('Paul Oșan', 'Romania', 'osan'),
	('Kristoffer Khazeni', 'Sweden', 'kristoffer khazeni'),
	('Kristoffer Khazeni', 'Sweden', 'khazeni'),
	('Albian Hajdari', 'Switzerland', 'albian hajdari'),
	('Albian Hajdari', 'Switzerland', 'hajdari'),
	('Griffin Yow', 'United States', 'yow'),
	('Griffin Yow', 'United States', 'griffin yow'),
	('Gustavo Galindo', 'Mexico', 'galindo'),
	('Gustavo Galindo', 'Mexico', 'gustavo galindo'),
	('Filston Mawana', 'Sweden', 'mawana'),
	('Filston Mawana', 'Sweden', 'filston mawana'),
	('Brayan Córdoba', 'Colombia', 'brayan cordoba'),
	('Brayan Córdoba', 'Colombia', 'cordoba'),
	('Joe Bateman', 'England', 'joe bateman'),
	('Joe Bateman', 'England', 'bateman'),
	('Wen Tianpeng', 'China PR', 'wen tianpeng'),
	('Wen Tianpeng', 'China PR', 'tianpeng'),
	('Daniel Bowry', 'Antigua & Barbuda', 'bowry'),
	('Daniel Bowry', 'Antigua & Barbuda', 'daniel bowry'),
	('Ryley Towler', 'England', 'ryley towler'),
	('Ryley Towler', 'England', 'towler'),
	('Chris-Vianney Goteni', 'France', 'goteni'),
	('Chris-Vianney Goteni', 'France', 'chrisvianney goteni'),
	('Tomson Minda', 'Ecuador', 'minda'),
	('Tomson Minda', 'Ecuador', 'tomson minda'),
	('Mohamed Traore', 'Senegal', 'mohamed traore'),
	('Mohamed Traore', 'Senegal', 'traore'),
	('Mohammad Al Burayh', 'Saudi Arabia', 'burayh'),
	('Mohammad Al Burayh', 'Saudi Arabia', 'mohammad al burayh'),
	('Jack Newman', 'Scotland', 'jack newman'),
	('Jack Newman', 'Scotland', 'newman'),
	('Agustín Alfaro', 'Uruguay', 'agustin alfaro'),
	('Agustín Alfaro', 'Uruguay', 'alfaro'),
	('Xu Jiamin', 'China PR', 'xu jiamin'),
	('Xu Jiamin', 'China PR', 'jiamin'),
	('Morgan Penfold', 'England', 'morgan penfold'),
	('Morgan Penfold', 'England', 'penfold'),
	('Matthew Weaire', 'Denmark', 'weaire'),
	('Matthew Weaire', 'Denmark', 'matthew weaire'),
	('Julian Dunn', 'Canada', 'dunn'),
	('Julian Dunn', 'Canada', 'julian dunn'),
	('Samuel Kasongo', 'Switzerland', 'kasongo'),
	('Samuel Kasongo', 'Switzerland', 'samuel kasongo'),
	('Cristian Măgerușan', 'Romania', 'cristian magerusan'),
	('Cristian Măgerușan', 'Romania', 'magerusan'),
	('Kreshnik Krasniqi', 'Kosovo', 'krasniqi'),
	('Kreshnik Krasniqi', 'Kosovo', 'kreshnik krasniqi'),
	('Cole Turner', 'United States', 'cole turner'),
	('Cole Turner', 'United States', 'turner'),
	('Jorge Sikora', 'Poland', 'jorge sikora'),
	('Jorge Sikora', 'Poland', 'sikora'),
	('Kwon Jae Beom', 'Korea Republic', 'beom'),
	('Kwon Jae Beom', 'Korea Republic', 'kwon jae beom'),
	('Wen Jiabao', 'China PR', 'wen jiabao'),
	('Wen Jiabao', 'China PR', 'jiabao'),
	('Maximiliano Rodríguez Vejar', 'Chile', 'vejar'),
	('Maximiliano Rodríguez Vejar', 'Chile', 'maximiliano rodriguez vejar'),
	('Bartosz Neugebauer', 'Poland', 'neugebauer'),
	('Bartosz Neugebauer', 'Poland', 'bartosz neugebauer'),
	('Paul Grave', 'Germany', 'paul grave'),
	('Paul Grave', 'Germany', 'grave'),
	('Carlos Salomón', 'Chile', 'carlos salomon'),
	('Carlos Salomón', 'Chile', 'salomon'),
	('Oliver Bundgaard', 'Denmark', 'bundgaard'),
	('Oliver Bundgaard', 'Denmark', 'oliver bundgaard'),
	('Tician Tushi', 'Switzerland', 'tician tushi'),
	('Tician Tushi', 'Switzerland', 'tushi'),
	('Szymon Lewkot', 'Poland', 'lewkot'),
	('Szymon Lewkot', 'Poland', 'szymon lewkot'),
	('Arthur Lyska', 'Germany', 'arthur lyska'),
	('Arthur Lyska', 'Germany', 'lyska'),
	('James Vennings', 'England', 'vennings'),
	('James Vennings', 'England', 'james vennings'),
	('Cameron Duke', 'United States', 'duke'),
	('Cameron Duke', 'United States', 'cameron duke'),
	('Hwang In Jae', 'Korea Republic', 'hwang in jae'),
	('Hwang In Jae', 'Korea Republic', 'jae'),
	('Teddy Sharman-Lowe', 'England', 'teddy sharmanlowe'),
	('Teddy Sharman-Lowe', 'England', 'sharmanlowe'),
	('Sondre Auklend', 'Norway', 'sondre auklend'),
	('Sondre Auklend', 'Norway', 'auklend'),
	('Will Dean', 'England', 'will dean'),
	('Will Dean', 'England', 'dean'),
	('Jesper Tolinsson', 'Sweden', 'jesper tolinsson'),
	('Jesper Tolinsson', 'Sweden', 'tolinsson'),
	('Josh Gould', 'Wales', 'gould'),
	('Josh Gould', 'Wales', 'josh gould'),
	('Jarvis Cleal', 'England', 'jarvis cleal'),
	('Jarvis Cleal', 'England', 'cleal'),
	('Ricardo Pepi', 'United States', 'ricardo pepi'),
	('Ricardo Pepi', 'United States', 'pepi'),
	('Hubert Turski', 'Poland', 'hubert turski'),
	('Hubert Turski', 'Poland', 'turski'),
	('Marcel Wędrychowski', 'Poland', 'marcel wedrychowski'),
	('Marcel Wędrychowski', 'Poland', 'wedrychowski'),
	('Akira Yoshida', 'Japan', 'yoshida'),
	('Akira Yoshida', 'Japan', 'akira yoshida'),
	('Melker Jonsson', 'Sweden', 'jonsson'),
	('Melker Jonsson', 'Sweden', 'melker jonsson'),
	('Malek Al Abdulmunem', 'Saudi Arabia', 'malek al abdulmunem'),
	('Malek Al Abdulmunem', 'Saudi Arabia', 'abdulmunem'),
	('Essam Al Muwallad', 'Saudi Arabia', 'muwallad'),
	('Essam Al Muwallad', 'Saudi Arabia', 'essam al muwallad'),
	('Thomas Oluwa', 'Republic of Ireland', 'oluwa'),
	('Thomas Oluwa', 'Republic of Ireland', 'thomas oluwa'),
	('Harry Kite', 'England', 'kite'),
	('Harry Kite', 'England', 'harry kite'),
	('Juan Ferrufino', 'Bolivia', 'ferrufino'),
	('Juan Ferrufino', 'Bolivia', 'juan ferrufino'),
	('Mateusz Pieńczak', 'Poland', 'mateusz pienczak'),
	('Mateusz Pieńczak', 'Poland', 'pienczak'),
	('Mathias Nilsson', 'Sweden', 'mathias nilsson'),
	('Mathias Nilsson', 'Sweden', 'nilsson'),
	('Mark Gallagher', 'England', 'mark gallagher'),
	('Mark Gallagher', 'England', 'gallagher'),
	('Joe Adams', 'Wales', 'joe adams'),
	('Joe Adams', 'Wales', 'adams'),
	('Elliot Panicco', 'United States', 'panicco'),
	('Elliot Panicco', 'United States', 'elliot panicco'),
	('Michael Elechi', 'England', 'michael elechi'),
	('Michael Elechi', 'England', 'elechi'),
	('Jalen Hawkins', 'United States', 'hawkins'),
	('Jalen Hawkins', 'United States', 'jalen hawkins'),
	('Marcus Andersen', 'Norway', 'andersen'),
	('Marcus Andersen', 'Norway', 'marcus andersen'),
	('Luke Haakenson', 'United States', 'luke haakenson'),
	('Luke Haakenson', 'United States', 'haakenson'),
	('Hidetoshi Takeda', 'Japan', 'takeda'),
	('Hidetoshi Takeda', 'Japan', 'hidetoshi takeda'),
	('Umut Ünlü', 'Germany', 'umut unlu'),
	('Umut Ünlü', 'Germany', 'unlu'),
	('Danny Finlayson', 'Northern Ireland', 'finlayson'),
	('Danny Finlayson', 'Northern Ireland', 'danny finlayson'),
	('Tom McGill', 'England', 'tom mcgill'),
	('Tom McGill', 'England', 'mcgill'),
	('Joel Randall', 'England', 'randall'),
	('Joel Randall', 'England', 'joel randall'),
	('Horenus Tadesse', 'Norway', 'tadesse'),
	('Horenus Tadesse', 'Norway', 'horenus tadesse'),
	('Alec Byrne', 'Republic of Ireland', 'byrne'),
	('Alec Byrne', 'Republic of Ireland', 'alec byrne'),
	('Guo Jing', 'China PR', 'jing'),
	('Guo Jing', 'China PR', 'guo jing'),
	('Mikkel Lassen', 'Denmark', 'mikkel lassen'),
	('Mikkel Lassen', 'Denmark', 'lassen'),
	('Yang Yiming', 'China PR', 'yiming'),
	('Yang Yiming', 'China PR', 'yang yiming'),
	('Florjan Seferaj', 'Switzerland', 'florjan seferaj'),
	('Florjan Seferaj', 'Switzerland', 'seferaj'),
	('Gustavo Gutiérrez', 'Mexico', 'gutierrez'),
	('Gustavo Gutiérrez', 'Mexico', 'gustavo gutierrez'),
	('Kyle Gourlay', 'Scotland', 'gourlay'),
	('Kyle Gourlay', 'Scotland', 'kyle gourlay'),
	('Curtis Lyle', 'Scotland', 'lyle'),
	('Curtis Lyle', 'Scotland', 'curtis lyle'),
	('Bradley Webb', 'England', 'bradley webb'),
	('Bradley Webb', 'England', 'webb'),
	('Connor Malley', 'England', 'connor malley'),
	('Connor Malley', 'England', 'malley'),
	('Rareș Pop', 'Romania', 'pop'),
	('Rareș Pop', 'Romania', 'rares pop'),
	('Moataz Al Baqawi', 'Saudi Arabia', 'moataz al baqawi'),
	('Moataz Al Baqawi', 'Saudi Arabia', 'baqawi'),
	('Yao Jiangshan', 'China PR', 'jiangshan'),
	('Yao Jiangshan', 'China PR', 'yao jiangshan'),
	('Alexander Abrahamsson', 'Sweden', 'abrahamsson'),
	('Alexander Abrahamsson', 'Sweden', 'alexander abrahamsson'),
	('George Buliga', 'Romania', 'buliga'),
	('George Buliga', 'Romania', 'george buliga'),
	('Haitham Asiri', 'Saudi Arabia', 'haitham asiri'),
	('Haitham Asiri', 'Saudi Arabia', 'asiri'),
	('Gilbert Fuentes', 'United States', 'fuentes'),
	('Gilbert Fuentes', 'United States', 'gilbert fuentes'),
	('Fredrik Repstad Hansen', 'Norway', 'hansen'),
	('Fredrik Repstad Hansen', 'Norway', 'fredrik repstad hansen'),
	('Sondre Skogen', 'Norway', 'skogen'),
	('Sondre Skogen', 'Norway', 'sondre skogen'),
	('Elies Mahmoud', 'France', 'elies mahmoud'),
	('Elies Mahmoud', 'France', 'mahmoud'),
	('Ardon Jashari', 'Switzerland', 'ardon jashari'),
	('Ardon Jashari', 'Switzerland', 'jashari'),
	('Grant Horton', 'England', 'horton'),
	('Grant Horton', 'England', 'grant horton'),
	('Solomon Brynn', 'England', 'brynn'),
	('Solomon Brynn', 'England', 'solomon brynn'),
	('Dean Williams', 'Republic of Ireland', 'williams'),
	('Dean Williams', 'Republic of Ireland', 'dean williams'),
	('Owen Windsor', 'England', 'owen windsor'),
	('Owen Windsor', 'England', 'windsor'),
	('Chen Kerui', 'China PR', 'chen kerui'),
	('Chen Kerui', 'China PR', 'kerui'),
	('Reuben Duncan', 'England', 'reuben duncan'),
	('Reuben Duncan', 'England', 'duncan'),
	('Eirik Asante Gayi', 'Norway', 'gayi'),
	('Eirik Asante Gayi', 'Norway', 'eirik asante gayi'),
	('Gareth Harkin', 'Republic of Ireland', 'harkin'),
	('Gareth Harkin', 'Republic of Ireland', 'gareth harkin'),
	('Kim Yeon Soo', 'Korea Republic', 'kim yeon soo'),
	('Kim Yeon Soo', 'Korea Republic', 'soo'),
	('Andreas Endresen', 'Norway', 'andreas endresen'),
	('Andreas Endresen', 'Norway', 'endresen'),
	('Denilson Ovando', 'Ecuador', 'ovando'),
	('Denilson Ovando', 'Ecuador', 'denilson ovando'),
	('Xie Weijun', 'China PR', 'weijun'),
	('Xie Weijun', 'China PR', 'xie weijun'),
	('Lee Ji Yong', 'Korea Republic', 'yong'),
	('Lee Ji Yong', 'Korea Republic', 'lee ji yong'),
	('Luis Fernandez', 'England', 'luis fernandez'),
	('Luis Fernandez', 'England', 'fernandez'),
	('Jin Bo', 'China PR', 'jin bo'),
	('Jin Bo', 'China PR', 'bo'),
	('George Hornshaw', 'England', 'hornshaw'),
	('George Hornshaw', 'England', 'george hornshaw'),
	('Leandro Finochietto', 'Argentina', 'finochietto'),
	('Leandro Finochietto', 'Argentina', 'leandro finochietto'),
	('Liu Jing', 'China PR', 'liu jing'),
	('Liu Jing', 'China PR', 'jing'),
	('Nicolas Vouilloz', 'Switzerland', 'nicolas vouilloz'),
	('Nicolas Vouilloz', 'Switzerland', 'vouilloz'),
	('Lucas Cueva', 'Ecuador', 'lucas cueva'),
	('Lucas Cueva', 'Ecuador', 'cueva'),
	('Alexander Hjælmhof', 'Denmark', 'alexander hjlmhof'),
	('Alexander Hjælmhof', 'Denmark', 'hjlmhof'),
	('Kai Meriluoto', 'Finland', 'kai meriluoto'),
	('Kai Meriluoto', 'Finland', 'meriluoto'),
	('Paul Bourdelle', 'France', 'bourdelle'),
	('Paul Bourdelle', 'France', 'paul bourdelle'),
	('Juan José Uribe', 'Colombia', 'juan jose uribe'),
	('Juan José Uribe', 'Colombia', 'uribe'),
	('Tiago Galletto', 'Uruguay', 'galletto'),
	('Tiago Galletto', 'Uruguay', 'tiago galletto'),
	('Daniel Andersen', 'Denmark', 'andersen'),
	('Daniel Andersen', 'Denmark', 'daniel andersen'),
	('Tristan Prendergast', 'Australia', 'tristan prendergast'),
	('Tristan Prendergast', 'Australia', 'prendergast'),
	('Jiang Zilei', 'China PR', 'jiang zilei'),
	('Jiang Zilei', 'China PR', 'zilei'),
	('Adam Senior', 'England', 'senior'),
	('Adam Senior', 'England', 'adam senior'),
	('Park Gwan Woo', 'Korea Republic', 'woo'),
	('Park Gwan Woo', 'Korea Republic', 'park gwan woo'),
	('Thomas Christiansen', 'Denmark', 'christiansen'),
	('Thomas Christiansen', 'Denmark', 'thomas christiansen'),
	('Siriky Sanogo', 'Ivory Coast', 'siriky sanogo'),
	('Siriky Sanogo', 'Ivory Coast', 'sanogo'),
	('Tommaso Fantacci', 'Italy', 'tommaso fantacci'),
	('Tommaso Fantacci', 'Italy', 'fantacci'),
	('Monther Al Nakhli', 'Saudi Arabia', 'monther al nakhli'),
	('Monther Al Nakhli', 'Saudi Arabia', 'nakhli'),
	('Tivonge Rushesha', 'Wales', 'rushesha'),
	('Tivonge Rushesha', 'Wales', 'tivonge rushesha'),
	('Yan Zihao', 'China PR', 'yan zihao'),
	('Yan Zihao', 'China PR', 'zihao'),
	('Jiang Weipeng', 'China PR', 'jiang weipeng'),
	('Jiang Weipeng', 'China PR', 'weipeng'),
	('Wilbert Hernández', 'Venezuela', 'wilbert hernandez'),
	('Wilbert Hernández', 'Venezuela', 'hernandez'),
	('Lewis Richards', 'Republic of Ireland', 'richards'),
	('Lewis Richards', 'Republic of Ireland', 'lewis richards'),
	('Rakan Al Najjar', 'Saudi Arabia', 'rakan al najjar'),
	('Rakan Al Najjar', 'Saudi Arabia', 'najjar'),
	('Kostandinos Grozos', 'Australia', 'kostandinos grozos'),
	('Kostandinos Grozos', 'Australia', 'grozos'),
	('Lino Lang', 'Switzerland', 'lang'),
	('Lino Lang', 'Switzerland', 'lino lang'),
	('Díver Torres', 'Venezuela', 'torres'),
	('Díver Torres', 'Venezuela', 'diver torres'),
	('Zhang Wentao', 'China PR', 'zhang wentao'),
	('Zhang Wentao', 'China PR', 'wentao')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';