INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Ben Liddle', 'England', 'player'),
	('Bryan Rivera', 'Ecuador', 'player'),
	('Beau Reus', 'Netherlands', 'player'),
	('Walter Figueira', 'England', 'player'),
	('Benjamin Ozegovic', 'Austria', 'player'),
	('Laurenz Dehl', 'Germany', 'player'),
	('Ramon Castellucci', 'Germany', 'player'),
	('Marlon Sündermann', 'Germany', 'player'),
	('Mohammed Attiyah', 'Saudi Arabia', 'player'),
	('Cameron McJannet', 'England', 'player'),
	('Luis Franco', 'Paraguay', 'player'),
	('Ayumu Ohata', 'Japan', 'player'),
	('Huang Zhengyu', 'China PR', 'player'),
	('Khalid Al Ghannam', 'Saudi Arabia', 'player'),
	('Zeng Chao', 'China PR', 'player'),
	('Matthew Smith', 'England', 'player'),
	('Erick Otieno', 'Kenya', 'player'),
	('Njegoš Kupusović', 'Serbia', 'player'),
	('Andrea Padula', 'Italy', 'player'),
	('Mitchy Ntelo', 'Belgium', 'player'),
	('Bryan Colula', 'Mexico', 'player'),
	('Ben Curville', 'Australia', 'player'),
	('Lucas Sanabria', 'Paraguay', 'player'),
	('John Popelard', 'France', 'player'),
	('Malcolm Barcola', 'Togo', 'player'),
	('Matthew Dolan', 'England', 'player'),
	('Adam Pearce', 'Australia', 'player'),
	('Lenny Lacroix', 'France', 'player'),
	('Jonas Sterner', 'Germany', 'player'),
	('Ali Al Hassan', 'Saudi Arabia', 'player'),
	('George Micle', 'Romania', 'player'),
	('Gabriel Barès', 'Switzerland', 'player'),
	('Marvin Senger', 'Germany', 'player'),
	('Martin Frese', 'Denmark', 'player'),
	('Kenneth Córdova', 'United States', 'player'),
	('Joan Cruz', 'Chile', 'player'),
	('Nacho Córdoba', 'Spain', 'player'),
	('Luís Mata', 'Portugal', 'player'),
	('Dong Yanfeng', 'China PR', 'player'),
	('Reagan Ogle', 'Australia', 'player'),
	('Mohammed Al Moqahwi', 'Saudi Arabia', 'player'),
	('Leonardo Justiniano', 'Bolivia', 'player'),
	('Alex De John', 'United States', 'player'),
	('Shaun Want', 'Scotland', 'player'),
	('Eduardo Torres', 'Mexico', 'player'),
	('Taylor Richards', 'England', 'player'),
	('Matty Daly', 'England', 'player'),
	('Cristian Dumitru', 'Romania', 'player'),
	('Omar Tejeda', 'Mexico', 'player'),
	('Maximiliano Cabral', 'Uruguay', 'player'),
	('Christian Marques', 'Switzerland', 'player'),
	('Vassilis Chatziemmanouil', 'Greece', 'player'),
	('Dylan Mottley-Henry', 'England', 'player'),
	('Lucas Greno', 'Uruguay', 'player'),
	('Ali Youssef', 'Sweden', 'player'),
	('Zhang Xiaobin', 'China PR', 'player'),
	('Guo Tianyu', 'China PR', 'player'),
	('Mickaël Nanizayamo', 'France', 'player'),
	('Alin Popa', 'Romania', 'player'),
	('Diogo', 'Brazil', 'player'),
	('Kim Tae Gon', 'Korea Republic', 'player'),
	('Mauro González', 'Argentina', 'player'),
	('Ethan Zubak', 'United States', 'player'),
	('Anthony Rosell', 'Peru', 'player'),
	('Peter Therkildsen', 'Denmark', 'player'),
	('José Guidino', 'Peru', 'player'),
	('Georgian Honciu', 'Romania', 'player'),
	('Kye Rowles', 'Australia', 'player'),
	('Kenta Ito', 'Japan', 'player'),
	('Na Sung Eun', 'Korea Republic', 'player'),
	('Matthew Drubble', 'Australia', 'player'),
	('Dennis Borkowski', 'Germany', 'player'),
	('Mert Kula', 'Turkey', 'player'),
	('Guo Hao', 'China PR', 'player'),
	('Lautaro Chávez', 'Argentina', 'player'),
	('Kim Joon Beom', 'Korea Republic', 'player'),
	('Bobby Thomas', 'England', 'player'),
	('Kasper Jørgensen', 'Denmark', 'player'),
	('Francisco Ginella', 'Uruguay', 'player'),
	('Feyzi Yıldırım', 'Turkey', 'player'),
	('George Mells', 'Australia', 'player'),
	('Djibril Bangoura', 'Guinea', 'player'),
	('Tobias Schättin', 'Switzerland', 'player'),
	('Edgar Lastre', 'Ecuador', 'player'),
	('Bryan Reynolds', 'United States', 'player'),
	('Noel Mbo', 'DR Congo', 'player'),
	('Lee Ji Seung', 'Korea Republic', 'player'),
	('Marcus Mehnert', 'Norway', 'player'),
	('Liam Scales', 'Republic of Ireland', 'player'),
	('Răzvan Andronic', 'Romania', 'player'),
	('Waniss Taïbi', 'France', 'player'),
	('Warren O''Hora', 'Republic of Ireland', 'player'),
	('Giannis Michailidis', 'Greece', 'player'),
	('Luca Stellwagen', 'Germany', 'player'),
	('Frederik Schram', 'Iceland', 'player'),
	('Yuito Suzuki', 'Japan', 'player'),
	('Jordan Carrillo', 'Mexico', 'player'),
	('Adrian Benedyczak', 'Poland', 'player'),
	('Josh Martin', 'England', 'player'),
	('Noel Niemann', 'Germany', 'player'),
	('Aleksandar Cirkovic', 'Serbia', 'player'),
	('Andrea Carboni', 'Italy', 'player'),
	('Jonathan Bumbu', 'France', 'player'),
	('Ciaran Kelly', 'Republic of Ireland', 'player'),
	('José Oliveira', 'Portugal', 'player'),
	('Alex Newby', 'England', 'player'),
	('Nurettin Korkmaz', 'Turkey', 'player'),
	('Jannis Rabold', 'Germany', 'player'),
	('Robbie Robinson', 'United States', 'player'),
	('Keita Takahata', 'Japan', 'player'),
	('Gordon Büch', 'Germany', 'player'),
	('Noah Chilvers', 'England', 'player'),
	('Christoph Messerer', 'Austria', 'player'),
	('Jack Ruddy', 'Scotland', 'player'),
	('Jonathan Stead', 'England', 'player'),
	('Yassin Fortune', 'France', 'player'),
	('Gerrit Gohlke', 'Germany', 'player'),
	('Paweł Żuk', 'Poland', 'player'),
	('Aloys Fouda', 'Cameroon', 'player'),
	('Jack Sowerby', 'England', 'player'),
	('Oliver Gastrell', 'Australia', 'player'),
	('Dawid Pakulski', 'Poland', 'player'),
	('Kevin Ellison', 'England', 'player'),
	('Julio Machado', 'Venezuela', 'player'),
	('Killian Le Roy', 'France', 'player'),
	('Olivier Deman', 'Belgium', 'player'),
	('Jomaine Consbruch', 'Germany', 'player'),
	('Kohei Okuno', 'Japan', 'player'),
	('Mohammed Rayman', 'Saudi Arabia', 'player'),
	('Riku Danzaki', 'Japan', 'player'),
	('Brandon Abundis', 'Mexico', 'player'),
	('Carlo Boukhalfa', 'Germany', 'player'),
	('Luo Hao', 'China PR', 'player'),
	('Miguel Angel Navarro', 'Venezuela', 'player'),
	('Nassim El Ablak', 'Netherlands', 'player'),
	('Ryan Edmondson', 'England', 'player'),
	('Chris Zuvela', 'Australia', 'player'),
	('Arambarri', 'Spain', 'player'),
	('Julian Buchta', 'Austria', 'player'),
	('Milislav Popovic', 'Australia', 'player'),
	('David Romero', 'Argentina', 'player'),
	('Niko Bretschneider', 'Germany', 'player'),
	('Stan van Dijck', 'Netherlands', 'player'),
	('Guido Chávez', 'Paraguay', 'player'),
	('Josh Reid', 'Scotland', 'player'),
	('Agustín Guiffrey', 'Argentina', 'player'),
	('Maksymilian Sitek', 'Poland', 'player'),
	('Anwar Elyounoussi', 'Norway', 'player'),
	('Jorge Gática', 'Chile', 'player'),
	('Aaron Bolger', 'Republic of Ireland', 'player'),
	('Muamer Aljic', 'France', 'player'),
	('Li Hailong', 'China PR', 'player'),
	('Teodor Axinte', 'Romania', 'player'),
	('Juan Pablo Juárez', 'Mexico', 'player'),
	('Dan Kemp', 'England', 'player'),
	('Khaled Al Dubaysh', 'Saudi Arabia', 'player'),
	('Lee Jun', 'Korea Republic', 'player'),
	('Edwin Mosquera', 'Colombia', 'player'),
	('Leon Sopić', 'Croatia', 'player'),
	('Juan Roa', 'Paraguay', 'player'),
	('Ross Millen', 'Scotland', 'player'),
	('Ryan Barnett', 'England', 'player'),
	('Isaac Boye', 'Nigeria', 'player'),
	('Daniel Ciobanu', 'Romania', 'player'),
	('Axel Grijalva', 'Mexico', 'player'),
	('Victor Torp', 'Denmark', 'player'),
	('Lucas Di Yorio', 'Argentina', 'player'),
	('Maarten Rieder', 'Netherlands', 'player'),
	('Andrei Sîntean', 'Romania', 'player'),
	('Cristofer Salas', 'Chile', 'player'),
	('Charlie Carter', 'England', 'player'),
	('Gastón Suso', 'Argentina', 'player'),
	('Robert Grecu', 'Romania', 'player'),
	('Barry Maguire', 'Scotland', 'player'),
	('Jamie Soule', 'England', 'player'),
	('Emanuel Montejano', 'Mexico', 'player'),
	('Joel Waterman', 'Canada', 'player'),
	('Marcelo Miño', 'Argentina', 'player'),
	('Abdullah Majrashi', 'Saudi Arabia', 'player'),
	('Boris Mathis', 'France', 'player'),
	('Tobías Donsanti', 'Argentina', 'player'),
	('Joey Jones', 'Northern Ireland', 'player'),
	('Natanael Ntolla Thio', 'France', 'player'),
	('Izaack Powell', 'Australia', 'player'),
	('Andy Burbano', 'Ecuador', 'player'),
	('Yannick Brugger', 'Germany', 'player'),
	('Jordan Slew', 'England', 'player'),
	('Harrison Ashby', 'Scotland', 'player'),
	('Jordi van Stappershoef', 'Netherlands', 'player'),
	('Kasper Thiesson Kristensen', 'Denmark', 'player'),
	('Kyle Jameson', 'England', 'player'),
	('Hassan Tombakti', 'Saudi Arabia', 'player'),
	('George Nurse', 'England', 'player'),
	('Jonas Dakir', 'Denmark', 'player'),
	('Thomas Secchi', 'France', 'player'),
	('Liu Ruofan', 'China PR', 'player'),
	('Cyril Zabou', 'France', 'player'),
	('Mao Hosoya', 'Japan', 'player'),
	('Peter Bjur', 'Denmark', 'player'),
	('Magnus Norman', 'England', 'player'),
	('Stéphane Zobo', 'Cameroon', 'player'),
	('Han Feng', 'China PR', 'player'),
	('Óscar Millán', 'Mexico', 'player'),
	('Kosovar Sadiki', 'Canada', 'player'),
	('Emanuel Cuevas', 'Argentina', 'player'),
	('James Tilley', 'England', 'player'),
	('Daniel Wilmering', 'Australia', 'player'),
	('Cendrim Kameraj', 'Kosovo', 'player'),
	('Mohammed Al Wakid', 'Saudi Arabia', 'player'),
	('Fahad Al Harbi', 'Saudi Arabia', 'player'),
	('Max Fenger', 'Denmark', 'player'),
	('Levente Bősz', 'Hungary', 'player'),
	('Elis Isufi', 'Switzerland', 'player'),
	('Joël van Kaam', 'Netherlands', 'player'),
	('Yahia Fofana', 'France', 'player'),
	('Kyle Callan-McFadden', 'Republic of Ireland', 'player'),
	('Ross Marshall', 'England', 'player'),
	('Jordan Brown', 'England', 'player'),
	('Akin Famewo', 'England', 'player'),
	('Tom Holmes', 'England', 'player'),
	('Giuseppe Cuomo', 'Italy', 'player'),
	('Oliver Villadsen', 'Denmark', 'player'),
	('Alexander Nadj', 'Sweden', 'player'),
	('Alan Kerouedan', 'France', 'player'),
	('Jack Hindle', 'England', 'player'),
	('Jared Stroud', 'United States', 'player'),
	('Taylor Allen', 'England', 'player'),
	('Karim Saab', 'Venezuela', 'player'),
	('Felix Seiwald', 'Austria', 'player'),
	('Marcel Tanzmayr', 'Austria', 'player'),
	('Toby Savin', 'England', 'player'),
	('Ollie Kensdale', 'England', 'player'),
	('Alaa Al Hajji', 'Saudi Arabia', 'player'),
	('Ștefan Cană', 'Romania', 'player'),
	('Oliver Petersen', 'Norway', 'player'),
	('Kosta Petratos', 'Australia', 'player'),
	('Jesse Edem Tugbenyo', 'Germany', 'player'),
	('Sebastian Bîrsan', 'Romania', 'player'),
	('Kashifu Bangunagande', 'Japan', 'player'),
	('Jack Emmett', 'England', 'player'),
	('Joshua Wehking', 'Germany', 'player'),
	('Thomas Mayer', 'Austria', 'player'),
	('Bartłomiej Wdowik', 'Poland', 'player'),
	('Georgie Kelly', 'Republic of Ireland', 'player'),
	('Luke Spokes', 'England', 'player'),
	('Chae Gwang Hoon', 'Korea Republic', 'player'),
	('Joel Quintero', 'Ecuador', 'player'),
	('Amar Sejdič', 'Germany', 'player'),
	('Innes Cameron', 'Scotland', 'player'),
	('Daiju Sasaki', 'Japan', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Ben Liddle', 'England', 'liddle'),
	('Ben Liddle', 'England', 'ben liddle'),
	('Bryan Rivera', 'Ecuador', 'bryan rivera'),
	('Bryan Rivera', 'Ecuador', 'rivera'),
	('Beau Reus', 'Netherlands', 'reus'),
	('Beau Reus', 'Netherlands', 'beau reus'),
	('Walter Figueira', 'England', 'walter figueira'),
	('Walter Figueira', 'England', 'figueira'),
	('Benjamin Ozegovic', 'Austria', 'benjamin ozegovic'),
	('Benjamin Ozegovic', 'Austria', 'ozegovic'),
	('Laurenz Dehl', 'Germany', 'dehl'),
	('Laurenz Dehl', 'Germany', 'laurenz dehl'),
	('Ramon Castellucci', 'Germany', 'castellucci'),
	('Ramon Castellucci', 'Germany', 'ramon castellucci'),
	('Marlon Sündermann', 'Germany', 'sundermann'),
	('Marlon Sündermann', 'Germany', 'marlon sundermann'),
	('Mohammed Attiyah', 'Saudi Arabia', 'mohammed attiyah'),
	('Mohammed Attiyah', 'Saudi Arabia', 'attiyah'),
	('Cameron McJannet', 'England', 'mcjannet'),
	('Cameron McJannet', 'England', 'cameron mcjannet'),
	('Luis Franco', 'Paraguay', 'luis franco'),
	('Luis Franco', 'Paraguay', 'franco'),
	('Ayumu Ohata', 'Japan', 'ayumu ohata'),
	('Ayumu Ohata', 'Japan', 'ohata'),
	('Huang Zhengyu', 'China PR', 'huang zhengyu'),
	('Huang Zhengyu', 'China PR', 'zhengyu'),
	('Khalid Al Ghannam', 'Saudi Arabia', 'ghannam'),
	('Khalid Al Ghannam', 'Saudi Arabia', 'khalid al ghannam'),
	('Zeng Chao', 'China PR', 'chao'),
	('Zeng Chao', 'China PR', 'zeng chao'),
	('Matthew Smith', 'England', 'matthew smith'),
	('Matthew Smith', 'England', 'smith'),
	('Erick Otieno', 'Kenya', 'otieno'),
	('Erick Otieno', 'Kenya', 'erick otieno'),
	('Njegoš Kupusović', 'Serbia', 'kupusovic'),
	('Njegoš Kupusović', 'Serbia', 'njegos kupusovic'),
	('Andrea Padula', 'Italy', 'padula'),
	('Andrea Padula', 'Italy', 'andrea padula'),
	('Mitchy Ntelo', 'Belgium', 'ntelo'),
	('Mitchy Ntelo', 'Belgium', 'mitchy ntelo'),
	('Bryan Colula', 'Mexico', 'bryan colula'),
	('Bryan Colula', 'Mexico', 'colula'),
	('Ben Curville', 'Australia', 'curville'),
	('Ben Curville', 'Australia', 'ben curville'),
	('Lucas Sanabria', 'Paraguay', 'lucas sanabria'),
	('Lucas Sanabria', 'Paraguay', 'sanabria'),
	('John Popelard', 'France', 'popelard'),
	('John Popelard', 'France', 'john popelard'),
	('Malcolm Barcola', 'Togo', 'malcolm barcola'),
	('Malcolm Barcola', 'Togo', 'barcola'),
	('Matthew Dolan', 'England', 'dolan'),
	('Matthew Dolan', 'England', 'matthew dolan'),
	('Adam Pearce', 'Australia', 'pearce'),
	('Adam Pearce', 'Australia', 'adam pearce'),
	('Lenny Lacroix', 'France', 'lacroix'),
	('Lenny Lacroix', 'France', 'lenny lacroix'),
	('Jonas Sterner', 'Germany', 'sterner'),
	('Jonas Sterner', 'Germany', 'jonas sterner'),
	('Ali Al Hassan', 'Saudi Arabia', 'ali al hassan'),
	('Ali Al Hassan', 'Saudi Arabia', 'hassan'),
	('George Micle', 'Romania', 'micle'),
	('George Micle', 'Romania', 'george micle'),
	('Gabriel Barès', 'Switzerland', 'bares'),
	('Gabriel Barès', 'Switzerland', 'gabriel bares'),
	('Marvin Senger', 'Germany', 'marvin senger'),
	('Marvin Senger', 'Germany', 'senger'),
	('Martin Frese', 'Denmark', 'frese'),
	('Martin Frese', 'Denmark', 'martin frese'),
	('Kenneth Córdova', 'United States', 'cordova'),
	('Kenneth Córdova', 'United States', 'kenneth cordova'),
	('Joan Cruz', 'Chile', 'joan cruz'),
	('Joan Cruz', 'Chile', 'cruz'),
	('Nacho Córdoba', 'Spain', 'nacho cordoba'),
	('Nacho Córdoba', 'Spain', 'cordoba'),
	('Luís Mata', 'Portugal', 'mata'),
	('Luís Mata', 'Portugal', 'luis mata'),
	('Dong Yanfeng', 'China PR', 'dong yanfeng'),
	('Dong Yanfeng', 'China PR', 'yanfeng'),
	('Reagan Ogle', 'Australia', 'reagan ogle'),
	('Reagan Ogle', 'Australia', 'ogle'),
	('Mohammed Al Moqahwi', 'Saudi Arabia', 'mohammed al moqahwi'),
	('Mohammed Al Moqahwi', 'Saudi Arabia', 'moqahwi'),
	('Leonardo Justiniano', 'Bolivia', 'justiniano'),
	('Leonardo Justiniano', 'Bolivia', 'leonardo justiniano'),
	('Alex De John', 'United States', 'john'),
	('Alex De John', 'United States', 'alex de john'),
	('Shaun Want', 'Scotland', 'shaun want'),
	('Shaun Want', 'Scotland', 'want'),
	('Eduardo Torres', 'Mexico', 'torres'),
	('Eduardo Torres', 'Mexico', 'eduardo torres'),
	('Taylor Richards', 'England', 'taylor richards'),
	('Taylor Richards', 'England', 'richards'),
	('Matty Daly', 'England', 'daly'),
	('Matty Daly', 'England', 'matty daly'),
	('Cristian Dumitru', 'Romania', 'cristian dumitru'),
	('Cristian Dumitru', 'Romania', 'dumitru'),
	('Omar Tejeda', 'Mexico', 'omar tejeda'),
	('Omar Tejeda', 'Mexico', 'tejeda'),
	('Maximiliano Cabral', 'Uruguay', 'maximiliano cabral'),
	('Maximiliano Cabral', 'Uruguay', 'cabral'),
	('Christian Marques', 'Switzerland', 'christian marques'),
	('Christian Marques', 'Switzerland', 'marques'),
	('Vassilis Chatziemmanouil', 'Greece', 'vassilis chatziemmanouil'),
	('Vassilis Chatziemmanouil', 'Greece', 'chatziemmanouil'),
	('Dylan Mottley-Henry', 'England', 'dylan mottleyhenry'),
	('Dylan Mottley-Henry', 'England', 'mottleyhenry'),
	('Lucas Greno', 'Uruguay', 'greno'),
	('Lucas Greno', 'Uruguay', 'lucas greno'),
	('Ali Youssef', 'Sweden', 'youssef'),
	('Ali Youssef', 'Sweden', 'ali youssef'),
	('Zhang Xiaobin', 'China PR', 'zhang xiaobin'),
	('Zhang Xiaobin', 'China PR', 'xiaobin'),
	('Guo Tianyu', 'China PR', 'tianyu'),
	('Guo Tianyu', 'China PR', 'guo tianyu'),
	('Mickaël Nanizayamo', 'France', 'nanizayamo'),
	('Mickaël Nanizayamo', 'France', 'mickael nanizayamo'),
	('Alin Popa', 'Romania', 'popa'),
	('Alin Popa', 'Romania', 'alin popa'),
	('Diogo', 'Brazil', 'diogo'),
	('Kim Tae Gon', 'Korea Republic', 'gon'),
	('Kim Tae Gon', 'Korea Republic', 'kim tae gon'),
	('Mauro González', 'Argentina', 'mauro gonzalez'),
	('Mauro González', 'Argentina', 'gonzalez'),
	('Ethan Zubak', 'United States', 'ethan zubak'),
	('Ethan Zubak', 'United States', 'zubak'),
	('Anthony Rosell', 'Peru', 'anthony rosell'),
	('Anthony Rosell', 'Peru', 'rosell'),
	('Peter Therkildsen', 'Denmark', 'therkildsen'),
	('Peter Therkildsen', 'Denmark', 'peter therkildsen'),
	('José Guidino', 'Peru', 'guidino'),
	('José Guidino', 'Peru', 'jose guidino'),
	('Georgian Honciu', 'Romania', 'honciu'),
	('Georgian Honciu', 'Romania', 'georgian honciu'),
	('Kye Rowles', 'Australia', 'kye rowles'),
	('Kye Rowles', 'Australia', 'rowles'),
	('Kenta Ito', 'Japan', 'kenta ito'),
	('Kenta Ito', 'Japan', 'ito'),
	('Na Sung Eun', 'Korea Republic', 'eun'),
	('Na Sung Eun', 'Korea Republic', 'na sung eun'),
	('Matthew Drubble', 'Australia', 'matthew drubble'),
	('Matthew Drubble', 'Australia', 'drubble'),
	('Dennis Borkowski', 'Germany', 'dennis borkowski'),
	('Dennis Borkowski', 'Germany', 'borkowski'),
	('Mert Kula', 'Turkey', 'mert kula'),
	('Mert Kula', 'Turkey', 'kula'),
	('Guo Hao', 'China PR', 'guo hao'),
	('Guo Hao', 'China PR', 'hao'),
	('Lautaro Chávez', 'Argentina', 'lautaro chavez'),
	('Lautaro Chávez', 'Argentina', 'chavez'),
	('Kim Joon Beom', 'Korea Republic', 'beom'),
	('Kim Joon Beom', 'Korea Republic', 'kim joon beom'),
	('Bobby Thomas', 'England', 'thomas'),
	('Bobby Thomas', 'England', 'bobby thomas'),
	('Kasper Jørgensen', 'Denmark', 'kasper jrgensen'),
	('Kasper Jørgensen', 'Denmark', 'jrgensen'),
	('Francisco Ginella', 'Uruguay', 'francisco ginella'),
	('Francisco Ginella', 'Uruguay', 'ginella'),
	('Feyzi Yıldırım', 'Turkey', 'feyzi yldrm'),
	('Feyzi Yıldırım', 'Turkey', 'yldrm'),
	('George Mells', 'Australia', 'george mells'),
	('George Mells', 'Australia', 'mells'),
	('Djibril Bangoura', 'Guinea', 'bangoura'),
	('Djibril Bangoura', 'Guinea', 'djibril bangoura'),
	('Tobias Schättin', 'Switzerland', 'schattin'),
	('Tobias Schättin', 'Switzerland', 'tobias schattin'),
	('Edgar Lastre', 'Ecuador', 'edgar lastre'),
	('Edgar Lastre', 'Ecuador', 'lastre'),
	('Bryan Reynolds', 'United States', 'reynolds'),
	('Bryan Reynolds', 'United States', 'bryan reynolds'),
	('Noel Mbo', 'DR Congo', 'mbo'),
	('Noel Mbo', 'DR Congo', 'noel mbo'),
	('Lee Ji Seung', 'Korea Republic', 'lee ji seung'),
	('Lee Ji Seung', 'Korea Republic', 'seung'),
	('Marcus Mehnert', 'Norway', 'marcus mehnert'),
	('Marcus Mehnert', 'Norway', 'mehnert'),
	('Liam Scales', 'Republic of Ireland', 'liam scales'),
	('Liam Scales', 'Republic of Ireland', 'scales'),
	('Răzvan Andronic', 'Romania', 'razvan andronic'),
	('Răzvan Andronic', 'Romania', 'andronic'),
	('Waniss Taïbi', 'France', 'taibi'),
	('Waniss Taïbi', 'France', 'waniss taibi'),
	('Warren O''Hora', 'Republic of Ireland', 'warren ohora'),
	('Warren O''Hora', 'Republic of Ireland', 'ohora'),
	('Giannis Michailidis', 'Greece', 'michailidis'),
	('Giannis Michailidis', 'Greece', 'giannis michailidis'),
	('Luca Stellwagen', 'Germany', 'stellwagen'),
	('Luca Stellwagen', 'Germany', 'luca stellwagen'),
	('Frederik Schram', 'Iceland', 'frederik schram'),
	('Frederik Schram', 'Iceland', 'schram'),
	('Yuito Suzuki', 'Japan', 'yuito suzuki'),
	('Yuito Suzuki', 'Japan', 'suzuki'),
	('Jordan Carrillo', 'Mexico', 'carrillo'),
	('Jordan Carrillo', 'Mexico', 'jordan carrillo'),
	('Adrian Benedyczak', 'Poland', 'benedyczak'),
	('Adrian Benedyczak', 'Poland', 'adrian benedyczak'),
	('Josh Martin', 'England', 'josh martin'),
	('Josh Martin', 'England', 'martin'),
	('Noel Niemann', 'Germany', 'niemann'),
	('Noel Niemann', 'Germany', 'noel niemann'),
	('Aleksandar Cirkovic', 'Serbia', 'cirkovic'),
	('Aleksandar Cirkovic', 'Serbia', 'aleksandar cirkovic'),
	('Andrea Carboni', 'Italy', 'carboni'),
	('Andrea Carboni', 'Italy', 'andrea carboni'),
	('Jonathan Bumbu', 'France', 'bumbu'),
	('Jonathan Bumbu', 'France', 'jonathan bumbu'),
	('Ciaran Kelly', 'Republic of Ireland', 'ciaran kelly'),
	('Ciaran Kelly', 'Republic of Ireland', 'kelly'),
	('José Oliveira', 'Portugal', 'oliveira'),
	('José Oliveira', 'Portugal', 'jose oliveira'),
	('Alex Newby', 'England', 'newby'),
	('Alex Newby', 'England', 'alex newby'),
	('Nurettin Korkmaz', 'Turkey', 'korkmaz'),
	('Nurettin Korkmaz', 'Turkey', 'nurettin korkmaz'),
	('Jannis Rabold', 'Germany', 'jannis rabold'),
	('Jannis Rabold', 'Germany', 'rabold'),
	('Robbie Robinson', 'United States', 'robinson'),
	('Robbie Robinson', 'United States', 'robbie robinson'),
	('Keita Takahata', 'Japan', 'keita takahata'),
	('Keita Takahata', 'Japan', 'takahata'),
	('Gordon Büch', 'Germany', 'gordon buch'),
	('Gordon Büch', 'Germany', 'buch'),
	('Noah Chilvers', 'England', 'noah chilvers'),
	('Noah Chilvers', 'England', 'chilvers'),
	('Christoph Messerer', 'Austria', 'messerer'),
	('Christoph Messerer', 'Austria', 'christoph messerer'),
	('Jack Ruddy', 'Scotland', 'ruddy'),
	('Jack Ruddy', 'Scotland', 'jack ruddy'),
	('Jonathan Stead', 'England', 'stead'),
	('Jonathan Stead', 'England', 'jonathan stead'),
	('Yassin Fortune', 'France', 'fortune'),
	('Yassin Fortune', 'France', 'yassin fortune'),
	('Gerrit Gohlke', 'Germany', 'gohlke'),
	('Gerrit Gohlke', 'Germany', 'gerrit gohlke'),
	('Paweł Żuk', 'Poland', 'pawe zuk'),
	('Paweł Żuk', 'Poland', 'zuk'),
	('Aloys Fouda', 'Cameroon', 'aloys fouda'),
	('Aloys Fouda', 'Cameroon', 'fouda'),
	('Jack Sowerby', 'England', 'jack sowerby'),
	('Jack Sowerby', 'England', 'sowerby'),
	('Oliver Gastrell', 'Australia', 'oliver gastrell'),
	('Oliver Gastrell', 'Australia', 'gastrell'),
	('Dawid Pakulski', 'Poland', 'dawid pakulski'),
	('Dawid Pakulski', 'Poland', 'pakulski'),
	('Kevin Ellison', 'England', 'kevin ellison'),
	('Kevin Ellison', 'England', 'ellison'),
	('Julio Machado', 'Venezuela', 'julio machado'),
	('Julio Machado', 'Venezuela', 'machado'),
	('Killian Le Roy', 'France', 'killian le roy'),
	('Killian Le Roy', 'France', 'roy'),
	('Olivier Deman', 'Belgium', 'deman'),
	('Olivier Deman', 'Belgium', 'olivier deman'),
	('Jomaine Consbruch', 'Germany', 'jomaine consbruch'),
	('Jomaine Consbruch', 'Germany', 'consbruch'),
	('Kohei Okuno', 'Japan', 'okuno'),
	('Kohei Okuno', 'Japan', 'kohei okuno'),
	('Mohammed Rayman', 'Saudi Arabia', 'rayman'),
	('Mohammed Rayman', 'Saudi Arabia', 'mohammed rayman'),
	('Riku Danzaki', 'Japan', 'danzaki'),
	('Riku Danzaki', 'Japan', 'riku danzaki'),
	('Brandon Abundis', 'Mexico', 'brandon abundis'),
	('Brandon Abundis', 'Mexico', 'abundis'),
	('Carlo Boukhalfa', 'Germany', 'boukhalfa'),
	('Carlo Boukhalfa', 'Germany', 'carlo boukhalfa'),
	('Luo Hao', 'China PR', 'hao'),
	('Luo Hao', 'China PR', 'luo hao'),
	('Miguel Angel Navarro', 'Venezuela', 'miguel angel navarro'),
	('Miguel Angel Navarro', 'Venezuela', 'navarro'),
	('Nassim El Ablak', 'Netherlands', 'ablak'),
	('Nassim El Ablak', 'Netherlands', 'nassim el ablak'),
	('Ryan Edmondson', 'England', 'edmondson'),
	('Ryan Edmondson', 'England', 'ryan edmondson'),
	('Chris Zuvela', 'Australia', 'chris zuvela'),
	('Chris Zuvela', 'Australia', 'zuvela'),
	('Arambarri', 'Spain', 'arambarri'),
	('Julian Buchta', 'Austria', 'julian buchta'),
	('Julian Buchta', 'Austria', 'buchta'),
	('Milislav Popovic', 'Australia', 'popovic'),
	('Milislav Popovic', 'Australia', 'milislav popovic'),
	('David Romero', 'Argentina', 'david romero'),
	('David Romero', 'Argentina', 'romero'),
	('Niko Bretschneider', 'Germany', 'niko bretschneider'),
	('Niko Bretschneider', 'Germany', 'bretschneider'),
	('Stan van Dijck', 'Netherlands', 'stan van dijck'),
	('Stan van Dijck', 'Netherlands', 'dijck'),
	('Guido Chávez', 'Paraguay', 'guido chavez'),
	('Guido Chávez', 'Paraguay', 'chavez'),
	('Josh Reid', 'Scotland', 'reid'),
	('Josh Reid', 'Scotland', 'josh reid'),
	('Agustín Guiffrey', 'Argentina', 'guiffrey'),
	('Agustín Guiffrey', 'Argentina', 'agustin guiffrey'),
	('Maksymilian Sitek', 'Poland', 'maksymilian sitek'),
	('Maksymilian Sitek', 'Poland', 'sitek'),
	('Anwar Elyounoussi', 'Norway', 'elyounoussi'),
	('Anwar Elyounoussi', 'Norway', 'anwar elyounoussi'),
	('Jorge Gática', 'Chile', 'gatica'),
	('Jorge Gática', 'Chile', 'jorge gatica'),
	('Aaron Bolger', 'Republic of Ireland', 'aaron bolger'),
	('Aaron Bolger', 'Republic of Ireland', 'bolger'),
	('Muamer Aljic', 'France', 'aljic'),
	('Muamer Aljic', 'France', 'muamer aljic'),
	('Li Hailong', 'China PR', 'hailong'),
	('Li Hailong', 'China PR', 'li hailong'),
	('Teodor Axinte', 'Romania', 'teodor axinte'),
	('Teodor Axinte', 'Romania', 'axinte'),
	('Juan Pablo Juárez', 'Mexico', 'juarez'),
	('Juan Pablo Juárez', 'Mexico', 'juan pablo juarez'),
	('Dan Kemp', 'England', 'dan kemp'),
	('Dan Kemp', 'England', 'kemp'),
	('Khaled Al Dubaysh', 'Saudi Arabia', 'dubaysh'),
	('Khaled Al Dubaysh', 'Saudi Arabia', 'khaled al dubaysh'),
	('Lee Jun', 'Korea Republic', 'lee jun'),
	('Lee Jun', 'Korea Republic', 'jun'),
	('Edwin Mosquera', 'Colombia', 'mosquera'),
	('Edwin Mosquera', 'Colombia', 'edwin mosquera'),
	('Leon Sopić', 'Croatia', 'leon sopic'),
	('Leon Sopić', 'Croatia', 'sopic'),
	('Juan Roa', 'Paraguay', 'roa'),
	('Juan Roa', 'Paraguay', 'juan roa'),
	('Ross Millen', 'Scotland', 'ross millen'),
	('Ross Millen', 'Scotland', 'millen'),
	('Ryan Barnett', 'England', 'barnett'),
	('Ryan Barnett', 'England', 'ryan barnett'),
	('Isaac Boye', 'Nigeria', 'boye'),
	('Isaac Boye', 'Nigeria', 'isaac boye'),
	('Daniel Ciobanu', 'Romania', 'ciobanu'),
	('Daniel Ciobanu', 'Romania', 'daniel ciobanu'),
	('Axel Grijalva', 'Mexico', 'axel grijalva'),
	('Axel Grijalva', 'Mexico', 'grijalva'),
	('Victor Torp', 'Denmark', 'torp'),
	('Victor Torp', 'Denmark', 'victor torp'),
	('Lucas Di Yorio', 'Argentina', 'lucas di yorio'),
	('Lucas Di Yorio', 'Argentina', 'yorio'),
	('Maarten Rieder', 'Netherlands', 'rieder'),
	('Maarten Rieder', 'Netherlands', 'maarten rieder'),
	('Andrei Sîntean', 'Romania', 'andrei sintean'),
	('Andrei Sîntean', 'Romania', 'sintean'),
	('Cristofer Salas', 'Chile', 'salas'),
	('Cristofer Salas', 'Chile', 'cristofer salas'),
	('Charlie Carter', 'England', 'carter'),
	('Charlie Carter', 'England', 'charlie carter'),
	('Gastón Suso', 'Argentina', 'suso'),
	('Gastón Suso', 'Argentina', 'gaston suso'),
	('Robert Grecu', 'Romania', 'grecu'),
	('Robert Grecu', 'Romania', 'robert grecu'),
	('Barry Maguire', 'Scotland', 'barry maguire'),
	('Barry Maguire', 'Scotland', 'maguire'),
	('Jamie Soule', 'England', 'jamie soule'),
	('Jamie Soule', 'England', 'soule'),
	('Emanuel Montejano', 'Mexico', 'montejano'),
	('Emanuel Montejano', 'Mexico', 'emanuel montejano'),
	('Joel Waterman', 'Canada', 'joel waterman'),
	('Joel Waterman', 'Canada', 'waterman'),
	('Marcelo Miño', 'Argentina', 'marcelo mino'),
	('Marcelo Miño', 'Argentina', 'mino'),
	('Abdullah Majrashi', 'Saudi Arabia', 'abdullah majrashi'),
	('Abdullah Majrashi', 'Saudi Arabia', 'majrashi'),
	('Boris Mathis', 'France', 'mathis'),
	('Boris Mathis', 'France', 'boris mathis'),
	('Tobías Donsanti', 'Argentina', 'donsanti'),
	('Tobías Donsanti', 'Argentina', 'tobias donsanti'),
	('Joey Jones', 'Northern Ireland', 'joey jones'),
	('Joey Jones', 'Northern Ireland', 'jones'),
	('Natanael Ntolla Thio', 'France', 'natanael ntolla thio'),
	('Natanael Ntolla Thio', 'France', 'thio'),
	('Izaack Powell', 'Australia', 'powell'),
	('Izaack Powell', 'Australia', 'izaack powell'),
	('Andy Burbano', 'Ecuador', 'andy burbano'),
	('Andy Burbano', 'Ecuador', 'burbano'),
	('Yannick Brugger', 'Germany', 'yannick brugger'),
	('Yannick Brugger', 'Germany', 'brugger'),
	('Jordan Slew', 'England', 'slew'),
	('Jordan Slew', 'England', 'jordan slew'),
	('Harrison Ashby', 'Scotland', 'ashby'),
	('Harrison Ashby', 'Scotland', 'harrison ashby'),
	('Jordi van Stappershoef', 'Netherlands', 'stappershoef'),
	('Jordi van Stappershoef', 'Netherlands', 'jordi van stappershoef'),
	('Kasper Thiesson Kristensen', 'Denmark', 'kristensen'),
	('Kasper Thiesson Kristensen', 'Denmark', 'kasper thiesson kristensen'),
	('Kyle Jameson', 'England', 'jameson'),
	('Kyle Jameson', 'England', 'kyle jameson'),
	('Hassan Tombakti', 'Saudi Arabia', 'hassan tombakti'),
	('Hassan Tombakti', 'Saudi Arabia', 'tombakti'),
	('George Nurse', 'England', 'nurse'),
	('George Nurse', 'England', 'george nurse'),
	('Jonas Dakir', 'Denmark', 'dakir'),
	('Jonas Dakir', 'Denmark', 'jonas dakir'),
	('Thomas Secchi', 'France', 'secchi'),
	('Thomas Secchi', 'France', 'thomas secchi'),
	('Liu Ruofan', 'China PR', 'liu ruofan'),
	('Liu Ruofan', 'China PR', 'ruofan'),
	('Cyril Zabou', 'France', 'zabou'),
	('Cyril Zabou', 'France', 'cyril zabou'),
	('Mao Hosoya', 'Japan', 'hosoya'),
	('Mao Hosoya', 'Japan', 'mao hosoya'),
	('Peter Bjur', 'Denmark', 'peter bjur'),
	('Peter Bjur', 'Denmark', 'bjur'),
	('Magnus Norman', 'England', 'magnus norman'),
	('Magnus Norman', 'England', 'norman'),
	('Stéphane Zobo', 'Cameroon', 'zobo'),
	('Stéphane Zobo', 'Cameroon', 'stephane zobo'),
	('Han Feng', 'China PR', 'han feng'),
	('Han Feng', 'China PR', 'feng'),
	('Óscar Millán', 'Mexico', 'millan'),
	('Óscar Millán', 'Mexico', 'oscar millan'),
	('Kosovar Sadiki', 'Canada', 'sadiki'),
	('Kosovar Sadiki', 'Canada', 'kosovar sadiki'),
	('Emanuel Cuevas', 'Argentina', 'cuevas'),
	('Emanuel Cuevas', 'Argentina', 'emanuel cuevas'),
	('James Tilley', 'England', 'james tilley'),
	('James Tilley', 'England', 'tilley'),
	('Daniel Wilmering', 'Australia', 'wilmering'),
	('Daniel Wilmering', 'Australia', 'daniel wilmering'),
	('Cendrim Kameraj', 'Kosovo', 'cendrim kameraj'),
	('Cendrim Kameraj', 'Kosovo', 'kameraj'),
	('Mohammed Al Wakid', 'Saudi Arabia', 'wakid'),
	('Mohammed Al Wakid', 'Saudi Arabia', 'mohammed al wakid'),
	('Fahad Al Harbi', 'Saudi Arabia', 'fahad al harbi'),
	('Fahad Al Harbi', 'Saudi Arabia', 'harbi'),
	('Max Fenger', 'Denmark', 'fenger'),
	('Max Fenger', 'Denmark', 'max fenger'),
	('Levente Bősz', 'Hungary', 'bosz'),
	('Levente Bősz', 'Hungary', 'levente bosz'),
	('Elis Isufi', 'Switzerland', 'isufi'),
	('Elis Isufi', 'Switzerland', 'elis isufi'),
	('Joël van Kaam', 'Netherlands', 'kaam'),
	('Joël van Kaam', 'Netherlands', 'joel van kaam'),
	('Yahia Fofana', 'France', 'fofana'),
	('Yahia Fofana', 'France', 'yahia fofana'),
	('Kyle Callan-McFadden', 'Republic of Ireland', 'kyle callanmcfadden'),
	('Kyle Callan-McFadden', 'Republic of Ireland', 'callanmcfadden'),
	('Ross Marshall', 'England', 'ross marshall'),
	('Ross Marshall', 'England', 'marshall'),
	('Jordan Brown', 'England', 'brown'),
	('Jordan Brown', 'England', 'jordan brown'),
	('Akin Famewo', 'England', 'akin famewo'),
	('Akin Famewo', 'England', 'famewo'),
	('Tom Holmes', 'England', 'holmes'),
	('Tom Holmes', 'England', 'tom holmes'),
	('Giuseppe Cuomo', 'Italy', 'giuseppe cuomo'),
	('Giuseppe Cuomo', 'Italy', 'cuomo'),
	('Oliver Villadsen', 'Denmark', 'villadsen'),
	('Oliver Villadsen', 'Denmark', 'oliver villadsen'),
	('Alexander Nadj', 'Sweden', 'nadj'),
	('Alexander Nadj', 'Sweden', 'alexander nadj'),
	('Alan Kerouedan', 'France', 'alan kerouedan'),
	('Alan Kerouedan', 'France', 'kerouedan'),
	('Jack Hindle', 'England', 'jack hindle'),
	('Jack Hindle', 'England', 'hindle'),
	('Jared Stroud', 'United States', 'jared stroud'),
	('Jared Stroud', 'United States', 'stroud'),
	('Taylor Allen', 'England', 'taylor allen'),
	('Taylor Allen', 'England', 'allen'),
	('Karim Saab', 'Venezuela', 'karim saab'),
	('Karim Saab', 'Venezuela', 'saab'),
	('Felix Seiwald', 'Austria', 'seiwald'),
	('Felix Seiwald', 'Austria', 'felix seiwald'),
	('Marcel Tanzmayr', 'Austria', 'marcel tanzmayr'),
	('Marcel Tanzmayr', 'Austria', 'tanzmayr'),
	('Toby Savin', 'England', 'toby savin'),
	('Toby Savin', 'England', 'savin'),
	('Ollie Kensdale', 'England', 'ollie kensdale'),
	('Ollie Kensdale', 'England', 'kensdale'),
	('Alaa Al Hajji', 'Saudi Arabia', 'alaa al hajji'),
	('Alaa Al Hajji', 'Saudi Arabia', 'hajji'),
	('Ștefan Cană', 'Romania', 'cana'),
	('Ștefan Cană', 'Romania', 'stefan cana'),
	('Oliver Petersen', 'Norway', 'oliver petersen'),
	('Oliver Petersen', 'Norway', 'petersen'),
	('Kosta Petratos', 'Australia', 'petratos'),
	('Kosta Petratos', 'Australia', 'kosta petratos'),
	('Jesse Edem Tugbenyo', 'Germany', 'jesse edem tugbenyo'),
	('Jesse Edem Tugbenyo', 'Germany', 'tugbenyo'),
	('Sebastian Bîrsan', 'Romania', 'sebastian birsan'),
	('Sebastian Bîrsan', 'Romania', 'birsan'),
	('Kashifu Bangunagande', 'Japan', 'kashifu bangunagande'),
	('Kashifu Bangunagande', 'Japan', 'bangunagande'),
	('Jack Emmett', 'England', 'jack emmett'),
	('Jack Emmett', 'England', 'emmett'),
	('Joshua Wehking', 'Germany', 'wehking'),
	('Joshua Wehking', 'Germany', 'joshua wehking'),
	('Thomas Mayer', 'Austria', 'mayer'),
	('Thomas Mayer', 'Austria', 'thomas mayer'),
	('Bartłomiej Wdowik', 'Poland', 'wdowik'),
	('Bartłomiej Wdowik', 'Poland', 'bartomiej wdowik'),
	('Georgie Kelly', 'Republic of Ireland', 'georgie kelly'),
	('Georgie Kelly', 'Republic of Ireland', 'kelly'),
	('Luke Spokes', 'England', 'spokes'),
	('Luke Spokes', 'England', 'luke spokes'),
	('Chae Gwang Hoon', 'Korea Republic', 'chae gwang hoon'),
	('Chae Gwang Hoon', 'Korea Republic', 'hoon'),
	('Joel Quintero', 'Ecuador', 'joel quintero'),
	('Joel Quintero', 'Ecuador', 'quintero'),
	('Amar Sejdič', 'Germany', 'sejdic'),
	('Amar Sejdič', 'Germany', 'amar sejdic'),
	('Innes Cameron', 'Scotland', 'innes cameron'),
	('Innes Cameron', 'Scotland', 'cameron'),
	('Daiju Sasaki', 'Japan', 'daiju sasaki'),
	('Daiju Sasaki', 'Japan', 'sasaki')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';