INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Adrián Leites', 'Uruguay', 'player'),
	('Erik Friberg', 'Sweden', 'player'),
	('Karim Azamoum', 'France', 'player'),
	('Aleksandar Ignjovski', 'Serbia', 'player'),
	('Imad Khalili', 'Palestine', 'player'),
	('Ricardo Salcedo', 'Peru', 'player'),
	('Guillermo de los Santos', 'Uruguay', 'player'),
	('Néstor Vidrio', 'Mexico', 'player'),
	('Fabian Menig', 'Germany', 'player'),
	('Tomás Asta-Buruaga', 'Chile', 'player'),
	('Adedeji Oshilaja', 'England', 'player'),
	('Rustamzhon Ashurmatov', 'Uzbekistan', 'player'),
	('Luan', 'Brazil', 'player'),
	('Yukitoshi Ito', 'Japan', 'player'),
	('José Andrés Martínez', 'Venezuela', 'player'),
	('Leonardo Flores', 'Venezuela', 'player'),
	('Shuto Yamamoto', 'Japan', 'player'),
	('Marvin Loría', 'Costa Rica', 'player'),
	('Luis Chávez', 'Mexico', 'player'),
	('Naoki Nomura', 'Japan', 'player'),
	('Farouk Chafaï', 'Algeria', 'player'),
	('Kim Sung Hwan', 'Korea Republic', 'player'),
	('Jens Odgaard', 'Denmark', 'player'),
	('Moreto Cassamá', 'Guinea Bissau', 'player'),
	('Jorn Brondeel', 'Belgium', 'player'),
	('Gavin Whyte', 'Northern Ireland', 'player'),
	('Lassana Faye', 'Netherlands', 'player'),
	('Aristote Nkaka', 'Belgium', 'player'),
	('Timothé Cognat', 'France', 'player'),
	('Charles Abi', 'France', 'player'),
	('Yohei Takaoka', 'Japan', 'player'),
	('Alimami Gory', 'France', 'player'),
	('Adriano Castanheira', 'Portugal', 'player'),
	('Carlos Rivero', 'Venezuela', 'player'),
	('Sergiy Bolbat', 'Ukraine', 'player'),
	('Andrei Radu', 'Romania', 'player'),
	('Ahmed Issa Koro Koné', 'Ivory Coast', 'player'),
	('Bogdan Milovanov', 'Ukraine', 'player'),
	('Marlon Hairston', 'United States', 'player'),
	('Nikita Haikin', 'Russia', 'player'),
	('Ivan Kecojević', 'Montenegro', 'player'),
	('David Worrall', 'England', 'player'),
	('Aboubakary Koita', 'Belgium', 'player'),
	('Abner', 'Brazil', 'player'),
	('Erce Kardeşler', 'Turkey', 'player'),
	('Ibou Touray', 'Gambia', 'player'),
	('Yankouba Jarju', 'Gambia', 'player'),
	('Patrick Sontheimer', 'Germany', 'player'),
	('Peter Kurzweg', 'Germany', 'player'),
	('Alexis Peña', 'Mexico', 'player'),
	('Andrés López', 'Ecuador', 'player'),
	('Jakub Żubrowski', 'Poland', 'player'),
	('Ken Tokura', 'Japan', 'player'),
	('Djordje Mihailovic', 'United States', 'player'),
	('Takuya Aoki', 'Japan', 'player'),
	('Dirk Abels', 'Netherlands', 'player'),
	('Georgiy Zhukov', 'Kazakhstan', 'player'),
	('Jair Torrico', 'Bolivia', 'player'),
	('Tomoya Ugajin', 'Japan', 'player'),
	('Gustavo Cortéz', 'Ecuador', 'player'),
	('André Moreira', 'Portugal', 'player'),
	('Curtis Edwards', 'England', 'player'),
	('Eduardo Fereira', 'Venezuela', 'player'),
	('Nico Antonitsch', 'Austria', 'player'),
	('Luca Zidane', 'France', 'player'),
	('Jorge Fernandes', 'Portugal', 'player'),
	('Murray Davidson', 'Scotland', 'player'),
	('Salih Dursun', 'Turkey', 'player'),
	('Luka Adžić', 'Serbia', 'player'),
	('Adam Lundqvist', 'Sweden', 'player'),
	('Ramazan Civelek', 'Turkey', 'player'),
	('Lucas Cunha', 'Brazil', 'player'),
	('Justin Shonga', 'Zambia', 'player'),
	('Loïc Nestor', 'France', 'player'),
	('Matías Cano', 'Argentina', 'player'),
	('Andi Zeqiri', 'Switzerland', 'player'),
	('Naoki Ishihara', 'Japan', 'player'),
	('Josh Williams', 'United States', 'player'),
	('Petrișor Petrescu', 'Romania', 'player'),
	('William Rémy', 'France', 'player'),
	('Diego Valencia', 'Chile', 'player'),
	('Felipe Román', 'Colombia', 'player'),
	('Raphael Rossi', 'Brazil', 'player'),
	('John Ogu', 'Nigeria', 'player'),
	('Ivan Franjić', 'Australia', 'player'),
	('Gwion Edwards', 'Wales', 'player'),
	('Paul Hanlon', 'Scotland', 'player'),
	('Benjamin Nygren', 'Sweden', 'player'),
	('Quentin Daubin', 'France', 'player'),
	('Jean Onana', 'Cameroon', 'player'),
	('Diogo Calila', 'Portugal', 'player'),
	('Yoshihiro Nakano', 'Japan', 'player'),
	('Jasmin Fejzić', 'Bosnia Herzegovina', 'player'),
	('Léo Schwechlen', 'France', 'player'),
	('Max Svensson', 'Sweden', 'player'),
	('Emil Riis', 'Denmark', 'player'),
	('Jimmy Ryan', 'Republic of Ireland', 'player'),
	('Jason Pendant', 'France', 'player'),
	('Mirkan Aydin', 'Germany', 'player'),
	('Fabian Reese', 'Germany', 'player'),
	('Takuya Iwanami', 'Japan', 'player'),
	('August Erlingmark', 'Sweden', 'player'),
	('Simon Strand', 'Sweden', 'player'),
	('Salvador Agra', 'Portugal', 'player'),
	('Tom Beugelsdijk', 'Netherlands', 'player'),
	('Tim Rieder', 'Germany', 'player'),
	('Jordan Willis', 'England', 'player'),
	('Elliot Lee', 'England', 'player'),
	('Josh Morris', 'England', 'player'),
	('Marvin Stefaniak', 'Germany', 'player'),
	('Peet Bijen', 'Netherlands', 'player'),
	('Connor Ogilvie', 'England', 'player'),
	('Aboubakar Keita', 'Ivory Coast', 'player'),
	('Yusuke Goto', 'Japan', 'player'),
	('Fábio Vieira', 'Portugal', 'player'),
	('David Caiado', 'Portugal', 'player'),
	('Mauro Ortíz', 'Argentina', 'player'),
	('Yang Liyu', 'China PR', 'player'),
	('Anthony Sauthier', 'Switzerland', 'player'),
	('Geovanny Nazareno', 'Ecuador', 'player'),
	('Jake Forster-Caskey', 'England', 'player'),
	('Giorgi Merebashvili', 'Georgia', 'player'),
	('Park Dae Han', 'Korea Republic', 'player'),
	('Sam McQueen', 'England', 'player'),
	('Alex Suárez', 'Spain', 'player'),
	('James Garner', 'England', 'player'),
	('Morten Frendrup', 'Denmark', 'player'),
	('Ignacio Pallas', 'Uruguay', 'player'),
	('Paweł Stolarski', 'Poland', 'player'),
	('Joona Toivio', 'Finland', 'player'),
	('Jordan Storey', 'England', 'player'),
	('Tommie Hoban', 'Republic of Ireland', 'player'),
	('Robert Hernández', 'Venezuela', 'player'),
	('Alfons Sampsted', 'Iceland', 'player'),
	('Elias Andersson', 'Sweden', 'player'),
	('Jason Davidson', 'Australia', 'player'),
	('Mihai Velisar', 'Romania', 'player'),
	('Yuto Misao', 'Japan', 'player'),
	('Riku Riski', 'Finland', 'player'),
	('Keziah Veendorp', 'Netherlands', 'player'),
	('Sory Kaba', 'Guinea', 'player'),
	('Vladimir Castellón', 'Bolivia', 'player'),
	('Eliel Peretz', 'Israel', 'player'),
	('Victor Mpindi Ekani', 'Cameroon', 'player'),
	('Willy Semedo', 'France', 'player'),
	('Florian Valot', 'France', 'player'),
	('Arial Mendy', 'Senegal', 'player'),
	('Anthony Osorio', 'Peru', 'player'),
	('Max Power', 'England', 'player'),
	('William Eskelinen', 'Sweden', 'player'),
	('Filip Rogić', 'Sweden', 'player'),
	('Robert Herrera', 'Uruguay', 'player'),
	('Arjan Swinkels', 'Netherlands', 'player'),
	('Mohamed Benkhemassa', 'Algeria', 'player'),
	('Bobby Shuttleworth', 'United States', 'player'),
	('Sam Winnall', 'England', 'player'),
	('Kristoffer Haraldseid', 'Norway', 'player'),
	('Mitja Lotrič', 'Slovenia', 'player'),
	('Rémi Mulumba', 'DR Congo', 'player'),
	('Ismael Quílez', 'Argentina', 'player'),
	('David Bates', 'Scotland', 'player'),
	('Zac MacMath', 'United States', 'player'),
	('Adri Castellano', 'Spain', 'player'),
	('Lorenzo Andrenacci', 'Italy', 'player'),
	('Ahn Yong Woo', 'Korea Republic', 'player'),
	('Andrei Vlad', 'Romania', 'player'),
	('Brandon Mason', 'England', 'player'),
	('Matheus Sávio', 'Brazil', 'player'),
	('Renzo Zambrano', 'Venezuela', 'player'),
	('Valmir Sulejmani', 'Kosovo', 'player'),
	('Kgotso Moleko', 'South Africa', 'player'),
	('Florian Rieder', 'Austria', 'player'),
	('Joao Rojas', 'Ecuador', 'player'),
	('Madallah Al Olayan', 'Saudi Arabia', 'player'),
	('Riki', 'Spain', 'player'),
	('Grant Ward', 'England', 'player'),
	('Keijiro Ogawa', 'Japan', 'player'),
	('Žarko Udovičić', 'Serbia', 'player'),
	('Sebastian Ohlsson', 'Sweden', 'player'),
	('Lukas Jäger', 'Austria', 'player'),
	('Peter Gál-Andrezly', 'Slovakia', 'player'),
	('Yuji Ono', 'Japan', 'player'),
	('Jake Hesketh', 'England', 'player'),
	('Hwang Hyun Soo', 'Korea Republic', 'player'),
	('Stephan Hain', 'Germany', 'player'),
	('Jamal Bajandouh', 'Saudi Arabia', 'player'),
	('Enriko Papa', 'Albania', 'player'),
	('Darius Charles', 'England', 'player'),
	('Facundo Cambeses', 'Argentina', 'player'),
	('Freddie Sears', 'England', 'player'),
	('Ibrahim Alhassan', 'Nigeria', 'player'),
	('Tomasz Jodłowiec', 'Poland', 'player'),
	('Yeon Je Woon', 'Korea Republic', 'player'),
	('Ali Şaşal Vural', 'Turkey', 'player'),
	('Max Burgess', 'Australia', 'player'),
	('Kenan Özer', 'Turkey', 'player'),
	('Ben Close', 'England', 'player'),
	('Simon Rhein', 'Germany', 'player'),
	('Manuel Farrona Pulido', 'Germany', 'player'),
	('Sven Schipplock', 'Germany', 'player'),
	('Dennis Telgenkamp', 'Netherlands', 'player'),
	('Mauro Da Luz', 'Uruguay', 'player'),
	('Jordan Leborgne', 'France', 'player'),
	('Saša Balić', 'Montenegro', 'player'),
	('Larry Angulo', 'Colombia', 'player'),
	('Dominik Holec', 'Slovakia', 'player'),
	('Henri Saivet', 'Senegal', 'player'),
	('Kike Pérez', 'Spain', 'player'),
	('Ben Woodburn', 'Wales', 'player'),
	('Patrick Joosten', 'Netherlands', 'player'),
	('Nikoloz Ninua', 'Georgia', 'player'),
	('Hubert Matynia', 'Poland', 'player'),
	('Herbie Kane', 'England', 'player'),
	('Mackay', 'Spain', 'player'),
	('Mihai Roman', 'Romania', 'player'),
	('Juan Aguilar', 'Paraguay', 'player'),
	('Jordan Faucher', 'France', 'player'),
	('Gabriel Hachen', 'Argentina', 'player'),
	('Jorge Grant', 'England', 'player'),
	('Grant Leadbitter', 'England', 'player'),
	('El Bilal Touré', 'Mali', 'player'),
	('Tsubasa Endoh', 'Japan', 'player'),
	('Jairo Torres', 'Mexico', 'player'),
	('Tsuyoshi Watanabe', 'Japan', 'player'),
	('Mohammed Abubakari', 'Ghana', 'player'),
	('Denis Prychynenko', 'Germany', 'player'),
	('Alexander Groiß', 'Germany', 'player'),
	('Josip Radošević', 'Croatia', 'player'),
	('Cadete', 'Spain', 'player'),
	('Flynn Downes', 'England', 'player'),
	('Antonio Donnarumma', 'Italy', 'player'),
	('Jordi Osei-Tutu', 'England', 'player'),
	('Jack Simpson', 'England', 'player'),
	('Josh Laurent', 'England', 'player'),
	('Lucas Melano', 'Argentina', 'player'),
	('Tom Flanagan', 'Northern Ireland', 'player'),
	('Nick Besler', 'United States', 'player'),
	('José Ángel', 'Spain', 'player'),
	('Kristoffer Velde', 'Norway', 'player'),
	('Stefan Haudum', 'Austria', 'player'),
	('Kazuma Watanabe', 'Japan', 'player'),
	('Daniel Barlaser', 'England', 'player'),
	('Jack Whatmough', 'England', 'player'),
	('Guram Giorbelidze', 'Georgia', 'player'),
	('Liberto Beltrán', 'Spain', 'player'),
	('Julio Nava', 'Mexico', 'player'),
	('Grego Sierra', 'Spain', 'player'),
	('Robin Krauße', 'Germany', 'player'),
	('Evan Bush', 'United States', 'player'),
	('Jindřich Staněk', 'Czech Republic', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Adrián Leites', 'Uruguay', 'adrian leites'),
	('Adrián Leites', 'Uruguay', 'leites'),
	('Erik Friberg', 'Sweden', 'erik friberg'),
	('Erik Friberg', 'Sweden', 'friberg'),
	('Karim Azamoum', 'France', 'azamoum'),
	('Karim Azamoum', 'France', 'karim azamoum'),
	('Aleksandar Ignjovski', 'Serbia', 'aleksandar ignjovski'),
	('Aleksandar Ignjovski', 'Serbia', 'ignjovski'),
	('Imad Khalili', 'Palestine', 'khalili'),
	('Imad Khalili', 'Palestine', 'imad khalili'),
	('Ricardo Salcedo', 'Peru', 'salcedo'),
	('Ricardo Salcedo', 'Peru', 'ricardo salcedo'),
	('Guillermo de los Santos', 'Uruguay', 'guillermo de los santos'),
	('Guillermo de los Santos', 'Uruguay', 'santos'),
	('Néstor Vidrio', 'Mexico', 'nestor vidrio'),
	('Néstor Vidrio', 'Mexico', 'vidrio'),
	('Fabian Menig', 'Germany', 'menig'),
	('Fabian Menig', 'Germany', 'fabian menig'),
	('Tomás Asta-Buruaga', 'Chile', 'tomas astaburuaga'),
	('Tomás Asta-Buruaga', 'Chile', 'astaburuaga'),
	('Adedeji Oshilaja', 'England', 'oshilaja'),
	('Adedeji Oshilaja', 'England', 'adedeji oshilaja'),
	('Rustamzhon Ashurmatov', 'Uzbekistan', 'rustamzhon ashurmatov'),
	('Rustamzhon Ashurmatov', 'Uzbekistan', 'ashurmatov'),
	('Luan', 'Brazil', 'luan'),
	('Yukitoshi Ito', 'Japan', 'yukitoshi ito'),
	('Yukitoshi Ito', 'Japan', 'ito'),
	('José Andrés Martínez', 'Venezuela', 'jose andres martinez'),
	('José Andrés Martínez', 'Venezuela', 'martinez'),
	('Leonardo Flores', 'Venezuela', 'leonardo flores'),
	('Leonardo Flores', 'Venezuela', 'flores'),
	('Shuto Yamamoto', 'Japan', 'yamamoto'),
	('Shuto Yamamoto', 'Japan', 'shuto yamamoto'),
	('Marvin Loría', 'Costa Rica', 'marvin loria'),
	('Marvin Loría', 'Costa Rica', 'loria'),
	('Luis Chávez', 'Mexico', 'chavez'),
	('Luis Chávez', 'Mexico', 'luis chavez'),
	('Naoki Nomura', 'Japan', 'nomura'),
	('Naoki Nomura', 'Japan', 'naoki nomura'),
	('Farouk Chafaï', 'Algeria', 'farouk chafai'),
	('Farouk Chafaï', 'Algeria', 'chafai'),
	('Kim Sung Hwan', 'Korea Republic', 'hwan'),
	('Kim Sung Hwan', 'Korea Republic', 'kim sung hwan'),
	('Jens Odgaard', 'Denmark', 'jens odgaard'),
	('Jens Odgaard', 'Denmark', 'odgaard'),
	('Moreto Cassamá', 'Guinea Bissau', 'moreto cassama'),
	('Moreto Cassamá', 'Guinea Bissau', 'cassama'),
	('Jorn Brondeel', 'Belgium', 'brondeel'),
	('Jorn Brondeel', 'Belgium', 'jorn brondeel'),
	('Gavin Whyte', 'Northern Ireland', 'whyte'),
	('Gavin Whyte', 'Northern Ireland', 'gavin whyte'),
	('Lassana Faye', 'Netherlands', 'lassana faye'),
	('Lassana Faye', 'Netherlands', 'faye'),
	('Aristote Nkaka', 'Belgium', 'nkaka'),
	('Aristote Nkaka', 'Belgium', 'aristote nkaka'),
	('Timothé Cognat', 'France', 'timothe cognat'),
	('Timothé Cognat', 'France', 'cognat'),
	('Charles Abi', 'France', 'charles abi'),
	('Charles Abi', 'France', 'abi'),
	('Yohei Takaoka', 'Japan', 'yohei takaoka'),
	('Yohei Takaoka', 'Japan', 'takaoka'),
	('Alimami Gory', 'France', 'gory'),
	('Alimami Gory', 'France', 'alimami gory'),
	('Adriano Castanheira', 'Portugal', 'castanheira'),
	('Adriano Castanheira', 'Portugal', 'adriano castanheira'),
	('Carlos Rivero', 'Venezuela', 'carlos rivero'),
	('Carlos Rivero', 'Venezuela', 'rivero'),
	('Sergiy Bolbat', 'Ukraine', 'bolbat'),
	('Sergiy Bolbat', 'Ukraine', 'sergiy bolbat'),
	('Andrei Radu', 'Romania', 'andrei radu'),
	('Andrei Radu', 'Romania', 'radu'),
	('Ahmed Issa Koro Koné', 'Ivory Coast', 'kone'),
	('Ahmed Issa Koro Koné', 'Ivory Coast', 'ahmed issa koro kone'),
	('Bogdan Milovanov', 'Ukraine', 'bogdan milovanov'),
	('Bogdan Milovanov', 'Ukraine', 'milovanov'),
	('Marlon Hairston', 'United States', 'hairston'),
	('Marlon Hairston', 'United States', 'marlon hairston'),
	('Nikita Haikin', 'Russia', 'nikita haikin'),
	('Nikita Haikin', 'Russia', 'haikin'),
	('Ivan Kecojević', 'Montenegro', 'ivan kecojevic'),
	('Ivan Kecojević', 'Montenegro', 'kecojevic'),
	('David Worrall', 'England', 'david worrall'),
	('David Worrall', 'England', 'worrall'),
	('Aboubakary Koita', 'Belgium', 'aboubakary koita'),
	('Aboubakary Koita', 'Belgium', 'koita'),
	('Abner', 'Brazil', 'abner'),
	('Erce Kardeşler', 'Turkey', 'kardesler'),
	('Erce Kardeşler', 'Turkey', 'erce kardesler'),
	('Ibou Touray', 'Gambia', 'ibou touray'),
	('Ibou Touray', 'Gambia', 'touray'),
	('Yankouba Jarju', 'Gambia', 'jarju'),
	('Yankouba Jarju', 'Gambia', 'yankouba jarju'),
	('Patrick Sontheimer', 'Germany', 'sontheimer'),
	('Patrick Sontheimer', 'Germany', 'patrick sontheimer'),
	('Peter Kurzweg', 'Germany', 'peter kurzweg'),
	('Peter Kurzweg', 'Germany', 'kurzweg'),
	('Alexis Peña', 'Mexico', 'alexis pena'),
	('Alexis Peña', 'Mexico', 'pena'),
	('Andrés López', 'Ecuador', 'lopez'),
	('Andrés López', 'Ecuador', 'andres lopez'),
	('Jakub Żubrowski', 'Poland', 'zubrowski'),
	('Jakub Żubrowski', 'Poland', 'jakub zubrowski'),
	('Ken Tokura', 'Japan', 'ken tokura'),
	('Ken Tokura', 'Japan', 'tokura'),
	('Djordje Mihailovic', 'United States', 'djordje mihailovic'),
	('Djordje Mihailovic', 'United States', 'mihailovic'),
	('Takuya Aoki', 'Japan', 'aoki'),
	('Takuya Aoki', 'Japan', 'takuya aoki'),
	('Dirk Abels', 'Netherlands', 'abels'),
	('Dirk Abels', 'Netherlands', 'dirk abels'),
	('Georgiy Zhukov', 'Kazakhstan', 'georgiy zhukov'),
	('Georgiy Zhukov', 'Kazakhstan', 'zhukov'),
	('Jair Torrico', 'Bolivia', 'jair torrico'),
	('Jair Torrico', 'Bolivia', 'torrico'),
	('Tomoya Ugajin', 'Japan', 'ugajin'),
	('Tomoya Ugajin', 'Japan', 'tomoya ugajin'),
	('Gustavo Cortéz', 'Ecuador', 'cortez'),
	('Gustavo Cortéz', 'Ecuador', 'gustavo cortez'),
	('André Moreira', 'Portugal', 'andre moreira'),
	('André Moreira', 'Portugal', 'moreira'),
	('Curtis Edwards', 'England', 'edwards'),
	('Curtis Edwards', 'England', 'curtis edwards'),
	('Eduardo Fereira', 'Venezuela', 'eduardo fereira'),
	('Eduardo Fereira', 'Venezuela', 'fereira'),
	('Nico Antonitsch', 'Austria', 'antonitsch'),
	('Nico Antonitsch', 'Austria', 'nico antonitsch'),
	('Luca Zidane', 'France', 'zidane'),
	('Luca Zidane', 'France', 'luca zidane'),
	('Jorge Fernandes', 'Portugal', 'jorge fernandes'),
	('Jorge Fernandes', 'Portugal', 'fernandes'),
	('Murray Davidson', 'Scotland', 'murray davidson'),
	('Murray Davidson', 'Scotland', 'davidson'),
	('Salih Dursun', 'Turkey', 'dursun'),
	('Salih Dursun', 'Turkey', 'salih dursun'),
	('Luka Adžić', 'Serbia', 'adzic'),
	('Luka Adžić', 'Serbia', 'luka adzic'),
	('Adam Lundqvist', 'Sweden', 'adam lundqvist'),
	('Adam Lundqvist', 'Sweden', 'lundqvist'),
	('Ramazan Civelek', 'Turkey', 'civelek'),
	('Ramazan Civelek', 'Turkey', 'ramazan civelek'),
	('Lucas Cunha', 'Brazil', 'cunha'),
	('Lucas Cunha', 'Brazil', 'lucas cunha'),
	('Justin Shonga', 'Zambia', 'shonga'),
	('Justin Shonga', 'Zambia', 'justin shonga'),
	('Loïc Nestor', 'France', 'loic nestor'),
	('Loïc Nestor', 'France', 'nestor'),
	('Matías Cano', 'Argentina', 'matias cano'),
	('Matías Cano', 'Argentina', 'cano'),
	('Andi Zeqiri', 'Switzerland', 'andi zeqiri'),
	('Andi Zeqiri', 'Switzerland', 'zeqiri'),
	('Naoki Ishihara', 'Japan', 'ishihara'),
	('Naoki Ishihara', 'Japan', 'naoki ishihara'),
	('Josh Williams', 'United States', 'josh williams'),
	('Josh Williams', 'United States', 'williams'),
	('Petrișor Petrescu', 'Romania', 'petrisor petrescu'),
	('Petrișor Petrescu', 'Romania', 'petrescu'),
	('William Rémy', 'France', 'remy'),
	('William Rémy', 'France', 'william remy'),
	('Diego Valencia', 'Chile', 'diego valencia'),
	('Diego Valencia', 'Chile', 'valencia'),
	('Felipe Román', 'Colombia', 'roman'),
	('Felipe Román', 'Colombia', 'felipe roman'),
	('Raphael Rossi', 'Brazil', 'raphael rossi'),
	('Raphael Rossi', 'Brazil', 'rossi'),
	('John Ogu', 'Nigeria', 'john ogu'),
	('John Ogu', 'Nigeria', 'ogu'),
	('Ivan Franjić', 'Australia', 'ivan franjic'),
	('Ivan Franjić', 'Australia', 'franjic'),
	('Gwion Edwards', 'Wales', 'edwards'),
	('Gwion Edwards', 'Wales', 'gwion edwards'),
	('Paul Hanlon', 'Scotland', 'hanlon'),
	('Paul Hanlon', 'Scotland', 'paul hanlon'),
	('Benjamin Nygren', 'Sweden', 'benjamin nygren'),
	('Benjamin Nygren', 'Sweden', 'nygren'),
	('Quentin Daubin', 'France', 'daubin'),
	('Quentin Daubin', 'France', 'quentin daubin'),
	('Jean Onana', 'Cameroon', 'onana'),
	('Jean Onana', 'Cameroon', 'jean onana'),
	('Diogo Calila', 'Portugal', 'calila'),
	('Diogo Calila', 'Portugal', 'diogo calila'),
	('Yoshihiro Nakano', 'Japan', 'yoshihiro nakano'),
	('Yoshihiro Nakano', 'Japan', 'nakano'),
	('Jasmin Fejzić', 'Bosnia Herzegovina', 'jasmin fejzic'),
	('Jasmin Fejzić', 'Bosnia Herzegovina', 'fejzic'),
	('Léo Schwechlen', 'France', 'leo schwechlen'),
	('Léo Schwechlen', 'France', 'schwechlen'),
	('Max Svensson', 'Sweden', 'max svensson'),
	('Max Svensson', 'Sweden', 'svensson'),
	('Emil Riis', 'Denmark', 'emil riis'),
	('Emil Riis', 'Denmark', 'riis'),
	('Jimmy Ryan', 'Republic of Ireland', 'jimmy ryan'),
	('Jimmy Ryan', 'Republic of Ireland', 'ryan'),
	('Jason Pendant', 'France', 'jason pendant'),
	('Jason Pendant', 'France', 'pendant'),
	('Mirkan Aydin', 'Germany', 'aydin'),
	('Mirkan Aydin', 'Germany', 'mirkan aydin'),
	('Fabian Reese', 'Germany', 'reese'),
	('Fabian Reese', 'Germany', 'fabian reese'),
	('Takuya Iwanami', 'Japan', 'takuya iwanami'),
	('Takuya Iwanami', 'Japan', 'iwanami'),
	('August Erlingmark', 'Sweden', 'august erlingmark'),
	('August Erlingmark', 'Sweden', 'erlingmark'),
	('Simon Strand', 'Sweden', 'simon strand'),
	('Simon Strand', 'Sweden', 'strand'),
	('Salvador Agra', 'Portugal', 'agra'),
	('Salvador Agra', 'Portugal', 'salvador agra'),
	('Tom Beugelsdijk', 'Netherlands', 'tom beugelsdijk'),
	('Tom Beugelsdijk', 'Netherlands', 'beugelsdijk'),
	('Tim Rieder', 'Germany', 'tim rieder'),
	('Tim Rieder', 'Germany', 'rieder'),
	('Jordan Willis', 'England', 'willis'),
	('Jordan Willis', 'England', 'jordan willis'),
	('Elliot Lee', 'England', 'elliot lee'),
	('Elliot Lee', 'England', 'lee'),
	('Josh Morris', 'England', 'morris'),
	('Josh Morris', 'England', 'josh morris'),
	('Marvin Stefaniak', 'Germany', 'marvin stefaniak'),
	('Marvin Stefaniak', 'Germany', 'stefaniak'),
	('Peet Bijen', 'Netherlands', 'peet bijen'),
	('Peet Bijen', 'Netherlands', 'bijen'),
	('Connor Ogilvie', 'England', 'connor ogilvie'),
	('Connor Ogilvie', 'England', 'ogilvie'),
	('Aboubakar Keita', 'Ivory Coast', 'aboubakar keita'),
	('Aboubakar Keita', 'Ivory Coast', 'keita'),
	('Yusuke Goto', 'Japan', 'yusuke goto'),
	('Yusuke Goto', 'Japan', 'goto'),
	('Fábio Vieira', 'Portugal', 'vieira'),
	('Fábio Vieira', 'Portugal', 'fabio vieira'),
	('David Caiado', 'Portugal', 'david caiado'),
	('David Caiado', 'Portugal', 'caiado'),
	('Mauro Ortíz', 'Argentina', 'ortiz'),
	('Mauro Ortíz', 'Argentina', 'mauro ortiz'),
	('Yang Liyu', 'China PR', 'yang liyu'),
	('Yang Liyu', 'China PR', 'liyu'),
	('Anthony Sauthier', 'Switzerland', 'sauthier'),
	('Anthony Sauthier', 'Switzerland', 'anthony sauthier'),
	('Geovanny Nazareno', 'Ecuador', 'nazareno'),
	('Geovanny Nazareno', 'Ecuador', 'geovanny nazareno'),
	('Jake Forster-Caskey', 'England', 'forstercaskey'),
	('Jake Forster-Caskey', 'England', 'jake forstercaskey'),
	('Giorgi Merebashvili', 'Georgia', 'giorgi merebashvili'),
	('Giorgi Merebashvili', 'Georgia', 'merebashvili'),
	('Park Dae Han', 'Korea Republic', 'park dae han'),
	('Park Dae Han', 'Korea Republic', 'han'),
	('Sam McQueen', 'England', 'sam mcqueen'),
	('Sam McQueen', 'England', 'mcqueen'),
	('Alex Suárez', 'Spain', 'suarez'),
	('Alex Suárez', 'Spain', 'alex suarez'),
	('James Garner', 'England', 'james garner'),
	('James Garner', 'England', 'garner'),
	('Morten Frendrup', 'Denmark', 'morten frendrup'),
	('Morten Frendrup', 'Denmark', 'frendrup'),
	('Ignacio Pallas', 'Uruguay', 'ignacio pallas'),
	('Ignacio Pallas', 'Uruguay', 'pallas'),
	('Paweł Stolarski', 'Poland', 'pawe stolarski'),
	('Paweł Stolarski', 'Poland', 'stolarski'),
	('Joona Toivio', 'Finland', 'joona toivio'),
	('Joona Toivio', 'Finland', 'toivio'),
	('Jordan Storey', 'England', 'storey'),
	('Jordan Storey', 'England', 'jordan storey'),
	('Tommie Hoban', 'Republic of Ireland', 'tommie hoban'),
	('Tommie Hoban', 'Republic of Ireland', 'hoban'),
	('Robert Hernández', 'Venezuela', 'robert hernandez'),
	('Robert Hernández', 'Venezuela', 'hernandez'),
	('Alfons Sampsted', 'Iceland', 'alfons sampsted'),
	('Alfons Sampsted', 'Iceland', 'sampsted'),
	('Elias Andersson', 'Sweden', 'elias andersson'),
	('Elias Andersson', 'Sweden', 'andersson'),
	('Jason Davidson', 'Australia', 'jason davidson'),
	('Jason Davidson', 'Australia', 'davidson'),
	('Mihai Velisar', 'Romania', 'velisar'),
	('Mihai Velisar', 'Romania', 'mihai velisar'),
	('Yuto Misao', 'Japan', 'yuto misao'),
	('Yuto Misao', 'Japan', 'misao'),
	('Riku Riski', 'Finland', 'riski'),
	('Riku Riski', 'Finland', 'riku riski'),
	('Keziah Veendorp', 'Netherlands', 'veendorp'),
	('Keziah Veendorp', 'Netherlands', 'keziah veendorp'),
	('Sory Kaba', 'Guinea', 'sory kaba'),
	('Sory Kaba', 'Guinea', 'kaba'),
	('Vladimir Castellón', 'Bolivia', 'vladimir castellon'),
	('Vladimir Castellón', 'Bolivia', 'castellon'),
	('Eliel Peretz', 'Israel', 'peretz'),
	('Eliel Peretz', 'Israel', 'eliel peretz'),
	('Victor Mpindi Ekani', 'Cameroon', 'ekani'),
	('Victor Mpindi Ekani', 'Cameroon', 'victor mpindi ekani'),
	('Willy Semedo', 'France', 'semedo'),
	('Willy Semedo', 'France', 'willy semedo'),
	('Florian Valot', 'France', 'florian valot'),
	('Florian Valot', 'France', 'valot'),
	('Arial Mendy', 'Senegal', 'mendy'),
	('Arial Mendy', 'Senegal', 'arial mendy'),
	('Anthony Osorio', 'Peru', 'osorio'),
	('Anthony Osorio', 'Peru', 'anthony osorio'),
	('Max Power', 'England', 'power'),
	('Max Power', 'England', 'max power'),
	('William Eskelinen', 'Sweden', 'eskelinen'),
	('William Eskelinen', 'Sweden', 'william eskelinen'),
	('Filip Rogić', 'Sweden', 'rogic'),
	('Filip Rogić', 'Sweden', 'filip rogic'),
	('Robert Herrera', 'Uruguay', 'herrera'),
	('Robert Herrera', 'Uruguay', 'robert herrera'),
	('Arjan Swinkels', 'Netherlands', 'arjan swinkels'),
	('Arjan Swinkels', 'Netherlands', 'swinkels'),
	('Mohamed Benkhemassa', 'Algeria', 'mohamed benkhemassa'),
	('Mohamed Benkhemassa', 'Algeria', 'benkhemassa'),
	('Bobby Shuttleworth', 'United States', 'shuttleworth'),
	('Bobby Shuttleworth', 'United States', 'bobby shuttleworth'),
	('Sam Winnall', 'England', 'sam winnall'),
	('Sam Winnall', 'England', 'winnall'),
	('Kristoffer Haraldseid', 'Norway', 'haraldseid'),
	('Kristoffer Haraldseid', 'Norway', 'kristoffer haraldseid'),
	('Mitja Lotrič', 'Slovenia', 'mitja lotric'),
	('Mitja Lotrič', 'Slovenia', 'lotric'),
	('Rémi Mulumba', 'DR Congo', 'mulumba'),
	('Rémi Mulumba', 'DR Congo', 'remi mulumba'),
	('Ismael Quílez', 'Argentina', 'ismael quilez'),
	('Ismael Quílez', 'Argentina', 'quilez'),
	('David Bates', 'Scotland', 'david bates'),
	('David Bates', 'Scotland', 'bates'),
	('Zac MacMath', 'United States', 'zac macmath'),
	('Zac MacMath', 'United States', 'macmath'),
	('Adri Castellano', 'Spain', 'adri castellano'),
	('Adri Castellano', 'Spain', 'castellano'),
	('Lorenzo Andrenacci', 'Italy', 'andrenacci'),
	('Lorenzo Andrenacci', 'Italy', 'lorenzo andrenacci'),
	('Ahn Yong Woo', 'Korea Republic', 'woo'),
	('Ahn Yong Woo', 'Korea Republic', 'ahn yong woo'),
	('Andrei Vlad', 'Romania', 'vlad'),
	('Andrei Vlad', 'Romania', 'andrei vlad'),
	('Brandon Mason', 'England', 'mason'),
	('Brandon Mason', 'England', 'brandon mason'),
	('Matheus Sávio', 'Brazil', 'savio'),
	('Matheus Sávio', 'Brazil', 'matheus savio'),
	('Renzo Zambrano', 'Venezuela', 'renzo zambrano'),
	('Renzo Zambrano', 'Venezuela', 'zambrano'),
	('Valmir Sulejmani', 'Kosovo', 'valmir sulejmani'),
	('Valmir Sulejmani', 'Kosovo', 'sulejmani'),
	('Kgotso Moleko', 'South Africa', 'moleko'),
	('Kgotso Moleko', 'South Africa', 'kgotso moleko'),
	('Florian Rieder', 'Austria', 'rieder'),
	('Florian Rieder', 'Austria', 'florian rieder'),
	('Joao Rojas', 'Ecuador', 'joao rojas'),
	('Joao Rojas', 'Ecuador', 'rojas'),
	('Madallah Al Olayan', 'Saudi Arabia', 'olayan'),
	('Madallah Al Olayan', 'Saudi Arabia', 'madallah al olayan'),
	('Riki', 'Spain', 'riki'),
	('Grant Ward', 'England', 'ward'),
	('Grant Ward', 'England', 'grant ward'),
	('Keijiro Ogawa', 'Japan', 'ogawa'),
	('Keijiro Ogawa', 'Japan', 'keijiro ogawa'),
	('Žarko Udovičić', 'Serbia', 'zarko udovicic'),
	('Žarko Udovičić', 'Serbia', 'udovicic'),
	('Sebastian Ohlsson', 'Sweden', 'ohlsson'),
	('Sebastian Ohlsson', 'Sweden', 'sebastian ohlsson'),
	('Lukas Jäger', 'Austria', 'lukas jager'),
	('Lukas Jäger', 'Austria', 'jager'),
	('Peter Gál-Andrezly', 'Slovakia', 'peter galandrezly'),
	('Peter Gál-Andrezly', 'Slovakia', 'galandrezly'),
	('Yuji Ono', 'Japan', 'yuji ono'),
	('Yuji Ono', 'Japan', 'ono'),
	('Jake Hesketh', 'England', 'jake hesketh'),
	('Jake Hesketh', 'England', 'hesketh'),
	('Hwang Hyun Soo', 'Korea Republic', 'soo'),
	('Hwang Hyun Soo', 'Korea Republic', 'hwang hyun soo'),
	('Stephan Hain', 'Germany', 'stephan hain'),
	('Stephan Hain', 'Germany', 'hain'),
	('Jamal Bajandouh', 'Saudi Arabia', 'bajandouh'),
	('Jamal Bajandouh', 'Saudi Arabia', 'jamal bajandouh'),
	('Enriko Papa', 'Albania', 'papa'),
	('Enriko Papa', 'Albania', 'enriko papa'),
	('Darius Charles', 'England', 'charles'),
	('Darius Charles', 'England', 'darius charles'),
	('Facundo Cambeses', 'Argentina', 'facundo cambeses'),
	('Facundo Cambeses', 'Argentina', 'cambeses'),
	('Freddie Sears', 'England', 'freddie sears'),
	('Freddie Sears', 'England', 'sears'),
	('Ibrahim Alhassan', 'Nigeria', 'ibrahim alhassan'),
	('Ibrahim Alhassan', 'Nigeria', 'alhassan'),
	('Tomasz Jodłowiec', 'Poland', 'jodowiec'),
	('Tomasz Jodłowiec', 'Poland', 'tomasz jodowiec'),
	('Yeon Je Woon', 'Korea Republic', 'yeon je woon'),
	('Yeon Je Woon', 'Korea Republic', 'woon'),
	('Ali Şaşal Vural', 'Turkey', 'vural'),
	('Ali Şaşal Vural', 'Turkey', 'ali sasal vural'),
	('Max Burgess', 'Australia', 'max burgess'),
	('Max Burgess', 'Australia', 'burgess'),
	('Kenan Özer', 'Turkey', 'kenan ozer'),
	('Kenan Özer', 'Turkey', 'ozer'),
	('Ben Close', 'England', 'close'),
	('Ben Close', 'England', 'ben close'),
	('Simon Rhein', 'Germany', 'rhein'),
	('Simon Rhein', 'Germany', 'simon rhein'),
	('Manuel Farrona Pulido', 'Germany', 'manuel farrona pulido'),
	('Manuel Farrona Pulido', 'Germany', 'pulido'),
	('Sven Schipplock', 'Germany', 'schipplock'),
	('Sven Schipplock', 'Germany', 'sven schipplock'),
	('Dennis Telgenkamp', 'Netherlands', 'telgenkamp'),
	('Dennis Telgenkamp', 'Netherlands', 'dennis telgenkamp'),
	('Mauro Da Luz', 'Uruguay', 'luz'),
	('Mauro Da Luz', 'Uruguay', 'mauro da luz'),
	('Jordan Leborgne', 'France', 'jordan leborgne'),
	('Jordan Leborgne', 'France', 'leborgne'),
	('Saša Balić', 'Montenegro', 'balic'),
	('Saša Balić', 'Montenegro', 'sasa balic'),
	('Larry Angulo', 'Colombia', 'larry angulo'),
	('Larry Angulo', 'Colombia', 'angulo'),
	('Dominik Holec', 'Slovakia', 'holec'),
	('Dominik Holec', 'Slovakia', 'dominik holec'),
	('Henri Saivet', 'Senegal', 'saivet'),
	('Henri Saivet', 'Senegal', 'henri saivet'),
	('Kike Pérez', 'Spain', 'kike perez'),
	('Kike Pérez', 'Spain', 'perez'),
	('Ben Woodburn', 'Wales', 'woodburn'),
	('Ben Woodburn', 'Wales', 'ben woodburn'),
	('Patrick Joosten', 'Netherlands', 'joosten'),
	('Patrick Joosten', 'Netherlands', 'patrick joosten'),
	('Nikoloz Ninua', 'Georgia', 'nikoloz ninua'),
	('Nikoloz Ninua', 'Georgia', 'ninua'),
	('Hubert Matynia', 'Poland', 'matynia'),
	('Hubert Matynia', 'Poland', 'hubert matynia'),
	('Herbie Kane', 'England', 'kane'),
	('Herbie Kane', 'England', 'herbie kane'),
	('Mackay', 'Spain', 'mackay'),
	('Mihai Roman', 'Romania', 'mihai roman'),
	('Mihai Roman', 'Romania', 'roman'),
	('Juan Aguilar', 'Paraguay', 'juan aguilar'),
	('Juan Aguilar', 'Paraguay', 'aguilar'),
	('Jordan Faucher', 'France', 'faucher'),
	('Jordan Faucher', 'France', 'jordan faucher'),
	('Gabriel Hachen', 'Argentina', 'hachen'),
	('Gabriel Hachen', 'Argentina', 'gabriel hachen'),
	('Jorge Grant', 'England', 'jorge grant'),
	('Jorge Grant', 'England', 'grant'),
	('Grant Leadbitter', 'England', 'leadbitter'),
	('Grant Leadbitter', 'England', 'grant leadbitter'),
	('El Bilal Touré', 'Mali', 'toure'),
	('El Bilal Touré', 'Mali', 'el bilal toure'),
	('Tsubasa Endoh', 'Japan', 'tsubasa endoh'),
	('Tsubasa Endoh', 'Japan', 'endoh'),
	('Jairo Torres', 'Mexico', 'torres'),
	('Jairo Torres', 'Mexico', 'jairo torres'),
	('Tsuyoshi Watanabe', 'Japan', 'watanabe'),
	('Tsuyoshi Watanabe', 'Japan', 'tsuyoshi watanabe'),
	('Mohammed Abubakari', 'Ghana', 'mohammed abubakari'),
	('Mohammed Abubakari', 'Ghana', 'abubakari'),
	('Denis Prychynenko', 'Germany', 'prychynenko'),
	('Denis Prychynenko', 'Germany', 'denis prychynenko'),
	('Alexander Groiß', 'Germany', 'alexander groi'),
	('Alexander Groiß', 'Germany', 'groi'),
	('Josip Radošević', 'Croatia', 'radosevic'),
	('Josip Radošević', 'Croatia', 'josip radosevic'),
	('Cadete', 'Spain', 'cadete'),
	('Flynn Downes', 'England', 'downes'),
	('Flynn Downes', 'England', 'flynn downes'),
	('Antonio Donnarumma', 'Italy', 'antonio donnarumma'),
	('Antonio Donnarumma', 'Italy', 'donnarumma'),
	('Jordi Osei-Tutu', 'England', 'oseitutu'),
	('Jordi Osei-Tutu', 'England', 'jordi oseitutu'),
	('Jack Simpson', 'England', 'jack simpson'),
	('Jack Simpson', 'England', 'simpson'),
	('Josh Laurent', 'England', 'josh laurent'),
	('Josh Laurent', 'England', 'laurent'),
	('Lucas Melano', 'Argentina', 'melano'),
	('Lucas Melano', 'Argentina', 'lucas melano'),
	('Tom Flanagan', 'Northern Ireland', 'flanagan'),
	('Tom Flanagan', 'Northern Ireland', 'tom flanagan'),
	('Nick Besler', 'United States', 'besler'),
	('Nick Besler', 'United States', 'nick besler'),
	('José Ángel', 'Spain', 'angel'),
	('José Ángel', 'Spain', 'jose angel'),
	('Kristoffer Velde', 'Norway', 'kristoffer velde'),
	('Kristoffer Velde', 'Norway', 'velde'),
	('Stefan Haudum', 'Austria', 'stefan haudum'),
	('Stefan Haudum', 'Austria', 'haudum'),
	('Kazuma Watanabe', 'Japan', 'kazuma watanabe'),
	('Kazuma Watanabe', 'Japan', 'watanabe'),
	('Daniel Barlaser', 'England', 'barlaser'),
	('Daniel Barlaser', 'England', 'daniel barlaser'),
	('Jack Whatmough', 'England', 'jack whatmough'),
	('Jack Whatmough', 'England', 'whatmough'),
	('Guram Giorbelidze', 'Georgia', 'guram giorbelidze'),
	('Guram Giorbelidze', 'Georgia', 'giorbelidze'),
	('Liberto Beltrán', 'Spain', 'liberto beltran'),
	('Liberto Beltrán', 'Spain', 'beltran'),
	('Julio Nava', 'Mexico', 'julio nava'),
	('Julio Nava', 'Mexico', 'nava'),
	('Grego Sierra', 'Spain', 'grego sierra'),
	('Grego Sierra', 'Spain', 'sierra'),
	('Robin Krauße', 'Germany', 'robin kraue'),
	('Robin Krauße', 'Germany', 'kraue'),
	('Evan Bush', 'United States', 'evan bush'),
	('Evan Bush', 'United States', 'bush'),
	('Jindřich Staněk', 'Czech Republic', 'stanek'),
	('Jindřich Staněk', 'Czech Republic', 'jindrich stanek')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';