INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Rafał Figiel', 'Poland', 'player'),
	('Liam Sercombe', 'England', 'player'),
	('Marcus Forss', 'Finland', 'player'),
	('Matías García', 'Argentina', 'player'),
	('Nicolás Dibble', 'Uruguay', 'player'),
	('Jérôme Phojo', 'France', 'player'),
	('David Andrade', 'Mexico', 'player'),
	('Juan Alvez', 'Uruguay', 'player'),
	('Nathan Holland', 'England', 'player'),
	('Jonathan Scherzer', 'Austria', 'player'),
	('Ollie Norburn', 'Grenada', 'player'),
	('Nikita Contini', 'Ukraine', 'player'),
	('Roy Gelmi', 'Switzerland', 'player'),
	('Scott Wharton', 'England', 'player'),
	('Kim Jung Min', 'Korea Republic', 'player'),
	('Nahuel Ferraresi', 'Venezuela', 'player'),
	('Christopher Schorch', 'Germany', 'player'),
	('Daniele Gabriele', 'Germany', 'player'),
	('Tom Parkes', 'England', 'player'),
	('Park Dae Won', 'Korea Republic', 'player'),
	('Amedej Vetrih', 'Slovenia', 'player'),
	('Bradley Halliday', 'England', 'player'),
	('Lars Lukas Mai', 'Germany', 'player'),
	('Mark Milligan', 'Australia', 'player'),
	('Fodé Doucouré', 'Mali', 'player'),
	('Hernán Pellerano', 'Argentina', 'player'),
	('Jiro Kamata', 'Japan', 'player'),
	('Roberto Fernández', 'Uruguay', 'player'),
	('Aimar Oroz', 'Spain', 'player'),
	('Franco Cristaldo', 'Argentina', 'player'),
	('Johnny Furdal', 'Norway', 'player'),
	('Jakub Vojtuš', 'Slovakia', 'player'),
	('Koba Koindredi', 'France', 'player'),
	('Julián Palacios', 'Argentina', 'player'),
	('Anthony Racioppi', 'Switzerland', 'player'),
	('Anderson Contreras', 'Venezuela', 'player'),
	('Tim Björkström', 'Sweden', 'player'),
	('Alberto Ocejo', 'Mexico', 'player'),
	('Loïc Badé', 'France', 'player'),
	('James Gibbons', 'England', 'player'),
	('Ethan Hamilton', 'Scotland', 'player'),
	('Fabián Torres', 'Chile', 'player'),
	('Indy Boonen', 'Belgium', 'player'),
	('Miguel Ortega', 'Mexico', 'player'),
	('Tomasz Nowak', 'Poland', 'player'),
	('George Hirst', 'England', 'player'),
	('Blaž Kramer', 'Slovenia', 'player'),
	('Jeremías Young', 'Argentina', 'player'),
	('Shane O''Neill', 'United States', 'player'),
	('Jorge Bava', 'Uruguay', 'player'),
	('Fredrik Carlsen', 'Norway', 'player'),
	('Leandro Silva', 'Brazil', 'player'),
	('Jasper van der Werff', 'Switzerland', 'player'),
	('Amin Askar', 'Ethiopia', 'player'),
	('Sean Kavanagh', 'Republic of Ireland', 'player'),
	('Tarık Çetin', 'Turkey', 'player'),
	('Kazunari Ono', 'Japan', 'player'),
	('Dan Scarr', 'England', 'player'),
	('Erwin Hoffer', 'Austria', 'player'),
	('Willem Geubbels', 'France', 'player'),
	('Maximilian Jansen', 'Germany', 'player'),
	('Hannes Delcroix', 'Belgium', 'player'),
	('Tom Elliott', 'England', 'player'),
	('Chrislain Matsima', 'France', 'player'),
	('Nadir Çiftçi', 'Turkey', 'player'),
	('Alejandro Guido', 'United States', 'player'),
	('Rodrigo Ramallo', 'Bolivia', 'player'),
	('Jo Sung Jin', 'Korea Republic', 'player'),
	('Andrés Solano', 'Colombia', 'player'),
	('Lucas Röser', 'Germany', 'player'),
	('Tom van de Looi', 'Netherlands', 'player'),
	('Ugarte', 'Spain', 'player'),
	('Jordy Delem', 'France', 'player'),
	('Lee Grace', 'Republic of Ireland', 'player'),
	('Mads Greve', 'Denmark', 'player'),
	('Pape Ibnou Ba', 'Senegal', 'player'),
	('Kevin Mensah', 'Denmark', 'player'),
	('Osman Çelik', 'Turkey', 'player'),
	('Oliver Lund', 'Denmark', 'player'),
	('Sven Sprangler', 'Austria', 'player'),
	('Joaquín Pereyra', 'Argentina', 'player'),
	('Adam Sušac', 'Croatia', 'player'),
	('Manfred Starke', 'Namibia', 'player'),
	('Rhys Norrington-Davies', 'Wales', 'player'),
	('Raul Opruț', 'Romania', 'player'),
	('Joel Cooper', 'Northern Ireland', 'player'),
	('Lucas Jensen', 'Denmark', 'player'),
	('Kazuki Kushibiki', 'Japan', 'player'),
	('Jonathan Mitchell', 'England', 'player'),
	('Conor Washington', 'Northern Ireland', 'player'),
	('Hui Jiakang', 'China PR', 'player'),
	('Franck Evina', 'Cameroon', 'player'),
	('Zain Westbrooke', 'England', 'player'),
	('Harouna Abou Demba', 'Mauritania', 'player'),
	('Fredrik Brustad', 'Norway', 'player'),
	('Gorka Pérez', 'Spain', 'player'),
	('Jon Kempin', 'United States', 'player'),
	('Madi', 'Portugal', 'player'),
	('Cătălin Straton', 'Romania', 'player'),
	('Abdulfatah Adam', 'Saudi Arabia', 'player'),
	('Yassin Fekir', 'France', 'player'),
	('Dylan McGowan', 'Australia', 'player'),
	('Gareth Evans', 'England', 'player'),
	('Harrison McGahey', 'England', 'player'),
	('Paul Gladon', 'Netherlands', 'player'),
	('Ronny Montero', 'Bolivia', 'player'),
	('Jeron Al-Hazaimeh', 'Germany', 'player'),
	('Francisco Gerometta', 'Argentina', 'player'),
	('Gaoussou Traoré', 'France', 'player'),
	('Afonso Sousa', 'Portugal', 'player'),
	('Reguero', 'Spain', 'player'),
	('Luis Miguel Escalada', 'Argentina', 'player'),
	('Mike Feigenspan', 'Germany', 'player'),
	('Jimmy Keohane', 'Republic of Ireland', 'player'),
	('Sebastien Ibeagha', 'United States', 'player'),
	('Andrej Kadlec', 'Slovakia', 'player'),
	('Quint Jansen', 'Netherlands', 'player'),
	('Roope Riski', 'Finland', 'player'),
	('Saleh Al Jaman', 'Saudi Arabia', 'player'),
	('Mohammed Fayez', 'United Arab Emirates', 'player'),
	('Romain Faivre', 'France', 'player'),
	('Jean Carlos', 'Brazil', 'player'),
	('Florin Berenguer', 'France', 'player'),
	('Seámus Conneely', 'Republic of Ireland', 'player'),
	('Sören Dieckmann', 'Germany', 'player'),
	('Jay-Roy Grot', 'Netherlands', 'player'),
	('Dylan Connolly', 'Republic of Ireland', 'player'),
	('Tobías Zárate', 'Argentina', 'player'),
	('Leao Butrón', 'Peru', 'player'),
	('Enrique Borja', 'Paraguay', 'player'),
	('Andrew Tarbell', 'United States', 'player'),
	('Noah Loosli', 'Switzerland', 'player'),
	('Scott Wright', 'Scotland', 'player'),
	('Emre Güral', 'Turkey', 'player'),
	('Jack Payne', 'England', 'player'),
	('Martín Galvan', 'Mexico', 'player'),
	('Chumi', 'Spain', 'player'),
	('Jorge Toledo', 'Peru', 'player'),
	('Leif Davis', 'England', 'player'),
	('Gary Sawyer', 'England', 'player'),
	('Sébastien Rénot', 'France', 'player'),
	('Darko Churlinov', 'North Macedonia', 'player'),
	('Roberto López', 'Spain', 'player'),
	('Charles Vanhoutte', 'Belgium', 'player'),
	('Arvin Appiah', 'England', 'player'),
	('Ezekiel Fryers', 'England', 'player'),
	('Muhammed Şengezer', 'Turkey', 'player'),
	('Federico Acuña', 'Paraguay', 'player'),
	('Ousseynou Cissé', 'Mali', 'player'),
	('Robbe Decostere', 'Belgium', 'player'),
	('Fernando Medeiros', 'Brazil', 'player'),
	('Juan Galeano', 'Argentina', 'player'),
	('Panajotis Dimitriadis', 'Sweden', 'player'),
	('Noah Holm', 'Norway', 'player'),
	('Johannes Handl', 'Austria', 'player'),
	('Iván Villalba', 'Paraguay', 'player'),
	('Elton Kabangu', 'Belgium', 'player'),
	('Steve Ambri', 'France', 'player'),
	('Gaëtan Laura', 'France', 'player'),
	('Óscar Pinchi', 'Spain', 'player'),
	('Joe Pritchard', 'England', 'player'),
	('Matthew Rusike', 'Zimbabwe', 'player'),
	('Yuji Takahashi', 'Japan', 'player'),
	('Arianit Ferati', 'Germany', 'player'),
	('Simen Bolkan Nordli', 'Norway', 'player'),
	('Ayumu Seko', 'Japan', 'player'),
	('Anthony Fontana', 'United States', 'player'),
	('Tommy St. Jago', 'Netherlands', 'player'),
	('Ahmet Engin', 'Germany', 'player'),
	('Yang Kuo', 'China PR', 'player'),
	('Sebastian Jacob', 'Germany', 'player'),
	('Richard Salinas', 'Paraguay', 'player'),
	('Augustín Palavecino', 'Argentina', 'player'),
	('Dorian Bertrand', 'France', 'player'),
	('Erwin Junior Sánchez', 'Bolivia', 'player'),
	('Josh Knight', 'England', 'player'),
	('Terell Thomas', 'England', 'player'),
	('Ronaldo Peña', 'Venezuela', 'player'),
	('Kaiyne Woolery', 'England', 'player'),
	('René Meléndez', 'Chile', 'player'),
	('Kevin Wright', 'Sierra Leone', 'player'),
	('Krystian Getinger', 'Poland', 'player'),
	('Manuel Roffo', 'Argentina', 'player'),
	('Maxime Leverbe', 'France', 'player'),
	('Gianluca Busio', 'United States', 'player'),
	('Ryuji Sugimoto', 'Japan', 'player'),
	('Dion Sanderson', 'England', 'player'),
	('Gai Assulin', 'Israel', 'player'),
	('José Junhior Velásquez', 'Peru', 'player'),
	('Razak Boukari', 'Togo', 'player'),
	('Riccardo Sottil', 'Italy', 'player'),
	('George Cooper', 'England', 'player'),
	('Martín Galmarini', 'Argentina', 'player'),
	('Matty Lund', 'Northern Ireland', 'player'),
	('Felix Torres', 'Ecuador', 'player'),
	('Andriy Boryachuk', 'Ukraine', 'player'),
	('Melle Meulensteen', 'Netherlands', 'player'),
	('Liu Yun', 'China PR', 'player'),
	('Yang Xu', 'China PR', 'player'),
	('Juan Manuel Tévez', 'Argentina', 'player'),
	('Carlton Morris', 'England', 'player'),
	('Luis Paz', 'Colombia', 'player'),
	('Anthony Syhre', 'Germany', 'player'),
	('Victor Melgar', 'Bolivia', 'player'),
	('Nikolaos Kainourgios', 'Greece', 'player'),
	('Saud Abdulhamid', 'Saudi Arabia', 'player'),
	('Alexandru Dandea', 'Romania', 'player'),
	('Johannes Tartarotti', 'Austria', 'player'),
	('Fodé Konaté', 'Mali', 'player'),
	('Anel Šabanadžović', 'Bosnia Herzegovina', 'player'),
	('Courtney Senior', 'England', 'player'),
	('Žan Rogelj', 'Slovenia', 'player'),
	('Dennis Erdmann', 'Germany', 'player'),
	('Jacori Hayes', 'United States', 'player'),
	('Takanori Sugeno', 'Japan', 'player'),
	('John Björkengren', 'Sweden', 'player'),
	('Ben Richards-Everton', 'England', 'player'),
	('Neftali Manzambi', 'Switzerland', 'player'),
	('Younès Kaabouni', 'France', 'player'),
	('Marko Kvasina', 'Austria', 'player'),
	('Afimico Pululu', 'Angola', 'player'),
	('Gary Roberts', 'England', 'player'),
	('Edwin Herrera', 'Colombia', 'player'),
	('Paul Akouokou', 'Ivory Coast', 'player'),
	('Boy Kemper', 'Netherlands', 'player'),
	('Piotr Johansson', 'Sweden', 'player'),
	('Alexander Rossipal', 'Germany', 'player'),
	('Hamdan Al Shamrani', 'Saudi Arabia', 'player'),
	('Yannick Schmid', 'Switzerland', 'player'),
	('Ryan Colclough', 'England', 'player'),
	('Isak Ssewankambo', 'Sweden', 'player'),
	('Nico Melamed', 'Spain', 'player'),
	('Ismael', 'Spain', 'player'),
	('Daiki Miya', 'Japan', 'player'),
	('Pablo Gozálbez', 'Spain', 'player'),
	('José Hernández', 'Mexico', 'player'),
	('Valtteri Moren', 'Finland', 'player'),
	('Max Reinthaler', 'Italy', 'player'),
	('Dennis Iapichino', 'Switzerland', 'player'),
	('Ben Pringle', 'England', 'player'),
	('Elliott Hewitt', 'Wales', 'player'),
	('Jorge Flores', 'Bolivia', 'player'),
	('Sambou Sissoko', 'France', 'player'),
	('Quirin Moll', 'Germany', 'player'),
	('Joao Ortiz', 'Ecuador', 'player'),
	('Martín Ezequiel Cañete', 'Argentina', 'player'),
	('David Löfquist', 'Sweden', 'player'),
	('Bruno Ramires', 'Brazil', 'player'),
	('Yuji Hoshi', 'Japan', 'player'),
	('Brek Shea', 'United States', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Rafał Figiel', 'Poland', 'figiel'),
	('Rafał Figiel', 'Poland', 'rafa figiel'),
	('Liam Sercombe', 'England', 'sercombe'),
	('Liam Sercombe', 'England', 'liam sercombe'),
	('Marcus Forss', 'Finland', 'forss'),
	('Marcus Forss', 'Finland', 'marcus forss'),
	('Matías García', 'Argentina', 'garcia'),
	('Matías García', 'Argentina', 'matias garcia'),
	('Nicolás Dibble', 'Uruguay', 'nicolas dibble'),
	('Nicolás Dibble', 'Uruguay', 'dibble'),
	('Jérôme Phojo', 'France', 'jerome phojo'),
	('Jérôme Phojo', 'France', 'phojo'),
	('David Andrade', 'Mexico', 'andrade'),
	('David Andrade', 'Mexico', 'david andrade'),
	('Juan Alvez', 'Uruguay', 'juan alvez'),
	('Juan Alvez', 'Uruguay', 'alvez'),
	('Nathan Holland', 'England', 'holland'),
	('Nathan Holland', 'England', 'nathan holland'),
	('Jonathan Scherzer', 'Austria', 'scherzer'),
	('Jonathan Scherzer', 'Austria', 'jonathan scherzer'),
	('Ollie Norburn', 'Grenada', 'ollie norburn'),
	('Ollie Norburn', 'Grenada', 'norburn'),
	('Nikita Contini', 'Ukraine', 'contini'),
	('Nikita Contini', 'Ukraine', 'nikita contini'),
	('Roy Gelmi', 'Switzerland', 'gelmi'),
	('Roy Gelmi', 'Switzerland', 'roy gelmi'),
	('Scott Wharton', 'England', 'wharton'),
	('Scott Wharton', 'England', 'scott wharton'),
	('Kim Jung Min', 'Korea Republic', 'kim jung min'),
	('Kim Jung Min', 'Korea Republic', 'min'),
	('Nahuel Ferraresi', 'Venezuela', 'nahuel ferraresi'),
	('Nahuel Ferraresi', 'Venezuela', 'ferraresi'),
	('Christopher Schorch', 'Germany', 'schorch'),
	('Christopher Schorch', 'Germany', 'christopher schorch'),
	('Daniele Gabriele', 'Germany', 'gabriele'),
	('Daniele Gabriele', 'Germany', 'daniele gabriele'),
	('Tom Parkes', 'England', 'tom parkes'),
	('Tom Parkes', 'England', 'parkes'),
	('Park Dae Won', 'Korea Republic', 'park dae won'),
	('Park Dae Won', 'Korea Republic', 'won'),
	('Amedej Vetrih', 'Slovenia', 'amedej vetrih'),
	('Amedej Vetrih', 'Slovenia', 'vetrih'),
	('Bradley Halliday', 'England', 'halliday'),
	('Bradley Halliday', 'England', 'bradley halliday'),
	('Lars Lukas Mai', 'Germany', 'mai'),
	('Lars Lukas Mai', 'Germany', 'lars lukas mai'),
	('Mark Milligan', 'Australia', 'mark milligan'),
	('Mark Milligan', 'Australia', 'milligan'),
	('Fodé Doucouré', 'Mali', 'fode doucoure'),
	('Fodé Doucouré', 'Mali', 'doucoure'),
	('Hernán Pellerano', 'Argentina', 'pellerano'),
	('Hernán Pellerano', 'Argentina', 'hernan pellerano'),
	('Jiro Kamata', 'Japan', 'kamata'),
	('Jiro Kamata', 'Japan', 'jiro kamata'),
	('Roberto Fernández', 'Uruguay', 'fernandez'),
	('Roberto Fernández', 'Uruguay', 'roberto fernandez'),
	('Aimar Oroz', 'Spain', 'oroz'),
	('Aimar Oroz', 'Spain', 'aimar oroz'),
	('Franco Cristaldo', 'Argentina', 'cristaldo'),
	('Franco Cristaldo', 'Argentina', 'franco cristaldo'),
	('Johnny Furdal', 'Norway', 'johnny furdal'),
	('Johnny Furdal', 'Norway', 'furdal'),
	('Jakub Vojtuš', 'Slovakia', 'jakub vojtus'),
	('Jakub Vojtuš', 'Slovakia', 'vojtus'),
	('Koba Koindredi', 'France', 'koba koindredi'),
	('Koba Koindredi', 'France', 'koindredi'),
	('Julián Palacios', 'Argentina', 'palacios'),
	('Julián Palacios', 'Argentina', 'julian palacios'),
	('Anthony Racioppi', 'Switzerland', 'racioppi'),
	('Anthony Racioppi', 'Switzerland', 'anthony racioppi'),
	('Anderson Contreras', 'Venezuela', 'contreras'),
	('Anderson Contreras', 'Venezuela', 'anderson contreras'),
	('Tim Björkström', 'Sweden', 'bjorkstrom'),
	('Tim Björkström', 'Sweden', 'tim bjorkstrom'),
	('Alberto Ocejo', 'Mexico', 'alberto ocejo'),
	('Alberto Ocejo', 'Mexico', 'ocejo'),
	('Loïc Badé', 'France', 'bade'),
	('Loïc Badé', 'France', 'loic bade'),
	('James Gibbons', 'England', 'gibbons'),
	('James Gibbons', 'England', 'james gibbons'),
	('Ethan Hamilton', 'Scotland', 'ethan hamilton'),
	('Ethan Hamilton', 'Scotland', 'hamilton'),
	('Fabián Torres', 'Chile', 'torres'),
	('Fabián Torres', 'Chile', 'fabian torres'),
	('Indy Boonen', 'Belgium', 'indy boonen'),
	('Indy Boonen', 'Belgium', 'boonen'),
	('Miguel Ortega', 'Mexico', 'miguel ortega'),
	('Miguel Ortega', 'Mexico', 'ortega'),
	('Tomasz Nowak', 'Poland', 'tomasz nowak'),
	('Tomasz Nowak', 'Poland', 'nowak'),
	('George Hirst', 'England', 'george hirst'),
	('George Hirst', 'England', 'hirst'),
	('Blaž Kramer', 'Slovenia', 'kramer'),
	('Blaž Kramer', 'Slovenia', 'blaz kramer'),
	('Jeremías Young', 'Argentina', 'young'),
	('Jeremías Young', 'Argentina', 'jeremias young'),
	('Shane O''Neill', 'United States', 'shane oneill'),
	('Shane O''Neill', 'United States', 'oneill'),
	('Jorge Bava', 'Uruguay', 'jorge bava'),
	('Jorge Bava', 'Uruguay', 'bava'),
	('Fredrik Carlsen', 'Norway', 'fredrik carlsen'),
	('Fredrik Carlsen', 'Norway', 'carlsen'),
	('Leandro Silva', 'Brazil', 'silva'),
	('Leandro Silva', 'Brazil', 'leandro silva'),
	('Jasper van der Werff', 'Switzerland', 'jasper van der werff'),
	('Jasper van der Werff', 'Switzerland', 'werff'),
	('Amin Askar', 'Ethiopia', 'askar'),
	('Amin Askar', 'Ethiopia', 'amin askar'),
	('Sean Kavanagh', 'Republic of Ireland', 'sean kavanagh'),
	('Sean Kavanagh', 'Republic of Ireland', 'kavanagh'),
	('Tarık Çetin', 'Turkey', 'cetin'),
	('Tarık Çetin', 'Turkey', 'tark cetin'),
	('Kazunari Ono', 'Japan', 'kazunari ono'),
	('Kazunari Ono', 'Japan', 'ono'),
	('Dan Scarr', 'England', 'dan scarr'),
	('Dan Scarr', 'England', 'scarr'),
	('Erwin Hoffer', 'Austria', 'erwin hoffer'),
	('Erwin Hoffer', 'Austria', 'hoffer'),
	('Willem Geubbels', 'France', 'geubbels'),
	('Willem Geubbels', 'France', 'willem geubbels'),
	('Maximilian Jansen', 'Germany', 'jansen'),
	('Maximilian Jansen', 'Germany', 'maximilian jansen'),
	('Hannes Delcroix', 'Belgium', 'hannes delcroix'),
	('Hannes Delcroix', 'Belgium', 'delcroix'),
	('Tom Elliott', 'England', 'tom elliott'),
	('Tom Elliott', 'England', 'elliott'),
	('Chrislain Matsima', 'France', 'chrislain matsima'),
	('Chrislain Matsima', 'France', 'matsima'),
	('Nadir Çiftçi', 'Turkey', 'nadir ciftci'),
	('Nadir Çiftçi', 'Turkey', 'ciftci'),
	('Alejandro Guido', 'United States', 'guido'),
	('Alejandro Guido', 'United States', 'alejandro guido'),
	('Rodrigo Ramallo', 'Bolivia', 'ramallo'),
	('Rodrigo Ramallo', 'Bolivia', 'rodrigo ramallo'),
	('Jo Sung Jin', 'Korea Republic', 'jin'),
	('Jo Sung Jin', 'Korea Republic', 'jo sung jin'),
	('Andrés Solano', 'Colombia', 'solano'),
	('Andrés Solano', 'Colombia', 'andres solano'),
	('Lucas Röser', 'Germany', 'roser'),
	('Lucas Röser', 'Germany', 'lucas roser'),
	('Tom van de Looi', 'Netherlands', 'looi'),
	('Tom van de Looi', 'Netherlands', 'tom van de looi'),
	('Ugarte', 'Spain', 'ugarte'),
	('Jordy Delem', 'France', 'delem'),
	('Jordy Delem', 'France', 'jordy delem'),
	('Lee Grace', 'Republic of Ireland', 'lee grace'),
	('Lee Grace', 'Republic of Ireland', 'grace'),
	('Mads Greve', 'Denmark', 'mads greve'),
	('Mads Greve', 'Denmark', 'greve'),
	('Pape Ibnou Ba', 'Senegal', 'pape ibnou ba'),
	('Pape Ibnou Ba', 'Senegal', 'ba'),
	('Kevin Mensah', 'Denmark', 'mensah'),
	('Kevin Mensah', 'Denmark', 'kevin mensah'),
	('Osman Çelik', 'Turkey', 'osman celik'),
	('Osman Çelik', 'Turkey', 'celik'),
	('Oliver Lund', 'Denmark', 'oliver lund'),
	('Oliver Lund', 'Denmark', 'lund'),
	('Sven Sprangler', 'Austria', 'sprangler'),
	('Sven Sprangler', 'Austria', 'sven sprangler'),
	('Joaquín Pereyra', 'Argentina', 'joaquin pereyra'),
	('Joaquín Pereyra', 'Argentina', 'pereyra'),
	('Adam Sušac', 'Croatia', 'susac'),
	('Adam Sušac', 'Croatia', 'adam susac'),
	('Manfred Starke', 'Namibia', 'starke'),
	('Manfred Starke', 'Namibia', 'manfred starke'),
	('Rhys Norrington-Davies', 'Wales', 'norringtondavies'),
	('Rhys Norrington-Davies', 'Wales', 'rhys norringtondavies'),
	('Raul Opruț', 'Romania', 'raul oprut'),
	('Raul Opruț', 'Romania', 'oprut'),
	('Joel Cooper', 'Northern Ireland', 'joel cooper'),
	('Joel Cooper', 'Northern Ireland', 'cooper'),
	('Lucas Jensen', 'Denmark', 'jensen'),
	('Lucas Jensen', 'Denmark', 'lucas jensen'),
	('Kazuki Kushibiki', 'Japan', 'kazuki kushibiki'),
	('Kazuki Kushibiki', 'Japan', 'kushibiki'),
	('Jonathan Mitchell', 'England', 'mitchell'),
	('Jonathan Mitchell', 'England', 'jonathan mitchell'),
	('Conor Washington', 'Northern Ireland', 'conor washington'),
	('Conor Washington', 'Northern Ireland', 'washington'),
	('Hui Jiakang', 'China PR', 'hui jiakang'),
	('Hui Jiakang', 'China PR', 'jiakang'),
	('Franck Evina', 'Cameroon', 'evina'),
	('Franck Evina', 'Cameroon', 'franck evina'),
	('Zain Westbrooke', 'England', 'westbrooke'),
	('Zain Westbrooke', 'England', 'zain westbrooke'),
	('Harouna Abou Demba', 'Mauritania', 'demba'),
	('Harouna Abou Demba', 'Mauritania', 'harouna abou demba'),
	('Fredrik Brustad', 'Norway', 'fredrik brustad'),
	('Fredrik Brustad', 'Norway', 'brustad'),
	('Gorka Pérez', 'Spain', 'gorka perez'),
	('Gorka Pérez', 'Spain', 'perez'),
	('Jon Kempin', 'United States', 'jon kempin'),
	('Jon Kempin', 'United States', 'kempin'),
	('Madi', 'Portugal', 'madi'),
	('Cătălin Straton', 'Romania', 'straton'),
	('Cătălin Straton', 'Romania', 'catalin straton'),
	('Abdulfatah Adam', 'Saudi Arabia', 'adam'),
	('Abdulfatah Adam', 'Saudi Arabia', 'abdulfatah adam'),
	('Yassin Fekir', 'France', 'yassin fekir'),
	('Yassin Fekir', 'France', 'fekir'),
	('Dylan McGowan', 'Australia', 'dylan mcgowan'),
	('Dylan McGowan', 'Australia', 'mcgowan'),
	('Gareth Evans', 'England', 'gareth evans'),
	('Gareth Evans', 'England', 'evans'),
	('Harrison McGahey', 'England', 'harrison mcgahey'),
	('Harrison McGahey', 'England', 'mcgahey'),
	('Paul Gladon', 'Netherlands', 'gladon'),
	('Paul Gladon', 'Netherlands', 'paul gladon'),
	('Ronny Montero', 'Bolivia', 'montero'),
	('Ronny Montero', 'Bolivia', 'ronny montero'),
	('Jeron Al-Hazaimeh', 'Germany', 'alhazaimeh'),
	('Jeron Al-Hazaimeh', 'Germany', 'jeron alhazaimeh'),
	('Francisco Gerometta', 'Argentina', 'francisco gerometta'),
	('Francisco Gerometta', 'Argentina', 'gerometta'),
	('Gaoussou Traoré', 'France', 'traore'),
	('Gaoussou Traoré', 'France', 'gaoussou traore'),
	('Afonso Sousa', 'Portugal', 'sousa'),
	('Afonso Sousa', 'Portugal', 'afonso sousa'),
	('Reguero', 'Spain', 'reguero'),
	('Luis Miguel Escalada', 'Argentina', 'escalada'),
	('Luis Miguel Escalada', 'Argentina', 'luis miguel escalada'),
	('Mike Feigenspan', 'Germany', 'feigenspan'),
	('Mike Feigenspan', 'Germany', 'mike feigenspan'),
	('Jimmy Keohane', 'Republic of Ireland', 'jimmy keohane'),
	('Jimmy Keohane', 'Republic of Ireland', 'keohane'),
	('Sebastien Ibeagha', 'United States', 'ibeagha'),
	('Sebastien Ibeagha', 'United States', 'sebastien ibeagha'),
	('Andrej Kadlec', 'Slovakia', 'andrej kadlec'),
	('Andrej Kadlec', 'Slovakia', 'kadlec'),
	('Quint Jansen', 'Netherlands', 'jansen'),
	('Quint Jansen', 'Netherlands', 'quint jansen'),
	('Roope Riski', 'Finland', 'riski'),
	('Roope Riski', 'Finland', 'roope riski'),
	('Saleh Al Jaman', 'Saudi Arabia', 'jaman'),
	('Saleh Al Jaman', 'Saudi Arabia', 'saleh al jaman'),
	('Mohammed Fayez', 'United Arab Emirates', 'mohammed fayez'),
	('Mohammed Fayez', 'United Arab Emirates', 'fayez'),
	('Romain Faivre', 'France', 'faivre'),
	('Romain Faivre', 'France', 'romain faivre'),
	('Jean Carlos', 'Brazil', 'jean carlos'),
	('Jean Carlos', 'Brazil', 'carlos'),
	('Florin Berenguer', 'France', 'florin berenguer'),
	('Florin Berenguer', 'France', 'berenguer'),
	('Seámus Conneely', 'Republic of Ireland', 'conneely'),
	('Seámus Conneely', 'Republic of Ireland', 'seamus conneely'),
	('Sören Dieckmann', 'Germany', 'soren dieckmann'),
	('Sören Dieckmann', 'Germany', 'dieckmann'),
	('Jay-Roy Grot', 'Netherlands', 'jayroy grot'),
	('Jay-Roy Grot', 'Netherlands', 'grot'),
	('Dylan Connolly', 'Republic of Ireland', 'dylan connolly'),
	('Dylan Connolly', 'Republic of Ireland', 'connolly'),
	('Tobías Zárate', 'Argentina', 'tobias zarate'),
	('Tobías Zárate', 'Argentina', 'zarate'),
	('Leao Butrón', 'Peru', 'leao butron'),
	('Leao Butrón', 'Peru', 'butron'),
	('Enrique Borja', 'Paraguay', 'borja'),
	('Enrique Borja', 'Paraguay', 'enrique borja'),
	('Andrew Tarbell', 'United States', 'andrew tarbell'),
	('Andrew Tarbell', 'United States', 'tarbell'),
	('Noah Loosli', 'Switzerland', 'loosli'),
	('Noah Loosli', 'Switzerland', 'noah loosli'),
	('Scott Wright', 'Scotland', 'scott wright'),
	('Scott Wright', 'Scotland', 'wright'),
	('Emre Güral', 'Turkey', 'gural'),
	('Emre Güral', 'Turkey', 'emre gural'),
	('Jack Payne', 'England', 'jack payne'),
	('Jack Payne', 'England', 'payne'),
	('Martín Galvan', 'Mexico', 'martin galvan'),
	('Martín Galvan', 'Mexico', 'galvan'),
	('Chumi', 'Spain', 'chumi'),
	('Jorge Toledo', 'Peru', 'jorge toledo'),
	('Jorge Toledo', 'Peru', 'toledo'),
	('Leif Davis', 'England', 'leif davis'),
	('Leif Davis', 'England', 'davis'),
	('Gary Sawyer', 'England', 'sawyer'),
	('Gary Sawyer', 'England', 'gary sawyer'),
	('Sébastien Rénot', 'France', 'renot'),
	('Sébastien Rénot', 'France', 'sebastien renot'),
	('Darko Churlinov', 'North Macedonia', 'darko churlinov'),
	('Darko Churlinov', 'North Macedonia', 'churlinov'),
	('Roberto López', 'Spain', 'roberto lopez'),
	('Roberto López', 'Spain', 'lopez'),
	('Charles Vanhoutte', 'Belgium', 'vanhoutte'),
	('Charles Vanhoutte', 'Belgium', 'charles vanhoutte'),
	('Arvin Appiah', 'England', 'appiah'),
	('Arvin Appiah', 'England', 'arvin appiah'),
	('Ezekiel Fryers', 'England', 'ezekiel fryers'),
	('Ezekiel Fryers', 'England', 'fryers'),
	('Muhammed Şengezer', 'Turkey', 'sengezer'),
	('Muhammed Şengezer', 'Turkey', 'muhammed sengezer'),
	('Federico Acuña', 'Paraguay', 'acuna'),
	('Federico Acuña', 'Paraguay', 'federico acuna'),
	('Ousseynou Cissé', 'Mali', 'ousseynou cisse'),
	('Ousseynou Cissé', 'Mali', 'cisse'),
	('Robbe Decostere', 'Belgium', 'robbe decostere'),
	('Robbe Decostere', 'Belgium', 'decostere'),
	('Fernando Medeiros', 'Brazil', 'fernando medeiros'),
	('Fernando Medeiros', 'Brazil', 'medeiros'),
	('Juan Galeano', 'Argentina', 'galeano'),
	('Juan Galeano', 'Argentina', 'juan galeano'),
	('Panajotis Dimitriadis', 'Sweden', 'panajotis dimitriadis'),
	('Panajotis Dimitriadis', 'Sweden', 'dimitriadis'),
	('Noah Holm', 'Norway', 'noah holm'),
	('Noah Holm', 'Norway', 'holm'),
	('Johannes Handl', 'Austria', 'handl'),
	('Johannes Handl', 'Austria', 'johannes handl'),
	('Iván Villalba', 'Paraguay', 'villalba'),
	('Iván Villalba', 'Paraguay', 'ivan villalba'),
	('Elton Kabangu', 'Belgium', 'elton kabangu'),
	('Elton Kabangu', 'Belgium', 'kabangu'),
	('Steve Ambri', 'France', 'ambri'),
	('Steve Ambri', 'France', 'steve ambri'),
	('Gaëtan Laura', 'France', 'gaetan laura'),
	('Gaëtan Laura', 'France', 'laura'),
	('Óscar Pinchi', 'Spain', 'pinchi'),
	('Óscar Pinchi', 'Spain', 'oscar pinchi'),
	('Joe Pritchard', 'England', 'pritchard'),
	('Joe Pritchard', 'England', 'joe pritchard'),
	('Matthew Rusike', 'Zimbabwe', 'matthew rusike'),
	('Matthew Rusike', 'Zimbabwe', 'rusike'),
	('Yuji Takahashi', 'Japan', 'yuji takahashi'),
	('Yuji Takahashi', 'Japan', 'takahashi'),
	('Arianit Ferati', 'Germany', 'arianit ferati'),
	('Arianit Ferati', 'Germany', 'ferati'),
	('Simen Bolkan Nordli', 'Norway', 'nordli'),
	('Simen Bolkan Nordli', 'Norway', 'simen bolkan nordli'),
	('Ayumu Seko', 'Japan', 'ayumu seko'),
	('Ayumu Seko', 'Japan', 'seko'),
	('Anthony Fontana', 'United States', 'anthony fontana'),
	('Anthony Fontana', 'United States', 'fontana'),
	('Tommy St. Jago', 'Netherlands', 'tommy st jago'),
	('Tommy St. Jago', 'Netherlands', 'jago'),
	('Ahmet Engin', 'Germany', 'ahmet engin'),
	('Ahmet Engin', 'Germany', 'engin'),
	('Yang Kuo', 'China PR', 'yang kuo'),
	('Yang Kuo', 'China PR', 'kuo'),
	('Sebastian Jacob', 'Germany', 'sebastian jacob'),
	('Sebastian Jacob', 'Germany', 'jacob'),
	('Richard Salinas', 'Paraguay', 'salinas'),
	('Richard Salinas', 'Paraguay', 'richard salinas'),
	('Augustín Palavecino', 'Argentina', 'palavecino'),
	('Augustín Palavecino', 'Argentina', 'augustin palavecino'),
	('Dorian Bertrand', 'France', 'dorian bertrand'),
	('Dorian Bertrand', 'France', 'bertrand'),
	('Erwin Junior Sánchez', 'Bolivia', 'erwin junior sanchez'),
	('Erwin Junior Sánchez', 'Bolivia', 'sanchez'),
	('Josh Knight', 'England', 'knight'),
	('Josh Knight', 'England', 'josh knight'),
	('Terell Thomas', 'England', 'terell thomas'),
	('Terell Thomas', 'England', 'thomas'),
	('Ronaldo Peña', 'Venezuela', 'pena'),
	('Ronaldo Peña', 'Venezuela', 'ronaldo pena'),
	('Kaiyne Woolery', 'England', 'woolery'),
	('Kaiyne Woolery', 'England', 'kaiyne woolery'),
	('René Meléndez', 'Chile', 'rene melendez'),
	('René Meléndez', 'Chile', 'melendez'),
	('Kevin Wright', 'Sierra Leone', 'kevin wright'),
	('Kevin Wright', 'Sierra Leone', 'wright'),
	('Krystian Getinger', 'Poland', 'getinger'),
	('Krystian Getinger', 'Poland', 'krystian getinger'),
	('Manuel Roffo', 'Argentina', 'manuel roffo'),
	('Manuel Roffo', 'Argentina', 'roffo'),
	('Maxime Leverbe', 'France', 'maxime leverbe'),
	('Maxime Leverbe', 'France', 'leverbe'),
	('Gianluca Busio', 'United States', 'gianluca busio'),
	('Gianluca Busio', 'United States', 'busio'),
	('Ryuji Sugimoto', 'Japan', 'ryuji sugimoto'),
	('Ryuji Sugimoto', 'Japan', 'sugimoto'),
	('Dion Sanderson', 'England', 'sanderson'),
	('Dion Sanderson', 'England', 'dion sanderson'),
	('Gai Assulin', 'Israel', 'assulin'),
	('Gai Assulin', 'Israel', 'gai assulin'),
	('José Junhior Velásquez', 'Peru', 'jose junhior velasquez'),
	('José Junhior Velásquez', 'Peru', 'velasquez'),
	('Razak Boukari', 'Togo', 'razak boukari'),
	('Razak Boukari', 'Togo', 'boukari'),
	('Riccardo Sottil', 'Italy', 'riccardo sottil'),
	('Riccardo Sottil', 'Italy', 'sottil'),
	('George Cooper', 'England', 'george cooper'),
	('George Cooper', 'England', 'cooper'),
	('Martín Galmarini', 'Argentina', 'galmarini'),
	('Martín Galmarini', 'Argentina', 'martin galmarini'),
	('Matty Lund', 'Northern Ireland', 'matty lund'),
	('Matty Lund', 'Northern Ireland', 'lund'),
	('Felix Torres', 'Ecuador', 'torres'),
	('Felix Torres', 'Ecuador', 'felix torres'),
	('Andriy Boryachuk', 'Ukraine', 'andriy boryachuk'),
	('Andriy Boryachuk', 'Ukraine', 'boryachuk'),
	('Melle Meulensteen', 'Netherlands', 'meulensteen'),
	('Melle Meulensteen', 'Netherlands', 'melle meulensteen'),
	('Liu Yun', 'China PR', 'liu yun'),
	('Liu Yun', 'China PR', 'yun'),
	('Yang Xu', 'China PR', 'yang xu'),
	('Yang Xu', 'China PR', 'xu'),
	('Juan Manuel Tévez', 'Argentina', 'tevez'),
	('Juan Manuel Tévez', 'Argentina', 'juan manuel tevez'),
	('Carlton Morris', 'England', 'carlton morris'),
	('Carlton Morris', 'England', 'morris'),
	('Luis Paz', 'Colombia', 'paz'),
	('Luis Paz', 'Colombia', 'luis paz'),
	('Anthony Syhre', 'Germany', 'anthony syhre'),
	('Anthony Syhre', 'Germany', 'syhre'),
	('Victor Melgar', 'Bolivia', 'melgar'),
	('Victor Melgar', 'Bolivia', 'victor melgar'),
	('Nikolaos Kainourgios', 'Greece', 'nikolaos kainourgios'),
	('Nikolaos Kainourgios', 'Greece', 'kainourgios'),
	('Saud Abdulhamid', 'Saudi Arabia', 'saud abdulhamid'),
	('Saud Abdulhamid', 'Saudi Arabia', 'abdulhamid'),
	('Alexandru Dandea', 'Romania', 'alexandru dandea'),
	('Alexandru Dandea', 'Romania', 'dandea'),
	('Johannes Tartarotti', 'Austria', 'tartarotti'),
	('Johannes Tartarotti', 'Austria', 'johannes tartarotti'),
	('Fodé Konaté', 'Mali', 'konate'),
	('Fodé Konaté', 'Mali', 'fode konate'),
	('Anel Šabanadžović', 'Bosnia Herzegovina', 'anel sabanadzovic'),
	('Anel Šabanadžović', 'Bosnia Herzegovina', 'sabanadzovic'),
	('Courtney Senior', 'England', 'senior'),
	('Courtney Senior', 'England', 'courtney senior'),
	('Žan Rogelj', 'Slovenia', 'rogelj'),
	('Žan Rogelj', 'Slovenia', 'zan rogelj'),
	('Dennis Erdmann', 'Germany', 'dennis erdmann'),
	('Dennis Erdmann', 'Germany', 'erdmann'),
	('Jacori Hayes', 'United States', 'jacori hayes'),
	('Jacori Hayes', 'United States', 'hayes'),
	('Takanori Sugeno', 'Japan', 'takanori sugeno'),
	('Takanori Sugeno', 'Japan', 'sugeno'),
	('John Björkengren', 'Sweden', 'john bjorkengren'),
	('John Björkengren', 'Sweden', 'bjorkengren'),
	('Ben Richards-Everton', 'England', 'richardseverton'),
	('Ben Richards-Everton', 'England', 'ben richardseverton'),
	('Neftali Manzambi', 'Switzerland', 'neftali manzambi'),
	('Neftali Manzambi', 'Switzerland', 'manzambi'),
	('Younès Kaabouni', 'France', 'younes kaabouni'),
	('Younès Kaabouni', 'France', 'kaabouni'),
	('Marko Kvasina', 'Austria', 'kvasina'),
	('Marko Kvasina', 'Austria', 'marko kvasina'),
	('Afimico Pululu', 'Angola', 'afimico pululu'),
	('Afimico Pululu', 'Angola', 'pululu'),
	('Gary Roberts', 'England', 'roberts'),
	('Gary Roberts', 'England', 'gary roberts'),
	('Edwin Herrera', 'Colombia', 'herrera'),
	('Edwin Herrera', 'Colombia', 'edwin herrera'),
	('Paul Akouokou', 'Ivory Coast', 'paul akouokou'),
	('Paul Akouokou', 'Ivory Coast', 'akouokou'),
	('Boy Kemper', 'Netherlands', 'boy kemper'),
	('Boy Kemper', 'Netherlands', 'kemper'),
	('Piotr Johansson', 'Sweden', 'johansson'),
	('Piotr Johansson', 'Sweden', 'piotr johansson'),
	('Alexander Rossipal', 'Germany', 'alexander rossipal'),
	('Alexander Rossipal', 'Germany', 'rossipal'),
	('Hamdan Al Shamrani', 'Saudi Arabia', 'hamdan al shamrani'),
	('Hamdan Al Shamrani', 'Saudi Arabia', 'shamrani'),
	('Yannick Schmid', 'Switzerland', 'yannick schmid'),
	('Yannick Schmid', 'Switzerland', 'schmid'),
	('Ryan Colclough', 'England', 'ryan colclough'),
	('Ryan Colclough', 'England', 'colclough'),
	('Isak Ssewankambo', 'Sweden', 'isak ssewankambo'),
	('Isak Ssewankambo', 'Sweden', 'ssewankambo'),
	('Nico Melamed', 'Spain', 'nico melamed'),
	('Nico Melamed', 'Spain', 'melamed'),
	('Ismael', 'Spain', 'ismael'),
	('Daiki Miya', 'Japan', 'miya'),
	('Daiki Miya', 'Japan', 'daiki miya'),
	('Pablo Gozálbez', 'Spain', 'gozalbez'),
	('Pablo Gozálbez', 'Spain', 'pablo gozalbez'),
	('José Hernández', 'Mexico', 'hernandez'),
	('José Hernández', 'Mexico', 'jose hernandez'),
	('Valtteri Moren', 'Finland', 'moren'),
	('Valtteri Moren', 'Finland', 'valtteri moren'),
	('Max Reinthaler', 'Italy', 'reinthaler'),
	('Max Reinthaler', 'Italy', 'max reinthaler'),
	('Dennis Iapichino', 'Switzerland', 'dennis iapichino'),
	('Dennis Iapichino', 'Switzerland', 'iapichino'),
	('Ben Pringle', 'England', 'ben pringle'),
	('Ben Pringle', 'England', 'pringle'),
	('Elliott Hewitt', 'Wales', 'hewitt'),
	('Elliott Hewitt', 'Wales', 'elliott hewitt'),
	('Jorge Flores', 'Bolivia', 'jorge flores'),
	('Jorge Flores', 'Bolivia', 'flores'),
	('Sambou Sissoko', 'France', 'sissoko'),
	('Sambou Sissoko', 'France', 'sambou sissoko'),
	('Quirin Moll', 'Germany', 'moll'),
	('Quirin Moll', 'Germany', 'quirin moll'),
	('Joao Ortiz', 'Ecuador', 'ortiz'),
	('Joao Ortiz', 'Ecuador', 'joao ortiz'),
	('Martín Ezequiel Cañete', 'Argentina', 'canete'),
	('Martín Ezequiel Cañete', 'Argentina', 'martin ezequiel canete'),
	('David Löfquist', 'Sweden', 'david lofquist'),
	('David Löfquist', 'Sweden', 'lofquist'),
	('Bruno Ramires', 'Brazil', 'ramires'),
	('Bruno Ramires', 'Brazil', 'bruno ramires'),
	('Yuji Hoshi', 'Japan', 'yuji hoshi'),
	('Yuji Hoshi', 'Japan', 'hoshi'),
	('Brek Shea', 'United States', 'shea'),
	('Brek Shea', 'United States', 'brek shea')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';