INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Blas Díaz', 'Paraguay', 'player'),
	('Flavien-Enzo Boyomo', 'France', 'player'),
	('Breiner Paz', 'Colombia', 'player'),
	('Christian Dalle Mura', 'Italy', 'player'),
	('Jota Gonçalves', 'Portugal', 'player'),
	('Amine Essabri', 'Belgium', 'player'),
	('George Miller', 'England', 'player'),
	('Owen Dale', 'England', 'player'),
	('Albin Winbo', 'Sweden', 'player'),
	('Anton Liljenbäck', 'Sweden', 'player'),
	('Novoa', 'Spain', 'player'),
	('Elhadj Dabo', 'Senegal', 'player'),
	('Adrien Lebeau', 'France', 'player'),
	('Muteb Al Mufarrij', 'Saudi Arabia', 'player'),
	('Joachim Soltvedt', 'Norway', 'player'),
	('Angus Thurgate', 'Australia', 'player'),
	('James Dayton', 'England', 'player'),
	('Diego Batista', 'Portugal', 'player'),
	('Dionicio Pérez', 'Paraguay', 'player'),
	('Connor Kirby', 'England', 'player'),
	('Ryota Aoki', 'Japan', 'player'),
	('Yuya Nakasaka', 'Japan', 'player'),
	('Viktor Johansson', 'Sweden', 'player'),
	('Cristian Paredes', 'Paraguay', 'player'),
	('Adam May', 'England', 'player'),
	('Amaury García', 'Mexico', 'player'),
	('Darell Tokpa', 'France', 'player'),
	('Matisse Samoise', 'Belgium', 'player'),
	('Zhang ZhenQiang', 'China PR', 'player'),
	('Anthony Scully', 'Republic of Ireland', 'player'),
	('Souleymane Aw', 'Senegal', 'player'),
	('Ko Sawada', 'Japan', 'player'),
	('Jin Pengxiang', 'China PR', 'player'),
	('Aníbal Gómez', 'Paraguay', 'player'),
	('Froilán', 'Spain', 'player'),
	('Mathieu De Smet', 'Belgium', 'player'),
	('Felipe Micael', 'Brazil', 'player'),
	('Dante Campisi', 'Argentina', 'player'),
	('Song Long', 'China PR', 'player'),
	('Kim Myeong Joon', 'Korea Republic', 'player'),
	('David Sesay', 'England', 'player'),
	('Mace Goodridge', 'England', 'player'),
	('Martin Vantruba', 'Slovakia', 'player'),
	('Yuto Iwasaki', 'Japan', 'player'),
	('Jorge Luna', 'Venezuela', 'player'),
	('Luke McCormick', 'England', 'player'),
	('David Moyo', 'Zimbabwe', 'player'),
	('Aldom Deuro', 'Mali', 'player'),
	('Diego Abella', 'Mexico', 'player'),
	('José Soto', 'Venezuela', 'player'),
	('Nick Anderton', 'England', 'player'),
	('Connor O''Toole', 'Australia', 'player'),
	('Matthis Harsman', 'Germany', 'player'),
	('Tobias Anselm', 'Austria', 'player'),
	('Sebastian Reyes', 'Bolivia', 'player'),
	('Maikol Quintero', 'Venezuela', 'player'),
	('Pascal Petlach', 'Austria', 'player'),
	('Widen Saucedo', 'Bolivia', 'player'),
	('Julian Schwermann', 'Germany', 'player'),
	('Alexis González', 'Paraguay', 'player'),
	('Juan Camilo Becerra', 'Colombia', 'player'),
	('Youssoupha N''Diaye', 'Senegal', 'player'),
	('Daniil Kulikov', 'Russia', 'player'),
	('Antoine Lejoly', 'Belgium', 'player'),
	('Mark McNulty', 'Republic of Ireland', 'player'),
	('Rob Cornwall', 'Republic of Ireland', 'player'),
	('Michel Rasmussen', 'Peru', 'player'),
	('Shawn Adewoye', 'Belgium', 'player'),
	('Jamie Cumming', 'England', 'player'),
	('Ruon Tongyik', 'South Sudan', 'player'),
	('Jofre', 'Spain', 'player'),
	('Lü Peng', 'China PR', 'player'),
	('Andre Wright', 'England', 'player'),
	('Pablo Míguez', 'Uruguay', 'player'),
	('Jaime Giraldo', 'Colombia', 'player'),
	('Rory Watson', 'England', 'player'),
	('Callum Cockerill-Mollett', 'Republic of Ireland', 'player'),
	('Dean Lyness', 'England', 'player'),
	('Julien Boyer', 'France', 'player'),
	('Bryan Sánchez', 'Ecuador', 'player'),
	('Cory Sene', 'Senegal', 'player'),
	('Rosario Latouchent', 'France', 'player'),
	('Souleymane Cissé', 'Senegal', 'player'),
	('Wesley Spieringhs', 'Netherlands', 'player'),
	('Connor Metcalfe', 'Australia', 'player'),
	('Juan Ignacio Nardoni', 'Argentina', 'player'),
	('Ricardo Marín', 'Mexico', 'player'),
	('Dimitar Mitov', 'Bulgaria', 'player'),
	('Keres Masangu', 'Belgium', 'player'),
	('Ryan Raposo', 'Canada', 'player'),
	('JJ Williams', 'United States', 'player'),
	('Matti Kamenz', 'Germany', 'player'),
	('Justin Neiß', 'Germany', 'player'),
	('Daniel-Edward Daniliuc', 'Austria', 'player'),
	('Yahcuroo Roemer', 'Netherlands', 'player'),
	('Dustin Willms', 'Germany', 'player'),
	('Otto Hindrich', 'Romania', 'player'),
	('Albie Morgan', 'England', 'player'),
	('Harry Clifton', 'Wales', 'player'),
	('Jan Just', 'Germany', 'player'),
	('Harry Trewbridge', 'Australia', 'player'),
	('Henry Rorig', 'Germany', 'player'),
	('Gaber Dobrovoljc', 'Slovenia', 'player'),
	('Harry Darling', 'England', 'player'),
	('Gastón Martirena', 'Uruguay', 'player'),
	('Jozo Stanić', 'Croatia', 'player'),
	('Filip Møller Delaveris', 'Norway', 'player'),
	('Yair Mena', 'Colombia', 'player'),
	('Fatih Kuruçuk', 'Turkey', 'player'),
	('David Miculescu', 'Romania', 'player'),
	('Jaman Al Dossary', 'Saudi Arabia', 'player'),
	('Archie Boroughbridge', 'Australia', 'player'),
	('Shayr Mohamed', 'Mexico', 'player'),
	('Romal Palmer', 'England', 'player'),
	('Mikhail Ageev', 'Russia', 'player'),
	('Momo Cissé', 'Guinea', 'player'),
	('Tom Clifford', 'England', 'player'),
	('Facundo Almada', 'Argentina', 'player'),
	('Hassane Adamou', 'Niger', 'player'),
	('Daniel Mikic', 'Germany', 'player'),
	('Damian Isac', 'Romania', 'player'),
	('Ai Zhibo', 'China PR', 'player'),
	('Iddy Ouattara', 'France', 'player'),
	('Brendan Kiernan', 'England', 'player'),
	('Kamal Bafounta', 'France', 'player'),
	('Patrick Hasenhüttl', 'Austria', 'player'),
	('Haruhiko Takimoto', 'Japan', 'player'),
	('David Parkhouse', 'Northern Ireland', 'player'),
	('Guillermo Centurión', 'Uruguay', 'player'),
	('Tomáš Suslov', 'Slovakia', 'player'),
	('Nenass', 'Cape Verde', 'player'),
	('Claudio Herrera', 'Uruguay', 'player'),
	('Lewis Hardcastle', 'England', 'player'),
	('Matthew Platt', 'England', 'player'),
	('Karol Szymański', 'Poland', 'player'),
	('Oliver Rushfort', 'Australia', 'player'),
	('Alihan Kalkan', 'Turkey', 'player'),
	('Marco Majouga', 'France', 'player'),
	('Jiang Jihong', 'China PR', 'player'),
	('Mauro Bustamante', 'Argentina', 'player'),
	('Osman Atilgan', 'Germany', 'player'),
	('Benedict dos Santos', 'Germany', 'player'),
	('Leverton Pierre', 'Haiti', 'player'),
	('Setigui Karamoko', 'France', 'player'),
	('Lee Gwang Yeon', 'Korea Republic', 'player'),
	('Ricky-Jade Jones', 'England', 'player'),
	('Facundo Cáseres', 'Argentina', 'player'),
	('Murat Sarıgül', 'Turkey', 'player'),
	('Lilian Egloff', 'Germany', 'player'),
	('Przemysław Bargiel', 'Poland', 'player'),
	('Tom Strannegård', 'Sweden', 'player'),
	('José Enamorado', 'Colombia', 'player'),
	('Franck Ellé Essouma', 'Cameroon', 'player'),
	('Yun Ju Tae', 'Korea Republic', 'player'),
	('Tobias Koch', 'Austria', 'player'),
	('Emre Kaplan', 'Azerbaijan', 'player'),
	('Julián Aude', 'Argentina', 'player'),
	('Konrad Handzlik', 'Poland', 'player'),
	('Sam Tillmanson', 'Australia', 'player'),
	('Muhammet Özkal', 'Turkey', 'player'),
	('Fynn Otto', 'Germany', 'player'),
	('Sylvain Deslandes', 'France', 'player'),
	('Moritz-Broni Kwarteng', 'Germany', 'player'),
	('Lirim Qamili', 'Albania', 'player'),
	('Johan Stenmark', 'Sweden', 'player'),
	('Frederik Jäkel', 'Germany', 'player'),
	('Alkain', 'Spain', 'player'),
	('Boris Moltenis', 'France', 'player'),
	('Musah Nuhu', 'Ghana', 'player'),
	('Nana Kofi Babil', 'Ghana', 'player'),
	('Jannes Wieckhoff', 'Germany', 'player'),
	('Nico Hecker', 'Germany', 'player'),
	('Niklas Tauer', 'Germany', 'player'),
	('Pablo Rodríguez', 'Spain', 'player'),
	('Akif Karagülmez', 'Netherlands', 'player'),
	('Habib Al Watyan', 'Saudi Arabia', 'player'),
	('Marius Hauptmann', 'Germany', 'player'),
	('Abdulaziz Al Dawsari', 'Saudi Arabia', 'player'),
	('Efe Tatlı', 'Turkey', 'player'),
	('Tobias Fleckstein', 'Germany', 'player'),
	('Daniel Bielica', 'Poland', 'player'),
	('Isak Jansson', 'Sweden', 'player'),
	('Dan N''Lundulu', 'England', 'player'),
	('Timon Weiner', 'Germany', 'player'),
	('Udoka Godwin-Malife', 'England', 'player'),
	('Ousoumane Camara', 'France', 'player'),
	('Luca Martínez Dupuy', 'Mexico', 'player'),
	('Ignacio Pais', 'Argentina', 'player'),
	('Tom Baack', 'Germany', 'player'),
	('Algobia', 'Spain', 'player'),
	('Benjamin McDriscoll', 'Australia', 'player'),
	('Gavin Kilkenny', 'Republic of Ireland', 'player'),
	('Abdoulaye Keita', 'Mali', 'player'),
	('Lars Markmanrud', 'Norway', 'player'),
	('Ifunayachi Achara', 'Nigeria', 'player'),
	('Gustavo Carvajal', 'Colombia', 'player'),
	('Andrea Ghezzi', 'Italy', 'player'),
	('Armando León', 'Mexico', 'player'),
	('Daniel Ściślak', 'Poland', 'player'),
	('Yuki Ohashi', 'Japan', 'player'),
	('Mikael Ndjoli', 'England', 'player'),
	('Juan de Dios Aguayo', 'Mexico', 'player'),
	('Patrick Plojer', 'Austria', 'player'),
	('Dragoș Balauru', 'Romania', 'player'),
	('Ahmet Gürleyen', 'Germany', 'player'),
	('Brandon Cooper', 'Wales', 'player'),
	('Lewis Italiano', 'Australia', 'player'),
	('Rarmani Edmonds-Green', 'England', 'player'),
	('Joey DeZart', 'Jamaica', 'player'),
	('Samed Karakoç', 'Turkey', 'player'),
	('Tyler Cordner', 'England', 'player'),
	('Omar Labrador', 'Venezuela', 'player'),
	('Nathan Sheron', 'England', 'player'),
	('Joe Fryer', 'England', 'player'),
	('Lucas Bernadou', 'France', 'player'),
	('Johannes Bühler', 'Germany', 'player'),
	('Piotr Pyrdoł', 'Poland', 'player'),
	('Lorik Emini', 'Switzerland', 'player'),
	('Victor Villalba', 'Paraguay', 'player'),
	('Dardan Shabanhaxhaj', 'Kosovo', 'player'),
	('Sam Ling', 'England', 'player'),
	('Baptiste Canelhas', 'France', 'player'),
	('Emmanuel Onariase', 'England', 'player'),
	('Oliver Casey', 'England', 'player'),
	('Jesús Sagredo', 'Bolivia', 'player'),
	('Ryu Jae Moon', 'Korea Republic', 'player'),
	('Viguera', 'Spain', 'player'),
	('Jesper Modig', 'Sweden', 'player'),
	('Ryan Loft', 'England', 'player'),
	('Owura Edwards', 'England', 'player'),
	('Maximilian Engl', 'Germany', 'player'),
	('Mustafa Al Bassas', 'Saudi Arabia', 'player'),
	('Brylon Petersen', 'South Africa', 'player'),
	('Brandon Pierrick', 'England', 'player'),
	('David Cawley', 'Republic of Ireland', 'player'),
	('Jakub Iskra', 'Poland', 'player'),
	('Erion Sadiku', 'Kosovo', 'player'),
	('Rekeil Pyke', 'England', 'player'),
	('Dren Feka', 'Kosovo', 'player'),
	('Olufela Olomola', 'England', 'player'),
	('Shu Mogi', 'Japan', 'player'),
	('Max Sanders', 'England', 'player'),
	('Andrei Dumiter', 'Romania', 'player'),
	('Hinata Kida', 'Japan', 'player'),
	('Li Yuanyi', 'China PR', 'player'),
	('Zhang Yuan', 'China PR', 'player'),
	('Odin Thiago Holm', 'Norway', 'player'),
	('Behadil Šabani', 'Germany', 'player'),
	('Abdoulaye Ndiaye', 'Senegal', 'player'),
	('Mohammed Al Majhad', 'Saudi Arabia', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Blas Díaz', 'Paraguay', 'blas diaz'),
	('Blas Díaz', 'Paraguay', 'diaz'),
	('Flavien-Enzo Boyomo', 'France', 'flavienenzo boyomo'),
	('Flavien-Enzo Boyomo', 'France', 'boyomo'),
	('Breiner Paz', 'Colombia', 'paz'),
	('Breiner Paz', 'Colombia', 'breiner paz'),
	('Christian Dalle Mura', 'Italy', 'mura'),
	('Christian Dalle Mura', 'Italy', 'christian dalle mura'),
	('Jota Gonçalves', 'Portugal', 'goncalves'),
	('Jota Gonçalves', 'Portugal', 'jota goncalves'),
	('Amine Essabri', 'Belgium', 'amine essabri'),
	('Amine Essabri', 'Belgium', 'essabri'),
	('George Miller', 'England', 'miller'),
	('George Miller', 'England', 'george miller'),
	('Owen Dale', 'England', 'dale'),
	('Owen Dale', 'England', 'owen dale'),
	('Albin Winbo', 'Sweden', 'albin winbo'),
	('Albin Winbo', 'Sweden', 'winbo'),
	('Anton Liljenbäck', 'Sweden', 'anton liljenback'),
	('Anton Liljenbäck', 'Sweden', 'liljenback'),
	('Novoa', 'Spain', 'novoa'),
	('Elhadj Dabo', 'Senegal', 'dabo'),
	('Elhadj Dabo', 'Senegal', 'elhadj dabo'),
	('Adrien Lebeau', 'France', 'lebeau'),
	('Adrien Lebeau', 'France', 'adrien lebeau'),
	('Muteb Al Mufarrij', 'Saudi Arabia', 'mufarrij'),
	('Muteb Al Mufarrij', 'Saudi Arabia', 'muteb al mufarrij'),
	('Joachim Soltvedt', 'Norway', 'soltvedt'),
	('Joachim Soltvedt', 'Norway', 'joachim soltvedt'),
	('Angus Thurgate', 'Australia', 'thurgate'),
	('Angus Thurgate', 'Australia', 'angus thurgate'),
	('James Dayton', 'England', 'james dayton'),
	('James Dayton', 'England', 'dayton'),
	('Diego Batista', 'Portugal', 'batista'),
	('Diego Batista', 'Portugal', 'diego batista'),
	('Dionicio Pérez', 'Paraguay', 'perez'),
	('Dionicio Pérez', 'Paraguay', 'dionicio perez'),
	('Connor Kirby', 'England', 'kirby'),
	('Connor Kirby', 'England', 'connor kirby'),
	('Ryota Aoki', 'Japan', 'aoki'),
	('Ryota Aoki', 'Japan', 'ryota aoki'),
	('Yuya Nakasaka', 'Japan', 'nakasaka'),
	('Yuya Nakasaka', 'Japan', 'yuya nakasaka'),
	('Viktor Johansson', 'Sweden', 'johansson'),
	('Viktor Johansson', 'Sweden', 'viktor johansson'),
	('Cristian Paredes', 'Paraguay', 'cristian paredes'),
	('Cristian Paredes', 'Paraguay', 'paredes'),
	('Adam May', 'England', 'adam may'),
	('Adam May', 'England', 'may'),
	('Amaury García', 'Mexico', 'amaury garcia'),
	('Amaury García', 'Mexico', 'garcia'),
	('Darell Tokpa', 'France', 'darell tokpa'),
	('Darell Tokpa', 'France', 'tokpa'),
	('Matisse Samoise', 'Belgium', 'samoise'),
	('Matisse Samoise', 'Belgium', 'matisse samoise'),
	('Zhang ZhenQiang', 'China PR', 'zhang zhenqiang'),
	('Zhang ZhenQiang', 'China PR', 'zhenqiang'),
	('Anthony Scully', 'Republic of Ireland', 'scully'),
	('Anthony Scully', 'Republic of Ireland', 'anthony scully'),
	('Souleymane Aw', 'Senegal', 'aw'),
	('Souleymane Aw', 'Senegal', 'souleymane aw'),
	('Ko Sawada', 'Japan', 'ko sawada'),
	('Ko Sawada', 'Japan', 'sawada'),
	('Jin Pengxiang', 'China PR', 'jin pengxiang'),
	('Jin Pengxiang', 'China PR', 'pengxiang'),
	('Aníbal Gómez', 'Paraguay', 'anibal gomez'),
	('Aníbal Gómez', 'Paraguay', 'gomez'),
	('Froilán', 'Spain', 'froilan'),
	('Mathieu De Smet', 'Belgium', 'smet'),
	('Mathieu De Smet', 'Belgium', 'mathieu de smet'),
	('Felipe Micael', 'Brazil', 'micael'),
	('Felipe Micael', 'Brazil', 'felipe micael'),
	('Dante Campisi', 'Argentina', 'campisi'),
	('Dante Campisi', 'Argentina', 'dante campisi'),
	('Song Long', 'China PR', 'song long'),
	('Song Long', 'China PR', 'long'),
	('Kim Myeong Joon', 'Korea Republic', 'joon'),
	('Kim Myeong Joon', 'Korea Republic', 'kim myeong joon'),
	('David Sesay', 'England', 'david sesay'),
	('David Sesay', 'England', 'sesay'),
	('Mace Goodridge', 'England', 'goodridge'),
	('Mace Goodridge', 'England', 'mace goodridge'),
	('Martin Vantruba', 'Slovakia', 'vantruba'),
	('Martin Vantruba', 'Slovakia', 'martin vantruba'),
	('Yuto Iwasaki', 'Japan', 'iwasaki'),
	('Yuto Iwasaki', 'Japan', 'yuto iwasaki'),
	('Jorge Luna', 'Venezuela', 'luna'),
	('Jorge Luna', 'Venezuela', 'jorge luna'),
	('Luke McCormick', 'England', 'luke mccormick'),
	('Luke McCormick', 'England', 'mccormick'),
	('David Moyo', 'Zimbabwe', 'moyo'),
	('David Moyo', 'Zimbabwe', 'david moyo'),
	('Aldom Deuro', 'Mali', 'deuro'),
	('Aldom Deuro', 'Mali', 'aldom deuro'),
	('Diego Abella', 'Mexico', 'diego abella'),
	('Diego Abella', 'Mexico', 'abella'),
	('José Soto', 'Venezuela', 'jose soto'),
	('José Soto', 'Venezuela', 'soto'),
	('Nick Anderton', 'England', 'nick anderton'),
	('Nick Anderton', 'England', 'anderton'),
	('Connor O''Toole', 'Australia', 'connor otoole'),
	('Connor O''Toole', 'Australia', 'otoole'),
	('Matthis Harsman', 'Germany', 'matthis harsman'),
	('Matthis Harsman', 'Germany', 'harsman'),
	('Tobias Anselm', 'Austria', 'tobias anselm'),
	('Tobias Anselm', 'Austria', 'anselm'),
	('Sebastian Reyes', 'Bolivia', 'sebastian reyes'),
	('Sebastian Reyes', 'Bolivia', 'reyes'),
	('Maikol Quintero', 'Venezuela', 'maikol quintero'),
	('Maikol Quintero', 'Venezuela', 'quintero'),
	('Pascal Petlach', 'Austria', 'pascal petlach'),
	('Pascal Petlach', 'Austria', 'petlach'),
	('Widen Saucedo', 'Bolivia', 'widen saucedo'),
	('Widen Saucedo', 'Bolivia', 'saucedo'),
	('Julian Schwermann', 'Germany', 'schwermann'),
	('Julian Schwermann', 'Germany', 'julian schwermann'),
	('Alexis González', 'Paraguay', 'gonzalez'),
	('Alexis González', 'Paraguay', 'alexis gonzalez'),
	('Juan Camilo Becerra', 'Colombia', 'becerra'),
	('Juan Camilo Becerra', 'Colombia', 'juan camilo becerra'),
	('Youssoupha N''Diaye', 'Senegal', 'ndiaye'),
	('Youssoupha N''Diaye', 'Senegal', 'youssoupha ndiaye'),
	('Daniil Kulikov', 'Russia', 'daniil kulikov'),
	('Daniil Kulikov', 'Russia', 'kulikov'),
	('Antoine Lejoly', 'Belgium', 'antoine lejoly'),
	('Antoine Lejoly', 'Belgium', 'lejoly'),
	('Mark McNulty', 'Republic of Ireland', 'mark mcnulty'),
	('Mark McNulty', 'Republic of Ireland', 'mcnulty'),
	('Rob Cornwall', 'Republic of Ireland', 'rob cornwall'),
	('Rob Cornwall', 'Republic of Ireland', 'cornwall'),
	('Michel Rasmussen', 'Peru', 'michel rasmussen'),
	('Michel Rasmussen', 'Peru', 'rasmussen'),
	('Shawn Adewoye', 'Belgium', 'adewoye'),
	('Shawn Adewoye', 'Belgium', 'shawn adewoye'),
	('Jamie Cumming', 'England', 'cumming'),
	('Jamie Cumming', 'England', 'jamie cumming'),
	('Ruon Tongyik', 'South Sudan', 'tongyik'),
	('Ruon Tongyik', 'South Sudan', 'ruon tongyik'),
	('Jofre', 'Spain', 'jofre'),
	('Lü Peng', 'China PR', 'lu peng'),
	('Lü Peng', 'China PR', 'peng'),
	('Andre Wright', 'England', 'andre wright'),
	('Andre Wright', 'England', 'wright'),
	('Pablo Míguez', 'Uruguay', 'pablo miguez'),
	('Pablo Míguez', 'Uruguay', 'miguez'),
	('Jaime Giraldo', 'Colombia', 'giraldo'),
	('Jaime Giraldo', 'Colombia', 'jaime giraldo'),
	('Rory Watson', 'England', 'watson'),
	('Rory Watson', 'England', 'rory watson'),
	('Callum Cockerill-Mollett', 'Republic of Ireland', 'callum cockerillmollett'),
	('Callum Cockerill-Mollett', 'Republic of Ireland', 'cockerillmollett'),
	('Dean Lyness', 'England', 'dean lyness'),
	('Dean Lyness', 'England', 'lyness'),
	('Julien Boyer', 'France', 'julien boyer'),
	('Julien Boyer', 'France', 'boyer'),
	('Bryan Sánchez', 'Ecuador', 'bryan sanchez'),
	('Bryan Sánchez', 'Ecuador', 'sanchez'),
	('Cory Sene', 'Senegal', 'sene'),
	('Cory Sene', 'Senegal', 'cory sene'),
	('Rosario Latouchent', 'France', 'latouchent'),
	('Rosario Latouchent', 'France', 'rosario latouchent'),
	('Souleymane Cissé', 'Senegal', 'souleymane cisse'),
	('Souleymane Cissé', 'Senegal', 'cisse'),
	('Wesley Spieringhs', 'Netherlands', 'wesley spieringhs'),
	('Wesley Spieringhs', 'Netherlands', 'spieringhs'),
	('Connor Metcalfe', 'Australia', 'connor metcalfe'),
	('Connor Metcalfe', 'Australia', 'metcalfe'),
	('Juan Ignacio Nardoni', 'Argentina', 'nardoni'),
	('Juan Ignacio Nardoni', 'Argentina', 'juan ignacio nardoni'),
	('Ricardo Marín', 'Mexico', 'ricardo marin'),
	('Ricardo Marín', 'Mexico', 'marin'),
	('Dimitar Mitov', 'Bulgaria', 'dimitar mitov'),
	('Dimitar Mitov', 'Bulgaria', 'mitov'),
	('Keres Masangu', 'Belgium', 'keres masangu'),
	('Keres Masangu', 'Belgium', 'masangu'),
	('Ryan Raposo', 'Canada', 'raposo'),
	('Ryan Raposo', 'Canada', 'ryan raposo'),
	('JJ Williams', 'United States', 'jj williams'),
	('JJ Williams', 'United States', 'williams'),
	('Matti Kamenz', 'Germany', 'matti kamenz'),
	('Matti Kamenz', 'Germany', 'kamenz'),
	('Justin Neiß', 'Germany', 'justin nei'),
	('Justin Neiß', 'Germany', 'nei'),
	('Daniel-Edward Daniliuc', 'Austria', 'danieledward daniliuc'),
	('Daniel-Edward Daniliuc', 'Austria', 'daniliuc'),
	('Yahcuroo Roemer', 'Netherlands', 'yahcuroo roemer'),
	('Yahcuroo Roemer', 'Netherlands', 'roemer'),
	('Dustin Willms', 'Germany', 'willms'),
	('Dustin Willms', 'Germany', 'dustin willms'),
	('Otto Hindrich', 'Romania', 'hindrich'),
	('Otto Hindrich', 'Romania', 'otto hindrich'),
	('Albie Morgan', 'England', 'albie morgan'),
	('Albie Morgan', 'England', 'morgan'),
	('Harry Clifton', 'Wales', 'harry clifton'),
	('Harry Clifton', 'Wales', 'clifton'),
	('Jan Just', 'Germany', 'jan just'),
	('Jan Just', 'Germany', 'just'),
	('Harry Trewbridge', 'Australia', 'harry trewbridge'),
	('Harry Trewbridge', 'Australia', 'trewbridge'),
	('Henry Rorig', 'Germany', 'henry rorig'),
	('Henry Rorig', 'Germany', 'rorig'),
	('Gaber Dobrovoljc', 'Slovenia', 'gaber dobrovoljc'),
	('Gaber Dobrovoljc', 'Slovenia', 'dobrovoljc'),
	('Harry Darling', 'England', 'harry darling'),
	('Harry Darling', 'England', 'darling'),
	('Gastón Martirena', 'Uruguay', 'martirena'),
	('Gastón Martirena', 'Uruguay', 'gaston martirena'),
	('Jozo Stanić', 'Croatia', 'jozo stanic'),
	('Jozo Stanić', 'Croatia', 'stanic'),
	('Filip Møller Delaveris', 'Norway', 'delaveris'),
	('Filip Møller Delaveris', 'Norway', 'filip mller delaveris'),
	('Yair Mena', 'Colombia', 'yair mena'),
	('Yair Mena', 'Colombia', 'mena'),
	('Fatih Kuruçuk', 'Turkey', 'kurucuk'),
	('Fatih Kuruçuk', 'Turkey', 'fatih kurucuk'),
	('David Miculescu', 'Romania', 'miculescu'),
	('David Miculescu', 'Romania', 'david miculescu'),
	('Jaman Al Dossary', 'Saudi Arabia', 'jaman al dossary'),
	('Jaman Al Dossary', 'Saudi Arabia', 'dossary'),
	('Archie Boroughbridge', 'Australia', 'archie boroughbridge'),
	('Archie Boroughbridge', 'Australia', 'boroughbridge'),
	('Shayr Mohamed', 'Mexico', 'shayr mohamed'),
	('Shayr Mohamed', 'Mexico', 'mohamed'),
	('Romal Palmer', 'England', 'palmer'),
	('Romal Palmer', 'England', 'romal palmer'),
	('Mikhail Ageev', 'Russia', 'mikhail ageev'),
	('Mikhail Ageev', 'Russia', 'ageev'),
	('Momo Cissé', 'Guinea', 'momo cisse'),
	('Momo Cissé', 'Guinea', 'cisse'),
	('Tom Clifford', 'England', 'tom clifford'),
	('Tom Clifford', 'England', 'clifford'),
	('Facundo Almada', 'Argentina', 'facundo almada'),
	('Facundo Almada', 'Argentina', 'almada'),
	('Hassane Adamou', 'Niger', 'adamou'),
	('Hassane Adamou', 'Niger', 'hassane adamou'),
	('Daniel Mikic', 'Germany', 'daniel mikic'),
	('Daniel Mikic', 'Germany', 'mikic'),
	('Damian Isac', 'Romania', 'damian isac'),
	('Damian Isac', 'Romania', 'isac'),
	('Ai Zhibo', 'China PR', 'zhibo'),
	('Ai Zhibo', 'China PR', 'ai zhibo'),
	('Iddy Ouattara', 'France', 'iddy ouattara'),
	('Iddy Ouattara', 'France', 'ouattara'),
	('Brendan Kiernan', 'England', 'kiernan'),
	('Brendan Kiernan', 'England', 'brendan kiernan'),
	('Kamal Bafounta', 'France', 'bafounta'),
	('Kamal Bafounta', 'France', 'kamal bafounta'),
	('Patrick Hasenhüttl', 'Austria', 'patrick hasenhuttl'),
	('Patrick Hasenhüttl', 'Austria', 'hasenhuttl'),
	('Haruhiko Takimoto', 'Japan', 'takimoto'),
	('Haruhiko Takimoto', 'Japan', 'haruhiko takimoto'),
	('David Parkhouse', 'Northern Ireland', 'david parkhouse'),
	('David Parkhouse', 'Northern Ireland', 'parkhouse'),
	('Guillermo Centurión', 'Uruguay', 'centurion'),
	('Guillermo Centurión', 'Uruguay', 'guillermo centurion'),
	('Tomáš Suslov', 'Slovakia', 'tomas suslov'),
	('Tomáš Suslov', 'Slovakia', 'suslov'),
	('Nenass', 'Cape Verde', 'nenass'),
	('Claudio Herrera', 'Uruguay', 'herrera'),
	('Claudio Herrera', 'Uruguay', 'claudio herrera'),
	('Lewis Hardcastle', 'England', 'hardcastle'),
	('Lewis Hardcastle', 'England', 'lewis hardcastle'),
	('Matthew Platt', 'England', 'matthew platt'),
	('Matthew Platt', 'England', 'platt'),
	('Karol Szymański', 'Poland', 'szymanski'),
	('Karol Szymański', 'Poland', 'karol szymanski'),
	('Oliver Rushfort', 'Australia', 'rushfort'),
	('Oliver Rushfort', 'Australia', 'oliver rushfort'),
	('Alihan Kalkan', 'Turkey', 'alihan kalkan'),
	('Alihan Kalkan', 'Turkey', 'kalkan'),
	('Marco Majouga', 'France', 'marco majouga'),
	('Marco Majouga', 'France', 'majouga'),
	('Jiang Jihong', 'China PR', 'jiang jihong'),
	('Jiang Jihong', 'China PR', 'jihong'),
	('Mauro Bustamante', 'Argentina', 'bustamante'),
	('Mauro Bustamante', 'Argentina', 'mauro bustamante'),
	('Osman Atilgan', 'Germany', 'osman atilgan'),
	('Osman Atilgan', 'Germany', 'atilgan'),
	('Benedict dos Santos', 'Germany', 'santos'),
	('Benedict dos Santos', 'Germany', 'benedict dos santos'),
	('Leverton Pierre', 'Haiti', 'leverton pierre'),
	('Leverton Pierre', 'Haiti', 'pierre'),
	('Setigui Karamoko', 'France', 'karamoko'),
	('Setigui Karamoko', 'France', 'setigui karamoko'),
	('Lee Gwang Yeon', 'Korea Republic', 'yeon'),
	('Lee Gwang Yeon', 'Korea Republic', 'lee gwang yeon'),
	('Ricky-Jade Jones', 'England', 'jones'),
	('Ricky-Jade Jones', 'England', 'rickyjade jones'),
	('Facundo Cáseres', 'Argentina', 'caseres'),
	('Facundo Cáseres', 'Argentina', 'facundo caseres'),
	('Murat Sarıgül', 'Turkey', 'sargul'),
	('Murat Sarıgül', 'Turkey', 'murat sargul'),
	('Lilian Egloff', 'Germany', 'lilian egloff'),
	('Lilian Egloff', 'Germany', 'egloff'),
	('Przemysław Bargiel', 'Poland', 'przemysaw bargiel'),
	('Przemysław Bargiel', 'Poland', 'bargiel'),
	('Tom Strannegård', 'Sweden', 'tom strannegard'),
	('Tom Strannegård', 'Sweden', 'strannegard'),
	('José Enamorado', 'Colombia', 'jose enamorado'),
	('José Enamorado', 'Colombia', 'enamorado'),
	('Franck Ellé Essouma', 'Cameroon', 'essouma'),
	('Franck Ellé Essouma', 'Cameroon', 'franck elle essouma'),
	('Yun Ju Tae', 'Korea Republic', 'tae'),
	('Yun Ju Tae', 'Korea Republic', 'yun ju tae'),
	('Tobias Koch', 'Austria', 'koch'),
	('Tobias Koch', 'Austria', 'tobias koch'),
	('Emre Kaplan', 'Azerbaijan', 'kaplan'),
	('Emre Kaplan', 'Azerbaijan', 'emre kaplan'),
	('Julián Aude', 'Argentina', 'aude'),
	('Julián Aude', 'Argentina', 'julian aude'),
	('Konrad Handzlik', 'Poland', 'konrad handzlik'),
	('Konrad Handzlik', 'Poland', 'handzlik'),
	('Sam Tillmanson', 'Australia', 'sam tillmanson'),
	('Sam Tillmanson', 'Australia', 'tillmanson'),
	('Muhammet Özkal', 'Turkey', 'muhammet ozkal'),
	('Muhammet Özkal', 'Turkey', 'ozkal'),
	('Fynn Otto', 'Germany', 'otto'),
	('Fynn Otto', 'Germany', 'fynn otto'),
	('Sylvain Deslandes', 'France', 'deslandes'),
	('Sylvain Deslandes', 'France', 'sylvain deslandes'),
	('Moritz-Broni Kwarteng', 'Germany', 'kwarteng'),
	('Moritz-Broni Kwarteng', 'Germany', 'moritzbroni kwarteng'),
	('Lirim Qamili', 'Albania', 'lirim qamili'),
	('Lirim Qamili', 'Albania', 'qamili'),
	('Johan Stenmark', 'Sweden', 'stenmark'),
	('Johan Stenmark', 'Sweden', 'johan stenmark'),
	('Frederik Jäkel', 'Germany', 'frederik jakel'),
	('Frederik Jäkel', 'Germany', 'jakel'),
	('Alkain', 'Spain', 'alkain'),
	('Boris Moltenis', 'France', 'moltenis'),
	('Boris Moltenis', 'France', 'boris moltenis'),
	('Musah Nuhu', 'Ghana', 'nuhu'),
	('Musah Nuhu', 'Ghana', 'musah nuhu'),
	('Nana Kofi Babil', 'Ghana', 'babil'),
	('Nana Kofi Babil', 'Ghana', 'nana kofi babil'),
	('Jannes Wieckhoff', 'Germany', 'wieckhoff'),
	('Jannes Wieckhoff', 'Germany', 'jannes wieckhoff'),
	('Nico Hecker', 'Germany', 'hecker'),
	('Nico Hecker', 'Germany', 'nico hecker'),
	('Niklas Tauer', 'Germany', 'tauer'),
	('Niklas Tauer', 'Germany', 'niklas tauer'),
	('Pablo Rodríguez', 'Spain', 'pablo rodriguez'),
	('Pablo Rodríguez', 'Spain', 'rodriguez'),
	('Akif Karagülmez', 'Netherlands', 'karagulmez'),
	('Akif Karagülmez', 'Netherlands', 'akif karagulmez'),
	('Habib Al Watyan', 'Saudi Arabia', 'habib al watyan'),
	('Habib Al Watyan', 'Saudi Arabia', 'watyan'),
	('Marius Hauptmann', 'Germany', 'marius hauptmann'),
	('Marius Hauptmann', 'Germany', 'hauptmann'),
	('Abdulaziz Al Dawsari', 'Saudi Arabia', 'abdulaziz al dawsari'),
	('Abdulaziz Al Dawsari', 'Saudi Arabia', 'dawsari'),
	('Efe Tatlı', 'Turkey', 'tatl'),
	('Efe Tatlı', 'Turkey', 'efe tatl'),
	('Tobias Fleckstein', 'Germany', 'fleckstein'),
	('Tobias Fleckstein', 'Germany', 'tobias fleckstein'),
	('Daniel Bielica', 'Poland', 'bielica'),
	('Daniel Bielica', 'Poland', 'daniel bielica'),
	('Isak Jansson', 'Sweden', 'isak jansson'),
	('Isak Jansson', 'Sweden', 'jansson'),
	('Dan N''Lundulu', 'England', 'dan nlundulu'),
	('Dan N''Lundulu', 'England', 'nlundulu'),
	('Timon Weiner', 'Germany', 'timon weiner'),
	('Timon Weiner', 'Germany', 'weiner'),
	('Udoka Godwin-Malife', 'England', 'udoka godwinmalife'),
	('Udoka Godwin-Malife', 'England', 'godwinmalife'),
	('Ousoumane Camara', 'France', 'ousoumane camara'),
	('Ousoumane Camara', 'France', 'camara'),
	('Luca Martínez Dupuy', 'Mexico', 'luca martinez dupuy'),
	('Luca Martínez Dupuy', 'Mexico', 'dupuy'),
	('Ignacio Pais', 'Argentina', 'pais'),
	('Ignacio Pais', 'Argentina', 'ignacio pais'),
	('Tom Baack', 'Germany', 'tom baack'),
	('Tom Baack', 'Germany', 'baack'),
	('Algobia', 'Spain', 'algobia'),
	('Benjamin McDriscoll', 'Australia', 'benjamin mcdriscoll'),
	('Benjamin McDriscoll', 'Australia', 'mcdriscoll'),
	('Gavin Kilkenny', 'Republic of Ireland', 'gavin kilkenny'),
	('Gavin Kilkenny', 'Republic of Ireland', 'kilkenny'),
	('Abdoulaye Keita', 'Mali', 'abdoulaye keita'),
	('Abdoulaye Keita', 'Mali', 'keita'),
	('Lars Markmanrud', 'Norway', 'markmanrud'),
	('Lars Markmanrud', 'Norway', 'lars markmanrud'),
	('Ifunayachi Achara', 'Nigeria', 'ifunayachi achara'),
	('Ifunayachi Achara', 'Nigeria', 'achara'),
	('Gustavo Carvajal', 'Colombia', 'carvajal'),
	('Gustavo Carvajal', 'Colombia', 'gustavo carvajal'),
	('Andrea Ghezzi', 'Italy', 'andrea ghezzi'),
	('Andrea Ghezzi', 'Italy', 'ghezzi'),
	('Armando León', 'Mexico', 'armando leon'),
	('Armando León', 'Mexico', 'leon'),
	('Daniel Ściślak', 'Poland', 'daniel scislak'),
	('Daniel Ściślak', 'Poland', 'scislak'),
	('Yuki Ohashi', 'Japan', 'ohashi'),
	('Yuki Ohashi', 'Japan', 'yuki ohashi'),
	('Mikael Ndjoli', 'England', 'ndjoli'),
	('Mikael Ndjoli', 'England', 'mikael ndjoli'),
	('Juan de Dios Aguayo', 'Mexico', 'juan de dios aguayo'),
	('Juan de Dios Aguayo', 'Mexico', 'aguayo'),
	('Patrick Plojer', 'Austria', 'plojer'),
	('Patrick Plojer', 'Austria', 'patrick plojer'),
	('Dragoș Balauru', 'Romania', 'dragos balauru'),
	('Dragoș Balauru', 'Romania', 'balauru'),
	('Ahmet Gürleyen', 'Germany', 'ahmet gurleyen'),
	('Ahmet Gürleyen', 'Germany', 'gurleyen'),
	('Brandon Cooper', 'Wales', 'brandon cooper'),
	('Brandon Cooper', 'Wales', 'cooper'),
	('Lewis Italiano', 'Australia', 'lewis italiano'),
	('Lewis Italiano', 'Australia', 'italiano'),
	('Rarmani Edmonds-Green', 'England', 'edmondsgreen'),
	('Rarmani Edmonds-Green', 'England', 'rarmani edmondsgreen'),
	('Joey DeZart', 'Jamaica', 'joey dezart'),
	('Joey DeZart', 'Jamaica', 'dezart'),
	('Samed Karakoç', 'Turkey', 'karakoc'),
	('Samed Karakoç', 'Turkey', 'samed karakoc'),
	('Tyler Cordner', 'England', 'tyler cordner'),
	('Tyler Cordner', 'England', 'cordner'),
	('Omar Labrador', 'Venezuela', 'labrador'),
	('Omar Labrador', 'Venezuela', 'omar labrador'),
	('Nathan Sheron', 'England', 'sheron'),
	('Nathan Sheron', 'England', 'nathan sheron'),
	('Joe Fryer', 'England', 'fryer'),
	('Joe Fryer', 'England', 'joe fryer'),
	('Lucas Bernadou', 'France', 'lucas bernadou'),
	('Lucas Bernadou', 'France', 'bernadou'),
	('Johannes Bühler', 'Germany', 'buhler'),
	('Johannes Bühler', 'Germany', 'johannes buhler'),
	('Piotr Pyrdoł', 'Poland', 'pyrdo'),
	('Piotr Pyrdoł', 'Poland', 'piotr pyrdo'),
	('Lorik Emini', 'Switzerland', 'emini'),
	('Lorik Emini', 'Switzerland', 'lorik emini'),
	('Victor Villalba', 'Paraguay', 'villalba'),
	('Victor Villalba', 'Paraguay', 'victor villalba'),
	('Dardan Shabanhaxhaj', 'Kosovo', 'shabanhaxhaj'),
	('Dardan Shabanhaxhaj', 'Kosovo', 'dardan shabanhaxhaj'),
	('Sam Ling', 'England', 'sam ling'),
	('Sam Ling', 'England', 'ling'),
	('Baptiste Canelhas', 'France', 'canelhas'),
	('Baptiste Canelhas', 'France', 'baptiste canelhas'),
	('Emmanuel Onariase', 'England', 'emmanuel onariase'),
	('Emmanuel Onariase', 'England', 'onariase'),
	('Oliver Casey', 'England', 'casey'),
	('Oliver Casey', 'England', 'oliver casey'),
	('Jesús Sagredo', 'Bolivia', 'sagredo'),
	('Jesús Sagredo', 'Bolivia', 'jesus sagredo'),
	('Ryu Jae Moon', 'Korea Republic', 'ryu jae moon'),
	('Ryu Jae Moon', 'Korea Republic', 'moon'),
	('Viguera', 'Spain', 'viguera'),
	('Jesper Modig', 'Sweden', 'jesper modig'),
	('Jesper Modig', 'Sweden', 'modig'),
	('Ryan Loft', 'England', 'loft'),
	('Ryan Loft', 'England', 'ryan loft'),
	('Owura Edwards', 'England', 'edwards'),
	('Owura Edwards', 'England', 'owura edwards'),
	('Maximilian Engl', 'Germany', 'engl'),
	('Maximilian Engl', 'Germany', 'maximilian engl'),
	('Mustafa Al Bassas', 'Saudi Arabia', 'bassas'),
	('Mustafa Al Bassas', 'Saudi Arabia', 'mustafa al bassas'),
	('Brylon Petersen', 'South Africa', 'petersen'),
	('Brylon Petersen', 'South Africa', 'brylon petersen'),
	('Brandon Pierrick', 'England', 'brandon pierrick'),
	('Brandon Pierrick', 'England', 'pierrick'),
	('David Cawley', 'Republic of Ireland', 'david cawley'),
	('David Cawley', 'Republic of Ireland', 'cawley'),
	('Jakub Iskra', 'Poland', 'jakub iskra'),
	('Jakub Iskra', 'Poland', 'iskra'),
	('Erion Sadiku', 'Kosovo', 'erion sadiku'),
	('Erion Sadiku', 'Kosovo', 'sadiku'),
	('Rekeil Pyke', 'England', 'pyke'),
	('Rekeil Pyke', 'England', 'rekeil pyke'),
	('Dren Feka', 'Kosovo', 'dren feka'),
	('Dren Feka', 'Kosovo', 'feka'),
	('Olufela Olomola', 'England', 'olomola'),
	('Olufela Olomola', 'England', 'olufela olomola'),
	('Shu Mogi', 'Japan', 'mogi'),
	('Shu Mogi', 'Japan', 'shu mogi'),
	('Max Sanders', 'England', 'max sanders'),
	('Max Sanders', 'England', 'sanders'),
	('Andrei Dumiter', 'Romania', 'andrei dumiter'),
	('Andrei Dumiter', 'Romania', 'dumiter'),
	('Hinata Kida', 'Japan', 'kida'),
	('Hinata Kida', 'Japan', 'hinata kida'),
	('Li Yuanyi', 'China PR', 'li yuanyi'),
	('Li Yuanyi', 'China PR', 'yuanyi'),
	('Zhang Yuan', 'China PR', 'zhang yuan'),
	('Zhang Yuan', 'China PR', 'yuan'),
	('Odin Thiago Holm', 'Norway', 'odin thiago holm'),
	('Odin Thiago Holm', 'Norway', 'holm'),
	('Behadil Šabani', 'Germany', 'behadil sabani'),
	('Behadil Šabani', 'Germany', 'sabani'),
	('Abdoulaye Ndiaye', 'Senegal', 'abdoulaye ndiaye'),
	('Abdoulaye Ndiaye', 'Senegal', 'ndiaye'),
	('Mohammed Al Majhad', 'Saudi Arabia', 'mohammed al majhad'),
	('Mohammed Al Majhad', 'Saudi Arabia', 'majhad')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';