INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Marco Rente', 'Germany', 'player'),
	('Tristan Nydam', 'England', 'player'),
	('Paul Kalambayi', 'England', 'player'),
	('Oli Shaw', 'Scotland', 'player'),
	('Lucian Dumitriu', 'Romania', 'player'),
	('Erik Israelsson', 'Sweden', 'player'),
	('Dominik Starkl', 'Austria', 'player'),
	('Echu', 'Spain', 'player'),
	('Vangelis Theocharis', 'Greece', 'player'),
	('Joan Monterde', 'Spain', 'player'),
	('Efrain Alvarez', 'Mexico', 'player'),
	('Michał Koj', 'Poland', 'player'),
	('Kim Tae Youn', 'Korea Republic', 'player'),
	('Nicolas Bürgy', 'Switzerland', 'player'),
	('Kim Seon Woo', 'Korea Republic', 'player'),
	('Ola Solbakken', 'Norway', 'player'),
	('Diego Becker', 'Argentina', 'player'),
	('Johannes Dörfler', 'Germany', 'player'),
	('Naoya Fukumori', 'Japan', 'player'),
	('Sébastien Flochon', 'France', 'player'),
	('Joe Widdowson', 'England', 'player'),
	('Lawrence Vigouroux', 'Chile', 'player'),
	('Guillaume Gigliotti', 'France', 'player'),
	('Chen Zhizhao', 'China PR', 'player'),
	('Yuta Higuchi', 'Japan', 'player'),
	('Cameron Puertas', 'Switzerland', 'player'),
	('Bryan Alceus', 'Haiti', 'player'),
	('Kieran O''Hara', 'Republic of Ireland', 'player'),
	('Thomas Glover', 'Australia', 'player'),
	('Yasyn Hamza', 'Saudi Arabia', 'player'),
	('Sylvanus Nimely', 'Liberia', 'player'),
	('Muslim Al Furayj', 'Saudi Arabia', 'player'),
	('Ali Lajami', 'Saudi Arabia', 'player'),
	('Viljar Myhra', 'Norway', 'player'),
	('Naif Hazazi', 'Saudi Arabia', 'player'),
	('Jonathan Fleita', 'Argentina', 'player'),
	('Răzvan Patriche', 'Romania', 'player'),
	('Filip Jörgensen', 'Sweden', 'player'),
	('Bryan Oña', 'Ecuador', 'player'),
	('Dimitrios Emmanouilidis', 'Greece', 'player'),
	('Kristófer Kristinsson', 'Iceland', 'player'),
	('Kwame Kizito', 'Ghana', 'player'),
	('Pier Graziano Gori', 'Italy', 'player'),
	('David Djigla', 'Benin', 'player'),
	('Jorge Henríquez', 'Chile', 'player'),
	('Demeaco Duhaney', 'England', 'player'),
	('Jordan Green', 'England', 'player'),
	('Charles Boli', 'France', 'player'),
	('Édgar Jiménez', 'Venezuela', 'player'),
	('Reece Hutchinson', 'England', 'player'),
	('Liam Fontaine', 'England', 'player'),
	('Indiana Vassilev', 'United States', 'player'),
	('Liu Yiming', 'China PR', 'player'),
	('Louis Bury', 'France', 'player'),
	('Erdoğan Kaya', 'Turkey', 'player'),
	('Zak Jules', 'Scotland', 'player'),
	('Yacouba Diori', 'Niger', 'player'),
	('Sam Sanna', 'France', 'player'),
	('Byron Moore', 'England', 'player'),
	('Manuel Fuentes', 'Venezuela', 'player'),
	('Joshua Gatt', 'United States', 'player'),
	('Cornel Dinu', 'Romania', 'player'),
	('Sondre Solholm Johansen', 'Norway', 'player'),
	('Luka Lochoshvili', 'Georgia', 'player'),
	('Daiki Matsuoka', 'Japan', 'player'),
	('Ben Johnson', 'England', 'player'),
	('Kim Hyun', 'Korea Republic', 'player'),
	('Benedikt Kirsch', 'Germany', 'player'),
	('Sebastian Mailat', 'Romania', 'player'),
	('Edvard Sandvik Tagseth', 'Norway', 'player'),
	('Malcom Braida', 'Argentina', 'player'),
	('Sebastian Osigwe', 'Nigeria', 'player'),
	('Rúben Gonçalves', 'Portugal', 'player'),
	('Grigore Turda', 'Romania', 'player'),
	('Aliou Traoré', 'France', 'player'),
	('Ruben Droehnle', 'France', 'player'),
	('Nathangelo Markelo', 'Netherlands', 'player'),
	('Rodrigo Alborno', 'Paraguay', 'player'),
	('Mohammed Al Saiari', 'Saudi Arabia', 'player'),
	('Marco Weymans', 'Belgium', 'player'),
	('Maurice Hehne', 'Germany', 'player'),
	('Juan Fernández', 'Spain', 'player'),
	('Gerard Bi Goua Gohou', 'Ivory Coast', 'player'),
	('Kosei Tani', 'Japan', 'player'),
	('Dalibor Velimirovic', 'Austria', 'player'),
	('Larrubia', 'Spain', 'player'),
	('Timothy Tillman', 'Germany', 'player'),
	('Martín Aruga', 'Argentina', 'player'),
	('Karl Söderström', 'Sweden', 'player'),
	('Nelson Hernández', 'Venezuela', 'player'),
	('Bermejo', 'Spain', 'player'),
	('Diego Barbosa', 'Mexico', 'player'),
	('John White', 'England', 'player'),
	('Xavier Pinoteau', 'France', 'player'),
	('Patrick Vroegh', 'Netherlands', 'player'),
	('Rodrigo Ruiz Díaz', 'Paraguay', 'player'),
	('Archie Collins', 'England', 'player'),
	('Amin Sarr', 'Sweden', 'player'),
	('Robbie Benson', 'Republic of Ireland', 'player'),
	('Joshua Daniels', 'Republic of Ireland', 'player'),
	('Bandiougou Fadiga', 'France', 'player'),
	('Paul Digby', 'England', 'player'),
	('Andreas Lie', 'Norway', 'player'),
	('Davis Keillor-Dunn', 'England', 'player'),
	('Jeffrey de Lange', 'Netherlands', 'player'),
	('Joe Murphy', 'Republic of Ireland', 'player'),
	('Gustavo Rojas', 'Venezuela', 'player'),
	('Viljormur Davidsen', 'Faroe Islands', 'player'),
	('Alexander Jallow', 'Sweden', 'player'),
	('Zech Medley', 'England', 'player'),
	('Enric Vallès', 'Spain', 'player'),
	('Michael Lema', 'Austria', 'player'),
	('Joe McNerney', 'England', 'player'),
	('Yuta Kamiya', 'Japan', 'player'),
	('Luka Sučić', 'Croatia', 'player'),
	('Jordan Flores', 'England', 'player'),
	('Álex Zalaya', 'Spain', 'player'),
	('Bilal Bayazit', 'Netherlands', 'player'),
	('Alex Roldan', 'United States', 'player'),
	('Blair Turgott', 'England', 'player'),
	('Tobias Schilk', 'Germany', 'player'),
	('Manu Justo', 'Spain', 'player'),
	('Iba May', 'Germany', 'player'),
	('Andrei Pițian', 'Romania', 'player'),
	('Tsuyoshi Kodama', 'Japan', 'player'),
	('Tom Conlon', 'England', 'player'),
	('Pedro Ramírez', 'Venezuela', 'player'),
	('Luca Andrada', 'Argentina', 'player'),
	('Nico Gorzel', 'Germany', 'player'),
	('Abdul Wahab Ibrahim', 'Ghana', 'player'),
	('Kim Dong Woo', 'Korea Republic', 'player'),
	('Ashley Baker', 'Wales', 'player'),
	('Amadou Sagna', 'Senegal', 'player'),
	('Kleandro Lleshi', 'Albania', 'player'),
	('Nosa Iyobosa Edokpolor', 'Austria', 'player'),
	('Thijs Oosting', 'Netherlands', 'player'),
	('Mark Ellis', 'England', 'player'),
	('Ali Al Mazaidi', 'Saudi Arabia', 'player'),
	('Nicolae Milinceanu', 'Moldova', 'player'),
	('Roberto Céspedes', 'Peru', 'player'),
	('Leon Jensen', 'Germany', 'player'),
	('Nawaf Al Subhi', 'Saudi Arabia', 'player'),
	('Julian Krahl', 'Germany', 'player'),
	('Piotr Malinowski', 'Poland', 'player'),
	('Ricardo Farro', 'Peru', 'player'),
	('Han Yong Su', 'Korea Republic', 'player'),
	('Stefan Cleveland', 'United States', 'player'),
	('Hussain Al Qahtani', 'Saudi Arabia', 'player'),
	('Mitsunari Musaka', 'Japan', 'player'),
	('Stefan Payne', 'England', 'player'),
	('Sean Murray', 'Republic of Ireland', 'player'),
	('Zak Mills', 'England', 'player'),
	('Darly N''Landu', 'France', 'player'),
	('Cameron Humphreys-Grant', 'England', 'player'),
	('Jeizon Ramírez', 'Venezuela', 'player'),
	('Ryotaro Ito', 'Japan', 'player'),
	('Luciano Pons', 'Argentina', 'player'),
	('Jonatan Kotzke', 'Germany', 'player'),
	('Andrzej Niewulis', 'Poland', 'player'),
	('Kyle John', 'England', 'player'),
	('André Becker', 'Germany', 'player'),
	('Nicolás Bazzana', 'Argentina', 'player'),
	('Tomislav Gomelt', 'Croatia', 'player'),
	('Willan Álvarez', 'Bolivia', 'player'),
	('Pedro Augusto', 'Brazil', 'player'),
	('Gerrit Wegkamp', 'Germany', 'player'),
	('Kevin Rendón', 'Colombia', 'player'),
	('Miguel Van Damme', 'Belgium', 'player'),
	('Josemi Castañeda', 'Spain', 'player'),
	('Dostonbek Tursunov', 'Uzbekistan', 'player'),
	('Ole Romeny', 'Netherlands', 'player'),
	('Darnell Johnson', 'England', 'player'),
	('Lee Dong Su', 'Korea Republic', 'player'),
	('Paul Gartler', 'Austria', 'player'),
	('Quentin Bena', 'France', 'player'),
	('Pablo Bonilla', 'Venezuela', 'player'),
	('Amin Affane', 'Sweden', 'player'),
	('Hiram Boateng', 'England', 'player'),
	('Fran Callejón', 'Spain', 'player'),
	('Dawid Kudła', 'Poland', 'player'),
	('Tim Erlandsson', 'Sweden', 'player'),
	('Boris Rotenberg', 'Finland', 'player'),
	('Ander Iru', 'Spain', 'player'),
	('Manuel Maranda', 'Austria', 'player'),
	('Emil Pálsson', 'Iceland', 'player'),
	('Abdulrahman Al Obud', 'Saudi Arabia', 'player'),
	('Arthur Gnahoua', 'France', 'player'),
	('Liam Gordon', 'Scotland', 'player'),
	('David Philipp', 'Germany', 'player'),
	('Roberts Uldriķis', 'Latvia', 'player'),
	('Cristhian Riveros', 'Paraguay', 'player'),
	('Famana Quizera', 'Portugal', 'player'),
	('Chuma Anene', 'Norway', 'player'),
	('Honoya Shoji', 'Japan', 'player'),
	('Colm Horgan', 'Republic of Ireland', 'player'),
	('He Chao', 'China PR', 'player'),
	('Guillermo Viscarra', 'Bolivia', 'player'),
	('Charles Vélez', 'Ecuador', 'player'),
	('Moussa Sissako', 'Mali', 'player'),
	('Victor Méndez', 'Spain', 'player'),
	('Kerim Çalhanoğlu', 'Germany', 'player'),
	('Steffen Lang', 'Germany', 'player'),
	('Ramiro Quintana', 'Uruguay', 'player'),
	('Will Aimson', 'Wales', 'player'),
	('Kenta Tanno', 'Japan', 'player'),
	('Markus Palionis', 'Lithuania', 'player'),
	('Brian Abel Luciatti', 'Argentina', 'player'),
	('Paulo Lima', 'Uruguay', 'player'),
	('Ayrton Mboko', 'Belgium', 'player'),
	('Lucas Rodrigues', 'Brazil', 'player'),
	('Maciej Domański', 'Poland', 'player'),
	('Panutche Camará', 'Guinea Bissau', 'player'),
	('Ali Al Nemer', 'Saudi Arabia', 'player'),
	('Agon Mehmeti', 'Albania', 'player'),
	('Víctor Figueroa', 'Argentina', 'player'),
	('Janio Pósito', 'Peru', 'player'),
	('Luke Mulholland', 'England', 'player'),
	('Juan Pretel', 'Peru', 'player'),
	('Henrik Robstad', 'Norway', 'player'),
	('Shunki Higashi', 'Japan', 'player'),
	('Tomáš Huk', 'Slovakia', 'player'),
	('Iain Vigurs', 'Scotland', 'player'),
	('Scott Robinson', 'Scotland', 'player'),
	('Nigel Boogaard', 'Australia', 'player'),
	('Adrian Winter', 'Switzerland', 'player'),
	('Vasile Constantin', 'Romania', 'player'),
	('José Luis Rodríguez', 'Panama', 'player'),
	('Denis Granečný', 'Czech Republic', 'player'),
	('Marco Festa', 'Italy', 'player'),
	('Cameron Dummigan', 'Northern Ireland', 'player'),
	('Josh Barrett', 'Republic of Ireland', 'player'),
	('Kasper Lunding', 'Denmark', 'player'),
	('Daniele Ragatzu', 'Italy', 'player'),
	('Niklas Klinger', 'Germany', 'player'),
	('Ahmed Ildız', 'Turkey', 'player'),
	('Tom Lebeau', 'France', 'player'),
	('Abdoulaye Dabo', 'France', 'player'),
	('Kyle Magennis', 'Scotland', 'player'),
	('Guito', 'Spain', 'player'),
	('Gearóid Morrissey', 'Republic of Ireland', 'player'),
	('Lee Jong Sung', 'Korea Republic', 'player'),
	('Lukas Rath', 'Austria', 'player'),
	('David Buchholz', 'Germany', 'player'),
	('Denzel Jubitana', 'Belgium', 'player'),
	('Abdulmajeed Al Suwat', 'Saudi Arabia', 'player'),
	('Zhang Chong', 'China PR', 'player'),
	('Christoph Haas', 'Austria', 'player'),
	('Rodi Ferreira', 'Paraguay', 'player'),
	('Hans Nicolussi Caviglia', 'Italy', 'player'),
	('Abdoulaye Sidibé', 'France', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Marco Rente', 'Germany', 'marco rente'),
	('Marco Rente', 'Germany', 'rente'),
	('Tristan Nydam', 'England', 'tristan nydam'),
	('Tristan Nydam', 'England', 'nydam'),
	('Paul Kalambayi', 'England', 'paul kalambayi'),
	('Paul Kalambayi', 'England', 'kalambayi'),
	('Oli Shaw', 'Scotland', 'oli shaw'),
	('Oli Shaw', 'Scotland', 'shaw'),
	('Lucian Dumitriu', 'Romania', 'lucian dumitriu'),
	('Lucian Dumitriu', 'Romania', 'dumitriu'),
	('Erik Israelsson', 'Sweden', 'erik israelsson'),
	('Erik Israelsson', 'Sweden', 'israelsson'),
	('Dominik Starkl', 'Austria', 'dominik starkl'),
	('Dominik Starkl', 'Austria', 'starkl'),
	('Echu', 'Spain', 'echu'),
	('Vangelis Theocharis', 'Greece', 'vangelis theocharis'),
	('Vangelis Theocharis', 'Greece', 'theocharis'),
	('Joan Monterde', 'Spain', 'monterde'),
	('Joan Monterde', 'Spain', 'joan monterde'),
	('Efrain Alvarez', 'Mexico', 'alvarez'),
	('Efrain Alvarez', 'Mexico', 'efrain alvarez'),
	('Michał Koj', 'Poland', 'micha koj'),
	('Michał Koj', 'Poland', 'koj'),
	('Kim Tae Youn', 'Korea Republic', 'kim tae youn'),
	('Kim Tae Youn', 'Korea Republic', 'youn'),
	('Nicolas Bürgy', 'Switzerland', 'nicolas burgy'),
	('Nicolas Bürgy', 'Switzerland', 'burgy'),
	('Kim Seon Woo', 'Korea Republic', 'woo'),
	('Kim Seon Woo', 'Korea Republic', 'kim seon woo'),
	('Ola Solbakken', 'Norway', 'solbakken'),
	('Ola Solbakken', 'Norway', 'ola solbakken'),
	('Diego Becker', 'Argentina', 'diego becker'),
	('Diego Becker', 'Argentina', 'becker'),
	('Johannes Dörfler', 'Germany', 'johannes dorfler'),
	('Johannes Dörfler', 'Germany', 'dorfler'),
	('Naoya Fukumori', 'Japan', 'naoya fukumori'),
	('Naoya Fukumori', 'Japan', 'fukumori'),
	('Sébastien Flochon', 'France', 'sebastien flochon'),
	('Sébastien Flochon', 'France', 'flochon'),
	('Joe Widdowson', 'England', 'joe widdowson'),
	('Joe Widdowson', 'England', 'widdowson'),
	('Lawrence Vigouroux', 'Chile', 'lawrence vigouroux'),
	('Lawrence Vigouroux', 'Chile', 'vigouroux'),
	('Guillaume Gigliotti', 'France', 'gigliotti'),
	('Guillaume Gigliotti', 'France', 'guillaume gigliotti'),
	('Chen Zhizhao', 'China PR', 'zhizhao'),
	('Chen Zhizhao', 'China PR', 'chen zhizhao'),
	('Yuta Higuchi', 'Japan', 'higuchi'),
	('Yuta Higuchi', 'Japan', 'yuta higuchi'),
	('Cameron Puertas', 'Switzerland', 'cameron puertas'),
	('Cameron Puertas', 'Switzerland', 'puertas'),
	('Bryan Alceus', 'Haiti', 'alceus'),
	('Bryan Alceus', 'Haiti', 'bryan alceus'),
	('Kieran O''Hara', 'Republic of Ireland', 'kieran ohara'),
	('Kieran O''Hara', 'Republic of Ireland', 'ohara'),
	('Thomas Glover', 'Australia', 'glover'),
	('Thomas Glover', 'Australia', 'thomas glover'),
	('Yasyn Hamza', 'Saudi Arabia', 'yasyn hamza'),
	('Yasyn Hamza', 'Saudi Arabia', 'hamza'),
	('Sylvanus Nimely', 'Liberia', 'sylvanus nimely'),
	('Sylvanus Nimely', 'Liberia', 'nimely'),
	('Muslim Al Furayj', 'Saudi Arabia', 'muslim al furayj'),
	('Muslim Al Furayj', 'Saudi Arabia', 'furayj'),
	('Ali Lajami', 'Saudi Arabia', 'ali lajami'),
	('Ali Lajami', 'Saudi Arabia', 'lajami'),
	('Viljar Myhra', 'Norway', 'viljar myhra'),
	('Viljar Myhra', 'Norway', 'myhra'),
	('Naif Hazazi', 'Saudi Arabia', 'hazazi'),
	('Naif Hazazi', 'Saudi Arabia', 'naif hazazi'),
	('Jonathan Fleita', 'Argentina', 'jonathan fleita'),
	('Jonathan Fleita', 'Argentina', 'fleita'),
	('Răzvan Patriche', 'Romania', 'patriche'),
	('Răzvan Patriche', 'Romania', 'razvan patriche'),
	('Filip Jörgensen', 'Sweden', 'filip jorgensen'),
	('Filip Jörgensen', 'Sweden', 'jorgensen'),
	('Bryan Oña', 'Ecuador', 'ona'),
	('Bryan Oña', 'Ecuador', 'bryan ona'),
	('Dimitrios Emmanouilidis', 'Greece', 'emmanouilidis'),
	('Dimitrios Emmanouilidis', 'Greece', 'dimitrios emmanouilidis'),
	('Kristófer Kristinsson', 'Iceland', 'kristofer kristinsson'),
	('Kristófer Kristinsson', 'Iceland', 'kristinsson'),
	('Kwame Kizito', 'Ghana', 'kwame kizito'),
	('Kwame Kizito', 'Ghana', 'kizito'),
	('Pier Graziano Gori', 'Italy', 'gori'),
	('Pier Graziano Gori', 'Italy', 'pier graziano gori'),
	('David Djigla', 'Benin', 'djigla'),
	('David Djigla', 'Benin', 'david djigla'),
	('Jorge Henríquez', 'Chile', 'jorge henriquez'),
	('Jorge Henríquez', 'Chile', 'henriquez'),
	('Demeaco Duhaney', 'England', 'duhaney'),
	('Demeaco Duhaney', 'England', 'demeaco duhaney'),
	('Jordan Green', 'England', 'green'),
	('Jordan Green', 'England', 'jordan green'),
	('Charles Boli', 'France', 'boli'),
	('Charles Boli', 'France', 'charles boli'),
	('Édgar Jiménez', 'Venezuela', 'edgar jimenez'),
	('Édgar Jiménez', 'Venezuela', 'jimenez'),
	('Reece Hutchinson', 'England', 'reece hutchinson'),
	('Reece Hutchinson', 'England', 'hutchinson'),
	('Liam Fontaine', 'England', 'liam fontaine'),
	('Liam Fontaine', 'England', 'fontaine'),
	('Indiana Vassilev', 'United States', 'vassilev'),
	('Indiana Vassilev', 'United States', 'indiana vassilev'),
	('Liu Yiming', 'China PR', 'liu yiming'),
	('Liu Yiming', 'China PR', 'yiming'),
	('Louis Bury', 'France', 'louis bury'),
	('Louis Bury', 'France', 'bury'),
	('Erdoğan Kaya', 'Turkey', 'erdogan kaya'),
	('Erdoğan Kaya', 'Turkey', 'kaya'),
	('Zak Jules', 'Scotland', 'jules'),
	('Zak Jules', 'Scotland', 'zak jules'),
	('Yacouba Diori', 'Niger', 'diori'),
	('Yacouba Diori', 'Niger', 'yacouba diori'),
	('Sam Sanna', 'France', 'sanna'),
	('Sam Sanna', 'France', 'sam sanna'),
	('Byron Moore', 'England', 'byron moore'),
	('Byron Moore', 'England', 'moore'),
	('Manuel Fuentes', 'Venezuela', 'fuentes'),
	('Manuel Fuentes', 'Venezuela', 'manuel fuentes'),
	('Joshua Gatt', 'United States', 'joshua gatt'),
	('Joshua Gatt', 'United States', 'gatt'),
	('Cornel Dinu', 'Romania', 'cornel dinu'),
	('Cornel Dinu', 'Romania', 'dinu'),
	('Sondre Solholm Johansen', 'Norway', 'johansen'),
	('Sondre Solholm Johansen', 'Norway', 'sondre solholm johansen'),
	('Luka Lochoshvili', 'Georgia', 'lochoshvili'),
	('Luka Lochoshvili', 'Georgia', 'luka lochoshvili'),
	('Daiki Matsuoka', 'Japan', 'daiki matsuoka'),
	('Daiki Matsuoka', 'Japan', 'matsuoka'),
	('Ben Johnson', 'England', 'ben johnson'),
	('Ben Johnson', 'England', 'johnson'),
	('Kim Hyun', 'Korea Republic', 'kim hyun'),
	('Kim Hyun', 'Korea Republic', 'hyun'),
	('Benedikt Kirsch', 'Germany', 'kirsch'),
	('Benedikt Kirsch', 'Germany', 'benedikt kirsch'),
	('Sebastian Mailat', 'Romania', 'sebastian mailat'),
	('Sebastian Mailat', 'Romania', 'mailat'),
	('Edvard Sandvik Tagseth', 'Norway', 'tagseth'),
	('Edvard Sandvik Tagseth', 'Norway', 'edvard sandvik tagseth'),
	('Malcom Braida', 'Argentina', 'malcom braida'),
	('Malcom Braida', 'Argentina', 'braida'),
	('Sebastian Osigwe', 'Nigeria', 'sebastian osigwe'),
	('Sebastian Osigwe', 'Nigeria', 'osigwe'),
	('Rúben Gonçalves', 'Portugal', 'goncalves'),
	('Rúben Gonçalves', 'Portugal', 'ruben goncalves'),
	('Grigore Turda', 'Romania', 'grigore turda'),
	('Grigore Turda', 'Romania', 'turda'),
	('Aliou Traoré', 'France', 'traore'),
	('Aliou Traoré', 'France', 'aliou traore'),
	('Ruben Droehnle', 'France', 'ruben droehnle'),
	('Ruben Droehnle', 'France', 'droehnle'),
	('Nathangelo Markelo', 'Netherlands', 'nathangelo markelo'),
	('Nathangelo Markelo', 'Netherlands', 'markelo'),
	('Rodrigo Alborno', 'Paraguay', 'rodrigo alborno'),
	('Rodrigo Alborno', 'Paraguay', 'alborno'),
	('Mohammed Al Saiari', 'Saudi Arabia', 'saiari'),
	('Mohammed Al Saiari', 'Saudi Arabia', 'mohammed al saiari'),
	('Marco Weymans', 'Belgium', 'marco weymans'),
	('Marco Weymans', 'Belgium', 'weymans'),
	('Maurice Hehne', 'Germany', 'maurice hehne'),
	('Maurice Hehne', 'Germany', 'hehne'),
	('Juan Fernández', 'Spain', 'fernandez'),
	('Juan Fernández', 'Spain', 'juan fernandez'),
	('Gerard Bi Goua Gohou', 'Ivory Coast', 'gerard bi goua gohou'),
	('Gerard Bi Goua Gohou', 'Ivory Coast', 'gohou'),
	('Kosei Tani', 'Japan', 'kosei tani'),
	('Kosei Tani', 'Japan', 'tani'),
	('Dalibor Velimirovic', 'Austria', 'velimirovic'),
	('Dalibor Velimirovic', 'Austria', 'dalibor velimirovic'),
	('Larrubia', 'Spain', 'larrubia'),
	('Timothy Tillman', 'Germany', 'timothy tillman'),
	('Timothy Tillman', 'Germany', 'tillman'),
	('Martín Aruga', 'Argentina', 'aruga'),
	('Martín Aruga', 'Argentina', 'martin aruga'),
	('Karl Söderström', 'Sweden', 'soderstrom'),
	('Karl Söderström', 'Sweden', 'karl soderstrom'),
	('Nelson Hernández', 'Venezuela', 'nelson hernandez'),
	('Nelson Hernández', 'Venezuela', 'hernandez'),
	('Bermejo', 'Spain', 'bermejo'),
	('Diego Barbosa', 'Mexico', 'barbosa'),
	('Diego Barbosa', 'Mexico', 'diego barbosa'),
	('John White', 'England', 'john white'),
	('John White', 'England', 'white'),
	('Xavier Pinoteau', 'France', 'pinoteau'),
	('Xavier Pinoteau', 'France', 'xavier pinoteau'),
	('Patrick Vroegh', 'Netherlands', 'vroegh'),
	('Patrick Vroegh', 'Netherlands', 'patrick vroegh'),
	('Rodrigo Ruiz Díaz', 'Paraguay', 'diaz'),
	('Rodrigo Ruiz Díaz', 'Paraguay', 'rodrigo ruiz diaz'),
	('Archie Collins', 'England', 'archie collins'),
	('Archie Collins', 'England', 'collins'),
	('Amin Sarr', 'Sweden', 'amin sarr'),
	('Amin Sarr', 'Sweden', 'sarr'),
	('Robbie Benson', 'Republic of Ireland', 'benson'),
	('Robbie Benson', 'Republic of Ireland', 'robbie benson'),
	('Joshua Daniels', 'Republic of Ireland', 'joshua daniels'),
	('Joshua Daniels', 'Republic of Ireland', 'daniels'),
	('Bandiougou Fadiga', 'France', 'bandiougou fadiga'),
	('Bandiougou Fadiga', 'France', 'fadiga'),
	('Paul Digby', 'England', 'paul digby'),
	('Paul Digby', 'England', 'digby'),
	('Andreas Lie', 'Norway', 'andreas lie'),
	('Andreas Lie', 'Norway', 'lie'),
	('Davis Keillor-Dunn', 'England', 'keillordunn'),
	('Davis Keillor-Dunn', 'England', 'davis keillordunn'),
	('Jeffrey de Lange', 'Netherlands', 'lange'),
	('Jeffrey de Lange', 'Netherlands', 'jeffrey de lange'),
	('Joe Murphy', 'Republic of Ireland', 'joe murphy'),
	('Joe Murphy', 'Republic of Ireland', 'murphy'),
	('Gustavo Rojas', 'Venezuela', 'gustavo rojas'),
	('Gustavo Rojas', 'Venezuela', 'rojas'),
	('Viljormur Davidsen', 'Faroe Islands', 'davidsen'),
	('Viljormur Davidsen', 'Faroe Islands', 'viljormur davidsen'),
	('Alexander Jallow', 'Sweden', 'alexander jallow'),
	('Alexander Jallow', 'Sweden', 'jallow'),
	('Zech Medley', 'England', 'medley'),
	('Zech Medley', 'England', 'zech medley'),
	('Enric Vallès', 'Spain', 'valles'),
	('Enric Vallès', 'Spain', 'enric valles'),
	('Michael Lema', 'Austria', 'lema'),
	('Michael Lema', 'Austria', 'michael lema'),
	('Joe McNerney', 'England', 'mcnerney'),
	('Joe McNerney', 'England', 'joe mcnerney'),
	('Yuta Kamiya', 'Japan', 'yuta kamiya'),
	('Yuta Kamiya', 'Japan', 'kamiya'),
	('Luka Sučić', 'Croatia', 'sucic'),
	('Luka Sučić', 'Croatia', 'luka sucic'),
	('Jordan Flores', 'England', 'flores'),
	('Jordan Flores', 'England', 'jordan flores'),
	('Álex Zalaya', 'Spain', 'alex zalaya'),
	('Álex Zalaya', 'Spain', 'zalaya'),
	('Bilal Bayazit', 'Netherlands', 'bilal bayazit'),
	('Bilal Bayazit', 'Netherlands', 'bayazit'),
	('Alex Roldan', 'United States', 'roldan'),
	('Alex Roldan', 'United States', 'alex roldan'),
	('Blair Turgott', 'England', 'turgott'),
	('Blair Turgott', 'England', 'blair turgott'),
	('Tobias Schilk', 'Germany', 'schilk'),
	('Tobias Schilk', 'Germany', 'tobias schilk'),
	('Manu Justo', 'Spain', 'manu justo'),
	('Manu Justo', 'Spain', 'justo'),
	('Iba May', 'Germany', 'iba may'),
	('Iba May', 'Germany', 'may'),
	('Andrei Pițian', 'Romania', 'andrei pitian'),
	('Andrei Pițian', 'Romania', 'pitian'),
	('Tsuyoshi Kodama', 'Japan', 'tsuyoshi kodama'),
	('Tsuyoshi Kodama', 'Japan', 'kodama'),
	('Tom Conlon', 'England', 'tom conlon'),
	('Tom Conlon', 'England', 'conlon'),
	('Pedro Ramírez', 'Venezuela', 'pedro ramirez'),
	('Pedro Ramírez', 'Venezuela', 'ramirez'),
	('Luca Andrada', 'Argentina', 'andrada'),
	('Luca Andrada', 'Argentina', 'luca andrada'),
	('Nico Gorzel', 'Germany', 'gorzel'),
	('Nico Gorzel', 'Germany', 'nico gorzel'),
	('Abdul Wahab Ibrahim', 'Ghana', 'ibrahim'),
	('Abdul Wahab Ibrahim', 'Ghana', 'abdul wahab ibrahim'),
	('Kim Dong Woo', 'Korea Republic', 'woo'),
	('Kim Dong Woo', 'Korea Republic', 'kim dong woo'),
	('Ashley Baker', 'Wales', 'baker'),
	('Ashley Baker', 'Wales', 'ashley baker'),
	('Amadou Sagna', 'Senegal', 'sagna'),
	('Amadou Sagna', 'Senegal', 'amadou sagna'),
	('Kleandro Lleshi', 'Albania', 'kleandro lleshi'),
	('Kleandro Lleshi', 'Albania', 'lleshi'),
	('Nosa Iyobosa Edokpolor', 'Austria', 'nosa iyobosa edokpolor'),
	('Nosa Iyobosa Edokpolor', 'Austria', 'edokpolor'),
	('Thijs Oosting', 'Netherlands', 'oosting'),
	('Thijs Oosting', 'Netherlands', 'thijs oosting'),
	('Mark Ellis', 'England', 'mark ellis'),
	('Mark Ellis', 'England', 'ellis'),
	('Ali Al Mazaidi', 'Saudi Arabia', 'ali al mazaidi'),
	('Ali Al Mazaidi', 'Saudi Arabia', 'mazaidi'),
	('Nicolae Milinceanu', 'Moldova', 'nicolae milinceanu'),
	('Nicolae Milinceanu', 'Moldova', 'milinceanu'),
	('Roberto Céspedes', 'Peru', 'cespedes'),
	('Roberto Céspedes', 'Peru', 'roberto cespedes'),
	('Leon Jensen', 'Germany', 'leon jensen'),
	('Leon Jensen', 'Germany', 'jensen'),
	('Nawaf Al Subhi', 'Saudi Arabia', 'nawaf al subhi'),
	('Nawaf Al Subhi', 'Saudi Arabia', 'subhi'),
	('Julian Krahl', 'Germany', 'julian krahl'),
	('Julian Krahl', 'Germany', 'krahl'),
	('Piotr Malinowski', 'Poland', 'piotr malinowski'),
	('Piotr Malinowski', 'Poland', 'malinowski'),
	('Ricardo Farro', 'Peru', 'farro'),
	('Ricardo Farro', 'Peru', 'ricardo farro'),
	('Han Yong Su', 'Korea Republic', 'han yong su'),
	('Han Yong Su', 'Korea Republic', 'su'),
	('Stefan Cleveland', 'United States', 'stefan cleveland'),
	('Stefan Cleveland', 'United States', 'cleveland'),
	('Hussain Al Qahtani', 'Saudi Arabia', 'qahtani'),
	('Hussain Al Qahtani', 'Saudi Arabia', 'hussain al qahtani'),
	('Mitsunari Musaka', 'Japan', 'musaka'),
	('Mitsunari Musaka', 'Japan', 'mitsunari musaka'),
	('Stefan Payne', 'England', 'stefan payne'),
	('Stefan Payne', 'England', 'payne'),
	('Sean Murray', 'Republic of Ireland', 'sean murray'),
	('Sean Murray', 'Republic of Ireland', 'murray'),
	('Zak Mills', 'England', 'mills'),
	('Zak Mills', 'England', 'zak mills'),
	('Darly N''Landu', 'France', 'darly nlandu'),
	('Darly N''Landu', 'France', 'nlandu'),
	('Cameron Humphreys-Grant', 'England', 'humphreysgrant'),
	('Cameron Humphreys-Grant', 'England', 'cameron humphreysgrant'),
	('Jeizon Ramírez', 'Venezuela', 'jeizon ramirez'),
	('Jeizon Ramírez', 'Venezuela', 'ramirez'),
	('Ryotaro Ito', 'Japan', 'ryotaro ito'),
	('Ryotaro Ito', 'Japan', 'ito'),
	('Luciano Pons', 'Argentina', 'pons'),
	('Luciano Pons', 'Argentina', 'luciano pons'),
	('Jonatan Kotzke', 'Germany', 'kotzke'),
	('Jonatan Kotzke', 'Germany', 'jonatan kotzke'),
	('Andrzej Niewulis', 'Poland', 'andrzej niewulis'),
	('Andrzej Niewulis', 'Poland', 'niewulis'),
	('Kyle John', 'England', 'john'),
	('Kyle John', 'England', 'kyle john'),
	('André Becker', 'Germany', 'andre becker'),
	('André Becker', 'Germany', 'becker'),
	('Nicolás Bazzana', 'Argentina', 'nicolas bazzana'),
	('Nicolás Bazzana', 'Argentina', 'bazzana'),
	('Tomislav Gomelt', 'Croatia', 'tomislav gomelt'),
	('Tomislav Gomelt', 'Croatia', 'gomelt'),
	('Willan Álvarez', 'Bolivia', 'alvarez'),
	('Willan Álvarez', 'Bolivia', 'willan alvarez'),
	('Pedro Augusto', 'Brazil', 'pedro augusto'),
	('Pedro Augusto', 'Brazil', 'augusto'),
	('Gerrit Wegkamp', 'Germany', 'wegkamp'),
	('Gerrit Wegkamp', 'Germany', 'gerrit wegkamp'),
	('Kevin Rendón', 'Colombia', 'kevin rendon'),
	('Kevin Rendón', 'Colombia', 'rendon'),
	('Miguel Van Damme', 'Belgium', 'damme'),
	('Miguel Van Damme', 'Belgium', 'miguel van damme'),
	('Josemi Castañeda', 'Spain', 'josemi castaneda'),
	('Josemi Castañeda', 'Spain', 'castaneda'),
	('Dostonbek Tursunov', 'Uzbekistan', 'tursunov'),
	('Dostonbek Tursunov', 'Uzbekistan', 'dostonbek tursunov'),
	('Ole Romeny', 'Netherlands', 'ole romeny'),
	('Ole Romeny', 'Netherlands', 'romeny'),
	('Darnell Johnson', 'England', 'darnell johnson'),
	('Darnell Johnson', 'England', 'johnson'),
	('Lee Dong Su', 'Korea Republic', 'su'),
	('Lee Dong Su', 'Korea Republic', 'lee dong su'),
	('Paul Gartler', 'Austria', 'gartler'),
	('Paul Gartler', 'Austria', 'paul gartler'),
	('Quentin Bena', 'France', 'bena'),
	('Quentin Bena', 'France', 'quentin bena'),
	('Pablo Bonilla', 'Venezuela', 'bonilla'),
	('Pablo Bonilla', 'Venezuela', 'pablo bonilla'),
	('Amin Affane', 'Sweden', 'affane'),
	('Amin Affane', 'Sweden', 'amin affane'),
	('Hiram Boateng', 'England', 'boateng'),
	('Hiram Boateng', 'England', 'hiram boateng'),
	('Fran Callejón', 'Spain', 'callejon'),
	('Fran Callejón', 'Spain', 'fran callejon'),
	('Dawid Kudła', 'Poland', 'dawid kuda'),
	('Dawid Kudła', 'Poland', 'kuda'),
	('Tim Erlandsson', 'Sweden', 'erlandsson'),
	('Tim Erlandsson', 'Sweden', 'tim erlandsson'),
	('Boris Rotenberg', 'Finland', 'rotenberg'),
	('Boris Rotenberg', 'Finland', 'boris rotenberg'),
	('Ander Iru', 'Spain', 'ander iru'),
	('Ander Iru', 'Spain', 'iru'),
	('Manuel Maranda', 'Austria', 'maranda'),
	('Manuel Maranda', 'Austria', 'manuel maranda'),
	('Emil Pálsson', 'Iceland', 'emil palsson'),
	('Emil Pálsson', 'Iceland', 'palsson'),
	('Abdulrahman Al Obud', 'Saudi Arabia', 'obud'),
	('Abdulrahman Al Obud', 'Saudi Arabia', 'abdulrahman al obud'),
	('Arthur Gnahoua', 'France', 'gnahoua'),
	('Arthur Gnahoua', 'France', 'arthur gnahoua'),
	('Liam Gordon', 'Scotland', 'gordon'),
	('Liam Gordon', 'Scotland', 'liam gordon'),
	('David Philipp', 'Germany', 'david philipp'),
	('David Philipp', 'Germany', 'philipp'),
	('Roberts Uldriķis', 'Latvia', 'uldrikis'),
	('Roberts Uldriķis', 'Latvia', 'roberts uldrikis'),
	('Cristhian Riveros', 'Paraguay', 'riveros'),
	('Cristhian Riveros', 'Paraguay', 'cristhian riveros'),
	('Famana Quizera', 'Portugal', 'famana quizera'),
	('Famana Quizera', 'Portugal', 'quizera'),
	('Chuma Anene', 'Norway', 'anene'),
	('Chuma Anene', 'Norway', 'chuma anene'),
	('Honoya Shoji', 'Japan', 'shoji'),
	('Honoya Shoji', 'Japan', 'honoya shoji'),
	('Colm Horgan', 'Republic of Ireland', 'colm horgan'),
	('Colm Horgan', 'Republic of Ireland', 'horgan'),
	('He Chao', 'China PR', 'he chao'),
	('He Chao', 'China PR', 'chao'),
	('Guillermo Viscarra', 'Bolivia', 'viscarra'),
	('Guillermo Viscarra', 'Bolivia', 'guillermo viscarra'),
	('Charles Vélez', 'Ecuador', 'velez'),
	('Charles Vélez', 'Ecuador', 'charles velez'),
	('Moussa Sissako', 'Mali', 'sissako'),
	('Moussa Sissako', 'Mali', 'moussa sissako'),
	('Victor Méndez', 'Spain', 'victor mendez'),
	('Victor Méndez', 'Spain', 'mendez'),
	('Kerim Çalhanoğlu', 'Germany', 'calhanoglu'),
	('Kerim Çalhanoğlu', 'Germany', 'kerim calhanoglu'),
	('Steffen Lang', 'Germany', 'lang'),
	('Steffen Lang', 'Germany', 'steffen lang'),
	('Ramiro Quintana', 'Uruguay', 'ramiro quintana'),
	('Ramiro Quintana', 'Uruguay', 'quintana'),
	('Will Aimson', 'Wales', 'aimson'),
	('Will Aimson', 'Wales', 'will aimson'),
	('Kenta Tanno', 'Japan', 'kenta tanno'),
	('Kenta Tanno', 'Japan', 'tanno'),
	('Markus Palionis', 'Lithuania', 'palionis'),
	('Markus Palionis', 'Lithuania', 'markus palionis'),
	('Brian Abel Luciatti', 'Argentina', 'brian abel luciatti'),
	('Brian Abel Luciatti', 'Argentina', 'luciatti'),
	('Paulo Lima', 'Uruguay', 'paulo lima'),
	('Paulo Lima', 'Uruguay', 'lima'),
	('Ayrton Mboko', 'Belgium', 'ayrton mboko'),
	('Ayrton Mboko', 'Belgium', 'mboko'),
	('Lucas Rodrigues', 'Brazil', 'lucas rodrigues'),
	('Lucas Rodrigues', 'Brazil', 'rodrigues'),
	('Maciej Domański', 'Poland', 'domanski'),
	('Maciej Domański', 'Poland', 'maciej domanski'),
	('Panutche Camará', 'Guinea Bissau', 'panutche camara'),
	('Panutche Camará', 'Guinea Bissau', 'camara'),
	('Ali Al Nemer', 'Saudi Arabia', 'nemer'),
	('Ali Al Nemer', 'Saudi Arabia', 'ali al nemer'),
	('Agon Mehmeti', 'Albania', 'mehmeti'),
	('Agon Mehmeti', 'Albania', 'agon mehmeti'),
	('Víctor Figueroa', 'Argentina', 'victor figueroa'),
	('Víctor Figueroa', 'Argentina', 'figueroa'),
	('Janio Pósito', 'Peru', 'janio posito'),
	('Janio Pósito', 'Peru', 'posito'),
	('Luke Mulholland', 'England', 'mulholland'),
	('Luke Mulholland', 'England', 'luke mulholland'),
	('Juan Pretel', 'Peru', 'juan pretel'),
	('Juan Pretel', 'Peru', 'pretel'),
	('Henrik Robstad', 'Norway', 'robstad'),
	('Henrik Robstad', 'Norway', 'henrik robstad'),
	('Shunki Higashi', 'Japan', 'higashi'),
	('Shunki Higashi', 'Japan', 'shunki higashi'),
	('Tomáš Huk', 'Slovakia', 'tomas huk'),
	('Tomáš Huk', 'Slovakia', 'huk'),
	('Iain Vigurs', 'Scotland', 'iain vigurs'),
	('Iain Vigurs', 'Scotland', 'vigurs'),
	('Scott Robinson', 'Scotland', 'robinson'),
	('Scott Robinson', 'Scotland', 'scott robinson'),
	('Nigel Boogaard', 'Australia', 'nigel boogaard'),
	('Nigel Boogaard', 'Australia', 'boogaard'),
	('Adrian Winter', 'Switzerland', 'winter'),
	('Adrian Winter', 'Switzerland', 'adrian winter'),
	('Vasile Constantin', 'Romania', 'vasile constantin'),
	('Vasile Constantin', 'Romania', 'constantin'),
	('José Luis Rodríguez', 'Panama', 'jose luis rodriguez'),
	('José Luis Rodríguez', 'Panama', 'rodriguez'),
	('Denis Granečný', 'Czech Republic', 'denis granecny'),
	('Denis Granečný', 'Czech Republic', 'granecny'),
	('Marco Festa', 'Italy', 'marco festa'),
	('Marco Festa', 'Italy', 'festa'),
	('Cameron Dummigan', 'Northern Ireland', 'cameron dummigan'),
	('Cameron Dummigan', 'Northern Ireland', 'dummigan'),
	('Josh Barrett', 'Republic of Ireland', 'barrett'),
	('Josh Barrett', 'Republic of Ireland', 'josh barrett'),
	('Kasper Lunding', 'Denmark', 'kasper lunding'),
	('Kasper Lunding', 'Denmark', 'lunding'),
	('Daniele Ragatzu', 'Italy', 'daniele ragatzu'),
	('Daniele Ragatzu', 'Italy', 'ragatzu'),
	('Niklas Klinger', 'Germany', 'klinger'),
	('Niklas Klinger', 'Germany', 'niklas klinger'),
	('Ahmed Ildız', 'Turkey', 'ahmed ildz'),
	('Ahmed Ildız', 'Turkey', 'ildz'),
	('Tom Lebeau', 'France', 'lebeau'),
	('Tom Lebeau', 'France', 'tom lebeau'),
	('Abdoulaye Dabo', 'France', 'dabo'),
	('Abdoulaye Dabo', 'France', 'abdoulaye dabo'),
	('Kyle Magennis', 'Scotland', 'magennis'),
	('Kyle Magennis', 'Scotland', 'kyle magennis'),
	('Guito', 'Spain', 'guito'),
	('Gearóid Morrissey', 'Republic of Ireland', 'morrissey'),
	('Gearóid Morrissey', 'Republic of Ireland', 'gearoid morrissey'),
	('Lee Jong Sung', 'Korea Republic', 'lee jong sung'),
	('Lee Jong Sung', 'Korea Republic', 'sung'),
	('Lukas Rath', 'Austria', 'lukas rath'),
	('Lukas Rath', 'Austria', 'rath'),
	('David Buchholz', 'Germany', 'david buchholz'),
	('David Buchholz', 'Germany', 'buchholz'),
	('Denzel Jubitana', 'Belgium', 'denzel jubitana'),
	('Denzel Jubitana', 'Belgium', 'jubitana'),
	('Abdulmajeed Al Suwat', 'Saudi Arabia', 'abdulmajeed al suwat'),
	('Abdulmajeed Al Suwat', 'Saudi Arabia', 'suwat'),
	('Zhang Chong', 'China PR', 'chong'),
	('Zhang Chong', 'China PR', 'zhang chong'),
	('Christoph Haas', 'Austria', 'haas'),
	('Christoph Haas', 'Austria', 'christoph haas'),
	('Rodi Ferreira', 'Paraguay', 'ferreira'),
	('Rodi Ferreira', 'Paraguay', 'rodi ferreira'),
	('Hans Nicolussi Caviglia', 'Italy', 'hans nicolussi caviglia'),
	('Hans Nicolussi Caviglia', 'Italy', 'caviglia'),
	('Abdoulaye Sidibé', 'France', 'sidibe'),
	('Abdoulaye Sidibé', 'France', 'abdoulaye sidibe')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';