INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Choi Jun Hyuk', 'Korea Republic', 'player'),
	('Jusuf Gazibegović', 'Bosnia Herzegovina', 'player'),
	('Josh Pask', 'England', 'player'),
	('Sixten Mohlin', 'Sweden', 'player'),
	('Ziggy Gordon', 'Scotland', 'player'),
	('Thomas O''Connor', 'Republic of Ireland', 'player'),
	('Sander Moen Foss', 'Norway', 'player'),
	('Ramiro Balbuena', 'Argentina', 'player'),
	('Stephen Hendrie', 'Scotland', 'player'),
	('Alioune Ba', 'France', 'player'),
	('Daniel Popa', 'Romania', 'player'),
	('Eric Kahl', 'Sweden', 'player'),
	('Brice Wembangomo', 'Norway', 'player'),
	('Khaled Al Khathlan', 'Saudi Arabia', 'player'),
	('Besard Sabovic', 'North Macedonia', 'player'),
	('Sam Schreck', 'Germany', 'player'),
	('Mike Hauptmeijer', 'Netherlands', 'player'),
	('Salih Kavrazlı', 'Turkey', 'player'),
	('Ousmane Ndong', 'Senegal', 'player'),
	('Stefan Perić', 'Austria', 'player'),
	('Manuel Haas', 'Austria', 'player'),
	('Bayron Garcés', 'Colombia', 'player'),
	('Vladyslav Vakula', 'Ukraine', 'player'),
	('Makoto Okazaki', 'Japan', 'player'),
	('Thierry Lutonda', 'Belgium', 'player'),
	('Zhu Chenjie', 'China PR', 'player'),
	('Nicolás Schiappacasse', 'Uruguay', 'player'),
	('Serge N''Guessan', 'Ivory Coast', 'player'),
	('Felix Drinkuth', 'Germany', 'player'),
	('Kays Ruiz-Atil', 'Morocco', 'player'),
	('Daniel Franco', 'Argentina', 'player'),
	('Stephen McGinn', 'Scotland', 'player'),
	('Maurice Malone', 'Germany', 'player'),
	('Robert Ivanov', 'Finland', 'player'),
	('Ryan Watson', 'England', 'player'),
	('Dominik Martinović', 'Croatia', 'player'),
	('Arton Zekaj', 'Kosovo', 'player'),
	('Jonathan Meier', 'Germany', 'player'),
	('Lee Han Do', 'Korea Republic', 'player'),
	('Erlend Segberg', 'Norway', 'player'),
	('Ryotaro Hironaga', 'Japan', 'player'),
	('Jørgen Olsen Øveraas', 'Norway', 'player'),
	('Gudmund Kongshavn', 'Norway', 'player'),
	('Jonas Lindberg', 'Sweden', 'player'),
	('Daniel Benítez', 'Venezuela', 'player'),
	('Pedro Ferreira', 'Portugal', 'player'),
	('Khaled Sharahili', 'Saudi Arabia', 'player'),
	('Park Dong Jin', 'Korea Republic', 'player'),
	('Aníbal Moreno', 'Argentina', 'player'),
	('Brendan Schoonbaert', 'Belgium', 'player'),
	('Jake Vokins', 'England', 'player'),
	('Jan Schöppner', 'Germany', 'player'),
	('Noah Diliberto', 'France', 'player'),
	('Jørgen Hatlehol', 'Norway', 'player'),
	('Bruno Jordão', 'Portugal', 'player'),
	('Moisés Velásquez', 'Peru', 'player'),
	('Abdullah Al Hamdan', 'Saudi Arabia', 'player'),
	('Nathaniel Knight-Percival', 'England', 'player'),
	('Jeon Min Gwang', 'Korea Republic', 'player'),
	('Niklas Geyrhofer', 'Austria', 'player'),
	('Henrik Heggheim', 'Norway', 'player'),
	('Morgan Ferrier', 'England', 'player'),
	('Moussa Diallo', 'France', 'player'),
	('Alessandro Berardi', 'Italy', 'player'),
	('Aimen Moueffek', 'France', 'player'),
	('Tomás Rojas', 'Paraguay', 'player'),
	('Osama Al Khalaf', 'Saudi Arabia', 'player'),
	('Danny Henriques', 'Portugal', 'player'),
	('Fernando Benítez', 'Paraguay', 'player'),
	('Bruny Nsimba', 'Belgium', 'player'),
	('Nkosingiphile Ngcobo', 'South Africa', 'player'),
	('Olivier Mbaizo', 'Cameroon', 'player'),
	('Kevin Moreno', 'Colombia', 'player'),
	('Jorge Cuellar', 'Bolivia', 'player'),
	('Mateusz Szczepaniak', 'Poland', 'player'),
	('Luke Hannant', 'England', 'player'),
	('Meritan Shabani', 'Germany', 'player'),
	('Kevin Velasco', 'Colombia', 'player'),
	('Han Pengfei', 'China PR', 'player'),
	('Rasmus Karjalainen', 'Finland', 'player'),
	('Richard Cabrera', 'Paraguay', 'player'),
	('Sead Hajrović', 'Bosnia Herzegovina', 'player'),
	('Federico Jourdan', 'Argentina', 'player'),
	('Lucas Lingman', 'Finland', 'player'),
	('Iván Jaime', 'Spain', 'player'),
	('Helmut Gutiérrez', 'Bolivia', 'player'),
	('Dawid Abramowicz', 'Poland', 'player'),
	('Kris Twardek', 'Canada', 'player'),
	('Heinz Mörschel', 'Dominican Republic', 'player'),
	('Abbas Ibrahim', 'Nigeria', 'player'),
	('Daniel Linárez', 'Venezuela', 'player'),
	('Görkem Sağlam', 'Germany', 'player'),
	('Calum MacDonald', 'Scotland', 'player'),
	('Roberto Piccoli', 'Italy', 'player'),
	('Dylan Ouédraogo', 'Burkina Faso', 'player'),
	('Jerónimo Pourtau', 'Argentina', 'player'),
	('Rasmus Wiedesheim-Paul', 'Sweden', 'player'),
	('Valentin Buhăcianu', 'Romania', 'player'),
	('Kristian Opseth', 'Norway', 'player'),
	('Kazuki Oiwa', 'Japan', 'player'),
	('Saïd Arab', 'France', 'player'),
	('Zinédine Ould Khaled', 'France', 'player'),
	('Cho Soo Hyuk', 'Korea Republic', 'player'),
	('Alexis Flips', 'France', 'player'),
	('Hideyoshi Arakaki', 'Peru', 'player'),
	('Jakub Wrąbel', 'Poland', 'player'),
	('Marvin Rittmüller', 'Germany', 'player'),
	('Tim Lemperle', 'Germany', 'player'),
	('Jonas Arweiler', 'Germany', 'player'),
	('José Florentín', 'Paraguay', 'player'),
	('Amine Oudrhiri', 'France', 'player'),
	('George Maris', 'England', 'player'),
	('Marcos Ledesma', 'Argentina', 'player'),
	('David Kopacz', 'Poland', 'player'),
	('Jimmy McLaughlin', 'United States', 'player'),
	('Osarenren Okungbowa', 'Austria', 'player'),
	('Grégoire Amiot', 'France', 'player'),
	('Alexandru Benga', 'Romania', 'player'),
	('Koki Kotegawa', 'Japan', 'player'),
	('Roberto Domínguez', 'El Salvador', 'player'),
	('Adrián Zendejas', 'United States', 'player'),
	('Kike Carrasco', 'Spain', 'player'),
	('Naoki Kawaguchi', 'Japan', 'player'),
	('Torben Müsel', 'Germany', 'player'),
	('Emanuel Coronel', 'Argentina', 'player'),
	('Federico Nicosia', 'Argentina', 'player'),
	('Martín Correa', 'Uruguay', 'player'),
	('Petar Slišković', 'Croatia', 'player'),
	('Tennai Watson', 'England', 'player'),
	('Luca Oyen', 'Belgium', 'player'),
	('Kristoffer N. Hansen', 'Norway', 'player'),
	('Jan Grzesik', 'Poland', 'player'),
	('Arnold Budimbu', 'Germany', 'player'),
	('Ahmad Toure Ngouyamsa', 'Cameroon', 'player'),
	('Marco Hausjell', 'Austria', 'player'),
	('Del Pozo', 'Spain', 'player'),
	('Tom King', 'Wales', 'player'),
	('Eugeniu Cebotaru', 'Moldova', 'player'),
	('Julius Eskesen', 'Denmark', 'player'),
	('Fabrizio Caligara', 'Italy', 'player'),
	('Cian Bolger', 'Republic of Ireland', 'player'),
	('Diallang Jaiyesimi', 'England', 'player'),
	('Joel Grant', 'Jamaica', 'player'),
	('Yann Aurel Bisseck', 'Germany', 'player'),
	('Ignace Van der Brempt', 'Belgium', 'player'),
	('Lucas Merolla', 'Argentina', 'player'),
	('Tate Russell', 'Australia', 'player'),
	('Davíð Kristján Ólafsson', 'Iceland', 'player'),
	('Rein Smit', 'Netherlands', 'player'),
	('Zhu Baojie', 'China PR', 'player'),
	('Hianga''a Mbock', 'France', 'player'),
	('Kiernan Dewsbury-Hall', 'England', 'player'),
	('Nicholas Mickelson', 'Norway', 'player'),
	('Lorenzo Callegari', 'France', 'player'),
	('Ali Odabas', 'Germany', 'player'),
	('Daniel Krezic', 'North Macedonia', 'player'),
	('Mads Roerslev', 'Denmark', 'player'),
	('Agustín Baldi', 'Argentina', 'player'),
	('James Hanson', 'England', 'player'),
	('Martin Sus', 'Czech Republic', 'player'),
	('Jakub Holúbek', 'Slovakia', 'player'),
	('Ian Lawlor', 'Republic of Ireland', 'player'),
	('Bethencourt', 'Spain', 'player'),
	('Storm Roux', 'New Zealand', 'player'),
	('Jonathan Aspropotamitis', 'Australia', 'player'),
	('Kazuhiko Chiba', 'Japan', 'player'),
	('Park Joon Kang', 'Korea Republic', 'player'),
	('Raid Al Ghamdi', 'Saudi Arabia', 'player'),
	('Kim Jung Hwan', 'Korea Republic', 'player'),
	('Adrian Gryszkiewicz', 'Poland', 'player'),
	('Alan Soñora', 'United States', 'player'),
	('Mustafa Çeçenoğlu', 'Turkey', 'player'),
	('Sam Vines', 'United States', 'player'),
	('Iago López', 'Spain', 'player'),
	('Johnny Koutroumbis', 'Australia', 'player'),
	('Andrija Luković', 'Serbia', 'player'),
	('Derik Lacerda', 'Brazil', 'player'),
	('Tashan Oakley-Boothe', 'England', 'player'),
	('Ludvig Fritzson', 'Sweden', 'player'),
	('Filippo Melegoni', 'Italy', 'player'),
	('Lautaro Guzmán', 'Argentina', 'player'),
	('Luka Racic', 'Denmark', 'player'),
	('Cristian Zúñiga', 'Colombia', 'player'),
	('Rubén Del Campo', 'Switzerland', 'player'),
	('Sid Nelson', 'England', 'player'),
	('Iké Ugbo', 'England', 'player'),
	('Brandon Vazquez', 'United States', 'player'),
	('Guillermo De Amores', 'Uruguay', 'player'),
	('Leonard Owusu', 'Ghana', 'player'),
	('Gabriel Lüchinger', 'Switzerland', 'player'),
	('Boniquet', 'Spain', 'player'),
	('Ilan Kebbal', 'France', 'player'),
	('Stephan Ambrosius', 'Germany', 'player'),
	('Lachlan Jackson', 'Australia', 'player'),
	('Vedran Janjetović', 'Australia', 'player'),
	('Julian Gölles', 'Austria', 'player'),
	('Aniss El Hriti', 'France', 'player'),
	('Malte Amundsen', 'Denmark', 'player'),
	('Damjan Daničić', 'Serbia', 'player'),
	('Jacob Mellis', 'England', 'player'),
	('Lim Min Hyuk', 'Korea Republic', 'player'),
	('Theo Robinson', 'Jamaica', 'player'),
	('Nelson Cabrera', 'Bolivia', 'player'),
	('Kristoffer Tønnessen', 'Norway', 'player'),
	('Jordan Turnbull', 'England', 'player'),
	('Zhang Wei', 'China PR', 'player'),
	('Josmar Zambrano', 'Venezuela', 'player'),
	('Cenk Özkacar', 'Turkey', 'player'),
	('Lefteris Lyratzis', 'Greece', 'player'),
	('Rafał Makowski', 'Poland', 'player'),
	('Robbie Gotts', 'England', 'player'),
	('Akihiko Takeshige', 'Japan', 'player'),
	('Rubén Pulido', 'Spain', 'player'),
	('Kelvin Yeboah', 'Ghana', 'player'),
	('Agustín Miranda', 'Uruguay', 'player'),
	('Jaime Sierra', 'Spain', 'player'),
	('Wang Hao', 'China PR', 'player'),
	('Nicky Clark', 'Scotland', 'player'),
	('Lars Olden Larsen', 'Norway', 'player'),
	('Jakub Bursztyn', 'Poland', 'player'),
	('Guillermo Benítez', 'Argentina', 'player'),
	('Clayton Donaldson', 'Jamaica', 'player'),
	('Craig Sibbald', 'Scotland', 'player'),
	('Santiago Briñone', 'Argentina', 'player'),
	('Pedro Quiñonez', 'Ecuador', 'player'),
	('Esteve Peña', 'Spain', 'player'),
	('Kevin Sibille', 'Argentina', 'player'),
	('Näis Djouahra', 'France', 'player'),
	('Jaime', 'Spain', 'player'),
	('Chris Clements', 'England', 'player'),
	('Théo Ndicka Matam', 'France', 'player'),
	('Will Nightingale', 'England', 'player'),
	('Bartosz Jaroch', 'Poland', 'player'),
	('Nicolas Janvier', 'France', 'player'),
	('Carmelo Algarañaz', 'Bolivia', 'player'),
	('Edwuin Pernía', 'Venezuela', 'player'),
	('Louis Munteanu', 'Romania', 'player'),
	('Nené', 'Portugal', 'player'),
	('Ole Amund Sveen', 'Norway', 'player'),
	('Antonio López', 'Guatemala', 'player'),
	('Ricardo Velho', 'Portugal', 'player'),
	('Martin Rønning Ovenstad', 'Norway', 'player'),
	('Jordon Garrick', 'Jamaica', 'player'),
	('Josh Benson', 'England', 'player'),
	('Abdallah Ali Mohamed', 'Comoros', 'player'),
	('Grégoire Lefebvre', 'France', 'player'),
	('Francisco Teixeira', 'Portugal', 'player'),
	('Octavio Zapata', 'Colombia', 'player'),
	('Aqeel Al Sahabi', 'Saudi Arabia', 'player'),
	('Jack Tucker', 'England', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Choi Jun Hyuk', 'Korea Republic', 'choi jun hyuk'),
	('Choi Jun Hyuk', 'Korea Republic', 'hyuk'),
	('Jusuf Gazibegović', 'Bosnia Herzegovina', 'jusuf gazibegovic'),
	('Jusuf Gazibegović', 'Bosnia Herzegovina', 'gazibegovic'),
	('Josh Pask', 'England', 'josh pask'),
	('Josh Pask', 'England', 'pask'),
	('Sixten Mohlin', 'Sweden', 'sixten mohlin'),
	('Sixten Mohlin', 'Sweden', 'mohlin'),
	('Ziggy Gordon', 'Scotland', 'gordon'),
	('Ziggy Gordon', 'Scotland', 'ziggy gordon'),
	('Thomas O''Connor', 'Republic of Ireland', 'thomas oconnor'),
	('Thomas O''Connor', 'Republic of Ireland', 'oconnor'),
	('Sander Moen Foss', 'Norway', 'foss'),
	('Sander Moen Foss', 'Norway', 'sander moen foss'),
	('Ramiro Balbuena', 'Argentina', 'ramiro balbuena'),
	('Ramiro Balbuena', 'Argentina', 'balbuena'),
	('Stephen Hendrie', 'Scotland', 'hendrie'),
	('Stephen Hendrie', 'Scotland', 'stephen hendrie'),
	('Alioune Ba', 'France', 'ba'),
	('Alioune Ba', 'France', 'alioune ba'),
	('Daniel Popa', 'Romania', 'popa'),
	('Daniel Popa', 'Romania', 'daniel popa'),
	('Eric Kahl', 'Sweden', 'kahl'),
	('Eric Kahl', 'Sweden', 'eric kahl'),
	('Brice Wembangomo', 'Norway', 'brice wembangomo'),
	('Brice Wembangomo', 'Norway', 'wembangomo'),
	('Khaled Al Khathlan', 'Saudi Arabia', 'khaled al khathlan'),
	('Khaled Al Khathlan', 'Saudi Arabia', 'khathlan'),
	('Besard Sabovic', 'North Macedonia', 'besard sabovic'),
	('Besard Sabovic', 'North Macedonia', 'sabovic'),
	('Sam Schreck', 'Germany', 'sam schreck'),
	('Sam Schreck', 'Germany', 'schreck'),
	('Mike Hauptmeijer', 'Netherlands', 'mike hauptmeijer'),
	('Mike Hauptmeijer', 'Netherlands', 'hauptmeijer'),
	('Salih Kavrazlı', 'Turkey', 'salih kavrazl'),
	('Salih Kavrazlı', 'Turkey', 'kavrazl'),
	('Ousmane Ndong', 'Senegal', 'ousmane ndong'),
	('Ousmane Ndong', 'Senegal', 'ndong'),
	('Stefan Perić', 'Austria', 'peric'),
	('Stefan Perić', 'Austria', 'stefan peric'),
	('Manuel Haas', 'Austria', 'manuel haas'),
	('Manuel Haas', 'Austria', 'haas'),
	('Bayron Garcés', 'Colombia', 'bayron garces'),
	('Bayron Garcés', 'Colombia', 'garces'),
	('Vladyslav Vakula', 'Ukraine', 'vladyslav vakula'),
	('Vladyslav Vakula', 'Ukraine', 'vakula'),
	('Makoto Okazaki', 'Japan', 'makoto okazaki'),
	('Makoto Okazaki', 'Japan', 'okazaki'),
	('Thierry Lutonda', 'Belgium', 'lutonda'),
	('Thierry Lutonda', 'Belgium', 'thierry lutonda'),
	('Zhu Chenjie', 'China PR', 'zhu chenjie'),
	('Zhu Chenjie', 'China PR', 'chenjie'),
	('Nicolás Schiappacasse', 'Uruguay', 'schiappacasse'),
	('Nicolás Schiappacasse', 'Uruguay', 'nicolas schiappacasse'),
	('Serge N''Guessan', 'Ivory Coast', 'nguessan'),
	('Serge N''Guessan', 'Ivory Coast', 'serge nguessan'),
	('Felix Drinkuth', 'Germany', 'felix drinkuth'),
	('Felix Drinkuth', 'Germany', 'drinkuth'),
	('Kays Ruiz-Atil', 'Morocco', 'kays ruizatil'),
	('Kays Ruiz-Atil', 'Morocco', 'ruizatil'),
	('Daniel Franco', 'Argentina', 'daniel franco'),
	('Daniel Franco', 'Argentina', 'franco'),
	('Stephen McGinn', 'Scotland', 'stephen mcginn'),
	('Stephen McGinn', 'Scotland', 'mcginn'),
	('Maurice Malone', 'Germany', 'malone'),
	('Maurice Malone', 'Germany', 'maurice malone'),
	('Robert Ivanov', 'Finland', 'robert ivanov'),
	('Robert Ivanov', 'Finland', 'ivanov'),
	('Ryan Watson', 'England', 'watson'),
	('Ryan Watson', 'England', 'ryan watson'),
	('Dominik Martinović', 'Croatia', 'dominik martinovic'),
	('Dominik Martinović', 'Croatia', 'martinovic'),
	('Arton Zekaj', 'Kosovo', 'zekaj'),
	('Arton Zekaj', 'Kosovo', 'arton zekaj'),
	('Jonathan Meier', 'Germany', 'jonathan meier'),
	('Jonathan Meier', 'Germany', 'meier'),
	('Lee Han Do', 'Korea Republic', 'do'),
	('Lee Han Do', 'Korea Republic', 'lee han do'),
	('Erlend Segberg', 'Norway', 'segberg'),
	('Erlend Segberg', 'Norway', 'erlend segberg'),
	('Ryotaro Hironaga', 'Japan', 'ryotaro hironaga'),
	('Ryotaro Hironaga', 'Japan', 'hironaga'),
	('Jørgen Olsen Øveraas', 'Norway', 'jrgen olsen veraas'),
	('Jørgen Olsen Øveraas', 'Norway', 'veraas'),
	('Gudmund Kongshavn', 'Norway', 'kongshavn'),
	('Gudmund Kongshavn', 'Norway', 'gudmund kongshavn'),
	('Jonas Lindberg', 'Sweden', 'jonas lindberg'),
	('Jonas Lindberg', 'Sweden', 'lindberg'),
	('Daniel Benítez', 'Venezuela', 'benitez'),
	('Daniel Benítez', 'Venezuela', 'daniel benitez'),
	('Pedro Ferreira', 'Portugal', 'pedro ferreira'),
	('Pedro Ferreira', 'Portugal', 'ferreira'),
	('Khaled Sharahili', 'Saudi Arabia', 'khaled sharahili'),
	('Khaled Sharahili', 'Saudi Arabia', 'sharahili'),
	('Park Dong Jin', 'Korea Republic', 'jin'),
	('Park Dong Jin', 'Korea Republic', 'park dong jin'),
	('Aníbal Moreno', 'Argentina', 'moreno'),
	('Aníbal Moreno', 'Argentina', 'anibal moreno'),
	('Brendan Schoonbaert', 'Belgium', 'schoonbaert'),
	('Brendan Schoonbaert', 'Belgium', 'brendan schoonbaert'),
	('Jake Vokins', 'England', 'vokins'),
	('Jake Vokins', 'England', 'jake vokins'),
	('Jan Schöppner', 'Germany', 'jan schoppner'),
	('Jan Schöppner', 'Germany', 'schoppner'),
	('Noah Diliberto', 'France', 'diliberto'),
	('Noah Diliberto', 'France', 'noah diliberto'),
	('Jørgen Hatlehol', 'Norway', 'hatlehol'),
	('Jørgen Hatlehol', 'Norway', 'jrgen hatlehol'),
	('Bruno Jordão', 'Portugal', 'bruno jordao'),
	('Bruno Jordão', 'Portugal', 'jordao'),
	('Moisés Velásquez', 'Peru', 'moises velasquez'),
	('Moisés Velásquez', 'Peru', 'velasquez'),
	('Abdullah Al Hamdan', 'Saudi Arabia', 'hamdan'),
	('Abdullah Al Hamdan', 'Saudi Arabia', 'abdullah al hamdan'),
	('Nathaniel Knight-Percival', 'England', 'knightpercival'),
	('Nathaniel Knight-Percival', 'England', 'nathaniel knightpercival'),
	('Jeon Min Gwang', 'Korea Republic', 'jeon min gwang'),
	('Jeon Min Gwang', 'Korea Republic', 'gwang'),
	('Niklas Geyrhofer', 'Austria', 'geyrhofer'),
	('Niklas Geyrhofer', 'Austria', 'niklas geyrhofer'),
	('Henrik Heggheim', 'Norway', 'henrik heggheim'),
	('Henrik Heggheim', 'Norway', 'heggheim'),
	('Morgan Ferrier', 'England', 'morgan ferrier'),
	('Morgan Ferrier', 'England', 'ferrier'),
	('Moussa Diallo', 'France', 'diallo'),
	('Moussa Diallo', 'France', 'moussa diallo'),
	('Alessandro Berardi', 'Italy', 'berardi'),
	('Alessandro Berardi', 'Italy', 'alessandro berardi'),
	('Aimen Moueffek', 'France', 'moueffek'),
	('Aimen Moueffek', 'France', 'aimen moueffek'),
	('Tomás Rojas', 'Paraguay', 'tomas rojas'),
	('Tomás Rojas', 'Paraguay', 'rojas'),
	('Osama Al Khalaf', 'Saudi Arabia', 'khalaf'),
	('Osama Al Khalaf', 'Saudi Arabia', 'osama al khalaf'),
	('Danny Henriques', 'Portugal', 'henriques'),
	('Danny Henriques', 'Portugal', 'danny henriques'),
	('Fernando Benítez', 'Paraguay', 'fernando benitez'),
	('Fernando Benítez', 'Paraguay', 'benitez'),
	('Bruny Nsimba', 'Belgium', 'bruny nsimba'),
	('Bruny Nsimba', 'Belgium', 'nsimba'),
	('Nkosingiphile Ngcobo', 'South Africa', 'ngcobo'),
	('Nkosingiphile Ngcobo', 'South Africa', 'nkosingiphile ngcobo'),
	('Olivier Mbaizo', 'Cameroon', 'mbaizo'),
	('Olivier Mbaizo', 'Cameroon', 'olivier mbaizo'),
	('Kevin Moreno', 'Colombia', 'moreno'),
	('Kevin Moreno', 'Colombia', 'kevin moreno'),
	('Jorge Cuellar', 'Bolivia', 'cuellar'),
	('Jorge Cuellar', 'Bolivia', 'jorge cuellar'),
	('Mateusz Szczepaniak', 'Poland', 'mateusz szczepaniak'),
	('Mateusz Szczepaniak', 'Poland', 'szczepaniak'),
	('Luke Hannant', 'England', 'hannant'),
	('Luke Hannant', 'England', 'luke hannant'),
	('Meritan Shabani', 'Germany', 'meritan shabani'),
	('Meritan Shabani', 'Germany', 'shabani'),
	('Kevin Velasco', 'Colombia', 'velasco'),
	('Kevin Velasco', 'Colombia', 'kevin velasco'),
	('Han Pengfei', 'China PR', 'pengfei'),
	('Han Pengfei', 'China PR', 'han pengfei'),
	('Rasmus Karjalainen', 'Finland', 'rasmus karjalainen'),
	('Rasmus Karjalainen', 'Finland', 'karjalainen'),
	('Richard Cabrera', 'Paraguay', 'cabrera'),
	('Richard Cabrera', 'Paraguay', 'richard cabrera'),
	('Sead Hajrović', 'Bosnia Herzegovina', 'hajrovic'),
	('Sead Hajrović', 'Bosnia Herzegovina', 'sead hajrovic'),
	('Federico Jourdan', 'Argentina', 'federico jourdan'),
	('Federico Jourdan', 'Argentina', 'jourdan'),
	('Lucas Lingman', 'Finland', 'lingman'),
	('Lucas Lingman', 'Finland', 'lucas lingman'),
	('Iván Jaime', 'Spain', 'ivan jaime'),
	('Iván Jaime', 'Spain', 'jaime'),
	('Helmut Gutiérrez', 'Bolivia', 'helmut gutierrez'),
	('Helmut Gutiérrez', 'Bolivia', 'gutierrez'),
	('Dawid Abramowicz', 'Poland', 'dawid abramowicz'),
	('Dawid Abramowicz', 'Poland', 'abramowicz'),
	('Kris Twardek', 'Canada', 'twardek'),
	('Kris Twardek', 'Canada', 'kris twardek'),
	('Heinz Mörschel', 'Dominican Republic', 'heinz morschel'),
	('Heinz Mörschel', 'Dominican Republic', 'morschel'),
	('Abbas Ibrahim', 'Nigeria', 'ibrahim'),
	('Abbas Ibrahim', 'Nigeria', 'abbas ibrahim'),
	('Daniel Linárez', 'Venezuela', 'linarez'),
	('Daniel Linárez', 'Venezuela', 'daniel linarez'),
	('Görkem Sağlam', 'Germany', 'saglam'),
	('Görkem Sağlam', 'Germany', 'gorkem saglam'),
	('Calum MacDonald', 'Scotland', 'calum macdonald'),
	('Calum MacDonald', 'Scotland', 'macdonald'),
	('Roberto Piccoli', 'Italy', 'roberto piccoli'),
	('Roberto Piccoli', 'Italy', 'piccoli'),
	('Dylan Ouédraogo', 'Burkina Faso', 'ouedraogo'),
	('Dylan Ouédraogo', 'Burkina Faso', 'dylan ouedraogo'),
	('Jerónimo Pourtau', 'Argentina', 'pourtau'),
	('Jerónimo Pourtau', 'Argentina', 'jeronimo pourtau'),
	('Rasmus Wiedesheim-Paul', 'Sweden', 'wiedesheimpaul'),
	('Rasmus Wiedesheim-Paul', 'Sweden', 'rasmus wiedesheimpaul'),
	('Valentin Buhăcianu', 'Romania', 'valentin buhacianu'),
	('Valentin Buhăcianu', 'Romania', 'buhacianu'),
	('Kristian Opseth', 'Norway', 'opseth'),
	('Kristian Opseth', 'Norway', 'kristian opseth'),
	('Kazuki Oiwa', 'Japan', 'oiwa'),
	('Kazuki Oiwa', 'Japan', 'kazuki oiwa'),
	('Saïd Arab', 'France', 'said arab'),
	('Saïd Arab', 'France', 'arab'),
	('Zinédine Ould Khaled', 'France', 'khaled'),
	('Zinédine Ould Khaled', 'France', 'zinedine ould khaled'),
	('Cho Soo Hyuk', 'Korea Republic', 'cho soo hyuk'),
	('Cho Soo Hyuk', 'Korea Republic', 'hyuk'),
	('Alexis Flips', 'France', 'alexis flips'),
	('Alexis Flips', 'France', 'flips'),
	('Hideyoshi Arakaki', 'Peru', 'hideyoshi arakaki'),
	('Hideyoshi Arakaki', 'Peru', 'arakaki'),
	('Jakub Wrąbel', 'Poland', 'wrabel'),
	('Jakub Wrąbel', 'Poland', 'jakub wrabel'),
	('Marvin Rittmüller', 'Germany', 'rittmuller'),
	('Marvin Rittmüller', 'Germany', 'marvin rittmuller'),
	('Tim Lemperle', 'Germany', 'lemperle'),
	('Tim Lemperle', 'Germany', 'tim lemperle'),
	('Jonas Arweiler', 'Germany', 'jonas arweiler'),
	('Jonas Arweiler', 'Germany', 'arweiler'),
	('José Florentín', 'Paraguay', 'florentin'),
	('José Florentín', 'Paraguay', 'jose florentin'),
	('Amine Oudrhiri', 'France', 'amine oudrhiri'),
	('Amine Oudrhiri', 'France', 'oudrhiri'),
	('George Maris', 'England', 'maris'),
	('George Maris', 'England', 'george maris'),
	('Marcos Ledesma', 'Argentina', 'ledesma'),
	('Marcos Ledesma', 'Argentina', 'marcos ledesma'),
	('David Kopacz', 'Poland', 'david kopacz'),
	('David Kopacz', 'Poland', 'kopacz'),
	('Jimmy McLaughlin', 'United States', 'jimmy mclaughlin'),
	('Jimmy McLaughlin', 'United States', 'mclaughlin'),
	('Osarenren Okungbowa', 'Austria', 'okungbowa'),
	('Osarenren Okungbowa', 'Austria', 'osarenren okungbowa'),
	('Grégoire Amiot', 'France', 'amiot'),
	('Grégoire Amiot', 'France', 'gregoire amiot'),
	('Alexandru Benga', 'Romania', 'benga'),
	('Alexandru Benga', 'Romania', 'alexandru benga'),
	('Koki Kotegawa', 'Japan', 'koki kotegawa'),
	('Koki Kotegawa', 'Japan', 'kotegawa'),
	('Roberto Domínguez', 'El Salvador', 'dominguez'),
	('Roberto Domínguez', 'El Salvador', 'roberto dominguez'),
	('Adrián Zendejas', 'United States', 'adrian zendejas'),
	('Adrián Zendejas', 'United States', 'zendejas'),
	('Kike Carrasco', 'Spain', 'carrasco'),
	('Kike Carrasco', 'Spain', 'kike carrasco'),
	('Naoki Kawaguchi', 'Japan', 'kawaguchi'),
	('Naoki Kawaguchi', 'Japan', 'naoki kawaguchi'),
	('Torben Müsel', 'Germany', 'musel'),
	('Torben Müsel', 'Germany', 'torben musel'),
	('Emanuel Coronel', 'Argentina', 'coronel'),
	('Emanuel Coronel', 'Argentina', 'emanuel coronel'),
	('Federico Nicosia', 'Argentina', 'nicosia'),
	('Federico Nicosia', 'Argentina', 'federico nicosia'),
	('Martín Correa', 'Uruguay', 'martin correa'),
	('Martín Correa', 'Uruguay', 'correa'),
	('Petar Slišković', 'Croatia', 'sliskovic'),
	('Petar Slišković', 'Croatia', 'petar sliskovic'),
	('Tennai Watson', 'England', 'watson'),
	('Tennai Watson', 'England', 'tennai watson'),
	('Luca Oyen', 'Belgium', 'oyen'),
	('Luca Oyen', 'Belgium', 'luca oyen'),
	('Kristoffer N. Hansen', 'Norway', 'hansen'),
	('Kristoffer N. Hansen', 'Norway', 'kristoffer n hansen'),
	('Jan Grzesik', 'Poland', 'jan grzesik'),
	('Jan Grzesik', 'Poland', 'grzesik'),
	('Arnold Budimbu', 'Germany', 'budimbu'),
	('Arnold Budimbu', 'Germany', 'arnold budimbu'),
	('Ahmad Toure Ngouyamsa', 'Cameroon', 'ahmad toure ngouyamsa'),
	('Ahmad Toure Ngouyamsa', 'Cameroon', 'ngouyamsa'),
	('Marco Hausjell', 'Austria', 'marco hausjell'),
	('Marco Hausjell', 'Austria', 'hausjell'),
	('Del Pozo', 'Spain', 'pozo'),
	('Del Pozo', 'Spain', 'del pozo'),
	('Tom King', 'Wales', 'tom king'),
	('Tom King', 'Wales', 'king'),
	('Eugeniu Cebotaru', 'Moldova', 'eugeniu cebotaru'),
	('Eugeniu Cebotaru', 'Moldova', 'cebotaru'),
	('Julius Eskesen', 'Denmark', 'eskesen'),
	('Julius Eskesen', 'Denmark', 'julius eskesen'),
	('Fabrizio Caligara', 'Italy', 'caligara'),
	('Fabrizio Caligara', 'Italy', 'fabrizio caligara'),
	('Cian Bolger', 'Republic of Ireland', 'bolger'),
	('Cian Bolger', 'Republic of Ireland', 'cian bolger'),
	('Diallang Jaiyesimi', 'England', 'jaiyesimi'),
	('Diallang Jaiyesimi', 'England', 'diallang jaiyesimi'),
	('Joel Grant', 'Jamaica', 'joel grant'),
	('Joel Grant', 'Jamaica', 'grant'),
	('Yann Aurel Bisseck', 'Germany', 'yann aurel bisseck'),
	('Yann Aurel Bisseck', 'Germany', 'bisseck'),
	('Ignace Van der Brempt', 'Belgium', 'brempt'),
	('Ignace Van der Brempt', 'Belgium', 'ignace van der brempt'),
	('Lucas Merolla', 'Argentina', 'lucas merolla'),
	('Lucas Merolla', 'Argentina', 'merolla'),
	('Tate Russell', 'Australia', 'tate russell'),
	('Tate Russell', 'Australia', 'russell'),
	('Davíð Kristján Ólafsson', 'Iceland', 'davi kristjan olafsson'),
	('Davíð Kristján Ólafsson', 'Iceland', 'olafsson'),
	('Rein Smit', 'Netherlands', 'rein smit'),
	('Rein Smit', 'Netherlands', 'smit'),
	('Zhu Baojie', 'China PR', 'zhu baojie'),
	('Zhu Baojie', 'China PR', 'baojie'),
	('Hianga''a Mbock', 'France', 'hiangaa mbock'),
	('Hianga''a Mbock', 'France', 'mbock'),
	('Kiernan Dewsbury-Hall', 'England', 'kiernan dewsburyhall'),
	('Kiernan Dewsbury-Hall', 'England', 'dewsburyhall'),
	('Nicholas Mickelson', 'Norway', 'nicholas mickelson'),
	('Nicholas Mickelson', 'Norway', 'mickelson'),
	('Lorenzo Callegari', 'France', 'callegari'),
	('Lorenzo Callegari', 'France', 'lorenzo callegari'),
	('Ali Odabas', 'Germany', 'odabas'),
	('Ali Odabas', 'Germany', 'ali odabas'),
	('Daniel Krezic', 'North Macedonia', 'daniel krezic'),
	('Daniel Krezic', 'North Macedonia', 'krezic'),
	('Mads Roerslev', 'Denmark', 'roerslev'),
	('Mads Roerslev', 'Denmark', 'mads roerslev'),
	('Agustín Baldi', 'Argentina', 'baldi'),
	('Agustín Baldi', 'Argentina', 'agustin baldi'),
	('James Hanson', 'England', 'hanson'),
	('James Hanson', 'England', 'james hanson'),
	('Martin Sus', 'Czech Republic', 'martin sus'),
	('Martin Sus', 'Czech Republic', 'sus'),
	('Jakub Holúbek', 'Slovakia', 'holubek'),
	('Jakub Holúbek', 'Slovakia', 'jakub holubek'),
	('Ian Lawlor', 'Republic of Ireland', 'ian lawlor'),
	('Ian Lawlor', 'Republic of Ireland', 'lawlor'),
	('Bethencourt', 'Spain', 'bethencourt'),
	('Storm Roux', 'New Zealand', 'roux'),
	('Storm Roux', 'New Zealand', 'storm roux'),
	('Jonathan Aspropotamitis', 'Australia', 'jonathan aspropotamitis'),
	('Jonathan Aspropotamitis', 'Australia', 'aspropotamitis'),
	('Kazuhiko Chiba', 'Japan', 'chiba'),
	('Kazuhiko Chiba', 'Japan', 'kazuhiko chiba'),
	('Park Joon Kang', 'Korea Republic', 'park joon kang'),
	('Park Joon Kang', 'Korea Republic', 'kang'),
	('Raid Al Ghamdi', 'Saudi Arabia', 'raid al ghamdi'),
	('Raid Al Ghamdi', 'Saudi Arabia', 'ghamdi'),
	('Kim Jung Hwan', 'Korea Republic', 'kim jung hwan'),
	('Kim Jung Hwan', 'Korea Republic', 'hwan'),
	('Adrian Gryszkiewicz', 'Poland', 'gryszkiewicz'),
	('Adrian Gryszkiewicz', 'Poland', 'adrian gryszkiewicz'),
	('Alan Soñora', 'United States', 'sonora'),
	('Alan Soñora', 'United States', 'alan sonora'),
	('Mustafa Çeçenoğlu', 'Turkey', 'cecenoglu'),
	('Mustafa Çeçenoğlu', 'Turkey', 'mustafa cecenoglu'),
	('Sam Vines', 'United States', 'vines'),
	('Sam Vines', 'United States', 'sam vines'),
	('Iago López', 'Spain', 'iago lopez'),
	('Iago López', 'Spain', 'lopez'),
	('Johnny Koutroumbis', 'Australia', 'johnny koutroumbis'),
	('Johnny Koutroumbis', 'Australia', 'koutroumbis'),
	('Andrija Luković', 'Serbia', 'lukovic'),
	('Andrija Luković', 'Serbia', 'andrija lukovic'),
	('Derik Lacerda', 'Brazil', 'derik lacerda'),
	('Derik Lacerda', 'Brazil', 'lacerda'),
	('Tashan Oakley-Boothe', 'England', 'oakleyboothe'),
	('Tashan Oakley-Boothe', 'England', 'tashan oakleyboothe'),
	('Ludvig Fritzson', 'Sweden', 'fritzson'),
	('Ludvig Fritzson', 'Sweden', 'ludvig fritzson'),
	('Filippo Melegoni', 'Italy', 'melegoni'),
	('Filippo Melegoni', 'Italy', 'filippo melegoni'),
	('Lautaro Guzmán', 'Argentina', 'lautaro guzman'),
	('Lautaro Guzmán', 'Argentina', 'guzman'),
	('Luka Racic', 'Denmark', 'racic'),
	('Luka Racic', 'Denmark', 'luka racic'),
	('Cristian Zúñiga', 'Colombia', 'zuniga'),
	('Cristian Zúñiga', 'Colombia', 'cristian zuniga'),
	('Rubén Del Campo', 'Switzerland', 'campo'),
	('Rubén Del Campo', 'Switzerland', 'ruben del campo'),
	('Sid Nelson', 'England', 'nelson'),
	('Sid Nelson', 'England', 'sid nelson'),
	('Iké Ugbo', 'England', 'ike ugbo'),
	('Iké Ugbo', 'England', 'ugbo'),
	('Brandon Vazquez', 'United States', 'brandon vazquez'),
	('Brandon Vazquez', 'United States', 'vazquez'),
	('Guillermo De Amores', 'Uruguay', 'guillermo de amores'),
	('Guillermo De Amores', 'Uruguay', 'amores'),
	('Leonard Owusu', 'Ghana', 'leonard owusu'),
	('Leonard Owusu', 'Ghana', 'owusu'),
	('Gabriel Lüchinger', 'Switzerland', 'luchinger'),
	('Gabriel Lüchinger', 'Switzerland', 'gabriel luchinger'),
	('Boniquet', 'Spain', 'boniquet'),
	('Ilan Kebbal', 'France', 'ilan kebbal'),
	('Ilan Kebbal', 'France', 'kebbal'),
	('Stephan Ambrosius', 'Germany', 'stephan ambrosius'),
	('Stephan Ambrosius', 'Germany', 'ambrosius'),
	('Lachlan Jackson', 'Australia', 'lachlan jackson'),
	('Lachlan Jackson', 'Australia', 'jackson'),
	('Vedran Janjetović', 'Australia', 'janjetovic'),
	('Vedran Janjetović', 'Australia', 'vedran janjetovic'),
	('Julian Gölles', 'Austria', 'golles'),
	('Julian Gölles', 'Austria', 'julian golles'),
	('Aniss El Hriti', 'France', 'aniss el hriti'),
	('Aniss El Hriti', 'France', 'hriti'),
	('Malte Amundsen', 'Denmark', 'amundsen'),
	('Malte Amundsen', 'Denmark', 'malte amundsen'),
	('Damjan Daničić', 'Serbia', 'danicic'),
	('Damjan Daničić', 'Serbia', 'damjan danicic'),
	('Jacob Mellis', 'England', 'jacob mellis'),
	('Jacob Mellis', 'England', 'mellis'),
	('Lim Min Hyuk', 'Korea Republic', 'lim min hyuk'),
	('Lim Min Hyuk', 'Korea Republic', 'hyuk'),
	('Theo Robinson', 'Jamaica', 'robinson'),
	('Theo Robinson', 'Jamaica', 'theo robinson'),
	('Nelson Cabrera', 'Bolivia', 'nelson cabrera'),
	('Nelson Cabrera', 'Bolivia', 'cabrera'),
	('Kristoffer Tønnessen', 'Norway', 'tnnessen'),
	('Kristoffer Tønnessen', 'Norway', 'kristoffer tnnessen'),
	('Jordan Turnbull', 'England', 'turnbull'),
	('Jordan Turnbull', 'England', 'jordan turnbull'),
	('Zhang Wei', 'China PR', 'wei'),
	('Zhang Wei', 'China PR', 'zhang wei'),
	('Josmar Zambrano', 'Venezuela', 'josmar zambrano'),
	('Josmar Zambrano', 'Venezuela', 'zambrano'),
	('Cenk Özkacar', 'Turkey', 'cenk ozkacar'),
	('Cenk Özkacar', 'Turkey', 'ozkacar'),
	('Lefteris Lyratzis', 'Greece', 'lefteris lyratzis'),
	('Lefteris Lyratzis', 'Greece', 'lyratzis'),
	('Rafał Makowski', 'Poland', 'makowski'),
	('Rafał Makowski', 'Poland', 'rafa makowski'),
	('Robbie Gotts', 'England', 'gotts'),
	('Robbie Gotts', 'England', 'robbie gotts'),
	('Akihiko Takeshige', 'Japan', 'akihiko takeshige'),
	('Akihiko Takeshige', 'Japan', 'takeshige'),
	('Rubén Pulido', 'Spain', 'pulido'),
	('Rubén Pulido', 'Spain', 'ruben pulido'),
	('Kelvin Yeboah', 'Ghana', 'yeboah'),
	('Kelvin Yeboah', 'Ghana', 'kelvin yeboah'),
	('Agustín Miranda', 'Uruguay', 'agustin miranda'),
	('Agustín Miranda', 'Uruguay', 'miranda'),
	('Jaime Sierra', 'Spain', 'jaime sierra'),
	('Jaime Sierra', 'Spain', 'sierra'),
	('Wang Hao', 'China PR', 'hao'),
	('Wang Hao', 'China PR', 'wang hao'),
	('Nicky Clark', 'Scotland', 'clark'),
	('Nicky Clark', 'Scotland', 'nicky clark'),
	('Lars Olden Larsen', 'Norway', 'larsen'),
	('Lars Olden Larsen', 'Norway', 'lars olden larsen'),
	('Jakub Bursztyn', 'Poland', 'bursztyn'),
	('Jakub Bursztyn', 'Poland', 'jakub bursztyn'),
	('Guillermo Benítez', 'Argentina', 'benitez'),
	('Guillermo Benítez', 'Argentina', 'guillermo benitez'),
	('Clayton Donaldson', 'Jamaica', 'donaldson'),
	('Clayton Donaldson', 'Jamaica', 'clayton donaldson'),
	('Craig Sibbald', 'Scotland', 'sibbald'),
	('Craig Sibbald', 'Scotland', 'craig sibbald'),
	('Santiago Briñone', 'Argentina', 'santiago brinone'),
	('Santiago Briñone', 'Argentina', 'brinone'),
	('Pedro Quiñonez', 'Ecuador', 'pedro quinonez'),
	('Pedro Quiñonez', 'Ecuador', 'quinonez'),
	('Esteve Peña', 'Spain', 'esteve pena'),
	('Esteve Peña', 'Spain', 'pena'),
	('Kevin Sibille', 'Argentina', 'sibille'),
	('Kevin Sibille', 'Argentina', 'kevin sibille'),
	('Näis Djouahra', 'France', 'djouahra'),
	('Näis Djouahra', 'France', 'nais djouahra'),
	('Jaime', 'Spain', 'jaime'),
	('Chris Clements', 'England', 'chris clements'),
	('Chris Clements', 'England', 'clements'),
	('Théo Ndicka Matam', 'France', 'theo ndicka matam'),
	('Théo Ndicka Matam', 'France', 'matam'),
	('Will Nightingale', 'England', 'will nightingale'),
	('Will Nightingale', 'England', 'nightingale'),
	('Bartosz Jaroch', 'Poland', 'bartosz jaroch'),
	('Bartosz Jaroch', 'Poland', 'jaroch'),
	('Nicolas Janvier', 'France', 'janvier'),
	('Nicolas Janvier', 'France', 'nicolas janvier'),
	('Carmelo Algarañaz', 'Bolivia', 'algaranaz'),
	('Carmelo Algarañaz', 'Bolivia', 'carmelo algaranaz'),
	('Edwuin Pernía', 'Venezuela', 'edwuin pernia'),
	('Edwuin Pernía', 'Venezuela', 'pernia'),
	('Louis Munteanu', 'Romania', 'louis munteanu'),
	('Louis Munteanu', 'Romania', 'munteanu'),
	('Nené', 'Portugal', 'nene'),
	('Ole Amund Sveen', 'Norway', 'ole amund sveen'),
	('Ole Amund Sveen', 'Norway', 'sveen'),
	('Antonio López', 'Guatemala', 'lopez'),
	('Antonio López', 'Guatemala', 'antonio lopez'),
	('Ricardo Velho', 'Portugal', 'ricardo velho'),
	('Ricardo Velho', 'Portugal', 'velho'),
	('Martin Rønning Ovenstad', 'Norway', 'martin rnning ovenstad'),
	('Martin Rønning Ovenstad', 'Norway', 'ovenstad'),
	('Jordon Garrick', 'Jamaica', 'garrick'),
	('Jordon Garrick', 'Jamaica', 'jordon garrick'),
	('Josh Benson', 'England', 'benson'),
	('Josh Benson', 'England', 'josh benson'),
	('Abdallah Ali Mohamed', 'Comoros', 'mohamed'),
	('Abdallah Ali Mohamed', 'Comoros', 'abdallah ali mohamed'),
	('Grégoire Lefebvre', 'France', 'gregoire lefebvre'),
	('Grégoire Lefebvre', 'France', 'lefebvre'),
	('Francisco Teixeira', 'Portugal', 'francisco teixeira'),
	('Francisco Teixeira', 'Portugal', 'teixeira'),
	('Octavio Zapata', 'Colombia', 'zapata'),
	('Octavio Zapata', 'Colombia', 'octavio zapata'),
	('Aqeel Al Sahabi', 'Saudi Arabia', 'sahabi'),
	('Aqeel Al Sahabi', 'Saudi Arabia', 'aqeel al sahabi'),
	('Jack Tucker', 'England', 'jack tucker'),
	('Jack Tucker', 'England', 'tucker')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';