INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Charles-Jesaja Herrmann', 'Germany', 'player'),
	('Sergio Carrasco', 'Spain', 'player'),
	('Vato Arveladze', 'Georgia', 'player'),
	('Stefan Bajic', 'France', 'player'),
	('Sayouba Mandé', 'Ivory Coast', 'player'),
	('Carlo Villanueva', 'Chile', 'player'),
	('Lukas Gabbichler', 'Austria', 'player'),
	('Leonardo Aponte', 'Venezuela', 'player'),
	('Patryk Szysz', 'Poland', 'player'),
	('Yuji Senuma', 'Japan', 'player'),
	('Henrik Löfkvist', 'Sweden', 'player'),
	('Iván Salazar', 'Uruguay', 'player'),
	('Keith Ward', 'Republic of Ireland', 'player'),
	('Brandon Fleming', 'England', 'player'),
	('Bartosz Kieliba', 'Poland', 'player'),
	('Martín Rea', 'Uruguay', 'player'),
	('Yulian Gómez', 'Colombia', 'player'),
	('Jakub Kiełb', 'Poland', 'player'),
	('Christoffer Carlsson', 'Sweden', 'player'),
	('Jamie McCart', 'Scotland', 'player'),
	('Shuaibu Lalle Ibrahim', 'Nigeria', 'player'),
	('Abdullah Al Shammari', 'Saudi Arabia', 'player'),
	('Dom Telford', 'England', 'player'),
	('Saturday Erimuya', 'Nigeria', 'player'),
	('Jonathan Klinsmann', 'United States', 'player'),
	('Yonaiker Reyes', 'Venezuela', 'player'),
	('Fredrik Sjølstad', 'Norway', 'player'),
	('Yanick van Osch', 'Netherlands', 'player'),
	('Thomás Ortega', 'Argentina', 'player'),
	('Florian Toplitsch', 'Austria', 'player'),
	('Wesam Suwayyid', 'Saudi Arabia', 'player'),
	('Aitor Lorea', 'Spain', 'player'),
	('Eman Marković', 'Norway', 'player'),
	('Kai Brünker', 'Germany', 'player'),
	('Lee Jae Kwon', 'Korea Republic', 'player'),
	('Ryan Delaney', 'Republic of Ireland', 'player'),
	('Josef Welzmüller', 'Germany', 'player'),
	('Patrick Sussek', 'Germany', 'player'),
	('Konan N''Dri', 'Ivory Coast', 'player'),
	('Trent Buhagiar', 'Australia', 'player'),
	('Jorge Trinidad', 'Uruguay', 'player'),
	('Julius Düker', 'Germany', 'player'),
	('Mario López Quintana', 'Paraguay', 'player'),
	('Matthias Hamrol', 'Germany', 'player'),
	('Ashley Eastham', 'England', 'player'),
	('Dennis Mast', 'Germany', 'player'),
	('Jeong Ho Jeong', 'Korea Republic', 'player'),
	('Joaquín Trasante', 'Uruguay', 'player'),
	('Ben Cabango', 'Wales', 'player'),
	('Paul Will', 'Germany', 'player'),
	('Harry Charsley', 'Republic of Ireland', 'player'),
	('John Salas', 'Chile', 'player'),
	('Oriol Rey', 'Spain', 'player'),
	('Li Shenglong', 'China PR', 'player'),
	('Bobby Grant', 'England', 'player'),
	('Kim Dong Jin', 'Korea Republic', 'player'),
	('Frederik Lauenborg', 'Denmark', 'player'),
	('Franco Flückiger', 'Germany', 'player'),
	('Mohamed Badamosi', 'Gambia', 'player'),
	('Felix Burmeister', 'Germany', 'player'),
	('Toni Lindenhahn', 'Germany', 'player'),
	('Myeong Joon Jae', 'Korea Republic', 'player'),
	('Kayne Ramsay', 'England', 'player'),
	('Mohammed Ahmed', 'United Arab Emirates', 'player'),
	('Bruno Morais', 'Portugal', 'player'),
	('Luis Castillo', 'Ecuador', 'player'),
	('Jesús Meza', 'Venezuela', 'player'),
	('Danny Rowe', 'England', 'player'),
	('Matías Oyola', 'Ecuador', 'player'),
	('Niels Hahn', 'Austria', 'player'),
	('Mihlali Mayambela', 'South Africa', 'player'),
	('Keisuke Saka', 'Japan', 'player'),
	('Jack Taylor', 'Republic of Ireland', 'player'),
	('Lewis Young', 'England', 'player'),
	('Ryan Malone', 'United States', 'player'),
	('Mohamed Gouaida', 'Tunisia', 'player'),
	('Alejandro Marcos', 'Spain', 'player'),
	('Julio Villalba', 'Paraguay', 'player'),
	('Pedro Álvarez', 'Venezuela', 'player'),
	('Zheng Dalun', 'China PR', 'player'),
	('Lamine Sherif', 'Guinea', 'player'),
	('Scott Burgess', 'England', 'player'),
	('Nico Rieble', 'Germany', 'player'),
	('Patrick Hobsch', 'Germany', 'player'),
	('Francesco Lo Celso', 'Argentina', 'player'),
	('Daniel Valdés', 'Venezuela', 'player'),
	('Willie Britto', 'Ivory Coast', 'player'),
	('Miguel Morro', 'Spain', 'player'),
	('Ronan Finn', 'Republic of Ireland', 'player'),
	('Filip Sachpekidis', 'Sweden', 'player'),
	('Ignacio Jáuregui', 'Argentina', 'player'),
	('Andres Gudiño', 'Mexico', 'player'),
	('Ignacio Pereira', 'Uruguay', 'player'),
	('Eliot Matazo', 'Belgium', 'player'),
	('Callum Gribbin', 'England', 'player'),
	('Lukas Watkowiak', 'Germany', 'player'),
	('Nicky Cadden', 'Scotland', 'player'),
	('Iago Indias', 'Spain', 'player'),
	('Doru Popadiuc', 'Romania', 'player'),
	('Nick Shinton', 'Belgium', 'player'),
	('Matheus Clemente', 'Portugal', 'player'),
	('Adrián Goransch', 'Mexico', 'player'),
	('Mike van Beijnen', 'Netherlands', 'player'),
	('Soufian Benyamina', 'Germany', 'player'),
	('Ahmed Al Kassar', 'Saudi Arabia', 'player'),
	('Kilian Jakob', 'Germany', 'player'),
	('Zoran Kvržić', 'Bosnia Herzegovina', 'player'),
	('Josh Lillis', 'England', 'player'),
	('Sebas Moyano', 'Spain', 'player'),
	('Remeao Hutton', 'England', 'player'),
	('Izunna Uzochukwu', 'Nigeria', 'player'),
	('Olaus Jair Skarsem', 'Norway', 'player'),
	('Gracjan Jaroch', 'Poland', 'player'),
	('Jacob Shaffelburg', 'Canada', 'player'),
	('Sivert Gussiås', 'Norway', 'player'),
	('Miles Welch-Hayes', 'England', 'player'),
	('Fortuño', 'Spain', 'player'),
	('Hou Yongyong', 'China PR', 'player'),
	('Hamad Al Jayzani', 'Saudi Arabia', 'player'),
	('Kevin Tshiembe', 'Denmark', 'player'),
	('Romain Vincelot', 'France', 'player'),
	('Ben Garratt', 'England', 'player'),
	('Sari Amro', 'Saudi Arabia', 'player'),
	('Gustav Marcussen', 'Denmark', 'player'),
	('Paolo Méndez', 'Peru', 'player'),
	('Victor Lobry', 'France', 'player'),
	('Shin Chang Moo', 'Korea Republic', 'player'),
	('Timm Golley', 'Germany', 'player'),
	('Yaki Yen', 'Chinese Taipei', 'player'),
	('Luis Ramírez', 'Venezuela', 'player'),
	('Elsamed Ramaj', 'Albania', 'player'),
	('Luís Santos', 'Portugal', 'player'),
	('Simon Thomas', 'Canada', 'player'),
	('Stuart Sinclair', 'England', 'player'),
	('Erhan Mašović', 'Serbia', 'player'),
	('Nair Tiknizyan', 'Russia', 'player'),
	('Luis Arce', 'Ecuador', 'player'),
	('Ali Koiki', 'England', 'player'),
	('Emmanuel Banda', 'Zambia', 'player'),
	('Abdallahi Mahmoud', 'Mauritania', 'player'),
	('Nicky Ajose', 'England', 'player'),
	('Jorge Ortiz', 'Argentina', 'player'),
	('Parfait Bizoza', 'Burundi', 'player'),
	('Jesús Rivas', 'Mexico', 'player'),
	('Darío Poveda', 'Spain', 'player'),
	('George Marsh', 'England', 'player'),
	('Luis Binks', 'England', 'player'),
	('Gustavo Olguín', 'Bolivia', 'player'),
	('Lü Haidong', 'China PR', 'player'),
	('Konstantin Maradishvili', 'Russia', 'player'),
	('Conor McAleny', 'England', 'player'),
	('Shi Zhe', 'China PR', 'player'),
	('William Bianda', 'France', 'player'),
	('Juan Lara', 'Ecuador', 'player'),
	('Aaron Greene', 'Republic of Ireland', 'player'),
	('Jacob Buus', 'Denmark', 'player'),
	('Luo Jing', 'China PR', 'player'),
	('Noah Fadiga', 'Belgium', 'player'),
	('Alexis Guendouz', 'France', 'player'),
	('Shaquill Sno', 'Netherlands', 'player'),
	('Armando Escobar', 'Mexico', 'player'),
	('Jack Rose', 'England', 'player'),
	('Josh Gordon', 'England', 'player'),
	('Turki Al Ammar', 'Saudi Arabia', 'player'),
	('Keith Watson', 'Scotland', 'player'),
	('Elias Ramírez', 'Spain', 'player'),
	('Alin Dobrosavlevici', 'Romania', 'player'),
	('Roque Caballero', 'Paraguay', 'player'),
	('Facundo Silvera', 'Uruguay', 'player'),
	('Aramide Oteh', 'England', 'player'),
	('Lino Kasten', 'Germany', 'player'),
	('Toumani Diagouraga', 'France', 'player'),
	('Reuben Reid', 'England', 'player'),
	('Kristian Dennis', 'England', 'player'),
	('Erwin Koffi', 'Ivory Coast', 'player'),
	('Christoph Daferner', 'Germany', 'player'),
	('Harry Lennon', 'England', 'player'),
	('Kwadwo Duah', 'Switzerland', 'player'),
	('Ibra Pérez', 'Spain', 'player'),
	('Marcos Lavín', 'Spain', 'player'),
	('Luis Nery Caballero', 'Paraguay', 'player'),
	('Daniele Sommariva', 'Italy', 'player'),
	('José Amo', 'Spain', 'player'),
	('Yosuke Akiyama', 'Japan', 'player'),
	('Shao Puliang', 'China PR', 'player'),
	('Kim Ji Hyun', 'Korea Republic', 'player'),
	('Nassim Ouammou', 'France', 'player'),
	('Nico Klaß', 'Germany', 'player'),
	('Nicolae Mușat', 'Romania', 'player'),
	('Selim Gündüz', 'Germany', 'player'),
	('Vegard Moberg', 'Norway', 'player'),
	('Abdulkarim Al Qahtani', 'Saudi Arabia', 'player'),
	('Álex Pachón', 'Spain', 'player'),
	('Milan Gajić', 'Serbia', 'player'),
	('Isidro Pitta', 'Paraguay', 'player'),
	('Lukas Malicsek', 'Austria', 'player'),
	('Happy Mashiane', 'South Africa', 'player'),
	('Nicolás Royón', 'Uruguay', 'player'),
	('Othoniel Arce', 'Mexico', 'player'),
	('Mateusz Żyro', 'Poland', 'player'),
	('Jan-Marc Schneider', 'Germany', 'player'),
	('Lewis Smith', 'Scotland', 'player'),
	('Gonçalo Inácio', 'Portugal', 'player'),
	('Hjalmar Ekdal', 'Sweden', 'player'),
	('Shun Yoshida', 'Japan', 'player'),
	('Luke Gambin', 'Malta', 'player'),
	('Michał Jakóbowski', 'Poland', 'player'),
	('Nicolás Giraldo', 'Colombia', 'player'),
	('Aleksa Terzić', 'Serbia', 'player'),
	('Juan Pablo Rioja', 'Bolivia', 'player'),
	('Benny Díaz', 'United States', 'player'),
	('Nicholas D''Agostino', 'Australia', 'player'),
	('Dan Casey', 'Republic of Ireland', 'player'),
	('Raffael Behounek', 'Austria', 'player'),
	('Júnior Brumado', 'Brazil', 'player'),
	('Diego Živulić', 'Croatia', 'player'),
	('Darragh Leahy', 'Republic of Ireland', 'player'),
	('Jonathan Suárez', 'United States', 'player'),
	('Elliott Whitehouse', 'England', 'player'),
	('Bai Yuefeng', 'China PR', 'player'),
	('Kim Sang Won', 'Korea Republic', 'player'),
	('Dennis Corozo', 'Ecuador', 'player'),
	('Thomas Keller', 'Germany', 'player'),
	('Mathias Bringaker', 'Norway', 'player'),
	('Carlos Torres', 'Venezuela', 'player'),
	('Diego Duarte', 'Paraguay', 'player'),
	('Sam Foley', 'Republic of Ireland', 'player'),
	('Rolando Ortíz', 'Paraguay', 'player'),
	('Tomás Castro', 'Portugal', 'player'),
	('Luis Ortíz', 'Paraguay', 'player'),
	('Alex Kenyon', 'England', 'player'),
	('Mario', 'Spain', 'player'),
	('Ivan Vujica', 'Australia', 'player'),
	('Martin Samuelsen', 'Norway', 'player'),
	('Samúel Kári Friðjónsson', 'Iceland', 'player'),
	('Pontus Almqvist', 'Sweden', 'player'),
	('Ben Jackson', 'England', 'player'),
	('Vlad Morar', 'Romania', 'player'),
	('Juan Mosquera', 'Colombia', 'player'),
	('Panagiotis Deligiannidis', 'Greece', 'player'),
	('Odysseus Velanas', 'Netherlands', 'player'),
	('Mun Kyung Gun', 'Korea Republic', 'player'),
	('Anthony Landázuri', 'Ecuador', 'player'),
	('Rune Frantsen', 'Denmark', 'player'),
	('Simone Bastoni', 'Italy', 'player'),
	('Matty Virtue', 'England', 'player'),
	('Lukáš Hroššo', 'Slovakia', 'player'),
	('Jung Hoon Sung', 'Korea Republic', 'player'),
	('Vadim Rață', 'Moldova', 'player'),
	('Jacson Pita', 'Ecuador', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Charles-Jesaja Herrmann', 'Germany', 'herrmann'),
	('Charles-Jesaja Herrmann', 'Germany', 'charlesjesaja herrmann'),
	('Sergio Carrasco', 'Spain', 'sergio carrasco'),
	('Sergio Carrasco', 'Spain', 'carrasco'),
	('Vato Arveladze', 'Georgia', 'arveladze'),
	('Vato Arveladze', 'Georgia', 'vato arveladze'),
	('Stefan Bajic', 'France', 'stefan bajic'),
	('Stefan Bajic', 'France', 'bajic'),
	('Sayouba Mandé', 'Ivory Coast', 'sayouba mande'),
	('Sayouba Mandé', 'Ivory Coast', 'mande'),
	('Carlo Villanueva', 'Chile', 'carlo villanueva'),
	('Carlo Villanueva', 'Chile', 'villanueva'),
	('Lukas Gabbichler', 'Austria', 'lukas gabbichler'),
	('Lukas Gabbichler', 'Austria', 'gabbichler'),
	('Leonardo Aponte', 'Venezuela', 'leonardo aponte'),
	('Leonardo Aponte', 'Venezuela', 'aponte'),
	('Patryk Szysz', 'Poland', 'patryk szysz'),
	('Patryk Szysz', 'Poland', 'szysz'),
	('Yuji Senuma', 'Japan', 'senuma'),
	('Yuji Senuma', 'Japan', 'yuji senuma'),
	('Henrik Löfkvist', 'Sweden', 'henrik lofkvist'),
	('Henrik Löfkvist', 'Sweden', 'lofkvist'),
	('Iván Salazar', 'Uruguay', 'salazar'),
	('Iván Salazar', 'Uruguay', 'ivan salazar'),
	('Keith Ward', 'Republic of Ireland', 'ward'),
	('Keith Ward', 'Republic of Ireland', 'keith ward'),
	('Brandon Fleming', 'England', 'brandon fleming'),
	('Brandon Fleming', 'England', 'fleming'),
	('Bartosz Kieliba', 'Poland', 'bartosz kieliba'),
	('Bartosz Kieliba', 'Poland', 'kieliba'),
	('Martín Rea', 'Uruguay', 'rea'),
	('Martín Rea', 'Uruguay', 'martin rea'),
	('Yulian Gómez', 'Colombia', 'gomez'),
	('Yulian Gómez', 'Colombia', 'yulian gomez'),
	('Jakub Kiełb', 'Poland', 'kieb'),
	('Jakub Kiełb', 'Poland', 'jakub kieb'),
	('Christoffer Carlsson', 'Sweden', 'christoffer carlsson'),
	('Christoffer Carlsson', 'Sweden', 'carlsson'),
	('Jamie McCart', 'Scotland', 'mccart'),
	('Jamie McCart', 'Scotland', 'jamie mccart'),
	('Shuaibu Lalle Ibrahim', 'Nigeria', 'ibrahim'),
	('Shuaibu Lalle Ibrahim', 'Nigeria', 'shuaibu lalle ibrahim'),
	('Abdullah Al Shammari', 'Saudi Arabia', 'abdullah al shammari'),
	('Abdullah Al Shammari', 'Saudi Arabia', 'shammari'),
	('Dom Telford', 'England', 'dom telford'),
	('Dom Telford', 'England', 'telford'),
	('Saturday Erimuya', 'Nigeria', 'erimuya'),
	('Saturday Erimuya', 'Nigeria', 'saturday erimuya'),
	('Jonathan Klinsmann', 'United States', 'jonathan klinsmann'),
	('Jonathan Klinsmann', 'United States', 'klinsmann'),
	('Yonaiker Reyes', 'Venezuela', 'yonaiker reyes'),
	('Yonaiker Reyes', 'Venezuela', 'reyes'),
	('Fredrik Sjølstad', 'Norway', 'fredrik sjlstad'),
	('Fredrik Sjølstad', 'Norway', 'sjlstad'),
	('Yanick van Osch', 'Netherlands', 'yanick van osch'),
	('Yanick van Osch', 'Netherlands', 'osch'),
	('Thomás Ortega', 'Argentina', 'ortega'),
	('Thomás Ortega', 'Argentina', 'thomas ortega'),
	('Florian Toplitsch', 'Austria', 'florian toplitsch'),
	('Florian Toplitsch', 'Austria', 'toplitsch'),
	('Wesam Suwayyid', 'Saudi Arabia', 'wesam suwayyid'),
	('Wesam Suwayyid', 'Saudi Arabia', 'suwayyid'),
	('Aitor Lorea', 'Spain', 'aitor lorea'),
	('Aitor Lorea', 'Spain', 'lorea'),
	('Eman Marković', 'Norway', 'eman markovic'),
	('Eman Marković', 'Norway', 'markovic'),
	('Kai Brünker', 'Germany', 'kai brunker'),
	('Kai Brünker', 'Germany', 'brunker'),
	('Lee Jae Kwon', 'Korea Republic', 'lee jae kwon'),
	('Lee Jae Kwon', 'Korea Republic', 'kwon'),
	('Ryan Delaney', 'Republic of Ireland', 'ryan delaney'),
	('Ryan Delaney', 'Republic of Ireland', 'delaney'),
	('Josef Welzmüller', 'Germany', 'josef welzmuller'),
	('Josef Welzmüller', 'Germany', 'welzmuller'),
	('Patrick Sussek', 'Germany', 'patrick sussek'),
	('Patrick Sussek', 'Germany', 'sussek'),
	('Konan N''Dri', 'Ivory Coast', 'konan ndri'),
	('Konan N''Dri', 'Ivory Coast', 'ndri'),
	('Trent Buhagiar', 'Australia', 'buhagiar'),
	('Trent Buhagiar', 'Australia', 'trent buhagiar'),
	('Jorge Trinidad', 'Uruguay', 'jorge trinidad'),
	('Jorge Trinidad', 'Uruguay', 'trinidad'),
	('Julius Düker', 'Germany', 'duker'),
	('Julius Düker', 'Germany', 'julius duker'),
	('Mario López Quintana', 'Paraguay', 'mario lopez quintana'),
	('Mario López Quintana', 'Paraguay', 'quintana'),
	('Matthias Hamrol', 'Germany', 'hamrol'),
	('Matthias Hamrol', 'Germany', 'matthias hamrol'),
	('Ashley Eastham', 'England', 'eastham'),
	('Ashley Eastham', 'England', 'ashley eastham'),
	('Dennis Mast', 'Germany', 'mast'),
	('Dennis Mast', 'Germany', 'dennis mast'),
	('Jeong Ho Jeong', 'Korea Republic', 'jeong'),
	('Jeong Ho Jeong', 'Korea Republic', 'jeong ho jeong'),
	('Joaquín Trasante', 'Uruguay', 'joaquin trasante'),
	('Joaquín Trasante', 'Uruguay', 'trasante'),
	('Ben Cabango', 'Wales', 'cabango'),
	('Ben Cabango', 'Wales', 'ben cabango'),
	('Paul Will', 'Germany', 'paul will'),
	('Paul Will', 'Germany', 'will'),
	('Harry Charsley', 'Republic of Ireland', 'charsley'),
	('Harry Charsley', 'Republic of Ireland', 'harry charsley'),
	('John Salas', 'Chile', 'salas'),
	('John Salas', 'Chile', 'john salas'),
	('Oriol Rey', 'Spain', 'rey'),
	('Oriol Rey', 'Spain', 'oriol rey'),
	('Li Shenglong', 'China PR', 'li shenglong'),
	('Li Shenglong', 'China PR', 'shenglong'),
	('Bobby Grant', 'England', 'grant'),
	('Bobby Grant', 'England', 'bobby grant'),
	('Kim Dong Jin', 'Korea Republic', 'jin'),
	('Kim Dong Jin', 'Korea Republic', 'kim dong jin'),
	('Frederik Lauenborg', 'Denmark', 'frederik lauenborg'),
	('Frederik Lauenborg', 'Denmark', 'lauenborg'),
	('Franco Flückiger', 'Germany', 'franco fluckiger'),
	('Franco Flückiger', 'Germany', 'fluckiger'),
	('Mohamed Badamosi', 'Gambia', 'mohamed badamosi'),
	('Mohamed Badamosi', 'Gambia', 'badamosi'),
	('Felix Burmeister', 'Germany', 'burmeister'),
	('Felix Burmeister', 'Germany', 'felix burmeister'),
	('Toni Lindenhahn', 'Germany', 'lindenhahn'),
	('Toni Lindenhahn', 'Germany', 'toni lindenhahn'),
	('Myeong Joon Jae', 'Korea Republic', 'myeong joon jae'),
	('Myeong Joon Jae', 'Korea Republic', 'jae'),
	('Kayne Ramsay', 'England', 'kayne ramsay'),
	('Kayne Ramsay', 'England', 'ramsay'),
	('Mohammed Ahmed', 'United Arab Emirates', 'ahmed'),
	('Mohammed Ahmed', 'United Arab Emirates', 'mohammed ahmed'),
	('Bruno Morais', 'Portugal', 'morais'),
	('Bruno Morais', 'Portugal', 'bruno morais'),
	('Luis Castillo', 'Ecuador', 'luis castillo'),
	('Luis Castillo', 'Ecuador', 'castillo'),
	('Jesús Meza', 'Venezuela', 'jesus meza'),
	('Jesús Meza', 'Venezuela', 'meza'),
	('Danny Rowe', 'England', 'rowe'),
	('Danny Rowe', 'England', 'danny rowe'),
	('Matías Oyola', 'Ecuador', 'oyola'),
	('Matías Oyola', 'Ecuador', 'matias oyola'),
	('Niels Hahn', 'Austria', 'hahn'),
	('Niels Hahn', 'Austria', 'niels hahn'),
	('Mihlali Mayambela', 'South Africa', 'mihlali mayambela'),
	('Mihlali Mayambela', 'South Africa', 'mayambela'),
	('Keisuke Saka', 'Japan', 'keisuke saka'),
	('Keisuke Saka', 'Japan', 'saka'),
	('Jack Taylor', 'Republic of Ireland', 'taylor'),
	('Jack Taylor', 'Republic of Ireland', 'jack taylor'),
	('Lewis Young', 'England', 'young'),
	('Lewis Young', 'England', 'lewis young'),
	('Ryan Malone', 'United States', 'malone'),
	('Ryan Malone', 'United States', 'ryan malone'),
	('Mohamed Gouaida', 'Tunisia', 'mohamed gouaida'),
	('Mohamed Gouaida', 'Tunisia', 'gouaida'),
	('Alejandro Marcos', 'Spain', 'marcos'),
	('Alejandro Marcos', 'Spain', 'alejandro marcos'),
	('Julio Villalba', 'Paraguay', 'villalba'),
	('Julio Villalba', 'Paraguay', 'julio villalba'),
	('Pedro Álvarez', 'Venezuela', 'alvarez'),
	('Pedro Álvarez', 'Venezuela', 'pedro alvarez'),
	('Zheng Dalun', 'China PR', 'dalun'),
	('Zheng Dalun', 'China PR', 'zheng dalun'),
	('Lamine Sherif', 'Guinea', 'sherif'),
	('Lamine Sherif', 'Guinea', 'lamine sherif'),
	('Scott Burgess', 'England', 'burgess'),
	('Scott Burgess', 'England', 'scott burgess'),
	('Nico Rieble', 'Germany', 'rieble'),
	('Nico Rieble', 'Germany', 'nico rieble'),
	('Patrick Hobsch', 'Germany', 'hobsch'),
	('Patrick Hobsch', 'Germany', 'patrick hobsch'),
	('Francesco Lo Celso', 'Argentina', 'francesco lo celso'),
	('Francesco Lo Celso', 'Argentina', 'celso'),
	('Daniel Valdés', 'Venezuela', 'valdes'),
	('Daniel Valdés', 'Venezuela', 'daniel valdes'),
	('Willie Britto', 'Ivory Coast', 'willie britto'),
	('Willie Britto', 'Ivory Coast', 'britto'),
	('Miguel Morro', 'Spain', 'morro'),
	('Miguel Morro', 'Spain', 'miguel morro'),
	('Ronan Finn', 'Republic of Ireland', 'finn'),
	('Ronan Finn', 'Republic of Ireland', 'ronan finn'),
	('Filip Sachpekidis', 'Sweden', 'filip sachpekidis'),
	('Filip Sachpekidis', 'Sweden', 'sachpekidis'),
	('Ignacio Jáuregui', 'Argentina', 'jauregui'),
	('Ignacio Jáuregui', 'Argentina', 'ignacio jauregui'),
	('Andres Gudiño', 'Mexico', 'gudino'),
	('Andres Gudiño', 'Mexico', 'andres gudino'),
	('Ignacio Pereira', 'Uruguay', 'pereira'),
	('Ignacio Pereira', 'Uruguay', 'ignacio pereira'),
	('Eliot Matazo', 'Belgium', 'eliot matazo'),
	('Eliot Matazo', 'Belgium', 'matazo'),
	('Callum Gribbin', 'England', 'callum gribbin'),
	('Callum Gribbin', 'England', 'gribbin'),
	('Lukas Watkowiak', 'Germany', 'lukas watkowiak'),
	('Lukas Watkowiak', 'Germany', 'watkowiak'),
	('Nicky Cadden', 'Scotland', 'cadden'),
	('Nicky Cadden', 'Scotland', 'nicky cadden'),
	('Iago Indias', 'Spain', 'iago indias'),
	('Iago Indias', 'Spain', 'indias'),
	('Doru Popadiuc', 'Romania', 'popadiuc'),
	('Doru Popadiuc', 'Romania', 'doru popadiuc'),
	('Nick Shinton', 'Belgium', 'nick shinton'),
	('Nick Shinton', 'Belgium', 'shinton'),
	('Matheus Clemente', 'Portugal', 'clemente'),
	('Matheus Clemente', 'Portugal', 'matheus clemente'),
	('Adrián Goransch', 'Mexico', 'goransch'),
	('Adrián Goransch', 'Mexico', 'adrian goransch'),
	('Mike van Beijnen', 'Netherlands', 'beijnen'),
	('Mike van Beijnen', 'Netherlands', 'mike van beijnen'),
	('Soufian Benyamina', 'Germany', 'soufian benyamina'),
	('Soufian Benyamina', 'Germany', 'benyamina'),
	('Ahmed Al Kassar', 'Saudi Arabia', 'ahmed al kassar'),
	('Ahmed Al Kassar', 'Saudi Arabia', 'kassar'),
	('Kilian Jakob', 'Germany', 'jakob'),
	('Kilian Jakob', 'Germany', 'kilian jakob'),
	('Zoran Kvržić', 'Bosnia Herzegovina', 'zoran kvrzic'),
	('Zoran Kvržić', 'Bosnia Herzegovina', 'kvrzic'),
	('Josh Lillis', 'England', 'josh lillis'),
	('Josh Lillis', 'England', 'lillis'),
	('Sebas Moyano', 'Spain', 'sebas moyano'),
	('Sebas Moyano', 'Spain', 'moyano'),
	('Remeao Hutton', 'England', 'remeao hutton'),
	('Remeao Hutton', 'England', 'hutton'),
	('Izunna Uzochukwu', 'Nigeria', 'izunna uzochukwu'),
	('Izunna Uzochukwu', 'Nigeria', 'uzochukwu'),
	('Olaus Jair Skarsem', 'Norway', 'skarsem'),
	('Olaus Jair Skarsem', 'Norway', 'olaus jair skarsem'),
	('Gracjan Jaroch', 'Poland', 'gracjan jaroch'),
	('Gracjan Jaroch', 'Poland', 'jaroch'),
	('Jacob Shaffelburg', 'Canada', 'jacob shaffelburg'),
	('Jacob Shaffelburg', 'Canada', 'shaffelburg'),
	('Sivert Gussiås', 'Norway', 'gussias'),
	('Sivert Gussiås', 'Norway', 'sivert gussias'),
	('Miles Welch-Hayes', 'England', 'miles welchhayes'),
	('Miles Welch-Hayes', 'England', 'welchhayes'),
	('Fortuño', 'Spain', 'fortuno'),
	('Hou Yongyong', 'China PR', 'yongyong'),
	('Hou Yongyong', 'China PR', 'hou yongyong'),
	('Hamad Al Jayzani', 'Saudi Arabia', 'hamad al jayzani'),
	('Hamad Al Jayzani', 'Saudi Arabia', 'jayzani'),
	('Kevin Tshiembe', 'Denmark', 'tshiembe'),
	('Kevin Tshiembe', 'Denmark', 'kevin tshiembe'),
	('Romain Vincelot', 'France', 'romain vincelot'),
	('Romain Vincelot', 'France', 'vincelot'),
	('Ben Garratt', 'England', 'ben garratt'),
	('Ben Garratt', 'England', 'garratt'),
	('Sari Amro', 'Saudi Arabia', 'amro'),
	('Sari Amro', 'Saudi Arabia', 'sari amro'),
	('Gustav Marcussen', 'Denmark', 'marcussen'),
	('Gustav Marcussen', 'Denmark', 'gustav marcussen'),
	('Paolo Méndez', 'Peru', 'mendez'),
	('Paolo Méndez', 'Peru', 'paolo mendez'),
	('Victor Lobry', 'France', 'lobry'),
	('Victor Lobry', 'France', 'victor lobry'),
	('Shin Chang Moo', 'Korea Republic', 'shin chang moo'),
	('Shin Chang Moo', 'Korea Republic', 'moo'),
	('Timm Golley', 'Germany', 'timm golley'),
	('Timm Golley', 'Germany', 'golley'),
	('Yaki Yen', 'Chinese Taipei', 'yaki yen'),
	('Yaki Yen', 'Chinese Taipei', 'yen'),
	('Luis Ramírez', 'Venezuela', 'luis ramirez'),
	('Luis Ramírez', 'Venezuela', 'ramirez'),
	('Elsamed Ramaj', 'Albania', 'elsamed ramaj'),
	('Elsamed Ramaj', 'Albania', 'ramaj'),
	('Luís Santos', 'Portugal', 'santos'),
	('Luís Santos', 'Portugal', 'luis santos'),
	('Simon Thomas', 'Canada', 'thomas'),
	('Simon Thomas', 'Canada', 'simon thomas'),
	('Stuart Sinclair', 'England', 'sinclair'),
	('Stuart Sinclair', 'England', 'stuart sinclair'),
	('Erhan Mašović', 'Serbia', 'masovic'),
	('Erhan Mašović', 'Serbia', 'erhan masovic'),
	('Nair Tiknizyan', 'Russia', 'tiknizyan'),
	('Nair Tiknizyan', 'Russia', 'nair tiknizyan'),
	('Luis Arce', 'Ecuador', 'luis arce'),
	('Luis Arce', 'Ecuador', 'arce'),
	('Ali Koiki', 'England', 'ali koiki'),
	('Ali Koiki', 'England', 'koiki'),
	('Emmanuel Banda', 'Zambia', 'emmanuel banda'),
	('Emmanuel Banda', 'Zambia', 'banda'),
	('Abdallahi Mahmoud', 'Mauritania', 'abdallahi mahmoud'),
	('Abdallahi Mahmoud', 'Mauritania', 'mahmoud'),
	('Nicky Ajose', 'England', 'ajose'),
	('Nicky Ajose', 'England', 'nicky ajose'),
	('Jorge Ortiz', 'Argentina', 'jorge ortiz'),
	('Jorge Ortiz', 'Argentina', 'ortiz'),
	('Parfait Bizoza', 'Burundi', 'parfait bizoza'),
	('Parfait Bizoza', 'Burundi', 'bizoza'),
	('Jesús Rivas', 'Mexico', 'rivas'),
	('Jesús Rivas', 'Mexico', 'jesus rivas'),
	('Darío Poveda', 'Spain', 'poveda'),
	('Darío Poveda', 'Spain', 'dario poveda'),
	('George Marsh', 'England', 'marsh'),
	('George Marsh', 'England', 'george marsh'),
	('Luis Binks', 'England', 'binks'),
	('Luis Binks', 'England', 'luis binks'),
	('Gustavo Olguín', 'Bolivia', 'gustavo olguin'),
	('Gustavo Olguín', 'Bolivia', 'olguin'),
	('Lü Haidong', 'China PR', 'lu haidong'),
	('Lü Haidong', 'China PR', 'haidong'),
	('Konstantin Maradishvili', 'Russia', 'maradishvili'),
	('Konstantin Maradishvili', 'Russia', 'konstantin maradishvili'),
	('Conor McAleny', 'England', 'conor mcaleny'),
	('Conor McAleny', 'England', 'mcaleny'),
	('Shi Zhe', 'China PR', 'zhe'),
	('Shi Zhe', 'China PR', 'shi zhe'),
	('William Bianda', 'France', 'william bianda'),
	('William Bianda', 'France', 'bianda'),
	('Juan Lara', 'Ecuador', 'lara'),
	('Juan Lara', 'Ecuador', 'juan lara'),
	('Aaron Greene', 'Republic of Ireland', 'greene'),
	('Aaron Greene', 'Republic of Ireland', 'aaron greene'),
	('Jacob Buus', 'Denmark', 'buus'),
	('Jacob Buus', 'Denmark', 'jacob buus'),
	('Luo Jing', 'China PR', 'jing'),
	('Luo Jing', 'China PR', 'luo jing'),
	('Noah Fadiga', 'Belgium', 'noah fadiga'),
	('Noah Fadiga', 'Belgium', 'fadiga'),
	('Alexis Guendouz', 'France', 'guendouz'),
	('Alexis Guendouz', 'France', 'alexis guendouz'),
	('Shaquill Sno', 'Netherlands', 'shaquill sno'),
	('Shaquill Sno', 'Netherlands', 'sno'),
	('Armando Escobar', 'Mexico', 'escobar'),
	('Armando Escobar', 'Mexico', 'armando escobar'),
	('Jack Rose', 'England', 'rose'),
	('Jack Rose', 'England', 'jack rose'),
	('Josh Gordon', 'England', 'gordon'),
	('Josh Gordon', 'England', 'josh gordon'),
	('Turki Al Ammar', 'Saudi Arabia', 'turki al ammar'),
	('Turki Al Ammar', 'Saudi Arabia', 'ammar'),
	('Keith Watson', 'Scotland', 'keith watson'),
	('Keith Watson', 'Scotland', 'watson'),
	('Elias Ramírez', 'Spain', 'elias ramirez'),
	('Elias Ramírez', 'Spain', 'ramirez'),
	('Alin Dobrosavlevici', 'Romania', 'alin dobrosavlevici'),
	('Alin Dobrosavlevici', 'Romania', 'dobrosavlevici'),
	('Roque Caballero', 'Paraguay', 'roque caballero'),
	('Roque Caballero', 'Paraguay', 'caballero'),
	('Facundo Silvera', 'Uruguay', 'facundo silvera'),
	('Facundo Silvera', 'Uruguay', 'silvera'),
	('Aramide Oteh', 'England', 'aramide oteh'),
	('Aramide Oteh', 'England', 'oteh'),
	('Lino Kasten', 'Germany', 'lino kasten'),
	('Lino Kasten', 'Germany', 'kasten'),
	('Toumani Diagouraga', 'France', 'diagouraga'),
	('Toumani Diagouraga', 'France', 'toumani diagouraga'),
	('Reuben Reid', 'England', 'reuben reid'),
	('Reuben Reid', 'England', 'reid'),
	('Kristian Dennis', 'England', 'dennis'),
	('Kristian Dennis', 'England', 'kristian dennis'),
	('Erwin Koffi', 'Ivory Coast', 'koffi'),
	('Erwin Koffi', 'Ivory Coast', 'erwin koffi'),
	('Christoph Daferner', 'Germany', 'daferner'),
	('Christoph Daferner', 'Germany', 'christoph daferner'),
	('Harry Lennon', 'England', 'lennon'),
	('Harry Lennon', 'England', 'harry lennon'),
	('Kwadwo Duah', 'Switzerland', 'kwadwo duah'),
	('Kwadwo Duah', 'Switzerland', 'duah'),
	('Ibra Pérez', 'Spain', 'perez'),
	('Ibra Pérez', 'Spain', 'ibra perez'),
	('Marcos Lavín', 'Spain', 'lavin'),
	('Marcos Lavín', 'Spain', 'marcos lavin'),
	('Luis Nery Caballero', 'Paraguay', 'luis nery caballero'),
	('Luis Nery Caballero', 'Paraguay', 'caballero'),
	('Daniele Sommariva', 'Italy', 'sommariva'),
	('Daniele Sommariva', 'Italy', 'daniele sommariva'),
	('José Amo', 'Spain', 'amo'),
	('José Amo', 'Spain', 'jose amo'),
	('Yosuke Akiyama', 'Japan', 'akiyama'),
	('Yosuke Akiyama', 'Japan', 'yosuke akiyama'),
	('Shao Puliang', 'China PR', 'puliang'),
	('Shao Puliang', 'China PR', 'shao puliang'),
	('Kim Ji Hyun', 'Korea Republic', 'hyun'),
	('Kim Ji Hyun', 'Korea Republic', 'kim ji hyun'),
	('Nassim Ouammou', 'France', 'ouammou'),
	('Nassim Ouammou', 'France', 'nassim ouammou'),
	('Nico Klaß', 'Germany', 'kla'),
	('Nico Klaß', 'Germany', 'nico kla'),
	('Nicolae Mușat', 'Romania', 'nicolae musat'),
	('Nicolae Mușat', 'Romania', 'musat'),
	('Selim Gündüz', 'Germany', 'selim gunduz'),
	('Selim Gündüz', 'Germany', 'gunduz'),
	('Vegard Moberg', 'Norway', 'moberg'),
	('Vegard Moberg', 'Norway', 'vegard moberg'),
	('Abdulkarim Al Qahtani', 'Saudi Arabia', 'qahtani'),
	('Abdulkarim Al Qahtani', 'Saudi Arabia', 'abdulkarim al qahtani'),
	('Álex Pachón', 'Spain', 'pachon'),
	('Álex Pachón', 'Spain', 'alex pachon'),
	('Milan Gajić', 'Serbia', 'gajic'),
	('Milan Gajić', 'Serbia', 'milan gajic'),
	('Isidro Pitta', 'Paraguay', 'isidro pitta'),
	('Isidro Pitta', 'Paraguay', 'pitta'),
	('Lukas Malicsek', 'Austria', 'malicsek'),
	('Lukas Malicsek', 'Austria', 'lukas malicsek'),
	('Happy Mashiane', 'South Africa', 'happy mashiane'),
	('Happy Mashiane', 'South Africa', 'mashiane'),
	('Nicolás Royón', 'Uruguay', 'royon'),
	('Nicolás Royón', 'Uruguay', 'nicolas royon'),
	('Othoniel Arce', 'Mexico', 'othoniel arce'),
	('Othoniel Arce', 'Mexico', 'arce'),
	('Mateusz Żyro', 'Poland', 'mateusz zyro'),
	('Mateusz Żyro', 'Poland', 'zyro'),
	('Jan-Marc Schneider', 'Germany', 'janmarc schneider'),
	('Jan-Marc Schneider', 'Germany', 'schneider'),
	('Lewis Smith', 'Scotland', 'smith'),
	('Lewis Smith', 'Scotland', 'lewis smith'),
	('Gonçalo Inácio', 'Portugal', 'inacio'),
	('Gonçalo Inácio', 'Portugal', 'goncalo inacio'),
	('Hjalmar Ekdal', 'Sweden', 'ekdal'),
	('Hjalmar Ekdal', 'Sweden', 'hjalmar ekdal'),
	('Shun Yoshida', 'Japan', 'yoshida'),
	('Shun Yoshida', 'Japan', 'shun yoshida'),
	('Luke Gambin', 'Malta', 'luke gambin'),
	('Luke Gambin', 'Malta', 'gambin'),
	('Michał Jakóbowski', 'Poland', 'micha jakobowski'),
	('Michał Jakóbowski', 'Poland', 'jakobowski'),
	('Nicolás Giraldo', 'Colombia', 'nicolas giraldo'),
	('Nicolás Giraldo', 'Colombia', 'giraldo'),
	('Aleksa Terzić', 'Serbia', 'aleksa terzic'),
	('Aleksa Terzić', 'Serbia', 'terzic'),
	('Juan Pablo Rioja', 'Bolivia', 'juan pablo rioja'),
	('Juan Pablo Rioja', 'Bolivia', 'rioja'),
	('Benny Díaz', 'United States', 'benny diaz'),
	('Benny Díaz', 'United States', 'diaz'),
	('Nicholas D''Agostino', 'Australia', 'dagostino'),
	('Nicholas D''Agostino', 'Australia', 'nicholas dagostino'),
	('Dan Casey', 'Republic of Ireland', 'casey'),
	('Dan Casey', 'Republic of Ireland', 'dan casey'),
	('Raffael Behounek', 'Austria', 'behounek'),
	('Raffael Behounek', 'Austria', 'raffael behounek'),
	('Júnior Brumado', 'Brazil', 'brumado'),
	('Júnior Brumado', 'Brazil', 'junior brumado'),
	('Diego Živulić', 'Croatia', 'diego zivulic'),
	('Diego Živulić', 'Croatia', 'zivulic'),
	('Darragh Leahy', 'Republic of Ireland', 'leahy'),
	('Darragh Leahy', 'Republic of Ireland', 'darragh leahy'),
	('Jonathan Suárez', 'United States', 'suarez'),
	('Jonathan Suárez', 'United States', 'jonathan suarez'),
	('Elliott Whitehouse', 'England', 'whitehouse'),
	('Elliott Whitehouse', 'England', 'elliott whitehouse'),
	('Bai Yuefeng', 'China PR', 'yuefeng'),
	('Bai Yuefeng', 'China PR', 'bai yuefeng'),
	('Kim Sang Won', 'Korea Republic', 'kim sang won'),
	('Kim Sang Won', 'Korea Republic', 'won'),
	('Dennis Corozo', 'Ecuador', 'corozo'),
	('Dennis Corozo', 'Ecuador', 'dennis corozo'),
	('Thomas Keller', 'Germany', 'thomas keller'),
	('Thomas Keller', 'Germany', 'keller'),
	('Mathias Bringaker', 'Norway', 'mathias bringaker'),
	('Mathias Bringaker', 'Norway', 'bringaker'),
	('Carlos Torres', 'Venezuela', 'torres'),
	('Carlos Torres', 'Venezuela', 'carlos torres'),
	('Diego Duarte', 'Paraguay', 'diego duarte'),
	('Diego Duarte', 'Paraguay', 'duarte'),
	('Sam Foley', 'Republic of Ireland', 'sam foley'),
	('Sam Foley', 'Republic of Ireland', 'foley'),
	('Rolando Ortíz', 'Paraguay', 'rolando ortiz'),
	('Rolando Ortíz', 'Paraguay', 'ortiz'),
	('Tomás Castro', 'Portugal', 'castro'),
	('Tomás Castro', 'Portugal', 'tomas castro'),
	('Luis Ortíz', 'Paraguay', 'ortiz'),
	('Luis Ortíz', 'Paraguay', 'luis ortiz'),
	('Alex Kenyon', 'England', 'alex kenyon'),
	('Alex Kenyon', 'England', 'kenyon'),
	('Mario', 'Spain', 'mario'),
	('Ivan Vujica', 'Australia', 'vujica'),
	('Ivan Vujica', 'Australia', 'ivan vujica'),
	('Martin Samuelsen', 'Norway', 'samuelsen'),
	('Martin Samuelsen', 'Norway', 'martin samuelsen'),
	('Samúel Kári Friðjónsson', 'Iceland', 'samuel kari frijonsson'),
	('Samúel Kári Friðjónsson', 'Iceland', 'frijonsson'),
	('Pontus Almqvist', 'Sweden', 'almqvist'),
	('Pontus Almqvist', 'Sweden', 'pontus almqvist'),
	('Ben Jackson', 'England', 'jackson'),
	('Ben Jackson', 'England', 'ben jackson'),
	('Vlad Morar', 'Romania', 'vlad morar'),
	('Vlad Morar', 'Romania', 'morar'),
	('Juan Mosquera', 'Colombia', 'juan mosquera'),
	('Juan Mosquera', 'Colombia', 'mosquera'),
	('Panagiotis Deligiannidis', 'Greece', 'deligiannidis'),
	('Panagiotis Deligiannidis', 'Greece', 'panagiotis deligiannidis'),
	('Odysseus Velanas', 'Netherlands', 'odysseus velanas'),
	('Odysseus Velanas', 'Netherlands', 'velanas'),
	('Mun Kyung Gun', 'Korea Republic', 'gun'),
	('Mun Kyung Gun', 'Korea Republic', 'mun kyung gun'),
	('Anthony Landázuri', 'Ecuador', 'anthony landazuri'),
	('Anthony Landázuri', 'Ecuador', 'landazuri'),
	('Rune Frantsen', 'Denmark', 'rune frantsen'),
	('Rune Frantsen', 'Denmark', 'frantsen'),
	('Simone Bastoni', 'Italy', 'bastoni'),
	('Simone Bastoni', 'Italy', 'simone bastoni'),
	('Matty Virtue', 'England', 'matty virtue'),
	('Matty Virtue', 'England', 'virtue'),
	('Lukáš Hroššo', 'Slovakia', 'lukas hrosso'),
	('Lukáš Hroššo', 'Slovakia', 'hrosso'),
	('Jung Hoon Sung', 'Korea Republic', 'jung hoon sung'),
	('Jung Hoon Sung', 'Korea Republic', 'sung'),
	('Vadim Rață', 'Moldova', 'vadim rata'),
	('Vadim Rață', 'Moldova', 'rata'),
	('Jacson Pita', 'Ecuador', 'jacson pita'),
	('Jacson Pita', 'Ecuador', 'pita')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';