INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Max Melbourne', 'England', 'player'),
	('Ross Doohan', 'Scotland', 'player'),
	('Issa Fomba', 'Mali', 'player'),
	('Moreno', 'Spain', 'player'),
	('Jesper Gustavsson', 'Sweden', 'player'),
	('Nicolás Cordero', 'Argentina', 'player'),
	('Ahmed Awad', 'Palestine', 'player'),
	('Kota Miyamoto', 'Japan', 'player'),
	('Carljohan Eriksson', 'Finland', 'player'),
	('Junior Morias', 'Jamaica', 'player'),
	('Matt Simon', 'Australia', 'player'),
	('Aidi Fulangxisi', 'China PR', 'player'),
	('Rúben Fonseca', 'Portugal', 'player'),
	('Shinta Appelkamp', 'Japan', 'player'),
	('Barne Pernot', 'Germany', 'player'),
	('Matías Romero', 'Argentina', 'player'),
	('Qi Tianyu', 'China PR', 'player'),
	('Mads Bech Sørensen', 'Denmark', 'player'),
	('Yonathan Samaniego', 'Paraguay', 'player'),
	('Sami Al Najai', 'Saudi Arabia', 'player'),
	('Vadaine Oliver', 'England', 'player'),
	('Dominic Thompson', 'England', 'player'),
	('Matthew Acton', 'Australia', 'player'),
	('Rodrigo Zalazar', 'Uruguay', 'player'),
	('Richard Rentería', 'Colombia', 'player'),
	('Chris Kane', 'Scotland', 'player'),
	('Markus Pettersen', 'Norway', 'player'),
	('Stephan Drăghici', 'Romania', 'player'),
	('James Brown', 'England', 'player'),
	('Martell Taylor-Crossdale', 'England', 'player'),
	('Abdulbasit Hindi', 'Saudi Arabia', 'player'),
	('Yannick Osée', 'Germany', 'player'),
	('Cao Xuan', 'China PR', 'player'),
	('Luke Jephcott', 'Wales', 'player'),
	('Harry Davis', 'England', 'player'),
	('Steeven Saba', 'Haiti', 'player'),
	('Fran Castillo', 'Spain', 'player'),
	('Cristian Castro', 'Colombia', 'player'),
	('Sveinn Aron Guðjohnsen', 'Iceland', 'player'),
	('Ricardo Garay', 'Paraguay', 'player'),
	('Wildo Alonso', 'Paraguay', 'player'),
	('Tiago Morais', 'Portugal', 'player'),
	('Leandro Contin', 'Argentina', 'player'),
	('Néstor Giménez', 'Paraguay', 'player'),
	('Aaron Amadi-Holloway', 'Wales', 'player'),
	('Benny Ashley-Seal', 'England', 'player'),
	('Niklas Tarnat', 'Germany', 'player'),
	('Conor McCormack', 'Republic of Ireland', 'player'),
	('Max Thompson', 'England', 'player'),
	('Daan Klinkenberg', 'Netherlands', 'player'),
	('Yazeed Al Bakr', 'Saudi Arabia', 'player'),
	('Joseph Mendes', 'Guinea Bissau', 'player'),
	('Pedro Gutiérrez', 'Peru', 'player'),
	('Sebastián Ramírez', 'Argentina', 'player'),
	('Abdulaziz Al Sharid', 'Saudi Arabia', 'player'),
	('Barbero', 'Spain', 'player'),
	('Nahuel Arroyo', 'Spain', 'player'),
	('Erik Brenden', 'Norway', 'player'),
	('Lewis Price', 'Wales', 'player'),
	('Florian Palmowski', 'Germany', 'player'),
	('Morgan Guilavogui', 'France', 'player'),
	('Raphael Sallinger', 'Austria', 'player'),
	('Shaquil Delos', 'France', 'player'),
	('Jamal Amofa', 'Netherlands', 'player'),
	('Jay Lynch', 'England', 'player'),
	('Carlo Lattanzio', 'Argentina', 'player'),
	('Adrian Scarlatache', 'Romania', 'player'),
	('Carlos Jimémez', 'Peru', 'player'),
	('Leon Schneider', 'Germany', 'player'),
	('Oliver Lancashire', 'England', 'player'),
	('Shan Pengfei', 'China PR', 'player'),
	('Carreira', 'Spain', 'player'),
	('Babacar Dione', 'Belgium', 'player'),
	('Cássio Scheid', 'Brazil', 'player'),
	('Gianni Stensness', 'New Zealand', 'player'),
	('Diogo Silva', 'Brazil', 'player'),
	('Josué Albert', 'France', 'player'),
	('Leandro Vella', 'Argentina', 'player'),
	('Adrián Vargas', 'Paraguay', 'player'),
	('Gerardo Ruíz', 'Mexico', 'player'),
	('Anouar Ait El Hadj', 'Belgium', 'player'),
	('Douglas Oliveira', 'Brazil', 'player'),
	('Jojo Wollacott', 'England', 'player'),
	('Romeri Villamizar', 'Venezuela', 'player'),
	('Hubert Adamczyk', 'Poland', 'player'),
	('Wojciech Szumilas', 'Poland', 'player'),
	('Gustaf Norlin', 'Sweden', 'player'),
	('Sergiu Ciocan', 'Romania', 'player'),
	('Luis Fernando Fernández', 'Colombia', 'player'),
	('Yusuf Abdioğlu', 'Turkey', 'player'),
	('Otis Khan', 'England', 'player'),
	('Jayson Papeau', 'France', 'player'),
	('Dominik Kother', 'Germany', 'player'),
	('Claudio Nuñez', 'Paraguay', 'player'),
	('Samuele Damiani', 'Italy', 'player'),
	('Ronal Huaccha', 'Peru', 'player'),
	('Bülent Cevahir', 'Turkey', 'player'),
	('Gibson Fuentes', 'Peru', 'player'),
	('Caballero', 'Spain', 'player'),
	('Nacho Ramón', 'Spain', 'player'),
	('Luke Matheson', 'England', 'player'),
	('Michał Skóraś', 'Poland', 'player'),
	('Gbenga Arokoyo', 'Nigeria', 'player'),
	('Vamouti Diomande', 'Ivory Coast', 'player'),
	('Pablo Magnín', 'Argentina', 'player'),
	('Hugo Ángeles', 'Peru', 'player'),
	('Pau Resta', 'Spain', 'player'),
	('Vincenzo Millico', 'Italy', 'player'),
	('Fernando Arismendi', 'Uruguay', 'player'),
	('Jesús Ramírez', 'Venezuela', 'player'),
	('Salem Abdullah', 'United Arab Emirates', 'player'),
	('Álvaro Preciado', 'Ecuador', 'player'),
	('Roman Macek', 'Czech Republic', 'player'),
	('Hans Anapak', 'Germany', 'player'),
	('Wojciech Lisowski', 'Poland', 'player'),
	('Jasper Dahlhaus', 'Netherlands', 'player'),
	('Nelson Insfrán', 'Argentina', 'player'),
	('Ugo Bertelli', 'France', 'player'),
	('Ethan Ross', 'England', 'player'),
	('Erick Sánchez', 'Mexico', 'player'),
	('Nasser Al Dawsari', 'Saudi Arabia', 'player'),
	('Soberón', 'Spain', 'player'),
	('Marin Šverko', 'Croatia', 'player'),
	('Lachlan Wales', 'Australia', 'player'),
	('Alessandro Tripaldelli', 'Italy', 'player'),
	('Recep Kutun', 'Turkey', 'player'),
	('Óskar Sverrisson', 'Iceland', 'player'),
	('Vasilios Xenopoulos', 'Greece', 'player'),
	('Thomas Poll', 'Netherlands', 'player'),
	('Hugo Magnetti', 'France', 'player'),
	('Jean Carlos Montaño', 'Ecuador', 'player'),
	('Nicholas Taitague', 'United States', 'player'),
	('Brad Walker', 'England', 'player'),
	('Marijan Ćavar', 'Bosnia Herzegovina', 'player'),
	('JT Marcinkowski', 'United States', 'player'),
	('Franco Godoy', 'Argentina', 'player'),
	('Sorin Bustea', 'Romania', 'player'),
	('Nikita Iosifov', 'Russia', 'player'),
	('Omar Panuco', 'Mexico', 'player'),
	('Yannick Langesberg', 'Germany', 'player'),
	('Abdullah Kanno', 'Saudi Arabia', 'player'),
	('Erik Majetschak', 'Germany', 'player'),
	('Elías Meza', 'Paraguay', 'player'),
	('John McAtee', 'England', 'player'),
	('Lukas Krüger', 'Germany', 'player'),
	('Tom Krauß', 'Germany', 'player'),
	('Maikel Chang', 'Cuba', 'player'),
	('Sergio Quintero', 'Ecuador', 'player'),
	('Nya Kirby', 'England', 'player'),
	('Ariel Shuartzman', 'Paraguay', 'player'),
	('Greg Sloggett', 'Republic of Ireland', 'player'),
	('Kian Slor', 'Netherlands', 'player'),
	('Takumi Sasaki', 'Japan', 'player'),
	('Ismaël Boura', 'France', 'player'),
	('Stephen McGuinness', 'Republic of Ireland', 'player'),
	('Viktor Noring', 'Sweden', 'player'),
	('Tomás Badaloni', 'Argentina', 'player'),
	('Ståle Stålinho Sæthre', 'Norway', 'player'),
	('Augusto Schott', 'Argentina', 'player'),
	('Mahamé Siby', 'France', 'player'),
	('Adrian Melksham', 'Australia', 'player'),
	('Pei Shuai', 'China PR', 'player'),
	('Maurice Čović', 'Germany', 'player'),
	('Simon Janssen', 'Netherlands', 'player'),
	('Sabit Abdulai', 'Ghana', 'player'),
	('Matías Belloso', 'Argentina', 'player'),
	('Matt Jay', 'England', 'player'),
	('Almerge', 'Spain', 'player'),
	('Felix Schwarzholz', 'Germany', 'player'),
	('Jannik Rochelt', 'Germany', 'player'),
	('Ellery Balcombe', 'England', 'player'),
	('Hiroto Yamada', 'Japan', 'player'),
	('Daniel Parra', 'Mexico', 'player'),
	('Kevin Mouanga', 'France', 'player'),
	('Bryan Limbombe', 'Belgium', 'player'),
	('Erik Botheim', 'Norway', 'player'),
	('Fraser Horsfall', 'England', 'player'),
	('Miguel Vargas', 'Chile', 'player'),
	('Thibaut Vargas', 'France', 'player'),
	('Ben Warland', 'Australia', 'player'),
	('Iván Martínez', 'Spain', 'player'),
	('Víctor Centurión', 'Paraguay', 'player'),
	('Tomás Diáz', 'Argentina', 'player'),
	('Abdulaziz Majrashi', 'Saudi Arabia', 'player'),
	('Agustín Álvarez Martínez', 'Uruguay', 'player'),
	('Maksymilian Stryjek', 'Poland', 'player'),
	('Aaron Morley', 'England', 'player'),
	('Tobias Kraulich', 'Germany', 'player'),
	('Kacper Michalski', 'Poland', 'player'),
	('Amund Wichne', 'Norway', 'player'),
	('Paulo Estrela', 'Portugal', 'player'),
	('Mohammed Khalfan', 'United Arab Emirates', 'player'),
	('Paddy Kirk', 'Republic of Ireland', 'player'),
	('Adam Crookes', 'England', 'player'),
	('Charlie Trafford', 'Canada', 'player'),
	('Andy Fisher', 'England', 'player'),
	('Brian Murphy', 'Republic of Ireland', 'player'),
	('Brian Farioli', 'Argentina', 'player'),
	('York Rafael', 'Sweden', 'player'),
	('Fernando Tapia', 'Mexico', 'player'),
	('Marlon Suliman Mustapha', 'Austria', 'player'),
	('Pius Krätschmer', 'Germany', 'player'),
	('Hou Sen', 'China PR', 'player'),
	('De La Mata', 'Spain', 'player'),
	('Shaun McWilliams', 'England', 'player'),
	('Ethan Robson', 'England', 'player'),
	('Maciej Rosołek', 'Poland', 'player'),
	('Robin Tihi', 'Finland', 'player'),
	('Amir Bilali', 'Albania', 'player'),
	('Ishaq Abdulrazak', 'Nigeria', 'player'),
	('Danny Rogers', 'Republic of Ireland', 'player'),
	('Tarek Elrich', 'Australia', 'player'),
	('Johan Brattberg', 'Sweden', 'player'),
	('Joe Powell', 'England', 'player'),
	('Shilow Tracey', 'England', 'player'),
	('Azón', 'Spain', 'player'),
	('João Monteiro', 'Portugal', 'player'),
	('Alessandro Confente', 'Italy', 'player'),
	('Raúl Sandoval', 'Mexico', 'player'),
	('Theo Bair', 'Canada', 'player'),
	('Emiliano González', 'Argentina', 'player'),
	('Fabian Greilinger', 'Germany', 'player'),
	('Jesús Vargas', 'Venezuela', 'player'),
	('Maxence Rivera', 'France', 'player'),
	('José Muñóz', 'Bolivia', 'player'),
	('Benjamín Galindo', 'Mexico', 'player'),
	('Adam Lewis', 'England', 'player'),
	('Jabor Issa', 'Saudi Arabia', 'player'),
	('Tom Grivosti', 'England', 'player'),
	('Takumi Nakamura', 'Japan', 'player'),
	('Jasser Khmiri', 'Tunisia', 'player'),
	('Agim Zeka', 'Albania', 'player'),
	('Eduardo Del Ángel', 'Mexico', 'player'),
	('Arne Ammerer', 'Austria', 'player'),
	('João Neto', 'Brazil', 'player'),
	('Romaric Yapi', 'France', 'player'),
	('Nelson Balongo', 'DR Congo', 'player'),
	('Gonçalo Franco', 'Portugal', 'player'),
	('Roli Pereira de Sa', 'France', 'player'),
	('Alfie Monksfield', 'Australia', 'player'),
	('Jesse Zamudio', 'Mexico', 'player'),
	('Jamie Mascoll', 'England', 'player'),
	('Jan Žambůrek', 'Czech Republic', 'player'),
	('Zabarte', 'Spain', 'player'),
	('Kyle Taylor', 'England', 'player'),
	('Ransford-Yeboah Königsdörffer', 'Germany', 'player'),
	('Han Xuan', 'China PR', 'player'),
	('Siriné Doucouré', 'France', 'player'),
	('Abdulmohsen Fallatah', 'Saudi Arabia', 'player'),
	('Kenshin Yoshimaru', 'Japan', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Max Melbourne', 'England', 'max melbourne'),
	('Max Melbourne', 'England', 'melbourne'),
	('Ross Doohan', 'Scotland', 'ross doohan'),
	('Ross Doohan', 'Scotland', 'doohan'),
	('Issa Fomba', 'Mali', 'fomba'),
	('Issa Fomba', 'Mali', 'issa fomba'),
	('Moreno', 'Spain', 'moreno'),
	('Jesper Gustavsson', 'Sweden', 'gustavsson'),
	('Jesper Gustavsson', 'Sweden', 'jesper gustavsson'),
	('Nicolás Cordero', 'Argentina', 'nicolas cordero'),
	('Nicolás Cordero', 'Argentina', 'cordero'),
	('Ahmed Awad', 'Palestine', 'ahmed awad'),
	('Ahmed Awad', 'Palestine', 'awad'),
	('Kota Miyamoto', 'Japan', 'miyamoto'),
	('Kota Miyamoto', 'Japan', 'kota miyamoto'),
	('Carljohan Eriksson', 'Finland', 'eriksson'),
	('Carljohan Eriksson', 'Finland', 'carljohan eriksson'),
	('Junior Morias', 'Jamaica', 'morias'),
	('Junior Morias', 'Jamaica', 'junior morias'),
	('Matt Simon', 'Australia', 'matt simon'),
	('Matt Simon', 'Australia', 'simon'),
	('Aidi Fulangxisi', 'China PR', 'fulangxisi'),
	('Aidi Fulangxisi', 'China PR', 'aidi fulangxisi'),
	('Rúben Fonseca', 'Portugal', 'fonseca'),
	('Rúben Fonseca', 'Portugal', 'ruben fonseca'),
	('Shinta Appelkamp', 'Japan', 'shinta appelkamp'),
	('Shinta Appelkamp', 'Japan', 'appelkamp'),
	('Barne Pernot', 'Germany', 'pernot'),
	('Barne Pernot', 'Germany', 'barne pernot'),
	('Matías Romero', 'Argentina', 'matias romero'),
	('Matías Romero', 'Argentina', 'romero'),
	('Qi Tianyu', 'China PR', 'qi tianyu'),
	('Qi Tianyu', 'China PR', 'tianyu'),
	('Mads Bech Sørensen', 'Denmark', 'srensen'),
	('Mads Bech Sørensen', 'Denmark', 'mads bech srensen'),
	('Yonathan Samaniego', 'Paraguay', 'samaniego'),
	('Yonathan Samaniego', 'Paraguay', 'yonathan samaniego'),
	('Sami Al Najai', 'Saudi Arabia', 'najai'),
	('Sami Al Najai', 'Saudi Arabia', 'sami al najai'),
	('Vadaine Oliver', 'England', 'vadaine oliver'),
	('Vadaine Oliver', 'England', 'oliver'),
	('Dominic Thompson', 'England', 'thompson'),
	('Dominic Thompson', 'England', 'dominic thompson'),
	('Matthew Acton', 'Australia', 'matthew acton'),
	('Matthew Acton', 'Australia', 'acton'),
	('Rodrigo Zalazar', 'Uruguay', 'rodrigo zalazar'),
	('Rodrigo Zalazar', 'Uruguay', 'zalazar'),
	('Richard Rentería', 'Colombia', 'renteria'),
	('Richard Rentería', 'Colombia', 'richard renteria'),
	('Chris Kane', 'Scotland', 'kane'),
	('Chris Kane', 'Scotland', 'chris kane'),
	('Markus Pettersen', 'Norway', 'markus pettersen'),
	('Markus Pettersen', 'Norway', 'pettersen'),
	('Stephan Drăghici', 'Romania', 'stephan draghici'),
	('Stephan Drăghici', 'Romania', 'draghici'),
	('James Brown', 'England', 'brown'),
	('James Brown', 'England', 'james brown'),
	('Martell Taylor-Crossdale', 'England', 'taylorcrossdale'),
	('Martell Taylor-Crossdale', 'England', 'martell taylorcrossdale'),
	('Abdulbasit Hindi', 'Saudi Arabia', 'abdulbasit hindi'),
	('Abdulbasit Hindi', 'Saudi Arabia', 'hindi'),
	('Yannick Osée', 'Germany', 'osee'),
	('Yannick Osée', 'Germany', 'yannick osee'),
	('Cao Xuan', 'China PR', 'xuan'),
	('Cao Xuan', 'China PR', 'cao xuan'),
	('Luke Jephcott', 'Wales', 'luke jephcott'),
	('Luke Jephcott', 'Wales', 'jephcott'),
	('Harry Davis', 'England', 'harry davis'),
	('Harry Davis', 'England', 'davis'),
	('Steeven Saba', 'Haiti', 'saba'),
	('Steeven Saba', 'Haiti', 'steeven saba'),
	('Fran Castillo', 'Spain', 'castillo'),
	('Fran Castillo', 'Spain', 'fran castillo'),
	('Cristian Castro', 'Colombia', 'castro'),
	('Cristian Castro', 'Colombia', 'cristian castro'),
	('Sveinn Aron Guðjohnsen', 'Iceland', 'gujohnsen'),
	('Sveinn Aron Guðjohnsen', 'Iceland', 'sveinn aron gujohnsen'),
	('Ricardo Garay', 'Paraguay', 'ricardo garay'),
	('Ricardo Garay', 'Paraguay', 'garay'),
	('Wildo Alonso', 'Paraguay', 'alonso'),
	('Wildo Alonso', 'Paraguay', 'wildo alonso'),
	('Tiago Morais', 'Portugal', 'morais'),
	('Tiago Morais', 'Portugal', 'tiago morais'),
	('Leandro Contin', 'Argentina', 'leandro contin'),
	('Leandro Contin', 'Argentina', 'contin'),
	('Néstor Giménez', 'Paraguay', 'gimenez'),
	('Néstor Giménez', 'Paraguay', 'nestor gimenez'),
	('Aaron Amadi-Holloway', 'Wales', 'aaron amadiholloway'),
	('Aaron Amadi-Holloway', 'Wales', 'amadiholloway'),
	('Benny Ashley-Seal', 'England', 'benny ashleyseal'),
	('Benny Ashley-Seal', 'England', 'ashleyseal'),
	('Niklas Tarnat', 'Germany', 'tarnat'),
	('Niklas Tarnat', 'Germany', 'niklas tarnat'),
	('Conor McCormack', 'Republic of Ireland', 'mccormack'),
	('Conor McCormack', 'Republic of Ireland', 'conor mccormack'),
	('Max Thompson', 'England', 'thompson'),
	('Max Thompson', 'England', 'max thompson'),
	('Daan Klinkenberg', 'Netherlands', 'daan klinkenberg'),
	('Daan Klinkenberg', 'Netherlands', 'klinkenberg'),
	('Yazeed Al Bakr', 'Saudi Arabia', 'bakr'),
	('Yazeed Al Bakr', 'Saudi Arabia', 'yazeed al bakr'),
	('Joseph Mendes', 'Guinea Bissau', 'joseph mendes'),
	('Joseph Mendes', 'Guinea Bissau', 'mendes'),
	('Pedro Gutiérrez', 'Peru', 'gutierrez'),
	('Pedro Gutiérrez', 'Peru', 'pedro gutierrez'),
	('Sebastián Ramírez', 'Argentina', 'sebastian ramirez'),
	('Sebastián Ramírez', 'Argentina', 'ramirez'),
	('Abdulaziz Al Sharid', 'Saudi Arabia', 'abdulaziz al sharid'),
	('Abdulaziz Al Sharid', 'Saudi Arabia', 'sharid'),
	('Barbero', 'Spain', 'barbero'),
	('Nahuel Arroyo', 'Spain', 'arroyo'),
	('Nahuel Arroyo', 'Spain', 'nahuel arroyo'),
	('Erik Brenden', 'Norway', 'erik brenden'),
	('Erik Brenden', 'Norway', 'brenden'),
	('Lewis Price', 'Wales', 'price'),
	('Lewis Price', 'Wales', 'lewis price'),
	('Florian Palmowski', 'Germany', 'florian palmowski'),
	('Florian Palmowski', 'Germany', 'palmowski'),
	('Morgan Guilavogui', 'France', 'guilavogui'),
	('Morgan Guilavogui', 'France', 'morgan guilavogui'),
	('Raphael Sallinger', 'Austria', 'raphael sallinger'),
	('Raphael Sallinger', 'Austria', 'sallinger'),
	('Shaquil Delos', 'France', 'delos'),
	('Shaquil Delos', 'France', 'shaquil delos'),
	('Jamal Amofa', 'Netherlands', 'jamal amofa'),
	('Jamal Amofa', 'Netherlands', 'amofa'),
	('Jay Lynch', 'England', 'lynch'),
	('Jay Lynch', 'England', 'jay lynch'),
	('Carlo Lattanzio', 'Argentina', 'carlo lattanzio'),
	('Carlo Lattanzio', 'Argentina', 'lattanzio'),
	('Adrian Scarlatache', 'Romania', 'scarlatache'),
	('Adrian Scarlatache', 'Romania', 'adrian scarlatache'),
	('Carlos Jimémez', 'Peru', 'jimemez'),
	('Carlos Jimémez', 'Peru', 'carlos jimemez'),
	('Leon Schneider', 'Germany', 'schneider'),
	('Leon Schneider', 'Germany', 'leon schneider'),
	('Oliver Lancashire', 'England', 'lancashire'),
	('Oliver Lancashire', 'England', 'oliver lancashire'),
	('Shan Pengfei', 'China PR', 'pengfei'),
	('Shan Pengfei', 'China PR', 'shan pengfei'),
	('Carreira', 'Spain', 'carreira'),
	('Babacar Dione', 'Belgium', 'babacar dione'),
	('Babacar Dione', 'Belgium', 'dione'),
	('Cássio Scheid', 'Brazil', 'cassio scheid'),
	('Cássio Scheid', 'Brazil', 'scheid'),
	('Gianni Stensness', 'New Zealand', 'gianni stensness'),
	('Gianni Stensness', 'New Zealand', 'stensness'),
	('Diogo Silva', 'Brazil', 'diogo silva'),
	('Diogo Silva', 'Brazil', 'silva'),
	('Josué Albert', 'France', 'josue albert'),
	('Josué Albert', 'France', 'albert'),
	('Leandro Vella', 'Argentina', 'vella'),
	('Leandro Vella', 'Argentina', 'leandro vella'),
	('Adrián Vargas', 'Paraguay', 'vargas'),
	('Adrián Vargas', 'Paraguay', 'adrian vargas'),
	('Gerardo Ruíz', 'Mexico', 'ruiz'),
	('Gerardo Ruíz', 'Mexico', 'gerardo ruiz'),
	('Anouar Ait El Hadj', 'Belgium', 'anouar ait el hadj'),
	('Anouar Ait El Hadj', 'Belgium', 'hadj'),
	('Douglas Oliveira', 'Brazil', 'oliveira'),
	('Douglas Oliveira', 'Brazil', 'douglas oliveira'),
	('Jojo Wollacott', 'England', 'jojo wollacott'),
	('Jojo Wollacott', 'England', 'wollacott'),
	('Romeri Villamizar', 'Venezuela', 'villamizar'),
	('Romeri Villamizar', 'Venezuela', 'romeri villamizar'),
	('Hubert Adamczyk', 'Poland', 'adamczyk'),
	('Hubert Adamczyk', 'Poland', 'hubert adamczyk'),
	('Wojciech Szumilas', 'Poland', 'szumilas'),
	('Wojciech Szumilas', 'Poland', 'wojciech szumilas'),
	('Gustaf Norlin', 'Sweden', 'norlin'),
	('Gustaf Norlin', 'Sweden', 'gustaf norlin'),
	('Sergiu Ciocan', 'Romania', 'ciocan'),
	('Sergiu Ciocan', 'Romania', 'sergiu ciocan'),
	('Luis Fernando Fernández', 'Colombia', 'fernandez'),
	('Luis Fernando Fernández', 'Colombia', 'luis fernando fernandez'),
	('Yusuf Abdioğlu', 'Turkey', 'yusuf abdioglu'),
	('Yusuf Abdioğlu', 'Turkey', 'abdioglu'),
	('Otis Khan', 'England', 'otis khan'),
	('Otis Khan', 'England', 'khan'),
	('Jayson Papeau', 'France', 'jayson papeau'),
	('Jayson Papeau', 'France', 'papeau'),
	('Dominik Kother', 'Germany', 'dominik kother'),
	('Dominik Kother', 'Germany', 'kother'),
	('Claudio Nuñez', 'Paraguay', 'nunez'),
	('Claudio Nuñez', 'Paraguay', 'claudio nunez'),
	('Samuele Damiani', 'Italy', 'samuele damiani'),
	('Samuele Damiani', 'Italy', 'damiani'),
	('Ronal Huaccha', 'Peru', 'ronal huaccha'),
	('Ronal Huaccha', 'Peru', 'huaccha'),
	('Bülent Cevahir', 'Turkey', 'bulent cevahir'),
	('Bülent Cevahir', 'Turkey', 'cevahir'),
	('Gibson Fuentes', 'Peru', 'fuentes'),
	('Gibson Fuentes', 'Peru', 'gibson fuentes'),
	('Caballero', 'Spain', 'caballero'),
	('Nacho Ramón', 'Spain', 'nacho ramon'),
	('Nacho Ramón', 'Spain', 'ramon'),
	('Luke Matheson', 'England', 'matheson'),
	('Luke Matheson', 'England', 'luke matheson'),
	('Michał Skóraś', 'Poland', 'skoras'),
	('Michał Skóraś', 'Poland', 'micha skoras'),
	('Gbenga Arokoyo', 'Nigeria', 'arokoyo'),
	('Gbenga Arokoyo', 'Nigeria', 'gbenga arokoyo'),
	('Vamouti Diomande', 'Ivory Coast', 'diomande'),
	('Vamouti Diomande', 'Ivory Coast', 'vamouti diomande'),
	('Pablo Magnín', 'Argentina', 'pablo magnin'),
	('Pablo Magnín', 'Argentina', 'magnin'),
	('Hugo Ángeles', 'Peru', 'angeles'),
	('Hugo Ángeles', 'Peru', 'hugo angeles'),
	('Pau Resta', 'Spain', 'resta'),
	('Pau Resta', 'Spain', 'pau resta'),
	('Vincenzo Millico', 'Italy', 'vincenzo millico'),
	('Vincenzo Millico', 'Italy', 'millico'),
	('Fernando Arismendi', 'Uruguay', 'arismendi'),
	('Fernando Arismendi', 'Uruguay', 'fernando arismendi'),
	('Jesús Ramírez', 'Venezuela', 'jesus ramirez'),
	('Jesús Ramírez', 'Venezuela', 'ramirez'),
	('Salem Abdullah', 'United Arab Emirates', 'abdullah'),
	('Salem Abdullah', 'United Arab Emirates', 'salem abdullah'),
	('Álvaro Preciado', 'Ecuador', 'alvaro preciado'),
	('Álvaro Preciado', 'Ecuador', 'preciado'),
	('Roman Macek', 'Czech Republic', 'roman macek'),
	('Roman Macek', 'Czech Republic', 'macek'),
	('Hans Anapak', 'Germany', 'hans anapak'),
	('Hans Anapak', 'Germany', 'anapak'),
	('Wojciech Lisowski', 'Poland', 'wojciech lisowski'),
	('Wojciech Lisowski', 'Poland', 'lisowski'),
	('Jasper Dahlhaus', 'Netherlands', 'jasper dahlhaus'),
	('Jasper Dahlhaus', 'Netherlands', 'dahlhaus'),
	('Nelson Insfrán', 'Argentina', 'insfran'),
	('Nelson Insfrán', 'Argentina', 'nelson insfran'),
	('Ugo Bertelli', 'France', 'bertelli'),
	('Ugo Bertelli', 'France', 'ugo bertelli'),
	('Ethan Ross', 'England', 'ross'),
	('Ethan Ross', 'England', 'ethan ross'),
	('Erick Sánchez', 'Mexico', 'sanchez'),
	('Erick Sánchez', 'Mexico', 'erick sanchez'),
	('Nasser Al Dawsari', 'Saudi Arabia', 'dawsari'),
	('Nasser Al Dawsari', 'Saudi Arabia', 'nasser al dawsari'),
	('Soberón', 'Spain', 'soberon'),
	('Marin Šverko', 'Croatia', 'sverko'),
	('Marin Šverko', 'Croatia', 'marin sverko'),
	('Lachlan Wales', 'Australia', 'wales'),
	('Lachlan Wales', 'Australia', 'lachlan wales'),
	('Alessandro Tripaldelli', 'Italy', 'tripaldelli'),
	('Alessandro Tripaldelli', 'Italy', 'alessandro tripaldelli'),
	('Recep Kutun', 'Turkey', 'kutun'),
	('Recep Kutun', 'Turkey', 'recep kutun'),
	('Óskar Sverrisson', 'Iceland', 'sverrisson'),
	('Óskar Sverrisson', 'Iceland', 'oskar sverrisson'),
	('Vasilios Xenopoulos', 'Greece', 'vasilios xenopoulos'),
	('Vasilios Xenopoulos', 'Greece', 'xenopoulos'),
	('Thomas Poll', 'Netherlands', 'poll'),
	('Thomas Poll', 'Netherlands', 'thomas poll'),
	('Hugo Magnetti', 'France', 'hugo magnetti'),
	('Hugo Magnetti', 'France', 'magnetti'),
	('Jean Carlos Montaño', 'Ecuador', 'jean carlos montano'),
	('Jean Carlos Montaño', 'Ecuador', 'montano'),
	('Nicholas Taitague', 'United States', 'nicholas taitague'),
	('Nicholas Taitague', 'United States', 'taitague'),
	('Brad Walker', 'England', 'brad walker'),
	('Brad Walker', 'England', 'walker'),
	('Marijan Ćavar', 'Bosnia Herzegovina', 'cavar'),
	('Marijan Ćavar', 'Bosnia Herzegovina', 'marijan cavar'),
	('JT Marcinkowski', 'United States', 'marcinkowski'),
	('JT Marcinkowski', 'United States', 'jt marcinkowski'),
	('Franco Godoy', 'Argentina', 'franco godoy'),
	('Franco Godoy', 'Argentina', 'godoy'),
	('Sorin Bustea', 'Romania', 'sorin bustea'),
	('Sorin Bustea', 'Romania', 'bustea'),
	('Nikita Iosifov', 'Russia', 'iosifov'),
	('Nikita Iosifov', 'Russia', 'nikita iosifov'),
	('Omar Panuco', 'Mexico', 'panuco'),
	('Omar Panuco', 'Mexico', 'omar panuco'),
	('Yannick Langesberg', 'Germany', 'yannick langesberg'),
	('Yannick Langesberg', 'Germany', 'langesberg'),
	('Abdullah Kanno', 'Saudi Arabia', 'kanno'),
	('Abdullah Kanno', 'Saudi Arabia', 'abdullah kanno'),
	('Erik Majetschak', 'Germany', 'majetschak'),
	('Erik Majetschak', 'Germany', 'erik majetschak'),
	('Elías Meza', 'Paraguay', 'elias meza'),
	('Elías Meza', 'Paraguay', 'meza'),
	('John McAtee', 'England', 'john mcatee'),
	('John McAtee', 'England', 'mcatee'),
	('Lukas Krüger', 'Germany', 'kruger'),
	('Lukas Krüger', 'Germany', 'lukas kruger'),
	('Tom Krauß', 'Germany', 'krau'),
	('Tom Krauß', 'Germany', 'tom krau'),
	('Maikel Chang', 'Cuba', 'chang'),
	('Maikel Chang', 'Cuba', 'maikel chang'),
	('Sergio Quintero', 'Ecuador', 'quintero'),
	('Sergio Quintero', 'Ecuador', 'sergio quintero'),
	('Nya Kirby', 'England', 'kirby'),
	('Nya Kirby', 'England', 'nya kirby'),
	('Ariel Shuartzman', 'Paraguay', 'ariel shuartzman'),
	('Ariel Shuartzman', 'Paraguay', 'shuartzman'),
	('Greg Sloggett', 'Republic of Ireland', 'greg sloggett'),
	('Greg Sloggett', 'Republic of Ireland', 'sloggett'),
	('Kian Slor', 'Netherlands', 'kian slor'),
	('Kian Slor', 'Netherlands', 'slor'),
	('Takumi Sasaki', 'Japan', 'sasaki'),
	('Takumi Sasaki', 'Japan', 'takumi sasaki'),
	('Ismaël Boura', 'France', 'boura'),
	('Ismaël Boura', 'France', 'ismael boura'),
	('Stephen McGuinness', 'Republic of Ireland', 'stephen mcguinness'),
	('Stephen McGuinness', 'Republic of Ireland', 'mcguinness'),
	('Viktor Noring', 'Sweden', 'viktor noring'),
	('Viktor Noring', 'Sweden', 'noring'),
	('Tomás Badaloni', 'Argentina', 'badaloni'),
	('Tomás Badaloni', 'Argentina', 'tomas badaloni'),
	('Ståle Stålinho Sæthre', 'Norway', 'sthre'),
	('Ståle Stålinho Sæthre', 'Norway', 'stale stalinho sthre'),
	('Augusto Schott', 'Argentina', 'schott'),
	('Augusto Schott', 'Argentina', 'augusto schott'),
	('Mahamé Siby', 'France', 'siby'),
	('Mahamé Siby', 'France', 'mahame siby'),
	('Adrian Melksham', 'Australia', 'melksham'),
	('Adrian Melksham', 'Australia', 'adrian melksham'),
	('Pei Shuai', 'China PR', 'pei shuai'),
	('Pei Shuai', 'China PR', 'shuai'),
	('Maurice Čović', 'Germany', 'maurice covic'),
	('Maurice Čović', 'Germany', 'covic'),
	('Simon Janssen', 'Netherlands', 'janssen'),
	('Simon Janssen', 'Netherlands', 'simon janssen'),
	('Sabit Abdulai', 'Ghana', 'abdulai'),
	('Sabit Abdulai', 'Ghana', 'sabit abdulai'),
	('Matías Belloso', 'Argentina', 'belloso'),
	('Matías Belloso', 'Argentina', 'matias belloso'),
	('Matt Jay', 'England', 'matt jay'),
	('Matt Jay', 'England', 'jay'),
	('Almerge', 'Spain', 'almerge'),
	('Felix Schwarzholz', 'Germany', 'felix schwarzholz'),
	('Felix Schwarzholz', 'Germany', 'schwarzholz'),
	('Jannik Rochelt', 'Germany', 'rochelt'),
	('Jannik Rochelt', 'Germany', 'jannik rochelt'),
	('Ellery Balcombe', 'England', 'balcombe'),
	('Ellery Balcombe', 'England', 'ellery balcombe'),
	('Hiroto Yamada', 'Japan', 'hiroto yamada'),
	('Hiroto Yamada', 'Japan', 'yamada'),
	('Daniel Parra', 'Mexico', 'daniel parra'),
	('Daniel Parra', 'Mexico', 'parra'),
	('Kevin Mouanga', 'France', 'mouanga'),
	('Kevin Mouanga', 'France', 'kevin mouanga'),
	('Bryan Limbombe', 'Belgium', 'limbombe'),
	('Bryan Limbombe', 'Belgium', 'bryan limbombe'),
	('Erik Botheim', 'Norway', 'erik botheim'),
	('Erik Botheim', 'Norway', 'botheim'),
	('Fraser Horsfall', 'England', 'fraser horsfall'),
	('Fraser Horsfall', 'England', 'horsfall'),
	('Miguel Vargas', 'Chile', 'vargas'),
	('Miguel Vargas', 'Chile', 'miguel vargas'),
	('Thibaut Vargas', 'France', 'vargas'),
	('Thibaut Vargas', 'France', 'thibaut vargas'),
	('Ben Warland', 'Australia', 'warland'),
	('Ben Warland', 'Australia', 'ben warland'),
	('Iván Martínez', 'Spain', 'martinez'),
	('Iván Martínez', 'Spain', 'ivan martinez'),
	('Víctor Centurión', 'Paraguay', 'centurion'),
	('Víctor Centurión', 'Paraguay', 'victor centurion'),
	('Tomás Diáz', 'Argentina', 'tomas diaz'),
	('Tomás Diáz', 'Argentina', 'diaz'),
	('Abdulaziz Majrashi', 'Saudi Arabia', 'abdulaziz majrashi'),
	('Abdulaziz Majrashi', 'Saudi Arabia', 'majrashi'),
	('Agustín Álvarez Martínez', 'Uruguay', 'agustin alvarez martinez'),
	('Agustín Álvarez Martínez', 'Uruguay', 'martinez'),
	('Maksymilian Stryjek', 'Poland', 'maksymilian stryjek'),
	('Maksymilian Stryjek', 'Poland', 'stryjek'),
	('Aaron Morley', 'England', 'morley'),
	('Aaron Morley', 'England', 'aaron morley'),
	('Tobias Kraulich', 'Germany', 'kraulich'),
	('Tobias Kraulich', 'Germany', 'tobias kraulich'),
	('Kacper Michalski', 'Poland', 'michalski'),
	('Kacper Michalski', 'Poland', 'kacper michalski'),
	('Amund Wichne', 'Norway', 'amund wichne'),
	('Amund Wichne', 'Norway', 'wichne'),
	('Paulo Estrela', 'Portugal', 'paulo estrela'),
	('Paulo Estrela', 'Portugal', 'estrela'),
	('Mohammed Khalfan', 'United Arab Emirates', 'mohammed khalfan'),
	('Mohammed Khalfan', 'United Arab Emirates', 'khalfan'),
	('Paddy Kirk', 'Republic of Ireland', 'paddy kirk'),
	('Paddy Kirk', 'Republic of Ireland', 'kirk'),
	('Adam Crookes', 'England', 'crookes'),
	('Adam Crookes', 'England', 'adam crookes'),
	('Charlie Trafford', 'Canada', 'trafford'),
	('Charlie Trafford', 'Canada', 'charlie trafford'),
	('Andy Fisher', 'England', 'andy fisher'),
	('Andy Fisher', 'England', 'fisher'),
	('Brian Murphy', 'Republic of Ireland', 'murphy'),
	('Brian Murphy', 'Republic of Ireland', 'brian murphy'),
	('Brian Farioli', 'Argentina', 'farioli'),
	('Brian Farioli', 'Argentina', 'brian farioli'),
	('York Rafael', 'Sweden', 'rafael'),
	('York Rafael', 'Sweden', 'york rafael'),
	('Fernando Tapia', 'Mexico', 'tapia'),
	('Fernando Tapia', 'Mexico', 'fernando tapia'),
	('Marlon Suliman Mustapha', 'Austria', 'marlon suliman mustapha'),
	('Marlon Suliman Mustapha', 'Austria', 'mustapha'),
	('Pius Krätschmer', 'Germany', 'pius kratschmer'),
	('Pius Krätschmer', 'Germany', 'kratschmer'),
	('Hou Sen', 'China PR', 'sen'),
	('Hou Sen', 'China PR', 'hou sen'),
	('De La Mata', 'Spain', 'de la mata'),
	('De La Mata', 'Spain', 'mata'),
	('Shaun McWilliams', 'England', 'mcwilliams'),
	('Shaun McWilliams', 'England', 'shaun mcwilliams'),
	('Ethan Robson', 'England', 'ethan robson'),
	('Ethan Robson', 'England', 'robson'),
	('Maciej Rosołek', 'Poland', 'maciej rosoek'),
	('Maciej Rosołek', 'Poland', 'rosoek'),
	('Robin Tihi', 'Finland', 'robin tihi'),
	('Robin Tihi', 'Finland', 'tihi'),
	('Amir Bilali', 'Albania', 'bilali'),
	('Amir Bilali', 'Albania', 'amir bilali'),
	('Ishaq Abdulrazak', 'Nigeria', 'abdulrazak'),
	('Ishaq Abdulrazak', 'Nigeria', 'ishaq abdulrazak'),
	('Danny Rogers', 'Republic of Ireland', 'danny rogers'),
	('Danny Rogers', 'Republic of Ireland', 'rogers'),
	('Tarek Elrich', 'Australia', 'elrich'),
	('Tarek Elrich', 'Australia', 'tarek elrich'),
	('Johan Brattberg', 'Sweden', 'johan brattberg'),
	('Johan Brattberg', 'Sweden', 'brattberg'),
	('Joe Powell', 'England', 'powell'),
	('Joe Powell', 'England', 'joe powell'),
	('Shilow Tracey', 'England', 'tracey'),
	('Shilow Tracey', 'England', 'shilow tracey'),
	('Azón', 'Spain', 'azon'),
	('João Monteiro', 'Portugal', 'joao monteiro'),
	('João Monteiro', 'Portugal', 'monteiro'),
	('Alessandro Confente', 'Italy', 'alessandro confente'),
	('Alessandro Confente', 'Italy', 'confente'),
	('Raúl Sandoval', 'Mexico', 'raul sandoval'),
	('Raúl Sandoval', 'Mexico', 'sandoval'),
	('Theo Bair', 'Canada', 'theo bair'),
	('Theo Bair', 'Canada', 'bair'),
	('Emiliano González', 'Argentina', 'emiliano gonzalez'),
	('Emiliano González', 'Argentina', 'gonzalez'),
	('Fabian Greilinger', 'Germany', 'greilinger'),
	('Fabian Greilinger', 'Germany', 'fabian greilinger'),
	('Jesús Vargas', 'Venezuela', 'vargas'),
	('Jesús Vargas', 'Venezuela', 'jesus vargas'),
	('Maxence Rivera', 'France', 'maxence rivera'),
	('Maxence Rivera', 'France', 'rivera'),
	('José Muñóz', 'Bolivia', 'jose munoz'),
	('José Muñóz', 'Bolivia', 'munoz'),
	('Benjamín Galindo', 'Mexico', 'galindo'),
	('Benjamín Galindo', 'Mexico', 'benjamin galindo'),
	('Adam Lewis', 'England', 'adam lewis'),
	('Adam Lewis', 'England', 'lewis'),
	('Jabor Issa', 'Saudi Arabia', 'jabor issa'),
	('Jabor Issa', 'Saudi Arabia', 'issa'),
	('Tom Grivosti', 'England', 'grivosti'),
	('Tom Grivosti', 'England', 'tom grivosti'),
	('Takumi Nakamura', 'Japan', 'nakamura'),
	('Takumi Nakamura', 'Japan', 'takumi nakamura'),
	('Jasser Khmiri', 'Tunisia', 'khmiri'),
	('Jasser Khmiri', 'Tunisia', 'jasser khmiri'),
	('Agim Zeka', 'Albania', 'zeka'),
	('Agim Zeka', 'Albania', 'agim zeka'),
	('Eduardo Del Ángel', 'Mexico', 'angel'),
	('Eduardo Del Ángel', 'Mexico', 'eduardo del angel'),
	('Arne Ammerer', 'Austria', 'ammerer'),
	('Arne Ammerer', 'Austria', 'arne ammerer'),
	('João Neto', 'Brazil', 'neto'),
	('João Neto', 'Brazil', 'joao neto'),
	('Romaric Yapi', 'France', 'romaric yapi'),
	('Romaric Yapi', 'France', 'yapi'),
	('Nelson Balongo', 'DR Congo', 'balongo'),
	('Nelson Balongo', 'DR Congo', 'nelson balongo'),
	('Gonçalo Franco', 'Portugal', 'franco'),
	('Gonçalo Franco', 'Portugal', 'goncalo franco'),
	('Roli Pereira de Sa', 'France', 'roli pereira de sa'),
	('Roli Pereira de Sa', 'France', 'sa'),
	('Alfie Monksfield', 'Australia', 'monksfield'),
	('Alfie Monksfield', 'Australia', 'alfie monksfield'),
	('Jesse Zamudio', 'Mexico', 'zamudio'),
	('Jesse Zamudio', 'Mexico', 'jesse zamudio'),
	('Jamie Mascoll', 'England', 'jamie mascoll'),
	('Jamie Mascoll', 'England', 'mascoll'),
	('Jan Žambůrek', 'Czech Republic', 'zamburek'),
	('Jan Žambůrek', 'Czech Republic', 'jan zamburek'),
	('Zabarte', 'Spain', 'zabarte'),
	('Kyle Taylor', 'England', 'taylor'),
	('Kyle Taylor', 'England', 'kyle taylor'),
	('Ransford-Yeboah Königsdörffer', 'Germany', 'ransfordyeboah konigsdorffer'),
	('Ransford-Yeboah Königsdörffer', 'Germany', 'konigsdorffer'),
	('Han Xuan', 'China PR', 'han xuan'),
	('Han Xuan', 'China PR', 'xuan'),
	('Siriné Doucouré', 'France', 'sirine doucoure'),
	('Siriné Doucouré', 'France', 'doucoure'),
	('Abdulmohsen Fallatah', 'Saudi Arabia', 'fallatah'),
	('Abdulmohsen Fallatah', 'Saudi Arabia', 'abdulmohsen fallatah'),
	('Kenshin Yoshimaru', 'Japan', 'kenshin yoshimaru'),
	('Kenshin Yoshimaru', 'Japan', 'yoshimaru')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';