INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Jake Hastie', 'Scotland', 'player'),
	('David Atanga', 'Ghana', 'player'),
	('Erling Knudtzon', 'Norway', 'player'),
	('Christopher Telo', 'Sweden', 'player'),
	('Miguel Oliveira', 'Portugal', 'player'),
	('Hamilton Piedra', 'Ecuador', 'player'),
	('Antoine Leautey', 'France', 'player'),
	('Guilherme Oliveira', 'Portugal', 'player'),
	('Joe Bendik', 'United States', 'player'),
	('Troy Parrott', 'Republic of Ireland', 'player'),
	('André Weis', 'Germany', 'player'),
	('Nicklas Shipnoski', 'Germany', 'player'),
	('Finn Stokkers', 'Netherlands', 'player'),
	('Yuki Otsu', 'Japan', 'player'),
	('Manuel Thurnwald', 'Austria', 'player'),
	('Armand Laurienté', 'France', 'player'),
	('Casagrande', 'Brazil', 'player'),
	('Roberto Luzárraga', 'Ecuador', 'player'),
	('Ziyad Al Sahafi', 'Saudi Arabia', 'player'),
	('Alejo Antilef', 'Argentina', 'player'),
	('Arthur Kevin Yamga', 'France', 'player'),
	('Hitoshi Sogahata', 'Japan', 'player'),
	('Salem Mbakata', 'France', 'player'),
	('Bruno Paz', 'Portugal', 'player'),
	('Oleksandr Syrota', 'Ukraine', 'player'),
	('Philipp Hercher', 'Germany', 'player'),
	('Han Seok Hee', 'Korea Republic', 'player'),
	('Adrián Lozano', 'Mexico', 'player'),
	('Niko Hansen', 'Denmark', 'player'),
	('Adebayo Akinfenwa', 'England', 'player'),
	('Nicolás Crovetto', 'Chile', 'player'),
	('Thomas Reifeltshammer', 'Austria', 'player'),
	('Campos', 'Spain', 'player'),
	('Nicolás Díaz', 'Chile', 'player'),
	('Óscar Rubio', 'Spain', 'player'),
	('Lukas Klemenz', 'Poland', 'player'),
	('Jermaine Hylton', 'England', 'player'),
	('Michał Żyro', 'Poland', 'player'),
	('Víctor Balta', 'Peru', 'player'),
	('Um Won Sang', 'Korea Republic', 'player'),
	('Mario Osuna', 'Mexico', 'player'),
	('Valentin Henry', 'France', 'player'),
	('Flavio', 'Brazil', 'player'),
	('Florian Loshaj', 'Kosovo', 'player'),
	('Leonardo Vaca', 'Bolivia', 'player'),
	('Luis Muñoz', 'Spain', 'player'),
	('Jay Bothroyd', 'England', 'player'),
	('David Stec', 'Austria', 'player'),
	('Hugo Vetlesen', 'Norway', 'player'),
	('Rocky Bushiri', 'Belgium', 'player'),
	('Rufo', 'Spain', 'player'),
	('Brett Pitman', 'England', 'player'),
	('Marko Marić', 'Croatia', 'player'),
	('Alan Acosta', 'Mexico', 'player'),
	('Jay Emmanuel-Thomas', 'England', 'player'),
	('Stephen Henderson', 'Republic of Ireland', 'player'),
	('Kevin Friesenbichler', 'Austria', 'player'),
	('Nathaniel Atkinson', 'Australia', 'player'),
	('Albion Vrenezi', 'Kosovo', 'player'),
	('Juninho', 'Brazil', 'player'),
	('Aly Ndom', 'France', 'player'),
	('Mi Haolun', 'China PR', 'player'),
	('Santiago Pérez', 'Uruguay', 'player'),
	('Marian Aioani', 'Romania', 'player'),
	('Daniel Moreno', 'Colombia', 'player'),
	('Alessio Da Cruz', 'Netherlands', 'player'),
	('Marcus Fraser', 'Scotland', 'player'),
	('Alexandre Raineau', 'France', 'player'),
	('Aleksandar Šušnjar', 'Australia', 'player'),
	('Lee Brown', 'England', 'player'),
	('Gao Zhunyi', 'China PR', 'player'),
	('Joshua Bitter', 'Germany', 'player'),
	('Jay O''Shea', 'Republic of Ireland', 'player'),
	('Anthony Maisonnial', 'France', 'player'),
	('Akira Ibayashi', 'Japan', 'player'),
	('Dan Butler', 'England', 'player'),
	('Rabyi Sufyani', 'Saudi Arabia', 'player'),
	('Matt Macey', 'England', 'player'),
	('Mustafa Akbaş', 'Turkey', 'player'),
	('Frank Ronstadt', 'Germany', 'player'),
	('Sorin Bușu', 'Romania', 'player'),
	('Yuto Uchida', 'Japan', 'player'),
	('Maximilian Rossmann', 'Germany', 'player'),
	('Juan Manuel Sanabria', 'Uruguay', 'player'),
	('Antoni Ivanov', 'Bulgaria', 'player'),
	('Yusuke Minagawa', 'Japan', 'player'),
	('Tyler Walker', 'England', 'player'),
	('Ryan Giles', 'England', 'player'),
	('Conor McLaughlin', 'Northern Ireland', 'player'),
	('Tomáš Holý', 'Czech Republic', 'player'),
	('Martin Pušić', 'Austria', 'player'),
	('Alejandro Cabrera', 'Argentina', 'player'),
	('Fanendo Adi', 'Nigeria', 'player'),
	('Wolke Janssens', 'Belgium', 'player'),
	('Jørgen Strand Larsen', 'Norway', 'player'),
	('Tristan Blackmon', 'United States', 'player'),
	('Andy Rose', 'Australia', 'player'),
	('Alex Palmer', 'England', 'player'),
	('Logan Ndenbe', 'Belgium', 'player'),
	('Steven Lewerenz', 'Germany', 'player'),
	('Dani Morer', 'Spain', 'player'),
	('José León', 'Spain', 'player'),
	('Toni Domgjoni', 'Switzerland', 'player'),
	('Grejohn Kyei', 'France', 'player'),
	('Ibrahim Cissé', 'Ivory Coast', 'player'),
	('Tom Van Hyfte', 'Belgium', 'player'),
	('Dylan Mbayo', 'Belgium', 'player'),
	('Yagan Sasman', 'South Africa', 'player'),
	('Yuber Mosquera', 'Colombia', 'player'),
	('Alex Schalk', 'Netherlands', 'player'),
	('David Templeton', 'Scotland', 'player'),
	('Paolo Yrizar', 'Mexico', 'player'),
	('Memo Rodriguez', 'United States', 'player'),
	('Kubilay Sönmez', 'Turkey', 'player'),
	('Gabriel Marques', 'Brazil', 'player'),
	('Eric Oelschlägel', 'Germany', 'player'),
	('Dmitriy Rybchinskiy', 'Russia', 'player'),
	('Kirk Broadfoot', 'Scotland', 'player'),
	('Fer Niño', 'Spain', 'player'),
	('Julien Ngoy', 'Belgium', 'player'),
	('Marius Willsch', 'Germany', 'player'),
	('Đorđe Nikolić', 'Serbia', 'player'),
	('Yan Dhanda', 'England', 'player'),
	('Jesper Juelsgård', 'Denmark', 'player'),
	('Rasmus Alm', 'Sweden', 'player'),
	('Carl Winchester', 'Northern Ireland', 'player'),
	('Joe Walsh', 'Wales', 'player'),
	('Felix Müller', 'Germany', 'player'),
	('Bryan Soumaré', 'France', 'player'),
	('Dylan McGeouch', 'Scotland', 'player'),
	('Alex Gilbey', 'England', 'player'),
	('Søren Reese', 'Denmark', 'player'),
	('Brandon Comley', 'Montserrat', 'player'),
	('Alfredo Rojas', 'Peru', 'player'),
	('Mahdi Camara', 'France', 'player'),
	('Lubambo Musonda', 'Zambia', 'player'),
	('Malvind Benning', 'England', 'player'),
	('Jesper Nyholm', 'Sweden', 'player'),
	('Ali Crawford', 'Scotland', 'player'),
	('Andrés Oña', 'Ecuador', 'player'),
	('Jordy Gaspar', 'France', 'player'),
	('Li Ang', 'China PR', 'player'),
	('Oleg Reabciuk', 'Moldova', 'player'),
	('Mohamed Ali Camara', 'Guinea', 'player'),
	('Lee Eu Ddeum', 'Korea Republic', 'player'),
	('Florin Gardoș', 'Romania', 'player'),
	('Siyabonga Ngezana', 'South Africa', 'player'),
	('Paul Papp', 'Romania', 'player'),
	('Zhang Yuning', 'China PR', 'player'),
	('Ka Sol Hyun', 'Korea Republic', 'player'),
	('Rafik Guitane', 'France', 'player'),
	('Cheng Yuelei', 'China PR', 'player'),
	('Damon Bansais', 'France', 'player'),
	('Perry Kitchen', 'United States', 'player'),
	('Yun Pyeong Gook', 'Korea Republic', 'player'),
	('Clint Irwin', 'United States', 'player'),
	('Simon Grether', 'Switzerland', 'player'),
	('Thore Pedersen', 'Norway', 'player'),
	('Raheem Edwards', 'Canada', 'player'),
	('Ole Jørgen Halvorsen', 'Norway', 'player'),
	('Takuya Okamoto', 'Japan', 'player'),
	('Toni Moya', 'Spain', 'player'),
	('Markus Schwabl', 'Germany', 'player'),
	('Agyemang Diawusie', 'Germany', 'player'),
	('Jonathan Betancourt', 'Ecuador', 'player'),
	('Basil Stillhart', 'Switzerland', 'player'),
	('Pierre Bourdin', 'France', 'player'),
	('Alex Woodyard', 'England', 'player'),
	('Donald Love', 'Scotland', 'player'),
	('Óliver Benítez', 'Argentina', 'player'),
	('Marvin Egho', 'Austria', 'player'),
	('Ognjen Gnjatić', 'Bosnia Herzegovina', 'player'),
	('Thanos Petsos', 'Greece', 'player'),
	('Jorge Recalde', 'Paraguay', 'player'),
	('Jesper Verlaat', 'Netherlands', 'player'),
	('Romain Basque', 'France', 'player'),
	('Yu Dabao', 'China PR', 'player'),
	('Richard O''Donnell', 'England', 'player'),
	('Florian Kath', 'Germany', 'player'),
	('Brendan Galloway', 'England', 'player'),
	('Jun Ichimori', 'Japan', 'player'),
	('Nikola Boranijašević', 'Serbia', 'player'),
	('Steven Sessegnon', 'England', 'player'),
	('Issouf Paro', 'Burkina Faso', 'player'),
	('Hidetoshi Miyuki', 'Japan', 'player'),
	('José de Jesús Godínez', 'Mexico', 'player'),
	('Alexander Winkler', 'Germany', 'player'),
	('Jacob Schoop', 'Denmark', 'player'),
	('Warren Tchimbembé', 'France', 'player'),
	('César Urpín', 'Venezuela', 'player'),
	('Roel Janssen', 'Netherlands', 'player'),
	('Moritz Heinrich', 'Germany', 'player'),
	('Osayamen Osawe', 'Nigeria', 'player'),
	('Yuya Takazawa', 'Japan', 'player'),
	('Leon Dajaku', 'Germany', 'player'),
	('Hamza Rafia', 'Tunisia', 'player'),
	('Darío Melo', 'Chile', 'player'),
	('Omar Islas', 'Mexico', 'player'),
	('Koki Machida', 'Japan', 'player'),
	('Yuta Koike', 'Japan', 'player'),
	('Julius Reinhardt', 'Germany', 'player'),
	('Lucas Hufnagel', 'Georgia', 'player'),
	('Spencer Richey', 'United States', 'player'),
	('Yugo Tatsuta', 'Japan', 'player'),
	('Ryo Hatsuse', 'Japan', 'player'),
	('Olmo', 'Spain', 'player'),
	('Erik Vera', 'Mexico', 'player'),
	('Adam Jackson', 'England', 'player'),
	('Nathanaël Dieng', 'France', 'player'),
	('John Mary', 'Cameroon', 'player'),
	('Gonzalo Montes', 'Uruguay', 'player'),
	('Michael Arroyo', 'Ecuador', 'player'),
	('Siyabonga Mpontshane', 'South Africa', 'player'),
	('Marius Høibråten', 'Norway', 'player'),
	('Glody Ngonda', 'DR Congo', 'player'),
	('Rai Vloet', 'Netherlands', 'player'),
	('Nicolás Franco', 'Argentina', 'player'),
	('Eduard Pap', 'Romania', 'player'),
	('Pierre Ruffaut', 'France', 'player'),
	('Ovidiu Horșia', 'Romania', 'player'),
	('Justin Eilers', 'Germany', 'player'),
	('Kevin Großkreutz', 'Germany', 'player'),
	('Bent Sørmo', 'Norway', 'player'),
	('Alejandro Frezzotti', 'Argentina', 'player'),
	('Joni Montiel', 'Spain', 'player'),
	('Daniel Luxbacher', 'Austria', 'player'),
	('Kevin Kraus', 'Germany', 'player'),
	('Richard Neudecker', 'Germany', 'player'),
	('Andy Cook', 'England', 'player'),
	('Jonathan Beaulieu', 'France', 'player'),
	('Tsukasa Umesaki', 'Japan', 'player'),
	('Joe Bell', 'New Zealand', 'player'),
	('Odin Luraas Bjørtuft', 'Norway', 'player'),
	('David Tavares', 'Portugal', 'player'),
	('Vincent Müller', 'Germany', 'player'),
	('Amidou Diop', 'Senegal', 'player'),
	('Terrence Dzvukamanja', 'Zimbabwe', 'player'),
	('Alfie Kilgour', 'England', 'player'),
	('David Gomis', 'France', 'player'),
	('Axel Bamba', 'Ivory Coast', 'player'),
	('Zito Luvumbo', 'Angola', 'player'),
	('Yacine Qasmi', 'Morocco', 'player'),
	('Rubén González', 'Mexico', 'player'),
	('Frankie Kent', 'England', 'player'),
	('Denver Hume', 'England', 'player'),
	('Leonel Justiniano', 'Bolivia', 'player'),
	('Kang Min Soo', 'Korea Republic', 'player'),
	('Yaw Ihle Amankwah', 'Norway', 'player'),
	('Loránd Fülöp', 'Romania', 'player'),
	('Jordan Harvey', 'United States', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Jake Hastie', 'Scotland', 'jake hastie'),
	('Jake Hastie', 'Scotland', 'hastie'),
	('David Atanga', 'Ghana', 'david atanga'),
	('David Atanga', 'Ghana', 'atanga'),
	('Erling Knudtzon', 'Norway', 'erling knudtzon'),
	('Erling Knudtzon', 'Norway', 'knudtzon'),
	('Christopher Telo', 'Sweden', 'christopher telo'),
	('Christopher Telo', 'Sweden', 'telo'),
	('Miguel Oliveira', 'Portugal', 'oliveira'),
	('Miguel Oliveira', 'Portugal', 'miguel oliveira'),
	('Hamilton Piedra', 'Ecuador', 'piedra'),
	('Hamilton Piedra', 'Ecuador', 'hamilton piedra'),
	('Antoine Leautey', 'France', 'leautey'),
	('Antoine Leautey', 'France', 'antoine leautey'),
	('Guilherme Oliveira', 'Portugal', 'oliveira'),
	('Guilherme Oliveira', 'Portugal', 'guilherme oliveira'),
	('Joe Bendik', 'United States', 'bendik'),
	('Joe Bendik', 'United States', 'joe bendik'),
	('Troy Parrott', 'Republic of Ireland', 'troy parrott'),
	('Troy Parrott', 'Republic of Ireland', 'parrott'),
	('André Weis', 'Germany', 'andre weis'),
	('André Weis', 'Germany', 'weis'),
	('Nicklas Shipnoski', 'Germany', 'shipnoski'),
	('Nicklas Shipnoski', 'Germany', 'nicklas shipnoski'),
	('Finn Stokkers', 'Netherlands', 'stokkers'),
	('Finn Stokkers', 'Netherlands', 'finn stokkers'),
	('Yuki Otsu', 'Japan', 'yuki otsu'),
	('Yuki Otsu', 'Japan', 'otsu'),
	('Manuel Thurnwald', 'Austria', 'thurnwald'),
	('Manuel Thurnwald', 'Austria', 'manuel thurnwald'),
	('Armand Laurienté', 'France', 'armand lauriente'),
	('Armand Laurienté', 'France', 'lauriente'),
	('Casagrande', 'Brazil', 'casagrande'),
	('Roberto Luzárraga', 'Ecuador', 'roberto luzarraga'),
	('Roberto Luzárraga', 'Ecuador', 'luzarraga'),
	('Ziyad Al Sahafi', 'Saudi Arabia', 'sahafi'),
	('Ziyad Al Sahafi', 'Saudi Arabia', 'ziyad al sahafi'),
	('Alejo Antilef', 'Argentina', 'alejo antilef'),
	('Alejo Antilef', 'Argentina', 'antilef'),
	('Arthur Kevin Yamga', 'France', 'yamga'),
	('Arthur Kevin Yamga', 'France', 'arthur kevin yamga'),
	('Hitoshi Sogahata', 'Japan', 'sogahata'),
	('Hitoshi Sogahata', 'Japan', 'hitoshi sogahata'),
	('Salem Mbakata', 'France', 'mbakata'),
	('Salem Mbakata', 'France', 'salem mbakata'),
	('Bruno Paz', 'Portugal', 'paz'),
	('Bruno Paz', 'Portugal', 'bruno paz'),
	('Oleksandr Syrota', 'Ukraine', 'syrota'),
	('Oleksandr Syrota', 'Ukraine', 'oleksandr syrota'),
	('Philipp Hercher', 'Germany', 'hercher'),
	('Philipp Hercher', 'Germany', 'philipp hercher'),
	('Han Seok Hee', 'Korea Republic', 'han seok hee'),
	('Han Seok Hee', 'Korea Republic', 'hee'),
	('Adrián Lozano', 'Mexico', 'lozano'),
	('Adrián Lozano', 'Mexico', 'adrian lozano'),
	('Niko Hansen', 'Denmark', 'niko hansen'),
	('Niko Hansen', 'Denmark', 'hansen'),
	('Adebayo Akinfenwa', 'England', 'akinfenwa'),
	('Adebayo Akinfenwa', 'England', 'adebayo akinfenwa'),
	('Nicolás Crovetto', 'Chile', 'crovetto'),
	('Nicolás Crovetto', 'Chile', 'nicolas crovetto'),
	('Thomas Reifeltshammer', 'Austria', 'thomas reifeltshammer'),
	('Thomas Reifeltshammer', 'Austria', 'reifeltshammer'),
	('Campos', 'Spain', 'campos'),
	('Nicolás Díaz', 'Chile', 'nicolas diaz'),
	('Nicolás Díaz', 'Chile', 'diaz'),
	('Óscar Rubio', 'Spain', 'rubio'),
	('Óscar Rubio', 'Spain', 'oscar rubio'),
	('Lukas Klemenz', 'Poland', 'klemenz'),
	('Lukas Klemenz', 'Poland', 'lukas klemenz'),
	('Jermaine Hylton', 'England', 'jermaine hylton'),
	('Jermaine Hylton', 'England', 'hylton'),
	('Michał Żyro', 'Poland', 'zyro'),
	('Michał Żyro', 'Poland', 'micha zyro'),
	('Víctor Balta', 'Peru', 'victor balta'),
	('Víctor Balta', 'Peru', 'balta'),
	('Um Won Sang', 'Korea Republic', 'um won sang'),
	('Um Won Sang', 'Korea Republic', 'sang'),
	('Mario Osuna', 'Mexico', 'mario osuna'),
	('Mario Osuna', 'Mexico', 'osuna'),
	('Valentin Henry', 'France', 'henry'),
	('Valentin Henry', 'France', 'valentin henry'),
	('Flavio', 'Brazil', 'flavio'),
	('Florian Loshaj', 'Kosovo', 'florian loshaj'),
	('Florian Loshaj', 'Kosovo', 'loshaj'),
	('Leonardo Vaca', 'Bolivia', 'leonardo vaca'),
	('Leonardo Vaca', 'Bolivia', 'vaca'),
	('Luis Muñoz', 'Spain', 'munoz'),
	('Luis Muñoz', 'Spain', 'luis munoz'),
	('Jay Bothroyd', 'England', 'bothroyd'),
	('Jay Bothroyd', 'England', 'jay bothroyd'),
	('David Stec', 'Austria', 'david stec'),
	('David Stec', 'Austria', 'stec'),
	('Hugo Vetlesen', 'Norway', 'vetlesen'),
	('Hugo Vetlesen', 'Norway', 'hugo vetlesen'),
	('Rocky Bushiri', 'Belgium', 'rocky bushiri'),
	('Rocky Bushiri', 'Belgium', 'bushiri'),
	('Rufo', 'Spain', 'rufo'),
	('Brett Pitman', 'England', 'brett pitman'),
	('Brett Pitman', 'England', 'pitman'),
	('Marko Marić', 'Croatia', 'maric'),
	('Marko Marić', 'Croatia', 'marko maric'),
	('Alan Acosta', 'Mexico', 'acosta'),
	('Alan Acosta', 'Mexico', 'alan acosta'),
	('Jay Emmanuel-Thomas', 'England', 'emmanuelthomas'),
	('Jay Emmanuel-Thomas', 'England', 'jay emmanuelthomas'),
	('Stephen Henderson', 'Republic of Ireland', 'henderson'),
	('Stephen Henderson', 'Republic of Ireland', 'stephen henderson'),
	('Kevin Friesenbichler', 'Austria', 'kevin friesenbichler'),
	('Kevin Friesenbichler', 'Austria', 'friesenbichler'),
	('Nathaniel Atkinson', 'Australia', 'atkinson'),
	('Nathaniel Atkinson', 'Australia', 'nathaniel atkinson'),
	('Albion Vrenezi', 'Kosovo', 'vrenezi'),
	('Albion Vrenezi', 'Kosovo', 'albion vrenezi'),
	('Juninho', 'Brazil', 'juninho'),
	('Aly Ndom', 'France', 'ndom'),
	('Aly Ndom', 'France', 'aly ndom'),
	('Mi Haolun', 'China PR', 'mi haolun'),
	('Mi Haolun', 'China PR', 'haolun'),
	('Santiago Pérez', 'Uruguay', 'santiago perez'),
	('Santiago Pérez', 'Uruguay', 'perez'),
	('Marian Aioani', 'Romania', 'marian aioani'),
	('Marian Aioani', 'Romania', 'aioani'),
	('Daniel Moreno', 'Colombia', 'moreno'),
	('Daniel Moreno', 'Colombia', 'daniel moreno'),
	('Alessio Da Cruz', 'Netherlands', 'alessio da cruz'),
	('Alessio Da Cruz', 'Netherlands', 'cruz'),
	('Marcus Fraser', 'Scotland', 'marcus fraser'),
	('Marcus Fraser', 'Scotland', 'fraser'),
	('Alexandre Raineau', 'France', 'raineau'),
	('Alexandre Raineau', 'France', 'alexandre raineau'),
	('Aleksandar Šušnjar', 'Australia', 'aleksandar susnjar'),
	('Aleksandar Šušnjar', 'Australia', 'susnjar'),
	('Lee Brown', 'England', 'brown'),
	('Lee Brown', 'England', 'lee brown'),
	('Gao Zhunyi', 'China PR', 'zhunyi'),
	('Gao Zhunyi', 'China PR', 'gao zhunyi'),
	('Joshua Bitter', 'Germany', 'bitter'),
	('Joshua Bitter', 'Germany', 'joshua bitter'),
	('Jay O''Shea', 'Republic of Ireland', 'jay oshea'),
	('Jay O''Shea', 'Republic of Ireland', 'oshea'),
	('Anthony Maisonnial', 'France', 'maisonnial'),
	('Anthony Maisonnial', 'France', 'anthony maisonnial'),
	('Akira Ibayashi', 'Japan', 'akira ibayashi'),
	('Akira Ibayashi', 'Japan', 'ibayashi'),
	('Dan Butler', 'England', 'dan butler'),
	('Dan Butler', 'England', 'butler'),
	('Rabyi Sufyani', 'Saudi Arabia', 'rabyi sufyani'),
	('Rabyi Sufyani', 'Saudi Arabia', 'sufyani'),
	('Matt Macey', 'England', 'matt macey'),
	('Matt Macey', 'England', 'macey'),
	('Mustafa Akbaş', 'Turkey', 'akbas'),
	('Mustafa Akbaş', 'Turkey', 'mustafa akbas'),
	('Frank Ronstadt', 'Germany', 'ronstadt'),
	('Frank Ronstadt', 'Germany', 'frank ronstadt'),
	('Sorin Bușu', 'Romania', 'sorin busu'),
	('Sorin Bușu', 'Romania', 'busu'),
	('Yuto Uchida', 'Japan', 'uchida'),
	('Yuto Uchida', 'Japan', 'yuto uchida'),
	('Maximilian Rossmann', 'Germany', 'rossmann'),
	('Maximilian Rossmann', 'Germany', 'maximilian rossmann'),
	('Juan Manuel Sanabria', 'Uruguay', 'sanabria'),
	('Juan Manuel Sanabria', 'Uruguay', 'juan manuel sanabria'),
	('Antoni Ivanov', 'Bulgaria', 'ivanov'),
	('Antoni Ivanov', 'Bulgaria', 'antoni ivanov'),
	('Yusuke Minagawa', 'Japan', 'yusuke minagawa'),
	('Yusuke Minagawa', 'Japan', 'minagawa'),
	('Tyler Walker', 'England', 'tyler walker'),
	('Tyler Walker', 'England', 'walker'),
	('Ryan Giles', 'England', 'ryan giles'),
	('Ryan Giles', 'England', 'giles'),
	('Conor McLaughlin', 'Northern Ireland', 'conor mclaughlin'),
	('Conor McLaughlin', 'Northern Ireland', 'mclaughlin'),
	('Tomáš Holý', 'Czech Republic', 'holy'),
	('Tomáš Holý', 'Czech Republic', 'tomas holy'),
	('Martin Pušić', 'Austria', 'martin pusic'),
	('Martin Pušić', 'Austria', 'pusic'),
	('Alejandro Cabrera', 'Argentina', 'cabrera'),
	('Alejandro Cabrera', 'Argentina', 'alejandro cabrera'),
	('Fanendo Adi', 'Nigeria', 'fanendo adi'),
	('Fanendo Adi', 'Nigeria', 'adi'),
	('Wolke Janssens', 'Belgium', 'janssens'),
	('Wolke Janssens', 'Belgium', 'wolke janssens'),
	('Jørgen Strand Larsen', 'Norway', 'larsen'),
	('Jørgen Strand Larsen', 'Norway', 'jrgen strand larsen'),
	('Tristan Blackmon', 'United States', 'blackmon'),
	('Tristan Blackmon', 'United States', 'tristan blackmon'),
	('Andy Rose', 'Australia', 'rose'),
	('Andy Rose', 'Australia', 'andy rose'),
	('Alex Palmer', 'England', 'palmer'),
	('Alex Palmer', 'England', 'alex palmer'),
	('Logan Ndenbe', 'Belgium', 'ndenbe'),
	('Logan Ndenbe', 'Belgium', 'logan ndenbe'),
	('Steven Lewerenz', 'Germany', 'steven lewerenz'),
	('Steven Lewerenz', 'Germany', 'lewerenz'),
	('Dani Morer', 'Spain', 'dani morer'),
	('Dani Morer', 'Spain', 'morer'),
	('José León', 'Spain', 'leon'),
	('José León', 'Spain', 'jose leon'),
	('Toni Domgjoni', 'Switzerland', 'toni domgjoni'),
	('Toni Domgjoni', 'Switzerland', 'domgjoni'),
	('Grejohn Kyei', 'France', 'grejohn kyei'),
	('Grejohn Kyei', 'France', 'kyei'),
	('Ibrahim Cissé', 'Ivory Coast', 'ibrahim cisse'),
	('Ibrahim Cissé', 'Ivory Coast', 'cisse'),
	('Tom Van Hyfte', 'Belgium', 'tom van hyfte'),
	('Tom Van Hyfte', 'Belgium', 'hyfte'),
	('Dylan Mbayo', 'Belgium', 'mbayo'),
	('Dylan Mbayo', 'Belgium', 'dylan mbayo'),
	('Yagan Sasman', 'South Africa', 'sasman'),
	('Yagan Sasman', 'South Africa', 'yagan sasman'),
	('Yuber Mosquera', 'Colombia', 'mosquera'),
	('Yuber Mosquera', 'Colombia', 'yuber mosquera'),
	('Alex Schalk', 'Netherlands', 'schalk'),
	('Alex Schalk', 'Netherlands', 'alex schalk'),
	('David Templeton', 'Scotland', 'david templeton'),
	('David Templeton', 'Scotland', 'templeton'),
	('Paolo Yrizar', 'Mexico', 'yrizar'),
	('Paolo Yrizar', 'Mexico', 'paolo yrizar'),
	('Memo Rodriguez', 'United States', 'memo rodriguez'),
	('Memo Rodriguez', 'United States', 'rodriguez'),
	('Kubilay Sönmez', 'Turkey', 'kubilay sonmez'),
	('Kubilay Sönmez', 'Turkey', 'sonmez'),
	('Gabriel Marques', 'Brazil', 'gabriel marques'),
	('Gabriel Marques', 'Brazil', 'marques'),
	('Eric Oelschlägel', 'Germany', 'eric oelschlagel'),
	('Eric Oelschlägel', 'Germany', 'oelschlagel'),
	('Dmitriy Rybchinskiy', 'Russia', 'dmitriy rybchinskiy'),
	('Dmitriy Rybchinskiy', 'Russia', 'rybchinskiy'),
	('Kirk Broadfoot', 'Scotland', 'broadfoot'),
	('Kirk Broadfoot', 'Scotland', 'kirk broadfoot'),
	('Fer Niño', 'Spain', 'fer nino'),
	('Fer Niño', 'Spain', 'nino'),
	('Julien Ngoy', 'Belgium', 'ngoy'),
	('Julien Ngoy', 'Belgium', 'julien ngoy'),
	('Marius Willsch', 'Germany', 'willsch'),
	('Marius Willsch', 'Germany', 'marius willsch'),
	('Đorđe Nikolić', 'Serbia', 'ore nikolic'),
	('Đorđe Nikolić', 'Serbia', 'nikolic'),
	('Yan Dhanda', 'England', 'yan dhanda'),
	('Yan Dhanda', 'England', 'dhanda'),
	('Jesper Juelsgård', 'Denmark', 'juelsgard'),
	('Jesper Juelsgård', 'Denmark', 'jesper juelsgard'),
	('Rasmus Alm', 'Sweden', 'rasmus alm'),
	('Rasmus Alm', 'Sweden', 'alm'),
	('Carl Winchester', 'Northern Ireland', 'carl winchester'),
	('Carl Winchester', 'Northern Ireland', 'winchester'),
	('Joe Walsh', 'Wales', 'joe walsh'),
	('Joe Walsh', 'Wales', 'walsh'),
	('Felix Müller', 'Germany', 'muller'),
	('Felix Müller', 'Germany', 'felix muller'),
	('Bryan Soumaré', 'France', 'soumare'),
	('Bryan Soumaré', 'France', 'bryan soumare'),
	('Dylan McGeouch', 'Scotland', 'dylan mcgeouch'),
	('Dylan McGeouch', 'Scotland', 'mcgeouch'),
	('Alex Gilbey', 'England', 'gilbey'),
	('Alex Gilbey', 'England', 'alex gilbey'),
	('Søren Reese', 'Denmark', 'reese'),
	('Søren Reese', 'Denmark', 'sren reese'),
	('Brandon Comley', 'Montserrat', 'comley'),
	('Brandon Comley', 'Montserrat', 'brandon comley'),
	('Alfredo Rojas', 'Peru', 'alfredo rojas'),
	('Alfredo Rojas', 'Peru', 'rojas'),
	('Mahdi Camara', 'France', 'mahdi camara'),
	('Mahdi Camara', 'France', 'camara'),
	('Lubambo Musonda', 'Zambia', 'musonda'),
	('Lubambo Musonda', 'Zambia', 'lubambo musonda'),
	('Malvind Benning', 'England', 'malvind benning'),
	('Malvind Benning', 'England', 'benning'),
	('Jesper Nyholm', 'Sweden', 'nyholm'),
	('Jesper Nyholm', 'Sweden', 'jesper nyholm'),
	('Ali Crawford', 'Scotland', 'ali crawford'),
	('Ali Crawford', 'Scotland', 'crawford'),
	('Andrés Oña', 'Ecuador', 'ona'),
	('Andrés Oña', 'Ecuador', 'andres ona'),
	('Jordy Gaspar', 'France', 'jordy gaspar'),
	('Jordy Gaspar', 'France', 'gaspar'),
	('Li Ang', 'China PR', 'li ang'),
	('Li Ang', 'China PR', 'ang'),
	('Oleg Reabciuk', 'Moldova', 'reabciuk'),
	('Oleg Reabciuk', 'Moldova', 'oleg reabciuk'),
	('Mohamed Ali Camara', 'Guinea', 'mohamed ali camara'),
	('Mohamed Ali Camara', 'Guinea', 'camara'),
	('Lee Eu Ddeum', 'Korea Republic', 'ddeum'),
	('Lee Eu Ddeum', 'Korea Republic', 'lee eu ddeum'),
	('Florin Gardoș', 'Romania', 'gardos'),
	('Florin Gardoș', 'Romania', 'florin gardos'),
	('Siyabonga Ngezana', 'South Africa', 'ngezana'),
	('Siyabonga Ngezana', 'South Africa', 'siyabonga ngezana'),
	('Paul Papp', 'Romania', 'papp'),
	('Paul Papp', 'Romania', 'paul papp'),
	('Zhang Yuning', 'China PR', 'zhang yuning'),
	('Zhang Yuning', 'China PR', 'yuning'),
	('Ka Sol Hyun', 'Korea Republic', 'hyun'),
	('Ka Sol Hyun', 'Korea Republic', 'ka sol hyun'),
	('Rafik Guitane', 'France', 'guitane'),
	('Rafik Guitane', 'France', 'rafik guitane'),
	('Cheng Yuelei', 'China PR', 'cheng yuelei'),
	('Cheng Yuelei', 'China PR', 'yuelei'),
	('Damon Bansais', 'France', 'bansais'),
	('Damon Bansais', 'France', 'damon bansais'),
	('Perry Kitchen', 'United States', 'perry kitchen'),
	('Perry Kitchen', 'United States', 'kitchen'),
	('Yun Pyeong Gook', 'Korea Republic', 'yun pyeong gook'),
	('Yun Pyeong Gook', 'Korea Republic', 'gook'),
	('Clint Irwin', 'United States', 'irwin'),
	('Clint Irwin', 'United States', 'clint irwin'),
	('Simon Grether', 'Switzerland', 'grether'),
	('Simon Grether', 'Switzerland', 'simon grether'),
	('Thore Pedersen', 'Norway', 'thore pedersen'),
	('Thore Pedersen', 'Norway', 'pedersen'),
	('Raheem Edwards', 'Canada', 'edwards'),
	('Raheem Edwards', 'Canada', 'raheem edwards'),
	('Ole Jørgen Halvorsen', 'Norway', 'halvorsen'),
	('Ole Jørgen Halvorsen', 'Norway', 'ole jrgen halvorsen'),
	('Takuya Okamoto', 'Japan', 'okamoto'),
	('Takuya Okamoto', 'Japan', 'takuya okamoto'),
	('Toni Moya', 'Spain', 'toni moya'),
	('Toni Moya', 'Spain', 'moya'),
	('Markus Schwabl', 'Germany', 'markus schwabl'),
	('Markus Schwabl', 'Germany', 'schwabl'),
	('Agyemang Diawusie', 'Germany', 'diawusie'),
	('Agyemang Diawusie', 'Germany', 'agyemang diawusie'),
	('Jonathan Betancourt', 'Ecuador', 'jonathan betancourt'),
	('Jonathan Betancourt', 'Ecuador', 'betancourt'),
	('Basil Stillhart', 'Switzerland', 'basil stillhart'),
	('Basil Stillhart', 'Switzerland', 'stillhart'),
	('Pierre Bourdin', 'France', 'bourdin'),
	('Pierre Bourdin', 'France', 'pierre bourdin'),
	('Alex Woodyard', 'England', 'alex woodyard'),
	('Alex Woodyard', 'England', 'woodyard'),
	('Donald Love', 'Scotland', 'donald love'),
	('Donald Love', 'Scotland', 'love'),
	('Óliver Benítez', 'Argentina', 'oliver benitez'),
	('Óliver Benítez', 'Argentina', 'benitez'),
	('Marvin Egho', 'Austria', 'egho'),
	('Marvin Egho', 'Austria', 'marvin egho'),
	('Ognjen Gnjatić', 'Bosnia Herzegovina', 'gnjatic'),
	('Ognjen Gnjatić', 'Bosnia Herzegovina', 'ognjen gnjatic'),
	('Thanos Petsos', 'Greece', 'petsos'),
	('Thanos Petsos', 'Greece', 'thanos petsos'),
	('Jorge Recalde', 'Paraguay', 'recalde'),
	('Jorge Recalde', 'Paraguay', 'jorge recalde'),
	('Jesper Verlaat', 'Netherlands', 'jesper verlaat'),
	('Jesper Verlaat', 'Netherlands', 'verlaat'),
	('Romain Basque', 'France', 'basque'),
	('Romain Basque', 'France', 'romain basque'),
	('Yu Dabao', 'China PR', 'yu dabao'),
	('Yu Dabao', 'China PR', 'dabao'),
	('Richard O''Donnell', 'England', 'odonnell'),
	('Richard O''Donnell', 'England', 'richard odonnell'),
	('Florian Kath', 'Germany', 'kath'),
	('Florian Kath', 'Germany', 'florian kath'),
	('Brendan Galloway', 'England', 'galloway'),
	('Brendan Galloway', 'England', 'brendan galloway'),
	('Jun Ichimori', 'Japan', 'jun ichimori'),
	('Jun Ichimori', 'Japan', 'ichimori'),
	('Nikola Boranijašević', 'Serbia', 'nikola boranijasevic'),
	('Nikola Boranijašević', 'Serbia', 'boranijasevic'),
	('Steven Sessegnon', 'England', 'sessegnon'),
	('Steven Sessegnon', 'England', 'steven sessegnon'),
	('Issouf Paro', 'Burkina Faso', 'issouf paro'),
	('Issouf Paro', 'Burkina Faso', 'paro'),
	('Hidetoshi Miyuki', 'Japan', 'miyuki'),
	('Hidetoshi Miyuki', 'Japan', 'hidetoshi miyuki'),
	('José de Jesús Godínez', 'Mexico', 'godinez'),
	('José de Jesús Godínez', 'Mexico', 'jose de jesus godinez'),
	('Alexander Winkler', 'Germany', 'winkler'),
	('Alexander Winkler', 'Germany', 'alexander winkler'),
	('Jacob Schoop', 'Denmark', 'jacob schoop'),
	('Jacob Schoop', 'Denmark', 'schoop'),
	('Warren Tchimbembé', 'France', 'warren tchimbembe'),
	('Warren Tchimbembé', 'France', 'tchimbembe'),
	('César Urpín', 'Venezuela', 'cesar urpin'),
	('César Urpín', 'Venezuela', 'urpin'),
	('Roel Janssen', 'Netherlands', 'janssen'),
	('Roel Janssen', 'Netherlands', 'roel janssen'),
	('Moritz Heinrich', 'Germany', 'moritz heinrich'),
	('Moritz Heinrich', 'Germany', 'heinrich'),
	('Osayamen Osawe', 'Nigeria', 'osayamen osawe'),
	('Osayamen Osawe', 'Nigeria', 'osawe'),
	('Yuya Takazawa', 'Japan', 'takazawa'),
	('Yuya Takazawa', 'Japan', 'yuya takazawa'),
	('Leon Dajaku', 'Germany', 'leon dajaku'),
	('Leon Dajaku', 'Germany', 'dajaku'),
	('Hamza Rafia', 'Tunisia', 'hamza rafia'),
	('Hamza Rafia', 'Tunisia', 'rafia'),
	('Darío Melo', 'Chile', 'dario melo'),
	('Darío Melo', 'Chile', 'melo'),
	('Omar Islas', 'Mexico', 'islas'),
	('Omar Islas', 'Mexico', 'omar islas'),
	('Koki Machida', 'Japan', 'koki machida'),
	('Koki Machida', 'Japan', 'machida'),
	('Yuta Koike', 'Japan', 'yuta koike'),
	('Yuta Koike', 'Japan', 'koike'),
	('Julius Reinhardt', 'Germany', 'reinhardt'),
	('Julius Reinhardt', 'Germany', 'julius reinhardt'),
	('Lucas Hufnagel', 'Georgia', 'lucas hufnagel'),
	('Lucas Hufnagel', 'Georgia', 'hufnagel'),
	('Spencer Richey', 'United States', 'richey'),
	('Spencer Richey', 'United States', 'spencer richey'),
	('Yugo Tatsuta', 'Japan', 'tatsuta'),
	('Yugo Tatsuta', 'Japan', 'yugo tatsuta'),
	('Ryo Hatsuse', 'Japan', 'hatsuse'),
	('Ryo Hatsuse', 'Japan', 'ryo hatsuse'),
	('Olmo', 'Spain', 'olmo'),
	('Erik Vera', 'Mexico', 'erik vera'),
	('Erik Vera', 'Mexico', 'vera'),
	('Adam Jackson', 'England', 'adam jackson'),
	('Adam Jackson', 'England', 'jackson'),
	('Nathanaël Dieng', 'France', 'nathanael dieng'),
	('Nathanaël Dieng', 'France', 'dieng'),
	('John Mary', 'Cameroon', 'mary'),
	('John Mary', 'Cameroon', 'john mary'),
	('Gonzalo Montes', 'Uruguay', 'gonzalo montes'),
	('Gonzalo Montes', 'Uruguay', 'montes'),
	('Michael Arroyo', 'Ecuador', 'michael arroyo'),
	('Michael Arroyo', 'Ecuador', 'arroyo'),
	('Siyabonga Mpontshane', 'South Africa', 'siyabonga mpontshane'),
	('Siyabonga Mpontshane', 'South Africa', 'mpontshane'),
	('Marius Høibråten', 'Norway', 'hibraten'),
	('Marius Høibråten', 'Norway', 'marius hibraten'),
	('Glody Ngonda', 'DR Congo', 'glody ngonda'),
	('Glody Ngonda', 'DR Congo', 'ngonda'),
	('Rai Vloet', 'Netherlands', 'vloet'),
	('Rai Vloet', 'Netherlands', 'rai vloet'),
	('Nicolás Franco', 'Argentina', 'nicolas franco'),
	('Nicolás Franco', 'Argentina', 'franco'),
	('Eduard Pap', 'Romania', 'eduard pap'),
	('Eduard Pap', 'Romania', 'pap'),
	('Pierre Ruffaut', 'France', 'pierre ruffaut'),
	('Pierre Ruffaut', 'France', 'ruffaut'),
	('Ovidiu Horșia', 'Romania', 'ovidiu horsia'),
	('Ovidiu Horșia', 'Romania', 'horsia'),
	('Justin Eilers', 'Germany', 'eilers'),
	('Justin Eilers', 'Germany', 'justin eilers'),
	('Kevin Großkreutz', 'Germany', 'kevin grokreutz'),
	('Kevin Großkreutz', 'Germany', 'grokreutz'),
	('Bent Sørmo', 'Norway', 'bent srmo'),
	('Bent Sørmo', 'Norway', 'srmo'),
	('Alejandro Frezzotti', 'Argentina', 'alejandro frezzotti'),
	('Alejandro Frezzotti', 'Argentina', 'frezzotti'),
	('Joni Montiel', 'Spain', 'joni montiel'),
	('Joni Montiel', 'Spain', 'montiel'),
	('Daniel Luxbacher', 'Austria', 'daniel luxbacher'),
	('Daniel Luxbacher', 'Austria', 'luxbacher'),
	('Kevin Kraus', 'Germany', 'kraus'),
	('Kevin Kraus', 'Germany', 'kevin kraus'),
	('Richard Neudecker', 'Germany', 'neudecker'),
	('Richard Neudecker', 'Germany', 'richard neudecker'),
	('Andy Cook', 'England', 'cook'),
	('Andy Cook', 'England', 'andy cook'),
	('Jonathan Beaulieu', 'France', 'jonathan beaulieu'),
	('Jonathan Beaulieu', 'France', 'beaulieu'),
	('Tsukasa Umesaki', 'Japan', 'umesaki'),
	('Tsukasa Umesaki', 'Japan', 'tsukasa umesaki'),
	('Joe Bell', 'New Zealand', 'bell'),
	('Joe Bell', 'New Zealand', 'joe bell'),
	('Odin Luraas Bjørtuft', 'Norway', 'bjrtuft'),
	('Odin Luraas Bjørtuft', 'Norway', 'odin luraas bjrtuft'),
	('David Tavares', 'Portugal', 'david tavares'),
	('David Tavares', 'Portugal', 'tavares'),
	('Vincent Müller', 'Germany', 'muller'),
	('Vincent Müller', 'Germany', 'vincent muller'),
	('Amidou Diop', 'Senegal', 'amidou diop'),
	('Amidou Diop', 'Senegal', 'diop'),
	('Terrence Dzvukamanja', 'Zimbabwe', 'dzvukamanja'),
	('Terrence Dzvukamanja', 'Zimbabwe', 'terrence dzvukamanja'),
	('Alfie Kilgour', 'England', 'kilgour'),
	('Alfie Kilgour', 'England', 'alfie kilgour'),
	('David Gomis', 'France', 'david gomis'),
	('David Gomis', 'France', 'gomis'),
	('Axel Bamba', 'Ivory Coast', 'axel bamba'),
	('Axel Bamba', 'Ivory Coast', 'bamba'),
	('Zito Luvumbo', 'Angola', 'zito luvumbo'),
	('Zito Luvumbo', 'Angola', 'luvumbo'),
	('Yacine Qasmi', 'Morocco', 'yacine qasmi'),
	('Yacine Qasmi', 'Morocco', 'qasmi'),
	('Rubén González', 'Mexico', 'ruben gonzalez'),
	('Rubén González', 'Mexico', 'gonzalez'),
	('Frankie Kent', 'England', 'frankie kent'),
	('Frankie Kent', 'England', 'kent'),
	('Denver Hume', 'England', 'hume'),
	('Denver Hume', 'England', 'denver hume'),
	('Leonel Justiniano', 'Bolivia', 'justiniano'),
	('Leonel Justiniano', 'Bolivia', 'leonel justiniano'),
	('Kang Min Soo', 'Korea Republic', 'soo'),
	('Kang Min Soo', 'Korea Republic', 'kang min soo'),
	('Yaw Ihle Amankwah', 'Norway', 'yaw ihle amankwah'),
	('Yaw Ihle Amankwah', 'Norway', 'amankwah'),
	('Loránd Fülöp', 'Romania', 'lorand fulop'),
	('Loránd Fülöp', 'Romania', 'fulop'),
	('Jordan Harvey', 'United States', 'harvey'),
	('Jordan Harvey', 'United States', 'jordan harvey')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';