INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Tyrone Marsh', 'England', 'player'),
	('Guo Quanbo', 'China PR', 'player'),
	('Abdullah Al Ammar', 'Saudi Arabia', 'player'),
	('Jeremiah Gutjahr', 'United States', 'player'),
	('Dennis Cirkin', 'England', 'player'),
	('Júlio Romão', 'Brazil', 'player'),
	('Mohammed Al Qarni', 'Saudi Arabia', 'player'),
	('Junior Ogedi-Uzokwe', 'England', 'player'),
	('Scott Kennedy', 'Canada', 'player'),
	('Didí Torrico', 'Bolivia', 'player'),
	('Takuya Masuda', 'Japan', 'player'),
	('Benji Michel', 'United States', 'player'),
	('Dan Gardner', 'England', 'player'),
	('Hamza Massoudi', 'Belgium', 'player'),
	('Egil Selvik', 'Norway', 'player'),
	('Ross Draper', 'England', 'player'),
	('Joseph Ceesay', 'Sweden', 'player'),
	('Emiliano Agüero', 'Argentina', 'player'),
	('Ayrton Páez', 'Venezuela', 'player'),
	('Moritz Fritz', 'Germany', 'player'),
	('David Bumberger', 'Austria', 'player'),
	('Matis Carvalho', 'Portugal', 'player'),
	('Sekou Sidibe', 'Belgium', 'player'),
	('Kosuke Kinoshita', 'Japan', 'player'),
	('Tyreeq Bakinson', 'England', 'player'),
	('Elliott List', 'England', 'player'),
	('Edyairth Ortega', 'Mexico', 'player'),
	('Tim Väyrynen', 'Finland', 'player'),
	('Horacio Igarzabal', 'Argentina', 'player'),
	('Kim Jin Gyu', 'Korea Republic', 'player'),
	('Samuel Costa', 'Portugal', 'player'),
	('Dominik Marx', 'Germany', 'player'),
	('Michael Guthörl', 'Germany', 'player'),
	('Nick Townsend', 'England', 'player'),
	('Eric Calvillo', 'United States', 'player'),
	('Luis Coordes', 'Dominican Republic', 'player'),
	('Kim Won Gun', 'Korea Republic', 'player'),
	('Charlie Kelman', 'United States', 'player'),
	('Alfon', 'Spain', 'player'),
	('Joel Nilsson', 'Sweden', 'player'),
	('Lars Dietz', 'Germany', 'player'),
	('Nicolás Fernández Mercau', 'Argentina', 'player'),
	('Antonio Jonjić', 'Germany', 'player'),
	('Azzeddine Toufiqui', 'France', 'player'),
	('Ranko Veselinović', 'Serbia', 'player'),
	('Ismaël Aaneba', 'France', 'player'),
	('Vicente Besuijen', 'Netherlands', 'player'),
	('Josh Grant', 'England', 'player'),
	('Jhohan Romaña', 'Colombia', 'player'),
	('Yuya Oki', 'Japan', 'player'),
	('Ryosuke Tone', 'Japan', 'player'),
	('Yuki Yamamoto', 'Japan', 'player'),
	('Warmed Omari', 'France', 'player'),
	('Andrew Putna', 'United States', 'player'),
	('Alfio Oviedo', 'Paraguay', 'player'),
	('Nigel Atangana', 'France', 'player'),
	('Liam Kitching', 'England', 'player'),
	('Ryan Fulton', 'Scotland', 'player'),
	('Doğukan Özkan', 'Turkey', 'player'),
	('Alexander Weidinger', 'Germany', 'player'),
	('Tobias Lauritsen', 'Norway', 'player'),
	('Edson Pérez', 'Bolivia', 'player'),
	('Calum Waters', 'Scotland', 'player'),
	('Matej Poplatnik', 'Slovenia', 'player'),
	('Brandon Palacios', 'Peru', 'player'),
	('Clément Bayiha', 'Canada', 'player'),
	('Namakoro Diallo', 'France', 'player'),
	('Matías Caseras', 'Uruguay', 'player'),
	('Omar Sowunmi', 'England', 'player'),
	('Chen Xiao', 'China PR', 'player'),
	('Marcin Flis', 'Poland', 'player'),
	('Ousmane Camara', 'Guinea', 'player'),
	('Ilay Elmkies', 'Israel', 'player'),
	('Anthony Hartigan', 'England', 'player'),
	('Cosmin Achim', 'Romania', 'player'),
	('Erik Viveros', 'Ecuador', 'player'),
	('Henry Plazas', 'Venezuela', 'player'),
	('Dawid Kocyła', 'Poland', 'player'),
	('Francisco Flores', 'Argentina', 'player'),
	('Han Eui Kwon', 'Korea Republic', 'player'),
	('Brendan Moore', 'United States', 'player'),
	('Antony Trujillo', 'Venezuela', 'player'),
	('Guy-Marcelin Kilama', 'Cameroon', 'player'),
	('Maximilian Bauer', 'Germany', 'player'),
	('Abdullah Al Joui', 'Saudi Arabia', 'player'),
	('Rodrigo Gomes', 'Portugal', 'player'),
	('Driss Trichard', 'France', 'player'),
	('Javi López', 'Spain', 'player'),
	('İrfan Can Eğribayat', 'Turkey', 'player'),
	('Rami Hajal', 'Sweden', 'player'),
	('Oscar Threlkeld', 'England', 'player'),
	('Valentin Gendrey', 'France', 'player'),
	('Moisés Acuña', 'Venezuela', 'player'),
	('Chico', 'Brazil', 'player'),
	('Harrison Dunk', 'England', 'player'),
	('Danny Newton', 'England', 'player'),
	('Scott Quigley', 'England', 'player'),
	('Denis Ventúra', 'Slovakia', 'player'),
	('Marius Funk', 'Germany', 'player'),
	('Sebastian Hausner', 'Denmark', 'player'),
	('Jhonny Lucas', 'Brazil', 'player'),
	('Juan Ruiz', 'Colombia', 'player'),
	('Robbie Crawford', 'Scotland', 'player'),
	('Collin Seedorf', 'Netherlands', 'player'),
	('Asier Córdoba', 'Spain', 'player'),
	('Mateo Klimowicz', 'Argentina', 'player'),
	('Michael Cooper', 'England', 'player'),
	('Thomas Sabitzer', 'Austria', 'player'),
	('Joaquín Indacoechea', 'Argentina', 'player'),
	('Matchoi Djaló', 'Portugal', 'player'),
	('Erick Cano', 'Bolivia', 'player'),
	('Franco Pérez', 'Argentina', 'player'),
	('Yannik Keitel', 'Germany', 'player'),
	('Felix Horn Myhre', 'Norway', 'player'),
	('Ari Leifsson', 'Iceland', 'player'),
	('Oltan Karakullukçu', 'Turkey', 'player'),
	('Asen Chandarov', 'Bulgaria', 'player'),
	('Damir Sadiković', 'Bosnia Herzegovina', 'player'),
	('Nathan Cameron', 'England', 'player'),
	('Paul Mullin', 'England', 'player'),
	('Alejandro Rivero', 'Argentina', 'player'),
	('Lewis Gibson', 'England', 'player'),
	('Richecard Richard', 'France', 'player'),
	('Álex Martínez', 'Spain', 'player'),
	('Boris Prokopič', 'Austria', 'player'),
	('Jordan Stevens', 'England', 'player'),
	('Agustín Álvarez', 'Argentina', 'player'),
	('Peteiro', 'Spain', 'player'),
	('Adrián Bernabé', 'Spain', 'player'),
	('Christian Viet', 'Germany', 'player'),
	('Kanya Fujimoto', 'Japan', 'player'),
	('Jimmy Valoyes', 'Colombia', 'player'),
	('Sui Weijie', 'China PR', 'player'),
	('Emanuel Emegha', 'Netherlands', 'player'),
	('Mark Byrne', 'Republic of Ireland', 'player'),
	('Stephen Mallon', 'Republic of Ireland', 'player'),
	('Mory Konaté', 'Guinea', 'player'),
	('Aldair Quintana', 'Colombia', 'player'),
	('Julius Kade', 'Germany', 'player'),
	('Frank Arhin', 'Ghana', 'player'),
	('Emanuele Zuelli', 'Italy', 'player'),
	('Sascha Härtel', 'Germany', 'player'),
	('Manato Shinada', 'Japan', 'player'),
	('Jayden Oosterwolde', 'Netherlands', 'player'),
	('Ross Laidlaw', 'Scotland', 'player'),
	('Alpay Çelebi', 'Turkey', 'player'),
	('Taylor Harwood-Bellis', 'England', 'player'),
	('Ricardo Santos', 'Portugal', 'player'),
	('Lim Jae Hyeok', 'Korea Republic', 'player'),
	('Callum Cooke', 'England', 'player'),
	('Even Østensen', 'Norway', 'player'),
	('Jack Aitchison', 'Scotland', 'player'),
	('David Ayala', 'Argentina', 'player'),
	('José Carabalí', 'Ecuador', 'player'),
	('Sinan Karweina', 'Germany', 'player'),
	('Yari Otto', 'Germany', 'player'),
	('Maxime Awoudja', 'Germany', 'player'),
	('Joël Schmied', 'Switzerland', 'player'),
	('Tamás Szántó', 'Hungary', 'player'),
	('César Villagra', 'Paraguay', 'player'),
	('Darwin Gómez', 'Venezuela', 'player'),
	('Hampus Zackrisson', 'Sweden', 'player'),
	('Lorenzo Colombo', 'Italy', 'player'),
	('Julius Ertlthaler', 'Austria', 'player'),
	('Ellis Iandolo', 'England', 'player'),
	('Ben Coker', 'England', 'player'),
	('Conor Wilkinson', 'Republic of Ireland', 'player'),
	('Elias Abouchabaka', 'Germany', 'player'),
	('Szymon Stasik', 'Poland', 'player'),
	('Hong Jung Nam', 'Korea Republic', 'player'),
	('Anthony Correia', 'France', 'player'),
	('Mateusz Hołownia', 'Poland', 'player'),
	('Luca Ranieri', 'Italy', 'player'),
	('Cristian Lasso', 'Colombia', 'player'),
	('George Taft', 'England', 'player'),
	('Carlos Castro', 'Venezuela', 'player'),
	('Filip Modelski', 'Poland', 'player'),
	('Andrew Lyons', 'Republic of Ireland', 'player'),
	('Ouasim Bouy', 'Netherlands', 'player'),
	('Frantz Pangop', 'Cameroon', 'player'),
	('Dinny Corcoran', 'Republic of Ireland', 'player'),
	('Víctor Cabezas', 'Colombia', 'player'),
	('Daiki Tomii', 'Japan', 'player'),
	('Jayden Nelson', 'Canada', 'player'),
	('Samed Onur', 'Turkey', 'player'),
	('Kim Hyo Gi', 'Korea Republic', 'player'),
	('Mateusz Kuzimski', 'Poland', 'player'),
	('Luis Romero', 'Venezuela', 'player'),
	('Yoan Severin', 'France', 'player'),
	('Andrei Marinescu', 'Romania', 'player'),
	('Moody Chana', 'Germany', 'player'),
	('Louis Ameka Autchanga', 'Gabon', 'player'),
	('Zak Dearnley', 'England', 'player'),
	('José Peñarrieta', 'Bolivia', 'player'),
	('Garry Buckley', 'Republic of Ireland', 'player'),
	('Jerónimo Rodríguez', 'Mexico', 'player'),
	('Siad Haji', 'United States', 'player'),
	('Mads Bidstrup', 'Denmark', 'player'),
	('Dominic Bernard', 'Republic of Ireland', 'player'),
	('Leonardo Terán', 'Venezuela', 'player'),
	('Miguel Ángel', 'Spain', 'player'),
	('Gabriel Deac', 'Romania', 'player'),
	('Emil Holm', 'Sweden', 'player'),
	('Thomas Van Den Keybus', 'Belgium', 'player'),
	('Jake Eastwood', 'England', 'player'),
	('Frazer Blake-Tracy', 'England', 'player'),
	('Daniel Segura', 'Ecuador', 'player'),
	('Blaise Yaméogo', 'Burkina Faso', 'player'),
	('Ivan Ilić', 'Serbia', 'player'),
	('Kevin Martin Krygård', 'Norway', 'player'),
	('José Canale', 'Paraguay', 'player'),
	('Alexi Pitu', 'Romania', 'player'),
	('Armin Đerlek', 'Serbia', 'player'),
	('Hamidou Maïga', 'Mali', 'player'),
	('Jair Yglesias', 'Peru', 'player'),
	('Blake Bodily', 'United States', 'player'),
	('Brandon Sartiaguin', 'Mexico', 'player'),
	('Kendall McIntosh', 'United States', 'player'),
	('Majed Hazazi', 'Saudi Arabia', 'player'),
	('Timothy Eyoma', 'England', 'player'),
	('Jacob Italiano', 'Australia', 'player'),
	('Dominik Lanius', 'Germany', 'player'),
	('Iván Martín', 'Spain', 'player'),
	('Mauricio Guzmán', 'Argentina', 'player'),
	('Cristian Costin', 'Romania', 'player'),
	('Jakub Arak', 'Poland', 'player'),
	('Khaled Al Samiri', 'Saudi Arabia', 'player'),
	('Sean Mackie', 'Scotland', 'player'),
	('Milciades Portillo', 'Paraguay', 'player'),
	('Ali Al Khaibari', 'Saudi Arabia', 'player'),
	('Emmanuel Oyeleke', 'England', 'player'),
	('Sulayman Bojang', 'Gambia', 'player'),
	('Răzvan Trif', 'Romania', 'player'),
	('Cameron Norman', 'England', 'player'),
	('Diego Pampín', 'Spain', 'player'),
	('Yasser Larouci', 'Algeria', 'player'),
	('Manuel Arteaga', 'Venezuela', 'player'),
	('Matthäus Taferner', 'Austria', 'player'),
	('Mauro Osores', 'Argentina', 'player'),
	('Han Rongze', 'China PR', 'player'),
	('Shaun Brisley', 'England', 'player'),
	('Daiki Niwa', 'Japan', 'player'),
	('Saif Al Qeshtah', 'Saudi Arabia', 'player'),
	('Tiago Almeida', 'Portugal', 'player'),
	('Franco Perinciolo', 'Argentina', 'player'),
	('Henrik Gjesdal', 'Norway', 'player'),
	('Dániel Gyollai', 'Hungary', 'player'),
	('Alan Liebeskind', 'Venezuela', 'player'),
	('Rok Sirk', 'Slovenia', 'player'),
	('Franco Petroli', 'Argentina', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Tyrone Marsh', 'England', 'marsh'),
	('Tyrone Marsh', 'England', 'tyrone marsh'),
	('Guo Quanbo', 'China PR', 'quanbo'),
	('Guo Quanbo', 'China PR', 'guo quanbo'),
	('Abdullah Al Ammar', 'Saudi Arabia', 'abdullah al ammar'),
	('Abdullah Al Ammar', 'Saudi Arabia', 'ammar'),
	('Jeremiah Gutjahr', 'United States', 'jeremiah gutjahr'),
	('Jeremiah Gutjahr', 'United States', 'gutjahr'),
	('Dennis Cirkin', 'England', 'dennis cirkin'),
	('Dennis Cirkin', 'England', 'cirkin'),
	('Júlio Romão', 'Brazil', 'julio romao'),
	('Júlio Romão', 'Brazil', 'romao'),
	('Mohammed Al Qarni', 'Saudi Arabia', 'qarni'),
	('Mohammed Al Qarni', 'Saudi Arabia', 'mohammed al qarni'),
	('Junior Ogedi-Uzokwe', 'England', 'junior ogediuzokwe'),
	('Junior Ogedi-Uzokwe', 'England', 'ogediuzokwe'),
	('Scott Kennedy', 'Canada', 'scott kennedy'),
	('Scott Kennedy', 'Canada', 'kennedy'),
	('Didí Torrico', 'Bolivia', 'didi torrico'),
	('Didí Torrico', 'Bolivia', 'torrico'),
	('Takuya Masuda', 'Japan', 'masuda'),
	('Takuya Masuda', 'Japan', 'takuya masuda'),
	('Benji Michel', 'United States', 'benji michel'),
	('Benji Michel', 'United States', 'michel'),
	('Dan Gardner', 'England', 'dan gardner'),
	('Dan Gardner', 'England', 'gardner'),
	('Hamza Massoudi', 'Belgium', 'hamza massoudi'),
	('Hamza Massoudi', 'Belgium', 'massoudi'),
	('Egil Selvik', 'Norway', 'egil selvik'),
	('Egil Selvik', 'Norway', 'selvik'),
	('Ross Draper', 'England', 'draper'),
	('Ross Draper', 'England', 'ross draper'),
	('Joseph Ceesay', 'Sweden', 'joseph ceesay'),
	('Joseph Ceesay', 'Sweden', 'ceesay'),
	('Emiliano Agüero', 'Argentina', 'aguero'),
	('Emiliano Agüero', 'Argentina', 'emiliano aguero'),
	('Ayrton Páez', 'Venezuela', 'paez'),
	('Ayrton Páez', 'Venezuela', 'ayrton paez'),
	('Moritz Fritz', 'Germany', 'moritz fritz'),
	('Moritz Fritz', 'Germany', 'fritz'),
	('David Bumberger', 'Austria', 'bumberger'),
	('David Bumberger', 'Austria', 'david bumberger'),
	('Matis Carvalho', 'Portugal', 'carvalho'),
	('Matis Carvalho', 'Portugal', 'matis carvalho'),
	('Sekou Sidibe', 'Belgium', 'sekou sidibe'),
	('Sekou Sidibe', 'Belgium', 'sidibe'),
	('Kosuke Kinoshita', 'Japan', 'kosuke kinoshita'),
	('Kosuke Kinoshita', 'Japan', 'kinoshita'),
	('Tyreeq Bakinson', 'England', 'tyreeq bakinson'),
	('Tyreeq Bakinson', 'England', 'bakinson'),
	('Elliott List', 'England', 'elliott list'),
	('Elliott List', 'England', 'list'),
	('Edyairth Ortega', 'Mexico', 'edyairth ortega'),
	('Edyairth Ortega', 'Mexico', 'ortega'),
	('Tim Väyrynen', 'Finland', 'vayrynen'),
	('Tim Väyrynen', 'Finland', 'tim vayrynen'),
	('Horacio Igarzabal', 'Argentina', 'igarzabal'),
	('Horacio Igarzabal', 'Argentina', 'horacio igarzabal'),
	('Kim Jin Gyu', 'Korea Republic', 'kim jin gyu'),
	('Kim Jin Gyu', 'Korea Republic', 'gyu'),
	('Samuel Costa', 'Portugal', 'costa'),
	('Samuel Costa', 'Portugal', 'samuel costa'),
	('Dominik Marx', 'Germany', 'marx'),
	('Dominik Marx', 'Germany', 'dominik marx'),
	('Michael Guthörl', 'Germany', 'guthorl'),
	('Michael Guthörl', 'Germany', 'michael guthorl'),
	('Nick Townsend', 'England', 'townsend'),
	('Nick Townsend', 'England', 'nick townsend'),
	('Eric Calvillo', 'United States', 'calvillo'),
	('Eric Calvillo', 'United States', 'eric calvillo'),
	('Luis Coordes', 'Dominican Republic', 'luis coordes'),
	('Luis Coordes', 'Dominican Republic', 'coordes'),
	('Kim Won Gun', 'Korea Republic', 'kim won gun'),
	('Kim Won Gun', 'Korea Republic', 'gun'),
	('Charlie Kelman', 'United States', 'charlie kelman'),
	('Charlie Kelman', 'United States', 'kelman'),
	('Alfon', 'Spain', 'alfon'),
	('Joel Nilsson', 'Sweden', 'joel nilsson'),
	('Joel Nilsson', 'Sweden', 'nilsson'),
	('Lars Dietz', 'Germany', 'dietz'),
	('Lars Dietz', 'Germany', 'lars dietz'),
	('Nicolás Fernández Mercau', 'Argentina', 'mercau'),
	('Nicolás Fernández Mercau', 'Argentina', 'nicolas fernandez mercau'),
	('Antonio Jonjić', 'Germany', 'antonio jonjic'),
	('Antonio Jonjić', 'Germany', 'jonjic'),
	('Azzeddine Toufiqui', 'France', 'azzeddine toufiqui'),
	('Azzeddine Toufiqui', 'France', 'toufiqui'),
	('Ranko Veselinović', 'Serbia', 'veselinovic'),
	('Ranko Veselinović', 'Serbia', 'ranko veselinovic'),
	('Ismaël Aaneba', 'France', 'ismael aaneba'),
	('Ismaël Aaneba', 'France', 'aaneba'),
	('Vicente Besuijen', 'Netherlands', 'vicente besuijen'),
	('Vicente Besuijen', 'Netherlands', 'besuijen'),
	('Josh Grant', 'England', 'josh grant'),
	('Josh Grant', 'England', 'grant'),
	('Jhohan Romaña', 'Colombia', 'jhohan romana'),
	('Jhohan Romaña', 'Colombia', 'romana'),
	('Yuya Oki', 'Japan', 'oki'),
	('Yuya Oki', 'Japan', 'yuya oki'),
	('Ryosuke Tone', 'Japan', 'tone'),
	('Ryosuke Tone', 'Japan', 'ryosuke tone'),
	('Yuki Yamamoto', 'Japan', 'yuki yamamoto'),
	('Yuki Yamamoto', 'Japan', 'yamamoto'),
	('Warmed Omari', 'France', 'warmed omari'),
	('Warmed Omari', 'France', 'omari'),
	('Andrew Putna', 'United States', 'putna'),
	('Andrew Putna', 'United States', 'andrew putna'),
	('Alfio Oviedo', 'Paraguay', 'oviedo'),
	('Alfio Oviedo', 'Paraguay', 'alfio oviedo'),
	('Nigel Atangana', 'France', 'nigel atangana'),
	('Nigel Atangana', 'France', 'atangana'),
	('Liam Kitching', 'England', 'kitching'),
	('Liam Kitching', 'England', 'liam kitching'),
	('Ryan Fulton', 'Scotland', 'fulton'),
	('Ryan Fulton', 'Scotland', 'ryan fulton'),
	('Doğukan Özkan', 'Turkey', 'dogukan ozkan'),
	('Doğukan Özkan', 'Turkey', 'ozkan'),
	('Alexander Weidinger', 'Germany', 'alexander weidinger'),
	('Alexander Weidinger', 'Germany', 'weidinger'),
	('Tobias Lauritsen', 'Norway', 'lauritsen'),
	('Tobias Lauritsen', 'Norway', 'tobias lauritsen'),
	('Edson Pérez', 'Bolivia', 'edson perez'),
	('Edson Pérez', 'Bolivia', 'perez'),
	('Calum Waters', 'Scotland', 'waters'),
	('Calum Waters', 'Scotland', 'calum waters'),
	('Matej Poplatnik', 'Slovenia', 'matej poplatnik'),
	('Matej Poplatnik', 'Slovenia', 'poplatnik'),
	('Brandon Palacios', 'Peru', 'brandon palacios'),
	('Brandon Palacios', 'Peru', 'palacios'),
	('Clément Bayiha', 'Canada', 'bayiha'),
	('Clément Bayiha', 'Canada', 'clement bayiha'),
	('Namakoro Diallo', 'France', 'namakoro diallo'),
	('Namakoro Diallo', 'France', 'diallo'),
	('Matías Caseras', 'Uruguay', 'matias caseras'),
	('Matías Caseras', 'Uruguay', 'caseras'),
	('Omar Sowunmi', 'England', 'omar sowunmi'),
	('Omar Sowunmi', 'England', 'sowunmi'),
	('Chen Xiao', 'China PR', 'xiao'),
	('Chen Xiao', 'China PR', 'chen xiao'),
	('Marcin Flis', 'Poland', 'marcin flis'),
	('Marcin Flis', 'Poland', 'flis'),
	('Ousmane Camara', 'Guinea', 'ousmane camara'),
	('Ousmane Camara', 'Guinea', 'camara'),
	('Ilay Elmkies', 'Israel', 'ilay elmkies'),
	('Ilay Elmkies', 'Israel', 'elmkies'),
	('Anthony Hartigan', 'England', 'hartigan'),
	('Anthony Hartigan', 'England', 'anthony hartigan'),
	('Cosmin Achim', 'Romania', 'cosmin achim'),
	('Cosmin Achim', 'Romania', 'achim'),
	('Erik Viveros', 'Ecuador', 'erik viveros'),
	('Erik Viveros', 'Ecuador', 'viveros'),
	('Henry Plazas', 'Venezuela', 'plazas'),
	('Henry Plazas', 'Venezuela', 'henry plazas'),
	('Dawid Kocyła', 'Poland', 'kocya'),
	('Dawid Kocyła', 'Poland', 'dawid kocya'),
	('Francisco Flores', 'Argentina', 'francisco flores'),
	('Francisco Flores', 'Argentina', 'flores'),
	('Han Eui Kwon', 'Korea Republic', 'han eui kwon'),
	('Han Eui Kwon', 'Korea Republic', 'kwon'),
	('Brendan Moore', 'United States', 'moore'),
	('Brendan Moore', 'United States', 'brendan moore'),
	('Antony Trujillo', 'Venezuela', 'antony trujillo'),
	('Antony Trujillo', 'Venezuela', 'trujillo'),
	('Guy-Marcelin Kilama', 'Cameroon', 'kilama'),
	('Guy-Marcelin Kilama', 'Cameroon', 'guymarcelin kilama'),
	('Maximilian Bauer', 'Germany', 'maximilian bauer'),
	('Maximilian Bauer', 'Germany', 'bauer'),
	('Abdullah Al Joui', 'Saudi Arabia', 'abdullah al joui'),
	('Abdullah Al Joui', 'Saudi Arabia', 'joui'),
	('Rodrigo Gomes', 'Portugal', 'rodrigo gomes'),
	('Rodrigo Gomes', 'Portugal', 'gomes'),
	('Driss Trichard', 'France', 'driss trichard'),
	('Driss Trichard', 'France', 'trichard'),
	('Javi López', 'Spain', 'lopez'),
	('Javi López', 'Spain', 'javi lopez'),
	('İrfan Can Eğribayat', 'Turkey', 'irfan can egribayat'),
	('İrfan Can Eğribayat', 'Turkey', 'egribayat'),
	('Rami Hajal', 'Sweden', 'hajal'),
	('Rami Hajal', 'Sweden', 'rami hajal'),
	('Oscar Threlkeld', 'England', 'oscar threlkeld'),
	('Oscar Threlkeld', 'England', 'threlkeld'),
	('Valentin Gendrey', 'France', 'valentin gendrey'),
	('Valentin Gendrey', 'France', 'gendrey'),
	('Moisés Acuña', 'Venezuela', 'moises acuna'),
	('Moisés Acuña', 'Venezuela', 'acuna'),
	('Chico', 'Brazil', 'chico'),
	('Harrison Dunk', 'England', 'harrison dunk'),
	('Harrison Dunk', 'England', 'dunk'),
	('Danny Newton', 'England', 'danny newton'),
	('Danny Newton', 'England', 'newton'),
	('Scott Quigley', 'England', 'scott quigley'),
	('Scott Quigley', 'England', 'quigley'),
	('Denis Ventúra', 'Slovakia', 'ventura'),
	('Denis Ventúra', 'Slovakia', 'denis ventura'),
	('Marius Funk', 'Germany', 'marius funk'),
	('Marius Funk', 'Germany', 'funk'),
	('Sebastian Hausner', 'Denmark', 'sebastian hausner'),
	('Sebastian Hausner', 'Denmark', 'hausner'),
	('Jhonny Lucas', 'Brazil', 'lucas'),
	('Jhonny Lucas', 'Brazil', 'jhonny lucas'),
	('Juan Ruiz', 'Colombia', 'ruiz'),
	('Juan Ruiz', 'Colombia', 'juan ruiz'),
	('Robbie Crawford', 'Scotland', 'crawford'),
	('Robbie Crawford', 'Scotland', 'robbie crawford'),
	('Collin Seedorf', 'Netherlands', 'seedorf'),
	('Collin Seedorf', 'Netherlands', 'collin seedorf'),
	('Asier Córdoba', 'Spain', 'asier cordoba'),
	('Asier Córdoba', 'Spain', 'cordoba'),
	('Mateo Klimowicz', 'Argentina', 'mateo klimowicz'),
	('Mateo Klimowicz', 'Argentina', 'klimowicz'),
	('Michael Cooper', 'England', 'michael cooper'),
	('Michael Cooper', 'England', 'cooper'),
	('Thomas Sabitzer', 'Austria', 'sabitzer'),
	('Thomas Sabitzer', 'Austria', 'thomas sabitzer'),
	('Joaquín Indacoechea', 'Argentina', 'joaquin indacoechea'),
	('Joaquín Indacoechea', 'Argentina', 'indacoechea'),
	('Matchoi Djaló', 'Portugal', 'djalo'),
	('Matchoi Djaló', 'Portugal', 'matchoi djalo'),
	('Erick Cano', 'Bolivia', 'cano'),
	('Erick Cano', 'Bolivia', 'erick cano'),
	('Franco Pérez', 'Argentina', 'franco perez'),
	('Franco Pérez', 'Argentina', 'perez'),
	('Yannik Keitel', 'Germany', 'keitel'),
	('Yannik Keitel', 'Germany', 'yannik keitel'),
	('Felix Horn Myhre', 'Norway', 'myhre'),
	('Felix Horn Myhre', 'Norway', 'felix horn myhre'),
	('Ari Leifsson', 'Iceland', 'leifsson'),
	('Ari Leifsson', 'Iceland', 'ari leifsson'),
	('Oltan Karakullukçu', 'Turkey', 'oltan karakullukcu'),
	('Oltan Karakullukçu', 'Turkey', 'karakullukcu'),
	('Asen Chandarov', 'Bulgaria', 'chandarov'),
	('Asen Chandarov', 'Bulgaria', 'asen chandarov'),
	('Damir Sadiković', 'Bosnia Herzegovina', 'sadikovic'),
	('Damir Sadiković', 'Bosnia Herzegovina', 'damir sadikovic'),
	('Nathan Cameron', 'England', 'nathan cameron'),
	('Nathan Cameron', 'England', 'cameron'),
	('Paul Mullin', 'England', 'paul mullin'),
	('Paul Mullin', 'England', 'mullin'),
	('Alejandro Rivero', 'Argentina', 'alejandro rivero'),
	('Alejandro Rivero', 'Argentina', 'rivero'),
	('Lewis Gibson', 'England', 'gibson'),
	('Lewis Gibson', 'England', 'lewis gibson'),
	('Richecard Richard', 'France', 'richard'),
	('Richecard Richard', 'France', 'richecard richard'),
	('Álex Martínez', 'Spain', 'martinez'),
	('Álex Martínez', 'Spain', 'alex martinez'),
	('Boris Prokopič', 'Austria', 'prokopic'),
	('Boris Prokopič', 'Austria', 'boris prokopic'),
	('Jordan Stevens', 'England', 'stevens'),
	('Jordan Stevens', 'England', 'jordan stevens'),
	('Agustín Álvarez', 'Argentina', 'agustin alvarez'),
	('Agustín Álvarez', 'Argentina', 'alvarez'),
	('Peteiro', 'Spain', 'peteiro'),
	('Adrián Bernabé', 'Spain', 'bernabe'),
	('Adrián Bernabé', 'Spain', 'adrian bernabe'),
	('Christian Viet', 'Germany', 'viet'),
	('Christian Viet', 'Germany', 'christian viet'),
	('Kanya Fujimoto', 'Japan', 'kanya fujimoto'),
	('Kanya Fujimoto', 'Japan', 'fujimoto'),
	('Jimmy Valoyes', 'Colombia', 'jimmy valoyes'),
	('Jimmy Valoyes', 'Colombia', 'valoyes'),
	('Sui Weijie', 'China PR', 'weijie'),
	('Sui Weijie', 'China PR', 'sui weijie'),
	('Emanuel Emegha', 'Netherlands', 'emanuel emegha'),
	('Emanuel Emegha', 'Netherlands', 'emegha'),
	('Mark Byrne', 'Republic of Ireland', 'byrne'),
	('Mark Byrne', 'Republic of Ireland', 'mark byrne'),
	('Stephen Mallon', 'Republic of Ireland', 'stephen mallon'),
	('Stephen Mallon', 'Republic of Ireland', 'mallon'),
	('Mory Konaté', 'Guinea', 'mory konate'),
	('Mory Konaté', 'Guinea', 'konate'),
	('Aldair Quintana', 'Colombia', 'quintana'),
	('Aldair Quintana', 'Colombia', 'aldair quintana'),
	('Julius Kade', 'Germany', 'julius kade'),
	('Julius Kade', 'Germany', 'kade'),
	('Frank Arhin', 'Ghana', 'arhin'),
	('Frank Arhin', 'Ghana', 'frank arhin'),
	('Emanuele Zuelli', 'Italy', 'emanuele zuelli'),
	('Emanuele Zuelli', 'Italy', 'zuelli'),
	('Sascha Härtel', 'Germany', 'sascha hartel'),
	('Sascha Härtel', 'Germany', 'hartel'),
	('Manato Shinada', 'Japan', 'manato shinada'),
	('Manato Shinada', 'Japan', 'shinada'),
	('Jayden Oosterwolde', 'Netherlands', 'oosterwolde'),
	('Jayden Oosterwolde', 'Netherlands', 'jayden oosterwolde'),
	('Ross Laidlaw', 'Scotland', 'ross laidlaw'),
	('Ross Laidlaw', 'Scotland', 'laidlaw'),
	('Alpay Çelebi', 'Turkey', 'alpay celebi'),
	('Alpay Çelebi', 'Turkey', 'celebi'),
	('Taylor Harwood-Bellis', 'England', 'harwoodbellis'),
	('Taylor Harwood-Bellis', 'England', 'taylor harwoodbellis'),
	('Ricardo Santos', 'Portugal', 'ricardo santos'),
	('Ricardo Santos', 'Portugal', 'santos'),
	('Lim Jae Hyeok', 'Korea Republic', 'hyeok'),
	('Lim Jae Hyeok', 'Korea Republic', 'lim jae hyeok'),
	('Callum Cooke', 'England', 'cooke'),
	('Callum Cooke', 'England', 'callum cooke'),
	('Even Østensen', 'Norway', 'even stensen'),
	('Even Østensen', 'Norway', 'stensen'),
	('Jack Aitchison', 'Scotland', 'aitchison'),
	('Jack Aitchison', 'Scotland', 'jack aitchison'),
	('David Ayala', 'Argentina', 'david ayala'),
	('David Ayala', 'Argentina', 'ayala'),
	('José Carabalí', 'Ecuador', 'carabali'),
	('José Carabalí', 'Ecuador', 'jose carabali'),
	('Sinan Karweina', 'Germany', 'sinan karweina'),
	('Sinan Karweina', 'Germany', 'karweina'),
	('Yari Otto', 'Germany', 'otto'),
	('Yari Otto', 'Germany', 'yari otto'),
	('Maxime Awoudja', 'Germany', 'maxime awoudja'),
	('Maxime Awoudja', 'Germany', 'awoudja'),
	('Joël Schmied', 'Switzerland', 'joel schmied'),
	('Joël Schmied', 'Switzerland', 'schmied'),
	('Tamás Szántó', 'Hungary', 'szanto'),
	('Tamás Szántó', 'Hungary', 'tamas szanto'),
	('César Villagra', 'Paraguay', 'villagra'),
	('César Villagra', 'Paraguay', 'cesar villagra'),
	('Darwin Gómez', 'Venezuela', 'gomez'),
	('Darwin Gómez', 'Venezuela', 'darwin gomez'),
	('Hampus Zackrisson', 'Sweden', 'zackrisson'),
	('Hampus Zackrisson', 'Sweden', 'hampus zackrisson'),
	('Lorenzo Colombo', 'Italy', 'colombo'),
	('Lorenzo Colombo', 'Italy', 'lorenzo colombo'),
	('Julius Ertlthaler', 'Austria', 'ertlthaler'),
	('Julius Ertlthaler', 'Austria', 'julius ertlthaler'),
	('Ellis Iandolo', 'England', 'iandolo'),
	('Ellis Iandolo', 'England', 'ellis iandolo'),
	('Ben Coker', 'England', 'coker'),
	('Ben Coker', 'England', 'ben coker'),
	('Conor Wilkinson', 'Republic of Ireland', 'conor wilkinson'),
	('Conor Wilkinson', 'Republic of Ireland', 'wilkinson'),
	('Elias Abouchabaka', 'Germany', 'elias abouchabaka'),
	('Elias Abouchabaka', 'Germany', 'abouchabaka'),
	('Szymon Stasik', 'Poland', 'szymon stasik'),
	('Szymon Stasik', 'Poland', 'stasik'),
	('Hong Jung Nam', 'Korea Republic', 'nam'),
	('Hong Jung Nam', 'Korea Republic', 'hong jung nam'),
	('Anthony Correia', 'France', 'anthony correia'),
	('Anthony Correia', 'France', 'correia'),
	('Mateusz Hołownia', 'Poland', 'hoownia'),
	('Mateusz Hołownia', 'Poland', 'mateusz hoownia'),
	('Luca Ranieri', 'Italy', 'ranieri'),
	('Luca Ranieri', 'Italy', 'luca ranieri'),
	('Cristian Lasso', 'Colombia', 'cristian lasso'),
	('Cristian Lasso', 'Colombia', 'lasso'),
	('George Taft', 'England', 'george taft'),
	('George Taft', 'England', 'taft'),
	('Carlos Castro', 'Venezuela', 'castro'),
	('Carlos Castro', 'Venezuela', 'carlos castro'),
	('Filip Modelski', 'Poland', 'modelski'),
	('Filip Modelski', 'Poland', 'filip modelski'),
	('Andrew Lyons', 'Republic of Ireland', 'lyons'),
	('Andrew Lyons', 'Republic of Ireland', 'andrew lyons'),
	('Ouasim Bouy', 'Netherlands', 'ouasim bouy'),
	('Ouasim Bouy', 'Netherlands', 'bouy'),
	('Frantz Pangop', 'Cameroon', 'pangop'),
	('Frantz Pangop', 'Cameroon', 'frantz pangop'),
	('Dinny Corcoran', 'Republic of Ireland', 'dinny corcoran'),
	('Dinny Corcoran', 'Republic of Ireland', 'corcoran'),
	('Víctor Cabezas', 'Colombia', 'cabezas'),
	('Víctor Cabezas', 'Colombia', 'victor cabezas'),
	('Daiki Tomii', 'Japan', 'daiki tomii'),
	('Daiki Tomii', 'Japan', 'tomii'),
	('Jayden Nelson', 'Canada', 'nelson'),
	('Jayden Nelson', 'Canada', 'jayden nelson'),
	('Samed Onur', 'Turkey', 'onur'),
	('Samed Onur', 'Turkey', 'samed onur'),
	('Kim Hyo Gi', 'Korea Republic', 'gi'),
	('Kim Hyo Gi', 'Korea Republic', 'kim hyo gi'),
	('Mateusz Kuzimski', 'Poland', 'mateusz kuzimski'),
	('Mateusz Kuzimski', 'Poland', 'kuzimski'),
	('Luis Romero', 'Venezuela', 'luis romero'),
	('Luis Romero', 'Venezuela', 'romero'),
	('Yoan Severin', 'France', 'yoan severin'),
	('Yoan Severin', 'France', 'severin'),
	('Andrei Marinescu', 'Romania', 'andrei marinescu'),
	('Andrei Marinescu', 'Romania', 'marinescu'),
	('Moody Chana', 'Germany', 'chana'),
	('Moody Chana', 'Germany', 'moody chana'),
	('Louis Ameka Autchanga', 'Gabon', 'louis ameka autchanga'),
	('Louis Ameka Autchanga', 'Gabon', 'autchanga'),
	('Zak Dearnley', 'England', 'dearnley'),
	('Zak Dearnley', 'England', 'zak dearnley'),
	('José Peñarrieta', 'Bolivia', 'jose penarrieta'),
	('José Peñarrieta', 'Bolivia', 'penarrieta'),
	('Garry Buckley', 'Republic of Ireland', 'garry buckley'),
	('Garry Buckley', 'Republic of Ireland', 'buckley'),
	('Jerónimo Rodríguez', 'Mexico', 'rodriguez'),
	('Jerónimo Rodríguez', 'Mexico', 'jeronimo rodriguez'),
	('Siad Haji', 'United States', 'haji'),
	('Siad Haji', 'United States', 'siad haji'),
	('Mads Bidstrup', 'Denmark', 'bidstrup'),
	('Mads Bidstrup', 'Denmark', 'mads bidstrup'),
	('Dominic Bernard', 'Republic of Ireland', 'dominic bernard'),
	('Dominic Bernard', 'Republic of Ireland', 'bernard'),
	('Leonardo Terán', 'Venezuela', 'teran'),
	('Leonardo Terán', 'Venezuela', 'leonardo teran'),
	('Miguel Ángel', 'Spain', 'miguel angel'),
	('Miguel Ángel', 'Spain', 'angel'),
	('Gabriel Deac', 'Romania', 'deac'),
	('Gabriel Deac', 'Romania', 'gabriel deac'),
	('Emil Holm', 'Sweden', 'emil holm'),
	('Emil Holm', 'Sweden', 'holm'),
	('Thomas Van Den Keybus', 'Belgium', 'keybus'),
	('Thomas Van Den Keybus', 'Belgium', 'thomas van den keybus'),
	('Jake Eastwood', 'England', 'jake eastwood'),
	('Jake Eastwood', 'England', 'eastwood'),
	('Frazer Blake-Tracy', 'England', 'frazer blaketracy'),
	('Frazer Blake-Tracy', 'England', 'blaketracy'),
	('Daniel Segura', 'Ecuador', 'daniel segura'),
	('Daniel Segura', 'Ecuador', 'segura'),
	('Blaise Yaméogo', 'Burkina Faso', 'yameogo'),
	('Blaise Yaméogo', 'Burkina Faso', 'blaise yameogo'),
	('Ivan Ilić', 'Serbia', 'ilic'),
	('Ivan Ilić', 'Serbia', 'ivan ilic'),
	('Kevin Martin Krygård', 'Norway', 'kevin martin krygard'),
	('Kevin Martin Krygård', 'Norway', 'krygard'),
	('José Canale', 'Paraguay', 'jose canale'),
	('José Canale', 'Paraguay', 'canale'),
	('Alexi Pitu', 'Romania', 'alexi pitu'),
	('Alexi Pitu', 'Romania', 'pitu'),
	('Armin Đerlek', 'Serbia', 'armin erlek'),
	('Armin Đerlek', 'Serbia', 'erlek'),
	('Hamidou Maïga', 'Mali', 'hamidou maiga'),
	('Hamidou Maïga', 'Mali', 'maiga'),
	('Jair Yglesias', 'Peru', 'yglesias'),
	('Jair Yglesias', 'Peru', 'jair yglesias'),
	('Blake Bodily', 'United States', 'blake bodily'),
	('Blake Bodily', 'United States', 'bodily'),
	('Brandon Sartiaguin', 'Mexico', 'sartiaguin'),
	('Brandon Sartiaguin', 'Mexico', 'brandon sartiaguin'),
	('Kendall McIntosh', 'United States', 'kendall mcintosh'),
	('Kendall McIntosh', 'United States', 'mcintosh'),
	('Majed Hazazi', 'Saudi Arabia', 'majed hazazi'),
	('Majed Hazazi', 'Saudi Arabia', 'hazazi'),
	('Timothy Eyoma', 'England', 'eyoma'),
	('Timothy Eyoma', 'England', 'timothy eyoma'),
	('Jacob Italiano', 'Australia', 'jacob italiano'),
	('Jacob Italiano', 'Australia', 'italiano'),
	('Dominik Lanius', 'Germany', 'lanius'),
	('Dominik Lanius', 'Germany', 'dominik lanius'),
	('Iván Martín', 'Spain', 'ivan martin'),
	('Iván Martín', 'Spain', 'martin'),
	('Mauricio Guzmán', 'Argentina', 'mauricio guzman'),
	('Mauricio Guzmán', 'Argentina', 'guzman'),
	('Cristian Costin', 'Romania', 'cristian costin'),
	('Cristian Costin', 'Romania', 'costin'),
	('Jakub Arak', 'Poland', 'arak'),
	('Jakub Arak', 'Poland', 'jakub arak'),
	('Khaled Al Samiri', 'Saudi Arabia', 'samiri'),
	('Khaled Al Samiri', 'Saudi Arabia', 'khaled al samiri'),
	('Sean Mackie', 'Scotland', 'sean mackie'),
	('Sean Mackie', 'Scotland', 'mackie'),
	('Milciades Portillo', 'Paraguay', 'milciades portillo'),
	('Milciades Portillo', 'Paraguay', 'portillo'),
	('Ali Al Khaibari', 'Saudi Arabia', 'ali al khaibari'),
	('Ali Al Khaibari', 'Saudi Arabia', 'khaibari'),
	('Emmanuel Oyeleke', 'England', 'oyeleke'),
	('Emmanuel Oyeleke', 'England', 'emmanuel oyeleke'),
	('Sulayman Bojang', 'Gambia', 'sulayman bojang'),
	('Sulayman Bojang', 'Gambia', 'bojang'),
	('Răzvan Trif', 'Romania', 'razvan trif'),
	('Răzvan Trif', 'Romania', 'trif'),
	('Cameron Norman', 'England', 'cameron norman'),
	('Cameron Norman', 'England', 'norman'),
	('Diego Pampín', 'Spain', 'pampin'),
	('Diego Pampín', 'Spain', 'diego pampin'),
	('Yasser Larouci', 'Algeria', 'larouci'),
	('Yasser Larouci', 'Algeria', 'yasser larouci'),
	('Manuel Arteaga', 'Venezuela', 'manuel arteaga'),
	('Manuel Arteaga', 'Venezuela', 'arteaga'),
	('Matthäus Taferner', 'Austria', 'taferner'),
	('Matthäus Taferner', 'Austria', 'matthaus taferner'),
	('Mauro Osores', 'Argentina', 'mauro osores'),
	('Mauro Osores', 'Argentina', 'osores'),
	('Han Rongze', 'China PR', 'han rongze'),
	('Han Rongze', 'China PR', 'rongze'),
	('Shaun Brisley', 'England', 'brisley'),
	('Shaun Brisley', 'England', 'shaun brisley'),
	('Daiki Niwa', 'Japan', 'niwa'),
	('Daiki Niwa', 'Japan', 'daiki niwa'),
	('Saif Al Qeshtah', 'Saudi Arabia', 'qeshtah'),
	('Saif Al Qeshtah', 'Saudi Arabia', 'saif al qeshtah'),
	('Tiago Almeida', 'Portugal', 'almeida'),
	('Tiago Almeida', 'Portugal', 'tiago almeida'),
	('Franco Perinciolo', 'Argentina', 'perinciolo'),
	('Franco Perinciolo', 'Argentina', 'franco perinciolo'),
	('Henrik Gjesdal', 'Norway', 'henrik gjesdal'),
	('Henrik Gjesdal', 'Norway', 'gjesdal'),
	('Dániel Gyollai', 'Hungary', 'gyollai'),
	('Dániel Gyollai', 'Hungary', 'daniel gyollai'),
	('Alan Liebeskind', 'Venezuela', 'liebeskind'),
	('Alan Liebeskind', 'Venezuela', 'alan liebeskind'),
	('Rok Sirk', 'Slovenia', 'rok sirk'),
	('Rok Sirk', 'Slovenia', 'sirk'),
	('Franco Petroli', 'Argentina', 'petroli'),
	('Franco Petroli', 'Argentina', 'franco petroli')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';