INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Sin Se Gye', 'Korea Republic', 'player'),
	('Efkan Bekiroglu', 'Germany', 'player'),
	('Osvaldo Rodríguez', 'Mexico', 'player'),
	('Yoann Etienne', 'France', 'player'),
	('Blessing Eleke', 'Nigeria', 'player'),
	('Mads Albæk', 'Denmark', 'player'),
	('Tom Naylor', 'England', 'player'),
	('Apa', 'Spain', 'player'),
	('Kim Sung Joon', 'Korea Republic', 'player'),
	('Axel Ngando', 'France', 'player'),
	('Hólmbert Aron Friðjónsson', 'Iceland', 'player'),
	('Koya Kitagawa', 'Japan', 'player'),
	('Guillermo Molins', 'Sweden', 'player'),
	('Hedgardo Marín', 'Mexico', 'player'),
	('Ruan', 'Brazil', 'player'),
	('Eric Junior Dina Ebimbe', 'France', 'player'),
	('Bright Addae', 'Ghana', 'player'),
	('Alexander Alvarado', 'Ecuador', 'player'),
	('Demetri Mitchell', 'England', 'player'),
	('Maikel van der Werff', 'Netherlands', 'player'),
	('Christian Gebauer', 'Austria', 'player'),
	('Nicolás Ramírez', 'Chile', 'player'),
	('Hidde Jurjus', 'Netherlands', 'player'),
	('Nicandro Breeveld', 'Netherlands', 'player'),
	('Stephan Zwierschitz', 'Austria', 'player'),
	('Kazuki Nagasawa', 'Japan', 'player'),
	('Levan Shengelia', 'Georgia', 'player'),
	('Xavier Mous', 'Netherlands', 'player'),
	('Connor McLennan', 'Scotland', 'player'),
	('Gauthier Hein', 'France', 'player'),
	('Ibrahim Drešević', 'Kosovo', 'player'),
	('Vincent Sierro', 'Switzerland', 'player'),
	('Leandro Grimi', 'Argentina', 'player'),
	('Jimmy', 'Spain', 'player'),
	('Dženis Burnić', 'Germany', 'player'),
	('Tom van Weert', 'Netherlands', 'player'),
	('Ahmed Said', 'Italy', 'player'),
	('Karlo Bartolec', 'Croatia', 'player'),
	('Charlie Mulgrew', 'Scotland', 'player'),
	('Lucas Necul', 'Argentina', 'player'),
	('Jody Lukoki', 'DR Congo', 'player'),
	('Cristian Herrera', 'Spain', 'player'),
	('Mario Pavelić', 'Austria', 'player'),
	('Sebastián Prediger', 'Argentina', 'player'),
	('Christian Früchtl', 'Germany', 'player'),
	('Cristian Olivera', 'Uruguay', 'player'),
	('Konstantinos Triantafyllopoulos', 'Greece', 'player'),
	('Jordan Moore-Taylor', 'England', 'player'),
	('Mark van der Maarel', 'Netherlands', 'player'),
	('Ayase Ueda', 'Japan', 'player'),
	('Christophe Psyché', 'France', 'player'),
	('David Fällman', 'Sweden', 'player'),
	('Chris Hussey', 'England', 'player'),
	('Ridge Munsy', 'Switzerland', 'player'),
	('Luke Chambers', 'England', 'player'),
	('Kévin Soni', 'Cameroon', 'player'),
	('Silviu Balaure', 'Romania', 'player'),
	('Lazarous Kambole', 'Zambia', 'player'),
	('Keita Nakamura', 'Japan', 'player'),
	('Cláudio Winck', 'Brazil', 'player'),
	('Denis Drăguș', 'Romania', 'player'),
	('Diego Mendoza', 'Argentina', 'player'),
	('Luis Ojeda', 'Argentina', 'player'),
	('Rostyn Griffiths', 'Australia', 'player'),
	('Alvas Powell', 'Jamaica', 'player'),
	('Dani Escriche', 'Spain', 'player'),
	('Neto Volpi', 'Brazil', 'player'),
	('Jordan Adéoti', 'Benin', 'player'),
	('Sebastián Gularte', 'Uruguay', 'player'),
	('Marvin Pourié', 'Germany', 'player'),
	('Loïc Mbe Soh', 'France', 'player'),
	('James Husband', 'England', 'player'),
	('David Nugent', 'England', 'player'),
	('Lars Vilsvik', 'Norway', 'player'),
	('Alan Mannus', 'Northern Ireland', 'player'),
	('Oleksandr Tymchyk', 'Ukraine', 'player'),
	('Juan Ignacio Méndez', 'Argentina', 'player'),
	('Marlon Ritter', 'Germany', 'player'),
	('Petar Brlek', 'Croatia', 'player'),
	('Brendan Hines-Ike', 'United States', 'player'),
	('Fatih Aksoy', 'Turkey', 'player'),
	('Anderson Emanuel', 'Angola', 'player'),
	('Marcus Olsson', 'Sweden', 'player'),
	('Sullay Kaikai', 'England', 'player'),
	('Harry Souttar', 'Australia', 'player'),
	('Alan Medina', 'Mexico', 'player'),
	('Patrick McEleney', 'Republic of Ireland', 'player'),
	('Mustafa Malaeka', 'Saudi Arabia', 'player'),
	('Brian White', 'United States', 'player'),
	('Gaspar', 'Spain', 'player'),
	('Robert Mudražija', 'Croatia', 'player'),
	('Samuel Holmén', 'Sweden', 'player'),
	('Faneva Andriatsima', 'Madagascar', 'player'),
	('Cameron Brannagan', 'England', 'player'),
	('Emir Kujović', 'Sweden', 'player'),
	('Manjrekar James', 'Canada', 'player'),
	('Lombán', 'Spain', 'player'),
	('Olivier Custodio', 'Switzerland', 'player'),
	('Alain Baroja', 'Venezuela', 'player'),
	('David Batanero', 'Spain', 'player'),
	('Burak Çamoğlu', 'Turkey', 'player'),
	('Mohammed Jahfali', 'Saudi Arabia', 'player'),
	('Javi Navarro', 'Spain', 'player'),
	('Leandro Barreiro Martins', 'Luxembourg', 'player'),
	('Sergio Ruiz', 'Spain', 'player'),
	('Beryly Lubala', 'DR Congo', 'player'),
	('Nicky Devlin', 'Scotland', 'player'),
	('Alexandre De Bruyn', 'Belgium', 'player'),
	('Adam Zreľák', 'Slovakia', 'player'),
	('Abdoulaye Ba', 'Senegal', 'player'),
	('Marcus Harness', 'England', 'player'),
	('Roberto Massimo', 'Germany', 'player'),
	('Sebastian Saucedo', 'United States', 'player'),
	('Rubén Díez', 'Spain', 'player'),
	('Ali Alipour', 'Iran', 'player'),
	('Brian Rowe', 'United States', 'player'),
	('Felix Lohkemper', 'Germany', 'player'),
	('Christopher Wernitznig', 'Austria', 'player'),
	('Carles Salvador', 'Spain', 'player'),
	('Yonathan Andia', 'Chile', 'player'),
	('Randell Williams', 'England', 'player'),
	('Albin Granlund', 'Finland', 'player'),
	('John Goossens', 'Netherlands', 'player'),
	('Reda Kharchouch', 'Netherlands', 'player'),
	('Ibrahim Al Zubaidi', 'Saudi Arabia', 'player'),
	('Reko', 'Portugal', 'player'),
	('Mo Adams', 'England', 'player'),
	('Josema', 'Spain', 'player'),
	('Pep Chavarría', 'Spain', 'player'),
	('Javi Alonso', 'Spain', 'player'),
	('Rezan Corlu', 'Denmark', 'player'),
	('San Román', 'Spain', 'player'),
	('Yvo Calleros', 'Uruguay', 'player'),
	('Onur Bulut', 'Germany', 'player'),
	('Mohammed Salem', 'Saudi Arabia', 'player'),
	('Chris Führich', 'Germany', 'player'),
	('Vítor Ferreira', 'Portugal', 'player'),
	('Jonathan Pitroipa', 'Burkina Faso', 'player'),
	('Ipalibo Jack', 'Nigeria', 'player'),
	('Marcel Gaus', 'Germany', 'player'),
	('Jamal Maroof', 'United Arab Emirates', 'player'),
	('Romario Caicedo', 'Ecuador', 'player'),
	('José Aja', 'Uruguay', 'player'),
	('Marcos Miers', 'Paraguay', 'player'),
	('Pietro Pellegri', 'Italy', 'player'),
	('Isaac Atanga', 'Ghana', 'player'),
	('Romain Gall', 'United States', 'player'),
	('Ovidiu Hoban', 'Romania', 'player'),
	('Gonçalo Agrelos', 'Portugal', 'player'),
	('Wes Hoolahan', 'Republic of Ireland', 'player'),
	('Takuma Nishimura', 'Japan', 'player'),
	('Mohammed Abdulrahman', 'United Arab Emirates', 'player'),
	('Marlon Frey', 'Germany', 'player'),
	('Kingsley Michael', 'Nigeria', 'player'),
	('Chris Duvall', 'United States', 'player'),
	('Václav Černý', 'Czech Republic', 'player'),
	('Matty James', 'England', 'player'),
	('Medwin Biteghé', 'Gabon', 'player'),
	('Łukasz Burliga', 'Poland', 'player'),
	('Mikkel Andersen', 'Denmark', 'player'),
	('Constantin Dima', 'Romania', 'player'),
	('Dennis Jastrzembski', 'Germany', 'player'),
	('Jakob Haugaard', 'Denmark', 'player'),
	('Marvin Ajani', 'Germany', 'player'),
	('Adam Andersson', 'Sweden', 'player'),
	('Abdülkerim Bardakcı', 'Turkey', 'player'),
	('Michael Lumb', 'Denmark', 'player'),
	('Jakov Puljić', 'Croatia', 'player'),
	('Mats Solheim', 'Norway', 'player'),
	('Ha Chang Rae', 'Korea Republic', 'player'),
	('George Edmundson', 'England', 'player'),
	('Beto da Silva', 'Peru', 'player'),
	('Jeong Seung Won', 'Korea Republic', 'player'),
	('Jake Larsson', 'Sweden', 'player'),
	('Cheikhou Dieng', 'Senegal', 'player'),
	('Christian Grindheim', 'Norway', 'player'),
	('Andrés Martín', 'Spain', 'player'),
	('Matej Delač', 'Croatia', 'player'),
	('Federico Pereyra', 'Argentina', 'player'),
	('Louka Prip', 'Denmark', 'player'),
	('Marlon Torres', 'Colombia', 'player'),
	('Thibang Phete', 'South Africa', 'player'),
	('Michael Harriman', 'Republic of Ireland', 'player'),
	('Anas Tahiri', 'Morocco', 'player'),
	('Braydon Manu', 'Germany', 'player'),
	('Tomislav Štrkalj', 'Croatia', 'player'),
	('Rafał Pietrzak', 'Poland', 'player'),
	('Etienne Vaessen', 'Netherlands', 'player'),
	('Branco van den Boomen', 'Netherlands', 'player'),
	('James Sands', 'United States', 'player'),
	('Michiel Kramer', 'Netherlands', 'player'),
	('Dorian Diring', 'France', 'player'),
	('Silvan Sidler', 'Switzerland', 'player'),
	('Sergio López', 'Spain', 'player'),
	('Christian Kühlwetter', 'Germany', 'player'),
	('Tahith Chong', 'Netherlands', 'player'),
	('Romário Pires', 'Brazil', 'player'),
	('Marco Grüll', 'Austria', 'player'),
	('Cubillas', 'Spain', 'player'),
	('Zak Vyner', 'England', 'player'),
	('Carlos Servín', 'Paraguay', 'player'),
	('Marc Andre Schmerböck', 'Austria', 'player'),
	('Luis Cabrera', 'Chile', 'player'),
	('Jean Ruiz', 'France', 'player'),
	('Oumar Solet', 'France', 'player'),
	('Andrey Galabinov', 'Bulgaria', 'player'),
	('Daniel Georgievski', 'North Macedonia', 'player'),
	('Dominik Hładun', 'Poland', 'player'),
	('Jakub Wójcicki', 'Poland', 'player'),
	('Ousmane Cissokho', 'Senegal', 'player'),
	('Luke Garbutt', 'England', 'player'),
	('Im Seon Yeong', 'Korea Republic', 'player'),
	('Takuya Wada', 'Japan', 'player'),
	('Ángel Martínez', 'Spain', 'player'),
	('Donovan Léon', 'France', 'player'),
	('Jack Hendry', 'Scotland', 'player'),
	('Hans Mulder', 'Netherlands', 'player'),
	('Jerome Opoku', 'England', 'player'),
	('Amine Atouchi', 'Morocco', 'player'),
	('Jesse Sekidika', 'Nigeria', 'player'),
	('Rafał Wolski', 'Poland', 'player'),
	('Noah Sonko Sundberg', 'Sweden', 'player'),
	('Yu Rui', 'China PR', 'player'),
	('Charlie Kirk', 'England', 'player'),
	('Lindon Selahi', 'Albania', 'player'),
	('James McKeown', 'Republic of Ireland', 'player'),
	('Paul Iacob', 'Romania', 'player'),
	('Tommy Høiland', 'Norway', 'player'),
	('Matej Oravec', 'Slovakia', 'player'),
	('Tunahan Çiçek', 'Switzerland', 'player'),
	('Camilo Ayala', 'Colombia', 'player'),
	('Lenny Pintor', 'France', 'player'),
	('John Brayford', 'England', 'player'),
	('Marco Sala', 'Italy', 'player'),
	('Kenneth Taylor', 'Netherlands', 'player'),
	('Jan Kirchhoff', 'Germany', 'player'),
	('Aaron Pierre', 'Grenada', 'player'),
	('Mateusz Mak', 'Poland', 'player'),
	('Mikey Devlin', 'Scotland', 'player'),
	('Ozkoidi', 'Spain', 'player'),
	('Maracás', 'Brazil', 'player'),
	('André Calisir', 'Armenia', 'player'),
	('Ali Abdi', 'Tunisia', 'player'),
	('Gégé', 'Cape Verde', 'player'),
	('Carlos Vargas', 'Mexico', 'player'),
	('Michael O''Halloran', 'Scotland', 'player'),
	('Tony Watt', 'Scotland', 'player'),
	('Neluț Roșu', 'Romania', 'player'),
	('Ángelo Preciado', 'Ecuador', 'player'),
	('Gianluca Korte', 'Germany', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Sin Se Gye', 'Korea Republic', 'sin se gye'),
	('Sin Se Gye', 'Korea Republic', 'gye'),
	('Efkan Bekiroglu', 'Germany', 'efkan bekiroglu'),
	('Efkan Bekiroglu', 'Germany', 'bekiroglu'),
	('Osvaldo Rodríguez', 'Mexico', 'osvaldo rodriguez'),
	('Osvaldo Rodríguez', 'Mexico', 'rodriguez'),
	('Yoann Etienne', 'France', 'etienne'),
	('Yoann Etienne', 'France', 'yoann etienne'),
	('Blessing Eleke', 'Nigeria', 'blessing eleke'),
	('Blessing Eleke', 'Nigeria', 'eleke'),
	('Mads Albæk', 'Denmark', 'mads albk'),
	('Mads Albæk', 'Denmark', 'albk'),
	('Tom Naylor', 'England', 'tom naylor'),
	('Tom Naylor', 'England', 'naylor'),
	('Apa', 'Spain', 'apa'),
	('Kim Sung Joon', 'Korea Republic', 'joon'),
	('Kim Sung Joon', 'Korea Republic', 'kim sung joon'),
	('Axel Ngando', 'France', 'axel ngando'),
	('Axel Ngando', 'France', 'ngando'),
	('Hólmbert Aron Friðjónsson', 'Iceland', 'holmbert aron frijonsson'),
	('Hólmbert Aron Friðjónsson', 'Iceland', 'frijonsson'),
	('Koya Kitagawa', 'Japan', 'koya kitagawa'),
	('Koya Kitagawa', 'Japan', 'kitagawa'),
	('Guillermo Molins', 'Sweden', 'molins'),
	('Guillermo Molins', 'Sweden', 'guillermo molins'),
	('Hedgardo Marín', 'Mexico', 'hedgardo marin'),
	('Hedgardo Marín', 'Mexico', 'marin'),
	('Ruan', 'Brazil', 'ruan'),
	('Eric Junior Dina Ebimbe', 'France', 'eric junior dina ebimbe'),
	('Eric Junior Dina Ebimbe', 'France', 'ebimbe'),
	('Bright Addae', 'Ghana', 'bright addae'),
	('Bright Addae', 'Ghana', 'addae'),
	('Alexander Alvarado', 'Ecuador', 'alexander alvarado'),
	('Alexander Alvarado', 'Ecuador', 'alvarado'),
	('Demetri Mitchell', 'England', 'mitchell'),
	('Demetri Mitchell', 'England', 'demetri mitchell'),
	('Maikel van der Werff', 'Netherlands', 'werff'),
	('Maikel van der Werff', 'Netherlands', 'maikel van der werff'),
	('Christian Gebauer', 'Austria', 'gebauer'),
	('Christian Gebauer', 'Austria', 'christian gebauer'),
	('Nicolás Ramírez', 'Chile', 'ramirez'),
	('Nicolás Ramírez', 'Chile', 'nicolas ramirez'),
	('Hidde Jurjus', 'Netherlands', 'hidde jurjus'),
	('Hidde Jurjus', 'Netherlands', 'jurjus'),
	('Nicandro Breeveld', 'Netherlands', 'nicandro breeveld'),
	('Nicandro Breeveld', 'Netherlands', 'breeveld'),
	('Stephan Zwierschitz', 'Austria', 'stephan zwierschitz'),
	('Stephan Zwierschitz', 'Austria', 'zwierschitz'),
	('Kazuki Nagasawa', 'Japan', 'kazuki nagasawa'),
	('Kazuki Nagasawa', 'Japan', 'nagasawa'),
	('Levan Shengelia', 'Georgia', 'levan shengelia'),
	('Levan Shengelia', 'Georgia', 'shengelia'),
	('Xavier Mous', 'Netherlands', 'mous'),
	('Xavier Mous', 'Netherlands', 'xavier mous'),
	('Connor McLennan', 'Scotland', 'connor mclennan'),
	('Connor McLennan', 'Scotland', 'mclennan'),
	('Gauthier Hein', 'France', 'hein'),
	('Gauthier Hein', 'France', 'gauthier hein'),
	('Ibrahim Drešević', 'Kosovo', 'ibrahim dresevic'),
	('Ibrahim Drešević', 'Kosovo', 'dresevic'),
	('Vincent Sierro', 'Switzerland', 'sierro'),
	('Vincent Sierro', 'Switzerland', 'vincent sierro'),
	('Leandro Grimi', 'Argentina', 'leandro grimi'),
	('Leandro Grimi', 'Argentina', 'grimi'),
	('Jimmy', 'Spain', 'jimmy'),
	('Dženis Burnić', 'Germany', 'burnic'),
	('Dženis Burnić', 'Germany', 'dzenis burnic'),
	('Tom van Weert', 'Netherlands', 'weert'),
	('Tom van Weert', 'Netherlands', 'tom van weert'),
	('Ahmed Said', 'Italy', 'ahmed said'),
	('Ahmed Said', 'Italy', 'said'),
	('Karlo Bartolec', 'Croatia', 'bartolec'),
	('Karlo Bartolec', 'Croatia', 'karlo bartolec'),
	('Charlie Mulgrew', 'Scotland', 'mulgrew'),
	('Charlie Mulgrew', 'Scotland', 'charlie mulgrew'),
	('Lucas Necul', 'Argentina', 'necul'),
	('Lucas Necul', 'Argentina', 'lucas necul'),
	('Jody Lukoki', 'DR Congo', 'lukoki'),
	('Jody Lukoki', 'DR Congo', 'jody lukoki'),
	('Cristian Herrera', 'Spain', 'cristian herrera'),
	('Cristian Herrera', 'Spain', 'herrera'),
	('Mario Pavelić', 'Austria', 'pavelic'),
	('Mario Pavelić', 'Austria', 'mario pavelic'),
	('Sebastián Prediger', 'Argentina', 'sebastian prediger'),
	('Sebastián Prediger', 'Argentina', 'prediger'),
	('Christian Früchtl', 'Germany', 'fruchtl'),
	('Christian Früchtl', 'Germany', 'christian fruchtl'),
	('Cristian Olivera', 'Uruguay', 'cristian olivera'),
	('Cristian Olivera', 'Uruguay', 'olivera'),
	('Konstantinos Triantafyllopoulos', 'Greece', 'triantafyllopoulos'),
	('Konstantinos Triantafyllopoulos', 'Greece', 'konstantinos triantafyllopoulos'),
	('Jordan Moore-Taylor', 'England', 'jordan mooretaylor'),
	('Jordan Moore-Taylor', 'England', 'mooretaylor'),
	('Mark van der Maarel', 'Netherlands', 'maarel'),
	('Mark van der Maarel', 'Netherlands', 'mark van der maarel'),
	('Ayase Ueda', 'Japan', 'ueda'),
	('Ayase Ueda', 'Japan', 'ayase ueda'),
	('Christophe Psyché', 'France', 'psyche'),
	('Christophe Psyché', 'France', 'christophe psyche'),
	('David Fällman', 'Sweden', 'fallman'),
	('David Fällman', 'Sweden', 'david fallman'),
	('Chris Hussey', 'England', 'chris hussey'),
	('Chris Hussey', 'England', 'hussey'),
	('Ridge Munsy', 'Switzerland', 'ridge munsy'),
	('Ridge Munsy', 'Switzerland', 'munsy'),
	('Luke Chambers', 'England', 'chambers'),
	('Luke Chambers', 'England', 'luke chambers'),
	('Kévin Soni', 'Cameroon', 'kevin soni'),
	('Kévin Soni', 'Cameroon', 'soni'),
	('Silviu Balaure', 'Romania', 'balaure'),
	('Silviu Balaure', 'Romania', 'silviu balaure'),
	('Lazarous Kambole', 'Zambia', 'lazarous kambole'),
	('Lazarous Kambole', 'Zambia', 'kambole'),
	('Keita Nakamura', 'Japan', 'nakamura'),
	('Keita Nakamura', 'Japan', 'keita nakamura'),
	('Cláudio Winck', 'Brazil', 'winck'),
	('Cláudio Winck', 'Brazil', 'claudio winck'),
	('Denis Drăguș', 'Romania', 'dragus'),
	('Denis Drăguș', 'Romania', 'denis dragus'),
	('Diego Mendoza', 'Argentina', 'mendoza'),
	('Diego Mendoza', 'Argentina', 'diego mendoza'),
	('Luis Ojeda', 'Argentina', 'ojeda'),
	('Luis Ojeda', 'Argentina', 'luis ojeda'),
	('Rostyn Griffiths', 'Australia', 'rostyn griffiths'),
	('Rostyn Griffiths', 'Australia', 'griffiths'),
	('Alvas Powell', 'Jamaica', 'powell'),
	('Alvas Powell', 'Jamaica', 'alvas powell'),
	('Dani Escriche', 'Spain', 'escriche'),
	('Dani Escriche', 'Spain', 'dani escriche'),
	('Neto Volpi', 'Brazil', 'neto volpi'),
	('Neto Volpi', 'Brazil', 'volpi'),
	('Jordan Adéoti', 'Benin', 'adeoti'),
	('Jordan Adéoti', 'Benin', 'jordan adeoti'),
	('Sebastián Gularte', 'Uruguay', 'gularte'),
	('Sebastián Gularte', 'Uruguay', 'sebastian gularte'),
	('Marvin Pourié', 'Germany', 'marvin pourie'),
	('Marvin Pourié', 'Germany', 'pourie'),
	('Loïc Mbe Soh', 'France', 'loic mbe soh'),
	('Loïc Mbe Soh', 'France', 'soh'),
	('James Husband', 'England', 'james husband'),
	('James Husband', 'England', 'husband'),
	('David Nugent', 'England', 'david nugent'),
	('David Nugent', 'England', 'nugent'),
	('Lars Vilsvik', 'Norway', 'lars vilsvik'),
	('Lars Vilsvik', 'Norway', 'vilsvik'),
	('Alan Mannus', 'Northern Ireland', 'mannus'),
	('Alan Mannus', 'Northern Ireland', 'alan mannus'),
	('Oleksandr Tymchyk', 'Ukraine', 'tymchyk'),
	('Oleksandr Tymchyk', 'Ukraine', 'oleksandr tymchyk'),
	('Juan Ignacio Méndez', 'Argentina', 'mendez'),
	('Juan Ignacio Méndez', 'Argentina', 'juan ignacio mendez'),
	('Marlon Ritter', 'Germany', 'ritter'),
	('Marlon Ritter', 'Germany', 'marlon ritter'),
	('Petar Brlek', 'Croatia', 'petar brlek'),
	('Petar Brlek', 'Croatia', 'brlek'),
	('Brendan Hines-Ike', 'United States', 'hinesike'),
	('Brendan Hines-Ike', 'United States', 'brendan hinesike'),
	('Fatih Aksoy', 'Turkey', 'aksoy'),
	('Fatih Aksoy', 'Turkey', 'fatih aksoy'),
	('Anderson Emanuel', 'Angola', 'emanuel'),
	('Anderson Emanuel', 'Angola', 'anderson emanuel'),
	('Marcus Olsson', 'Sweden', 'marcus olsson'),
	('Marcus Olsson', 'Sweden', 'olsson'),
	('Sullay Kaikai', 'England', 'kaikai'),
	('Sullay Kaikai', 'England', 'sullay kaikai'),
	('Harry Souttar', 'Australia', 'harry souttar'),
	('Harry Souttar', 'Australia', 'souttar'),
	('Alan Medina', 'Mexico', 'alan medina'),
	('Alan Medina', 'Mexico', 'medina'),
	('Patrick McEleney', 'Republic of Ireland', 'patrick mceleney'),
	('Patrick McEleney', 'Republic of Ireland', 'mceleney'),
	('Mustafa Malaeka', 'Saudi Arabia', 'malaeka'),
	('Mustafa Malaeka', 'Saudi Arabia', 'mustafa malaeka'),
	('Brian White', 'United States', 'white'),
	('Brian White', 'United States', 'brian white'),
	('Gaspar', 'Spain', 'gaspar'),
	('Robert Mudražija', 'Croatia', 'mudrazija'),
	('Robert Mudražija', 'Croatia', 'robert mudrazija'),
	('Samuel Holmén', 'Sweden', 'holmen'),
	('Samuel Holmén', 'Sweden', 'samuel holmen'),
	('Faneva Andriatsima', 'Madagascar', 'faneva andriatsima'),
	('Faneva Andriatsima', 'Madagascar', 'andriatsima'),
	('Cameron Brannagan', 'England', 'cameron brannagan'),
	('Cameron Brannagan', 'England', 'brannagan'),
	('Emir Kujović', 'Sweden', 'emir kujovic'),
	('Emir Kujović', 'Sweden', 'kujovic'),
	('Manjrekar James', 'Canada', 'manjrekar james'),
	('Manjrekar James', 'Canada', 'james'),
	('Lombán', 'Spain', 'lomban'),
	('Olivier Custodio', 'Switzerland', 'olivier custodio'),
	('Olivier Custodio', 'Switzerland', 'custodio'),
	('Alain Baroja', 'Venezuela', 'alain baroja'),
	('Alain Baroja', 'Venezuela', 'baroja'),
	('David Batanero', 'Spain', 'batanero'),
	('David Batanero', 'Spain', 'david batanero'),
	('Burak Çamoğlu', 'Turkey', 'camoglu'),
	('Burak Çamoğlu', 'Turkey', 'burak camoglu'),
	('Mohammed Jahfali', 'Saudi Arabia', 'jahfali'),
	('Mohammed Jahfali', 'Saudi Arabia', 'mohammed jahfali'),
	('Javi Navarro', 'Spain', 'navarro'),
	('Javi Navarro', 'Spain', 'javi navarro'),
	('Leandro Barreiro Martins', 'Luxembourg', 'leandro barreiro martins'),
	('Leandro Barreiro Martins', 'Luxembourg', 'martins'),
	('Sergio Ruiz', 'Spain', 'ruiz'),
	('Sergio Ruiz', 'Spain', 'sergio ruiz'),
	('Beryly Lubala', 'DR Congo', 'beryly lubala'),
	('Beryly Lubala', 'DR Congo', 'lubala'),
	('Nicky Devlin', 'Scotland', 'nicky devlin'),
	('Nicky Devlin', 'Scotland', 'devlin'),
	('Alexandre De Bruyn', 'Belgium', 'alexandre de bruyn'),
	('Alexandre De Bruyn', 'Belgium', 'bruyn'),
	('Adam Zreľák', 'Slovakia', 'zrelak'),
	('Adam Zreľák', 'Slovakia', 'adam zrelak'),
	('Abdoulaye Ba', 'Senegal', 'ba'),
	('Abdoulaye Ba', 'Senegal', 'abdoulaye ba'),
	('Marcus Harness', 'England', 'harness'),
	('Marcus Harness', 'England', 'marcus harness'),
	('Roberto Massimo', 'Germany', 'roberto massimo'),
	('Roberto Massimo', 'Germany', 'massimo'),
	('Sebastian Saucedo', 'United States', 'saucedo'),
	('Sebastian Saucedo', 'United States', 'sebastian saucedo'),
	('Rubén Díez', 'Spain', 'diez'),
	('Rubén Díez', 'Spain', 'ruben diez'),
	('Ali Alipour', 'Iran', 'ali alipour'),
	('Ali Alipour', 'Iran', 'alipour'),
	('Brian Rowe', 'United States', 'brian rowe'),
	('Brian Rowe', 'United States', 'rowe'),
	('Felix Lohkemper', 'Germany', 'lohkemper'),
	('Felix Lohkemper', 'Germany', 'felix lohkemper'),
	('Christopher Wernitznig', 'Austria', 'christopher wernitznig'),
	('Christopher Wernitznig', 'Austria', 'wernitznig'),
	('Carles Salvador', 'Spain', 'carles salvador'),
	('Carles Salvador', 'Spain', 'salvador'),
	('Yonathan Andia', 'Chile', 'yonathan andia'),
	('Yonathan Andia', 'Chile', 'andia'),
	('Randell Williams', 'England', 'randell williams'),
	('Randell Williams', 'England', 'williams'),
	('Albin Granlund', 'Finland', 'granlund'),
	('Albin Granlund', 'Finland', 'albin granlund'),
	('John Goossens', 'Netherlands', 'john goossens'),
	('John Goossens', 'Netherlands', 'goossens'),
	('Reda Kharchouch', 'Netherlands', 'kharchouch'),
	('Reda Kharchouch', 'Netherlands', 'reda kharchouch'),
	('Ibrahim Al Zubaidi', 'Saudi Arabia', 'ibrahim al zubaidi'),
	('Ibrahim Al Zubaidi', 'Saudi Arabia', 'zubaidi'),
	('Reko', 'Portugal', 'reko'),
	('Mo Adams', 'England', 'mo adams'),
	('Mo Adams', 'England', 'adams'),
	('Josema', 'Spain', 'josema'),
	('Pep Chavarría', 'Spain', 'chavarria'),
	('Pep Chavarría', 'Spain', 'pep chavarria'),
	('Javi Alonso', 'Spain', 'alonso'),
	('Javi Alonso', 'Spain', 'javi alonso'),
	('Rezan Corlu', 'Denmark', 'rezan corlu'),
	('Rezan Corlu', 'Denmark', 'corlu'),
	('San Román', 'Spain', 'roman'),
	('San Román', 'Spain', 'san roman'),
	('Yvo Calleros', 'Uruguay', 'calleros'),
	('Yvo Calleros', 'Uruguay', 'yvo calleros'),
	('Onur Bulut', 'Germany', 'bulut'),
	('Onur Bulut', 'Germany', 'onur bulut'),
	('Mohammed Salem', 'Saudi Arabia', 'salem'),
	('Mohammed Salem', 'Saudi Arabia', 'mohammed salem'),
	('Chris Führich', 'Germany', 'chris fuhrich'),
	('Chris Führich', 'Germany', 'fuhrich'),
	('Vítor Ferreira', 'Portugal', 'vitor ferreira'),
	('Vítor Ferreira', 'Portugal', 'ferreira'),
	('Jonathan Pitroipa', 'Burkina Faso', 'jonathan pitroipa'),
	('Jonathan Pitroipa', 'Burkina Faso', 'pitroipa'),
	('Ipalibo Jack', 'Nigeria', 'jack'),
	('Ipalibo Jack', 'Nigeria', 'ipalibo jack'),
	('Marcel Gaus', 'Germany', 'gaus'),
	('Marcel Gaus', 'Germany', 'marcel gaus'),
	('Jamal Maroof', 'United Arab Emirates', 'jamal maroof'),
	('Jamal Maroof', 'United Arab Emirates', 'maroof'),
	('Romario Caicedo', 'Ecuador', 'romario caicedo'),
	('Romario Caicedo', 'Ecuador', 'caicedo'),
	('José Aja', 'Uruguay', 'aja'),
	('José Aja', 'Uruguay', 'jose aja'),
	('Marcos Miers', 'Paraguay', 'marcos miers'),
	('Marcos Miers', 'Paraguay', 'miers'),
	('Pietro Pellegri', 'Italy', 'pellegri'),
	('Pietro Pellegri', 'Italy', 'pietro pellegri'),
	('Isaac Atanga', 'Ghana', 'atanga'),
	('Isaac Atanga', 'Ghana', 'isaac atanga'),
	('Romain Gall', 'United States', 'romain gall'),
	('Romain Gall', 'United States', 'gall'),
	('Ovidiu Hoban', 'Romania', 'ovidiu hoban'),
	('Ovidiu Hoban', 'Romania', 'hoban'),
	('Gonçalo Agrelos', 'Portugal', 'goncalo agrelos'),
	('Gonçalo Agrelos', 'Portugal', 'agrelos'),
	('Wes Hoolahan', 'Republic of Ireland', 'hoolahan'),
	('Wes Hoolahan', 'Republic of Ireland', 'wes hoolahan'),
	('Takuma Nishimura', 'Japan', 'takuma nishimura'),
	('Takuma Nishimura', 'Japan', 'nishimura'),
	('Mohammed Abdulrahman', 'United Arab Emirates', 'mohammed abdulrahman'),
	('Mohammed Abdulrahman', 'United Arab Emirates', 'abdulrahman'),
	('Marlon Frey', 'Germany', 'marlon frey'),
	('Marlon Frey', 'Germany', 'frey'),
	('Kingsley Michael', 'Nigeria', 'michael'),
	('Kingsley Michael', 'Nigeria', 'kingsley michael'),
	('Chris Duvall', 'United States', 'chris duvall'),
	('Chris Duvall', 'United States', 'duvall'),
	('Václav Černý', 'Czech Republic', 'vaclav cerny'),
	('Václav Černý', 'Czech Republic', 'cerny'),
	('Matty James', 'England', 'matty james'),
	('Matty James', 'England', 'james'),
	('Medwin Biteghé', 'Gabon', 'biteghe'),
	('Medwin Biteghé', 'Gabon', 'medwin biteghe'),
	('Łukasz Burliga', 'Poland', 'ukasz burliga'),
	('Łukasz Burliga', 'Poland', 'burliga'),
	('Mikkel Andersen', 'Denmark', 'andersen'),
	('Mikkel Andersen', 'Denmark', 'mikkel andersen'),
	('Constantin Dima', 'Romania', 'dima'),
	('Constantin Dima', 'Romania', 'constantin dima'),
	('Dennis Jastrzembski', 'Germany', 'jastrzembski'),
	('Dennis Jastrzembski', 'Germany', 'dennis jastrzembski'),
	('Jakob Haugaard', 'Denmark', 'jakob haugaard'),
	('Jakob Haugaard', 'Denmark', 'haugaard'),
	('Marvin Ajani', 'Germany', 'ajani'),
	('Marvin Ajani', 'Germany', 'marvin ajani'),
	('Adam Andersson', 'Sweden', 'adam andersson'),
	('Adam Andersson', 'Sweden', 'andersson'),
	('Abdülkerim Bardakcı', 'Turkey', 'abdulkerim bardakc'),
	('Abdülkerim Bardakcı', 'Turkey', 'bardakc'),
	('Michael Lumb', 'Denmark', 'lumb'),
	('Michael Lumb', 'Denmark', 'michael lumb'),
	('Jakov Puljić', 'Croatia', 'jakov puljic'),
	('Jakov Puljić', 'Croatia', 'puljic'),
	('Mats Solheim', 'Norway', 'mats solheim'),
	('Mats Solheim', 'Norway', 'solheim'),
	('Ha Chang Rae', 'Korea Republic', 'rae'),
	('Ha Chang Rae', 'Korea Republic', 'ha chang rae'),
	('George Edmundson', 'England', 'edmundson'),
	('George Edmundson', 'England', 'george edmundson'),
	('Beto da Silva', 'Peru', 'silva'),
	('Beto da Silva', 'Peru', 'beto da silva'),
	('Jeong Seung Won', 'Korea Republic', 'jeong seung won'),
	('Jeong Seung Won', 'Korea Republic', 'won'),
	('Jake Larsson', 'Sweden', 'jake larsson'),
	('Jake Larsson', 'Sweden', 'larsson'),
	('Cheikhou Dieng', 'Senegal', 'dieng'),
	('Cheikhou Dieng', 'Senegal', 'cheikhou dieng'),
	('Christian Grindheim', 'Norway', 'grindheim'),
	('Christian Grindheim', 'Norway', 'christian grindheim'),
	('Andrés Martín', 'Spain', 'andres martin'),
	('Andrés Martín', 'Spain', 'martin'),
	('Matej Delač', 'Croatia', 'delac'),
	('Matej Delač', 'Croatia', 'matej delac'),
	('Federico Pereyra', 'Argentina', 'pereyra'),
	('Federico Pereyra', 'Argentina', 'federico pereyra'),
	('Louka Prip', 'Denmark', 'louka prip'),
	('Louka Prip', 'Denmark', 'prip'),
	('Marlon Torres', 'Colombia', 'torres'),
	('Marlon Torres', 'Colombia', 'marlon torres'),
	('Thibang Phete', 'South Africa', 'phete'),
	('Thibang Phete', 'South Africa', 'thibang phete'),
	('Michael Harriman', 'Republic of Ireland', 'harriman'),
	('Michael Harriman', 'Republic of Ireland', 'michael harriman'),
	('Anas Tahiri', 'Morocco', 'anas tahiri'),
	('Anas Tahiri', 'Morocco', 'tahiri'),
	('Braydon Manu', 'Germany', 'braydon manu'),
	('Braydon Manu', 'Germany', 'manu'),
	('Tomislav Štrkalj', 'Croatia', 'strkalj'),
	('Tomislav Štrkalj', 'Croatia', 'tomislav strkalj'),
	('Rafał Pietrzak', 'Poland', 'rafa pietrzak'),
	('Rafał Pietrzak', 'Poland', 'pietrzak'),
	('Etienne Vaessen', 'Netherlands', 'vaessen'),
	('Etienne Vaessen', 'Netherlands', 'etienne vaessen'),
	('Branco van den Boomen', 'Netherlands', 'branco van den boomen'),
	('Branco van den Boomen', 'Netherlands', 'boomen'),
	('James Sands', 'United States', 'sands'),
	('James Sands', 'United States', 'james sands'),
	('Michiel Kramer', 'Netherlands', 'kramer'),
	('Michiel Kramer', 'Netherlands', 'michiel kramer'),
	('Dorian Diring', 'France', 'dorian diring'),
	('Dorian Diring', 'France', 'diring'),
	('Silvan Sidler', 'Switzerland', 'silvan sidler'),
	('Silvan Sidler', 'Switzerland', 'sidler'),
	('Sergio López', 'Spain', 'lopez'),
	('Sergio López', 'Spain', 'sergio lopez'),
	('Christian Kühlwetter', 'Germany', 'kuhlwetter'),
	('Christian Kühlwetter', 'Germany', 'christian kuhlwetter'),
	('Tahith Chong', 'Netherlands', 'tahith chong'),
	('Tahith Chong', 'Netherlands', 'chong'),
	('Romário Pires', 'Brazil', 'romario pires'),
	('Romário Pires', 'Brazil', 'pires'),
	('Marco Grüll', 'Austria', 'marco grull'),
	('Marco Grüll', 'Austria', 'grull'),
	('Cubillas', 'Spain', 'cubillas'),
	('Zak Vyner', 'England', 'zak vyner'),
	('Zak Vyner', 'England', 'vyner'),
	('Carlos Servín', 'Paraguay', 'servin'),
	('Carlos Servín', 'Paraguay', 'carlos servin'),
	('Marc Andre Schmerböck', 'Austria', 'schmerbock'),
	('Marc Andre Schmerböck', 'Austria', 'marc andre schmerbock'),
	('Luis Cabrera', 'Chile', 'luis cabrera'),
	('Luis Cabrera', 'Chile', 'cabrera'),
	('Jean Ruiz', 'France', 'ruiz'),
	('Jean Ruiz', 'France', 'jean ruiz'),
	('Oumar Solet', 'France', 'oumar solet'),
	('Oumar Solet', 'France', 'solet'),
	('Andrey Galabinov', 'Bulgaria', 'andrey galabinov'),
	('Andrey Galabinov', 'Bulgaria', 'galabinov'),
	('Daniel Georgievski', 'North Macedonia', 'daniel georgievski'),
	('Daniel Georgievski', 'North Macedonia', 'georgievski'),
	('Dominik Hładun', 'Poland', 'dominik hadun'),
	('Dominik Hładun', 'Poland', 'hadun'),
	('Jakub Wójcicki', 'Poland', 'jakub wojcicki'),
	('Jakub Wójcicki', 'Poland', 'wojcicki'),
	('Ousmane Cissokho', 'Senegal', 'ousmane cissokho'),
	('Ousmane Cissokho', 'Senegal', 'cissokho'),
	('Luke Garbutt', 'England', 'luke garbutt'),
	('Luke Garbutt', 'England', 'garbutt'),
	('Im Seon Yeong', 'Korea Republic', 'im seon yeong'),
	('Im Seon Yeong', 'Korea Republic', 'yeong'),
	('Takuya Wada', 'Japan', 'wada'),
	('Takuya Wada', 'Japan', 'takuya wada'),
	('Ángel Martínez', 'Spain', 'martinez'),
	('Ángel Martínez', 'Spain', 'angel martinez'),
	('Donovan Léon', 'France', 'leon'),
	('Donovan Léon', 'France', 'donovan leon'),
	('Jack Hendry', 'Scotland', 'hendry'),
	('Jack Hendry', 'Scotland', 'jack hendry'),
	('Hans Mulder', 'Netherlands', 'mulder'),
	('Hans Mulder', 'Netherlands', 'hans mulder'),
	('Jerome Opoku', 'England', 'opoku'),
	('Jerome Opoku', 'England', 'jerome opoku'),
	('Amine Atouchi', 'Morocco', 'amine atouchi'),
	('Amine Atouchi', 'Morocco', 'atouchi'),
	('Jesse Sekidika', 'Nigeria', 'sekidika'),
	('Jesse Sekidika', 'Nigeria', 'jesse sekidika'),
	('Rafał Wolski', 'Poland', 'rafa wolski'),
	('Rafał Wolski', 'Poland', 'wolski'),
	('Noah Sonko Sundberg', 'Sweden', 'noah sonko sundberg'),
	('Noah Sonko Sundberg', 'Sweden', 'sundberg'),
	('Yu Rui', 'China PR', 'rui'),
	('Yu Rui', 'China PR', 'yu rui'),
	('Charlie Kirk', 'England', 'charlie kirk'),
	('Charlie Kirk', 'England', 'kirk'),
	('Lindon Selahi', 'Albania', 'selahi'),
	('Lindon Selahi', 'Albania', 'lindon selahi'),
	('James McKeown', 'Republic of Ireland', 'james mckeown'),
	('James McKeown', 'Republic of Ireland', 'mckeown'),
	('Paul Iacob', 'Romania', 'iacob'),
	('Paul Iacob', 'Romania', 'paul iacob'),
	('Tommy Høiland', 'Norway', 'hiland'),
	('Tommy Høiland', 'Norway', 'tommy hiland'),
	('Matej Oravec', 'Slovakia', 'matej oravec'),
	('Matej Oravec', 'Slovakia', 'oravec'),
	('Tunahan Çiçek', 'Switzerland', 'cicek'),
	('Tunahan Çiçek', 'Switzerland', 'tunahan cicek'),
	('Camilo Ayala', 'Colombia', 'ayala'),
	('Camilo Ayala', 'Colombia', 'camilo ayala'),
	('Lenny Pintor', 'France', 'pintor'),
	('Lenny Pintor', 'France', 'lenny pintor'),
	('John Brayford', 'England', 'brayford'),
	('John Brayford', 'England', 'john brayford'),
	('Marco Sala', 'Italy', 'sala'),
	('Marco Sala', 'Italy', 'marco sala'),
	('Kenneth Taylor', 'Netherlands', 'taylor'),
	('Kenneth Taylor', 'Netherlands', 'kenneth taylor'),
	('Jan Kirchhoff', 'Germany', 'kirchhoff'),
	('Jan Kirchhoff', 'Germany', 'jan kirchhoff'),
	('Aaron Pierre', 'Grenada', 'aaron pierre'),
	('Aaron Pierre', 'Grenada', 'pierre'),
	('Mateusz Mak', 'Poland', 'mateusz mak'),
	('Mateusz Mak', 'Poland', 'mak'),
	('Mikey Devlin', 'Scotland', 'mikey devlin'),
	('Mikey Devlin', 'Scotland', 'devlin'),
	('Ozkoidi', 'Spain', 'ozkoidi'),
	('Maracás', 'Brazil', 'maracas'),
	('André Calisir', 'Armenia', 'andre calisir'),
	('André Calisir', 'Armenia', 'calisir'),
	('Ali Abdi', 'Tunisia', 'ali abdi'),
	('Ali Abdi', 'Tunisia', 'abdi'),
	('Gégé', 'Cape Verde', 'gege'),
	('Carlos Vargas', 'Mexico', 'vargas'),
	('Carlos Vargas', 'Mexico', 'carlos vargas'),
	('Michael O''Halloran', 'Scotland', 'ohalloran'),
	('Michael O''Halloran', 'Scotland', 'michael ohalloran'),
	('Tony Watt', 'Scotland', 'tony watt'),
	('Tony Watt', 'Scotland', 'watt'),
	('Neluț Roșu', 'Romania', 'rosu'),
	('Neluț Roșu', 'Romania', 'nelut rosu'),
	('Ángelo Preciado', 'Ecuador', 'angelo preciado'),
	('Ángelo Preciado', 'Ecuador', 'preciado'),
	('Gianluca Korte', 'Germany', 'korte'),
	('Gianluca Korte', 'Germany', 'gianluca korte')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';