INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('John García', 'Bolivia', 'player'),
	('Elicer Mina', 'Venezuela', 'player'),
	('Enes Tubluk', 'Germany', 'player'),
	('Liu Shangkun', 'China PR', 'player'),
	('Diego Otoya', 'Peru', 'player'),
	('Živko Kostadinović', 'Switzerland', 'player'),
	('Tom Beadling', 'England', 'player'),
	('Logan Chalmers', 'Scotland', 'player'),
	('Ely Valderrey', 'Venezuela', 'player'),
	('Renato Josipović', 'Croatia', 'player'),
	('Harry Paton', 'Canada', 'player'),
	('Giovanny León', 'Mexico', 'player'),
	('Enrique Peña Zauner', 'Venezuela', 'player'),
	('Amaar Al Dohaim', 'Saudi Arabia', 'player'),
	('Ciaron Harkin', 'Northern Ireland', 'player'),
	('Michael Gurski', 'Germany', 'player'),
	('Patrik Wålemark', 'Sweden', 'player'),
	('José Alfonso Alvarado', 'Mexico', 'player'),
	('Johnny Dunleavy', 'Republic of Ireland', 'player'),
	('Gustavo Canto', 'Argentina', 'player'),
	('Mattie Pollock', 'England', 'player'),
	('Edward Vaca', 'Bolivia', 'player'),
	('Abdulaziz Al Aryani', 'Saudi Arabia', 'player'),
	('Jonah Ayunga', 'Kenya', 'player'),
	('Sadou Diallo', 'England', 'player'),
	('Park Jung Soo', 'Korea Republic', 'player'),
	('Daniel Ríos', 'Mexico', 'player'),
	('James Finnerty', 'Republic of Ireland', 'player'),
	('Dani Albiar', 'Spain', 'player'),
	('Abdulrahman Al Riou', 'Saudi Arabia', 'player'),
	('Rasmus Vinderslev', 'Denmark', 'player'),
	('Luis Klatte', 'Germany', 'player'),
	('Rodrigo Febres', 'Venezuela', 'player'),
	('Brayan Calderon', 'Bolivia', 'player'),
	('Harvey Rodgers', 'England', 'player'),
	('Piotr Krawczyk', 'Poland', 'player'),
	('Yanis Begraoui', 'France', 'player'),
	('Gaute Vetti', 'Norway', 'player'),
	('Georgios Siadas', 'Germany', 'player'),
	('Gift Links', 'South Africa', 'player'),
	('Johannes Naschberger', 'Austria', 'player'),
	('Andy Dales', 'England', 'player'),
	('Carlos Kevin', 'Spain', 'player'),
	('Henry Quiñonez', 'Ecuador', 'player'),
	('Stephen Folan', 'Republic of Ireland', 'player'),
	('Jamshid Iskanderov', 'Uzbekistan', 'player'),
	('Iron Gomis', 'France', 'player'),
	('Dan Kelly', 'Republic of Ireland', 'player'),
	('Jaakko Oksanen', 'Finland', 'player'),
	('Timothé Nkada', 'France', 'player'),
	('Gabriel Florentín', 'Argentina', 'player'),
	('Aston Oxborough', 'England', 'player'),
	('Mahmut Özen', 'Sweden', 'player'),
	('Mathew Hudson', 'England', 'player'),
	('Jahmal Hector-Ingram', 'England', 'player'),
	('Berkan Taz', 'Germany', 'player'),
	('Julio César Pérez', 'Bolivia', 'player'),
	('Alexis Peyrelade', 'France', 'player'),
	('Maxime Delanghe', 'Belgium', 'player'),
	('Franco Fragueda', 'Argentina', 'player'),
	('Douglas Martínez', 'Honduras', 'player'),
	('Ibrahima Koné', 'Mali', 'player'),
	('Dominik Steczyk', 'Poland', 'player'),
	('Francisco Mwepu', 'Zambia', 'player'),
	('Jesse Bosch', 'Netherlands', 'player'),
	('Gary Deegan', 'Republic of Ireland', 'player'),
	('Nikolaos Baxevanos', 'Greece', 'player'),
	('Ben Waine', 'New Zealand', 'player'),
	('Jehad Al Zoaed', 'Saudi Arabia', 'player'),
	('Ahmad Al Ruhaili', 'Saudi Arabia', 'player'),
	('Tomoki Takamine', 'Japan', 'player'),
	('Jonas Gemmer', 'Denmark', 'player'),
	('David Trivunić', 'Serbia', 'player'),
	('Gavin Reilly', 'Scotland', 'player'),
	('Hamed Al Ghamdi', 'Saudi Arabia', 'player'),
	('Milan Iloski', 'United States', 'player'),
	('Paul Méliande', 'France', 'player'),
	('Oliver Finney', 'England', 'player'),
	('Youssuf Ndayishimiye', 'Burundi', 'player'),
	('Simon Stehle', 'Germany', 'player'),
	('Adam Oudjani', 'France', 'player'),
	('David Tomić', 'Germany', 'player'),
	('Ryan Fallowfield', 'England', 'player'),
	('Matthias Haeder', 'Germany', 'player'),
	('Hassan Al Raheb', 'Saudi Arabia', 'player'),
	('Danny Amos', 'Northern Ireland', 'player'),
	('Denis Olivera', 'Uruguay', 'player'),
	('Juan Di Lorenzo', 'Argentina', 'player'),
	('Santiago Eneme', 'Equatorial Guinea', 'player'),
	('Daniel Mikołajewski', 'Poland', 'player'),
	('Alexis Gutiérrez', 'Mexico', 'player'),
	('Neil Farrugia', 'Republic of Ireland', 'player'),
	('Tong Lei', 'China PR', 'player'),
	('Will Bapaga', 'England', 'player'),
	('Ezequiel Bullaude', 'Argentina', 'player'),
	('Indjai Correia', 'Guinea Bissau', 'player'),
	('George Blackwood', 'Australia', 'player'),
	('Facundo Melivilo', 'Argentina', 'player'),
	('Mateo Komar', 'Argentina', 'player'),
	('Gustavo Vallecilla', 'Ecuador', 'player'),
	('Kim Dong Hyun', 'Korea Republic', 'player'),
	('Ángel Zapata', 'Mexico', 'player'),
	('Giuseppe Di Serio', 'Italy', 'player'),
	('Dylan Ryan', 'Australia', 'player'),
	('Liam Cullen', 'Wales', 'player'),
	('Bobby Duncan', 'England', 'player'),
	('Lucas Agüero', 'Argentina', 'player'),
	('Tom Nichols', 'England', 'player'),
	('Harry Pritchard', 'England', 'player'),
	('Ronan Murray', 'Republic of Ireland', 'player'),
	('César Moreno', 'Spain', 'player'),
	('Yoan Zouma', 'France', 'player'),
	('Alexandru Voda', 'Romania', 'player'),
	('Felipe Villagrán', 'Chile', 'player'),
	('Samuel Adrian', 'Sweden', 'player'),
	('Rei Hirakawa', 'Japan', 'player'),
	('Ronaldo Báez', 'Paraguay', 'player'),
	('David Richards', 'Wales', 'player'),
	('Till Brinkmann', 'Germany', 'player'),
	('Joaquín Abdala', 'Chile', 'player'),
	('Liam Bossin', 'Republic of Ireland', 'player'),
	('Max Crocombe', 'New Zealand', 'player'),
	('Gökhan Altıparmak', 'Turkey', 'player'),
	('Jackson Rodríguez', 'Ecuador', 'player'),
	('Sebastian Berhalter', 'United States', 'player'),
	('Felipe Mejía', 'Ecuador', 'player'),
	('Darwin Matheus', 'Venezuela', 'player'),
	('Kazuyoshi Miura', 'Japan', 'player'),
	('Carlos Peralta', 'Ecuador', 'player'),
	('Tristan Abrahams', 'England', 'player'),
	('Aldo Cubilla', 'Paraguay', 'player'),
	('Bader Al Seliteen', 'Saudi Arabia', 'player'),
	('Dominik Franke', 'Germany', 'player'),
	('Okan Turp', 'Turkey', 'player'),
	('Steve Mvoué', 'Cameroon', 'player'),
	('Abdul Manaf Nurudeen', 'Ghana', 'player'),
	('Daniel Aguilar', 'Mexico', 'player'),
	('Yang Boyu', 'China PR', 'player'),
	('Aaron Collins', 'Wales', 'player'),
	('Tareq Abdullah', 'Saudi Arabia', 'player'),
	('Emilio Saba', 'Peru', 'player'),
	('Ayo Akinola', 'United States', 'player'),
	('Raoul Baicu', 'Romania', 'player'),
	('Ousseynou Diagne', 'Senegal', 'player'),
	('Remco Balk', 'Netherlands', 'player'),
	('Erlend Hustad', 'Norway', 'player'),
	('Odin Bailey', 'England', 'player'),
	('Dušan Melichárek', 'Czech Republic', 'player'),
	('Onur Ünlüçifçi', 'Germany', 'player'),
	('Itsuki Someno', 'Japan', 'player'),
	('Gianni Antoniazzi', 'Switzerland', 'player'),
	('Matic Kotnik', 'Slovenia', 'player'),
	('Mukhair Al Rashidi', 'Saudi Arabia', 'player'),
	('Duván Rodríguez', 'Colombia', 'player'),
	('Jhonathan Ramis', 'Uruguay', 'player'),
	('Moustapha Mbow', 'Senegal', 'player'),
	('Will Ferry', 'Republic of Ireland', 'player'),
	('Massimo Bertagnoli', 'Italy', 'player'),
	('Niklas Hoffmann', 'Germany', 'player'),
	('Ogulcan Bekar', 'Austria', 'player'),
	('Matt Freese', 'United States', 'player'),
	('Jerry Skotadis', 'Australia', 'player'),
	('Luis Estupiñán', 'Ecuador', 'player'),
	('Ciarán Coll', 'Republic of Ireland', 'player'),
	('Bryan De Jesús', 'Ecuador', 'player'),
	('Facundo Garcés', 'Argentina', 'player'),
	('Edgardo Orzuza', 'Paraguay', 'player'),
	('Zheng Kaimu', 'China PR', 'player'),
	('James Morton', 'England', 'player'),
	('Sebastián Fassi', 'Mexico', 'player'),
	('Osmar Fernández', 'Paraguay', 'player'),
	('Joel King', 'Australia', 'player'),
	('Yalçın Kayan', 'Turkey', 'player'),
	('Sixto Mina', 'Ecuador', 'player'),
	('Admiral Muskwe', 'Zimbabwe', 'player'),
	('Luciano Pizarro', 'Argentina', 'player'),
	('Lucas Gourna-Douath', 'France', 'player'),
	('Evan Rottier', 'Netherlands', 'player'),
	('Darren Cole', 'Scotland', 'player'),
	('Robin Kehr', 'Germany', 'player'),
	('Andreas Müller', 'Germany', 'player'),
	('Mohamed Morabet', 'Germany', 'player'),
	('José Barreto', 'Argentina', 'player'),
	('Josh Nisbet', 'Australia', 'player'),
	('Glen McAuley', 'Republic of Ireland', 'player'),
	('Linus Obexer', 'Switzerland', 'player'),
	('Tylor Golden', 'England', 'player'),
	('Trova Boni', 'Burkina Faso', 'player'),
	('Will Smith', 'England', 'player'),
	('Mohammed Al Rubaie', 'Saudi Arabia', 'player'),
	('Dawood Al Saeed', 'Saudi Arabia', 'player'),
	('Daniel Pérez', 'Bolivia', 'player'),
	('Enes Karakuş', 'Turkey', 'player'),
	('Maxwell Woledzi', 'Ghana', 'player'),
	('Omari Patrick', 'England', 'player'),
	('José Marrufo', 'Venezuela', 'player'),
	('Fahad Al Shammari', 'Saudi Arabia', 'player'),
	('Ricky Korboa', 'England', 'player'),
	('Danny Whitehall', 'England', 'player'),
	('Michel Ndary Adopo', 'France', 'player'),
	('Juan Cruz Zurbriggen', 'Argentina', 'player'),
	('Nico Mai', 'Germany', 'player'),
	('Horațiu Moldovan', 'Romania', 'player'),
	('Murat Sipahioğlu', 'Turkey', 'player'),
	('Kei Ishikawa', 'Japan', 'player'),
	('Lucas Valente', 'Argentina', 'player'),
	('Oladapo Afolayan', 'England', 'player'),
	('Relu', 'Spain', 'player'),
	('Christoph Ehlich', 'Germany', 'player'),
	('Thibault Tamas', 'France', 'player'),
	('Patrick Koffi', 'France', 'player'),
	('Jo Jin Woo', 'Korea Republic', 'player'),
	('Marokhy Ndione', 'Sweden', 'player'),
	('Tyreece John-Jules', 'England', 'player'),
	('Giovanni Haag', 'France', 'player'),
	('Kim Tae Han', 'Korea Republic', 'player'),
	('Dominik Sváček', 'Czech Republic', 'player'),
	('Myles Judd', 'England', 'player'),
	('Ulaş Zengin', 'Turkey', 'player'),
	('Daniel O''Reilly', 'Republic of Ireland', 'player'),
	('Park Tae Jun', 'Korea Republic', 'player'),
	('Dejan Bozic', 'Germany', 'player'),
	('Keisuke Kurokawa', 'Japan', 'player'),
	('Kenan Dünnwald-Turan', 'Germany', 'player'),
	('Dmytro Bashlay', 'Ukraine', 'player'),
	('Nathan Zohoré', 'France', 'player'),
	('Dominik Jończy', 'Poland', 'player'),
	('Jaisam Korbaj', 'Venezuela', 'player'),
	('Juan Gauto', 'Paraguay', 'player'),
	('Mirel Bolboașă', 'Romania', 'player'),
	('Sebastian Jarl', 'Norway', 'player'),
	('Sam Hornby', 'England', 'player'),
	('Dan Sweeney', 'England', 'player'),
	('Rafael Bandeira', 'Portugal', 'player'),
	('Jonathan Díaz', 'Mexico', 'player'),
	('Alexander Sorge', 'Germany', 'player'),
	('Moussa Guel', 'Ivory Coast', 'player'),
	('Aaron Rowe', 'England', 'player'),
	('Regan Slater', 'England', 'player'),
	('Muhammed Egemen Pehlivan', 'Turkey', 'player'),
	('Melayro Bogarde', 'Netherlands', 'player'),
	('Jacob Bedeau', 'England', 'player'),
	('John Nelson', 'United States', 'player'),
	('Frank Vincent', 'England', 'player'),
	('Salifou Diarrassouba', 'Burkina Faso', 'player'),
	('Mateo Tanlongo', 'Argentina', 'player'),
	('Agustín Casco', 'Argentina', 'player'),
	('Hirofumi Yamauchi', 'Japan', 'player'),
	('Fernán López', 'Spain', 'player'),
	('Aldo López', 'Mexico', 'player');

WITH v(name, cat, alias) AS (VALUES
	('John García', 'Bolivia', 'john garcia'),
	('John García', 'Bolivia', 'garcia'),
	('Elicer Mina', 'Venezuela', 'elicer mina'),
	('Elicer Mina', 'Venezuela', 'mina'),
	('Enes Tubluk', 'Germany', 'enes tubluk'),
	('Enes Tubluk', 'Germany', 'tubluk'),
	('Liu Shangkun', 'China PR', 'liu shangkun'),
	('Liu Shangkun', 'China PR', 'shangkun'),
	('Diego Otoya', 'Peru', 'diego otoya'),
	('Diego Otoya', 'Peru', 'otoya'),
	('Živko Kostadinović', 'Switzerland', 'zivko kostadinovic'),
	('Živko Kostadinović', 'Switzerland', 'kostadinovic'),
	('Tom Beadling', 'England', 'beadling'),
	('Tom Beadling', 'England', 'tom beadling'),
	('Logan Chalmers', 'Scotland', 'chalmers'),
	('Logan Chalmers', 'Scotland', 'logan chalmers'),
	('Ely Valderrey', 'Venezuela', 'ely valderrey'),
	('Ely Valderrey', 'Venezuela', 'valderrey'),
	('Renato Josipović', 'Croatia', 'renato josipovic'),
	('Renato Josipović', 'Croatia', 'josipovic'),
	('Harry Paton', 'Canada', 'paton'),
	('Harry Paton', 'Canada', 'harry paton'),
	('Giovanny León', 'Mexico', 'leon'),
	('Giovanny León', 'Mexico', 'giovanny leon'),
	('Enrique Peña Zauner', 'Venezuela', 'enrique pena zauner'),
	('Enrique Peña Zauner', 'Venezuela', 'zauner'),
	('Amaar Al Dohaim', 'Saudi Arabia', 'dohaim'),
	('Amaar Al Dohaim', 'Saudi Arabia', 'amaar al dohaim'),
	('Ciaron Harkin', 'Northern Ireland', 'harkin'),
	('Ciaron Harkin', 'Northern Ireland', 'ciaron harkin'),
	('Michael Gurski', 'Germany', 'michael gurski'),
	('Michael Gurski', 'Germany', 'gurski'),
	('Patrik Wålemark', 'Sweden', 'patrik walemark'),
	('Patrik Wålemark', 'Sweden', 'walemark'),
	('José Alfonso Alvarado', 'Mexico', 'jose alfonso alvarado'),
	('José Alfonso Alvarado', 'Mexico', 'alvarado'),
	('Johnny Dunleavy', 'Republic of Ireland', 'johnny dunleavy'),
	('Johnny Dunleavy', 'Republic of Ireland', 'dunleavy'),
	('Gustavo Canto', 'Argentina', 'canto'),
	('Gustavo Canto', 'Argentina', 'gustavo canto'),
	('Mattie Pollock', 'England', 'pollock'),
	('Mattie Pollock', 'England', 'mattie pollock'),
	('Edward Vaca', 'Bolivia', 'vaca'),
	('Edward Vaca', 'Bolivia', 'edward vaca'),
	('Abdulaziz Al Aryani', 'Saudi Arabia', 'abdulaziz al aryani'),
	('Abdulaziz Al Aryani', 'Saudi Arabia', 'aryani'),
	('Jonah Ayunga', 'Kenya', 'ayunga'),
	('Jonah Ayunga', 'Kenya', 'jonah ayunga'),
	('Sadou Diallo', 'England', 'diallo'),
	('Sadou Diallo', 'England', 'sadou diallo'),
	('Park Jung Soo', 'Korea Republic', 'park jung soo'),
	('Park Jung Soo', 'Korea Republic', 'soo'),
	('Daniel Ríos', 'Mexico', 'daniel rios'),
	('Daniel Ríos', 'Mexico', 'rios'),
	('James Finnerty', 'Republic of Ireland', 'james finnerty'),
	('James Finnerty', 'Republic of Ireland', 'finnerty'),
	('Dani Albiar', 'Spain', 'albiar'),
	('Dani Albiar', 'Spain', 'dani albiar'),
	('Abdulrahman Al Riou', 'Saudi Arabia', 'abdulrahman al riou'),
	('Abdulrahman Al Riou', 'Saudi Arabia', 'riou'),
	('Rasmus Vinderslev', 'Denmark', 'rasmus vinderslev'),
	('Rasmus Vinderslev', 'Denmark', 'vinderslev'),
	('Luis Klatte', 'Germany', 'klatte'),
	('Luis Klatte', 'Germany', 'luis klatte'),
	('Rodrigo Febres', 'Venezuela', 'febres'),
	('Rodrigo Febres', 'Venezuela', 'rodrigo febres'),
	('Brayan Calderon', 'Bolivia', 'brayan calderon'),
	('Brayan Calderon', 'Bolivia', 'calderon'),
	('Harvey Rodgers', 'England', 'harvey rodgers'),
	('Harvey Rodgers', 'England', 'rodgers'),
	('Piotr Krawczyk', 'Poland', 'krawczyk'),
	('Piotr Krawczyk', 'Poland', 'piotr krawczyk'),
	('Yanis Begraoui', 'France', 'begraoui'),
	('Yanis Begraoui', 'France', 'yanis begraoui'),
	('Gaute Vetti', 'Norway', 'vetti'),
	('Gaute Vetti', 'Norway', 'gaute vetti'),
	('Georgios Siadas', 'Germany', 'georgios siadas'),
	('Georgios Siadas', 'Germany', 'siadas'),
	('Gift Links', 'South Africa', 'links'),
	('Gift Links', 'South Africa', 'gift links'),
	('Johannes Naschberger', 'Austria', 'johannes naschberger'),
	('Johannes Naschberger', 'Austria', 'naschberger'),
	('Andy Dales', 'England', 'andy dales'),
	('Andy Dales', 'England', 'dales'),
	('Carlos Kevin', 'Spain', 'kevin'),
	('Carlos Kevin', 'Spain', 'carlos kevin'),
	('Henry Quiñonez', 'Ecuador', 'henry quinonez'),
	('Henry Quiñonez', 'Ecuador', 'quinonez'),
	('Stephen Folan', 'Republic of Ireland', 'stephen folan'),
	('Stephen Folan', 'Republic of Ireland', 'folan'),
	('Jamshid Iskanderov', 'Uzbekistan', 'jamshid iskanderov'),
	('Jamshid Iskanderov', 'Uzbekistan', 'iskanderov'),
	('Iron Gomis', 'France', 'gomis'),
	('Iron Gomis', 'France', 'iron gomis'),
	('Dan Kelly', 'Republic of Ireland', 'kelly'),
	('Dan Kelly', 'Republic of Ireland', 'dan kelly'),
	('Jaakko Oksanen', 'Finland', 'oksanen'),
	('Jaakko Oksanen', 'Finland', 'jaakko oksanen'),
	('Timothé Nkada', 'France', 'nkada'),
	('Timothé Nkada', 'France', 'timothe nkada'),
	('Gabriel Florentín', 'Argentina', 'florentin'),
	('Gabriel Florentín', 'Argentina', 'gabriel florentin'),
	('Aston Oxborough', 'England', 'aston oxborough'),
	('Aston Oxborough', 'England', 'oxborough'),
	('Mahmut Özen', 'Sweden', 'ozen'),
	('Mahmut Özen', 'Sweden', 'mahmut ozen'),
	('Mathew Hudson', 'England', 'mathew hudson'),
	('Mathew Hudson', 'England', 'hudson'),
	('Jahmal Hector-Ingram', 'England', 'jahmal hectoringram'),
	('Jahmal Hector-Ingram', 'England', 'hectoringram'),
	('Berkan Taz', 'Germany', 'taz'),
	('Berkan Taz', 'Germany', 'berkan taz'),
	('Julio César Pérez', 'Bolivia', 'julio cesar perez'),
	('Julio César Pérez', 'Bolivia', 'perez'),
	('Alexis Peyrelade', 'France', 'peyrelade'),
	('Alexis Peyrelade', 'France', 'alexis peyrelade'),
	('Maxime Delanghe', 'Belgium', 'maxime delanghe'),
	('Maxime Delanghe', 'Belgium', 'delanghe'),
	('Franco Fragueda', 'Argentina', 'fragueda'),
	('Franco Fragueda', 'Argentina', 'franco fragueda'),
	('Douglas Martínez', 'Honduras', 'douglas martinez'),
	('Douglas Martínez', 'Honduras', 'martinez'),
	('Ibrahima Koné', 'Mali', 'ibrahima kone'),
	('Ibrahima Koné', 'Mali', 'kone'),
	('Dominik Steczyk', 'Poland', 'dominik steczyk'),
	('Dominik Steczyk', 'Poland', 'steczyk'),
	('Francisco Mwepu', 'Zambia', 'mwepu'),
	('Francisco Mwepu', 'Zambia', 'francisco mwepu'),
	('Jesse Bosch', 'Netherlands', 'bosch'),
	('Jesse Bosch', 'Netherlands', 'jesse bosch'),
	('Gary Deegan', 'Republic of Ireland', 'deegan'),
	('Gary Deegan', 'Republic of Ireland', 'gary deegan'),
	('Nikolaos Baxevanos', 'Greece', 'nikolaos baxevanos'),
	('Nikolaos Baxevanos', 'Greece', 'baxevanos'),
	('Ben Waine', 'New Zealand', 'ben waine'),
	('Ben Waine', 'New Zealand', 'waine'),
	('Jehad Al Zoaed', 'Saudi Arabia', 'zoaed'),
	('Jehad Al Zoaed', 'Saudi Arabia', 'jehad al zoaed'),
	('Ahmad Al Ruhaili', 'Saudi Arabia', 'ruhaili'),
	('Ahmad Al Ruhaili', 'Saudi Arabia', 'ahmad al ruhaili'),
	('Tomoki Takamine', 'Japan', 'tomoki takamine'),
	('Tomoki Takamine', 'Japan', 'takamine'),
	('Jonas Gemmer', 'Denmark', 'gemmer'),
	('Jonas Gemmer', 'Denmark', 'jonas gemmer'),
	('David Trivunić', 'Serbia', 'trivunic'),
	('David Trivunić', 'Serbia', 'david trivunic'),
	('Gavin Reilly', 'Scotland', 'gavin reilly'),
	('Gavin Reilly', 'Scotland', 'reilly'),
	('Hamed Al Ghamdi', 'Saudi Arabia', 'hamed al ghamdi'),
	('Hamed Al Ghamdi', 'Saudi Arabia', 'ghamdi'),
	('Milan Iloski', 'United States', 'milan iloski'),
	('Milan Iloski', 'United States', 'iloski'),
	('Paul Méliande', 'France', 'paul meliande'),
	('Paul Méliande', 'France', 'meliande'),
	('Oliver Finney', 'England', 'oliver finney'),
	('Oliver Finney', 'England', 'finney'),
	('Youssuf Ndayishimiye', 'Burundi', 'youssuf ndayishimiye'),
	('Youssuf Ndayishimiye', 'Burundi', 'ndayishimiye'),
	('Simon Stehle', 'Germany', 'stehle'),
	('Simon Stehle', 'Germany', 'simon stehle'),
	('Adam Oudjani', 'France', 'adam oudjani'),
	('Adam Oudjani', 'France', 'oudjani'),
	('David Tomić', 'Germany', 'tomic'),
	('David Tomić', 'Germany', 'david tomic'),
	('Ryan Fallowfield', 'England', 'fallowfield'),
	('Ryan Fallowfield', 'England', 'ryan fallowfield'),
	('Matthias Haeder', 'Germany', 'haeder'),
	('Matthias Haeder', 'Germany', 'matthias haeder'),
	('Hassan Al Raheb', 'Saudi Arabia', 'raheb'),
	('Hassan Al Raheb', 'Saudi Arabia', 'hassan al raheb'),
	('Danny Amos', 'Northern Ireland', 'danny amos'),
	('Danny Amos', 'Northern Ireland', 'amos'),
	('Denis Olivera', 'Uruguay', 'olivera'),
	('Denis Olivera', 'Uruguay', 'denis olivera'),
	('Juan Di Lorenzo', 'Argentina', 'juan di lorenzo'),
	('Juan Di Lorenzo', 'Argentina', 'lorenzo'),
	('Santiago Eneme', 'Equatorial Guinea', 'santiago eneme'),
	('Santiago Eneme', 'Equatorial Guinea', 'eneme'),
	('Daniel Mikołajewski', 'Poland', 'mikoajewski'),
	('Daniel Mikołajewski', 'Poland', 'daniel mikoajewski'),
	('Alexis Gutiérrez', 'Mexico', 'gutierrez'),
	('Alexis Gutiérrez', 'Mexico', 'alexis gutierrez'),
	('Neil Farrugia', 'Republic of Ireland', 'neil farrugia'),
	('Neil Farrugia', 'Republic of Ireland', 'farrugia'),
	('Tong Lei', 'China PR', 'lei'),
	('Tong Lei', 'China PR', 'tong lei'),
	('Will Bapaga', 'England', 'will bapaga'),
	('Will Bapaga', 'England', 'bapaga'),
	('Ezequiel Bullaude', 'Argentina', 'bullaude'),
	('Ezequiel Bullaude', 'Argentina', 'ezequiel bullaude'),
	('Indjai Correia', 'Guinea Bissau', 'indjai correia'),
	('Indjai Correia', 'Guinea Bissau', 'correia'),
	('George Blackwood', 'Australia', 'george blackwood'),
	('George Blackwood', 'Australia', 'blackwood'),
	('Facundo Melivilo', 'Argentina', 'melivilo'),
	('Facundo Melivilo', 'Argentina', 'facundo melivilo'),
	('Mateo Komar', 'Argentina', 'mateo komar'),
	('Mateo Komar', 'Argentina', 'komar'),
	('Gustavo Vallecilla', 'Ecuador', 'vallecilla'),
	('Gustavo Vallecilla', 'Ecuador', 'gustavo vallecilla'),
	('Kim Dong Hyun', 'Korea Republic', 'hyun'),
	('Kim Dong Hyun', 'Korea Republic', 'kim dong hyun'),
	('Ángel Zapata', 'Mexico', 'zapata'),
	('Ángel Zapata', 'Mexico', 'angel zapata'),
	('Giuseppe Di Serio', 'Italy', 'serio'),
	('Giuseppe Di Serio', 'Italy', 'giuseppe di serio'),
	('Dylan Ryan', 'Australia', 'ryan'),
	('Dylan Ryan', 'Australia', 'dylan ryan'),
	('Liam Cullen', 'Wales', 'liam cullen'),
	('Liam Cullen', 'Wales', 'cullen'),
	('Bobby Duncan', 'England', 'bobby duncan'),
	('Bobby Duncan', 'England', 'duncan'),
	('Lucas Agüero', 'Argentina', 'lucas aguero'),
	('Lucas Agüero', 'Argentina', 'aguero'),
	('Tom Nichols', 'England', 'nichols'),
	('Tom Nichols', 'England', 'tom nichols'),
	('Harry Pritchard', 'England', 'pritchard'),
	('Harry Pritchard', 'England', 'harry pritchard'),
	('Ronan Murray', 'Republic of Ireland', 'ronan murray'),
	('Ronan Murray', 'Republic of Ireland', 'murray'),
	('César Moreno', 'Spain', 'moreno'),
	('César Moreno', 'Spain', 'cesar moreno'),
	('Yoan Zouma', 'France', 'zouma'),
	('Yoan Zouma', 'France', 'yoan zouma'),
	('Alexandru Voda', 'Romania', 'voda'),
	('Alexandru Voda', 'Romania', 'alexandru voda'),
	('Felipe Villagrán', 'Chile', 'felipe villagran'),
	('Felipe Villagrán', 'Chile', 'villagran'),
	('Samuel Adrian', 'Sweden', 'adrian'),
	('Samuel Adrian', 'Sweden', 'samuel adrian'),
	('Rei Hirakawa', 'Japan', 'rei hirakawa'),
	('Rei Hirakawa', 'Japan', 'hirakawa'),
	('Ronaldo Báez', 'Paraguay', 'ronaldo baez'),
	('Ronaldo Báez', 'Paraguay', 'baez'),
	('David Richards', 'Wales', 'david richards'),
	('David Richards', 'Wales', 'richards'),
	('Till Brinkmann', 'Germany', 'brinkmann'),
	('Till Brinkmann', 'Germany', 'till brinkmann'),
	('Joaquín Abdala', 'Chile', 'abdala'),
	('Joaquín Abdala', 'Chile', 'joaquin abdala'),
	('Liam Bossin', 'Republic of Ireland', 'liam bossin'),
	('Liam Bossin', 'Republic of Ireland', 'bossin'),
	('Max Crocombe', 'New Zealand', 'max crocombe'),
	('Max Crocombe', 'New Zealand', 'crocombe'),
	('Gökhan Altıparmak', 'Turkey', 'altparmak'),
	('Gökhan Altıparmak', 'Turkey', 'gokhan altparmak'),
	('Jackson Rodríguez', 'Ecuador', 'rodriguez'),
	('Jackson Rodríguez', 'Ecuador', 'jackson rodriguez'),
	('Sebastian Berhalter', 'United States', 'berhalter'),
	('Sebastian Berhalter', 'United States', 'sebastian berhalter'),
	('Felipe Mejía', 'Ecuador', 'felipe mejia'),
	('Felipe Mejía', 'Ecuador', 'mejia'),
	('Darwin Matheus', 'Venezuela', 'matheus'),
	('Darwin Matheus', 'Venezuela', 'darwin matheus'),
	('Kazuyoshi Miura', 'Japan', 'kazuyoshi miura'),
	('Kazuyoshi Miura', 'Japan', 'miura'),
	('Carlos Peralta', 'Ecuador', 'carlos peralta'),
	('Carlos Peralta', 'Ecuador', 'peralta'),
	('Tristan Abrahams', 'England', 'tristan abrahams'),
	('Tristan Abrahams', 'England', 'abrahams'),
	('Aldo Cubilla', 'Paraguay', 'aldo cubilla'),
	('Aldo Cubilla', 'Paraguay', 'cubilla'),
	('Bader Al Seliteen', 'Saudi Arabia', 'seliteen'),
	('Bader Al Seliteen', 'Saudi Arabia', 'bader al seliteen'),
	('Dominik Franke', 'Germany', 'franke'),
	('Dominik Franke', 'Germany', 'dominik franke'),
	('Okan Turp', 'Turkey', 'okan turp'),
	('Okan Turp', 'Turkey', 'turp'),
	('Steve Mvoué', 'Cameroon', 'steve mvoue'),
	('Steve Mvoué', 'Cameroon', 'mvoue'),
	('Abdul Manaf Nurudeen', 'Ghana', 'abdul manaf nurudeen'),
	('Abdul Manaf Nurudeen', 'Ghana', 'nurudeen'),
	('Daniel Aguilar', 'Mexico', 'aguilar'),
	('Daniel Aguilar', 'Mexico', 'daniel aguilar'),
	('Yang Boyu', 'China PR', 'boyu'),
	('Yang Boyu', 'China PR', 'yang boyu'),
	('Aaron Collins', 'Wales', 'aaron collins'),
	('Aaron Collins', 'Wales', 'collins'),
	('Tareq Abdullah', 'Saudi Arabia', 'abdullah'),
	('Tareq Abdullah', 'Saudi Arabia', 'tareq abdullah'),
	('Emilio Saba', 'Peru', 'emilio saba'),
	('Emilio Saba', 'Peru', 'saba'),
	('Ayo Akinola', 'United States', 'ayo akinola'),
	('Ayo Akinola', 'United States', 'akinola'),
	('Raoul Baicu', 'Romania', 'raoul baicu'),
	('Raoul Baicu', 'Romania', 'baicu'),
	('Ousseynou Diagne', 'Senegal', 'ousseynou diagne'),
	('Ousseynou Diagne', 'Senegal', 'diagne'),
	('Remco Balk', 'Netherlands', 'balk'),
	('Remco Balk', 'Netherlands', 'remco balk'),
	('Erlend Hustad', 'Norway', 'hustad'),
	('Erlend Hustad', 'Norway', 'erlend hustad'),
	('Odin Bailey', 'England', 'odin bailey'),
	('Odin Bailey', 'England', 'bailey'),
	('Dušan Melichárek', 'Czech Republic', 'dusan melicharek'),
	('Dušan Melichárek', 'Czech Republic', 'melicharek'),
	('Onur Ünlüçifçi', 'Germany', 'unlucifci'),
	('Onur Ünlüçifçi', 'Germany', 'onur unlucifci'),
	('Itsuki Someno', 'Japan', 'someno'),
	('Itsuki Someno', 'Japan', 'itsuki someno'),
	('Gianni Antoniazzi', 'Switzerland', 'gianni antoniazzi'),
	('Gianni Antoniazzi', 'Switzerland', 'antoniazzi'),
	('Matic Kotnik', 'Slovenia', 'kotnik'),
	('Matic Kotnik', 'Slovenia', 'matic kotnik'),
	('Mukhair Al Rashidi', 'Saudi Arabia', 'rashidi'),
	('Mukhair Al Rashidi', 'Saudi Arabia', 'mukhair al rashidi'),
	('Duván Rodríguez', 'Colombia', 'duvan rodriguez'),
	('Duván Rodríguez', 'Colombia', 'rodriguez'),
	('Jhonathan Ramis', 'Uruguay', 'ramis'),
	('Jhonathan Ramis', 'Uruguay', 'jhonathan ramis'),
	('Moustapha Mbow', 'Senegal', 'moustapha mbow'),
	('Moustapha Mbow', 'Senegal', 'mbow'),
	('Will Ferry', 'Republic of Ireland', 'ferry'),
	('Will Ferry', 'Republic of Ireland', 'will ferry'),
	('Massimo Bertagnoli', 'Italy', 'massimo bertagnoli'),
	('Massimo Bertagnoli', 'Italy', 'bertagnoli'),
	('Niklas Hoffmann', 'Germany', 'hoffmann'),
	('Niklas Hoffmann', 'Germany', 'niklas hoffmann'),
	('Ogulcan Bekar', 'Austria', 'bekar'),
	('Ogulcan Bekar', 'Austria', 'ogulcan bekar'),
	('Matt Freese', 'United States', 'matt freese'),
	('Matt Freese', 'United States', 'freese'),
	('Jerry Skotadis', 'Australia', 'skotadis'),
	('Jerry Skotadis', 'Australia', 'jerry skotadis'),
	('Luis Estupiñán', 'Ecuador', 'estupinan'),
	('Luis Estupiñán', 'Ecuador', 'luis estupinan'),
	('Ciarán Coll', 'Republic of Ireland', 'coll'),
	('Ciarán Coll', 'Republic of Ireland', 'ciaran coll'),
	('Bryan De Jesús', 'Ecuador', 'jesus'),
	('Bryan De Jesús', 'Ecuador', 'bryan de jesus'),
	('Facundo Garcés', 'Argentina', 'garces'),
	('Facundo Garcés', 'Argentina', 'facundo garces'),
	('Edgardo Orzuza', 'Paraguay', 'orzuza'),
	('Edgardo Orzuza', 'Paraguay', 'edgardo orzuza'),
	('Zheng Kaimu', 'China PR', 'kaimu'),
	('Zheng Kaimu', 'China PR', 'zheng kaimu'),
	('James Morton', 'England', 'james morton'),
	('James Morton', 'England', 'morton'),
	('Sebastián Fassi', 'Mexico', 'sebastian fassi'),
	('Sebastián Fassi', 'Mexico', 'fassi'),
	('Osmar Fernández', 'Paraguay', 'fernandez'),
	('Osmar Fernández', 'Paraguay', 'osmar fernandez'),
	('Joel King', 'Australia', 'joel king'),
	('Joel King', 'Australia', 'king'),
	('Yalçın Kayan', 'Turkey', 'yalcn kayan'),
	('Yalçın Kayan', 'Turkey', 'kayan'),
	('Sixto Mina', 'Ecuador', 'mina'),
	('Sixto Mina', 'Ecuador', 'sixto mina'),
	('Admiral Muskwe', 'Zimbabwe', 'admiral muskwe'),
	('Admiral Muskwe', 'Zimbabwe', 'muskwe'),
	('Luciano Pizarro', 'Argentina', 'pizarro'),
	('Luciano Pizarro', 'Argentina', 'luciano pizarro'),
	('Lucas Gourna-Douath', 'France', 'lucas gournadouath'),
	('Lucas Gourna-Douath', 'France', 'gournadouath'),
	('Evan Rottier', 'Netherlands', 'evan rottier'),
	('Evan Rottier', 'Netherlands', 'rottier'),
	('Darren Cole', 'Scotland', 'darren cole'),
	('Darren Cole', 'Scotland', 'cole'),
	('Robin Kehr', 'Germany', 'robin kehr'),
	('Robin Kehr', 'Germany', 'kehr'),
	('Andreas Müller', 'Germany', 'muller'),
	('Andreas Müller', 'Germany', 'andreas muller'),
	('Mohamed Morabet', 'Germany', 'mohamed morabet'),
	('Mohamed Morabet', 'Germany', 'morabet'),
	('José Barreto', 'Argentina', 'barreto'),
	('José Barreto', 'Argentina', 'jose barreto'),
	('Josh Nisbet', 'Australia', 'josh nisbet'),
	('Josh Nisbet', 'Australia', 'nisbet'),
	('Glen McAuley', 'Republic of Ireland', 'mcauley'),
	('Glen McAuley', 'Republic of Ireland', 'glen mcauley'),
	('Linus Obexer', 'Switzerland', 'obexer'),
	('Linus Obexer', 'Switzerland', 'linus obexer'),
	('Tylor Golden', 'England', 'golden'),
	('Tylor Golden', 'England', 'tylor golden'),
	('Trova Boni', 'Burkina Faso', 'boni'),
	('Trova Boni', 'Burkina Faso', 'trova boni'),
	('Will Smith', 'England', 'smith'),
	('Will Smith', 'England', 'will smith'),
	('Mohammed Al Rubaie', 'Saudi Arabia', 'mohammed al rubaie'),
	('Mohammed Al Rubaie', 'Saudi Arabia', 'rubaie'),
	('Dawood Al Saeed', 'Saudi Arabia', 'dawood al saeed'),
	('Dawood Al Saeed', 'Saudi Arabia', 'saeed'),
	('Daniel Pérez', 'Bolivia', 'daniel perez'),
	('Daniel Pérez', 'Bolivia', 'perez'),
	('Enes Karakuş', 'Turkey', 'karakus'),
	('Enes Karakuş', 'Turkey', 'enes karakus'),
	('Maxwell Woledzi', 'Ghana', 'woledzi'),
	('Maxwell Woledzi', 'Ghana', 'maxwell woledzi'),
	('Omari Patrick', 'England', 'omari patrick'),
	('Omari Patrick', 'England', 'patrick'),
	('José Marrufo', 'Venezuela', 'jose marrufo'),
	('José Marrufo', 'Venezuela', 'marrufo'),
	('Fahad Al Shammari', 'Saudi Arabia', 'fahad al shammari'),
	('Fahad Al Shammari', 'Saudi Arabia', 'shammari'),
	('Ricky Korboa', 'England', 'korboa'),
	('Ricky Korboa', 'England', 'ricky korboa'),
	('Danny Whitehall', 'England', 'whitehall'),
	('Danny Whitehall', 'England', 'danny whitehall'),
	('Michel Ndary Adopo', 'France', 'adopo'),
	('Michel Ndary Adopo', 'France', 'michel ndary adopo'),
	('Juan Cruz Zurbriggen', 'Argentina', 'juan cruz zurbriggen'),
	('Juan Cruz Zurbriggen', 'Argentina', 'zurbriggen'),
	('Nico Mai', 'Germany', 'mai'),
	('Nico Mai', 'Germany', 'nico mai'),
	('Horațiu Moldovan', 'Romania', 'moldovan'),
	('Horațiu Moldovan', 'Romania', 'horatiu moldovan'),
	('Murat Sipahioğlu', 'Turkey', 'sipahioglu'),
	('Murat Sipahioğlu', 'Turkey', 'murat sipahioglu'),
	('Kei Ishikawa', 'Japan', 'kei ishikawa'),
	('Kei Ishikawa', 'Japan', 'ishikawa'),
	('Lucas Valente', 'Argentina', 'lucas valente'),
	('Lucas Valente', 'Argentina', 'valente'),
	('Oladapo Afolayan', 'England', 'oladapo afolayan'),
	('Oladapo Afolayan', 'England', 'afolayan'),
	('Relu', 'Spain', 'relu'),
	('Christoph Ehlich', 'Germany', 'christoph ehlich'),
	('Christoph Ehlich', 'Germany', 'ehlich'),
	('Thibault Tamas', 'France', 'tamas'),
	('Thibault Tamas', 'France', 'thibault tamas'),
	('Patrick Koffi', 'France', 'koffi'),
	('Patrick Koffi', 'France', 'patrick koffi'),
	('Jo Jin Woo', 'Korea Republic', 'woo'),
	('Jo Jin Woo', 'Korea Republic', 'jo jin woo'),
	('Marokhy Ndione', 'Sweden', 'marokhy ndione'),
	('Marokhy Ndione', 'Sweden', 'ndione'),
	('Tyreece John-Jules', 'England', 'johnjules'),
	('Tyreece John-Jules', 'England', 'tyreece johnjules'),
	('Giovanni Haag', 'France', 'giovanni haag'),
	('Giovanni Haag', 'France', 'haag'),
	('Kim Tae Han', 'Korea Republic', 'han'),
	('Kim Tae Han', 'Korea Republic', 'kim tae han'),
	('Dominik Sváček', 'Czech Republic', 'dominik svacek'),
	('Dominik Sváček', 'Czech Republic', 'svacek'),
	('Myles Judd', 'England', 'judd'),
	('Myles Judd', 'England', 'myles judd'),
	('Ulaş Zengin', 'Turkey', 'zengin'),
	('Ulaş Zengin', 'Turkey', 'ulas zengin'),
	('Daniel O''Reilly', 'Republic of Ireland', 'daniel oreilly'),
	('Daniel O''Reilly', 'Republic of Ireland', 'oreilly'),
	('Park Tae Jun', 'Korea Republic', 'park tae jun'),
	('Park Tae Jun', 'Korea Republic', 'jun'),
	('Dejan Bozic', 'Germany', 'bozic'),
	('Dejan Bozic', 'Germany', 'dejan bozic'),
	('Keisuke Kurokawa', 'Japan', 'kurokawa'),
	('Keisuke Kurokawa', 'Japan', 'keisuke kurokawa'),
	('Kenan Dünnwald-Turan', 'Germany', 'dunnwaldturan'),
	('Kenan Dünnwald-Turan', 'Germany', 'kenan dunnwaldturan'),
	('Dmytro Bashlay', 'Ukraine', 'bashlay'),
	('Dmytro Bashlay', 'Ukraine', 'dmytro bashlay'),
	('Nathan Zohoré', 'France', 'nathan zohore'),
	('Nathan Zohoré', 'France', 'zohore'),
	('Dominik Jończy', 'Poland', 'dominik jonczy'),
	('Dominik Jończy', 'Poland', 'jonczy'),
	('Jaisam Korbaj', 'Venezuela', 'jaisam korbaj'),
	('Jaisam Korbaj', 'Venezuela', 'korbaj'),
	('Juan Gauto', 'Paraguay', 'juan gauto'),
	('Juan Gauto', 'Paraguay', 'gauto'),
	('Mirel Bolboașă', 'Romania', 'mirel bolboasa'),
	('Mirel Bolboașă', 'Romania', 'bolboasa'),
	('Sebastian Jarl', 'Norway', 'sebastian jarl'),
	('Sebastian Jarl', 'Norway', 'jarl'),
	('Sam Hornby', 'England', 'hornby'),
	('Sam Hornby', 'England', 'sam hornby'),
	('Dan Sweeney', 'England', 'sweeney'),
	('Dan Sweeney', 'England', 'dan sweeney'),
	('Rafael Bandeira', 'Portugal', 'rafael bandeira'),
	('Rafael Bandeira', 'Portugal', 'bandeira'),
	('Jonathan Díaz', 'Mexico', 'diaz'),
	('Jonathan Díaz', 'Mexico', 'jonathan diaz'),
	('Alexander Sorge', 'Germany', 'alexander sorge'),
	('Alexander Sorge', 'Germany', 'sorge'),
	('Moussa Guel', 'Ivory Coast', 'guel'),
	('Moussa Guel', 'Ivory Coast', 'moussa guel'),
	('Aaron Rowe', 'England', 'rowe'),
	('Aaron Rowe', 'England', 'aaron rowe'),
	('Regan Slater', 'England', 'regan slater'),
	('Regan Slater', 'England', 'slater'),
	('Muhammed Egemen Pehlivan', 'Turkey', 'muhammed egemen pehlivan'),
	('Muhammed Egemen Pehlivan', 'Turkey', 'pehlivan'),
	('Melayro Bogarde', 'Netherlands', 'bogarde'),
	('Melayro Bogarde', 'Netherlands', 'melayro bogarde'),
	('Jacob Bedeau', 'England', 'jacob bedeau'),
	('Jacob Bedeau', 'England', 'bedeau'),
	('John Nelson', 'United States', 'nelson'),
	('John Nelson', 'United States', 'john nelson'),
	('Frank Vincent', 'England', 'vincent'),
	('Frank Vincent', 'England', 'frank vincent'),
	('Salifou Diarrassouba', 'Burkina Faso', 'salifou diarrassouba'),
	('Salifou Diarrassouba', 'Burkina Faso', 'diarrassouba'),
	('Mateo Tanlongo', 'Argentina', 'tanlongo'),
	('Mateo Tanlongo', 'Argentina', 'mateo tanlongo'),
	('Agustín Casco', 'Argentina', 'casco'),
	('Agustín Casco', 'Argentina', 'agustin casco'),
	('Hirofumi Yamauchi', 'Japan', 'hirofumi yamauchi'),
	('Hirofumi Yamauchi', 'Japan', 'yamauchi'),
	('Fernán López', 'Spain', 'lopez'),
	('Fernán López', 'Spain', 'fernan lopez'),
	('Aldo López', 'Mexico', 'aldo lopez'),
	('Aldo López', 'Mexico', 'lopez')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';