INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Sean Hoare', 'Republic of Ireland', 'player'),
	('Rob Hunt', 'England', 'player'),
	('Moritz Nicolas', 'Germany', 'player'),
	('Bobby Adekanye', 'Netherlands', 'player'),
	('Janoi Donacien', 'Saint Lucia', 'player'),
	('David Browne', 'Papua New Guinea', 'player'),
	('Lazaros Rota', 'Greece', 'player'),
	('Christian Dahle Borchgrevink', 'Norway', 'player'),
	('Ben Tozer', 'England', 'player'),
	('Andrija Vukčević', 'Montenegro', 'player'),
	('Andrés Reyes', 'Colombia', 'player'),
	('Eddy Sylvestre', 'France', 'player'),
	('Nicolás Messiniti', 'Argentina', 'player'),
	('Dinu Moldovan', 'Romania', 'player'),
	('Ivan Näsberg', 'Norway', 'player'),
	('Belman', 'Spain', 'player'),
	('Curtis Tilt', 'England', 'player'),
	('Scott Neville', 'Australia', 'player'),
	('Mathias Nielsen', 'Denmark', 'player'),
	('Emiliano Alfaro', 'Uruguay', 'player'),
	('Maksim Glushenkov', 'Russia', 'player'),
	('Jordan Hamilton', 'Canada', 'player'),
	('Yuki Abe', 'Japan', 'player'),
	('Johan Mina', 'Ecuador', 'player'),
	('Scott Caldwell', 'United States', 'player'),
	('Federico Navarro', 'Argentina', 'player'),
	('Piotr Tomasik', 'Poland', 'player'),
	('Matt Bloomfield', 'England', 'player'),
	('Serkan Asan', 'Turkey', 'player'),
	('Sebastian Bauer', 'Austria', 'player'),
	('Kortne Ford', 'United States', 'player'),
	('Naoki Yamada', 'Japan', 'player'),
	('Jonas Nietfeld', 'Germany', 'player'),
	('Josh Vela', 'England', 'player'),
	('Michael Almebäck', 'Sweden', 'player'),
	('Darlin Yongwa', 'Cameroon', 'player'),
	('Tyrick Mitchell', 'England', 'player'),
	('Jayson Leutwiler', 'Canada', 'player'),
	('Kim Soo Beom', 'Korea Republic', 'player'),
	('Alex Gilliead', 'England', 'player'),
	('Leo Bengtsson', 'Sweden', 'player'),
	('Patryk Lipski', 'Poland', 'player'),
	('Alexis Maldonado', 'Argentina', 'player'),
	('Igor Sapała', 'Poland', 'player'),
	('Bryan Passi', 'France', 'player'),
	('Takuya Yasui', 'Japan', 'player'),
	('Afeez Aremu', 'Nigeria', 'player'),
	('Jonas Thorsen', 'Denmark', 'player'),
	('Fridolin Wagner', 'Germany', 'player'),
	('Lu Lin', 'China PR', 'player'),
	('Víctor Mañón', 'Mexico', 'player'),
	('James Vaughan', 'England', 'player'),
	('Kohei Isa', 'Japan', 'player'),
	('Axel Bakayoko', 'France', 'player'),
	('Lee Sang Heon', 'Korea Republic', 'player'),
	('Go Hatano', 'Japan', 'player'),
	('Anass Achahbar', 'Netherlands', 'player'),
	('Glenn Middleton', 'Scotland', 'player'),
	('Faisal Darwish', 'Saudi Arabia', 'player'),
	('Kim Sun Min', 'Korea Republic', 'player'),
	('Oston Urunov', 'Uzbekistan', 'player'),
	('Danel Sinani', 'Luxembourg', 'player'),
	('Matt Lampson', 'United States', 'player'),
	('John O''Sullivan', 'Republic of Ireland', 'player'),
	('Yves-Simon Pambou', 'Congo', 'player'),
	('Kyoung Rok Choi', 'Korea Republic', 'player'),
	('Lucas Dias', 'France', 'player'),
	('Jonathan Ávila', 'Colombia', 'player'),
	('Rodny Cabral', 'Cape Verde', 'player'),
	('Saliou Sané', 'Germany', 'player'),
	('Marc Echarri', 'Spain', 'player'),
	('Federico Andueza', 'Uruguay', 'player'),
	('Dominic Samuel', 'England', 'player'),
	('Philipp Ochs', 'Germany', 'player'),
	('Thuram', 'Brazil', 'player'),
	('Park Won Jae', 'Korea Republic', 'player'),
	('Ronaldo Deaconu', 'Romania', 'player'),
	('Abdullah Al Jadani', 'Saudi Arabia', 'player'),
	('Cristian Melinte', 'Romania', 'player'),
	('Jan Niklas Beste', 'Germany', 'player'),
	('Julian Derstroff', 'Germany', 'player'),
	('Cody Cropper', 'United States', 'player'),
	('Idekel Domínguez', 'Mexico', 'player'),
	('Leonardo Marchi', 'Argentina', 'player'),
	('Hugo Vera Oviedo', 'Paraguay', 'player'),
	('Roy O''Donovan', 'Republic of Ireland', 'player'),
	('Bilel Mohsni', 'Tunisia', 'player'),
	('Marlon Mejía', 'Ecuador', 'player'),
	('Ian Harkes', 'United States', 'player'),
	('Clévid Dikamona', 'Congo', 'player'),
	('Ashtone Morgan', 'Canada', 'player'),
	('Betsiel Hernández', 'Mexico', 'player'),
	('Lassana Doucouré', 'France', 'player'),
	('Gil Burón', 'Mexico', 'player'),
	('Patrick', 'Cape Verde', 'player'),
	('Franco Romero', 'Uruguay', 'player'),
	('John Yeboah', 'Germany', 'player'),
	('Abdulaziz Al Bishi', 'Saudi Arabia', 'player'),
	('Guillem Jaime', 'Spain', 'player'),
	('Sebastián Lentinelly', 'Uruguay', 'player'),
	('Pablo Adorno', 'Paraguay', 'player'),
	('Peng Xinli', 'China PR', 'player'),
	('Stanislav Magkeev', 'Russia', 'player'),
	('Calum Butcher', 'England', 'player'),
	('Salvador Reyes', 'Mexico', 'player'),
	('Mason Toye', 'United States', 'player'),
	('Erik Tallig', 'Germany', 'player'),
	('Adrián Jusino', 'Bolivia', 'player'),
	('Gianfranco Gazzaniga', 'Argentina', 'player'),
	('Vincent Thill', 'Luxembourg', 'player'),
	('João Queirós', 'Portugal', 'player'),
	('Chen Binbin', 'China PR', 'player'),
	('Craig Conway', 'Scotland', 'player'),
	('Raphael Aflalo', 'Brazil', 'player'),
	('Kota Watanabe', 'Japan', 'player'),
	('Bandar Al Mutairi', 'Saudi Arabia', 'player'),
	('Jakub Kamiński', 'Poland', 'player'),
	('Christian Latorre', 'Uruguay', 'player'),
	('Dane Massey', 'Republic of Ireland', 'player'),
	('Zelu', 'Spain', 'player'),
	('Mark O''Hara', 'Scotland', 'player'),
	('Stefan Gölles', 'Austria', 'player'),
	('Ismael Benegas', 'Paraguay', 'player'),
	('Ákos Kecskés', 'Hungary', 'player'),
	('Luke McGee', 'England', 'player'),
	('Bryan Olivera', 'Uruguay', 'player'),
	('Nicolai Næss', 'Norway', 'player'),
	('Dairon Asprilla', 'Colombia', 'player'),
	('Ulysses Llanez Jr.', 'United States', 'player'),
	('Jeon Se Jin', 'Korea Republic', 'player'),
	('Marcio Valverde', 'Peru', 'player'),
	('Óscar Bagüí', 'Ecuador', 'player'),
	('Davor Lovren', 'Croatia', 'player'),
	('Andreias Calcan', 'Romania', 'player'),
	('Brent Kallman', 'United States', 'player'),
	('Duplexe Tchamba', 'Cameroon', 'player'),
	('Jorge Antonio Ortiz', 'Bolivia', 'player'),
	('Donervon Daniels', 'Montserrat', 'player'),
	('Cléo', 'Brazil', 'player'),
	('Lucas Ribeiro', 'Brazil', 'player'),
	('Santiago Brunelli', 'Uruguay', 'player'),
	('Nick Proschwitz', 'Germany', 'player'),
	('Sam Finley', 'England', 'player'),
	('Joel Latibeaudiere', 'England', 'player'),
	('Maxim De Cuyper', 'Belgium', 'player'),
	('Christian Gartner', 'Austria', 'player'),
	('Jordi Escobar', 'Spain', 'player'),
	('Alexander Díaz', 'Argentina', 'player'),
	('Manuel Sutter', 'Austria', 'player'),
	('Dominik Reiter', 'Austria', 'player'),
	('Eirik Schulze', 'Norway', 'player'),
	('Dennis Dressel', 'Germany', 'player'),
	('Mathias Ross', 'Denmark', 'player'),
	('Tobias Jänicke', 'Germany', 'player'),
	('Santiago Bueno', 'Uruguay', 'player'),
	('Jonathan Tamimi', 'Jordan', 'player'),
	('Ross Stewart', 'Scotland', 'player'),
	('Luke Bolton', 'England', 'player'),
	('Deroy Duarte', 'Netherlands', 'player'),
	('Kebba Ceesay', 'Gambia', 'player'),
	('Mingotes', 'Spain', 'player'),
	('Ryan Strain', 'Australia', 'player'),
	('Stefan Maierhofer', 'Austria', 'player'),
	('Janis Antiste', 'France', 'player'),
	('Fali Candé', 'Portugal', 'player'),
	('Nolan Mbemba', 'France', 'player'),
	('Takashi Kanai', 'Japan', 'player'),
	('Joe Pigott', 'England', 'player'),
	('Janik Bachmann', 'Germany', 'player'),
	('Pascal Sohm', 'Germany', 'player'),
	('Brian Figueroa', 'Mexico', 'player'),
	('Leonardo Lukacevic', 'Austria', 'player'),
	('Timo Königsmann', 'Germany', 'player'),
	('Tomislav Tomić', 'Bosnia Herzegovina', 'player'),
	('Ezequías Redín', 'Uruguay', 'player'),
	('Dylan Chambost', 'France', 'player'),
	('Andre Shinyashiki', 'Brazil', 'player'),
	('Yuta Minami', 'Japan', 'player'),
	('Saleh Al Qumayzi', 'Saudi Arabia', 'player'),
	('Alec Georgen', 'France', 'player'),
	('Ahmed Isaiah', 'Nigeria', 'player'),
	('Julian Guttau', 'Germany', 'player'),
	('David Wheater', 'England', 'player'),
	('Tanner Tessmann', 'United States', 'player'),
	('Pavol Šafranko', 'Slovakia', 'player'),
	('Mohamed Ofkir', 'Norway', 'player'),
	('Keshi Anderson', 'England', 'player'),
	('George Francomb', 'England', 'player'),
	('Ass Mandaw Sy', 'Senegal', 'player'),
	('Ali Al Zaqan', 'Saudi Arabia', 'player'),
	('Yutaro Hakamata', 'Japan', 'player'),
	('Kane Wilson', 'England', 'player'),
	('Nicky Law', 'England', 'player'),
	('Andrei Prepeliță', 'Romania', 'player'),
	('Sean Clare', 'England', 'player'),
	('Joshua Kitolano', 'Norway', 'player'),
	('Gennaro Acampora', 'Italy', 'player'),
	('Patrick Ziegler', 'Germany', 'player'),
	('Luka Stojanović', 'Serbia', 'player'),
	('Borja Domínguez', 'Spain', 'player'),
	('Juan Castro', 'Mexico', 'player'),
	('Pascal Steinwender', 'Germany', 'player'),
	('Shaun MacDonald', 'Wales', 'player'),
	('Can Bozdogan', 'Germany', 'player'),
	('Sean Raggett', 'England', 'player'),
	('Álex Martín', 'Spain', 'player'),
	('Cenk Gönen', 'Turkey', 'player'),
	('Katsuhiro Nakayama', 'Japan', 'player'),
	('Alexandru Răuță', 'Romania', 'player'),
	('Patrick Wimmer', 'Austria', 'player'),
	('Takuma Hamasaki', 'Japan', 'player'),
	('Tatsuki Seko', 'Japan', 'player'),
	('Eirik Holmen Johansen', 'Norway', 'player'),
	('Florin Bejan', 'Romania', 'player'),
	('Kieran Agard', 'England', 'player'),
	('Joe Martinez', 'Peru', 'player'),
	('Romel Quiñonez', 'Bolivia', 'player'),
	('Mamudu Moro', 'Ghana', 'player'),
	('Paul McMullan', 'Scotland', 'player'),
	('Conor Hazard', 'Northern Ireland', 'player'),
	('Flavius Daniliuc', 'Austria', 'player'),
	('Michael Gardawski', 'Germany', 'player'),
	('Cameron Borthwick-Jackson', 'England', 'player'),
	('Loïc Bessilé', 'France', 'player'),
	('Markus Halsti', 'Finland', 'player'),
	('Scott Tanser', 'England', 'player'),
	('Koki Saito', 'Japan', 'player'),
	('Nicolás Olsak', 'Argentina', 'player'),
	('Lewis Page', 'England', 'player'),
	('Brian Koglin', 'Germany', 'player'),
	('Kevin Kunz', 'Germany', 'player'),
	('Bevic Moussiti-Oko', 'Congo', 'player'),
	('Karol Danielak', 'Poland', 'player'),
	('Over Mandanda', 'DR Congo', 'player'),
	('Hamdi Akujobi', 'Nigeria', 'player'),
	('Marcin Bułka', 'Poland', 'player'),
	('Anthony Fuentes', 'Peru', 'player'),
	('Iván Cartés', 'Uruguay', 'player'),
	('Alan Cantero', 'Argentina', 'player'),
	('Cristian Tănase', 'Romania', 'player'),
	('Irving Zurita', 'Mexico', 'player'),
	('Mikey Ambrose', 'United States', 'player'),
	('Guevin Tormin', 'France', 'player'),
	('Łukasz Wolsztyński', 'Poland', 'player'),
	('Lucas Ríos', 'Argentina', 'player'),
	('Leon Bell Bell', 'Cameroon', 'player'),
	('Robert Cueto', 'Bolivia', 'player'),
	('Ryoya Morishita', 'Japan', 'player'),
	('Fernando Madrigal', 'Mexico', 'player'),
	('Desevio Payne', 'United States', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Sean Hoare', 'Republic of Ireland', 'hoare'),
	('Sean Hoare', 'Republic of Ireland', 'sean hoare'),
	('Rob Hunt', 'England', 'rob hunt'),
	('Rob Hunt', 'England', 'hunt'),
	('Moritz Nicolas', 'Germany', 'moritz nicolas'),
	('Moritz Nicolas', 'Germany', 'nicolas'),
	('Bobby Adekanye', 'Netherlands', 'bobby adekanye'),
	('Bobby Adekanye', 'Netherlands', 'adekanye'),
	('Janoi Donacien', 'Saint Lucia', 'janoi donacien'),
	('Janoi Donacien', 'Saint Lucia', 'donacien'),
	('David Browne', 'Papua New Guinea', 'david browne'),
	('David Browne', 'Papua New Guinea', 'browne'),
	('Lazaros Rota', 'Greece', 'lazaros rota'),
	('Lazaros Rota', 'Greece', 'rota'),
	('Christian Dahle Borchgrevink', 'Norway', 'christian dahle borchgrevink'),
	('Christian Dahle Borchgrevink', 'Norway', 'borchgrevink'),
	('Ben Tozer', 'England', 'tozer'),
	('Ben Tozer', 'England', 'ben tozer'),
	('Andrija Vukčević', 'Montenegro', 'vukcevic'),
	('Andrija Vukčević', 'Montenegro', 'andrija vukcevic'),
	('Andrés Reyes', 'Colombia', 'andres reyes'),
	('Andrés Reyes', 'Colombia', 'reyes'),
	('Eddy Sylvestre', 'France', 'sylvestre'),
	('Eddy Sylvestre', 'France', 'eddy sylvestre'),
	('Nicolás Messiniti', 'Argentina', 'messiniti'),
	('Nicolás Messiniti', 'Argentina', 'nicolas messiniti'),
	('Dinu Moldovan', 'Romania', 'moldovan'),
	('Dinu Moldovan', 'Romania', 'dinu moldovan'),
	('Ivan Näsberg', 'Norway', 'nasberg'),
	('Ivan Näsberg', 'Norway', 'ivan nasberg'),
	('Belman', 'Spain', 'belman'),
	('Curtis Tilt', 'England', 'curtis tilt'),
	('Curtis Tilt', 'England', 'tilt'),
	('Scott Neville', 'Australia', 'scott neville'),
	('Scott Neville', 'Australia', 'neville'),
	('Mathias Nielsen', 'Denmark', 'nielsen'),
	('Mathias Nielsen', 'Denmark', 'mathias nielsen'),
	('Emiliano Alfaro', 'Uruguay', 'emiliano alfaro'),
	('Emiliano Alfaro', 'Uruguay', 'alfaro'),
	('Maksim Glushenkov', 'Russia', 'maksim glushenkov'),
	('Maksim Glushenkov', 'Russia', 'glushenkov'),
	('Jordan Hamilton', 'Canada', 'jordan hamilton'),
	('Jordan Hamilton', 'Canada', 'hamilton'),
	('Yuki Abe', 'Japan', 'abe'),
	('Yuki Abe', 'Japan', 'yuki abe'),
	('Johan Mina', 'Ecuador', 'johan mina'),
	('Johan Mina', 'Ecuador', 'mina'),
	('Scott Caldwell', 'United States', 'caldwell'),
	('Scott Caldwell', 'United States', 'scott caldwell'),
	('Federico Navarro', 'Argentina', 'federico navarro'),
	('Federico Navarro', 'Argentina', 'navarro'),
	('Piotr Tomasik', 'Poland', 'piotr tomasik'),
	('Piotr Tomasik', 'Poland', 'tomasik'),
	('Matt Bloomfield', 'England', 'matt bloomfield'),
	('Matt Bloomfield', 'England', 'bloomfield'),
	('Serkan Asan', 'Turkey', 'asan'),
	('Serkan Asan', 'Turkey', 'serkan asan'),
	('Sebastian Bauer', 'Austria', 'sebastian bauer'),
	('Sebastian Bauer', 'Austria', 'bauer'),
	('Kortne Ford', 'United States', 'kortne ford'),
	('Kortne Ford', 'United States', 'ford'),
	('Naoki Yamada', 'Japan', 'naoki yamada'),
	('Naoki Yamada', 'Japan', 'yamada'),
	('Jonas Nietfeld', 'Germany', 'nietfeld'),
	('Jonas Nietfeld', 'Germany', 'jonas nietfeld'),
	('Josh Vela', 'England', 'josh vela'),
	('Josh Vela', 'England', 'vela'),
	('Michael Almebäck', 'Sweden', 'almeback'),
	('Michael Almebäck', 'Sweden', 'michael almeback'),
	('Darlin Yongwa', 'Cameroon', 'darlin yongwa'),
	('Darlin Yongwa', 'Cameroon', 'yongwa'),
	('Tyrick Mitchell', 'England', 'mitchell'),
	('Tyrick Mitchell', 'England', 'tyrick mitchell'),
	('Jayson Leutwiler', 'Canada', 'jayson leutwiler'),
	('Jayson Leutwiler', 'Canada', 'leutwiler'),
	('Kim Soo Beom', 'Korea Republic', 'kim soo beom'),
	('Kim Soo Beom', 'Korea Republic', 'beom'),
	('Alex Gilliead', 'England', 'gilliead'),
	('Alex Gilliead', 'England', 'alex gilliead'),
	('Leo Bengtsson', 'Sweden', 'bengtsson'),
	('Leo Bengtsson', 'Sweden', 'leo bengtsson'),
	('Patryk Lipski', 'Poland', 'patryk lipski'),
	('Patryk Lipski', 'Poland', 'lipski'),
	('Alexis Maldonado', 'Argentina', 'maldonado'),
	('Alexis Maldonado', 'Argentina', 'alexis maldonado'),
	('Igor Sapała', 'Poland', 'igor sapaa'),
	('Igor Sapała', 'Poland', 'sapaa'),
	('Bryan Passi', 'France', 'bryan passi'),
	('Bryan Passi', 'France', 'passi'),
	('Takuya Yasui', 'Japan', 'takuya yasui'),
	('Takuya Yasui', 'Japan', 'yasui'),
	('Afeez Aremu', 'Nigeria', 'afeez aremu'),
	('Afeez Aremu', 'Nigeria', 'aremu'),
	('Jonas Thorsen', 'Denmark', 'jonas thorsen'),
	('Jonas Thorsen', 'Denmark', 'thorsen'),
	('Fridolin Wagner', 'Germany', 'wagner'),
	('Fridolin Wagner', 'Germany', 'fridolin wagner'),
	('Lu Lin', 'China PR', 'lu lin'),
	('Lu Lin', 'China PR', 'lin'),
	('Víctor Mañón', 'Mexico', 'manon'),
	('Víctor Mañón', 'Mexico', 'victor manon'),
	('James Vaughan', 'England', 'vaughan'),
	('James Vaughan', 'England', 'james vaughan'),
	('Kohei Isa', 'Japan', 'kohei isa'),
	('Kohei Isa', 'Japan', 'isa'),
	('Axel Bakayoko', 'France', 'axel bakayoko'),
	('Axel Bakayoko', 'France', 'bakayoko'),
	('Lee Sang Heon', 'Korea Republic', 'heon'),
	('Lee Sang Heon', 'Korea Republic', 'lee sang heon'),
	('Go Hatano', 'Japan', 'go hatano'),
	('Go Hatano', 'Japan', 'hatano'),
	('Anass Achahbar', 'Netherlands', 'achahbar'),
	('Anass Achahbar', 'Netherlands', 'anass achahbar'),
	('Glenn Middleton', 'Scotland', 'glenn middleton'),
	('Glenn Middleton', 'Scotland', 'middleton'),
	('Faisal Darwish', 'Saudi Arabia', 'darwish'),
	('Faisal Darwish', 'Saudi Arabia', 'faisal darwish'),
	('Kim Sun Min', 'Korea Republic', 'kim sun min'),
	('Kim Sun Min', 'Korea Republic', 'min'),
	('Oston Urunov', 'Uzbekistan', 'urunov'),
	('Oston Urunov', 'Uzbekistan', 'oston urunov'),
	('Danel Sinani', 'Luxembourg', 'danel sinani'),
	('Danel Sinani', 'Luxembourg', 'sinani'),
	('Matt Lampson', 'United States', 'matt lampson'),
	('Matt Lampson', 'United States', 'lampson'),
	('John O''Sullivan', 'Republic of Ireland', 'osullivan'),
	('John O''Sullivan', 'Republic of Ireland', 'john osullivan'),
	('Yves-Simon Pambou', 'Congo', 'yvessimon pambou'),
	('Yves-Simon Pambou', 'Congo', 'pambou'),
	('Kyoung Rok Choi', 'Korea Republic', 'choi'),
	('Kyoung Rok Choi', 'Korea Republic', 'kyoung rok choi'),
	('Lucas Dias', 'France', 'dias'),
	('Lucas Dias', 'France', 'lucas dias'),
	('Jonathan Ávila', 'Colombia', 'jonathan avila'),
	('Jonathan Ávila', 'Colombia', 'avila'),
	('Rodny Cabral', 'Cape Verde', 'rodny cabral'),
	('Rodny Cabral', 'Cape Verde', 'cabral'),
	('Saliou Sané', 'Germany', 'saliou sane'),
	('Saliou Sané', 'Germany', 'sane'),
	('Marc Echarri', 'Spain', 'echarri'),
	('Marc Echarri', 'Spain', 'marc echarri'),
	('Federico Andueza', 'Uruguay', 'andueza'),
	('Federico Andueza', 'Uruguay', 'federico andueza'),
	('Dominic Samuel', 'England', 'samuel'),
	('Dominic Samuel', 'England', 'dominic samuel'),
	('Philipp Ochs', 'Germany', 'ochs'),
	('Philipp Ochs', 'Germany', 'philipp ochs'),
	('Thuram', 'Brazil', 'thuram'),
	('Park Won Jae', 'Korea Republic', 'park won jae'),
	('Park Won Jae', 'Korea Republic', 'jae'),
	('Ronaldo Deaconu', 'Romania', 'ronaldo deaconu'),
	('Ronaldo Deaconu', 'Romania', 'deaconu'),
	('Abdullah Al Jadani', 'Saudi Arabia', 'abdullah al jadani'),
	('Abdullah Al Jadani', 'Saudi Arabia', 'jadani'),
	('Cristian Melinte', 'Romania', 'cristian melinte'),
	('Cristian Melinte', 'Romania', 'melinte'),
	('Jan Niklas Beste', 'Germany', 'beste'),
	('Jan Niklas Beste', 'Germany', 'jan niklas beste'),
	('Julian Derstroff', 'Germany', 'derstroff'),
	('Julian Derstroff', 'Germany', 'julian derstroff'),
	('Cody Cropper', 'United States', 'cody cropper'),
	('Cody Cropper', 'United States', 'cropper'),
	('Idekel Domínguez', 'Mexico', 'dominguez'),
	('Idekel Domínguez', 'Mexico', 'idekel dominguez'),
	('Leonardo Marchi', 'Argentina', 'leonardo marchi'),
	('Leonardo Marchi', 'Argentina', 'marchi'),
	('Hugo Vera Oviedo', 'Paraguay', 'oviedo'),
	('Hugo Vera Oviedo', 'Paraguay', 'hugo vera oviedo'),
	('Roy O''Donovan', 'Republic of Ireland', 'roy odonovan'),
	('Roy O''Donovan', 'Republic of Ireland', 'odonovan'),
	('Bilel Mohsni', 'Tunisia', 'mohsni'),
	('Bilel Mohsni', 'Tunisia', 'bilel mohsni'),
	('Marlon Mejía', 'Ecuador', 'mejia'),
	('Marlon Mejía', 'Ecuador', 'marlon mejia'),
	('Ian Harkes', 'United States', 'harkes'),
	('Ian Harkes', 'United States', 'ian harkes'),
	('Clévid Dikamona', 'Congo', 'dikamona'),
	('Clévid Dikamona', 'Congo', 'clevid dikamona'),
	('Ashtone Morgan', 'Canada', 'ashtone morgan'),
	('Ashtone Morgan', 'Canada', 'morgan'),
	('Betsiel Hernández', 'Mexico', 'betsiel hernandez'),
	('Betsiel Hernández', 'Mexico', 'hernandez'),
	('Lassana Doucouré', 'France', 'doucoure'),
	('Lassana Doucouré', 'France', 'lassana doucoure'),
	('Gil Burón', 'Mexico', 'buron'),
	('Gil Burón', 'Mexico', 'gil buron'),
	('Patrick', 'Cape Verde', 'patrick'),
	('Franco Romero', 'Uruguay', 'franco romero'),
	('Franco Romero', 'Uruguay', 'romero'),
	('John Yeboah', 'Germany', 'john yeboah'),
	('John Yeboah', 'Germany', 'yeboah'),
	('Abdulaziz Al Bishi', 'Saudi Arabia', 'abdulaziz al bishi'),
	('Abdulaziz Al Bishi', 'Saudi Arabia', 'bishi'),
	('Guillem Jaime', 'Spain', 'guillem jaime'),
	('Guillem Jaime', 'Spain', 'jaime'),
	('Sebastián Lentinelly', 'Uruguay', 'lentinelly'),
	('Sebastián Lentinelly', 'Uruguay', 'sebastian lentinelly'),
	('Pablo Adorno', 'Paraguay', 'pablo adorno'),
	('Pablo Adorno', 'Paraguay', 'adorno'),
	('Peng Xinli', 'China PR', 'peng xinli'),
	('Peng Xinli', 'China PR', 'xinli'),
	('Stanislav Magkeev', 'Russia', 'stanislav magkeev'),
	('Stanislav Magkeev', 'Russia', 'magkeev'),
	('Calum Butcher', 'England', 'calum butcher'),
	('Calum Butcher', 'England', 'butcher'),
	('Salvador Reyes', 'Mexico', 'salvador reyes'),
	('Salvador Reyes', 'Mexico', 'reyes'),
	('Mason Toye', 'United States', 'mason toye'),
	('Mason Toye', 'United States', 'toye'),
	('Erik Tallig', 'Germany', 'erik tallig'),
	('Erik Tallig', 'Germany', 'tallig'),
	('Adrián Jusino', 'Bolivia', 'jusino'),
	('Adrián Jusino', 'Bolivia', 'adrian jusino'),
	('Gianfranco Gazzaniga', 'Argentina', 'gianfranco gazzaniga'),
	('Gianfranco Gazzaniga', 'Argentina', 'gazzaniga'),
	('Vincent Thill', 'Luxembourg', 'thill'),
	('Vincent Thill', 'Luxembourg', 'vincent thill'),
	('João Queirós', 'Portugal', 'joao queiros'),
	('João Queirós', 'Portugal', 'queiros'),
	('Chen Binbin', 'China PR', 'chen binbin'),
	('Chen Binbin', 'China PR', 'binbin'),
	('Craig Conway', 'Scotland', 'conway'),
	('Craig Conway', 'Scotland', 'craig conway'),
	('Raphael Aflalo', 'Brazil', 'raphael aflalo'),
	('Raphael Aflalo', 'Brazil', 'aflalo'),
	('Kota Watanabe', 'Japan', 'watanabe'),
	('Kota Watanabe', 'Japan', 'kota watanabe'),
	('Bandar Al Mutairi', 'Saudi Arabia', 'bandar al mutairi'),
	('Bandar Al Mutairi', 'Saudi Arabia', 'mutairi'),
	('Jakub Kamiński', 'Poland', 'jakub kaminski'),
	('Jakub Kamiński', 'Poland', 'kaminski'),
	('Christian Latorre', 'Uruguay', 'latorre'),
	('Christian Latorre', 'Uruguay', 'christian latorre'),
	('Dane Massey', 'Republic of Ireland', 'massey'),
	('Dane Massey', 'Republic of Ireland', 'dane massey'),
	('Zelu', 'Spain', 'zelu'),
	('Mark O''Hara', 'Scotland', 'ohara'),
	('Mark O''Hara', 'Scotland', 'mark ohara'),
	('Stefan Gölles', 'Austria', 'stefan golles'),
	('Stefan Gölles', 'Austria', 'golles'),
	('Ismael Benegas', 'Paraguay', 'ismael benegas'),
	('Ismael Benegas', 'Paraguay', 'benegas'),
	('Ákos Kecskés', 'Hungary', 'akos kecskes'),
	('Ákos Kecskés', 'Hungary', 'kecskes'),
	('Luke McGee', 'England', 'luke mcgee'),
	('Luke McGee', 'England', 'mcgee'),
	('Bryan Olivera', 'Uruguay', 'olivera'),
	('Bryan Olivera', 'Uruguay', 'bryan olivera'),
	('Nicolai Næss', 'Norway', 'nss'),
	('Nicolai Næss', 'Norway', 'nicolai nss'),
	('Dairon Asprilla', 'Colombia', 'asprilla'),
	('Dairon Asprilla', 'Colombia', 'dairon asprilla'),
	('Ulysses Llanez Jr.', 'United States', 'jr'),
	('Ulysses Llanez Jr.', 'United States', 'ulysses llanez jr'),
	('Jeon Se Jin', 'Korea Republic', 'jin'),
	('Jeon Se Jin', 'Korea Republic', 'jeon se jin'),
	('Marcio Valverde', 'Peru', 'valverde'),
	('Marcio Valverde', 'Peru', 'marcio valverde'),
	('Óscar Bagüí', 'Ecuador', 'bagui'),
	('Óscar Bagüí', 'Ecuador', 'oscar bagui'),
	('Davor Lovren', 'Croatia', 'davor lovren'),
	('Davor Lovren', 'Croatia', 'lovren'),
	('Andreias Calcan', 'Romania', 'andreias calcan'),
	('Andreias Calcan', 'Romania', 'calcan'),
	('Brent Kallman', 'United States', 'brent kallman'),
	('Brent Kallman', 'United States', 'kallman'),
	('Duplexe Tchamba', 'Cameroon', 'tchamba'),
	('Duplexe Tchamba', 'Cameroon', 'duplexe tchamba'),
	('Jorge Antonio Ortiz', 'Bolivia', 'jorge antonio ortiz'),
	('Jorge Antonio Ortiz', 'Bolivia', 'ortiz'),
	('Donervon Daniels', 'Montserrat', 'donervon daniels'),
	('Donervon Daniels', 'Montserrat', 'daniels'),
	('Cléo', 'Brazil', 'cleo'),
	('Lucas Ribeiro', 'Brazil', 'ribeiro'),
	('Lucas Ribeiro', 'Brazil', 'lucas ribeiro'),
	('Santiago Brunelli', 'Uruguay', 'brunelli'),
	('Santiago Brunelli', 'Uruguay', 'santiago brunelli'),
	('Nick Proschwitz', 'Germany', 'proschwitz'),
	('Nick Proschwitz', 'Germany', 'nick proschwitz'),
	('Sam Finley', 'England', 'finley'),
	('Sam Finley', 'England', 'sam finley'),
	('Joel Latibeaudiere', 'England', 'latibeaudiere'),
	('Joel Latibeaudiere', 'England', 'joel latibeaudiere'),
	('Maxim De Cuyper', 'Belgium', 'cuyper'),
	('Maxim De Cuyper', 'Belgium', 'maxim de cuyper'),
	('Christian Gartner', 'Austria', 'gartner'),
	('Christian Gartner', 'Austria', 'christian gartner'),
	('Jordi Escobar', 'Spain', 'escobar'),
	('Jordi Escobar', 'Spain', 'jordi escobar'),
	('Alexander Díaz', 'Argentina', 'alexander diaz'),
	('Alexander Díaz', 'Argentina', 'diaz'),
	('Manuel Sutter', 'Austria', 'sutter'),
	('Manuel Sutter', 'Austria', 'manuel sutter'),
	('Dominik Reiter', 'Austria', 'reiter'),
	('Dominik Reiter', 'Austria', 'dominik reiter'),
	('Eirik Schulze', 'Norway', 'schulze'),
	('Eirik Schulze', 'Norway', 'eirik schulze'),
	('Dennis Dressel', 'Germany', 'dressel'),
	('Dennis Dressel', 'Germany', 'dennis dressel'),
	('Mathias Ross', 'Denmark', 'ross'),
	('Mathias Ross', 'Denmark', 'mathias ross'),
	('Tobias Jänicke', 'Germany', 'janicke'),
	('Tobias Jänicke', 'Germany', 'tobias janicke'),
	('Santiago Bueno', 'Uruguay', 'bueno'),
	('Santiago Bueno', 'Uruguay', 'santiago bueno'),
	('Jonathan Tamimi', 'Jordan', 'jonathan tamimi'),
	('Jonathan Tamimi', 'Jordan', 'tamimi'),
	('Ross Stewart', 'Scotland', 'stewart'),
	('Ross Stewart', 'Scotland', 'ross stewart'),
	('Luke Bolton', 'England', 'bolton'),
	('Luke Bolton', 'England', 'luke bolton'),
	('Deroy Duarte', 'Netherlands', 'duarte'),
	('Deroy Duarte', 'Netherlands', 'deroy duarte'),
	('Kebba Ceesay', 'Gambia', 'ceesay'),
	('Kebba Ceesay', 'Gambia', 'kebba ceesay'),
	('Mingotes', 'Spain', 'mingotes'),
	('Ryan Strain', 'Australia', 'ryan strain'),
	('Ryan Strain', 'Australia', 'strain'),
	('Stefan Maierhofer', 'Austria', 'maierhofer'),
	('Stefan Maierhofer', 'Austria', 'stefan maierhofer'),
	('Janis Antiste', 'France', 'antiste'),
	('Janis Antiste', 'France', 'janis antiste'),
	('Fali Candé', 'Portugal', 'cande'),
	('Fali Candé', 'Portugal', 'fali cande'),
	('Nolan Mbemba', 'France', 'mbemba'),
	('Nolan Mbemba', 'France', 'nolan mbemba'),
	('Takashi Kanai', 'Japan', 'takashi kanai'),
	('Takashi Kanai', 'Japan', 'kanai'),
	('Joe Pigott', 'England', 'joe pigott'),
	('Joe Pigott', 'England', 'pigott'),
	('Janik Bachmann', 'Germany', 'janik bachmann'),
	('Janik Bachmann', 'Germany', 'bachmann'),
	('Pascal Sohm', 'Germany', 'pascal sohm'),
	('Pascal Sohm', 'Germany', 'sohm'),
	('Brian Figueroa', 'Mexico', 'figueroa'),
	('Brian Figueroa', 'Mexico', 'brian figueroa'),
	('Leonardo Lukacevic', 'Austria', 'lukacevic'),
	('Leonardo Lukacevic', 'Austria', 'leonardo lukacevic'),
	('Timo Königsmann', 'Germany', 'konigsmann'),
	('Timo Königsmann', 'Germany', 'timo konigsmann'),
	('Tomislav Tomić', 'Bosnia Herzegovina', 'tomic'),
	('Tomislav Tomić', 'Bosnia Herzegovina', 'tomislav tomic'),
	('Ezequías Redín', 'Uruguay', 'ezequias redin'),
	('Ezequías Redín', 'Uruguay', 'redin'),
	('Dylan Chambost', 'France', 'chambost'),
	('Dylan Chambost', 'France', 'dylan chambost'),
	('Andre Shinyashiki', 'Brazil', 'shinyashiki'),
	('Andre Shinyashiki', 'Brazil', 'andre shinyashiki'),
	('Yuta Minami', 'Japan', 'minami'),
	('Yuta Minami', 'Japan', 'yuta minami'),
	('Saleh Al Qumayzi', 'Saudi Arabia', 'saleh al qumayzi'),
	('Saleh Al Qumayzi', 'Saudi Arabia', 'qumayzi'),
	('Alec Georgen', 'France', 'georgen'),
	('Alec Georgen', 'France', 'alec georgen'),
	('Ahmed Isaiah', 'Nigeria', 'ahmed isaiah'),
	('Ahmed Isaiah', 'Nigeria', 'isaiah'),
	('Julian Guttau', 'Germany', 'julian guttau'),
	('Julian Guttau', 'Germany', 'guttau'),
	('David Wheater', 'England', 'wheater'),
	('David Wheater', 'England', 'david wheater'),
	('Tanner Tessmann', 'United States', 'tanner tessmann'),
	('Tanner Tessmann', 'United States', 'tessmann'),
	('Pavol Šafranko', 'Slovakia', 'pavol safranko'),
	('Pavol Šafranko', 'Slovakia', 'safranko'),
	('Mohamed Ofkir', 'Norway', 'ofkir'),
	('Mohamed Ofkir', 'Norway', 'mohamed ofkir'),
	('Keshi Anderson', 'England', 'keshi anderson'),
	('Keshi Anderson', 'England', 'anderson'),
	('George Francomb', 'England', 'francomb'),
	('George Francomb', 'England', 'george francomb'),
	('Ass Mandaw Sy', 'Senegal', 'ass mandaw sy'),
	('Ass Mandaw Sy', 'Senegal', 'sy'),
	('Ali Al Zaqan', 'Saudi Arabia', 'ali al zaqan'),
	('Ali Al Zaqan', 'Saudi Arabia', 'zaqan'),
	('Yutaro Hakamata', 'Japan', 'yutaro hakamata'),
	('Yutaro Hakamata', 'Japan', 'hakamata'),
	('Kane Wilson', 'England', 'wilson'),
	('Kane Wilson', 'England', 'kane wilson'),
	('Nicky Law', 'England', 'nicky law'),
	('Nicky Law', 'England', 'law'),
	('Andrei Prepeliță', 'Romania', 'andrei prepelita'),
	('Andrei Prepeliță', 'Romania', 'prepelita'),
	('Sean Clare', 'England', 'sean clare'),
	('Sean Clare', 'England', 'clare'),
	('Joshua Kitolano', 'Norway', 'kitolano'),
	('Joshua Kitolano', 'Norway', 'joshua kitolano'),
	('Gennaro Acampora', 'Italy', 'gennaro acampora'),
	('Gennaro Acampora', 'Italy', 'acampora'),
	('Patrick Ziegler', 'Germany', 'ziegler'),
	('Patrick Ziegler', 'Germany', 'patrick ziegler'),
	('Luka Stojanović', 'Serbia', 'stojanovic'),
	('Luka Stojanović', 'Serbia', 'luka stojanovic'),
	('Borja Domínguez', 'Spain', 'dominguez'),
	('Borja Domínguez', 'Spain', 'borja dominguez'),
	('Juan Castro', 'Mexico', 'juan castro'),
	('Juan Castro', 'Mexico', 'castro'),
	('Pascal Steinwender', 'Germany', 'steinwender'),
	('Pascal Steinwender', 'Germany', 'pascal steinwender'),
	('Shaun MacDonald', 'Wales', 'shaun macdonald'),
	('Shaun MacDonald', 'Wales', 'macdonald'),
	('Can Bozdogan', 'Germany', 'bozdogan'),
	('Can Bozdogan', 'Germany', 'can bozdogan'),
	('Sean Raggett', 'England', 'raggett'),
	('Sean Raggett', 'England', 'sean raggett'),
	('Álex Martín', 'Spain', 'alex martin'),
	('Álex Martín', 'Spain', 'martin'),
	('Cenk Gönen', 'Turkey', 'gonen'),
	('Cenk Gönen', 'Turkey', 'cenk gonen'),
	('Katsuhiro Nakayama', 'Japan', 'katsuhiro nakayama'),
	('Katsuhiro Nakayama', 'Japan', 'nakayama'),
	('Alexandru Răuță', 'Romania', 'alexandru rauta'),
	('Alexandru Răuță', 'Romania', 'rauta'),
	('Patrick Wimmer', 'Austria', 'wimmer'),
	('Patrick Wimmer', 'Austria', 'patrick wimmer'),
	('Takuma Hamasaki', 'Japan', 'takuma hamasaki'),
	('Takuma Hamasaki', 'Japan', 'hamasaki'),
	('Tatsuki Seko', 'Japan', 'tatsuki seko'),
	('Tatsuki Seko', 'Japan', 'seko'),
	('Eirik Holmen Johansen', 'Norway', 'johansen'),
	('Eirik Holmen Johansen', 'Norway', 'eirik holmen johansen'),
	('Florin Bejan', 'Romania', 'bejan'),
	('Florin Bejan', 'Romania', 'florin bejan'),
	('Kieran Agard', 'England', 'agard'),
	('Kieran Agard', 'England', 'kieran agard'),
	('Joe Martinez', 'Peru', 'joe martinez'),
	('Joe Martinez', 'Peru', 'martinez'),
	('Romel Quiñonez', 'Bolivia', 'quinonez'),
	('Romel Quiñonez', 'Bolivia', 'romel quinonez'),
	('Mamudu Moro', 'Ghana', 'moro'),
	('Mamudu Moro', 'Ghana', 'mamudu moro'),
	('Paul McMullan', 'Scotland', 'paul mcmullan'),
	('Paul McMullan', 'Scotland', 'mcmullan'),
	('Conor Hazard', 'Northern Ireland', 'hazard'),
	('Conor Hazard', 'Northern Ireland', 'conor hazard'),
	('Flavius Daniliuc', 'Austria', 'daniliuc'),
	('Flavius Daniliuc', 'Austria', 'flavius daniliuc'),
	('Michael Gardawski', 'Germany', 'michael gardawski'),
	('Michael Gardawski', 'Germany', 'gardawski'),
	('Cameron Borthwick-Jackson', 'England', 'cameron borthwickjackson'),
	('Cameron Borthwick-Jackson', 'England', 'borthwickjackson'),
	('Loïc Bessilé', 'France', 'loic bessile'),
	('Loïc Bessilé', 'France', 'bessile'),
	('Markus Halsti', 'Finland', 'halsti'),
	('Markus Halsti', 'Finland', 'markus halsti'),
	('Scott Tanser', 'England', 'tanser'),
	('Scott Tanser', 'England', 'scott tanser'),
	('Koki Saito', 'Japan', 'koki saito'),
	('Koki Saito', 'Japan', 'saito'),
	('Nicolás Olsak', 'Argentina', 'olsak'),
	('Nicolás Olsak', 'Argentina', 'nicolas olsak'),
	('Lewis Page', 'England', 'lewis page'),
	('Lewis Page', 'England', 'page'),
	('Brian Koglin', 'Germany', 'brian koglin'),
	('Brian Koglin', 'Germany', 'koglin'),
	('Kevin Kunz', 'Germany', 'kunz'),
	('Kevin Kunz', 'Germany', 'kevin kunz'),
	('Bevic Moussiti-Oko', 'Congo', 'moussitioko'),
	('Bevic Moussiti-Oko', 'Congo', 'bevic moussitioko'),
	('Karol Danielak', 'Poland', 'karol danielak'),
	('Karol Danielak', 'Poland', 'danielak'),
	('Over Mandanda', 'DR Congo', 'over mandanda'),
	('Over Mandanda', 'DR Congo', 'mandanda'),
	('Hamdi Akujobi', 'Nigeria', 'akujobi'),
	('Hamdi Akujobi', 'Nigeria', 'hamdi akujobi'),
	('Marcin Bułka', 'Poland', 'marcin buka'),
	('Marcin Bułka', 'Poland', 'buka'),
	('Anthony Fuentes', 'Peru', 'anthony fuentes'),
	('Anthony Fuentes', 'Peru', 'fuentes'),
	('Iván Cartés', 'Uruguay', 'ivan cartes'),
	('Iván Cartés', 'Uruguay', 'cartes'),
	('Alan Cantero', 'Argentina', 'alan cantero'),
	('Alan Cantero', 'Argentina', 'cantero'),
	('Cristian Tănase', 'Romania', 'tanase'),
	('Cristian Tănase', 'Romania', 'cristian tanase'),
	('Irving Zurita', 'Mexico', 'irving zurita'),
	('Irving Zurita', 'Mexico', 'zurita'),
	('Mikey Ambrose', 'United States', 'mikey ambrose'),
	('Mikey Ambrose', 'United States', 'ambrose'),
	('Guevin Tormin', 'France', 'tormin'),
	('Guevin Tormin', 'France', 'guevin tormin'),
	('Łukasz Wolsztyński', 'Poland', 'wolsztynski'),
	('Łukasz Wolsztyński', 'Poland', 'ukasz wolsztynski'),
	('Lucas Ríos', 'Argentina', 'lucas rios'),
	('Lucas Ríos', 'Argentina', 'rios'),
	('Leon Bell Bell', 'Cameroon', 'leon bell bell'),
	('Leon Bell Bell', 'Cameroon', 'bell'),
	('Robert Cueto', 'Bolivia', 'cueto'),
	('Robert Cueto', 'Bolivia', 'robert cueto'),
	('Ryoya Morishita', 'Japan', 'morishita'),
	('Ryoya Morishita', 'Japan', 'ryoya morishita'),
	('Fernando Madrigal', 'Mexico', 'madrigal'),
	('Fernando Madrigal', 'Mexico', 'fernando madrigal'),
	('Desevio Payne', 'United States', 'desevio payne'),
	('Desevio Payne', 'United States', 'payne')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';