INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Masakazu Tashiro', 'Japan', 'player'),
	('Harry Pell', 'England', 'player'),
	('Danny Mayor', 'England', 'player'),
	('Aurélien Tertereau', 'France', 'player'),
	('Sacha Boey', 'France', 'player'),
	('Kuki Zalazar', 'Spain', 'player'),
	('Eduardo Herrera', 'Mexico', 'player'),
	('Ilyas Chouaref', 'France', 'player'),
	('Ben Williams', 'Wales', 'player'),
	('Crysan', 'Brazil', 'player'),
	('Branislav Niňaj', 'Slovakia', 'player'),
	('Nikolas Dyhr', 'Denmark', 'player'),
	('Yanis Hamache', 'France', 'player'),
	('Horacio Salaberry', 'Uruguay', 'player'),
	('Hallur Hansson', 'Faroe Islands', 'player'),
	('Ebou Adams', 'Gambia', 'player'),
	('Daiki Sugioka', 'Japan', 'player'),
	('Joel Fernández', 'Bolivia', 'player'),
	('Alexander Juel Andersen', 'Denmark', 'player'),
	('Illia Zabarnyi', 'Ukraine', 'player'),
	('Eray Birniçan', 'Turkey', 'player'),
	('Darren Pratley', 'England', 'player'),
	('Stian Aasmundsen', 'Norway', 'player'),
	('Harry Chapman', 'England', 'player'),
	('Kaoru Takayama', 'Japan', 'player'),
	('Gijs Smal', 'Netherlands', 'player'),
	('Troels Kløve', 'Denmark', 'player'),
	('Simon Skrabb', 'Finland', 'player'),
	('Agustín Doffo', 'Argentina', 'player'),
	('Sean Long', 'Republic of Ireland', 'player'),
	('Kévin Denkey', 'Togo', 'player'),
	('Marin Aničić', 'Bosnia Herzegovina', 'player'),
	('Iván Bravo', 'Spain', 'player'),
	('Konrad Forenc', 'Poland', 'player'),
	('Joaquín Varela', 'Argentina', 'player'),
	('Tim Payne', 'New Zealand', 'player'),
	('Cho Dong Gun', 'Korea Republic', 'player'),
	('Coll Donaldson', 'Scotland', 'player'),
	('Ahn Joon Soo', 'Korea Republic', 'player'),
	('Sulejman Krpić', 'Bosnia Herzegovina', 'player'),
	('Iván Ramírez', 'Paraguay', 'player'),
	('Josh Dacres-Cogley', 'England', 'player'),
	('Samy Mmaee', 'Belgium', 'player'),
	('Bjarke Jacobsen', 'Denmark', 'player'),
	('Kim Nam Chun', 'Korea Republic', 'player'),
	('Tobias Christensen', 'Norway', 'player'),
	('Pol Freixanet', 'Spain', 'player'),
	('Daniel Bartl', 'Czech Republic', 'player'),
	('Fernand Mayembo', 'Congo', 'player'),
	('Godfried Roemeratoe', 'Netherlands', 'player'),
	('Birama Ndoye', 'Senegal', 'player'),
	('Okan Kocuk', 'Turkey', 'player'),
	('Pascal Breier', 'Germany', 'player'),
	('Sebastian Milewski', 'Poland', 'player'),
	('Mansur', 'Brazil', 'player'),
	('Juan Aponte', 'Bolivia', 'player'),
	('Vitalie Damascan', 'Moldova', 'player'),
	('Alexander Bittroff', 'Germany', 'player'),
	('Stanley Elbers', 'Netherlands', 'player'),
	('Benjamín Vidal', 'Chile', 'player'),
	('Koya Yuruki', 'Japan', 'player'),
	('Joachim Eickmayer', 'France', 'player'),
	('Akimi Barada', 'Japan', 'player'),
	('Oscar Añez', 'Bolivia', 'player'),
	('İbrahim Akdağ', 'Turkey', 'player'),
	('Arturo Molina', 'Spain', 'player'),
	('Jeremy Cijntje', 'Curacao', 'player'),
	('Gálvez', 'Spain', 'player'),
	('Lukas Gugganig', 'Austria', 'player'),
	('Ahmed Sharahili', 'Saudi Arabia', 'player'),
	('James Bolton', 'England', 'player'),
	('Mustafa Abdellaoue', 'Norway', 'player'),
	('Vincent Trummer', 'Austria', 'player'),
	('Bilal Hussein', 'Sweden', 'player'),
	('Luke Joyce', 'England', 'player'),
	('Radosław Cierzniak', 'Poland', 'player'),
	('Jason Knight', 'Republic of Ireland', 'player'),
	('Ryan McLaughlin', 'Northern Ireland', 'player'),
	('Mohanad Salem', 'United Arab Emirates', 'player'),
	('Jean Peña', 'Ecuador', 'player'),
	('Benjamin Siegrist', 'Switzerland', 'player'),
	('Lukas Grozurek', 'Austria', 'player'),
	('Brandon Haunstrup', 'England', 'player'),
	('Diego Montiel', 'Sweden', 'player'),
	('Ariajasuru Hasegawa', 'Japan', 'player'),
	('Jordi Cortizo', 'Mexico', 'player'),
	('Sebastián Méndez', 'Ecuador', 'player'),
	('George Davies', 'Sierra Leone', 'player'),
	('Tomislav Kiš', 'Croatia', 'player'),
	('Han Seung Gyu', 'Korea Republic', 'player'),
	('Jason Cummings', 'Scotland', 'player'),
	('Nicolò Armini', 'Italy', 'player'),
	('Philipp Netzer', 'Austria', 'player'),
	('Simon Skarlatidis', 'Germany', 'player'),
	('Nicke Kabamba', 'England', 'player'),
	('Daouda Peeters', 'Belgium', 'player'),
	('Dominik Wydra', 'Austria', 'player'),
	('Oliver Valaker Edvardsen', 'Norway', 'player'),
	('Maureen Franco', 'Uruguay', 'player'),
	('Aynsley Pears', 'England', 'player'),
	('István Fülöp', 'Romania', 'player'),
	('Sven Sonnenberg', 'Germany', 'player'),
	('Fotis Ioannidis', 'Greece', 'player'),
	('Guilherme Mantuan', 'Brazil', 'player'),
	('Thomas Eisfeld', 'Germany', 'player'),
	('Wilder Cartagena', 'Peru', 'player'),
	('Javier Parraguez', 'Chile', 'player'),
	('Cho Jae Wan', 'Korea Republic', 'player'),
	('Yoshiki Matsushita', 'Japan', 'player'),
	('Alec Deneumostier', 'Peru', 'player'),
	('Richie Towell', 'Republic of Ireland', 'player'),
	('Yusuf Demir', 'Austria', 'player'),
	('Marvin Martin', 'France', 'player'),
	('Min Sang Gi', 'Korea Republic', 'player'),
	('Billy Jones', 'England', 'player'),
	('Victorio Ramis', 'Argentina', 'player'),
	('Mohammed Shaker', 'United Arab Emirates', 'player'),
	('Dong Chunyu', 'China PR', 'player'),
	('Christy Pym', 'England', 'player'),
	('Jesper Drost', 'Netherlands', 'player'),
	('Jamie Shackleton', 'England', 'player'),
	('Toby Sibbick', 'England', 'player'),
	('Lewis Stevenson', 'Scotland', 'player'),
	('Choi Bo Kyung', 'Korea Republic', 'player'),
	('Guillaume Dequaire', 'France', 'player'),
	('Maximiliano Calzada', 'Uruguay', 'player'),
	('Yuki Saneto', 'Japan', 'player'),
	('Cheikh Tidiane Sabaly', 'Senegal', 'player'),
	('Andy Polar', 'Peru', 'player'),
	('Enson Rodríguez', 'Venezuela', 'player'),
	('Éric Bocat', 'France', 'player'),
	('Jannik Bandowski', 'Germany', 'player'),
	('Johnny Vidales', 'Peru', 'player'),
	('Jamie Lindsay', 'Scotland', 'player'),
	('Joris Chougrani', 'France', 'player'),
	('Florian David', 'France', 'player'),
	('Aron Elís Þrándarson', 'Iceland', 'player'),
	('De Lucas', 'Spain', 'player'),
	('Moussa Sidibé', 'Mali', 'player'),
	('Pierre Kanstrup', 'Denmark', 'player'),
	('Aaron Hickey', 'Scotland', 'player'),
	('Jan Fortelný', 'Czech Republic', 'player'),
	('George Dobson', 'England', 'player'),
	('Kjartan Finnbogason', 'Iceland', 'player'),
	('Manuel Zeitz', 'Germany', 'player'),
	('Nicolás Avellaneda', 'Argentina', 'player'),
	('Martin Erlić', 'Croatia', 'player'),
	('Kristopher da Graca', 'Sweden', 'player'),
	('Milton Benítez', 'Paraguay', 'player'),
	('Liam Feeney', 'England', 'player'),
	('Luís Rocha', 'Portugal', 'player'),
	('Stephane Acka', 'Ivory Coast', 'player'),
	('Felicio Brown Forbes', 'Costa Rica', 'player'),
	('Marko Janković', 'Montenegro', 'player'),
	('Aiden O''Neill', 'Australia', 'player'),
	('Furkan Soyalp', 'Turkey', 'player'),
	('Dario Van den Buijs', 'Belgium', 'player'),
	('Colby Bishop', 'England', 'player'),
	('Micheal Fabbro', 'Italy', 'player'),
	('Víctor Mendoza', 'Ecuador', 'player'),
	('Aykut Özer', 'Turkey', 'player'),
	('Paul McGinn', 'Scotland', 'player'),
	('Ronaldo Cisneros', 'Mexico', 'player'),
	('Kohei Tezuka', 'Japan', 'player'),
	('Matěj Polidar', 'Czech Republic', 'player'),
	('Juan Espínola', 'Paraguay', 'player'),
	('Dejan Jaković', 'Canada', 'player'),
	('Luca Meisl', 'Austria', 'player'),
	('Emanuel Aiwu', 'Austria', 'player'),
	('Connal Trueman', 'England', 'player'),
	('Taylor Moore', 'England', 'player'),
	('Issam Jebali', 'Tunisia', 'player'),
	('Alexis Gonçalves Pereira', 'France', 'player'),
	('Kristoffer Tokstad', 'Norway', 'player'),
	('Dani Vivian', 'Spain', 'player'),
	('Ersan Gülüm', 'Turkey', 'player'),
	('Daniel De Silva', 'Australia', 'player'),
	('Jeong Tae Wook', 'Korea Republic', 'player'),
	('René Vollath', 'Germany', 'player'),
	('Bryan Mendoza', 'Mexico', 'player'),
	('Abdelhamid El Kaoutari', 'Morocco', 'player'),
	('Erik Zenga', 'Germany', 'player'),
	('Írven Ávila', 'Peru', 'player'),
	('Matt Penney', 'England', 'player'),
	('Håkon Opdal', 'Norway', 'player'),
	('Alexis Rodríguez', 'Argentina', 'player'),
	('Christián Herc', 'Slovakia', 'player'),
	('Nouh Al Mousa', 'Saudi Arabia', 'player'),
	('Kim Seung Joon', 'Korea Republic', 'player'),
	('Leandro Domingues', 'Brazil', 'player'),
	('Cristian Souza', 'Uruguay', 'player'),
	('Ricardo Friedrich', 'Brazil', 'player'),
	('Magnus Christensen', 'Denmark', 'player'),
	('Jordan Thorniley', 'England', 'player'),
	('Andreas Lukse', 'Austria', 'player'),
	('Sergio Camello', 'Spain', 'player'),
	('Ethan Ebanks-Landell', 'England', 'player'),
	('Johan Absalonsen', 'Denmark', 'player'),
	('Zou Dehai', 'China PR', 'player'),
	('Jeppe Arctander Moe', 'Norway', 'player'),
	('Facundo Martínez', 'Argentina', 'player'),
	('Scott Wagstaff', 'England', 'player'),
	('Robin Becker', 'Germany', 'player'),
	('Daan Heymans', 'Belgium', 'player'),
	('Daniel Avramovski', 'North Macedonia', 'player'),
	('Marc Bola', 'England', 'player'),
	('Hiromu Mitsumaru', 'Japan', 'player'),
	('Viktor Agardius', 'Sweden', 'player'),
	('Ricki Lamie', 'Scotland', 'player'),
	('Yuta Someya', 'Japan', 'player'),
	('Aurélien Scheidler', 'France', 'player'),
	('Marcelo Weigandt', 'Argentina', 'player'),
	('Konrad Michalak', 'Poland', 'player'),
	('Alexander Fuchs', 'Germany', 'player'),
	('Michael Bostwick', 'England', 'player'),
	('Ahmed Touba', 'Belgium', 'player'),
	('Ibrahima Conté', 'Guinea', 'player'),
	('Mikkel Kallesøe', 'Denmark', 'player'),
	('Vincent Vermeij', 'Netherlands', 'player'),
	('Răzvan Tincu', 'Romania', 'player'),
	('Cameron Devlin', 'Australia', 'player'),
	('Lukas Scherff', 'Germany', 'player'),
	('James Shea', 'England', 'player'),
	('Zlatko Janjić', 'Bosnia Herzegovina', 'player'),
	('Leonard Zuta', 'North Macedonia', 'player'),
	('Lukas Grgic', 'Austria', 'player'),
	('Dušan Lagator', 'Montenegro', 'player'),
	('Hobie Verhulst', 'Netherlands', 'player'),
	('Shunki Takahashi', 'Japan', 'player'),
	('Aleksander Foosnæs', 'Norway', 'player'),
	('Néstor Moiraghi', 'Argentina', 'player'),
	('Marvin Bartley', 'England', 'player'),
	('Collen Warner', 'United States', 'player'),
	('Alex Gogić', 'Cyprus', 'player'),
	('Erik Marxen', 'Denmark', 'player'),
	('Gustav Berggren', 'Sweden', 'player'),
	('Jon-Helge Tveita', 'Norway', 'player'),
	('Michał Gliwa', 'Poland', 'player'),
	('Ángel Benítez', 'Paraguay', 'player'),
	('Francisco Apaolaza', 'Argentina', 'player'),
	('Niklas Gunnarsson', 'Norway', 'player'),
	('Jason Holt', 'Scotland', 'player'),
	('Benjamin Hansen', 'Denmark', 'player'),
	('Pierre Bardy', 'France', 'player'),
	('Alexandru Țigănașu', 'Romania', 'player'),
	('Jamie Devitt', 'Republic of Ireland', 'player'),
	('Florian Egerer', 'Germany', 'player'),
	('Muguruza', 'Spain', 'player'),
	('Jorrit Smeets', 'Netherlands', 'player'),
	('Jesús Areso', 'Spain', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Masakazu Tashiro', 'Japan', 'tashiro'),
	('Masakazu Tashiro', 'Japan', 'masakazu tashiro'),
	('Harry Pell', 'England', 'harry pell'),
	('Harry Pell', 'England', 'pell'),
	('Danny Mayor', 'England', 'mayor'),
	('Danny Mayor', 'England', 'danny mayor'),
	('Aurélien Tertereau', 'France', 'aurelien tertereau'),
	('Aurélien Tertereau', 'France', 'tertereau'),
	('Sacha Boey', 'France', 'sacha boey'),
	('Sacha Boey', 'France', 'boey'),
	('Kuki Zalazar', 'Spain', 'kuki zalazar'),
	('Kuki Zalazar', 'Spain', 'zalazar'),
	('Eduardo Herrera', 'Mexico', 'eduardo herrera'),
	('Eduardo Herrera', 'Mexico', 'herrera'),
	('Ilyas Chouaref', 'France', 'chouaref'),
	('Ilyas Chouaref', 'France', 'ilyas chouaref'),
	('Ben Williams', 'Wales', 'williams'),
	('Ben Williams', 'Wales', 'ben williams'),
	('Crysan', 'Brazil', 'crysan'),
	('Branislav Niňaj', 'Slovakia', 'ninaj'),
	('Branislav Niňaj', 'Slovakia', 'branislav ninaj'),
	('Nikolas Dyhr', 'Denmark', 'dyhr'),
	('Nikolas Dyhr', 'Denmark', 'nikolas dyhr'),
	('Yanis Hamache', 'France', 'hamache'),
	('Yanis Hamache', 'France', 'yanis hamache'),
	('Horacio Salaberry', 'Uruguay', 'salaberry'),
	('Horacio Salaberry', 'Uruguay', 'horacio salaberry'),
	('Hallur Hansson', 'Faroe Islands', 'hallur hansson'),
	('Hallur Hansson', 'Faroe Islands', 'hansson'),
	('Ebou Adams', 'Gambia', 'ebou adams'),
	('Ebou Adams', 'Gambia', 'adams'),
	('Daiki Sugioka', 'Japan', 'sugioka'),
	('Daiki Sugioka', 'Japan', 'daiki sugioka'),
	('Joel Fernández', 'Bolivia', 'fernandez'),
	('Joel Fernández', 'Bolivia', 'joel fernandez'),
	('Alexander Juel Andersen', 'Denmark', 'alexander juel andersen'),
	('Alexander Juel Andersen', 'Denmark', 'andersen'),
	('Illia Zabarnyi', 'Ukraine', 'zabarnyi'),
	('Illia Zabarnyi', 'Ukraine', 'illia zabarnyi'),
	('Eray Birniçan', 'Turkey', 'birnican'),
	('Eray Birniçan', 'Turkey', 'eray birnican'),
	('Darren Pratley', 'England', 'darren pratley'),
	('Darren Pratley', 'England', 'pratley'),
	('Stian Aasmundsen', 'Norway', 'aasmundsen'),
	('Stian Aasmundsen', 'Norway', 'stian aasmundsen'),
	('Harry Chapman', 'England', 'harry chapman'),
	('Harry Chapman', 'England', 'chapman'),
	('Kaoru Takayama', 'Japan', 'kaoru takayama'),
	('Kaoru Takayama', 'Japan', 'takayama'),
	('Gijs Smal', 'Netherlands', 'smal'),
	('Gijs Smal', 'Netherlands', 'gijs smal'),
	('Troels Kløve', 'Denmark', 'troels klve'),
	('Troels Kløve', 'Denmark', 'klve'),
	('Simon Skrabb', 'Finland', 'skrabb'),
	('Simon Skrabb', 'Finland', 'simon skrabb'),
	('Agustín Doffo', 'Argentina', 'doffo'),
	('Agustín Doffo', 'Argentina', 'agustin doffo'),
	('Sean Long', 'Republic of Ireland', 'long'),
	('Sean Long', 'Republic of Ireland', 'sean long'),
	('Kévin Denkey', 'Togo', 'kevin denkey'),
	('Kévin Denkey', 'Togo', 'denkey'),
	('Marin Aničić', 'Bosnia Herzegovina', 'marin anicic'),
	('Marin Aničić', 'Bosnia Herzegovina', 'anicic'),
	('Iván Bravo', 'Spain', 'ivan bravo'),
	('Iván Bravo', 'Spain', 'bravo'),
	('Konrad Forenc', 'Poland', 'konrad forenc'),
	('Konrad Forenc', 'Poland', 'forenc'),
	('Joaquín Varela', 'Argentina', 'joaquin varela'),
	('Joaquín Varela', 'Argentina', 'varela'),
	('Tim Payne', 'New Zealand', 'tim payne'),
	('Tim Payne', 'New Zealand', 'payne'),
	('Cho Dong Gun', 'Korea Republic', 'cho dong gun'),
	('Cho Dong Gun', 'Korea Republic', 'gun'),
	('Coll Donaldson', 'Scotland', 'donaldson'),
	('Coll Donaldson', 'Scotland', 'coll donaldson'),
	('Ahn Joon Soo', 'Korea Republic', 'ahn joon soo'),
	('Ahn Joon Soo', 'Korea Republic', 'soo'),
	('Sulejman Krpić', 'Bosnia Herzegovina', 'krpic'),
	('Sulejman Krpić', 'Bosnia Herzegovina', 'sulejman krpic'),
	('Iván Ramírez', 'Paraguay', 'ivan ramirez'),
	('Iván Ramírez', 'Paraguay', 'ramirez'),
	('Josh Dacres-Cogley', 'England', 'josh dacrescogley'),
	('Josh Dacres-Cogley', 'England', 'dacrescogley'),
	('Samy Mmaee', 'Belgium', 'mmaee'),
	('Samy Mmaee', 'Belgium', 'samy mmaee'),
	('Bjarke Jacobsen', 'Denmark', 'bjarke jacobsen'),
	('Bjarke Jacobsen', 'Denmark', 'jacobsen'),
	('Kim Nam Chun', 'Korea Republic', 'kim nam chun'),
	('Kim Nam Chun', 'Korea Republic', 'chun'),
	('Tobias Christensen', 'Norway', 'christensen'),
	('Tobias Christensen', 'Norway', 'tobias christensen'),
	('Pol Freixanet', 'Spain', 'pol freixanet'),
	('Pol Freixanet', 'Spain', 'freixanet'),
	('Daniel Bartl', 'Czech Republic', 'daniel bartl'),
	('Daniel Bartl', 'Czech Republic', 'bartl'),
	('Fernand Mayembo', 'Congo', 'fernand mayembo'),
	('Fernand Mayembo', 'Congo', 'mayembo'),
	('Godfried Roemeratoe', 'Netherlands', 'roemeratoe'),
	('Godfried Roemeratoe', 'Netherlands', 'godfried roemeratoe'),
	('Birama Ndoye', 'Senegal', 'ndoye'),
	('Birama Ndoye', 'Senegal', 'birama ndoye'),
	('Okan Kocuk', 'Turkey', 'kocuk'),
	('Okan Kocuk', 'Turkey', 'okan kocuk'),
	('Pascal Breier', 'Germany', 'breier'),
	('Pascal Breier', 'Germany', 'pascal breier'),
	('Sebastian Milewski', 'Poland', 'sebastian milewski'),
	('Sebastian Milewski', 'Poland', 'milewski'),
	('Mansur', 'Brazil', 'mansur'),
	('Juan Aponte', 'Bolivia', 'juan aponte'),
	('Juan Aponte', 'Bolivia', 'aponte'),
	('Vitalie Damascan', 'Moldova', 'damascan'),
	('Vitalie Damascan', 'Moldova', 'vitalie damascan'),
	('Alexander Bittroff', 'Germany', 'bittroff'),
	('Alexander Bittroff', 'Germany', 'alexander bittroff'),
	('Stanley Elbers', 'Netherlands', 'stanley elbers'),
	('Stanley Elbers', 'Netherlands', 'elbers'),
	('Benjamín Vidal', 'Chile', 'vidal'),
	('Benjamín Vidal', 'Chile', 'benjamin vidal'),
	('Koya Yuruki', 'Japan', 'koya yuruki'),
	('Koya Yuruki', 'Japan', 'yuruki'),
	('Joachim Eickmayer', 'France', 'eickmayer'),
	('Joachim Eickmayer', 'France', 'joachim eickmayer'),
	('Akimi Barada', 'Japan', 'barada'),
	('Akimi Barada', 'Japan', 'akimi barada'),
	('Oscar Añez', 'Bolivia', 'anez'),
	('Oscar Añez', 'Bolivia', 'oscar anez'),
	('İbrahim Akdağ', 'Turkey', 'akdag'),
	('İbrahim Akdağ', 'Turkey', 'ibrahim akdag'),
	('Arturo Molina', 'Spain', 'arturo molina'),
	('Arturo Molina', 'Spain', 'molina'),
	('Jeremy Cijntje', 'Curacao', 'jeremy cijntje'),
	('Jeremy Cijntje', 'Curacao', 'cijntje'),
	('Gálvez', 'Spain', 'galvez'),
	('Lukas Gugganig', 'Austria', 'lukas gugganig'),
	('Lukas Gugganig', 'Austria', 'gugganig'),
	('Ahmed Sharahili', 'Saudi Arabia', 'ahmed sharahili'),
	('Ahmed Sharahili', 'Saudi Arabia', 'sharahili'),
	('James Bolton', 'England', 'james bolton'),
	('James Bolton', 'England', 'bolton'),
	('Mustafa Abdellaoue', 'Norway', 'mustafa abdellaoue'),
	('Mustafa Abdellaoue', 'Norway', 'abdellaoue'),
	('Vincent Trummer', 'Austria', 'trummer'),
	('Vincent Trummer', 'Austria', 'vincent trummer'),
	('Bilal Hussein', 'Sweden', 'bilal hussein'),
	('Bilal Hussein', 'Sweden', 'hussein'),
	('Luke Joyce', 'England', 'joyce'),
	('Luke Joyce', 'England', 'luke joyce'),
	('Radosław Cierzniak', 'Poland', 'cierzniak'),
	('Radosław Cierzniak', 'Poland', 'radosaw cierzniak'),
	('Jason Knight', 'Republic of Ireland', 'jason knight'),
	('Jason Knight', 'Republic of Ireland', 'knight'),
	('Ryan McLaughlin', 'Northern Ireland', 'ryan mclaughlin'),
	('Ryan McLaughlin', 'Northern Ireland', 'mclaughlin'),
	('Mohanad Salem', 'United Arab Emirates', 'salem'),
	('Mohanad Salem', 'United Arab Emirates', 'mohanad salem'),
	('Jean Peña', 'Ecuador', 'jean pena'),
	('Jean Peña', 'Ecuador', 'pena'),
	('Benjamin Siegrist', 'Switzerland', 'siegrist'),
	('Benjamin Siegrist', 'Switzerland', 'benjamin siegrist'),
	('Lukas Grozurek', 'Austria', 'grozurek'),
	('Lukas Grozurek', 'Austria', 'lukas grozurek'),
	('Brandon Haunstrup', 'England', 'haunstrup'),
	('Brandon Haunstrup', 'England', 'brandon haunstrup'),
	('Diego Montiel', 'Sweden', 'montiel'),
	('Diego Montiel', 'Sweden', 'diego montiel'),
	('Ariajasuru Hasegawa', 'Japan', 'ariajasuru hasegawa'),
	('Ariajasuru Hasegawa', 'Japan', 'hasegawa'),
	('Jordi Cortizo', 'Mexico', 'jordi cortizo'),
	('Jordi Cortizo', 'Mexico', 'cortizo'),
	('Sebastián Méndez', 'Ecuador', 'mendez'),
	('Sebastián Méndez', 'Ecuador', 'sebastian mendez'),
	('George Davies', 'Sierra Leone', 'george davies'),
	('George Davies', 'Sierra Leone', 'davies'),
	('Tomislav Kiš', 'Croatia', 'kis'),
	('Tomislav Kiš', 'Croatia', 'tomislav kis'),
	('Han Seung Gyu', 'Korea Republic', 'gyu'),
	('Han Seung Gyu', 'Korea Republic', 'han seung gyu'),
	('Jason Cummings', 'Scotland', 'jason cummings'),
	('Jason Cummings', 'Scotland', 'cummings'),
	('Nicolò Armini', 'Italy', 'armini'),
	('Nicolò Armini', 'Italy', 'nicolo armini'),
	('Philipp Netzer', 'Austria', 'netzer'),
	('Philipp Netzer', 'Austria', 'philipp netzer'),
	('Simon Skarlatidis', 'Germany', 'skarlatidis'),
	('Simon Skarlatidis', 'Germany', 'simon skarlatidis'),
	('Nicke Kabamba', 'England', 'nicke kabamba'),
	('Nicke Kabamba', 'England', 'kabamba'),
	('Daouda Peeters', 'Belgium', 'peeters'),
	('Daouda Peeters', 'Belgium', 'daouda peeters'),
	('Dominik Wydra', 'Austria', 'wydra'),
	('Dominik Wydra', 'Austria', 'dominik wydra'),
	('Oliver Valaker Edvardsen', 'Norway', 'edvardsen'),
	('Oliver Valaker Edvardsen', 'Norway', 'oliver valaker edvardsen'),
	('Maureen Franco', 'Uruguay', 'maureen franco'),
	('Maureen Franco', 'Uruguay', 'franco'),
	('Aynsley Pears', 'England', 'aynsley pears'),
	('Aynsley Pears', 'England', 'pears'),
	('István Fülöp', 'Romania', 'fulop'),
	('István Fülöp', 'Romania', 'istvan fulop'),
	('Sven Sonnenberg', 'Germany', 'sonnenberg'),
	('Sven Sonnenberg', 'Germany', 'sven sonnenberg'),
	('Fotis Ioannidis', 'Greece', 'ioannidis'),
	('Fotis Ioannidis', 'Greece', 'fotis ioannidis'),
	('Guilherme Mantuan', 'Brazil', 'mantuan'),
	('Guilherme Mantuan', 'Brazil', 'guilherme mantuan'),
	('Thomas Eisfeld', 'Germany', 'eisfeld'),
	('Thomas Eisfeld', 'Germany', 'thomas eisfeld'),
	('Wilder Cartagena', 'Peru', 'cartagena'),
	('Wilder Cartagena', 'Peru', 'wilder cartagena'),
	('Javier Parraguez', 'Chile', 'parraguez'),
	('Javier Parraguez', 'Chile', 'javier parraguez'),
	('Cho Jae Wan', 'Korea Republic', 'cho jae wan'),
	('Cho Jae Wan', 'Korea Republic', 'wan'),
	('Yoshiki Matsushita', 'Japan', 'yoshiki matsushita'),
	('Yoshiki Matsushita', 'Japan', 'matsushita'),
	('Alec Deneumostier', 'Peru', 'deneumostier'),
	('Alec Deneumostier', 'Peru', 'alec deneumostier'),
	('Richie Towell', 'Republic of Ireland', 'richie towell'),
	('Richie Towell', 'Republic of Ireland', 'towell'),
	('Yusuf Demir', 'Austria', 'demir'),
	('Yusuf Demir', 'Austria', 'yusuf demir'),
	('Marvin Martin', 'France', 'marvin martin'),
	('Marvin Martin', 'France', 'martin'),
	('Min Sang Gi', 'Korea Republic', 'gi'),
	('Min Sang Gi', 'Korea Republic', 'min sang gi'),
	('Billy Jones', 'England', 'jones'),
	('Billy Jones', 'England', 'billy jones'),
	('Victorio Ramis', 'Argentina', 'ramis'),
	('Victorio Ramis', 'Argentina', 'victorio ramis'),
	('Mohammed Shaker', 'United Arab Emirates', 'mohammed shaker'),
	('Mohammed Shaker', 'United Arab Emirates', 'shaker'),
	('Dong Chunyu', 'China PR', 'dong chunyu'),
	('Dong Chunyu', 'China PR', 'chunyu'),
	('Christy Pym', 'England', 'pym'),
	('Christy Pym', 'England', 'christy pym'),
	('Jesper Drost', 'Netherlands', 'jesper drost'),
	('Jesper Drost', 'Netherlands', 'drost'),
	('Jamie Shackleton', 'England', 'jamie shackleton'),
	('Jamie Shackleton', 'England', 'shackleton'),
	('Toby Sibbick', 'England', 'toby sibbick'),
	('Toby Sibbick', 'England', 'sibbick'),
	('Lewis Stevenson', 'Scotland', 'stevenson'),
	('Lewis Stevenson', 'Scotland', 'lewis stevenson'),
	('Choi Bo Kyung', 'Korea Republic', 'kyung'),
	('Choi Bo Kyung', 'Korea Republic', 'choi bo kyung'),
	('Guillaume Dequaire', 'France', 'guillaume dequaire'),
	('Guillaume Dequaire', 'France', 'dequaire'),
	('Maximiliano Calzada', 'Uruguay', 'maximiliano calzada'),
	('Maximiliano Calzada', 'Uruguay', 'calzada'),
	('Yuki Saneto', 'Japan', 'saneto'),
	('Yuki Saneto', 'Japan', 'yuki saneto'),
	('Cheikh Tidiane Sabaly', 'Senegal', 'sabaly'),
	('Cheikh Tidiane Sabaly', 'Senegal', 'cheikh tidiane sabaly'),
	('Andy Polar', 'Peru', 'polar'),
	('Andy Polar', 'Peru', 'andy polar'),
	('Enson Rodríguez', 'Venezuela', 'enson rodriguez'),
	('Enson Rodríguez', 'Venezuela', 'rodriguez'),
	('Éric Bocat', 'France', 'eric bocat'),
	('Éric Bocat', 'France', 'bocat'),
	('Jannik Bandowski', 'Germany', 'jannik bandowski'),
	('Jannik Bandowski', 'Germany', 'bandowski'),
	('Johnny Vidales', 'Peru', 'vidales'),
	('Johnny Vidales', 'Peru', 'johnny vidales'),
	('Jamie Lindsay', 'Scotland', 'lindsay'),
	('Jamie Lindsay', 'Scotland', 'jamie lindsay'),
	('Joris Chougrani', 'France', 'joris chougrani'),
	('Joris Chougrani', 'France', 'chougrani'),
	('Florian David', 'France', 'florian david'),
	('Florian David', 'France', 'david'),
	('Aron Elís Þrándarson', 'Iceland', 'randarson'),
	('Aron Elís Þrándarson', 'Iceland', 'aron elis randarson'),
	('De Lucas', 'Spain', 'lucas'),
	('De Lucas', 'Spain', 'de lucas'),
	('Moussa Sidibé', 'Mali', 'moussa sidibe'),
	('Moussa Sidibé', 'Mali', 'sidibe'),
	('Pierre Kanstrup', 'Denmark', 'pierre kanstrup'),
	('Pierre Kanstrup', 'Denmark', 'kanstrup'),
	('Aaron Hickey', 'Scotland', 'aaron hickey'),
	('Aaron Hickey', 'Scotland', 'hickey'),
	('Jan Fortelný', 'Czech Republic', 'fortelny'),
	('Jan Fortelný', 'Czech Republic', 'jan fortelny'),
	('George Dobson', 'England', 'dobson'),
	('George Dobson', 'England', 'george dobson'),
	('Kjartan Finnbogason', 'Iceland', 'finnbogason'),
	('Kjartan Finnbogason', 'Iceland', 'kjartan finnbogason'),
	('Manuel Zeitz', 'Germany', 'zeitz'),
	('Manuel Zeitz', 'Germany', 'manuel zeitz'),
	('Nicolás Avellaneda', 'Argentina', 'nicolas avellaneda'),
	('Nicolás Avellaneda', 'Argentina', 'avellaneda'),
	('Martin Erlić', 'Croatia', 'erlic'),
	('Martin Erlić', 'Croatia', 'martin erlic'),
	('Kristopher da Graca', 'Sweden', 'graca'),
	('Kristopher da Graca', 'Sweden', 'kristopher da graca'),
	('Milton Benítez', 'Paraguay', 'milton benitez'),
	('Milton Benítez', 'Paraguay', 'benitez'),
	('Liam Feeney', 'England', 'feeney'),
	('Liam Feeney', 'England', 'liam feeney'),
	('Luís Rocha', 'Portugal', 'luis rocha'),
	('Luís Rocha', 'Portugal', 'rocha'),
	('Stephane Acka', 'Ivory Coast', 'stephane acka'),
	('Stephane Acka', 'Ivory Coast', 'acka'),
	('Felicio Brown Forbes', 'Costa Rica', 'forbes'),
	('Felicio Brown Forbes', 'Costa Rica', 'felicio brown forbes'),
	('Marko Janković', 'Montenegro', 'marko jankovic'),
	('Marko Janković', 'Montenegro', 'jankovic'),
	('Aiden O''Neill', 'Australia', 'aiden oneill'),
	('Aiden O''Neill', 'Australia', 'oneill'),
	('Furkan Soyalp', 'Turkey', 'furkan soyalp'),
	('Furkan Soyalp', 'Turkey', 'soyalp'),
	('Dario Van den Buijs', 'Belgium', 'buijs'),
	('Dario Van den Buijs', 'Belgium', 'dario van den buijs'),
	('Colby Bishop', 'England', 'colby bishop'),
	('Colby Bishop', 'England', 'bishop'),
	('Micheal Fabbro', 'Italy', 'fabbro'),
	('Micheal Fabbro', 'Italy', 'micheal fabbro'),
	('Víctor Mendoza', 'Ecuador', 'mendoza'),
	('Víctor Mendoza', 'Ecuador', 'victor mendoza'),
	('Aykut Özer', 'Turkey', 'ozer'),
	('Aykut Özer', 'Turkey', 'aykut ozer'),
	('Paul McGinn', 'Scotland', 'paul mcginn'),
	('Paul McGinn', 'Scotland', 'mcginn'),
	('Ronaldo Cisneros', 'Mexico', 'cisneros'),
	('Ronaldo Cisneros', 'Mexico', 'ronaldo cisneros'),
	('Kohei Tezuka', 'Japan', 'tezuka'),
	('Kohei Tezuka', 'Japan', 'kohei tezuka'),
	('Matěj Polidar', 'Czech Republic', 'matej polidar'),
	('Matěj Polidar', 'Czech Republic', 'polidar'),
	('Juan Espínola', 'Paraguay', 'juan espinola'),
	('Juan Espínola', 'Paraguay', 'espinola'),
	('Dejan Jaković', 'Canada', 'jakovic'),
	('Dejan Jaković', 'Canada', 'dejan jakovic'),
	('Luca Meisl', 'Austria', 'luca meisl'),
	('Luca Meisl', 'Austria', 'meisl'),
	('Emanuel Aiwu', 'Austria', 'emanuel aiwu'),
	('Emanuel Aiwu', 'Austria', 'aiwu'),
	('Connal Trueman', 'England', 'connal trueman'),
	('Connal Trueman', 'England', 'trueman'),
	('Taylor Moore', 'England', 'taylor moore'),
	('Taylor Moore', 'England', 'moore'),
	('Issam Jebali', 'Tunisia', 'issam jebali'),
	('Issam Jebali', 'Tunisia', 'jebali'),
	('Alexis Gonçalves Pereira', 'France', 'pereira'),
	('Alexis Gonçalves Pereira', 'France', 'alexis goncalves pereira'),
	('Kristoffer Tokstad', 'Norway', 'tokstad'),
	('Kristoffer Tokstad', 'Norway', 'kristoffer tokstad'),
	('Dani Vivian', 'Spain', 'vivian'),
	('Dani Vivian', 'Spain', 'dani vivian'),
	('Ersan Gülüm', 'Turkey', 'ersan gulum'),
	('Ersan Gülüm', 'Turkey', 'gulum'),
	('Daniel De Silva', 'Australia', 'silva'),
	('Daniel De Silva', 'Australia', 'daniel de silva'),
	('Jeong Tae Wook', 'Korea Republic', 'jeong tae wook'),
	('Jeong Tae Wook', 'Korea Republic', 'wook'),
	('René Vollath', 'Germany', 'rene vollath'),
	('René Vollath', 'Germany', 'vollath'),
	('Bryan Mendoza', 'Mexico', 'mendoza'),
	('Bryan Mendoza', 'Mexico', 'bryan mendoza'),
	('Abdelhamid El Kaoutari', 'Morocco', 'abdelhamid el kaoutari'),
	('Abdelhamid El Kaoutari', 'Morocco', 'kaoutari'),
	('Erik Zenga', 'Germany', 'erik zenga'),
	('Erik Zenga', 'Germany', 'zenga'),
	('Írven Ávila', 'Peru', 'irven avila'),
	('Írven Ávila', 'Peru', 'avila'),
	('Matt Penney', 'England', 'penney'),
	('Matt Penney', 'England', 'matt penney'),
	('Håkon Opdal', 'Norway', 'opdal'),
	('Håkon Opdal', 'Norway', 'hakon opdal'),
	('Alexis Rodríguez', 'Argentina', 'rodriguez'),
	('Alexis Rodríguez', 'Argentina', 'alexis rodriguez'),
	('Christián Herc', 'Slovakia', 'herc'),
	('Christián Herc', 'Slovakia', 'christian herc'),
	('Nouh Al Mousa', 'Saudi Arabia', 'mousa'),
	('Nouh Al Mousa', 'Saudi Arabia', 'nouh al mousa'),
	('Kim Seung Joon', 'Korea Republic', 'joon'),
	('Kim Seung Joon', 'Korea Republic', 'kim seung joon'),
	('Leandro Domingues', 'Brazil', 'domingues'),
	('Leandro Domingues', 'Brazil', 'leandro domingues'),
	('Cristian Souza', 'Uruguay', 'souza'),
	('Cristian Souza', 'Uruguay', 'cristian souza'),
	('Ricardo Friedrich', 'Brazil', 'ricardo friedrich'),
	('Ricardo Friedrich', 'Brazil', 'friedrich'),
	('Magnus Christensen', 'Denmark', 'christensen'),
	('Magnus Christensen', 'Denmark', 'magnus christensen'),
	('Jordan Thorniley', 'England', 'thorniley'),
	('Jordan Thorniley', 'England', 'jordan thorniley'),
	('Andreas Lukse', 'Austria', 'lukse'),
	('Andreas Lukse', 'Austria', 'andreas lukse'),
	('Sergio Camello', 'Spain', 'camello'),
	('Sergio Camello', 'Spain', 'sergio camello'),
	('Ethan Ebanks-Landell', 'England', 'ethan ebankslandell'),
	('Ethan Ebanks-Landell', 'England', 'ebankslandell'),
	('Johan Absalonsen', 'Denmark', 'johan absalonsen'),
	('Johan Absalonsen', 'Denmark', 'absalonsen'),
	('Zou Dehai', 'China PR', 'zou dehai'),
	('Zou Dehai', 'China PR', 'dehai'),
	('Jeppe Arctander Moe', 'Norway', 'jeppe arctander moe'),
	('Jeppe Arctander Moe', 'Norway', 'moe'),
	('Facundo Martínez', 'Argentina', 'martinez'),
	('Facundo Martínez', 'Argentina', 'facundo martinez'),
	('Scott Wagstaff', 'England', 'scott wagstaff'),
	('Scott Wagstaff', 'England', 'wagstaff'),
	('Robin Becker', 'Germany', 'becker'),
	('Robin Becker', 'Germany', 'robin becker'),
	('Daan Heymans', 'Belgium', 'daan heymans'),
	('Daan Heymans', 'Belgium', 'heymans'),
	('Daniel Avramovski', 'North Macedonia', 'daniel avramovski'),
	('Daniel Avramovski', 'North Macedonia', 'avramovski'),
	('Marc Bola', 'England', 'marc bola'),
	('Marc Bola', 'England', 'bola'),
	('Hiromu Mitsumaru', 'Japan', 'mitsumaru'),
	('Hiromu Mitsumaru', 'Japan', 'hiromu mitsumaru'),
	('Viktor Agardius', 'Sweden', 'viktor agardius'),
	('Viktor Agardius', 'Sweden', 'agardius'),
	('Ricki Lamie', 'Scotland', 'lamie'),
	('Ricki Lamie', 'Scotland', 'ricki lamie'),
	('Yuta Someya', 'Japan', 'yuta someya'),
	('Yuta Someya', 'Japan', 'someya'),
	('Aurélien Scheidler', 'France', 'scheidler'),
	('Aurélien Scheidler', 'France', 'aurelien scheidler'),
	('Marcelo Weigandt', 'Argentina', 'marcelo weigandt'),
	('Marcelo Weigandt', 'Argentina', 'weigandt'),
	('Konrad Michalak', 'Poland', 'michalak'),
	('Konrad Michalak', 'Poland', 'konrad michalak'),
	('Alexander Fuchs', 'Germany', 'alexander fuchs'),
	('Alexander Fuchs', 'Germany', 'fuchs'),
	('Michael Bostwick', 'England', 'bostwick'),
	('Michael Bostwick', 'England', 'michael bostwick'),
	('Ahmed Touba', 'Belgium', 'touba'),
	('Ahmed Touba', 'Belgium', 'ahmed touba'),
	('Ibrahima Conté', 'Guinea', 'ibrahima conte'),
	('Ibrahima Conté', 'Guinea', 'conte'),
	('Mikkel Kallesøe', 'Denmark', 'kallese'),
	('Mikkel Kallesøe', 'Denmark', 'mikkel kallese'),
	('Vincent Vermeij', 'Netherlands', 'vermeij'),
	('Vincent Vermeij', 'Netherlands', 'vincent vermeij'),
	('Răzvan Tincu', 'Romania', 'tincu'),
	('Răzvan Tincu', 'Romania', 'razvan tincu'),
	('Cameron Devlin', 'Australia', 'cameron devlin'),
	('Cameron Devlin', 'Australia', 'devlin'),
	('Lukas Scherff', 'Germany', 'lukas scherff'),
	('Lukas Scherff', 'Germany', 'scherff'),
	('James Shea', 'England', 'james shea'),
	('James Shea', 'England', 'shea'),
	('Zlatko Janjić', 'Bosnia Herzegovina', 'janjic'),
	('Zlatko Janjić', 'Bosnia Herzegovina', 'zlatko janjic'),
	('Leonard Zuta', 'North Macedonia', 'zuta'),
	('Leonard Zuta', 'North Macedonia', 'leonard zuta'),
	('Lukas Grgic', 'Austria', 'grgic'),
	('Lukas Grgic', 'Austria', 'lukas grgic'),
	('Dušan Lagator', 'Montenegro', 'lagator'),
	('Dušan Lagator', 'Montenegro', 'dusan lagator'),
	('Hobie Verhulst', 'Netherlands', 'hobie verhulst'),
	('Hobie Verhulst', 'Netherlands', 'verhulst'),
	('Shunki Takahashi', 'Japan', 'shunki takahashi'),
	('Shunki Takahashi', 'Japan', 'takahashi'),
	('Aleksander Foosnæs', 'Norway', 'foosns'),
	('Aleksander Foosnæs', 'Norway', 'aleksander foosns'),
	('Néstor Moiraghi', 'Argentina', 'moiraghi'),
	('Néstor Moiraghi', 'Argentina', 'nestor moiraghi'),
	('Marvin Bartley', 'England', 'marvin bartley'),
	('Marvin Bartley', 'England', 'bartley'),
	('Collen Warner', 'United States', 'collen warner'),
	('Collen Warner', 'United States', 'warner'),
	('Alex Gogić', 'Cyprus', 'gogic'),
	('Alex Gogić', 'Cyprus', 'alex gogic'),
	('Erik Marxen', 'Denmark', 'erik marxen'),
	('Erik Marxen', 'Denmark', 'marxen'),
	('Gustav Berggren', 'Sweden', 'berggren'),
	('Gustav Berggren', 'Sweden', 'gustav berggren'),
	('Jon-Helge Tveita', 'Norway', 'tveita'),
	('Jon-Helge Tveita', 'Norway', 'jonhelge tveita'),
	('Michał Gliwa', 'Poland', 'gliwa'),
	('Michał Gliwa', 'Poland', 'micha gliwa'),
	('Ángel Benítez', 'Paraguay', 'angel benitez'),
	('Ángel Benítez', 'Paraguay', 'benitez'),
	('Francisco Apaolaza', 'Argentina', 'apaolaza'),
	('Francisco Apaolaza', 'Argentina', 'francisco apaolaza'),
	('Niklas Gunnarsson', 'Norway', 'gunnarsson'),
	('Niklas Gunnarsson', 'Norway', 'niklas gunnarsson'),
	('Jason Holt', 'Scotland', 'jason holt'),
	('Jason Holt', 'Scotland', 'holt'),
	('Benjamin Hansen', 'Denmark', 'benjamin hansen'),
	('Benjamin Hansen', 'Denmark', 'hansen'),
	('Pierre Bardy', 'France', 'bardy'),
	('Pierre Bardy', 'France', 'pierre bardy'),
	('Alexandru Țigănașu', 'Romania', 'tiganasu'),
	('Alexandru Țigănașu', 'Romania', 'alexandru tiganasu'),
	('Jamie Devitt', 'Republic of Ireland', 'devitt'),
	('Jamie Devitt', 'Republic of Ireland', 'jamie devitt'),
	('Florian Egerer', 'Germany', 'egerer'),
	('Florian Egerer', 'Germany', 'florian egerer'),
	('Muguruza', 'Spain', 'muguruza'),
	('Jorrit Smeets', 'Netherlands', 'smeets'),
	('Jorrit Smeets', 'Netherlands', 'jorrit smeets'),
	('Jesús Areso', 'Spain', 'areso'),
	('Jesús Areso', 'Spain', 'jesus areso')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';