INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Tom Pietermaat', 'Belgium', 'player'),
	('Mirnes Pepić', 'Montenegro', 'player'),
	('Ryan Johnson Laursen', 'Denmark', 'player'),
	('Nordin Jackers', 'Belgium', 'player'),
	('Emanuel Schreiner', 'Austria', 'player'),
	('Stevie Mallan', 'Scotland', 'player'),
	('Esquerdo', 'Spain', 'player'),
	('Stefan Kutschke', 'Germany', 'player'),
	('Fran Vélez', 'Spain', 'player'),
	('David Niepsuj', 'Poland', 'player'),
	('Damian Rasak', 'Poland', 'player'),
	('Romário Baldé', 'Guinea Bissau', 'player'),
	('Samuel Shashoua', 'England', 'player'),
	('Samuel Lino', 'Brazil', 'player'),
	('Chris Ramos', 'Spain', 'player'),
	('Ben Wilmot', 'England', 'player'),
	('Ramiro Guerra', 'Uruguay', 'player'),
	('Iván Colman', 'Argentina', 'player'),
	('Nicklas Helenius', 'Denmark', 'player'),
	('Antoine Colassin', 'Belgium', 'player'),
	('Dries Wuytens', 'Belgium', 'player'),
	('Zhang Chi', 'China PR', 'player'),
	('Jason Naismith', 'Scotland', 'player'),
	('Piotr Celeban', 'Poland', 'player'),
	('Sam Surridge', 'England', 'player'),
	('Brad Knighton', 'United States', 'player'),
	('José Suárez', 'Spain', 'player'),
	('Melker Hallberg', 'Sweden', 'player'),
	('Williams Riveros', 'Paraguay', 'player'),
	('Aly Abeid', 'Mauritania', 'player'),
	('Radoslav Dimitrov', 'Bulgaria', 'player'),
	('Ivan Goranov', 'Bulgaria', 'player'),
	('Michał Mak', 'Poland', 'player'),
	('Sascha Mockenhaupt', 'Germany', 'player'),
	('Maximiliano Perg', 'Uruguay', 'player'),
	('Yassin Ben Balla', 'France', 'player'),
	('David Murillo', 'Colombia', 'player'),
	('David Wheeler', 'England', 'player'),
	('Obinna Nwobodo', 'Nigeria', 'player'),
	('Gjermund Åsen', 'Norway', 'player'),
	('Stefan Stangl', 'Austria', 'player'),
	('Thomas Bruns', 'Netherlands', 'player'),
	('Jak Alnwick', 'England', 'player'),
	('Jérémy Perbet', 'France', 'player'),
	('Simone Edera', 'Italy', 'player'),
	('Cole Skuse', 'England', 'player'),
	('Vito Hammershøy-Mistrati', 'Denmark', 'player'),
	('Han-Noah Massengo', 'France', 'player'),
	('Yevgen Cheberko', 'Ukraine', 'player'),
	('Marcus Antonsson', 'Sweden', 'player'),
	('Yusuke Chajima', 'Japan', 'player'),
	('Emmanuel Ntim', 'Ghana', 'player'),
	('Marc Heider', 'Germany', 'player'),
	('Babacar Niasse', 'Senegal', 'player'),
	('Jugurtha Hamroun', 'Algeria', 'player'),
	('Mirko Boland', 'Germany', 'player'),
	('Tiago Tomás', 'Portugal', 'player'),
	('Simon Piesinger', 'Austria', 'player'),
	('Harrison Delbridge', 'Australia', 'player'),
	('Alexander Farnerud', 'Sweden', 'player'),
	('Willer Ditta', 'Colombia', 'player'),
	('Kenny Prince Redondo', 'Germany', 'player'),
	('Iñaki Sáenz', 'Spain', 'player'),
	('Andrea Danzi', 'Italy', 'player'),
	('Woo Ju Sung', 'Korea Republic', 'player'),
	('Francisco Feuillassier', 'Argentina', 'player'),
	('Bartosz Białek', 'Poland', 'player'),
	('Abdulaziz Al Jebreen', 'Saudi Arabia', 'player'),
	('Brendan Chardonnet', 'France', 'player'),
	('Mark Travers', 'Republic of Ireland', 'player'),
	('Eoin Doyle', 'Republic of Ireland', 'player'),
	('Teenage Hadebe', 'Zimbabwe', 'player'),
	('Jeremy Ngakia', 'England', 'player'),
	('Simon Eastwood', 'England', 'player'),
	('José Valencia', 'Colombia', 'player'),
	('Andrés Flores', 'El Salvador', 'player'),
	('Borys Tashchy', 'Ukraine', 'player'),
	('Hamidou Keyta', 'France', 'player'),
	('Fidel Escobar', 'Panama', 'player'),
	('Shin Kwang Hoon', 'Korea Republic', 'player'),
	('Guillaume Bosca', 'France', 'player'),
	('Rilwan Hassan', 'Nigeria', 'player'),
	('Pablo Sisniega', 'Mexico', 'player'),
	('Kazushi Mitsuhira', 'Japan', 'player'),
	('Cristo Romero', 'Spain', 'player'),
	('Choi Sung Geun', 'Korea Republic', 'player'),
	('Đorđe Crnomarković', 'Serbia', 'player'),
	('Murat Yıldırım', 'Turkey', 'player'),
	('Marco Kana', 'Belgium', 'player'),
	('Boubacar Barry', 'Germany', 'player'),
	('Sikou Niakaté', 'France', 'player'),
	('Alberto Acosta', 'Mexico', 'player'),
	('Richard Windbichler', 'Austria', 'player'),
	('Terrence Boyd', 'United States', 'player'),
	('Fawaz Al Qarni', 'Saudi Arabia', 'player'),
	('Jan Zwischenbrugger', 'Austria', 'player'),
	('David Milinković', 'France', 'player'),
	('César Carrillo', 'Colombia', 'player'),
	('Jhojan Julio', 'Ecuador', 'player'),
	('Danilo Carando', 'Argentina', 'player'),
	('Robert Taylor', 'Finland', 'player'),
	('Guan Zhen', 'China PR', 'player'),
	('Killian Sardella', 'Belgium', 'player'),
	('Nicolás Acevedo', 'Uruguay', 'player'),
	('Awadh Khamis', 'Saudi Arabia', 'player'),
	('Dante Rigo', 'Belgium', 'player'),
	('Jarosław Jach', 'Poland', 'player'),
	('Daniel Høegh', 'Denmark', 'player'),
	('Rafał Boguski', 'Poland', 'player'),
	('Pablo Lavandeira', 'Peru', 'player'),
	('Maksym Koval', 'Ukraine', 'player'),
	('David Gil', 'Spain', 'player'),
	('Boniek García', 'Honduras', 'player'),
	('Arbnor Mucolli', 'Albania', 'player'),
	('Wouter Biebauw', 'Belgium', 'player'),
	('Connor Wood', 'England', 'player'),
	('André Luís', 'Brazil', 'player'),
	('Cristian Vega', 'Argentina', 'player'),
	('Santiago Amorín', 'Uruguay', 'player'),
	('Anders K. Jacobsen', 'Denmark', 'player'),
	('Mikael Anderson', 'Iceland', 'player'),
	('Martín Payero', 'Argentina', 'player'),
	('Zheng Long', 'China PR', 'player'),
	('Janio Bikel', 'Portugal', 'player'),
	('Rafael Romo', 'Venezuela', 'player'),
	('Gabriel Enache', 'Romania', 'player'),
	('Jonathan Augustinsson', 'Sweden', 'player'),
	('Carlos Gutiérrez', 'Mexico', 'player'),
	('Sebastiano Esposito', 'Italy', 'player'),
	('Tom Pearce', 'England', 'player'),
	('Goduine Koyalipou', 'France', 'player'),
	('Richard Wood', 'England', 'player'),
	('Thomas Grøgaard', 'Norway', 'player'),
	('Wouter Burger', 'Netherlands', 'player'),
	('Mattia Montini', 'Italy', 'player'),
	('Jakub Piotrowski', 'Poland', 'player'),
	('Gwon Wan Gyu', 'Korea Republic', 'player'),
	('Jeong Dong Ho', 'Korea Republic', 'player'),
	('Harold Gómez', 'Colombia', 'player'),
	('Behrang Safari', 'Sweden', 'player'),
	('Simon Makienok', 'Denmark', 'player'),
	('Wang Yongpo', 'China PR', 'player'),
	('Carlos Luna', 'Argentina', 'player'),
	('Jordy Alcívar', 'Ecuador', 'player'),
	('Jhonathan Candia', 'Uruguay', 'player'),
	('Cenk Alkılıç', 'Turkey', 'player'),
	('Kensuke Sato', 'Japan', 'player'),
	('Babacar Gueye', 'Senegal', 'player'),
	('Shaun Whalley', 'England', 'player'),
	('Marius Kleinsorge', 'Germany', 'player'),
	('Aurélien Collin', 'France', 'player'),
	('Carlos Augusto', 'Brazil', 'player'),
	('Jake Carroll', 'Republic of Ireland', 'player'),
	('Ryan Wintle', 'England', 'player'),
	('Mustafa Amini', 'Australia', 'player'),
	('Yuta Koide', 'Japan', 'player'),
	('Louie Sibley', 'England', 'player'),
	('José Rivas', 'Venezuela', 'player'),
	('Daniel Hägele', 'Germany', 'player'),
	('Benjamin Girth', 'Germany', 'player'),
	('Doğan Erdoğan', 'Turkey', 'player'),
	('David Martin', 'England', 'player'),
	('Gu Cao', 'China PR', 'player'),
	('Sefa Yılmaz', 'Turkey', 'player'),
	('Michael Covea', 'Venezuela', 'player'),
	('Lukas Königshofer', 'Austria', 'player'),
	('Shea Salinas', 'United States', 'player'),
	('Mossa', 'Spain', 'player'),
	('Jeremias Lorch', 'Germany', 'player'),
	('Rodrigo Abascal', 'Uruguay', 'player'),
	('Kane Vincent-Young', 'England', 'player'),
	('Dan Potts', 'England', 'player'),
	('Lalaïna Nomenjanahary', 'Madagascar', 'player'),
	('Dominic Hyam', 'Scotland', 'player'),
	('Chiedozie Ogbene', 'Nigeria', 'player'),
	('Tomasz Makowski', 'Poland', 'player'),
	('Carlo Sickinger', 'Germany', 'player'),
	('Martin Kobras', 'Austria', 'player'),
	('Darwin Cuero', 'Ecuador', 'player'),
	('Jean-Pierre Rhyner', 'Switzerland', 'player'),
	('Abass Issah', 'Ghana', 'player'),
	('Chris Durkin', 'United States', 'player'),
	('Marcos Caicedo', 'Ecuador', 'player'),
	('Vlad Achim', 'Romania', 'player'),
	('Finn Porath', 'Germany', 'player'),
	('Nahuel Estévez', 'Argentina', 'player'),
	('Thomas Buitink', 'Netherlands', 'player'),
	('Bryan Cabezas', 'Ecuador', 'player'),
	('Carlos Hernández', 'Spain', 'player'),
	('Adrián Arregui', 'Argentina', 'player'),
	('Carlos Caraza', 'Peru', 'player'),
	('Marco Komenda', 'Germany', 'player'),
	('Cosmin Matei', 'Romania', 'player'),
	('Joel Amoroso', 'Argentina', 'player'),
	('Diego Alende', 'Spain', 'player'),
	('Maxence Lacroix', 'France', 'player'),
	('Kouadio Manu Koné', 'France', 'player'),
	('Yusuke Matsuo', 'Japan', 'player'),
	('Junior Adamu', 'Austria', 'player'),
	('Ash Taylor', 'Wales', 'player'),
	('Kofi Schulz', 'Germany', 'player'),
	('Patric Klandt', 'Germany', 'player'),
	('Tomás Andrade', 'Argentina', 'player'),
	('Richard Smallwood', 'England', 'player'),
	('Chima Akas', 'Nigeria', 'player'),
	('Marko Poletanović', 'Serbia', 'player'),
	('Luciano Ospina', 'Colombia', 'player'),
	('Adi Nalić', 'Sweden', 'player'),
	('Joel Asoro', 'Sweden', 'player'),
	('Héber Pena', 'Spain', 'player'),
	('Elliot', 'Spain', 'player'),
	('Aaron Herrera', 'United States', 'player'),
	('Bonke Innocent', 'Nigeria', 'player'),
	('John-Patrick Strauß', 'Philippines', 'player'),
	('Alexandru Albu', 'Romania', 'player'),
	('Drey Wright', 'England', 'player'),
	('Ismaël Chester Diallo', 'Ivory Coast', 'player'),
	('Jordan Williams', 'England', 'player'),
	('Mihai Căpățînă', 'Romania', 'player'),
	('Saad Agouzoul', 'Morocco', 'player'),
	('Brandon Soppy', 'France', 'player'),
	('Edgar Hernández', 'Spain', 'player'),
	('Eirik Ulland Andersen', 'Norway', 'player'),
	('Herolind Shala', 'Kosovo', 'player'),
	('Pierre Cornud', 'France', 'player'),
	('Clinton Mola', 'England', 'player'),
	('Federico Palacios Martínez', 'Spain', 'player'),
	('Jefferson Gómez', 'Colombia', 'player'),
	('Lukas Daschner', 'Germany', 'player'),
	('Sylla Sow', 'Netherlands', 'player'),
	('Ibrahim Chenihi', 'Algeria', 'player'),
	('Christian Cruz', 'Ecuador', 'player'),
	('Bakary Nimaga', 'Mali', 'player'),
	('Steffen Puttkammer', 'Germany', 'player'),
	('Juan Familia-Castillo', 'Netherlands', 'player'),
	('Michiel Jonckheere', 'Belgium', 'player'),
	('Jann-Fiete Arp', 'Germany', 'player'),
	('Alhaji Kamara', 'Sierra Leone', 'player'),
	('Alex Bass', 'England', 'player'),
	('Viti Rozada', 'Spain', 'player'),
	('Marcos Curado', 'Argentina', 'player'),
	('Daniel Cervantes', 'Mexico', 'player'),
	('Lukas Ried', 'Austria', 'player'),
	('Grégory Grisez', 'Belgium', 'player'),
	('Joan Oumari', 'Lebanon', 'player'),
	('Ian Henderson', 'England', 'player'),
	('Christoffer Aasbak', 'Norway', 'player'),
	('Louis Bostyn', 'Belgium', 'player'),
	('Simon Handle', 'Germany', 'player'),
	('Reece Oxford', 'England', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Tom Pietermaat', 'Belgium', 'pietermaat'),
	('Tom Pietermaat', 'Belgium', 'tom pietermaat'),
	('Mirnes Pepić', 'Montenegro', 'mirnes pepic'),
	('Mirnes Pepić', 'Montenegro', 'pepic'),
	('Ryan Johnson Laursen', 'Denmark', 'laursen'),
	('Ryan Johnson Laursen', 'Denmark', 'ryan johnson laursen'),
	('Nordin Jackers', 'Belgium', 'jackers'),
	('Nordin Jackers', 'Belgium', 'nordin jackers'),
	('Emanuel Schreiner', 'Austria', 'emanuel schreiner'),
	('Emanuel Schreiner', 'Austria', 'schreiner'),
	('Stevie Mallan', 'Scotland', 'mallan'),
	('Stevie Mallan', 'Scotland', 'stevie mallan'),
	('Esquerdo', 'Spain', 'esquerdo'),
	('Stefan Kutschke', 'Germany', 'kutschke'),
	('Stefan Kutschke', 'Germany', 'stefan kutschke'),
	('Fran Vélez', 'Spain', 'velez'),
	('Fran Vélez', 'Spain', 'fran velez'),
	('David Niepsuj', 'Poland', 'david niepsuj'),
	('David Niepsuj', 'Poland', 'niepsuj'),
	('Damian Rasak', 'Poland', 'damian rasak'),
	('Damian Rasak', 'Poland', 'rasak'),
	('Romário Baldé', 'Guinea Bissau', 'romario balde'),
	('Romário Baldé', 'Guinea Bissau', 'balde'),
	('Samuel Shashoua', 'England', 'samuel shashoua'),
	('Samuel Shashoua', 'England', 'shashoua'),
	('Samuel Lino', 'Brazil', 'samuel lino'),
	('Samuel Lino', 'Brazil', 'lino'),
	('Chris Ramos', 'Spain', 'ramos'),
	('Chris Ramos', 'Spain', 'chris ramos'),
	('Ben Wilmot', 'England', 'wilmot'),
	('Ben Wilmot', 'England', 'ben wilmot'),
	('Ramiro Guerra', 'Uruguay', 'ramiro guerra'),
	('Ramiro Guerra', 'Uruguay', 'guerra'),
	('Iván Colman', 'Argentina', 'ivan colman'),
	('Iván Colman', 'Argentina', 'colman'),
	('Nicklas Helenius', 'Denmark', 'helenius'),
	('Nicklas Helenius', 'Denmark', 'nicklas helenius'),
	('Antoine Colassin', 'Belgium', 'colassin'),
	('Antoine Colassin', 'Belgium', 'antoine colassin'),
	('Dries Wuytens', 'Belgium', 'wuytens'),
	('Dries Wuytens', 'Belgium', 'dries wuytens'),
	('Zhang Chi', 'China PR', 'zhang chi'),
	('Zhang Chi', 'China PR', 'chi'),
	('Jason Naismith', 'Scotland', 'naismith'),
	('Jason Naismith', 'Scotland', 'jason naismith'),
	('Piotr Celeban', 'Poland', 'piotr celeban'),
	('Piotr Celeban', 'Poland', 'celeban'),
	('Sam Surridge', 'England', 'surridge'),
	('Sam Surridge', 'England', 'sam surridge'),
	('Brad Knighton', 'United States', 'knighton'),
	('Brad Knighton', 'United States', 'brad knighton'),
	('José Suárez', 'Spain', 'jose suarez'),
	('José Suárez', 'Spain', 'suarez'),
	('Melker Hallberg', 'Sweden', 'hallberg'),
	('Melker Hallberg', 'Sweden', 'melker hallberg'),
	('Williams Riveros', 'Paraguay', 'riveros'),
	('Williams Riveros', 'Paraguay', 'williams riveros'),
	('Aly Abeid', 'Mauritania', 'abeid'),
	('Aly Abeid', 'Mauritania', 'aly abeid'),
	('Radoslav Dimitrov', 'Bulgaria', 'radoslav dimitrov'),
	('Radoslav Dimitrov', 'Bulgaria', 'dimitrov'),
	('Ivan Goranov', 'Bulgaria', 'ivan goranov'),
	('Ivan Goranov', 'Bulgaria', 'goranov'),
	('Michał Mak', 'Poland', 'mak'),
	('Michał Mak', 'Poland', 'micha mak'),
	('Sascha Mockenhaupt', 'Germany', 'sascha mockenhaupt'),
	('Sascha Mockenhaupt', 'Germany', 'mockenhaupt'),
	('Maximiliano Perg', 'Uruguay', 'maximiliano perg'),
	('Maximiliano Perg', 'Uruguay', 'perg'),
	('Yassin Ben Balla', 'France', 'balla'),
	('Yassin Ben Balla', 'France', 'yassin ben balla'),
	('David Murillo', 'Colombia', 'david murillo'),
	('David Murillo', 'Colombia', 'murillo'),
	('David Wheeler', 'England', 'wheeler'),
	('David Wheeler', 'England', 'david wheeler'),
	('Obinna Nwobodo', 'Nigeria', 'obinna nwobodo'),
	('Obinna Nwobodo', 'Nigeria', 'nwobodo'),
	('Gjermund Åsen', 'Norway', 'gjermund asen'),
	('Gjermund Åsen', 'Norway', 'asen'),
	('Stefan Stangl', 'Austria', 'stefan stangl'),
	('Stefan Stangl', 'Austria', 'stangl'),
	('Thomas Bruns', 'Netherlands', 'thomas bruns'),
	('Thomas Bruns', 'Netherlands', 'bruns'),
	('Jak Alnwick', 'England', 'jak alnwick'),
	('Jak Alnwick', 'England', 'alnwick'),
	('Jérémy Perbet', 'France', 'perbet'),
	('Jérémy Perbet', 'France', 'jeremy perbet'),
	('Simone Edera', 'Italy', 'edera'),
	('Simone Edera', 'Italy', 'simone edera'),
	('Cole Skuse', 'England', 'skuse'),
	('Cole Skuse', 'England', 'cole skuse'),
	('Vito Hammershøy-Mistrati', 'Denmark', 'hammershymistrati'),
	('Vito Hammershøy-Mistrati', 'Denmark', 'vito hammershymistrati'),
	('Han-Noah Massengo', 'France', 'massengo'),
	('Han-Noah Massengo', 'France', 'hannoah massengo'),
	('Yevgen Cheberko', 'Ukraine', 'cheberko'),
	('Yevgen Cheberko', 'Ukraine', 'yevgen cheberko'),
	('Marcus Antonsson', 'Sweden', 'antonsson'),
	('Marcus Antonsson', 'Sweden', 'marcus antonsson'),
	('Yusuke Chajima', 'Japan', 'yusuke chajima'),
	('Yusuke Chajima', 'Japan', 'chajima'),
	('Emmanuel Ntim', 'Ghana', 'ntim'),
	('Emmanuel Ntim', 'Ghana', 'emmanuel ntim'),
	('Marc Heider', 'Germany', 'heider'),
	('Marc Heider', 'Germany', 'marc heider'),
	('Babacar Niasse', 'Senegal', 'niasse'),
	('Babacar Niasse', 'Senegal', 'babacar niasse'),
	('Jugurtha Hamroun', 'Algeria', 'jugurtha hamroun'),
	('Jugurtha Hamroun', 'Algeria', 'hamroun'),
	('Mirko Boland', 'Germany', 'mirko boland'),
	('Mirko Boland', 'Germany', 'boland'),
	('Tiago Tomás', 'Portugal', 'tiago tomas'),
	('Tiago Tomás', 'Portugal', 'tomas'),
	('Simon Piesinger', 'Austria', 'piesinger'),
	('Simon Piesinger', 'Austria', 'simon piesinger'),
	('Harrison Delbridge', 'Australia', 'delbridge'),
	('Harrison Delbridge', 'Australia', 'harrison delbridge'),
	('Alexander Farnerud', 'Sweden', 'farnerud'),
	('Alexander Farnerud', 'Sweden', 'alexander farnerud'),
	('Willer Ditta', 'Colombia', 'willer ditta'),
	('Willer Ditta', 'Colombia', 'ditta'),
	('Kenny Prince Redondo', 'Germany', 'kenny prince redondo'),
	('Kenny Prince Redondo', 'Germany', 'redondo'),
	('Iñaki Sáenz', 'Spain', 'saenz'),
	('Iñaki Sáenz', 'Spain', 'inaki saenz'),
	('Andrea Danzi', 'Italy', 'danzi'),
	('Andrea Danzi', 'Italy', 'andrea danzi'),
	('Woo Ju Sung', 'Korea Republic', 'woo ju sung'),
	('Woo Ju Sung', 'Korea Republic', 'sung'),
	('Francisco Feuillassier', 'Argentina', 'francisco feuillassier'),
	('Francisco Feuillassier', 'Argentina', 'feuillassier'),
	('Bartosz Białek', 'Poland', 'bartosz biaek'),
	('Bartosz Białek', 'Poland', 'biaek'),
	('Abdulaziz Al Jebreen', 'Saudi Arabia', 'abdulaziz al jebreen'),
	('Abdulaziz Al Jebreen', 'Saudi Arabia', 'jebreen'),
	('Brendan Chardonnet', 'France', 'brendan chardonnet'),
	('Brendan Chardonnet', 'France', 'chardonnet'),
	('Mark Travers', 'Republic of Ireland', 'mark travers'),
	('Mark Travers', 'Republic of Ireland', 'travers'),
	('Eoin Doyle', 'Republic of Ireland', 'eoin doyle'),
	('Eoin Doyle', 'Republic of Ireland', 'doyle'),
	('Teenage Hadebe', 'Zimbabwe', 'teenage hadebe'),
	('Teenage Hadebe', 'Zimbabwe', 'hadebe'),
	('Jeremy Ngakia', 'England', 'jeremy ngakia'),
	('Jeremy Ngakia', 'England', 'ngakia'),
	('Simon Eastwood', 'England', 'eastwood'),
	('Simon Eastwood', 'England', 'simon eastwood'),
	('José Valencia', 'Colombia', 'valencia'),
	('José Valencia', 'Colombia', 'jose valencia'),
	('Andrés Flores', 'El Salvador', 'andres flores'),
	('Andrés Flores', 'El Salvador', 'flores'),
	('Borys Tashchy', 'Ukraine', 'tashchy'),
	('Borys Tashchy', 'Ukraine', 'borys tashchy'),
	('Hamidou Keyta', 'France', 'keyta'),
	('Hamidou Keyta', 'France', 'hamidou keyta'),
	('Fidel Escobar', 'Panama', 'escobar'),
	('Fidel Escobar', 'Panama', 'fidel escobar'),
	('Shin Kwang Hoon', 'Korea Republic', 'shin kwang hoon'),
	('Shin Kwang Hoon', 'Korea Republic', 'hoon'),
	('Guillaume Bosca', 'France', 'bosca'),
	('Guillaume Bosca', 'France', 'guillaume bosca'),
	('Rilwan Hassan', 'Nigeria', 'rilwan hassan'),
	('Rilwan Hassan', 'Nigeria', 'hassan'),
	('Pablo Sisniega', 'Mexico', 'pablo sisniega'),
	('Pablo Sisniega', 'Mexico', 'sisniega'),
	('Kazushi Mitsuhira', 'Japan', 'kazushi mitsuhira'),
	('Kazushi Mitsuhira', 'Japan', 'mitsuhira'),
	('Cristo Romero', 'Spain', 'cristo romero'),
	('Cristo Romero', 'Spain', 'romero'),
	('Choi Sung Geun', 'Korea Republic', 'choi sung geun'),
	('Choi Sung Geun', 'Korea Republic', 'geun'),
	('Đorđe Crnomarković', 'Serbia', 'crnomarkovic'),
	('Đorđe Crnomarković', 'Serbia', 'ore crnomarkovic'),
	('Murat Yıldırım', 'Turkey', 'murat yldrm'),
	('Murat Yıldırım', 'Turkey', 'yldrm'),
	('Marco Kana', 'Belgium', 'marco kana'),
	('Marco Kana', 'Belgium', 'kana'),
	('Boubacar Barry', 'Germany', 'barry'),
	('Boubacar Barry', 'Germany', 'boubacar barry'),
	('Sikou Niakaté', 'France', 'niakate'),
	('Sikou Niakaté', 'France', 'sikou niakate'),
	('Alberto Acosta', 'Mexico', 'alberto acosta'),
	('Alberto Acosta', 'Mexico', 'acosta'),
	('Richard Windbichler', 'Austria', 'windbichler'),
	('Richard Windbichler', 'Austria', 'richard windbichler'),
	('Terrence Boyd', 'United States', 'boyd'),
	('Terrence Boyd', 'United States', 'terrence boyd'),
	('Fawaz Al Qarni', 'Saudi Arabia', 'qarni'),
	('Fawaz Al Qarni', 'Saudi Arabia', 'fawaz al qarni'),
	('Jan Zwischenbrugger', 'Austria', 'zwischenbrugger'),
	('Jan Zwischenbrugger', 'Austria', 'jan zwischenbrugger'),
	('David Milinković', 'France', 'david milinkovic'),
	('David Milinković', 'France', 'milinkovic'),
	('César Carrillo', 'Colombia', 'carrillo'),
	('César Carrillo', 'Colombia', 'cesar carrillo'),
	('Jhojan Julio', 'Ecuador', 'jhojan julio'),
	('Jhojan Julio', 'Ecuador', 'julio'),
	('Danilo Carando', 'Argentina', 'danilo carando'),
	('Danilo Carando', 'Argentina', 'carando'),
	('Robert Taylor', 'Finland', 'taylor'),
	('Robert Taylor', 'Finland', 'robert taylor'),
	('Guan Zhen', 'China PR', 'zhen'),
	('Guan Zhen', 'China PR', 'guan zhen'),
	('Killian Sardella', 'Belgium', 'sardella'),
	('Killian Sardella', 'Belgium', 'killian sardella'),
	('Nicolás Acevedo', 'Uruguay', 'nicolas acevedo'),
	('Nicolás Acevedo', 'Uruguay', 'acevedo'),
	('Awadh Khamis', 'Saudi Arabia', 'khamis'),
	('Awadh Khamis', 'Saudi Arabia', 'awadh khamis'),
	('Dante Rigo', 'Belgium', 'dante rigo'),
	('Dante Rigo', 'Belgium', 'rigo'),
	('Jarosław Jach', 'Poland', 'jach'),
	('Jarosław Jach', 'Poland', 'jarosaw jach'),
	('Daniel Høegh', 'Denmark', 'hegh'),
	('Daniel Høegh', 'Denmark', 'daniel hegh'),
	('Rafał Boguski', 'Poland', 'boguski'),
	('Rafał Boguski', 'Poland', 'rafa boguski'),
	('Pablo Lavandeira', 'Peru', 'lavandeira'),
	('Pablo Lavandeira', 'Peru', 'pablo lavandeira'),
	('Maksym Koval', 'Ukraine', 'koval'),
	('Maksym Koval', 'Ukraine', 'maksym koval'),
	('David Gil', 'Spain', 'gil'),
	('David Gil', 'Spain', 'david gil'),
	('Boniek García', 'Honduras', 'garcia'),
	('Boniek García', 'Honduras', 'boniek garcia'),
	('Arbnor Mucolli', 'Albania', 'mucolli'),
	('Arbnor Mucolli', 'Albania', 'arbnor mucolli'),
	('Wouter Biebauw', 'Belgium', 'wouter biebauw'),
	('Wouter Biebauw', 'Belgium', 'biebauw'),
	('Connor Wood', 'England', 'connor wood'),
	('Connor Wood', 'England', 'wood'),
	('André Luís', 'Brazil', 'andre luis'),
	('André Luís', 'Brazil', 'luis'),
	('Cristian Vega', 'Argentina', 'vega'),
	('Cristian Vega', 'Argentina', 'cristian vega'),
	('Santiago Amorín', 'Uruguay', 'amorin'),
	('Santiago Amorín', 'Uruguay', 'santiago amorin'),
	('Anders K. Jacobsen', 'Denmark', 'anders k jacobsen'),
	('Anders K. Jacobsen', 'Denmark', 'jacobsen'),
	('Mikael Anderson', 'Iceland', 'mikael anderson'),
	('Mikael Anderson', 'Iceland', 'anderson'),
	('Martín Payero', 'Argentina', 'payero'),
	('Martín Payero', 'Argentina', 'martin payero'),
	('Zheng Long', 'China PR', 'zheng long'),
	('Zheng Long', 'China PR', 'long'),
	('Janio Bikel', 'Portugal', 'bikel'),
	('Janio Bikel', 'Portugal', 'janio bikel'),
	('Rafael Romo', 'Venezuela', 'rafael romo'),
	('Rafael Romo', 'Venezuela', 'romo'),
	('Gabriel Enache', 'Romania', 'enache'),
	('Gabriel Enache', 'Romania', 'gabriel enache'),
	('Jonathan Augustinsson', 'Sweden', 'augustinsson'),
	('Jonathan Augustinsson', 'Sweden', 'jonathan augustinsson'),
	('Carlos Gutiérrez', 'Mexico', 'carlos gutierrez'),
	('Carlos Gutiérrez', 'Mexico', 'gutierrez'),
	('Sebastiano Esposito', 'Italy', 'esposito'),
	('Sebastiano Esposito', 'Italy', 'sebastiano esposito'),
	('Tom Pearce', 'England', 'pearce'),
	('Tom Pearce', 'England', 'tom pearce'),
	('Goduine Koyalipou', 'France', 'koyalipou'),
	('Goduine Koyalipou', 'France', 'goduine koyalipou'),
	('Richard Wood', 'England', 'richard wood'),
	('Richard Wood', 'England', 'wood'),
	('Thomas Grøgaard', 'Norway', 'thomas grgaard'),
	('Thomas Grøgaard', 'Norway', 'grgaard'),
	('Wouter Burger', 'Netherlands', 'burger'),
	('Wouter Burger', 'Netherlands', 'wouter burger'),
	('Mattia Montini', 'Italy', 'montini'),
	('Mattia Montini', 'Italy', 'mattia montini'),
	('Jakub Piotrowski', 'Poland', 'piotrowski'),
	('Jakub Piotrowski', 'Poland', 'jakub piotrowski'),
	('Gwon Wan Gyu', 'Korea Republic', 'gwon wan gyu'),
	('Gwon Wan Gyu', 'Korea Republic', 'gyu'),
	('Jeong Dong Ho', 'Korea Republic', 'ho'),
	('Jeong Dong Ho', 'Korea Republic', 'jeong dong ho'),
	('Harold Gómez', 'Colombia', 'gomez'),
	('Harold Gómez', 'Colombia', 'harold gomez'),
	('Behrang Safari', 'Sweden', 'safari'),
	('Behrang Safari', 'Sweden', 'behrang safari'),
	('Simon Makienok', 'Denmark', 'makienok'),
	('Simon Makienok', 'Denmark', 'simon makienok'),
	('Wang Yongpo', 'China PR', 'yongpo'),
	('Wang Yongpo', 'China PR', 'wang yongpo'),
	('Carlos Luna', 'Argentina', 'carlos luna'),
	('Carlos Luna', 'Argentina', 'luna'),
	('Jordy Alcívar', 'Ecuador', 'alcivar'),
	('Jordy Alcívar', 'Ecuador', 'jordy alcivar'),
	('Jhonathan Candia', 'Uruguay', 'candia'),
	('Jhonathan Candia', 'Uruguay', 'jhonathan candia'),
	('Cenk Alkılıç', 'Turkey', 'cenk alklc'),
	('Cenk Alkılıç', 'Turkey', 'alklc'),
	('Kensuke Sato', 'Japan', 'kensuke sato'),
	('Kensuke Sato', 'Japan', 'sato'),
	('Babacar Gueye', 'Senegal', 'babacar gueye'),
	('Babacar Gueye', 'Senegal', 'gueye'),
	('Shaun Whalley', 'England', 'whalley'),
	('Shaun Whalley', 'England', 'shaun whalley'),
	('Marius Kleinsorge', 'Germany', 'kleinsorge'),
	('Marius Kleinsorge', 'Germany', 'marius kleinsorge'),
	('Aurélien Collin', 'France', 'aurelien collin'),
	('Aurélien Collin', 'France', 'collin'),
	('Carlos Augusto', 'Brazil', 'augusto'),
	('Carlos Augusto', 'Brazil', 'carlos augusto'),
	('Jake Carroll', 'Republic of Ireland', 'carroll'),
	('Jake Carroll', 'Republic of Ireland', 'jake carroll'),
	('Ryan Wintle', 'England', 'wintle'),
	('Ryan Wintle', 'England', 'ryan wintle'),
	('Mustafa Amini', 'Australia', 'mustafa amini'),
	('Mustafa Amini', 'Australia', 'amini'),
	('Yuta Koide', 'Japan', 'koide'),
	('Yuta Koide', 'Japan', 'yuta koide'),
	('Louie Sibley', 'England', 'louie sibley'),
	('Louie Sibley', 'England', 'sibley'),
	('José Rivas', 'Venezuela', 'jose rivas'),
	('José Rivas', 'Venezuela', 'rivas'),
	('Daniel Hägele', 'Germany', 'daniel hagele'),
	('Daniel Hägele', 'Germany', 'hagele'),
	('Benjamin Girth', 'Germany', 'benjamin girth'),
	('Benjamin Girth', 'Germany', 'girth'),
	('Doğan Erdoğan', 'Turkey', 'erdogan'),
	('Doğan Erdoğan', 'Turkey', 'dogan erdogan'),
	('David Martin', 'England', 'david martin'),
	('David Martin', 'England', 'martin'),
	('Gu Cao', 'China PR', 'cao'),
	('Gu Cao', 'China PR', 'gu cao'),
	('Sefa Yılmaz', 'Turkey', 'ylmaz'),
	('Sefa Yılmaz', 'Turkey', 'sefa ylmaz'),
	('Michael Covea', 'Venezuela', 'michael covea'),
	('Michael Covea', 'Venezuela', 'covea'),
	('Lukas Königshofer', 'Austria', 'lukas konigshofer'),
	('Lukas Königshofer', 'Austria', 'konigshofer'),
	('Shea Salinas', 'United States', 'salinas'),
	('Shea Salinas', 'United States', 'shea salinas'),
	('Mossa', 'Spain', 'mossa'),
	('Jeremias Lorch', 'Germany', 'jeremias lorch'),
	('Jeremias Lorch', 'Germany', 'lorch'),
	('Rodrigo Abascal', 'Uruguay', 'abascal'),
	('Rodrigo Abascal', 'Uruguay', 'rodrigo abascal'),
	('Kane Vincent-Young', 'England', 'vincentyoung'),
	('Kane Vincent-Young', 'England', 'kane vincentyoung'),
	('Dan Potts', 'England', 'dan potts'),
	('Dan Potts', 'England', 'potts'),
	('Lalaïna Nomenjanahary', 'Madagascar', 'nomenjanahary'),
	('Lalaïna Nomenjanahary', 'Madagascar', 'lalaina nomenjanahary'),
	('Dominic Hyam', 'Scotland', 'hyam'),
	('Dominic Hyam', 'Scotland', 'dominic hyam'),
	('Chiedozie Ogbene', 'Nigeria', 'chiedozie ogbene'),
	('Chiedozie Ogbene', 'Nigeria', 'ogbene'),
	('Tomasz Makowski', 'Poland', 'makowski'),
	('Tomasz Makowski', 'Poland', 'tomasz makowski'),
	('Carlo Sickinger', 'Germany', 'carlo sickinger'),
	('Carlo Sickinger', 'Germany', 'sickinger'),
	('Martin Kobras', 'Austria', 'kobras'),
	('Martin Kobras', 'Austria', 'martin kobras'),
	('Darwin Cuero', 'Ecuador', 'darwin cuero'),
	('Darwin Cuero', 'Ecuador', 'cuero'),
	('Jean-Pierre Rhyner', 'Switzerland', 'rhyner'),
	('Jean-Pierre Rhyner', 'Switzerland', 'jeanpierre rhyner'),
	('Abass Issah', 'Ghana', 'issah'),
	('Abass Issah', 'Ghana', 'abass issah'),
	('Chris Durkin', 'United States', 'chris durkin'),
	('Chris Durkin', 'United States', 'durkin'),
	('Marcos Caicedo', 'Ecuador', 'caicedo'),
	('Marcos Caicedo', 'Ecuador', 'marcos caicedo'),
	('Vlad Achim', 'Romania', 'achim'),
	('Vlad Achim', 'Romania', 'vlad achim'),
	('Finn Porath', 'Germany', 'finn porath'),
	('Finn Porath', 'Germany', 'porath'),
	('Nahuel Estévez', 'Argentina', 'nahuel estevez'),
	('Nahuel Estévez', 'Argentina', 'estevez'),
	('Thomas Buitink', 'Netherlands', 'thomas buitink'),
	('Thomas Buitink', 'Netherlands', 'buitink'),
	('Bryan Cabezas', 'Ecuador', 'bryan cabezas'),
	('Bryan Cabezas', 'Ecuador', 'cabezas'),
	('Carlos Hernández', 'Spain', 'hernandez'),
	('Carlos Hernández', 'Spain', 'carlos hernandez'),
	('Adrián Arregui', 'Argentina', 'arregui'),
	('Adrián Arregui', 'Argentina', 'adrian arregui'),
	('Carlos Caraza', 'Peru', 'caraza'),
	('Carlos Caraza', 'Peru', 'carlos caraza'),
	('Marco Komenda', 'Germany', 'komenda'),
	('Marco Komenda', 'Germany', 'marco komenda'),
	('Cosmin Matei', 'Romania', 'cosmin matei'),
	('Cosmin Matei', 'Romania', 'matei'),
	('Joel Amoroso', 'Argentina', 'joel amoroso'),
	('Joel Amoroso', 'Argentina', 'amoroso'),
	('Diego Alende', 'Spain', 'alende'),
	('Diego Alende', 'Spain', 'diego alende'),
	('Maxence Lacroix', 'France', 'lacroix'),
	('Maxence Lacroix', 'France', 'maxence lacroix'),
	('Kouadio Manu Koné', 'France', 'kouadio manu kone'),
	('Kouadio Manu Koné', 'France', 'kone'),
	('Yusuke Matsuo', 'Japan', 'yusuke matsuo'),
	('Yusuke Matsuo', 'Japan', 'matsuo'),
	('Junior Adamu', 'Austria', 'junior adamu'),
	('Junior Adamu', 'Austria', 'adamu'),
	('Ash Taylor', 'Wales', 'taylor'),
	('Ash Taylor', 'Wales', 'ash taylor'),
	('Kofi Schulz', 'Germany', 'kofi schulz'),
	('Kofi Schulz', 'Germany', 'schulz'),
	('Patric Klandt', 'Germany', 'patric klandt'),
	('Patric Klandt', 'Germany', 'klandt'),
	('Tomás Andrade', 'Argentina', 'andrade'),
	('Tomás Andrade', 'Argentina', 'tomas andrade'),
	('Richard Smallwood', 'England', 'smallwood'),
	('Richard Smallwood', 'England', 'richard smallwood'),
	('Chima Akas', 'Nigeria', 'akas'),
	('Chima Akas', 'Nigeria', 'chima akas'),
	('Marko Poletanović', 'Serbia', 'poletanovic'),
	('Marko Poletanović', 'Serbia', 'marko poletanovic'),
	('Luciano Ospina', 'Colombia', 'ospina'),
	('Luciano Ospina', 'Colombia', 'luciano ospina'),
	('Adi Nalić', 'Sweden', 'adi nalic'),
	('Adi Nalić', 'Sweden', 'nalic'),
	('Joel Asoro', 'Sweden', 'asoro'),
	('Joel Asoro', 'Sweden', 'joel asoro'),
	('Héber Pena', 'Spain', 'heber pena'),
	('Héber Pena', 'Spain', 'pena'),
	('Elliot', 'Spain', 'elliot'),
	('Aaron Herrera', 'United States', 'herrera'),
	('Aaron Herrera', 'United States', 'aaron herrera'),
	('Bonke Innocent', 'Nigeria', 'innocent'),
	('Bonke Innocent', 'Nigeria', 'bonke innocent'),
	('John-Patrick Strauß', 'Philippines', 'johnpatrick strau'),
	('John-Patrick Strauß', 'Philippines', 'strau'),
	('Alexandru Albu', 'Romania', 'alexandru albu'),
	('Alexandru Albu', 'Romania', 'albu'),
	('Drey Wright', 'England', 'drey wright'),
	('Drey Wright', 'England', 'wright'),
	('Ismaël Chester Diallo', 'Ivory Coast', 'diallo'),
	('Ismaël Chester Diallo', 'Ivory Coast', 'ismael chester diallo'),
	('Jordan Williams', 'England', 'jordan williams'),
	('Jordan Williams', 'England', 'williams'),
	('Mihai Căpățînă', 'Romania', 'mihai capatina'),
	('Mihai Căpățînă', 'Romania', 'capatina'),
	('Saad Agouzoul', 'Morocco', 'agouzoul'),
	('Saad Agouzoul', 'Morocco', 'saad agouzoul'),
	('Brandon Soppy', 'France', 'soppy'),
	('Brandon Soppy', 'France', 'brandon soppy'),
	('Edgar Hernández', 'Spain', 'hernandez'),
	('Edgar Hernández', 'Spain', 'edgar hernandez'),
	('Eirik Ulland Andersen', 'Norway', 'andersen'),
	('Eirik Ulland Andersen', 'Norway', 'eirik ulland andersen'),
	('Herolind Shala', 'Kosovo', 'herolind shala'),
	('Herolind Shala', 'Kosovo', 'shala'),
	('Pierre Cornud', 'France', 'cornud'),
	('Pierre Cornud', 'France', 'pierre cornud'),
	('Clinton Mola', 'England', 'mola'),
	('Clinton Mola', 'England', 'clinton mola'),
	('Federico Palacios Martínez', 'Spain', 'federico palacios martinez'),
	('Federico Palacios Martínez', 'Spain', 'martinez'),
	('Jefferson Gómez', 'Colombia', 'gomez'),
	('Jefferson Gómez', 'Colombia', 'jefferson gomez'),
	('Lukas Daschner', 'Germany', 'lukas daschner'),
	('Lukas Daschner', 'Germany', 'daschner'),
	('Sylla Sow', 'Netherlands', 'sylla sow'),
	('Sylla Sow', 'Netherlands', 'sow'),
	('Ibrahim Chenihi', 'Algeria', 'chenihi'),
	('Ibrahim Chenihi', 'Algeria', 'ibrahim chenihi'),
	('Christian Cruz', 'Ecuador', 'cruz'),
	('Christian Cruz', 'Ecuador', 'christian cruz'),
	('Bakary Nimaga', 'Mali', 'bakary nimaga'),
	('Bakary Nimaga', 'Mali', 'nimaga'),
	('Steffen Puttkammer', 'Germany', 'steffen puttkammer'),
	('Steffen Puttkammer', 'Germany', 'puttkammer'),
	('Juan Familia-Castillo', 'Netherlands', 'familiacastillo'),
	('Juan Familia-Castillo', 'Netherlands', 'juan familiacastillo'),
	('Michiel Jonckheere', 'Belgium', 'michiel jonckheere'),
	('Michiel Jonckheere', 'Belgium', 'jonckheere'),
	('Jann-Fiete Arp', 'Germany', 'arp'),
	('Jann-Fiete Arp', 'Germany', 'jannfiete arp'),
	('Alhaji Kamara', 'Sierra Leone', 'alhaji kamara'),
	('Alhaji Kamara', 'Sierra Leone', 'kamara'),
	('Alex Bass', 'England', 'bass'),
	('Alex Bass', 'England', 'alex bass'),
	('Viti Rozada', 'Spain', 'rozada'),
	('Viti Rozada', 'Spain', 'viti rozada'),
	('Marcos Curado', 'Argentina', 'curado'),
	('Marcos Curado', 'Argentina', 'marcos curado'),
	('Daniel Cervantes', 'Mexico', 'cervantes'),
	('Daniel Cervantes', 'Mexico', 'daniel cervantes'),
	('Lukas Ried', 'Austria', 'lukas ried'),
	('Lukas Ried', 'Austria', 'ried'),
	('Grégory Grisez', 'Belgium', 'grisez'),
	('Grégory Grisez', 'Belgium', 'gregory grisez'),
	('Joan Oumari', 'Lebanon', 'joan oumari'),
	('Joan Oumari', 'Lebanon', 'oumari'),
	('Ian Henderson', 'England', 'henderson'),
	('Ian Henderson', 'England', 'ian henderson'),
	('Christoffer Aasbak', 'Norway', 'aasbak'),
	('Christoffer Aasbak', 'Norway', 'christoffer aasbak'),
	('Louis Bostyn', 'Belgium', 'bostyn'),
	('Louis Bostyn', 'Belgium', 'louis bostyn'),
	('Simon Handle', 'Germany', 'handle'),
	('Simon Handle', 'Germany', 'simon handle'),
	('Reece Oxford', 'England', 'reece oxford'),
	('Reece Oxford', 'England', 'oxford')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';