INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Atienza', 'Spain', 'player'),
	('Song Wenjie', 'China PR', 'player'),
	('Krzysztof Kubica', 'Poland', 'player'),
	('Maximilian Zaiser', 'Germany', 'player'),
	('Onurhan Babuscu', 'Austria', 'player'),
	('Ira Jackson Jr', 'England', 'player'),
	('Guðmundur Andri Tryggvason', 'Iceland', 'player'),
	('Max Sprang', 'Germany', 'player'),
	('Denso Ulysse', 'Haiti', 'player'),
	('Jordan Holsgrove', 'Scotland', 'player'),
	('Marcel Zylla', 'Poland', 'player'),
	('Luke Wade-Slater', 'Republic of Ireland', 'player'),
	('Million Manhoef', 'Netherlands', 'player'),
	('Kento Haneda', 'Japan', 'player'),
	('Sebastian Pasquali', 'Australia', 'player'),
	('Armel Zohouri', 'Ivory Coast', 'player'),
	('Murat Paluli', 'Turkey', 'player'),
	('Martin Peralta', 'Argentina', 'player'),
	('Sultan Faqihi', 'Saudi Arabia', 'player'),
	('Adam Ratajczyk', 'Poland', 'player'),
	('Jack Rudoni', 'England', 'player'),
	('Herman Haugen', 'Norway', 'player'),
	('Takuro Kaneko', 'Japan', 'player'),
	('Manuel Ugarte', 'Uruguay', 'player'),
	('Doğukan Emeksiz', 'Turkey', 'player'),
	('Franco Pizzicanella', 'Argentina', 'player'),
	('Mateo Montenegro', 'Argentina', 'player'),
	('Elliot Watt', 'Scotland', 'player'),
	('Keelan O''Connell', 'England', 'player'),
	('Mark Beck', 'Scotland', 'player'),
	('Joffré Escobar', 'Ecuador', 'player'),
	('Lévi Ntumba', 'France', 'player'),
	('Vincent Schippers', 'Netherlands', 'player'),
	('Fabio Schneider', 'Germany', 'player'),
	('Armando Vera', 'Paraguay', 'player'),
	('Guo Wei', 'China PR', 'player'),
	('Cristian Blanco', 'Colombia', 'player'),
	('Pedro González', 'Paraguay', 'player'),
	('Fabricio Manzo', 'Chile', 'player'),
	('Kacper Chodyna', 'Poland', 'player'),
	('Angelo Mayer', 'Germany', 'player'),
	('Stelios Kokovas', 'Greece', 'player'),
	('Milton Garzón', 'Bolivia', 'player'),
	('Cristian Tovar', 'Colombia', 'player'),
	('Liu Zhenli', 'China PR', 'player'),
	('Kyle Smith', 'United States', 'player'),
	('Dino Visser', 'South Africa', 'player'),
	('Semi Belkahia', 'Germany', 'player'),
	('Daniel Szelągowski', 'Poland', 'player'),
	('Maximiliano Centurión', 'Argentina', 'player'),
	('Jason Ngouabi', 'France', 'player'),
	('Josué Gómez', 'Mexico', 'player'),
	('Rayan Philippe', 'France', 'player'),
	('Lucas Lemos', 'Uruguay', 'player'),
	('Sodai Hasukawa', 'Japan', 'player'),
	('Amer Eriksson Ibragic', 'Sweden', 'player'),
	('Leon Schaffran', 'Germany', 'player'),
	('Will Patching', 'England', 'player'),
	('Diego Fernández', 'Paraguay', 'player'),
	('Agustín Curruhinca', 'Argentina', 'player'),
	('Michael Fabrie', 'Netherlands', 'player'),
	('Kevin Isa', 'Argentina', 'player'),
	('Monday Samuel', 'Nigeria', 'player'),
	('Rory Feely', 'Republic of Ireland', 'player'),
	('George Thomson', 'England', 'player'),
	('Leonel Montano', 'Denmark', 'player'),
	('Ariel Cáceres', 'Chile', 'player'),
	('Ryan Brennan', 'Republic of Ireland', 'player'),
	('Freddie Hinds', 'England', 'player'),
	('Jonah Fabisch', 'Germany', 'player'),
	('Mésaque Djú', 'Portugal', 'player'),
	('Tobias Carlsson', 'Sweden', 'player'),
	('Daichi Hayashi', 'Japan', 'player'),
	('José Llovera', 'Venezuela', 'player'),
	('Park Byung Hyun', 'Korea Republic', 'player'),
	('Harrison Biggins', 'England', 'player'),
	('Choi Young Eun', 'Korea Republic', 'player'),
	('Zhou Yajun', 'China PR', 'player'),
	('Kian Harratt', 'England', 'player'),
	('Baba Touré', 'France', 'player'),
	('Kluiverth Aguilar', 'Peru', 'player'),
	('Diaz Wright', 'England', 'player'),
	('Danny Kane', 'Republic of Ireland', 'player'),
	('Shuhei Kawasaki', 'Japan', 'player'),
	('Mahamadou Dembélé', 'France', 'player'),
	('Cem-Tuna Türkmen', 'Turkey', 'player'),
	('Daniel Cabrera', 'Peru', 'player'),
	('Mohammed Sangare', 'Liberia', 'player'),
	('Cammy MacPherson', 'Scotland', 'player'),
	('Alessio Carlone', 'Belgium', 'player'),
	('Daniel Udoh', 'Nigeria', 'player'),
	('Lautaro López', 'Argentina', 'player'),
	('Bartłomiej Sielewski', 'Poland', 'player'),
	('Mathew Stevens', 'England', 'player'),
	('Barry McNamee', 'Republic of Ireland', 'player'),
	('Felix Irorere', 'Germany', 'player'),
	('Dillon Barnes', 'England', 'player'),
	('Arkadiusz Pyrka', 'Poland', 'player'),
	('Jader Valencia', 'Colombia', 'player'),
	('Abdullah Al Khatib', 'Saudi Arabia', 'player'),
	('Damian Primel', 'Poland', 'player'),
	('Maik Nawrocki', 'Poland', 'player'),
	('Niklas Kastenhofer', 'Germany', 'player'),
	('Murtadha Al Burayh', 'Saudi Arabia', 'player'),
	('Ozkan Cetiner', 'France', 'player'),
	('Julian von Moos', 'Switzerland', 'player'),
	('Mesut Çaytemel', 'Turkey', 'player'),
	('Christian Celesia', 'Italy', 'player'),
	('Benjamin Hvidt', 'Denmark', 'player'),
	('Adrian Laskowski', 'Poland', 'player'),
	('Jakub Wróbel', 'Poland', 'player'),
	('Donaldo Açka', 'Albania', 'player'),
	('Leon Bürger', 'Germany', 'player'),
	('Ciaron Brown', 'Northern Ireland', 'player'),
	('Robbie McCourt', 'Republic of Ireland', 'player'),
	('Rodrigo Esteban', 'Spain', 'player'),
	('Alex Denny', 'England', 'player'),
	('Rafał Leszczyński', 'Poland', 'player'),
	('Mateusz Praszelik', 'Poland', 'player'),
	('Peter Kioso', 'DR Congo', 'player'),
	('Ryan Cooney', 'England', 'player'),
	('Abdulsamed Damlu', 'Turkey', 'player'),
	('Facundo Torres', 'Uruguay', 'player'),
	('Oh Hyun Gyu', 'Korea Republic', 'player'),
	('Tyrese Sinclair', 'England', 'player'),
	('Saad Al Selouli', 'Saudi Arabia', 'player'),
	('Brandon Servania', 'United States', 'player'),
	('Moritz Schulze', 'Germany', 'player'),
	('Dariusz Pawłowski', 'Poland', 'player'),
	('Dion Lopy', 'Senegal', 'player'),
	('Josh Davison', 'England', 'player'),
	('Yahya Boussakou', 'Netherlands', 'player'),
	('Joe Grayson', 'England', 'player'),
	('Molina', 'Spain', 'player'),
	('Mohammed Al Sahli', 'Saudi Arabia', 'player'),
	('Alvin Jones', 'Trinidad & Tobago', 'player'),
	('Brandon Domingues', 'France', 'player'),
	('Nathan Monzango', 'DR Congo', 'player'),
	('Charly Jan', 'France', 'player'),
	('Gianfranco Facchineri', 'Canada', 'player'),
	('Elias Damergy', 'Tunisia', 'player'),
	('Katio Landi', 'Italy', 'player'),
	('Thijs Dallinga', 'Netherlands', 'player'),
	('Wahid Faghir', 'Denmark', 'player'),
	('Ender Aygören', 'Turkey', 'player'),
	('Dean Clarke', 'Republic of Ireland', 'player'),
	('Jun Nishikawa', 'Japan', 'player'),
	('Alistair Coote', 'Scotland', 'player'),
	('Anıl Gözütok', 'Germany', 'player'),
	('Iván Bolaño', 'Argentina', 'player'),
	('Jorge Vieira', 'Portugal', 'player'),
	('Ovidiu Perianu', 'Romania', 'player'),
	('Jaber Asiri', 'Saudi Arabia', 'player'),
	('Gerardo Bruna', 'Argentina', 'player'),
	('Gastón Pérez', 'Uruguay', 'player'),
	('Robbie Weir', 'Northern Ireland', 'player'),
	('Georgie Poynton', 'Republic of Ireland', 'player'),
	('Jake Brimmer', 'Australia', 'player'),
	('Gökhan Kardeş', 'Turkey', 'player'),
	('Noah Awuku', 'Germany', 'player'),
	('Isaac Christie-Davies', 'Wales', 'player'),
	('Luke Armstrong', 'England', 'player'),
	('Francisco Casanova', 'Uruguay', 'player'),
	('Diego Aravena', 'Chile', 'player'),
	('Muteb Al Mutlaq', 'Saudi Arabia', 'player'),
	('Tyler Smith', 'England', 'player'),
	('Yan', 'Brazil', 'player'),
	('Diego Bri', 'Spain', 'player'),
	('Gonzalo Pérez', 'Uruguay', 'player'),
	('Ahmed Al Sultan', 'Saudi Arabia', 'player'),
	('Aidan Stone', 'England', 'player'),
	('Pablo Oro', 'Argentina', 'player'),
	('Casper Tengstedt', 'Denmark', 'player'),
	('Kyowaan Hoshi', 'Japan', 'player'),
	('Pablo Abel Argañaraz', 'Argentina', 'player'),
	('Alexander Ahl Holmström', 'Sweden', 'player'),
	('Waleed Hezam Al Anazi', 'Saudi Arabia', 'player'),
	('Akinkunmi Amoo', 'Nigeria', 'player'),
	('Marcos Montiel', 'Uruguay', 'player'),
	('Mohammed Al Hassawi', 'Saudi Arabia', 'player'),
	('Dylan Fage', 'France', 'player'),
	('Noah Alexandersson', 'Sweden', 'player'),
	('Gonzalo Gómez', 'Argentina', 'player'),
	('Soner Dikmen', 'Turkey', 'player'),
	('Enzo Cabrera', 'Argentina', 'player'),
	('Fawaz Al Tryes', 'Saudi Arabia', 'player'),
	('Bruninho', 'Portugal', 'player'),
	('Christopher Lungoyi', 'Switzerland', 'player'),
	('Egzon Kryeziu', 'Slovenia', 'player'),
	('Abdulrahman Al Yami', 'Saudi Arabia', 'player'),
	('Liam Edwards', 'England', 'player'),
	('Mishari Al Qahtani', 'Saudi Arabia', 'player'),
	('Jordan Rezabala', 'Ecuador', 'player'),
	('Javier Ibarra', 'Mexico', 'player'),
	('Josh March', 'England', 'player'),
	('Enmerson Batalla', 'Colombia', 'player'),
	('Sami Ben Amar', 'Morocco', 'player'),
	('Godwin Bentil', 'Ghana', 'player'),
	('Rob Atkinson', 'England', 'player'),
	('Wellington Ramírez', 'Ecuador', 'player'),
	('Mauricio Isais', 'United States', 'player'),
	('Teun van Grunsven', 'Netherlands', 'player'),
	('Aidan Morris', 'United States', 'player'),
	('Brackzon León', 'Peru', 'player'),
	('Fabian Rohner', 'Switzerland', 'player'),
	('Jai Ingham', 'New Zealand', 'player'),
	('Peter Gwargis', 'Sweden', 'player'),
	('Oliver Antman', 'Finland', 'player'),
	('Nikell Touglo', 'Germany', 'player'),
	('Samuel Renel', 'France', 'player'),
	('Paul Lewis', 'England', 'player'),
	('Dennis Gorka', 'Germany', 'player'),
	('Jop van der Avert', 'Netherlands', 'player'),
	('Alex Addai', 'England', 'player'),
	('Hamdan Al Ruwaili', 'Saudi Arabia', 'player'),
	('Hassan Al Geed', 'Saudi Arabia', 'player'),
	('Astals', 'Spain', 'player'),
	('Yang Yu', 'China PR', 'player'),
	('Çağtay Kurukalıp', 'Turkey', 'player'),
	('Rodrigo Morínigo', 'Paraguay', 'player'),
	('Joachim Carcela-González', 'Belgium', 'player'),
	('Sebastián Cocimano', 'Argentina', 'player'),
	('Fuchi Honda', 'Japan', 'player'),
	('Paul Costea', 'Romania', 'player'),
	('Michael Steinwender', 'Austria', 'player'),
	('Ismael Omar', 'Saudi Arabia', 'player'),
	('Alex Purver', 'England', 'player'),
	('Alexander Ammitzbøll', 'Denmark', 'player'),
	('Morgan Boyes', 'Wales', 'player'),
	('Marcos Duré', 'Paraguay', 'player'),
	('Aaron McCarey', 'Republic of Ireland', 'player'),
	('Ryotaro Araki', 'Japan', 'player'),
	('Bugra Temel', 'Turkey', 'player'),
	('Cory Galvin', 'Republic of Ireland', 'player'),
	('Magnus S. Lundal', 'Norway', 'player'),
	('Lukas Fadinger', 'Austria', 'player'),
	('Omer Hanin', 'Israel', 'player'),
	('Giacomo Ricci', 'Italy', 'player'),
	('Josh Eccles', 'England', 'player'),
	('Shunta Awaka', 'Japan', 'player'),
	('Alejandro Samudio', 'Paraguay', 'player'),
	('Aymane Mourid', 'Morocco', 'player'),
	('Carlos Pando', 'Peru', 'player'),
	('Rémy Vita', 'France', 'player'),
	('George Ray', 'Wales', 'player'),
	('Lewis Butroid', 'England', 'player'),
	('Dean Campbell', 'Scotland', 'player'),
	('Dickson Abiama', 'Nigeria', 'player'),
	('Ryan Ponti', 'France', 'player'),
	('Juan Vieyra', 'Argentina', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Atienza', 'Spain', 'atienza'),
	('Song Wenjie', 'China PR', 'song wenjie'),
	('Song Wenjie', 'China PR', 'wenjie'),
	('Krzysztof Kubica', 'Poland', 'kubica'),
	('Krzysztof Kubica', 'Poland', 'krzysztof kubica'),
	('Maximilian Zaiser', 'Germany', 'maximilian zaiser'),
	('Maximilian Zaiser', 'Germany', 'zaiser'),
	('Onurhan Babuscu', 'Austria', 'onurhan babuscu'),
	('Onurhan Babuscu', 'Austria', 'babuscu'),
	('Ira Jackson Jr', 'England', 'jr'),
	('Ira Jackson Jr', 'England', 'ira jackson jr'),
	('Guðmundur Andri Tryggvason', 'Iceland', 'gumundur andri tryggvason'),
	('Guðmundur Andri Tryggvason', 'Iceland', 'tryggvason'),
	('Max Sprang', 'Germany', 'sprang'),
	('Max Sprang', 'Germany', 'max sprang'),
	('Denso Ulysse', 'Haiti', 'ulysse'),
	('Denso Ulysse', 'Haiti', 'denso ulysse'),
	('Jordan Holsgrove', 'Scotland', 'holsgrove'),
	('Jordan Holsgrove', 'Scotland', 'jordan holsgrove'),
	('Marcel Zylla', 'Poland', 'zylla'),
	('Marcel Zylla', 'Poland', 'marcel zylla'),
	('Luke Wade-Slater', 'Republic of Ireland', 'wadeslater'),
	('Luke Wade-Slater', 'Republic of Ireland', 'luke wadeslater'),
	('Million Manhoef', 'Netherlands', 'million manhoef'),
	('Million Manhoef', 'Netherlands', 'manhoef'),
	('Kento Haneda', 'Japan', 'kento haneda'),
	('Kento Haneda', 'Japan', 'haneda'),
	('Sebastian Pasquali', 'Australia', 'sebastian pasquali'),
	('Sebastian Pasquali', 'Australia', 'pasquali'),
	('Armel Zohouri', 'Ivory Coast', 'zohouri'),
	('Armel Zohouri', 'Ivory Coast', 'armel zohouri'),
	('Murat Paluli', 'Turkey', 'murat paluli'),
	('Murat Paluli', 'Turkey', 'paluli'),
	('Martin Peralta', 'Argentina', 'peralta'),
	('Martin Peralta', 'Argentina', 'martin peralta'),
	('Sultan Faqihi', 'Saudi Arabia', 'faqihi'),
	('Sultan Faqihi', 'Saudi Arabia', 'sultan faqihi'),
	('Adam Ratajczyk', 'Poland', 'ratajczyk'),
	('Adam Ratajczyk', 'Poland', 'adam ratajczyk'),
	('Jack Rudoni', 'England', 'rudoni'),
	('Jack Rudoni', 'England', 'jack rudoni'),
	('Herman Haugen', 'Norway', 'herman haugen'),
	('Herman Haugen', 'Norway', 'haugen'),
	('Takuro Kaneko', 'Japan', 'takuro kaneko'),
	('Takuro Kaneko', 'Japan', 'kaneko'),
	('Manuel Ugarte', 'Uruguay', 'manuel ugarte'),
	('Manuel Ugarte', 'Uruguay', 'ugarte'),
	('Doğukan Emeksiz', 'Turkey', 'emeksiz'),
	('Doğukan Emeksiz', 'Turkey', 'dogukan emeksiz'),
	('Franco Pizzicanella', 'Argentina', 'franco pizzicanella'),
	('Franco Pizzicanella', 'Argentina', 'pizzicanella'),
	('Mateo Montenegro', 'Argentina', 'mateo montenegro'),
	('Mateo Montenegro', 'Argentina', 'montenegro'),
	('Elliot Watt', 'Scotland', 'elliot watt'),
	('Elliot Watt', 'Scotland', 'watt'),
	('Keelan O''Connell', 'England', 'keelan oconnell'),
	('Keelan O''Connell', 'England', 'oconnell'),
	('Mark Beck', 'Scotland', 'mark beck'),
	('Mark Beck', 'Scotland', 'beck'),
	('Joffré Escobar', 'Ecuador', 'escobar'),
	('Joffré Escobar', 'Ecuador', 'joffre escobar'),
	('Lévi Ntumba', 'France', 'levi ntumba'),
	('Lévi Ntumba', 'France', 'ntumba'),
	('Vincent Schippers', 'Netherlands', 'vincent schippers'),
	('Vincent Schippers', 'Netherlands', 'schippers'),
	('Fabio Schneider', 'Germany', 'fabio schneider'),
	('Fabio Schneider', 'Germany', 'schneider'),
	('Armando Vera', 'Paraguay', 'vera'),
	('Armando Vera', 'Paraguay', 'armando vera'),
	('Guo Wei', 'China PR', 'wei'),
	('Guo Wei', 'China PR', 'guo wei'),
	('Cristian Blanco', 'Colombia', 'blanco'),
	('Cristian Blanco', 'Colombia', 'cristian blanco'),
	('Pedro González', 'Paraguay', 'pedro gonzalez'),
	('Pedro González', 'Paraguay', 'gonzalez'),
	('Fabricio Manzo', 'Chile', 'fabricio manzo'),
	('Fabricio Manzo', 'Chile', 'manzo'),
	('Kacper Chodyna', 'Poland', 'kacper chodyna'),
	('Kacper Chodyna', 'Poland', 'chodyna'),
	('Angelo Mayer', 'Germany', 'mayer'),
	('Angelo Mayer', 'Germany', 'angelo mayer'),
	('Stelios Kokovas', 'Greece', 'stelios kokovas'),
	('Stelios Kokovas', 'Greece', 'kokovas'),
	('Milton Garzón', 'Bolivia', 'milton garzon'),
	('Milton Garzón', 'Bolivia', 'garzon'),
	('Cristian Tovar', 'Colombia', 'tovar'),
	('Cristian Tovar', 'Colombia', 'cristian tovar'),
	('Liu Zhenli', 'China PR', 'liu zhenli'),
	('Liu Zhenli', 'China PR', 'zhenli'),
	('Kyle Smith', 'United States', 'smith'),
	('Kyle Smith', 'United States', 'kyle smith'),
	('Dino Visser', 'South Africa', 'visser'),
	('Dino Visser', 'South Africa', 'dino visser'),
	('Semi Belkahia', 'Germany', 'belkahia'),
	('Semi Belkahia', 'Germany', 'semi belkahia'),
	('Daniel Szelągowski', 'Poland', 'szelagowski'),
	('Daniel Szelągowski', 'Poland', 'daniel szelagowski'),
	('Maximiliano Centurión', 'Argentina', 'centurion'),
	('Maximiliano Centurión', 'Argentina', 'maximiliano centurion'),
	('Jason Ngouabi', 'France', 'ngouabi'),
	('Jason Ngouabi', 'France', 'jason ngouabi'),
	('Josué Gómez', 'Mexico', 'gomez'),
	('Josué Gómez', 'Mexico', 'josue gomez'),
	('Rayan Philippe', 'France', 'rayan philippe'),
	('Rayan Philippe', 'France', 'philippe'),
	('Lucas Lemos', 'Uruguay', 'lucas lemos'),
	('Lucas Lemos', 'Uruguay', 'lemos'),
	('Sodai Hasukawa', 'Japan', 'hasukawa'),
	('Sodai Hasukawa', 'Japan', 'sodai hasukawa'),
	('Amer Eriksson Ibragic', 'Sweden', 'ibragic'),
	('Amer Eriksson Ibragic', 'Sweden', 'amer eriksson ibragic'),
	('Leon Schaffran', 'Germany', 'schaffran'),
	('Leon Schaffran', 'Germany', 'leon schaffran'),
	('Will Patching', 'England', 'patching'),
	('Will Patching', 'England', 'will patching'),
	('Diego Fernández', 'Paraguay', 'fernandez'),
	('Diego Fernández', 'Paraguay', 'diego fernandez'),
	('Agustín Curruhinca', 'Argentina', 'agustin curruhinca'),
	('Agustín Curruhinca', 'Argentina', 'curruhinca'),
	('Michael Fabrie', 'Netherlands', 'fabrie'),
	('Michael Fabrie', 'Netherlands', 'michael fabrie'),
	('Kevin Isa', 'Argentina', 'isa'),
	('Kevin Isa', 'Argentina', 'kevin isa'),
	('Monday Samuel', 'Nigeria', 'samuel'),
	('Monday Samuel', 'Nigeria', 'monday samuel'),
	('Rory Feely', 'Republic of Ireland', 'rory feely'),
	('Rory Feely', 'Republic of Ireland', 'feely'),
	('George Thomson', 'England', 'george thomson'),
	('George Thomson', 'England', 'thomson'),
	('Leonel Montano', 'Denmark', 'leonel montano'),
	('Leonel Montano', 'Denmark', 'montano'),
	('Ariel Cáceres', 'Chile', 'ariel caceres'),
	('Ariel Cáceres', 'Chile', 'caceres'),
	('Ryan Brennan', 'Republic of Ireland', 'ryan brennan'),
	('Ryan Brennan', 'Republic of Ireland', 'brennan'),
	('Freddie Hinds', 'England', 'hinds'),
	('Freddie Hinds', 'England', 'freddie hinds'),
	('Jonah Fabisch', 'Germany', 'jonah fabisch'),
	('Jonah Fabisch', 'Germany', 'fabisch'),
	('Mésaque Djú', 'Portugal', 'dju'),
	('Mésaque Djú', 'Portugal', 'mesaque dju'),
	('Tobias Carlsson', 'Sweden', 'carlsson'),
	('Tobias Carlsson', 'Sweden', 'tobias carlsson'),
	('Daichi Hayashi', 'Japan', 'daichi hayashi'),
	('Daichi Hayashi', 'Japan', 'hayashi'),
	('José Llovera', 'Venezuela', 'llovera'),
	('José Llovera', 'Venezuela', 'jose llovera'),
	('Park Byung Hyun', 'Korea Republic', 'hyun'),
	('Park Byung Hyun', 'Korea Republic', 'park byung hyun'),
	('Harrison Biggins', 'England', 'biggins'),
	('Harrison Biggins', 'England', 'harrison biggins'),
	('Choi Young Eun', 'Korea Republic', 'eun'),
	('Choi Young Eun', 'Korea Republic', 'choi young eun'),
	('Zhou Yajun', 'China PR', 'yajun'),
	('Zhou Yajun', 'China PR', 'zhou yajun'),
	('Kian Harratt', 'England', 'kian harratt'),
	('Kian Harratt', 'England', 'harratt'),
	('Baba Touré', 'France', 'baba toure'),
	('Baba Touré', 'France', 'toure'),
	('Kluiverth Aguilar', 'Peru', 'aguilar'),
	('Kluiverth Aguilar', 'Peru', 'kluiverth aguilar'),
	('Diaz Wright', 'England', 'diaz wright'),
	('Diaz Wright', 'England', 'wright'),
	('Danny Kane', 'Republic of Ireland', 'kane'),
	('Danny Kane', 'Republic of Ireland', 'danny kane'),
	('Shuhei Kawasaki', 'Japan', 'shuhei kawasaki'),
	('Shuhei Kawasaki', 'Japan', 'kawasaki'),
	('Mahamadou Dembélé', 'France', 'dembele'),
	('Mahamadou Dembélé', 'France', 'mahamadou dembele'),
	('Cem-Tuna Türkmen', 'Turkey', 'turkmen'),
	('Cem-Tuna Türkmen', 'Turkey', 'cemtuna turkmen'),
	('Daniel Cabrera', 'Peru', 'daniel cabrera'),
	('Daniel Cabrera', 'Peru', 'cabrera'),
	('Mohammed Sangare', 'Liberia', 'sangare'),
	('Mohammed Sangare', 'Liberia', 'mohammed sangare'),
	('Cammy MacPherson', 'Scotland', 'cammy macpherson'),
	('Cammy MacPherson', 'Scotland', 'macpherson'),
	('Alessio Carlone', 'Belgium', 'carlone'),
	('Alessio Carlone', 'Belgium', 'alessio carlone'),
	('Daniel Udoh', 'Nigeria', 'daniel udoh'),
	('Daniel Udoh', 'Nigeria', 'udoh'),
	('Lautaro López', 'Argentina', 'lautaro lopez'),
	('Lautaro López', 'Argentina', 'lopez'),
	('Bartłomiej Sielewski', 'Poland', 'sielewski'),
	('Bartłomiej Sielewski', 'Poland', 'bartomiej sielewski'),
	('Mathew Stevens', 'England', 'stevens'),
	('Mathew Stevens', 'England', 'mathew stevens'),
	('Barry McNamee', 'Republic of Ireland', 'mcnamee'),
	('Barry McNamee', 'Republic of Ireland', 'barry mcnamee'),
	('Felix Irorere', 'Germany', 'felix irorere'),
	('Felix Irorere', 'Germany', 'irorere'),
	('Dillon Barnes', 'England', 'dillon barnes'),
	('Dillon Barnes', 'England', 'barnes'),
	('Arkadiusz Pyrka', 'Poland', 'arkadiusz pyrka'),
	('Arkadiusz Pyrka', 'Poland', 'pyrka'),
	('Jader Valencia', 'Colombia', 'valencia'),
	('Jader Valencia', 'Colombia', 'jader valencia'),
	('Abdullah Al Khatib', 'Saudi Arabia', 'abdullah al khatib'),
	('Abdullah Al Khatib', 'Saudi Arabia', 'khatib'),
	('Damian Primel', 'Poland', 'damian primel'),
	('Damian Primel', 'Poland', 'primel'),
	('Maik Nawrocki', 'Poland', 'nawrocki'),
	('Maik Nawrocki', 'Poland', 'maik nawrocki'),
	('Niklas Kastenhofer', 'Germany', 'kastenhofer'),
	('Niklas Kastenhofer', 'Germany', 'niklas kastenhofer'),
	('Murtadha Al Burayh', 'Saudi Arabia', 'murtadha al burayh'),
	('Murtadha Al Burayh', 'Saudi Arabia', 'burayh'),
	('Ozkan Cetiner', 'France', 'ozkan cetiner'),
	('Ozkan Cetiner', 'France', 'cetiner'),
	('Julian von Moos', 'Switzerland', 'julian von moos'),
	('Julian von Moos', 'Switzerland', 'moos'),
	('Mesut Çaytemel', 'Turkey', 'mesut caytemel'),
	('Mesut Çaytemel', 'Turkey', 'caytemel'),
	('Christian Celesia', 'Italy', 'christian celesia'),
	('Christian Celesia', 'Italy', 'celesia'),
	('Benjamin Hvidt', 'Denmark', 'benjamin hvidt'),
	('Benjamin Hvidt', 'Denmark', 'hvidt'),
	('Adrian Laskowski', 'Poland', 'laskowski'),
	('Adrian Laskowski', 'Poland', 'adrian laskowski'),
	('Jakub Wróbel', 'Poland', 'jakub wrobel'),
	('Jakub Wróbel', 'Poland', 'wrobel'),
	('Donaldo Açka', 'Albania', 'acka'),
	('Donaldo Açka', 'Albania', 'donaldo acka'),
	('Leon Bürger', 'Germany', 'burger'),
	('Leon Bürger', 'Germany', 'leon burger'),
	('Ciaron Brown', 'Northern Ireland', 'brown'),
	('Ciaron Brown', 'Northern Ireland', 'ciaron brown'),
	('Robbie McCourt', 'Republic of Ireland', 'mccourt'),
	('Robbie McCourt', 'Republic of Ireland', 'robbie mccourt'),
	('Rodrigo Esteban', 'Spain', 'esteban'),
	('Rodrigo Esteban', 'Spain', 'rodrigo esteban'),
	('Alex Denny', 'England', 'denny'),
	('Alex Denny', 'England', 'alex denny'),
	('Rafał Leszczyński', 'Poland', 'rafa leszczynski'),
	('Rafał Leszczyński', 'Poland', 'leszczynski'),
	('Mateusz Praszelik', 'Poland', 'praszelik'),
	('Mateusz Praszelik', 'Poland', 'mateusz praszelik'),
	('Peter Kioso', 'DR Congo', 'peter kioso'),
	('Peter Kioso', 'DR Congo', 'kioso'),
	('Ryan Cooney', 'England', 'ryan cooney'),
	('Ryan Cooney', 'England', 'cooney'),
	('Abdulsamed Damlu', 'Turkey', 'damlu'),
	('Abdulsamed Damlu', 'Turkey', 'abdulsamed damlu'),
	('Facundo Torres', 'Uruguay', 'torres'),
	('Facundo Torres', 'Uruguay', 'facundo torres'),
	('Oh Hyun Gyu', 'Korea Republic', 'oh hyun gyu'),
	('Oh Hyun Gyu', 'Korea Republic', 'gyu'),
	('Tyrese Sinclair', 'England', 'tyrese sinclair'),
	('Tyrese Sinclair', 'England', 'sinclair'),
	('Saad Al Selouli', 'Saudi Arabia', 'saad al selouli'),
	('Saad Al Selouli', 'Saudi Arabia', 'selouli'),
	('Brandon Servania', 'United States', 'servania'),
	('Brandon Servania', 'United States', 'brandon servania'),
	('Moritz Schulze', 'Germany', 'schulze'),
	('Moritz Schulze', 'Germany', 'moritz schulze'),
	('Dariusz Pawłowski', 'Poland', 'dariusz pawowski'),
	('Dariusz Pawłowski', 'Poland', 'pawowski'),
	('Dion Lopy', 'Senegal', 'lopy'),
	('Dion Lopy', 'Senegal', 'dion lopy'),
	('Josh Davison', 'England', 'davison'),
	('Josh Davison', 'England', 'josh davison'),
	('Yahya Boussakou', 'Netherlands', 'yahya boussakou'),
	('Yahya Boussakou', 'Netherlands', 'boussakou'),
	('Joe Grayson', 'England', 'joe grayson'),
	('Joe Grayson', 'England', 'grayson'),
	('Molina', 'Spain', 'molina'),
	('Mohammed Al Sahli', 'Saudi Arabia', 'mohammed al sahli'),
	('Mohammed Al Sahli', 'Saudi Arabia', 'sahli'),
	('Alvin Jones', 'Trinidad & Tobago', 'alvin jones'),
	('Alvin Jones', 'Trinidad & Tobago', 'jones'),
	('Brandon Domingues', 'France', 'brandon domingues'),
	('Brandon Domingues', 'France', 'domingues'),
	('Nathan Monzango', 'DR Congo', 'monzango'),
	('Nathan Monzango', 'DR Congo', 'nathan monzango'),
	('Charly Jan', 'France', 'charly jan'),
	('Charly Jan', 'France', 'jan'),
	('Gianfranco Facchineri', 'Canada', 'facchineri'),
	('Gianfranco Facchineri', 'Canada', 'gianfranco facchineri'),
	('Elias Damergy', 'Tunisia', 'damergy'),
	('Elias Damergy', 'Tunisia', 'elias damergy'),
	('Katio Landi', 'Italy', 'landi'),
	('Katio Landi', 'Italy', 'katio landi'),
	('Thijs Dallinga', 'Netherlands', 'dallinga'),
	('Thijs Dallinga', 'Netherlands', 'thijs dallinga'),
	('Wahid Faghir', 'Denmark', 'faghir'),
	('Wahid Faghir', 'Denmark', 'wahid faghir'),
	('Ender Aygören', 'Turkey', 'ender aygoren'),
	('Ender Aygören', 'Turkey', 'aygoren'),
	('Dean Clarke', 'Republic of Ireland', 'clarke'),
	('Dean Clarke', 'Republic of Ireland', 'dean clarke'),
	('Jun Nishikawa', 'Japan', 'jun nishikawa'),
	('Jun Nishikawa', 'Japan', 'nishikawa'),
	('Alistair Coote', 'Scotland', 'coote'),
	('Alistair Coote', 'Scotland', 'alistair coote'),
	('Anıl Gözütok', 'Germany', 'gozutok'),
	('Anıl Gözütok', 'Germany', 'anl gozutok'),
	('Iván Bolaño', 'Argentina', 'ivan bolano'),
	('Iván Bolaño', 'Argentina', 'bolano'),
	('Jorge Vieira', 'Portugal', 'jorge vieira'),
	('Jorge Vieira', 'Portugal', 'vieira'),
	('Ovidiu Perianu', 'Romania', 'perianu'),
	('Ovidiu Perianu', 'Romania', 'ovidiu perianu'),
	('Jaber Asiri', 'Saudi Arabia', 'jaber asiri'),
	('Jaber Asiri', 'Saudi Arabia', 'asiri'),
	('Gerardo Bruna', 'Argentina', 'bruna'),
	('Gerardo Bruna', 'Argentina', 'gerardo bruna'),
	('Gastón Pérez', 'Uruguay', 'gaston perez'),
	('Gastón Pérez', 'Uruguay', 'perez'),
	('Robbie Weir', 'Northern Ireland', 'weir'),
	('Robbie Weir', 'Northern Ireland', 'robbie weir'),
	('Georgie Poynton', 'Republic of Ireland', 'georgie poynton'),
	('Georgie Poynton', 'Republic of Ireland', 'poynton'),
	('Jake Brimmer', 'Australia', 'brimmer'),
	('Jake Brimmer', 'Australia', 'jake brimmer'),
	('Gökhan Kardeş', 'Turkey', 'gokhan kardes'),
	('Gökhan Kardeş', 'Turkey', 'kardes'),
	('Noah Awuku', 'Germany', 'awuku'),
	('Noah Awuku', 'Germany', 'noah awuku'),
	('Isaac Christie-Davies', 'Wales', 'christiedavies'),
	('Isaac Christie-Davies', 'Wales', 'isaac christiedavies'),
	('Luke Armstrong', 'England', 'luke armstrong'),
	('Luke Armstrong', 'England', 'armstrong'),
	('Francisco Casanova', 'Uruguay', 'francisco casanova'),
	('Francisco Casanova', 'Uruguay', 'casanova'),
	('Diego Aravena', 'Chile', 'diego aravena'),
	('Diego Aravena', 'Chile', 'aravena'),
	('Muteb Al Mutlaq', 'Saudi Arabia', 'mutlaq'),
	('Muteb Al Mutlaq', 'Saudi Arabia', 'muteb al mutlaq'),
	('Tyler Smith', 'England', 'smith'),
	('Tyler Smith', 'England', 'tyler smith'),
	('Yan', 'Brazil', 'yan'),
	('Diego Bri', 'Spain', 'diego bri'),
	('Diego Bri', 'Spain', 'bri'),
	('Gonzalo Pérez', 'Uruguay', 'gonzalo perez'),
	('Gonzalo Pérez', 'Uruguay', 'perez'),
	('Ahmed Al Sultan', 'Saudi Arabia', 'ahmed al sultan'),
	('Ahmed Al Sultan', 'Saudi Arabia', 'sultan'),
	('Aidan Stone', 'England', 'stone'),
	('Aidan Stone', 'England', 'aidan stone'),
	('Pablo Oro', 'Argentina', 'pablo oro'),
	('Pablo Oro', 'Argentina', 'oro'),
	('Casper Tengstedt', 'Denmark', 'casper tengstedt'),
	('Casper Tengstedt', 'Denmark', 'tengstedt'),
	('Kyowaan Hoshi', 'Japan', 'kyowaan hoshi'),
	('Kyowaan Hoshi', 'Japan', 'hoshi'),
	('Pablo Abel Argañaraz', 'Argentina', 'arganaraz'),
	('Pablo Abel Argañaraz', 'Argentina', 'pablo abel arganaraz'),
	('Alexander Ahl Holmström', 'Sweden', 'holmstrom'),
	('Alexander Ahl Holmström', 'Sweden', 'alexander ahl holmstrom'),
	('Waleed Hezam Al Anazi', 'Saudi Arabia', 'waleed hezam al anazi'),
	('Waleed Hezam Al Anazi', 'Saudi Arabia', 'anazi'),
	('Akinkunmi Amoo', 'Nigeria', 'amoo'),
	('Akinkunmi Amoo', 'Nigeria', 'akinkunmi amoo'),
	('Marcos Montiel', 'Uruguay', 'montiel'),
	('Marcos Montiel', 'Uruguay', 'marcos montiel'),
	('Mohammed Al Hassawi', 'Saudi Arabia', 'mohammed al hassawi'),
	('Mohammed Al Hassawi', 'Saudi Arabia', 'hassawi'),
	('Dylan Fage', 'France', 'fage'),
	('Dylan Fage', 'France', 'dylan fage'),
	('Noah Alexandersson', 'Sweden', 'noah alexandersson'),
	('Noah Alexandersson', 'Sweden', 'alexandersson'),
	('Gonzalo Gómez', 'Argentina', 'gomez'),
	('Gonzalo Gómez', 'Argentina', 'gonzalo gomez'),
	('Soner Dikmen', 'Turkey', 'soner dikmen'),
	('Soner Dikmen', 'Turkey', 'dikmen'),
	('Enzo Cabrera', 'Argentina', 'enzo cabrera'),
	('Enzo Cabrera', 'Argentina', 'cabrera'),
	('Fawaz Al Tryes', 'Saudi Arabia', 'fawaz al tryes'),
	('Fawaz Al Tryes', 'Saudi Arabia', 'tryes'),
	('Bruninho', 'Portugal', 'bruninho'),
	('Christopher Lungoyi', 'Switzerland', 'lungoyi'),
	('Christopher Lungoyi', 'Switzerland', 'christopher lungoyi'),
	('Egzon Kryeziu', 'Slovenia', 'egzon kryeziu'),
	('Egzon Kryeziu', 'Slovenia', 'kryeziu'),
	('Abdulrahman Al Yami', 'Saudi Arabia', 'abdulrahman al yami'),
	('Abdulrahman Al Yami', 'Saudi Arabia', 'yami'),
	('Liam Edwards', 'England', 'edwards'),
	('Liam Edwards', 'England', 'liam edwards'),
	('Mishari Al Qahtani', 'Saudi Arabia', 'qahtani'),
	('Mishari Al Qahtani', 'Saudi Arabia', 'mishari al qahtani'),
	('Jordan Rezabala', 'Ecuador', 'jordan rezabala'),
	('Jordan Rezabala', 'Ecuador', 'rezabala'),
	('Javier Ibarra', 'Mexico', 'ibarra'),
	('Javier Ibarra', 'Mexico', 'javier ibarra'),
	('Josh March', 'England', 'josh march'),
	('Josh March', 'England', 'march'),
	('Enmerson Batalla', 'Colombia', 'batalla'),
	('Enmerson Batalla', 'Colombia', 'enmerson batalla'),
	('Sami Ben Amar', 'Morocco', 'amar'),
	('Sami Ben Amar', 'Morocco', 'sami ben amar'),
	('Godwin Bentil', 'Ghana', 'godwin bentil'),
	('Godwin Bentil', 'Ghana', 'bentil'),
	('Rob Atkinson', 'England', 'atkinson'),
	('Rob Atkinson', 'England', 'rob atkinson'),
	('Wellington Ramírez', 'Ecuador', 'wellington ramirez'),
	('Wellington Ramírez', 'Ecuador', 'ramirez'),
	('Mauricio Isais', 'United States', 'mauricio isais'),
	('Mauricio Isais', 'United States', 'isais'),
	('Teun van Grunsven', 'Netherlands', 'grunsven'),
	('Teun van Grunsven', 'Netherlands', 'teun van grunsven'),
	('Aidan Morris', 'United States', 'morris'),
	('Aidan Morris', 'United States', 'aidan morris'),
	('Brackzon León', 'Peru', 'leon'),
	('Brackzon León', 'Peru', 'brackzon leon'),
	('Fabian Rohner', 'Switzerland', 'fabian rohner'),
	('Fabian Rohner', 'Switzerland', 'rohner'),
	('Jai Ingham', 'New Zealand', 'jai ingham'),
	('Jai Ingham', 'New Zealand', 'ingham'),
	('Peter Gwargis', 'Sweden', 'peter gwargis'),
	('Peter Gwargis', 'Sweden', 'gwargis'),
	('Oliver Antman', 'Finland', 'antman'),
	('Oliver Antman', 'Finland', 'oliver antman'),
	('Nikell Touglo', 'Germany', 'nikell touglo'),
	('Nikell Touglo', 'Germany', 'touglo'),
	('Samuel Renel', 'France', 'samuel renel'),
	('Samuel Renel', 'France', 'renel'),
	('Paul Lewis', 'England', 'lewis'),
	('Paul Lewis', 'England', 'paul lewis'),
	('Dennis Gorka', 'Germany', 'dennis gorka'),
	('Dennis Gorka', 'Germany', 'gorka'),
	('Jop van der Avert', 'Netherlands', 'avert'),
	('Jop van der Avert', 'Netherlands', 'jop van der avert'),
	('Alex Addai', 'England', 'addai'),
	('Alex Addai', 'England', 'alex addai'),
	('Hamdan Al Ruwaili', 'Saudi Arabia', 'hamdan al ruwaili'),
	('Hamdan Al Ruwaili', 'Saudi Arabia', 'ruwaili'),
	('Hassan Al Geed', 'Saudi Arabia', 'geed'),
	('Hassan Al Geed', 'Saudi Arabia', 'hassan al geed'),
	('Astals', 'Spain', 'astals'),
	('Yang Yu', 'China PR', 'yang yu'),
	('Yang Yu', 'China PR', 'yu'),
	('Çağtay Kurukalıp', 'Turkey', 'kurukalp'),
	('Çağtay Kurukalıp', 'Turkey', 'cagtay kurukalp'),
	('Rodrigo Morínigo', 'Paraguay', 'rodrigo morinigo'),
	('Rodrigo Morínigo', 'Paraguay', 'morinigo'),
	('Joachim Carcela-González', 'Belgium', 'carcelagonzalez'),
	('Joachim Carcela-González', 'Belgium', 'joachim carcelagonzalez'),
	('Sebastián Cocimano', 'Argentina', 'sebastian cocimano'),
	('Sebastián Cocimano', 'Argentina', 'cocimano'),
	('Fuchi Honda', 'Japan', 'honda'),
	('Fuchi Honda', 'Japan', 'fuchi honda'),
	('Paul Costea', 'Romania', 'paul costea'),
	('Paul Costea', 'Romania', 'costea'),
	('Michael Steinwender', 'Austria', 'michael steinwender'),
	('Michael Steinwender', 'Austria', 'steinwender'),
	('Ismael Omar', 'Saudi Arabia', 'omar'),
	('Ismael Omar', 'Saudi Arabia', 'ismael omar'),
	('Alex Purver', 'England', 'alex purver'),
	('Alex Purver', 'England', 'purver'),
	('Alexander Ammitzbøll', 'Denmark', 'alexander ammitzbll'),
	('Alexander Ammitzbøll', 'Denmark', 'ammitzbll'),
	('Morgan Boyes', 'Wales', 'morgan boyes'),
	('Morgan Boyes', 'Wales', 'boyes'),
	('Marcos Duré', 'Paraguay', 'dure'),
	('Marcos Duré', 'Paraguay', 'marcos dure'),
	('Aaron McCarey', 'Republic of Ireland', 'aaron mccarey'),
	('Aaron McCarey', 'Republic of Ireland', 'mccarey'),
	('Ryotaro Araki', 'Japan', 'araki'),
	('Ryotaro Araki', 'Japan', 'ryotaro araki'),
	('Bugra Temel', 'Turkey', 'temel'),
	('Bugra Temel', 'Turkey', 'bugra temel'),
	('Cory Galvin', 'Republic of Ireland', 'galvin'),
	('Cory Galvin', 'Republic of Ireland', 'cory galvin'),
	('Magnus S. Lundal', 'Norway', 'lundal'),
	('Magnus S. Lundal', 'Norway', 'magnus s lundal'),
	('Lukas Fadinger', 'Austria', 'lukas fadinger'),
	('Lukas Fadinger', 'Austria', 'fadinger'),
	('Omer Hanin', 'Israel', 'hanin'),
	('Omer Hanin', 'Israel', 'omer hanin'),
	('Giacomo Ricci', 'Italy', 'ricci'),
	('Giacomo Ricci', 'Italy', 'giacomo ricci'),
	('Josh Eccles', 'England', 'josh eccles'),
	('Josh Eccles', 'England', 'eccles'),
	('Shunta Awaka', 'Japan', 'shunta awaka'),
	('Shunta Awaka', 'Japan', 'awaka'),
	('Alejandro Samudio', 'Paraguay', 'alejandro samudio'),
	('Alejandro Samudio', 'Paraguay', 'samudio'),
	('Aymane Mourid', 'Morocco', 'aymane mourid'),
	('Aymane Mourid', 'Morocco', 'mourid'),
	('Carlos Pando', 'Peru', 'pando'),
	('Carlos Pando', 'Peru', 'carlos pando'),
	('Rémy Vita', 'France', 'remy vita'),
	('Rémy Vita', 'France', 'vita'),
	('George Ray', 'Wales', 'george ray'),
	('George Ray', 'Wales', 'ray'),
	('Lewis Butroid', 'England', 'butroid'),
	('Lewis Butroid', 'England', 'lewis butroid'),
	('Dean Campbell', 'Scotland', 'dean campbell'),
	('Dean Campbell', 'Scotland', 'campbell'),
	('Dickson Abiama', 'Nigeria', 'dickson abiama'),
	('Dickson Abiama', 'Nigeria', 'abiama'),
	('Ryan Ponti', 'France', 'ryan ponti'),
	('Ryan Ponti', 'France', 'ponti'),
	('Juan Vieyra', 'Argentina', 'juan vieyra'),
	('Juan Vieyra', 'Argentina', 'vieyra')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';