INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Henrich Ravas', 'Slovakia', 'player'),
	('Jack Armer', 'Scotland', 'player'),
	('Park Jae Woo', 'Korea Republic', 'player'),
	('Theo Rochat', 'Switzerland', 'player'),
	('Mariusz Kaczmarek', 'Poland', 'player'),
	('Mawlanyaz Dilmurat', 'China PR', 'player'),
	('Chen Wei', 'China PR', 'player'),
	('Zach Jeacock', 'England', 'player'),
	('Alexis André Jr', 'Morocco', 'player'),
	('Gan Chao', 'China PR', 'player'),
	('Bruno Rivas', 'Bolivia', 'player'),
	('Emmanuel Longelo', 'England', 'player'),
	('Aaron Anderson', 'Australia', 'player'),
	('Billy Johnson', 'England', 'player'),
	('Jack Burroughs', 'Scotland', 'player'),
	('Matty Smith', 'Scotland', 'player'),
	('Kamil Broda', 'Poland', 'player'),
	('Song Zhiwei', 'China PR', 'player'),
	('Branden Horton', 'England', 'player'),
	('Adam Kelsey', 'England', 'player'),
	('Nicholas Milanovic', 'Australia', 'player'),
	('Owen Gallacher', 'Scotland', 'player'),
	('Kleiber Palomino', 'Venezuela', 'player'),
	('Luis Lawrie-Lattanzio', 'Australia', 'player'),
	('Marcelo Medel', 'Chile', 'player'),
	('Piero Antón', 'Peru', 'player'),
	('Melvin Minter', 'England', 'player'),
	('Harry Ransom', 'England', 'player'),
	('Denis Ciofu', 'Romania', 'player'),
	('Federico Brancolini', 'Italy', 'player'),
	('Agustín Morales', 'Uruguay', 'player'),
	('Zhao Jianfei', 'China PR', 'player'),
	('Franco Rivasseau', 'Argentina', 'player'),
	('Ethan Walker', 'England', 'player'),
	('Cristian Aguirre', 'Chile', 'player'),
	('Odysseus Alfa', 'Nigeria', 'player'),
	('Jason McClelland', 'Republic of Ireland', 'player'),
	('Jack Diamond', 'England', 'player'),
	('Calvin Ramsay', 'Scotland', 'player'),
	('Ionuț Mitran', 'Romania', 'player'),
	('Abdullah Al Meqran', 'Saudi Arabia', 'player'),
	('Matti Peltola', 'Finland', 'player'),
	('Rhys-James Fenlon', 'England', 'player'),
	('Muhannad Al Shudukhi', 'Saudi Arabia', 'player'),
	('Marco Tilio', 'Australia', 'player'),
	('Saul Shotton', 'England', 'player'),
	('Wang Fei', 'China PR', 'player'),
	('Danny Walker-Rice', 'England', 'player'),
	('Yasser Sahfi', 'Saudi Arabia', 'player'),
	('George Nugent', 'England', 'player'),
	('Mateusz Wyjadłowski', 'Poland', 'player'),
	('Peder Meen Johansen', 'Norway', 'player'),
	('Liu Jiashen', 'China PR', 'player'),
	('Oliver Dovin', 'Sweden', 'player'),
	('Jack Sanders', 'England', 'player'),
	('Nicolas P. Jenssen', 'Norway', 'player'),
	('Dominik Meisel', 'Germany', 'player'),
	('Bradley James', 'England', 'player'),
	('Tomasz Bała', 'Poland', 'player'),
	('Adrian Moescu', 'Romania', 'player'),
	('Bobby Jones', 'Republic of Ireland', 'player'),
	('Jake McGuire', 'United States', 'player'),
	('Imari Samuels', 'England', 'player'),
	('MacKenzie O''Neill', 'Northern Ireland', 'player'),
	('Marius Ulla', 'Norway', 'player'),
	('Gonzalo Tapia', 'Chile', 'player'),
	('Tyrese Fornah', 'England', 'player'),
	('Cristóbal Finch', 'Chile', 'player'),
	('Julian Vazquez', 'Mexico', 'player'),
	('Adam Sørensen', 'Denmark', 'player'),
	('Abdallah Basit', 'Ghana', 'player'),
	('Zaid Al Bawardi', 'Saudi Arabia', 'player'),
	('Matty Wolfe', 'England', 'player'),
	('Jordan Courtney-Perkins', 'Australia', 'player'),
	('Harry Ditchfield', 'England', 'player'),
	('Víctor Abrego', 'Bolivia', 'player'),
	('Julio Recoba', 'Uruguay', 'player'),
	('Kai Trewin', 'Australia', 'player'),
	('Joe Piggott', 'England', 'player'),
	('Doğan Alemdar', 'Turkey', 'player'),
	('Jordi Swibel', 'Australia', 'player'),
	('Nils Bertilsson', 'Sweden', 'player'),
	('Eren Kinali', 'England', 'player'),
	('Liam Shaw', 'England', 'player'),
	('David Jovanović', 'Switzerland', 'player'),
	('Tarik Ibrahimagić', 'Denmark', 'player'),
	('Walter Gaona', 'Paraguay', 'player'),
	('Krzysztof Bąkowski', 'Poland', 'player'),
	('Xing Yu', 'China PR', 'player'),
	('Christian Vestergaard', 'Denmark', 'player'),
	('Corey Panter', 'England', 'player'),
	('Marc Augé', 'Germany', 'player'),
	('Mikal Berg Kvinge', 'Norway', 'player'),
	('Nicolás Forastiero', 'Argentina', 'player'),
	('Ross Munro', 'Scotland', 'player'),
	('Gabriel Popovic', 'Australia', 'player'),
	('Stefan Kiefer', 'Germany', 'player'),
	('Trym Sølvberg Ur', 'Norway', 'player'),
	('Oliver Tølbøll Rimmen', 'Denmark', 'player'),
	('Karl Leth', 'Denmark', 'player'),
	('Jack Stevens', 'England', 'player'),
	('Adam Parkes', 'England', 'player'),
	('Dan Hawkins', 'Wales', 'player'),
	('Jamie Fielding', 'England', 'player'),
	('Mark Marleku', 'Kosovo', 'player'),
	('Axel Torres', 'Mexico', 'player'),
	('Alistair Taylor', 'Scotland', 'player'),
	('Jake Burton', 'England', 'player'),
	('Sondre Eide', 'Norway', 'player'),
	('John Russell', 'Republic of Ireland', 'player'),
	('Kacper Trelowski', 'Poland', 'player'),
	('Luo Shipeng', 'China PR', 'player'),
	('Park Kyung Bae', 'Korea Republic', 'player'),
	('Jack de Vries', 'United States', 'player'),
	('Jakub Bieroński', 'Poland', 'player'),
	('Michał Rostkowski', 'Poland', 'player'),
	('Lewis Brunt', 'England', 'player'),
	('Ollie Battersby', 'England', 'player'),
	('Karabo Molefe', 'South Africa', 'player'),
	('Renny Folleco', 'Ecuador', 'player'),
	('Zain Walker', 'England', 'player'),
	('James Dodd', 'England', 'player'),
	('Iván Acero', 'Mexico', 'player'),
	('Jordan Dyer', 'England', 'player'),
	('Ross Graham', 'Scotland', 'player'),
	('Basil Al Bahrani', 'Saudi Arabia', 'player'),
	('Marcus Hannesbo', 'Denmark', 'player'),
	('Sergio Núñez', 'Uruguay', 'player'),
	('Dong Honglin', 'China PR', 'player'),
	('Dawson Devoy', 'Republic of Ireland', 'player'),
	('Kacper Smoliński', 'Poland', 'player'),
	('Dean Walsh', 'Republic of Ireland', 'player'),
	('Martin Rennie', 'Scotland', 'player'),
	('Erik McCue', 'Sweden', 'player'),
	('Joe Hancott', 'England', 'player'),
	('Michał Rakowiecki', 'Poland', 'player'),
	('Joe Robbins', 'England', 'player'),
	('Nikola Curcija', 'Canada', 'player'),
	('Jose Andre Cozma', 'Romania', 'player'),
	('Michael Nelson', 'United States', 'player'),
	('Gary Maley', 'Scotland', 'player'),
	('Tomás Canteros', 'Argentina', 'player'),
	('Oktay Ozkara', 'Romania', 'player'),
	('So Nishikawa', 'Japan', 'player'),
	('Andreas Gülstorff', 'Denmark', 'player'),
	('Lukas Schneller', 'Germany', 'player'),
	('Florinel Sandu', 'Romania', 'player'),
	('Furkan Bekleviç', 'Turkey', 'player'),
	('Alex Fojtíček', 'Slovakia', 'player'),
	('Ask Tjærandsen-Skau', 'Norway', 'player'),
	('Lucas Maus', 'Belgium', 'player'),
	('Julian Hermann', 'Switzerland', 'player'),
	('Zhao Shi', 'China PR', 'player'),
	('Filip Laskowski', 'Poland', 'player'),
	('Daniel Trickett-Smith', 'England', 'player'),
	('Eryk Mirus', 'Poland', 'player'),
	('Alexander Kogler', 'Austria', 'player'),
	('Kyran Lofthouse', 'England', 'player'),
	('Sean Quinn', 'Republic of Ireland', 'player'),
	('Mateusz Dudek', 'Poland', 'player'),
	('Emilian Metu', 'Austria', 'player'),
	('Denzil Fernandes', 'Republic of Ireland', 'player'),
	('Kacper Sadłocha', 'Poland', 'player'),
	('Dagur Dan Þór­halls­son', 'Iceland', 'player'),
	('Mao Haoyu', 'China PR', 'player'),
	('Nathan Woodthorpe', 'England', 'player'),
	('Stefano Piccinini', 'Italy', 'player'),
	('Jevan Anderson', 'Scotland', 'player'),
	('Kevin Paredes', 'United States', 'player'),
	('Jayden Campbell', 'England', 'player'),
	('Kliver Moreno', 'Colombia', 'player'),
	('Daniel Phillips', 'England', 'player'),
	('Meshal Sibyani', 'Saudi Arabia', 'player'),
	('Marco Ramkilde', 'Denmark', 'player'),
	('Edson López', 'Peru', 'player'),
	('Kyron Gordon', 'England', 'player'),
	('Alban Ajdini', 'Kosovo', 'player'),
	('Finn Cousin-Dawson', 'England', 'player'),
	('Chris Garcia', 'United States', 'player'),
	('Simen Vidtun Nilsen', 'Norway', 'player'),
	('Gianluca Bucci', 'England', 'player'),
	('Moudi Najjar', 'Australia', 'player'),
	('Will Lancaster', 'England', 'player'),
	('William Pacho', 'Ecuador', 'player'),
	('Josh Lundstram', 'England', 'player'),
	('Andrei Mirică', 'Romania', 'player'),
	('Maki Petratos', 'Australia', 'player'),
	('Ever Urrutia', 'Venezuela', 'player'),
	('Alexandru Chilili', 'Romania', 'player'),
	('Feng Boyuan', 'China PR', 'player'),
	('Dakota Ochsenham', 'Australia', 'player'),
	('Florent Hoti', 'Kosovo', 'player'),
	('Momodou Touray', 'Wales', 'player'),
	('Reegan Mimnaugh', 'Scotland', 'player'),
	('Ashley Maynard-Brewer', 'Australia', 'player'),
	('Leo Donnellan', 'Republic of Ireland', 'player'),
	('Alexis Martial', 'France', 'player'),
	('Anthony Patterson', 'England', 'player'),
	('Claudio Fraga', 'Venezuela', 'player'),
	('Filip Panjeskovic', 'Denmark', 'player'),
	('Wilver Jimenéz', 'Venezuela', 'player'),
	('Diego Guillen', 'Venezuela', 'player'),
	('Adan Abadala Hussein', 'Norway', 'player'),
	('Mohammad Ahmadi', 'Sweden', 'player'),
	('Mansour Al Muwallad', 'Saudi Arabia', 'player'),
	('Casper Terho', 'Finland', 'player'),
	('Rodrigo Orihuela', 'Bolivia', 'player'),
	('Jeremi Escate', 'Peru', 'player'),
	('Callum Hawkins', 'England', 'player'),
	('Jordan Bender', 'United States', 'player'),
	('Albert Grønbæk', 'Denmark', 'player'),
	('Li Guanxi', 'China PR', 'player'),
	('Meshari Sanyor', 'Saudi Arabia', 'player'),
	('Valentin Borcea', 'Romania', 'player'),
	('Thomas Hallstensen', 'Norway', 'player'),
	('Kim Min Gyu', 'Korea Republic', 'player'),
	('Dominik Smykowski', 'Poland', 'player'),
	('Sebastián Cavero', 'Peru', 'player'),
	('Greg Ranjitsingh', 'Trinidad & Tobago', 'player'),
	('Bruno Barticciotto', 'Chile', 'player'),
	('Jack Currie', 'England', 'player'),
	('Carlos Arrua', 'Paraguay', 'player'),
	('Mads Fagerli Halsøy', 'Norway', 'player'),
	('Freddie Price', 'England', 'player'),
	('David Norman Jr.', 'Canada', 'player'),
	('Zhang Junzhe', 'China PR', 'player'),
	('Aleksander B. Stenseth', 'Norway', 'player'),
	('Víctor Valdez', 'Ecuador', 'player'),
	('Jack Simmons', 'Australia', 'player'),
	('Cameron Antwi', 'England', 'player'),
	('Kyle Joseph', 'Scotland', 'player'),
	('Xu Wu', 'China PR', 'player'),
	('Mohsen Al Hadhderi', 'Saudi Arabia', 'player'),
	('Teddy Bartouche', 'France', 'player'),
	('Joshua Varga', 'Australia', 'player'),
	('Brandon Taylor', 'England', 'player'),
	('Martín Parra', 'Chile', 'player'),
	('Liam Smyth', 'Northern Ireland', 'player'),
	('Patrick Langlois', 'Australia', 'player'),
	('Niklas Jeck', 'Germany', 'player'),
	('Adan George', 'England', 'player'),
	('Norbert Wojtuszek', 'Poland', 'player'),
	('Jake Hackett', 'England', 'player'),
	('Giovanni Davis', 'Chile', 'player'),
	('Henry Woods', 'England', 'player'),
	('Hampus Holgersson', 'Sweden', 'player'),
	('Andreas Bredahl', 'Denmark', 'player'),
	('Edgaras Dubickas', 'Lithuania', 'player'),
	('Jiang Shenglong', 'China PR', 'player'),
	('Kamil Kruk', 'Poland', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Henrich Ravas', 'Slovakia', 'ravas'),
	('Henrich Ravas', 'Slovakia', 'henrich ravas'),
	('Jack Armer', 'Scotland', 'jack armer'),
	('Jack Armer', 'Scotland', 'armer'),
	('Park Jae Woo', 'Korea Republic', 'woo'),
	('Park Jae Woo', 'Korea Republic', 'park jae woo'),
	('Theo Rochat', 'Switzerland', 'rochat'),
	('Theo Rochat', 'Switzerland', 'theo rochat'),
	('Mariusz Kaczmarek', 'Poland', 'mariusz kaczmarek'),
	('Mariusz Kaczmarek', 'Poland', 'kaczmarek'),
	('Mawlanyaz Dilmurat', 'China PR', 'mawlanyaz dilmurat'),
	('Mawlanyaz Dilmurat', 'China PR', 'dilmurat'),
	('Chen Wei', 'China PR', 'chen wei'),
	('Chen Wei', 'China PR', 'wei'),
	('Zach Jeacock', 'England', 'zach jeacock'),
	('Zach Jeacock', 'England', 'jeacock'),
	('Alexis André Jr', 'Morocco', 'jr'),
	('Alexis André Jr', 'Morocco', 'alexis andre jr'),
	('Gan Chao', 'China PR', 'chao'),
	('Gan Chao', 'China PR', 'gan chao'),
	('Bruno Rivas', 'Bolivia', 'rivas'),
	('Bruno Rivas', 'Bolivia', 'bruno rivas'),
	('Emmanuel Longelo', 'England', 'emmanuel longelo'),
	('Emmanuel Longelo', 'England', 'longelo'),
	('Aaron Anderson', 'Australia', 'anderson'),
	('Aaron Anderson', 'Australia', 'aaron anderson'),
	('Billy Johnson', 'England', 'johnson'),
	('Billy Johnson', 'England', 'billy johnson'),
	('Jack Burroughs', 'Scotland', 'jack burroughs'),
	('Jack Burroughs', 'Scotland', 'burroughs'),
	('Matty Smith', 'Scotland', 'matty smith'),
	('Matty Smith', 'Scotland', 'smith'),
	('Kamil Broda', 'Poland', 'kamil broda'),
	('Kamil Broda', 'Poland', 'broda'),
	('Song Zhiwei', 'China PR', 'zhiwei'),
	('Song Zhiwei', 'China PR', 'song zhiwei'),
	('Branden Horton', 'England', 'branden horton'),
	('Branden Horton', 'England', 'horton'),
	('Adam Kelsey', 'England', 'adam kelsey'),
	('Adam Kelsey', 'England', 'kelsey'),
	('Nicholas Milanovic', 'Australia', 'milanovic'),
	('Nicholas Milanovic', 'Australia', 'nicholas milanovic'),
	('Owen Gallacher', 'Scotland', 'gallacher'),
	('Owen Gallacher', 'Scotland', 'owen gallacher'),
	('Kleiber Palomino', 'Venezuela', 'palomino'),
	('Kleiber Palomino', 'Venezuela', 'kleiber palomino'),
	('Luis Lawrie-Lattanzio', 'Australia', 'luis lawrielattanzio'),
	('Luis Lawrie-Lattanzio', 'Australia', 'lawrielattanzio'),
	('Marcelo Medel', 'Chile', 'medel'),
	('Marcelo Medel', 'Chile', 'marcelo medel'),
	('Piero Antón', 'Peru', 'piero anton'),
	('Piero Antón', 'Peru', 'anton'),
	('Melvin Minter', 'England', 'minter'),
	('Melvin Minter', 'England', 'melvin minter'),
	('Harry Ransom', 'England', 'harry ransom'),
	('Harry Ransom', 'England', 'ransom'),
	('Denis Ciofu', 'Romania', 'denis ciofu'),
	('Denis Ciofu', 'Romania', 'ciofu'),
	('Federico Brancolini', 'Italy', 'federico brancolini'),
	('Federico Brancolini', 'Italy', 'brancolini'),
	('Agustín Morales', 'Uruguay', 'agustin morales'),
	('Agustín Morales', 'Uruguay', 'morales'),
	('Zhao Jianfei', 'China PR', 'jianfei'),
	('Zhao Jianfei', 'China PR', 'zhao jianfei'),
	('Franco Rivasseau', 'Argentina', 'rivasseau'),
	('Franco Rivasseau', 'Argentina', 'franco rivasseau'),
	('Ethan Walker', 'England', 'ethan walker'),
	('Ethan Walker', 'England', 'walker'),
	('Cristian Aguirre', 'Chile', 'aguirre'),
	('Cristian Aguirre', 'Chile', 'cristian aguirre'),
	('Odysseus Alfa', 'Nigeria', 'alfa'),
	('Odysseus Alfa', 'Nigeria', 'odysseus alfa'),
	('Jason McClelland', 'Republic of Ireland', 'mcclelland'),
	('Jason McClelland', 'Republic of Ireland', 'jason mcclelland'),
	('Jack Diamond', 'England', 'diamond'),
	('Jack Diamond', 'England', 'jack diamond'),
	('Calvin Ramsay', 'Scotland', 'ramsay'),
	('Calvin Ramsay', 'Scotland', 'calvin ramsay'),
	('Ionuț Mitran', 'Romania', 'ionut mitran'),
	('Ionuț Mitran', 'Romania', 'mitran'),
	('Abdullah Al Meqran', 'Saudi Arabia', 'meqran'),
	('Abdullah Al Meqran', 'Saudi Arabia', 'abdullah al meqran'),
	('Matti Peltola', 'Finland', 'peltola'),
	('Matti Peltola', 'Finland', 'matti peltola'),
	('Rhys-James Fenlon', 'England', 'fenlon'),
	('Rhys-James Fenlon', 'England', 'rhysjames fenlon'),
	('Muhannad Al Shudukhi', 'Saudi Arabia', 'shudukhi'),
	('Muhannad Al Shudukhi', 'Saudi Arabia', 'muhannad al shudukhi'),
	('Marco Tilio', 'Australia', 'tilio'),
	('Marco Tilio', 'Australia', 'marco tilio'),
	('Saul Shotton', 'England', 'shotton'),
	('Saul Shotton', 'England', 'saul shotton'),
	('Wang Fei', 'China PR', 'fei'),
	('Wang Fei', 'China PR', 'wang fei'),
	('Danny Walker-Rice', 'England', 'danny walkerrice'),
	('Danny Walker-Rice', 'England', 'walkerrice'),
	('Yasser Sahfi', 'Saudi Arabia', 'sahfi'),
	('Yasser Sahfi', 'Saudi Arabia', 'yasser sahfi'),
	('George Nugent', 'England', 'george nugent'),
	('George Nugent', 'England', 'nugent'),
	('Mateusz Wyjadłowski', 'Poland', 'wyjadowski'),
	('Mateusz Wyjadłowski', 'Poland', 'mateusz wyjadowski'),
	('Peder Meen Johansen', 'Norway', 'johansen'),
	('Peder Meen Johansen', 'Norway', 'peder meen johansen'),
	('Liu Jiashen', 'China PR', 'jiashen'),
	('Liu Jiashen', 'China PR', 'liu jiashen'),
	('Oliver Dovin', 'Sweden', 'dovin'),
	('Oliver Dovin', 'Sweden', 'oliver dovin'),
	('Jack Sanders', 'England', 'sanders'),
	('Jack Sanders', 'England', 'jack sanders'),
	('Nicolas P. Jenssen', 'Norway', 'nicolas p jenssen'),
	('Nicolas P. Jenssen', 'Norway', 'jenssen'),
	('Dominik Meisel', 'Germany', 'meisel'),
	('Dominik Meisel', 'Germany', 'dominik meisel'),
	('Bradley James', 'England', 'bradley james'),
	('Bradley James', 'England', 'james'),
	('Tomasz Bała', 'Poland', 'baa'),
	('Tomasz Bała', 'Poland', 'tomasz baa'),
	('Adrian Moescu', 'Romania', 'moescu'),
	('Adrian Moescu', 'Romania', 'adrian moescu'),
	('Bobby Jones', 'Republic of Ireland', 'bobby jones'),
	('Bobby Jones', 'Republic of Ireland', 'jones'),
	('Jake McGuire', 'United States', 'mcguire'),
	('Jake McGuire', 'United States', 'jake mcguire'),
	('Imari Samuels', 'England', 'imari samuels'),
	('Imari Samuels', 'England', 'samuels'),
	('MacKenzie O''Neill', 'Northern Ireland', 'mackenzie oneill'),
	('MacKenzie O''Neill', 'Northern Ireland', 'oneill'),
	('Marius Ulla', 'Norway', 'ulla'),
	('Marius Ulla', 'Norway', 'marius ulla'),
	('Gonzalo Tapia', 'Chile', 'gonzalo tapia'),
	('Gonzalo Tapia', 'Chile', 'tapia'),
	('Tyrese Fornah', 'England', 'tyrese fornah'),
	('Tyrese Fornah', 'England', 'fornah'),
	('Cristóbal Finch', 'Chile', 'finch'),
	('Cristóbal Finch', 'Chile', 'cristobal finch'),
	('Julian Vazquez', 'Mexico', 'vazquez'),
	('Julian Vazquez', 'Mexico', 'julian vazquez'),
	('Adam Sørensen', 'Denmark', 'srensen'),
	('Adam Sørensen', 'Denmark', 'adam srensen'),
	('Abdallah Basit', 'Ghana', 'basit'),
	('Abdallah Basit', 'Ghana', 'abdallah basit'),
	('Zaid Al Bawardi', 'Saudi Arabia', 'bawardi'),
	('Zaid Al Bawardi', 'Saudi Arabia', 'zaid al bawardi'),
	('Matty Wolfe', 'England', 'wolfe'),
	('Matty Wolfe', 'England', 'matty wolfe'),
	('Jordan Courtney-Perkins', 'Australia', 'jordan courtneyperkins'),
	('Jordan Courtney-Perkins', 'Australia', 'courtneyperkins'),
	('Harry Ditchfield', 'England', 'ditchfield'),
	('Harry Ditchfield', 'England', 'harry ditchfield'),
	('Víctor Abrego', 'Bolivia', 'abrego'),
	('Víctor Abrego', 'Bolivia', 'victor abrego'),
	('Julio Recoba', 'Uruguay', 'recoba'),
	('Julio Recoba', 'Uruguay', 'julio recoba'),
	('Kai Trewin', 'Australia', 'kai trewin'),
	('Kai Trewin', 'Australia', 'trewin'),
	('Joe Piggott', 'England', 'piggott'),
	('Joe Piggott', 'England', 'joe piggott'),
	('Doğan Alemdar', 'Turkey', 'alemdar'),
	('Doğan Alemdar', 'Turkey', 'dogan alemdar'),
	('Jordi Swibel', 'Australia', 'jordi swibel'),
	('Jordi Swibel', 'Australia', 'swibel'),
	('Nils Bertilsson', 'Sweden', 'nils bertilsson'),
	('Nils Bertilsson', 'Sweden', 'bertilsson'),
	('Eren Kinali', 'England', 'kinali'),
	('Eren Kinali', 'England', 'eren kinali'),
	('Liam Shaw', 'England', 'liam shaw'),
	('Liam Shaw', 'England', 'shaw'),
	('David Jovanović', 'Switzerland', 'david jovanovic'),
	('David Jovanović', 'Switzerland', 'jovanovic'),
	('Tarik Ibrahimagić', 'Denmark', 'tarik ibrahimagic'),
	('Tarik Ibrahimagić', 'Denmark', 'ibrahimagic'),
	('Walter Gaona', 'Paraguay', 'walter gaona'),
	('Walter Gaona', 'Paraguay', 'gaona'),
	('Krzysztof Bąkowski', 'Poland', 'krzysztof bakowski'),
	('Krzysztof Bąkowski', 'Poland', 'bakowski'),
	('Xing Yu', 'China PR', 'xing yu'),
	('Xing Yu', 'China PR', 'yu'),
	('Christian Vestergaard', 'Denmark', 'christian vestergaard'),
	('Christian Vestergaard', 'Denmark', 'vestergaard'),
	('Corey Panter', 'England', 'corey panter'),
	('Corey Panter', 'England', 'panter'),
	('Marc Augé', 'Germany', 'marc auge'),
	('Marc Augé', 'Germany', 'auge'),
	('Mikal Berg Kvinge', 'Norway', 'mikal berg kvinge'),
	('Mikal Berg Kvinge', 'Norway', 'kvinge'),
	('Nicolás Forastiero', 'Argentina', 'forastiero'),
	('Nicolás Forastiero', 'Argentina', 'nicolas forastiero'),
	('Ross Munro', 'Scotland', 'munro'),
	('Ross Munro', 'Scotland', 'ross munro'),
	('Gabriel Popovic', 'Australia', 'popovic'),
	('Gabriel Popovic', 'Australia', 'gabriel popovic'),
	('Stefan Kiefer', 'Germany', 'kiefer'),
	('Stefan Kiefer', 'Germany', 'stefan kiefer'),
	('Trym Sølvberg Ur', 'Norway', 'trym slvberg ur'),
	('Trym Sølvberg Ur', 'Norway', 'ur'),
	('Oliver Tølbøll Rimmen', 'Denmark', 'oliver tlbll rimmen'),
	('Oliver Tølbøll Rimmen', 'Denmark', 'rimmen'),
	('Karl Leth', 'Denmark', 'karl leth'),
	('Karl Leth', 'Denmark', 'leth'),
	('Jack Stevens', 'England', 'stevens'),
	('Jack Stevens', 'England', 'jack stevens'),
	('Adam Parkes', 'England', 'adam parkes'),
	('Adam Parkes', 'England', 'parkes'),
	('Dan Hawkins', 'Wales', 'hawkins'),
	('Dan Hawkins', 'Wales', 'dan hawkins'),
	('Jamie Fielding', 'England', 'jamie fielding'),
	('Jamie Fielding', 'England', 'fielding'),
	('Mark Marleku', 'Kosovo', 'mark marleku'),
	('Mark Marleku', 'Kosovo', 'marleku'),
	('Axel Torres', 'Mexico', 'torres'),
	('Axel Torres', 'Mexico', 'axel torres'),
	('Alistair Taylor', 'Scotland', 'taylor'),
	('Alistair Taylor', 'Scotland', 'alistair taylor'),
	('Jake Burton', 'England', 'burton'),
	('Jake Burton', 'England', 'jake burton'),
	('Sondre Eide', 'Norway', 'sondre eide'),
	('Sondre Eide', 'Norway', 'eide'),
	('John Russell', 'Republic of Ireland', 'russell'),
	('John Russell', 'Republic of Ireland', 'john russell'),
	('Kacper Trelowski', 'Poland', 'trelowski'),
	('Kacper Trelowski', 'Poland', 'kacper trelowski'),
	('Luo Shipeng', 'China PR', 'shipeng'),
	('Luo Shipeng', 'China PR', 'luo shipeng'),
	('Park Kyung Bae', 'Korea Republic', 'bae'),
	('Park Kyung Bae', 'Korea Republic', 'park kyung bae'),
	('Jack de Vries', 'United States', 'jack de vries'),
	('Jack de Vries', 'United States', 'vries'),
	('Jakub Bieroński', 'Poland', 'bieronski'),
	('Jakub Bieroński', 'Poland', 'jakub bieronski'),
	('Michał Rostkowski', 'Poland', 'micha rostkowski'),
	('Michał Rostkowski', 'Poland', 'rostkowski'),
	('Lewis Brunt', 'England', 'brunt'),
	('Lewis Brunt', 'England', 'lewis brunt'),
	('Ollie Battersby', 'England', 'ollie battersby'),
	('Ollie Battersby', 'England', 'battersby'),
	('Karabo Molefe', 'South Africa', 'karabo molefe'),
	('Karabo Molefe', 'South Africa', 'molefe'),
	('Renny Folleco', 'Ecuador', 'folleco'),
	('Renny Folleco', 'Ecuador', 'renny folleco'),
	('Zain Walker', 'England', 'zain walker'),
	('Zain Walker', 'England', 'walker'),
	('James Dodd', 'England', 'dodd'),
	('James Dodd', 'England', 'james dodd'),
	('Iván Acero', 'Mexico', 'acero'),
	('Iván Acero', 'Mexico', 'ivan acero'),
	('Jordan Dyer', 'England', 'dyer'),
	('Jordan Dyer', 'England', 'jordan dyer'),
	('Ross Graham', 'Scotland', 'ross graham'),
	('Ross Graham', 'Scotland', 'graham'),
	('Basil Al Bahrani', 'Saudi Arabia', 'bahrani'),
	('Basil Al Bahrani', 'Saudi Arabia', 'basil al bahrani'),
	('Marcus Hannesbo', 'Denmark', 'marcus hannesbo'),
	('Marcus Hannesbo', 'Denmark', 'hannesbo'),
	('Sergio Núñez', 'Uruguay', 'sergio nunez'),
	('Sergio Núñez', 'Uruguay', 'nunez'),
	('Dong Honglin', 'China PR', 'dong honglin'),
	('Dong Honglin', 'China PR', 'honglin'),
	('Dawson Devoy', 'Republic of Ireland', 'dawson devoy'),
	('Dawson Devoy', 'Republic of Ireland', 'devoy'),
	('Kacper Smoliński', 'Poland', 'kacper smolinski'),
	('Kacper Smoliński', 'Poland', 'smolinski'),
	('Dean Walsh', 'Republic of Ireland', 'walsh'),
	('Dean Walsh', 'Republic of Ireland', 'dean walsh'),
	('Martin Rennie', 'Scotland', 'martin rennie'),
	('Martin Rennie', 'Scotland', 'rennie'),
	('Erik McCue', 'Sweden', 'erik mccue'),
	('Erik McCue', 'Sweden', 'mccue'),
	('Joe Hancott', 'England', 'hancott'),
	('Joe Hancott', 'England', 'joe hancott'),
	('Michał Rakowiecki', 'Poland', 'rakowiecki'),
	('Michał Rakowiecki', 'Poland', 'micha rakowiecki'),
	('Joe Robbins', 'England', 'joe robbins'),
	('Joe Robbins', 'England', 'robbins'),
	('Nikola Curcija', 'Canada', 'nikola curcija'),
	('Nikola Curcija', 'Canada', 'curcija'),
	('Jose Andre Cozma', 'Romania', 'jose andre cozma'),
	('Jose Andre Cozma', 'Romania', 'cozma'),
	('Michael Nelson', 'United States', 'nelson'),
	('Michael Nelson', 'United States', 'michael nelson'),
	('Gary Maley', 'Scotland', 'maley'),
	('Gary Maley', 'Scotland', 'gary maley'),
	('Tomás Canteros', 'Argentina', 'canteros'),
	('Tomás Canteros', 'Argentina', 'tomas canteros'),
	('Oktay Ozkara', 'Romania', 'oktay ozkara'),
	('Oktay Ozkara', 'Romania', 'ozkara'),
	('So Nishikawa', 'Japan', 'so nishikawa'),
	('So Nishikawa', 'Japan', 'nishikawa'),
	('Andreas Gülstorff', 'Denmark', 'andreas gulstorff'),
	('Andreas Gülstorff', 'Denmark', 'gulstorff'),
	('Lukas Schneller', 'Germany', 'lukas schneller'),
	('Lukas Schneller', 'Germany', 'schneller'),
	('Florinel Sandu', 'Romania', 'florinel sandu'),
	('Florinel Sandu', 'Romania', 'sandu'),
	('Furkan Bekleviç', 'Turkey', 'furkan beklevic'),
	('Furkan Bekleviç', 'Turkey', 'beklevic'),
	('Alex Fojtíček', 'Slovakia', 'alex fojticek'),
	('Alex Fojtíček', 'Slovakia', 'fojticek'),
	('Ask Tjærandsen-Skau', 'Norway', 'tjrandsenskau'),
	('Ask Tjærandsen-Skau', 'Norway', 'ask tjrandsenskau'),
	('Lucas Maus', 'Belgium', 'maus'),
	('Lucas Maus', 'Belgium', 'lucas maus'),
	('Julian Hermann', 'Switzerland', 'julian hermann'),
	('Julian Hermann', 'Switzerland', 'hermann'),
	('Zhao Shi', 'China PR', 'zhao shi'),
	('Zhao Shi', 'China PR', 'shi'),
	('Filip Laskowski', 'Poland', 'laskowski'),
	('Filip Laskowski', 'Poland', 'filip laskowski'),
	('Daniel Trickett-Smith', 'England', 'trickettsmith'),
	('Daniel Trickett-Smith', 'England', 'daniel trickettsmith'),
	('Eryk Mirus', 'Poland', 'eryk mirus'),
	('Eryk Mirus', 'Poland', 'mirus'),
	('Alexander Kogler', 'Austria', 'kogler'),
	('Alexander Kogler', 'Austria', 'alexander kogler'),
	('Kyran Lofthouse', 'England', 'lofthouse'),
	('Kyran Lofthouse', 'England', 'kyran lofthouse'),
	('Sean Quinn', 'Republic of Ireland', 'sean quinn'),
	('Sean Quinn', 'Republic of Ireland', 'quinn'),
	('Mateusz Dudek', 'Poland', 'dudek'),
	('Mateusz Dudek', 'Poland', 'mateusz dudek'),
	('Emilian Metu', 'Austria', 'emilian metu'),
	('Emilian Metu', 'Austria', 'metu'),
	('Denzil Fernandes', 'Republic of Ireland', 'fernandes'),
	('Denzil Fernandes', 'Republic of Ireland', 'denzil fernandes'),
	('Kacper Sadłocha', 'Poland', 'sadocha'),
	('Kacper Sadłocha', 'Poland', 'kacper sadocha'),
	('Dagur Dan Þór­halls­son', 'Iceland', 'dagur dan orhallsson'),
	('Dagur Dan Þór­halls­son', 'Iceland', 'orhallsson'),
	('Mao Haoyu', 'China PR', 'haoyu'),
	('Mao Haoyu', 'China PR', 'mao haoyu'),
	('Nathan Woodthorpe', 'England', 'nathan woodthorpe'),
	('Nathan Woodthorpe', 'England', 'woodthorpe'),
	('Stefano Piccinini', 'Italy', 'piccinini'),
	('Stefano Piccinini', 'Italy', 'stefano piccinini'),
	('Jevan Anderson', 'Scotland', 'anderson'),
	('Jevan Anderson', 'Scotland', 'jevan anderson'),
	('Kevin Paredes', 'United States', 'paredes'),
	('Kevin Paredes', 'United States', 'kevin paredes'),
	('Jayden Campbell', 'England', 'jayden campbell'),
	('Jayden Campbell', 'England', 'campbell'),
	('Kliver Moreno', 'Colombia', 'moreno'),
	('Kliver Moreno', 'Colombia', 'kliver moreno'),
	('Daniel Phillips', 'England', 'phillips'),
	('Daniel Phillips', 'England', 'daniel phillips'),
	('Meshal Sibyani', 'Saudi Arabia', 'sibyani'),
	('Meshal Sibyani', 'Saudi Arabia', 'meshal sibyani'),
	('Marco Ramkilde', 'Denmark', 'marco ramkilde'),
	('Marco Ramkilde', 'Denmark', 'ramkilde'),
	('Edson López', 'Peru', 'edson lopez'),
	('Edson López', 'Peru', 'lopez'),
	('Kyron Gordon', 'England', 'gordon'),
	('Kyron Gordon', 'England', 'kyron gordon'),
	('Alban Ajdini', 'Kosovo', 'ajdini'),
	('Alban Ajdini', 'Kosovo', 'alban ajdini'),
	('Finn Cousin-Dawson', 'England', 'finn cousindawson'),
	('Finn Cousin-Dawson', 'England', 'cousindawson'),
	('Chris Garcia', 'United States', 'garcia'),
	('Chris Garcia', 'United States', 'chris garcia'),
	('Simen Vidtun Nilsen', 'Norway', 'nilsen'),
	('Simen Vidtun Nilsen', 'Norway', 'simen vidtun nilsen'),
	('Gianluca Bucci', 'England', 'bucci'),
	('Gianluca Bucci', 'England', 'gianluca bucci'),
	('Moudi Najjar', 'Australia', 'moudi najjar'),
	('Moudi Najjar', 'Australia', 'najjar'),
	('Will Lancaster', 'England', 'will lancaster'),
	('Will Lancaster', 'England', 'lancaster'),
	('William Pacho', 'Ecuador', 'william pacho'),
	('William Pacho', 'Ecuador', 'pacho'),
	('Josh Lundstram', 'England', 'lundstram'),
	('Josh Lundstram', 'England', 'josh lundstram'),
	('Andrei Mirică', 'Romania', 'mirica'),
	('Andrei Mirică', 'Romania', 'andrei mirica'),
	('Maki Petratos', 'Australia', 'petratos'),
	('Maki Petratos', 'Australia', 'maki petratos'),
	('Ever Urrutia', 'Venezuela', 'urrutia'),
	('Ever Urrutia', 'Venezuela', 'ever urrutia'),
	('Alexandru Chilili', 'Romania', 'alexandru chilili'),
	('Alexandru Chilili', 'Romania', 'chilili'),
	('Feng Boyuan', 'China PR', 'boyuan'),
	('Feng Boyuan', 'China PR', 'feng boyuan'),
	('Dakota Ochsenham', 'Australia', 'dakota ochsenham'),
	('Dakota Ochsenham', 'Australia', 'ochsenham'),
	('Florent Hoti', 'Kosovo', 'florent hoti'),
	('Florent Hoti', 'Kosovo', 'hoti'),
	('Momodou Touray', 'Wales', 'momodou touray'),
	('Momodou Touray', 'Wales', 'touray'),
	('Reegan Mimnaugh', 'Scotland', 'reegan mimnaugh'),
	('Reegan Mimnaugh', 'Scotland', 'mimnaugh'),
	('Ashley Maynard-Brewer', 'Australia', 'maynardbrewer'),
	('Ashley Maynard-Brewer', 'Australia', 'ashley maynardbrewer'),
	('Leo Donnellan', 'Republic of Ireland', 'donnellan'),
	('Leo Donnellan', 'Republic of Ireland', 'leo donnellan'),
	('Alexis Martial', 'France', 'alexis martial'),
	('Alexis Martial', 'France', 'martial'),
	('Anthony Patterson', 'England', 'patterson'),
	('Anthony Patterson', 'England', 'anthony patterson'),
	('Claudio Fraga', 'Venezuela', 'fraga'),
	('Claudio Fraga', 'Venezuela', 'claudio fraga'),
	('Filip Panjeskovic', 'Denmark', 'filip panjeskovic'),
	('Filip Panjeskovic', 'Denmark', 'panjeskovic'),
	('Wilver Jimenéz', 'Venezuela', 'jimenez'),
	('Wilver Jimenéz', 'Venezuela', 'wilver jimenez'),
	('Diego Guillen', 'Venezuela', 'diego guillen'),
	('Diego Guillen', 'Venezuela', 'guillen'),
	('Adan Abadala Hussein', 'Norway', 'adan abadala hussein'),
	('Adan Abadala Hussein', 'Norway', 'hussein'),
	('Mohammad Ahmadi', 'Sweden', 'ahmadi'),
	('Mohammad Ahmadi', 'Sweden', 'mohammad ahmadi'),
	('Mansour Al Muwallad', 'Saudi Arabia', 'muwallad'),
	('Mansour Al Muwallad', 'Saudi Arabia', 'mansour al muwallad'),
	('Casper Terho', 'Finland', 'casper terho'),
	('Casper Terho', 'Finland', 'terho'),
	('Rodrigo Orihuela', 'Bolivia', 'orihuela'),
	('Rodrigo Orihuela', 'Bolivia', 'rodrigo orihuela'),
	('Jeremi Escate', 'Peru', 'jeremi escate'),
	('Jeremi Escate', 'Peru', 'escate'),
	('Callum Hawkins', 'England', 'callum hawkins'),
	('Callum Hawkins', 'England', 'hawkins'),
	('Jordan Bender', 'United States', 'bender'),
	('Jordan Bender', 'United States', 'jordan bender'),
	('Albert Grønbæk', 'Denmark', 'grnbk'),
	('Albert Grønbæk', 'Denmark', 'albert grnbk'),
	('Li Guanxi', 'China PR', 'li guanxi'),
	('Li Guanxi', 'China PR', 'guanxi'),
	('Meshari Sanyor', 'Saudi Arabia', 'sanyor'),
	('Meshari Sanyor', 'Saudi Arabia', 'meshari sanyor'),
	('Valentin Borcea', 'Romania', 'borcea'),
	('Valentin Borcea', 'Romania', 'valentin borcea'),
	('Thomas Hallstensen', 'Norway', 'hallstensen'),
	('Thomas Hallstensen', 'Norway', 'thomas hallstensen'),
	('Kim Min Gyu', 'Korea Republic', 'kim min gyu'),
	('Kim Min Gyu', 'Korea Republic', 'gyu'),
	('Dominik Smykowski', 'Poland', 'dominik smykowski'),
	('Dominik Smykowski', 'Poland', 'smykowski'),
	('Sebastián Cavero', 'Peru', 'cavero'),
	('Sebastián Cavero', 'Peru', 'sebastian cavero'),
	('Greg Ranjitsingh', 'Trinidad & Tobago', 'greg ranjitsingh'),
	('Greg Ranjitsingh', 'Trinidad & Tobago', 'ranjitsingh'),
	('Bruno Barticciotto', 'Chile', 'bruno barticciotto'),
	('Bruno Barticciotto', 'Chile', 'barticciotto'),
	('Jack Currie', 'England', 'currie'),
	('Jack Currie', 'England', 'jack currie'),
	('Carlos Arrua', 'Paraguay', 'arrua'),
	('Carlos Arrua', 'Paraguay', 'carlos arrua'),
	('Mads Fagerli Halsøy', 'Norway', 'halsy'),
	('Mads Fagerli Halsøy', 'Norway', 'mads fagerli halsy'),
	('Freddie Price', 'England', 'price'),
	('Freddie Price', 'England', 'freddie price'),
	('David Norman Jr.', 'Canada', 'jr'),
	('David Norman Jr.', 'Canada', 'david norman jr'),
	('Zhang Junzhe', 'China PR', 'junzhe'),
	('Zhang Junzhe', 'China PR', 'zhang junzhe'),
	('Aleksander B. Stenseth', 'Norway', 'stenseth'),
	('Aleksander B. Stenseth', 'Norway', 'aleksander b stenseth'),
	('Víctor Valdez', 'Ecuador', 'valdez'),
	('Víctor Valdez', 'Ecuador', 'victor valdez'),
	('Jack Simmons', 'Australia', 'simmons'),
	('Jack Simmons', 'Australia', 'jack simmons'),
	('Cameron Antwi', 'England', 'cameron antwi'),
	('Cameron Antwi', 'England', 'antwi'),
	('Kyle Joseph', 'Scotland', 'kyle joseph'),
	('Kyle Joseph', 'Scotland', 'joseph'),
	('Xu Wu', 'China PR', 'xu wu'),
	('Xu Wu', 'China PR', 'wu'),
	('Mohsen Al Hadhderi', 'Saudi Arabia', 'mohsen al hadhderi'),
	('Mohsen Al Hadhderi', 'Saudi Arabia', 'hadhderi'),
	('Teddy Bartouche', 'France', 'teddy bartouche'),
	('Teddy Bartouche', 'France', 'bartouche'),
	('Joshua Varga', 'Australia', 'varga'),
	('Joshua Varga', 'Australia', 'joshua varga'),
	('Brandon Taylor', 'England', 'taylor'),
	('Brandon Taylor', 'England', 'brandon taylor'),
	('Martín Parra', 'Chile', 'martin parra'),
	('Martín Parra', 'Chile', 'parra'),
	('Liam Smyth', 'Northern Ireland', 'liam smyth'),
	('Liam Smyth', 'Northern Ireland', 'smyth'),
	('Patrick Langlois', 'Australia', 'patrick langlois'),
	('Patrick Langlois', 'Australia', 'langlois'),
	('Niklas Jeck', 'Germany', 'jeck'),
	('Niklas Jeck', 'Germany', 'niklas jeck'),
	('Adan George', 'England', 'adan george'),
	('Adan George', 'England', 'george'),
	('Norbert Wojtuszek', 'Poland', 'norbert wojtuszek'),
	('Norbert Wojtuszek', 'Poland', 'wojtuszek'),
	('Jake Hackett', 'England', 'jake hackett'),
	('Jake Hackett', 'England', 'hackett'),
	('Giovanni Davis', 'Chile', 'giovanni davis'),
	('Giovanni Davis', 'Chile', 'davis'),
	('Henry Woods', 'England', 'henry woods'),
	('Henry Woods', 'England', 'woods'),
	('Hampus Holgersson', 'Sweden', 'holgersson'),
	('Hampus Holgersson', 'Sweden', 'hampus holgersson'),
	('Andreas Bredahl', 'Denmark', 'andreas bredahl'),
	('Andreas Bredahl', 'Denmark', 'bredahl'),
	('Edgaras Dubickas', 'Lithuania', 'dubickas'),
	('Edgaras Dubickas', 'Lithuania', 'edgaras dubickas'),
	('Jiang Shenglong', 'China PR', 'jiang shenglong'),
	('Jiang Shenglong', 'China PR', 'shenglong'),
	('Kamil Kruk', 'Poland', 'kruk'),
	('Kamil Kruk', 'Poland', 'kamil kruk')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';