INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Grégoire Puel', 'France', 'player'),
	('Alexis Arias', 'Peru', 'player'),
	('Andrei Cordea', 'Romania', 'player'),
	('Lukas Boeder', 'Germany', 'player'),
	('Enzo Millot', 'France', 'player'),
	('Augusto Lotti', 'Argentina', 'player'),
	('Yacine Bourhane', 'Comoros', 'player'),
	('Danny Guthrie', 'England', 'player'),
	('Sebastian Ring', 'Sweden', 'player'),
	('Matteo Cotali', 'Italy', 'player'),
	('Gonzalo Asís', 'Argentina', 'player'),
	('Will Jääskeläinen', 'Finland', 'player'),
	('Patrick Koronkiewicz', 'Germany', 'player'),
	('Aarón Rey', 'Spain', 'player'),
	('Yuma Obata', 'Japan', 'player'),
	('Francés', 'Spain', 'player'),
	('Bartosz Bida', 'Poland', 'player'),
	('Tim Kircher', 'Germany', 'player'),
	('Ousama Siddiki', 'Morocco', 'player'),
	('Stefan van der Lei', 'Netherlands', 'player'),
	('William Balikwisha', 'DR Congo', 'player'),
	('Davide Bettella', 'Italy', 'player'),
	('Nicolas Meister', 'Austria', 'player'),
	('Kike Saverio', 'Ecuador', 'player'),
	('Craig Clay', 'England', 'player'),
	('Eiichi Katayama', 'Japan', 'player'),
	('Robert Janicki', 'Poland', 'player'),
	('Kosuke Saito', 'Japan', 'player'),
	('Steve Arnold', 'England', 'player'),
	('Szymon Sobczak', 'Poland', 'player'),
	('Svend Brodersen', 'Germany', 'player'),
	('Jason Demetriou', 'Cyprus', 'player'),
	('Song Si Woo', 'Korea Republic', 'player'),
	('Robin Ziegele', 'Germany', 'player'),
	('Claudio Mendes', 'Spain', 'player'),
	('Tsubasa Nishi', 'Japan', 'player'),
	('Gaspar Campos', 'Spain', 'player'),
	('Pape Sané', 'Senegal', 'player'),
	('Chen Lei', 'China PR', 'player'),
	('Rocco Reitz', 'Germany', 'player'),
	('Mark Reynolds', 'Scotland', 'player'),
	('Edson Torres', 'Mexico', 'player'),
	('Waleed Abdullah', 'Saudi Arabia', 'player'),
	('Baena', 'Spain', 'player'),
	('Lazar Samardžić', 'Germany', 'player'),
	('Kim Jin Hyuk', 'Korea Republic', 'player'),
	('Igor Jovanović', 'Croatia', 'player'),
	('Enzo Ebosse', 'France', 'player'),
	('Kelechi Nwakali', 'Nigeria', 'player'),
	('Ignacio Chicco', 'Argentina', 'player'),
	('Filip Ugrinic', 'Switzerland', 'player'),
	('Víctor Chust', 'Spain', 'player'),
	('Altube', 'Spain', 'player'),
	('José Gragera', 'Spain', 'player'),
	('Lee Dong Jun', 'Korea Republic', 'player'),
	('Abdullah Saud Al Mutairi', 'Saudi Arabia', 'player'),
	('Nabil Alioui', 'France', 'player'),
	('Maximiliano Villa', 'Uruguay', 'player'),
	('Eric Ramírez', 'Argentina', 'player'),
	('Marlon de Jesús', 'Ecuador', 'player'),
	('Ibrahima Wadji', 'Senegal', 'player'),
	('Igor Łasicki', 'Poland', 'player'),
	('Gustav Ludwigson', 'Sweden', 'player'),
	('Daniel Hanslik', 'Germany', 'player'),
	('Hirotsugu Nakabayashi', 'Japan', 'player'),
	('Lautaro Rinaldi', 'Argentina', 'player'),
	('Cesar Menacho', 'Bolivia', 'player'),
	('Alessandro Deiola', 'Italy', 'player'),
	('Malick Evouna', 'Gabon', 'player'),
	('Herbert Bockhorn', 'Uganda', 'player'),
	('Manuel Balda', 'Ecuador', 'player'),
	('Mattia Viviani', 'Italy', 'player'),
	('Hilal El-Helwe', 'Lebanon', 'player'),
	('Thor Lange', 'Denmark', 'player'),
	('Betim Fazliji', 'Switzerland', 'player'),
	('Vladimir Screciu', 'Romania', 'player'),
	('Dennis Politic', 'Romania', 'player'),
	('Javi Benítez', 'Spain', 'player'),
	('Kwame Yeboah', 'Australia', 'player'),
	('Steffen Nkansah', 'Germany', 'player'),
	('Torbjørn Agdestein', 'Norway', 'player'),
	('Lukas Hornicek', 'Dominican Republic', 'player'),
	('Mandela Egbo', 'England', 'player'),
	('Rodrigo Villagra', 'Argentina', 'player'),
	('Cemali Sertel', 'Turkey', 'player'),
	('Mattia Bottani', 'Switzerland', 'player'),
	('Ondřej Bačo', 'Czech Republic', 'player'),
	('Kévin Rimane', 'France', 'player'),
	('Maodo Malick Mbaye', 'Senegal', 'player'),
	('Nils Butzen', 'Germany', 'player'),
	('Othman Boussaid', 'Belgium', 'player'),
	('Sirlord Conteh', 'Germany', 'player'),
	('Yuya Fukuda', 'Japan', 'player'),
	('Valentine Ozornwafor', 'Nigeria', 'player'),
	('Héctor Zeta', 'Peru', 'player'),
	('Gedion Zelalem', 'United States', 'player'),
	('Song Boxuan', 'China PR', 'player'),
	('Yannick Mamilonne', 'France', 'player'),
	('Ryotaro Meshino', 'Japan', 'player'),
	('Driss Khalid', 'Morocco', 'player'),
	('Jonas David', 'Germany', 'player'),
	('Tobias Schützenauer', 'Austria', 'player'),
	('David McMillan', 'Republic of Ireland', 'player'),
	('Sander Christiansen', 'Norway', 'player'),
	('Amir Arli', 'Turkey', 'player'),
	('Lucas Cueto', 'Germany', 'player'),
	('Gjoko Zajkov', 'North Macedonia', 'player'),
	('Taichi Hara', 'Japan', 'player'),
	('Filip Marchwiński', 'Poland', 'player'),
	('Mark Oxley', 'England', 'player'),
	('Mariusz Pawelec', 'Poland', 'player'),
	('Agustín Obando', 'Argentina', 'player'),
	('Shumpei Naruse', 'Japan', 'player'),
	('Sean McLoughlin', 'Republic of Ireland', 'player'),
	('Pablo Becker', 'Argentina', 'player'),
	('David Meza Colli', 'Paraguay', 'player'),
	('Toichi Suzuki', 'Japan', 'player'),
	('Alexander Laukart', 'Germany', 'player'),
	('Alex Samuel', 'Wales', 'player'),
	('Marco Tumminello', 'Italy', 'player'),
	('Chris Lines', 'England', 'player'),
	('Lee O''Connor', 'Republic of Ireland', 'player'),
	('Mouhamed Mbaye', 'Senegal', 'player'),
	('Benjamin Bertrand', 'France', 'player'),
	('Anatoliy Trubin', 'Ukraine', 'player'),
	('Dinu Graur', 'Moldova', 'player'),
	('Benjamin Büchel', 'Liechtenstein', 'player'),
	('Bendik Bye', 'Norway', 'player'),
	('Opa Sangante', 'Senegal', 'player'),
	('Finn Dahmen', 'Germany', 'player'),
	('Tom Lapslie', 'England', 'player'),
	('Grzegorz Tomasiewicz', 'Poland', 'player'),
	('Mehdi Merghem', 'France', 'player'),
	('Fran Vieites', 'Spain', 'player'),
	('Hillel Konaté', 'Ivory Coast', 'player'),
	('Fabiano Alves', 'Brazil', 'player'),
	('Ryo Takano', 'Japan', 'player'),
	('Kevin van Veen', 'Netherlands', 'player'),
	('Joe Maguire', 'England', 'player'),
	('Luz Rodríguez', 'Mexico', 'player'),
	('Elton Monteiro', 'Portugal', 'player'),
	('Breno', 'Portugal', 'player'),
	('Emmanuel Sowah', 'Ghana', 'player'),
	('Alex Baptiste', 'England', 'player'),
	('Dion Charles', 'Northern Ireland', 'player'),
	('Daniel Offenbacher', 'Austria', 'player'),
	('Antonis Stergiakis', 'Greece', 'player'),
	('Paulino', 'Spain', 'player'),
	('Sebastián Gamarra', 'Bolivia', 'player'),
	('Hayden White', 'England', 'player'),
	('Jofre Carreras', 'Spain', 'player'),
	('David Tijanić', 'Slovenia', 'player'),
	('Callum Whelan', 'England', 'player'),
	('Nick Freeman', 'England', 'player'),
	('Billy Clarke', 'Republic of Ireland', 'player'),
	('Fernando Luna', 'Argentina', 'player'),
	('Adam Ståhl', 'Sweden', 'player'),
	('Florian Stritzel', 'Germany', 'player'),
	('Lee Tae Hee', 'Korea Republic', 'player'),
	('Johan Valencia', 'Colombia', 'player'),
	('João Virgínia', 'Portugal', 'player'),
	('Steffen Schäfer', 'Germany', 'player'),
	('Antonios Papadopoulos', 'Germany', 'player'),
	('Hirokazu Ishihara', 'Japan', 'player'),
	('Lucas Felippe', 'Brazil', 'player'),
	('Martin Minchev', 'Bulgaria', 'player'),
	('Stephan Andersen', 'Denmark', 'player'),
	('Chris Porter', 'England', 'player'),
	('Joel Coleman', 'England', 'player'),
	('Gabriel Alanís', 'Argentina', 'player'),
	('Marcel Holzmann', 'Austria', 'player'),
	('Rodolfo Cardoso', 'Portugal', 'player'),
	('Mats Haakenstad', 'Norway', 'player'),
	('Joseph Boyamba', 'Germany', 'player'),
	('Brahim Konaté', 'France', 'player'),
	('Stiven Vega', 'Colombia', 'player'),
	('Mateusz Kupczak', 'Poland', 'player'),
	('Pedro Mateus', 'Portugal', 'player'),
	('Milan Kocić', 'Slovenia', 'player'),
	('Gergely Bobál', 'Hungary', 'player'),
	('Greg Bolger', 'Republic of Ireland', 'player'),
	('Leonel Picco', 'Argentina', 'player'),
	('Jack Roles', 'Cyprus', 'player'),
	('Maximilian Krauß', 'Germany', 'player'),
	('Tom Müller', 'Germany', 'player'),
	('Víctor López', 'Spain', 'player'),
	('Keanan Bennetts', 'England', 'player'),
	('Wayde Jooste', 'South Africa', 'player'),
	('Valmir Berisha', 'Sweden', 'player'),
	('Luis Cangá', 'Ecuador', 'player'),
	('Nazareno Colombo', 'Argentina', 'player'),
	('Ersin Zehir', 'Germany', 'player'),
	('Linda Mntambo', 'South Africa', 'player'),
	('Nathan Ralph', 'England', 'player'),
	('Ali Hazazi', 'Saudi Arabia', 'player'),
	('Patryk Kun', 'Poland', 'player'),
	('Han Hee Hoon', 'Korea Republic', 'player'),
	('Reynaldo', 'Brazil', 'player'),
	('Sam Hughes', 'England', 'player'),
	('Branislav Pindroch', 'Slovakia', 'player'),
	('Mickel Miller', 'England', 'player'),
	('Pascu', 'Spain', 'player'),
	('Mateo Bajamich', 'Argentina', 'player'),
	('Jordan Houghton', 'England', 'player'),
	('Ilmari Niskanen', 'Finland', 'player'),
	('Simon Sohm', 'Switzerland', 'player'),
	('Karamoko Dembélé', 'England', 'player'),
	('Juan Manuel Ramos', 'Uruguay', 'player'),
	('Haji Wright', 'United States', 'player'),
	('Feng Jin', 'China PR', 'player'),
	('Marcus Mathisen', 'Denmark', 'player'),
	('Nathan McGinley', 'England', 'player'),
	('Pelayo Suárez', 'Spain', 'player'),
	('Dylan Levitt', 'Wales', 'player'),
	('Sergio Adrián', 'Bolivia', 'player'),
	('Colin Daniel', 'England', 'player'),
	('Matías Villarreal', 'Argentina', 'player'),
	('Jorge Pereira', 'Portugal', 'player'),
	('Diego Osio', 'Venezuela', 'player'),
	('Damián Ezequiel Petcoff', 'Argentina', 'player'),
	('Nicolai Brock-Madsen', 'Denmark', 'player'),
	('Daniel Florea', 'Romania', 'player'),
	('Luke Norris', 'England', 'player'),
	('Gervane Kastaneer', 'Curacao', 'player'),
	('Michele Rigione', 'Italy', 'player'),
	('Gino Fechner', 'Germany', 'player'),
	('Niclas Stierlin', 'Germany', 'player'),
	('Jorris Romil', 'France', 'player'),
	('Joaquín Blázquez', 'Argentina', 'player'),
	('Jordan Tillson', 'England', 'player'),
	('Henrique Trevisan', 'Brazil', 'player'),
	('Clarke Oduor', 'Kenya', 'player'),
	('Diego Barreto', 'Paraguay', 'player'),
	('Patrick Choroba', 'Germany', 'player'),
	('Ricardo Schutte', 'Portugal', 'player'),
	('Bryan Nouvier', 'France', 'player'),
	('Kevin Romay', 'Bolivia', 'player'),
	('Moustapha Seck', 'Senegal', 'player'),
	('Mickey Demetriou', 'England', 'player'),
	('Elder Arauz', 'Bolivia', 'player'),
	('Lucien Agoume', 'France', 'player'),
	('Massimiliano Mangraviti', 'Italy', 'player'),
	('Hervé Kambou', 'Ivory Coast', 'player'),
	('David Schnegg', 'Austria', 'player'),
	('Aaron Schoenfeld', 'United States', 'player'),
	('Alex Pattison', 'England', 'player'),
	('Keisuke Iwashita', 'Japan', 'player'),
	('David Gugganig', 'Austria', 'player'),
	('Mohammed Al Fehaid', 'Saudi Arabia', 'player'),
	('Mohamed Bayo', 'France', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Grégoire Puel', 'France', 'gregoire puel'),
	('Grégoire Puel', 'France', 'puel'),
	('Alexis Arias', 'Peru', 'alexis arias'),
	('Alexis Arias', 'Peru', 'arias'),
	('Andrei Cordea', 'Romania', 'cordea'),
	('Andrei Cordea', 'Romania', 'andrei cordea'),
	('Lukas Boeder', 'Germany', 'lukas boeder'),
	('Lukas Boeder', 'Germany', 'boeder'),
	('Enzo Millot', 'France', 'enzo millot'),
	('Enzo Millot', 'France', 'millot'),
	('Augusto Lotti', 'Argentina', 'augusto lotti'),
	('Augusto Lotti', 'Argentina', 'lotti'),
	('Yacine Bourhane', 'Comoros', 'bourhane'),
	('Yacine Bourhane', 'Comoros', 'yacine bourhane'),
	('Danny Guthrie', 'England', 'guthrie'),
	('Danny Guthrie', 'England', 'danny guthrie'),
	('Sebastian Ring', 'Sweden', 'ring'),
	('Sebastian Ring', 'Sweden', 'sebastian ring'),
	('Matteo Cotali', 'Italy', 'matteo cotali'),
	('Matteo Cotali', 'Italy', 'cotali'),
	('Gonzalo Asís', 'Argentina', 'asis'),
	('Gonzalo Asís', 'Argentina', 'gonzalo asis'),
	('Will Jääskeläinen', 'Finland', 'jaaskelainen'),
	('Will Jääskeläinen', 'Finland', 'will jaaskelainen'),
	('Patrick Koronkiewicz', 'Germany', 'koronkiewicz'),
	('Patrick Koronkiewicz', 'Germany', 'patrick koronkiewicz'),
	('Aarón Rey', 'Spain', 'rey'),
	('Aarón Rey', 'Spain', 'aaron rey'),
	('Yuma Obata', 'Japan', 'yuma obata'),
	('Yuma Obata', 'Japan', 'obata'),
	('Francés', 'Spain', 'frances'),
	('Bartosz Bida', 'Poland', 'bartosz bida'),
	('Bartosz Bida', 'Poland', 'bida'),
	('Tim Kircher', 'Germany', 'kircher'),
	('Tim Kircher', 'Germany', 'tim kircher'),
	('Ousama Siddiki', 'Morocco', 'siddiki'),
	('Ousama Siddiki', 'Morocco', 'ousama siddiki'),
	('Stefan van der Lei', 'Netherlands', 'lei'),
	('Stefan van der Lei', 'Netherlands', 'stefan van der lei'),
	('William Balikwisha', 'DR Congo', 'balikwisha'),
	('William Balikwisha', 'DR Congo', 'william balikwisha'),
	('Davide Bettella', 'Italy', 'davide bettella'),
	('Davide Bettella', 'Italy', 'bettella'),
	('Nicolas Meister', 'Austria', 'meister'),
	('Nicolas Meister', 'Austria', 'nicolas meister'),
	('Kike Saverio', 'Ecuador', 'kike saverio'),
	('Kike Saverio', 'Ecuador', 'saverio'),
	('Craig Clay', 'England', 'craig clay'),
	('Craig Clay', 'England', 'clay'),
	('Eiichi Katayama', 'Japan', 'katayama'),
	('Eiichi Katayama', 'Japan', 'eiichi katayama'),
	('Robert Janicki', 'Poland', 'janicki'),
	('Robert Janicki', 'Poland', 'robert janicki'),
	('Kosuke Saito', 'Japan', 'saito'),
	('Kosuke Saito', 'Japan', 'kosuke saito'),
	('Steve Arnold', 'England', 'steve arnold'),
	('Steve Arnold', 'England', 'arnold'),
	('Szymon Sobczak', 'Poland', 'sobczak'),
	('Szymon Sobczak', 'Poland', 'szymon sobczak'),
	('Svend Brodersen', 'Germany', 'brodersen'),
	('Svend Brodersen', 'Germany', 'svend brodersen'),
	('Jason Demetriou', 'Cyprus', 'demetriou'),
	('Jason Demetriou', 'Cyprus', 'jason demetriou'),
	('Song Si Woo', 'Korea Republic', 'woo'),
	('Song Si Woo', 'Korea Republic', 'song si woo'),
	('Robin Ziegele', 'Germany', 'robin ziegele'),
	('Robin Ziegele', 'Germany', 'ziegele'),
	('Claudio Mendes', 'Spain', 'claudio mendes'),
	('Claudio Mendes', 'Spain', 'mendes'),
	('Tsubasa Nishi', 'Japan', 'tsubasa nishi'),
	('Tsubasa Nishi', 'Japan', 'nishi'),
	('Gaspar Campos', 'Spain', 'gaspar campos'),
	('Gaspar Campos', 'Spain', 'campos'),
	('Pape Sané', 'Senegal', 'pape sane'),
	('Pape Sané', 'Senegal', 'sane'),
	('Chen Lei', 'China PR', 'lei'),
	('Chen Lei', 'China PR', 'chen lei'),
	('Rocco Reitz', 'Germany', 'rocco reitz'),
	('Rocco Reitz', 'Germany', 'reitz'),
	('Mark Reynolds', 'Scotland', 'reynolds'),
	('Mark Reynolds', 'Scotland', 'mark reynolds'),
	('Edson Torres', 'Mexico', 'torres'),
	('Edson Torres', 'Mexico', 'edson torres'),
	('Waleed Abdullah', 'Saudi Arabia', 'waleed abdullah'),
	('Waleed Abdullah', 'Saudi Arabia', 'abdullah'),
	('Baena', 'Spain', 'baena'),
	('Lazar Samardžić', 'Germany', 'lazar samardzic'),
	('Lazar Samardžić', 'Germany', 'samardzic'),
	('Kim Jin Hyuk', 'Korea Republic', 'kim jin hyuk'),
	('Kim Jin Hyuk', 'Korea Republic', 'hyuk'),
	('Igor Jovanović', 'Croatia', 'igor jovanovic'),
	('Igor Jovanović', 'Croatia', 'jovanovic'),
	('Enzo Ebosse', 'France', 'ebosse'),
	('Enzo Ebosse', 'France', 'enzo ebosse'),
	('Kelechi Nwakali', 'Nigeria', 'nwakali'),
	('Kelechi Nwakali', 'Nigeria', 'kelechi nwakali'),
	('Ignacio Chicco', 'Argentina', 'chicco'),
	('Ignacio Chicco', 'Argentina', 'ignacio chicco'),
	('Filip Ugrinic', 'Switzerland', 'ugrinic'),
	('Filip Ugrinic', 'Switzerland', 'filip ugrinic'),
	('Víctor Chust', 'Spain', 'victor chust'),
	('Víctor Chust', 'Spain', 'chust'),
	('Altube', 'Spain', 'altube'),
	('José Gragera', 'Spain', 'jose gragera'),
	('José Gragera', 'Spain', 'gragera'),
	('Lee Dong Jun', 'Korea Republic', 'jun'),
	('Lee Dong Jun', 'Korea Republic', 'lee dong jun'),
	('Abdullah Saud Al Mutairi', 'Saudi Arabia', 'abdullah saud al mutairi'),
	('Abdullah Saud Al Mutairi', 'Saudi Arabia', 'mutairi'),
	('Nabil Alioui', 'France', 'nabil alioui'),
	('Nabil Alioui', 'France', 'alioui'),
	('Maximiliano Villa', 'Uruguay', 'maximiliano villa'),
	('Maximiliano Villa', 'Uruguay', 'villa'),
	('Eric Ramírez', 'Argentina', 'eric ramirez'),
	('Eric Ramírez', 'Argentina', 'ramirez'),
	('Marlon de Jesús', 'Ecuador', 'marlon de jesus'),
	('Marlon de Jesús', 'Ecuador', 'jesus'),
	('Ibrahima Wadji', 'Senegal', 'ibrahima wadji'),
	('Ibrahima Wadji', 'Senegal', 'wadji'),
	('Igor Łasicki', 'Poland', 'igor asicki'),
	('Igor Łasicki', 'Poland', 'asicki'),
	('Gustav Ludwigson', 'Sweden', 'ludwigson'),
	('Gustav Ludwigson', 'Sweden', 'gustav ludwigson'),
	('Daniel Hanslik', 'Germany', 'hanslik'),
	('Daniel Hanslik', 'Germany', 'daniel hanslik'),
	('Hirotsugu Nakabayashi', 'Japan', 'nakabayashi'),
	('Hirotsugu Nakabayashi', 'Japan', 'hirotsugu nakabayashi'),
	('Lautaro Rinaldi', 'Argentina', 'lautaro rinaldi'),
	('Lautaro Rinaldi', 'Argentina', 'rinaldi'),
	('Cesar Menacho', 'Bolivia', 'cesar menacho'),
	('Cesar Menacho', 'Bolivia', 'menacho'),
	('Alessandro Deiola', 'Italy', 'deiola'),
	('Alessandro Deiola', 'Italy', 'alessandro deiola'),
	('Malick Evouna', 'Gabon', 'malick evouna'),
	('Malick Evouna', 'Gabon', 'evouna'),
	('Herbert Bockhorn', 'Uganda', 'herbert bockhorn'),
	('Herbert Bockhorn', 'Uganda', 'bockhorn'),
	('Manuel Balda', 'Ecuador', 'balda'),
	('Manuel Balda', 'Ecuador', 'manuel balda'),
	('Mattia Viviani', 'Italy', 'mattia viviani'),
	('Mattia Viviani', 'Italy', 'viviani'),
	('Hilal El-Helwe', 'Lebanon', 'hilal elhelwe'),
	('Hilal El-Helwe', 'Lebanon', 'elhelwe'),
	('Thor Lange', 'Denmark', 'thor lange'),
	('Thor Lange', 'Denmark', 'lange'),
	('Betim Fazliji', 'Switzerland', 'fazliji'),
	('Betim Fazliji', 'Switzerland', 'betim fazliji'),
	('Vladimir Screciu', 'Romania', 'vladimir screciu'),
	('Vladimir Screciu', 'Romania', 'screciu'),
	('Dennis Politic', 'Romania', 'dennis politic'),
	('Dennis Politic', 'Romania', 'politic'),
	('Javi Benítez', 'Spain', 'benitez'),
	('Javi Benítez', 'Spain', 'javi benitez'),
	('Kwame Yeboah', 'Australia', 'kwame yeboah'),
	('Kwame Yeboah', 'Australia', 'yeboah'),
	('Steffen Nkansah', 'Germany', 'nkansah'),
	('Steffen Nkansah', 'Germany', 'steffen nkansah'),
	('Torbjørn Agdestein', 'Norway', 'torbjrn agdestein'),
	('Torbjørn Agdestein', 'Norway', 'agdestein'),
	('Lukas Hornicek', 'Dominican Republic', 'hornicek'),
	('Lukas Hornicek', 'Dominican Republic', 'lukas hornicek'),
	('Mandela Egbo', 'England', 'mandela egbo'),
	('Mandela Egbo', 'England', 'egbo'),
	('Rodrigo Villagra', 'Argentina', 'villagra'),
	('Rodrigo Villagra', 'Argentina', 'rodrigo villagra'),
	('Cemali Sertel', 'Turkey', 'cemali sertel'),
	('Cemali Sertel', 'Turkey', 'sertel'),
	('Mattia Bottani', 'Switzerland', 'mattia bottani'),
	('Mattia Bottani', 'Switzerland', 'bottani'),
	('Ondřej Bačo', 'Czech Republic', 'ondrej baco'),
	('Ondřej Bačo', 'Czech Republic', 'baco'),
	('Kévin Rimane', 'France', 'kevin rimane'),
	('Kévin Rimane', 'France', 'rimane'),
	('Maodo Malick Mbaye', 'Senegal', 'mbaye'),
	('Maodo Malick Mbaye', 'Senegal', 'maodo malick mbaye'),
	('Nils Butzen', 'Germany', 'butzen'),
	('Nils Butzen', 'Germany', 'nils butzen'),
	('Othman Boussaid', 'Belgium', 'boussaid'),
	('Othman Boussaid', 'Belgium', 'othman boussaid'),
	('Sirlord Conteh', 'Germany', 'sirlord conteh'),
	('Sirlord Conteh', 'Germany', 'conteh'),
	('Yuya Fukuda', 'Japan', 'yuya fukuda'),
	('Yuya Fukuda', 'Japan', 'fukuda'),
	('Valentine Ozornwafor', 'Nigeria', 'ozornwafor'),
	('Valentine Ozornwafor', 'Nigeria', 'valentine ozornwafor'),
	('Héctor Zeta', 'Peru', 'hector zeta'),
	('Héctor Zeta', 'Peru', 'zeta'),
	('Gedion Zelalem', 'United States', 'zelalem'),
	('Gedion Zelalem', 'United States', 'gedion zelalem'),
	('Song Boxuan', 'China PR', 'boxuan'),
	('Song Boxuan', 'China PR', 'song boxuan'),
	('Yannick Mamilonne', 'France', 'yannick mamilonne'),
	('Yannick Mamilonne', 'France', 'mamilonne'),
	('Ryotaro Meshino', 'Japan', 'meshino'),
	('Ryotaro Meshino', 'Japan', 'ryotaro meshino'),
	('Driss Khalid', 'Morocco', 'driss khalid'),
	('Driss Khalid', 'Morocco', 'khalid'),
	('Jonas David', 'Germany', 'jonas david'),
	('Jonas David', 'Germany', 'david'),
	('Tobias Schützenauer', 'Austria', 'tobias schutzenauer'),
	('Tobias Schützenauer', 'Austria', 'schutzenauer'),
	('David McMillan', 'Republic of Ireland', 'mcmillan'),
	('David McMillan', 'Republic of Ireland', 'david mcmillan'),
	('Sander Christiansen', 'Norway', 'christiansen'),
	('Sander Christiansen', 'Norway', 'sander christiansen'),
	('Amir Arli', 'Turkey', 'arli'),
	('Amir Arli', 'Turkey', 'amir arli'),
	('Lucas Cueto', 'Germany', 'cueto'),
	('Lucas Cueto', 'Germany', 'lucas cueto'),
	('Gjoko Zajkov', 'North Macedonia', 'zajkov'),
	('Gjoko Zajkov', 'North Macedonia', 'gjoko zajkov'),
	('Taichi Hara', 'Japan', 'taichi hara'),
	('Taichi Hara', 'Japan', 'hara'),
	('Filip Marchwiński', 'Poland', 'filip marchwinski'),
	('Filip Marchwiński', 'Poland', 'marchwinski'),
	('Mark Oxley', 'England', 'oxley'),
	('Mark Oxley', 'England', 'mark oxley'),
	('Mariusz Pawelec', 'Poland', 'mariusz pawelec'),
	('Mariusz Pawelec', 'Poland', 'pawelec'),
	('Agustín Obando', 'Argentina', 'agustin obando'),
	('Agustín Obando', 'Argentina', 'obando'),
	('Shumpei Naruse', 'Japan', 'naruse'),
	('Shumpei Naruse', 'Japan', 'shumpei naruse'),
	('Sean McLoughlin', 'Republic of Ireland', 'sean mcloughlin'),
	('Sean McLoughlin', 'Republic of Ireland', 'mcloughlin'),
	('Pablo Becker', 'Argentina', 'pablo becker'),
	('Pablo Becker', 'Argentina', 'becker'),
	('David Meza Colli', 'Paraguay', 'david meza colli'),
	('David Meza Colli', 'Paraguay', 'colli'),
	('Toichi Suzuki', 'Japan', 'toichi suzuki'),
	('Toichi Suzuki', 'Japan', 'suzuki'),
	('Alexander Laukart', 'Germany', 'alexander laukart'),
	('Alexander Laukart', 'Germany', 'laukart'),
	('Alex Samuel', 'Wales', 'samuel'),
	('Alex Samuel', 'Wales', 'alex samuel'),
	('Marco Tumminello', 'Italy', 'tumminello'),
	('Marco Tumminello', 'Italy', 'marco tumminello'),
	('Chris Lines', 'England', 'lines'),
	('Chris Lines', 'England', 'chris lines'),
	('Lee O''Connor', 'Republic of Ireland', 'oconnor'),
	('Lee O''Connor', 'Republic of Ireland', 'lee oconnor'),
	('Mouhamed Mbaye', 'Senegal', 'mbaye'),
	('Mouhamed Mbaye', 'Senegal', 'mouhamed mbaye'),
	('Benjamin Bertrand', 'France', 'bertrand'),
	('Benjamin Bertrand', 'France', 'benjamin bertrand'),
	('Anatoliy Trubin', 'Ukraine', 'anatoliy trubin'),
	('Anatoliy Trubin', 'Ukraine', 'trubin'),
	('Dinu Graur', 'Moldova', 'graur'),
	('Dinu Graur', 'Moldova', 'dinu graur'),
	('Benjamin Büchel', 'Liechtenstein', 'benjamin buchel'),
	('Benjamin Büchel', 'Liechtenstein', 'buchel'),
	('Bendik Bye', 'Norway', 'bye'),
	('Bendik Bye', 'Norway', 'bendik bye'),
	('Opa Sangante', 'Senegal', 'opa sangante'),
	('Opa Sangante', 'Senegal', 'sangante'),
	('Finn Dahmen', 'Germany', 'dahmen'),
	('Finn Dahmen', 'Germany', 'finn dahmen'),
	('Tom Lapslie', 'England', 'tom lapslie'),
	('Tom Lapslie', 'England', 'lapslie'),
	('Grzegorz Tomasiewicz', 'Poland', 'tomasiewicz'),
	('Grzegorz Tomasiewicz', 'Poland', 'grzegorz tomasiewicz'),
	('Mehdi Merghem', 'France', 'merghem'),
	('Mehdi Merghem', 'France', 'mehdi merghem'),
	('Fran Vieites', 'Spain', 'vieites'),
	('Fran Vieites', 'Spain', 'fran vieites'),
	('Hillel Konaté', 'Ivory Coast', 'hillel konate'),
	('Hillel Konaté', 'Ivory Coast', 'konate'),
	('Fabiano Alves', 'Brazil', 'alves'),
	('Fabiano Alves', 'Brazil', 'fabiano alves'),
	('Ryo Takano', 'Japan', 'ryo takano'),
	('Ryo Takano', 'Japan', 'takano'),
	('Kevin van Veen', 'Netherlands', 'veen'),
	('Kevin van Veen', 'Netherlands', 'kevin van veen'),
	('Joe Maguire', 'England', 'joe maguire'),
	('Joe Maguire', 'England', 'maguire'),
	('Luz Rodríguez', 'Mexico', 'luz rodriguez'),
	('Luz Rodríguez', 'Mexico', 'rodriguez'),
	('Elton Monteiro', 'Portugal', 'monteiro'),
	('Elton Monteiro', 'Portugal', 'elton monteiro'),
	('Breno', 'Portugal', 'breno'),
	('Emmanuel Sowah', 'Ghana', 'emmanuel sowah'),
	('Emmanuel Sowah', 'Ghana', 'sowah'),
	('Alex Baptiste', 'England', 'alex baptiste'),
	('Alex Baptiste', 'England', 'baptiste'),
	('Dion Charles', 'Northern Ireland', 'charles'),
	('Dion Charles', 'Northern Ireland', 'dion charles'),
	('Daniel Offenbacher', 'Austria', 'offenbacher'),
	('Daniel Offenbacher', 'Austria', 'daniel offenbacher'),
	('Antonis Stergiakis', 'Greece', 'stergiakis'),
	('Antonis Stergiakis', 'Greece', 'antonis stergiakis'),
	('Paulino', 'Spain', 'paulino'),
	('Sebastián Gamarra', 'Bolivia', 'sebastian gamarra'),
	('Sebastián Gamarra', 'Bolivia', 'gamarra'),
	('Hayden White', 'England', 'white'),
	('Hayden White', 'England', 'hayden white'),
	('Jofre Carreras', 'Spain', 'carreras'),
	('Jofre Carreras', 'Spain', 'jofre carreras'),
	('David Tijanić', 'Slovenia', 'tijanic'),
	('David Tijanić', 'Slovenia', 'david tijanic'),
	('Callum Whelan', 'England', 'callum whelan'),
	('Callum Whelan', 'England', 'whelan'),
	('Nick Freeman', 'England', 'nick freeman'),
	('Nick Freeman', 'England', 'freeman'),
	('Billy Clarke', 'Republic of Ireland', 'clarke'),
	('Billy Clarke', 'Republic of Ireland', 'billy clarke'),
	('Fernando Luna', 'Argentina', 'luna'),
	('Fernando Luna', 'Argentina', 'fernando luna'),
	('Adam Ståhl', 'Sweden', 'stahl'),
	('Adam Ståhl', 'Sweden', 'adam stahl'),
	('Florian Stritzel', 'Germany', 'stritzel'),
	('Florian Stritzel', 'Germany', 'florian stritzel'),
	('Lee Tae Hee', 'Korea Republic', 'lee tae hee'),
	('Lee Tae Hee', 'Korea Republic', 'hee'),
	('Johan Valencia', 'Colombia', 'valencia'),
	('Johan Valencia', 'Colombia', 'johan valencia'),
	('João Virgínia', 'Portugal', 'joao virginia'),
	('João Virgínia', 'Portugal', 'virginia'),
	('Steffen Schäfer', 'Germany', 'schafer'),
	('Steffen Schäfer', 'Germany', 'steffen schafer'),
	('Antonios Papadopoulos', 'Germany', 'papadopoulos'),
	('Antonios Papadopoulos', 'Germany', 'antonios papadopoulos'),
	('Hirokazu Ishihara', 'Japan', 'ishihara'),
	('Hirokazu Ishihara', 'Japan', 'hirokazu ishihara'),
	('Lucas Felippe', 'Brazil', 'lucas felippe'),
	('Lucas Felippe', 'Brazil', 'felippe'),
	('Martin Minchev', 'Bulgaria', 'martin minchev'),
	('Martin Minchev', 'Bulgaria', 'minchev'),
	('Stephan Andersen', 'Denmark', 'stephan andersen'),
	('Stephan Andersen', 'Denmark', 'andersen'),
	('Chris Porter', 'England', 'porter'),
	('Chris Porter', 'England', 'chris porter'),
	('Joel Coleman', 'England', 'joel coleman'),
	('Joel Coleman', 'England', 'coleman'),
	('Gabriel Alanís', 'Argentina', 'alanis'),
	('Gabriel Alanís', 'Argentina', 'gabriel alanis'),
	('Marcel Holzmann', 'Austria', 'marcel holzmann'),
	('Marcel Holzmann', 'Austria', 'holzmann'),
	('Rodolfo Cardoso', 'Portugal', 'rodolfo cardoso'),
	('Rodolfo Cardoso', 'Portugal', 'cardoso'),
	('Mats Haakenstad', 'Norway', 'mats haakenstad'),
	('Mats Haakenstad', 'Norway', 'haakenstad'),
	('Joseph Boyamba', 'Germany', 'joseph boyamba'),
	('Joseph Boyamba', 'Germany', 'boyamba'),
	('Brahim Konaté', 'France', 'brahim konate'),
	('Brahim Konaté', 'France', 'konate'),
	('Stiven Vega', 'Colombia', 'stiven vega'),
	('Stiven Vega', 'Colombia', 'vega'),
	('Mateusz Kupczak', 'Poland', 'mateusz kupczak'),
	('Mateusz Kupczak', 'Poland', 'kupczak'),
	('Pedro Mateus', 'Portugal', 'pedro mateus'),
	('Pedro Mateus', 'Portugal', 'mateus'),
	('Milan Kocić', 'Slovenia', 'milan kocic'),
	('Milan Kocić', 'Slovenia', 'kocic'),
	('Gergely Bobál', 'Hungary', 'bobal'),
	('Gergely Bobál', 'Hungary', 'gergely bobal'),
	('Greg Bolger', 'Republic of Ireland', 'bolger'),
	('Greg Bolger', 'Republic of Ireland', 'greg bolger'),
	('Leonel Picco', 'Argentina', 'leonel picco'),
	('Leonel Picco', 'Argentina', 'picco'),
	('Jack Roles', 'Cyprus', 'jack roles'),
	('Jack Roles', 'Cyprus', 'roles'),
	('Maximilian Krauß', 'Germany', 'maximilian krau'),
	('Maximilian Krauß', 'Germany', 'krau'),
	('Tom Müller', 'Germany', 'muller'),
	('Tom Müller', 'Germany', 'tom muller'),
	('Víctor López', 'Spain', 'victor lopez'),
	('Víctor López', 'Spain', 'lopez'),
	('Keanan Bennetts', 'England', 'bennetts'),
	('Keanan Bennetts', 'England', 'keanan bennetts'),
	('Wayde Jooste', 'South Africa', 'wayde jooste'),
	('Wayde Jooste', 'South Africa', 'jooste'),
	('Valmir Berisha', 'Sweden', 'berisha'),
	('Valmir Berisha', 'Sweden', 'valmir berisha'),
	('Luis Cangá', 'Ecuador', 'luis canga'),
	('Luis Cangá', 'Ecuador', 'canga'),
	('Nazareno Colombo', 'Argentina', 'colombo'),
	('Nazareno Colombo', 'Argentina', 'nazareno colombo'),
	('Ersin Zehir', 'Germany', 'zehir'),
	('Ersin Zehir', 'Germany', 'ersin zehir'),
	('Linda Mntambo', 'South Africa', 'linda mntambo'),
	('Linda Mntambo', 'South Africa', 'mntambo'),
	('Nathan Ralph', 'England', 'nathan ralph'),
	('Nathan Ralph', 'England', 'ralph'),
	('Ali Hazazi', 'Saudi Arabia', 'ali hazazi'),
	('Ali Hazazi', 'Saudi Arabia', 'hazazi'),
	('Patryk Kun', 'Poland', 'patryk kun'),
	('Patryk Kun', 'Poland', 'kun'),
	('Han Hee Hoon', 'Korea Republic', 'han hee hoon'),
	('Han Hee Hoon', 'Korea Republic', 'hoon'),
	('Reynaldo', 'Brazil', 'reynaldo'),
	('Sam Hughes', 'England', 'hughes'),
	('Sam Hughes', 'England', 'sam hughes'),
	('Branislav Pindroch', 'Slovakia', 'pindroch'),
	('Branislav Pindroch', 'Slovakia', 'branislav pindroch'),
	('Mickel Miller', 'England', 'miller'),
	('Mickel Miller', 'England', 'mickel miller'),
	('Pascu', 'Spain', 'pascu'),
	('Mateo Bajamich', 'Argentina', 'bajamich'),
	('Mateo Bajamich', 'Argentina', 'mateo bajamich'),
	('Jordan Houghton', 'England', 'jordan houghton'),
	('Jordan Houghton', 'England', 'houghton'),
	('Ilmari Niskanen', 'Finland', 'ilmari niskanen'),
	('Ilmari Niskanen', 'Finland', 'niskanen'),
	('Simon Sohm', 'Switzerland', 'sohm'),
	('Simon Sohm', 'Switzerland', 'simon sohm'),
	('Karamoko Dembélé', 'England', 'karamoko dembele'),
	('Karamoko Dembélé', 'England', 'dembele'),
	('Juan Manuel Ramos', 'Uruguay', 'ramos'),
	('Juan Manuel Ramos', 'Uruguay', 'juan manuel ramos'),
	('Haji Wright', 'United States', 'wright'),
	('Haji Wright', 'United States', 'haji wright'),
	('Feng Jin', 'China PR', 'jin'),
	('Feng Jin', 'China PR', 'feng jin'),
	('Marcus Mathisen', 'Denmark', 'marcus mathisen'),
	('Marcus Mathisen', 'Denmark', 'mathisen'),
	('Nathan McGinley', 'England', 'mcginley'),
	('Nathan McGinley', 'England', 'nathan mcginley'),
	('Pelayo Suárez', 'Spain', 'suarez'),
	('Pelayo Suárez', 'Spain', 'pelayo suarez'),
	('Dylan Levitt', 'Wales', 'levitt'),
	('Dylan Levitt', 'Wales', 'dylan levitt'),
	('Sergio Adrián', 'Bolivia', 'sergio adrian'),
	('Sergio Adrián', 'Bolivia', 'adrian'),
	('Colin Daniel', 'England', 'daniel'),
	('Colin Daniel', 'England', 'colin daniel'),
	('Matías Villarreal', 'Argentina', 'villarreal'),
	('Matías Villarreal', 'Argentina', 'matias villarreal'),
	('Jorge Pereira', 'Portugal', 'jorge pereira'),
	('Jorge Pereira', 'Portugal', 'pereira'),
	('Diego Osio', 'Venezuela', 'diego osio'),
	('Diego Osio', 'Venezuela', 'osio'),
	('Damián Ezequiel Petcoff', 'Argentina', 'damian ezequiel petcoff'),
	('Damián Ezequiel Petcoff', 'Argentina', 'petcoff'),
	('Nicolai Brock-Madsen', 'Denmark', 'nicolai brockmadsen'),
	('Nicolai Brock-Madsen', 'Denmark', 'brockmadsen'),
	('Daniel Florea', 'Romania', 'daniel florea'),
	('Daniel Florea', 'Romania', 'florea'),
	('Luke Norris', 'England', 'luke norris'),
	('Luke Norris', 'England', 'norris'),
	('Gervane Kastaneer', 'Curacao', 'kastaneer'),
	('Gervane Kastaneer', 'Curacao', 'gervane kastaneer'),
	('Michele Rigione', 'Italy', 'rigione'),
	('Michele Rigione', 'Italy', 'michele rigione'),
	('Gino Fechner', 'Germany', 'fechner'),
	('Gino Fechner', 'Germany', 'gino fechner'),
	('Niclas Stierlin', 'Germany', 'niclas stierlin'),
	('Niclas Stierlin', 'Germany', 'stierlin'),
	('Jorris Romil', 'France', 'jorris romil'),
	('Jorris Romil', 'France', 'romil'),
	('Joaquín Blázquez', 'Argentina', 'blazquez'),
	('Joaquín Blázquez', 'Argentina', 'joaquin blazquez'),
	('Jordan Tillson', 'England', 'tillson'),
	('Jordan Tillson', 'England', 'jordan tillson'),
	('Henrique Trevisan', 'Brazil', 'henrique trevisan'),
	('Henrique Trevisan', 'Brazil', 'trevisan'),
	('Clarke Oduor', 'Kenya', 'oduor'),
	('Clarke Oduor', 'Kenya', 'clarke oduor'),
	('Diego Barreto', 'Paraguay', 'barreto'),
	('Diego Barreto', 'Paraguay', 'diego barreto'),
	('Patrick Choroba', 'Germany', 'patrick choroba'),
	('Patrick Choroba', 'Germany', 'choroba'),
	('Ricardo Schutte', 'Portugal', 'ricardo schutte'),
	('Ricardo Schutte', 'Portugal', 'schutte'),
	('Bryan Nouvier', 'France', 'nouvier'),
	('Bryan Nouvier', 'France', 'bryan nouvier'),
	('Kevin Romay', 'Bolivia', 'kevin romay'),
	('Kevin Romay', 'Bolivia', 'romay'),
	('Moustapha Seck', 'Senegal', 'seck'),
	('Moustapha Seck', 'Senegal', 'moustapha seck'),
	('Mickey Demetriou', 'England', 'demetriou'),
	('Mickey Demetriou', 'England', 'mickey demetriou'),
	('Elder Arauz', 'Bolivia', 'elder arauz'),
	('Elder Arauz', 'Bolivia', 'arauz'),
	('Lucien Agoume', 'France', 'agoume'),
	('Lucien Agoume', 'France', 'lucien agoume'),
	('Massimiliano Mangraviti', 'Italy', 'massimiliano mangraviti'),
	('Massimiliano Mangraviti', 'Italy', 'mangraviti'),
	('Hervé Kambou', 'Ivory Coast', 'herve kambou'),
	('Hervé Kambou', 'Ivory Coast', 'kambou'),
	('David Schnegg', 'Austria', 'schnegg'),
	('David Schnegg', 'Austria', 'david schnegg'),
	('Aaron Schoenfeld', 'United States', 'schoenfeld'),
	('Aaron Schoenfeld', 'United States', 'aaron schoenfeld'),
	('Alex Pattison', 'England', 'alex pattison'),
	('Alex Pattison', 'England', 'pattison'),
	('Keisuke Iwashita', 'Japan', 'keisuke iwashita'),
	('Keisuke Iwashita', 'Japan', 'iwashita'),
	('David Gugganig', 'Austria', 'david gugganig'),
	('David Gugganig', 'Austria', 'gugganig'),
	('Mohammed Al Fehaid', 'Saudi Arabia', 'fehaid'),
	('Mohammed Al Fehaid', 'Saudi Arabia', 'mohammed al fehaid'),
	('Mohamed Bayo', 'France', 'mohamed bayo'),
	('Mohamed Bayo', 'France', 'bayo')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';