INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Nathan Thompson', 'England', 'player'),
	('Rubert Quijada', 'Venezuela', 'player'),
	('Bruno Godeau', 'Belgium', 'player'),
	('Dardo Miloc', 'Argentina', 'player'),
	('Clint Leemans', 'Netherlands', 'player'),
	('Rene Swete', 'Austria', 'player'),
	('Emmanuel Iyoha', 'Germany', 'player'),
	('Nicky Adams', 'Wales', 'player'),
	('Takahiro Sekine', 'Japan', 'player'),
	('Stefano Callegari', 'Argentina', 'player'),
	('Satrústegui', 'Spain', 'player'),
	('Dominik Baumgartner', 'Austria', 'player'),
	('Miloš Pantović', 'Serbia', 'player'),
	('Tomoya Inukai', 'Japan', 'player'),
	('Diego Moreno', 'Colombia', 'player'),
	('Mohamed Daramy', 'Denmark', 'player'),
	('Kaxe', 'Spain', 'player'),
	('César Munder', 'Chile', 'player'),
	('Adaílton', 'Brazil', 'player'),
	('Guillem Molina', 'Spain', 'player'),
	('Bobby Wood', 'United States', 'player'),
	('Andrés Prieto', 'Spain', 'player'),
	('Dominic Ball', 'England', 'player'),
	('Greg Garza', 'United States', 'player'),
	('Antônio Carlos', 'Brazil', 'player'),
	('Mario Risso', 'Uruguay', 'player'),
	('Jonathan Bornstein', 'United States', 'player'),
	('Craig Noone', 'England', 'player'),
	('Dennis Kempe', 'Germany', 'player'),
	('Mario Rondón', 'Venezuela', 'player'),
	('Paulo Da Silva', 'Paraguay', 'player'),
	('Christian Klem', 'Austria', 'player'),
	('Lewis MacLeod', 'Scotland', 'player'),
	('Gonzalo Verdú', 'Spain', 'player'),
	('Andrei Chindriș', 'Romania', 'player'),
	('Christian Doidge', 'Wales', 'player'),
	('Petar Golubović', 'Serbia', 'player'),
	('Hekuran Kryeziu', 'Kosovo', 'player'),
	('Matt Crooks', 'England', 'player'),
	('Bruno Soares', 'Brazil', 'player'),
	('Jan Thielmann', 'Germany', 'player'),
	('Kevin Castañeda', 'Mexico', 'player'),
	('Misael Domínguez', 'Mexico', 'player'),
	('Ryo Takeuchi', 'Japan', 'player'),
	('Jakob Nerwinski', 'United States', 'player'),
	('Hervé Bazile', 'Haiti', 'player'),
	('Pablo Larrea', 'Spain', 'player'),
	('Ray Vanegas', 'Colombia', 'player'),
	('Taylan Antalyalı', 'Turkey', 'player'),
	('Björn Kopplin', 'Germany', 'player'),
	('Yasuki Kimoto', 'Japan', 'player'),
	('Bram van Polen', 'Netherlands', 'player'),
	('Sebastian Eriksson', 'Sweden', 'player'),
	('Dominik Stahl', 'Germany', 'player'),
	('Fabian Koch', 'Austria', 'player'),
	('Dominic Gape', 'England', 'player'),
	('Jung Seok Hwa', 'Korea Republic', 'player'),
	('Mats Knoester', 'Netherlands', 'player'),
	('Luuk Koopmans', 'Netherlands', 'player'),
	('Tesho Akindele', 'Canada', 'player'),
	('Yacouba Coulibaly', 'Burkina Faso', 'player'),
	('Jeisson Vargas', 'Chile', 'player'),
	('Josh Magennis', 'Northern Ireland', 'player'),
	('Mohammed Al Kuwaykibi', 'Saudi Arabia', 'player'),
	('Dylan Saint-Louis', 'Congo', 'player'),
	('James Bree', 'England', 'player'),
	('Keanu Baccus', 'Australia', 'player'),
	('Charalampos Lykogiannis', 'Greece', 'player'),
	('Lukáš Droppa', 'Czech Republic', 'player'),
	('Andrew Redmayne', 'Australia', 'player'),
	('Emir Karic', 'Austria', 'player'),
	('Denis Will Poha', 'France', 'player'),
	('Aitor Ruibal', 'Spain', 'player'),
	('Markus Lackner', 'Austria', 'player'),
	('Mathías Corujo', 'Uruguay', 'player'),
	('Kim Do Hyeok', 'Korea Republic', 'player'),
	('Fernando Elizari', 'Argentina', 'player'),
	('Adam Karabec', 'Czech Republic', 'player'),
	('Tom Clarke', 'England', 'player'),
	('Ángelo Gabrielli', 'Uruguay', 'player'),
	('Miguel', 'Spain', 'player'),
	('Adama Mbengue', 'Senegal', 'player'),
	('Linus Hallenius', 'Sweden', 'player'),
	('Dylan Batubinsika', 'France', 'player'),
	('Shota Kaneko', 'Japan', 'player'),
	('Kristopher Vida', 'Hungary', 'player'),
	('Juan Acosta', 'Uruguay', 'player'),
	('Bryan Oviedo', 'Costa Rica', 'player'),
	('Matthías Vilhjálmsson', 'Iceland', 'player'),
	('Sakıb Aytaç', 'Turkey', 'player'),
	('David Stockdale', 'England', 'player'),
	('Ante Puljić', 'Croatia', 'player'),
	('Marco Schuster', 'Germany', 'player'),
	('Zhao Mingjian', 'China PR', 'player'),
	('David Wotherspoon', 'Canada', 'player'),
	('Alexandre Olliero', 'France', 'player'),
	('Mark Beevers', 'England', 'player'),
	('Joel Graterol', 'Venezuela', 'player'),
	('Ben Amos', 'England', 'player'),
	('Joseph Amoah', 'Ghana', 'player'),
	('Jack Grimmer', 'Scotland', 'player'),
	('Eduardo Aranda', 'Paraguay', 'player'),
	('Emmanuel Rivière', 'France', 'player'),
	('Savvas Gentsoglou', 'Greece', 'player'),
	('İlhan Parlak', 'Turkey', 'player'),
	('Matthew Pennington', 'England', 'player'),
	('Lim Chai Min', 'Korea Republic', 'player'),
	('Kevin Peralta', 'Ecuador', 'player'),
	('Hjörtur Hermannsson', 'Iceland', 'player'),
	('Haris Duljević', 'Bosnia Herzegovina', 'player'),
	('Oliver Christensen', 'Denmark', 'player'),
	('André Rømer', 'Denmark', 'player'),
	('Mohammed Al Fatil', 'Saudi Arabia', 'player'),
	('Facundo Colidio', 'Argentina', 'player'),
	('Frantzdy Pierrot', 'Haiti', 'player'),
	('Rasmus Thelander', 'Denmark', 'player'),
	('Koji Suzuki', 'Japan', 'player'),
	('Andrei Ivan', 'Romania', 'player'),
	('Mateusz Wieteska', 'Poland', 'player'),
	('Ioannis Gelios', 'Greece', 'player'),
	('Marco Meilinger', 'Austria', 'player'),
	('Kristoffer Barmen', 'Norway', 'player'),
	('Juan Agudelo', 'United States', 'player'),
	('Kearyn Baccus', 'Australia', 'player'),
	('Tiago Dantas', 'Portugal', 'player'),
	('Yuki Soma', 'Japan', 'player'),
	('Ivan Fiolić', 'Croatia', 'player'),
	('Markus Kuster', 'Austria', 'player'),
	('Philipp Ziereis', 'Germany', 'player'),
	('Deni Hočko', 'Montenegro', 'player'),
	('Francisco Rodríguez', 'Colombia', 'player'),
	('Rafael Barbosa', 'Portugal', 'player'),
	('Varol Tasar', 'Germany', 'player'),
	('Kjell Scherpen', 'Netherlands', 'player'),
	('Mitchell Duke', 'Australia', 'player'),
	('Thorsten Kirschbaum', 'Germany', 'player'),
	('Jesús Pretell', 'Peru', 'player'),
	('Anfernee Dijksteel', 'Netherlands', 'player'),
	('Jonas', 'Brazil', 'player'),
	('Moi Delgado', 'Spain', 'player'),
	('Brice Maubleu', 'France', 'player'),
	('Xiao Zhi', 'China PR', 'player'),
	('Jack Clarke', 'England', 'player'),
	('Adrián Diéguez', 'Spain', 'player'),
	('Muğdat Çelik', 'Turkey', 'player'),
	('Alejandro Araque', 'Venezuela', 'player'),
	('Jordan Teze', 'Netherlands', 'player'),
	('Mario Sonnleitner', 'Austria', 'player'),
	('Bartosz Nowak', 'Poland', 'player'),
	('José Cevallos', 'Ecuador', 'player'),
	('Daouda Karamoko Bamba', 'Ivory Coast', 'player'),
	('Kevin Wolze', 'Germany', 'player'),
	('Raúl Osorio', 'Chile', 'player'),
	('Deng Hanwen', 'China PR', 'player'),
	('Philip Türpitz', 'Germany', 'player'),
	('Álex Blanco', 'Spain', 'player'),
	('Benjamín Rollheiser', 'Argentina', 'player'),
	('Eddy Silvestre', 'Azerbaijan', 'player'),
	('Tom Baumgart', 'Germany', 'player'),
	('Erik Jirka', 'Slovakia', 'player'),
	('Fatos Bećiraj', 'Montenegro', 'player'),
	('Sam Lundholm', 'Sweden', 'player'),
	('Tayfur Bingöl', 'Turkey', 'player'),
	('Kelvin Arase', 'Austria', 'player'),
	('Karol Mets', 'Estonia', 'player'),
	('Giorgi Papunashvili', 'Georgia', 'player'),
	('Kevin Mercado', 'Ecuador', 'player'),
	('Quentin Maceiras', 'Switzerland', 'player'),
	('Anderson Santamaría', 'Peru', 'player'),
	('Simon Banza', 'France', 'player'),
	('Nemanja Rnić', 'Serbia', 'player'),
	('Juan Hernández', 'Spain', 'player'),
	('Santiago Rosales', 'Argentina', 'player'),
	('Sebastian Mrowca', 'Poland', 'player'),
	('Mansour Al Harbi', 'Saudi Arabia', 'player'),
	('Stefan Schimmer', 'Germany', 'player'),
	('Tomáš Pekhart', 'Czech Republic', 'player'),
	('Alex Bono', 'United States', 'player'),
	('Jon Toral', 'Spain', 'player'),
	('Paxton Pomykal', 'United States', 'player'),
	('Sam Field', 'England', 'player'),
	('John Mousinho', 'England', 'player'),
	('Andrés Ríos', 'Argentina', 'player'),
	('Kasper Larsen', 'Denmark', 'player'),
	('Fabian Herbers', 'Germany', 'player'),
	('Nick Hagglund', 'United States', 'player'),
	('Jonathan Leko', 'England', 'player'),
	('Dimitrios Nikolaou', 'Greece', 'player'),
	('Lucas Woudenberg', 'Netherlands', 'player'),
	('Javi Jiménez', 'Spain', 'player'),
	('Ferris N''Goma', 'France', 'player'),
	('Ibrahima Camará', 'Guinea', 'player'),
	('Daniel Lopar', 'Switzerland', 'player'),
	('Gregory Wüthrich', 'Switzerland', 'player'),
	('Siphesihle Ndlovu', 'South Africa', 'player'),
	('Lucas Perrin', 'France', 'player'),
	('Christian Bravo', 'Chile', 'player'),
	('Jordan Clark', 'England', 'player'),
	('Denis Thomalla', 'Germany', 'player'),
	('Auston Trusty', 'United States', 'player'),
	('Marco Bürki', 'Switzerland', 'player'),
	('Danilo Santacruz', 'Paraguay', 'player'),
	('Yun Suk Young', 'Korea Republic', 'player'),
	('Pedro Velasco', 'Ecuador', 'player'),
	('Andreas Albers', 'Denmark', 'player'),
	('Marvin Vallecilla', 'Colombia', 'player'),
	('Fredrik Semb Berge', 'Norway', 'player'),
	('Francisco Moura', 'Portugal', 'player'),
	('Sammie Szmodics', 'England', 'player'),
	('Tomoya Koyamatsu', 'Japan', 'player'),
	('Manuel Palacios', 'Colombia', 'player'),
	('Mikkel Desler', 'Denmark', 'player'),
	('Nika Kacharava', 'Georgia', 'player'),
	('Lars Krogh Gerson', 'Luxembourg', 'player'),
	('Jefferson Orejuela', 'Ecuador', 'player'),
	('Beni Baningime', 'DR Congo', 'player'),
	('Fabien Ourega', 'France', 'player'),
	('Erickson Gallardo', 'Venezuela', 'player'),
	('Danny Post', 'Netherlands', 'player'),
	('Tim Albutat', 'Germany', 'player'),
	('Benjamin Pranter', 'Austria', 'player'),
	('Ikromjon Alibaev', 'Uzbekistan', 'player'),
	('Samuel Sosa', 'Venezuela', 'player'),
	('Simone Aresti', 'Italy', 'player'),
	('Fernando Guerrero', 'Ecuador', 'player'),
	('Abdulmajeed Al Sulayhim', 'Saudi Arabia', 'player'),
	('Sinan Bakış', 'Turkey', 'player'),
	('Yanis Merdji', 'France', 'player'),
	('Sebastian Mai', 'Germany', 'player'),
	('Stone Mambo', 'DR Congo', 'player'),
	('Volodymyr Kostevych', 'Ukraine', 'player'),
	('Krzysztof Kamiński', 'Poland', 'player'),
	('Hicham Boussefiane', 'Morocco', 'player'),
	('Hector Jimenez', 'United States', 'player'),
	('Cristian Cedrés', 'Spain', 'player'),
	('Ross McCrorie', 'Scotland', 'player'),
	('Biagio Meccariello', 'Italy', 'player'),
	('Hólmar Örn Eyjólfsson', 'Iceland', 'player'),
	('Denis Haruț', 'Romania', 'player'),
	('Mo El Hankouri', 'Morocco', 'player'),
	('Mohammed Saeid', 'Eritrea', 'player'),
	('Ben Sweat', 'United States', 'player'),
	('Manuel Castro', 'Uruguay', 'player'),
	('Alexander Bah', 'Denmark', 'player'),
	('Kim Min Hyeok', 'Korea Republic', 'player'),
	('Diego Oyarzún', 'Chile', 'player'),
	('Dujon Sterling', 'England', 'player'),
	('Jur Schryvers', 'Belgium', 'player'),
	('Johan Carbonero', 'Colombia', 'player'),
	('Przemysław Tytoń', 'Poland', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Nathan Thompson', 'England', 'thompson'),
	('Nathan Thompson', 'England', 'nathan thompson'),
	('Rubert Quijada', 'Venezuela', 'quijada'),
	('Rubert Quijada', 'Venezuela', 'rubert quijada'),
	('Bruno Godeau', 'Belgium', 'bruno godeau'),
	('Bruno Godeau', 'Belgium', 'godeau'),
	('Dardo Miloc', 'Argentina', 'miloc'),
	('Dardo Miloc', 'Argentina', 'dardo miloc'),
	('Clint Leemans', 'Netherlands', 'clint leemans'),
	('Clint Leemans', 'Netherlands', 'leemans'),
	('Rene Swete', 'Austria', 'swete'),
	('Rene Swete', 'Austria', 'rene swete'),
	('Emmanuel Iyoha', 'Germany', 'iyoha'),
	('Emmanuel Iyoha', 'Germany', 'emmanuel iyoha'),
	('Nicky Adams', 'Wales', 'nicky adams'),
	('Nicky Adams', 'Wales', 'adams'),
	('Takahiro Sekine', 'Japan', 'sekine'),
	('Takahiro Sekine', 'Japan', 'takahiro sekine'),
	('Stefano Callegari', 'Argentina', 'callegari'),
	('Stefano Callegari', 'Argentina', 'stefano callegari'),
	('Satrústegui', 'Spain', 'satrustegui'),
	('Dominik Baumgartner', 'Austria', 'baumgartner'),
	('Dominik Baumgartner', 'Austria', 'dominik baumgartner'),
	('Miloš Pantović', 'Serbia', 'milos pantovic'),
	('Miloš Pantović', 'Serbia', 'pantovic'),
	('Tomoya Inukai', 'Japan', 'inukai'),
	('Tomoya Inukai', 'Japan', 'tomoya inukai'),
	('Diego Moreno', 'Colombia', 'moreno'),
	('Diego Moreno', 'Colombia', 'diego moreno'),
	('Mohamed Daramy', 'Denmark', 'mohamed daramy'),
	('Mohamed Daramy', 'Denmark', 'daramy'),
	('Kaxe', 'Spain', 'kaxe'),
	('César Munder', 'Chile', 'munder'),
	('César Munder', 'Chile', 'cesar munder'),
	('Adaílton', 'Brazil', 'adailton'),
	('Guillem Molina', 'Spain', 'molina'),
	('Guillem Molina', 'Spain', 'guillem molina'),
	('Bobby Wood', 'United States', 'bobby wood'),
	('Bobby Wood', 'United States', 'wood'),
	('Andrés Prieto', 'Spain', 'prieto'),
	('Andrés Prieto', 'Spain', 'andres prieto'),
	('Dominic Ball', 'England', 'ball'),
	('Dominic Ball', 'England', 'dominic ball'),
	('Greg Garza', 'United States', 'garza'),
	('Greg Garza', 'United States', 'greg garza'),
	('Antônio Carlos', 'Brazil', 'carlos'),
	('Antônio Carlos', 'Brazil', 'antonio carlos'),
	('Mario Risso', 'Uruguay', 'risso'),
	('Mario Risso', 'Uruguay', 'mario risso'),
	('Jonathan Bornstein', 'United States', 'jonathan bornstein'),
	('Jonathan Bornstein', 'United States', 'bornstein'),
	('Craig Noone', 'England', 'craig noone'),
	('Craig Noone', 'England', 'noone'),
	('Dennis Kempe', 'Germany', 'kempe'),
	('Dennis Kempe', 'Germany', 'dennis kempe'),
	('Mario Rondón', 'Venezuela', 'mario rondon'),
	('Mario Rondón', 'Venezuela', 'rondon'),
	('Paulo Da Silva', 'Paraguay', 'silva'),
	('Paulo Da Silva', 'Paraguay', 'paulo da silva'),
	('Christian Klem', 'Austria', 'klem'),
	('Christian Klem', 'Austria', 'christian klem'),
	('Lewis MacLeod', 'Scotland', 'lewis macleod'),
	('Lewis MacLeod', 'Scotland', 'macleod'),
	('Gonzalo Verdú', 'Spain', 'gonzalo verdu'),
	('Gonzalo Verdú', 'Spain', 'verdu'),
	('Andrei Chindriș', 'Romania', 'andrei chindris'),
	('Andrei Chindriș', 'Romania', 'chindris'),
	('Christian Doidge', 'Wales', 'christian doidge'),
	('Christian Doidge', 'Wales', 'doidge'),
	('Petar Golubović', 'Serbia', 'golubovic'),
	('Petar Golubović', 'Serbia', 'petar golubovic'),
	('Hekuran Kryeziu', 'Kosovo', 'kryeziu'),
	('Hekuran Kryeziu', 'Kosovo', 'hekuran kryeziu'),
	('Matt Crooks', 'England', 'matt crooks'),
	('Matt Crooks', 'England', 'crooks'),
	('Bruno Soares', 'Brazil', 'bruno soares'),
	('Bruno Soares', 'Brazil', 'soares'),
	('Jan Thielmann', 'Germany', 'thielmann'),
	('Jan Thielmann', 'Germany', 'jan thielmann'),
	('Kevin Castañeda', 'Mexico', 'kevin castaneda'),
	('Kevin Castañeda', 'Mexico', 'castaneda'),
	('Misael Domínguez', 'Mexico', 'dominguez'),
	('Misael Domínguez', 'Mexico', 'misael dominguez'),
	('Ryo Takeuchi', 'Japan', 'ryo takeuchi'),
	('Ryo Takeuchi', 'Japan', 'takeuchi'),
	('Jakob Nerwinski', 'United States', 'nerwinski'),
	('Jakob Nerwinski', 'United States', 'jakob nerwinski'),
	('Hervé Bazile', 'Haiti', 'herve bazile'),
	('Hervé Bazile', 'Haiti', 'bazile'),
	('Pablo Larrea', 'Spain', 'larrea'),
	('Pablo Larrea', 'Spain', 'pablo larrea'),
	('Ray Vanegas', 'Colombia', 'ray vanegas'),
	('Ray Vanegas', 'Colombia', 'vanegas'),
	('Taylan Antalyalı', 'Turkey', 'antalyal'),
	('Taylan Antalyalı', 'Turkey', 'taylan antalyal'),
	('Björn Kopplin', 'Germany', 'kopplin'),
	('Björn Kopplin', 'Germany', 'bjorn kopplin'),
	('Yasuki Kimoto', 'Japan', 'kimoto'),
	('Yasuki Kimoto', 'Japan', 'yasuki kimoto'),
	('Bram van Polen', 'Netherlands', 'bram van polen'),
	('Bram van Polen', 'Netherlands', 'polen'),
	('Sebastian Eriksson', 'Sweden', 'sebastian eriksson'),
	('Sebastian Eriksson', 'Sweden', 'eriksson'),
	('Dominik Stahl', 'Germany', 'dominik stahl'),
	('Dominik Stahl', 'Germany', 'stahl'),
	('Fabian Koch', 'Austria', 'fabian koch'),
	('Fabian Koch', 'Austria', 'koch'),
	('Dominic Gape', 'England', 'gape'),
	('Dominic Gape', 'England', 'dominic gape'),
	('Jung Seok Hwa', 'Korea Republic', 'hwa'),
	('Jung Seok Hwa', 'Korea Republic', 'jung seok hwa'),
	('Mats Knoester', 'Netherlands', 'knoester'),
	('Mats Knoester', 'Netherlands', 'mats knoester'),
	('Luuk Koopmans', 'Netherlands', 'luuk koopmans'),
	('Luuk Koopmans', 'Netherlands', 'koopmans'),
	('Tesho Akindele', 'Canada', 'tesho akindele'),
	('Tesho Akindele', 'Canada', 'akindele'),
	('Yacouba Coulibaly', 'Burkina Faso', 'coulibaly'),
	('Yacouba Coulibaly', 'Burkina Faso', 'yacouba coulibaly'),
	('Jeisson Vargas', 'Chile', 'jeisson vargas'),
	('Jeisson Vargas', 'Chile', 'vargas'),
	('Josh Magennis', 'Northern Ireland', 'magennis'),
	('Josh Magennis', 'Northern Ireland', 'josh magennis'),
	('Mohammed Al Kuwaykibi', 'Saudi Arabia', 'mohammed al kuwaykibi'),
	('Mohammed Al Kuwaykibi', 'Saudi Arabia', 'kuwaykibi'),
	('Dylan Saint-Louis', 'Congo', 'saintlouis'),
	('Dylan Saint-Louis', 'Congo', 'dylan saintlouis'),
	('James Bree', 'England', 'james bree'),
	('James Bree', 'England', 'bree'),
	('Keanu Baccus', 'Australia', 'keanu baccus'),
	('Keanu Baccus', 'Australia', 'baccus'),
	('Charalampos Lykogiannis', 'Greece', 'lykogiannis'),
	('Charalampos Lykogiannis', 'Greece', 'charalampos lykogiannis'),
	('Lukáš Droppa', 'Czech Republic', 'lukas droppa'),
	('Lukáš Droppa', 'Czech Republic', 'droppa'),
	('Andrew Redmayne', 'Australia', 'redmayne'),
	('Andrew Redmayne', 'Australia', 'andrew redmayne'),
	('Emir Karic', 'Austria', 'karic'),
	('Emir Karic', 'Austria', 'emir karic'),
	('Denis Will Poha', 'France', 'denis will poha'),
	('Denis Will Poha', 'France', 'poha'),
	('Aitor Ruibal', 'Spain', 'aitor ruibal'),
	('Aitor Ruibal', 'Spain', 'ruibal'),
	('Markus Lackner', 'Austria', 'lackner'),
	('Markus Lackner', 'Austria', 'markus lackner'),
	('Mathías Corujo', 'Uruguay', 'mathias corujo'),
	('Mathías Corujo', 'Uruguay', 'corujo'),
	('Kim Do Hyeok', 'Korea Republic', 'hyeok'),
	('Kim Do Hyeok', 'Korea Republic', 'kim do hyeok'),
	('Fernando Elizari', 'Argentina', 'fernando elizari'),
	('Fernando Elizari', 'Argentina', 'elizari'),
	('Adam Karabec', 'Czech Republic', 'adam karabec'),
	('Adam Karabec', 'Czech Republic', 'karabec'),
	('Tom Clarke', 'England', 'clarke'),
	('Tom Clarke', 'England', 'tom clarke'),
	('Ángelo Gabrielli', 'Uruguay', 'angelo gabrielli'),
	('Ángelo Gabrielli', 'Uruguay', 'gabrielli'),
	('Miguel', 'Spain', 'miguel'),
	('Adama Mbengue', 'Senegal', 'adama mbengue'),
	('Adama Mbengue', 'Senegal', 'mbengue'),
	('Linus Hallenius', 'Sweden', 'hallenius'),
	('Linus Hallenius', 'Sweden', 'linus hallenius'),
	('Dylan Batubinsika', 'France', 'dylan batubinsika'),
	('Dylan Batubinsika', 'France', 'batubinsika'),
	('Shota Kaneko', 'Japan', 'shota kaneko'),
	('Shota Kaneko', 'Japan', 'kaneko'),
	('Kristopher Vida', 'Hungary', 'kristopher vida'),
	('Kristopher Vida', 'Hungary', 'vida'),
	('Juan Acosta', 'Uruguay', 'juan acosta'),
	('Juan Acosta', 'Uruguay', 'acosta'),
	('Bryan Oviedo', 'Costa Rica', 'oviedo'),
	('Bryan Oviedo', 'Costa Rica', 'bryan oviedo'),
	('Matthías Vilhjálmsson', 'Iceland', 'matthias vilhjalmsson'),
	('Matthías Vilhjálmsson', 'Iceland', 'vilhjalmsson'),
	('Sakıb Aytaç', 'Turkey', 'sakb aytac'),
	('Sakıb Aytaç', 'Turkey', 'aytac'),
	('David Stockdale', 'England', 'david stockdale'),
	('David Stockdale', 'England', 'stockdale'),
	('Ante Puljić', 'Croatia', 'puljic'),
	('Ante Puljić', 'Croatia', 'ante puljic'),
	('Marco Schuster', 'Germany', 'marco schuster'),
	('Marco Schuster', 'Germany', 'schuster'),
	('Zhao Mingjian', 'China PR', 'zhao mingjian'),
	('Zhao Mingjian', 'China PR', 'mingjian'),
	('David Wotherspoon', 'Canada', 'wotherspoon'),
	('David Wotherspoon', 'Canada', 'david wotherspoon'),
	('Alexandre Olliero', 'France', 'olliero'),
	('Alexandre Olliero', 'France', 'alexandre olliero'),
	('Mark Beevers', 'England', 'mark beevers'),
	('Mark Beevers', 'England', 'beevers'),
	('Joel Graterol', 'Venezuela', 'graterol'),
	('Joel Graterol', 'Venezuela', 'joel graterol'),
	('Ben Amos', 'England', 'amos'),
	('Ben Amos', 'England', 'ben amos'),
	('Joseph Amoah', 'Ghana', 'amoah'),
	('Joseph Amoah', 'Ghana', 'joseph amoah'),
	('Jack Grimmer', 'Scotland', 'grimmer'),
	('Jack Grimmer', 'Scotland', 'jack grimmer'),
	('Eduardo Aranda', 'Paraguay', 'eduardo aranda'),
	('Eduardo Aranda', 'Paraguay', 'aranda'),
	('Emmanuel Rivière', 'France', 'emmanuel riviere'),
	('Emmanuel Rivière', 'France', 'riviere'),
	('Savvas Gentsoglou', 'Greece', 'gentsoglou'),
	('Savvas Gentsoglou', 'Greece', 'savvas gentsoglou'),
	('İlhan Parlak', 'Turkey', 'ilhan parlak'),
	('İlhan Parlak', 'Turkey', 'parlak'),
	('Matthew Pennington', 'England', 'pennington'),
	('Matthew Pennington', 'England', 'matthew pennington'),
	('Lim Chai Min', 'Korea Republic', 'lim chai min'),
	('Lim Chai Min', 'Korea Republic', 'min'),
	('Kevin Peralta', 'Ecuador', 'kevin peralta'),
	('Kevin Peralta', 'Ecuador', 'peralta'),
	('Hjörtur Hermannsson', 'Iceland', 'hjortur hermannsson'),
	('Hjörtur Hermannsson', 'Iceland', 'hermannsson'),
	('Haris Duljević', 'Bosnia Herzegovina', 'haris duljevic'),
	('Haris Duljević', 'Bosnia Herzegovina', 'duljevic'),
	('Oliver Christensen', 'Denmark', 'christensen'),
	('Oliver Christensen', 'Denmark', 'oliver christensen'),
	('André Rømer', 'Denmark', 'rmer'),
	('André Rømer', 'Denmark', 'andre rmer'),
	('Mohammed Al Fatil', 'Saudi Arabia', 'mohammed al fatil'),
	('Mohammed Al Fatil', 'Saudi Arabia', 'fatil'),
	('Facundo Colidio', 'Argentina', 'colidio'),
	('Facundo Colidio', 'Argentina', 'facundo colidio'),
	('Frantzdy Pierrot', 'Haiti', 'pierrot'),
	('Frantzdy Pierrot', 'Haiti', 'frantzdy pierrot'),
	('Rasmus Thelander', 'Denmark', 'thelander'),
	('Rasmus Thelander', 'Denmark', 'rasmus thelander'),
	('Koji Suzuki', 'Japan', 'koji suzuki'),
	('Koji Suzuki', 'Japan', 'suzuki'),
	('Andrei Ivan', 'Romania', 'ivan'),
	('Andrei Ivan', 'Romania', 'andrei ivan'),
	('Mateusz Wieteska', 'Poland', 'mateusz wieteska'),
	('Mateusz Wieteska', 'Poland', 'wieteska'),
	('Ioannis Gelios', 'Greece', 'ioannis gelios'),
	('Ioannis Gelios', 'Greece', 'gelios'),
	('Marco Meilinger', 'Austria', 'marco meilinger'),
	('Marco Meilinger', 'Austria', 'meilinger'),
	('Kristoffer Barmen', 'Norway', 'barmen'),
	('Kristoffer Barmen', 'Norway', 'kristoffer barmen'),
	('Juan Agudelo', 'United States', 'juan agudelo'),
	('Juan Agudelo', 'United States', 'agudelo'),
	('Kearyn Baccus', 'Australia', 'kearyn baccus'),
	('Kearyn Baccus', 'Australia', 'baccus'),
	('Tiago Dantas', 'Portugal', 'dantas'),
	('Tiago Dantas', 'Portugal', 'tiago dantas'),
	('Yuki Soma', 'Japan', 'yuki soma'),
	('Yuki Soma', 'Japan', 'soma'),
	('Ivan Fiolić', 'Croatia', 'ivan fiolic'),
	('Ivan Fiolić', 'Croatia', 'fiolic'),
	('Markus Kuster', 'Austria', 'kuster'),
	('Markus Kuster', 'Austria', 'markus kuster'),
	('Philipp Ziereis', 'Germany', 'ziereis'),
	('Philipp Ziereis', 'Germany', 'philipp ziereis'),
	('Deni Hočko', 'Montenegro', 'deni hocko'),
	('Deni Hočko', 'Montenegro', 'hocko'),
	('Francisco Rodríguez', 'Colombia', 'francisco rodriguez'),
	('Francisco Rodríguez', 'Colombia', 'rodriguez'),
	('Rafael Barbosa', 'Portugal', 'rafael barbosa'),
	('Rafael Barbosa', 'Portugal', 'barbosa'),
	('Varol Tasar', 'Germany', 'varol tasar'),
	('Varol Tasar', 'Germany', 'tasar'),
	('Kjell Scherpen', 'Netherlands', 'scherpen'),
	('Kjell Scherpen', 'Netherlands', 'kjell scherpen'),
	('Mitchell Duke', 'Australia', 'duke'),
	('Mitchell Duke', 'Australia', 'mitchell duke'),
	('Thorsten Kirschbaum', 'Germany', 'kirschbaum'),
	('Thorsten Kirschbaum', 'Germany', 'thorsten kirschbaum'),
	('Jesús Pretell', 'Peru', 'pretell'),
	('Jesús Pretell', 'Peru', 'jesus pretell'),
	('Anfernee Dijksteel', 'Netherlands', 'dijksteel'),
	('Anfernee Dijksteel', 'Netherlands', 'anfernee dijksteel'),
	('Jonas', 'Brazil', 'jonas'),
	('Moi Delgado', 'Spain', 'moi delgado'),
	('Moi Delgado', 'Spain', 'delgado'),
	('Brice Maubleu', 'France', 'maubleu'),
	('Brice Maubleu', 'France', 'brice maubleu'),
	('Xiao Zhi', 'China PR', 'zhi'),
	('Xiao Zhi', 'China PR', 'xiao zhi'),
	('Jack Clarke', 'England', 'clarke'),
	('Jack Clarke', 'England', 'jack clarke'),
	('Adrián Diéguez', 'Spain', 'adrian dieguez'),
	('Adrián Diéguez', 'Spain', 'dieguez'),
	('Muğdat Çelik', 'Turkey', 'celik'),
	('Muğdat Çelik', 'Turkey', 'mugdat celik'),
	('Alejandro Araque', 'Venezuela', 'araque'),
	('Alejandro Araque', 'Venezuela', 'alejandro araque'),
	('Jordan Teze', 'Netherlands', 'jordan teze'),
	('Jordan Teze', 'Netherlands', 'teze'),
	('Mario Sonnleitner', 'Austria', 'sonnleitner'),
	('Mario Sonnleitner', 'Austria', 'mario sonnleitner'),
	('Bartosz Nowak', 'Poland', 'bartosz nowak'),
	('Bartosz Nowak', 'Poland', 'nowak'),
	('José Cevallos', 'Ecuador', 'jose cevallos'),
	('José Cevallos', 'Ecuador', 'cevallos'),
	('Daouda Karamoko Bamba', 'Ivory Coast', 'daouda karamoko bamba'),
	('Daouda Karamoko Bamba', 'Ivory Coast', 'bamba'),
	('Kevin Wolze', 'Germany', 'wolze'),
	('Kevin Wolze', 'Germany', 'kevin wolze'),
	('Raúl Osorio', 'Chile', 'osorio'),
	('Raúl Osorio', 'Chile', 'raul osorio'),
	('Deng Hanwen', 'China PR', 'hanwen'),
	('Deng Hanwen', 'China PR', 'deng hanwen'),
	('Philip Türpitz', 'Germany', 'philip turpitz'),
	('Philip Türpitz', 'Germany', 'turpitz'),
	('Álex Blanco', 'Spain', 'alex blanco'),
	('Álex Blanco', 'Spain', 'blanco'),
	('Benjamín Rollheiser', 'Argentina', 'benjamin rollheiser'),
	('Benjamín Rollheiser', 'Argentina', 'rollheiser'),
	('Eddy Silvestre', 'Azerbaijan', 'silvestre'),
	('Eddy Silvestre', 'Azerbaijan', 'eddy silvestre'),
	('Tom Baumgart', 'Germany', 'baumgart'),
	('Tom Baumgart', 'Germany', 'tom baumgart'),
	('Erik Jirka', 'Slovakia', 'jirka'),
	('Erik Jirka', 'Slovakia', 'erik jirka'),
	('Fatos Bećiraj', 'Montenegro', 'beciraj'),
	('Fatos Bećiraj', 'Montenegro', 'fatos beciraj'),
	('Sam Lundholm', 'Sweden', 'lundholm'),
	('Sam Lundholm', 'Sweden', 'sam lundholm'),
	('Tayfur Bingöl', 'Turkey', 'tayfur bingol'),
	('Tayfur Bingöl', 'Turkey', 'bingol'),
	('Kelvin Arase', 'Austria', 'arase'),
	('Kelvin Arase', 'Austria', 'kelvin arase'),
	('Karol Mets', 'Estonia', 'karol mets'),
	('Karol Mets', 'Estonia', 'mets'),
	('Giorgi Papunashvili', 'Georgia', 'papunashvili'),
	('Giorgi Papunashvili', 'Georgia', 'giorgi papunashvili'),
	('Kevin Mercado', 'Ecuador', 'kevin mercado'),
	('Kevin Mercado', 'Ecuador', 'mercado'),
	('Quentin Maceiras', 'Switzerland', 'quentin maceiras'),
	('Quentin Maceiras', 'Switzerland', 'maceiras'),
	('Anderson Santamaría', 'Peru', 'santamaria'),
	('Anderson Santamaría', 'Peru', 'anderson santamaria'),
	('Simon Banza', 'France', 'simon banza'),
	('Simon Banza', 'France', 'banza'),
	('Nemanja Rnić', 'Serbia', 'nemanja rnic'),
	('Nemanja Rnić', 'Serbia', 'rnic'),
	('Juan Hernández', 'Spain', 'juan hernandez'),
	('Juan Hernández', 'Spain', 'hernandez'),
	('Santiago Rosales', 'Argentina', 'rosales'),
	('Santiago Rosales', 'Argentina', 'santiago rosales'),
	('Sebastian Mrowca', 'Poland', 'mrowca'),
	('Sebastian Mrowca', 'Poland', 'sebastian mrowca'),
	('Mansour Al Harbi', 'Saudi Arabia', 'harbi'),
	('Mansour Al Harbi', 'Saudi Arabia', 'mansour al harbi'),
	('Stefan Schimmer', 'Germany', 'stefan schimmer'),
	('Stefan Schimmer', 'Germany', 'schimmer'),
	('Tomáš Pekhart', 'Czech Republic', 'pekhart'),
	('Tomáš Pekhart', 'Czech Republic', 'tomas pekhart'),
	('Alex Bono', 'United States', 'alex bono'),
	('Alex Bono', 'United States', 'bono'),
	('Jon Toral', 'Spain', 'jon toral'),
	('Jon Toral', 'Spain', 'toral'),
	('Paxton Pomykal', 'United States', 'pomykal'),
	('Paxton Pomykal', 'United States', 'paxton pomykal'),
	('Sam Field', 'England', 'sam field'),
	('Sam Field', 'England', 'field'),
	('John Mousinho', 'England', 'mousinho'),
	('John Mousinho', 'England', 'john mousinho'),
	('Andrés Ríos', 'Argentina', 'rios'),
	('Andrés Ríos', 'Argentina', 'andres rios'),
	('Kasper Larsen', 'Denmark', 'larsen'),
	('Kasper Larsen', 'Denmark', 'kasper larsen'),
	('Fabian Herbers', 'Germany', 'herbers'),
	('Fabian Herbers', 'Germany', 'fabian herbers'),
	('Nick Hagglund', 'United States', 'nick hagglund'),
	('Nick Hagglund', 'United States', 'hagglund'),
	('Jonathan Leko', 'England', 'leko'),
	('Jonathan Leko', 'England', 'jonathan leko'),
	('Dimitrios Nikolaou', 'Greece', 'nikolaou'),
	('Dimitrios Nikolaou', 'Greece', 'dimitrios nikolaou'),
	('Lucas Woudenberg', 'Netherlands', 'woudenberg'),
	('Lucas Woudenberg', 'Netherlands', 'lucas woudenberg'),
	('Javi Jiménez', 'Spain', 'javi jimenez'),
	('Javi Jiménez', 'Spain', 'jimenez'),
	('Ferris N''Goma', 'France', 'ngoma'),
	('Ferris N''Goma', 'France', 'ferris ngoma'),
	('Ibrahima Camará', 'Guinea', 'camara'),
	('Ibrahima Camará', 'Guinea', 'ibrahima camara'),
	('Daniel Lopar', 'Switzerland', 'lopar'),
	('Daniel Lopar', 'Switzerland', 'daniel lopar'),
	('Gregory Wüthrich', 'Switzerland', 'wuthrich'),
	('Gregory Wüthrich', 'Switzerland', 'gregory wuthrich'),
	('Siphesihle Ndlovu', 'South Africa', 'ndlovu'),
	('Siphesihle Ndlovu', 'South Africa', 'siphesihle ndlovu'),
	('Lucas Perrin', 'France', 'perrin'),
	('Lucas Perrin', 'France', 'lucas perrin'),
	('Christian Bravo', 'Chile', 'bravo'),
	('Christian Bravo', 'Chile', 'christian bravo'),
	('Jordan Clark', 'England', 'jordan clark'),
	('Jordan Clark', 'England', 'clark'),
	('Denis Thomalla', 'Germany', 'thomalla'),
	('Denis Thomalla', 'Germany', 'denis thomalla'),
	('Auston Trusty', 'United States', 'trusty'),
	('Auston Trusty', 'United States', 'auston trusty'),
	('Marco Bürki', 'Switzerland', 'burki'),
	('Marco Bürki', 'Switzerland', 'marco burki'),
	('Danilo Santacruz', 'Paraguay', 'santacruz'),
	('Danilo Santacruz', 'Paraguay', 'danilo santacruz'),
	('Yun Suk Young', 'Korea Republic', 'young'),
	('Yun Suk Young', 'Korea Republic', 'yun suk young'),
	('Pedro Velasco', 'Ecuador', 'pedro velasco'),
	('Pedro Velasco', 'Ecuador', 'velasco'),
	('Andreas Albers', 'Denmark', 'andreas albers'),
	('Andreas Albers', 'Denmark', 'albers'),
	('Marvin Vallecilla', 'Colombia', 'vallecilla'),
	('Marvin Vallecilla', 'Colombia', 'marvin vallecilla'),
	('Fredrik Semb Berge', 'Norway', 'fredrik semb berge'),
	('Fredrik Semb Berge', 'Norway', 'berge'),
	('Francisco Moura', 'Portugal', 'francisco moura'),
	('Francisco Moura', 'Portugal', 'moura'),
	('Sammie Szmodics', 'England', 'sammie szmodics'),
	('Sammie Szmodics', 'England', 'szmodics'),
	('Tomoya Koyamatsu', 'Japan', 'tomoya koyamatsu'),
	('Tomoya Koyamatsu', 'Japan', 'koyamatsu'),
	('Manuel Palacios', 'Colombia', 'palacios'),
	('Manuel Palacios', 'Colombia', 'manuel palacios'),
	('Mikkel Desler', 'Denmark', 'desler'),
	('Mikkel Desler', 'Denmark', 'mikkel desler'),
	('Nika Kacharava', 'Georgia', 'nika kacharava'),
	('Nika Kacharava', 'Georgia', 'kacharava'),
	('Lars Krogh Gerson', 'Luxembourg', 'lars krogh gerson'),
	('Lars Krogh Gerson', 'Luxembourg', 'gerson'),
	('Jefferson Orejuela', 'Ecuador', 'jefferson orejuela'),
	('Jefferson Orejuela', 'Ecuador', 'orejuela'),
	('Beni Baningime', 'DR Congo', 'baningime'),
	('Beni Baningime', 'DR Congo', 'beni baningime'),
	('Fabien Ourega', 'France', 'fabien ourega'),
	('Fabien Ourega', 'France', 'ourega'),
	('Erickson Gallardo', 'Venezuela', 'erickson gallardo'),
	('Erickson Gallardo', 'Venezuela', 'gallardo'),
	('Danny Post', 'Netherlands', 'post'),
	('Danny Post', 'Netherlands', 'danny post'),
	('Tim Albutat', 'Germany', 'tim albutat'),
	('Tim Albutat', 'Germany', 'albutat'),
	('Benjamin Pranter', 'Austria', 'pranter'),
	('Benjamin Pranter', 'Austria', 'benjamin pranter'),
	('Ikromjon Alibaev', 'Uzbekistan', 'alibaev'),
	('Ikromjon Alibaev', 'Uzbekistan', 'ikromjon alibaev'),
	('Samuel Sosa', 'Venezuela', 'sosa'),
	('Samuel Sosa', 'Venezuela', 'samuel sosa'),
	('Simone Aresti', 'Italy', 'simone aresti'),
	('Simone Aresti', 'Italy', 'aresti'),
	('Fernando Guerrero', 'Ecuador', 'fernando guerrero'),
	('Fernando Guerrero', 'Ecuador', 'guerrero'),
	('Abdulmajeed Al Sulayhim', 'Saudi Arabia', 'sulayhim'),
	('Abdulmajeed Al Sulayhim', 'Saudi Arabia', 'abdulmajeed al sulayhim'),
	('Sinan Bakış', 'Turkey', 'baks'),
	('Sinan Bakış', 'Turkey', 'sinan baks'),
	('Yanis Merdji', 'France', 'merdji'),
	('Yanis Merdji', 'France', 'yanis merdji'),
	('Sebastian Mai', 'Germany', 'mai'),
	('Sebastian Mai', 'Germany', 'sebastian mai'),
	('Stone Mambo', 'DR Congo', 'mambo'),
	('Stone Mambo', 'DR Congo', 'stone mambo'),
	('Volodymyr Kostevych', 'Ukraine', 'kostevych'),
	('Volodymyr Kostevych', 'Ukraine', 'volodymyr kostevych'),
	('Krzysztof Kamiński', 'Poland', 'krzysztof kaminski'),
	('Krzysztof Kamiński', 'Poland', 'kaminski'),
	('Hicham Boussefiane', 'Morocco', 'hicham boussefiane'),
	('Hicham Boussefiane', 'Morocco', 'boussefiane'),
	('Hector Jimenez', 'United States', 'jimenez'),
	('Hector Jimenez', 'United States', 'hector jimenez'),
	('Cristian Cedrés', 'Spain', 'cedres'),
	('Cristian Cedrés', 'Spain', 'cristian cedres'),
	('Ross McCrorie', 'Scotland', 'mccrorie'),
	('Ross McCrorie', 'Scotland', 'ross mccrorie'),
	('Biagio Meccariello', 'Italy', 'meccariello'),
	('Biagio Meccariello', 'Italy', 'biagio meccariello'),
	('Hólmar Örn Eyjólfsson', 'Iceland', 'holmar orn eyjolfsson'),
	('Hólmar Örn Eyjólfsson', 'Iceland', 'eyjolfsson'),
	('Denis Haruț', 'Romania', 'harut'),
	('Denis Haruț', 'Romania', 'denis harut'),
	('Mo El Hankouri', 'Morocco', 'hankouri'),
	('Mo El Hankouri', 'Morocco', 'mo el hankouri'),
	('Mohammed Saeid', 'Eritrea', 'saeid'),
	('Mohammed Saeid', 'Eritrea', 'mohammed saeid'),
	('Ben Sweat', 'United States', 'ben sweat'),
	('Ben Sweat', 'United States', 'sweat'),
	('Manuel Castro', 'Uruguay', 'castro'),
	('Manuel Castro', 'Uruguay', 'manuel castro'),
	('Alexander Bah', 'Denmark', 'alexander bah'),
	('Alexander Bah', 'Denmark', 'bah'),
	('Kim Min Hyeok', 'Korea Republic', 'hyeok'),
	('Kim Min Hyeok', 'Korea Republic', 'kim min hyeok'),
	('Diego Oyarzún', 'Chile', 'diego oyarzun'),
	('Diego Oyarzún', 'Chile', 'oyarzun'),
	('Dujon Sterling', 'England', 'sterling'),
	('Dujon Sterling', 'England', 'dujon sterling'),
	('Jur Schryvers', 'Belgium', 'schryvers'),
	('Jur Schryvers', 'Belgium', 'jur schryvers'),
	('Johan Carbonero', 'Colombia', 'johan carbonero'),
	('Johan Carbonero', 'Colombia', 'carbonero'),
	('Przemysław Tytoń', 'Poland', 'przemysaw tyton'),
	('Przemysław Tytoń', 'Poland', 'tyton')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';