INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Ben Seymour', 'England', 'player'),
	('Tunmise Sobowale', 'Republic of Ireland', 'player'),
	('Karifa Yao', 'Canada', 'player'),
	('Guzmán Rodríguez', 'Uruguay', 'player'),
	('Williams Barlasina', 'Argentina', 'player'),
	('Tom Mehew', 'England', 'player'),
	('Andreas Skjøtt Foged', 'Denmark', 'player'),
	('Callum Smith', 'Scotland', 'player'),
	('Matthew Sorinola', 'England', 'player'),
	('Oh Hoo Sung', 'Korea Republic', 'player'),
	('Michael Tait', 'England', 'player'),
	('Alexander Bernhardsson', 'Sweden', 'player'),
	('Abel Moreno', 'Chile', 'player'),
	('Luca Moro', 'Italy', 'player'),
	('Emeka Nnamani', 'Denmark', 'player'),
	('Musab Habkoor', 'Saudi Arabia', 'player'),
	('Benedikt Grawe', 'Germany', 'player'),
	('György Székely', 'Hungary', 'player'),
	('Matthew Durrans', 'England', 'player'),
	('Ferhat Saglam', 'Liechtenstein', 'player'),
	('Lucas Mauragis', 'Australia', 'player'),
	('Johann Ngounou Djayo', 'Germany', 'player'),
	('Majed Al Ghamdi', 'Saudi Arabia', 'player'),
	('Jang Seong Won', 'Korea Republic', 'player'),
	('Tobias Andersson', 'Sweden', 'player'),
	('Tayvon Gray', 'United States', 'player'),
	('Christian Silva', 'Uruguay', 'player'),
	('Simon Colyn', 'Canada', 'player'),
	('Uniss Kargbo', 'Republic of Ireland', 'player'),
	('Jacob Akanyirige', 'United States', 'player'),
	('Arthur Read', 'England', 'player'),
	('Nicolás Ruíz', 'Venezuela', 'player'),
	('Ben Bottomley', 'England', 'player'),
	('Tyler Freeman', 'United States', 'player'),
	('Ben Voll', 'Germany', 'player'),
	('Christoffer Petersen', 'Denmark', 'player'),
	('Rayan Al Marshoud', 'Saudi Arabia', 'player'),
	('Filip Małek', 'Poland', 'player'),
	('Batuhan Ünsal', 'Turkey', 'player'),
	('Luca Florică', 'Romania', 'player'),
	('Harvey Saunders', 'England', 'player'),
	('Rasmus Wikström', 'Sweden', 'player'),
	('Vicente Bernedo', 'Chile', 'player'),
	('Noah Pagden', 'Australia', 'player'),
	('Johan Olstad', 'Norway', 'player'),
	('Tavio D''Almeida', 'Ivory Coast', 'player'),
	('Barry Baggley', 'Northern Ireland', 'player'),
	('Ben Sault', 'England', 'player'),
	('Jacob Trenskow', 'Denmark', 'player'),
	('Dante Sealy', 'United States', 'player'),
	('Oliver Stefánsson', 'Iceland', 'player'),
	('Brage Skaret', 'Norway', 'player'),
	('Charlie Fleming', 'Republic of Ireland', 'player'),
	('Sun Xuelong', 'China PR', 'player'),
	('Jake Peck', 'England', 'player'),
	('Jeff Caldwell', 'United States', 'player'),
	('Kristian Bernt Torgersen', 'Norway', 'player'),
	('Luke Duzel', 'Australia', 'player'),
	('Deng Yubiao', 'China PR', 'player'),
	('Liu Guobo', 'China PR', 'player'),
	('Gianluca Iannucci', 'Australia', 'player'),
	('Kamil Bielikow', 'Poland', 'player'),
	('John Freeman', 'England', 'player'),
	('Ben Blythe', 'England', 'player'),
	('Lucas Marsella', 'France', 'player'),
	('Jeong Han Min', 'Korea Republic', 'player'),
	('Jeisson Pinillo', 'Colombia', 'player'),
	('Harrison Holgate', 'England', 'player'),
	('Billy Sass-Davies', 'Wales', 'player'),
	('Vaughn Covil', 'United States', 'player'),
	('Harvey Rew', 'Wales', 'player'),
	('Kevin Yakob', 'Sweden', 'player'),
	('Beineón O''Brien-Whitmarsh', 'Republic of Ireland', 'player'),
	('Harvey Bunker', 'England', 'player'),
	('Ismaël Doukouré', 'France', 'player'),
	('Max Harris', 'England', 'player'),
	('Charlie Caton', 'Wales', 'player'),
	('Louis Khoury', 'Australia', 'player'),
	('Anders Hoff', 'Denmark', 'player'),
	('Julius Paris', 'Germany', 'player'),
	('Chen Pu', 'China PR', 'player'),
	('Mathias Madsen', 'Denmark', 'player'),
	('George Stanger', 'New Zealand', 'player'),
	('Joe Gubbins', 'England', 'player'),
	('Diego Abadía', 'Colombia', 'player'),
	('Alejandro Rojo', 'Chile', 'player'),
	('Josh Dixon', 'England', 'player'),
	('Idemudia Udebhu-Osimeh', 'England', 'player'),
	('Adelin Voinescu', 'Romania', 'player'),
	('Bruno Scorza', 'Uruguay', 'player'),
	('Liu Ziming', 'China PR', 'player'),
	('Ertuğrul Tekşen', 'Turkey', 'player'),
	('Sam Perry', 'England', 'player'),
	('Emil Kornvig', 'Denmark', 'player'),
	('Roni Arabaci', 'Denmark', 'player'),
	('Nikolaos Dosis', 'Sweden', 'player'),
	('Łukasz Seweryn', 'Poland', 'player'),
	('Jakub Sypek', 'Poland', 'player'),
	('Tyron Owusu', 'Switzerland', 'player'),
	('Stephan Seiler', 'Switzerland', 'player'),
	('Faysal Bettache', 'England', 'player'),
	('Sammie McLeod', 'England', 'player'),
	('Yin Congyao', 'China PR', 'player'),
	('Max Williamsen', 'Norway', 'player'),
	('Bughrahan Iskandar', 'China PR', 'player'),
	('Jordan Barnett', 'England', 'player'),
	('Martín Lagunes', 'Mexico', 'player'),
	('Tom Wilson', 'England', 'player'),
	('Taylor Seymour', 'England', 'player'),
	('Ronan Boyce', 'Republic of Ireland', 'player'),
	('Cian Bargary', 'Republic of Ireland', 'player'),
	('Jack Sims', 'England', 'player'),
	('Fabian Monge', 'Australia', 'player'),
	('He Yupeng', 'China PR', 'player'),
	('Maciej Bortniczuk', 'Poland', 'player'),
	('Ibrahim Bakare', 'England', 'player'),
	('James Hill', 'England', 'player'),
	('Bryan Soto', 'Chile', 'player'),
	('Tom Chamberlain', 'England', 'player'),
	('Archie Matthews', 'England', 'player'),
	('Anthony Valencia', 'Ecuador', 'player'),
	('Kim Dong Bum', 'Korea Republic', 'player'),
	('Flynn Clarke', 'England', 'player'),
	('Mads Winther', 'Denmark', 'player'),
	('Alexis Verdún', 'Paraguay', 'player'),
	('Ramón Sosa', 'Paraguay', 'player'),
	('Joe Dunne', 'England', 'player'),
	('Krzysztof Toporkiewicz', 'Poland', 'player'),
	('Oscar Vilhelmsson', 'Sweden', 'player'),
	('Tobias Fjeld Gulliksen', 'Norway', 'player'),
	('Ibrahim Al Otaibi', 'Saudi Arabia', 'player'),
	('Gonzalo Duré', 'Paraguay', 'player'),
	('Germán Contreras', 'Venezuela', 'player'),
	('Liberman Torres', 'Ecuador', 'player'),
	('Toby Holland', 'England', 'player'),
	('Matt Rush', 'England', 'player'),
	('Chen Zhechao', 'China PR', 'player'),
	('Aidan Liu', 'United States', 'player'),
	('Renné Rivas', 'Venezuela', 'player'),
	('Lucas Chang-Andersen', 'Denmark', 'player'),
	('Xavier Dziekoński', 'Poland', 'player'),
	('Stefan Colakovski', 'Australia', 'player'),
	('Joe Scally', 'United States', 'player'),
	('Ma Chongchong', 'China PR', 'player'),
	('Ryan Scott', 'Australia', 'player'),
	('Jay Matete', 'England', 'player'),
	('Shadrach Ogie', 'Republic of Ireland', 'player'),
	('Enmanuel Moreno', 'Venezuela', 'player'),
	('Henrik Falchener', 'Norway', 'player'),
	('Dan Neil', 'England', 'player'),
	('Avan Jones', 'England', 'player'),
	('Callum Rowe', 'England', 'player'),
	('Dorian Salhi', 'France', 'player'),
	('Simen Hammershaug', 'Norway', 'player'),
	('Jacob Gratton', 'England', 'player'),
	('Connor Shanks', 'England', 'player'),
	('Sander Tangvik', 'Norway', 'player'),
	('Lee Jae Won', 'Korea Republic', 'player'),
	('Andrew Mills', 'England', 'player'),
	('Dylan Asonganyi', 'England', 'player'),
	('Fabio Lopes', 'Portugal', 'player'),
	('Jeremy Quintero', 'Venezuela', 'player'),
	('Junior Quitirna', 'Guinea Bissau', 'player'),
	('Kristoffer S. Ødven', 'Norway', 'player'),
	('Oliver Rojas', 'Chile', 'player'),
	('Alejandro Machuca', 'Paraguay', 'player'),
	('Lewis Collins', 'Wales', 'player'),
	('Vicente Ramírez', 'Chile', 'player'),
	('Kai McKenzie-Lyle', 'Guyana', 'player'),
	('Wilson Barrios', 'Venezuela', 'player'),
	('Adam Petersson', 'Sweden', 'player'),
	('Ylan Gomes', 'France', 'player'),
	('Jake Trew', 'Australia', 'player'),
	('Ahanna Agbowo', 'Germany', 'player'),
	('Lucas Tomlinson', 'England', 'player'),
	('Bobby Copping', 'England', 'player'),
	('Liu Xinyu', 'China PR', 'player'),
	('Carlos Sánchez', 'Ecuador', 'player'),
	('Jhohann Yabur', 'Colombia', 'player'),
	('Joel Bagan', 'England', 'player'),
	('Patryk Królczyk', 'Poland', 'player'),
	('Jeong Yeong Ung', 'Korea Republic', 'player'),
	('Jayden Sweeney', 'England', 'player'),
	('Travis Johnson', 'England', 'player'),
	('Ben Worman', 'England', 'player'),
	('Jack Serrant-Green', 'England', 'player'),
	('José Ignacio Molina', 'Chile', 'player'),
	('Joseph Hope', 'England', 'player'),
	('Huang Chuang', 'China PR', 'player'),
	('Qian Yumiao', 'China PR', 'player'),
	('Diego Vergara', 'Chile', 'player'),
	('Benjamín Iglesias', 'Chile', 'player'),
	('Taylor Charters', 'England', 'player'),
	('Dominik Kalinowski', 'Poland', 'player'),
	('Harry Boyes', 'England', 'player'),
	('Álvaro Garrido', 'Chile', 'player'),
	('Callum Coulter', 'England', 'player'),
	('Mikkel Ceïde', 'Norway', 'player'),
	('Alex Doyle', 'England', 'player'),
	('Teng Shangkun', 'China PR', 'player'),
	('Casper Widell', 'Sweden', 'player'),
	('Johan Karlsson', 'Sweden', 'player'),
	('Lirak Hasani', 'England', 'player'),
	('Hampus Danielsson', 'Sweden', 'player'),
	('Ryan Hillier', 'Wales', 'player'),
	('Didier La Torre', 'Peru', 'player'),
	('Liam Isherwood', 'England', 'player'),
	('Jake Young', 'England', 'player'),
	('Ged Garner', 'England', 'player'),
	('Jean Belehouan', 'France', 'player'),
	('Will Shepherd', 'England', 'player'),
	('Noah De Queiroz', 'Switzerland', 'player'),
	('Asım Aksungur', 'Turkey', 'player'),
	('Jesse Devers', 'Republic of Ireland', 'player'),
	('Axel García', 'Mexico', 'player'),
	('Tom Dickens', 'England', 'player'),
	('David Croitoru', 'Romania', 'player'),
	('Dániel Csóka', 'Hungary', 'player'),
	('Felix Jakobsson', 'Sweden', 'player'),
	('Juan Carlos González', 'Venezuela', 'player'),
	('Theodore Rask', 'Sweden', 'player'),
	('Adam Foley', 'Northern Ireland', 'player'),
	('Adam O''Reilly', 'Republic of Ireland', 'player'),
	('Gao Dalun', 'China PR', 'player'),
	('Isaac Boehmer', 'Canada', 'player'),
	('Ahmed Al Enazi', 'Saudi Arabia', 'player'),
	('Rasmus Fridolf', 'Sweden', 'player'),
	('Cao Dong', 'China PR', 'player'),
	('Agustín Cano', 'Colombia', 'player'),
	('Kian Scales', 'England', 'player'),
	('Zhou Baizhao', 'China PR', 'player'),
	('Cui Lin', 'China PR', 'player'),
	('Sean Callan', 'Republic of Ireland', 'player'),
	('Lukas Schellenberg', 'Germany', 'player'),
	('André Mendes', 'Portugal', 'player'),
	('Deng Jiaxing', 'China PR', 'player'),
	('Sebastien Pineau', 'Peru', 'player'),
	('Saleh Al Saeed', 'Saudi Arabia', 'player'),
	('Henry Kendrick', 'England', 'player'),
	('Jairo Quinteros', 'Bolivia', 'player'),
	('Noah Solskjær', 'Norway', 'player'),
	('Wassim Aouachria', 'Algeria', 'player'),
	('Shane Farrell', 'Republic of Ireland', 'player'),
	('Ciaran Brennan', 'Republic of Ireland', 'player'),
	('Ali Fouad', 'Saudi Arabia', 'player'),
	('Gustav Leijon', 'Sweden', 'player'),
	('Patrick Metcalfe', 'Canada', 'player'),
	('Jackson Lee', 'Australia', 'player'),
	('Jack Baxter', 'England', 'player'),
	('David Kruse', 'Denmark', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Ben Seymour', 'England', 'seymour'),
	('Ben Seymour', 'England', 'ben seymour'),
	('Tunmise Sobowale', 'Republic of Ireland', 'sobowale'),
	('Tunmise Sobowale', 'Republic of Ireland', 'tunmise sobowale'),
	('Karifa Yao', 'Canada', 'yao'),
	('Karifa Yao', 'Canada', 'karifa yao'),
	('Guzmán Rodríguez', 'Uruguay', 'guzman rodriguez'),
	('Guzmán Rodríguez', 'Uruguay', 'rodriguez'),
	('Williams Barlasina', 'Argentina', 'barlasina'),
	('Williams Barlasina', 'Argentina', 'williams barlasina'),
	('Tom Mehew', 'England', 'tom mehew'),
	('Tom Mehew', 'England', 'mehew'),
	('Andreas Skjøtt Foged', 'Denmark', 'andreas skjtt foged'),
	('Andreas Skjøtt Foged', 'Denmark', 'foged'),
	('Callum Smith', 'Scotland', 'smith'),
	('Callum Smith', 'Scotland', 'callum smith'),
	('Matthew Sorinola', 'England', 'matthew sorinola'),
	('Matthew Sorinola', 'England', 'sorinola'),
	('Oh Hoo Sung', 'Korea Republic', 'oh hoo sung'),
	('Oh Hoo Sung', 'Korea Republic', 'sung'),
	('Michael Tait', 'England', 'michael tait'),
	('Michael Tait', 'England', 'tait'),
	('Alexander Bernhardsson', 'Sweden', 'alexander bernhardsson'),
	('Alexander Bernhardsson', 'Sweden', 'bernhardsson'),
	('Abel Moreno', 'Chile', 'moreno'),
	('Abel Moreno', 'Chile', 'abel moreno'),
	('Luca Moro', 'Italy', 'moro'),
	('Luca Moro', 'Italy', 'luca moro'),
	('Emeka Nnamani', 'Denmark', 'emeka nnamani'),
	('Emeka Nnamani', 'Denmark', 'nnamani'),
	('Musab Habkoor', 'Saudi Arabia', 'habkoor'),
	('Musab Habkoor', 'Saudi Arabia', 'musab habkoor'),
	('Benedikt Grawe', 'Germany', 'grawe'),
	('Benedikt Grawe', 'Germany', 'benedikt grawe'),
	('György Székely', 'Hungary', 'gyorgy szekely'),
	('György Székely', 'Hungary', 'szekely'),
	('Matthew Durrans', 'England', 'durrans'),
	('Matthew Durrans', 'England', 'matthew durrans'),
	('Ferhat Saglam', 'Liechtenstein', 'saglam'),
	('Ferhat Saglam', 'Liechtenstein', 'ferhat saglam'),
	('Lucas Mauragis', 'Australia', 'lucas mauragis'),
	('Lucas Mauragis', 'Australia', 'mauragis'),
	('Johann Ngounou Djayo', 'Germany', 'johann ngounou djayo'),
	('Johann Ngounou Djayo', 'Germany', 'djayo'),
	('Majed Al Ghamdi', 'Saudi Arabia', 'majed al ghamdi'),
	('Majed Al Ghamdi', 'Saudi Arabia', 'ghamdi'),
	('Jang Seong Won', 'Korea Republic', 'jang seong won'),
	('Jang Seong Won', 'Korea Republic', 'won'),
	('Tobias Andersson', 'Sweden', 'tobias andersson'),
	('Tobias Andersson', 'Sweden', 'andersson'),
	('Tayvon Gray', 'United States', 'tayvon gray'),
	('Tayvon Gray', 'United States', 'gray'),
	('Christian Silva', 'Uruguay', 'silva'),
	('Christian Silva', 'Uruguay', 'christian silva'),
	('Simon Colyn', 'Canada', 'colyn'),
	('Simon Colyn', 'Canada', 'simon colyn'),
	('Uniss Kargbo', 'Republic of Ireland', 'kargbo'),
	('Uniss Kargbo', 'Republic of Ireland', 'uniss kargbo'),
	('Jacob Akanyirige', 'United States', 'jacob akanyirige'),
	('Jacob Akanyirige', 'United States', 'akanyirige'),
	('Arthur Read', 'England', 'read'),
	('Arthur Read', 'England', 'arthur read'),
	('Nicolás Ruíz', 'Venezuela', 'nicolas ruiz'),
	('Nicolás Ruíz', 'Venezuela', 'ruiz'),
	('Ben Bottomley', 'England', 'ben bottomley'),
	('Ben Bottomley', 'England', 'bottomley'),
	('Tyler Freeman', 'United States', 'tyler freeman'),
	('Tyler Freeman', 'United States', 'freeman'),
	('Ben Voll', 'Germany', 'ben voll'),
	('Ben Voll', 'Germany', 'voll'),
	('Christoffer Petersen', 'Denmark', 'petersen'),
	('Christoffer Petersen', 'Denmark', 'christoffer petersen'),
	('Rayan Al Marshoud', 'Saudi Arabia', 'rayan al marshoud'),
	('Rayan Al Marshoud', 'Saudi Arabia', 'marshoud'),
	('Filip Małek', 'Poland', 'filip maek'),
	('Filip Małek', 'Poland', 'maek'),
	('Batuhan Ünsal', 'Turkey', 'unsal'),
	('Batuhan Ünsal', 'Turkey', 'batuhan unsal'),
	('Luca Florică', 'Romania', 'luca florica'),
	('Luca Florică', 'Romania', 'florica'),
	('Harvey Saunders', 'England', 'saunders'),
	('Harvey Saunders', 'England', 'harvey saunders'),
	('Rasmus Wikström', 'Sweden', 'rasmus wikstrom'),
	('Rasmus Wikström', 'Sweden', 'wikstrom'),
	('Vicente Bernedo', 'Chile', 'bernedo'),
	('Vicente Bernedo', 'Chile', 'vicente bernedo'),
	('Noah Pagden', 'Australia', 'pagden'),
	('Noah Pagden', 'Australia', 'noah pagden'),
	('Johan Olstad', 'Norway', 'olstad'),
	('Johan Olstad', 'Norway', 'johan olstad'),
	('Tavio D''Almeida', 'Ivory Coast', 'dalmeida'),
	('Tavio D''Almeida', 'Ivory Coast', 'tavio dalmeida'),
	('Barry Baggley', 'Northern Ireland', 'barry baggley'),
	('Barry Baggley', 'Northern Ireland', 'baggley'),
	('Ben Sault', 'England', 'ben sault'),
	('Ben Sault', 'England', 'sault'),
	('Jacob Trenskow', 'Denmark', 'trenskow'),
	('Jacob Trenskow', 'Denmark', 'jacob trenskow'),
	('Dante Sealy', 'United States', 'sealy'),
	('Dante Sealy', 'United States', 'dante sealy'),
	('Oliver Stefánsson', 'Iceland', 'stefansson'),
	('Oliver Stefánsson', 'Iceland', 'oliver stefansson'),
	('Brage Skaret', 'Norway', 'skaret'),
	('Brage Skaret', 'Norway', 'brage skaret'),
	('Charlie Fleming', 'Republic of Ireland', 'fleming'),
	('Charlie Fleming', 'Republic of Ireland', 'charlie fleming'),
	('Sun Xuelong', 'China PR', 'sun xuelong'),
	('Sun Xuelong', 'China PR', 'xuelong'),
	('Jake Peck', 'England', 'peck'),
	('Jake Peck', 'England', 'jake peck'),
	('Jeff Caldwell', 'United States', 'caldwell'),
	('Jeff Caldwell', 'United States', 'jeff caldwell'),
	('Kristian Bernt Torgersen', 'Norway', 'torgersen'),
	('Kristian Bernt Torgersen', 'Norway', 'kristian bernt torgersen'),
	('Luke Duzel', 'Australia', 'duzel'),
	('Luke Duzel', 'Australia', 'luke duzel'),
	('Deng Yubiao', 'China PR', 'yubiao'),
	('Deng Yubiao', 'China PR', 'deng yubiao'),
	('Liu Guobo', 'China PR', 'guobo'),
	('Liu Guobo', 'China PR', 'liu guobo'),
	('Gianluca Iannucci', 'Australia', 'gianluca iannucci'),
	('Gianluca Iannucci', 'Australia', 'iannucci'),
	('Kamil Bielikow', 'Poland', 'bielikow'),
	('Kamil Bielikow', 'Poland', 'kamil bielikow'),
	('John Freeman', 'England', 'freeman'),
	('John Freeman', 'England', 'john freeman'),
	('Ben Blythe', 'England', 'ben blythe'),
	('Ben Blythe', 'England', 'blythe'),
	('Lucas Marsella', 'France', 'marsella'),
	('Lucas Marsella', 'France', 'lucas marsella'),
	('Jeong Han Min', 'Korea Republic', 'jeong han min'),
	('Jeong Han Min', 'Korea Republic', 'min'),
	('Jeisson Pinillo', 'Colombia', 'jeisson pinillo'),
	('Jeisson Pinillo', 'Colombia', 'pinillo'),
	('Harrison Holgate', 'England', 'harrison holgate'),
	('Harrison Holgate', 'England', 'holgate'),
	('Billy Sass-Davies', 'Wales', 'sassdavies'),
	('Billy Sass-Davies', 'Wales', 'billy sassdavies'),
	('Vaughn Covil', 'United States', 'covil'),
	('Vaughn Covil', 'United States', 'vaughn covil'),
	('Harvey Rew', 'Wales', 'rew'),
	('Harvey Rew', 'Wales', 'harvey rew'),
	('Kevin Yakob', 'Sweden', 'kevin yakob'),
	('Kevin Yakob', 'Sweden', 'yakob'),
	('Beineón O''Brien-Whitmarsh', 'Republic of Ireland', 'beineon obrienwhitmarsh'),
	('Beineón O''Brien-Whitmarsh', 'Republic of Ireland', 'obrienwhitmarsh'),
	('Harvey Bunker', 'England', 'bunker'),
	('Harvey Bunker', 'England', 'harvey bunker'),
	('Ismaël Doukouré', 'France', 'doukoure'),
	('Ismaël Doukouré', 'France', 'ismael doukoure'),
	('Max Harris', 'England', 'harris'),
	('Max Harris', 'England', 'max harris'),
	('Charlie Caton', 'Wales', 'charlie caton'),
	('Charlie Caton', 'Wales', 'caton'),
	('Louis Khoury', 'Australia', 'louis khoury'),
	('Louis Khoury', 'Australia', 'khoury'),
	('Anders Hoff', 'Denmark', 'hoff'),
	('Anders Hoff', 'Denmark', 'anders hoff'),
	('Julius Paris', 'Germany', 'julius paris'),
	('Julius Paris', 'Germany', 'paris'),
	('Chen Pu', 'China PR', 'pu'),
	('Chen Pu', 'China PR', 'chen pu'),
	('Mathias Madsen', 'Denmark', 'mathias madsen'),
	('Mathias Madsen', 'Denmark', 'madsen'),
	('George Stanger', 'New Zealand', 'stanger'),
	('George Stanger', 'New Zealand', 'george stanger'),
	('Joe Gubbins', 'England', 'gubbins'),
	('Joe Gubbins', 'England', 'joe gubbins'),
	('Diego Abadía', 'Colombia', 'abadia'),
	('Diego Abadía', 'Colombia', 'diego abadia'),
	('Alejandro Rojo', 'Chile', 'rojo'),
	('Alejandro Rojo', 'Chile', 'alejandro rojo'),
	('Josh Dixon', 'England', 'dixon'),
	('Josh Dixon', 'England', 'josh dixon'),
	('Idemudia Udebhu-Osimeh', 'England', 'idemudia udebhuosimeh'),
	('Idemudia Udebhu-Osimeh', 'England', 'udebhuosimeh'),
	('Adelin Voinescu', 'Romania', 'voinescu'),
	('Adelin Voinescu', 'Romania', 'adelin voinescu'),
	('Bruno Scorza', 'Uruguay', 'scorza'),
	('Bruno Scorza', 'Uruguay', 'bruno scorza'),
	('Liu Ziming', 'China PR', 'liu ziming'),
	('Liu Ziming', 'China PR', 'ziming'),
	('Ertuğrul Tekşen', 'Turkey', 'ertugrul teksen'),
	('Ertuğrul Tekşen', 'Turkey', 'teksen'),
	('Sam Perry', 'England', 'perry'),
	('Sam Perry', 'England', 'sam perry'),
	('Emil Kornvig', 'Denmark', 'kornvig'),
	('Emil Kornvig', 'Denmark', 'emil kornvig'),
	('Roni Arabaci', 'Denmark', 'roni arabaci'),
	('Roni Arabaci', 'Denmark', 'arabaci'),
	('Nikolaos Dosis', 'Sweden', 'dosis'),
	('Nikolaos Dosis', 'Sweden', 'nikolaos dosis'),
	('Łukasz Seweryn', 'Poland', 'ukasz seweryn'),
	('Łukasz Seweryn', 'Poland', 'seweryn'),
	('Jakub Sypek', 'Poland', 'sypek'),
	('Jakub Sypek', 'Poland', 'jakub sypek'),
	('Tyron Owusu', 'Switzerland', 'tyron owusu'),
	('Tyron Owusu', 'Switzerland', 'owusu'),
	('Stephan Seiler', 'Switzerland', 'stephan seiler'),
	('Stephan Seiler', 'Switzerland', 'seiler'),
	('Faysal Bettache', 'England', 'faysal bettache'),
	('Faysal Bettache', 'England', 'bettache'),
	('Sammie McLeod', 'England', 'mcleod'),
	('Sammie McLeod', 'England', 'sammie mcleod'),
	('Yin Congyao', 'China PR', 'congyao'),
	('Yin Congyao', 'China PR', 'yin congyao'),
	('Max Williamsen', 'Norway', 'max williamsen'),
	('Max Williamsen', 'Norway', 'williamsen'),
	('Bughrahan Iskandar', 'China PR', 'iskandar'),
	('Bughrahan Iskandar', 'China PR', 'bughrahan iskandar'),
	('Jordan Barnett', 'England', 'barnett'),
	('Jordan Barnett', 'England', 'jordan barnett'),
	('Martín Lagunes', 'Mexico', 'lagunes'),
	('Martín Lagunes', 'Mexico', 'martin lagunes'),
	('Tom Wilson', 'England', 'tom wilson'),
	('Tom Wilson', 'England', 'wilson'),
	('Taylor Seymour', 'England', 'seymour'),
	('Taylor Seymour', 'England', 'taylor seymour'),
	('Ronan Boyce', 'Republic of Ireland', 'boyce'),
	('Ronan Boyce', 'Republic of Ireland', 'ronan boyce'),
	('Cian Bargary', 'Republic of Ireland', 'cian bargary'),
	('Cian Bargary', 'Republic of Ireland', 'bargary'),
	('Jack Sims', 'England', 'jack sims'),
	('Jack Sims', 'England', 'sims'),
	('Fabian Monge', 'Australia', 'fabian monge'),
	('Fabian Monge', 'Australia', 'monge'),
	('He Yupeng', 'China PR', 'yupeng'),
	('He Yupeng', 'China PR', 'he yupeng'),
	('Maciej Bortniczuk', 'Poland', 'bortniczuk'),
	('Maciej Bortniczuk', 'Poland', 'maciej bortniczuk'),
	('Ibrahim Bakare', 'England', 'ibrahim bakare'),
	('Ibrahim Bakare', 'England', 'bakare'),
	('James Hill', 'England', 'hill'),
	('James Hill', 'England', 'james hill'),
	('Bryan Soto', 'Chile', 'bryan soto'),
	('Bryan Soto', 'Chile', 'soto'),
	('Tom Chamberlain', 'England', 'tom chamberlain'),
	('Tom Chamberlain', 'England', 'chamberlain'),
	('Archie Matthews', 'England', 'matthews'),
	('Archie Matthews', 'England', 'archie matthews'),
	('Anthony Valencia', 'Ecuador', 'valencia'),
	('Anthony Valencia', 'Ecuador', 'anthony valencia'),
	('Kim Dong Bum', 'Korea Republic', 'bum'),
	('Kim Dong Bum', 'Korea Republic', 'kim dong bum'),
	('Flynn Clarke', 'England', 'clarke'),
	('Flynn Clarke', 'England', 'flynn clarke'),
	('Mads Winther', 'Denmark', 'mads winther'),
	('Mads Winther', 'Denmark', 'winther'),
	('Alexis Verdún', 'Paraguay', 'verdun'),
	('Alexis Verdún', 'Paraguay', 'alexis verdun'),
	('Ramón Sosa', 'Paraguay', 'sosa'),
	('Ramón Sosa', 'Paraguay', 'ramon sosa'),
	('Joe Dunne', 'England', 'dunne'),
	('Joe Dunne', 'England', 'joe dunne'),
	('Krzysztof Toporkiewicz', 'Poland', 'toporkiewicz'),
	('Krzysztof Toporkiewicz', 'Poland', 'krzysztof toporkiewicz'),
	('Oscar Vilhelmsson', 'Sweden', 'vilhelmsson'),
	('Oscar Vilhelmsson', 'Sweden', 'oscar vilhelmsson'),
	('Tobias Fjeld Gulliksen', 'Norway', 'gulliksen'),
	('Tobias Fjeld Gulliksen', 'Norway', 'tobias fjeld gulliksen'),
	('Ibrahim Al Otaibi', 'Saudi Arabia', 'otaibi'),
	('Ibrahim Al Otaibi', 'Saudi Arabia', 'ibrahim al otaibi'),
	('Gonzalo Duré', 'Paraguay', 'dure'),
	('Gonzalo Duré', 'Paraguay', 'gonzalo dure'),
	('Germán Contreras', 'Venezuela', 'german contreras'),
	('Germán Contreras', 'Venezuela', 'contreras'),
	('Liberman Torres', 'Ecuador', 'torres'),
	('Liberman Torres', 'Ecuador', 'liberman torres'),
	('Toby Holland', 'England', 'toby holland'),
	('Toby Holland', 'England', 'holland'),
	('Matt Rush', 'England', 'rush'),
	('Matt Rush', 'England', 'matt rush'),
	('Chen Zhechao', 'China PR', 'chen zhechao'),
	('Chen Zhechao', 'China PR', 'zhechao'),
	('Aidan Liu', 'United States', 'liu'),
	('Aidan Liu', 'United States', 'aidan liu'),
	('Renné Rivas', 'Venezuela', 'rivas'),
	('Renné Rivas', 'Venezuela', 'renne rivas'),
	('Lucas Chang-Andersen', 'Denmark', 'lucas changandersen'),
	('Lucas Chang-Andersen', 'Denmark', 'changandersen'),
	('Xavier Dziekoński', 'Poland', 'dziekonski'),
	('Xavier Dziekoński', 'Poland', 'xavier dziekonski'),
	('Stefan Colakovski', 'Australia', 'colakovski'),
	('Stefan Colakovski', 'Australia', 'stefan colakovski'),
	('Joe Scally', 'United States', 'joe scally'),
	('Joe Scally', 'United States', 'scally'),
	('Ma Chongchong', 'China PR', 'ma chongchong'),
	('Ma Chongchong', 'China PR', 'chongchong'),
	('Ryan Scott', 'Australia', 'ryan scott'),
	('Ryan Scott', 'Australia', 'scott'),
	('Jay Matete', 'England', 'matete'),
	('Jay Matete', 'England', 'jay matete'),
	('Shadrach Ogie', 'Republic of Ireland', 'ogie'),
	('Shadrach Ogie', 'Republic of Ireland', 'shadrach ogie'),
	('Enmanuel Moreno', 'Venezuela', 'moreno'),
	('Enmanuel Moreno', 'Venezuela', 'enmanuel moreno'),
	('Henrik Falchener', 'Norway', 'henrik falchener'),
	('Henrik Falchener', 'Norway', 'falchener'),
	('Dan Neil', 'England', 'dan neil'),
	('Dan Neil', 'England', 'neil'),
	('Avan Jones', 'England', 'avan jones'),
	('Avan Jones', 'England', 'jones'),
	('Callum Rowe', 'England', 'rowe'),
	('Callum Rowe', 'England', 'callum rowe'),
	('Dorian Salhi', 'France', 'dorian salhi'),
	('Dorian Salhi', 'France', 'salhi'),
	('Simen Hammershaug', 'Norway', 'simen hammershaug'),
	('Simen Hammershaug', 'Norway', 'hammershaug'),
	('Jacob Gratton', 'England', 'jacob gratton'),
	('Jacob Gratton', 'England', 'gratton'),
	('Connor Shanks', 'England', 'shanks'),
	('Connor Shanks', 'England', 'connor shanks'),
	('Sander Tangvik', 'Norway', 'sander tangvik'),
	('Sander Tangvik', 'Norway', 'tangvik'),
	('Lee Jae Won', 'Korea Republic', 'lee jae won'),
	('Lee Jae Won', 'Korea Republic', 'won'),
	('Andrew Mills', 'England', 'mills'),
	('Andrew Mills', 'England', 'andrew mills'),
	('Dylan Asonganyi', 'England', 'dylan asonganyi'),
	('Dylan Asonganyi', 'England', 'asonganyi'),
	('Fabio Lopes', 'Portugal', 'fabio lopes'),
	('Fabio Lopes', 'Portugal', 'lopes'),
	('Jeremy Quintero', 'Venezuela', 'quintero'),
	('Jeremy Quintero', 'Venezuela', 'jeremy quintero'),
	('Junior Quitirna', 'Guinea Bissau', 'junior quitirna'),
	('Junior Quitirna', 'Guinea Bissau', 'quitirna'),
	('Kristoffer S. Ødven', 'Norway', 'kristoffer s dven'),
	('Kristoffer S. Ødven', 'Norway', 'dven'),
	('Oliver Rojas', 'Chile', 'oliver rojas'),
	('Oliver Rojas', 'Chile', 'rojas'),
	('Alejandro Machuca', 'Paraguay', 'alejandro machuca'),
	('Alejandro Machuca', 'Paraguay', 'machuca'),
	('Lewis Collins', 'Wales', 'collins'),
	('Lewis Collins', 'Wales', 'lewis collins'),
	('Vicente Ramírez', 'Chile', 'vicente ramirez'),
	('Vicente Ramírez', 'Chile', 'ramirez'),
	('Kai McKenzie-Lyle', 'Guyana', 'mckenzielyle'),
	('Kai McKenzie-Lyle', 'Guyana', 'kai mckenzielyle'),
	('Wilson Barrios', 'Venezuela', 'wilson barrios'),
	('Wilson Barrios', 'Venezuela', 'barrios'),
	('Adam Petersson', 'Sweden', 'adam petersson'),
	('Adam Petersson', 'Sweden', 'petersson'),
	('Ylan Gomes', 'France', 'ylan gomes'),
	('Ylan Gomes', 'France', 'gomes'),
	('Jake Trew', 'Australia', 'trew'),
	('Jake Trew', 'Australia', 'jake trew'),
	('Ahanna Agbowo', 'Germany', 'agbowo'),
	('Ahanna Agbowo', 'Germany', 'ahanna agbowo'),
	('Lucas Tomlinson', 'England', 'lucas tomlinson'),
	('Lucas Tomlinson', 'England', 'tomlinson'),
	('Bobby Copping', 'England', 'bobby copping'),
	('Bobby Copping', 'England', 'copping'),
	('Liu Xinyu', 'China PR', 'xinyu'),
	('Liu Xinyu', 'China PR', 'liu xinyu'),
	('Carlos Sánchez', 'Ecuador', 'carlos sanchez'),
	('Carlos Sánchez', 'Ecuador', 'sanchez'),
	('Jhohann Yabur', 'Colombia', 'yabur'),
	('Jhohann Yabur', 'Colombia', 'jhohann yabur'),
	('Joel Bagan', 'England', 'bagan'),
	('Joel Bagan', 'England', 'joel bagan'),
	('Patryk Królczyk', 'Poland', 'patryk krolczyk'),
	('Patryk Królczyk', 'Poland', 'krolczyk'),
	('Jeong Yeong Ung', 'Korea Republic', 'jeong yeong ung'),
	('Jeong Yeong Ung', 'Korea Republic', 'ung'),
	('Jayden Sweeney', 'England', 'sweeney'),
	('Jayden Sweeney', 'England', 'jayden sweeney'),
	('Travis Johnson', 'England', 'travis johnson'),
	('Travis Johnson', 'England', 'johnson'),
	('Ben Worman', 'England', 'worman'),
	('Ben Worman', 'England', 'ben worman'),
	('Jack Serrant-Green', 'England', 'jack serrantgreen'),
	('Jack Serrant-Green', 'England', 'serrantgreen'),
	('José Ignacio Molina', 'Chile', 'jose ignacio molina'),
	('José Ignacio Molina', 'Chile', 'molina'),
	('Joseph Hope', 'England', 'joseph hope'),
	('Joseph Hope', 'England', 'hope'),
	('Huang Chuang', 'China PR', 'chuang'),
	('Huang Chuang', 'China PR', 'huang chuang'),
	('Qian Yumiao', 'China PR', 'yumiao'),
	('Qian Yumiao', 'China PR', 'qian yumiao'),
	('Diego Vergara', 'Chile', 'diego vergara'),
	('Diego Vergara', 'Chile', 'vergara'),
	('Benjamín Iglesias', 'Chile', 'iglesias'),
	('Benjamín Iglesias', 'Chile', 'benjamin iglesias'),
	('Taylor Charters', 'England', 'charters'),
	('Taylor Charters', 'England', 'taylor charters'),
	('Dominik Kalinowski', 'Poland', 'dominik kalinowski'),
	('Dominik Kalinowski', 'Poland', 'kalinowski'),
	('Harry Boyes', 'England', 'harry boyes'),
	('Harry Boyes', 'England', 'boyes'),
	('Álvaro Garrido', 'Chile', 'garrido'),
	('Álvaro Garrido', 'Chile', 'alvaro garrido'),
	('Callum Coulter', 'England', 'coulter'),
	('Callum Coulter', 'England', 'callum coulter'),
	('Mikkel Ceïde', 'Norway', 'mikkel ceide'),
	('Mikkel Ceïde', 'Norway', 'ceide'),
	('Alex Doyle', 'England', 'alex doyle'),
	('Alex Doyle', 'England', 'doyle'),
	('Teng Shangkun', 'China PR', 'teng shangkun'),
	('Teng Shangkun', 'China PR', 'shangkun'),
	('Casper Widell', 'Sweden', 'casper widell'),
	('Casper Widell', 'Sweden', 'widell'),
	('Johan Karlsson', 'Sweden', 'karlsson'),
	('Johan Karlsson', 'Sweden', 'johan karlsson'),
	('Lirak Hasani', 'England', 'lirak hasani'),
	('Lirak Hasani', 'England', 'hasani'),
	('Hampus Danielsson', 'Sweden', 'danielsson'),
	('Hampus Danielsson', 'Sweden', 'hampus danielsson'),
	('Ryan Hillier', 'Wales', 'hillier'),
	('Ryan Hillier', 'Wales', 'ryan hillier'),
	('Didier La Torre', 'Peru', 'torre'),
	('Didier La Torre', 'Peru', 'didier la torre'),
	('Liam Isherwood', 'England', 'liam isherwood'),
	('Liam Isherwood', 'England', 'isherwood'),
	('Jake Young', 'England', 'young'),
	('Jake Young', 'England', 'jake young'),
	('Ged Garner', 'England', 'ged garner'),
	('Ged Garner', 'England', 'garner'),
	('Jean Belehouan', 'France', 'jean belehouan'),
	('Jean Belehouan', 'France', 'belehouan'),
	('Will Shepherd', 'England', 'shepherd'),
	('Will Shepherd', 'England', 'will shepherd'),
	('Noah De Queiroz', 'Switzerland', 'noah de queiroz'),
	('Noah De Queiroz', 'Switzerland', 'queiroz'),
	('Asım Aksungur', 'Turkey', 'asm aksungur'),
	('Asım Aksungur', 'Turkey', 'aksungur'),
	('Jesse Devers', 'Republic of Ireland', 'devers'),
	('Jesse Devers', 'Republic of Ireland', 'jesse devers'),
	('Axel García', 'Mexico', 'garcia'),
	('Axel García', 'Mexico', 'axel garcia'),
	('Tom Dickens', 'England', 'dickens'),
	('Tom Dickens', 'England', 'tom dickens'),
	('David Croitoru', 'Romania', 'croitoru'),
	('David Croitoru', 'Romania', 'david croitoru'),
	('Dániel Csóka', 'Hungary', 'daniel csoka'),
	('Dániel Csóka', 'Hungary', 'csoka'),
	('Felix Jakobsson', 'Sweden', 'felix jakobsson'),
	('Felix Jakobsson', 'Sweden', 'jakobsson'),
	('Juan Carlos González', 'Venezuela', 'juan carlos gonzalez'),
	('Juan Carlos González', 'Venezuela', 'gonzalez'),
	('Theodore Rask', 'Sweden', 'rask'),
	('Theodore Rask', 'Sweden', 'theodore rask'),
	('Adam Foley', 'Northern Ireland', 'foley'),
	('Adam Foley', 'Northern Ireland', 'adam foley'),
	('Adam O''Reilly', 'Republic of Ireland', 'adam oreilly'),
	('Adam O''Reilly', 'Republic of Ireland', 'oreilly'),
	('Gao Dalun', 'China PR', 'dalun'),
	('Gao Dalun', 'China PR', 'gao dalun'),
	('Isaac Boehmer', 'Canada', 'isaac boehmer'),
	('Isaac Boehmer', 'Canada', 'boehmer'),
	('Ahmed Al Enazi', 'Saudi Arabia', 'enazi'),
	('Ahmed Al Enazi', 'Saudi Arabia', 'ahmed al enazi'),
	('Rasmus Fridolf', 'Sweden', 'fridolf'),
	('Rasmus Fridolf', 'Sweden', 'rasmus fridolf'),
	('Cao Dong', 'China PR', 'cao dong'),
	('Cao Dong', 'China PR', 'dong'),
	('Agustín Cano', 'Colombia', 'cano'),
	('Agustín Cano', 'Colombia', 'agustin cano'),
	('Kian Scales', 'England', 'kian scales'),
	('Kian Scales', 'England', 'scales'),
	('Zhou Baizhao', 'China PR', 'baizhao'),
	('Zhou Baizhao', 'China PR', 'zhou baizhao'),
	('Cui Lin', 'China PR', 'lin'),
	('Cui Lin', 'China PR', 'cui lin'),
	('Sean Callan', 'Republic of Ireland', 'sean callan'),
	('Sean Callan', 'Republic of Ireland', 'callan'),
	('Lukas Schellenberg', 'Germany', 'lukas schellenberg'),
	('Lukas Schellenberg', 'Germany', 'schellenberg'),
	('André Mendes', 'Portugal', 'andre mendes'),
	('André Mendes', 'Portugal', 'mendes'),
	('Deng Jiaxing', 'China PR', 'jiaxing'),
	('Deng Jiaxing', 'China PR', 'deng jiaxing'),
	('Sebastien Pineau', 'Peru', 'pineau'),
	('Sebastien Pineau', 'Peru', 'sebastien pineau'),
	('Saleh Al Saeed', 'Saudi Arabia', 'saleh al saeed'),
	('Saleh Al Saeed', 'Saudi Arabia', 'saeed'),
	('Henry Kendrick', 'England', 'kendrick'),
	('Henry Kendrick', 'England', 'henry kendrick'),
	('Jairo Quinteros', 'Bolivia', 'jairo quinteros'),
	('Jairo Quinteros', 'Bolivia', 'quinteros'),
	('Noah Solskjær', 'Norway', 'noah solskjr'),
	('Noah Solskjær', 'Norway', 'solskjr'),
	('Wassim Aouachria', 'Algeria', 'aouachria'),
	('Wassim Aouachria', 'Algeria', 'wassim aouachria'),
	('Shane Farrell', 'Republic of Ireland', 'farrell'),
	('Shane Farrell', 'Republic of Ireland', 'shane farrell'),
	('Ciaran Brennan', 'Republic of Ireland', 'brennan'),
	('Ciaran Brennan', 'Republic of Ireland', 'ciaran brennan'),
	('Ali Fouad', 'Saudi Arabia', 'ali fouad'),
	('Ali Fouad', 'Saudi Arabia', 'fouad'),
	('Gustav Leijon', 'Sweden', 'leijon'),
	('Gustav Leijon', 'Sweden', 'gustav leijon'),
	('Patrick Metcalfe', 'Canada', 'patrick metcalfe'),
	('Patrick Metcalfe', 'Canada', 'metcalfe'),
	('Jackson Lee', 'Australia', 'lee'),
	('Jackson Lee', 'Australia', 'jackson lee'),
	('Jack Baxter', 'England', 'baxter'),
	('Jack Baxter', 'England', 'jack baxter'),
	('David Kruse', 'Denmark', 'kruse'),
	('David Kruse', 'Denmark', 'david kruse')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';