INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('David Gray', 'Scotland', 'player'),
	('Saša Jovanović', 'Serbia', 'player'),
	('Sondre Bjørshol', 'Norway', 'player'),
	('Paddy Madden', 'Republic of Ireland', 'player'),
	('Noë Dussenne', 'Belgium', 'player'),
	('Siphelele Ntshangase', 'South Africa', 'player'),
	('Mikel Villanueva', 'Venezuela', 'player'),
	('Max Dombrowka', 'Germany', 'player'),
	('Iriome', 'Spain', 'player'),
	('Davide Di Gennaro', 'Italy', 'player'),
	('Timo Perthel', 'Germany', 'player'),
	('Luca Clemenza', 'Italy', 'player'),
	('Jacob Brown', 'England', 'player'),
	('Zou Zheng', 'China PR', 'player'),
	('Dylan Gissi', 'Switzerland', 'player'),
	('Bård Finne', 'Norway', 'player'),
	('Pleguezuelo', 'Spain', 'player'),
	('Mayron George', 'Costa Rica', 'player'),
	('Verza', 'Spain', 'player'),
	('Tatsuya Morita', 'Japan', 'player'),
	('Răzvan Oaidă', 'Romania', 'player'),
	('Mijat Marić', 'Switzerland', 'player'),
	('Alexandros Katranis', 'Greece', 'player'),
	('Kamal Sowah', 'Ghana', 'player'),
	('Rémi Pillot', 'France', 'player'),
	('Hugo Seco', 'Portugal', 'player'),
	('Ryan Allsop', 'England', 'player'),
	('Jakub Szumski', 'Poland', 'player'),
	('Sim Sang Min', 'Korea Republic', 'player'),
	('Zlatan Alomerović', 'Serbia', 'player'),
	('Reza Asadi', 'Iran', 'player'),
	('Matías Esquivel', 'Argentina', 'player'),
	('Patrik Karlsson Lagemyr', 'Sweden', 'player'),
	('Leo Coelho', 'Brazil', 'player'),
	('Andreas Leitner', 'Austria', 'player'),
	('Michael Pereira', 'France', 'player'),
	('Johannes Wurtz', 'Germany', 'player'),
	('Philipp Zulechner', 'Austria', 'player'),
	('Sessi D''Almeida', 'Benin', 'player'),
	('Brandon Bye', 'United States', 'player'),
	('Luka Ilić', 'Serbia', 'player'),
	('Ersin Destanoğlu', 'Turkey', 'player'),
	('Bart Vriends', 'Netherlands', 'player'),
	('Walter Clar', 'Paraguay', 'player'),
	('Charles Monsalvo', 'Colombia', 'player'),
	('Stefan Lex', 'Germany', 'player'),
	('Jean-Claude Billong', 'France', 'player'),
	('Eldin Jakupović', 'Switzerland', 'player'),
	('Scott McMann', 'Scotland', 'player'),
	('Cándido Ramírez', 'Mexico', 'player'),
	('Mart Lieder', 'Netherlands', 'player'),
	('Mattia Finotto', 'Italy', 'player'),
	('Yuki Kobayashi', 'Japan', 'player'),
	('Luis Perea', 'Spain', 'player'),
	('Daniel Febles', 'Venezuela', 'player'),
	('Erik Expósito', 'Spain', 'player'),
	('Toshio Shimakawa', 'Japan', 'player'),
	('Marc McNulty', 'Scotland', 'player'),
	('Dario Del Fabro', 'Italy', 'player'),
	('Shinnosuke Nakatani', 'Japan', 'player'),
	('Kirian', 'Spain', 'player'),
	('Robert Lundström', 'Sweden', 'player'),
	('Quenten Martinus', 'Curacao', 'player'),
	('Max O''Leary', 'England', 'player'),
	('Bojan Letić', 'Bosnia Herzegovina', 'player'),
	('Rafael Barros', 'Brazil', 'player'),
	('Sean McConville', 'England', 'player'),
	('Jesús Medina', 'Paraguay', 'player'),
	('Mario de Luna', 'Mexico', 'player'),
	('Salvatore Esposito', 'Italy', 'player'),
	('Jonathan Toledo', 'Uruguay', 'player'),
	('Joshua Smits', 'Netherlands', 'player'),
	('Muammer Yıldırım', 'Turkey', 'player'),
	('Gary Madine', 'England', 'player'),
	('Carlos Melgar', 'Bolivia', 'player'),
	('Xavier Arreaga', 'Ecuador', 'player'),
	('Aster Vranckx', 'Belgium', 'player'),
	('Olaetxea', 'Spain', 'player'),
	('Leandro Suhr', 'Uruguay', 'player'),
	('Niklas Sandberg', 'Norway', 'player'),
	('Jake Mulraney', 'Republic of Ireland', 'player'),
	('Scott Pittman', 'Scotland', 'player'),
	('Tomás Esteves', 'Portugal', 'player'),
	('Gaspar Iñiguez', 'Argentina', 'player'),
	('Tobias Schwede', 'Germany', 'player'),
	('Matt Olosunde', 'United States', 'player'),
	('Makana Baku', 'Germany', 'player'),
	('Andreas Landgren', 'Sweden', 'player'),
	('Marcel Ziegl', 'Austria', 'player'),
	('Tortol Lumanza Lembi', 'Belgium', 'player'),
	('Murat Uçar', 'Turkey', 'player'),
	('Milan Dimun', 'Slovakia', 'player'),
	('Bright Edomwonyi', 'Nigeria', 'player'),
	('Christian Dorda', 'Germany', 'player'),
	('Adam Frączczak', 'Poland', 'player'),
	('Daniel-Kofi Kyereh', 'Germany', 'player'),
	('Arild Østbø', 'Norway', 'player'),
	('Gabriel Brazão', 'Brazil', 'player'),
	('Moussa Sylla', 'France', 'player'),
	('Alan Lithgow', 'Scotland', 'player'),
	('Sam McCallum', 'England', 'player'),
	('Juan Alano', 'Brazil', 'player'),
	('Matías Pardo', 'Argentina', 'player'),
	('Jonathan Grounds', 'England', 'player'),
	('Lukáš Juliš', 'Czech Republic', 'player'),
	('Nicolò Manfredini', 'Italy', 'player'),
	('Dean Furman', 'South Africa', 'player'),
	('Greg Leigh', 'England', 'player'),
	('Tom Boere', 'Netherlands', 'player'),
	('Joseph Mills', 'England', 'player'),
	('Russell Teibert', 'Canada', 'player'),
	('Abdullah Madu', 'Saudi Arabia', 'player'),
	('Facundo Altamirano', 'Argentina', 'player'),
	('Marian Pleașcă', 'Romania', 'player'),
	('Kristoffer Løkberg', 'Norway', 'player'),
	('Jordan Shipley', 'Republic of Ireland', 'player'),
	('Luis Segovia', 'Ecuador', 'player'),
	('Dave Gnaase', 'Germany', 'player'),
	('Cristian Colmán', 'Paraguay', 'player'),
	('Ricardo Alves', 'Portugal', 'player'),
	('Xie Pengfei', 'China PR', 'player'),
	('Rodrigo Ureña', 'Chile', 'player'),
	('Ruben Kristiansen', 'Norway', 'player'),
	('Jorge Zules Caicedo', 'Colombia', 'player'),
	('Pablo Cifuentes', 'Ecuador', 'player'),
	('Ștefan Vlădoiu', 'Romania', 'player'),
	('Bentley Baxter Bahn', 'Germany', 'player'),
	('Morgan Poaty', 'France', 'player'),
	('Nikola Jambor', 'Croatia', 'player'),
	('Paseka Mako', 'South Africa', 'player'),
	('Olabe', 'Spain', 'player'),
	('Niklas Hauptmann', 'Germany', 'player'),
	('Petrus Boumal', 'Cameroon', 'player'),
	('Mohammed Abu', 'Ghana', 'player'),
	('Marcin Listkowski', 'Poland', 'player'),
	('Ethan Laird', 'England', 'player'),
	('Sven Köhler', 'Germany', 'player'),
	('Janner Corozo', 'Ecuador', 'player'),
	('Park Jong Woo', 'Korea Republic', 'player'),
	('Gabriel Simion', 'Romania', 'player'),
	('Marco Ureña', 'Costa Rica', 'player'),
	('Yuichi Maruyama', 'Japan', 'player'),
	('Diego Sosa', 'Argentina', 'player'),
	('Pavel Maslov', 'Russia', 'player'),
	('Wojciech Golla', 'Poland', 'player'),
	('Andersson Ordóñez', 'Ecuador', 'player'),
	('John Fajardo', 'Peru', 'player'),
	('Daniel Fuzato', 'Brazil', 'player'),
	('Kei Koizumi', 'Japan', 'player'),
	('Gastón Gómez', 'Argentina', 'player'),
	('Tuta', 'Brazil', 'player'),
	('Cristian Flores', 'Venezuela', 'player'),
	('Rudy Camacho', 'France', 'player'),
	('Makhtar Gueye', 'Senegal', 'player'),
	('Michal Sipľak', 'Slovakia', 'player'),
	('Lennart Moser', 'Germany', 'player'),
	('Forniés', 'Spain', 'player'),
	('Ko Seung Beom', 'Korea Republic', 'player'),
	('Denis Rodríguez', 'Argentina', 'player'),
	('Jordan Cousins', 'England', 'player'),
	('Jessic Ngankam', 'Germany', 'player'),
	('Eric Smith', 'Sweden', 'player'),
	('Jin Jingdao', 'China PR', 'player'),
	('Bilel Saidani', 'Tunisia', 'player'),
	('Callum Johnson', 'England', 'player'),
	('Serge Tabekou', 'Cameroon', 'player'),
	('Stian Rode Gregersen', 'Norway', 'player'),
	('Dimitri Mohamed', 'France', 'player'),
	('Zié Mohamed Ouattara', 'Ivory Coast', 'player'),
	('Tim Boss', 'Germany', 'player'),
	('Abdullah Al Khaibari', 'Saudi Arabia', 'player'),
	('Ufuk Akyol', 'Germany', 'player'),
	('Fredrik Oldrup Jensen', 'Norway', 'player'),
	('Dylan Louiserre', 'France', 'player'),
	('Romario Moise', 'Romania', 'player'),
	('Jack Colback', 'England', 'player'),
	('Tim Kister', 'Germany', 'player'),
	('Jakub Bartkowski', 'Poland', 'player'),
	('Muzepper Mirahmetjan', 'China PR', 'player'),
	('Lasse Vibe', 'Denmark', 'player'),
	('Hassan Kadish', 'Saudi Arabia', 'player'),
	('Nik Omladič', 'Slovenia', 'player'),
	('Gabriel Souza', 'Brazil', 'player'),
	('Leonardo Bertone', 'Switzerland', 'player'),
	('Luke Hemmerich', 'Germany', 'player'),
	('Yasin Pehlivan', 'Austria', 'player'),
	('Diego Martínez', 'Colombia', 'player'),
	('Jhon Vásquez', 'Colombia', 'player'),
	('Rasmus Nicolaisen', 'Denmark', 'player'),
	('Cristian', 'Spain', 'player'),
	('Kyohei Yoshino', 'Japan', 'player'),
	('Max Besuschkow', 'Germany', 'player'),
	('Scott Jamieson', 'Australia', 'player'),
	('Yin Hongbo', 'China PR', 'player'),
	('Fabian Kalig', 'Germany', 'player'),
	('Danilo Arboleda', 'Colombia', 'player'),
	('Ionuț Larie', 'Romania', 'player'),
	('Ferdinand Oswald', 'Germany', 'player'),
	('Alan Judge', 'Republic of Ireland', 'player'),
	('Sascha Mölders', 'Germany', 'player'),
	('Maxime D''Arpino', 'France', 'player'),
	('Daniël van Kaam', 'Netherlands', 'player'),
	('Delano Burgzorg', 'Netherlands', 'player'),
	('Roland Niczuly', 'Romania', 'player'),
	('Kayden Jackson', 'England', 'player'),
	('Gaëtan Karlen', 'Switzerland', 'player'),
	('Paweł Cibicki', 'Sweden', 'player'),
	('Prosper Mendy', 'France', 'player'),
	('Abdullah Durak', 'Turkey', 'player'),
	('Wálter Chalá', 'Ecuador', 'player'),
	('Sérgio Marakis', 'Portugal', 'player'),
	('Wang Shangyuan', 'China PR', 'player'),
	('Mairon Quiñones', 'Colombia', 'player'),
	('Nils Fröling', 'Sweden', 'player'),
	('Dominique Badji', 'Senegal', 'player'),
	('A.J. DeLaGarza', 'Guam', 'player'),
	('Tim Coremans', 'Netherlands', 'player'),
	('Fabian Nürnberger', 'Germany', 'player'),
	('Wu Xinghan', 'China PR', 'player'),
	('Jakub Słowik', 'Poland', 'player'),
	('Michael Heylen', 'Belgium', 'player'),
	('Michael Huber', 'Austria', 'player'),
	('Julien Serrano', 'France', 'player'),
	('Yuta Nakayama', 'Japan', 'player'),
	('Javier Salas', 'Mexico', 'player'),
	('Ntsikelelo Nyauza', 'South Africa', 'player'),
	('Victor Wernersson', 'Sweden', 'player'),
	('Aaron Tshibola', 'DR Congo', 'player'),
	('Pa Konate', 'Guinea', 'player'),
	('Riquelme', 'Spain', 'player'),
	('Daiki Watari', 'Japan', 'player'),
	('Carlos Miguel', 'Brazil', 'player'),
	('Abel Mabaso', 'South Africa', 'player'),
	('Igor Zlatanović', 'Serbia', 'player'),
	('Ryosuke Maeda', 'Japan', 'player'),
	('Ayman Ben Mohamed', 'Tunisia', 'player'),
	('Kohei Shimizu', 'Japan', 'player'),
	('Per Frick', 'Sweden', 'player'),
	('Jonas Carls', 'Germany', 'player'),
	('Lee Yeong Jae', 'Korea Republic', 'player'),
	('David Carmona', 'Spain', 'player'),
	('Leo Weinkauf', 'Germany', 'player'),
	('Jordan Rossiter', 'England', 'player'),
	('Juan Ibiza', 'Spain', 'player'),
	('Tommy Oar', 'Australia', 'player'),
	('Maximilian Welzmüller', 'Germany', 'player'),
	('Dimitri Lavalée', 'Belgium', 'player'),
	('Maic Sema', 'Sweden', 'player'),
	('Murat Akça', 'Turkey', 'player'),
	('Daniel Quiñones', 'Colombia', 'player');

WITH v(name, cat, alias) AS (VALUES
	('David Gray', 'Scotland', 'david gray'),
	('David Gray', 'Scotland', 'gray'),
	('Saša Jovanović', 'Serbia', 'sasa jovanovic'),
	('Saša Jovanović', 'Serbia', 'jovanovic'),
	('Sondre Bjørshol', 'Norway', 'sondre bjrshol'),
	('Sondre Bjørshol', 'Norway', 'bjrshol'),
	('Paddy Madden', 'Republic of Ireland', 'madden'),
	('Paddy Madden', 'Republic of Ireland', 'paddy madden'),
	('Noë Dussenne', 'Belgium', 'dussenne'),
	('Noë Dussenne', 'Belgium', 'noe dussenne'),
	('Siphelele Ntshangase', 'South Africa', 'ntshangase'),
	('Siphelele Ntshangase', 'South Africa', 'siphelele ntshangase'),
	('Mikel Villanueva', 'Venezuela', 'mikel villanueva'),
	('Mikel Villanueva', 'Venezuela', 'villanueva'),
	('Max Dombrowka', 'Germany', 'dombrowka'),
	('Max Dombrowka', 'Germany', 'max dombrowka'),
	('Iriome', 'Spain', 'iriome'),
	('Davide Di Gennaro', 'Italy', 'davide di gennaro'),
	('Davide Di Gennaro', 'Italy', 'gennaro'),
	('Timo Perthel', 'Germany', 'timo perthel'),
	('Timo Perthel', 'Germany', 'perthel'),
	('Luca Clemenza', 'Italy', 'clemenza'),
	('Luca Clemenza', 'Italy', 'luca clemenza'),
	('Jacob Brown', 'England', 'jacob brown'),
	('Jacob Brown', 'England', 'brown'),
	('Zou Zheng', 'China PR', 'zheng'),
	('Zou Zheng', 'China PR', 'zou zheng'),
	('Dylan Gissi', 'Switzerland', 'gissi'),
	('Dylan Gissi', 'Switzerland', 'dylan gissi'),
	('Bård Finne', 'Norway', 'finne'),
	('Bård Finne', 'Norway', 'bard finne'),
	('Pleguezuelo', 'Spain', 'pleguezuelo'),
	('Mayron George', 'Costa Rica', 'mayron george'),
	('Mayron George', 'Costa Rica', 'george'),
	('Verza', 'Spain', 'verza'),
	('Tatsuya Morita', 'Japan', 'morita'),
	('Tatsuya Morita', 'Japan', 'tatsuya morita'),
	('Răzvan Oaidă', 'Romania', 'razvan oaida'),
	('Răzvan Oaidă', 'Romania', 'oaida'),
	('Mijat Marić', 'Switzerland', 'maric'),
	('Mijat Marić', 'Switzerland', 'mijat maric'),
	('Alexandros Katranis', 'Greece', 'alexandros katranis'),
	('Alexandros Katranis', 'Greece', 'katranis'),
	('Kamal Sowah', 'Ghana', 'sowah'),
	('Kamal Sowah', 'Ghana', 'kamal sowah'),
	('Rémi Pillot', 'France', 'pillot'),
	('Rémi Pillot', 'France', 'remi pillot'),
	('Hugo Seco', 'Portugal', 'seco'),
	('Hugo Seco', 'Portugal', 'hugo seco'),
	('Ryan Allsop', 'England', 'allsop'),
	('Ryan Allsop', 'England', 'ryan allsop'),
	('Jakub Szumski', 'Poland', 'szumski'),
	('Jakub Szumski', 'Poland', 'jakub szumski'),
	('Sim Sang Min', 'Korea Republic', 'sim sang min'),
	('Sim Sang Min', 'Korea Republic', 'min'),
	('Zlatan Alomerović', 'Serbia', 'zlatan alomerovic'),
	('Zlatan Alomerović', 'Serbia', 'alomerovic'),
	('Reza Asadi', 'Iran', 'asadi'),
	('Reza Asadi', 'Iran', 'reza asadi'),
	('Matías Esquivel', 'Argentina', 'esquivel'),
	('Matías Esquivel', 'Argentina', 'matias esquivel'),
	('Patrik Karlsson Lagemyr', 'Sweden', 'patrik karlsson lagemyr'),
	('Patrik Karlsson Lagemyr', 'Sweden', 'lagemyr'),
	('Leo Coelho', 'Brazil', 'coelho'),
	('Leo Coelho', 'Brazil', 'leo coelho'),
	('Andreas Leitner', 'Austria', 'andreas leitner'),
	('Andreas Leitner', 'Austria', 'leitner'),
	('Michael Pereira', 'France', 'pereira'),
	('Michael Pereira', 'France', 'michael pereira'),
	('Johannes Wurtz', 'Germany', 'wurtz'),
	('Johannes Wurtz', 'Germany', 'johannes wurtz'),
	('Philipp Zulechner', 'Austria', 'philipp zulechner'),
	('Philipp Zulechner', 'Austria', 'zulechner'),
	('Sessi D''Almeida', 'Benin', 'dalmeida'),
	('Sessi D''Almeida', 'Benin', 'sessi dalmeida'),
	('Brandon Bye', 'United States', 'brandon bye'),
	('Brandon Bye', 'United States', 'bye'),
	('Luka Ilić', 'Serbia', 'luka ilic'),
	('Luka Ilić', 'Serbia', 'ilic'),
	('Ersin Destanoğlu', 'Turkey', 'destanoglu'),
	('Ersin Destanoğlu', 'Turkey', 'ersin destanoglu'),
	('Bart Vriends', 'Netherlands', 'vriends'),
	('Bart Vriends', 'Netherlands', 'bart vriends'),
	('Walter Clar', 'Paraguay', 'clar'),
	('Walter Clar', 'Paraguay', 'walter clar'),
	('Charles Monsalvo', 'Colombia', 'charles monsalvo'),
	('Charles Monsalvo', 'Colombia', 'monsalvo'),
	('Stefan Lex', 'Germany', 'stefan lex'),
	('Stefan Lex', 'Germany', 'lex'),
	('Jean-Claude Billong', 'France', 'billong'),
	('Jean-Claude Billong', 'France', 'jeanclaude billong'),
	('Eldin Jakupović', 'Switzerland', 'eldin jakupovic'),
	('Eldin Jakupović', 'Switzerland', 'jakupovic'),
	('Scott McMann', 'Scotland', 'mcmann'),
	('Scott McMann', 'Scotland', 'scott mcmann'),
	('Cándido Ramírez', 'Mexico', 'candido ramirez'),
	('Cándido Ramírez', 'Mexico', 'ramirez'),
	('Mart Lieder', 'Netherlands', 'lieder'),
	('Mart Lieder', 'Netherlands', 'mart lieder'),
	('Mattia Finotto', 'Italy', 'finotto'),
	('Mattia Finotto', 'Italy', 'mattia finotto'),
	('Yuki Kobayashi', 'Japan', 'kobayashi'),
	('Yuki Kobayashi', 'Japan', 'yuki kobayashi'),
	('Luis Perea', 'Spain', 'luis perea'),
	('Luis Perea', 'Spain', 'perea'),
	('Daniel Febles', 'Venezuela', 'daniel febles'),
	('Daniel Febles', 'Venezuela', 'febles'),
	('Erik Expósito', 'Spain', 'erik exposito'),
	('Erik Expósito', 'Spain', 'exposito'),
	('Toshio Shimakawa', 'Japan', 'shimakawa'),
	('Toshio Shimakawa', 'Japan', 'toshio shimakawa'),
	('Marc McNulty', 'Scotland', 'mcnulty'),
	('Marc McNulty', 'Scotland', 'marc mcnulty'),
	('Dario Del Fabro', 'Italy', 'dario del fabro'),
	('Dario Del Fabro', 'Italy', 'fabro'),
	('Shinnosuke Nakatani', 'Japan', 'nakatani'),
	('Shinnosuke Nakatani', 'Japan', 'shinnosuke nakatani'),
	('Kirian', 'Spain', 'kirian'),
	('Robert Lundström', 'Sweden', 'robert lundstrom'),
	('Robert Lundström', 'Sweden', 'lundstrom'),
	('Quenten Martinus', 'Curacao', 'quenten martinus'),
	('Quenten Martinus', 'Curacao', 'martinus'),
	('Max O''Leary', 'England', 'max oleary'),
	('Max O''Leary', 'England', 'oleary'),
	('Bojan Letić', 'Bosnia Herzegovina', 'letic'),
	('Bojan Letić', 'Bosnia Herzegovina', 'bojan letic'),
	('Rafael Barros', 'Brazil', 'rafael barros'),
	('Rafael Barros', 'Brazil', 'barros'),
	('Sean McConville', 'England', 'mcconville'),
	('Sean McConville', 'England', 'sean mcconville'),
	('Jesús Medina', 'Paraguay', 'jesus medina'),
	('Jesús Medina', 'Paraguay', 'medina'),
	('Mario de Luna', 'Mexico', 'luna'),
	('Mario de Luna', 'Mexico', 'mario de luna'),
	('Salvatore Esposito', 'Italy', 'salvatore esposito'),
	('Salvatore Esposito', 'Italy', 'esposito'),
	('Jonathan Toledo', 'Uruguay', 'jonathan toledo'),
	('Jonathan Toledo', 'Uruguay', 'toledo'),
	('Joshua Smits', 'Netherlands', 'smits'),
	('Joshua Smits', 'Netherlands', 'joshua smits'),
	('Muammer Yıldırım', 'Turkey', 'yldrm'),
	('Muammer Yıldırım', 'Turkey', 'muammer yldrm'),
	('Gary Madine', 'England', 'madine'),
	('Gary Madine', 'England', 'gary madine'),
	('Carlos Melgar', 'Bolivia', 'carlos melgar'),
	('Carlos Melgar', 'Bolivia', 'melgar'),
	('Xavier Arreaga', 'Ecuador', 'arreaga'),
	('Xavier Arreaga', 'Ecuador', 'xavier arreaga'),
	('Aster Vranckx', 'Belgium', 'vranckx'),
	('Aster Vranckx', 'Belgium', 'aster vranckx'),
	('Olaetxea', 'Spain', 'olaetxea'),
	('Leandro Suhr', 'Uruguay', 'leandro suhr'),
	('Leandro Suhr', 'Uruguay', 'suhr'),
	('Niklas Sandberg', 'Norway', 'niklas sandberg'),
	('Niklas Sandberg', 'Norway', 'sandberg'),
	('Jake Mulraney', 'Republic of Ireland', 'jake mulraney'),
	('Jake Mulraney', 'Republic of Ireland', 'mulraney'),
	('Scott Pittman', 'Scotland', 'scott pittman'),
	('Scott Pittman', 'Scotland', 'pittman'),
	('Tomás Esteves', 'Portugal', 'tomas esteves'),
	('Tomás Esteves', 'Portugal', 'esteves'),
	('Gaspar Iñiguez', 'Argentina', 'iniguez'),
	('Gaspar Iñiguez', 'Argentina', 'gaspar iniguez'),
	('Tobias Schwede', 'Germany', 'schwede'),
	('Tobias Schwede', 'Germany', 'tobias schwede'),
	('Matt Olosunde', 'United States', 'olosunde'),
	('Matt Olosunde', 'United States', 'matt olosunde'),
	('Makana Baku', 'Germany', 'makana baku'),
	('Makana Baku', 'Germany', 'baku'),
	('Andreas Landgren', 'Sweden', 'andreas landgren'),
	('Andreas Landgren', 'Sweden', 'landgren'),
	('Marcel Ziegl', 'Austria', 'ziegl'),
	('Marcel Ziegl', 'Austria', 'marcel ziegl'),
	('Tortol Lumanza Lembi', 'Belgium', 'tortol lumanza lembi'),
	('Tortol Lumanza Lembi', 'Belgium', 'lembi'),
	('Murat Uçar', 'Turkey', 'murat ucar'),
	('Murat Uçar', 'Turkey', 'ucar'),
	('Milan Dimun', 'Slovakia', 'milan dimun'),
	('Milan Dimun', 'Slovakia', 'dimun'),
	('Bright Edomwonyi', 'Nigeria', 'edomwonyi'),
	('Bright Edomwonyi', 'Nigeria', 'bright edomwonyi'),
	('Christian Dorda', 'Germany', 'dorda'),
	('Christian Dorda', 'Germany', 'christian dorda'),
	('Adam Frączczak', 'Poland', 'adam fraczczak'),
	('Adam Frączczak', 'Poland', 'fraczczak'),
	('Daniel-Kofi Kyereh', 'Germany', 'kyereh'),
	('Daniel-Kofi Kyereh', 'Germany', 'danielkofi kyereh'),
	('Arild Østbø', 'Norway', 'arild stb'),
	('Arild Østbø', 'Norway', 'stb'),
	('Gabriel Brazão', 'Brazil', 'brazao'),
	('Gabriel Brazão', 'Brazil', 'gabriel brazao'),
	('Moussa Sylla', 'France', 'sylla'),
	('Moussa Sylla', 'France', 'moussa sylla'),
	('Alan Lithgow', 'Scotland', 'lithgow'),
	('Alan Lithgow', 'Scotland', 'alan lithgow'),
	('Sam McCallum', 'England', 'sam mccallum'),
	('Sam McCallum', 'England', 'mccallum'),
	('Juan Alano', 'Brazil', 'alano'),
	('Juan Alano', 'Brazil', 'juan alano'),
	('Matías Pardo', 'Argentina', 'pardo'),
	('Matías Pardo', 'Argentina', 'matias pardo'),
	('Jonathan Grounds', 'England', 'grounds'),
	('Jonathan Grounds', 'England', 'jonathan grounds'),
	('Lukáš Juliš', 'Czech Republic', 'julis'),
	('Lukáš Juliš', 'Czech Republic', 'lukas julis'),
	('Nicolò Manfredini', 'Italy', 'nicolo manfredini'),
	('Nicolò Manfredini', 'Italy', 'manfredini'),
	('Dean Furman', 'South Africa', 'dean furman'),
	('Dean Furman', 'South Africa', 'furman'),
	('Greg Leigh', 'England', 'leigh'),
	('Greg Leigh', 'England', 'greg leigh'),
	('Tom Boere', 'Netherlands', 'tom boere'),
	('Tom Boere', 'Netherlands', 'boere'),
	('Joseph Mills', 'England', 'joseph mills'),
	('Joseph Mills', 'England', 'mills'),
	('Russell Teibert', 'Canada', 'teibert'),
	('Russell Teibert', 'Canada', 'russell teibert'),
	('Abdullah Madu', 'Saudi Arabia', 'madu'),
	('Abdullah Madu', 'Saudi Arabia', 'abdullah madu'),
	('Facundo Altamirano', 'Argentina', 'facundo altamirano'),
	('Facundo Altamirano', 'Argentina', 'altamirano'),
	('Marian Pleașcă', 'Romania', 'marian pleasca'),
	('Marian Pleașcă', 'Romania', 'pleasca'),
	('Kristoffer Løkberg', 'Norway', 'kristoffer lkberg'),
	('Kristoffer Løkberg', 'Norway', 'lkberg'),
	('Jordan Shipley', 'Republic of Ireland', 'shipley'),
	('Jordan Shipley', 'Republic of Ireland', 'jordan shipley'),
	('Luis Segovia', 'Ecuador', 'segovia'),
	('Luis Segovia', 'Ecuador', 'luis segovia'),
	('Dave Gnaase', 'Germany', 'gnaase'),
	('Dave Gnaase', 'Germany', 'dave gnaase'),
	('Cristian Colmán', 'Paraguay', 'cristian colman'),
	('Cristian Colmán', 'Paraguay', 'colman'),
	('Ricardo Alves', 'Portugal', 'alves'),
	('Ricardo Alves', 'Portugal', 'ricardo alves'),
	('Xie Pengfei', 'China PR', 'xie pengfei'),
	('Xie Pengfei', 'China PR', 'pengfei'),
	('Rodrigo Ureña', 'Chile', 'urena'),
	('Rodrigo Ureña', 'Chile', 'rodrigo urena'),
	('Ruben Kristiansen', 'Norway', 'kristiansen'),
	('Ruben Kristiansen', 'Norway', 'ruben kristiansen'),
	('Jorge Zules Caicedo', 'Colombia', 'jorge zules caicedo'),
	('Jorge Zules Caicedo', 'Colombia', 'caicedo'),
	('Pablo Cifuentes', 'Ecuador', 'cifuentes'),
	('Pablo Cifuentes', 'Ecuador', 'pablo cifuentes'),
	('Ștefan Vlădoiu', 'Romania', 'vladoiu'),
	('Ștefan Vlădoiu', 'Romania', 'stefan vladoiu'),
	('Bentley Baxter Bahn', 'Germany', 'bahn'),
	('Bentley Baxter Bahn', 'Germany', 'bentley baxter bahn'),
	('Morgan Poaty', 'France', 'morgan poaty'),
	('Morgan Poaty', 'France', 'poaty'),
	('Nikola Jambor', 'Croatia', 'nikola jambor'),
	('Nikola Jambor', 'Croatia', 'jambor'),
	('Paseka Mako', 'South Africa', 'mako'),
	('Paseka Mako', 'South Africa', 'paseka mako'),
	('Olabe', 'Spain', 'olabe'),
	('Niklas Hauptmann', 'Germany', 'niklas hauptmann'),
	('Niklas Hauptmann', 'Germany', 'hauptmann'),
	('Petrus Boumal', 'Cameroon', 'petrus boumal'),
	('Petrus Boumal', 'Cameroon', 'boumal'),
	('Mohammed Abu', 'Ghana', 'mohammed abu'),
	('Mohammed Abu', 'Ghana', 'abu'),
	('Marcin Listkowski', 'Poland', 'marcin listkowski'),
	('Marcin Listkowski', 'Poland', 'listkowski'),
	('Ethan Laird', 'England', 'ethan laird'),
	('Ethan Laird', 'England', 'laird'),
	('Sven Köhler', 'Germany', 'sven kohler'),
	('Sven Köhler', 'Germany', 'kohler'),
	('Janner Corozo', 'Ecuador', 'janner corozo'),
	('Janner Corozo', 'Ecuador', 'corozo'),
	('Park Jong Woo', 'Korea Republic', 'woo'),
	('Park Jong Woo', 'Korea Republic', 'park jong woo'),
	('Gabriel Simion', 'Romania', 'gabriel simion'),
	('Gabriel Simion', 'Romania', 'simion'),
	('Marco Ureña', 'Costa Rica', 'marco urena'),
	('Marco Ureña', 'Costa Rica', 'urena'),
	('Yuichi Maruyama', 'Japan', 'maruyama'),
	('Yuichi Maruyama', 'Japan', 'yuichi maruyama'),
	('Diego Sosa', 'Argentina', 'sosa'),
	('Diego Sosa', 'Argentina', 'diego sosa'),
	('Pavel Maslov', 'Russia', 'maslov'),
	('Pavel Maslov', 'Russia', 'pavel maslov'),
	('Wojciech Golla', 'Poland', 'golla'),
	('Wojciech Golla', 'Poland', 'wojciech golla'),
	('Andersson Ordóñez', 'Ecuador', 'ordonez'),
	('Andersson Ordóñez', 'Ecuador', 'andersson ordonez'),
	('John Fajardo', 'Peru', 'john fajardo'),
	('John Fajardo', 'Peru', 'fajardo'),
	('Daniel Fuzato', 'Brazil', 'fuzato'),
	('Daniel Fuzato', 'Brazil', 'daniel fuzato'),
	('Kei Koizumi', 'Japan', 'koizumi'),
	('Kei Koizumi', 'Japan', 'kei koizumi'),
	('Gastón Gómez', 'Argentina', 'gomez'),
	('Gastón Gómez', 'Argentina', 'gaston gomez'),
	('Tuta', 'Brazil', 'tuta'),
	('Cristian Flores', 'Venezuela', 'cristian flores'),
	('Cristian Flores', 'Venezuela', 'flores'),
	('Rudy Camacho', 'France', 'camacho'),
	('Rudy Camacho', 'France', 'rudy camacho'),
	('Makhtar Gueye', 'Senegal', 'makhtar gueye'),
	('Makhtar Gueye', 'Senegal', 'gueye'),
	('Michal Sipľak', 'Slovakia', 'michal siplak'),
	('Michal Sipľak', 'Slovakia', 'siplak'),
	('Lennart Moser', 'Germany', 'moser'),
	('Lennart Moser', 'Germany', 'lennart moser'),
	('Forniés', 'Spain', 'fornies'),
	('Ko Seung Beom', 'Korea Republic', 'ko seung beom'),
	('Ko Seung Beom', 'Korea Republic', 'beom'),
	('Denis Rodríguez', 'Argentina', 'rodriguez'),
	('Denis Rodríguez', 'Argentina', 'denis rodriguez'),
	('Jordan Cousins', 'England', 'cousins'),
	('Jordan Cousins', 'England', 'jordan cousins'),
	('Jessic Ngankam', 'Germany', 'jessic ngankam'),
	('Jessic Ngankam', 'Germany', 'ngankam'),
	('Eric Smith', 'Sweden', 'smith'),
	('Eric Smith', 'Sweden', 'eric smith'),
	('Jin Jingdao', 'China PR', 'jin jingdao'),
	('Jin Jingdao', 'China PR', 'jingdao'),
	('Bilel Saidani', 'Tunisia', 'bilel saidani'),
	('Bilel Saidani', 'Tunisia', 'saidani'),
	('Callum Johnson', 'England', 'johnson'),
	('Callum Johnson', 'England', 'callum johnson'),
	('Serge Tabekou', 'Cameroon', 'serge tabekou'),
	('Serge Tabekou', 'Cameroon', 'tabekou'),
	('Stian Rode Gregersen', 'Norway', 'gregersen'),
	('Stian Rode Gregersen', 'Norway', 'stian rode gregersen'),
	('Dimitri Mohamed', 'France', 'dimitri mohamed'),
	('Dimitri Mohamed', 'France', 'mohamed'),
	('Zié Mohamed Ouattara', 'Ivory Coast', 'zie mohamed ouattara'),
	('Zié Mohamed Ouattara', 'Ivory Coast', 'ouattara'),
	('Tim Boss', 'Germany', 'boss'),
	('Tim Boss', 'Germany', 'tim boss'),
	('Abdullah Al Khaibari', 'Saudi Arabia', 'khaibari'),
	('Abdullah Al Khaibari', 'Saudi Arabia', 'abdullah al khaibari'),
	('Ufuk Akyol', 'Germany', 'akyol'),
	('Ufuk Akyol', 'Germany', 'ufuk akyol'),
	('Fredrik Oldrup Jensen', 'Norway', 'fredrik oldrup jensen'),
	('Fredrik Oldrup Jensen', 'Norway', 'jensen'),
	('Dylan Louiserre', 'France', 'dylan louiserre'),
	('Dylan Louiserre', 'France', 'louiserre'),
	('Romario Moise', 'Romania', 'romario moise'),
	('Romario Moise', 'Romania', 'moise'),
	('Jack Colback', 'England', 'jack colback'),
	('Jack Colback', 'England', 'colback'),
	('Tim Kister', 'Germany', 'kister'),
	('Tim Kister', 'Germany', 'tim kister'),
	('Jakub Bartkowski', 'Poland', 'bartkowski'),
	('Jakub Bartkowski', 'Poland', 'jakub bartkowski'),
	('Muzepper Mirahmetjan', 'China PR', 'mirahmetjan'),
	('Muzepper Mirahmetjan', 'China PR', 'muzepper mirahmetjan'),
	('Lasse Vibe', 'Denmark', 'lasse vibe'),
	('Lasse Vibe', 'Denmark', 'vibe'),
	('Hassan Kadish', 'Saudi Arabia', 'kadish'),
	('Hassan Kadish', 'Saudi Arabia', 'hassan kadish'),
	('Nik Omladič', 'Slovenia', 'nik omladic'),
	('Nik Omladič', 'Slovenia', 'omladic'),
	('Gabriel Souza', 'Brazil', 'souza'),
	('Gabriel Souza', 'Brazil', 'gabriel souza'),
	('Leonardo Bertone', 'Switzerland', 'leonardo bertone'),
	('Leonardo Bertone', 'Switzerland', 'bertone'),
	('Luke Hemmerich', 'Germany', 'luke hemmerich'),
	('Luke Hemmerich', 'Germany', 'hemmerich'),
	('Yasin Pehlivan', 'Austria', 'pehlivan'),
	('Yasin Pehlivan', 'Austria', 'yasin pehlivan'),
	('Diego Martínez', 'Colombia', 'martinez'),
	('Diego Martínez', 'Colombia', 'diego martinez'),
	('Jhon Vásquez', 'Colombia', 'vasquez'),
	('Jhon Vásquez', 'Colombia', 'jhon vasquez'),
	('Rasmus Nicolaisen', 'Denmark', 'rasmus nicolaisen'),
	('Rasmus Nicolaisen', 'Denmark', 'nicolaisen'),
	('Cristian', 'Spain', 'cristian'),
	('Kyohei Yoshino', 'Japan', 'kyohei yoshino'),
	('Kyohei Yoshino', 'Japan', 'yoshino'),
	('Max Besuschkow', 'Germany', 'besuschkow'),
	('Max Besuschkow', 'Germany', 'max besuschkow'),
	('Scott Jamieson', 'Australia', 'jamieson'),
	('Scott Jamieson', 'Australia', 'scott jamieson'),
	('Yin Hongbo', 'China PR', 'hongbo'),
	('Yin Hongbo', 'China PR', 'yin hongbo'),
	('Fabian Kalig', 'Germany', 'kalig'),
	('Fabian Kalig', 'Germany', 'fabian kalig'),
	('Danilo Arboleda', 'Colombia', 'danilo arboleda'),
	('Danilo Arboleda', 'Colombia', 'arboleda'),
	('Ionuț Larie', 'Romania', 'larie'),
	('Ionuț Larie', 'Romania', 'ionut larie'),
	('Ferdinand Oswald', 'Germany', 'ferdinand oswald'),
	('Ferdinand Oswald', 'Germany', 'oswald'),
	('Alan Judge', 'Republic of Ireland', 'alan judge'),
	('Alan Judge', 'Republic of Ireland', 'judge'),
	('Sascha Mölders', 'Germany', 'molders'),
	('Sascha Mölders', 'Germany', 'sascha molders'),
	('Maxime D''Arpino', 'France', 'maxime darpino'),
	('Maxime D''Arpino', 'France', 'darpino'),
	('Daniël van Kaam', 'Netherlands', 'daniel van kaam'),
	('Daniël van Kaam', 'Netherlands', 'kaam'),
	('Delano Burgzorg', 'Netherlands', 'burgzorg'),
	('Delano Burgzorg', 'Netherlands', 'delano burgzorg'),
	('Roland Niczuly', 'Romania', 'niczuly'),
	('Roland Niczuly', 'Romania', 'roland niczuly'),
	('Kayden Jackson', 'England', 'kayden jackson'),
	('Kayden Jackson', 'England', 'jackson'),
	('Gaëtan Karlen', 'Switzerland', 'gaetan karlen'),
	('Gaëtan Karlen', 'Switzerland', 'karlen'),
	('Paweł Cibicki', 'Sweden', 'cibicki'),
	('Paweł Cibicki', 'Sweden', 'pawe cibicki'),
	('Prosper Mendy', 'France', 'mendy'),
	('Prosper Mendy', 'France', 'prosper mendy'),
	('Abdullah Durak', 'Turkey', 'abdullah durak'),
	('Abdullah Durak', 'Turkey', 'durak'),
	('Wálter Chalá', 'Ecuador', 'chala'),
	('Wálter Chalá', 'Ecuador', 'walter chala'),
	('Sérgio Marakis', 'Portugal', 'sergio marakis'),
	('Sérgio Marakis', 'Portugal', 'marakis'),
	('Wang Shangyuan', 'China PR', 'wang shangyuan'),
	('Wang Shangyuan', 'China PR', 'shangyuan'),
	('Mairon Quiñones', 'Colombia', 'quinones'),
	('Mairon Quiñones', 'Colombia', 'mairon quinones'),
	('Nils Fröling', 'Sweden', 'nils froling'),
	('Nils Fröling', 'Sweden', 'froling'),
	('Dominique Badji', 'Senegal', 'dominique badji'),
	('Dominique Badji', 'Senegal', 'badji'),
	('A.J. DeLaGarza', 'Guam', 'delagarza'),
	('A.J. DeLaGarza', 'Guam', 'aj delagarza'),
	('Tim Coremans', 'Netherlands', 'tim coremans'),
	('Tim Coremans', 'Netherlands', 'coremans'),
	('Fabian Nürnberger', 'Germany', 'nurnberger'),
	('Fabian Nürnberger', 'Germany', 'fabian nurnberger'),
	('Wu Xinghan', 'China PR', 'wu xinghan'),
	('Wu Xinghan', 'China PR', 'xinghan'),
	('Jakub Słowik', 'Poland', 'jakub sowik'),
	('Jakub Słowik', 'Poland', 'sowik'),
	('Michael Heylen', 'Belgium', 'heylen'),
	('Michael Heylen', 'Belgium', 'michael heylen'),
	('Michael Huber', 'Austria', 'michael huber'),
	('Michael Huber', 'Austria', 'huber'),
	('Julien Serrano', 'France', 'julien serrano'),
	('Julien Serrano', 'France', 'serrano'),
	('Yuta Nakayama', 'Japan', 'nakayama'),
	('Yuta Nakayama', 'Japan', 'yuta nakayama'),
	('Javier Salas', 'Mexico', 'javier salas'),
	('Javier Salas', 'Mexico', 'salas'),
	('Ntsikelelo Nyauza', 'South Africa', 'ntsikelelo nyauza'),
	('Ntsikelelo Nyauza', 'South Africa', 'nyauza'),
	('Victor Wernersson', 'Sweden', 'victor wernersson'),
	('Victor Wernersson', 'Sweden', 'wernersson'),
	('Aaron Tshibola', 'DR Congo', 'tshibola'),
	('Aaron Tshibola', 'DR Congo', 'aaron tshibola'),
	('Pa Konate', 'Guinea', 'pa konate'),
	('Pa Konate', 'Guinea', 'konate'),
	('Riquelme', 'Spain', 'riquelme'),
	('Daiki Watari', 'Japan', 'daiki watari'),
	('Daiki Watari', 'Japan', 'watari'),
	('Carlos Miguel', 'Brazil', 'carlos miguel'),
	('Carlos Miguel', 'Brazil', 'miguel'),
	('Abel Mabaso', 'South Africa', 'abel mabaso'),
	('Abel Mabaso', 'South Africa', 'mabaso'),
	('Igor Zlatanović', 'Serbia', 'igor zlatanovic'),
	('Igor Zlatanović', 'Serbia', 'zlatanovic'),
	('Ryosuke Maeda', 'Japan', 'maeda'),
	('Ryosuke Maeda', 'Japan', 'ryosuke maeda'),
	('Ayman Ben Mohamed', 'Tunisia', 'ayman ben mohamed'),
	('Ayman Ben Mohamed', 'Tunisia', 'mohamed'),
	('Kohei Shimizu', 'Japan', 'kohei shimizu'),
	('Kohei Shimizu', 'Japan', 'shimizu'),
	('Per Frick', 'Sweden', 'frick'),
	('Per Frick', 'Sweden', 'per frick'),
	('Jonas Carls', 'Germany', 'jonas carls'),
	('Jonas Carls', 'Germany', 'carls'),
	('Lee Yeong Jae', 'Korea Republic', 'jae'),
	('Lee Yeong Jae', 'Korea Republic', 'lee yeong jae'),
	('David Carmona', 'Spain', 'david carmona'),
	('David Carmona', 'Spain', 'carmona'),
	('Leo Weinkauf', 'Germany', 'weinkauf'),
	('Leo Weinkauf', 'Germany', 'leo weinkauf'),
	('Jordan Rossiter', 'England', 'rossiter'),
	('Jordan Rossiter', 'England', 'jordan rossiter'),
	('Juan Ibiza', 'Spain', 'ibiza'),
	('Juan Ibiza', 'Spain', 'juan ibiza'),
	('Tommy Oar', 'Australia', 'tommy oar'),
	('Tommy Oar', 'Australia', 'oar'),
	('Maximilian Welzmüller', 'Germany', 'welzmuller'),
	('Maximilian Welzmüller', 'Germany', 'maximilian welzmuller'),
	('Dimitri Lavalée', 'Belgium', 'lavalee'),
	('Dimitri Lavalée', 'Belgium', 'dimitri lavalee'),
	('Maic Sema', 'Sweden', 'maic sema'),
	('Maic Sema', 'Sweden', 'sema'),
	('Murat Akça', 'Turkey', 'akca'),
	('Murat Akça', 'Turkey', 'murat akca'),
	('Daniel Quiñones', 'Colombia', 'quinones'),
	('Daniel Quiñones', 'Colombia', 'daniel quinones')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';