INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Lucas Pirard', 'Belgium', 'player'),
	('Tyronne Ebuehi', 'Nigeria', 'player'),
	('Sone Aluko', 'Nigeria', 'player'),
	('Thomas Deng', 'Australia', 'player'),
	('Jonathan Sabbatini', 'Uruguay', 'player'),
	('Norberto Briasco', 'Armenia', 'player'),
	('Patryk Klimala', 'Poland', 'player'),
	('Morten Behrens', 'Germany', 'player'),
	('Jairo González', 'Mexico', 'player'),
	('Matt Ingram', 'England', 'player'),
	('Michael', 'Brazil', 'player'),
	('Chris Long', 'England', 'player'),
	('Jeickson Reyes', 'Peru', 'player'),
	('Navajo Bakboord', 'Netherlands', 'player'),
	('Jonathan Heris', 'Belgium', 'player'),
	('Jay Spearing', 'England', 'player'),
	('Víctor Peña', 'Peru', 'player'),
	('Joe Willis', 'United States', 'player'),
	('Kim Gun Hee', 'Korea Republic', 'player'),
	('James Coppinger', 'England', 'player'),
	('Joel Pereira', 'Portugal', 'player'),
	('Alan Uryga', 'Poland', 'player'),
	('George Moncur', 'England', 'player'),
	('Kawin Thamsatchanan', 'Thailand', 'player'),
	('Chris Seitz', 'United States', 'player'),
	('Wilfried Kanga', 'France', 'player'),
	('Jérémy Guillemenot', 'Switzerland', 'player'),
	('Robinho', 'Brazil', 'player'),
	('Danilo Wiebe', 'Germany', 'player'),
	('Oliver Rathbone', 'England', 'player'),
	('Jonathan Parr', 'Norway', 'player'),
	('Elvis Bwomono', 'Uganda', 'player'),
	('Tesfaldet Tekie', 'Sweden', 'player'),
	('Ryan Meara', 'United States', 'player'),
	('Mohamed Ezzarfani', 'Morocco', 'player'),
	('Carlos Neyra', 'Peru', 'player'),
	('Bruno Vides', 'Argentina', 'player'),
	('Marco Borgnino', 'Argentina', 'player'),
	('Ezequiel', 'Brazil', 'player'),
	('Henry Wingo', 'United States', 'player'),
	('Harry Pickering', 'England', 'player'),
	('Axel Björnström', 'Sweden', 'player'),
	('Kosuke Taketomi', 'Japan', 'player'),
	('Tobias Schröck', 'Germany', 'player'),
	('Martin Hansen', 'Denmark', 'player'),
	('Mateusz Cholewiak', 'Poland', 'player'),
	('Eduardo Aguirre', 'Mexico', 'player'),
	('Cedric Teguía', 'Spain', 'player'),
	('Félix Correia', 'Portugal', 'player'),
	('Marcel Gottschling', 'Germany', 'player'),
	('Antonio Delamea', 'Slovenia', 'player'),
	('Kim Chang Soo', 'Korea Republic', 'player'),
	('Maximilian Thiel', 'Germany', 'player'),
	('Vitaliy Lisakovich', 'Belarus', 'player'),
	('Vitor Carvalho', 'Brazil', 'player'),
	('Maurice Deville', 'Luxembourg', 'player'),
	('Simon Sluga', 'Croatia', 'player'),
	('Adonis Frías', 'Argentina', 'player'),
	('Song Bum Keun', 'Korea Republic', 'player'),
	('Yohann Magnin', 'France', 'player'),
	('Gonçalo Cardoso', 'Portugal', 'player'),
	('Herman Stengel', 'Norway', 'player'),
	('Paolo Fernandes', 'Spain', 'player'),
	('Michael Schultz', 'Germany', 'player'),
	('Frédéric Duplus', 'France', 'player'),
	('Jairo Padilla', 'Ecuador', 'player'),
	('Sofian Chakla', 'Morocco', 'player'),
	('Ryan McGowan', 'Australia', 'player'),
	('Yu Sang Hun', 'Korea Republic', 'player'),
	('Saleh Al Shehri', 'Saudi Arabia', 'player'),
	('Mateo Cassierra', 'Colombia', 'player'),
	('Stallone Limbombe', 'Belgium', 'player'),
	('Mathias Rasmussen', 'Norway', 'player'),
	('Filipe Melo', 'Portugal', 'player'),
	('Arnaldo Giménez', 'Paraguay', 'player'),
	('Jovan Stojanović', 'Serbia', 'player'),
	('Jaime Seoane', 'Spain', 'player'),
	('Przemysław Wiśniewski', 'Poland', 'player'),
	('Jang Ho Ik', 'Korea Republic', 'player'),
	('Moses Ogbu', 'Nigeria', 'player'),
	('Carlos Cuero', 'Ecuador', 'player'),
	('Seo Bo Min', 'Korea Republic', 'player'),
	('Luca Vignali', 'Italy', 'player'),
	('Ben Sheaf', 'England', 'player'),
	('Rasmus Jönsson', 'Sweden', 'player'),
	('Dave Romney', 'United States', 'player'),
	('César Díaz', 'Spain', 'player'),
	('Matías Gómez', 'Argentina', 'player'),
	('Siriki Dembele', 'Scotland', 'player'),
	('Anthony Grant', 'England', 'player'),
	('Ousmane Viera', 'Ivory Coast', 'player'),
	('Stephan Auer', 'Austria', 'player'),
	('Jørgen Skjelvik', 'Norway', 'player'),
	('Ignacio Saavedra', 'Chile', 'player'),
	('Patrick Kammerbauer', 'Germany', 'player'),
	('Axel Sjöberg', 'Sweden', 'player'),
	('Alassane Ndiaye', 'France', 'player'),
	('Luis Congo', 'Ecuador', 'player'),
	('Tom Aldred', 'Scotland', 'player'),
	('Óscar Sielva', 'Spain', 'player'),
	('Mario Barco', 'Spain', 'player'),
	('Keito Nakamura', 'Japan', 'player'),
	('Alex Cairns', 'England', 'player'),
	('Kolja Pusch', 'Germany', 'player'),
	('Nathan', 'Brazil', 'player'),
	('Sebastian Hertner', 'Germany', 'player'),
	('Manfred Fischer', 'Austria', 'player'),
	('Montero', 'Spain', 'player'),
	('Jefté', 'Spain', 'player'),
	('Georgios Giakoumakis', 'Greece', 'player'),
	('Joost van Aken', 'Netherlands', 'player'),
	('Kim Yong Hwan', 'Korea Republic', 'player'),
	('Andreas Eines Hopmark', 'Norway', 'player'),
	('Boris Sekulić', 'Slovakia', 'player'),
	('Malcolm Cacutalua', 'Germany', 'player'),
	('Gilberto Sepúlveda', 'Mexico', 'player'),
	('Liam Polworth', 'Scotland', 'player'),
	('Evert Linthorst', 'Netherlands', 'player'),
	('Nathan De Medina', 'Belgium', 'player'),
	('Yuji Rokutan', 'Japan', 'player'),
	('Zapater', 'Spain', 'player'),
	('Haithem Loucif', 'Algeria', 'player'),
	('Jean-Manuel Mbom', 'Germany', 'player'),
	('Bogdan Mitrea', 'Romania', 'player'),
	('Nildo Viera', 'Paraguay', 'player'),
	('Joel López Pissano', 'Argentina', 'player'),
	('Chris Bedia', 'Ivory Coast', 'player'),
	('Pará', 'Brazil', 'player'),
	('Go Moo Yol', 'Korea Republic', 'player'),
	('Dominik Kotarski', 'Croatia', 'player'),
	('Ryan Tafazolli', 'England', 'player'),
	('Iven Austbø', 'Norway', 'player'),
	('Elliott Moore', 'England', 'player'),
	('Callum Camps', 'Northern Ireland', 'player'),
	('Franco Ezequiel Calderón', 'Argentina', 'player'),
	('Jürgen Gjasula', 'Albania', 'player'),
	('Iban Salvador', 'Equatorial Guinea', 'player'),
	('Jérémy Taravel', 'France', 'player'),
	('Moussa Sanoh', 'Netherlands', 'player'),
	('Cristian González', 'Uruguay', 'player'),
	('Steve Lawson', 'Togo', 'player'),
	('Mateu Morey', 'Spain', 'player'),
	('Paul Quasten', 'Czech Republic', 'player'),
	('Nils Röseler', 'Germany', 'player'),
	('Dejan Dražić', 'Serbia', 'player'),
	('Tariq Lamptey', 'England', 'player'),
	('Israel Poblete', 'Chile', 'player'),
	('Dejan Petrovič', 'Slovenia', 'player'),
	('Borja Sainz', 'Spain', 'player'),
	('Anthony Belmonte', 'France', 'player'),
	('Arnaud Kalimuendo', 'France', 'player'),
	('Tom Barlow', 'United States', 'player'),
	('Jaroslav Mihalík', 'Slovakia', 'player'),
	('Warren Creavalle', 'Guyana', 'player'),
	('Scott Kashket', 'England', 'player'),
	('Kyle Duncan', 'United States', 'player'),
	('Zé Uilton', 'Brazil', 'player'),
	('Tim Knipping', 'Germany', 'player'),
	('Anderson', 'Brazil', 'player'),
	('Petter Strand', 'Norway', 'player'),
	('Dario Čanađija', 'Croatia', 'player'),
	('Marcel Rømer', 'Denmark', 'player'),
	('Kim Byeong Oh', 'Korea Republic', 'player'),
	('Malik Tchokounté', 'France', 'player'),
	('Ahmet Arslan', 'Germany', 'player'),
	('Hakan Çinemre', 'Turkey', 'player'),
	('Yang Dong Hyen', 'Korea Republic', 'player'),
	('Mathieu Baudry', 'France', 'player'),
	('Warleson', 'Brazil', 'player'),
	('Emmanuel Lomotey', 'Ghana', 'player'),
	('Wilmer Godoy', 'Ecuador', 'player'),
	('Marcus Piossek', 'Poland', 'player'),
	('Oliver Turton', 'England', 'player'),
	('Micheal Azira', 'Uganda', 'player'),
	('Jon Nolan', 'England', 'player'),
	('Yohan Roche', 'France', 'player'),
	('Joe Newell', 'England', 'player'),
	('Magnar Ødegaard', 'Norway', 'player'),
	('Miguel Angel Sansores', 'Mexico', 'player'),
	('Jonny Smith', 'England', 'player'),
	('Kasper Enghardt', 'Denmark', 'player'),
	('Devyne Rensch', 'Netherlands', 'player'),
	('Mateusz Szwoch', 'Poland', 'player'),
	('Andrew Durante', 'New Zealand', 'player'),
	('Mikkel Kaufmann', 'Denmark', 'player'),
	('Óscar Whalley', 'Spain', 'player'),
	('Shingo Tomita', 'Japan', 'player'),
	('Ufuk Ceylan', 'Turkey', 'player'),
	('Antoni Sarcevic', 'England', 'player'),
	('Connor Ripley', 'England', 'player'),
	('Emeka Friday Eze', 'Nigeria', 'player'),
	('Joe Wildsmith', 'England', 'player'),
	('Leigh Broxham', 'Australia', 'player'),
	('Facundo Pons', 'Argentina', 'player'),
	('Senou Coulibaly', 'Mali', 'player'),
	('Terence Baya', 'France', 'player'),
	('Kyle Vassell', 'Northern Ireland', 'player'),
	('Joe Day', 'England', 'player'),
	('Mohammed Khubrani', 'Saudi Arabia', 'player'),
	('Daniel Pedersen', 'Denmark', 'player'),
	('Joselito Vaca', 'Bolivia', 'player'),
	('Daniel Granli', 'Norway', 'player'),
	('Roni', 'Spain', 'player'),
	('Hernán Figueredo', 'Uruguay', 'player'),
	('Luca Pfeiffer', 'Germany', 'player'),
	('Elias Huth', 'Germany', 'player'),
	('Dimitry Bertaud', 'France', 'player'),
	('Lass Bangoura', 'Guinea', 'player'),
	('Nico Granatowski', 'Germany', 'player'),
	('Bradley Collins', 'England', 'player'),
	('Bryan Gil', 'Spain', 'player'),
	('Carbonell', 'Spain', 'player'),
	('Darren McGregor', 'Scotland', 'player'),
	('Ched Evans', 'Wales', 'player'),
	('Lorenco Šimić', 'Croatia', 'player'),
	('Nicolás Mezquida', 'Uruguay', 'player'),
	('Teden Mengi', 'England', 'player'),
	('Steven Lawless', 'Scotland', 'player'),
	('Myles Kenlock', 'England', 'player'),
	('Nicky Maynard', 'England', 'player'),
	('Miguel Ángel Merentiel', 'Uruguay', 'player'),
	('Hidajet Hankić', 'Austria', 'player'),
	('Abdurrahim Dursun', 'Turkey', 'player'),
	('Tim Rönning', 'Sweden', 'player'),
	('Cillian Sheridan', 'Republic of Ireland', 'player'),
	('Nordin Gerzić', 'Sweden', 'player'),
	('Tawfiq Bu Haymid', 'Saudi Arabia', 'player'),
	('Sepp van den Berg', 'Netherlands', 'player'),
	('Charles Carolus Andriamahitsinoro', 'Madagascar', 'player'),
	('Jeong Hyun Cheol', 'Korea Republic', 'player'),
	('Mark McKenzie', 'United States', 'player'),
	('Jonas Deumeland', 'Germany', 'player'),
	('Daniel Vega', 'Argentina', 'player'),
	('Varo', 'Spain', 'player'),
	('Aliou Coly', 'Senegal', 'player'),
	('Ellis Harrison', 'Wales', 'player'),
	('Cohen Bramall', 'England', 'player'),
	('Mauricio Asenjo', 'Argentina', 'player'),
	('Emanuel Gularte', 'Uruguay', 'player'),
	('El-Hadji Ba', 'France', 'player'),
	('Diego Vallejos', 'Chile', 'player'),
	('Ely', 'Cape Verde', 'player'),
	('Luis Miguel Quezada', 'Dominican Republic', 'player'),
	('John McCarthy', 'United States', 'player'),
	('Delgado', 'Spain', 'player'),
	('Ertuğrul Taşkıran', 'Turkey', 'player'),
	('Gabriel Gudmundsson', 'Sweden', 'player'),
	('Bartosz Slisz', 'Poland', 'player'),
	('Enzo Loiodice', 'France', 'player'),
	('Gustavo Fernández', 'Argentina', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Lucas Pirard', 'Belgium', 'lucas pirard'),
	('Lucas Pirard', 'Belgium', 'pirard'),
	('Tyronne Ebuehi', 'Nigeria', 'ebuehi'),
	('Tyronne Ebuehi', 'Nigeria', 'tyronne ebuehi'),
	('Sone Aluko', 'Nigeria', 'aluko'),
	('Sone Aluko', 'Nigeria', 'sone aluko'),
	('Thomas Deng', 'Australia', 'deng'),
	('Thomas Deng', 'Australia', 'thomas deng'),
	('Jonathan Sabbatini', 'Uruguay', 'jonathan sabbatini'),
	('Jonathan Sabbatini', 'Uruguay', 'sabbatini'),
	('Norberto Briasco', 'Armenia', 'briasco'),
	('Norberto Briasco', 'Armenia', 'norberto briasco'),
	('Patryk Klimala', 'Poland', 'klimala'),
	('Patryk Klimala', 'Poland', 'patryk klimala'),
	('Morten Behrens', 'Germany', 'morten behrens'),
	('Morten Behrens', 'Germany', 'behrens'),
	('Jairo González', 'Mexico', 'jairo gonzalez'),
	('Jairo González', 'Mexico', 'gonzalez'),
	('Matt Ingram', 'England', 'matt ingram'),
	('Matt Ingram', 'England', 'ingram'),
	('Michael', 'Brazil', 'michael'),
	('Chris Long', 'England', 'long'),
	('Chris Long', 'England', 'chris long'),
	('Jeickson Reyes', 'Peru', 'jeickson reyes'),
	('Jeickson Reyes', 'Peru', 'reyes'),
	('Navajo Bakboord', 'Netherlands', 'navajo bakboord'),
	('Navajo Bakboord', 'Netherlands', 'bakboord'),
	('Jonathan Heris', 'Belgium', 'jonathan heris'),
	('Jonathan Heris', 'Belgium', 'heris'),
	('Jay Spearing', 'England', 'jay spearing'),
	('Jay Spearing', 'England', 'spearing'),
	('Víctor Peña', 'Peru', 'victor pena'),
	('Víctor Peña', 'Peru', 'pena'),
	('Joe Willis', 'United States', 'willis'),
	('Joe Willis', 'United States', 'joe willis'),
	('Kim Gun Hee', 'Korea Republic', 'kim gun hee'),
	('Kim Gun Hee', 'Korea Republic', 'hee'),
	('James Coppinger', 'England', 'james coppinger'),
	('James Coppinger', 'England', 'coppinger'),
	('Joel Pereira', 'Portugal', 'joel pereira'),
	('Joel Pereira', 'Portugal', 'pereira'),
	('Alan Uryga', 'Poland', 'uryga'),
	('Alan Uryga', 'Poland', 'alan uryga'),
	('George Moncur', 'England', 'george moncur'),
	('George Moncur', 'England', 'moncur'),
	('Kawin Thamsatchanan', 'Thailand', 'thamsatchanan'),
	('Kawin Thamsatchanan', 'Thailand', 'kawin thamsatchanan'),
	('Chris Seitz', 'United States', 'seitz'),
	('Chris Seitz', 'United States', 'chris seitz'),
	('Wilfried Kanga', 'France', 'wilfried kanga'),
	('Wilfried Kanga', 'France', 'kanga'),
	('Jérémy Guillemenot', 'Switzerland', 'jeremy guillemenot'),
	('Jérémy Guillemenot', 'Switzerland', 'guillemenot'),
	('Robinho', 'Brazil', 'robinho'),
	('Danilo Wiebe', 'Germany', 'danilo wiebe'),
	('Danilo Wiebe', 'Germany', 'wiebe'),
	('Oliver Rathbone', 'England', 'oliver rathbone'),
	('Oliver Rathbone', 'England', 'rathbone'),
	('Jonathan Parr', 'Norway', 'jonathan parr'),
	('Jonathan Parr', 'Norway', 'parr'),
	('Elvis Bwomono', 'Uganda', 'elvis bwomono'),
	('Elvis Bwomono', 'Uganda', 'bwomono'),
	('Tesfaldet Tekie', 'Sweden', 'tekie'),
	('Tesfaldet Tekie', 'Sweden', 'tesfaldet tekie'),
	('Ryan Meara', 'United States', 'ryan meara'),
	('Ryan Meara', 'United States', 'meara'),
	('Mohamed Ezzarfani', 'Morocco', 'ezzarfani'),
	('Mohamed Ezzarfani', 'Morocco', 'mohamed ezzarfani'),
	('Carlos Neyra', 'Peru', 'neyra'),
	('Carlos Neyra', 'Peru', 'carlos neyra'),
	('Bruno Vides', 'Argentina', 'vides'),
	('Bruno Vides', 'Argentina', 'bruno vides'),
	('Marco Borgnino', 'Argentina', 'marco borgnino'),
	('Marco Borgnino', 'Argentina', 'borgnino'),
	('Ezequiel', 'Brazil', 'ezequiel'),
	('Henry Wingo', 'United States', 'henry wingo'),
	('Henry Wingo', 'United States', 'wingo'),
	('Harry Pickering', 'England', 'pickering'),
	('Harry Pickering', 'England', 'harry pickering'),
	('Axel Björnström', 'Sweden', 'axel bjornstrom'),
	('Axel Björnström', 'Sweden', 'bjornstrom'),
	('Kosuke Taketomi', 'Japan', 'kosuke taketomi'),
	('Kosuke Taketomi', 'Japan', 'taketomi'),
	('Tobias Schröck', 'Germany', 'schrock'),
	('Tobias Schröck', 'Germany', 'tobias schrock'),
	('Martin Hansen', 'Denmark', 'hansen'),
	('Martin Hansen', 'Denmark', 'martin hansen'),
	('Mateusz Cholewiak', 'Poland', 'mateusz cholewiak'),
	('Mateusz Cholewiak', 'Poland', 'cholewiak'),
	('Eduardo Aguirre', 'Mexico', 'aguirre'),
	('Eduardo Aguirre', 'Mexico', 'eduardo aguirre'),
	('Cedric Teguía', 'Spain', 'teguia'),
	('Cedric Teguía', 'Spain', 'cedric teguia'),
	('Félix Correia', 'Portugal', 'felix correia'),
	('Félix Correia', 'Portugal', 'correia'),
	('Marcel Gottschling', 'Germany', 'gottschling'),
	('Marcel Gottschling', 'Germany', 'marcel gottschling'),
	('Antonio Delamea', 'Slovenia', 'antonio delamea'),
	('Antonio Delamea', 'Slovenia', 'delamea'),
	('Kim Chang Soo', 'Korea Republic', 'soo'),
	('Kim Chang Soo', 'Korea Republic', 'kim chang soo'),
	('Maximilian Thiel', 'Germany', 'maximilian thiel'),
	('Maximilian Thiel', 'Germany', 'thiel'),
	('Vitaliy Lisakovich', 'Belarus', 'lisakovich'),
	('Vitaliy Lisakovich', 'Belarus', 'vitaliy lisakovich'),
	('Vitor Carvalho', 'Brazil', 'vitor carvalho'),
	('Vitor Carvalho', 'Brazil', 'carvalho'),
	('Maurice Deville', 'Luxembourg', 'maurice deville'),
	('Maurice Deville', 'Luxembourg', 'deville'),
	('Simon Sluga', 'Croatia', 'simon sluga'),
	('Simon Sluga', 'Croatia', 'sluga'),
	('Adonis Frías', 'Argentina', 'adonis frias'),
	('Adonis Frías', 'Argentina', 'frias'),
	('Song Bum Keun', 'Korea Republic', 'song bum keun'),
	('Song Bum Keun', 'Korea Republic', 'keun'),
	('Yohann Magnin', 'France', 'yohann magnin'),
	('Yohann Magnin', 'France', 'magnin'),
	('Gonçalo Cardoso', 'Portugal', 'goncalo cardoso'),
	('Gonçalo Cardoso', 'Portugal', 'cardoso'),
	('Herman Stengel', 'Norway', 'stengel'),
	('Herman Stengel', 'Norway', 'herman stengel'),
	('Paolo Fernandes', 'Spain', 'paolo fernandes'),
	('Paolo Fernandes', 'Spain', 'fernandes'),
	('Michael Schultz', 'Germany', 'schultz'),
	('Michael Schultz', 'Germany', 'michael schultz'),
	('Frédéric Duplus', 'France', 'duplus'),
	('Frédéric Duplus', 'France', 'frederic duplus'),
	('Jairo Padilla', 'Ecuador', 'padilla'),
	('Jairo Padilla', 'Ecuador', 'jairo padilla'),
	('Sofian Chakla', 'Morocco', 'sofian chakla'),
	('Sofian Chakla', 'Morocco', 'chakla'),
	('Ryan McGowan', 'Australia', 'ryan mcgowan'),
	('Ryan McGowan', 'Australia', 'mcgowan'),
	('Yu Sang Hun', 'Korea Republic', 'yu sang hun'),
	('Yu Sang Hun', 'Korea Republic', 'hun'),
	('Saleh Al Shehri', 'Saudi Arabia', 'saleh al shehri'),
	('Saleh Al Shehri', 'Saudi Arabia', 'shehri'),
	('Mateo Cassierra', 'Colombia', 'mateo cassierra'),
	('Mateo Cassierra', 'Colombia', 'cassierra'),
	('Stallone Limbombe', 'Belgium', 'stallone limbombe'),
	('Stallone Limbombe', 'Belgium', 'limbombe'),
	('Mathias Rasmussen', 'Norway', 'rasmussen'),
	('Mathias Rasmussen', 'Norway', 'mathias rasmussen'),
	('Filipe Melo', 'Portugal', 'filipe melo'),
	('Filipe Melo', 'Portugal', 'melo'),
	('Arnaldo Giménez', 'Paraguay', 'gimenez'),
	('Arnaldo Giménez', 'Paraguay', 'arnaldo gimenez'),
	('Jovan Stojanović', 'Serbia', 'stojanovic'),
	('Jovan Stojanović', 'Serbia', 'jovan stojanovic'),
	('Jaime Seoane', 'Spain', 'seoane'),
	('Jaime Seoane', 'Spain', 'jaime seoane'),
	('Przemysław Wiśniewski', 'Poland', 'przemysaw wisniewski'),
	('Przemysław Wiśniewski', 'Poland', 'wisniewski'),
	('Jang Ho Ik', 'Korea Republic', 'jang ho ik'),
	('Jang Ho Ik', 'Korea Republic', 'ik'),
	('Moses Ogbu', 'Nigeria', 'moses ogbu'),
	('Moses Ogbu', 'Nigeria', 'ogbu'),
	('Carlos Cuero', 'Ecuador', 'carlos cuero'),
	('Carlos Cuero', 'Ecuador', 'cuero'),
	('Seo Bo Min', 'Korea Republic', 'seo bo min'),
	('Seo Bo Min', 'Korea Republic', 'min'),
	('Luca Vignali', 'Italy', 'luca vignali'),
	('Luca Vignali', 'Italy', 'vignali'),
	('Ben Sheaf', 'England', 'ben sheaf'),
	('Ben Sheaf', 'England', 'sheaf'),
	('Rasmus Jönsson', 'Sweden', 'jonsson'),
	('Rasmus Jönsson', 'Sweden', 'rasmus jonsson'),
	('Dave Romney', 'United States', 'dave romney'),
	('Dave Romney', 'United States', 'romney'),
	('César Díaz', 'Spain', 'cesar diaz'),
	('César Díaz', 'Spain', 'diaz'),
	('Matías Gómez', 'Argentina', 'matias gomez'),
	('Matías Gómez', 'Argentina', 'gomez'),
	('Siriki Dembele', 'Scotland', 'dembele'),
	('Siriki Dembele', 'Scotland', 'siriki dembele'),
	('Anthony Grant', 'England', 'grant'),
	('Anthony Grant', 'England', 'anthony grant'),
	('Ousmane Viera', 'Ivory Coast', 'ousmane viera'),
	('Ousmane Viera', 'Ivory Coast', 'viera'),
	('Stephan Auer', 'Austria', 'auer'),
	('Stephan Auer', 'Austria', 'stephan auer'),
	('Jørgen Skjelvik', 'Norway', 'skjelvik'),
	('Jørgen Skjelvik', 'Norway', 'jrgen skjelvik'),
	('Ignacio Saavedra', 'Chile', 'ignacio saavedra'),
	('Ignacio Saavedra', 'Chile', 'saavedra'),
	('Patrick Kammerbauer', 'Germany', 'kammerbauer'),
	('Patrick Kammerbauer', 'Germany', 'patrick kammerbauer'),
	('Axel Sjöberg', 'Sweden', 'sjoberg'),
	('Axel Sjöberg', 'Sweden', 'axel sjoberg'),
	('Alassane Ndiaye', 'France', 'alassane ndiaye'),
	('Alassane Ndiaye', 'France', 'ndiaye'),
	('Luis Congo', 'Ecuador', 'congo'),
	('Luis Congo', 'Ecuador', 'luis congo'),
	('Tom Aldred', 'Scotland', 'tom aldred'),
	('Tom Aldred', 'Scotland', 'aldred'),
	('Óscar Sielva', 'Spain', 'sielva'),
	('Óscar Sielva', 'Spain', 'oscar sielva'),
	('Mario Barco', 'Spain', 'barco'),
	('Mario Barco', 'Spain', 'mario barco'),
	('Keito Nakamura', 'Japan', 'keito nakamura'),
	('Keito Nakamura', 'Japan', 'nakamura'),
	('Alex Cairns', 'England', 'alex cairns'),
	('Alex Cairns', 'England', 'cairns'),
	('Kolja Pusch', 'Germany', 'kolja pusch'),
	('Kolja Pusch', 'Germany', 'pusch'),
	('Nathan', 'Brazil', 'nathan'),
	('Sebastian Hertner', 'Germany', 'hertner'),
	('Sebastian Hertner', 'Germany', 'sebastian hertner'),
	('Manfred Fischer', 'Austria', 'manfred fischer'),
	('Manfred Fischer', 'Austria', 'fischer'),
	('Montero', 'Spain', 'montero'),
	('Jefté', 'Spain', 'jefte'),
	('Georgios Giakoumakis', 'Greece', 'georgios giakoumakis'),
	('Georgios Giakoumakis', 'Greece', 'giakoumakis'),
	('Joost van Aken', 'Netherlands', 'aken'),
	('Joost van Aken', 'Netherlands', 'joost van aken'),
	('Kim Yong Hwan', 'Korea Republic', 'hwan'),
	('Kim Yong Hwan', 'Korea Republic', 'kim yong hwan'),
	('Andreas Eines Hopmark', 'Norway', 'andreas eines hopmark'),
	('Andreas Eines Hopmark', 'Norway', 'hopmark'),
	('Boris Sekulić', 'Slovakia', 'boris sekulic'),
	('Boris Sekulić', 'Slovakia', 'sekulic'),
	('Malcolm Cacutalua', 'Germany', 'cacutalua'),
	('Malcolm Cacutalua', 'Germany', 'malcolm cacutalua'),
	('Gilberto Sepúlveda', 'Mexico', 'gilberto sepulveda'),
	('Gilberto Sepúlveda', 'Mexico', 'sepulveda'),
	('Liam Polworth', 'Scotland', 'polworth'),
	('Liam Polworth', 'Scotland', 'liam polworth'),
	('Evert Linthorst', 'Netherlands', 'linthorst'),
	('Evert Linthorst', 'Netherlands', 'evert linthorst'),
	('Nathan De Medina', 'Belgium', 'nathan de medina'),
	('Nathan De Medina', 'Belgium', 'medina'),
	('Yuji Rokutan', 'Japan', 'yuji rokutan'),
	('Yuji Rokutan', 'Japan', 'rokutan'),
	('Zapater', 'Spain', 'zapater'),
	('Haithem Loucif', 'Algeria', 'loucif'),
	('Haithem Loucif', 'Algeria', 'haithem loucif'),
	('Jean-Manuel Mbom', 'Germany', 'jeanmanuel mbom'),
	('Jean-Manuel Mbom', 'Germany', 'mbom'),
	('Bogdan Mitrea', 'Romania', 'mitrea'),
	('Bogdan Mitrea', 'Romania', 'bogdan mitrea'),
	('Nildo Viera', 'Paraguay', 'nildo viera'),
	('Nildo Viera', 'Paraguay', 'viera'),
	('Joel López Pissano', 'Argentina', 'pissano'),
	('Joel López Pissano', 'Argentina', 'joel lopez pissano'),
	('Chris Bedia', 'Ivory Coast', 'chris bedia'),
	('Chris Bedia', 'Ivory Coast', 'bedia'),
	('Pará', 'Brazil', 'para'),
	('Go Moo Yol', 'Korea Republic', 'go moo yol'),
	('Go Moo Yol', 'Korea Republic', 'yol'),
	('Dominik Kotarski', 'Croatia', 'dominik kotarski'),
	('Dominik Kotarski', 'Croatia', 'kotarski'),
	('Ryan Tafazolli', 'England', 'tafazolli'),
	('Ryan Tafazolli', 'England', 'ryan tafazolli'),
	('Iven Austbø', 'Norway', 'iven austb'),
	('Iven Austbø', 'Norway', 'austb'),
	('Elliott Moore', 'England', 'elliott moore'),
	('Elliott Moore', 'England', 'moore'),
	('Callum Camps', 'Northern Ireland', 'callum camps'),
	('Callum Camps', 'Northern Ireland', 'camps'),
	('Franco Ezequiel Calderón', 'Argentina', 'franco ezequiel calderon'),
	('Franco Ezequiel Calderón', 'Argentina', 'calderon'),
	('Jürgen Gjasula', 'Albania', 'gjasula'),
	('Jürgen Gjasula', 'Albania', 'jurgen gjasula'),
	('Iban Salvador', 'Equatorial Guinea', 'iban salvador'),
	('Iban Salvador', 'Equatorial Guinea', 'salvador'),
	('Jérémy Taravel', 'France', 'jeremy taravel'),
	('Jérémy Taravel', 'France', 'taravel'),
	('Moussa Sanoh', 'Netherlands', 'moussa sanoh'),
	('Moussa Sanoh', 'Netherlands', 'sanoh'),
	('Cristian González', 'Uruguay', 'cristian gonzalez'),
	('Cristian González', 'Uruguay', 'gonzalez'),
	('Steve Lawson', 'Togo', 'steve lawson'),
	('Steve Lawson', 'Togo', 'lawson'),
	('Mateu Morey', 'Spain', 'morey'),
	('Mateu Morey', 'Spain', 'mateu morey'),
	('Paul Quasten', 'Czech Republic', 'quasten'),
	('Paul Quasten', 'Czech Republic', 'paul quasten'),
	('Nils Röseler', 'Germany', 'nils roseler'),
	('Nils Röseler', 'Germany', 'roseler'),
	('Dejan Dražić', 'Serbia', 'drazic'),
	('Dejan Dražić', 'Serbia', 'dejan drazic'),
	('Tariq Lamptey', 'England', 'tariq lamptey'),
	('Tariq Lamptey', 'England', 'lamptey'),
	('Israel Poblete', 'Chile', 'poblete'),
	('Israel Poblete', 'Chile', 'israel poblete'),
	('Dejan Petrovič', 'Slovenia', 'dejan petrovic'),
	('Dejan Petrovič', 'Slovenia', 'petrovic'),
	('Borja Sainz', 'Spain', 'sainz'),
	('Borja Sainz', 'Spain', 'borja sainz'),
	('Anthony Belmonte', 'France', 'belmonte'),
	('Anthony Belmonte', 'France', 'anthony belmonte'),
	('Arnaud Kalimuendo', 'France', 'arnaud kalimuendo'),
	('Arnaud Kalimuendo', 'France', 'kalimuendo'),
	('Tom Barlow', 'United States', 'tom barlow'),
	('Tom Barlow', 'United States', 'barlow'),
	('Jaroslav Mihalík', 'Slovakia', 'mihalik'),
	('Jaroslav Mihalík', 'Slovakia', 'jaroslav mihalik'),
	('Warren Creavalle', 'Guyana', 'warren creavalle'),
	('Warren Creavalle', 'Guyana', 'creavalle'),
	('Scott Kashket', 'England', 'scott kashket'),
	('Scott Kashket', 'England', 'kashket'),
	('Kyle Duncan', 'United States', 'kyle duncan'),
	('Kyle Duncan', 'United States', 'duncan'),
	('Zé Uilton', 'Brazil', 'ze uilton'),
	('Zé Uilton', 'Brazil', 'uilton'),
	('Tim Knipping', 'Germany', 'knipping'),
	('Tim Knipping', 'Germany', 'tim knipping'),
	('Anderson', 'Brazil', 'anderson'),
	('Petter Strand', 'Norway', 'petter strand'),
	('Petter Strand', 'Norway', 'strand'),
	('Dario Čanađija', 'Croatia', 'dario canaija'),
	('Dario Čanađija', 'Croatia', 'canaija'),
	('Marcel Rømer', 'Denmark', 'rmer'),
	('Marcel Rømer', 'Denmark', 'marcel rmer'),
	('Kim Byeong Oh', 'Korea Republic', 'oh'),
	('Kim Byeong Oh', 'Korea Republic', 'kim byeong oh'),
	('Malik Tchokounté', 'France', 'tchokounte'),
	('Malik Tchokounté', 'France', 'malik tchokounte'),
	('Ahmet Arslan', 'Germany', 'ahmet arslan'),
	('Ahmet Arslan', 'Germany', 'arslan'),
	('Hakan Çinemre', 'Turkey', 'hakan cinemre'),
	('Hakan Çinemre', 'Turkey', 'cinemre'),
	('Yang Dong Hyen', 'Korea Republic', 'yang dong hyen'),
	('Yang Dong Hyen', 'Korea Republic', 'hyen'),
	('Mathieu Baudry', 'France', 'baudry'),
	('Mathieu Baudry', 'France', 'mathieu baudry'),
	('Warleson', 'Brazil', 'warleson'),
	('Emmanuel Lomotey', 'Ghana', 'emmanuel lomotey'),
	('Emmanuel Lomotey', 'Ghana', 'lomotey'),
	('Wilmer Godoy', 'Ecuador', 'godoy'),
	('Wilmer Godoy', 'Ecuador', 'wilmer godoy'),
	('Marcus Piossek', 'Poland', 'piossek'),
	('Marcus Piossek', 'Poland', 'marcus piossek'),
	('Oliver Turton', 'England', 'oliver turton'),
	('Oliver Turton', 'England', 'turton'),
	('Micheal Azira', 'Uganda', 'micheal azira'),
	('Micheal Azira', 'Uganda', 'azira'),
	('Jon Nolan', 'England', 'jon nolan'),
	('Jon Nolan', 'England', 'nolan'),
	('Yohan Roche', 'France', 'roche'),
	('Yohan Roche', 'France', 'yohan roche'),
	('Joe Newell', 'England', 'joe newell'),
	('Joe Newell', 'England', 'newell'),
	('Magnar Ødegaard', 'Norway', 'magnar degaard'),
	('Magnar Ødegaard', 'Norway', 'degaard'),
	('Miguel Angel Sansores', 'Mexico', 'miguel angel sansores'),
	('Miguel Angel Sansores', 'Mexico', 'sansores'),
	('Jonny Smith', 'England', 'smith'),
	('Jonny Smith', 'England', 'jonny smith'),
	('Kasper Enghardt', 'Denmark', 'enghardt'),
	('Kasper Enghardt', 'Denmark', 'kasper enghardt'),
	('Devyne Rensch', 'Netherlands', 'rensch'),
	('Devyne Rensch', 'Netherlands', 'devyne rensch'),
	('Mateusz Szwoch', 'Poland', 'mateusz szwoch'),
	('Mateusz Szwoch', 'Poland', 'szwoch'),
	('Andrew Durante', 'New Zealand', 'andrew durante'),
	('Andrew Durante', 'New Zealand', 'durante'),
	('Mikkel Kaufmann', 'Denmark', 'mikkel kaufmann'),
	('Mikkel Kaufmann', 'Denmark', 'kaufmann'),
	('Óscar Whalley', 'Spain', 'whalley'),
	('Óscar Whalley', 'Spain', 'oscar whalley'),
	('Shingo Tomita', 'Japan', 'tomita'),
	('Shingo Tomita', 'Japan', 'shingo tomita'),
	('Ufuk Ceylan', 'Turkey', 'ceylan'),
	('Ufuk Ceylan', 'Turkey', 'ufuk ceylan'),
	('Antoni Sarcevic', 'England', 'antoni sarcevic'),
	('Antoni Sarcevic', 'England', 'sarcevic'),
	('Connor Ripley', 'England', 'connor ripley'),
	('Connor Ripley', 'England', 'ripley'),
	('Emeka Friday Eze', 'Nigeria', 'emeka friday eze'),
	('Emeka Friday Eze', 'Nigeria', 'eze'),
	('Joe Wildsmith', 'England', 'joe wildsmith'),
	('Joe Wildsmith', 'England', 'wildsmith'),
	('Leigh Broxham', 'Australia', 'broxham'),
	('Leigh Broxham', 'Australia', 'leigh broxham'),
	('Facundo Pons', 'Argentina', 'pons'),
	('Facundo Pons', 'Argentina', 'facundo pons'),
	('Senou Coulibaly', 'Mali', 'senou coulibaly'),
	('Senou Coulibaly', 'Mali', 'coulibaly'),
	('Terence Baya', 'France', 'terence baya'),
	('Terence Baya', 'France', 'baya'),
	('Kyle Vassell', 'Northern Ireland', 'vassell'),
	('Kyle Vassell', 'Northern Ireland', 'kyle vassell'),
	('Joe Day', 'England', 'joe day'),
	('Joe Day', 'England', 'day'),
	('Mohammed Khubrani', 'Saudi Arabia', 'khubrani'),
	('Mohammed Khubrani', 'Saudi Arabia', 'mohammed khubrani'),
	('Daniel Pedersen', 'Denmark', 'daniel pedersen'),
	('Daniel Pedersen', 'Denmark', 'pedersen'),
	('Joselito Vaca', 'Bolivia', 'vaca'),
	('Joselito Vaca', 'Bolivia', 'joselito vaca'),
	('Daniel Granli', 'Norway', 'daniel granli'),
	('Daniel Granli', 'Norway', 'granli'),
	('Roni', 'Spain', 'roni'),
	('Hernán Figueredo', 'Uruguay', 'figueredo'),
	('Hernán Figueredo', 'Uruguay', 'hernan figueredo'),
	('Luca Pfeiffer', 'Germany', 'luca pfeiffer'),
	('Luca Pfeiffer', 'Germany', 'pfeiffer'),
	('Elias Huth', 'Germany', 'huth'),
	('Elias Huth', 'Germany', 'elias huth'),
	('Dimitry Bertaud', 'France', 'dimitry bertaud'),
	('Dimitry Bertaud', 'France', 'bertaud'),
	('Lass Bangoura', 'Guinea', 'bangoura'),
	('Lass Bangoura', 'Guinea', 'lass bangoura'),
	('Nico Granatowski', 'Germany', 'granatowski'),
	('Nico Granatowski', 'Germany', 'nico granatowski'),
	('Bradley Collins', 'England', 'collins'),
	('Bradley Collins', 'England', 'bradley collins'),
	('Bryan Gil', 'Spain', 'gil'),
	('Bryan Gil', 'Spain', 'bryan gil'),
	('Carbonell', 'Spain', 'carbonell'),
	('Darren McGregor', 'Scotland', 'mcgregor'),
	('Darren McGregor', 'Scotland', 'darren mcgregor'),
	('Ched Evans', 'Wales', 'evans'),
	('Ched Evans', 'Wales', 'ched evans'),
	('Lorenco Šimić', 'Croatia', 'simic'),
	('Lorenco Šimić', 'Croatia', 'lorenco simic'),
	('Nicolás Mezquida', 'Uruguay', 'mezquida'),
	('Nicolás Mezquida', 'Uruguay', 'nicolas mezquida'),
	('Teden Mengi', 'England', 'teden mengi'),
	('Teden Mengi', 'England', 'mengi'),
	('Steven Lawless', 'Scotland', 'steven lawless'),
	('Steven Lawless', 'Scotland', 'lawless'),
	('Myles Kenlock', 'England', 'myles kenlock'),
	('Myles Kenlock', 'England', 'kenlock'),
	('Nicky Maynard', 'England', 'maynard'),
	('Nicky Maynard', 'England', 'nicky maynard'),
	('Miguel Ángel Merentiel', 'Uruguay', 'merentiel'),
	('Miguel Ángel Merentiel', 'Uruguay', 'miguel angel merentiel'),
	('Hidajet Hankić', 'Austria', 'hidajet hankic'),
	('Hidajet Hankić', 'Austria', 'hankic'),
	('Abdurrahim Dursun', 'Turkey', 'dursun'),
	('Abdurrahim Dursun', 'Turkey', 'abdurrahim dursun'),
	('Tim Rönning', 'Sweden', 'ronning'),
	('Tim Rönning', 'Sweden', 'tim ronning'),
	('Cillian Sheridan', 'Republic of Ireland', 'sheridan'),
	('Cillian Sheridan', 'Republic of Ireland', 'cillian sheridan'),
	('Nordin Gerzić', 'Sweden', 'nordin gerzic'),
	('Nordin Gerzić', 'Sweden', 'gerzic'),
	('Tawfiq Bu Haymid', 'Saudi Arabia', 'haymid'),
	('Tawfiq Bu Haymid', 'Saudi Arabia', 'tawfiq bu haymid'),
	('Sepp van den Berg', 'Netherlands', 'sepp van den berg'),
	('Sepp van den Berg', 'Netherlands', 'berg'),
	('Charles Carolus Andriamahitsinoro', 'Madagascar', 'andriamahitsinoro'),
	('Charles Carolus Andriamahitsinoro', 'Madagascar', 'charles carolus andriamahitsinoro'),
	('Jeong Hyun Cheol', 'Korea Republic', 'jeong hyun cheol'),
	('Jeong Hyun Cheol', 'Korea Republic', 'cheol'),
	('Mark McKenzie', 'United States', 'mark mckenzie'),
	('Mark McKenzie', 'United States', 'mckenzie'),
	('Jonas Deumeland', 'Germany', 'jonas deumeland'),
	('Jonas Deumeland', 'Germany', 'deumeland'),
	('Daniel Vega', 'Argentina', 'daniel vega'),
	('Daniel Vega', 'Argentina', 'vega'),
	('Varo', 'Spain', 'varo'),
	('Aliou Coly', 'Senegal', 'coly'),
	('Aliou Coly', 'Senegal', 'aliou coly'),
	('Ellis Harrison', 'Wales', 'ellis harrison'),
	('Ellis Harrison', 'Wales', 'harrison'),
	('Cohen Bramall', 'England', 'cohen bramall'),
	('Cohen Bramall', 'England', 'bramall'),
	('Mauricio Asenjo', 'Argentina', 'mauricio asenjo'),
	('Mauricio Asenjo', 'Argentina', 'asenjo'),
	('Emanuel Gularte', 'Uruguay', 'gularte'),
	('Emanuel Gularte', 'Uruguay', 'emanuel gularte'),
	('El-Hadji Ba', 'France', 'ba'),
	('El-Hadji Ba', 'France', 'elhadji ba'),
	('Diego Vallejos', 'Chile', 'vallejos'),
	('Diego Vallejos', 'Chile', 'diego vallejos'),
	('Ely', 'Cape Verde', 'ely'),
	('Luis Miguel Quezada', 'Dominican Republic', 'luis miguel quezada'),
	('Luis Miguel Quezada', 'Dominican Republic', 'quezada'),
	('John McCarthy', 'United States', 'mccarthy'),
	('John McCarthy', 'United States', 'john mccarthy'),
	('Delgado', 'Spain', 'delgado'),
	('Ertuğrul Taşkıran', 'Turkey', 'taskran'),
	('Ertuğrul Taşkıran', 'Turkey', 'ertugrul taskran'),
	('Gabriel Gudmundsson', 'Sweden', 'gudmundsson'),
	('Gabriel Gudmundsson', 'Sweden', 'gabriel gudmundsson'),
	('Bartosz Slisz', 'Poland', 'bartosz slisz'),
	('Bartosz Slisz', 'Poland', 'slisz'),
	('Enzo Loiodice', 'France', 'loiodice'),
	('Enzo Loiodice', 'France', 'enzo loiodice'),
	('Gustavo Fernández', 'Argentina', 'fernandez'),
	('Gustavo Fernández', 'Argentina', 'gustavo fernandez')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';