INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Inih Effiong', 'England', 'player'),
	('William Camargo', 'Brazil', 'player'),
	('Mateusz Bogusz', 'Poland', 'player'),
	('Jabez Makanda', 'Angola', 'player'),
	('Rahmetullah Berişbek', 'Turkey', 'player'),
	('Álex Cruz', 'Spain', 'player'),
	('Tanguy Coulibaly', 'France', 'player'),
	('Zeno Ibsen Rossi', 'England', 'player'),
	('Bright Akwo Arrey-Mbi', 'Germany', 'player'),
	('Peter Cherrie', 'Scotland', 'player'),
	('Michał Rzuchowski', 'Poland', 'player'),
	('Sondre Fosnæss Hanssen', 'Norway', 'player'),
	('Armando Broja', 'Albania', 'player'),
	('Sam Matthews', 'England', 'player'),
	('Wojciech Hajda', 'Poland', 'player'),
	('Ethan Chislett', 'South Africa', 'player'),
	('Tomáš Břečka', 'Czech Republic', 'player'),
	('Shuto Abe', 'Japan', 'player'),
	('Martín Calderón', 'Spain', 'player'),
	('Hasan Hatipoğlu', 'Turkey', 'player'),
	('Abdulwahab Jafar', 'Saudi Arabia', 'player'),
	('Mathias Eriksen Ranmark', 'Norway', 'player'),
	('Koen Bucker', 'Netherlands', 'player'),
	('Mohammed Mohsen Harzan', 'Saudi Arabia', 'player'),
	('Juan Miguel Ojeda', 'Paraguay', 'player'),
	('Bridge Ndilu', 'France', 'player'),
	('Adrian Łyszczarz', 'Poland', 'player'),
	('Rui Encarnação', 'Portugal', 'player'),
	('Valdimar Þór Ingimundarson', 'Iceland', 'player'),
	('Brandon Kavanagh', 'Republic of Ireland', 'player'),
	('Thomas Allan', 'England', 'player'),
	('Al Hassan Toure', 'Australia', 'player'),
	('Dragoljub Savić', 'Serbia', 'player'),
	('Leandro Morante', 'France', 'player'),
	('Rohat Agca', 'Netherlands', 'player'),
	('Hasan Hüseyin Acar', 'Turkey', 'player'),
	('Kelland Watts', 'England', 'player'),
	('Hugo Espínola', 'Paraguay', 'player'),
	('Kazushige Kirihata', 'Japan', 'player'),
	('Safa Kınalı', 'Turkey', 'player'),
	('Luis López', 'Mexico', 'player'),
	('David Boateng', 'England', 'player'),
	('Pepe Sánchez', 'Spain', 'player'),
	('David Costa', 'Portugal', 'player'),
	('Hong Joon Ho', 'Korea Republic', 'player'),
	('Layton Ndukwu', 'England', 'player'),
	('Maximilian Franzke', 'Germany', 'player'),
	('Antoine Valerio', 'France', 'player'),
	('Sandro Notaroberto', 'Venezuela', 'player'),
	('Mamadou Diallo', 'Senegal', 'player'),
	('Morten Rüdiger', 'Germany', 'player'),
	('Tsvetelin Chunchukov', 'Bulgaria', 'player'),
	('Aleksander Buksa', 'Poland', 'player'),
	('Juan Flere', 'Argentina', 'player'),
	('James Belshaw', 'England', 'player'),
	('Vasilis Zagaritis', 'Greece', 'player'),
	('Elia Caprile', 'Italy', 'player'),
	('Connor Hall', 'England', 'player'),
	('Che Shiwei', 'China PR', 'player'),
	('Abdullah Qaisi', 'Saudi Arabia', 'player'),
	('Emin Bayram', 'Turkey', 'player'),
	('Chris Forrester', 'Republic of Ireland', 'player'),
	('Wang Ziming', 'China PR', 'player'),
	('Moaath Afana', 'Jordan', 'player'),
	('Juan Córdova', 'Canada', 'player'),
	('Faustino Dettler', 'Argentina', 'player'),
	('Santiago Naveda', 'Mexico', 'player'),
	('Francesco Rossi', 'Italy', 'player'),
	('Alexandru Boiciuc', 'Moldova', 'player'),
	('Lucas González', 'Argentina', 'player'),
	('Jamie McGrath', 'Republic of Ireland', 'player'),
	('Jasurbek Jaloliddinov', 'Uzbekistan', 'player'),
	('Victor van den Bogert', 'Netherlands', 'player'),
	('Danny McNamara', 'Republic of Ireland', 'player'),
	('Hassan Essa Jafry', 'Saudi Arabia', 'player'),
	('Adrien Perez', 'United States', 'player'),
	('Kenny Romero', 'Venezuela', 'player'),
	('Yannick Schlößer', 'Germany', 'player'),
	('Michael Eberwein', 'Germany', 'player'),
	('Desley Ubbink', 'Netherlands', 'player'),
	('Keanin Ayer', 'South Africa', 'player'),
	('Exequiel Beltramone', 'Argentina', 'player'),
	('Ethan Erhahon', 'Scotland', 'player'),
	('Giacomo Quagliata', 'Italy', 'player'),
	('Brian Negro', 'Argentina', 'player'),
	('Giles Phillips', 'United States', 'player'),
	('Majed Kanabah', 'Saudi Arabia', 'player'),
	('Sun Shilin', 'China PR', 'player'),
	('Patryk Janasik', 'Poland', 'player'),
	('Jacob Maddox', 'England', 'player'),
	('Justin Portillo', 'United States', 'player'),
	('Gustavo Viera', 'Uruguay', 'player'),
	('Lin Liangming', 'China PR', 'player'),
	('Emil Cuello', 'Argentina', 'player'),
	('Jérémy Le Douaron', 'France', 'player'),
	('Noah Billingsley', 'New Zealand', 'player'),
	('Nicolas Hebisch', 'Germany', 'player'),
	('Kartal Yılmaz', 'Turkey', 'player'),
	('Jefferson Tabinas', 'Philippines', 'player'),
	('Efraín Orona', 'Mexico', 'player'),
	('Hussain Shaian', 'Saudi Arabia', 'player'),
	('Denis Genreau', 'Australia', 'player'),
	('Tony Njiké', 'France', 'player'),
	('Raúl Moro', 'Spain', 'player'),
	('Soner Örnek', 'Turkey', 'player'),
	('Juan Argüello', 'Paraguay', 'player'),
	('Ibrahima Cissé', 'France', 'player'),
	('Evelio Cardozo', 'Argentina', 'player'),
	('Jean Paul García', 'Colombia', 'player'),
	('Balázs Csiszér', 'Romania', 'player'),
	('Krisztofer Horváth', 'Hungary', 'player'),
	('Barredo', 'Spain', 'player'),
	('Reko Silva', 'Portugal', 'player'),
	('Mateusz Czyżycki', 'Poland', 'player'),
	('Ijiel Protti', 'Argentina', 'player'),
	('Adrian Hajdari', 'North Macedonia', 'player'),
	('Marco Schikora', 'Germany', 'player'),
	('Basim Al Baqi', 'Saudi Arabia', 'player'),
	('Jack Muldoon', 'England', 'player'),
	('Maximiliano Araújo', 'Uruguay', 'player'),
	('Rashad Muhammed', 'France', 'player'),
	('Luis Ingolotti', 'Argentina', 'player'),
	('Myles Hippolyte', 'England', 'player'),
	('Guillermo Pozos', 'Mexico', 'player'),
	('Francho Serrano', 'Spain', 'player'),
	('Braulio Uraezaña', 'Bolivia', 'player'),
	('AJ Leitch-Smith', 'England', 'player'),
	('Nemanja Celic', 'Austria', 'player'),
	('Dylan Watts', 'Republic of Ireland', 'player'),
	('Meris Skenderović', 'Montenegro', 'player'),
	('Mergim Fejzullahu', 'Switzerland', 'player'),
	('Dannie Bulman', 'England', 'player'),
	('Shunsuke Ando', 'Japan', 'player'),
	('Wan Kuzain', 'United States', 'player'),
	('Henry Cangá', 'Ecuador', 'player'),
	('Yannik Bangsow', 'Germany', 'player'),
	('Stephen Kelly', 'Scotland', 'player'),
	('Lewis Miller', 'Australia', 'player'),
	('Yuki Kusano', 'Japan', 'player'),
	('Maelo Reátegui', 'Peru', 'player'),
	('Nasser Al Omran', 'Saudi Arabia', 'player'),
	('Juan Ezequiel Da Rosa', 'Argentina', 'player'),
	('Daishawn Redan', 'Netherlands', 'player'),
	('Rodrigo Cabrera', 'Uruguay', 'player'),
	('Kim Ju Kong', 'Korea Republic', 'player'),
	('Romario Roesch', 'Germany', 'player'),
	('Jack Clisby', 'Australia', 'player'),
	('Sam Hird', 'England', 'player'),
	('Aleksandar Jukic', 'Austria', 'player'),
	('Florian Heister', 'Germany', 'player'),
	('Carlos Mena', 'Spain', 'player'),
	('Edward McGinty', 'Republic of Ireland', 'player'),
	('Abdullah Al Saleh', 'Saudi Arabia', 'player'),
	('Brayton Vázquez', 'Mexico', 'player'),
	('Aleks Ławniczak', 'Poland', 'player'),
	('Mateo Hernández', 'Argentina', 'player'),
	('Raúl Martín', 'Spain', 'player'),
	('Luis Nițu', 'Romania', 'player'),
	('Richard Nuñez', 'Uruguay', 'player'),
	('Andreas Helmersen', 'Norway', 'player'),
	('Julio Martínez', 'Spain', 'player'),
	('Jandro', 'Spain', 'player'),
	('Goro Kawanami', 'Japan', 'player'),
	('Sam Bone', 'England', 'player'),
	('Andreas Bruus', 'Denmark', 'player'),
	('Milan Robin', 'France', 'player'),
	('Unai', 'Spain', 'player'),
	('Yosuke Yuzawa', 'Japan', 'player'),
	('Steven Deana', 'Switzerland', 'player'),
	('Yaroslav Meykher', 'Ukraine', 'player'),
	('Stefan Mladenovic', 'Norway', 'player'),
	('Josh Coulson', 'England', 'player'),
	('John Mahon', 'Republic of Ireland', 'player'),
	('Sebastian Tounekti', 'Norway', 'player'),
	('Raúl Alberto Lozano', 'Argentina', 'player'),
	('José Alfredo Castillo', 'Bolivia', 'player'),
	('Ren Fujimura', 'Japan', 'player'),
	('Henri Toivomäki', 'Finland', 'player'),
	('Cephas Malele', 'Switzerland', 'player'),
	('Eduardo Duarte', 'Paraguay', 'player'),
	('Juan Torres', 'United States', 'player'),
	('Santiago Moreno', 'Colombia', 'player'),
	('George Cîmpanu', 'Romania', 'player'),
	('Alan Marinelli', 'Argentina', 'player'),
	('Lenny Borges', 'Germany', 'player'),
	('Becir Omeragic', 'Switzerland', 'player'),
	('Tatsuya Yamaguchi', 'Japan', 'player'),
	('Diego Nava', 'Mexico', 'player'),
	('Morgan Whittaker', 'England', 'player'),
	('Federico Costa', 'Argentina', 'player'),
	('Jaushua Sotirio', 'Australia', 'player'),
	('Abdelkabir Abqar', 'Morocco', 'player'),
	('Nathan Ngoumou', 'France', 'player'),
	('Lucian Buzan', 'Romania', 'player'),
	('Ryan Schofield', 'England', 'player'),
	('Ji Eon Hak', 'Korea Republic', 'player'),
	('Ravy Tsouka', 'Congo', 'player'),
	('Matías Ruiz Díaz', 'Argentina', 'player'),
	('Bastian Badu', 'France', 'player'),
	('Carlos Vázquez', 'Cuba', 'player'),
	('Keith Buckley', 'Republic of Ireland', 'player'),
	('Marcus Mølvadgaard', 'Denmark', 'player'),
	('Gavin Bazunu', 'Republic of Ireland', 'player'),
	('Fabrice Hartmann', 'Germany', 'player'),
	('Li Tixiang', 'China PR', 'player'),
	('Tim Prica', 'Sweden', 'player'),
	('Federico Pereira', 'Uruguay', 'player'),
	('Baptiste Dedola', 'France', 'player'),
	('Gerard Barri', 'Spain', 'player'),
	('Rory Gaffney', 'Republic of Ireland', 'player'),
	('Erik Pärsson', 'Sweden', 'player'),
	('Matías Córdoba', 'Argentina', 'player'),
	('Răzvan Horj', 'Romania', 'player'),
	('Marko Soldo', 'Austria', 'player'),
	('Nikola Petković', 'Serbia', 'player'),
	('Liam O''Neil', 'England', 'player'),
	('Mateusz Marzec', 'Poland', 'player'),
	('Teddy Howe', 'England', 'player'),
	('Nicolas Lüchinger', 'Switzerland', 'player'),
	('Mateusz Sopoćko', 'Poland', 'player'),
	('Ramón Juárez', 'Mexico', 'player'),
	('Martín Fernández', 'Uruguay', 'player'),
	('Sonny Laiton', 'France', 'player'),
	('Tommy Mina', 'Ecuador', 'player'),
	('Alexander B. Hansen', 'Norway', 'player'),
	('Konstantinos Tzolakis', 'Greece', 'player'),
	('Amad Diallo Traore', 'Ivory Coast', 'player'),
	('Yannik Möker', 'Germany', 'player'),
	('Wilson Mena', 'Colombia', 'player'),
	('Jorge Graví', 'Uruguay', 'player'),
	('Elliot Embleton', 'England', 'player'),
	('Antón Escobar', 'Spain', 'player'),
	('Julian Rieckmann', 'Germany', 'player'),
	('Malachi Fagan-Walcott', 'England', 'player'),
	('Nathan Wood', 'England', 'player'),
	('David Nemeth', 'Austria', 'player'),
	('Ayman Al Khulaif', 'Saudi Arabia', 'player'),
	('Felipe Hernandez', 'United States', 'player'),
	('Nicolò Casale', 'Italy', 'player'),
	('Eric Cantú', 'Mexico', 'player'),
	('Joel Sousa', 'Portugal', 'player'),
	('Nicolas Wähling', 'Germany', 'player'),
	('Tom Walker', 'England', 'player'),
	('Killian Benvindo', 'France', 'player'),
	('Oytun Özdoğan', 'Turkey', 'player'),
	('Lucas Kal', 'Brazil', 'player'),
	('Ahmed Ashraf', 'Saudi Arabia', 'player'),
	('Yoon Jong Gyu', 'Korea Republic', 'player'),
	('Michael Crowe', 'Wales', 'player'),
	('Jaiber Jiménez', 'Mexico', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Inih Effiong', 'England', 'effiong'),
	('Inih Effiong', 'England', 'inih effiong'),
	('William Camargo', 'Brazil', 'william camargo'),
	('William Camargo', 'Brazil', 'camargo'),
	('Mateusz Bogusz', 'Poland', 'bogusz'),
	('Mateusz Bogusz', 'Poland', 'mateusz bogusz'),
	('Jabez Makanda', 'Angola', 'jabez makanda'),
	('Jabez Makanda', 'Angola', 'makanda'),
	('Rahmetullah Berişbek', 'Turkey', 'berisbek'),
	('Rahmetullah Berişbek', 'Turkey', 'rahmetullah berisbek'),
	('Álex Cruz', 'Spain', 'alex cruz'),
	('Álex Cruz', 'Spain', 'cruz'),
	('Tanguy Coulibaly', 'France', 'tanguy coulibaly'),
	('Tanguy Coulibaly', 'France', 'coulibaly'),
	('Zeno Ibsen Rossi', 'England', 'zeno ibsen rossi'),
	('Zeno Ibsen Rossi', 'England', 'rossi'),
	('Bright Akwo Arrey-Mbi', 'Germany', 'arreymbi'),
	('Bright Akwo Arrey-Mbi', 'Germany', 'bright akwo arreymbi'),
	('Peter Cherrie', 'Scotland', 'cherrie'),
	('Peter Cherrie', 'Scotland', 'peter cherrie'),
	('Michał Rzuchowski', 'Poland', 'micha rzuchowski'),
	('Michał Rzuchowski', 'Poland', 'rzuchowski'),
	('Sondre Fosnæss Hanssen', 'Norway', 'sondre fosnss hanssen'),
	('Sondre Fosnæss Hanssen', 'Norway', 'hanssen'),
	('Armando Broja', 'Albania', 'armando broja'),
	('Armando Broja', 'Albania', 'broja'),
	('Sam Matthews', 'England', 'matthews'),
	('Sam Matthews', 'England', 'sam matthews'),
	('Wojciech Hajda', 'Poland', 'hajda'),
	('Wojciech Hajda', 'Poland', 'wojciech hajda'),
	('Ethan Chislett', 'South Africa', 'chislett'),
	('Ethan Chislett', 'South Africa', 'ethan chislett'),
	('Tomáš Břečka', 'Czech Republic', 'tomas brecka'),
	('Tomáš Břečka', 'Czech Republic', 'brecka'),
	('Shuto Abe', 'Japan', 'shuto abe'),
	('Shuto Abe', 'Japan', 'abe'),
	('Martín Calderón', 'Spain', 'calderon'),
	('Martín Calderón', 'Spain', 'martin calderon'),
	('Hasan Hatipoğlu', 'Turkey', 'hatipoglu'),
	('Hasan Hatipoğlu', 'Turkey', 'hasan hatipoglu'),
	('Abdulwahab Jafar', 'Saudi Arabia', 'jafar'),
	('Abdulwahab Jafar', 'Saudi Arabia', 'abdulwahab jafar'),
	('Mathias Eriksen Ranmark', 'Norway', 'ranmark'),
	('Mathias Eriksen Ranmark', 'Norway', 'mathias eriksen ranmark'),
	('Koen Bucker', 'Netherlands', 'bucker'),
	('Koen Bucker', 'Netherlands', 'koen bucker'),
	('Mohammed Mohsen Harzan', 'Saudi Arabia', 'mohammed mohsen harzan'),
	('Mohammed Mohsen Harzan', 'Saudi Arabia', 'harzan'),
	('Juan Miguel Ojeda', 'Paraguay', 'ojeda'),
	('Juan Miguel Ojeda', 'Paraguay', 'juan miguel ojeda'),
	('Bridge Ndilu', 'France', 'ndilu'),
	('Bridge Ndilu', 'France', 'bridge ndilu'),
	('Adrian Łyszczarz', 'Poland', 'yszczarz'),
	('Adrian Łyszczarz', 'Poland', 'adrian yszczarz'),
	('Rui Encarnação', 'Portugal', 'rui encarnacao'),
	('Rui Encarnação', 'Portugal', 'encarnacao'),
	('Valdimar Þór Ingimundarson', 'Iceland', 'ingimundarson'),
	('Valdimar Þór Ingimundarson', 'Iceland', 'valdimar or ingimundarson'),
	('Brandon Kavanagh', 'Republic of Ireland', 'kavanagh'),
	('Brandon Kavanagh', 'Republic of Ireland', 'brandon kavanagh'),
	('Thomas Allan', 'England', 'allan'),
	('Thomas Allan', 'England', 'thomas allan'),
	('Al Hassan Toure', 'Australia', 'al hassan toure'),
	('Al Hassan Toure', 'Australia', 'toure'),
	('Dragoljub Savić', 'Serbia', 'savic'),
	('Dragoljub Savić', 'Serbia', 'dragoljub savic'),
	('Leandro Morante', 'France', 'leandro morante'),
	('Leandro Morante', 'France', 'morante'),
	('Rohat Agca', 'Netherlands', 'agca'),
	('Rohat Agca', 'Netherlands', 'rohat agca'),
	('Hasan Hüseyin Acar', 'Turkey', 'acar'),
	('Hasan Hüseyin Acar', 'Turkey', 'hasan huseyin acar'),
	('Kelland Watts', 'England', 'watts'),
	('Kelland Watts', 'England', 'kelland watts'),
	('Hugo Espínola', 'Paraguay', 'hugo espinola'),
	('Hugo Espínola', 'Paraguay', 'espinola'),
	('Kazushige Kirihata', 'Japan', 'kirihata'),
	('Kazushige Kirihata', 'Japan', 'kazushige kirihata'),
	('Safa Kınalı', 'Turkey', 'safa knal'),
	('Safa Kınalı', 'Turkey', 'knal'),
	('Luis López', 'Mexico', 'luis lopez'),
	('Luis López', 'Mexico', 'lopez'),
	('David Boateng', 'England', 'boateng'),
	('David Boateng', 'England', 'david boateng'),
	('Pepe Sánchez', 'Spain', 'sanchez'),
	('Pepe Sánchez', 'Spain', 'pepe sanchez'),
	('David Costa', 'Portugal', 'david costa'),
	('David Costa', 'Portugal', 'costa'),
	('Hong Joon Ho', 'Korea Republic', 'ho'),
	('Hong Joon Ho', 'Korea Republic', 'hong joon ho'),
	('Layton Ndukwu', 'England', 'layton ndukwu'),
	('Layton Ndukwu', 'England', 'ndukwu'),
	('Maximilian Franzke', 'Germany', 'maximilian franzke'),
	('Maximilian Franzke', 'Germany', 'franzke'),
	('Antoine Valerio', 'France', 'valerio'),
	('Antoine Valerio', 'France', 'antoine valerio'),
	('Sandro Notaroberto', 'Venezuela', 'sandro notaroberto'),
	('Sandro Notaroberto', 'Venezuela', 'notaroberto'),
	('Mamadou Diallo', 'Senegal', 'diallo'),
	('Mamadou Diallo', 'Senegal', 'mamadou diallo'),
	('Morten Rüdiger', 'Germany', 'morten rudiger'),
	('Morten Rüdiger', 'Germany', 'rudiger'),
	('Tsvetelin Chunchukov', 'Bulgaria', 'chunchukov'),
	('Tsvetelin Chunchukov', 'Bulgaria', 'tsvetelin chunchukov'),
	('Aleksander Buksa', 'Poland', 'buksa'),
	('Aleksander Buksa', 'Poland', 'aleksander buksa'),
	('Juan Flere', 'Argentina', 'flere'),
	('Juan Flere', 'Argentina', 'juan flere'),
	('James Belshaw', 'England', 'belshaw'),
	('James Belshaw', 'England', 'james belshaw'),
	('Vasilis Zagaritis', 'Greece', 'zagaritis'),
	('Vasilis Zagaritis', 'Greece', 'vasilis zagaritis'),
	('Elia Caprile', 'Italy', 'caprile'),
	('Elia Caprile', 'Italy', 'elia caprile'),
	('Connor Hall', 'England', 'connor hall'),
	('Connor Hall', 'England', 'hall'),
	('Che Shiwei', 'China PR', 'shiwei'),
	('Che Shiwei', 'China PR', 'che shiwei'),
	('Abdullah Qaisi', 'Saudi Arabia', 'qaisi'),
	('Abdullah Qaisi', 'Saudi Arabia', 'abdullah qaisi'),
	('Emin Bayram', 'Turkey', 'emin bayram'),
	('Emin Bayram', 'Turkey', 'bayram'),
	('Chris Forrester', 'Republic of Ireland', 'chris forrester'),
	('Chris Forrester', 'Republic of Ireland', 'forrester'),
	('Wang Ziming', 'China PR', 'wang ziming'),
	('Wang Ziming', 'China PR', 'ziming'),
	('Moaath Afana', 'Jordan', 'afana'),
	('Moaath Afana', 'Jordan', 'moaath afana'),
	('Juan Córdova', 'Canada', 'cordova'),
	('Juan Córdova', 'Canada', 'juan cordova'),
	('Faustino Dettler', 'Argentina', 'dettler'),
	('Faustino Dettler', 'Argentina', 'faustino dettler'),
	('Santiago Naveda', 'Mexico', 'santiago naveda'),
	('Santiago Naveda', 'Mexico', 'naveda'),
	('Francesco Rossi', 'Italy', 'francesco rossi'),
	('Francesco Rossi', 'Italy', 'rossi'),
	('Alexandru Boiciuc', 'Moldova', 'boiciuc'),
	('Alexandru Boiciuc', 'Moldova', 'alexandru boiciuc'),
	('Lucas González', 'Argentina', 'lucas gonzalez'),
	('Lucas González', 'Argentina', 'gonzalez'),
	('Jamie McGrath', 'Republic of Ireland', 'jamie mcgrath'),
	('Jamie McGrath', 'Republic of Ireland', 'mcgrath'),
	('Jasurbek Jaloliddinov', 'Uzbekistan', 'jaloliddinov'),
	('Jasurbek Jaloliddinov', 'Uzbekistan', 'jasurbek jaloliddinov'),
	('Victor van den Bogert', 'Netherlands', 'bogert'),
	('Victor van den Bogert', 'Netherlands', 'victor van den bogert'),
	('Danny McNamara', 'Republic of Ireland', 'mcnamara'),
	('Danny McNamara', 'Republic of Ireland', 'danny mcnamara'),
	('Hassan Essa Jafry', 'Saudi Arabia', 'jafry'),
	('Hassan Essa Jafry', 'Saudi Arabia', 'hassan essa jafry'),
	('Adrien Perez', 'United States', 'adrien perez'),
	('Adrien Perez', 'United States', 'perez'),
	('Kenny Romero', 'Venezuela', 'romero'),
	('Kenny Romero', 'Venezuela', 'kenny romero'),
	('Yannick Schlößer', 'Germany', 'schloer'),
	('Yannick Schlößer', 'Germany', 'yannick schloer'),
	('Michael Eberwein', 'Germany', 'eberwein'),
	('Michael Eberwein', 'Germany', 'michael eberwein'),
	('Desley Ubbink', 'Netherlands', 'desley ubbink'),
	('Desley Ubbink', 'Netherlands', 'ubbink'),
	('Keanin Ayer', 'South Africa', 'keanin ayer'),
	('Keanin Ayer', 'South Africa', 'ayer'),
	('Exequiel Beltramone', 'Argentina', 'beltramone'),
	('Exequiel Beltramone', 'Argentina', 'exequiel beltramone'),
	('Ethan Erhahon', 'Scotland', 'erhahon'),
	('Ethan Erhahon', 'Scotland', 'ethan erhahon'),
	('Giacomo Quagliata', 'Italy', 'quagliata'),
	('Giacomo Quagliata', 'Italy', 'giacomo quagliata'),
	('Brian Negro', 'Argentina', 'brian negro'),
	('Brian Negro', 'Argentina', 'negro'),
	('Giles Phillips', 'United States', 'phillips'),
	('Giles Phillips', 'United States', 'giles phillips'),
	('Majed Kanabah', 'Saudi Arabia', 'majed kanabah'),
	('Majed Kanabah', 'Saudi Arabia', 'kanabah'),
	('Sun Shilin', 'China PR', 'shilin'),
	('Sun Shilin', 'China PR', 'sun shilin'),
	('Patryk Janasik', 'Poland', 'patryk janasik'),
	('Patryk Janasik', 'Poland', 'janasik'),
	('Jacob Maddox', 'England', 'jacob maddox'),
	('Jacob Maddox', 'England', 'maddox'),
	('Justin Portillo', 'United States', 'justin portillo'),
	('Justin Portillo', 'United States', 'portillo'),
	('Gustavo Viera', 'Uruguay', 'viera'),
	('Gustavo Viera', 'Uruguay', 'gustavo viera'),
	('Lin Liangming', 'China PR', 'liangming'),
	('Lin Liangming', 'China PR', 'lin liangming'),
	('Emil Cuello', 'Argentina', 'emil cuello'),
	('Emil Cuello', 'Argentina', 'cuello'),
	('Jérémy Le Douaron', 'France', 'jeremy le douaron'),
	('Jérémy Le Douaron', 'France', 'douaron'),
	('Noah Billingsley', 'New Zealand', 'billingsley'),
	('Noah Billingsley', 'New Zealand', 'noah billingsley'),
	('Nicolas Hebisch', 'Germany', 'nicolas hebisch'),
	('Nicolas Hebisch', 'Germany', 'hebisch'),
	('Kartal Yılmaz', 'Turkey', 'kartal ylmaz'),
	('Kartal Yılmaz', 'Turkey', 'ylmaz'),
	('Jefferson Tabinas', 'Philippines', 'jefferson tabinas'),
	('Jefferson Tabinas', 'Philippines', 'tabinas'),
	('Efraín Orona', 'Mexico', 'orona'),
	('Efraín Orona', 'Mexico', 'efrain orona'),
	('Hussain Shaian', 'Saudi Arabia', 'hussain shaian'),
	('Hussain Shaian', 'Saudi Arabia', 'shaian'),
	('Denis Genreau', 'Australia', 'genreau'),
	('Denis Genreau', 'Australia', 'denis genreau'),
	('Tony Njiké', 'France', 'tony njike'),
	('Tony Njiké', 'France', 'njike'),
	('Raúl Moro', 'Spain', 'raul moro'),
	('Raúl Moro', 'Spain', 'moro'),
	('Soner Örnek', 'Turkey', 'soner ornek'),
	('Soner Örnek', 'Turkey', 'ornek'),
	('Juan Argüello', 'Paraguay', 'juan arguello'),
	('Juan Argüello', 'Paraguay', 'arguello'),
	('Ibrahima Cissé', 'France', 'ibrahima cisse'),
	('Ibrahima Cissé', 'France', 'cisse'),
	('Evelio Cardozo', 'Argentina', 'evelio cardozo'),
	('Evelio Cardozo', 'Argentina', 'cardozo'),
	('Jean Paul García', 'Colombia', 'jean paul garcia'),
	('Jean Paul García', 'Colombia', 'garcia'),
	('Balázs Csiszér', 'Romania', 'balazs csiszer'),
	('Balázs Csiszér', 'Romania', 'csiszer'),
	('Krisztofer Horváth', 'Hungary', 'krisztofer horvath'),
	('Krisztofer Horváth', 'Hungary', 'horvath'),
	('Barredo', 'Spain', 'barredo'),
	('Reko Silva', 'Portugal', 'reko silva'),
	('Reko Silva', 'Portugal', 'silva'),
	('Mateusz Czyżycki', 'Poland', 'czyzycki'),
	('Mateusz Czyżycki', 'Poland', 'mateusz czyzycki'),
	('Ijiel Protti', 'Argentina', 'ijiel protti'),
	('Ijiel Protti', 'Argentina', 'protti'),
	('Adrian Hajdari', 'North Macedonia', 'adrian hajdari'),
	('Adrian Hajdari', 'North Macedonia', 'hajdari'),
	('Marco Schikora', 'Germany', 'marco schikora'),
	('Marco Schikora', 'Germany', 'schikora'),
	('Basim Al Baqi', 'Saudi Arabia', 'baqi'),
	('Basim Al Baqi', 'Saudi Arabia', 'basim al baqi'),
	('Jack Muldoon', 'England', 'jack muldoon'),
	('Jack Muldoon', 'England', 'muldoon'),
	('Maximiliano Araújo', 'Uruguay', 'maximiliano araujo'),
	('Maximiliano Araújo', 'Uruguay', 'araujo'),
	('Rashad Muhammed', 'France', 'muhammed'),
	('Rashad Muhammed', 'France', 'rashad muhammed'),
	('Luis Ingolotti', 'Argentina', 'luis ingolotti'),
	('Luis Ingolotti', 'Argentina', 'ingolotti'),
	('Myles Hippolyte', 'England', 'hippolyte'),
	('Myles Hippolyte', 'England', 'myles hippolyte'),
	('Guillermo Pozos', 'Mexico', 'pozos'),
	('Guillermo Pozos', 'Mexico', 'guillermo pozos'),
	('Francho Serrano', 'Spain', 'serrano'),
	('Francho Serrano', 'Spain', 'francho serrano'),
	('Braulio Uraezaña', 'Bolivia', 'braulio uraezana'),
	('Braulio Uraezaña', 'Bolivia', 'uraezana'),
	('AJ Leitch-Smith', 'England', 'leitchsmith'),
	('AJ Leitch-Smith', 'England', 'aj leitchsmith'),
	('Nemanja Celic', 'Austria', 'nemanja celic'),
	('Nemanja Celic', 'Austria', 'celic'),
	('Dylan Watts', 'Republic of Ireland', 'watts'),
	('Dylan Watts', 'Republic of Ireland', 'dylan watts'),
	('Meris Skenderović', 'Montenegro', 'skenderovic'),
	('Meris Skenderović', 'Montenegro', 'meris skenderovic'),
	('Mergim Fejzullahu', 'Switzerland', 'mergim fejzullahu'),
	('Mergim Fejzullahu', 'Switzerland', 'fejzullahu'),
	('Dannie Bulman', 'England', 'bulman'),
	('Dannie Bulman', 'England', 'dannie bulman'),
	('Shunsuke Ando', 'Japan', 'shunsuke ando'),
	('Shunsuke Ando', 'Japan', 'ando'),
	('Wan Kuzain', 'United States', 'kuzain'),
	('Wan Kuzain', 'United States', 'wan kuzain'),
	('Henry Cangá', 'Ecuador', 'canga'),
	('Henry Cangá', 'Ecuador', 'henry canga'),
	('Yannik Bangsow', 'Germany', 'bangsow'),
	('Yannik Bangsow', 'Germany', 'yannik bangsow'),
	('Stephen Kelly', 'Scotland', 'stephen kelly'),
	('Stephen Kelly', 'Scotland', 'kelly'),
	('Lewis Miller', 'Australia', 'lewis miller'),
	('Lewis Miller', 'Australia', 'miller'),
	('Yuki Kusano', 'Japan', 'kusano'),
	('Yuki Kusano', 'Japan', 'yuki kusano'),
	('Maelo Reátegui', 'Peru', 'maelo reategui'),
	('Maelo Reátegui', 'Peru', 'reategui'),
	('Nasser Al Omran', 'Saudi Arabia', 'nasser al omran'),
	('Nasser Al Omran', 'Saudi Arabia', 'omran'),
	('Juan Ezequiel Da Rosa', 'Argentina', 'juan ezequiel da rosa'),
	('Juan Ezequiel Da Rosa', 'Argentina', 'rosa'),
	('Daishawn Redan', 'Netherlands', 'daishawn redan'),
	('Daishawn Redan', 'Netherlands', 'redan'),
	('Rodrigo Cabrera', 'Uruguay', 'cabrera'),
	('Rodrigo Cabrera', 'Uruguay', 'rodrigo cabrera'),
	('Kim Ju Kong', 'Korea Republic', 'kim ju kong'),
	('Kim Ju Kong', 'Korea Republic', 'kong'),
	('Romario Roesch', 'Germany', 'roesch'),
	('Romario Roesch', 'Germany', 'romario roesch'),
	('Jack Clisby', 'Australia', 'clisby'),
	('Jack Clisby', 'Australia', 'jack clisby'),
	('Sam Hird', 'England', 'hird'),
	('Sam Hird', 'England', 'sam hird'),
	('Aleksandar Jukic', 'Austria', 'jukic'),
	('Aleksandar Jukic', 'Austria', 'aleksandar jukic'),
	('Florian Heister', 'Germany', 'heister'),
	('Florian Heister', 'Germany', 'florian heister'),
	('Carlos Mena', 'Spain', 'mena'),
	('Carlos Mena', 'Spain', 'carlos mena'),
	('Edward McGinty', 'Republic of Ireland', 'edward mcginty'),
	('Edward McGinty', 'Republic of Ireland', 'mcginty'),
	('Abdullah Al Saleh', 'Saudi Arabia', 'saleh'),
	('Abdullah Al Saleh', 'Saudi Arabia', 'abdullah al saleh'),
	('Brayton Vázquez', 'Mexico', 'vazquez'),
	('Brayton Vázquez', 'Mexico', 'brayton vazquez'),
	('Aleks Ławniczak', 'Poland', 'awniczak'),
	('Aleks Ławniczak', 'Poland', 'aleks awniczak'),
	('Mateo Hernández', 'Argentina', 'mateo hernandez'),
	('Mateo Hernández', 'Argentina', 'hernandez'),
	('Raúl Martín', 'Spain', 'raul martin'),
	('Raúl Martín', 'Spain', 'martin'),
	('Luis Nițu', 'Romania', 'luis nitu'),
	('Luis Nițu', 'Romania', 'nitu'),
	('Richard Nuñez', 'Uruguay', 'richard nunez'),
	('Richard Nuñez', 'Uruguay', 'nunez'),
	('Andreas Helmersen', 'Norway', 'helmersen'),
	('Andreas Helmersen', 'Norway', 'andreas helmersen'),
	('Julio Martínez', 'Spain', 'martinez'),
	('Julio Martínez', 'Spain', 'julio martinez'),
	('Jandro', 'Spain', 'jandro'),
	('Goro Kawanami', 'Japan', 'goro kawanami'),
	('Goro Kawanami', 'Japan', 'kawanami'),
	('Sam Bone', 'England', 'sam bone'),
	('Sam Bone', 'England', 'bone'),
	('Andreas Bruus', 'Denmark', 'bruus'),
	('Andreas Bruus', 'Denmark', 'andreas bruus'),
	('Milan Robin', 'France', 'robin'),
	('Milan Robin', 'France', 'milan robin'),
	('Unai', 'Spain', 'unai'),
	('Yosuke Yuzawa', 'Japan', 'yosuke yuzawa'),
	('Yosuke Yuzawa', 'Japan', 'yuzawa'),
	('Steven Deana', 'Switzerland', 'deana'),
	('Steven Deana', 'Switzerland', 'steven deana'),
	('Yaroslav Meykher', 'Ukraine', 'meykher'),
	('Yaroslav Meykher', 'Ukraine', 'yaroslav meykher'),
	('Stefan Mladenovic', 'Norway', 'mladenovic'),
	('Stefan Mladenovic', 'Norway', 'stefan mladenovic'),
	('Josh Coulson', 'England', 'coulson'),
	('Josh Coulson', 'England', 'josh coulson'),
	('John Mahon', 'Republic of Ireland', 'john mahon'),
	('John Mahon', 'Republic of Ireland', 'mahon'),
	('Sebastian Tounekti', 'Norway', 'sebastian tounekti'),
	('Sebastian Tounekti', 'Norway', 'tounekti'),
	('Raúl Alberto Lozano', 'Argentina', 'raul alberto lozano'),
	('Raúl Alberto Lozano', 'Argentina', 'lozano'),
	('José Alfredo Castillo', 'Bolivia', 'jose alfredo castillo'),
	('José Alfredo Castillo', 'Bolivia', 'castillo'),
	('Ren Fujimura', 'Japan', 'fujimura'),
	('Ren Fujimura', 'Japan', 'ren fujimura'),
	('Henri Toivomäki', 'Finland', 'toivomaki'),
	('Henri Toivomäki', 'Finland', 'henri toivomaki'),
	('Cephas Malele', 'Switzerland', 'malele'),
	('Cephas Malele', 'Switzerland', 'cephas malele'),
	('Eduardo Duarte', 'Paraguay', 'eduardo duarte'),
	('Eduardo Duarte', 'Paraguay', 'duarte'),
	('Juan Torres', 'United States', 'torres'),
	('Juan Torres', 'United States', 'juan torres'),
	('Santiago Moreno', 'Colombia', 'moreno'),
	('Santiago Moreno', 'Colombia', 'santiago moreno'),
	('George Cîmpanu', 'Romania', 'george cimpanu'),
	('George Cîmpanu', 'Romania', 'cimpanu'),
	('Alan Marinelli', 'Argentina', 'marinelli'),
	('Alan Marinelli', 'Argentina', 'alan marinelli'),
	('Lenny Borges', 'Germany', 'borges'),
	('Lenny Borges', 'Germany', 'lenny borges'),
	('Becir Omeragic', 'Switzerland', 'becir omeragic'),
	('Becir Omeragic', 'Switzerland', 'omeragic'),
	('Tatsuya Yamaguchi', 'Japan', 'yamaguchi'),
	('Tatsuya Yamaguchi', 'Japan', 'tatsuya yamaguchi'),
	('Diego Nava', 'Mexico', 'diego nava'),
	('Diego Nava', 'Mexico', 'nava'),
	('Morgan Whittaker', 'England', 'morgan whittaker'),
	('Morgan Whittaker', 'England', 'whittaker'),
	('Federico Costa', 'Argentina', 'federico costa'),
	('Federico Costa', 'Argentina', 'costa'),
	('Jaushua Sotirio', 'Australia', 'sotirio'),
	('Jaushua Sotirio', 'Australia', 'jaushua sotirio'),
	('Abdelkabir Abqar', 'Morocco', 'abqar'),
	('Abdelkabir Abqar', 'Morocco', 'abdelkabir abqar'),
	('Nathan Ngoumou', 'France', 'nathan ngoumou'),
	('Nathan Ngoumou', 'France', 'ngoumou'),
	('Lucian Buzan', 'Romania', 'lucian buzan'),
	('Lucian Buzan', 'Romania', 'buzan'),
	('Ryan Schofield', 'England', 'schofield'),
	('Ryan Schofield', 'England', 'ryan schofield'),
	('Ji Eon Hak', 'Korea Republic', 'ji eon hak'),
	('Ji Eon Hak', 'Korea Republic', 'hak'),
	('Ravy Tsouka', 'Congo', 'tsouka'),
	('Ravy Tsouka', 'Congo', 'ravy tsouka'),
	('Matías Ruiz Díaz', 'Argentina', 'matias ruiz diaz'),
	('Matías Ruiz Díaz', 'Argentina', 'diaz'),
	('Bastian Badu', 'France', 'badu'),
	('Bastian Badu', 'France', 'bastian badu'),
	('Carlos Vázquez', 'Cuba', 'carlos vazquez'),
	('Carlos Vázquez', 'Cuba', 'vazquez'),
	('Keith Buckley', 'Republic of Ireland', 'buckley'),
	('Keith Buckley', 'Republic of Ireland', 'keith buckley'),
	('Marcus Mølvadgaard', 'Denmark', 'marcus mlvadgaard'),
	('Marcus Mølvadgaard', 'Denmark', 'mlvadgaard'),
	('Gavin Bazunu', 'Republic of Ireland', 'bazunu'),
	('Gavin Bazunu', 'Republic of Ireland', 'gavin bazunu'),
	('Fabrice Hartmann', 'Germany', 'hartmann'),
	('Fabrice Hartmann', 'Germany', 'fabrice hartmann'),
	('Li Tixiang', 'China PR', 'tixiang'),
	('Li Tixiang', 'China PR', 'li tixiang'),
	('Tim Prica', 'Sweden', 'prica'),
	('Tim Prica', 'Sweden', 'tim prica'),
	('Federico Pereira', 'Uruguay', 'federico pereira'),
	('Federico Pereira', 'Uruguay', 'pereira'),
	('Baptiste Dedola', 'France', 'baptiste dedola'),
	('Baptiste Dedola', 'France', 'dedola'),
	('Gerard Barri', 'Spain', 'barri'),
	('Gerard Barri', 'Spain', 'gerard barri'),
	('Rory Gaffney', 'Republic of Ireland', 'gaffney'),
	('Rory Gaffney', 'Republic of Ireland', 'rory gaffney'),
	('Erik Pärsson', 'Sweden', 'parsson'),
	('Erik Pärsson', 'Sweden', 'erik parsson'),
	('Matías Córdoba', 'Argentina', 'matias cordoba'),
	('Matías Córdoba', 'Argentina', 'cordoba'),
	('Răzvan Horj', 'Romania', 'razvan horj'),
	('Răzvan Horj', 'Romania', 'horj'),
	('Marko Soldo', 'Austria', 'marko soldo'),
	('Marko Soldo', 'Austria', 'soldo'),
	('Nikola Petković', 'Serbia', 'petkovic'),
	('Nikola Petković', 'Serbia', 'nikola petkovic'),
	('Liam O''Neil', 'England', 'liam oneil'),
	('Liam O''Neil', 'England', 'oneil'),
	('Mateusz Marzec', 'Poland', 'marzec'),
	('Mateusz Marzec', 'Poland', 'mateusz marzec'),
	('Teddy Howe', 'England', 'teddy howe'),
	('Teddy Howe', 'England', 'howe'),
	('Nicolas Lüchinger', 'Switzerland', 'luchinger'),
	('Nicolas Lüchinger', 'Switzerland', 'nicolas luchinger'),
	('Mateusz Sopoćko', 'Poland', 'mateusz sopocko'),
	('Mateusz Sopoćko', 'Poland', 'sopocko'),
	('Ramón Juárez', 'Mexico', 'ramon juarez'),
	('Ramón Juárez', 'Mexico', 'juarez'),
	('Martín Fernández', 'Uruguay', 'fernandez'),
	('Martín Fernández', 'Uruguay', 'martin fernandez'),
	('Sonny Laiton', 'France', 'laiton'),
	('Sonny Laiton', 'France', 'sonny laiton'),
	('Tommy Mina', 'Ecuador', 'mina'),
	('Tommy Mina', 'Ecuador', 'tommy mina'),
	('Alexander B. Hansen', 'Norway', 'hansen'),
	('Alexander B. Hansen', 'Norway', 'alexander b hansen'),
	('Konstantinos Tzolakis', 'Greece', 'tzolakis'),
	('Konstantinos Tzolakis', 'Greece', 'konstantinos tzolakis'),
	('Amad Diallo Traore', 'Ivory Coast', 'amad diallo traore'),
	('Amad Diallo Traore', 'Ivory Coast', 'traore'),
	('Yannik Möker', 'Germany', 'yannik moker'),
	('Yannik Möker', 'Germany', 'moker'),
	('Wilson Mena', 'Colombia', 'mena'),
	('Wilson Mena', 'Colombia', 'wilson mena'),
	('Jorge Graví', 'Uruguay', 'gravi'),
	('Jorge Graví', 'Uruguay', 'jorge gravi'),
	('Elliot Embleton', 'England', 'elliot embleton'),
	('Elliot Embleton', 'England', 'embleton'),
	('Antón Escobar', 'Spain', 'anton escobar'),
	('Antón Escobar', 'Spain', 'escobar'),
	('Julian Rieckmann', 'Germany', 'julian rieckmann'),
	('Julian Rieckmann', 'Germany', 'rieckmann'),
	('Malachi Fagan-Walcott', 'England', 'faganwalcott'),
	('Malachi Fagan-Walcott', 'England', 'malachi faganwalcott'),
	('Nathan Wood', 'England', 'nathan wood'),
	('Nathan Wood', 'England', 'wood'),
	('David Nemeth', 'Austria', 'david nemeth'),
	('David Nemeth', 'Austria', 'nemeth'),
	('Ayman Al Khulaif', 'Saudi Arabia', 'khulaif'),
	('Ayman Al Khulaif', 'Saudi Arabia', 'ayman al khulaif'),
	('Felipe Hernandez', 'United States', 'felipe hernandez'),
	('Felipe Hernandez', 'United States', 'hernandez'),
	('Nicolò Casale', 'Italy', 'casale'),
	('Nicolò Casale', 'Italy', 'nicolo casale'),
	('Eric Cantú', 'Mexico', 'cantu'),
	('Eric Cantú', 'Mexico', 'eric cantu'),
	('Joel Sousa', 'Portugal', 'joel sousa'),
	('Joel Sousa', 'Portugal', 'sousa'),
	('Nicolas Wähling', 'Germany', 'wahling'),
	('Nicolas Wähling', 'Germany', 'nicolas wahling'),
	('Tom Walker', 'England', 'tom walker'),
	('Tom Walker', 'England', 'walker'),
	('Killian Benvindo', 'France', 'killian benvindo'),
	('Killian Benvindo', 'France', 'benvindo'),
	('Oytun Özdoğan', 'Turkey', 'ozdogan'),
	('Oytun Özdoğan', 'Turkey', 'oytun ozdogan'),
	('Lucas Kal', 'Brazil', 'kal'),
	('Lucas Kal', 'Brazil', 'lucas kal'),
	('Ahmed Ashraf', 'Saudi Arabia', 'ashraf'),
	('Ahmed Ashraf', 'Saudi Arabia', 'ahmed ashraf'),
	('Yoon Jong Gyu', 'Korea Republic', 'yoon jong gyu'),
	('Yoon Jong Gyu', 'Korea Republic', 'gyu'),
	('Michael Crowe', 'Wales', 'crowe'),
	('Michael Crowe', 'Wales', 'michael crowe'),
	('Jaiber Jiménez', 'Mexico', 'jaiber jimenez'),
	('Jaiber Jiménez', 'Mexico', 'jimenez')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';