INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Sanousi Hawsawi', 'Saudi Arabia', 'player'),
	('Linus Borgström', 'Sweden', 'player'),
	('Phelipe', 'Brazil', 'player'),
	('Ștefan Bodișteanu', 'Romania', 'player'),
	('Dragoș Tescan', 'Romania', 'player'),
	('Peter Morrison', 'Scotland', 'player'),
	('Anthony Breslin', 'Republic of Ireland', 'player'),
	('Deshane Dalling', 'England', 'player'),
	('Darragh Noone', 'Republic of Ireland', 'player'),
	('Filip Szymczak', 'Poland', 'player'),
	('Bonsu Osei', 'Ghana', 'player'),
	('James Rowland', 'England', 'player'),
	('Murathan Sütçü', 'Turkey', 'player'),
	('André Österholm', 'Sweden', 'player'),
	('Sergio Sulbarán', 'Venezuela', 'player'),
	('İlker Karakaş', 'Turkey', 'player'),
	('George Lloyd', 'England', 'player'),
	('Robin Jalving', 'Netherlands', 'player'),
	('Johl Powell', 'England', 'player'),
	('Ole Didrik Blomberg', 'Norway', 'player'),
	('Sava-Arangel Cestic', 'Germany', 'player'),
	('Remy Howarth', 'England', 'player'),
	('Noor Al Rashidi', 'Saudi Arabia', 'player'),
	('George Campbell', 'United States', 'player'),
	('Franco Quinteros', 'Argentina', 'player'),
	('Mickaël Biron', 'France', 'player'),
	('Ágúst Hlynsson', 'Iceland', 'player'),
	('Ronan Jay', 'France', 'player'),
	('Lloyd Kerry', 'England', 'player'),
	('Ryan Scully', 'Scotland', 'player'),
	('Andrés Barboza', 'Uruguay', 'player'),
	('Wang Yaopeng', 'China PR', 'player'),
	('Tom Dele-Bashiru', 'Nigeria', 'player'),
	('Zaid Al-Hussaini', 'England', 'player'),
	('Rafiki Saïd', 'Comoros', 'player'),
	('Kelyan Guessoum', 'France', 'player'),
	('Tunde Owolabi', 'Nigeria', 'player'),
	('Rasmus Rosenqvist', 'Sweden', 'player'),
	('Juan Esteban Moreno', 'Colombia', 'player'),
	('Patrick Trindade', 'France', 'player'),
	('Ricardo Gutiérrez', 'Mexico', 'player'),
	('Kwadwo Baah', 'England', 'player'),
	('Mikael Ugland', 'Norway', 'player'),
	('James Doona', 'Republic of Ireland', 'player'),
	('Apostolos Stamatelopoulos', 'Australia', 'player'),
	('Isak Dahlqvist', 'Sweden', 'player'),
	('Tobe Leysen', 'Belgium', 'player'),
	('Mohammed Al Haeti', 'Saudi Arabia', 'player'),
	('Luis Acevedo', 'Uruguay', 'player'),
	('Luqman Hakim', 'Malaysia', 'player'),
	('Henrik Bellman', 'Sweden', 'player'),
	('Justin Löwe', 'Germany', 'player'),
	('Joël Monteiro', 'Portugal', 'player'),
	('Israel Reyes', 'Mexico', 'player'),
	('Emmanuel Léonce Kouadio', 'Germany', 'player'),
	('Jhonnyer Rojas', 'Ecuador', 'player'),
	('Isaiah Jones', 'England', 'player'),
	('Alexander Nilsson', 'Sweden', 'player'),
	('Raffaele Cretaro', 'Republic of Ireland', 'player'),
	('Søren Tengstedt', 'Denmark', 'player'),
	('Luca Philipp', 'Germany', 'player'),
	('Dominik Frelek', 'Poland', 'player'),
	('Nathan Patterson', 'Scotland', 'player'),
	('Jonas Brauti', 'Norway', 'player'),
	('Nmadi-Morris Igbokwe', 'Germany', 'player'),
	('Nikodem Fiedosewicz', 'Poland', 'player'),
	('Ömer Uzun', 'Turkey', 'player'),
	('Koki Tachi', 'Japan', 'player'),
	('Alistair Johnston', 'Canada', 'player'),
	('Shpetim Xhaka', 'Albania', 'player'),
	('Ethan Bristow', 'England', 'player'),
	('Alex Cooper', 'Scotland', 'player'),
	('Zhang Yi', 'China PR', 'player'),
	('Yvan Alounga', 'Switzerland', 'player'),
	('Jonas Brendieck', 'Germany', 'player'),
	('Shane McEleney', 'Republic of Ireland', 'player'),
	('Szymon Mroczko', 'Poland', 'player'),
	('Mark McGuinness', 'Republic of Ireland', 'player'),
	('Luke McNally', 'Republic of Ireland', 'player'),
	('Yosimar Rodríguez', 'Ecuador', 'player'),
	('Kalpi Ouattara', 'Ivory Coast', 'player'),
	('Thomas Vannoye', 'France', 'player'),
	('Tomas Brindley', 'Scotland', 'player'),
	('Shuto Watanabe', 'Japan', 'player'),
	('Yeboah Amankwah', 'Ghana', 'player'),
	('Haruya Fujii', 'Japan', 'player'),
	('Vetle Fiskerstrand', 'Norway', 'player'),
	('Hussain Al Hajouj', 'Saudi Arabia', 'player'),
	('Zheng Zhiyun', 'China PR', 'player'),
	('Ramzi Solan', 'Saudi Arabia', 'player'),
	('Adrian Edqvist', 'Sweden', 'player'),
	('Mauro Rojas', 'Paraguay', 'player'),
	('Scott Wilson', 'England', 'player'),
	('Lluis Andreu', 'Spain', 'player'),
	('Jordan Hallam', 'England', 'player'),
	('Ionuț Pop', 'Romania', 'player'),
	('Lenn Jastremski', 'Germany', 'player'),
	('Kilian Bauernfeind', 'Austria', 'player'),
	('Anthony Descotte', 'Belgium', 'player'),
	('Peter Buch Christiansen', 'Denmark', 'player'),
	('Julian Albrecht', 'Germany', 'player'),
	('Oliver Klitten', 'Denmark', 'player'),
	('Salis Abdul Samed', 'Ghana', 'player'),
	('Mikkel Hyllegaard', 'Denmark', 'player'),
	('Daiki Hotta', 'Japan', 'player'),
	('Juan Etchebarne', 'Uruguay', 'player'),
	('Cho Gue Sung', 'Korea Republic', 'player'),
	('Wataru Tanaka', 'Japan', 'player'),
	('Tomás Ahumada', 'Chile', 'player'),
	('Magnus Warming', 'Denmark', 'player'),
	('Walter Scott', 'Australia', 'player'),
	('George Gibson', 'Norway', 'player'),
	('Dejan Tetek', 'Serbia', 'player'),
	('Radhi Al Otaibi', 'Saudi Arabia', 'player'),
	('Niall Morahan', 'Republic of Ireland', 'player'),
	('Egy Maulana Vikri', 'Indonesia', 'player'),
	('Mohammed Awaji', 'Saudi Arabia', 'player'),
	('Alexander Bolaños', 'Ecuador', 'player'),
	('Joseph Espinoza', 'Ecuador', 'player'),
	('Gürkan Başkan', 'Turkey', 'player'),
	('Ed Williams', 'England', 'player'),
	('Aidan Friel', 'Republic of Ireland', 'player'),
	('Alan Bennett', 'Republic of Ireland', 'player'),
	('Piotr Samiec-Talar', 'Poland', 'player'),
	('Adonis Preciado', 'Ecuador', 'player'),
	('Dario De Vita', 'Germany', 'player'),
	('Juan Sforza', 'Argentina', 'player'),
	('Juan Daniel Cifuentes', 'Colombia', 'player'),
	('Xavier Pineda', 'Ecuador', 'player'),
	('Jordan Eastham', 'England', 'player'),
	('Robert Voloder', 'Germany', 'player'),
	('Harry Phillips', 'England', 'player'),
	('Qiao Wei', 'China PR', 'player'),
	('Kevin Lokko', 'England', 'player'),
	('Wang Xianjun', 'China PR', 'player'),
	('Akinwale Odimayo', 'England', 'player'),
	('Rockson Renteria', 'Ecuador', 'player'),
	('Benjamin Gommert', 'Germany', 'player'),
	('Bao Yaxiong', 'China PR', 'player'),
	('Mert-Yusuf Torlak', 'Turkey', 'player'),
	('Hugo Constant', 'France', 'player'),
	('Lim Seung Gyeom', 'Korea Republic', 'player'),
	('Alexis Villalva', 'Paraguay', 'player'),
	('Ali Ateş', 'Turkey', 'player'),
	('Derlis Aquino', 'Paraguay', 'player'),
	('Tomás Pozzo', 'Argentina', 'player'),
	('Sebastian S. Sebulonsen', 'Norway', 'player'),
	('Louis Jones', 'England', 'player'),
	('Harvey Cartwright', 'England', 'player'),
	('Niklo Dailly', 'Belgium', 'player'),
	('Gonzalo Sánchez', 'Peru', 'player'),
	('Charlie Winfield', 'England', 'player'),
	('Kim Jung Hyun', 'Korea Republic', 'player'),
	('Denilson Gonzáles', 'Peru', 'player'),
	('William Fitzgerald', 'Republic of Ireland', 'player'),
	('Leonard Bredol', 'Germany', 'player'),
	('Nsana Simon', 'France', 'player'),
	('Ge Zhen', 'China PR', 'player'),
	('Ben Stirling', 'Scotland', 'player'),
	('Mason Stajduhar', 'United States', 'player'),
	('Qasem Lajami', 'Saudi Arabia', 'player'),
	('Oscar Brennan', 'Republic of Ireland', 'player'),
	('Matías Miranda', 'Argentina', 'player'),
	('Zico Bailey', 'United States', 'player'),
	('Carlos Niño Espinola', 'Paraguay', 'player'),
	('Erland Tangvik', 'Norway', 'player'),
	('Bryce Duke', 'United States', 'player'),
	('Juan Gamboa', 'Mexico', 'player'),
	('Sam Ashford', 'England', 'player'),
	('Łukasz Zjawiński', 'Poland', 'player'),
	('Caleb Chukwuemeka', 'England', 'player'),
	('Steve Shamal', 'France', 'player'),
	('Bartłomiej Mruk', 'Poland', 'player'),
	('Charlie Cresswell', 'England', 'player'),
	('Tommy Pawlson', 'Australia', 'player'),
	('Darius Ghindovean', 'Romania', 'player'),
	('Vicente Pizarro', 'Chile', 'player'),
	('Tom Schlitter', 'Germany', 'player'),
	('Jeyson Rojas', 'Chile', 'player'),
	('Carl Gustafsson', 'Sweden', 'player'),
	('Sander Risan Mørk', 'Norway', 'player'),
	('Patrick Flottmann', 'Australia', 'player'),
	('Jakub Niewiadomski', 'Poland', 'player'),
	('Marco Raimondo-Metzger', 'Germany', 'player'),
	('Arian Kabashi', 'Kosovo', 'player'),
	('Mark McChrystal', 'Northern Ireland', 'player'),
	('Zhang Yan', 'China PR', 'player'),
	('Albert Popa', 'Romania', 'player'),
	('Yun Ji Hyeok', 'Korea Republic', 'player'),
	('Leonel Miguel', 'Netherlands', 'player'),
	('Gastón Avila', 'Argentina', 'player'),
	('Jaze Kabia', 'Republic of Ireland', 'player'),
	('Nicolás Dávila', 'Ecuador', 'player'),
	('Richard Spenhay', 'Bolivia', 'player'),
	('Samuel Pozo', 'Bolivia', 'player'),
	('Nikita Kotin', 'Russia', 'player'),
	('Sören Lippert', 'Germany', 'player'),
	('Luis Casiani', 'Venezuela', 'player'),
	('Magnus R. Jensen', 'Denmark', 'player'),
	('Feng Gang', 'China PR', 'player'),
	('Esteban Petignat', 'Switzerland', 'player'),
	('Sam Sutton', 'New Zealand', 'player'),
	('Assad Al Hamlawi', 'Sweden', 'player'),
	('Harry Van der Saag', 'Australia', 'player'),
	('Ajibola Alese', 'England', 'player'),
	('Charlie Barker', 'England', 'player'),
	('Sean Roughan', 'Republic of Ireland', 'player'),
	('Mohannad Awadh', 'Saudi Arabia', 'player'),
	('Lee Si Heon', 'Korea Republic', 'player'),
	('Jon Mellish', 'England', 'player'),
	('Kusini Yengi', 'Australia', 'player'),
	('Yusho Takahashi', 'Japan', 'player'),
	('Corentin Chaminade', 'France', 'player'),
	('Ema Twumasi', 'Ghana', 'player'),
	('Wu Wei', 'China PR', 'player'),
	('Clody Menacho', 'Bolivia', 'player'),
	('Kerem Kesgin', 'Turkey', 'player'),
	('Mohammed Al Saeed', 'Saudi Arabia', 'player'),
	('Niklas Lang', 'Germany', 'player'),
	('Andre Hasanally', 'England', 'player'),
	('Tian Xin', 'China PR', 'player'),
	('Tyler Burey', 'England', 'player'),
	('Andre Rawls', 'United States', 'player'),
	('Tommy McCabe', 'United States', 'player'),
	('Dan Moss', 'England', 'player'),
	('Kevin Serna', 'Colombia', 'player'),
	('Jeong Chi In', 'Korea Republic', 'player'),
	('Tadhg Ryan', 'Republic of Ireland', 'player'),
	('Patrick Osterhage', 'Germany', 'player'),
	('Ayil Haqawi', 'Saudi Arabia', 'player'),
	('Aldair Peña', 'Venezuela', 'player'),
	('Omar Al Sunain', 'Saudi Arabia', 'player'),
	('Javier Domínguez', 'Paraguay', 'player'),
	('Lassine Sinayoko', 'France', 'player'),
	('Diego Navarro', 'Bolivia', 'player'),
	('Dayle Rooney', 'Republic of Ireland', 'player'),
	('Conor Kearns', 'Republic of Ireland', 'player'),
	('Luis Ibarra', 'Paraguay', 'player'),
	('Riyo Kawamoto', 'Japan', 'player'),
	('Marc-Antoine Guillaume', 'France', 'player'),
	('Matt Bersano', 'United States', 'player'),
	('Zehn Mohammed', 'England', 'player'),
	('Isaac Olaofe', 'England', 'player'),
	('Kaito Kamiya', 'Japan', 'player'),
	('Mark Russell', 'Scotland', 'player'),
	('Joshué Quiñónez', 'Ecuador', 'player'),
	('Saikou Janneh', 'Gambia', 'player'),
	('Tony McNamee', 'Republic of Ireland', 'player'),
	('Manuel Llano', 'Argentina', 'player'),
	('Esteban Valencia', 'Chile', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Sanousi Hawsawi', 'Saudi Arabia', 'hawsawi'),
	('Sanousi Hawsawi', 'Saudi Arabia', 'sanousi hawsawi'),
	('Linus Borgström', 'Sweden', 'linus borgstrom'),
	('Linus Borgström', 'Sweden', 'borgstrom'),
	('Phelipe', 'Brazil', 'phelipe'),
	('Ștefan Bodișteanu', 'Romania', 'bodisteanu'),
	('Ștefan Bodișteanu', 'Romania', 'stefan bodisteanu'),
	('Dragoș Tescan', 'Romania', 'tescan'),
	('Dragoș Tescan', 'Romania', 'dragos tescan'),
	('Peter Morrison', 'Scotland', 'morrison'),
	('Peter Morrison', 'Scotland', 'peter morrison'),
	('Anthony Breslin', 'Republic of Ireland', 'anthony breslin'),
	('Anthony Breslin', 'Republic of Ireland', 'breslin'),
	('Deshane Dalling', 'England', 'dalling'),
	('Deshane Dalling', 'England', 'deshane dalling'),
	('Darragh Noone', 'Republic of Ireland', 'darragh noone'),
	('Darragh Noone', 'Republic of Ireland', 'noone'),
	('Filip Szymczak', 'Poland', 'filip szymczak'),
	('Filip Szymczak', 'Poland', 'szymczak'),
	('Bonsu Osei', 'Ghana', 'osei'),
	('Bonsu Osei', 'Ghana', 'bonsu osei'),
	('James Rowland', 'England', 'rowland'),
	('James Rowland', 'England', 'james rowland'),
	('Murathan Sütçü', 'Turkey', 'murathan sutcu'),
	('Murathan Sütçü', 'Turkey', 'sutcu'),
	('André Österholm', 'Sweden', 'osterholm'),
	('André Österholm', 'Sweden', 'andre osterholm'),
	('Sergio Sulbarán', 'Venezuela', 'sulbaran'),
	('Sergio Sulbarán', 'Venezuela', 'sergio sulbaran'),
	('İlker Karakaş', 'Turkey', 'karakas'),
	('İlker Karakaş', 'Turkey', 'ilker karakas'),
	('George Lloyd', 'England', 'lloyd'),
	('George Lloyd', 'England', 'george lloyd'),
	('Robin Jalving', 'Netherlands', 'robin jalving'),
	('Robin Jalving', 'Netherlands', 'jalving'),
	('Johl Powell', 'England', 'powell'),
	('Johl Powell', 'England', 'johl powell'),
	('Ole Didrik Blomberg', 'Norway', 'ole didrik blomberg'),
	('Ole Didrik Blomberg', 'Norway', 'blomberg'),
	('Sava-Arangel Cestic', 'Germany', 'cestic'),
	('Sava-Arangel Cestic', 'Germany', 'savaarangel cestic'),
	('Remy Howarth', 'England', 'remy howarth'),
	('Remy Howarth', 'England', 'howarth'),
	('Noor Al Rashidi', 'Saudi Arabia', 'noor al rashidi'),
	('Noor Al Rashidi', 'Saudi Arabia', 'rashidi'),
	('George Campbell', 'United States', 'george campbell'),
	('George Campbell', 'United States', 'campbell'),
	('Franco Quinteros', 'Argentina', 'franco quinteros'),
	('Franco Quinteros', 'Argentina', 'quinteros'),
	('Mickaël Biron', 'France', 'biron'),
	('Mickaël Biron', 'France', 'mickael biron'),
	('Ágúst Hlynsson', 'Iceland', 'hlynsson'),
	('Ágúst Hlynsson', 'Iceland', 'agust hlynsson'),
	('Ronan Jay', 'France', 'ronan jay'),
	('Ronan Jay', 'France', 'jay'),
	('Lloyd Kerry', 'England', 'lloyd kerry'),
	('Lloyd Kerry', 'England', 'kerry'),
	('Ryan Scully', 'Scotland', 'ryan scully'),
	('Ryan Scully', 'Scotland', 'scully'),
	('Andrés Barboza', 'Uruguay', 'andres barboza'),
	('Andrés Barboza', 'Uruguay', 'barboza'),
	('Wang Yaopeng', 'China PR', 'wang yaopeng'),
	('Wang Yaopeng', 'China PR', 'yaopeng'),
	('Tom Dele-Bashiru', 'Nigeria', 'delebashiru'),
	('Tom Dele-Bashiru', 'Nigeria', 'tom delebashiru'),
	('Zaid Al-Hussaini', 'England', 'alhussaini'),
	('Zaid Al-Hussaini', 'England', 'zaid alhussaini'),
	('Rafiki Saïd', 'Comoros', 'rafiki said'),
	('Rafiki Saïd', 'Comoros', 'said'),
	('Kelyan Guessoum', 'France', 'kelyan guessoum'),
	('Kelyan Guessoum', 'France', 'guessoum'),
	('Tunde Owolabi', 'Nigeria', 'tunde owolabi'),
	('Tunde Owolabi', 'Nigeria', 'owolabi'),
	('Rasmus Rosenqvist', 'Sweden', 'rosenqvist'),
	('Rasmus Rosenqvist', 'Sweden', 'rasmus rosenqvist'),
	('Juan Esteban Moreno', 'Colombia', 'moreno'),
	('Juan Esteban Moreno', 'Colombia', 'juan esteban moreno'),
	('Patrick Trindade', 'France', 'patrick trindade'),
	('Patrick Trindade', 'France', 'trindade'),
	('Ricardo Gutiérrez', 'Mexico', 'ricardo gutierrez'),
	('Ricardo Gutiérrez', 'Mexico', 'gutierrez'),
	('Kwadwo Baah', 'England', 'kwadwo baah'),
	('Kwadwo Baah', 'England', 'baah'),
	('Mikael Ugland', 'Norway', 'ugland'),
	('Mikael Ugland', 'Norway', 'mikael ugland'),
	('James Doona', 'Republic of Ireland', 'doona'),
	('James Doona', 'Republic of Ireland', 'james doona'),
	('Apostolos Stamatelopoulos', 'Australia', 'apostolos stamatelopoulos'),
	('Apostolos Stamatelopoulos', 'Australia', 'stamatelopoulos'),
	('Isak Dahlqvist', 'Sweden', 'isak dahlqvist'),
	('Isak Dahlqvist', 'Sweden', 'dahlqvist'),
	('Tobe Leysen', 'Belgium', 'leysen'),
	('Tobe Leysen', 'Belgium', 'tobe leysen'),
	('Mohammed Al Haeti', 'Saudi Arabia', 'haeti'),
	('Mohammed Al Haeti', 'Saudi Arabia', 'mohammed al haeti'),
	('Luis Acevedo', 'Uruguay', 'luis acevedo'),
	('Luis Acevedo', 'Uruguay', 'acevedo'),
	('Luqman Hakim', 'Malaysia', 'luqman hakim'),
	('Luqman Hakim', 'Malaysia', 'hakim'),
	('Henrik Bellman', 'Sweden', 'henrik bellman'),
	('Henrik Bellman', 'Sweden', 'bellman'),
	('Justin Löwe', 'Germany', 'justin lowe'),
	('Justin Löwe', 'Germany', 'lowe'),
	('Joël Monteiro', 'Portugal', 'joel monteiro'),
	('Joël Monteiro', 'Portugal', 'monteiro'),
	('Israel Reyes', 'Mexico', 'israel reyes'),
	('Israel Reyes', 'Mexico', 'reyes'),
	('Emmanuel Léonce Kouadio', 'Germany', 'emmanuel leonce kouadio'),
	('Emmanuel Léonce Kouadio', 'Germany', 'kouadio'),
	('Jhonnyer Rojas', 'Ecuador', 'jhonnyer rojas'),
	('Jhonnyer Rojas', 'Ecuador', 'rojas'),
	('Isaiah Jones', 'England', 'jones'),
	('Isaiah Jones', 'England', 'isaiah jones'),
	('Alexander Nilsson', 'Sweden', 'nilsson'),
	('Alexander Nilsson', 'Sweden', 'alexander nilsson'),
	('Raffaele Cretaro', 'Republic of Ireland', 'cretaro'),
	('Raffaele Cretaro', 'Republic of Ireland', 'raffaele cretaro'),
	('Søren Tengstedt', 'Denmark', 'sren tengstedt'),
	('Søren Tengstedt', 'Denmark', 'tengstedt'),
	('Luca Philipp', 'Germany', 'luca philipp'),
	('Luca Philipp', 'Germany', 'philipp'),
	('Dominik Frelek', 'Poland', 'dominik frelek'),
	('Dominik Frelek', 'Poland', 'frelek'),
	('Nathan Patterson', 'Scotland', 'patterson'),
	('Nathan Patterson', 'Scotland', 'nathan patterson'),
	('Jonas Brauti', 'Norway', 'jonas brauti'),
	('Jonas Brauti', 'Norway', 'brauti'),
	('Nmadi-Morris Igbokwe', 'Germany', 'igbokwe'),
	('Nmadi-Morris Igbokwe', 'Germany', 'nmadimorris igbokwe'),
	('Nikodem Fiedosewicz', 'Poland', 'fiedosewicz'),
	('Nikodem Fiedosewicz', 'Poland', 'nikodem fiedosewicz'),
	('Ömer Uzun', 'Turkey', 'omer uzun'),
	('Ömer Uzun', 'Turkey', 'uzun'),
	('Koki Tachi', 'Japan', 'tachi'),
	('Koki Tachi', 'Japan', 'koki tachi'),
	('Alistair Johnston', 'Canada', 'johnston'),
	('Alistair Johnston', 'Canada', 'alistair johnston'),
	('Shpetim Xhaka', 'Albania', 'shpetim xhaka'),
	('Shpetim Xhaka', 'Albania', 'xhaka'),
	('Ethan Bristow', 'England', 'bristow'),
	('Ethan Bristow', 'England', 'ethan bristow'),
	('Alex Cooper', 'Scotland', 'cooper'),
	('Alex Cooper', 'Scotland', 'alex cooper'),
	('Zhang Yi', 'China PR', 'yi'),
	('Zhang Yi', 'China PR', 'zhang yi'),
	('Yvan Alounga', 'Switzerland', 'alounga'),
	('Yvan Alounga', 'Switzerland', 'yvan alounga'),
	('Jonas Brendieck', 'Germany', 'jonas brendieck'),
	('Jonas Brendieck', 'Germany', 'brendieck'),
	('Shane McEleney', 'Republic of Ireland', 'shane mceleney'),
	('Shane McEleney', 'Republic of Ireland', 'mceleney'),
	('Szymon Mroczko', 'Poland', 'mroczko'),
	('Szymon Mroczko', 'Poland', 'szymon mroczko'),
	('Mark McGuinness', 'Republic of Ireland', 'mark mcguinness'),
	('Mark McGuinness', 'Republic of Ireland', 'mcguinness'),
	('Luke McNally', 'Republic of Ireland', 'luke mcnally'),
	('Luke McNally', 'Republic of Ireland', 'mcnally'),
	('Yosimar Rodríguez', 'Ecuador', 'yosimar rodriguez'),
	('Yosimar Rodríguez', 'Ecuador', 'rodriguez'),
	('Kalpi Ouattara', 'Ivory Coast', 'kalpi ouattara'),
	('Kalpi Ouattara', 'Ivory Coast', 'ouattara'),
	('Thomas Vannoye', 'France', 'vannoye'),
	('Thomas Vannoye', 'France', 'thomas vannoye'),
	('Tomas Brindley', 'Scotland', 'tomas brindley'),
	('Tomas Brindley', 'Scotland', 'brindley'),
	('Shuto Watanabe', 'Japan', 'watanabe'),
	('Shuto Watanabe', 'Japan', 'shuto watanabe'),
	('Yeboah Amankwah', 'Ghana', 'amankwah'),
	('Yeboah Amankwah', 'Ghana', 'yeboah amankwah'),
	('Haruya Fujii', 'Japan', 'haruya fujii'),
	('Haruya Fujii', 'Japan', 'fujii'),
	('Vetle Fiskerstrand', 'Norway', 'fiskerstrand'),
	('Vetle Fiskerstrand', 'Norway', 'vetle fiskerstrand'),
	('Hussain Al Hajouj', 'Saudi Arabia', 'hajouj'),
	('Hussain Al Hajouj', 'Saudi Arabia', 'hussain al hajouj'),
	('Zheng Zhiyun', 'China PR', 'zhiyun'),
	('Zheng Zhiyun', 'China PR', 'zheng zhiyun'),
	('Ramzi Solan', 'Saudi Arabia', 'ramzi solan'),
	('Ramzi Solan', 'Saudi Arabia', 'solan'),
	('Adrian Edqvist', 'Sweden', 'edqvist'),
	('Adrian Edqvist', 'Sweden', 'adrian edqvist'),
	('Mauro Rojas', 'Paraguay', 'mauro rojas'),
	('Mauro Rojas', 'Paraguay', 'rojas'),
	('Scott Wilson', 'England', 'scott wilson'),
	('Scott Wilson', 'England', 'wilson'),
	('Lluis Andreu', 'Spain', 'andreu'),
	('Lluis Andreu', 'Spain', 'lluis andreu'),
	('Jordan Hallam', 'England', 'hallam'),
	('Jordan Hallam', 'England', 'jordan hallam'),
	('Ionuț Pop', 'Romania', 'ionut pop'),
	('Ionuț Pop', 'Romania', 'pop'),
	('Lenn Jastremski', 'Germany', 'jastremski'),
	('Lenn Jastremski', 'Germany', 'lenn jastremski'),
	('Kilian Bauernfeind', 'Austria', 'kilian bauernfeind'),
	('Kilian Bauernfeind', 'Austria', 'bauernfeind'),
	('Anthony Descotte', 'Belgium', 'anthony descotte'),
	('Anthony Descotte', 'Belgium', 'descotte'),
	('Peter Buch Christiansen', 'Denmark', 'peter buch christiansen'),
	('Peter Buch Christiansen', 'Denmark', 'christiansen'),
	('Julian Albrecht', 'Germany', 'albrecht'),
	('Julian Albrecht', 'Germany', 'julian albrecht'),
	('Oliver Klitten', 'Denmark', 'klitten'),
	('Oliver Klitten', 'Denmark', 'oliver klitten'),
	('Salis Abdul Samed', 'Ghana', 'samed'),
	('Salis Abdul Samed', 'Ghana', 'salis abdul samed'),
	('Mikkel Hyllegaard', 'Denmark', 'hyllegaard'),
	('Mikkel Hyllegaard', 'Denmark', 'mikkel hyllegaard'),
	('Daiki Hotta', 'Japan', 'hotta'),
	('Daiki Hotta', 'Japan', 'daiki hotta'),
	('Juan Etchebarne', 'Uruguay', 'etchebarne'),
	('Juan Etchebarne', 'Uruguay', 'juan etchebarne'),
	('Cho Gue Sung', 'Korea Republic', 'cho gue sung'),
	('Cho Gue Sung', 'Korea Republic', 'sung'),
	('Wataru Tanaka', 'Japan', 'wataru tanaka'),
	('Wataru Tanaka', 'Japan', 'tanaka'),
	('Tomás Ahumada', 'Chile', 'tomas ahumada'),
	('Tomás Ahumada', 'Chile', 'ahumada'),
	('Magnus Warming', 'Denmark', 'magnus warming'),
	('Magnus Warming', 'Denmark', 'warming'),
	('Walter Scott', 'Australia', 'walter scott'),
	('Walter Scott', 'Australia', 'scott'),
	('George Gibson', 'Norway', 'gibson'),
	('George Gibson', 'Norway', 'george gibson'),
	('Dejan Tetek', 'Serbia', 'tetek'),
	('Dejan Tetek', 'Serbia', 'dejan tetek'),
	('Radhi Al Otaibi', 'Saudi Arabia', 'radhi al otaibi'),
	('Radhi Al Otaibi', 'Saudi Arabia', 'otaibi'),
	('Niall Morahan', 'Republic of Ireland', 'morahan'),
	('Niall Morahan', 'Republic of Ireland', 'niall morahan'),
	('Egy Maulana Vikri', 'Indonesia', 'egy maulana vikri'),
	('Egy Maulana Vikri', 'Indonesia', 'vikri'),
	('Mohammed Awaji', 'Saudi Arabia', 'mohammed awaji'),
	('Mohammed Awaji', 'Saudi Arabia', 'awaji'),
	('Alexander Bolaños', 'Ecuador', 'bolanos'),
	('Alexander Bolaños', 'Ecuador', 'alexander bolanos'),
	('Joseph Espinoza', 'Ecuador', 'joseph espinoza'),
	('Joseph Espinoza', 'Ecuador', 'espinoza'),
	('Gürkan Başkan', 'Turkey', 'gurkan baskan'),
	('Gürkan Başkan', 'Turkey', 'baskan'),
	('Ed Williams', 'England', 'ed williams'),
	('Ed Williams', 'England', 'williams'),
	('Aidan Friel', 'Republic of Ireland', 'aidan friel'),
	('Aidan Friel', 'Republic of Ireland', 'friel'),
	('Alan Bennett', 'Republic of Ireland', 'bennett'),
	('Alan Bennett', 'Republic of Ireland', 'alan bennett'),
	('Piotr Samiec-Talar', 'Poland', 'piotr samiectalar'),
	('Piotr Samiec-Talar', 'Poland', 'samiectalar'),
	('Adonis Preciado', 'Ecuador', 'preciado'),
	('Adonis Preciado', 'Ecuador', 'adonis preciado'),
	('Dario De Vita', 'Germany', 'vita'),
	('Dario De Vita', 'Germany', 'dario de vita'),
	('Juan Sforza', 'Argentina', 'juan sforza'),
	('Juan Sforza', 'Argentina', 'sforza'),
	('Juan Daniel Cifuentes', 'Colombia', 'cifuentes'),
	('Juan Daniel Cifuentes', 'Colombia', 'juan daniel cifuentes'),
	('Xavier Pineda', 'Ecuador', 'pineda'),
	('Xavier Pineda', 'Ecuador', 'xavier pineda'),
	('Jordan Eastham', 'England', 'eastham'),
	('Jordan Eastham', 'England', 'jordan eastham'),
	('Robert Voloder', 'Germany', 'robert voloder'),
	('Robert Voloder', 'Germany', 'voloder'),
	('Harry Phillips', 'England', 'harry phillips'),
	('Harry Phillips', 'England', 'phillips'),
	('Qiao Wei', 'China PR', 'qiao wei'),
	('Qiao Wei', 'China PR', 'wei'),
	('Kevin Lokko', 'England', 'kevin lokko'),
	('Kevin Lokko', 'England', 'lokko'),
	('Wang Xianjun', 'China PR', 'wang xianjun'),
	('Wang Xianjun', 'China PR', 'xianjun'),
	('Akinwale Odimayo', 'England', 'odimayo'),
	('Akinwale Odimayo', 'England', 'akinwale odimayo'),
	('Rockson Renteria', 'Ecuador', 'rockson renteria'),
	('Rockson Renteria', 'Ecuador', 'renteria'),
	('Benjamin Gommert', 'Germany', 'benjamin gommert'),
	('Benjamin Gommert', 'Germany', 'gommert'),
	('Bao Yaxiong', 'China PR', 'yaxiong'),
	('Bao Yaxiong', 'China PR', 'bao yaxiong'),
	('Mert-Yusuf Torlak', 'Turkey', 'torlak'),
	('Mert-Yusuf Torlak', 'Turkey', 'mertyusuf torlak'),
	('Hugo Constant', 'France', 'constant'),
	('Hugo Constant', 'France', 'hugo constant'),
	('Lim Seung Gyeom', 'Korea Republic', 'gyeom'),
	('Lim Seung Gyeom', 'Korea Republic', 'lim seung gyeom'),
	('Alexis Villalva', 'Paraguay', 'alexis villalva'),
	('Alexis Villalva', 'Paraguay', 'villalva'),
	('Ali Ateş', 'Turkey', 'ates'),
	('Ali Ateş', 'Turkey', 'ali ates'),
	('Derlis Aquino', 'Paraguay', 'derlis aquino'),
	('Derlis Aquino', 'Paraguay', 'aquino'),
	('Tomás Pozzo', 'Argentina', 'pozzo'),
	('Tomás Pozzo', 'Argentina', 'tomas pozzo'),
	('Sebastian S. Sebulonsen', 'Norway', 'sebulonsen'),
	('Sebastian S. Sebulonsen', 'Norway', 'sebastian s sebulonsen'),
	('Louis Jones', 'England', 'louis jones'),
	('Louis Jones', 'England', 'jones'),
	('Harvey Cartwright', 'England', 'harvey cartwright'),
	('Harvey Cartwright', 'England', 'cartwright'),
	('Niklo Dailly', 'Belgium', 'niklo dailly'),
	('Niklo Dailly', 'Belgium', 'dailly'),
	('Gonzalo Sánchez', 'Peru', 'gonzalo sanchez'),
	('Gonzalo Sánchez', 'Peru', 'sanchez'),
	('Charlie Winfield', 'England', 'charlie winfield'),
	('Charlie Winfield', 'England', 'winfield'),
	('Kim Jung Hyun', 'Korea Republic', 'hyun'),
	('Kim Jung Hyun', 'Korea Republic', 'kim jung hyun'),
	('Denilson Gonzáles', 'Peru', 'denilson gonzales'),
	('Denilson Gonzáles', 'Peru', 'gonzales'),
	('William Fitzgerald', 'Republic of Ireland', 'william fitzgerald'),
	('William Fitzgerald', 'Republic of Ireland', 'fitzgerald'),
	('Leonard Bredol', 'Germany', 'leonard bredol'),
	('Leonard Bredol', 'Germany', 'bredol'),
	('Nsana Simon', 'France', 'nsana simon'),
	('Nsana Simon', 'France', 'simon'),
	('Ge Zhen', 'China PR', 'zhen'),
	('Ge Zhen', 'China PR', 'ge zhen'),
	('Ben Stirling', 'Scotland', 'ben stirling'),
	('Ben Stirling', 'Scotland', 'stirling'),
	('Mason Stajduhar', 'United States', 'stajduhar'),
	('Mason Stajduhar', 'United States', 'mason stajduhar'),
	('Qasem Lajami', 'Saudi Arabia', 'lajami'),
	('Qasem Lajami', 'Saudi Arabia', 'qasem lajami'),
	('Oscar Brennan', 'Republic of Ireland', 'oscar brennan'),
	('Oscar Brennan', 'Republic of Ireland', 'brennan'),
	('Matías Miranda', 'Argentina', 'miranda'),
	('Matías Miranda', 'Argentina', 'matias miranda'),
	('Zico Bailey', 'United States', 'zico bailey'),
	('Zico Bailey', 'United States', 'bailey'),
	('Carlos Niño Espinola', 'Paraguay', 'carlos nino espinola'),
	('Carlos Niño Espinola', 'Paraguay', 'espinola'),
	('Erland Tangvik', 'Norway', 'tangvik'),
	('Erland Tangvik', 'Norway', 'erland tangvik'),
	('Bryce Duke', 'United States', 'duke'),
	('Bryce Duke', 'United States', 'bryce duke'),
	('Juan Gamboa', 'Mexico', 'juan gamboa'),
	('Juan Gamboa', 'Mexico', 'gamboa'),
	('Sam Ashford', 'England', 'sam ashford'),
	('Sam Ashford', 'England', 'ashford'),
	('Łukasz Zjawiński', 'Poland', 'zjawinski'),
	('Łukasz Zjawiński', 'Poland', 'ukasz zjawinski'),
	('Caleb Chukwuemeka', 'England', 'chukwuemeka'),
	('Caleb Chukwuemeka', 'England', 'caleb chukwuemeka'),
	('Steve Shamal', 'France', 'shamal'),
	('Steve Shamal', 'France', 'steve shamal'),
	('Bartłomiej Mruk', 'Poland', 'mruk'),
	('Bartłomiej Mruk', 'Poland', 'bartomiej mruk'),
	('Charlie Cresswell', 'England', 'cresswell'),
	('Charlie Cresswell', 'England', 'charlie cresswell'),
	('Tommy Pawlson', 'Australia', 'pawlson'),
	('Tommy Pawlson', 'Australia', 'tommy pawlson'),
	('Darius Ghindovean', 'Romania', 'ghindovean'),
	('Darius Ghindovean', 'Romania', 'darius ghindovean'),
	('Vicente Pizarro', 'Chile', 'pizarro'),
	('Vicente Pizarro', 'Chile', 'vicente pizarro'),
	('Tom Schlitter', 'Germany', 'schlitter'),
	('Tom Schlitter', 'Germany', 'tom schlitter'),
	('Jeyson Rojas', 'Chile', 'jeyson rojas'),
	('Jeyson Rojas', 'Chile', 'rojas'),
	('Carl Gustafsson', 'Sweden', 'gustafsson'),
	('Carl Gustafsson', 'Sweden', 'carl gustafsson'),
	('Sander Risan Mørk', 'Norway', 'sander risan mrk'),
	('Sander Risan Mørk', 'Norway', 'mrk'),
	('Patrick Flottmann', 'Australia', 'patrick flottmann'),
	('Patrick Flottmann', 'Australia', 'flottmann'),
	('Jakub Niewiadomski', 'Poland', 'niewiadomski'),
	('Jakub Niewiadomski', 'Poland', 'jakub niewiadomski'),
	('Marco Raimondo-Metzger', 'Germany', 'raimondometzger'),
	('Marco Raimondo-Metzger', 'Germany', 'marco raimondometzger'),
	('Arian Kabashi', 'Kosovo', 'arian kabashi'),
	('Arian Kabashi', 'Kosovo', 'kabashi'),
	('Mark McChrystal', 'Northern Ireland', 'mcchrystal'),
	('Mark McChrystal', 'Northern Ireland', 'mark mcchrystal'),
	('Zhang Yan', 'China PR', 'yan'),
	('Zhang Yan', 'China PR', 'zhang yan'),
	('Albert Popa', 'Romania', 'albert popa'),
	('Albert Popa', 'Romania', 'popa'),
	('Yun Ji Hyeok', 'Korea Republic', 'hyeok'),
	('Yun Ji Hyeok', 'Korea Republic', 'yun ji hyeok'),
	('Leonel Miguel', 'Netherlands', 'leonel miguel'),
	('Leonel Miguel', 'Netherlands', 'miguel'),
	('Gastón Avila', 'Argentina', 'gaston avila'),
	('Gastón Avila', 'Argentina', 'avila'),
	('Jaze Kabia', 'Republic of Ireland', 'kabia'),
	('Jaze Kabia', 'Republic of Ireland', 'jaze kabia'),
	('Nicolás Dávila', 'Ecuador', 'nicolas davila'),
	('Nicolás Dávila', 'Ecuador', 'davila'),
	('Richard Spenhay', 'Bolivia', 'spenhay'),
	('Richard Spenhay', 'Bolivia', 'richard spenhay'),
	('Samuel Pozo', 'Bolivia', 'samuel pozo'),
	('Samuel Pozo', 'Bolivia', 'pozo'),
	('Nikita Kotin', 'Russia', 'kotin'),
	('Nikita Kotin', 'Russia', 'nikita kotin'),
	('Sören Lippert', 'Germany', 'soren lippert'),
	('Sören Lippert', 'Germany', 'lippert'),
	('Luis Casiani', 'Venezuela', 'luis casiani'),
	('Luis Casiani', 'Venezuela', 'casiani'),
	('Magnus R. Jensen', 'Denmark', 'magnus r jensen'),
	('Magnus R. Jensen', 'Denmark', 'jensen'),
	('Feng Gang', 'China PR', 'feng gang'),
	('Feng Gang', 'China PR', 'gang'),
	('Esteban Petignat', 'Switzerland', 'petignat'),
	('Esteban Petignat', 'Switzerland', 'esteban petignat'),
	('Sam Sutton', 'New Zealand', 'sutton'),
	('Sam Sutton', 'New Zealand', 'sam sutton'),
	('Assad Al Hamlawi', 'Sweden', 'assad al hamlawi'),
	('Assad Al Hamlawi', 'Sweden', 'hamlawi'),
	('Harry Van der Saag', 'Australia', 'harry van der saag'),
	('Harry Van der Saag', 'Australia', 'saag'),
	('Ajibola Alese', 'England', 'alese'),
	('Ajibola Alese', 'England', 'ajibola alese'),
	('Charlie Barker', 'England', 'charlie barker'),
	('Charlie Barker', 'England', 'barker'),
	('Sean Roughan', 'Republic of Ireland', 'sean roughan'),
	('Sean Roughan', 'Republic of Ireland', 'roughan'),
	('Mohannad Awadh', 'Saudi Arabia', 'awadh'),
	('Mohannad Awadh', 'Saudi Arabia', 'mohannad awadh'),
	('Lee Si Heon', 'Korea Republic', 'heon'),
	('Lee Si Heon', 'Korea Republic', 'lee si heon'),
	('Jon Mellish', 'England', 'jon mellish'),
	('Jon Mellish', 'England', 'mellish'),
	('Kusini Yengi', 'Australia', 'kusini yengi'),
	('Kusini Yengi', 'Australia', 'yengi'),
	('Yusho Takahashi', 'Japan', 'yusho takahashi'),
	('Yusho Takahashi', 'Japan', 'takahashi'),
	('Corentin Chaminade', 'France', 'corentin chaminade'),
	('Corentin Chaminade', 'France', 'chaminade'),
	('Ema Twumasi', 'Ghana', 'ema twumasi'),
	('Ema Twumasi', 'Ghana', 'twumasi'),
	('Wu Wei', 'China PR', 'wu wei'),
	('Wu Wei', 'China PR', 'wei'),
	('Clody Menacho', 'Bolivia', 'clody menacho'),
	('Clody Menacho', 'Bolivia', 'menacho'),
	('Kerem Kesgin', 'Turkey', 'kesgin'),
	('Kerem Kesgin', 'Turkey', 'kerem kesgin'),
	('Mohammed Al Saeed', 'Saudi Arabia', 'mohammed al saeed'),
	('Mohammed Al Saeed', 'Saudi Arabia', 'saeed'),
	('Niklas Lang', 'Germany', 'lang'),
	('Niklas Lang', 'Germany', 'niklas lang'),
	('Andre Hasanally', 'England', 'hasanally'),
	('Andre Hasanally', 'England', 'andre hasanally'),
	('Tian Xin', 'China PR', 'xin'),
	('Tian Xin', 'China PR', 'tian xin'),
	('Tyler Burey', 'England', 'burey'),
	('Tyler Burey', 'England', 'tyler burey'),
	('Andre Rawls', 'United States', 'rawls'),
	('Andre Rawls', 'United States', 'andre rawls'),
	('Tommy McCabe', 'United States', 'tommy mccabe'),
	('Tommy McCabe', 'United States', 'mccabe'),
	('Dan Moss', 'England', 'moss'),
	('Dan Moss', 'England', 'dan moss'),
	('Kevin Serna', 'Colombia', 'kevin serna'),
	('Kevin Serna', 'Colombia', 'serna'),
	('Jeong Chi In', 'Korea Republic', 'jeong chi in'),
	('Jeong Chi In', 'Korea Republic', 'in'),
	('Tadhg Ryan', 'Republic of Ireland', 'ryan'),
	('Tadhg Ryan', 'Republic of Ireland', 'tadhg ryan'),
	('Patrick Osterhage', 'Germany', 'patrick osterhage'),
	('Patrick Osterhage', 'Germany', 'osterhage'),
	('Ayil Haqawi', 'Saudi Arabia', 'haqawi'),
	('Ayil Haqawi', 'Saudi Arabia', 'ayil haqawi'),
	('Aldair Peña', 'Venezuela', 'aldair pena'),
	('Aldair Peña', 'Venezuela', 'pena'),
	('Omar Al Sunain', 'Saudi Arabia', 'sunain'),
	('Omar Al Sunain', 'Saudi Arabia', 'omar al sunain'),
	('Javier Domínguez', 'Paraguay', 'javier dominguez'),
	('Javier Domínguez', 'Paraguay', 'dominguez'),
	('Lassine Sinayoko', 'France', 'sinayoko'),
	('Lassine Sinayoko', 'France', 'lassine sinayoko'),
	('Diego Navarro', 'Bolivia', 'navarro'),
	('Diego Navarro', 'Bolivia', 'diego navarro'),
	('Dayle Rooney', 'Republic of Ireland', 'dayle rooney'),
	('Dayle Rooney', 'Republic of Ireland', 'rooney'),
	('Conor Kearns', 'Republic of Ireland', 'kearns'),
	('Conor Kearns', 'Republic of Ireland', 'conor kearns'),
	('Luis Ibarra', 'Paraguay', 'ibarra'),
	('Luis Ibarra', 'Paraguay', 'luis ibarra'),
	('Riyo Kawamoto', 'Japan', 'kawamoto'),
	('Riyo Kawamoto', 'Japan', 'riyo kawamoto'),
	('Marc-Antoine Guillaume', 'France', 'guillaume'),
	('Marc-Antoine Guillaume', 'France', 'marcantoine guillaume'),
	('Matt Bersano', 'United States', 'bersano'),
	('Matt Bersano', 'United States', 'matt bersano'),
	('Zehn Mohammed', 'England', 'zehn mohammed'),
	('Zehn Mohammed', 'England', 'mohammed'),
	('Isaac Olaofe', 'England', 'isaac olaofe'),
	('Isaac Olaofe', 'England', 'olaofe'),
	('Kaito Kamiya', 'Japan', 'kaito kamiya'),
	('Kaito Kamiya', 'Japan', 'kamiya'),
	('Mark Russell', 'Scotland', 'mark russell'),
	('Mark Russell', 'Scotland', 'russell'),
	('Joshué Quiñónez', 'Ecuador', 'joshue quinonez'),
	('Joshué Quiñónez', 'Ecuador', 'quinonez'),
	('Saikou Janneh', 'Gambia', 'saikou janneh'),
	('Saikou Janneh', 'Gambia', 'janneh'),
	('Tony McNamee', 'Republic of Ireland', 'mcnamee'),
	('Tony McNamee', 'Republic of Ireland', 'tony mcnamee'),
	('Manuel Llano', 'Argentina', 'manuel llano'),
	('Manuel Llano', 'Argentina', 'llano'),
	('Esteban Valencia', 'Chile', 'valencia'),
	('Esteban Valencia', 'Chile', 'esteban valencia')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';