INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Abdulquddus Attiah', 'Saudi Arabia', 'player'),
	('Jonatan Benedetti', 'Argentina', 'player'),
	('Siebren Lathouwers', 'Belgium', 'player'),
	('Mathias Fredriksen', 'Norway', 'player'),
	('Jesper Isaksen', 'Norway', 'player'),
	('Ronald Cuellar', 'Bolivia', 'player'),
	('George Acosta', 'United States', 'player'),
	('Facundo Vigo', 'Uruguay', 'player'),
	('Lewis Neilson', 'Scotland', 'player'),
	('Connor van den Berg', 'Netherlands', 'player'),
	('Jan de Boer', 'Netherlands', 'player'),
	('Sebastián Claure', 'Bolivia', 'player'),
	('Jérémy Huysman', 'France', 'player'),
	('Sam Todd', 'Republic of Ireland', 'player'),
	('Jakob Voelkerling Persson', 'Sweden', 'player'),
	('Hiroya Matsumoto', 'Japan', 'player'),
	('Jack Evans', 'England', 'player'),
	('Gonzalo Goñi', 'Argentina', 'player'),
	('Pat Webber', 'England', 'player'),
	('Armando Dobra', 'Albania', 'player'),
	('Stefan Westra', 'Netherlands', 'player'),
	('Augusto Aguirre', 'Argentina', 'player'),
	('Choi Beom Kyung', 'Korea Republic', 'player'),
	('Luo Yi', 'China PR', 'player'),
	('James Delianov', 'Australia', 'player'),
	('Xavier Flores', 'Venezuela', 'player'),
	('Ruel Sotiriou', 'Cyprus', 'player'),
	('Erik Björndahl', 'Sweden', 'player'),
	('Lino Tempelmann', 'Germany', 'player'),
	('Yanis Barka', 'France', 'player'),
	('Tass Mourdoukoutas', 'Australia', 'player'),
	('Fabian Tauchhammer', 'Austria', 'player'),
	('Pablo Caro', 'Colombia', 'player'),
	('Declan Glass', 'Scotland', 'player'),
	('Jonas Singer', 'Germany', 'player'),
	('Jake Beesley', 'England', 'player'),
	('Joel Mumbongo', 'Sweden', 'player'),
	('Abdullah Al Yousif', 'Saudi Arabia', 'player'),
	('Tom White', 'England', 'player'),
	('Qiu Tianyi', 'China PR', 'player'),
	('Billy Crellin', 'England', 'player'),
	('An Jin Beom', 'Korea Republic', 'player'),
	('Sander Sjøkvist', 'Norway', 'player'),
	('Arnold López', 'Venezuela', 'player'),
	('Osaze Urhoghide', 'England', 'player'),
	('Jorge Lumbreras', 'Mexico', 'player'),
	('Alfie Lewis', 'England', 'player'),
	('Ronan Darcy', 'England', 'player'),
	('Saqer Otayf', 'Saudi Arabia', 'player'),
	('Marwan Al Haidari', 'Saudi Arabia', 'player'),
	('Paul Löhr', 'Germany', 'player'),
	('José Estupiñán', 'Colombia', 'player'),
	('Marciano Aziz', 'Belgium', 'player'),
	('Sam Nombe', 'England', 'player'),
	('Yousef Omar', 'Niger', 'player'),
	('Ramiz Zerrouki', 'Netherlands', 'player'),
	('Robin Canido', 'Bolivia', 'player'),
	('Liu Weiguo', 'China PR', 'player'),
	('Lachlan Brook', 'Australia', 'player'),
	('Alex Hartridge', 'England', 'player'),
	('Carlos Solíz', 'Bolivia', 'player'),
	('Milton Maciel', 'Paraguay', 'player'),
	('Axel Norén', 'Sweden', 'player'),
	('Brian Anunga', 'Cameroon', 'player'),
	('Kyriakos Stamatopoulos', 'Canada', 'player'),
	('Lukas Klitten', 'Denmark', 'player'),
	('Matteo Di Giusto', 'Switzerland', 'player'),
	('Abdullah Al Humayan', 'Saudi Arabia', 'player'),
	('Ryan Bouallak', 'France', 'player'),
	('Michael Baldisimo', 'Canada', 'player'),
	('Moritz Römling', 'Germany', 'player'),
	('Awn Al Saluli', 'Saudi Arabia', 'player'),
	('Thamer Al Ali', 'Saudi Arabia', 'player'),
	('Mauricio Cabral', 'Bolivia', 'player'),
	('Joseph Olowu', 'England', 'player'),
	('Mick Gudra', 'Germany', 'player'),
	('Gao Huaze', 'China PR', 'player'),
	('Femi Akinwande', 'England', 'player'),
	('Luke Ivanovic', 'Australia', 'player'),
	('José Antonio Cobián', 'Mexico', 'player'),
	('Muhannad Al Shanqeeti', 'Saudi Arabia', 'player'),
	('Lee Sang Hyeob', 'Korea Republic', 'player'),
	('Mike Grim', 'Netherlands', 'player'),
	('Zac McGraw', 'United States', 'player'),
	('Dior Angus', 'England', 'player'),
	('Rayan Souici', 'France', 'player'),
	('Fernando Martínez', 'Paraguay', 'player'),
	('Edward Francis', 'England', 'player'),
	('Andrew Dallas', 'Scotland', 'player'),
	('Giovanni McGregor', 'England', 'player'),
	('Pierce Waring', 'Australia', 'player'),
	('Tahvon Campbell', 'England', 'player'),
	('Taiyo Hama', 'Japan', 'player'),
	('Justin Rennicks', 'United States', 'player'),
	('Zachary Duncan', 'Australia', 'player'),
	('Cristian Martin', 'Uruguay', 'player'),
	('Hasan Emiroğlu', 'Turkey', 'player'),
	('Jordi Govea', 'Ecuador', 'player'),
	('Saúl Zamora', 'Mexico', 'player'),
	('Nico Hug', 'Germany', 'player'),
	('Sebastian Zettl', 'Austria', 'player'),
	('Jimmy Congo', 'Colombia', 'player'),
	('Ahmed Al Shamrani', 'Saudi Arabia', 'player'),
	('Gianni Azzinnari', 'Italy', 'player'),
	('Elliot Osborne', 'England', 'player'),
	('Lee Rae Joon', 'Korea Republic', 'player'),
	('Ömer Faruk Beyaz', 'Turkey', 'player'),
	('Taiki Yamada', 'Japan', 'player'),
	('Stefan Lauf', 'Austria', 'player'),
	('Wilitty Younoussa', 'Cameroon', 'player'),
	('Selim Ilgaz', 'France', 'player'),
	('Erlantz', 'Spain', 'player'),
	('Mathias Pinto', 'Chile', 'player'),
	('Mustafa Kapı', 'Turkey', 'player'),
	('Fumiya Unoki', 'Japan', 'player'),
	('Joseph Vega', 'Peru', 'player'),
	('Enzo Basilio', 'France', 'player'),
	('Carlos Alvarado', 'Ecuador', 'player'),
	('Masataka Nishimoto', 'Japan', 'player'),
	('Rene Gilmartin', 'Republic of Ireland', 'player'),
	('Renato Mendoza', 'Mexico', 'player'),
	('Oscar Pettersson', 'Sweden', 'player'),
	('Justin Vom Steeg', 'United States', 'player'),
	('Santeri Väänänen', 'Finland', 'player'),
	('Marvin Dewaele', 'Belgium', 'player'),
	('Sam Sargeant', 'England', 'player'),
	('Lee Hyun Sik', 'Korea Republic', 'player'),
	('Marian Șerban', 'Romania', 'player'),
	('Ouparine Djoco', 'France', 'player'),
	('Federico Ortíz', 'Argentina', 'player'),
	('Călin Popescu', 'Romania', 'player'),
	('Felipe Mesones', 'Peru', 'player'),
	('Markus Seehusen Karlsbakk', 'Norway', 'player'),
	('Aron Timmerman', 'Netherlands', 'player'),
	('Calvin Bombo', 'France', 'player'),
	('Mihai Cotolan', 'Romania', 'player'),
	('Mihai Popa', 'Romania', 'player'),
	('Nassim Innocenti', 'France', 'player'),
	('Zain Issaka', 'Japan', 'player'),
	('Sem Steijn', 'Netherlands', 'player'),
	('Justin Ospelt', 'Liechtenstein', 'player'),
	('Aaron O''Driscoll', 'Republic of Ireland', 'player'),
	('Fuad Rahimi', 'Kosovo', 'player'),
	('Firas Al Birekan', 'Saudi Arabia', 'player'),
	('Amadou Diallo', 'England', 'player'),
	('Hussain Al Eissa', 'Saudi Arabia', 'player'),
	('Du Changjie', 'China PR', 'player'),
	('Dinesh Gillela', 'England', 'player'),
	('Fabio Carvalho', 'England', 'player'),
	('Jannes Van Hecke', 'Belgium', 'player'),
	('Timmy Abraham', 'England', 'player'),
	('Ekin Celebi', 'Germany', 'player'),
	('Rodrigo Menacho', 'Peru', 'player'),
	('Ricardo Bettocchi', 'Peru', 'player'),
	('Max Kulke', 'Germany', 'player'),
	('Jens Craenmehr', 'Netherlands', 'player'),
	('Enzo Roldán', 'Argentina', 'player'),
	('Jorge Cabezudo', 'Peru', 'player'),
	('Paul Komposch', 'Austria', 'player'),
	('Sofyan Chader', 'France', 'player'),
	('Rob Nizet', 'Belgium', 'player'),
	('Francisco Nevarez', 'Mexico', 'player'),
	('Takumi Nagaishi', 'Japan', 'player'),
	('Christopher McVey', 'Sweden', 'player'),
	('Issac Schmidt', 'Switzerland', 'player'),
	('Terrell Egbri', 'England', 'player'),
	('Noah Smerdon', 'England', 'player'),
	('Rasim Bulic', 'Germany', 'player'),
	('Kyle Zobeck', 'United States', 'player'),
	('Mathieu Scalet', 'France', 'player'),
	('Agustín Lagos', 'Argentina', 'player'),
	('Jakub Kałuziński', 'Poland', 'player'),
	('Pedro Sánchez', 'Chile', 'player'),
	('Ramy Najjarine', 'Australia', 'player'),
	('Lee Sang Jun', 'Korea Republic', 'player'),
	('Yao Hanlin', 'China PR', 'player'),
	('Patryk Plewka', 'Poland', 'player'),
	('David Quintero', 'Colombia', 'player'),
	('Sam Woods', 'England', 'player'),
	('Kim Ju Sung', 'Korea Republic', 'player'),
	('Lukas Gütlbauer', 'Austria', 'player'),
	('Danny Leyva', 'United States', 'player'),
	('Thomas Heward-Belle', 'Australia', 'player'),
	('Michael O''Connor', 'Republic of Ireland', 'player'),
	('Simon Graves', 'Denmark', 'player'),
	('Arne Cassaert', 'Belgium', 'player'),
	('Scott Pollock', 'England', 'player'),
	('Paolo Izaguirre', 'Peru', 'player'),
	('Park Sang Hyuk', 'Korea Republic', 'player'),
	('Agustín Manzur', 'Argentina', 'player'),
	('Tyler Magloire', 'England', 'player'),
	('Ruslan Neshcheret', 'Ukraine', 'player'),
	('Ibrahim Karamoko', 'France', 'player'),
	('Khaled Al Blooshi', 'United Arab Emirates', 'player'),
	('Joshua Kayode', 'Nigeria', 'player'),
	('Jordan Adebayo-Smith', 'United States', 'player'),
	('Thaar Al Otaibi', 'Saudi Arabia', 'player'),
	('Ibrahim Meite', 'England', 'player'),
	('Gabin Delguel', 'France', 'player'),
	('Mohsen Abdullah', 'United Arab Emirates', 'player'),
	('Rodrigo Cerecedo', 'Mexico', 'player'),
	('Alistair Smith', 'England', 'player'),
	('Chris Lema', 'United States', 'player'),
	('Seol Young Woo', 'Korea Republic', 'player'),
	('Jon Russell', 'England', 'player'),
	('Josué Mamani', 'Bolivia', 'player'),
	('Jamie Gullan', 'Scotland', 'player'),
	('Connor Barrett', 'England', 'player'),
	('Hayden Carter', 'England', 'player'),
	('Ennio van der Gouw', 'Netherlands', 'player'),
	('Chanka Zimba', 'England', 'player'),
	('Huseyin Biler', 'England', 'player'),
	('Hussein Ali', 'Sweden', 'player'),
	('Shaun Hobson', 'England', 'player'),
	('Griffin Dorsey', 'United States', 'player'),
	('Alex Hunt', 'England', 'player'),
	('Victor Daguin', 'France', 'player'),
	('Martin Niøten Palumbo', 'Norway', 'player'),
	('Tom Knowles', 'England', 'player'),
	('Teemu Penninkangas', 'Finland', 'player'),
	('Robbie Cundy', 'England', 'player'),
	('Fahad Al Rashidi', 'Saudi Arabia', 'player'),
	('Geraldo Bajrami', 'Albania', 'player'),
	('Karol Stanek', 'Poland', 'player'),
	('Sidney Obissa', 'Gabon', 'player'),
	('Baris Ekincier', 'Azerbaijan', 'player'),
	('Ignacio Russo', 'Argentina', 'player'),
	('Jaime Moreno', 'Nicaragua', 'player'),
	('Julio Herrera', 'Bolivia', 'player'),
	('Nabili Touaizi', 'Spain', 'player'),
	('Emile Acquah', 'England', 'player'),
	('Charlie Jolley', 'England', 'player'),
	('Daniel Byrne', 'Republic of Ireland', 'player'),
	('Anthonys Matos', 'Venezuela', 'player'),
	('Will Rickard', 'Wales', 'player'),
	('Bertie Smith-Hylton', 'Australia', 'player'),
	('Alexandru Oroian', 'Romania', 'player'),
	('Aboubacar Konté', 'Mali', 'player'),
	('Tajon Buchanan', 'Canada', 'player'),
	('Birkan Kirdar', 'Australia', 'player'),
	('Andres Dumitrescu', 'Romania', 'player'),
	('Jack Young', 'England', 'player'),
	('Shandon Hopeau', 'United States', 'player'),
	('Sam Junqua', 'United States', 'player'),
	('Choi Cheol Won', 'Korea Republic', 'player'),
	('Abdulaziz Al Jamaan', 'Saudi Arabia', 'player'),
	('Chang Feiya', 'China PR', 'player'),
	('Divin Baningime', 'DR Congo', 'player'),
	('Obed Nkambadio', 'France', 'player'),
	('Gino Infantino', 'Argentina', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Abdulquddus Attiah', 'Saudi Arabia', 'attiah'),
	('Abdulquddus Attiah', 'Saudi Arabia', 'abdulquddus attiah'),
	('Jonatan Benedetti', 'Argentina', 'jonatan benedetti'),
	('Jonatan Benedetti', 'Argentina', 'benedetti'),
	('Siebren Lathouwers', 'Belgium', 'lathouwers'),
	('Siebren Lathouwers', 'Belgium', 'siebren lathouwers'),
	('Mathias Fredriksen', 'Norway', 'mathias fredriksen'),
	('Mathias Fredriksen', 'Norway', 'fredriksen'),
	('Jesper Isaksen', 'Norway', 'jesper isaksen'),
	('Jesper Isaksen', 'Norway', 'isaksen'),
	('Ronald Cuellar', 'Bolivia', 'cuellar'),
	('Ronald Cuellar', 'Bolivia', 'ronald cuellar'),
	('George Acosta', 'United States', 'acosta'),
	('George Acosta', 'United States', 'george acosta'),
	('Facundo Vigo', 'Uruguay', 'facundo vigo'),
	('Facundo Vigo', 'Uruguay', 'vigo'),
	('Lewis Neilson', 'Scotland', 'neilson'),
	('Lewis Neilson', 'Scotland', 'lewis neilson'),
	('Connor van den Berg', 'Netherlands', 'connor van den berg'),
	('Connor van den Berg', 'Netherlands', 'berg'),
	('Jan de Boer', 'Netherlands', 'boer'),
	('Jan de Boer', 'Netherlands', 'jan de boer'),
	('Sebastián Claure', 'Bolivia', 'claure'),
	('Sebastián Claure', 'Bolivia', 'sebastian claure'),
	('Jérémy Huysman', 'France', 'jeremy huysman'),
	('Jérémy Huysman', 'France', 'huysman'),
	('Sam Todd', 'Republic of Ireland', 'sam todd'),
	('Sam Todd', 'Republic of Ireland', 'todd'),
	('Jakob Voelkerling Persson', 'Sweden', 'jakob voelkerling persson'),
	('Jakob Voelkerling Persson', 'Sweden', 'persson'),
	('Hiroya Matsumoto', 'Japan', 'matsumoto'),
	('Hiroya Matsumoto', 'Japan', 'hiroya matsumoto'),
	('Jack Evans', 'England', 'jack evans'),
	('Jack Evans', 'England', 'evans'),
	('Gonzalo Goñi', 'Argentina', 'gonzalo goni'),
	('Gonzalo Goñi', 'Argentina', 'goni'),
	('Pat Webber', 'England', 'pat webber'),
	('Pat Webber', 'England', 'webber'),
	('Armando Dobra', 'Albania', 'dobra'),
	('Armando Dobra', 'Albania', 'armando dobra'),
	('Stefan Westra', 'Netherlands', 'westra'),
	('Stefan Westra', 'Netherlands', 'stefan westra'),
	('Augusto Aguirre', 'Argentina', 'augusto aguirre'),
	('Augusto Aguirre', 'Argentina', 'aguirre'),
	('Choi Beom Kyung', 'Korea Republic', 'choi beom kyung'),
	('Choi Beom Kyung', 'Korea Republic', 'kyung'),
	('Luo Yi', 'China PR', 'luo yi'),
	('Luo Yi', 'China PR', 'yi'),
	('James Delianov', 'Australia', 'delianov'),
	('James Delianov', 'Australia', 'james delianov'),
	('Xavier Flores', 'Venezuela', 'xavier flores'),
	('Xavier Flores', 'Venezuela', 'flores'),
	('Ruel Sotiriou', 'Cyprus', 'sotiriou'),
	('Ruel Sotiriou', 'Cyprus', 'ruel sotiriou'),
	('Erik Björndahl', 'Sweden', 'erik bjorndahl'),
	('Erik Björndahl', 'Sweden', 'bjorndahl'),
	('Lino Tempelmann', 'Germany', 'lino tempelmann'),
	('Lino Tempelmann', 'Germany', 'tempelmann'),
	('Yanis Barka', 'France', 'barka'),
	('Yanis Barka', 'France', 'yanis barka'),
	('Tass Mourdoukoutas', 'Australia', 'mourdoukoutas'),
	('Tass Mourdoukoutas', 'Australia', 'tass mourdoukoutas'),
	('Fabian Tauchhammer', 'Austria', 'tauchhammer'),
	('Fabian Tauchhammer', 'Austria', 'fabian tauchhammer'),
	('Pablo Caro', 'Colombia', 'caro'),
	('Pablo Caro', 'Colombia', 'pablo caro'),
	('Declan Glass', 'Scotland', 'declan glass'),
	('Declan Glass', 'Scotland', 'glass'),
	('Jonas Singer', 'Germany', 'jonas singer'),
	('Jonas Singer', 'Germany', 'singer'),
	('Jake Beesley', 'England', 'jake beesley'),
	('Jake Beesley', 'England', 'beesley'),
	('Joel Mumbongo', 'Sweden', 'mumbongo'),
	('Joel Mumbongo', 'Sweden', 'joel mumbongo'),
	('Abdullah Al Yousif', 'Saudi Arabia', 'abdullah al yousif'),
	('Abdullah Al Yousif', 'Saudi Arabia', 'yousif'),
	('Tom White', 'England', 'tom white'),
	('Tom White', 'England', 'white'),
	('Qiu Tianyi', 'China PR', 'qiu tianyi'),
	('Qiu Tianyi', 'China PR', 'tianyi'),
	('Billy Crellin', 'England', 'crellin'),
	('Billy Crellin', 'England', 'billy crellin'),
	('An Jin Beom', 'Korea Republic', 'an jin beom'),
	('An Jin Beom', 'Korea Republic', 'beom'),
	('Sander Sjøkvist', 'Norway', 'sander sjkvist'),
	('Sander Sjøkvist', 'Norway', 'sjkvist'),
	('Arnold López', 'Venezuela', 'lopez'),
	('Arnold López', 'Venezuela', 'arnold lopez'),
	('Osaze Urhoghide', 'England', 'osaze urhoghide'),
	('Osaze Urhoghide', 'England', 'urhoghide'),
	('Jorge Lumbreras', 'Mexico', 'jorge lumbreras'),
	('Jorge Lumbreras', 'Mexico', 'lumbreras'),
	('Alfie Lewis', 'England', 'alfie lewis'),
	('Alfie Lewis', 'England', 'lewis'),
	('Ronan Darcy', 'England', 'ronan darcy'),
	('Ronan Darcy', 'England', 'darcy'),
	('Saqer Otayf', 'Saudi Arabia', 'otayf'),
	('Saqer Otayf', 'Saudi Arabia', 'saqer otayf'),
	('Marwan Al Haidari', 'Saudi Arabia', 'marwan al haidari'),
	('Marwan Al Haidari', 'Saudi Arabia', 'haidari'),
	('Paul Löhr', 'Germany', 'lohr'),
	('Paul Löhr', 'Germany', 'paul lohr'),
	('José Estupiñán', 'Colombia', 'estupinan'),
	('José Estupiñán', 'Colombia', 'jose estupinan'),
	('Marciano Aziz', 'Belgium', 'marciano aziz'),
	('Marciano Aziz', 'Belgium', 'aziz'),
	('Sam Nombe', 'England', 'sam nombe'),
	('Sam Nombe', 'England', 'nombe'),
	('Yousef Omar', 'Niger', 'omar'),
	('Yousef Omar', 'Niger', 'yousef omar'),
	('Ramiz Zerrouki', 'Netherlands', 'ramiz zerrouki'),
	('Ramiz Zerrouki', 'Netherlands', 'zerrouki'),
	('Robin Canido', 'Bolivia', 'canido'),
	('Robin Canido', 'Bolivia', 'robin canido'),
	('Liu Weiguo', 'China PR', 'liu weiguo'),
	('Liu Weiguo', 'China PR', 'weiguo'),
	('Lachlan Brook', 'Australia', 'lachlan brook'),
	('Lachlan Brook', 'Australia', 'brook'),
	('Alex Hartridge', 'England', 'hartridge'),
	('Alex Hartridge', 'England', 'alex hartridge'),
	('Carlos Solíz', 'Bolivia', 'soliz'),
	('Carlos Solíz', 'Bolivia', 'carlos soliz'),
	('Milton Maciel', 'Paraguay', 'maciel'),
	('Milton Maciel', 'Paraguay', 'milton maciel'),
	('Axel Norén', 'Sweden', 'noren'),
	('Axel Norén', 'Sweden', 'axel noren'),
	('Brian Anunga', 'Cameroon', 'anunga'),
	('Brian Anunga', 'Cameroon', 'brian anunga'),
	('Kyriakos Stamatopoulos', 'Canada', 'kyriakos stamatopoulos'),
	('Kyriakos Stamatopoulos', 'Canada', 'stamatopoulos'),
	('Lukas Klitten', 'Denmark', 'klitten'),
	('Lukas Klitten', 'Denmark', 'lukas klitten'),
	('Matteo Di Giusto', 'Switzerland', 'matteo di giusto'),
	('Matteo Di Giusto', 'Switzerland', 'giusto'),
	('Abdullah Al Humayan', 'Saudi Arabia', 'abdullah al humayan'),
	('Abdullah Al Humayan', 'Saudi Arabia', 'humayan'),
	('Ryan Bouallak', 'France', 'ryan bouallak'),
	('Ryan Bouallak', 'France', 'bouallak'),
	('Michael Baldisimo', 'Canada', 'michael baldisimo'),
	('Michael Baldisimo', 'Canada', 'baldisimo'),
	('Moritz Römling', 'Germany', 'romling'),
	('Moritz Römling', 'Germany', 'moritz romling'),
	('Awn Al Saluli', 'Saudi Arabia', 'awn al saluli'),
	('Awn Al Saluli', 'Saudi Arabia', 'saluli'),
	('Thamer Al Ali', 'Saudi Arabia', 'ali'),
	('Thamer Al Ali', 'Saudi Arabia', 'thamer al ali'),
	('Mauricio Cabral', 'Bolivia', 'cabral'),
	('Mauricio Cabral', 'Bolivia', 'mauricio cabral'),
	('Joseph Olowu', 'England', 'olowu'),
	('Joseph Olowu', 'England', 'joseph olowu'),
	('Mick Gudra', 'Germany', 'mick gudra'),
	('Mick Gudra', 'Germany', 'gudra'),
	('Gao Huaze', 'China PR', 'gao huaze'),
	('Gao Huaze', 'China PR', 'huaze'),
	('Femi Akinwande', 'England', 'akinwande'),
	('Femi Akinwande', 'England', 'femi akinwande'),
	('Luke Ivanovic', 'Australia', 'ivanovic'),
	('Luke Ivanovic', 'Australia', 'luke ivanovic'),
	('José Antonio Cobián', 'Mexico', 'jose antonio cobian'),
	('José Antonio Cobián', 'Mexico', 'cobian'),
	('Muhannad Al Shanqeeti', 'Saudi Arabia', 'shanqeeti'),
	('Muhannad Al Shanqeeti', 'Saudi Arabia', 'muhannad al shanqeeti'),
	('Lee Sang Hyeob', 'Korea Republic', 'lee sang hyeob'),
	('Lee Sang Hyeob', 'Korea Republic', 'hyeob'),
	('Mike Grim', 'Netherlands', 'grim'),
	('Mike Grim', 'Netherlands', 'mike grim'),
	('Zac McGraw', 'United States', 'zac mcgraw'),
	('Zac McGraw', 'United States', 'mcgraw'),
	('Dior Angus', 'England', 'angus'),
	('Dior Angus', 'England', 'dior angus'),
	('Rayan Souici', 'France', 'rayan souici'),
	('Rayan Souici', 'France', 'souici'),
	('Fernando Martínez', 'Paraguay', 'martinez'),
	('Fernando Martínez', 'Paraguay', 'fernando martinez'),
	('Edward Francis', 'England', 'francis'),
	('Edward Francis', 'England', 'edward francis'),
	('Andrew Dallas', 'Scotland', 'andrew dallas'),
	('Andrew Dallas', 'Scotland', 'dallas'),
	('Giovanni McGregor', 'England', 'giovanni mcgregor'),
	('Giovanni McGregor', 'England', 'mcgregor'),
	('Pierce Waring', 'Australia', 'pierce waring'),
	('Pierce Waring', 'Australia', 'waring'),
	('Tahvon Campbell', 'England', 'campbell'),
	('Tahvon Campbell', 'England', 'tahvon campbell'),
	('Taiyo Hama', 'Japan', 'hama'),
	('Taiyo Hama', 'Japan', 'taiyo hama'),
	('Justin Rennicks', 'United States', 'rennicks'),
	('Justin Rennicks', 'United States', 'justin rennicks'),
	('Zachary Duncan', 'Australia', 'duncan'),
	('Zachary Duncan', 'Australia', 'zachary duncan'),
	('Cristian Martin', 'Uruguay', 'cristian martin'),
	('Cristian Martin', 'Uruguay', 'martin'),
	('Hasan Emiroğlu', 'Turkey', 'emiroglu'),
	('Hasan Emiroğlu', 'Turkey', 'hasan emiroglu'),
	('Jordi Govea', 'Ecuador', 'govea'),
	('Jordi Govea', 'Ecuador', 'jordi govea'),
	('Saúl Zamora', 'Mexico', 'zamora'),
	('Saúl Zamora', 'Mexico', 'saul zamora'),
	('Nico Hug', 'Germany', 'hug'),
	('Nico Hug', 'Germany', 'nico hug'),
	('Sebastian Zettl', 'Austria', 'zettl'),
	('Sebastian Zettl', 'Austria', 'sebastian zettl'),
	('Jimmy Congo', 'Colombia', 'congo'),
	('Jimmy Congo', 'Colombia', 'jimmy congo'),
	('Ahmed Al Shamrani', 'Saudi Arabia', 'ahmed al shamrani'),
	('Ahmed Al Shamrani', 'Saudi Arabia', 'shamrani'),
	('Gianni Azzinnari', 'Italy', 'azzinnari'),
	('Gianni Azzinnari', 'Italy', 'gianni azzinnari'),
	('Elliot Osborne', 'England', 'osborne'),
	('Elliot Osborne', 'England', 'elliot osborne'),
	('Lee Rae Joon', 'Korea Republic', 'joon'),
	('Lee Rae Joon', 'Korea Republic', 'lee rae joon'),
	('Ömer Faruk Beyaz', 'Turkey', 'omer faruk beyaz'),
	('Ömer Faruk Beyaz', 'Turkey', 'beyaz'),
	('Taiki Yamada', 'Japan', 'taiki yamada'),
	('Taiki Yamada', 'Japan', 'yamada'),
	('Stefan Lauf', 'Austria', 'stefan lauf'),
	('Stefan Lauf', 'Austria', 'lauf'),
	('Wilitty Younoussa', 'Cameroon', 'younoussa'),
	('Wilitty Younoussa', 'Cameroon', 'wilitty younoussa'),
	('Selim Ilgaz', 'France', 'selim ilgaz'),
	('Selim Ilgaz', 'France', 'ilgaz'),
	('Erlantz', 'Spain', 'erlantz'),
	('Mathias Pinto', 'Chile', 'mathias pinto'),
	('Mathias Pinto', 'Chile', 'pinto'),
	('Mustafa Kapı', 'Turkey', 'mustafa kap'),
	('Mustafa Kapı', 'Turkey', 'kap'),
	('Fumiya Unoki', 'Japan', 'unoki'),
	('Fumiya Unoki', 'Japan', 'fumiya unoki'),
	('Joseph Vega', 'Peru', 'vega'),
	('Joseph Vega', 'Peru', 'joseph vega'),
	('Enzo Basilio', 'France', 'basilio'),
	('Enzo Basilio', 'France', 'enzo basilio'),
	('Carlos Alvarado', 'Ecuador', 'carlos alvarado'),
	('Carlos Alvarado', 'Ecuador', 'alvarado'),
	('Masataka Nishimoto', 'Japan', 'masataka nishimoto'),
	('Masataka Nishimoto', 'Japan', 'nishimoto'),
	('Rene Gilmartin', 'Republic of Ireland', 'rene gilmartin'),
	('Rene Gilmartin', 'Republic of Ireland', 'gilmartin'),
	('Renato Mendoza', 'Mexico', 'renato mendoza'),
	('Renato Mendoza', 'Mexico', 'mendoza'),
	('Oscar Pettersson', 'Sweden', 'oscar pettersson'),
	('Oscar Pettersson', 'Sweden', 'pettersson'),
	('Justin Vom Steeg', 'United States', 'justin vom steeg'),
	('Justin Vom Steeg', 'United States', 'steeg'),
	('Santeri Väänänen', 'Finland', 'santeri vaananen'),
	('Santeri Väänänen', 'Finland', 'vaananen'),
	('Marvin Dewaele', 'Belgium', 'marvin dewaele'),
	('Marvin Dewaele', 'Belgium', 'dewaele'),
	('Sam Sargeant', 'England', 'sargeant'),
	('Sam Sargeant', 'England', 'sam sargeant'),
	('Lee Hyun Sik', 'Korea Republic', 'lee hyun sik'),
	('Lee Hyun Sik', 'Korea Republic', 'sik'),
	('Marian Șerban', 'Romania', 'serban'),
	('Marian Șerban', 'Romania', 'marian serban'),
	('Ouparine Djoco', 'France', 'ouparine djoco'),
	('Ouparine Djoco', 'France', 'djoco'),
	('Federico Ortíz', 'Argentina', 'ortiz'),
	('Federico Ortíz', 'Argentina', 'federico ortiz'),
	('Călin Popescu', 'Romania', 'calin popescu'),
	('Călin Popescu', 'Romania', 'popescu'),
	('Felipe Mesones', 'Peru', 'mesones'),
	('Felipe Mesones', 'Peru', 'felipe mesones'),
	('Markus Seehusen Karlsbakk', 'Norway', 'markus seehusen karlsbakk'),
	('Markus Seehusen Karlsbakk', 'Norway', 'karlsbakk'),
	('Aron Timmerman', 'Netherlands', 'timmerman'),
	('Aron Timmerman', 'Netherlands', 'aron timmerman'),
	('Calvin Bombo', 'France', 'bombo'),
	('Calvin Bombo', 'France', 'calvin bombo'),
	('Mihai Cotolan', 'Romania', 'cotolan'),
	('Mihai Cotolan', 'Romania', 'mihai cotolan'),
	('Mihai Popa', 'Romania', 'popa'),
	('Mihai Popa', 'Romania', 'mihai popa'),
	('Nassim Innocenti', 'France', 'innocenti'),
	('Nassim Innocenti', 'France', 'nassim innocenti'),
	('Zain Issaka', 'Japan', 'zain issaka'),
	('Zain Issaka', 'Japan', 'issaka'),
	('Sem Steijn', 'Netherlands', 'sem steijn'),
	('Sem Steijn', 'Netherlands', 'steijn'),
	('Justin Ospelt', 'Liechtenstein', 'justin ospelt'),
	('Justin Ospelt', 'Liechtenstein', 'ospelt'),
	('Aaron O''Driscoll', 'Republic of Ireland', 'odriscoll'),
	('Aaron O''Driscoll', 'Republic of Ireland', 'aaron odriscoll'),
	('Fuad Rahimi', 'Kosovo', 'fuad rahimi'),
	('Fuad Rahimi', 'Kosovo', 'rahimi'),
	('Firas Al Birekan', 'Saudi Arabia', 'birekan'),
	('Firas Al Birekan', 'Saudi Arabia', 'firas al birekan'),
	('Amadou Diallo', 'England', 'diallo'),
	('Amadou Diallo', 'England', 'amadou diallo'),
	('Hussain Al Eissa', 'Saudi Arabia', 'eissa'),
	('Hussain Al Eissa', 'Saudi Arabia', 'hussain al eissa'),
	('Du Changjie', 'China PR', 'changjie'),
	('Du Changjie', 'China PR', 'du changjie'),
	('Dinesh Gillela', 'England', 'gillela'),
	('Dinesh Gillela', 'England', 'dinesh gillela'),
	('Fabio Carvalho', 'England', 'carvalho'),
	('Fabio Carvalho', 'England', 'fabio carvalho'),
	('Jannes Van Hecke', 'Belgium', 'jannes van hecke'),
	('Jannes Van Hecke', 'Belgium', 'hecke'),
	('Timmy Abraham', 'England', 'timmy abraham'),
	('Timmy Abraham', 'England', 'abraham'),
	('Ekin Celebi', 'Germany', 'ekin celebi'),
	('Ekin Celebi', 'Germany', 'celebi'),
	('Rodrigo Menacho', 'Peru', 'rodrigo menacho'),
	('Rodrigo Menacho', 'Peru', 'menacho'),
	('Ricardo Bettocchi', 'Peru', 'bettocchi'),
	('Ricardo Bettocchi', 'Peru', 'ricardo bettocchi'),
	('Max Kulke', 'Germany', 'kulke'),
	('Max Kulke', 'Germany', 'max kulke'),
	('Jens Craenmehr', 'Netherlands', 'jens craenmehr'),
	('Jens Craenmehr', 'Netherlands', 'craenmehr'),
	('Enzo Roldán', 'Argentina', 'roldan'),
	('Enzo Roldán', 'Argentina', 'enzo roldan'),
	('Jorge Cabezudo', 'Peru', 'cabezudo'),
	('Jorge Cabezudo', 'Peru', 'jorge cabezudo'),
	('Paul Komposch', 'Austria', 'paul komposch'),
	('Paul Komposch', 'Austria', 'komposch'),
	('Sofyan Chader', 'France', 'chader'),
	('Sofyan Chader', 'France', 'sofyan chader'),
	('Rob Nizet', 'Belgium', 'nizet'),
	('Rob Nizet', 'Belgium', 'rob nizet'),
	('Francisco Nevarez', 'Mexico', 'francisco nevarez'),
	('Francisco Nevarez', 'Mexico', 'nevarez'),
	('Takumi Nagaishi', 'Japan', 'nagaishi'),
	('Takumi Nagaishi', 'Japan', 'takumi nagaishi'),
	('Christopher McVey', 'Sweden', 'mcvey'),
	('Christopher McVey', 'Sweden', 'christopher mcvey'),
	('Issac Schmidt', 'Switzerland', 'schmidt'),
	('Issac Schmidt', 'Switzerland', 'issac schmidt'),
	('Terrell Egbri', 'England', 'terrell egbri'),
	('Terrell Egbri', 'England', 'egbri'),
	('Noah Smerdon', 'England', 'noah smerdon'),
	('Noah Smerdon', 'England', 'smerdon'),
	('Rasim Bulic', 'Germany', 'rasim bulic'),
	('Rasim Bulic', 'Germany', 'bulic'),
	('Kyle Zobeck', 'United States', 'zobeck'),
	('Kyle Zobeck', 'United States', 'kyle zobeck'),
	('Mathieu Scalet', 'France', 'mathieu scalet'),
	('Mathieu Scalet', 'France', 'scalet'),
	('Agustín Lagos', 'Argentina', 'lagos'),
	('Agustín Lagos', 'Argentina', 'agustin lagos'),
	('Jakub Kałuziński', 'Poland', 'kauzinski'),
	('Jakub Kałuziński', 'Poland', 'jakub kauzinski'),
	('Pedro Sánchez', 'Chile', 'pedro sanchez'),
	('Pedro Sánchez', 'Chile', 'sanchez'),
	('Ramy Najjarine', 'Australia', 'ramy najjarine'),
	('Ramy Najjarine', 'Australia', 'najjarine'),
	('Lee Sang Jun', 'Korea Republic', 'lee sang jun'),
	('Lee Sang Jun', 'Korea Republic', 'jun'),
	('Yao Hanlin', 'China PR', 'hanlin'),
	('Yao Hanlin', 'China PR', 'yao hanlin'),
	('Patryk Plewka', 'Poland', 'plewka'),
	('Patryk Plewka', 'Poland', 'patryk plewka'),
	('David Quintero', 'Colombia', 'david quintero'),
	('David Quintero', 'Colombia', 'quintero'),
	('Sam Woods', 'England', 'sam woods'),
	('Sam Woods', 'England', 'woods'),
	('Kim Ju Sung', 'Korea Republic', 'sung'),
	('Kim Ju Sung', 'Korea Republic', 'kim ju sung'),
	('Lukas Gütlbauer', 'Austria', 'lukas gutlbauer'),
	('Lukas Gütlbauer', 'Austria', 'gutlbauer'),
	('Danny Leyva', 'United States', 'leyva'),
	('Danny Leyva', 'United States', 'danny leyva'),
	('Thomas Heward-Belle', 'Australia', 'hewardbelle'),
	('Thomas Heward-Belle', 'Australia', 'thomas hewardbelle'),
	('Michael O''Connor', 'Republic of Ireland', 'michael oconnor'),
	('Michael O''Connor', 'Republic of Ireland', 'oconnor'),
	('Simon Graves', 'Denmark', 'graves'),
	('Simon Graves', 'Denmark', 'simon graves'),
	('Arne Cassaert', 'Belgium', 'cassaert'),
	('Arne Cassaert', 'Belgium', 'arne cassaert'),
	('Scott Pollock', 'England', 'scott pollock'),
	('Scott Pollock', 'England', 'pollock'),
	('Paolo Izaguirre', 'Peru', 'paolo izaguirre'),
	('Paolo Izaguirre', 'Peru', 'izaguirre'),
	('Park Sang Hyuk', 'Korea Republic', 'park sang hyuk'),
	('Park Sang Hyuk', 'Korea Republic', 'hyuk'),
	('Agustín Manzur', 'Argentina', 'agustin manzur'),
	('Agustín Manzur', 'Argentina', 'manzur'),
	('Tyler Magloire', 'England', 'magloire'),
	('Tyler Magloire', 'England', 'tyler magloire'),
	('Ruslan Neshcheret', 'Ukraine', 'neshcheret'),
	('Ruslan Neshcheret', 'Ukraine', 'ruslan neshcheret'),
	('Ibrahim Karamoko', 'France', 'ibrahim karamoko'),
	('Ibrahim Karamoko', 'France', 'karamoko'),
	('Khaled Al Blooshi', 'United Arab Emirates', 'blooshi'),
	('Khaled Al Blooshi', 'United Arab Emirates', 'khaled al blooshi'),
	('Joshua Kayode', 'Nigeria', 'kayode'),
	('Joshua Kayode', 'Nigeria', 'joshua kayode'),
	('Jordan Adebayo-Smith', 'United States', 'jordan adebayosmith'),
	('Jordan Adebayo-Smith', 'United States', 'adebayosmith'),
	('Thaar Al Otaibi', 'Saudi Arabia', 'thaar al otaibi'),
	('Thaar Al Otaibi', 'Saudi Arabia', 'otaibi'),
	('Ibrahim Meite', 'England', 'meite'),
	('Ibrahim Meite', 'England', 'ibrahim meite'),
	('Gabin Delguel', 'France', 'delguel'),
	('Gabin Delguel', 'France', 'gabin delguel'),
	('Mohsen Abdullah', 'United Arab Emirates', 'abdullah'),
	('Mohsen Abdullah', 'United Arab Emirates', 'mohsen abdullah'),
	('Rodrigo Cerecedo', 'Mexico', 'cerecedo'),
	('Rodrigo Cerecedo', 'Mexico', 'rodrigo cerecedo'),
	('Alistair Smith', 'England', 'smith'),
	('Alistair Smith', 'England', 'alistair smith'),
	('Chris Lema', 'United States', 'lema'),
	('Chris Lema', 'United States', 'chris lema'),
	('Seol Young Woo', 'Korea Republic', 'woo'),
	('Seol Young Woo', 'Korea Republic', 'seol young woo'),
	('Jon Russell', 'England', 'jon russell'),
	('Jon Russell', 'England', 'russell'),
	('Josué Mamani', 'Bolivia', 'mamani'),
	('Josué Mamani', 'Bolivia', 'josue mamani'),
	('Jamie Gullan', 'Scotland', 'gullan'),
	('Jamie Gullan', 'Scotland', 'jamie gullan'),
	('Connor Barrett', 'England', 'connor barrett'),
	('Connor Barrett', 'England', 'barrett'),
	('Hayden Carter', 'England', 'carter'),
	('Hayden Carter', 'England', 'hayden carter'),
	('Ennio van der Gouw', 'Netherlands', 'gouw'),
	('Ennio van der Gouw', 'Netherlands', 'ennio van der gouw'),
	('Chanka Zimba', 'England', 'zimba'),
	('Chanka Zimba', 'England', 'chanka zimba'),
	('Huseyin Biler', 'England', 'huseyin biler'),
	('Huseyin Biler', 'England', 'biler'),
	('Hussein Ali', 'Sweden', 'hussein ali'),
	('Hussein Ali', 'Sweden', 'ali'),
	('Shaun Hobson', 'England', 'hobson'),
	('Shaun Hobson', 'England', 'shaun hobson'),
	('Griffin Dorsey', 'United States', 'dorsey'),
	('Griffin Dorsey', 'United States', 'griffin dorsey'),
	('Alex Hunt', 'England', 'alex hunt'),
	('Alex Hunt', 'England', 'hunt'),
	('Victor Daguin', 'France', 'victor daguin'),
	('Victor Daguin', 'France', 'daguin'),
	('Martin Niøten Palumbo', 'Norway', 'martin niten palumbo'),
	('Martin Niøten Palumbo', 'Norway', 'palumbo'),
	('Tom Knowles', 'England', 'tom knowles'),
	('Tom Knowles', 'England', 'knowles'),
	('Teemu Penninkangas', 'Finland', 'penninkangas'),
	('Teemu Penninkangas', 'Finland', 'teemu penninkangas'),
	('Robbie Cundy', 'England', 'cundy'),
	('Robbie Cundy', 'England', 'robbie cundy'),
	('Fahad Al Rashidi', 'Saudi Arabia', 'fahad al rashidi'),
	('Fahad Al Rashidi', 'Saudi Arabia', 'rashidi'),
	('Geraldo Bajrami', 'Albania', 'geraldo bajrami'),
	('Geraldo Bajrami', 'Albania', 'bajrami'),
	('Karol Stanek', 'Poland', 'stanek'),
	('Karol Stanek', 'Poland', 'karol stanek'),
	('Sidney Obissa', 'Gabon', 'obissa'),
	('Sidney Obissa', 'Gabon', 'sidney obissa'),
	('Baris Ekincier', 'Azerbaijan', 'baris ekincier'),
	('Baris Ekincier', 'Azerbaijan', 'ekincier'),
	('Ignacio Russo', 'Argentina', 'russo'),
	('Ignacio Russo', 'Argentina', 'ignacio russo'),
	('Jaime Moreno', 'Nicaragua', 'moreno'),
	('Jaime Moreno', 'Nicaragua', 'jaime moreno'),
	('Julio Herrera', 'Bolivia', 'julio herrera'),
	('Julio Herrera', 'Bolivia', 'herrera'),
	('Nabili Touaizi', 'Spain', 'touaizi'),
	('Nabili Touaizi', 'Spain', 'nabili touaizi'),
	('Emile Acquah', 'England', 'acquah'),
	('Emile Acquah', 'England', 'emile acquah'),
	('Charlie Jolley', 'England', 'jolley'),
	('Charlie Jolley', 'England', 'charlie jolley'),
	('Daniel Byrne', 'Republic of Ireland', 'daniel byrne'),
	('Daniel Byrne', 'Republic of Ireland', 'byrne'),
	('Anthonys Matos', 'Venezuela', 'anthonys matos'),
	('Anthonys Matos', 'Venezuela', 'matos'),
	('Will Rickard', 'Wales', 'will rickard'),
	('Will Rickard', 'Wales', 'rickard'),
	('Bertie Smith-Hylton', 'Australia', 'bertie smithhylton'),
	('Bertie Smith-Hylton', 'Australia', 'smithhylton'),
	('Alexandru Oroian', 'Romania', 'alexandru oroian'),
	('Alexandru Oroian', 'Romania', 'oroian'),
	('Aboubacar Konté', 'Mali', 'konte'),
	('Aboubacar Konté', 'Mali', 'aboubacar konte'),
	('Tajon Buchanan', 'Canada', 'buchanan'),
	('Tajon Buchanan', 'Canada', 'tajon buchanan'),
	('Birkan Kirdar', 'Australia', 'kirdar'),
	('Birkan Kirdar', 'Australia', 'birkan kirdar'),
	('Andres Dumitrescu', 'Romania', 'andres dumitrescu'),
	('Andres Dumitrescu', 'Romania', 'dumitrescu'),
	('Jack Young', 'England', 'young'),
	('Jack Young', 'England', 'jack young'),
	('Shandon Hopeau', 'United States', 'shandon hopeau'),
	('Shandon Hopeau', 'United States', 'hopeau'),
	('Sam Junqua', 'United States', 'sam junqua'),
	('Sam Junqua', 'United States', 'junqua'),
	('Choi Cheol Won', 'Korea Republic', 'choi cheol won'),
	('Choi Cheol Won', 'Korea Republic', 'won'),
	('Abdulaziz Al Jamaan', 'Saudi Arabia', 'jamaan'),
	('Abdulaziz Al Jamaan', 'Saudi Arabia', 'abdulaziz al jamaan'),
	('Chang Feiya', 'China PR', 'feiya'),
	('Chang Feiya', 'China PR', 'chang feiya'),
	('Divin Baningime', 'DR Congo', 'baningime'),
	('Divin Baningime', 'DR Congo', 'divin baningime'),
	('Obed Nkambadio', 'France', 'nkambadio'),
	('Obed Nkambadio', 'France', 'obed nkambadio'),
	('Gino Infantino', 'Argentina', 'gino infantino'),
	('Gino Infantino', 'Argentina', 'infantino')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';