INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Reo Hatate', 'Japan', 'player'),
	('Amadou Dia', 'United States', 'player'),
	('Mohamed El Makrini', 'Netherlands', 'player'),
	('Joris Correa', 'France', 'player'),
	('Franco Lepore', 'Italy', 'player'),
	('Javi Díaz', 'Spain', 'player'),
	('Milton Álvarez', 'Argentina', 'player'),
	('Nils Miatke', 'Germany', 'player'),
	('Matt Derbyshire', 'England', 'player'),
	('Fejiri Okenabirhie', 'England', 'player'),
	('Frederik Gytkjær', 'Denmark', 'player'),
	('Lee Chang Geun', 'Korea Republic', 'player'),
	('Patryk Sokołowski', 'Poland', 'player'),
	('Marc Lais', 'Germany', 'player'),
	('Marcel Titsch Rivero', 'Germany', 'player'),
	('Fausto Montero', 'Argentina', 'player'),
	('Giovanni Di Noia', 'Italy', 'player'),
	('Gilli Rólantsson', 'Faroe Islands', 'player'),
	('Kevin Kabran', 'Sweden', 'player'),
	('Emmanuel Monthe', 'Cameroon', 'player'),
	('Miroslav Čovilo', 'Bosnia Herzegovina', 'player'),
	('Sebastian Maier', 'Germany', 'player'),
	('Marius Briceag', 'Romania', 'player'),
	('Graham Burke', 'Republic of Ireland', 'player'),
	('Djavan Anderson', 'Netherlands', 'player'),
	('Simone Pinna', 'Italy', 'player'),
	('Giancarlo Carmona', 'Peru', 'player'),
	('Charlie Colkett', 'England', 'player'),
	('Nikolai Topor-Stanley', 'Australia', 'player'),
	('Ricardo Pedriel', 'Bolivia', 'player'),
	('Francisco Pol Hurtado', 'Venezuela', 'player'),
	('Mushaga Bakenga', 'Norway', 'player'),
	('Stephen Dooley', 'Northern Ireland', 'player'),
	('Matěj Kovář', 'Czech Republic', 'player'),
	('Ryan Broom', 'Wales', 'player'),
	('Liam Smith', 'Scotland', 'player'),
	('Sam Long', 'England', 'player'),
	('Richard Blanco', 'Venezuela', 'player'),
	('Tommy McNamara', 'United States', 'player'),
	('Luca de la Torre', 'United States', 'player'),
	('Wilhelm Vorsager', 'Austria', 'player'),
	('Emmanuel Agbadou', 'Ivory Coast', 'player'),
	('Redouane Kerrouche', 'France', 'player'),
	('Wes Burns', 'Wales', 'player'),
	('Melvin Sitti', 'France', 'player'),
	('Dixon Arroyo', 'Ecuador', 'player'),
	('Rafa Mújica', 'Spain', 'player'),
	('Kasim Rabihic', 'Germany', 'player'),
	('Balakiyem Takougnadi', 'Austria', 'player'),
	('Michał Kopczyński', 'Poland', 'player'),
	('Erdoğan Yeşilyurt', 'Germany', 'player'),
	('Lasse Schlüter', 'Germany', 'player'),
	('Ande Dona Ndoh', 'Cameroon', 'player'),
	('Manfred Gollner', 'Austria', 'player'),
	('Ole Söderberg', 'Sweden', 'player'),
	('Jesús Ruiz', 'Spain', 'player'),
	('Yan Couto', 'Brazil', 'player'),
	('Phillip Tietz', 'Germany', 'player'),
	('Fredrik Nordkvelle', 'Norway', 'player'),
	('Alan Cervantes', 'Mexico', 'player'),
	('Cristian Martínez Borja', 'Colombia', 'player'),
	('Monchu', 'Spain', 'player'),
	('Rolf Daniel Vikstøl', 'Norway', 'player'),
	('Laros Duarte', 'Netherlands', 'player'),
	('Anthony Forde', 'Republic of Ireland', 'player'),
	('Simon Cox', 'Republic of Ireland', 'player'),
	('Ryan Flynn', 'Scotland', 'player'),
	('Aritz Castro', 'Spain', 'player'),
	('Dominik Stroh-Engel', 'Germany', 'player'),
	('Lucas Kruspzky', 'Argentina', 'player'),
	('Hussain Sulaimani', 'Saudi Arabia', 'player'),
	('Mohammed Abusabaan', 'Saudi Arabia', 'player'),
	('Rolf Feltscher', 'Venezuela', 'player'),
	('Fabián Assmann', 'Argentina', 'player'),
	('Alexandre Phliponeau', 'France', 'player'),
	('Alasana Manneh', 'Gambia', 'player'),
	('Adrían Spörle', 'Argentina', 'player'),
	('Alex Sobczyk', 'Austria', 'player'),
	('Eric Björkander', 'Sweden', 'player'),
	('Issa Marega', 'France', 'player'),
	('Manuel Insaurralde', 'Argentina', 'player'),
	('Álvaro Fernández', 'Uruguay', 'player'),
	('Shahryiar Moghanlou', 'Iran', 'player'),
	('Rhys Healey', 'England', 'player'),
	('José Carlos', 'Spain', 'player'),
	('Carlos Montiel', 'Paraguay', 'player'),
	('Bart Straalman', 'Netherlands', 'player'),
	('Luis Pedro Figueroa', 'Chile', 'player'),
	('Leonel González', 'Argentina', 'player'),
	('Togo Umeda', 'Japan', 'player'),
	('Brian Rubio', 'Mexico', 'player'),
	('Luke Southwood', 'England', 'player'),
	('Jeppe Okkels', 'Denmark', 'player'),
	('Abdoul Ba', 'Mauritania', 'player'),
	('Saeed Juma', 'United Arab Emirates', 'player'),
	('Kelvin Ofori', 'Ghana', 'player'),
	('Teddy Akumu Agay', 'Kenya', 'player'),
	('Edemir Rodríguez', 'Bolivia', 'player'),
	('Callum Reilly', 'Republic of Ireland', 'player'),
	('Liu Junshuai', 'China PR', 'player'),
	('Franco Torgnascioli', 'Uruguay', 'player'),
	('Osame Sahraoui', 'Norway', 'player'),
	('Mehdi Léris', 'France', 'player'),
	('Daniel Mesenhöler', 'Germany', 'player'),
	('Agustín Sienra', 'Argentina', 'player'),
	('Abdel Medioub', 'France', 'player'),
	('Abdulrahman Al Ghamdi', 'Saudi Arabia', 'player'),
	('Jack Walton', 'England', 'player'),
	('Harry McKirdy', 'England', 'player'),
	('Mücahit Albayrak', 'Turkey', 'player'),
	('Thomas Gebauer', 'Austria', 'player'),
	('Haissem Hassan', 'France', 'player'),
	('Farrend Rawson', 'England', 'player'),
	('Agus Medina', 'Spain', 'player'),
	('Maduka Okoye', 'Nigeria', 'player'),
	('Mikkel Maigaard', 'Denmark', 'player'),
	('Joaquín Ardaiz', 'Uruguay', 'player'),
	('Hamza Saghiri', 'Germany', 'player'),
	('Masahiko Inoha', 'Japan', 'player'),
	('Julian Wießmeier', 'Germany', 'player'),
	('Deng Xiaofei', 'China PR', 'player'),
	('Lee Min Gi', 'Korea Republic', 'player'),
	('Óscar Salomón', 'Argentina', 'player'),
	('Fraser Hornby', 'Scotland', 'player'),
	('Gustavo Giménez', 'Paraguay', 'player'),
	('Nicolás Eduardo Castro', 'Argentina', 'player'),
	('Matías Alonso', 'Uruguay', 'player'),
	('Israel Rivera', 'Mexico', 'player'),
	('Viktor Lundberg', 'Sweden', 'player'),
	('Martin Polaček', 'Slovakia', 'player'),
	('Michele Troiani', 'Italy', 'player'),
	('Frankie Amaya', 'United States', 'player'),
	('Pablo Moreno', 'Spain', 'player'),
	('Dominik Schmidt', 'Germany', 'player'),
	('Ben Stevenson', 'England', 'player'),
	('Constantin Reiner', 'Austria', 'player'),
	('Jakub Szmatuła', 'Poland', 'player'),
	('Marco Prieto', 'Paraguay', 'player'),
	('Edis Ibargüen', 'Colombia', 'player'),
	('Michael Blauensteiner', 'Austria', 'player'),
	('Franco Boló', 'Argentina', 'player'),
	('Maurice Litka', 'Germany', 'player'),
	('Jorge Fernández', 'Spain', 'player'),
	('Joe Ward', 'England', 'player'),
	('Kevin Tapoko', 'France', 'player'),
	('Moses Mawa', 'Norway', 'player'),
	('Luis Felipe', 'United States', 'player'),
	('Daniel Lafferty', 'Northern Ireland', 'player'),
	('DeJuan Jones', 'United States', 'player'),
	('Marc Castells', 'Spain', 'player'),
	('Mohammed Al Sahlawi', 'Saudi Arabia', 'player'),
	('Timmy Thiele', 'Germany', 'player'),
	('Avdo Spahić', 'Bosnia Herzegovina', 'player'),
	('Franco Sivetti', 'Argentina', 'player'),
	('Yuya Asano', 'Japan', 'player'),
	('Jiang Zhe', 'China PR', 'player'),
	('Kim Sung Ju', 'Korea Republic', 'player'),
	('Allan Cruz', 'Costa Rica', 'player'),
	('Erico', 'Brazil', 'player'),
	('Marcel Hilßner', 'Germany', 'player'),
	('Alexis Doldán', 'Paraguay', 'player'),
	('Yvan Neyou', 'Cameroon', 'player'),
	('Anthony O''Connor', 'Republic of Ireland', 'player'),
	('Jhonny Quiñónez', 'Ecuador', 'player'),
	('Luc Kassi', 'Ivory Coast', 'player'),
	('İsmail Çipe', 'Turkey', 'player'),
	('Pablo Palacios', 'Paraguay', 'player'),
	('Kevin Nisbet', 'Scotland', 'player'),
	('Naoufel Khacef', 'Algeria', 'player'),
	('Jonathan Bond', 'England', 'player'),
	('Josh Mullin', 'Scotland', 'player'),
	('Joe Riley', 'England', 'player'),
	('Quentin Braat', 'France', 'player'),
	('Guillaume Heinry', 'France', 'player'),
	('Rashid Mahazi', 'Australia', 'player'),
	('Jordan Tunnicliffe', 'England', 'player'),
	('Ricardo Grigore', 'Romania', 'player'),
	('Néstor Querol', 'Spain', 'player'),
	('Übeyd Adıyaman', 'Turkey', 'player'),
	('Christoph Halper', 'Austria', 'player'),
	('Liridon Kalludra', 'Sweden', 'player'),
	('Park Han Bin', 'Korea Republic', 'player'),
	('Davy Frick', 'Germany', 'player'),
	('Shandon Baptiste', 'Grenada', 'player'),
	('Chuca', 'Spain', 'player'),
	('Mounaïm El Idrissy', 'France', 'player'),
	('Brian Araújo', 'Portugal', 'player'),
	('Hamad Al Mansour', 'Saudi Arabia', 'player'),
	('Stephen McLaughlin', 'Republic of Ireland', 'player'),
	('Anthony Jackson-Hamel', 'Canada', 'player'),
	('Kim Dae Won', 'Korea Republic', 'player'),
	('Ángel Faría', 'Venezuela', 'player'),
	('Lion Lauberbach', 'Germany', 'player'),
	('Luis Cabral', 'Paraguay', 'player'),
	('Yann Kitala', 'France', 'player'),
	('Kyle McAllister', 'Scotland', 'player'),
	('Shunya Mori', 'Japan', 'player'),
	('Marcel Costly', 'Germany', 'player'),
	('Kenny Rocha Santos', 'Cape Verde', 'player'),
	('Lee Sang Ki', 'Korea Republic', 'player'),
	('Park Tae Min', 'Korea Republic', 'player'),
	('Andrés Mehring', 'Argentina', 'player'),
	('Idrissa Ba', 'France', 'player'),
	('Lukas Jonsson', 'Sweden', 'player'),
	('Duan Liuyu', 'China PR', 'player'),
	('Carl Johansson', 'Sweden', 'player'),
	('Mohamed Taabouni', 'Netherlands', 'player'),
	('Teddy Bishop', 'England', 'player'),
	('Hakim Ouro-Sama', 'Togo', 'player'),
	('Carlos Daniel Hidalgo', 'Colombia', 'player'),
	('Scott Golbourne', 'England', 'player'),
	('Yairo Moreno', 'Colombia', 'player'),
	('Muhannad Asiri', 'Saudi Arabia', 'player'),
	('Elías López', 'Argentina', 'player'),
	('Hakeeb Adelakun', 'England', 'player'),
	('Marcelo Freitas', 'Brazil', 'player'),
	('Ibrahim Sadiq', 'Ghana', 'player'),
	('Emil Ceïde', 'Norway', 'player'),
	('Jeff Hardeveld', 'Netherlands', 'player'),
	('Oscar Noguera', 'Paraguay', 'player'),
	('Sandro Wieser', 'Liechtenstein', 'player'),
	('Andrea Adorante', 'Italy', 'player'),
	('Ryan Hardie', 'Scotland', 'player'),
	('James Efmorfidis', 'Greece', 'player'),
	('Niklas Thor', 'Sweden', 'player'),
	('Edison Vega', 'Ecuador', 'player'),
	('Árpád Tordai', 'Romania', 'player'),
	('Damian Węglarz', 'Poland', 'player'),
	('Robin Šimović', 'Sweden', 'player'),
	('Fabian Piasecki', 'Poland', 'player'),
	('Collado', 'Spain', 'player'),
	('Felix Hörberg', 'Sweden', 'player'),
	('Marcus Godinho', 'Canada', 'player'),
	('Enea Mihaj', 'Albania', 'player'),
	('Flamur Kastrati', 'Kosovo', 'player'),
	('Boné Uaferro', 'Germany', 'player'),
	('Frederik Børsting', 'Denmark', 'player'),
	('Taiga Maekawa', 'Japan', 'player'),
	('Sami Al Khaibari', 'Saudi Arabia', 'player'),
	('Luke Hendrie', 'England', 'player'),
	('Sean Scannell', 'Republic of Ireland', 'player'),
	('Jordan White', 'Scotland', 'player'),
	('Kennedy Igboananike', 'Nigeria', 'player'),
	('Mikael Soisalo', 'Finland', 'player'),
	('Leon Legge', 'England', 'player'),
	('Daiya Maekawa', 'Japan', 'player'),
	('Adrián Bone', 'Ecuador', 'player'),
	('Steven Zellner', 'Germany', 'player'),
	('Oh Se Hun', 'Korea Republic', 'player'),
	('Teun Bijleveld', 'Netherlands', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Reo Hatate', 'Japan', 'hatate'),
	('Reo Hatate', 'Japan', 'reo hatate'),
	('Amadou Dia', 'United States', 'amadou dia'),
	('Amadou Dia', 'United States', 'dia'),
	('Mohamed El Makrini', 'Netherlands', 'makrini'),
	('Mohamed El Makrini', 'Netherlands', 'mohamed el makrini'),
	('Joris Correa', 'France', 'joris correa'),
	('Joris Correa', 'France', 'correa'),
	('Franco Lepore', 'Italy', 'franco lepore'),
	('Franco Lepore', 'Italy', 'lepore'),
	('Javi Díaz', 'Spain', 'javi diaz'),
	('Javi Díaz', 'Spain', 'diaz'),
	('Milton Álvarez', 'Argentina', 'alvarez'),
	('Milton Álvarez', 'Argentina', 'milton alvarez'),
	('Nils Miatke', 'Germany', 'miatke'),
	('Nils Miatke', 'Germany', 'nils miatke'),
	('Matt Derbyshire', 'England', 'derbyshire'),
	('Matt Derbyshire', 'England', 'matt derbyshire'),
	('Fejiri Okenabirhie', 'England', 'fejiri okenabirhie'),
	('Fejiri Okenabirhie', 'England', 'okenabirhie'),
	('Frederik Gytkjær', 'Denmark', 'gytkjr'),
	('Frederik Gytkjær', 'Denmark', 'frederik gytkjr'),
	('Lee Chang Geun', 'Korea Republic', 'lee chang geun'),
	('Lee Chang Geun', 'Korea Republic', 'geun'),
	('Patryk Sokołowski', 'Poland', 'patryk sokoowski'),
	('Patryk Sokołowski', 'Poland', 'sokoowski'),
	('Marc Lais', 'Germany', 'lais'),
	('Marc Lais', 'Germany', 'marc lais'),
	('Marcel Titsch Rivero', 'Germany', 'marcel titsch rivero'),
	('Marcel Titsch Rivero', 'Germany', 'rivero'),
	('Fausto Montero', 'Argentina', 'fausto montero'),
	('Fausto Montero', 'Argentina', 'montero'),
	('Giovanni Di Noia', 'Italy', 'giovanni di noia'),
	('Giovanni Di Noia', 'Italy', 'noia'),
	('Gilli Rólantsson', 'Faroe Islands', 'gilli rolantsson'),
	('Gilli Rólantsson', 'Faroe Islands', 'rolantsson'),
	('Kevin Kabran', 'Sweden', 'kevin kabran'),
	('Kevin Kabran', 'Sweden', 'kabran'),
	('Emmanuel Monthe', 'Cameroon', 'emmanuel monthe'),
	('Emmanuel Monthe', 'Cameroon', 'monthe'),
	('Miroslav Čovilo', 'Bosnia Herzegovina', 'covilo'),
	('Miroslav Čovilo', 'Bosnia Herzegovina', 'miroslav covilo'),
	('Sebastian Maier', 'Germany', 'sebastian maier'),
	('Sebastian Maier', 'Germany', 'maier'),
	('Marius Briceag', 'Romania', 'marius briceag'),
	('Marius Briceag', 'Romania', 'briceag'),
	('Graham Burke', 'Republic of Ireland', 'graham burke'),
	('Graham Burke', 'Republic of Ireland', 'burke'),
	('Djavan Anderson', 'Netherlands', 'anderson'),
	('Djavan Anderson', 'Netherlands', 'djavan anderson'),
	('Simone Pinna', 'Italy', 'pinna'),
	('Simone Pinna', 'Italy', 'simone pinna'),
	('Giancarlo Carmona', 'Peru', 'giancarlo carmona'),
	('Giancarlo Carmona', 'Peru', 'carmona'),
	('Charlie Colkett', 'England', 'charlie colkett'),
	('Charlie Colkett', 'England', 'colkett'),
	('Nikolai Topor-Stanley', 'Australia', 'nikolai toporstanley'),
	('Nikolai Topor-Stanley', 'Australia', 'toporstanley'),
	('Ricardo Pedriel', 'Bolivia', 'ricardo pedriel'),
	('Ricardo Pedriel', 'Bolivia', 'pedriel'),
	('Francisco Pol Hurtado', 'Venezuela', 'hurtado'),
	('Francisco Pol Hurtado', 'Venezuela', 'francisco pol hurtado'),
	('Mushaga Bakenga', 'Norway', 'mushaga bakenga'),
	('Mushaga Bakenga', 'Norway', 'bakenga'),
	('Stephen Dooley', 'Northern Ireland', 'dooley'),
	('Stephen Dooley', 'Northern Ireland', 'stephen dooley'),
	('Matěj Kovář', 'Czech Republic', 'kovar'),
	('Matěj Kovář', 'Czech Republic', 'matej kovar'),
	('Ryan Broom', 'Wales', 'ryan broom'),
	('Ryan Broom', 'Wales', 'broom'),
	('Liam Smith', 'Scotland', 'smith'),
	('Liam Smith', 'Scotland', 'liam smith'),
	('Sam Long', 'England', 'sam long'),
	('Sam Long', 'England', 'long'),
	('Richard Blanco', 'Venezuela', 'blanco'),
	('Richard Blanco', 'Venezuela', 'richard blanco'),
	('Tommy McNamara', 'United States', 'mcnamara'),
	('Tommy McNamara', 'United States', 'tommy mcnamara'),
	('Luca de la Torre', 'United States', 'torre'),
	('Luca de la Torre', 'United States', 'luca de la torre'),
	('Wilhelm Vorsager', 'Austria', 'wilhelm vorsager'),
	('Wilhelm Vorsager', 'Austria', 'vorsager'),
	('Emmanuel Agbadou', 'Ivory Coast', 'emmanuel agbadou'),
	('Emmanuel Agbadou', 'Ivory Coast', 'agbadou'),
	('Redouane Kerrouche', 'France', 'kerrouche'),
	('Redouane Kerrouche', 'France', 'redouane kerrouche'),
	('Wes Burns', 'Wales', 'burns'),
	('Wes Burns', 'Wales', 'wes burns'),
	('Melvin Sitti', 'France', 'sitti'),
	('Melvin Sitti', 'France', 'melvin sitti'),
	('Dixon Arroyo', 'Ecuador', 'dixon arroyo'),
	('Dixon Arroyo', 'Ecuador', 'arroyo'),
	('Rafa Mújica', 'Spain', 'rafa mujica'),
	('Rafa Mújica', 'Spain', 'mujica'),
	('Kasim Rabihic', 'Germany', 'rabihic'),
	('Kasim Rabihic', 'Germany', 'kasim rabihic'),
	('Balakiyem Takougnadi', 'Austria', 'takougnadi'),
	('Balakiyem Takougnadi', 'Austria', 'balakiyem takougnadi'),
	('Michał Kopczyński', 'Poland', 'micha kopczynski'),
	('Michał Kopczyński', 'Poland', 'kopczynski'),
	('Erdoğan Yeşilyurt', 'Germany', 'yesilyurt'),
	('Erdoğan Yeşilyurt', 'Germany', 'erdogan yesilyurt'),
	('Lasse Schlüter', 'Germany', 'lasse schluter'),
	('Lasse Schlüter', 'Germany', 'schluter'),
	('Ande Dona Ndoh', 'Cameroon', 'ande dona ndoh'),
	('Ande Dona Ndoh', 'Cameroon', 'ndoh'),
	('Manfred Gollner', 'Austria', 'manfred gollner'),
	('Manfred Gollner', 'Austria', 'gollner'),
	('Ole Söderberg', 'Sweden', 'ole soderberg'),
	('Ole Söderberg', 'Sweden', 'soderberg'),
	('Jesús Ruiz', 'Spain', 'jesus ruiz'),
	('Jesús Ruiz', 'Spain', 'ruiz'),
	('Yan Couto', 'Brazil', 'yan couto'),
	('Yan Couto', 'Brazil', 'couto'),
	('Phillip Tietz', 'Germany', 'phillip tietz'),
	('Phillip Tietz', 'Germany', 'tietz'),
	('Fredrik Nordkvelle', 'Norway', 'nordkvelle'),
	('Fredrik Nordkvelle', 'Norway', 'fredrik nordkvelle'),
	('Alan Cervantes', 'Mexico', 'cervantes'),
	('Alan Cervantes', 'Mexico', 'alan cervantes'),
	('Cristian Martínez Borja', 'Colombia', 'borja'),
	('Cristian Martínez Borja', 'Colombia', 'cristian martinez borja'),
	('Monchu', 'Spain', 'monchu'),
	('Rolf Daniel Vikstøl', 'Norway', 'vikstl'),
	('Rolf Daniel Vikstøl', 'Norway', 'rolf daniel vikstl'),
	('Laros Duarte', 'Netherlands', 'duarte'),
	('Laros Duarte', 'Netherlands', 'laros duarte'),
	('Anthony Forde', 'Republic of Ireland', 'forde'),
	('Anthony Forde', 'Republic of Ireland', 'anthony forde'),
	('Simon Cox', 'Republic of Ireland', 'cox'),
	('Simon Cox', 'Republic of Ireland', 'simon cox'),
	('Ryan Flynn', 'Scotland', 'ryan flynn'),
	('Ryan Flynn', 'Scotland', 'flynn'),
	('Aritz Castro', 'Spain', 'castro'),
	('Aritz Castro', 'Spain', 'aritz castro'),
	('Dominik Stroh-Engel', 'Germany', 'strohengel'),
	('Dominik Stroh-Engel', 'Germany', 'dominik strohengel'),
	('Lucas Kruspzky', 'Argentina', 'lucas kruspzky'),
	('Lucas Kruspzky', 'Argentina', 'kruspzky'),
	('Hussain Sulaimani', 'Saudi Arabia', 'sulaimani'),
	('Hussain Sulaimani', 'Saudi Arabia', 'hussain sulaimani'),
	('Mohammed Abusabaan', 'Saudi Arabia', 'mohammed abusabaan'),
	('Mohammed Abusabaan', 'Saudi Arabia', 'abusabaan'),
	('Rolf Feltscher', 'Venezuela', 'feltscher'),
	('Rolf Feltscher', 'Venezuela', 'rolf feltscher'),
	('Fabián Assmann', 'Argentina', 'fabian assmann'),
	('Fabián Assmann', 'Argentina', 'assmann'),
	('Alexandre Phliponeau', 'France', 'alexandre phliponeau'),
	('Alexandre Phliponeau', 'France', 'phliponeau'),
	('Alasana Manneh', 'Gambia', 'alasana manneh'),
	('Alasana Manneh', 'Gambia', 'manneh'),
	('Adrían Spörle', 'Argentina', 'adrian sporle'),
	('Adrían Spörle', 'Argentina', 'sporle'),
	('Alex Sobczyk', 'Austria', 'alex sobczyk'),
	('Alex Sobczyk', 'Austria', 'sobczyk'),
	('Eric Björkander', 'Sweden', 'bjorkander'),
	('Eric Björkander', 'Sweden', 'eric bjorkander'),
	('Issa Marega', 'France', 'marega'),
	('Issa Marega', 'France', 'issa marega'),
	('Manuel Insaurralde', 'Argentina', 'manuel insaurralde'),
	('Manuel Insaurralde', 'Argentina', 'insaurralde'),
	('Álvaro Fernández', 'Uruguay', 'fernandez'),
	('Álvaro Fernández', 'Uruguay', 'alvaro fernandez'),
	('Shahryiar Moghanlou', 'Iran', 'shahryiar moghanlou'),
	('Shahryiar Moghanlou', 'Iran', 'moghanlou'),
	('Rhys Healey', 'England', 'rhys healey'),
	('Rhys Healey', 'England', 'healey'),
	('José Carlos', 'Spain', 'jose carlos'),
	('José Carlos', 'Spain', 'carlos'),
	('Carlos Montiel', 'Paraguay', 'carlos montiel'),
	('Carlos Montiel', 'Paraguay', 'montiel'),
	('Bart Straalman', 'Netherlands', 'bart straalman'),
	('Bart Straalman', 'Netherlands', 'straalman'),
	('Luis Pedro Figueroa', 'Chile', 'figueroa'),
	('Luis Pedro Figueroa', 'Chile', 'luis pedro figueroa'),
	('Leonel González', 'Argentina', 'leonel gonzalez'),
	('Leonel González', 'Argentina', 'gonzalez'),
	('Togo Umeda', 'Japan', 'togo umeda'),
	('Togo Umeda', 'Japan', 'umeda'),
	('Brian Rubio', 'Mexico', 'rubio'),
	('Brian Rubio', 'Mexico', 'brian rubio'),
	('Luke Southwood', 'England', 'luke southwood'),
	('Luke Southwood', 'England', 'southwood'),
	('Jeppe Okkels', 'Denmark', 'okkels'),
	('Jeppe Okkels', 'Denmark', 'jeppe okkels'),
	('Abdoul Ba', 'Mauritania', 'ba'),
	('Abdoul Ba', 'Mauritania', 'abdoul ba'),
	('Saeed Juma', 'United Arab Emirates', 'saeed juma'),
	('Saeed Juma', 'United Arab Emirates', 'juma'),
	('Kelvin Ofori', 'Ghana', 'ofori'),
	('Kelvin Ofori', 'Ghana', 'kelvin ofori'),
	('Teddy Akumu Agay', 'Kenya', 'agay'),
	('Teddy Akumu Agay', 'Kenya', 'teddy akumu agay'),
	('Edemir Rodríguez', 'Bolivia', 'rodriguez'),
	('Edemir Rodríguez', 'Bolivia', 'edemir rodriguez'),
	('Callum Reilly', 'Republic of Ireland', 'callum reilly'),
	('Callum Reilly', 'Republic of Ireland', 'reilly'),
	('Liu Junshuai', 'China PR', 'junshuai'),
	('Liu Junshuai', 'China PR', 'liu junshuai'),
	('Franco Torgnascioli', 'Uruguay', 'torgnascioli'),
	('Franco Torgnascioli', 'Uruguay', 'franco torgnascioli'),
	('Osame Sahraoui', 'Norway', 'osame sahraoui'),
	('Osame Sahraoui', 'Norway', 'sahraoui'),
	('Mehdi Léris', 'France', 'leris'),
	('Mehdi Léris', 'France', 'mehdi leris'),
	('Daniel Mesenhöler', 'Germany', 'mesenholer'),
	('Daniel Mesenhöler', 'Germany', 'daniel mesenholer'),
	('Agustín Sienra', 'Argentina', 'agustin sienra'),
	('Agustín Sienra', 'Argentina', 'sienra'),
	('Abdel Medioub', 'France', 'abdel medioub'),
	('Abdel Medioub', 'France', 'medioub'),
	('Abdulrahman Al Ghamdi', 'Saudi Arabia', 'abdulrahman al ghamdi'),
	('Abdulrahman Al Ghamdi', 'Saudi Arabia', 'ghamdi'),
	('Jack Walton', 'England', 'walton'),
	('Jack Walton', 'England', 'jack walton'),
	('Harry McKirdy', 'England', 'harry mckirdy'),
	('Harry McKirdy', 'England', 'mckirdy'),
	('Mücahit Albayrak', 'Turkey', 'mucahit albayrak'),
	('Mücahit Albayrak', 'Turkey', 'albayrak'),
	('Thomas Gebauer', 'Austria', 'gebauer'),
	('Thomas Gebauer', 'Austria', 'thomas gebauer'),
	('Haissem Hassan', 'France', 'haissem hassan'),
	('Haissem Hassan', 'France', 'hassan'),
	('Farrend Rawson', 'England', 'farrend rawson'),
	('Farrend Rawson', 'England', 'rawson'),
	('Agus Medina', 'Spain', 'agus medina'),
	('Agus Medina', 'Spain', 'medina'),
	('Maduka Okoye', 'Nigeria', 'maduka okoye'),
	('Maduka Okoye', 'Nigeria', 'okoye'),
	('Mikkel Maigaard', 'Denmark', 'maigaard'),
	('Mikkel Maigaard', 'Denmark', 'mikkel maigaard'),
	('Joaquín Ardaiz', 'Uruguay', 'joaquin ardaiz'),
	('Joaquín Ardaiz', 'Uruguay', 'ardaiz'),
	('Hamza Saghiri', 'Germany', 'hamza saghiri'),
	('Hamza Saghiri', 'Germany', 'saghiri'),
	('Masahiko Inoha', 'Japan', 'masahiko inoha'),
	('Masahiko Inoha', 'Japan', 'inoha'),
	('Julian Wießmeier', 'Germany', 'julian wiemeier'),
	('Julian Wießmeier', 'Germany', 'wiemeier'),
	('Deng Xiaofei', 'China PR', 'xiaofei'),
	('Deng Xiaofei', 'China PR', 'deng xiaofei'),
	('Lee Min Gi', 'Korea Republic', 'lee min gi'),
	('Lee Min Gi', 'Korea Republic', 'gi'),
	('Óscar Salomón', 'Argentina', 'salomon'),
	('Óscar Salomón', 'Argentina', 'oscar salomon'),
	('Fraser Hornby', 'Scotland', 'fraser hornby'),
	('Fraser Hornby', 'Scotland', 'hornby'),
	('Gustavo Giménez', 'Paraguay', 'gimenez'),
	('Gustavo Giménez', 'Paraguay', 'gustavo gimenez'),
	('Nicolás Eduardo Castro', 'Argentina', 'castro'),
	('Nicolás Eduardo Castro', 'Argentina', 'nicolas eduardo castro'),
	('Matías Alonso', 'Uruguay', 'alonso'),
	('Matías Alonso', 'Uruguay', 'matias alonso'),
	('Israel Rivera', 'Mexico', 'israel rivera'),
	('Israel Rivera', 'Mexico', 'rivera'),
	('Viktor Lundberg', 'Sweden', 'viktor lundberg'),
	('Viktor Lundberg', 'Sweden', 'lundberg'),
	('Martin Polaček', 'Slovakia', 'polacek'),
	('Martin Polaček', 'Slovakia', 'martin polacek'),
	('Michele Troiani', 'Italy', 'michele troiani'),
	('Michele Troiani', 'Italy', 'troiani'),
	('Frankie Amaya', 'United States', 'amaya'),
	('Frankie Amaya', 'United States', 'frankie amaya'),
	('Pablo Moreno', 'Spain', 'moreno'),
	('Pablo Moreno', 'Spain', 'pablo moreno'),
	('Dominik Schmidt', 'Germany', 'dominik schmidt'),
	('Dominik Schmidt', 'Germany', 'schmidt'),
	('Ben Stevenson', 'England', 'ben stevenson'),
	('Ben Stevenson', 'England', 'stevenson'),
	('Constantin Reiner', 'Austria', 'constantin reiner'),
	('Constantin Reiner', 'Austria', 'reiner'),
	('Jakub Szmatuła', 'Poland', 'jakub szmatua'),
	('Jakub Szmatuła', 'Poland', 'szmatua'),
	('Marco Prieto', 'Paraguay', 'prieto'),
	('Marco Prieto', 'Paraguay', 'marco prieto'),
	('Edis Ibargüen', 'Colombia', 'ibarguen'),
	('Edis Ibargüen', 'Colombia', 'edis ibarguen'),
	('Michael Blauensteiner', 'Austria', 'michael blauensteiner'),
	('Michael Blauensteiner', 'Austria', 'blauensteiner'),
	('Franco Boló', 'Argentina', 'bolo'),
	('Franco Boló', 'Argentina', 'franco bolo'),
	('Maurice Litka', 'Germany', 'maurice litka'),
	('Maurice Litka', 'Germany', 'litka'),
	('Jorge Fernández', 'Spain', 'jorge fernandez'),
	('Jorge Fernández', 'Spain', 'fernandez'),
	('Joe Ward', 'England', 'ward'),
	('Joe Ward', 'England', 'joe ward'),
	('Kevin Tapoko', 'France', 'tapoko'),
	('Kevin Tapoko', 'France', 'kevin tapoko'),
	('Moses Mawa', 'Norway', 'mawa'),
	('Moses Mawa', 'Norway', 'moses mawa'),
	('Luis Felipe', 'United States', 'luis felipe'),
	('Luis Felipe', 'United States', 'felipe'),
	('Daniel Lafferty', 'Northern Ireland', 'daniel lafferty'),
	('Daniel Lafferty', 'Northern Ireland', 'lafferty'),
	('DeJuan Jones', 'United States', 'jones'),
	('DeJuan Jones', 'United States', 'dejuan jones'),
	('Marc Castells', 'Spain', 'marc castells'),
	('Marc Castells', 'Spain', 'castells'),
	('Mohammed Al Sahlawi', 'Saudi Arabia', 'sahlawi'),
	('Mohammed Al Sahlawi', 'Saudi Arabia', 'mohammed al sahlawi'),
	('Timmy Thiele', 'Germany', 'timmy thiele'),
	('Timmy Thiele', 'Germany', 'thiele'),
	('Avdo Spahić', 'Bosnia Herzegovina', 'avdo spahic'),
	('Avdo Spahić', 'Bosnia Herzegovina', 'spahic'),
	('Franco Sivetti', 'Argentina', 'franco sivetti'),
	('Franco Sivetti', 'Argentina', 'sivetti'),
	('Yuya Asano', 'Japan', 'yuya asano'),
	('Yuya Asano', 'Japan', 'asano'),
	('Jiang Zhe', 'China PR', 'zhe'),
	('Jiang Zhe', 'China PR', 'jiang zhe'),
	('Kim Sung Ju', 'Korea Republic', 'kim sung ju'),
	('Kim Sung Ju', 'Korea Republic', 'ju'),
	('Allan Cruz', 'Costa Rica', 'allan cruz'),
	('Allan Cruz', 'Costa Rica', 'cruz'),
	('Erico', 'Brazil', 'erico'),
	('Marcel Hilßner', 'Germany', 'marcel hilner'),
	('Marcel Hilßner', 'Germany', 'hilner'),
	('Alexis Doldán', 'Paraguay', 'doldan'),
	('Alexis Doldán', 'Paraguay', 'alexis doldan'),
	('Yvan Neyou', 'Cameroon', 'yvan neyou'),
	('Yvan Neyou', 'Cameroon', 'neyou'),
	('Anthony O''Connor', 'Republic of Ireland', 'anthony oconnor'),
	('Anthony O''Connor', 'Republic of Ireland', 'oconnor'),
	('Jhonny Quiñónez', 'Ecuador', 'jhonny quinonez'),
	('Jhonny Quiñónez', 'Ecuador', 'quinonez'),
	('Luc Kassi', 'Ivory Coast', 'luc kassi'),
	('Luc Kassi', 'Ivory Coast', 'kassi'),
	('İsmail Çipe', 'Turkey', 'ismail cipe'),
	('İsmail Çipe', 'Turkey', 'cipe'),
	('Pablo Palacios', 'Paraguay', 'pablo palacios'),
	('Pablo Palacios', 'Paraguay', 'palacios'),
	('Kevin Nisbet', 'Scotland', 'kevin nisbet'),
	('Kevin Nisbet', 'Scotland', 'nisbet'),
	('Naoufel Khacef', 'Algeria', 'naoufel khacef'),
	('Naoufel Khacef', 'Algeria', 'khacef'),
	('Jonathan Bond', 'England', 'jonathan bond'),
	('Jonathan Bond', 'England', 'bond'),
	('Josh Mullin', 'Scotland', 'mullin'),
	('Josh Mullin', 'Scotland', 'josh mullin'),
	('Joe Riley', 'England', 'riley'),
	('Joe Riley', 'England', 'joe riley'),
	('Quentin Braat', 'France', 'quentin braat'),
	('Quentin Braat', 'France', 'braat'),
	('Guillaume Heinry', 'France', 'heinry'),
	('Guillaume Heinry', 'France', 'guillaume heinry'),
	('Rashid Mahazi', 'Australia', 'rashid mahazi'),
	('Rashid Mahazi', 'Australia', 'mahazi'),
	('Jordan Tunnicliffe', 'England', 'tunnicliffe'),
	('Jordan Tunnicliffe', 'England', 'jordan tunnicliffe'),
	('Ricardo Grigore', 'Romania', 'grigore'),
	('Ricardo Grigore', 'Romania', 'ricardo grigore'),
	('Néstor Querol', 'Spain', 'querol'),
	('Néstor Querol', 'Spain', 'nestor querol'),
	('Übeyd Adıyaman', 'Turkey', 'adyaman'),
	('Übeyd Adıyaman', 'Turkey', 'ubeyd adyaman'),
	('Christoph Halper', 'Austria', 'christoph halper'),
	('Christoph Halper', 'Austria', 'halper'),
	('Liridon Kalludra', 'Sweden', 'liridon kalludra'),
	('Liridon Kalludra', 'Sweden', 'kalludra'),
	('Park Han Bin', 'Korea Republic', 'park han bin'),
	('Park Han Bin', 'Korea Republic', 'bin'),
	('Davy Frick', 'Germany', 'frick'),
	('Davy Frick', 'Germany', 'davy frick'),
	('Shandon Baptiste', 'Grenada', 'baptiste'),
	('Shandon Baptiste', 'Grenada', 'shandon baptiste'),
	('Chuca', 'Spain', 'chuca'),
	('Mounaïm El Idrissy', 'France', 'idrissy'),
	('Mounaïm El Idrissy', 'France', 'mounaim el idrissy'),
	('Brian Araújo', 'Portugal', 'brian araujo'),
	('Brian Araújo', 'Portugal', 'araujo'),
	('Hamad Al Mansour', 'Saudi Arabia', 'mansour'),
	('Hamad Al Mansour', 'Saudi Arabia', 'hamad al mansour'),
	('Stephen McLaughlin', 'Republic of Ireland', 'stephen mclaughlin'),
	('Stephen McLaughlin', 'Republic of Ireland', 'mclaughlin'),
	('Anthony Jackson-Hamel', 'Canada', 'anthony jacksonhamel'),
	('Anthony Jackson-Hamel', 'Canada', 'jacksonhamel'),
	('Kim Dae Won', 'Korea Republic', 'kim dae won'),
	('Kim Dae Won', 'Korea Republic', 'won'),
	('Ángel Faría', 'Venezuela', 'faria'),
	('Ángel Faría', 'Venezuela', 'angel faria'),
	('Lion Lauberbach', 'Germany', 'lion lauberbach'),
	('Lion Lauberbach', 'Germany', 'lauberbach'),
	('Luis Cabral', 'Paraguay', 'cabral'),
	('Luis Cabral', 'Paraguay', 'luis cabral'),
	('Yann Kitala', 'France', 'kitala'),
	('Yann Kitala', 'France', 'yann kitala'),
	('Kyle McAllister', 'Scotland', 'mcallister'),
	('Kyle McAllister', 'Scotland', 'kyle mcallister'),
	('Shunya Mori', 'Japan', 'shunya mori'),
	('Shunya Mori', 'Japan', 'mori'),
	('Marcel Costly', 'Germany', 'costly'),
	('Marcel Costly', 'Germany', 'marcel costly'),
	('Kenny Rocha Santos', 'Cape Verde', 'kenny rocha santos'),
	('Kenny Rocha Santos', 'Cape Verde', 'santos'),
	('Lee Sang Ki', 'Korea Republic', 'lee sang ki'),
	('Lee Sang Ki', 'Korea Republic', 'ki'),
	('Park Tae Min', 'Korea Republic', 'min'),
	('Park Tae Min', 'Korea Republic', 'park tae min'),
	('Andrés Mehring', 'Argentina', 'mehring'),
	('Andrés Mehring', 'Argentina', 'andres mehring'),
	('Idrissa Ba', 'France', 'ba'),
	('Idrissa Ba', 'France', 'idrissa ba'),
	('Lukas Jonsson', 'Sweden', 'jonsson'),
	('Lukas Jonsson', 'Sweden', 'lukas jonsson'),
	('Duan Liuyu', 'China PR', 'liuyu'),
	('Duan Liuyu', 'China PR', 'duan liuyu'),
	('Carl Johansson', 'Sweden', 'johansson'),
	('Carl Johansson', 'Sweden', 'carl johansson'),
	('Mohamed Taabouni', 'Netherlands', 'mohamed taabouni'),
	('Mohamed Taabouni', 'Netherlands', 'taabouni'),
	('Teddy Bishop', 'England', 'bishop'),
	('Teddy Bishop', 'England', 'teddy bishop'),
	('Hakim Ouro-Sama', 'Togo', 'hakim ourosama'),
	('Hakim Ouro-Sama', 'Togo', 'ourosama'),
	('Carlos Daniel Hidalgo', 'Colombia', 'carlos daniel hidalgo'),
	('Carlos Daniel Hidalgo', 'Colombia', 'hidalgo'),
	('Scott Golbourne', 'England', 'scott golbourne'),
	('Scott Golbourne', 'England', 'golbourne'),
	('Yairo Moreno', 'Colombia', 'moreno'),
	('Yairo Moreno', 'Colombia', 'yairo moreno'),
	('Muhannad Asiri', 'Saudi Arabia', 'muhannad asiri'),
	('Muhannad Asiri', 'Saudi Arabia', 'asiri'),
	('Elías López', 'Argentina', 'elias lopez'),
	('Elías López', 'Argentina', 'lopez'),
	('Hakeeb Adelakun', 'England', 'hakeeb adelakun'),
	('Hakeeb Adelakun', 'England', 'adelakun'),
	('Marcelo Freitas', 'Brazil', 'marcelo freitas'),
	('Marcelo Freitas', 'Brazil', 'freitas'),
	('Ibrahim Sadiq', 'Ghana', 'sadiq'),
	('Ibrahim Sadiq', 'Ghana', 'ibrahim sadiq'),
	('Emil Ceïde', 'Norway', 'emil ceide'),
	('Emil Ceïde', 'Norway', 'ceide'),
	('Jeff Hardeveld', 'Netherlands', 'jeff hardeveld'),
	('Jeff Hardeveld', 'Netherlands', 'hardeveld'),
	('Oscar Noguera', 'Paraguay', 'oscar noguera'),
	('Oscar Noguera', 'Paraguay', 'noguera'),
	('Sandro Wieser', 'Liechtenstein', 'wieser'),
	('Sandro Wieser', 'Liechtenstein', 'sandro wieser'),
	('Andrea Adorante', 'Italy', 'andrea adorante'),
	('Andrea Adorante', 'Italy', 'adorante'),
	('Ryan Hardie', 'Scotland', 'hardie'),
	('Ryan Hardie', 'Scotland', 'ryan hardie'),
	('James Efmorfidis', 'Greece', 'james efmorfidis'),
	('James Efmorfidis', 'Greece', 'efmorfidis'),
	('Niklas Thor', 'Sweden', 'niklas thor'),
	('Niklas Thor', 'Sweden', 'thor'),
	('Edison Vega', 'Ecuador', 'edison vega'),
	('Edison Vega', 'Ecuador', 'vega'),
	('Árpád Tordai', 'Romania', 'arpad tordai'),
	('Árpád Tordai', 'Romania', 'tordai'),
	('Damian Węglarz', 'Poland', 'damian weglarz'),
	('Damian Węglarz', 'Poland', 'weglarz'),
	('Robin Šimović', 'Sweden', 'robin simovic'),
	('Robin Šimović', 'Sweden', 'simovic'),
	('Fabian Piasecki', 'Poland', 'piasecki'),
	('Fabian Piasecki', 'Poland', 'fabian piasecki'),
	('Collado', 'Spain', 'collado'),
	('Felix Hörberg', 'Sweden', 'horberg'),
	('Felix Hörberg', 'Sweden', 'felix horberg'),
	('Marcus Godinho', 'Canada', 'godinho'),
	('Marcus Godinho', 'Canada', 'marcus godinho'),
	('Enea Mihaj', 'Albania', 'enea mihaj'),
	('Enea Mihaj', 'Albania', 'mihaj'),
	('Flamur Kastrati', 'Kosovo', 'flamur kastrati'),
	('Flamur Kastrati', 'Kosovo', 'kastrati'),
	('Boné Uaferro', 'Germany', 'bone uaferro'),
	('Boné Uaferro', 'Germany', 'uaferro'),
	('Frederik Børsting', 'Denmark', 'frederik brsting'),
	('Frederik Børsting', 'Denmark', 'brsting'),
	('Taiga Maekawa', 'Japan', 'maekawa'),
	('Taiga Maekawa', 'Japan', 'taiga maekawa'),
	('Sami Al Khaibari', 'Saudi Arabia', 'khaibari'),
	('Sami Al Khaibari', 'Saudi Arabia', 'sami al khaibari'),
	('Luke Hendrie', 'England', 'hendrie'),
	('Luke Hendrie', 'England', 'luke hendrie'),
	('Sean Scannell', 'Republic of Ireland', 'sean scannell'),
	('Sean Scannell', 'Republic of Ireland', 'scannell'),
	('Jordan White', 'Scotland', 'white'),
	('Jordan White', 'Scotland', 'jordan white'),
	('Kennedy Igboananike', 'Nigeria', 'igboananike'),
	('Kennedy Igboananike', 'Nigeria', 'kennedy igboananike'),
	('Mikael Soisalo', 'Finland', 'mikael soisalo'),
	('Mikael Soisalo', 'Finland', 'soisalo'),
	('Leon Legge', 'England', 'leon legge'),
	('Leon Legge', 'England', 'legge'),
	('Daiya Maekawa', 'Japan', 'maekawa'),
	('Daiya Maekawa', 'Japan', 'daiya maekawa'),
	('Adrián Bone', 'Ecuador', 'bone'),
	('Adrián Bone', 'Ecuador', 'adrian bone'),
	('Steven Zellner', 'Germany', 'zellner'),
	('Steven Zellner', 'Germany', 'steven zellner'),
	('Oh Se Hun', 'Korea Republic', 'oh se hun'),
	('Oh Se Hun', 'Korea Republic', 'hun'),
	('Teun Bijleveld', 'Netherlands', 'teun bijleveld'),
	('Teun Bijleveld', 'Netherlands', 'bijleveld')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';