INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Argenis Gómez', 'Venezuela', 'player'),
	('Jerome Kiesewetter', 'United States', 'player'),
	('Gaël Ondoua', 'Cameroon', 'player'),
	('Roberto Pirrello', 'Italy', 'player'),
	('Paul McShane', 'Republic of Ireland', 'player'),
	('Marcelo Djaló', 'Guinea Bissau', 'player'),
	('Mārcis Ošs', 'Latvia', 'player'),
	('Aaron Seydel', 'Germany', 'player'),
	('Jonathan Amon', 'United States', 'player'),
	('Petar Mićin', 'Serbia', 'player'),
	('Connor Pain', 'Australia', 'player'),
	('Unai Vencedor', 'Spain', 'player'),
	('Rayan Yaslam', 'United Arab Emirates', 'player'),
	('Niall Mason', 'England', 'player'),
	('Hugo Silveira', 'Uruguay', 'player'),
	('Luca Marseiler', 'Germany', 'player'),
	('Sammy Skytte', 'Denmark', 'player'),
	('Ronald Hernández', 'Venezuela', 'player'),
	('Marcus Holmgren Pedersen', 'Norway', 'player'),
	('Ísak Bergmann Jóhannesson', 'Iceland', 'player'),
	('Stevie May', 'Scotland', 'player'),
	('Roberto Lopes', 'Cape Verde', 'player'),
	('David Babunski', 'North Macedonia', 'player'),
	('Tom McIntyre', 'Scotland', 'player'),
	('Florian Buchacher', 'Austria', 'player'),
	('Assani Lukimya', 'DR Congo', 'player'),
	('Emilio Orrantía', 'Mexico', 'player'),
	('Curtis Thompson', 'England', 'player'),
	('John Chibuike', 'Nigeria', 'player'),
	('Leonardo Villagra', 'Paraguay', 'player'),
	('Zhou Yun', 'China PR', 'player'),
	('Saeid Ezatolahi', 'Iran', 'player'),
	('Arthur Zagré', 'France', 'player'),
	('Abdullah Al Zori', 'Saudi Arabia', 'player'),
	('Wilson Kamavuaka', 'DR Congo', 'player'),
	('Scott Wootton', 'England', 'player'),
	('Tomáš Hájek', 'Czech Republic', 'player'),
	('Hilary Gong', 'Nigeria', 'player'),
	('Juriën Gaari', 'Curacao', 'player'),
	('Ricard', 'Spain', 'player'),
	('Emeric Dudouit', 'France', 'player'),
	('Nicolás Delgadillo', 'Argentina', 'player'),
	('Shuhei Akasaki', 'Japan', 'player'),
	('Thibault Campanini', 'France', 'player'),
	('Karl Larson', 'Sweden', 'player'),
	('Joseph Akomadi', 'Ghana', 'player'),
	('Paul Delecroix', 'France', 'player'),
	('Kelyn Rowe', 'United States', 'player'),
	('Kasper Pedersen', 'Denmark', 'player'),
	('Marko Kolar', 'Croatia', 'player'),
	('Abdoulie Sanyang', 'Gambia', 'player'),
	('Joan Femenías', 'Spain', 'player'),
	('Fabian Kunze', 'Germany', 'player'),
	('Matheus Kayser', 'Brazil', 'player'),
	('Andrés Colorado', 'Colombia', 'player'),
	('Leroy-Jacques Mickels', 'Germany', 'player'),
	('Kilian Ludewig', 'Germany', 'player'),
	('Lars Ritzka', 'Germany', 'player'),
	('Yannis Letard', 'France', 'player'),
	('Cristian Rivas', 'Venezuela', 'player'),
	('Hugo Suárez', 'Bolivia', 'player'),
	('Ryan Tunnicliffe', 'England', 'player'),
	('John Buckley', 'England', 'player'),
	('Mohammed Al Amri', 'Saudi Arabia', 'player'),
	('Cheick Diarra', 'Mali', 'player'),
	('Rodrigo Fernández', 'Uruguay', 'player'),
	('Ryan Jackson', 'England', 'player'),
	('Sebastián Rodríguez', 'Uruguay', 'player'),
	('Maikel Mesa', 'Spain', 'player'),
	('Fawaz Al Sagour', 'Saudi Arabia', 'player'),
	('Rodrigo González', 'Chile', 'player'),
	('Carlos David', 'Spain', 'player'),
	('Danilo Acosta', 'Honduras', 'player'),
	('Stefan Gartenmann', 'Denmark', 'player'),
	('Alejandro Fuenmayor', 'Venezuela', 'player'),
	('Reno Piscopo', 'Australia', 'player'),
	('Jordan Graham', 'England', 'player'),
	('Michael Pinto', 'Luxembourg', 'player'),
	('Conrado', 'Brazil', 'player'),
	('Kevin Holzweiler', 'Germany', 'player'),
	('Marco Bueno', 'Mexico', 'player'),
	('Luis Haquín', 'Bolivia', 'player'),
	('Dominik Plechatý', 'Czech Republic', 'player'),
	('Daisuke Takagi', 'Japan', 'player'),
	('Platini', 'Cape Verde', 'player'),
	('Andorinha', 'Portugal', 'player'),
	('Aapo Halme', 'Finland', 'player'),
	('Rúben Macedo', 'Portugal', 'player'),
	('Leo Väisänen', 'Finland', 'player'),
	('Óscar Vaca', 'Bolivia', 'player'),
	('Patrick Wiegers', 'Germany', 'player'),
	('Johanna Omolo', 'Kenya', 'player'),
	('Yvann Maçon', 'France', 'player'),
	('Carlos Doncel', 'Spain', 'player'),
	('Jô Santos', 'Brazil', 'player'),
	('Miguel Jacquet', 'Paraguay', 'player'),
	('Robert Zwinkels', 'Netherlands', 'player'),
	('Kim Ho Jun', 'Korea Republic', 'player'),
	('Kamaldeen Sulemana', 'Ghana', 'player'),
	('Jeong Jae Hee', 'Korea Republic', 'player'),
	('Stratos Svarnas', 'Greece', 'player'),
	('Hernesto Caballero', 'Paraguay', 'player'),
	('Taijo Teniste', 'Estonia', 'player'),
	('Blas Armoa', 'Paraguay', 'player'),
	('Erik Wekesser', 'Germany', 'player'),
	('Anton Walkes', 'England', 'player'),
	('Luis Donaldo Hernández', 'Mexico', 'player'),
	('Christoph Kobald', 'Austria', 'player'),
	('André Ferreira', 'Portugal', 'player'),
	('Tobias Müller', 'Germany', 'player'),
	('Oliver Batista Meier', 'Germany', 'player'),
	('Abdulelah Al Malki', 'Saudi Arabia', 'player'),
	('Takuto Hayashi', 'Japan', 'player'),
	('Tshegofatso Mabasa', 'South Africa', 'player'),
	('Hwang Seok Ho', 'Korea Republic', 'player'),
	('Nikolai Alho', 'Finland', 'player'),
	('Imad Faraj', 'France', 'player'),
	('Benjamin Goller', 'Germany', 'player'),
	('Malek Chergui', 'France', 'player'),
	('Yannick Mbone', 'Cameroon', 'player'),
	('Peter van Ooijen', 'Netherlands', 'player'),
	('Bongani Sam', 'South Africa', 'player'),
	('Zarraga', 'Spain', 'player'),
	('Pape Djibril Diaw', 'Senegal', 'player'),
	('Böðvar Böðvarsson', 'Iceland', 'player'),
	('Michael Heinloth', 'Germany', 'player'),
	('Aníbal Leguizamón', 'Argentina', 'player'),
	('Cătălin Itu', 'Romania', 'player'),
	('Daniel Wein', 'Germany', 'player'),
	('Paulo Retre', 'Australia', 'player'),
	('Alexandru Buzbuchi', 'Romania', 'player'),
	('Erik Sabo', 'Slovakia', 'player'),
	('Luigi Canotto', 'Italy', 'player'),
	('Kevin Ehlers', 'Germany', 'player'),
	('Jonathan Perlaza', 'Ecuador', 'player'),
	('Eduardo Mancha', 'Brazil', 'player'),
	('Fabrice Olinga', 'Cameroon', 'player'),
	('Kang Sang Woo', 'Korea Republic', 'player'),
	('Louis Reed', 'England', 'player'),
	('Ahmed Asiri', 'Saudi Arabia', 'player'),
	('Mascarenhas', 'Brazil', 'player'),
	('Alexander Stølås', 'Norway', 'player'),
	('Takayoshi Ishihara', 'Japan', 'player'),
	('Sam Hoskins', 'England', 'player'),
	('Pedrão', 'Brazil', 'player'),
	('Derek Cornelius', 'Canada', 'player'),
	('Ryogo Yamasaki', 'Japan', 'player'),
	('Luis Gutiérrez', 'Bolivia', 'player'),
	('Sébastien Cibois', 'France', 'player'),
	('Guus Hupperts', 'Netherlands', 'player'),
	('Edson Montaño', 'Ecuador', 'player'),
	('Lloyd Isgrove', 'Wales', 'player'),
	('Zach Clough', 'England', 'player'),
	('Facundo Cobos', 'Argentina', 'player'),
	('Lucas Akins', 'England', 'player'),
	('Shunya Suganuma', 'Japan', 'player'),
	('Berk Yıldız', 'Turkey', 'player'),
	('Gaspar Servio', 'Argentina', 'player'),
	('Rubén Martínez', 'Spain', 'player'),
	('Eunan O''Kane', 'Republic of Ireland', 'player'),
	('Adam Idah', 'Republic of Ireland', 'player'),
	('Scott McDonald', 'Australia', 'player'),
	('Alin Șeroni', 'Romania', 'player'),
	('David Amoo', 'England', 'player'),
	('Hideto Takahashi', 'Japan', 'player'),
	('Gökhan Gül', 'Germany', 'player'),
	('Atomu Tanaka', 'Japan', 'player'),
	('Thibo Somers', 'Belgium', 'player'),
	('Ayrton Cougo', 'Uruguay', 'player'),
	('Devante Cole', 'England', 'player'),
	('Jon Guthrie', 'England', 'player'),
	('Adam Eriksson', 'Sweden', 'player'),
	('Nikola Mileusnić', 'Australia', 'player'),
	('Gustavo Britos', 'Argentina', 'player'),
	('Ross Sykes', 'England', 'player'),
	('Simon Pontdemé', 'France', 'player'),
	('Loris Néry', 'France', 'player'),
	('Siphosakhe Ntiya-Ntiya', 'South Africa', 'player'),
	('Mateusz Lis', 'Poland', 'player'),
	('Bruno Piñatares', 'Uruguay', 'player'),
	('Karlo Muhar', 'Croatia', 'player'),
	('Jérémy Vachoux', 'France', 'player'),
	('Jørgen Horn', 'Norway', 'player'),
	('Charlie Raglan', 'England', 'player'),
	('Robert Ljubicic', 'Austria', 'player'),
	('Takaaki Shichi', 'Japan', 'player'),
	('Miguel Ángel Benítez', 'Paraguay', 'player'),
	('Ryan Edwards', 'Australia', 'player'),
	('Manuel Kuttin', 'Austria', 'player'),
	('Kristoffer Pallesen', 'Denmark', 'player'),
	('Anthony Barylla', 'Germany', 'player'),
	('Elio Castro', 'Mexico', 'player'),
	('Barış Başdaş', 'Turkey', 'player'),
	('Serge Leuko', 'Cameroon', 'player'),
	('Ollie Clarke', 'England', 'player'),
	('Thomas Castella', 'Switzerland', 'player'),
	('Sam Walker', 'England', 'player'),
	('Will Grigg', 'Northern Ireland', 'player'),
	('Hiroki Iikura', 'Japan', 'player'),
	('Astrit Selmani', 'Sweden', 'player'),
	('Jimmy Maurer', 'United States', 'player'),
	('Greg Docherty', 'Scotland', 'player'),
	('Jafar Arias', 'Curacao', 'player'),
	('Jens Martin Gammelby', 'Denmark', 'player'),
	('Jonathan Bay', 'Argentina', 'player'),
	('Andreas Poulsen', 'Denmark', 'player'),
	('Ylber Ramadani', 'Albania', 'player'),
	('Edson Reséndez', 'Mexico', 'player'),
	('Michael Langer', 'Austria', 'player'),
	('Marcel Hofrath', 'Germany', 'player'),
	('Alan McCormack', 'Republic of Ireland', 'player'),
	('Eryk Williamson', 'United States', 'player'),
	('Simon Kroon', 'Sweden', 'player'),
	('Nedim Bajrami', 'Switzerland', 'player'),
	('Jack Hingert', 'Australia', 'player'),
	('Dominik Ernst', 'Germany', 'player'),
	('Vladan Danilović', 'Bosnia Herzegovina', 'player'),
	('Josepmir Ballón', 'Peru', 'player'),
	('Marco Djuricin', 'Austria', 'player'),
	('Dean Lewington', 'England', 'player'),
	('Qin Sheng', 'China PR', 'player'),
	('Alan Velasco', 'Argentina', 'player'),
	('Christophe Diedhiou', 'Senegal', 'player'),
	('Clément Depres', 'France', 'player'),
	('Liu Yang', 'China PR', 'player'),
	('Maciej Gajos', 'Poland', 'player'),
	('Kevin Álvarez', 'Mexico', 'player'),
	('José María Carrasco', 'Bolivia', 'player'),
	('Jack Baldwin', 'England', 'player'),
	('Lucas Passerini', 'Argentina', 'player'),
	('Théo Defourny', 'Belgium', 'player'),
	('Danijel Petković', 'Montenegro', 'player'),
	('Julian Riedel', 'Germany', 'player'),
	('Bruno Leite', 'Cape Verde', 'player'),
	('Marcel Seegert', 'Germany', 'player'),
	('Bernie Ibini', 'Australia', 'player'),
	('Patrick Drewes', 'Germany', 'player'),
	('Antoine Batisse', 'France', 'player'),
	('Lautaro Morales', 'Argentina', 'player'),
	('Michał Buchalik', 'Poland', 'player'),
	('Haibrany Ruíz Díaz', 'Uruguay', 'player'),
	('Dor Hugi', 'Israel', 'player'),
	('Glenn Morris', 'England', 'player'),
	('Colin Doyle', 'Republic of Ireland', 'player'),
	('Sebastian Jakubiak', 'Germany', 'player'),
	('Franck Elimane Kanouté', 'Senegal', 'player'),
	('Oliver Hein', 'Germany', 'player'),
	('Jayden Stockley', 'England', 'player'),
	('Cosmin Frăsinescu', 'Romania', 'player'),
	('Matías Palacios', 'Argentina', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Argenis Gómez', 'Venezuela', 'argenis gomez'),
	('Argenis Gómez', 'Venezuela', 'gomez'),
	('Jerome Kiesewetter', 'United States', 'jerome kiesewetter'),
	('Jerome Kiesewetter', 'United States', 'kiesewetter'),
	('Gaël Ondoua', 'Cameroon', 'gael ondoua'),
	('Gaël Ondoua', 'Cameroon', 'ondoua'),
	('Roberto Pirrello', 'Italy', 'pirrello'),
	('Roberto Pirrello', 'Italy', 'roberto pirrello'),
	('Paul McShane', 'Republic of Ireland', 'mcshane'),
	('Paul McShane', 'Republic of Ireland', 'paul mcshane'),
	('Marcelo Djaló', 'Guinea Bissau', 'marcelo djalo'),
	('Marcelo Djaló', 'Guinea Bissau', 'djalo'),
	('Mārcis Ošs', 'Latvia', 'marcis oss'),
	('Mārcis Ošs', 'Latvia', 'oss'),
	('Aaron Seydel', 'Germany', 'aaron seydel'),
	('Aaron Seydel', 'Germany', 'seydel'),
	('Jonathan Amon', 'United States', 'jonathan amon'),
	('Jonathan Amon', 'United States', 'amon'),
	('Petar Mićin', 'Serbia', 'petar micin'),
	('Petar Mićin', 'Serbia', 'micin'),
	('Connor Pain', 'Australia', 'pain'),
	('Connor Pain', 'Australia', 'connor pain'),
	('Unai Vencedor', 'Spain', 'unai vencedor'),
	('Unai Vencedor', 'Spain', 'vencedor'),
	('Rayan Yaslam', 'United Arab Emirates', 'rayan yaslam'),
	('Rayan Yaslam', 'United Arab Emirates', 'yaslam'),
	('Niall Mason', 'England', 'mason'),
	('Niall Mason', 'England', 'niall mason'),
	('Hugo Silveira', 'Uruguay', 'hugo silveira'),
	('Hugo Silveira', 'Uruguay', 'silveira'),
	('Luca Marseiler', 'Germany', 'luca marseiler'),
	('Luca Marseiler', 'Germany', 'marseiler'),
	('Sammy Skytte', 'Denmark', 'skytte'),
	('Sammy Skytte', 'Denmark', 'sammy skytte'),
	('Ronald Hernández', 'Venezuela', 'ronald hernandez'),
	('Ronald Hernández', 'Venezuela', 'hernandez'),
	('Marcus Holmgren Pedersen', 'Norway', 'marcus holmgren pedersen'),
	('Marcus Holmgren Pedersen', 'Norway', 'pedersen'),
	('Ísak Bergmann Jóhannesson', 'Iceland', 'isak bergmann johannesson'),
	('Ísak Bergmann Jóhannesson', 'Iceland', 'johannesson'),
	('Stevie May', 'Scotland', 'may'),
	('Stevie May', 'Scotland', 'stevie may'),
	('Roberto Lopes', 'Cape Verde', 'lopes'),
	('Roberto Lopes', 'Cape Verde', 'roberto lopes'),
	('David Babunski', 'North Macedonia', 'babunski'),
	('David Babunski', 'North Macedonia', 'david babunski'),
	('Tom McIntyre', 'Scotland', 'tom mcintyre'),
	('Tom McIntyre', 'Scotland', 'mcintyre'),
	('Florian Buchacher', 'Austria', 'buchacher'),
	('Florian Buchacher', 'Austria', 'florian buchacher'),
	('Assani Lukimya', 'DR Congo', 'lukimya'),
	('Assani Lukimya', 'DR Congo', 'assani lukimya'),
	('Emilio Orrantía', 'Mexico', 'emilio orrantia'),
	('Emilio Orrantía', 'Mexico', 'orrantia'),
	('Curtis Thompson', 'England', 'thompson'),
	('Curtis Thompson', 'England', 'curtis thompson'),
	('John Chibuike', 'Nigeria', 'john chibuike'),
	('John Chibuike', 'Nigeria', 'chibuike'),
	('Leonardo Villagra', 'Paraguay', 'leonardo villagra'),
	('Leonardo Villagra', 'Paraguay', 'villagra'),
	('Zhou Yun', 'China PR', 'zhou yun'),
	('Zhou Yun', 'China PR', 'yun'),
	('Saeid Ezatolahi', 'Iran', 'saeid ezatolahi'),
	('Saeid Ezatolahi', 'Iran', 'ezatolahi'),
	('Arthur Zagré', 'France', 'arthur zagre'),
	('Arthur Zagré', 'France', 'zagre'),
	('Abdullah Al Zori', 'Saudi Arabia', 'abdullah al zori'),
	('Abdullah Al Zori', 'Saudi Arabia', 'zori'),
	('Wilson Kamavuaka', 'DR Congo', 'kamavuaka'),
	('Wilson Kamavuaka', 'DR Congo', 'wilson kamavuaka'),
	('Scott Wootton', 'England', 'scott wootton'),
	('Scott Wootton', 'England', 'wootton'),
	('Tomáš Hájek', 'Czech Republic', 'tomas hajek'),
	('Tomáš Hájek', 'Czech Republic', 'hajek'),
	('Hilary Gong', 'Nigeria', 'hilary gong'),
	('Hilary Gong', 'Nigeria', 'gong'),
	('Juriën Gaari', 'Curacao', 'jurien gaari'),
	('Juriën Gaari', 'Curacao', 'gaari'),
	('Ricard', 'Spain', 'ricard'),
	('Emeric Dudouit', 'France', 'emeric dudouit'),
	('Emeric Dudouit', 'France', 'dudouit'),
	('Nicolás Delgadillo', 'Argentina', 'delgadillo'),
	('Nicolás Delgadillo', 'Argentina', 'nicolas delgadillo'),
	('Shuhei Akasaki', 'Japan', 'shuhei akasaki'),
	('Shuhei Akasaki', 'Japan', 'akasaki'),
	('Thibault Campanini', 'France', 'thibault campanini'),
	('Thibault Campanini', 'France', 'campanini'),
	('Karl Larson', 'Sweden', 'karl larson'),
	('Karl Larson', 'Sweden', 'larson'),
	('Joseph Akomadi', 'Ghana', 'joseph akomadi'),
	('Joseph Akomadi', 'Ghana', 'akomadi'),
	('Paul Delecroix', 'France', 'delecroix'),
	('Paul Delecroix', 'France', 'paul delecroix'),
	('Kelyn Rowe', 'United States', 'rowe'),
	('Kelyn Rowe', 'United States', 'kelyn rowe'),
	('Kasper Pedersen', 'Denmark', 'pedersen'),
	('Kasper Pedersen', 'Denmark', 'kasper pedersen'),
	('Marko Kolar', 'Croatia', 'kolar'),
	('Marko Kolar', 'Croatia', 'marko kolar'),
	('Abdoulie Sanyang', 'Gambia', 'abdoulie sanyang'),
	('Abdoulie Sanyang', 'Gambia', 'sanyang'),
	('Joan Femenías', 'Spain', 'femenias'),
	('Joan Femenías', 'Spain', 'joan femenias'),
	('Fabian Kunze', 'Germany', 'fabian kunze'),
	('Fabian Kunze', 'Germany', 'kunze'),
	('Matheus Kayser', 'Brazil', 'matheus kayser'),
	('Matheus Kayser', 'Brazil', 'kayser'),
	('Andrés Colorado', 'Colombia', 'colorado'),
	('Andrés Colorado', 'Colombia', 'andres colorado'),
	('Leroy-Jacques Mickels', 'Germany', 'leroyjacques mickels'),
	('Leroy-Jacques Mickels', 'Germany', 'mickels'),
	('Kilian Ludewig', 'Germany', 'kilian ludewig'),
	('Kilian Ludewig', 'Germany', 'ludewig'),
	('Lars Ritzka', 'Germany', 'lars ritzka'),
	('Lars Ritzka', 'Germany', 'ritzka'),
	('Yannis Letard', 'France', 'yannis letard'),
	('Yannis Letard', 'France', 'letard'),
	('Cristian Rivas', 'Venezuela', 'rivas'),
	('Cristian Rivas', 'Venezuela', 'cristian rivas'),
	('Hugo Suárez', 'Bolivia', 'suarez'),
	('Hugo Suárez', 'Bolivia', 'hugo suarez'),
	('Ryan Tunnicliffe', 'England', 'tunnicliffe'),
	('Ryan Tunnicliffe', 'England', 'ryan tunnicliffe'),
	('John Buckley', 'England', 'john buckley'),
	('John Buckley', 'England', 'buckley'),
	('Mohammed Al Amri', 'Saudi Arabia', 'amri'),
	('Mohammed Al Amri', 'Saudi Arabia', 'mohammed al amri'),
	('Cheick Diarra', 'Mali', 'cheick diarra'),
	('Cheick Diarra', 'Mali', 'diarra'),
	('Rodrigo Fernández', 'Uruguay', 'fernandez'),
	('Rodrigo Fernández', 'Uruguay', 'rodrigo fernandez'),
	('Ryan Jackson', 'England', 'jackson'),
	('Ryan Jackson', 'England', 'ryan jackson'),
	('Sebastián Rodríguez', 'Uruguay', 'sebastian rodriguez'),
	('Sebastián Rodríguez', 'Uruguay', 'rodriguez'),
	('Maikel Mesa', 'Spain', 'mesa'),
	('Maikel Mesa', 'Spain', 'maikel mesa'),
	('Fawaz Al Sagour', 'Saudi Arabia', 'sagour'),
	('Fawaz Al Sagour', 'Saudi Arabia', 'fawaz al sagour'),
	('Rodrigo González', 'Chile', 'rodrigo gonzalez'),
	('Rodrigo González', 'Chile', 'gonzalez'),
	('Carlos David', 'Spain', 'carlos david'),
	('Carlos David', 'Spain', 'david'),
	('Danilo Acosta', 'Honduras', 'acosta'),
	('Danilo Acosta', 'Honduras', 'danilo acosta'),
	('Stefan Gartenmann', 'Denmark', 'gartenmann'),
	('Stefan Gartenmann', 'Denmark', 'stefan gartenmann'),
	('Alejandro Fuenmayor', 'Venezuela', 'alejandro fuenmayor'),
	('Alejandro Fuenmayor', 'Venezuela', 'fuenmayor'),
	('Reno Piscopo', 'Australia', 'piscopo'),
	('Reno Piscopo', 'Australia', 'reno piscopo'),
	('Jordan Graham', 'England', 'graham'),
	('Jordan Graham', 'England', 'jordan graham'),
	('Michael Pinto', 'Luxembourg', 'michael pinto'),
	('Michael Pinto', 'Luxembourg', 'pinto'),
	('Conrado', 'Brazil', 'conrado'),
	('Kevin Holzweiler', 'Germany', 'holzweiler'),
	('Kevin Holzweiler', 'Germany', 'kevin holzweiler'),
	('Marco Bueno', 'Mexico', 'bueno'),
	('Marco Bueno', 'Mexico', 'marco bueno'),
	('Luis Haquín', 'Bolivia', 'luis haquin'),
	('Luis Haquín', 'Bolivia', 'haquin'),
	('Dominik Plechatý', 'Czech Republic', 'plechaty'),
	('Dominik Plechatý', 'Czech Republic', 'dominik plechaty'),
	('Daisuke Takagi', 'Japan', 'daisuke takagi'),
	('Daisuke Takagi', 'Japan', 'takagi'),
	('Platini', 'Cape Verde', 'platini'),
	('Andorinha', 'Portugal', 'andorinha'),
	('Aapo Halme', 'Finland', 'halme'),
	('Aapo Halme', 'Finland', 'aapo halme'),
	('Rúben Macedo', 'Portugal', 'macedo'),
	('Rúben Macedo', 'Portugal', 'ruben macedo'),
	('Leo Väisänen', 'Finland', 'vaisanen'),
	('Leo Väisänen', 'Finland', 'leo vaisanen'),
	('Óscar Vaca', 'Bolivia', 'oscar vaca'),
	('Óscar Vaca', 'Bolivia', 'vaca'),
	('Patrick Wiegers', 'Germany', 'patrick wiegers'),
	('Patrick Wiegers', 'Germany', 'wiegers'),
	('Johanna Omolo', 'Kenya', 'omolo'),
	('Johanna Omolo', 'Kenya', 'johanna omolo'),
	('Yvann Maçon', 'France', 'macon'),
	('Yvann Maçon', 'France', 'yvann macon'),
	('Carlos Doncel', 'Spain', 'doncel'),
	('Carlos Doncel', 'Spain', 'carlos doncel'),
	('Jô Santos', 'Brazil', 'jo santos'),
	('Jô Santos', 'Brazil', 'santos'),
	('Miguel Jacquet', 'Paraguay', 'jacquet'),
	('Miguel Jacquet', 'Paraguay', 'miguel jacquet'),
	('Robert Zwinkels', 'Netherlands', 'zwinkels'),
	('Robert Zwinkels', 'Netherlands', 'robert zwinkels'),
	('Kim Ho Jun', 'Korea Republic', 'kim ho jun'),
	('Kim Ho Jun', 'Korea Republic', 'jun'),
	('Kamaldeen Sulemana', 'Ghana', 'kamaldeen sulemana'),
	('Kamaldeen Sulemana', 'Ghana', 'sulemana'),
	('Jeong Jae Hee', 'Korea Republic', 'hee'),
	('Jeong Jae Hee', 'Korea Republic', 'jeong jae hee'),
	('Stratos Svarnas', 'Greece', 'svarnas'),
	('Stratos Svarnas', 'Greece', 'stratos svarnas'),
	('Hernesto Caballero', 'Paraguay', 'hernesto caballero'),
	('Hernesto Caballero', 'Paraguay', 'caballero'),
	('Taijo Teniste', 'Estonia', 'taijo teniste'),
	('Taijo Teniste', 'Estonia', 'teniste'),
	('Blas Armoa', 'Paraguay', 'blas armoa'),
	('Blas Armoa', 'Paraguay', 'armoa'),
	('Erik Wekesser', 'Germany', 'wekesser'),
	('Erik Wekesser', 'Germany', 'erik wekesser'),
	('Anton Walkes', 'England', 'walkes'),
	('Anton Walkes', 'England', 'anton walkes'),
	('Luis Donaldo Hernández', 'Mexico', 'luis donaldo hernandez'),
	('Luis Donaldo Hernández', 'Mexico', 'hernandez'),
	('Christoph Kobald', 'Austria', 'kobald'),
	('Christoph Kobald', 'Austria', 'christoph kobald'),
	('André Ferreira', 'Portugal', 'andre ferreira'),
	('André Ferreira', 'Portugal', 'ferreira'),
	('Tobias Müller', 'Germany', 'muller'),
	('Tobias Müller', 'Germany', 'tobias muller'),
	('Oliver Batista Meier', 'Germany', 'oliver batista meier'),
	('Oliver Batista Meier', 'Germany', 'meier'),
	('Abdulelah Al Malki', 'Saudi Arabia', 'malki'),
	('Abdulelah Al Malki', 'Saudi Arabia', 'abdulelah al malki'),
	('Takuto Hayashi', 'Japan', 'takuto hayashi'),
	('Takuto Hayashi', 'Japan', 'hayashi'),
	('Tshegofatso Mabasa', 'South Africa', 'mabasa'),
	('Tshegofatso Mabasa', 'South Africa', 'tshegofatso mabasa'),
	('Hwang Seok Ho', 'Korea Republic', 'ho'),
	('Hwang Seok Ho', 'Korea Republic', 'hwang seok ho'),
	('Nikolai Alho', 'Finland', 'alho'),
	('Nikolai Alho', 'Finland', 'nikolai alho'),
	('Imad Faraj', 'France', 'faraj'),
	('Imad Faraj', 'France', 'imad faraj'),
	('Benjamin Goller', 'Germany', 'goller'),
	('Benjamin Goller', 'Germany', 'benjamin goller'),
	('Malek Chergui', 'France', 'chergui'),
	('Malek Chergui', 'France', 'malek chergui'),
	('Yannick Mbone', 'Cameroon', 'yannick mbone'),
	('Yannick Mbone', 'Cameroon', 'mbone'),
	('Peter van Ooijen', 'Netherlands', 'ooijen'),
	('Peter van Ooijen', 'Netherlands', 'peter van ooijen'),
	('Bongani Sam', 'South Africa', 'sam'),
	('Bongani Sam', 'South Africa', 'bongani sam'),
	('Zarraga', 'Spain', 'zarraga'),
	('Pape Djibril Diaw', 'Senegal', 'diaw'),
	('Pape Djibril Diaw', 'Senegal', 'pape djibril diaw'),
	('Böðvar Böðvarsson', 'Iceland', 'bovarsson'),
	('Böðvar Böðvarsson', 'Iceland', 'bovar bovarsson'),
	('Michael Heinloth', 'Germany', 'michael heinloth'),
	('Michael Heinloth', 'Germany', 'heinloth'),
	('Aníbal Leguizamón', 'Argentina', 'anibal leguizamon'),
	('Aníbal Leguizamón', 'Argentina', 'leguizamon'),
	('Cătălin Itu', 'Romania', 'catalin itu'),
	('Cătălin Itu', 'Romania', 'itu'),
	('Daniel Wein', 'Germany', 'daniel wein'),
	('Daniel Wein', 'Germany', 'wein'),
	('Paulo Retre', 'Australia', 'retre'),
	('Paulo Retre', 'Australia', 'paulo retre'),
	('Alexandru Buzbuchi', 'Romania', 'buzbuchi'),
	('Alexandru Buzbuchi', 'Romania', 'alexandru buzbuchi'),
	('Erik Sabo', 'Slovakia', 'sabo'),
	('Erik Sabo', 'Slovakia', 'erik sabo'),
	('Luigi Canotto', 'Italy', 'canotto'),
	('Luigi Canotto', 'Italy', 'luigi canotto'),
	('Kevin Ehlers', 'Germany', 'kevin ehlers'),
	('Kevin Ehlers', 'Germany', 'ehlers'),
	('Jonathan Perlaza', 'Ecuador', 'perlaza'),
	('Jonathan Perlaza', 'Ecuador', 'jonathan perlaza'),
	('Eduardo Mancha', 'Brazil', 'eduardo mancha'),
	('Eduardo Mancha', 'Brazil', 'mancha'),
	('Fabrice Olinga', 'Cameroon', 'olinga'),
	('Fabrice Olinga', 'Cameroon', 'fabrice olinga'),
	('Kang Sang Woo', 'Korea Republic', 'woo'),
	('Kang Sang Woo', 'Korea Republic', 'kang sang woo'),
	('Louis Reed', 'England', 'louis reed'),
	('Louis Reed', 'England', 'reed'),
	('Ahmed Asiri', 'Saudi Arabia', 'ahmed asiri'),
	('Ahmed Asiri', 'Saudi Arabia', 'asiri'),
	('Mascarenhas', 'Brazil', 'mascarenhas'),
	('Alexander Stølås', 'Norway', 'stlas'),
	('Alexander Stølås', 'Norway', 'alexander stlas'),
	('Takayoshi Ishihara', 'Japan', 'takayoshi ishihara'),
	('Takayoshi Ishihara', 'Japan', 'ishihara'),
	('Sam Hoskins', 'England', 'sam hoskins'),
	('Sam Hoskins', 'England', 'hoskins'),
	('Pedrão', 'Brazil', 'pedrao'),
	('Derek Cornelius', 'Canada', 'cornelius'),
	('Derek Cornelius', 'Canada', 'derek cornelius'),
	('Ryogo Yamasaki', 'Japan', 'yamasaki'),
	('Ryogo Yamasaki', 'Japan', 'ryogo yamasaki'),
	('Luis Gutiérrez', 'Bolivia', 'gutierrez'),
	('Luis Gutiérrez', 'Bolivia', 'luis gutierrez'),
	('Sébastien Cibois', 'France', 'cibois'),
	('Sébastien Cibois', 'France', 'sebastien cibois'),
	('Guus Hupperts', 'Netherlands', 'guus hupperts'),
	('Guus Hupperts', 'Netherlands', 'hupperts'),
	('Edson Montaño', 'Ecuador', 'edson montano'),
	('Edson Montaño', 'Ecuador', 'montano'),
	('Lloyd Isgrove', 'Wales', 'isgrove'),
	('Lloyd Isgrove', 'Wales', 'lloyd isgrove'),
	('Zach Clough', 'England', 'zach clough'),
	('Zach Clough', 'England', 'clough'),
	('Facundo Cobos', 'Argentina', 'cobos'),
	('Facundo Cobos', 'Argentina', 'facundo cobos'),
	('Lucas Akins', 'England', 'akins'),
	('Lucas Akins', 'England', 'lucas akins'),
	('Shunya Suganuma', 'Japan', 'suganuma'),
	('Shunya Suganuma', 'Japan', 'shunya suganuma'),
	('Berk Yıldız', 'Turkey', 'yldz'),
	('Berk Yıldız', 'Turkey', 'berk yldz'),
	('Gaspar Servio', 'Argentina', 'servio'),
	('Gaspar Servio', 'Argentina', 'gaspar servio'),
	('Rubén Martínez', 'Spain', 'ruben martinez'),
	('Rubén Martínez', 'Spain', 'martinez'),
	('Eunan O''Kane', 'Republic of Ireland', 'eunan okane'),
	('Eunan O''Kane', 'Republic of Ireland', 'okane'),
	('Adam Idah', 'Republic of Ireland', 'adam idah'),
	('Adam Idah', 'Republic of Ireland', 'idah'),
	('Scott McDonald', 'Australia', 'mcdonald'),
	('Scott McDonald', 'Australia', 'scott mcdonald'),
	('Alin Șeroni', 'Romania', 'alin seroni'),
	('Alin Șeroni', 'Romania', 'seroni'),
	('David Amoo', 'England', 'amoo'),
	('David Amoo', 'England', 'david amoo'),
	('Hideto Takahashi', 'Japan', 'hideto takahashi'),
	('Hideto Takahashi', 'Japan', 'takahashi'),
	('Gökhan Gül', 'Germany', 'gul'),
	('Gökhan Gül', 'Germany', 'gokhan gul'),
	('Atomu Tanaka', 'Japan', 'atomu tanaka'),
	('Atomu Tanaka', 'Japan', 'tanaka'),
	('Thibo Somers', 'Belgium', 'thibo somers'),
	('Thibo Somers', 'Belgium', 'somers'),
	('Ayrton Cougo', 'Uruguay', 'cougo'),
	('Ayrton Cougo', 'Uruguay', 'ayrton cougo'),
	('Devante Cole', 'England', 'devante cole'),
	('Devante Cole', 'England', 'cole'),
	('Jon Guthrie', 'England', 'guthrie'),
	('Jon Guthrie', 'England', 'jon guthrie'),
	('Adam Eriksson', 'Sweden', 'adam eriksson'),
	('Adam Eriksson', 'Sweden', 'eriksson'),
	('Nikola Mileusnić', 'Australia', 'mileusnic'),
	('Nikola Mileusnić', 'Australia', 'nikola mileusnic'),
	('Gustavo Britos', 'Argentina', 'britos'),
	('Gustavo Britos', 'Argentina', 'gustavo britos'),
	('Ross Sykes', 'England', 'sykes'),
	('Ross Sykes', 'England', 'ross sykes'),
	('Simon Pontdemé', 'France', 'pontdeme'),
	('Simon Pontdemé', 'France', 'simon pontdeme'),
	('Loris Néry', 'France', 'nery'),
	('Loris Néry', 'France', 'loris nery'),
	('Siphosakhe Ntiya-Ntiya', 'South Africa', 'ntiyantiya'),
	('Siphosakhe Ntiya-Ntiya', 'South Africa', 'siphosakhe ntiyantiya'),
	('Mateusz Lis', 'Poland', 'lis'),
	('Mateusz Lis', 'Poland', 'mateusz lis'),
	('Bruno Piñatares', 'Uruguay', 'bruno pinatares'),
	('Bruno Piñatares', 'Uruguay', 'pinatares'),
	('Karlo Muhar', 'Croatia', 'muhar'),
	('Karlo Muhar', 'Croatia', 'karlo muhar'),
	('Jérémy Vachoux', 'France', 'jeremy vachoux'),
	('Jérémy Vachoux', 'France', 'vachoux'),
	('Jørgen Horn', 'Norway', 'horn'),
	('Jørgen Horn', 'Norway', 'jrgen horn'),
	('Charlie Raglan', 'England', 'raglan'),
	('Charlie Raglan', 'England', 'charlie raglan'),
	('Robert Ljubicic', 'Austria', 'ljubicic'),
	('Robert Ljubicic', 'Austria', 'robert ljubicic'),
	('Takaaki Shichi', 'Japan', 'shichi'),
	('Takaaki Shichi', 'Japan', 'takaaki shichi'),
	('Miguel Ángel Benítez', 'Paraguay', 'benitez'),
	('Miguel Ángel Benítez', 'Paraguay', 'miguel angel benitez'),
	('Ryan Edwards', 'Australia', 'ryan edwards'),
	('Ryan Edwards', 'Australia', 'edwards'),
	('Manuel Kuttin', 'Austria', 'manuel kuttin'),
	('Manuel Kuttin', 'Austria', 'kuttin'),
	('Kristoffer Pallesen', 'Denmark', 'kristoffer pallesen'),
	('Kristoffer Pallesen', 'Denmark', 'pallesen'),
	('Anthony Barylla', 'Germany', 'barylla'),
	('Anthony Barylla', 'Germany', 'anthony barylla'),
	('Elio Castro', 'Mexico', 'elio castro'),
	('Elio Castro', 'Mexico', 'castro'),
	('Barış Başdaş', 'Turkey', 'bars basdas'),
	('Barış Başdaş', 'Turkey', 'basdas'),
	('Serge Leuko', 'Cameroon', 'leuko'),
	('Serge Leuko', 'Cameroon', 'serge leuko'),
	('Ollie Clarke', 'England', 'clarke'),
	('Ollie Clarke', 'England', 'ollie clarke'),
	('Thomas Castella', 'Switzerland', 'castella'),
	('Thomas Castella', 'Switzerland', 'thomas castella'),
	('Sam Walker', 'England', 'sam walker'),
	('Sam Walker', 'England', 'walker'),
	('Will Grigg', 'Northern Ireland', 'will grigg'),
	('Will Grigg', 'Northern Ireland', 'grigg'),
	('Hiroki Iikura', 'Japan', 'iikura'),
	('Hiroki Iikura', 'Japan', 'hiroki iikura'),
	('Astrit Selmani', 'Sweden', 'astrit selmani'),
	('Astrit Selmani', 'Sweden', 'selmani'),
	('Jimmy Maurer', 'United States', 'jimmy maurer'),
	('Jimmy Maurer', 'United States', 'maurer'),
	('Greg Docherty', 'Scotland', 'docherty'),
	('Greg Docherty', 'Scotland', 'greg docherty'),
	('Jafar Arias', 'Curacao', 'arias'),
	('Jafar Arias', 'Curacao', 'jafar arias'),
	('Jens Martin Gammelby', 'Denmark', 'jens martin gammelby'),
	('Jens Martin Gammelby', 'Denmark', 'gammelby'),
	('Jonathan Bay', 'Argentina', 'bay'),
	('Jonathan Bay', 'Argentina', 'jonathan bay'),
	('Andreas Poulsen', 'Denmark', 'poulsen'),
	('Andreas Poulsen', 'Denmark', 'andreas poulsen'),
	('Ylber Ramadani', 'Albania', 'ylber ramadani'),
	('Ylber Ramadani', 'Albania', 'ramadani'),
	('Edson Reséndez', 'Mexico', 'edson resendez'),
	('Edson Reséndez', 'Mexico', 'resendez'),
	('Michael Langer', 'Austria', 'langer'),
	('Michael Langer', 'Austria', 'michael langer'),
	('Marcel Hofrath', 'Germany', 'marcel hofrath'),
	('Marcel Hofrath', 'Germany', 'hofrath'),
	('Alan McCormack', 'Republic of Ireland', 'mccormack'),
	('Alan McCormack', 'Republic of Ireland', 'alan mccormack'),
	('Eryk Williamson', 'United States', 'eryk williamson'),
	('Eryk Williamson', 'United States', 'williamson'),
	('Simon Kroon', 'Sweden', 'simon kroon'),
	('Simon Kroon', 'Sweden', 'kroon'),
	('Nedim Bajrami', 'Switzerland', 'nedim bajrami'),
	('Nedim Bajrami', 'Switzerland', 'bajrami'),
	('Jack Hingert', 'Australia', 'hingert'),
	('Jack Hingert', 'Australia', 'jack hingert'),
	('Dominik Ernst', 'Germany', 'ernst'),
	('Dominik Ernst', 'Germany', 'dominik ernst'),
	('Vladan Danilović', 'Bosnia Herzegovina', 'danilovic'),
	('Vladan Danilović', 'Bosnia Herzegovina', 'vladan danilovic'),
	('Josepmir Ballón', 'Peru', 'josepmir ballon'),
	('Josepmir Ballón', 'Peru', 'ballon'),
	('Marco Djuricin', 'Austria', 'djuricin'),
	('Marco Djuricin', 'Austria', 'marco djuricin'),
	('Dean Lewington', 'England', 'lewington'),
	('Dean Lewington', 'England', 'dean lewington'),
	('Qin Sheng', 'China PR', 'sheng'),
	('Qin Sheng', 'China PR', 'qin sheng'),
	('Alan Velasco', 'Argentina', 'velasco'),
	('Alan Velasco', 'Argentina', 'alan velasco'),
	('Christophe Diedhiou', 'Senegal', 'diedhiou'),
	('Christophe Diedhiou', 'Senegal', 'christophe diedhiou'),
	('Clément Depres', 'France', 'clement depres'),
	('Clément Depres', 'France', 'depres'),
	('Liu Yang', 'China PR', 'liu yang'),
	('Liu Yang', 'China PR', 'yang'),
	('Maciej Gajos', 'Poland', 'gajos'),
	('Maciej Gajos', 'Poland', 'maciej gajos'),
	('Kevin Álvarez', 'Mexico', 'alvarez'),
	('Kevin Álvarez', 'Mexico', 'kevin alvarez'),
	('José María Carrasco', 'Bolivia', 'carrasco'),
	('José María Carrasco', 'Bolivia', 'jose maria carrasco'),
	('Jack Baldwin', 'England', 'baldwin'),
	('Jack Baldwin', 'England', 'jack baldwin'),
	('Lucas Passerini', 'Argentina', 'lucas passerini'),
	('Lucas Passerini', 'Argentina', 'passerini'),
	('Théo Defourny', 'Belgium', 'defourny'),
	('Théo Defourny', 'Belgium', 'theo defourny'),
	('Danijel Petković', 'Montenegro', 'petkovic'),
	('Danijel Petković', 'Montenegro', 'danijel petkovic'),
	('Julian Riedel', 'Germany', 'julian riedel'),
	('Julian Riedel', 'Germany', 'riedel'),
	('Bruno Leite', 'Cape Verde', 'bruno leite'),
	('Bruno Leite', 'Cape Verde', 'leite'),
	('Marcel Seegert', 'Germany', 'seegert'),
	('Marcel Seegert', 'Germany', 'marcel seegert'),
	('Bernie Ibini', 'Australia', 'ibini'),
	('Bernie Ibini', 'Australia', 'bernie ibini'),
	('Patrick Drewes', 'Germany', 'patrick drewes'),
	('Patrick Drewes', 'Germany', 'drewes'),
	('Antoine Batisse', 'France', 'batisse'),
	('Antoine Batisse', 'France', 'antoine batisse'),
	('Lautaro Morales', 'Argentina', 'morales'),
	('Lautaro Morales', 'Argentina', 'lautaro morales'),
	('Michał Buchalik', 'Poland', 'micha buchalik'),
	('Michał Buchalik', 'Poland', 'buchalik'),
	('Haibrany Ruíz Díaz', 'Uruguay', 'haibrany ruiz diaz'),
	('Haibrany Ruíz Díaz', 'Uruguay', 'diaz'),
	('Dor Hugi', 'Israel', 'dor hugi'),
	('Dor Hugi', 'Israel', 'hugi'),
	('Glenn Morris', 'England', 'morris'),
	('Glenn Morris', 'England', 'glenn morris'),
	('Colin Doyle', 'Republic of Ireland', 'colin doyle'),
	('Colin Doyle', 'Republic of Ireland', 'doyle'),
	('Sebastian Jakubiak', 'Germany', 'jakubiak'),
	('Sebastian Jakubiak', 'Germany', 'sebastian jakubiak'),
	('Franck Elimane Kanouté', 'Senegal', 'kanoute'),
	('Franck Elimane Kanouté', 'Senegal', 'franck elimane kanoute'),
	('Oliver Hein', 'Germany', 'oliver hein'),
	('Oliver Hein', 'Germany', 'hein'),
	('Jayden Stockley', 'England', 'jayden stockley'),
	('Jayden Stockley', 'England', 'stockley'),
	('Cosmin Frăsinescu', 'Romania', 'frasinescu'),
	('Cosmin Frăsinescu', 'Romania', 'cosmin frasinescu'),
	('Matías Palacios', 'Argentina', 'palacios'),
	('Matías Palacios', 'Argentina', 'matias palacios')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';