INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Martin Smith', 'England', 'player'),
	('Wang Guoming', 'China PR', 'player'),
	('Tate Schmitt', 'United States', 'player'),
	('Karl Moore', 'Republic of Ireland', 'player'),
	('Erik Holt', 'United States', 'player'),
	('Kevin Harr', 'Korea Republic', 'player'),
	('Nicolás Sansotre', 'Argentina', 'player'),
	('Daouda Gueye', 'Senegal', 'player'),
	('Keigo Tsunemoto', 'Japan', 'player'),
	('Alex O''Hanlon', 'Republic of Ireland', 'player'),
	('Curtis Anderson', 'England', 'player'),
	('Pacifique Niyongabire', 'Burundi', 'player'),
	('Kristian Arnstad', 'Norway', 'player'),
	('Abdourahmane Barry', 'France', 'player'),
	('Park Jung In', 'Korea Republic', 'player'),
	('Bismar Castro', 'Ecuador', 'player'),
	('Alessandro Kräuchi', 'Switzerland', 'player'),
	('Taras Gomulka', 'Australia', 'player'),
	('Sven Mijnans', 'Netherlands', 'player'),
	('Fernando Cosciuc', 'Argentina', 'player'),
	('Tom Scully', 'England', 'player'),
	('Cristóbal Marín', 'Chile', 'player'),
	('Mikael Tørset Johnsen', 'Norway', 'player'),
	('Ben Lederman', 'United States', 'player'),
	('Darragh Markey', 'Republic of Ireland', 'player'),
	('Sam Sherring', 'England', 'player'),
	('Elias K. Hagen', 'Norway', 'player'),
	('Merveille Papela', 'Germany', 'player'),
	('Ryan Connolly', 'Republic of Ireland', 'player'),
	('Taulant Seferi', 'Albania', 'player'),
	('Andri Fannar Baldursson', 'Iceland', 'player'),
	('Antonio Castillo', 'Chile', 'player'),
	('Benedikt Zahn', 'Germany', 'player'),
	('Taylan Özgün', 'Turkey', 'player'),
	('Daniel Devine', 'England', 'player'),
	('Alejandro Maciel', 'Argentina', 'player'),
	('Stefano Turati', 'Italy', 'player'),
	('Georges Mukumbilwa', 'Canada', 'player'),
	('Andre Reynolds II', 'United States', 'player'),
	('Álvaro Delgado', 'Chile', 'player'),
	('Batuhan Kırdaroğlu', 'Turkey', 'player'),
	('Jamie Barjonas', 'Scotland', 'player'),
	('Morgan Williams', 'England', 'player'),
	('Elias Sierra', 'Belgium', 'player'),
	('Samuel Asoma', 'Belgium', 'player'),
	('Baptiste Roux', 'France', 'player'),
	('Yousef Al Harbi', 'Saudi Arabia', 'player'),
	('Ayman Al Hejaili', 'Saudi Arabia', 'player'),
	('Lars Coveliers', 'Belgium', 'player'),
	('Alex Negrea', 'Romania', 'player'),
	('Aljaž Casar', 'Slovenia', 'player'),
	('Ivan Mihaljević', 'Croatia', 'player'),
	('Abdullah Al Samtai', 'Saudi Arabia', 'player'),
	('Stefano Guidotti', 'Switzerland', 'player'),
	('Adam Roscrow', 'Wales', 'player'),
	('Antonis Aidonis', 'Germany', 'player'),
	('Harry Crookside', 'Australia', 'player'),
	('Jorge Rengifo', 'Colombia', 'player'),
	('Marius Liesegang', 'Germany', 'player'),
	('Nikola Tzanev', 'New Zealand', 'player'),
	('Tomás Durso', 'Argentina', 'player'),
	('Facundo Trinidad', 'Uruguay', 'player'),
	('Stefan Čolović', 'Serbia', 'player'),
	('Ilya Golosov', 'Russia', 'player'),
	('Andrés Catalán', 'Mexico', 'player'),
	('Aleksander Paluszek', 'Poland', 'player'),
	('Yang Shiyuan', 'China PR', 'player'),
	('Lucas Margueron', 'France', 'player'),
	('Ryan Cassidy', 'Republic of Ireland', 'player'),
	('Ricardo García', 'Mexico', 'player'),
	('Tiago Cantoro', 'Argentina', 'player'),
	('Luis Barraza', 'United States', 'player'),
	('Tyreke Wilson', 'Republic of Ireland', 'player'),
	('José Serrano', 'Venezuela', 'player'),
	('Ali Al Salem', 'Saudi Arabia', 'player'),
	('Bradley M''Bondo', 'France', 'player'),
	('Ali Majrashi', 'Saudi Arabia', 'player'),
	('Luis Rangel', 'Venezuela', 'player'),
	('Jan Shcherbakovski', 'Belarus', 'player'),
	('Yasufumi Nishimura', 'Japan', 'player'),
	('Rob Howard', 'England', 'player'),
	('Andreas Hirtlreiter', 'Germany', 'player'),
	('Kaisei Ishii', 'Japan', 'player'),
	('Yasin Dülger', 'Turkey', 'player'),
	('Jakob Münzner', 'Germany', 'player'),
	('David Webster', 'Republic of Ireland', 'player'),
	('Marcos Arturia', 'Argentina', 'player'),
	('Simon Beccari', 'Italy', 'player'),
	('Aimar Sher', 'Sweden', 'player'),
	('Aaron Martin', 'England', 'player'),
	('Kristoffer Askildsen', 'Norway', 'player'),
	('Moritz Jenz', 'Germany', 'player'),
	('Allan Linguet', 'France', 'player'),
	('Lim Eun Soo', 'Korea Republic', 'player'),
	('Kim Min Ho', 'Korea Republic', 'player'),
	('Grégory Coelho', 'France', 'player'),
	('Edison Penilla', 'Venezuela', 'player'),
	('Janis Hanek', 'Germany', 'player'),
	('Ciaran Kilduff', 'Republic of Ireland', 'player'),
	('Aubin Long', 'France', 'player'),
	('Sebastian Müller', 'Germany', 'player'),
	('Mark McGinley', 'Republic of Ireland', 'player'),
	('Kai Lukas Stratznig', 'Austria', 'player'),
	('Luis Rojas', 'Chile', 'player'),
	('Kélian Nsona', 'France', 'player'),
	('Dennis Adeniran', 'England', 'player'),
	('Michael Barker', 'Republic of Ireland', 'player'),
	('Mees Hilgers', 'Netherlands', 'player'),
	('Halldor Stenevik', 'Norway', 'player'),
	('Zak Brunt', 'England', 'player'),
	('Cian Coleman', 'Republic of Ireland', 'player'),
	('Jamie Hamilton', 'Scotland', 'player'),
	('Daniel Klein', 'Germany', 'player'),
	('Saeed Al Dosari', 'Saudi Arabia', 'player'),
	('Alibek Aliev', 'Sweden', 'player'),
	('Philipp Sturm', 'Austria', 'player'),
	('Josh Griffiths', 'England', 'player'),
	('Leomar Mosquera', 'Venezuela', 'player'),
	('Patrick Seagrist', 'United States', 'player'),
	('Danny Musovski', 'United States', 'player'),
	('Jan Ras', 'Netherlands', 'player'),
	('David Gallardo', 'Argentina', 'player'),
	('Juan Cataldi', 'Argentina', 'player'),
	('Nicolas Tié', 'Ivory Coast', 'player'),
	('Godson Kyeremeh', 'France', 'player'),
	('Georgios Vagiannidis', 'Greece', 'player'),
	('Edgar López', 'Mexico', 'player'),
	('Rauf Öktem', 'Turkey', 'player'),
	('Paris Maghoma', 'England', 'player'),
	('Manuel Trías', 'Venezuela', 'player'),
	('Hasan Yurtseven', 'Turkey', 'player'),
	('Billy Koumetio', 'France', 'player'),
	('Eduardo Bravo', 'Mexico', 'player'),
	('Evangelos Patoulidis', 'Belgium', 'player'),
	('José Paradela', 'Argentina', 'player'),
	('Gabriel Șerban', 'Romania', 'player'),
	('Héctor Holguín', 'United States', 'player'),
	('Paul-Philipp Besong', 'Germany', 'player'),
	('Sun Le', 'China PR', 'player'),
	('Aaron Drinan', 'Republic of Ireland', 'player'),
	('Carlos Moreno', 'Mexico', 'player'),
	('Shunta Tanaka', 'Japan', 'player'),
	('Park Soo Il', 'Korea Republic', 'player'),
	('Jonathan Viscosi', 'Canada', 'player'),
	('Kazuya Konno', 'Japan', 'player'),
	('Jaimy Kroesen', 'Netherlands', 'player'),
	('Carlos Canales', 'Peru', 'player'),
	('Nicolás Andereggen', 'Argentina', 'player'),
	('Elias Oubella', 'Germany', 'player'),
	('David Titov', 'Latvia', 'player'),
	('Cheon Seong-Hoon', 'Korea Republic', 'player'),
	('Jefferson Arce', 'Ecuador', 'player'),
	('Mathias Kvistgaarden', 'Denmark', 'player'),
	('Kyle Adams', 'New Zealand', 'player'),
	('Emeka Obi', 'Nigeria', 'player'),
	('Will Dennis', 'England', 'player'),
	('Tim Walbrecht', 'Germany', 'player'),
	('Branco Provoste', 'Chile', 'player'),
	('Lee Ho Seok', 'Korea Republic', 'player'),
	('Tetsushi Yamakawa', 'Japan', 'player'),
	('Ianoș Brînză', 'Moldova', 'player'),
	('Agostino Spina', 'Argentina', 'player'),
	('Yannick Touré', 'Switzerland', 'player'),
	('Bourama Fomba', 'Mali', 'player'),
	('Michael Luyambula', 'DR Congo', 'player'),
	('Álvaro Gracés', 'Uruguay', 'player'),
	('Rafał Strączek', 'Poland', 'player'),
	('Luca Mack', 'Germany', 'player'),
	('Davide Riccardi', 'Italy', 'player'),
	('Robert Dadok', 'Poland', 'player'),
	('Jairo Otero', 'Venezuela', 'player'),
	('Dylan Pierias', 'Australia', 'player'),
	('Álex Vázquez', 'Uruguay', 'player'),
	('Juan García', 'Colombia', 'player'),
	('Leon Müller', 'Germany', 'player'),
	('Ezequiel Escobar', 'Uruguay', 'player'),
	('Sturla Ottesen', 'Norway', 'player'),
	('Carl Klaus', 'Germany', 'player'),
	('Ji Xiaoxuan', 'China PR', 'player'),
	('Mohammed Al Subaie', 'Saudi Arabia', 'player'),
	('Kai Koreniuk', 'United States', 'player'),
	('Marc-Olivier Doué', 'France', 'player'),
	('Dawid Szot', 'Poland', 'player'),
	('Nigel Langras', 'Netherlands', 'player'),
	('Steven Rodríguez', 'Colombia', 'player'),
	('Murat Sevimler', 'Turkey', 'player'),
	('Scott High', 'England', 'player'),
	('Isaak Davies', 'Wales', 'player'),
	('Stephan Mensah', 'Germany', 'player'),
	('Dimitris Serpezis', 'Greece', 'player'),
	('Yassine Benhattab', 'France', 'player'),
	('Mattias Andersson', 'Sweden', 'player'),
	('Alfred Canales', 'Chile', 'player'),
	('Vladimir Nikolov', 'Bulgaria', 'player'),
	('Riyadh Sharahili', 'Saudi Arabia', 'player'),
	('Jonás Romero', 'Argentina', 'player'),
	('Sotiris Alexandropoulos', 'Greece', 'player'),
	('Robert Harker', 'England', 'player'),
	('William Seymore', 'United States', 'player'),
	('Yu In Soo', 'Korea Republic', 'player'),
	('Bali Mumba', 'England', 'player'),
	('Idris El Mizouni', 'Tunisia', 'player'),
	('Ivan Mayta', 'Peru', 'player'),
	('Mathis Picouleau', 'France', 'player'),
	('Jason Law', 'England', 'player'),
	('Paul Justiniano', 'Bolivia', 'player'),
	('Christopher Engelhart', 'Mexico', 'player'),
	('Naif Kariri', 'Saudi Arabia', 'player'),
	('David Min', 'Netherlands', 'player'),
	('Wang Qiuming', 'China PR', 'player'),
	('Tyrese Francois', 'Australia', 'player'),
	('Mateusz Żukowski', 'Poland', 'player'),
	('Jefferson Vernaza', 'Ecuador', 'player'),
	('Arturo Batioja', 'Ecuador', 'player'),
	('Ansou Sow', 'Senegal', 'player'),
	('Sun Guowen', 'China PR', 'player'),
	('Eduard Florescu', 'Romania', 'player'),
	('Jean-Marie Plath', 'Germany', 'player'),
	('Wilfried Bedfian', 'France', 'player'),
	('Brendan Sarpong-Wiredu', 'England', 'player'),
	('Lucas Sanseviero', 'Uruguay', 'player'),
	('Jeon Jong Hyeok', 'Korea Republic', 'player'),
	('Emre Kurt', 'Germany', 'player'),
	('Luke Byrne', 'Republic of Ireland', 'player'),
	('Dean Cornelius', 'Scotland', 'player'),
	('Mediop Ndiaye', 'Senegal', 'player'),
	('Robert Kakeeto', 'Uganda', 'player'),
	('Moon Ji Hwan', 'Korea Republic', 'player'),
	('Hussain Halawani', 'Saudi Arabia', 'player'),
	('Ross Callachan', 'Scotland', 'player'),
	('Adrian Ioniță', 'Romania', 'player'),
	('Cameron Yates', 'Scotland', 'player'),
	('Vintecinco', 'Brazil', 'player'),
	('Dai Wai-Tsun', 'Hong Kong', 'player'),
	('Gordon Wild', 'Germany', 'player'),
	('Yang Shuai', 'China PR', 'player'),
	('Ángel Fraga', 'Spain', 'player'),
	('Isaak Touré', 'France', 'player'),
	('Mansour Jawhar', 'Saudi Arabia', 'player'),
	('Romoney Crichlow', 'England', 'player'),
	('Oskar Nowak', 'Poland', 'player'),
	('Baltazar', 'Brazil', 'player'),
	('Devante Rodney', 'England', 'player'),
	('Dani Vidal', 'Spain', 'player'),
	('Ünal Tosun', 'Germany', 'player'),
	('Mohammad Al Sharimi', 'Saudi Arabia', 'player'),
	('Kakeru Kumagawa', 'Japan', 'player'),
	('Mons Bassouamina', 'France', 'player'),
	('Eric Martel', 'Germany', 'player'),
	('Nezar S''rifi', 'Belgium', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Martin Smith', 'England', 'smith'),
	('Martin Smith', 'England', 'martin smith'),
	('Wang Guoming', 'China PR', 'wang guoming'),
	('Wang Guoming', 'China PR', 'guoming'),
	('Tate Schmitt', 'United States', 'tate schmitt'),
	('Tate Schmitt', 'United States', 'schmitt'),
	('Karl Moore', 'Republic of Ireland', 'karl moore'),
	('Karl Moore', 'Republic of Ireland', 'moore'),
	('Erik Holt', 'United States', 'erik holt'),
	('Erik Holt', 'United States', 'holt'),
	('Kevin Harr', 'Korea Republic', 'kevin harr'),
	('Kevin Harr', 'Korea Republic', 'harr'),
	('Nicolás Sansotre', 'Argentina', 'nicolas sansotre'),
	('Nicolás Sansotre', 'Argentina', 'sansotre'),
	('Daouda Gueye', 'Senegal', 'gueye'),
	('Daouda Gueye', 'Senegal', 'daouda gueye'),
	('Keigo Tsunemoto', 'Japan', 'tsunemoto'),
	('Keigo Tsunemoto', 'Japan', 'keigo tsunemoto'),
	('Alex O''Hanlon', 'Republic of Ireland', 'alex ohanlon'),
	('Alex O''Hanlon', 'Republic of Ireland', 'ohanlon'),
	('Curtis Anderson', 'England', 'curtis anderson'),
	('Curtis Anderson', 'England', 'anderson'),
	('Pacifique Niyongabire', 'Burundi', 'pacifique niyongabire'),
	('Pacifique Niyongabire', 'Burundi', 'niyongabire'),
	('Kristian Arnstad', 'Norway', 'kristian arnstad'),
	('Kristian Arnstad', 'Norway', 'arnstad'),
	('Abdourahmane Barry', 'France', 'barry'),
	('Abdourahmane Barry', 'France', 'abdourahmane barry'),
	('Park Jung In', 'Korea Republic', 'park jung in'),
	('Park Jung In', 'Korea Republic', 'in'),
	('Bismar Castro', 'Ecuador', 'castro'),
	('Bismar Castro', 'Ecuador', 'bismar castro'),
	('Alessandro Kräuchi', 'Switzerland', 'krauchi'),
	('Alessandro Kräuchi', 'Switzerland', 'alessandro krauchi'),
	('Taras Gomulka', 'Australia', 'taras gomulka'),
	('Taras Gomulka', 'Australia', 'gomulka'),
	('Sven Mijnans', 'Netherlands', 'sven mijnans'),
	('Sven Mijnans', 'Netherlands', 'mijnans'),
	('Fernando Cosciuc', 'Argentina', 'cosciuc'),
	('Fernando Cosciuc', 'Argentina', 'fernando cosciuc'),
	('Tom Scully', 'England', 'scully'),
	('Tom Scully', 'England', 'tom scully'),
	('Cristóbal Marín', 'Chile', 'cristobal marin'),
	('Cristóbal Marín', 'Chile', 'marin'),
	('Mikael Tørset Johnsen', 'Norway', 'mikael trset johnsen'),
	('Mikael Tørset Johnsen', 'Norway', 'johnsen'),
	('Ben Lederman', 'United States', 'ben lederman'),
	('Ben Lederman', 'United States', 'lederman'),
	('Darragh Markey', 'Republic of Ireland', 'darragh markey'),
	('Darragh Markey', 'Republic of Ireland', 'markey'),
	('Sam Sherring', 'England', 'sam sherring'),
	('Sam Sherring', 'England', 'sherring'),
	('Elias K. Hagen', 'Norway', 'elias k hagen'),
	('Elias K. Hagen', 'Norway', 'hagen'),
	('Merveille Papela', 'Germany', 'merveille papela'),
	('Merveille Papela', 'Germany', 'papela'),
	('Ryan Connolly', 'Republic of Ireland', 'ryan connolly'),
	('Ryan Connolly', 'Republic of Ireland', 'connolly'),
	('Taulant Seferi', 'Albania', 'taulant seferi'),
	('Taulant Seferi', 'Albania', 'seferi'),
	('Andri Fannar Baldursson', 'Iceland', 'andri fannar baldursson'),
	('Andri Fannar Baldursson', 'Iceland', 'baldursson'),
	('Antonio Castillo', 'Chile', 'antonio castillo'),
	('Antonio Castillo', 'Chile', 'castillo'),
	('Benedikt Zahn', 'Germany', 'benedikt zahn'),
	('Benedikt Zahn', 'Germany', 'zahn'),
	('Taylan Özgün', 'Turkey', 'ozgun'),
	('Taylan Özgün', 'Turkey', 'taylan ozgun'),
	('Daniel Devine', 'England', 'daniel devine'),
	('Daniel Devine', 'England', 'devine'),
	('Alejandro Maciel', 'Argentina', 'alejandro maciel'),
	('Alejandro Maciel', 'Argentina', 'maciel'),
	('Stefano Turati', 'Italy', 'turati'),
	('Stefano Turati', 'Italy', 'stefano turati'),
	('Georges Mukumbilwa', 'Canada', 'mukumbilwa'),
	('Georges Mukumbilwa', 'Canada', 'georges mukumbilwa'),
	('Andre Reynolds II', 'United States', 'ii'),
	('Andre Reynolds II', 'United States', 'andre reynolds ii'),
	('Álvaro Delgado', 'Chile', 'alvaro delgado'),
	('Álvaro Delgado', 'Chile', 'delgado'),
	('Batuhan Kırdaroğlu', 'Turkey', 'krdaroglu'),
	('Batuhan Kırdaroğlu', 'Turkey', 'batuhan krdaroglu'),
	('Jamie Barjonas', 'Scotland', 'jamie barjonas'),
	('Jamie Barjonas', 'Scotland', 'barjonas'),
	('Morgan Williams', 'England', 'morgan williams'),
	('Morgan Williams', 'England', 'williams'),
	('Elias Sierra', 'Belgium', 'elias sierra'),
	('Elias Sierra', 'Belgium', 'sierra'),
	('Samuel Asoma', 'Belgium', 'samuel asoma'),
	('Samuel Asoma', 'Belgium', 'asoma'),
	('Baptiste Roux', 'France', 'baptiste roux'),
	('Baptiste Roux', 'France', 'roux'),
	('Yousef Al Harbi', 'Saudi Arabia', 'yousef al harbi'),
	('Yousef Al Harbi', 'Saudi Arabia', 'harbi'),
	('Ayman Al Hejaili', 'Saudi Arabia', 'hejaili'),
	('Ayman Al Hejaili', 'Saudi Arabia', 'ayman al hejaili'),
	('Lars Coveliers', 'Belgium', 'lars coveliers'),
	('Lars Coveliers', 'Belgium', 'coveliers'),
	('Alex Negrea', 'Romania', 'alex negrea'),
	('Alex Negrea', 'Romania', 'negrea'),
	('Aljaž Casar', 'Slovenia', 'casar'),
	('Aljaž Casar', 'Slovenia', 'aljaz casar'),
	('Ivan Mihaljević', 'Croatia', 'mihaljevic'),
	('Ivan Mihaljević', 'Croatia', 'ivan mihaljevic'),
	('Abdullah Al Samtai', 'Saudi Arabia', 'samtai'),
	('Abdullah Al Samtai', 'Saudi Arabia', 'abdullah al samtai'),
	('Stefano Guidotti', 'Switzerland', 'guidotti'),
	('Stefano Guidotti', 'Switzerland', 'stefano guidotti'),
	('Adam Roscrow', 'Wales', 'adam roscrow'),
	('Adam Roscrow', 'Wales', 'roscrow'),
	('Antonis Aidonis', 'Germany', 'antonis aidonis'),
	('Antonis Aidonis', 'Germany', 'aidonis'),
	('Harry Crookside', 'Australia', 'crookside'),
	('Harry Crookside', 'Australia', 'harry crookside'),
	('Jorge Rengifo', 'Colombia', 'rengifo'),
	('Jorge Rengifo', 'Colombia', 'jorge rengifo'),
	('Marius Liesegang', 'Germany', 'marius liesegang'),
	('Marius Liesegang', 'Germany', 'liesegang'),
	('Nikola Tzanev', 'New Zealand', 'nikola tzanev'),
	('Nikola Tzanev', 'New Zealand', 'tzanev'),
	('Tomás Durso', 'Argentina', 'tomas durso'),
	('Tomás Durso', 'Argentina', 'durso'),
	('Facundo Trinidad', 'Uruguay', 'facundo trinidad'),
	('Facundo Trinidad', 'Uruguay', 'trinidad'),
	('Stefan Čolović', 'Serbia', 'stefan colovic'),
	('Stefan Čolović', 'Serbia', 'colovic'),
	('Ilya Golosov', 'Russia', 'golosov'),
	('Ilya Golosov', 'Russia', 'ilya golosov'),
	('Andrés Catalán', 'Mexico', 'catalan'),
	('Andrés Catalán', 'Mexico', 'andres catalan'),
	('Aleksander Paluszek', 'Poland', 'paluszek'),
	('Aleksander Paluszek', 'Poland', 'aleksander paluszek'),
	('Yang Shiyuan', 'China PR', 'yang shiyuan'),
	('Yang Shiyuan', 'China PR', 'shiyuan'),
	('Lucas Margueron', 'France', 'margueron'),
	('Lucas Margueron', 'France', 'lucas margueron'),
	('Ryan Cassidy', 'Republic of Ireland', 'cassidy'),
	('Ryan Cassidy', 'Republic of Ireland', 'ryan cassidy'),
	('Ricardo García', 'Mexico', 'ricardo garcia'),
	('Ricardo García', 'Mexico', 'garcia'),
	('Tiago Cantoro', 'Argentina', 'cantoro'),
	('Tiago Cantoro', 'Argentina', 'tiago cantoro'),
	('Luis Barraza', 'United States', 'luis barraza'),
	('Luis Barraza', 'United States', 'barraza'),
	('Tyreke Wilson', 'Republic of Ireland', 'wilson'),
	('Tyreke Wilson', 'Republic of Ireland', 'tyreke wilson'),
	('José Serrano', 'Venezuela', 'serrano'),
	('José Serrano', 'Venezuela', 'jose serrano'),
	('Ali Al Salem', 'Saudi Arabia', 'salem'),
	('Ali Al Salem', 'Saudi Arabia', 'ali al salem'),
	('Bradley M''Bondo', 'France', 'mbondo'),
	('Bradley M''Bondo', 'France', 'bradley mbondo'),
	('Ali Majrashi', 'Saudi Arabia', 'ali majrashi'),
	('Ali Majrashi', 'Saudi Arabia', 'majrashi'),
	('Luis Rangel', 'Venezuela', 'rangel'),
	('Luis Rangel', 'Venezuela', 'luis rangel'),
	('Jan Shcherbakovski', 'Belarus', 'jan shcherbakovski'),
	('Jan Shcherbakovski', 'Belarus', 'shcherbakovski'),
	('Yasufumi Nishimura', 'Japan', 'yasufumi nishimura'),
	('Yasufumi Nishimura', 'Japan', 'nishimura'),
	('Rob Howard', 'England', 'howard'),
	('Rob Howard', 'England', 'rob howard'),
	('Andreas Hirtlreiter', 'Germany', 'hirtlreiter'),
	('Andreas Hirtlreiter', 'Germany', 'andreas hirtlreiter'),
	('Kaisei Ishii', 'Japan', 'ishii'),
	('Kaisei Ishii', 'Japan', 'kaisei ishii'),
	('Yasin Dülger', 'Turkey', 'dulger'),
	('Yasin Dülger', 'Turkey', 'yasin dulger'),
	('Jakob Münzner', 'Germany', 'munzner'),
	('Jakob Münzner', 'Germany', 'jakob munzner'),
	('David Webster', 'Republic of Ireland', 'david webster'),
	('David Webster', 'Republic of Ireland', 'webster'),
	('Marcos Arturia', 'Argentina', 'arturia'),
	('Marcos Arturia', 'Argentina', 'marcos arturia'),
	('Simon Beccari', 'Italy', 'beccari'),
	('Simon Beccari', 'Italy', 'simon beccari'),
	('Aimar Sher', 'Sweden', 'aimar sher'),
	('Aimar Sher', 'Sweden', 'sher'),
	('Aaron Martin', 'England', 'aaron martin'),
	('Aaron Martin', 'England', 'martin'),
	('Kristoffer Askildsen', 'Norway', 'askildsen'),
	('Kristoffer Askildsen', 'Norway', 'kristoffer askildsen'),
	('Moritz Jenz', 'Germany', 'moritz jenz'),
	('Moritz Jenz', 'Germany', 'jenz'),
	('Allan Linguet', 'France', 'allan linguet'),
	('Allan Linguet', 'France', 'linguet'),
	('Lim Eun Soo', 'Korea Republic', 'soo'),
	('Lim Eun Soo', 'Korea Republic', 'lim eun soo'),
	('Kim Min Ho', 'Korea Republic', 'ho'),
	('Kim Min Ho', 'Korea Republic', 'kim min ho'),
	('Grégory Coelho', 'France', 'coelho'),
	('Grégory Coelho', 'France', 'gregory coelho'),
	('Edison Penilla', 'Venezuela', 'penilla'),
	('Edison Penilla', 'Venezuela', 'edison penilla'),
	('Janis Hanek', 'Germany', 'janis hanek'),
	('Janis Hanek', 'Germany', 'hanek'),
	('Ciaran Kilduff', 'Republic of Ireland', 'kilduff'),
	('Ciaran Kilduff', 'Republic of Ireland', 'ciaran kilduff'),
	('Aubin Long', 'France', 'long'),
	('Aubin Long', 'France', 'aubin long'),
	('Sebastian Müller', 'Germany', 'muller'),
	('Sebastian Müller', 'Germany', 'sebastian muller'),
	('Mark McGinley', 'Republic of Ireland', 'mark mcginley'),
	('Mark McGinley', 'Republic of Ireland', 'mcginley'),
	('Kai Lukas Stratznig', 'Austria', 'kai lukas stratznig'),
	('Kai Lukas Stratznig', 'Austria', 'stratznig'),
	('Luis Rojas', 'Chile', 'rojas'),
	('Luis Rojas', 'Chile', 'luis rojas'),
	('Kélian Nsona', 'France', 'kelian nsona'),
	('Kélian Nsona', 'France', 'nsona'),
	('Dennis Adeniran', 'England', 'adeniran'),
	('Dennis Adeniran', 'England', 'dennis adeniran'),
	('Michael Barker', 'Republic of Ireland', 'barker'),
	('Michael Barker', 'Republic of Ireland', 'michael barker'),
	('Mees Hilgers', 'Netherlands', 'mees hilgers'),
	('Mees Hilgers', 'Netherlands', 'hilgers'),
	('Halldor Stenevik', 'Norway', 'stenevik'),
	('Halldor Stenevik', 'Norway', 'halldor stenevik'),
	('Zak Brunt', 'England', 'zak brunt'),
	('Zak Brunt', 'England', 'brunt'),
	('Cian Coleman', 'Republic of Ireland', 'cian coleman'),
	('Cian Coleman', 'Republic of Ireland', 'coleman'),
	('Jamie Hamilton', 'Scotland', 'hamilton'),
	('Jamie Hamilton', 'Scotland', 'jamie hamilton'),
	('Daniel Klein', 'Germany', 'daniel klein'),
	('Daniel Klein', 'Germany', 'klein'),
	('Saeed Al Dosari', 'Saudi Arabia', 'dosari'),
	('Saeed Al Dosari', 'Saudi Arabia', 'saeed al dosari'),
	('Alibek Aliev', 'Sweden', 'aliev'),
	('Alibek Aliev', 'Sweden', 'alibek aliev'),
	('Philipp Sturm', 'Austria', 'sturm'),
	('Philipp Sturm', 'Austria', 'philipp sturm'),
	('Josh Griffiths', 'England', 'josh griffiths'),
	('Josh Griffiths', 'England', 'griffiths'),
	('Leomar Mosquera', 'Venezuela', 'mosquera'),
	('Leomar Mosquera', 'Venezuela', 'leomar mosquera'),
	('Patrick Seagrist', 'United States', 'patrick seagrist'),
	('Patrick Seagrist', 'United States', 'seagrist'),
	('Danny Musovski', 'United States', 'musovski'),
	('Danny Musovski', 'United States', 'danny musovski'),
	('Jan Ras', 'Netherlands', 'jan ras'),
	('Jan Ras', 'Netherlands', 'ras'),
	('David Gallardo', 'Argentina', 'david gallardo'),
	('David Gallardo', 'Argentina', 'gallardo'),
	('Juan Cataldi', 'Argentina', 'cataldi'),
	('Juan Cataldi', 'Argentina', 'juan cataldi'),
	('Nicolas Tié', 'Ivory Coast', 'nicolas tie'),
	('Nicolas Tié', 'Ivory Coast', 'tie'),
	('Godson Kyeremeh', 'France', 'godson kyeremeh'),
	('Godson Kyeremeh', 'France', 'kyeremeh'),
	('Georgios Vagiannidis', 'Greece', 'georgios vagiannidis'),
	('Georgios Vagiannidis', 'Greece', 'vagiannidis'),
	('Edgar López', 'Mexico', 'edgar lopez'),
	('Edgar López', 'Mexico', 'lopez'),
	('Rauf Öktem', 'Turkey', 'oktem'),
	('Rauf Öktem', 'Turkey', 'rauf oktem'),
	('Paris Maghoma', 'England', 'paris maghoma'),
	('Paris Maghoma', 'England', 'maghoma'),
	('Manuel Trías', 'Venezuela', 'trias'),
	('Manuel Trías', 'Venezuela', 'manuel trias'),
	('Hasan Yurtseven', 'Turkey', 'yurtseven'),
	('Hasan Yurtseven', 'Turkey', 'hasan yurtseven'),
	('Billy Koumetio', 'France', 'koumetio'),
	('Billy Koumetio', 'France', 'billy koumetio'),
	('Eduardo Bravo', 'Mexico', 'eduardo bravo'),
	('Eduardo Bravo', 'Mexico', 'bravo'),
	('Evangelos Patoulidis', 'Belgium', 'evangelos patoulidis'),
	('Evangelos Patoulidis', 'Belgium', 'patoulidis'),
	('José Paradela', 'Argentina', 'paradela'),
	('José Paradela', 'Argentina', 'jose paradela'),
	('Gabriel Șerban', 'Romania', 'serban'),
	('Gabriel Șerban', 'Romania', 'gabriel serban'),
	('Héctor Holguín', 'United States', 'hector holguin'),
	('Héctor Holguín', 'United States', 'holguin'),
	('Paul-Philipp Besong', 'Germany', 'paulphilipp besong'),
	('Paul-Philipp Besong', 'Germany', 'besong'),
	('Sun Le', 'China PR', 'le'),
	('Sun Le', 'China PR', 'sun le'),
	('Aaron Drinan', 'Republic of Ireland', 'aaron drinan'),
	('Aaron Drinan', 'Republic of Ireland', 'drinan'),
	('Carlos Moreno', 'Mexico', 'moreno'),
	('Carlos Moreno', 'Mexico', 'carlos moreno'),
	('Shunta Tanaka', 'Japan', 'tanaka'),
	('Shunta Tanaka', 'Japan', 'shunta tanaka'),
	('Park Soo Il', 'Korea Republic', 'il'),
	('Park Soo Il', 'Korea Republic', 'park soo il'),
	('Jonathan Viscosi', 'Canada', 'jonathan viscosi'),
	('Jonathan Viscosi', 'Canada', 'viscosi'),
	('Kazuya Konno', 'Japan', 'konno'),
	('Kazuya Konno', 'Japan', 'kazuya konno'),
	('Jaimy Kroesen', 'Netherlands', 'kroesen'),
	('Jaimy Kroesen', 'Netherlands', 'jaimy kroesen'),
	('Carlos Canales', 'Peru', 'canales'),
	('Carlos Canales', 'Peru', 'carlos canales'),
	('Nicolás Andereggen', 'Argentina', 'nicolas andereggen'),
	('Nicolás Andereggen', 'Argentina', 'andereggen'),
	('Elias Oubella', 'Germany', 'elias oubella'),
	('Elias Oubella', 'Germany', 'oubella'),
	('David Titov', 'Latvia', 'titov'),
	('David Titov', 'Latvia', 'david titov'),
	('Cheon Seong-Hoon', 'Korea Republic', 'cheon seonghoon'),
	('Cheon Seong-Hoon', 'Korea Republic', 'seonghoon'),
	('Jefferson Arce', 'Ecuador', 'jefferson arce'),
	('Jefferson Arce', 'Ecuador', 'arce'),
	('Mathias Kvistgaarden', 'Denmark', 'kvistgaarden'),
	('Mathias Kvistgaarden', 'Denmark', 'mathias kvistgaarden'),
	('Kyle Adams', 'New Zealand', 'kyle adams'),
	('Kyle Adams', 'New Zealand', 'adams'),
	('Emeka Obi', 'Nigeria', 'obi'),
	('Emeka Obi', 'Nigeria', 'emeka obi'),
	('Will Dennis', 'England', 'will dennis'),
	('Will Dennis', 'England', 'dennis'),
	('Tim Walbrecht', 'Germany', 'walbrecht'),
	('Tim Walbrecht', 'Germany', 'tim walbrecht'),
	('Branco Provoste', 'Chile', 'branco provoste'),
	('Branco Provoste', 'Chile', 'provoste'),
	('Lee Ho Seok', 'Korea Republic', 'seok'),
	('Lee Ho Seok', 'Korea Republic', 'lee ho seok'),
	('Tetsushi Yamakawa', 'Japan', 'tetsushi yamakawa'),
	('Tetsushi Yamakawa', 'Japan', 'yamakawa'),
	('Ianoș Brînză', 'Moldova', 'ianos brinza'),
	('Ianoș Brînză', 'Moldova', 'brinza'),
	('Agostino Spina', 'Argentina', 'agostino spina'),
	('Agostino Spina', 'Argentina', 'spina'),
	('Yannick Touré', 'Switzerland', 'yannick toure'),
	('Yannick Touré', 'Switzerland', 'toure'),
	('Bourama Fomba', 'Mali', 'fomba'),
	('Bourama Fomba', 'Mali', 'bourama fomba'),
	('Michael Luyambula', 'DR Congo', 'michael luyambula'),
	('Michael Luyambula', 'DR Congo', 'luyambula'),
	('Álvaro Gracés', 'Uruguay', 'alvaro graces'),
	('Álvaro Gracés', 'Uruguay', 'graces'),
	('Rafał Strączek', 'Poland', 'rafa straczek'),
	('Rafał Strączek', 'Poland', 'straczek'),
	('Luca Mack', 'Germany', 'luca mack'),
	('Luca Mack', 'Germany', 'mack'),
	('Davide Riccardi', 'Italy', 'davide riccardi'),
	('Davide Riccardi', 'Italy', 'riccardi'),
	('Robert Dadok', 'Poland', 'dadok'),
	('Robert Dadok', 'Poland', 'robert dadok'),
	('Jairo Otero', 'Venezuela', 'otero'),
	('Jairo Otero', 'Venezuela', 'jairo otero'),
	('Dylan Pierias', 'Australia', 'pierias'),
	('Dylan Pierias', 'Australia', 'dylan pierias'),
	('Álex Vázquez', 'Uruguay', 'vazquez'),
	('Álex Vázquez', 'Uruguay', 'alex vazquez'),
	('Juan García', 'Colombia', 'juan garcia'),
	('Juan García', 'Colombia', 'garcia'),
	('Leon Müller', 'Germany', 'leon muller'),
	('Leon Müller', 'Germany', 'muller'),
	('Ezequiel Escobar', 'Uruguay', 'escobar'),
	('Ezequiel Escobar', 'Uruguay', 'ezequiel escobar'),
	('Sturla Ottesen', 'Norway', 'ottesen'),
	('Sturla Ottesen', 'Norway', 'sturla ottesen'),
	('Carl Klaus', 'Germany', 'klaus'),
	('Carl Klaus', 'Germany', 'carl klaus'),
	('Ji Xiaoxuan', 'China PR', 'ji xiaoxuan'),
	('Ji Xiaoxuan', 'China PR', 'xiaoxuan'),
	('Mohammed Al Subaie', 'Saudi Arabia', 'mohammed al subaie'),
	('Mohammed Al Subaie', 'Saudi Arabia', 'subaie'),
	('Kai Koreniuk', 'United States', 'kai koreniuk'),
	('Kai Koreniuk', 'United States', 'koreniuk'),
	('Marc-Olivier Doué', 'France', 'marcolivier doue'),
	('Marc-Olivier Doué', 'France', 'doue'),
	('Dawid Szot', 'Poland', 'szot'),
	('Dawid Szot', 'Poland', 'dawid szot'),
	('Nigel Langras', 'Netherlands', 'langras'),
	('Nigel Langras', 'Netherlands', 'nigel langras'),
	('Steven Rodríguez', 'Colombia', 'steven rodriguez'),
	('Steven Rodríguez', 'Colombia', 'rodriguez'),
	('Murat Sevimler', 'Turkey', 'sevimler'),
	('Murat Sevimler', 'Turkey', 'murat sevimler'),
	('Scott High', 'England', 'high'),
	('Scott High', 'England', 'scott high'),
	('Isaak Davies', 'Wales', 'davies'),
	('Isaak Davies', 'Wales', 'isaak davies'),
	('Stephan Mensah', 'Germany', 'mensah'),
	('Stephan Mensah', 'Germany', 'stephan mensah'),
	('Dimitris Serpezis', 'Greece', 'serpezis'),
	('Dimitris Serpezis', 'Greece', 'dimitris serpezis'),
	('Yassine Benhattab', 'France', 'benhattab'),
	('Yassine Benhattab', 'France', 'yassine benhattab'),
	('Mattias Andersson', 'Sweden', 'mattias andersson'),
	('Mattias Andersson', 'Sweden', 'andersson'),
	('Alfred Canales', 'Chile', 'alfred canales'),
	('Alfred Canales', 'Chile', 'canales'),
	('Vladimir Nikolov', 'Bulgaria', 'vladimir nikolov'),
	('Vladimir Nikolov', 'Bulgaria', 'nikolov'),
	('Riyadh Sharahili', 'Saudi Arabia', 'sharahili'),
	('Riyadh Sharahili', 'Saudi Arabia', 'riyadh sharahili'),
	('Jonás Romero', 'Argentina', 'romero'),
	('Jonás Romero', 'Argentina', 'jonas romero'),
	('Sotiris Alexandropoulos', 'Greece', 'sotiris alexandropoulos'),
	('Sotiris Alexandropoulos', 'Greece', 'alexandropoulos'),
	('Robert Harker', 'England', 'robert harker'),
	('Robert Harker', 'England', 'harker'),
	('William Seymore', 'United States', 'seymore'),
	('William Seymore', 'United States', 'william seymore'),
	('Yu In Soo', 'Korea Republic', 'yu in soo'),
	('Yu In Soo', 'Korea Republic', 'soo'),
	('Bali Mumba', 'England', 'mumba'),
	('Bali Mumba', 'England', 'bali mumba'),
	('Idris El Mizouni', 'Tunisia', 'idris el mizouni'),
	('Idris El Mizouni', 'Tunisia', 'mizouni'),
	('Ivan Mayta', 'Peru', 'ivan mayta'),
	('Ivan Mayta', 'Peru', 'mayta'),
	('Mathis Picouleau', 'France', 'picouleau'),
	('Mathis Picouleau', 'France', 'mathis picouleau'),
	('Jason Law', 'England', 'law'),
	('Jason Law', 'England', 'jason law'),
	('Paul Justiniano', 'Bolivia', 'paul justiniano'),
	('Paul Justiniano', 'Bolivia', 'justiniano'),
	('Christopher Engelhart', 'Mexico', 'christopher engelhart'),
	('Christopher Engelhart', 'Mexico', 'engelhart'),
	('Naif Kariri', 'Saudi Arabia', 'naif kariri'),
	('Naif Kariri', 'Saudi Arabia', 'kariri'),
	('David Min', 'Netherlands', 'david min'),
	('David Min', 'Netherlands', 'min'),
	('Wang Qiuming', 'China PR', 'wang qiuming'),
	('Wang Qiuming', 'China PR', 'qiuming'),
	('Tyrese Francois', 'Australia', 'tyrese francois'),
	('Tyrese Francois', 'Australia', 'francois'),
	('Mateusz Żukowski', 'Poland', 'mateusz zukowski'),
	('Mateusz Żukowski', 'Poland', 'zukowski'),
	('Jefferson Vernaza', 'Ecuador', 'vernaza'),
	('Jefferson Vernaza', 'Ecuador', 'jefferson vernaza'),
	('Arturo Batioja', 'Ecuador', 'batioja'),
	('Arturo Batioja', 'Ecuador', 'arturo batioja'),
	('Ansou Sow', 'Senegal', 'ansou sow'),
	('Ansou Sow', 'Senegal', 'sow'),
	('Sun Guowen', 'China PR', 'sun guowen'),
	('Sun Guowen', 'China PR', 'guowen'),
	('Eduard Florescu', 'Romania', 'florescu'),
	('Eduard Florescu', 'Romania', 'eduard florescu'),
	('Jean-Marie Plath', 'Germany', 'jeanmarie plath'),
	('Jean-Marie Plath', 'Germany', 'plath'),
	('Wilfried Bedfian', 'France', 'wilfried bedfian'),
	('Wilfried Bedfian', 'France', 'bedfian'),
	('Brendan Sarpong-Wiredu', 'England', 'sarpongwiredu'),
	('Brendan Sarpong-Wiredu', 'England', 'brendan sarpongwiredu'),
	('Lucas Sanseviero', 'Uruguay', 'sanseviero'),
	('Lucas Sanseviero', 'Uruguay', 'lucas sanseviero'),
	('Jeon Jong Hyeok', 'Korea Republic', 'hyeok'),
	('Jeon Jong Hyeok', 'Korea Republic', 'jeon jong hyeok'),
	('Emre Kurt', 'Germany', 'kurt'),
	('Emre Kurt', 'Germany', 'emre kurt'),
	('Luke Byrne', 'Republic of Ireland', 'byrne'),
	('Luke Byrne', 'Republic of Ireland', 'luke byrne'),
	('Dean Cornelius', 'Scotland', 'dean cornelius'),
	('Dean Cornelius', 'Scotland', 'cornelius'),
	('Mediop Ndiaye', 'Senegal', 'mediop ndiaye'),
	('Mediop Ndiaye', 'Senegal', 'ndiaye'),
	('Robert Kakeeto', 'Uganda', 'robert kakeeto'),
	('Robert Kakeeto', 'Uganda', 'kakeeto'),
	('Moon Ji Hwan', 'Korea Republic', 'hwan'),
	('Moon Ji Hwan', 'Korea Republic', 'moon ji hwan'),
	('Hussain Halawani', 'Saudi Arabia', 'halawani'),
	('Hussain Halawani', 'Saudi Arabia', 'hussain halawani'),
	('Ross Callachan', 'Scotland', 'ross callachan'),
	('Ross Callachan', 'Scotland', 'callachan'),
	('Adrian Ioniță', 'Romania', 'ionita'),
	('Adrian Ioniță', 'Romania', 'adrian ionita'),
	('Cameron Yates', 'Scotland', 'yates'),
	('Cameron Yates', 'Scotland', 'cameron yates'),
	('Vintecinco', 'Brazil', 'vintecinco'),
	('Dai Wai-Tsun', 'Hong Kong', 'waitsun'),
	('Dai Wai-Tsun', 'Hong Kong', 'dai waitsun'),
	('Gordon Wild', 'Germany', 'wild'),
	('Gordon Wild', 'Germany', 'gordon wild'),
	('Yang Shuai', 'China PR', 'yang shuai'),
	('Yang Shuai', 'China PR', 'shuai'),
	('Ángel Fraga', 'Spain', 'fraga'),
	('Ángel Fraga', 'Spain', 'angel fraga'),
	('Isaak Touré', 'France', 'toure'),
	('Isaak Touré', 'France', 'isaak toure'),
	('Mansour Jawhar', 'Saudi Arabia', 'jawhar'),
	('Mansour Jawhar', 'Saudi Arabia', 'mansour jawhar'),
	('Romoney Crichlow', 'England', 'crichlow'),
	('Romoney Crichlow', 'England', 'romoney crichlow'),
	('Oskar Nowak', 'Poland', 'oskar nowak'),
	('Oskar Nowak', 'Poland', 'nowak'),
	('Baltazar', 'Brazil', 'baltazar'),
	('Devante Rodney', 'England', 'rodney'),
	('Devante Rodney', 'England', 'devante rodney'),
	('Dani Vidal', 'Spain', 'vidal'),
	('Dani Vidal', 'Spain', 'dani vidal'),
	('Ünal Tosun', 'Germany', 'tosun'),
	('Ünal Tosun', 'Germany', 'unal tosun'),
	('Mohammad Al Sharimi', 'Saudi Arabia', 'mohammad al sharimi'),
	('Mohammad Al Sharimi', 'Saudi Arabia', 'sharimi'),
	('Kakeru Kumagawa', 'Japan', 'kakeru kumagawa'),
	('Kakeru Kumagawa', 'Japan', 'kumagawa'),
	('Mons Bassouamina', 'France', 'mons bassouamina'),
	('Mons Bassouamina', 'France', 'bassouamina'),
	('Eric Martel', 'Germany', 'eric martel'),
	('Eric Martel', 'Germany', 'martel'),
	('Nezar S''rifi', 'Belgium', 'nezar srifi'),
	('Nezar S''rifi', 'Belgium', 'srifi')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';