INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Stojan Lukić', 'Bosnia Herzegovina', 'player'),
	('Connor Randall', 'England', 'player'),
	('Stefan Velkov', 'Bulgaria', 'player'),
	('Aaron Wildig', 'England', 'player'),
	('Dennis Smarsch', 'Germany', 'player'),
	('Antonino Gallo', 'Italy', 'player'),
	('Mateusz Spychała', 'Poland', 'player'),
	('William Boyle', 'England', 'player'),
	('Zhao Xuri', 'China PR', 'player'),
	('Josua Mejías', 'Venezuela', 'player'),
	('Luke Waterfall', 'England', 'player'),
	('Jovan Marković', 'Romania', 'player'),
	('Runar Hove', 'Norway', 'player'),
	('Can Coskun', 'Turkey', 'player'),
	('Cho Ji Hun', 'Korea Republic', 'player'),
	('Mariusz Rybicki', 'Poland', 'player'),
	('Brendan Clarke', 'Republic of Ireland', 'player'),
	('Ben Reeves', 'Northern Ireland', 'player'),
	('Juan Sánchez Purata', 'Mexico', 'player'),
	('Alex MacDonald', 'Scotland', 'player'),
	('Pedro Brazão', 'Portugal', 'player'),
	('Harry Smith', 'England', 'player'),
	('Duckens Nazon', 'Haiti', 'player'),
	('Oliver Šarkić', 'Montenegro', 'player'),
	('Erik Figueroa', 'Sweden', 'player'),
	('Antoine Baroan', 'France', 'player'),
	('Santeri Hostikka', 'Finland', 'player'),
	('Laurențiu Popescu', 'Romania', 'player'),
	('Ahmed Al Nazera', 'Saudi Arabia', 'player'),
	('Piao Shihao', 'China PR', 'player'),
	('Donovan Pines', 'United States', 'player'),
	('Álex Escardó', 'Spain', 'player'),
	('Kadir Hodžić', 'Sweden', 'player'),
	('Eduardo Rabanal', 'Peru', 'player'),
	('Luca Coccolo', 'Italy', 'player'),
	('Roberto Carlos Fernández', 'Bolivia', 'player'),
	('Jack Sparkes', 'England', 'player'),
	('Richard Mina', 'Ecuador', 'player'),
	('Marco Armellino', 'Italy', 'player'),
	('Kevin Salvatierra', 'Bolivia', 'player'),
	('Ryang Yong Gi', 'Korea DPR', 'player'),
	('Armel Bella-Kotchap', 'Germany', 'player'),
	('Marko Malenica', 'Croatia', 'player'),
	('Yann Songo''o', 'Cameroon', 'player'),
	('Isaac Twum', 'Ghana', 'player'),
	('Tim Siersleben', 'Germany', 'player'),
	('Bryn Morris', 'England', 'player'),
	('Marcelo Palomino', 'United States', 'player'),
	('Madger Gomes', 'Spain', 'player'),
	('Emil Frederiksen', 'Denmark', 'player'),
	('Adrián Turmo', 'Spain', 'player'),
	('Steven Luštica', 'Australia', 'player'),
	('Henrik Castegren', 'Sweden', 'player'),
	('Lewis Ward', 'England', 'player'),
	('Daniel Sandy', 'Bolivia', 'player'),
	('Garissone Innocent', 'France', 'player'),
	('Itaitinga', 'Brazil', 'player'),
	('Charalambos Makridis', 'Germany', 'player'),
	('Lee Erwin', 'Scotland', 'player'),
	('Conor McGrandles', 'Scotland', 'player'),
	('Elijah Adebayo', 'England', 'player'),
	('Pádraig Amond', 'Republic of Ireland', 'player'),
	('Elliot Parish', 'England', 'player'),
	('Valentin Grubeck', 'Austria', 'player'),
	('Brandon Hanlan', 'England', 'player'),
	('Brian Gartland', 'Republic of Ireland', 'player'),
	('Lucas Beltrán', 'Argentina', 'player'),
	('Miguel Bandarra', 'Portugal', 'player'),
	('Jack Lahne', 'Sweden', 'player'),
	('Amar Ćatić', 'Bosnia Herzegovina', 'player'),
	('Edwin Cangá', 'Ecuador', 'player'),
	('Tòfol Montiel', 'Spain', 'player'),
	('Renny Smith', 'Austria', 'player'),
	('Paris Cowan-Hall', 'England', 'player'),
	('Erdon Daci', 'North Macedonia', 'player'),
	('Scot Bennett', 'England', 'player'),
	('Bryan Meredith', 'United States', 'player'),
	('Alexis Sosa', 'Argentina', 'player'),
	('Nebiyou Perry', 'Sweden', 'player'),
	('David Fleitas', 'Paraguay', 'player'),
	('Mees Bakker', 'Netherlands', 'player'),
	('Mohammed Al Dawsari', 'Saudi Arabia', 'player'),
	('Viktor Gustafson', 'Sweden', 'player'),
	('Fernando Romero', 'Paraguay', 'player'),
	('Daniel Steininger', 'Germany', 'player'),
	('Abdullah Hassoun', 'Saudi Arabia', 'player'),
	('Miro Tenho', 'Finland', 'player'),
	('Uri', 'Spain', 'player'),
	('Dan Agyei', 'England', 'player'),
	('Éder Cetré', 'Ecuador', 'player'),
	('Serge-Philippe Raux-Yao', 'France', 'player'),
	('Jayson Breitenbach', 'Germany', 'player'),
	('Wang Zihao', 'China PR', 'player'),
	('Aaron Kamardin', 'France', 'player'),
	('Andrei Trușescu', 'Romania', 'player'),
	('Erol Alkan', 'Turkey', 'player'),
	('Hakeem Odoffin', 'England', 'player'),
	('Nixon Molina', 'Ecuador', 'player'),
	('Jesper Löfgren', 'Sweden', 'player'),
	('Dženan Zajmović', 'Bosnia Herzegovina', 'player'),
	('Richard Fernández', 'Uruguay', 'player'),
	('Macaulay Gillesphey', 'England', 'player'),
	('Wang Jinxian', 'China PR', 'player'),
	('Aldo Maiz', 'Paraguay', 'player'),
	('Geir André Herrem', 'Norway', 'player'),
	('Nathan Tella', 'England', 'player'),
	('Benjamin Stokke', 'Norway', 'player'),
	('Hussain Al Shuwaysh', 'Saudi Arabia', 'player'),
	('Matthew Briggs', 'Guyana', 'player'),
	('Julian Stöckner', 'Germany', 'player'),
	('Yun Yong Ho', 'Korea Republic', 'player'),
	('Jonathan Rasheed', 'Norway', 'player'),
	('Alex Rufer', 'New Zealand', 'player'),
	('Axel Andrésson', 'Iceland', 'player'),
	('Leonardo Morales', 'Argentina', 'player'),
	('Tosaint Ricketts', 'Canada', 'player'),
	('Jeroen Houwen', 'Netherlands', 'player'),
	('Maciej Pałaszewski', 'Poland', 'player'),
	('Niccolò Zanellato', 'Italy', 'player'),
	('Adetayo Edun', 'England', 'player'),
	('Benrandy Abdallah', 'France', 'player'),
	('Ismail El Harchi', 'Morocco', 'player'),
	('Cian Harries', 'Wales', 'player'),
	('Kubilay Aktaş', 'Turkey', 'player'),
	('Himad Abdelli', 'France', 'player'),
	('Emmanuel Osadebe', 'Republic of Ireland', 'player'),
	('Jacob Greaves', 'England', 'player'),
	('Andreas Hansen', 'Denmark', 'player'),
	('Gonzalo Crettaz', 'Argentina', 'player'),
	('Andy Pembélé', 'France', 'player'),
	('Lorenzo Carissoni', 'Italy', 'player'),
	('Joss Labadie', 'England', 'player'),
	('Simo Rumbullaku', 'Albania', 'player'),
	('Marlon Fossey', 'United States', 'player'),
	('Ben Wilson', 'England', 'player'),
	('Anthony Koura', 'Burkina Faso', 'player'),
	('Tobias Lawal', 'Nigeria', 'player'),
	('Kurtis Guthrie', 'England', 'player'),
	('Maciej Ambrosiewicz', 'Poland', 'player'),
	('Matija Šarkić', 'Montenegro', 'player'),
	('Shogo Nakahara', 'Japan', 'player'),
	('Jorès Rahou', 'France', 'player'),
	('Florian Baak', 'Germany', 'player'),
	('Márton Dárdai', 'Germany', 'player'),
	('Kim Young Bin', 'Korea Republic', 'player'),
	('Sven Mende', 'Germany', 'player'),
	('Zhu Jianrong', 'China PR', 'player'),
	('Abdel Hakim Abdallah', 'Comoros', 'player'),
	('Eduardo Dos Santos Haesler', 'Germany', 'player'),
	('Malaly Dembélé', 'France', 'player'),
	('Simon Amin', 'Syria', 'player'),
	('Gary Woods', 'England', 'player'),
	('Nick Fitzgerald', 'Australia', 'player'),
	('Gabriele Zappa', 'Italy', 'player'),
	('Edson Rivas', 'Venezuela', 'player'),
	('Lasse Jürgensen', 'Germany', 'player'),
	('Joe Gelhardt', 'England', 'player'),
	('Pape Meissa Ba', 'Senegal', 'player'),
	('Kevin Sessa', 'Germany', 'player'),
	('Lewis Montsma', 'Netherlands', 'player'),
	('Jayden Mitchell-Lawson', 'England', 'player'),
	('Abdullah Al Yousef', 'Saudi Arabia', 'player'),
	('Julio Gracia', 'Spain', 'player'),
	('Matt Real', 'United States', 'player'),
	('Kostas Lazaridis', 'Greece', 'player'),
	('Mohamed Youssouf', 'Comoros', 'player'),
	('Hwang Tae Hyun', 'Korea Republic', 'player'),
	('Luděk Vejmola', 'Czech Republic', 'player'),
	('Nicolas Madsen', 'Denmark', 'player'),
	('Azur Velagic', 'Germany', 'player'),
	('Benjamín Gazzolo', 'Chile', 'player'),
	('Nicholas Gioacchini', 'United States', 'player'),
	('Omar Imeri', 'Albania', 'player'),
	('Rijad Kobiljar', 'Bosnia Herzegovina', 'player'),
	('Christian Gauseth', 'Norway', 'player'),
	('Isaac Nuhu', 'Ghana', 'player'),
	('Orhan Ademi', 'Switzerland', 'player'),
	('Lee Seung Mo', 'Korea Republic', 'player'),
	('Abdulelah Al Amri', 'Saudi Arabia', 'player'),
	('Marc Baró', 'Spain', 'player'),
	('Erick Wiemberg', 'Chile', 'player'),
	('Aaron Boupendza', 'Gabon', 'player'),
	('Sam Lavelle', 'Scotland', 'player'),
	('Ilia Gruev', 'Bulgaria', 'player'),
	('Frederik Lach', 'Germany', 'player'),
	('Bryan Figueroa', 'Chile', 'player'),
	('Aaron Lewis', 'Wales', 'player'),
	('Omar Bertel', 'Colombia', 'player'),
	('Cody Drameh', 'England', 'player'),
	('Kjetil Haug', 'Norway', 'player'),
	('Alex Dobre', 'Romania', 'player'),
	('Toon Raemaekers', 'Belgium', 'player'),
	('Sascha Korb', 'Germany', 'player'),
	('Lee Angol', 'England', 'player'),
	('Ikuma Sekigawa', 'Japan', 'player'),
	('Renzo López', 'Uruguay', 'player'),
	('Paul Grauschopf', 'Germany', 'player'),
	('Andrés Balanta', 'Colombia', 'player'),
	('Alan Virginius', 'France', 'player'),
	('Levi Lumeka', 'England', 'player'),
	('Faress Al Aiyaf', 'Saudi Arabia', 'player'),
	('André Riel', 'Denmark', 'player'),
	('Boubacar Hanne', 'Portugal', 'player'),
	('Danny Whitehead', 'England', 'player'),
	('Wyatt Omsberg', 'United States', 'player'),
	('Thijs van Leeuwen', 'Netherlands', 'player'),
	('Benas Satkus', 'Lithuania', 'player'),
	('Valdeci', 'Brazil', 'player'),
	('Admir Bajrovic', 'Sweden', 'player'),
	('Lee Chang Yong', 'Korea Republic', 'player'),
	('Pedro Martelo', 'Portugal', 'player'),
	('Chris Stokes', 'England', 'player'),
	('Lukas Gottwalt', 'Germany', 'player'),
	('Alfie McCalmont', 'Northern Ireland', 'player'),
	('Deniz Mehmet', 'Turkey', 'player'),
	('Noel Knothe', 'Germany', 'player'),
	('Mauricio Pineda', 'United States', 'player'),
	('Josh Parker', 'Antigua & Barbuda', 'player'),
	('Michael Neill', 'Australia', 'player'),
	('Karol Niemczycki', 'Poland', 'player'),
	('Earl Edwards Jr.', 'United States', 'player'),
	('Kristers Tobers', 'Latvia', 'player'),
	('Javi Vázquez', 'Spain', 'player'),
	('Takuya Uchida', 'Japan', 'player'),
	('Minos Gouras', 'Germany', 'player'),
	('Park Jun Hui', 'Korea Republic', 'player'),
	('Hotaka Nakamura', 'Japan', 'player'),
	('Jimmy Isita', 'Bolivia', 'player'),
	('Michael Tørnes', 'Denmark', 'player'),
	('Yanis Ammour', 'France', 'player'),
	('Callum Guy', 'England', 'player'),
	('Josh Doig', 'Scotland', 'player'),
	('Alexander Ruud Tveter', 'Norway', 'player'),
	('Josip Šutalo', 'Croatia', 'player'),
	('Bradley Barry', 'England', 'player'),
	('Kianz Froese', 'Canada', 'player'),
	('Maurício Cortés', 'Colombia', 'player'),
	('Ștefan Târnovanu', 'Romania', 'player'),
	('Hallam Hope', 'Barbados', 'player'),
	('Federico Gattoni', 'Argentina', 'player'),
	('Milan Tučić', 'Slovenia', 'player'),
	('Léo Seydoux', 'Switzerland', 'player'),
	('Atakan Gündüz', 'Turkey', 'player'),
	('Lewis Spence', 'Scotland', 'player'),
	('Aurélien Nguiamba', 'France', 'player'),
	('Aaron Herzog', 'Germany', 'player'),
	('Luis Sandoval', 'Colombia', 'player'),
	('Luiz Júnior', 'Brazil', 'player'),
	('Joshua Hare', 'England', 'player'),
	('Mabrouk Rouai', 'France', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Stojan Lukić', 'Bosnia Herzegovina', 'lukic'),
	('Stojan Lukić', 'Bosnia Herzegovina', 'stojan lukic'),
	('Connor Randall', 'England', 'randall'),
	('Connor Randall', 'England', 'connor randall'),
	('Stefan Velkov', 'Bulgaria', 'velkov'),
	('Stefan Velkov', 'Bulgaria', 'stefan velkov'),
	('Aaron Wildig', 'England', 'aaron wildig'),
	('Aaron Wildig', 'England', 'wildig'),
	('Dennis Smarsch', 'Germany', 'smarsch'),
	('Dennis Smarsch', 'Germany', 'dennis smarsch'),
	('Antonino Gallo', 'Italy', 'antonino gallo'),
	('Antonino Gallo', 'Italy', 'gallo'),
	('Mateusz Spychała', 'Poland', 'mateusz spychaa'),
	('Mateusz Spychała', 'Poland', 'spychaa'),
	('William Boyle', 'England', 'boyle'),
	('William Boyle', 'England', 'william boyle'),
	('Zhao Xuri', 'China PR', 'zhao xuri'),
	('Zhao Xuri', 'China PR', 'xuri'),
	('Josua Mejías', 'Venezuela', 'mejias'),
	('Josua Mejías', 'Venezuela', 'josua mejias'),
	('Luke Waterfall', 'England', 'waterfall'),
	('Luke Waterfall', 'England', 'luke waterfall'),
	('Jovan Marković', 'Romania', 'markovic'),
	('Jovan Marković', 'Romania', 'jovan markovic'),
	('Runar Hove', 'Norway', 'runar hove'),
	('Runar Hove', 'Norway', 'hove'),
	('Can Coskun', 'Turkey', 'coskun'),
	('Can Coskun', 'Turkey', 'can coskun'),
	('Cho Ji Hun', 'Korea Republic', 'cho ji hun'),
	('Cho Ji Hun', 'Korea Republic', 'hun'),
	('Mariusz Rybicki', 'Poland', 'rybicki'),
	('Mariusz Rybicki', 'Poland', 'mariusz rybicki'),
	('Brendan Clarke', 'Republic of Ireland', 'clarke'),
	('Brendan Clarke', 'Republic of Ireland', 'brendan clarke'),
	('Ben Reeves', 'Northern Ireland', 'reeves'),
	('Ben Reeves', 'Northern Ireland', 'ben reeves'),
	('Juan Sánchez Purata', 'Mexico', 'juan sanchez purata'),
	('Juan Sánchez Purata', 'Mexico', 'purata'),
	('Alex MacDonald', 'Scotland', 'macdonald'),
	('Alex MacDonald', 'Scotland', 'alex macdonald'),
	('Pedro Brazão', 'Portugal', 'pedro brazao'),
	('Pedro Brazão', 'Portugal', 'brazao'),
	('Harry Smith', 'England', 'smith'),
	('Harry Smith', 'England', 'harry smith'),
	('Duckens Nazon', 'Haiti', 'duckens nazon'),
	('Duckens Nazon', 'Haiti', 'nazon'),
	('Oliver Šarkić', 'Montenegro', 'sarkic'),
	('Oliver Šarkić', 'Montenegro', 'oliver sarkic'),
	('Erik Figueroa', 'Sweden', 'figueroa'),
	('Erik Figueroa', 'Sweden', 'erik figueroa'),
	('Antoine Baroan', 'France', 'antoine baroan'),
	('Antoine Baroan', 'France', 'baroan'),
	('Santeri Hostikka', 'Finland', 'hostikka'),
	('Santeri Hostikka', 'Finland', 'santeri hostikka'),
	('Laurențiu Popescu', 'Romania', 'laurentiu popescu'),
	('Laurențiu Popescu', 'Romania', 'popescu'),
	('Ahmed Al Nazera', 'Saudi Arabia', 'nazera'),
	('Ahmed Al Nazera', 'Saudi Arabia', 'ahmed al nazera'),
	('Piao Shihao', 'China PR', 'shihao'),
	('Piao Shihao', 'China PR', 'piao shihao'),
	('Donovan Pines', 'United States', 'donovan pines'),
	('Donovan Pines', 'United States', 'pines'),
	('Álex Escardó', 'Spain', 'alex escardo'),
	('Álex Escardó', 'Spain', 'escardo'),
	('Kadir Hodžić', 'Sweden', 'kadir hodzic'),
	('Kadir Hodžić', 'Sweden', 'hodzic'),
	('Eduardo Rabanal', 'Peru', 'eduardo rabanal'),
	('Eduardo Rabanal', 'Peru', 'rabanal'),
	('Luca Coccolo', 'Italy', 'coccolo'),
	('Luca Coccolo', 'Italy', 'luca coccolo'),
	('Roberto Carlos Fernández', 'Bolivia', 'fernandez'),
	('Roberto Carlos Fernández', 'Bolivia', 'roberto carlos fernandez'),
	('Jack Sparkes', 'England', 'sparkes'),
	('Jack Sparkes', 'England', 'jack sparkes'),
	('Richard Mina', 'Ecuador', 'mina'),
	('Richard Mina', 'Ecuador', 'richard mina'),
	('Marco Armellino', 'Italy', 'armellino'),
	('Marco Armellino', 'Italy', 'marco armellino'),
	('Kevin Salvatierra', 'Bolivia', 'salvatierra'),
	('Kevin Salvatierra', 'Bolivia', 'kevin salvatierra'),
	('Ryang Yong Gi', 'Korea DPR', 'gi'),
	('Ryang Yong Gi', 'Korea DPR', 'ryang yong gi'),
	('Armel Bella-Kotchap', 'Germany', 'armel bellakotchap'),
	('Armel Bella-Kotchap', 'Germany', 'bellakotchap'),
	('Marko Malenica', 'Croatia', 'marko malenica'),
	('Marko Malenica', 'Croatia', 'malenica'),
	('Yann Songo''o', 'Cameroon', 'yann songoo'),
	('Yann Songo''o', 'Cameroon', 'songoo'),
	('Isaac Twum', 'Ghana', 'isaac twum'),
	('Isaac Twum', 'Ghana', 'twum'),
	('Tim Siersleben', 'Germany', 'siersleben'),
	('Tim Siersleben', 'Germany', 'tim siersleben'),
	('Bryn Morris', 'England', 'morris'),
	('Bryn Morris', 'England', 'bryn morris'),
	('Marcelo Palomino', 'United States', 'palomino'),
	('Marcelo Palomino', 'United States', 'marcelo palomino'),
	('Madger Gomes', 'Spain', 'madger gomes'),
	('Madger Gomes', 'Spain', 'gomes'),
	('Emil Frederiksen', 'Denmark', 'emil frederiksen'),
	('Emil Frederiksen', 'Denmark', 'frederiksen'),
	('Adrián Turmo', 'Spain', 'turmo'),
	('Adrián Turmo', 'Spain', 'adrian turmo'),
	('Steven Luštica', 'Australia', 'steven lustica'),
	('Steven Luštica', 'Australia', 'lustica'),
	('Henrik Castegren', 'Sweden', 'castegren'),
	('Henrik Castegren', 'Sweden', 'henrik castegren'),
	('Lewis Ward', 'England', 'ward'),
	('Lewis Ward', 'England', 'lewis ward'),
	('Daniel Sandy', 'Bolivia', 'sandy'),
	('Daniel Sandy', 'Bolivia', 'daniel sandy'),
	('Garissone Innocent', 'France', 'innocent'),
	('Garissone Innocent', 'France', 'garissone innocent'),
	('Itaitinga', 'Brazil', 'itaitinga'),
	('Charalambos Makridis', 'Germany', 'makridis'),
	('Charalambos Makridis', 'Germany', 'charalambos makridis'),
	('Lee Erwin', 'Scotland', 'erwin'),
	('Lee Erwin', 'Scotland', 'lee erwin'),
	('Conor McGrandles', 'Scotland', 'mcgrandles'),
	('Conor McGrandles', 'Scotland', 'conor mcgrandles'),
	('Elijah Adebayo', 'England', 'elijah adebayo'),
	('Elijah Adebayo', 'England', 'adebayo'),
	('Pádraig Amond', 'Republic of Ireland', 'amond'),
	('Pádraig Amond', 'Republic of Ireland', 'padraig amond'),
	('Elliot Parish', 'England', 'parish'),
	('Elliot Parish', 'England', 'elliot parish'),
	('Valentin Grubeck', 'Austria', 'valentin grubeck'),
	('Valentin Grubeck', 'Austria', 'grubeck'),
	('Brandon Hanlan', 'England', 'brandon hanlan'),
	('Brandon Hanlan', 'England', 'hanlan'),
	('Brian Gartland', 'Republic of Ireland', 'brian gartland'),
	('Brian Gartland', 'Republic of Ireland', 'gartland'),
	('Lucas Beltrán', 'Argentina', 'lucas beltran'),
	('Lucas Beltrán', 'Argentina', 'beltran'),
	('Miguel Bandarra', 'Portugal', 'bandarra'),
	('Miguel Bandarra', 'Portugal', 'miguel bandarra'),
	('Jack Lahne', 'Sweden', 'lahne'),
	('Jack Lahne', 'Sweden', 'jack lahne'),
	('Amar Ćatić', 'Bosnia Herzegovina', 'amar catic'),
	('Amar Ćatić', 'Bosnia Herzegovina', 'catic'),
	('Edwin Cangá', 'Ecuador', 'canga'),
	('Edwin Cangá', 'Ecuador', 'edwin canga'),
	('Tòfol Montiel', 'Spain', 'tofol montiel'),
	('Tòfol Montiel', 'Spain', 'montiel'),
	('Renny Smith', 'Austria', 'smith'),
	('Renny Smith', 'Austria', 'renny smith'),
	('Paris Cowan-Hall', 'England', 'cowanhall'),
	('Paris Cowan-Hall', 'England', 'paris cowanhall'),
	('Erdon Daci', 'North Macedonia', 'erdon daci'),
	('Erdon Daci', 'North Macedonia', 'daci'),
	('Scot Bennett', 'England', 'bennett'),
	('Scot Bennett', 'England', 'scot bennett'),
	('Bryan Meredith', 'United States', 'bryan meredith'),
	('Bryan Meredith', 'United States', 'meredith'),
	('Alexis Sosa', 'Argentina', 'alexis sosa'),
	('Alexis Sosa', 'Argentina', 'sosa'),
	('Nebiyou Perry', 'Sweden', 'nebiyou perry'),
	('Nebiyou Perry', 'Sweden', 'perry'),
	('David Fleitas', 'Paraguay', 'david fleitas'),
	('David Fleitas', 'Paraguay', 'fleitas'),
	('Mees Bakker', 'Netherlands', 'mees bakker'),
	('Mees Bakker', 'Netherlands', 'bakker'),
	('Mohammed Al Dawsari', 'Saudi Arabia', 'dawsari'),
	('Mohammed Al Dawsari', 'Saudi Arabia', 'mohammed al dawsari'),
	('Viktor Gustafson', 'Sweden', 'gustafson'),
	('Viktor Gustafson', 'Sweden', 'viktor gustafson'),
	('Fernando Romero', 'Paraguay', 'fernando romero'),
	('Fernando Romero', 'Paraguay', 'romero'),
	('Daniel Steininger', 'Germany', 'steininger'),
	('Daniel Steininger', 'Germany', 'daniel steininger'),
	('Abdullah Hassoun', 'Saudi Arabia', 'abdullah hassoun'),
	('Abdullah Hassoun', 'Saudi Arabia', 'hassoun'),
	('Miro Tenho', 'Finland', 'tenho'),
	('Miro Tenho', 'Finland', 'miro tenho'),
	('Uri', 'Spain', 'uri'),
	('Dan Agyei', 'England', 'agyei'),
	('Dan Agyei', 'England', 'dan agyei'),
	('Éder Cetré', 'Ecuador', 'eder cetre'),
	('Éder Cetré', 'Ecuador', 'cetre'),
	('Serge-Philippe Raux-Yao', 'France', 'rauxyao'),
	('Serge-Philippe Raux-Yao', 'France', 'sergephilippe rauxyao'),
	('Jayson Breitenbach', 'Germany', 'breitenbach'),
	('Jayson Breitenbach', 'Germany', 'jayson breitenbach'),
	('Wang Zihao', 'China PR', 'zihao'),
	('Wang Zihao', 'China PR', 'wang zihao'),
	('Aaron Kamardin', 'France', 'aaron kamardin'),
	('Aaron Kamardin', 'France', 'kamardin'),
	('Andrei Trușescu', 'Romania', 'andrei trusescu'),
	('Andrei Trușescu', 'Romania', 'trusescu'),
	('Erol Alkan', 'Turkey', 'erol alkan'),
	('Erol Alkan', 'Turkey', 'alkan'),
	('Hakeem Odoffin', 'England', 'hakeem odoffin'),
	('Hakeem Odoffin', 'England', 'odoffin'),
	('Nixon Molina', 'Ecuador', 'molina'),
	('Nixon Molina', 'Ecuador', 'nixon molina'),
	('Jesper Löfgren', 'Sweden', 'lofgren'),
	('Jesper Löfgren', 'Sweden', 'jesper lofgren'),
	('Dženan Zajmović', 'Bosnia Herzegovina', 'dzenan zajmovic'),
	('Dženan Zajmović', 'Bosnia Herzegovina', 'zajmovic'),
	('Richard Fernández', 'Uruguay', 'richard fernandez'),
	('Richard Fernández', 'Uruguay', 'fernandez'),
	('Macaulay Gillesphey', 'England', 'macaulay gillesphey'),
	('Macaulay Gillesphey', 'England', 'gillesphey'),
	('Wang Jinxian', 'China PR', 'wang jinxian'),
	('Wang Jinxian', 'China PR', 'jinxian'),
	('Aldo Maiz', 'Paraguay', 'maiz'),
	('Aldo Maiz', 'Paraguay', 'aldo maiz'),
	('Geir André Herrem', 'Norway', 'geir andre herrem'),
	('Geir André Herrem', 'Norway', 'herrem'),
	('Nathan Tella', 'England', 'tella'),
	('Nathan Tella', 'England', 'nathan tella'),
	('Benjamin Stokke', 'Norway', 'stokke'),
	('Benjamin Stokke', 'Norway', 'benjamin stokke'),
	('Hussain Al Shuwaysh', 'Saudi Arabia', 'shuwaysh'),
	('Hussain Al Shuwaysh', 'Saudi Arabia', 'hussain al shuwaysh'),
	('Matthew Briggs', 'Guyana', 'briggs'),
	('Matthew Briggs', 'Guyana', 'matthew briggs'),
	('Julian Stöckner', 'Germany', 'julian stockner'),
	('Julian Stöckner', 'Germany', 'stockner'),
	('Yun Yong Ho', 'Korea Republic', 'yun yong ho'),
	('Yun Yong Ho', 'Korea Republic', 'ho'),
	('Jonathan Rasheed', 'Norway', 'jonathan rasheed'),
	('Jonathan Rasheed', 'Norway', 'rasheed'),
	('Alex Rufer', 'New Zealand', 'alex rufer'),
	('Alex Rufer', 'New Zealand', 'rufer'),
	('Axel Andrésson', 'Iceland', 'axel andresson'),
	('Axel Andrésson', 'Iceland', 'andresson'),
	('Leonardo Morales', 'Argentina', 'leonardo morales'),
	('Leonardo Morales', 'Argentina', 'morales'),
	('Tosaint Ricketts', 'Canada', 'tosaint ricketts'),
	('Tosaint Ricketts', 'Canada', 'ricketts'),
	('Jeroen Houwen', 'Netherlands', 'jeroen houwen'),
	('Jeroen Houwen', 'Netherlands', 'houwen'),
	('Maciej Pałaszewski', 'Poland', 'maciej paaszewski'),
	('Maciej Pałaszewski', 'Poland', 'paaszewski'),
	('Niccolò Zanellato', 'Italy', 'niccolo zanellato'),
	('Niccolò Zanellato', 'Italy', 'zanellato'),
	('Adetayo Edun', 'England', 'adetayo edun'),
	('Adetayo Edun', 'England', 'edun'),
	('Benrandy Abdallah', 'France', 'benrandy abdallah'),
	('Benrandy Abdallah', 'France', 'abdallah'),
	('Ismail El Harchi', 'Morocco', 'ismail el harchi'),
	('Ismail El Harchi', 'Morocco', 'harchi'),
	('Cian Harries', 'Wales', 'harries'),
	('Cian Harries', 'Wales', 'cian harries'),
	('Kubilay Aktaş', 'Turkey', 'aktas'),
	('Kubilay Aktaş', 'Turkey', 'kubilay aktas'),
	('Himad Abdelli', 'France', 'abdelli'),
	('Himad Abdelli', 'France', 'himad abdelli'),
	('Emmanuel Osadebe', 'Republic of Ireland', 'osadebe'),
	('Emmanuel Osadebe', 'Republic of Ireland', 'emmanuel osadebe'),
	('Jacob Greaves', 'England', 'jacob greaves'),
	('Jacob Greaves', 'England', 'greaves'),
	('Andreas Hansen', 'Denmark', 'hansen'),
	('Andreas Hansen', 'Denmark', 'andreas hansen'),
	('Gonzalo Crettaz', 'Argentina', 'gonzalo crettaz'),
	('Gonzalo Crettaz', 'Argentina', 'crettaz'),
	('Andy Pembélé', 'France', 'pembele'),
	('Andy Pembélé', 'France', 'andy pembele'),
	('Lorenzo Carissoni', 'Italy', 'lorenzo carissoni'),
	('Lorenzo Carissoni', 'Italy', 'carissoni'),
	('Joss Labadie', 'England', 'labadie'),
	('Joss Labadie', 'England', 'joss labadie'),
	('Simo Rumbullaku', 'Albania', 'simo rumbullaku'),
	('Simo Rumbullaku', 'Albania', 'rumbullaku'),
	('Marlon Fossey', 'United States', 'fossey'),
	('Marlon Fossey', 'United States', 'marlon fossey'),
	('Ben Wilson', 'England', 'ben wilson'),
	('Ben Wilson', 'England', 'wilson'),
	('Anthony Koura', 'Burkina Faso', 'anthony koura'),
	('Anthony Koura', 'Burkina Faso', 'koura'),
	('Tobias Lawal', 'Nigeria', 'tobias lawal'),
	('Tobias Lawal', 'Nigeria', 'lawal'),
	('Kurtis Guthrie', 'England', 'guthrie'),
	('Kurtis Guthrie', 'England', 'kurtis guthrie'),
	('Maciej Ambrosiewicz', 'Poland', 'ambrosiewicz'),
	('Maciej Ambrosiewicz', 'Poland', 'maciej ambrosiewicz'),
	('Matija Šarkić', 'Montenegro', 'sarkic'),
	('Matija Šarkić', 'Montenegro', 'matija sarkic'),
	('Shogo Nakahara', 'Japan', 'nakahara'),
	('Shogo Nakahara', 'Japan', 'shogo nakahara'),
	('Jorès Rahou', 'France', 'jores rahou'),
	('Jorès Rahou', 'France', 'rahou'),
	('Florian Baak', 'Germany', 'florian baak'),
	('Florian Baak', 'Germany', 'baak'),
	('Márton Dárdai', 'Germany', 'dardai'),
	('Márton Dárdai', 'Germany', 'marton dardai'),
	('Kim Young Bin', 'Korea Republic', 'kim young bin'),
	('Kim Young Bin', 'Korea Republic', 'bin'),
	('Sven Mende', 'Germany', 'sven mende'),
	('Sven Mende', 'Germany', 'mende'),
	('Zhu Jianrong', 'China PR', 'jianrong'),
	('Zhu Jianrong', 'China PR', 'zhu jianrong'),
	('Abdel Hakim Abdallah', 'Comoros', 'abdel hakim abdallah'),
	('Abdel Hakim Abdallah', 'Comoros', 'abdallah'),
	('Eduardo Dos Santos Haesler', 'Germany', 'haesler'),
	('Eduardo Dos Santos Haesler', 'Germany', 'eduardo dos santos haesler'),
	('Malaly Dembélé', 'France', 'dembele'),
	('Malaly Dembélé', 'France', 'malaly dembele'),
	('Simon Amin', 'Syria', 'simon amin'),
	('Simon Amin', 'Syria', 'amin'),
	('Gary Woods', 'England', 'woods'),
	('Gary Woods', 'England', 'gary woods'),
	('Nick Fitzgerald', 'Australia', 'nick fitzgerald'),
	('Nick Fitzgerald', 'Australia', 'fitzgerald'),
	('Gabriele Zappa', 'Italy', 'zappa'),
	('Gabriele Zappa', 'Italy', 'gabriele zappa'),
	('Edson Rivas', 'Venezuela', 'rivas'),
	('Edson Rivas', 'Venezuela', 'edson rivas'),
	('Lasse Jürgensen', 'Germany', 'jurgensen'),
	('Lasse Jürgensen', 'Germany', 'lasse jurgensen'),
	('Joe Gelhardt', 'England', 'joe gelhardt'),
	('Joe Gelhardt', 'England', 'gelhardt'),
	('Pape Meissa Ba', 'Senegal', 'ba'),
	('Pape Meissa Ba', 'Senegal', 'pape meissa ba'),
	('Kevin Sessa', 'Germany', 'kevin sessa'),
	('Kevin Sessa', 'Germany', 'sessa'),
	('Lewis Montsma', 'Netherlands', 'montsma'),
	('Lewis Montsma', 'Netherlands', 'lewis montsma'),
	('Jayden Mitchell-Lawson', 'England', 'mitchelllawson'),
	('Jayden Mitchell-Lawson', 'England', 'jayden mitchelllawson'),
	('Abdullah Al Yousef', 'Saudi Arabia', 'abdullah al yousef'),
	('Abdullah Al Yousef', 'Saudi Arabia', 'yousef'),
	('Julio Gracia', 'Spain', 'gracia'),
	('Julio Gracia', 'Spain', 'julio gracia'),
	('Matt Real', 'United States', 'real'),
	('Matt Real', 'United States', 'matt real'),
	('Kostas Lazaridis', 'Greece', 'kostas lazaridis'),
	('Kostas Lazaridis', 'Greece', 'lazaridis'),
	('Mohamed Youssouf', 'Comoros', 'youssouf'),
	('Mohamed Youssouf', 'Comoros', 'mohamed youssouf'),
	('Hwang Tae Hyun', 'Korea Republic', 'hwang tae hyun'),
	('Hwang Tae Hyun', 'Korea Republic', 'hyun'),
	('Luděk Vejmola', 'Czech Republic', 'vejmola'),
	('Luděk Vejmola', 'Czech Republic', 'ludek vejmola'),
	('Nicolas Madsen', 'Denmark', 'nicolas madsen'),
	('Nicolas Madsen', 'Denmark', 'madsen'),
	('Azur Velagic', 'Germany', 'azur velagic'),
	('Azur Velagic', 'Germany', 'velagic'),
	('Benjamín Gazzolo', 'Chile', 'benjamin gazzolo'),
	('Benjamín Gazzolo', 'Chile', 'gazzolo'),
	('Nicholas Gioacchini', 'United States', 'nicholas gioacchini'),
	('Nicholas Gioacchini', 'United States', 'gioacchini'),
	('Omar Imeri', 'Albania', 'imeri'),
	('Omar Imeri', 'Albania', 'omar imeri'),
	('Rijad Kobiljar', 'Bosnia Herzegovina', 'kobiljar'),
	('Rijad Kobiljar', 'Bosnia Herzegovina', 'rijad kobiljar'),
	('Christian Gauseth', 'Norway', 'gauseth'),
	('Christian Gauseth', 'Norway', 'christian gauseth'),
	('Isaac Nuhu', 'Ghana', 'isaac nuhu'),
	('Isaac Nuhu', 'Ghana', 'nuhu'),
	('Orhan Ademi', 'Switzerland', 'orhan ademi'),
	('Orhan Ademi', 'Switzerland', 'ademi'),
	('Lee Seung Mo', 'Korea Republic', 'mo'),
	('Lee Seung Mo', 'Korea Republic', 'lee seung mo'),
	('Abdulelah Al Amri', 'Saudi Arabia', 'amri'),
	('Abdulelah Al Amri', 'Saudi Arabia', 'abdulelah al amri'),
	('Marc Baró', 'Spain', 'baro'),
	('Marc Baró', 'Spain', 'marc baro'),
	('Erick Wiemberg', 'Chile', 'erick wiemberg'),
	('Erick Wiemberg', 'Chile', 'wiemberg'),
	('Aaron Boupendza', 'Gabon', 'boupendza'),
	('Aaron Boupendza', 'Gabon', 'aaron boupendza'),
	('Sam Lavelle', 'Scotland', 'lavelle'),
	('Sam Lavelle', 'Scotland', 'sam lavelle'),
	('Ilia Gruev', 'Bulgaria', 'ilia gruev'),
	('Ilia Gruev', 'Bulgaria', 'gruev'),
	('Frederik Lach', 'Germany', 'frederik lach'),
	('Frederik Lach', 'Germany', 'lach'),
	('Bryan Figueroa', 'Chile', 'figueroa'),
	('Bryan Figueroa', 'Chile', 'bryan figueroa'),
	('Aaron Lewis', 'Wales', 'aaron lewis'),
	('Aaron Lewis', 'Wales', 'lewis'),
	('Omar Bertel', 'Colombia', 'omar bertel'),
	('Omar Bertel', 'Colombia', 'bertel'),
	('Cody Drameh', 'England', 'cody drameh'),
	('Cody Drameh', 'England', 'drameh'),
	('Kjetil Haug', 'Norway', 'kjetil haug'),
	('Kjetil Haug', 'Norway', 'haug'),
	('Alex Dobre', 'Romania', 'alex dobre'),
	('Alex Dobre', 'Romania', 'dobre'),
	('Toon Raemaekers', 'Belgium', 'raemaekers'),
	('Toon Raemaekers', 'Belgium', 'toon raemaekers'),
	('Sascha Korb', 'Germany', 'sascha korb'),
	('Sascha Korb', 'Germany', 'korb'),
	('Lee Angol', 'England', 'angol'),
	('Lee Angol', 'England', 'lee angol'),
	('Ikuma Sekigawa', 'Japan', 'sekigawa'),
	('Ikuma Sekigawa', 'Japan', 'ikuma sekigawa'),
	('Renzo López', 'Uruguay', 'lopez'),
	('Renzo López', 'Uruguay', 'renzo lopez'),
	('Paul Grauschopf', 'Germany', 'paul grauschopf'),
	('Paul Grauschopf', 'Germany', 'grauschopf'),
	('Andrés Balanta', 'Colombia', 'andres balanta'),
	('Andrés Balanta', 'Colombia', 'balanta'),
	('Alan Virginius', 'France', 'alan virginius'),
	('Alan Virginius', 'France', 'virginius'),
	('Levi Lumeka', 'England', 'lumeka'),
	('Levi Lumeka', 'England', 'levi lumeka'),
	('Faress Al Aiyaf', 'Saudi Arabia', 'aiyaf'),
	('Faress Al Aiyaf', 'Saudi Arabia', 'faress al aiyaf'),
	('André Riel', 'Denmark', 'andre riel'),
	('André Riel', 'Denmark', 'riel'),
	('Boubacar Hanne', 'Portugal', 'boubacar hanne'),
	('Boubacar Hanne', 'Portugal', 'hanne'),
	('Danny Whitehead', 'England', 'danny whitehead'),
	('Danny Whitehead', 'England', 'whitehead'),
	('Wyatt Omsberg', 'United States', 'omsberg'),
	('Wyatt Omsberg', 'United States', 'wyatt omsberg'),
	('Thijs van Leeuwen', 'Netherlands', 'thijs van leeuwen'),
	('Thijs van Leeuwen', 'Netherlands', 'leeuwen'),
	('Benas Satkus', 'Lithuania', 'benas satkus'),
	('Benas Satkus', 'Lithuania', 'satkus'),
	('Valdeci', 'Brazil', 'valdeci'),
	('Admir Bajrovic', 'Sweden', 'bajrovic'),
	('Admir Bajrovic', 'Sweden', 'admir bajrovic'),
	('Lee Chang Yong', 'Korea Republic', 'yong'),
	('Lee Chang Yong', 'Korea Republic', 'lee chang yong'),
	('Pedro Martelo', 'Portugal', 'pedro martelo'),
	('Pedro Martelo', 'Portugal', 'martelo'),
	('Chris Stokes', 'England', 'chris stokes'),
	('Chris Stokes', 'England', 'stokes'),
	('Lukas Gottwalt', 'Germany', 'gottwalt'),
	('Lukas Gottwalt', 'Germany', 'lukas gottwalt'),
	('Alfie McCalmont', 'Northern Ireland', 'alfie mccalmont'),
	('Alfie McCalmont', 'Northern Ireland', 'mccalmont'),
	('Deniz Mehmet', 'Turkey', 'mehmet'),
	('Deniz Mehmet', 'Turkey', 'deniz mehmet'),
	('Noel Knothe', 'Germany', 'noel knothe'),
	('Noel Knothe', 'Germany', 'knothe'),
	('Mauricio Pineda', 'United States', 'mauricio pineda'),
	('Mauricio Pineda', 'United States', 'pineda'),
	('Josh Parker', 'Antigua & Barbuda', 'parker'),
	('Josh Parker', 'Antigua & Barbuda', 'josh parker'),
	('Michael Neill', 'Australia', 'michael neill'),
	('Michael Neill', 'Australia', 'neill'),
	('Karol Niemczycki', 'Poland', 'karol niemczycki'),
	('Karol Niemczycki', 'Poland', 'niemczycki'),
	('Earl Edwards Jr.', 'United States', 'jr'),
	('Earl Edwards Jr.', 'United States', 'earl edwards jr'),
	('Kristers Tobers', 'Latvia', 'kristers tobers'),
	('Kristers Tobers', 'Latvia', 'tobers'),
	('Javi Vázquez', 'Spain', 'vazquez'),
	('Javi Vázquez', 'Spain', 'javi vazquez'),
	('Takuya Uchida', 'Japan', 'uchida'),
	('Takuya Uchida', 'Japan', 'takuya uchida'),
	('Minos Gouras', 'Germany', 'minos gouras'),
	('Minos Gouras', 'Germany', 'gouras'),
	('Park Jun Hui', 'Korea Republic', 'park jun hui'),
	('Park Jun Hui', 'Korea Republic', 'hui'),
	('Hotaka Nakamura', 'Japan', 'hotaka nakamura'),
	('Hotaka Nakamura', 'Japan', 'nakamura'),
	('Jimmy Isita', 'Bolivia', 'isita'),
	('Jimmy Isita', 'Bolivia', 'jimmy isita'),
	('Michael Tørnes', 'Denmark', 'michael trnes'),
	('Michael Tørnes', 'Denmark', 'trnes'),
	('Yanis Ammour', 'France', 'ammour'),
	('Yanis Ammour', 'France', 'yanis ammour'),
	('Callum Guy', 'England', 'guy'),
	('Callum Guy', 'England', 'callum guy'),
	('Josh Doig', 'Scotland', 'doig'),
	('Josh Doig', 'Scotland', 'josh doig'),
	('Alexander Ruud Tveter', 'Norway', 'tveter'),
	('Alexander Ruud Tveter', 'Norway', 'alexander ruud tveter'),
	('Josip Šutalo', 'Croatia', 'sutalo'),
	('Josip Šutalo', 'Croatia', 'josip sutalo'),
	('Bradley Barry', 'England', 'barry'),
	('Bradley Barry', 'England', 'bradley barry'),
	('Kianz Froese', 'Canada', 'kianz froese'),
	('Kianz Froese', 'Canada', 'froese'),
	('Maurício Cortés', 'Colombia', 'cortes'),
	('Maurício Cortés', 'Colombia', 'mauricio cortes'),
	('Ștefan Târnovanu', 'Romania', 'stefan tarnovanu'),
	('Ștefan Târnovanu', 'Romania', 'tarnovanu'),
	('Hallam Hope', 'Barbados', 'hallam hope'),
	('Hallam Hope', 'Barbados', 'hope'),
	('Federico Gattoni', 'Argentina', 'federico gattoni'),
	('Federico Gattoni', 'Argentina', 'gattoni'),
	('Milan Tučić', 'Slovenia', 'tucic'),
	('Milan Tučić', 'Slovenia', 'milan tucic'),
	('Léo Seydoux', 'Switzerland', 'leo seydoux'),
	('Léo Seydoux', 'Switzerland', 'seydoux'),
	('Atakan Gündüz', 'Turkey', 'atakan gunduz'),
	('Atakan Gündüz', 'Turkey', 'gunduz'),
	('Lewis Spence', 'Scotland', 'lewis spence'),
	('Lewis Spence', 'Scotland', 'spence'),
	('Aurélien Nguiamba', 'France', 'nguiamba'),
	('Aurélien Nguiamba', 'France', 'aurelien nguiamba'),
	('Aaron Herzog', 'Germany', 'aaron herzog'),
	('Aaron Herzog', 'Germany', 'herzog'),
	('Luis Sandoval', 'Colombia', 'luis sandoval'),
	('Luis Sandoval', 'Colombia', 'sandoval'),
	('Luiz Júnior', 'Brazil', 'luiz junior'),
	('Luiz Júnior', 'Brazil', 'junior'),
	('Joshua Hare', 'England', 'joshua hare'),
	('Joshua Hare', 'England', 'hare'),
	('Mabrouk Rouai', 'France', 'mabrouk rouai'),
	('Mabrouk Rouai', 'France', 'rouai')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';