INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('André Hainault', 'Canada', 'player'),
	('Ollie Palmer', 'England', 'player'),
	('Mohanad Jeahze', 'Sweden', 'player'),
	('Nahuel Gallardo', 'Argentina', 'player'),
	('Jaylin Lindsey', 'United States', 'player'),
	('Luca Zanimacchia', 'Italy', 'player'),
	('Luis Vasquez', 'Colombia', 'player'),
	('Nick DePuy', 'United States', 'player'),
	('Miguel Nazarit', 'Colombia', 'player'),
	('Ke Zhao', 'China PR', 'player'),
	('Joaquín Piquerez', 'Uruguay', 'player'),
	('Valentino Müller', 'Austria', 'player'),
	('Joël Geissmann', 'Switzerland', 'player'),
	('Nicolai Flø', 'Denmark', 'player'),
	('Kim Jungya', 'Korea Republic', 'player'),
	('Rick Wulle', 'Germany', 'player'),
	('Joe Wright', 'Wales', 'player'),
	('Ilya Gaponov', 'Russia', 'player'),
	('Nathan Delfouneso', 'England', 'player'),
	('Anderson Perea', 'Colombia', 'player'),
	('Liam Roberts', 'England', 'player'),
	('Pedro Simões', 'Portugal', 'player'),
	('Fabricio Díaz', 'Uruguay', 'player'),
	('Calvin Dekuyper', 'Belgium', 'player'),
	('Tomás Sandoval', 'Argentina', 'player'),
	('Sebastian Santin', 'Austria', 'player'),
	('José Cifuentes', 'Ecuador', 'player'),
	('Lautaro Blanco', 'Argentina', 'player'),
	('Leonardo Villar', 'Peru', 'player'),
	('Daiki Kaneko', 'Japan', 'player'),
	('Roberto Romeo', 'Italy', 'player'),
	('Miguel Carranza', 'Peru', 'player'),
	('Julian Justvan', 'Germany', 'player'),
	('Leo Román', 'Spain', 'player'),
	('Lee Ju Yong', 'Korea Republic', 'player'),
	('Olamide Shodipo', 'Republic of Ireland', 'player'),
	('Dany Mota', 'Portugal', 'player'),
	('Edgar Ferreira', 'Paraguay', 'player'),
	('Joan Mazzaco', 'Argentina', 'player'),
	('Teruki Hara', 'Japan', 'player'),
	('Adam Hellborg', 'Sweden', 'player'),
	('Mads Frøkjær-Jensen', 'Denmark', 'player'),
	('Paul Omo Mukairu', 'Nigeria', 'player'),
	('Juergen Farid Elitim', 'Colombia', 'player'),
	('Alan Forrest', 'Scotland', 'player'),
	('Kim Hyun Sung', 'Korea Republic', 'player'),
	('Cristian Montano', 'Colombia', 'player'),
	('Conor Masterson', 'Republic of Ireland', 'player'),
	('James Wilson', 'Wales', 'player'),
	('Oğuz Kağan Güçtekin', 'Turkey', 'player'),
	('Lennerd Daneels', 'Belgium', 'player'),
	('Lee Burge', 'England', 'player'),
	('Bae Jae Woo', 'Korea Republic', 'player'),
	('Juan Pablo Passaglia', 'Argentina', 'player'),
	('Haruki Fukushima', 'Japan', 'player'),
	('Chen Hao', 'China PR', 'player'),
	('Josimar Atoche', 'Peru', 'player'),
	('Cristhian Arabe', 'Bolivia', 'player'),
	('Alexandru Ioniță', 'Romania', 'player'),
	('Erik Domaschke', 'Germany', 'player'),
	('Tobias Raschl', 'Germany', 'player'),
	('Lim Sang Hyub', 'Korea Republic', 'player'),
	('Connor Krempicki', 'Germany', 'player'),
	('Marc Vales', 'Andorra', 'player'),
	('Arda Akbulut', 'Turkey', 'player'),
	('Robbert de Vos', 'Netherlands', 'player'),
	('Cristian Martínez', 'Panama', 'player'),
	('Clemente', 'Spain', 'player'),
	('Fernando Arce', 'United States', 'player'),
	('Cristian Cherchez', 'Romania', 'player'),
	('Pedro Marques', 'Portugal', 'player'),
	('Agustín Dávila', 'Uruguay', 'player'),
	('Tymoteusz Klupś', 'Poland', 'player'),
	('Élie Youan', 'France', 'player'),
	('Marvin Thiel', 'Germany', 'player'),
	('Andrés Chicaiza', 'Ecuador', 'player'),
	('Cristian Neguț', 'Romania', 'player'),
	('Diego Armas', 'Ecuador', 'player'),
	('Mehmet Kurt', 'Germany', 'player'),
	('Mihai Neicuțescu', 'Romania', 'player'),
	('Paul Arano', 'Bolivia', 'player'),
	('Sibiry Keita', 'Mali', 'player'),
	('Dean Huiberts', 'Netherlands', 'player'),
	('Nahom Girmai Netabay', 'Sweden', 'player'),
	('Igor Armaș', 'Moldova', 'player'),
	('Lionel Mpasi', 'France', 'player'),
	('Jason Hoffman', 'Australia', 'player'),
	('Ian González', 'Spain', 'player'),
	('Aljaž Ivačič', 'Slovenia', 'player'),
	('Pol Lozano', 'Spain', 'player'),
	('Kim Won Sik', 'Korea Republic', 'player'),
	('Lee Bum Soo', 'Korea Republic', 'player'),
	('James Perch', 'England', 'player'),
	('Kees de Boer', 'Netherlands', 'player'),
	('Ryuho Kikuchi', 'Japan', 'player'),
	('Ben Gladwin', 'England', 'player'),
	('Charles-Andreas Brym', 'Canada', 'player'),
	('Isaac Lihadji', 'France', 'player'),
	('Martin Sourzac', 'France', 'player'),
	('Markus Scholz', 'Germany', 'player'),
	('Paul Smyth', 'Northern Ireland', 'player'),
	('Erlend Dahl Reitan', 'Norway', 'player'),
	('Idrissa Touré', 'Germany', 'player'),
	('Angel Ojeda', 'Peru', 'player'),
	('Lee Bum Young', 'Korea Republic', 'player'),
	('Caleb Stanko', 'United States', 'player'),
	('Ahmet Muhamedbegovic', 'Austria', 'player'),
	('Rasmus Thellufsen', 'Denmark', 'player'),
	('Michael Lansing', 'United States', 'player'),
	('Marek Štěch', 'Czech Republic', 'player'),
	('Edvinas Girdvainis', 'Lithuania', 'player'),
	('Lorenzo Del Pinto', 'Italy', 'player'),
	('Sergio Lozano', 'Spain', 'player'),
	('George Williams', 'England', 'player'),
	('Tom Hopper', 'England', 'player'),
	('Joackim Olsen Solberg', 'Norway', 'player'),
	('Rory Holden', 'Northern Ireland', 'player'),
	('Santiago Ormeño', 'Mexico', 'player'),
	('Takahiro Yanagi', 'Japan', 'player'),
	('Nathan Smith', 'England', 'player'),
	('Nazareno Bazan', 'Argentina', 'player'),
	('Markus Kaasa', 'Norway', 'player'),
	('Ethan Galbraith', 'Northern Ireland', 'player'),
	('Andreas Blomqvist', 'Sweden', 'player'),
	('Ayoub Abdellaoui', 'Algeria', 'player'),
	('Javi Rubio', 'Spain', 'player'),
	('Diego Vicente', 'Uruguay', 'player'),
	('Shaun Rooney', 'Scotland', 'player'),
	('Rod McDonald', 'England', 'player'),
	('Khaled Al Kaabi', 'Saudi Arabia', 'player'),
	('Florian Faist', 'Austria', 'player'),
	('Jevani Brown', 'Jamaica', 'player'),
	('Gergő Kocsis', 'Hungary', 'player'),
	('Lasse Sørensen', 'Denmark', 'player'),
	('André Mesquita', 'Portugal', 'player'),
	('Daniel Șerbănică', 'Romania', 'player'),
	('Scott Galloway', 'Australia', 'player'),
	('Ewan Henderson', 'Scotland', 'player'),
	('Cesar Taborda', 'Argentina', 'player'),
	('Moon Chang Jin', 'Korea Republic', 'player'),
	('Dominic Volkmer', 'Germany', 'player'),
	('Seth Paintsil', 'Ghana', 'player'),
	('Gustaf Nilsson', 'Sweden', 'player'),
	('Cameron Pring', 'England', 'player'),
	('Leo Greiml', 'Austria', 'player'),
	('Andrés Veizaga', 'Bolivia', 'player'),
	('Largie Ramazani', 'Belgium', 'player'),
	('Ahmed Abdu', 'Saudi Arabia', 'player'),
	('Adrián Szőke', 'Hungary', 'player'),
	('Joaquín Fernández', 'Uruguay', 'player'),
	('Adriano Grimaldi', 'Germany', 'player'),
	('Jannik Pohl', 'Denmark', 'player'),
	('Mert Yılmaz', 'Germany', 'player'),
	('Ryan Sears', 'Wales', 'player'),
	('Cameron Burgess', 'Australia', 'player'),
	('Jesper Lindstrøm', 'Denmark', 'player'),
	('Loïc Kouagba', 'France', 'player'),
	('Jan Elvedi', 'Switzerland', 'player'),
	('Miullen', 'Brazil', 'player'),
	('Ed Upson', 'England', 'player'),
	('Ole Käuper', 'Germany', 'player'),
	('Andrei Blejdea', 'Romania', 'player'),
	('Atakan Akkaynak', 'Germany', 'player'),
	('Jung San', 'Korea Republic', 'player'),
	('Kim Jun Yub', 'Korea Republic', 'player'),
	('Liam Kinsella', 'Republic of Ireland', 'player'),
	('Michael Ratajczak', 'Germany', 'player'),
	('Abu Danladi', 'Ghana', 'player'),
	('Francisco Grahl', 'Argentina', 'player'),
	('Abdulrahman Ghareeb', 'Saudi Arabia', 'player'),
	('CJ Hamilton', 'England', 'player'),
	('Kamil Kościelny', 'Poland', 'player'),
	('Niall Ennis', 'England', 'player'),
	('Berto Hórreo', 'Spain', 'player'),
	('Jakub Łabojko', 'Poland', 'player'),
	('Juan José Franco', 'Paraguay', 'player'),
	('Jean-Philippe Krasso', 'France', 'player'),
	('Hwang Soon Min', 'Korea Republic', 'player'),
	('Kornel Osyra', 'Poland', 'player'),
	('Marko Johansson', 'Sweden', 'player'),
	('Lucas Algozino', 'Argentina', 'player'),
	('Felix Schröter', 'Germany', 'player'),
	('Unai Etxebarría', 'Spain', 'player'),
	('George Thomas', 'Wales', 'player'),
	('Franco Bustamante', 'Argentina', 'player'),
	('Mihai Leca', 'Romania', 'player'),
	('Simon Elisor', 'France', 'player'),
	('Tom Bayliss', 'England', 'player'),
	('Thibault Vialla', 'France', 'player'),
	('Bruce Kamau', 'Australia', 'player'),
	('Diego Ferraresso', 'Bulgaria', 'player'),
	('Joakim Våge Nilsen', 'Norway', 'player'),
	('Luke O''Neill', 'England', 'player'),
	('Flavius Croitoru', 'Romania', 'player'),
	('Tahiru Awudu', 'Ghana', 'player'),
	('Liam Ridehalgh', 'England', 'player'),
	('Juan Cruz Bolado', 'Argentina', 'player'),
	('Lucas Chacana', 'Argentina', 'player'),
	('Sondre Sørli', 'Norway', 'player'),
	('Florin Achim', 'Romania', 'player'),
	('Paul Farman', 'England', 'player'),
	('Yannick Deichmann', 'Germany', 'player'),
	('Kiichi Yajima', 'Japan', 'player'),
	('Alfie Whiteman', 'England', 'player'),
	('Khaled Al Barakah', 'Saudi Arabia', 'player'),
	('Ben Kantie Karamoko', 'Ivory Coast', 'player'),
	('Maxence Derrien', 'France', 'player'),
	('José Monaga', 'Ecuador', 'player'),
	('Dru Yearwood', 'England', 'player'),
	('Brayan Hurtado', 'Venezuela', 'player'),
	('Andrei Tofan', 'Romania', 'player'),
	('Danzell Gravenberch', 'Netherlands', 'player'),
	('Séga Coulibaly', 'France', 'player'),
	('Maxime Biamou', 'France', 'player'),
	('Jon Gallagher', 'Republic of Ireland', 'player'),
	('Immanuel Pherai', 'Netherlands', 'player'),
	('João Mendes', 'Portugal', 'player'),
	('Fredrik Torsteinbø', 'Norway', 'player'),
	('Gerardo Moreno', 'Mexico', 'player'),
	('Pascal Gregor', 'Denmark', 'player'),
	('Ernesto Goñi', 'Uruguay', 'player'),
	('Jacob Storevik', 'Norway', 'player'),
	('Leandro Putaro', 'Germany', 'player'),
	('Mario Stefel', 'Austria', 'player'),
	('Ryutaro Iio', 'Japan', 'player'),
	('Marcelo Freites', 'Argentina', 'player'),
	('Conor Grant', 'England', 'player'),
	('Ali Yasar', 'Belgium', 'player'),
	('Jay Chapman', 'Canada', 'player'),
	('Marcos Barrera', 'Argentina', 'player'),
	('Merveille Goblet', 'Belgium', 'player'),
	('Victor Rîmniceanu', 'Romania', 'player'),
	('Peter Orry Larsen', 'Norway', 'player'),
	('Gary Rogers', 'Republic of Ireland', 'player'),
	('Scott Davies', 'England', 'player'),
	('Utku Yuvakuran', 'Turkey', 'player'),
	('Charles Dunne', 'Republic of Ireland', 'player'),
	('Kyle Knoyle', 'England', 'player'),
	('Rory McArdle', 'Northern Ireland', 'player'),
	('Medhy Guezoui', 'France', 'player'),
	('Enes Sağlık', 'Belgium', 'player'),
	('Iñaki Álvarez', 'Spain', 'player'),
	('Johan Mårtensson', 'Sweden', 'player'),
	('Park Jeong Su', 'Korea Republic', 'player'),
	('Kieran Wallace', 'England', 'player'),
	('Omir Fernandez', 'United States', 'player'),
	('Philipp Erhardt', 'Austria', 'player'),
	('Adrian Stanilewicz', 'Poland', 'player'),
	('Alessandro Buongiorno', 'Italy', 'player'),
	('Mohamed Coulibaly', 'Senegal', 'player');

WITH v(name, cat, alias) AS (VALUES
	('André Hainault', 'Canada', 'hainault'),
	('André Hainault', 'Canada', 'andre hainault'),
	('Ollie Palmer', 'England', 'palmer'),
	('Ollie Palmer', 'England', 'ollie palmer'),
	('Mohanad Jeahze', 'Sweden', 'jeahze'),
	('Mohanad Jeahze', 'Sweden', 'mohanad jeahze'),
	('Nahuel Gallardo', 'Argentina', 'nahuel gallardo'),
	('Nahuel Gallardo', 'Argentina', 'gallardo'),
	('Jaylin Lindsey', 'United States', 'jaylin lindsey'),
	('Jaylin Lindsey', 'United States', 'lindsey'),
	('Luca Zanimacchia', 'Italy', 'luca zanimacchia'),
	('Luca Zanimacchia', 'Italy', 'zanimacchia'),
	('Luis Vasquez', 'Colombia', 'vasquez'),
	('Luis Vasquez', 'Colombia', 'luis vasquez'),
	('Nick DePuy', 'United States', 'depuy'),
	('Nick DePuy', 'United States', 'nick depuy'),
	('Miguel Nazarit', 'Colombia', 'nazarit'),
	('Miguel Nazarit', 'Colombia', 'miguel nazarit'),
	('Ke Zhao', 'China PR', 'zhao'),
	('Ke Zhao', 'China PR', 'ke zhao'),
	('Joaquín Piquerez', 'Uruguay', 'joaquin piquerez'),
	('Joaquín Piquerez', 'Uruguay', 'piquerez'),
	('Valentino Müller', 'Austria', 'valentino muller'),
	('Valentino Müller', 'Austria', 'muller'),
	('Joël Geissmann', 'Switzerland', 'geissmann'),
	('Joël Geissmann', 'Switzerland', 'joel geissmann'),
	('Nicolai Flø', 'Denmark', 'fl'),
	('Nicolai Flø', 'Denmark', 'nicolai fl'),
	('Kim Jungya', 'Korea Republic', 'jungya'),
	('Kim Jungya', 'Korea Republic', 'kim jungya'),
	('Rick Wulle', 'Germany', 'wulle'),
	('Rick Wulle', 'Germany', 'rick wulle'),
	('Joe Wright', 'Wales', 'joe wright'),
	('Joe Wright', 'Wales', 'wright'),
	('Ilya Gaponov', 'Russia', 'ilya gaponov'),
	('Ilya Gaponov', 'Russia', 'gaponov'),
	('Nathan Delfouneso', 'England', 'delfouneso'),
	('Nathan Delfouneso', 'England', 'nathan delfouneso'),
	('Anderson Perea', 'Colombia', 'anderson perea'),
	('Anderson Perea', 'Colombia', 'perea'),
	('Liam Roberts', 'England', 'liam roberts'),
	('Liam Roberts', 'England', 'roberts'),
	('Pedro Simões', 'Portugal', 'pedro simoes'),
	('Pedro Simões', 'Portugal', 'simoes'),
	('Fabricio Díaz', 'Uruguay', 'diaz'),
	('Fabricio Díaz', 'Uruguay', 'fabricio diaz'),
	('Calvin Dekuyper', 'Belgium', 'dekuyper'),
	('Calvin Dekuyper', 'Belgium', 'calvin dekuyper'),
	('Tomás Sandoval', 'Argentina', 'sandoval'),
	('Tomás Sandoval', 'Argentina', 'tomas sandoval'),
	('Sebastian Santin', 'Austria', 'sebastian santin'),
	('Sebastian Santin', 'Austria', 'santin'),
	('José Cifuentes', 'Ecuador', 'cifuentes'),
	('José Cifuentes', 'Ecuador', 'jose cifuentes'),
	('Lautaro Blanco', 'Argentina', 'lautaro blanco'),
	('Lautaro Blanco', 'Argentina', 'blanco'),
	('Leonardo Villar', 'Peru', 'villar'),
	('Leonardo Villar', 'Peru', 'leonardo villar'),
	('Daiki Kaneko', 'Japan', 'kaneko'),
	('Daiki Kaneko', 'Japan', 'daiki kaneko'),
	('Roberto Romeo', 'Italy', 'roberto romeo'),
	('Roberto Romeo', 'Italy', 'romeo'),
	('Miguel Carranza', 'Peru', 'carranza'),
	('Miguel Carranza', 'Peru', 'miguel carranza'),
	('Julian Justvan', 'Germany', 'justvan'),
	('Julian Justvan', 'Germany', 'julian justvan'),
	('Leo Román', 'Spain', 'roman'),
	('Leo Román', 'Spain', 'leo roman'),
	('Lee Ju Yong', 'Korea Republic', 'yong'),
	('Lee Ju Yong', 'Korea Republic', 'lee ju yong'),
	('Olamide Shodipo', 'Republic of Ireland', 'shodipo'),
	('Olamide Shodipo', 'Republic of Ireland', 'olamide shodipo'),
	('Dany Mota', 'Portugal', 'dany mota'),
	('Dany Mota', 'Portugal', 'mota'),
	('Edgar Ferreira', 'Paraguay', 'edgar ferreira'),
	('Edgar Ferreira', 'Paraguay', 'ferreira'),
	('Joan Mazzaco', 'Argentina', 'joan mazzaco'),
	('Joan Mazzaco', 'Argentina', 'mazzaco'),
	('Teruki Hara', 'Japan', 'teruki hara'),
	('Teruki Hara', 'Japan', 'hara'),
	('Adam Hellborg', 'Sweden', 'hellborg'),
	('Adam Hellborg', 'Sweden', 'adam hellborg'),
	('Mads Frøkjær-Jensen', 'Denmark', 'mads frkjrjensen'),
	('Mads Frøkjær-Jensen', 'Denmark', 'frkjrjensen'),
	('Paul Omo Mukairu', 'Nigeria', 'mukairu'),
	('Paul Omo Mukairu', 'Nigeria', 'paul omo mukairu'),
	('Juergen Farid Elitim', 'Colombia', 'juergen farid elitim'),
	('Juergen Farid Elitim', 'Colombia', 'elitim'),
	('Alan Forrest', 'Scotland', 'forrest'),
	('Alan Forrest', 'Scotland', 'alan forrest'),
	('Kim Hyun Sung', 'Korea Republic', 'sung'),
	('Kim Hyun Sung', 'Korea Republic', 'kim hyun sung'),
	('Cristian Montano', 'Colombia', 'cristian montano'),
	('Cristian Montano', 'Colombia', 'montano'),
	('Conor Masterson', 'Republic of Ireland', 'masterson'),
	('Conor Masterson', 'Republic of Ireland', 'conor masterson'),
	('James Wilson', 'Wales', 'wilson'),
	('James Wilson', 'Wales', 'james wilson'),
	('Oğuz Kağan Güçtekin', 'Turkey', 'guctekin'),
	('Oğuz Kağan Güçtekin', 'Turkey', 'oguz kagan guctekin'),
	('Lennerd Daneels', 'Belgium', 'lennerd daneels'),
	('Lennerd Daneels', 'Belgium', 'daneels'),
	('Lee Burge', 'England', 'burge'),
	('Lee Burge', 'England', 'lee burge'),
	('Bae Jae Woo', 'Korea Republic', 'bae jae woo'),
	('Bae Jae Woo', 'Korea Republic', 'woo'),
	('Juan Pablo Passaglia', 'Argentina', 'juan pablo passaglia'),
	('Juan Pablo Passaglia', 'Argentina', 'passaglia'),
	('Haruki Fukushima', 'Japan', 'haruki fukushima'),
	('Haruki Fukushima', 'Japan', 'fukushima'),
	('Chen Hao', 'China PR', 'hao'),
	('Chen Hao', 'China PR', 'chen hao'),
	('Josimar Atoche', 'Peru', 'josimar atoche'),
	('Josimar Atoche', 'Peru', 'atoche'),
	('Cristhian Arabe', 'Bolivia', 'arabe'),
	('Cristhian Arabe', 'Bolivia', 'cristhian arabe'),
	('Alexandru Ioniță', 'Romania', 'alexandru ionita'),
	('Alexandru Ioniță', 'Romania', 'ionita'),
	('Erik Domaschke', 'Germany', 'domaschke'),
	('Erik Domaschke', 'Germany', 'erik domaschke'),
	('Tobias Raschl', 'Germany', 'tobias raschl'),
	('Tobias Raschl', 'Germany', 'raschl'),
	('Lim Sang Hyub', 'Korea Republic', 'lim sang hyub'),
	('Lim Sang Hyub', 'Korea Republic', 'hyub'),
	('Connor Krempicki', 'Germany', 'connor krempicki'),
	('Connor Krempicki', 'Germany', 'krempicki'),
	('Marc Vales', 'Andorra', 'marc vales'),
	('Marc Vales', 'Andorra', 'vales'),
	('Arda Akbulut', 'Turkey', 'arda akbulut'),
	('Arda Akbulut', 'Turkey', 'akbulut'),
	('Robbert de Vos', 'Netherlands', 'robbert de vos'),
	('Robbert de Vos', 'Netherlands', 'vos'),
	('Cristian Martínez', 'Panama', 'martinez'),
	('Cristian Martínez', 'Panama', 'cristian martinez'),
	('Clemente', 'Spain', 'clemente'),
	('Fernando Arce', 'United States', 'fernando arce'),
	('Fernando Arce', 'United States', 'arce'),
	('Cristian Cherchez', 'Romania', 'cristian cherchez'),
	('Cristian Cherchez', 'Romania', 'cherchez'),
	('Pedro Marques', 'Portugal', 'pedro marques'),
	('Pedro Marques', 'Portugal', 'marques'),
	('Agustín Dávila', 'Uruguay', 'agustin davila'),
	('Agustín Dávila', 'Uruguay', 'davila'),
	('Tymoteusz Klupś', 'Poland', 'tymoteusz klups'),
	('Tymoteusz Klupś', 'Poland', 'klups'),
	('Élie Youan', 'France', 'elie youan'),
	('Élie Youan', 'France', 'youan'),
	('Marvin Thiel', 'Germany', 'marvin thiel'),
	('Marvin Thiel', 'Germany', 'thiel'),
	('Andrés Chicaiza', 'Ecuador', 'chicaiza'),
	('Andrés Chicaiza', 'Ecuador', 'andres chicaiza'),
	('Cristian Neguț', 'Romania', 'cristian negut'),
	('Cristian Neguț', 'Romania', 'negut'),
	('Diego Armas', 'Ecuador', 'diego armas'),
	('Diego Armas', 'Ecuador', 'armas'),
	('Mehmet Kurt', 'Germany', 'kurt'),
	('Mehmet Kurt', 'Germany', 'mehmet kurt'),
	('Mihai Neicuțescu', 'Romania', 'mihai neicutescu'),
	('Mihai Neicuțescu', 'Romania', 'neicutescu'),
	('Paul Arano', 'Bolivia', 'arano'),
	('Paul Arano', 'Bolivia', 'paul arano'),
	('Sibiry Keita', 'Mali', 'sibiry keita'),
	('Sibiry Keita', 'Mali', 'keita'),
	('Dean Huiberts', 'Netherlands', 'huiberts'),
	('Dean Huiberts', 'Netherlands', 'dean huiberts'),
	('Nahom Girmai Netabay', 'Sweden', 'netabay'),
	('Nahom Girmai Netabay', 'Sweden', 'nahom girmai netabay'),
	('Igor Armaș', 'Moldova', 'igor armas'),
	('Igor Armaș', 'Moldova', 'armas'),
	('Lionel Mpasi', 'France', 'mpasi'),
	('Lionel Mpasi', 'France', 'lionel mpasi'),
	('Jason Hoffman', 'Australia', 'hoffman'),
	('Jason Hoffman', 'Australia', 'jason hoffman'),
	('Ian González', 'Spain', 'gonzalez'),
	('Ian González', 'Spain', 'ian gonzalez'),
	('Aljaž Ivačič', 'Slovenia', 'ivacic'),
	('Aljaž Ivačič', 'Slovenia', 'aljaz ivacic'),
	('Pol Lozano', 'Spain', 'lozano'),
	('Pol Lozano', 'Spain', 'pol lozano'),
	('Kim Won Sik', 'Korea Republic', 'kim won sik'),
	('Kim Won Sik', 'Korea Republic', 'sik'),
	('Lee Bum Soo', 'Korea Republic', 'soo'),
	('Lee Bum Soo', 'Korea Republic', 'lee bum soo'),
	('James Perch', 'England', 'james perch'),
	('James Perch', 'England', 'perch'),
	('Kees de Boer', 'Netherlands', 'boer'),
	('Kees de Boer', 'Netherlands', 'kees de boer'),
	('Ryuho Kikuchi', 'Japan', 'ryuho kikuchi'),
	('Ryuho Kikuchi', 'Japan', 'kikuchi'),
	('Ben Gladwin', 'England', 'gladwin'),
	('Ben Gladwin', 'England', 'ben gladwin'),
	('Charles-Andreas Brym', 'Canada', 'brym'),
	('Charles-Andreas Brym', 'Canada', 'charlesandreas brym'),
	('Isaac Lihadji', 'France', 'isaac lihadji'),
	('Isaac Lihadji', 'France', 'lihadji'),
	('Martin Sourzac', 'France', 'martin sourzac'),
	('Martin Sourzac', 'France', 'sourzac'),
	('Markus Scholz', 'Germany', 'scholz'),
	('Markus Scholz', 'Germany', 'markus scholz'),
	('Paul Smyth', 'Northern Ireland', 'smyth'),
	('Paul Smyth', 'Northern Ireland', 'paul smyth'),
	('Erlend Dahl Reitan', 'Norway', 'erlend dahl reitan'),
	('Erlend Dahl Reitan', 'Norway', 'reitan'),
	('Idrissa Touré', 'Germany', 'toure'),
	('Idrissa Touré', 'Germany', 'idrissa toure'),
	('Angel Ojeda', 'Peru', 'angel ojeda'),
	('Angel Ojeda', 'Peru', 'ojeda'),
	('Lee Bum Young', 'Korea Republic', 'young'),
	('Lee Bum Young', 'Korea Republic', 'lee bum young'),
	('Caleb Stanko', 'United States', 'caleb stanko'),
	('Caleb Stanko', 'United States', 'stanko'),
	('Ahmet Muhamedbegovic', 'Austria', 'ahmet muhamedbegovic'),
	('Ahmet Muhamedbegovic', 'Austria', 'muhamedbegovic'),
	('Rasmus Thellufsen', 'Denmark', 'thellufsen'),
	('Rasmus Thellufsen', 'Denmark', 'rasmus thellufsen'),
	('Michael Lansing', 'United States', 'michael lansing'),
	('Michael Lansing', 'United States', 'lansing'),
	('Marek Štěch', 'Czech Republic', 'stech'),
	('Marek Štěch', 'Czech Republic', 'marek stech'),
	('Edvinas Girdvainis', 'Lithuania', 'girdvainis'),
	('Edvinas Girdvainis', 'Lithuania', 'edvinas girdvainis'),
	('Lorenzo Del Pinto', 'Italy', 'lorenzo del pinto'),
	('Lorenzo Del Pinto', 'Italy', 'pinto'),
	('Sergio Lozano', 'Spain', 'lozano'),
	('Sergio Lozano', 'Spain', 'sergio lozano'),
	('George Williams', 'England', 'george williams'),
	('George Williams', 'England', 'williams'),
	('Tom Hopper', 'England', 'hopper'),
	('Tom Hopper', 'England', 'tom hopper'),
	('Joackim Olsen Solberg', 'Norway', 'joackim olsen solberg'),
	('Joackim Olsen Solberg', 'Norway', 'solberg'),
	('Rory Holden', 'Northern Ireland', 'rory holden'),
	('Rory Holden', 'Northern Ireland', 'holden'),
	('Santiago Ormeño', 'Mexico', 'ormeno'),
	('Santiago Ormeño', 'Mexico', 'santiago ormeno'),
	('Takahiro Yanagi', 'Japan', 'takahiro yanagi'),
	('Takahiro Yanagi', 'Japan', 'yanagi'),
	('Nathan Smith', 'England', 'smith'),
	('Nathan Smith', 'England', 'nathan smith'),
	('Nazareno Bazan', 'Argentina', 'nazareno bazan'),
	('Nazareno Bazan', 'Argentina', 'bazan'),
	('Markus Kaasa', 'Norway', 'markus kaasa'),
	('Markus Kaasa', 'Norway', 'kaasa'),
	('Ethan Galbraith', 'Northern Ireland', 'ethan galbraith'),
	('Ethan Galbraith', 'Northern Ireland', 'galbraith'),
	('Andreas Blomqvist', 'Sweden', 'andreas blomqvist'),
	('Andreas Blomqvist', 'Sweden', 'blomqvist'),
	('Ayoub Abdellaoui', 'Algeria', 'abdellaoui'),
	('Ayoub Abdellaoui', 'Algeria', 'ayoub abdellaoui'),
	('Javi Rubio', 'Spain', 'rubio'),
	('Javi Rubio', 'Spain', 'javi rubio'),
	('Diego Vicente', 'Uruguay', 'diego vicente'),
	('Diego Vicente', 'Uruguay', 'vicente'),
	('Shaun Rooney', 'Scotland', 'shaun rooney'),
	('Shaun Rooney', 'Scotland', 'rooney'),
	('Rod McDonald', 'England', 'rod mcdonald'),
	('Rod McDonald', 'England', 'mcdonald'),
	('Khaled Al Kaabi', 'Saudi Arabia', 'khaled al kaabi'),
	('Khaled Al Kaabi', 'Saudi Arabia', 'kaabi'),
	('Florian Faist', 'Austria', 'faist'),
	('Florian Faist', 'Austria', 'florian faist'),
	('Jevani Brown', 'Jamaica', 'brown'),
	('Jevani Brown', 'Jamaica', 'jevani brown'),
	('Gergő Kocsis', 'Hungary', 'gergo kocsis'),
	('Gergő Kocsis', 'Hungary', 'kocsis'),
	('Lasse Sørensen', 'Denmark', 'srensen'),
	('Lasse Sørensen', 'Denmark', 'lasse srensen'),
	('André Mesquita', 'Portugal', 'andre mesquita'),
	('André Mesquita', 'Portugal', 'mesquita'),
	('Daniel Șerbănică', 'Romania', 'serbanica'),
	('Daniel Șerbănică', 'Romania', 'daniel serbanica'),
	('Scott Galloway', 'Australia', 'scott galloway'),
	('Scott Galloway', 'Australia', 'galloway'),
	('Ewan Henderson', 'Scotland', 'ewan henderson'),
	('Ewan Henderson', 'Scotland', 'henderson'),
	('Cesar Taborda', 'Argentina', 'taborda'),
	('Cesar Taborda', 'Argentina', 'cesar taborda'),
	('Moon Chang Jin', 'Korea Republic', 'jin'),
	('Moon Chang Jin', 'Korea Republic', 'moon chang jin'),
	('Dominic Volkmer', 'Germany', 'volkmer'),
	('Dominic Volkmer', 'Germany', 'dominic volkmer'),
	('Seth Paintsil', 'Ghana', 'seth paintsil'),
	('Seth Paintsil', 'Ghana', 'paintsil'),
	('Gustaf Nilsson', 'Sweden', 'gustaf nilsson'),
	('Gustaf Nilsson', 'Sweden', 'nilsson'),
	('Cameron Pring', 'England', 'cameron pring'),
	('Cameron Pring', 'England', 'pring'),
	('Leo Greiml', 'Austria', 'leo greiml'),
	('Leo Greiml', 'Austria', 'greiml'),
	('Andrés Veizaga', 'Bolivia', 'andres veizaga'),
	('Andrés Veizaga', 'Bolivia', 'veizaga'),
	('Largie Ramazani', 'Belgium', 'ramazani'),
	('Largie Ramazani', 'Belgium', 'largie ramazani'),
	('Ahmed Abdu', 'Saudi Arabia', 'ahmed abdu'),
	('Ahmed Abdu', 'Saudi Arabia', 'abdu'),
	('Adrián Szőke', 'Hungary', 'szoke'),
	('Adrián Szőke', 'Hungary', 'adrian szoke'),
	('Joaquín Fernández', 'Uruguay', 'fernandez'),
	('Joaquín Fernández', 'Uruguay', 'joaquin fernandez'),
	('Adriano Grimaldi', 'Germany', 'adriano grimaldi'),
	('Adriano Grimaldi', 'Germany', 'grimaldi'),
	('Jannik Pohl', 'Denmark', 'pohl'),
	('Jannik Pohl', 'Denmark', 'jannik pohl'),
	('Mert Yılmaz', 'Germany', 'ylmaz'),
	('Mert Yılmaz', 'Germany', 'mert ylmaz'),
	('Ryan Sears', 'Wales', 'ryan sears'),
	('Ryan Sears', 'Wales', 'sears'),
	('Cameron Burgess', 'Australia', 'cameron burgess'),
	('Cameron Burgess', 'Australia', 'burgess'),
	('Jesper Lindstrøm', 'Denmark', 'jesper lindstrm'),
	('Jesper Lindstrøm', 'Denmark', 'lindstrm'),
	('Loïc Kouagba', 'France', 'kouagba'),
	('Loïc Kouagba', 'France', 'loic kouagba'),
	('Jan Elvedi', 'Switzerland', 'elvedi'),
	('Jan Elvedi', 'Switzerland', 'jan elvedi'),
	('Miullen', 'Brazil', 'miullen'),
	('Ed Upson', 'England', 'ed upson'),
	('Ed Upson', 'England', 'upson'),
	('Ole Käuper', 'Germany', 'ole kauper'),
	('Ole Käuper', 'Germany', 'kauper'),
	('Andrei Blejdea', 'Romania', 'andrei blejdea'),
	('Andrei Blejdea', 'Romania', 'blejdea'),
	('Atakan Akkaynak', 'Germany', 'akkaynak'),
	('Atakan Akkaynak', 'Germany', 'atakan akkaynak'),
	('Jung San', 'Korea Republic', 'san'),
	('Jung San', 'Korea Republic', 'jung san'),
	('Kim Jun Yub', 'Korea Republic', 'yub'),
	('Kim Jun Yub', 'Korea Republic', 'kim jun yub'),
	('Liam Kinsella', 'Republic of Ireland', 'liam kinsella'),
	('Liam Kinsella', 'Republic of Ireland', 'kinsella'),
	('Michael Ratajczak', 'Germany', 'ratajczak'),
	('Michael Ratajczak', 'Germany', 'michael ratajczak'),
	('Abu Danladi', 'Ghana', 'danladi'),
	('Abu Danladi', 'Ghana', 'abu danladi'),
	('Francisco Grahl', 'Argentina', 'grahl'),
	('Francisco Grahl', 'Argentina', 'francisco grahl'),
	('Abdulrahman Ghareeb', 'Saudi Arabia', 'ghareeb'),
	('Abdulrahman Ghareeb', 'Saudi Arabia', 'abdulrahman ghareeb'),
	('CJ Hamilton', 'England', 'hamilton'),
	('CJ Hamilton', 'England', 'cj hamilton'),
	('Kamil Kościelny', 'Poland', 'kamil koscielny'),
	('Kamil Kościelny', 'Poland', 'koscielny'),
	('Niall Ennis', 'England', 'niall ennis'),
	('Niall Ennis', 'England', 'ennis'),
	('Berto Hórreo', 'Spain', 'horreo'),
	('Berto Hórreo', 'Spain', 'berto horreo'),
	('Jakub Łabojko', 'Poland', 'jakub abojko'),
	('Jakub Łabojko', 'Poland', 'abojko'),
	('Juan José Franco', 'Paraguay', 'juan jose franco'),
	('Juan José Franco', 'Paraguay', 'franco'),
	('Jean-Philippe Krasso', 'France', 'krasso'),
	('Jean-Philippe Krasso', 'France', 'jeanphilippe krasso'),
	('Hwang Soon Min', 'Korea Republic', 'hwang soon min'),
	('Hwang Soon Min', 'Korea Republic', 'min'),
	('Kornel Osyra', 'Poland', 'kornel osyra'),
	('Kornel Osyra', 'Poland', 'osyra'),
	('Marko Johansson', 'Sweden', 'johansson'),
	('Marko Johansson', 'Sweden', 'marko johansson'),
	('Lucas Algozino', 'Argentina', 'lucas algozino'),
	('Lucas Algozino', 'Argentina', 'algozino'),
	('Felix Schröter', 'Germany', 'schroter'),
	('Felix Schröter', 'Germany', 'felix schroter'),
	('Unai Etxebarría', 'Spain', 'etxebarria'),
	('Unai Etxebarría', 'Spain', 'unai etxebarria'),
	('George Thomas', 'Wales', 'thomas'),
	('George Thomas', 'Wales', 'george thomas'),
	('Franco Bustamante', 'Argentina', 'bustamante'),
	('Franco Bustamante', 'Argentina', 'franco bustamante'),
	('Mihai Leca', 'Romania', 'mihai leca'),
	('Mihai Leca', 'Romania', 'leca'),
	('Simon Elisor', 'France', 'elisor'),
	('Simon Elisor', 'France', 'simon elisor'),
	('Tom Bayliss', 'England', 'tom bayliss'),
	('Tom Bayliss', 'England', 'bayliss'),
	('Thibault Vialla', 'France', 'thibault vialla'),
	('Thibault Vialla', 'France', 'vialla'),
	('Bruce Kamau', 'Australia', 'kamau'),
	('Bruce Kamau', 'Australia', 'bruce kamau'),
	('Diego Ferraresso', 'Bulgaria', 'ferraresso'),
	('Diego Ferraresso', 'Bulgaria', 'diego ferraresso'),
	('Joakim Våge Nilsen', 'Norway', 'nilsen'),
	('Joakim Våge Nilsen', 'Norway', 'joakim vage nilsen'),
	('Luke O''Neill', 'England', 'luke oneill'),
	('Luke O''Neill', 'England', 'oneill'),
	('Flavius Croitoru', 'Romania', 'croitoru'),
	('Flavius Croitoru', 'Romania', 'flavius croitoru'),
	('Tahiru Awudu', 'Ghana', 'awudu'),
	('Tahiru Awudu', 'Ghana', 'tahiru awudu'),
	('Liam Ridehalgh', 'England', 'ridehalgh'),
	('Liam Ridehalgh', 'England', 'liam ridehalgh'),
	('Juan Cruz Bolado', 'Argentina', 'bolado'),
	('Juan Cruz Bolado', 'Argentina', 'juan cruz bolado'),
	('Lucas Chacana', 'Argentina', 'chacana'),
	('Lucas Chacana', 'Argentina', 'lucas chacana'),
	('Sondre Sørli', 'Norway', 'sondre srli'),
	('Sondre Sørli', 'Norway', 'srli'),
	('Florin Achim', 'Romania', 'achim'),
	('Florin Achim', 'Romania', 'florin achim'),
	('Paul Farman', 'England', 'farman'),
	('Paul Farman', 'England', 'paul farman'),
	('Yannick Deichmann', 'Germany', 'yannick deichmann'),
	('Yannick Deichmann', 'Germany', 'deichmann'),
	('Kiichi Yajima', 'Japan', 'kiichi yajima'),
	('Kiichi Yajima', 'Japan', 'yajima'),
	('Alfie Whiteman', 'England', 'whiteman'),
	('Alfie Whiteman', 'England', 'alfie whiteman'),
	('Khaled Al Barakah', 'Saudi Arabia', 'khaled al barakah'),
	('Khaled Al Barakah', 'Saudi Arabia', 'barakah'),
	('Ben Kantie Karamoko', 'Ivory Coast', 'karamoko'),
	('Ben Kantie Karamoko', 'Ivory Coast', 'ben kantie karamoko'),
	('Maxence Derrien', 'France', 'derrien'),
	('Maxence Derrien', 'France', 'maxence derrien'),
	('José Monaga', 'Ecuador', 'monaga'),
	('José Monaga', 'Ecuador', 'jose monaga'),
	('Dru Yearwood', 'England', 'yearwood'),
	('Dru Yearwood', 'England', 'dru yearwood'),
	('Brayan Hurtado', 'Venezuela', 'hurtado'),
	('Brayan Hurtado', 'Venezuela', 'brayan hurtado'),
	('Andrei Tofan', 'Romania', 'tofan'),
	('Andrei Tofan', 'Romania', 'andrei tofan'),
	('Danzell Gravenberch', 'Netherlands', 'danzell gravenberch'),
	('Danzell Gravenberch', 'Netherlands', 'gravenberch'),
	('Séga Coulibaly', 'France', 'sega coulibaly'),
	('Séga Coulibaly', 'France', 'coulibaly'),
	('Maxime Biamou', 'France', 'biamou'),
	('Maxime Biamou', 'France', 'maxime biamou'),
	('Jon Gallagher', 'Republic of Ireland', 'jon gallagher'),
	('Jon Gallagher', 'Republic of Ireland', 'gallagher'),
	('Immanuel Pherai', 'Netherlands', 'immanuel pherai'),
	('Immanuel Pherai', 'Netherlands', 'pherai'),
	('João Mendes', 'Portugal', 'mendes'),
	('João Mendes', 'Portugal', 'joao mendes'),
	('Fredrik Torsteinbø', 'Norway', 'fredrik torsteinb'),
	('Fredrik Torsteinbø', 'Norway', 'torsteinb'),
	('Gerardo Moreno', 'Mexico', 'gerardo moreno'),
	('Gerardo Moreno', 'Mexico', 'moreno'),
	('Pascal Gregor', 'Denmark', 'pascal gregor'),
	('Pascal Gregor', 'Denmark', 'gregor'),
	('Ernesto Goñi', 'Uruguay', 'goni'),
	('Ernesto Goñi', 'Uruguay', 'ernesto goni'),
	('Jacob Storevik', 'Norway', 'storevik'),
	('Jacob Storevik', 'Norway', 'jacob storevik'),
	('Leandro Putaro', 'Germany', 'putaro'),
	('Leandro Putaro', 'Germany', 'leandro putaro'),
	('Mario Stefel', 'Austria', 'stefel'),
	('Mario Stefel', 'Austria', 'mario stefel'),
	('Ryutaro Iio', 'Japan', 'iio'),
	('Ryutaro Iio', 'Japan', 'ryutaro iio'),
	('Marcelo Freites', 'Argentina', 'marcelo freites'),
	('Marcelo Freites', 'Argentina', 'freites'),
	('Conor Grant', 'England', 'conor grant'),
	('Conor Grant', 'England', 'grant'),
	('Ali Yasar', 'Belgium', 'ali yasar'),
	('Ali Yasar', 'Belgium', 'yasar'),
	('Jay Chapman', 'Canada', 'jay chapman'),
	('Jay Chapman', 'Canada', 'chapman'),
	('Marcos Barrera', 'Argentina', 'barrera'),
	('Marcos Barrera', 'Argentina', 'marcos barrera'),
	('Merveille Goblet', 'Belgium', 'goblet'),
	('Merveille Goblet', 'Belgium', 'merveille goblet'),
	('Victor Rîmniceanu', 'Romania', 'victor rimniceanu'),
	('Victor Rîmniceanu', 'Romania', 'rimniceanu'),
	('Peter Orry Larsen', 'Norway', 'peter orry larsen'),
	('Peter Orry Larsen', 'Norway', 'larsen'),
	('Gary Rogers', 'Republic of Ireland', 'rogers'),
	('Gary Rogers', 'Republic of Ireland', 'gary rogers'),
	('Scott Davies', 'England', 'davies'),
	('Scott Davies', 'England', 'scott davies'),
	('Utku Yuvakuran', 'Turkey', 'yuvakuran'),
	('Utku Yuvakuran', 'Turkey', 'utku yuvakuran'),
	('Charles Dunne', 'Republic of Ireland', 'charles dunne'),
	('Charles Dunne', 'Republic of Ireland', 'dunne'),
	('Kyle Knoyle', 'England', 'kyle knoyle'),
	('Kyle Knoyle', 'England', 'knoyle'),
	('Rory McArdle', 'Northern Ireland', 'rory mcardle'),
	('Rory McArdle', 'Northern Ireland', 'mcardle'),
	('Medhy Guezoui', 'France', 'guezoui'),
	('Medhy Guezoui', 'France', 'medhy guezoui'),
	('Enes Sağlık', 'Belgium', 'enes saglk'),
	('Enes Sağlık', 'Belgium', 'saglk'),
	('Iñaki Álvarez', 'Spain', 'alvarez'),
	('Iñaki Álvarez', 'Spain', 'inaki alvarez'),
	('Johan Mårtensson', 'Sweden', 'johan martensson'),
	('Johan Mårtensson', 'Sweden', 'martensson'),
	('Park Jeong Su', 'Korea Republic', 'park jeong su'),
	('Park Jeong Su', 'Korea Republic', 'su'),
	('Kieran Wallace', 'England', 'wallace'),
	('Kieran Wallace', 'England', 'kieran wallace'),
	('Omir Fernandez', 'United States', 'fernandez'),
	('Omir Fernandez', 'United States', 'omir fernandez'),
	('Philipp Erhardt', 'Austria', 'erhardt'),
	('Philipp Erhardt', 'Austria', 'philipp erhardt'),
	('Adrian Stanilewicz', 'Poland', 'adrian stanilewicz'),
	('Adrian Stanilewicz', 'Poland', 'stanilewicz'),
	('Alessandro Buongiorno', 'Italy', 'alessandro buongiorno'),
	('Alessandro Buongiorno', 'Italy', 'buongiorno'),
	('Mohamed Coulibaly', 'Senegal', 'coulibaly'),
	('Mohamed Coulibaly', 'Senegal', 'mohamed coulibaly')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';