INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('David Zibung', 'Switzerland', 'player'),
	('Te Atawhai Hudson-Wihongi', 'New Zealand', 'player'),
	('Jasse Tuominen', 'Finland', 'player'),
	('Contreras', 'Spain', 'player'),
	('Batista Mendy', 'France', 'player'),
	('Sylvester Jasper', 'England', 'player'),
	('Facundo Giacopuzzi', 'Argentina', 'player'),
	('Harry Brockbank', 'England', 'player'),
	('Filip Piszczek', 'Poland', 'player'),
	('Lars Nieuwpoort', 'Netherlands', 'player'),
	('Luc Ihorst', 'Germany', 'player'),
	('Joe Martin', 'England', 'player'),
	('Du Jia', 'China PR', 'player'),
	('Thomas Gundelund', 'Denmark', 'player'),
	('Paweł Tomczyk', 'Poland', 'player'),
	('Joel Kabongo', 'Denmark', 'player'),
	('Ahmet Canbaz', 'Turkey', 'player'),
	('Xu Yang', 'China PR', 'player'),
	('Antony Evans', 'England', 'player'),
	('Vladis Emmersón', 'Congo', 'player'),
	('Philimon Tawiah', 'Ghana', 'player'),
	('Paul Osew', 'England', 'player'),
	('Offrande Zanzala', 'Congo', 'player'),
	('Anıl Aktaş', 'Turkey', 'player'),
	('Charlie Owens', 'Northern Ireland', 'player'),
	('Ricard Pujol', 'Spain', 'player'),
	('Ibrahim Mahnashi', 'Saudi Arabia', 'player'),
	('Claudiu Petrila', 'Romania', 'player'),
	('Sigurd Haugen', 'Norway', 'player'),
	('Jeong Jun Yeon', 'Korea Republic', 'player'),
	('Zhou Tong', 'China PR', 'player'),
	('Nathan Trott', 'England', 'player'),
	('Walter Tandazo', 'Peru', 'player'),
	('Owen Evans', 'Wales', 'player'),
	('Lucas Buades', 'France', 'player'),
	('Hassan Al Habib', 'Saudi Arabia', 'player'),
	('Li Songyi', 'China PR', 'player'),
	('Andy Butler', 'England', 'player'),
	('Mattias Moström', 'Sweden', 'player'),
	('Luo Senwen', 'China PR', 'player'),
	('Hu Jinghang', 'China PR', 'player'),
	('Tobias Englund', 'Sweden', 'player'),
	('Yordi Vílchez', 'Peru', 'player'),
	('Andy Williams', 'England', 'player'),
	('Wang Jianan', 'China PR', 'player'),
	('Simon Asta', 'Germany', 'player'),
	('Montassar Talbi', 'Tunisia', 'player'),
	('Denis Dumitrașcu', 'Romania', 'player'),
	('Filip Jørgensen', 'Norway', 'player'),
	('Tommy Grupe', 'Germany', 'player'),
	('Dion Conroy', 'England', 'player'),
	('Christopher Trejo', 'Mexico', 'player'),
	('Melvin Ramusović', 'Bosnia Herzegovina', 'player'),
	('Tobias Børkeeiet', 'Norway', 'player'),
	('Tomás Escalante', 'Argentina', 'player'),
	('Badr Al Nakhli', 'Saudi Arabia', 'player'),
	('Ervin Taha', 'France', 'player'),
	('Edixson González', 'Venezuela', 'player'),
	('Jamie Proctor', 'England', 'player'),
	('Tomoki Imai', 'Japan', 'player'),
	('Kazunori Yoshimoto', 'Japan', 'player'),
	('Justin Lonwijk', 'Netherlands', 'player'),
	('Zhang Chenglin', 'China PR', 'player'),
	('Joaquín Mendive', 'Argentina', 'player'),
	('Jonny Maxted', 'England', 'player'),
	('Luke Offord', 'England', 'player'),
	('Alfie Bates', 'England', 'player'),
	('Joe Nuttall', 'England', 'player'),
	('Bi Jinhao', 'China PR', 'player'),
	('Georgi Pashov', 'Bulgaria', 'player'),
	('Roque Guachiré', 'Paraguay', 'player'),
	('Jhony Rodríguez', 'Venezuela', 'player'),
	('Amadou Traoré', 'France', 'player'),
	('Miguel Tapias', 'Mexico', 'player'),
	('Miguel Aucca', 'Peru', 'player'),
	('Santiago Cartagena', 'Uruguay', 'player'),
	('Julen Lobete', 'Spain', 'player'),
	('Lee Soo Bin', 'Korea Republic', 'player'),
	('Daniel Rojas', 'Bolivia', 'player'),
	('Florin Plămadă', 'Romania', 'player'),
	('Daisuke Matsui', 'Japan', 'player'),
	('Wei Zhen', 'China PR', 'player'),
	('Jan-Christoph Bartels', 'Germany', 'player'),
	('Gabriel Pereira', 'Brazil', 'player'),
	('Junior Vargas', 'Venezuela', 'player'),
	('Andreas Mihaiu', 'Romania', 'player'),
	('Easah Suliman', 'England', 'player'),
	('Edison Carcelén', 'Ecuador', 'player'),
	('Jamie Lennon', 'Republic of Ireland', 'player'),
	('Renzo Orihuela', 'Uruguay', 'player'),
	('Ashley Nathaniel-George', 'England', 'player'),
	('Mark Cullen', 'England', 'player'),
	('Michael Kelly', 'Scotland', 'player'),
	('Karl Sheppard', 'Republic of Ireland', 'player'),
	('Juan Raúl Neira', 'Peru', 'player'),
	('Ali Sarı', 'Turkey', 'player'),
	('Miguel Rodríguez', 'Spain', 'player'),
	('Arjen van der Heide', 'Netherlands', 'player'),
	('Michael Nottingham', 'Saint Kitts and Nevis', 'player'),
	('Zahid Muñoz', 'Mexico', 'player'),
	('Alex Fisher', 'England', 'player'),
	('Ulrik Fredriksen', 'Norway', 'player'),
	('Adama Fofana', 'Ivory Coast', 'player'),
	('Ahmad Al Habib', 'Saudi Arabia', 'player'),
	('Eric Verstappen', 'Netherlands', 'player'),
	('Niels Nkounkou', 'France', 'player'),
	('Calvin Miller', 'Scotland', 'player'),
	('Yeo Bong Hun', 'Korea Republic', 'player'),
	('Darío Pazmiño', 'Ecuador', 'player'),
	('Rafał Kobryń', 'Poland', 'player'),
	('Amer Ordagić', 'Bosnia Herzegovina', 'player'),
	('Destan Bajselmani', 'Netherlands', 'player'),
	('Alexander Lungwitz', 'Germany', 'player'),
	('Christian Makoun', 'Venezuela', 'player'),
	('Qian Jiegei', 'China PR', 'player'),
	('Billy King', 'Scotland', 'player'),
	('Alexis Alégué', 'Cameroon', 'player'),
	('Morais', 'Venezuela', 'player'),
	('Shaun Miller', 'England', 'player'),
	('Shkodran Maholli', 'Sweden', 'player'),
	('Luca Unbehaun', 'Germany', 'player'),
	('Abduwal Ablet', 'China PR', 'player'),
	('Fabián González', 'Colombia', 'player'),
	('Jerry León', 'Ecuador', 'player'),
	('Murat Sağlam', 'Turkey', 'player'),
	('Yohei Nishibe', 'Japan', 'player'),
	('Zhang Xiuwei', 'China PR', 'player'),
	('Miloš Spasić', 'Serbia', 'player'),
	('Elvis Kamsoba', 'Burundi', 'player'),
	('Tibor Joza', 'Sweden', 'player'),
	('Ronald Mukiibi', 'Uganda', 'player'),
	('Jakov Medić', 'Croatia', 'player'),
	('Ryan Kitto', 'Australia', 'player'),
	('Alejandro Villalva', 'Ecuador', 'player'),
	('Moisés Villarroel', 'Bolivia', 'player'),
	('Vinni Triboulet', 'France', 'player'),
	('Mohammed Diomande', 'Ivory Coast', 'player'),
	('Quindimil', 'Spain', 'player'),
	('José Pierre Vunguidica', 'Angola', 'player'),
	('Majed Al Najrani', 'Saudi Arabia', 'player'),
	('Marvin Ekpiteta', 'England', 'player'),
	('Gonzalo Viera', 'Uruguay', 'player'),
	('Zhang Cheng', 'China PR', 'player'),
	('Tomasz Mokwa', 'Poland', 'player'),
	('Anthony Glennon', 'England', 'player'),
	('Quintana', 'Spain', 'player'),
	('Regan Charles-Cook', 'England', 'player'),
	('Mario Ordoñez', 'Spain', 'player'),
	('Zachary Elbouzedi', 'Republic of Ireland', 'player'),
	('Kellan Gordon', 'England', 'player'),
	('Matty Willock', 'England', 'player'),
	('Nicolás Miracco', 'Argentina', 'player'),
	('Josué Homawoo', 'Togo', 'player'),
	('Ludvig Öhman', 'Sweden', 'player'),
	('Kevin Magaña', 'Mexico', 'player'),
	('Sultan Mandash', 'Saudi Arabia', 'player'),
	('Jaume Cuéllar', 'Bolivia', 'player'),
	('Kai Klefisch', 'Germany', 'player'),
	('Javier Castro', 'Spain', 'player'),
	('Pablo Labrin', 'Peru', 'player'),
	('Harry Kyprianou', 'Cyprus', 'player'),
	('Emin Nouri', 'Azerbaijan', 'player'),
	('Roman Vantukh', 'Ukraine', 'player'),
	('Axel Sánchez', 'Peru', 'player'),
	('Liam Gibson', 'England', 'player'),
	('Junes Barny', 'Sweden', 'player'),
	('Tashreeq Matthews', 'South Africa', 'player'),
	('Paolo Jiménez', 'Costa Rica', 'player'),
	('Josh Doherty', 'Northern Ireland', 'player'),
	('Ben Mines', 'United States', 'player'),
	('Sebastián Benega', 'Argentina', 'player'),
	('Maimaitiyili Bali', 'China PR', 'player'),
	('Jamie Reid', 'Northern Ireland', 'player'),
	('Çağlar Şahin Akbaba', 'Turkey', 'player'),
	('Doo Hyun Seok', 'Korea Republic', 'player'),
	('Filip Bainović', 'Serbia', 'player'),
	('Lars Grorud', 'Norway', 'player'),
	('Paolo Fuentes', 'Peru', 'player'),
	('Juan Montenegro', 'Bolivia', 'player'),
	('Brandon Thomas-Asante', 'England', 'player'),
	('James Jones', 'Scotland', 'player'),
	('Adam Phillips', 'England', 'player'),
	('Armin Gigović', 'Sweden', 'player'),
	('Charlie Lakin', 'England', 'player'),
	('Joel Pinto', 'Peru', 'player'),
	('Filip Lesniak', 'Slovakia', 'player'),
	('Lee Jin Hyung', 'Korea Republic', 'player'),
	('Marcel Guaramato', 'Venezuela', 'player'),
	('Bartol Franjic', 'Croatia', 'player'),
	('Gian Luca Schulz', 'Germany', 'player'),
	('Louis Carnot', 'France', 'player'),
	('Eray İşcan', 'Turkey', 'player'),
	('Ciprian Gliga', 'Romania', 'player'),
	('Mihovil Klapan', 'Croatia', 'player'),
	('Ahn Young Kyu', 'Korea Republic', 'player'),
	('Ionuț Șerban', 'Romania', 'player'),
	('Elliot Simões', 'Portugal', 'player'),
	('Kevin Lewis', 'Uruguay', 'player'),
	('Alán Mercado', 'Bolivia', 'player'),
	('Wilson Ibarrola', 'Paraguay', 'player'),
	('Fabián Píriz', 'Uruguay', 'player'),
	('Carlos Monges', 'Paraguay', 'player'),
	('Andrei Panait', 'Romania', 'player'),
	('Brandur Hendriksson Olsen', 'Faroe Islands', 'player'),
	('Sumayhan Al Nabit', 'Saudi Arabia', 'player'),
	('Bryan Lasme', 'France', 'player'),
	('Robert Moldoveanu', 'Romania', 'player'),
	('Tian Yinong', 'China PR', 'player'),
	('Yohei Takeda', 'Japan', 'player'),
	('Fahad Ghazi', 'Saudi Arabia', 'player'),
	('Abdulaziz Al Nashi', 'Saudi Arabia', 'player'),
	('Kyle Howkins', 'England', 'player'),
	('Layneker Zafra', 'Venezuela', 'player'),
	('Shane Griffin', 'Republic of Ireland', 'player'),
	('Reiss Greenidge', 'Guyana', 'player'),
	('Abu Francis', 'Ghana', 'player'),
	('Kiwara Miyazaki', 'Japan', 'player'),
	('Elliot Collier', 'New Zealand', 'player'),
	('Louis Dennis', 'England', 'player'),
	('Shingo Hyodo', 'Japan', 'player'),
	('Karam Barnawi', 'Saudi Arabia', 'player'),
	('Stefan Drljača', 'Germany', 'player'),
	('Brendan Hamill', 'Australia', 'player'),
	('Davide Itter', 'Germany', 'player'),
	('Luis Vergara', 'Colombia', 'player'),
	('Kevin O''Connor', 'Republic of Ireland', 'player'),
	('Francis Jno-Baptiste', 'England', 'player'),
	('Carlo Casap', 'Romania', 'player'),
	('Rodrigo Schlegel', 'Argentina', 'player'),
	('Jim McNulty', 'Scotland', 'player'),
	('Melih Ibrahimoglu', 'Austria', 'player'),
	('Mladen Jutrić', 'Austria', 'player'),
	('Yasir Subaşı', 'Turkey', 'player'),
	('Santos Navarro', 'Bolivia', 'player'),
	('Camilo Núñez', 'Uruguay', 'player'),
	('Rodrigo Banegas', 'Bolivia', 'player'),
	('Joaquín Astorga', 'Peru', 'player'),
	('Marcos Delgado', 'Peru', 'player'),
	('Furkan Kircicek', 'Germany', 'player'),
	('Stephen Sama', 'Germany', 'player'),
	('Lóránt Kovács', 'Romania', 'player'),
	('Homero Calderón', 'Venezuela', 'player'),
	('Jon Birkfeldt', 'Sweden', 'player'),
	('Matthias Phaëton', 'France', 'player'),
	('Kevin Piscopo', 'Italy', 'player'),
	('Corey Brown', 'Australia', 'player'),
	('Yeerjieti Yeerzati', 'China PR', 'player'),
	('Jack Lankester', 'England', 'player'),
	('Oddbjørn Lie', 'Norway', 'player'),
	('Callum Ainley', 'England', 'player');

WITH v(name, cat, alias) AS (VALUES
	('David Zibung', 'Switzerland', 'zibung'),
	('David Zibung', 'Switzerland', 'david zibung'),
	('Te Atawhai Hudson-Wihongi', 'New Zealand', 'te atawhai hudsonwihongi'),
	('Te Atawhai Hudson-Wihongi', 'New Zealand', 'hudsonwihongi'),
	('Jasse Tuominen', 'Finland', 'jasse tuominen'),
	('Jasse Tuominen', 'Finland', 'tuominen'),
	('Contreras', 'Spain', 'contreras'),
	('Batista Mendy', 'France', 'mendy'),
	('Batista Mendy', 'France', 'batista mendy'),
	('Sylvester Jasper', 'England', 'sylvester jasper'),
	('Sylvester Jasper', 'England', 'jasper'),
	('Facundo Giacopuzzi', 'Argentina', 'giacopuzzi'),
	('Facundo Giacopuzzi', 'Argentina', 'facundo giacopuzzi'),
	('Harry Brockbank', 'England', 'harry brockbank'),
	('Harry Brockbank', 'England', 'brockbank'),
	('Filip Piszczek', 'Poland', 'piszczek'),
	('Filip Piszczek', 'Poland', 'filip piszczek'),
	('Lars Nieuwpoort', 'Netherlands', 'lars nieuwpoort'),
	('Lars Nieuwpoort', 'Netherlands', 'nieuwpoort'),
	('Luc Ihorst', 'Germany', 'luc ihorst'),
	('Luc Ihorst', 'Germany', 'ihorst'),
	('Joe Martin', 'England', 'joe martin'),
	('Joe Martin', 'England', 'martin'),
	('Du Jia', 'China PR', 'du jia'),
	('Du Jia', 'China PR', 'jia'),
	('Thomas Gundelund', 'Denmark', 'gundelund'),
	('Thomas Gundelund', 'Denmark', 'thomas gundelund'),
	('Paweł Tomczyk', 'Poland', 'pawe tomczyk'),
	('Paweł Tomczyk', 'Poland', 'tomczyk'),
	('Joel Kabongo', 'Denmark', 'kabongo'),
	('Joel Kabongo', 'Denmark', 'joel kabongo'),
	('Ahmet Canbaz', 'Turkey', 'canbaz'),
	('Ahmet Canbaz', 'Turkey', 'ahmet canbaz'),
	('Xu Yang', 'China PR', 'xu yang'),
	('Xu Yang', 'China PR', 'yang'),
	('Antony Evans', 'England', 'antony evans'),
	('Antony Evans', 'England', 'evans'),
	('Vladis Emmersón', 'Congo', 'emmerson'),
	('Vladis Emmersón', 'Congo', 'vladis emmerson'),
	('Philimon Tawiah', 'Ghana', 'philimon tawiah'),
	('Philimon Tawiah', 'Ghana', 'tawiah'),
	('Paul Osew', 'England', 'paul osew'),
	('Paul Osew', 'England', 'osew'),
	('Offrande Zanzala', 'Congo', 'zanzala'),
	('Offrande Zanzala', 'Congo', 'offrande zanzala'),
	('Anıl Aktaş', 'Turkey', 'aktas'),
	('Anıl Aktaş', 'Turkey', 'anl aktas'),
	('Charlie Owens', 'Northern Ireland', 'charlie owens'),
	('Charlie Owens', 'Northern Ireland', 'owens'),
	('Ricard Pujol', 'Spain', 'ricard pujol'),
	('Ricard Pujol', 'Spain', 'pujol'),
	('Ibrahim Mahnashi', 'Saudi Arabia', 'ibrahim mahnashi'),
	('Ibrahim Mahnashi', 'Saudi Arabia', 'mahnashi'),
	('Claudiu Petrila', 'Romania', 'claudiu petrila'),
	('Claudiu Petrila', 'Romania', 'petrila'),
	('Sigurd Haugen', 'Norway', 'sigurd haugen'),
	('Sigurd Haugen', 'Norway', 'haugen'),
	('Jeong Jun Yeon', 'Korea Republic', 'yeon'),
	('Jeong Jun Yeon', 'Korea Republic', 'jeong jun yeon'),
	('Zhou Tong', 'China PR', 'zhou tong'),
	('Zhou Tong', 'China PR', 'tong'),
	('Nathan Trott', 'England', 'trott'),
	('Nathan Trott', 'England', 'nathan trott'),
	('Walter Tandazo', 'Peru', 'tandazo'),
	('Walter Tandazo', 'Peru', 'walter tandazo'),
	('Owen Evans', 'Wales', 'evans'),
	('Owen Evans', 'Wales', 'owen evans'),
	('Lucas Buades', 'France', 'buades'),
	('Lucas Buades', 'France', 'lucas buades'),
	('Hassan Al Habib', 'Saudi Arabia', 'habib'),
	('Hassan Al Habib', 'Saudi Arabia', 'hassan al habib'),
	('Li Songyi', 'China PR', 'li songyi'),
	('Li Songyi', 'China PR', 'songyi'),
	('Andy Butler', 'England', 'andy butler'),
	('Andy Butler', 'England', 'butler'),
	('Mattias Moström', 'Sweden', 'mattias mostrom'),
	('Mattias Moström', 'Sweden', 'mostrom'),
	('Luo Senwen', 'China PR', 'luo senwen'),
	('Luo Senwen', 'China PR', 'senwen'),
	('Hu Jinghang', 'China PR', 'hu jinghang'),
	('Hu Jinghang', 'China PR', 'jinghang'),
	('Tobias Englund', 'Sweden', 'tobias englund'),
	('Tobias Englund', 'Sweden', 'englund'),
	('Yordi Vílchez', 'Peru', 'yordi vilchez'),
	('Yordi Vílchez', 'Peru', 'vilchez'),
	('Andy Williams', 'England', 'andy williams'),
	('Andy Williams', 'England', 'williams'),
	('Wang Jianan', 'China PR', 'jianan'),
	('Wang Jianan', 'China PR', 'wang jianan'),
	('Simon Asta', 'Germany', 'asta'),
	('Simon Asta', 'Germany', 'simon asta'),
	('Montassar Talbi', 'Tunisia', 'talbi'),
	('Montassar Talbi', 'Tunisia', 'montassar talbi'),
	('Denis Dumitrașcu', 'Romania', 'dumitrascu'),
	('Denis Dumitrașcu', 'Romania', 'denis dumitrascu'),
	('Filip Jørgensen', 'Norway', 'jrgensen'),
	('Filip Jørgensen', 'Norway', 'filip jrgensen'),
	('Tommy Grupe', 'Germany', 'grupe'),
	('Tommy Grupe', 'Germany', 'tommy grupe'),
	('Dion Conroy', 'England', 'conroy'),
	('Dion Conroy', 'England', 'dion conroy'),
	('Christopher Trejo', 'Mexico', 'christopher trejo'),
	('Christopher Trejo', 'Mexico', 'trejo'),
	('Melvin Ramusović', 'Bosnia Herzegovina', 'melvin ramusovic'),
	('Melvin Ramusović', 'Bosnia Herzegovina', 'ramusovic'),
	('Tobias Børkeeiet', 'Norway', 'tobias brkeeiet'),
	('Tobias Børkeeiet', 'Norway', 'brkeeiet'),
	('Tomás Escalante', 'Argentina', 'escalante'),
	('Tomás Escalante', 'Argentina', 'tomas escalante'),
	('Badr Al Nakhli', 'Saudi Arabia', 'nakhli'),
	('Badr Al Nakhli', 'Saudi Arabia', 'badr al nakhli'),
	('Ervin Taha', 'France', 'ervin taha'),
	('Ervin Taha', 'France', 'taha'),
	('Edixson González', 'Venezuela', 'edixson gonzalez'),
	('Edixson González', 'Venezuela', 'gonzalez'),
	('Jamie Proctor', 'England', 'jamie proctor'),
	('Jamie Proctor', 'England', 'proctor'),
	('Tomoki Imai', 'Japan', 'imai'),
	('Tomoki Imai', 'Japan', 'tomoki imai'),
	('Kazunori Yoshimoto', 'Japan', 'kazunori yoshimoto'),
	('Kazunori Yoshimoto', 'Japan', 'yoshimoto'),
	('Justin Lonwijk', 'Netherlands', 'lonwijk'),
	('Justin Lonwijk', 'Netherlands', 'justin lonwijk'),
	('Zhang Chenglin', 'China PR', 'chenglin'),
	('Zhang Chenglin', 'China PR', 'zhang chenglin'),
	('Joaquín Mendive', 'Argentina', 'joaquin mendive'),
	('Joaquín Mendive', 'Argentina', 'mendive'),
	('Jonny Maxted', 'England', 'maxted'),
	('Jonny Maxted', 'England', 'jonny maxted'),
	('Luke Offord', 'England', 'luke offord'),
	('Luke Offord', 'England', 'offord'),
	('Alfie Bates', 'England', 'bates'),
	('Alfie Bates', 'England', 'alfie bates'),
	('Joe Nuttall', 'England', 'joe nuttall'),
	('Joe Nuttall', 'England', 'nuttall'),
	('Bi Jinhao', 'China PR', 'jinhao'),
	('Bi Jinhao', 'China PR', 'bi jinhao'),
	('Georgi Pashov', 'Bulgaria', 'georgi pashov'),
	('Georgi Pashov', 'Bulgaria', 'pashov'),
	('Roque Guachiré', 'Paraguay', 'guachire'),
	('Roque Guachiré', 'Paraguay', 'roque guachire'),
	('Jhony Rodríguez', 'Venezuela', 'jhony rodriguez'),
	('Jhony Rodríguez', 'Venezuela', 'rodriguez'),
	('Amadou Traoré', 'France', 'amadou traore'),
	('Amadou Traoré', 'France', 'traore'),
	('Miguel Tapias', 'Mexico', 'tapias'),
	('Miguel Tapias', 'Mexico', 'miguel tapias'),
	('Miguel Aucca', 'Peru', 'miguel aucca'),
	('Miguel Aucca', 'Peru', 'aucca'),
	('Santiago Cartagena', 'Uruguay', 'cartagena'),
	('Santiago Cartagena', 'Uruguay', 'santiago cartagena'),
	('Julen Lobete', 'Spain', 'lobete'),
	('Julen Lobete', 'Spain', 'julen lobete'),
	('Lee Soo Bin', 'Korea Republic', 'bin'),
	('Lee Soo Bin', 'Korea Republic', 'lee soo bin'),
	('Daniel Rojas', 'Bolivia', 'daniel rojas'),
	('Daniel Rojas', 'Bolivia', 'rojas'),
	('Florin Plămadă', 'Romania', 'plamada'),
	('Florin Plămadă', 'Romania', 'florin plamada'),
	('Daisuke Matsui', 'Japan', 'matsui'),
	('Daisuke Matsui', 'Japan', 'daisuke matsui'),
	('Wei Zhen', 'China PR', 'zhen'),
	('Wei Zhen', 'China PR', 'wei zhen'),
	('Jan-Christoph Bartels', 'Germany', 'bartels'),
	('Jan-Christoph Bartels', 'Germany', 'janchristoph bartels'),
	('Gabriel Pereira', 'Brazil', 'pereira'),
	('Gabriel Pereira', 'Brazil', 'gabriel pereira'),
	('Junior Vargas', 'Venezuela', 'vargas'),
	('Junior Vargas', 'Venezuela', 'junior vargas'),
	('Andreas Mihaiu', 'Romania', 'andreas mihaiu'),
	('Andreas Mihaiu', 'Romania', 'mihaiu'),
	('Easah Suliman', 'England', 'suliman'),
	('Easah Suliman', 'England', 'easah suliman'),
	('Edison Carcelén', 'Ecuador', 'carcelen'),
	('Edison Carcelén', 'Ecuador', 'edison carcelen'),
	('Jamie Lennon', 'Republic of Ireland', 'lennon'),
	('Jamie Lennon', 'Republic of Ireland', 'jamie lennon'),
	('Renzo Orihuela', 'Uruguay', 'orihuela'),
	('Renzo Orihuela', 'Uruguay', 'renzo orihuela'),
	('Ashley Nathaniel-George', 'England', 'nathanielgeorge'),
	('Ashley Nathaniel-George', 'England', 'ashley nathanielgeorge'),
	('Mark Cullen', 'England', 'cullen'),
	('Mark Cullen', 'England', 'mark cullen'),
	('Michael Kelly', 'Scotland', 'kelly'),
	('Michael Kelly', 'Scotland', 'michael kelly'),
	('Karl Sheppard', 'Republic of Ireland', 'sheppard'),
	('Karl Sheppard', 'Republic of Ireland', 'karl sheppard'),
	('Juan Raúl Neira', 'Peru', 'juan raul neira'),
	('Juan Raúl Neira', 'Peru', 'neira'),
	('Ali Sarı', 'Turkey', 'sar'),
	('Ali Sarı', 'Turkey', 'ali sar'),
	('Miguel Rodríguez', 'Spain', 'rodriguez'),
	('Miguel Rodríguez', 'Spain', 'miguel rodriguez'),
	('Arjen van der Heide', 'Netherlands', 'heide'),
	('Arjen van der Heide', 'Netherlands', 'arjen van der heide'),
	('Michael Nottingham', 'Saint Kitts and Nevis', 'nottingham'),
	('Michael Nottingham', 'Saint Kitts and Nevis', 'michael nottingham'),
	('Zahid Muñoz', 'Mexico', 'zahid munoz'),
	('Zahid Muñoz', 'Mexico', 'munoz'),
	('Alex Fisher', 'England', 'fisher'),
	('Alex Fisher', 'England', 'alex fisher'),
	('Ulrik Fredriksen', 'Norway', 'ulrik fredriksen'),
	('Ulrik Fredriksen', 'Norway', 'fredriksen'),
	('Adama Fofana', 'Ivory Coast', 'adama fofana'),
	('Adama Fofana', 'Ivory Coast', 'fofana'),
	('Ahmad Al Habib', 'Saudi Arabia', 'habib'),
	('Ahmad Al Habib', 'Saudi Arabia', 'ahmad al habib'),
	('Eric Verstappen', 'Netherlands', 'eric verstappen'),
	('Eric Verstappen', 'Netherlands', 'verstappen'),
	('Niels Nkounkou', 'France', 'nkounkou'),
	('Niels Nkounkou', 'France', 'niels nkounkou'),
	('Calvin Miller', 'Scotland', 'calvin miller'),
	('Calvin Miller', 'Scotland', 'miller'),
	('Yeo Bong Hun', 'Korea Republic', 'yeo bong hun'),
	('Yeo Bong Hun', 'Korea Republic', 'hun'),
	('Darío Pazmiño', 'Ecuador', 'pazmino'),
	('Darío Pazmiño', 'Ecuador', 'dario pazmino'),
	('Rafał Kobryń', 'Poland', 'kobryn'),
	('Rafał Kobryń', 'Poland', 'rafa kobryn'),
	('Amer Ordagić', 'Bosnia Herzegovina', 'amer ordagic'),
	('Amer Ordagić', 'Bosnia Herzegovina', 'ordagic'),
	('Destan Bajselmani', 'Netherlands', 'bajselmani'),
	('Destan Bajselmani', 'Netherlands', 'destan bajselmani'),
	('Alexander Lungwitz', 'Germany', 'alexander lungwitz'),
	('Alexander Lungwitz', 'Germany', 'lungwitz'),
	('Christian Makoun', 'Venezuela', 'makoun'),
	('Christian Makoun', 'Venezuela', 'christian makoun'),
	('Qian Jiegei', 'China PR', 'jiegei'),
	('Qian Jiegei', 'China PR', 'qian jiegei'),
	('Billy King', 'Scotland', 'billy king'),
	('Billy King', 'Scotland', 'king'),
	('Alexis Alégué', 'Cameroon', 'alexis alegue'),
	('Alexis Alégué', 'Cameroon', 'alegue'),
	('Morais', 'Venezuela', 'morais'),
	('Shaun Miller', 'England', 'miller'),
	('Shaun Miller', 'England', 'shaun miller'),
	('Shkodran Maholli', 'Sweden', 'maholli'),
	('Shkodran Maholli', 'Sweden', 'shkodran maholli'),
	('Luca Unbehaun', 'Germany', 'luca unbehaun'),
	('Luca Unbehaun', 'Germany', 'unbehaun'),
	('Abduwal Ablet', 'China PR', 'ablet'),
	('Abduwal Ablet', 'China PR', 'abduwal ablet'),
	('Fabián González', 'Colombia', 'gonzalez'),
	('Fabián González', 'Colombia', 'fabian gonzalez'),
	('Jerry León', 'Ecuador', 'leon'),
	('Jerry León', 'Ecuador', 'jerry leon'),
	('Murat Sağlam', 'Turkey', 'saglam'),
	('Murat Sağlam', 'Turkey', 'murat saglam'),
	('Yohei Nishibe', 'Japan', 'nishibe'),
	('Yohei Nishibe', 'Japan', 'yohei nishibe'),
	('Zhang Xiuwei', 'China PR', 'xiuwei'),
	('Zhang Xiuwei', 'China PR', 'zhang xiuwei'),
	('Miloš Spasić', 'Serbia', 'milos spasic'),
	('Miloš Spasić', 'Serbia', 'spasic'),
	('Elvis Kamsoba', 'Burundi', 'kamsoba'),
	('Elvis Kamsoba', 'Burundi', 'elvis kamsoba'),
	('Tibor Joza', 'Sweden', 'joza'),
	('Tibor Joza', 'Sweden', 'tibor joza'),
	('Ronald Mukiibi', 'Uganda', 'ronald mukiibi'),
	('Ronald Mukiibi', 'Uganda', 'mukiibi'),
	('Jakov Medić', 'Croatia', 'jakov medic'),
	('Jakov Medić', 'Croatia', 'medic'),
	('Ryan Kitto', 'Australia', 'ryan kitto'),
	('Ryan Kitto', 'Australia', 'kitto'),
	('Alejandro Villalva', 'Ecuador', 'alejandro villalva'),
	('Alejandro Villalva', 'Ecuador', 'villalva'),
	('Moisés Villarroel', 'Bolivia', 'moises villarroel'),
	('Moisés Villarroel', 'Bolivia', 'villarroel'),
	('Vinni Triboulet', 'France', 'triboulet'),
	('Vinni Triboulet', 'France', 'vinni triboulet'),
	('Mohammed Diomande', 'Ivory Coast', 'mohammed diomande'),
	('Mohammed Diomande', 'Ivory Coast', 'diomande'),
	('Quindimil', 'Spain', 'quindimil'),
	('José Pierre Vunguidica', 'Angola', 'jose pierre vunguidica'),
	('José Pierre Vunguidica', 'Angola', 'vunguidica'),
	('Majed Al Najrani', 'Saudi Arabia', 'majed al najrani'),
	('Majed Al Najrani', 'Saudi Arabia', 'najrani'),
	('Marvin Ekpiteta', 'England', 'ekpiteta'),
	('Marvin Ekpiteta', 'England', 'marvin ekpiteta'),
	('Gonzalo Viera', 'Uruguay', 'gonzalo viera'),
	('Gonzalo Viera', 'Uruguay', 'viera'),
	('Zhang Cheng', 'China PR', 'cheng'),
	('Zhang Cheng', 'China PR', 'zhang cheng'),
	('Tomasz Mokwa', 'Poland', 'tomasz mokwa'),
	('Tomasz Mokwa', 'Poland', 'mokwa'),
	('Anthony Glennon', 'England', 'glennon'),
	('Anthony Glennon', 'England', 'anthony glennon'),
	('Quintana', 'Spain', 'quintana'),
	('Regan Charles-Cook', 'England', 'regan charlescook'),
	('Regan Charles-Cook', 'England', 'charlescook'),
	('Mario Ordoñez', 'Spain', 'ordonez'),
	('Mario Ordoñez', 'Spain', 'mario ordonez'),
	('Zachary Elbouzedi', 'Republic of Ireland', 'zachary elbouzedi'),
	('Zachary Elbouzedi', 'Republic of Ireland', 'elbouzedi'),
	('Kellan Gordon', 'England', 'gordon'),
	('Kellan Gordon', 'England', 'kellan gordon'),
	('Matty Willock', 'England', 'matty willock'),
	('Matty Willock', 'England', 'willock'),
	('Nicolás Miracco', 'Argentina', 'nicolas miracco'),
	('Nicolás Miracco', 'Argentina', 'miracco'),
	('Josué Homawoo', 'Togo', 'josue homawoo'),
	('Josué Homawoo', 'Togo', 'homawoo'),
	('Ludvig Öhman', 'Sweden', 'ohman'),
	('Ludvig Öhman', 'Sweden', 'ludvig ohman'),
	('Kevin Magaña', 'Mexico', 'magana'),
	('Kevin Magaña', 'Mexico', 'kevin magana'),
	('Sultan Mandash', 'Saudi Arabia', 'sultan mandash'),
	('Sultan Mandash', 'Saudi Arabia', 'mandash'),
	('Jaume Cuéllar', 'Bolivia', 'cuellar'),
	('Jaume Cuéllar', 'Bolivia', 'jaume cuellar'),
	('Kai Klefisch', 'Germany', 'kai klefisch'),
	('Kai Klefisch', 'Germany', 'klefisch'),
	('Javier Castro', 'Spain', 'castro'),
	('Javier Castro', 'Spain', 'javier castro'),
	('Pablo Labrin', 'Peru', 'labrin'),
	('Pablo Labrin', 'Peru', 'pablo labrin'),
	('Harry Kyprianou', 'Cyprus', 'kyprianou'),
	('Harry Kyprianou', 'Cyprus', 'harry kyprianou'),
	('Emin Nouri', 'Azerbaijan', 'nouri'),
	('Emin Nouri', 'Azerbaijan', 'emin nouri'),
	('Roman Vantukh', 'Ukraine', 'roman vantukh'),
	('Roman Vantukh', 'Ukraine', 'vantukh'),
	('Axel Sánchez', 'Peru', 'axel sanchez'),
	('Axel Sánchez', 'Peru', 'sanchez'),
	('Liam Gibson', 'England', 'gibson'),
	('Liam Gibson', 'England', 'liam gibson'),
	('Junes Barny', 'Sweden', 'barny'),
	('Junes Barny', 'Sweden', 'junes barny'),
	('Tashreeq Matthews', 'South Africa', 'matthews'),
	('Tashreeq Matthews', 'South Africa', 'tashreeq matthews'),
	('Paolo Jiménez', 'Costa Rica', 'jimenez'),
	('Paolo Jiménez', 'Costa Rica', 'paolo jimenez'),
	('Josh Doherty', 'Northern Ireland', 'josh doherty'),
	('Josh Doherty', 'Northern Ireland', 'doherty'),
	('Ben Mines', 'United States', 'ben mines'),
	('Ben Mines', 'United States', 'mines'),
	('Sebastián Benega', 'Argentina', 'sebastian benega'),
	('Sebastián Benega', 'Argentina', 'benega'),
	('Maimaitiyili Bali', 'China PR', 'bali'),
	('Maimaitiyili Bali', 'China PR', 'maimaitiyili bali'),
	('Jamie Reid', 'Northern Ireland', 'reid'),
	('Jamie Reid', 'Northern Ireland', 'jamie reid'),
	('Çağlar Şahin Akbaba', 'Turkey', 'caglar sahin akbaba'),
	('Çağlar Şahin Akbaba', 'Turkey', 'akbaba'),
	('Doo Hyun Seok', 'Korea Republic', 'seok'),
	('Doo Hyun Seok', 'Korea Republic', 'doo hyun seok'),
	('Filip Bainović', 'Serbia', 'filip bainovic'),
	('Filip Bainović', 'Serbia', 'bainovic'),
	('Lars Grorud', 'Norway', 'grorud'),
	('Lars Grorud', 'Norway', 'lars grorud'),
	('Paolo Fuentes', 'Peru', 'fuentes'),
	('Paolo Fuentes', 'Peru', 'paolo fuentes'),
	('Juan Montenegro', 'Bolivia', 'juan montenegro'),
	('Juan Montenegro', 'Bolivia', 'montenegro'),
	('Brandon Thomas-Asante', 'England', 'thomasasante'),
	('Brandon Thomas-Asante', 'England', 'brandon thomasasante'),
	('James Jones', 'Scotland', 'james jones'),
	('James Jones', 'Scotland', 'jones'),
	('Adam Phillips', 'England', 'adam phillips'),
	('Adam Phillips', 'England', 'phillips'),
	('Armin Gigović', 'Sweden', 'gigovic'),
	('Armin Gigović', 'Sweden', 'armin gigovic'),
	('Charlie Lakin', 'England', 'lakin'),
	('Charlie Lakin', 'England', 'charlie lakin'),
	('Joel Pinto', 'Peru', 'pinto'),
	('Joel Pinto', 'Peru', 'joel pinto'),
	('Filip Lesniak', 'Slovakia', 'filip lesniak'),
	('Filip Lesniak', 'Slovakia', 'lesniak'),
	('Lee Jin Hyung', 'Korea Republic', 'lee jin hyung'),
	('Lee Jin Hyung', 'Korea Republic', 'hyung'),
	('Marcel Guaramato', 'Venezuela', 'guaramato'),
	('Marcel Guaramato', 'Venezuela', 'marcel guaramato'),
	('Bartol Franjic', 'Croatia', 'franjic'),
	('Bartol Franjic', 'Croatia', 'bartol franjic'),
	('Gian Luca Schulz', 'Germany', 'gian luca schulz'),
	('Gian Luca Schulz', 'Germany', 'schulz'),
	('Louis Carnot', 'France', 'carnot'),
	('Louis Carnot', 'France', 'louis carnot'),
	('Eray İşcan', 'Turkey', 'iscan'),
	('Eray İşcan', 'Turkey', 'eray iscan'),
	('Ciprian Gliga', 'Romania', 'gliga'),
	('Ciprian Gliga', 'Romania', 'ciprian gliga'),
	('Mihovil Klapan', 'Croatia', 'klapan'),
	('Mihovil Klapan', 'Croatia', 'mihovil klapan'),
	('Ahn Young Kyu', 'Korea Republic', 'ahn young kyu'),
	('Ahn Young Kyu', 'Korea Republic', 'kyu'),
	('Ionuț Șerban', 'Romania', 'ionut serban'),
	('Ionuț Șerban', 'Romania', 'serban'),
	('Elliot Simões', 'Portugal', 'elliot simoes'),
	('Elliot Simões', 'Portugal', 'simoes'),
	('Kevin Lewis', 'Uruguay', 'kevin lewis'),
	('Kevin Lewis', 'Uruguay', 'lewis'),
	('Alán Mercado', 'Bolivia', 'alan mercado'),
	('Alán Mercado', 'Bolivia', 'mercado'),
	('Wilson Ibarrola', 'Paraguay', 'ibarrola'),
	('Wilson Ibarrola', 'Paraguay', 'wilson ibarrola'),
	('Fabián Píriz', 'Uruguay', 'piriz'),
	('Fabián Píriz', 'Uruguay', 'fabian piriz'),
	('Carlos Monges', 'Paraguay', 'monges'),
	('Carlos Monges', 'Paraguay', 'carlos monges'),
	('Andrei Panait', 'Romania', 'andrei panait'),
	('Andrei Panait', 'Romania', 'panait'),
	('Brandur Hendriksson Olsen', 'Faroe Islands', 'brandur hendriksson olsen'),
	('Brandur Hendriksson Olsen', 'Faroe Islands', 'olsen'),
	('Sumayhan Al Nabit', 'Saudi Arabia', 'nabit'),
	('Sumayhan Al Nabit', 'Saudi Arabia', 'sumayhan al nabit'),
	('Bryan Lasme', 'France', 'bryan lasme'),
	('Bryan Lasme', 'France', 'lasme'),
	('Robert Moldoveanu', 'Romania', 'moldoveanu'),
	('Robert Moldoveanu', 'Romania', 'robert moldoveanu'),
	('Tian Yinong', 'China PR', 'yinong'),
	('Tian Yinong', 'China PR', 'tian yinong'),
	('Yohei Takeda', 'Japan', 'takeda'),
	('Yohei Takeda', 'Japan', 'yohei takeda'),
	('Fahad Ghazi', 'Saudi Arabia', 'ghazi'),
	('Fahad Ghazi', 'Saudi Arabia', 'fahad ghazi'),
	('Abdulaziz Al Nashi', 'Saudi Arabia', 'nashi'),
	('Abdulaziz Al Nashi', 'Saudi Arabia', 'abdulaziz al nashi'),
	('Kyle Howkins', 'England', 'howkins'),
	('Kyle Howkins', 'England', 'kyle howkins'),
	('Layneker Zafra', 'Venezuela', 'zafra'),
	('Layneker Zafra', 'Venezuela', 'layneker zafra'),
	('Shane Griffin', 'Republic of Ireland', 'griffin'),
	('Shane Griffin', 'Republic of Ireland', 'shane griffin'),
	('Reiss Greenidge', 'Guyana', 'greenidge'),
	('Reiss Greenidge', 'Guyana', 'reiss greenidge'),
	('Abu Francis', 'Ghana', 'abu francis'),
	('Abu Francis', 'Ghana', 'francis'),
	('Kiwara Miyazaki', 'Japan', 'miyazaki'),
	('Kiwara Miyazaki', 'Japan', 'kiwara miyazaki'),
	('Elliot Collier', 'New Zealand', 'collier'),
	('Elliot Collier', 'New Zealand', 'elliot collier'),
	('Louis Dennis', 'England', 'dennis'),
	('Louis Dennis', 'England', 'louis dennis'),
	('Shingo Hyodo', 'Japan', 'shingo hyodo'),
	('Shingo Hyodo', 'Japan', 'hyodo'),
	('Karam Barnawi', 'Saudi Arabia', 'karam barnawi'),
	('Karam Barnawi', 'Saudi Arabia', 'barnawi'),
	('Stefan Drljača', 'Germany', 'stefan drljaca'),
	('Stefan Drljača', 'Germany', 'drljaca'),
	('Brendan Hamill', 'Australia', 'hamill'),
	('Brendan Hamill', 'Australia', 'brendan hamill'),
	('Davide Itter', 'Germany', 'itter'),
	('Davide Itter', 'Germany', 'davide itter'),
	('Luis Vergara', 'Colombia', 'luis vergara'),
	('Luis Vergara', 'Colombia', 'vergara'),
	('Kevin O''Connor', 'Republic of Ireland', 'kevin oconnor'),
	('Kevin O''Connor', 'Republic of Ireland', 'oconnor'),
	('Francis Jno-Baptiste', 'England', 'francis jnobaptiste'),
	('Francis Jno-Baptiste', 'England', 'jnobaptiste'),
	('Carlo Casap', 'Romania', 'carlo casap'),
	('Carlo Casap', 'Romania', 'casap'),
	('Rodrigo Schlegel', 'Argentina', 'rodrigo schlegel'),
	('Rodrigo Schlegel', 'Argentina', 'schlegel'),
	('Jim McNulty', 'Scotland', 'jim mcnulty'),
	('Jim McNulty', 'Scotland', 'mcnulty'),
	('Melih Ibrahimoglu', 'Austria', 'ibrahimoglu'),
	('Melih Ibrahimoglu', 'Austria', 'melih ibrahimoglu'),
	('Mladen Jutrić', 'Austria', 'jutric'),
	('Mladen Jutrić', 'Austria', 'mladen jutric'),
	('Yasir Subaşı', 'Turkey', 'yasir subas'),
	('Yasir Subaşı', 'Turkey', 'subas'),
	('Santos Navarro', 'Bolivia', 'navarro'),
	('Santos Navarro', 'Bolivia', 'santos navarro'),
	('Camilo Núñez', 'Uruguay', 'camilo nunez'),
	('Camilo Núñez', 'Uruguay', 'nunez'),
	('Rodrigo Banegas', 'Bolivia', 'banegas'),
	('Rodrigo Banegas', 'Bolivia', 'rodrigo banegas'),
	('Joaquín Astorga', 'Peru', 'joaquin astorga'),
	('Joaquín Astorga', 'Peru', 'astorga'),
	('Marcos Delgado', 'Peru', 'marcos delgado'),
	('Marcos Delgado', 'Peru', 'delgado'),
	('Furkan Kircicek', 'Germany', 'furkan kircicek'),
	('Furkan Kircicek', 'Germany', 'kircicek'),
	('Stephen Sama', 'Germany', 'stephen sama'),
	('Stephen Sama', 'Germany', 'sama'),
	('Lóránt Kovács', 'Romania', 'lorant kovacs'),
	('Lóránt Kovács', 'Romania', 'kovacs'),
	('Homero Calderón', 'Venezuela', 'calderon'),
	('Homero Calderón', 'Venezuela', 'homero calderon'),
	('Jon Birkfeldt', 'Sweden', 'jon birkfeldt'),
	('Jon Birkfeldt', 'Sweden', 'birkfeldt'),
	('Matthias Phaëton', 'France', 'phaeton'),
	('Matthias Phaëton', 'France', 'matthias phaeton'),
	('Kevin Piscopo', 'Italy', 'kevin piscopo'),
	('Kevin Piscopo', 'Italy', 'piscopo'),
	('Corey Brown', 'Australia', 'brown'),
	('Corey Brown', 'Australia', 'corey brown'),
	('Yeerjieti Yeerzati', 'China PR', 'yeerzati'),
	('Yeerjieti Yeerzati', 'China PR', 'yeerjieti yeerzati'),
	('Jack Lankester', 'England', 'lankester'),
	('Jack Lankester', 'England', 'jack lankester'),
	('Oddbjørn Lie', 'Norway', 'oddbjrn lie'),
	('Oddbjørn Lie', 'Norway', 'lie'),
	('Callum Ainley', 'England', 'callum ainley'),
	('Callum Ainley', 'England', 'ainley')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';