INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Omar Rodríguez', 'Mexico', 'player'),
	('Tarryn Allarakhia', 'England', 'player'),
	('Ethan Dobbelaere', 'United States', 'player'),
	('Manasse Kusu', 'Sweden', 'player'),
	('Laorent Shabani', 'Albania', 'player'),
	('Dominic Revan', 'England', 'player'),
	('Damiano Pecile', 'Canada', 'player'),
	('Miguel Ángel Cornejo', 'Peru', 'player'),
	('Loïc Ritière', 'Belgium', 'player'),
	('Ben Garrity', 'England', 'player'),
	('Adrian Skrzyniak', 'Poland', 'player'),
	('Josias Lukembila', 'Switzerland', 'player'),
	('Liu Yue', 'China PR', 'player'),
	('Su Yuanjie', 'China PR', 'player'),
	('Tom Sang', 'England', 'player'),
	('Abdulbasit Abdullah', 'Saudi Arabia', 'player'),
	('Diego Castillo', 'Venezuela', 'player'),
	('Lee Gyu Seong', 'Korea Republic', 'player'),
	('Mateusz Lewandowski', 'Poland', 'player'),
	('Hernán Cardozo', 'Bolivia', 'player'),
	('Nick Hayes', 'England', 'player'),
	('Claudiu Borțoneanu', 'Romania', 'player'),
	('Devis Vásquez', 'Colombia', 'player'),
	('Jorben Vanhulle', 'Belgium', 'player'),
	('Santiago Hezze', 'Argentina', 'player'),
	('Kevin Andrade', 'Colombia', 'player'),
	('Scott Fenwick', 'England', 'player'),
	('Ezequiel Navarro', 'Argentina', 'player'),
	('Nawaf Boushal', 'Saudi Arabia', 'player'),
	('Arthur Iontton', 'England', 'player'),
	('Jack Brady', 'Republic of Ireland', 'player'),
	('Adem Husejnović', 'Bosnia Herzegovina', 'player'),
	('Jared Khasa', 'France', 'player'),
	('Julius Lindgren', 'Sweden', 'player'),
	('Dejan Djokic', 'Switzerland', 'player'),
	('Hector Kyprianou', 'Cyprus', 'player'),
	('Noah Smith', 'Australia', 'player'),
	('Hugo Keto', 'Finland', 'player'),
	('Cameron Evans', 'Wales', 'player'),
	('Lars Holtkamp', 'Germany', 'player'),
	('Montel Gibson', 'England', 'player'),
	('Devarn Green', 'England', 'player'),
	('Manny Adebowale', 'England', 'player'),
	('Kevin Egell-Johnsen', 'Norway', 'player'),
	('Casper Staring', 'Netherlands', 'player'),
	('Ma Sang Hoon', 'Korea Republic', 'player'),
	('Oliver Ottesen', 'Denmark', 'player'),
	('Eitaro Matsuda', 'Japan', 'player'),
	('Brayan Palmezano', 'Venezuela', 'player'),
	('Nathan Gartside', 'Northern Ireland', 'player'),
	('Kristian Popovic', 'Australia', 'player'),
	('Kim So Woong', 'Korea Republic', 'player'),
	('Bobby Edwards', 'United States', 'player'),
	('Umut Güneş', 'Turkey', 'player'),
	('Hamed Fallatah', 'Saudi Arabia', 'player'),
	('Xu Tianyuan', 'China PR', 'player'),
	('Matthéo Xantippe', 'France', 'player'),
	('Jannick Liburd', 'Denmark', 'player'),
	('Leodan Chalá', 'Ecuador', 'player'),
	('Ahmed Emad Eldeen Andejani', 'Saudi Arabia', 'player'),
	('Hugo Gambor', 'France', 'player'),
	('Duncan Turnbull', 'United States', 'player'),
	('Bas Van Den Eynden', 'Belgium', 'player'),
	('Lukas Fahrnberger', 'Austria', 'player'),
	('Marius B. Larsen', 'Norway', 'player'),
	('Zach Robinson', 'England', 'player'),
	('Ensar Arslan', 'Germany', 'player'),
	('Dylan Ruiz-Diaz', 'Australia', 'player'),
	('Karl O''Sullivan', 'Republic of Ireland', 'player'),
	('Felix Kekoh Ndifor II', 'Cameroon', 'player'),
	('Emmanuel Idem', 'England', 'player'),
	('Mathieu Cordier', 'Australia', 'player'),
	('Joachim Imbrechts', 'Sweden', 'player'),
	('Bandar Al Enezi', 'Saudi Arabia', 'player'),
	('Yoshiaki Arai', 'Japan', 'player'),
	('Jin Qiang', 'China PR', 'player'),
	('Yéiler Góez', 'Colombia', 'player'),
	('Jack Nolan', 'England', 'player'),
	('Ryan Longman', 'England', 'player'),
	('Wu Shaocong', 'China PR', 'player'),
	('Fahad Al Hamad', 'Saudi Arabia', 'player'),
	('Liam McGing', 'Australia', 'player'),
	('Filip Frei', 'Switzerland', 'player'),
	('Tomislav Uskok', 'Australia', 'player'),
	('Sun Shoubo', 'China PR', 'player'),
	('Max Rundqvist', 'Sweden', 'player'),
	('Diego Zago', 'Mexico', 'player'),
	('Tim Staubli', 'Switzerland', 'player'),
	('Genta Ito', 'Japan', 'player'),
	('Yusuf Hussain', 'Scotland', 'player'),
	('Tochi Chukwuani', 'Denmark', 'player'),
	('Ronan Hughes', 'Scotland', 'player'),
	('Wang Kai', 'China PR', 'player'),
	('Takahiro Nakazato', 'Japan', 'player'),
	('Ali Eren Yalçın', 'Turkey', 'player'),
	('Téo Herr', 'France', 'player'),
	('Cameron Dunbar', 'United States', 'player'),
	('Danny Preston', 'England', 'player'),
	('Camilo Albornoz', 'Argentina', 'player'),
	('Jökull Andrésson', 'Iceland', 'player'),
	('Tobias Klysner', 'Denmark', 'player'),
	('Nicolás Machado', 'Uruguay', 'player'),
	('Nico Lemoine', 'United States', 'player'),
	('Alex Hurst', 'England', 'player'),
	('Laurence Wyke', 'England', 'player'),
	('Rodrigo Vera', 'Paraguay', 'player'),
	('Kryss Chapelle', 'France', 'player'),
	('Carlos Montoya', 'Peru', 'player'),
	('Rassoul Ndiaye', 'France', 'player'),
	('Daniel Williams', 'Wales', 'player'),
	('Luke Cundle', 'England', 'player'),
	('Christian Gómez', 'Venezuela', 'player'),
	('Gabriel Johansson', 'Sweden', 'player'),
	('Daniels Ontužāns', 'Latvia', 'player'),
	('Serhat Tasdemir', 'Azerbaijan', 'player'),
	('Andreas Hellum', 'Norway', 'player'),
	('Luke McNicholas', 'Republic of Ireland', 'player'),
	('César Ramos', 'Mexico', 'player'),
	('Alex Cochrane', 'England', 'player'),
	('Jak Hickman', 'England', 'player'),
	('Rico Richards', 'England', 'player'),
	('David Ochoa', 'United States', 'player'),
	('Fredrik Hammar', 'Sweden', 'player'),
	('Ángel Luna', 'Uruguay', 'player'),
	('Gard Thomas', 'Norway', 'player'),
	('Seo Ju Hwan', 'Korea Republic', 'player'),
	('Yannick Marchand', 'Switzerland', 'player'),
	('Oliver Crankshaw', 'England', 'player'),
	('Eddy Mejía', 'Ecuador', 'player'),
	('Samuel Folarin', 'England', 'player'),
	('Imanol Enríquez', 'Argentina', 'player'),
	('Marcos Olmedo', 'Ecuador', 'player'),
	('Mohamed Adam', 'Sudan', 'player'),
	('Mark Coyle', 'Republic of Ireland', 'player'),
	('Adem Doğan', 'Turkey', 'player'),
	('Adonis Ajeti', 'Switzerland', 'player'),
	('Marcel Elva-Fountaine', 'England', 'player'),
	('Matthias Heiland', 'Germany', 'player'),
	('Aymen Boutoutaou', 'France', 'player'),
	('Rolando Arrasco', 'Peru', 'player'),
	('Benjamin Kimpioka', 'Sweden', 'player'),
	('Aiden Walker', 'England', 'player'),
	('Ren Wei', 'China PR', 'player'),
	('Joshua Render', 'England', 'player'),
	('Jay Barnett', 'Australia', 'player'),
	('Víctor González', 'Chile', 'player'),
	('Ryan Shanley', 'Scotland', 'player'),
	('Souleymane Anne', 'Mauritania', 'player'),
	('Cho Yoon Sung', 'Korea Republic', 'player'),
	('Hüseyin Altıntaş', 'Turkey', 'player'),
	('Tom Hendriks', 'Netherlands', 'player'),
	('Alex González', 'Paraguay', 'player'),
	('Ntazana Mayembe', 'England', 'player'),
	('Christian Sosa', 'Paraguay', 'player'),
	('Silvan Wallner', 'Switzerland', 'player'),
	('Brice Verkerken', 'Belgium', 'player'),
	('Christian Pastina', 'Italy', 'player'),
	('Vladislav Molchan', 'Russia', 'player'),
	('Sebastián Uzcátegui', 'Venezuela', 'player'),
	('Piao Taoyu', 'China PR', 'player'),
	('Bogdan Jica', 'Romania', 'player'),
	('Tim Möller', 'Germany', 'player'),
	('Tom Collins', 'England', 'player'),
	('Kristoffer Gunnarshaug', 'Norway', 'player'),
	('Nick Suman', 'Australia', 'player'),
	('Taiga Hata', 'Japan', 'player'),
	('Nader Al Sharari', 'Saudi Arabia', 'player'),
	('Ben Hughes', 'England', 'player'),
	('Jack Skahan', 'United States', 'player'),
	('Paolo Alcocer', 'Bolivia', 'player'),
	('Sigitas Olberkis', 'Lithuania', 'player'),
	('Jamie-Liam Shalom', 'Germany', 'player'),
	('James Gomez', 'Gambia', 'player'),
	('Fabio Solimando', 'Switzerland', 'player'),
	('Dennis Waidner', 'Germany', 'player'),
	('Oliver Cooper', 'Wales', 'player'),
	('Simon Gefvert', 'Sweden', 'player'),
	('Mauricio Matzuda', 'Peru', 'player'),
	('Matthew Blake', 'Wales', 'player'),
	('Max Hunt', 'England', 'player'),
	('Tariq Uwakwe', 'England', 'player'),
	('Nicholas Slonina', 'United States', 'player'),
	('Nawaf Al Habashi', 'Saudi Arabia', 'player'),
	('Juan Briones', 'Ecuador', 'player'),
	('Laurenz Beckemeyer', 'Germany', 'player'),
	('Jung Min Woo', 'Korea Republic', 'player'),
	('James Olayinka', 'England', 'player'),
	('Jakob Odehnal', 'Austria', 'player'),
	('Kevin Alaníz', 'Uruguay', 'player'),
	('Juan Camilo Moreno', 'Colombia', 'player'),
	('Daniel Obbekjær', 'Denmark', 'player'),
	('Edvin Crona', 'Sweden', 'player'),
	('Fabio Tavares', 'England', 'player'),
	('Sun Kai', 'China PR', 'player'),
	('Lundrim Hetemi', 'Albania', 'player'),
	('Abdullah Al Hassan', 'Saudi Arabia', 'player'),
	('Benedict Hollerbach', 'Germany', 'player'),
	('Alidu Seidu', 'Ivory Coast', 'player'),
	('Eddie Munjoma', 'United States', 'player'),
	('Yackson Rivas', 'Venezuela', 'player'),
	('Qi Yuxi', 'China PR', 'player'),
	('Zhang Gong', 'China PR', 'player'),
	('Billy Chadwick', 'England', 'player'),
	('Leon Pöhls', 'Germany', 'player'),
	('Francisco Duclós', 'Peru', 'player'),
	('Oliver Daedlow', 'Germany', 'player'),
	('Dominique Youfeigane', 'France', 'player'),
	('Kit Elliott', 'England', 'player'),
	('Nikola Tavares', 'Croatia', 'player'),
	('Lleyton Brooks', 'Australia', 'player'),
	('Nawaf Al Ghamdi', 'Saudi Arabia', 'player'),
	('Keaton Ward', 'England', 'player'),
	('Lewis Freestone', 'England', 'player'),
	('Kristoffer Stephensen', 'Norway', 'player'),
	('Daiki Mitsui', 'Japan', 'player'),
	('Michael Wagner', 'Germany', 'player'),
	('Reece Staunton', 'Republic of Ireland', 'player'),
	('Marley Marshall-Miranda', 'England', 'player'),
	('Bjørn Mæland', 'Norway', 'player'),
	('Lirik Vishi', 'Switzerland', 'player'),
	('Matthew Sutton', 'Australia', 'player'),
	('Andreas Nyhagen', 'Norway', 'player'),
	('Billy Mitchell', 'England', 'player'),
	('Muhammadu Faal', 'England', 'player'),
	('Brad Binns', 'England', 'player'),
	('Franco Medina', 'Peru', 'player'),
	('Jordan Helliwell', 'England', 'player'),
	('Adam Randell', 'England', 'player'),
	('Rumarn Burrell', 'England', 'player'),
	('Sonny Graham', 'England', 'player'),
	('Elias Skogvoll', 'Norway', 'player'),
	('Josh Neufville', 'England', 'player'),
	('Juan Nieva', 'Colombia', 'player'),
	('Henry Jon Crosthwaite', 'Germany', 'player'),
	('Alfonso Ocampo-Chavez', 'United States', 'player'),
	('Hong Si Hoo', 'Korea Republic', 'player'),
	('Hassan Al Slais', 'Saudi Arabia', 'player'),
	('Mario Barbery', 'Bolivia', 'player'),
	('Jai Rowe', 'England', 'player'),
	('Terry Taylor', 'Wales', 'player'),
	('Jorge Echeverría', 'Venezuela', 'player'),
	('Aaron Dobbs', 'Republic of Ireland', 'player'),
	('Tim Schreiber', 'Germany', 'player'),
	('Mason O''Malley', 'Republic of Ireland', 'player'),
	('Santiago Zamora', 'Ecuador', 'player'),
	('Justin Butler', 'United States', 'player'),
	('Drake Callender', 'United States', 'player'),
	('George Harmon', 'England', 'player'),
	('Matteo Regillo', 'Switzerland', 'player'),
	('Gion Fadri Chande', 'Switzerland', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Omar Rodríguez', 'Mexico', 'rodriguez'),
	('Omar Rodríguez', 'Mexico', 'omar rodriguez'),
	('Tarryn Allarakhia', 'England', 'tarryn allarakhia'),
	('Tarryn Allarakhia', 'England', 'allarakhia'),
	('Ethan Dobbelaere', 'United States', 'dobbelaere'),
	('Ethan Dobbelaere', 'United States', 'ethan dobbelaere'),
	('Manasse Kusu', 'Sweden', 'kusu'),
	('Manasse Kusu', 'Sweden', 'manasse kusu'),
	('Laorent Shabani', 'Albania', 'laorent shabani'),
	('Laorent Shabani', 'Albania', 'shabani'),
	('Dominic Revan', 'England', 'revan'),
	('Dominic Revan', 'England', 'dominic revan'),
	('Damiano Pecile', 'Canada', 'damiano pecile'),
	('Damiano Pecile', 'Canada', 'pecile'),
	('Miguel Ángel Cornejo', 'Peru', 'cornejo'),
	('Miguel Ángel Cornejo', 'Peru', 'miguel angel cornejo'),
	('Loïc Ritière', 'Belgium', 'ritiere'),
	('Loïc Ritière', 'Belgium', 'loic ritiere'),
	('Ben Garrity', 'England', 'garrity'),
	('Ben Garrity', 'England', 'ben garrity'),
	('Adrian Skrzyniak', 'Poland', 'skrzyniak'),
	('Adrian Skrzyniak', 'Poland', 'adrian skrzyniak'),
	('Josias Lukembila', 'Switzerland', 'lukembila'),
	('Josias Lukembila', 'Switzerland', 'josias lukembila'),
	('Liu Yue', 'China PR', 'yue'),
	('Liu Yue', 'China PR', 'liu yue'),
	('Su Yuanjie', 'China PR', 'su yuanjie'),
	('Su Yuanjie', 'China PR', 'yuanjie'),
	('Tom Sang', 'England', 'tom sang'),
	('Tom Sang', 'England', 'sang'),
	('Abdulbasit Abdullah', 'Saudi Arabia', 'abdulbasit abdullah'),
	('Abdulbasit Abdullah', 'Saudi Arabia', 'abdullah'),
	('Diego Castillo', 'Venezuela', 'diego castillo'),
	('Diego Castillo', 'Venezuela', 'castillo'),
	('Lee Gyu Seong', 'Korea Republic', 'seong'),
	('Lee Gyu Seong', 'Korea Republic', 'lee gyu seong'),
	('Mateusz Lewandowski', 'Poland', 'mateusz lewandowski'),
	('Mateusz Lewandowski', 'Poland', 'lewandowski'),
	('Hernán Cardozo', 'Bolivia', 'hernan cardozo'),
	('Hernán Cardozo', 'Bolivia', 'cardozo'),
	('Nick Hayes', 'England', 'hayes'),
	('Nick Hayes', 'England', 'nick hayes'),
	('Claudiu Borțoneanu', 'Romania', 'claudiu bortoneanu'),
	('Claudiu Borțoneanu', 'Romania', 'bortoneanu'),
	('Devis Vásquez', 'Colombia', 'devis vasquez'),
	('Devis Vásquez', 'Colombia', 'vasquez'),
	('Jorben Vanhulle', 'Belgium', 'vanhulle'),
	('Jorben Vanhulle', 'Belgium', 'jorben vanhulle'),
	('Santiago Hezze', 'Argentina', 'santiago hezze'),
	('Santiago Hezze', 'Argentina', 'hezze'),
	('Kevin Andrade', 'Colombia', 'andrade'),
	('Kevin Andrade', 'Colombia', 'kevin andrade'),
	('Scott Fenwick', 'England', 'scott fenwick'),
	('Scott Fenwick', 'England', 'fenwick'),
	('Ezequiel Navarro', 'Argentina', 'navarro'),
	('Ezequiel Navarro', 'Argentina', 'ezequiel navarro'),
	('Nawaf Boushal', 'Saudi Arabia', 'nawaf boushal'),
	('Nawaf Boushal', 'Saudi Arabia', 'boushal'),
	('Arthur Iontton', 'England', 'arthur iontton'),
	('Arthur Iontton', 'England', 'iontton'),
	('Jack Brady', 'Republic of Ireland', 'brady'),
	('Jack Brady', 'Republic of Ireland', 'jack brady'),
	('Adem Husejnović', 'Bosnia Herzegovina', 'husejnovic'),
	('Adem Husejnović', 'Bosnia Herzegovina', 'adem husejnovic'),
	('Jared Khasa', 'France', 'jared khasa'),
	('Jared Khasa', 'France', 'khasa'),
	('Julius Lindgren', 'Sweden', 'lindgren'),
	('Julius Lindgren', 'Sweden', 'julius lindgren'),
	('Dejan Djokic', 'Switzerland', 'djokic'),
	('Dejan Djokic', 'Switzerland', 'dejan djokic'),
	('Hector Kyprianou', 'Cyprus', 'kyprianou'),
	('Hector Kyprianou', 'Cyprus', 'hector kyprianou'),
	('Noah Smith', 'Australia', 'smith'),
	('Noah Smith', 'Australia', 'noah smith'),
	('Hugo Keto', 'Finland', 'hugo keto'),
	('Hugo Keto', 'Finland', 'keto'),
	('Cameron Evans', 'Wales', 'cameron evans'),
	('Cameron Evans', 'Wales', 'evans'),
	('Lars Holtkamp', 'Germany', 'holtkamp'),
	('Lars Holtkamp', 'Germany', 'lars holtkamp'),
	('Montel Gibson', 'England', 'montel gibson'),
	('Montel Gibson', 'England', 'gibson'),
	('Devarn Green', 'England', 'devarn green'),
	('Devarn Green', 'England', 'green'),
	('Manny Adebowale', 'England', 'adebowale'),
	('Manny Adebowale', 'England', 'manny adebowale'),
	('Kevin Egell-Johnsen', 'Norway', 'kevin egelljohnsen'),
	('Kevin Egell-Johnsen', 'Norway', 'egelljohnsen'),
	('Casper Staring', 'Netherlands', 'casper staring'),
	('Casper Staring', 'Netherlands', 'staring'),
	('Ma Sang Hoon', 'Korea Republic', 'ma sang hoon'),
	('Ma Sang Hoon', 'Korea Republic', 'hoon'),
	('Oliver Ottesen', 'Denmark', 'ottesen'),
	('Oliver Ottesen', 'Denmark', 'oliver ottesen'),
	('Eitaro Matsuda', 'Japan', 'matsuda'),
	('Eitaro Matsuda', 'Japan', 'eitaro matsuda'),
	('Brayan Palmezano', 'Venezuela', 'palmezano'),
	('Brayan Palmezano', 'Venezuela', 'brayan palmezano'),
	('Nathan Gartside', 'Northern Ireland', 'gartside'),
	('Nathan Gartside', 'Northern Ireland', 'nathan gartside'),
	('Kristian Popovic', 'Australia', 'popovic'),
	('Kristian Popovic', 'Australia', 'kristian popovic'),
	('Kim So Woong', 'Korea Republic', 'woong'),
	('Kim So Woong', 'Korea Republic', 'kim so woong'),
	('Bobby Edwards', 'United States', 'edwards'),
	('Bobby Edwards', 'United States', 'bobby edwards'),
	('Umut Güneş', 'Turkey', 'umut gunes'),
	('Umut Güneş', 'Turkey', 'gunes'),
	('Hamed Fallatah', 'Saudi Arabia', 'hamed fallatah'),
	('Hamed Fallatah', 'Saudi Arabia', 'fallatah'),
	('Xu Tianyuan', 'China PR', 'xu tianyuan'),
	('Xu Tianyuan', 'China PR', 'tianyuan'),
	('Matthéo Xantippe', 'France', 'mattheo xantippe'),
	('Matthéo Xantippe', 'France', 'xantippe'),
	('Jannick Liburd', 'Denmark', 'liburd'),
	('Jannick Liburd', 'Denmark', 'jannick liburd'),
	('Leodan Chalá', 'Ecuador', 'leodan chala'),
	('Leodan Chalá', 'Ecuador', 'chala'),
	('Ahmed Emad Eldeen Andejani', 'Saudi Arabia', 'ahmed emad eldeen andejani'),
	('Ahmed Emad Eldeen Andejani', 'Saudi Arabia', 'andejani'),
	('Hugo Gambor', 'France', 'gambor'),
	('Hugo Gambor', 'France', 'hugo gambor'),
	('Duncan Turnbull', 'United States', 'duncan turnbull'),
	('Duncan Turnbull', 'United States', 'turnbull'),
	('Bas Van Den Eynden', 'Belgium', 'eynden'),
	('Bas Van Den Eynden', 'Belgium', 'bas van den eynden'),
	('Lukas Fahrnberger', 'Austria', 'lukas fahrnberger'),
	('Lukas Fahrnberger', 'Austria', 'fahrnberger'),
	('Marius B. Larsen', 'Norway', 'marius b larsen'),
	('Marius B. Larsen', 'Norway', 'larsen'),
	('Zach Robinson', 'England', 'robinson'),
	('Zach Robinson', 'England', 'zach robinson'),
	('Ensar Arslan', 'Germany', 'arslan'),
	('Ensar Arslan', 'Germany', 'ensar arslan'),
	('Dylan Ruiz-Diaz', 'Australia', 'dylan ruizdiaz'),
	('Dylan Ruiz-Diaz', 'Australia', 'ruizdiaz'),
	('Karl O''Sullivan', 'Republic of Ireland', 'karl osullivan'),
	('Karl O''Sullivan', 'Republic of Ireland', 'osullivan'),
	('Felix Kekoh Ndifor II', 'Cameroon', 'ii'),
	('Felix Kekoh Ndifor II', 'Cameroon', 'felix kekoh ndifor ii'),
	('Emmanuel Idem', 'England', 'idem'),
	('Emmanuel Idem', 'England', 'emmanuel idem'),
	('Mathieu Cordier', 'Australia', 'mathieu cordier'),
	('Mathieu Cordier', 'Australia', 'cordier'),
	('Joachim Imbrechts', 'Sweden', 'joachim imbrechts'),
	('Joachim Imbrechts', 'Sweden', 'imbrechts'),
	('Bandar Al Enezi', 'Saudi Arabia', 'bandar al enezi'),
	('Bandar Al Enezi', 'Saudi Arabia', 'enezi'),
	('Yoshiaki Arai', 'Japan', 'arai'),
	('Yoshiaki Arai', 'Japan', 'yoshiaki arai'),
	('Jin Qiang', 'China PR', 'qiang'),
	('Jin Qiang', 'China PR', 'jin qiang'),
	('Yéiler Góez', 'Colombia', 'goez'),
	('Yéiler Góez', 'Colombia', 'yeiler goez'),
	('Jack Nolan', 'England', 'jack nolan'),
	('Jack Nolan', 'England', 'nolan'),
	('Ryan Longman', 'England', 'ryan longman'),
	('Ryan Longman', 'England', 'longman'),
	('Wu Shaocong', 'China PR', 'shaocong'),
	('Wu Shaocong', 'China PR', 'wu shaocong'),
	('Fahad Al Hamad', 'Saudi Arabia', 'fahad al hamad'),
	('Fahad Al Hamad', 'Saudi Arabia', 'hamad'),
	('Liam McGing', 'Australia', 'liam mcging'),
	('Liam McGing', 'Australia', 'mcging'),
	('Filip Frei', 'Switzerland', 'filip frei'),
	('Filip Frei', 'Switzerland', 'frei'),
	('Tomislav Uskok', 'Australia', 'tomislav uskok'),
	('Tomislav Uskok', 'Australia', 'uskok'),
	('Sun Shoubo', 'China PR', 'sun shoubo'),
	('Sun Shoubo', 'China PR', 'shoubo'),
	('Max Rundqvist', 'Sweden', 'rundqvist'),
	('Max Rundqvist', 'Sweden', 'max rundqvist'),
	('Diego Zago', 'Mexico', 'diego zago'),
	('Diego Zago', 'Mexico', 'zago'),
	('Tim Staubli', 'Switzerland', 'tim staubli'),
	('Tim Staubli', 'Switzerland', 'staubli'),
	('Genta Ito', 'Japan', 'genta ito'),
	('Genta Ito', 'Japan', 'ito'),
	('Yusuf Hussain', 'Scotland', 'hussain'),
	('Yusuf Hussain', 'Scotland', 'yusuf hussain'),
	('Tochi Chukwuani', 'Denmark', 'chukwuani'),
	('Tochi Chukwuani', 'Denmark', 'tochi chukwuani'),
	('Ronan Hughes', 'Scotland', 'ronan hughes'),
	('Ronan Hughes', 'Scotland', 'hughes'),
	('Wang Kai', 'China PR', 'wang kai'),
	('Wang Kai', 'China PR', 'kai'),
	('Takahiro Nakazato', 'Japan', 'nakazato'),
	('Takahiro Nakazato', 'Japan', 'takahiro nakazato'),
	('Ali Eren Yalçın', 'Turkey', 'yalcn'),
	('Ali Eren Yalçın', 'Turkey', 'ali eren yalcn'),
	('Téo Herr', 'France', 'herr'),
	('Téo Herr', 'France', 'teo herr'),
	('Cameron Dunbar', 'United States', 'dunbar'),
	('Cameron Dunbar', 'United States', 'cameron dunbar'),
	('Danny Preston', 'England', 'preston'),
	('Danny Preston', 'England', 'danny preston'),
	('Camilo Albornoz', 'Argentina', 'albornoz'),
	('Camilo Albornoz', 'Argentina', 'camilo albornoz'),
	('Jökull Andrésson', 'Iceland', 'andresson'),
	('Jökull Andrésson', 'Iceland', 'jokull andresson'),
	('Tobias Klysner', 'Denmark', 'tobias klysner'),
	('Tobias Klysner', 'Denmark', 'klysner'),
	('Nicolás Machado', 'Uruguay', 'machado'),
	('Nicolás Machado', 'Uruguay', 'nicolas machado'),
	('Nico Lemoine', 'United States', 'nico lemoine'),
	('Nico Lemoine', 'United States', 'lemoine'),
	('Alex Hurst', 'England', 'alex hurst'),
	('Alex Hurst', 'England', 'hurst'),
	('Laurence Wyke', 'England', 'wyke'),
	('Laurence Wyke', 'England', 'laurence wyke'),
	('Rodrigo Vera', 'Paraguay', 'vera'),
	('Rodrigo Vera', 'Paraguay', 'rodrigo vera'),
	('Kryss Chapelle', 'France', 'kryss chapelle'),
	('Kryss Chapelle', 'France', 'chapelle'),
	('Carlos Montoya', 'Peru', 'carlos montoya'),
	('Carlos Montoya', 'Peru', 'montoya'),
	('Rassoul Ndiaye', 'France', 'ndiaye'),
	('Rassoul Ndiaye', 'France', 'rassoul ndiaye'),
	('Daniel Williams', 'Wales', 'daniel williams'),
	('Daniel Williams', 'Wales', 'williams'),
	('Luke Cundle', 'England', 'cundle'),
	('Luke Cundle', 'England', 'luke cundle'),
	('Christian Gómez', 'Venezuela', 'gomez'),
	('Christian Gómez', 'Venezuela', 'christian gomez'),
	('Gabriel Johansson', 'Sweden', 'gabriel johansson'),
	('Gabriel Johansson', 'Sweden', 'johansson'),
	('Daniels Ontužāns', 'Latvia', 'ontuzans'),
	('Daniels Ontužāns', 'Latvia', 'daniels ontuzans'),
	('Serhat Tasdemir', 'Azerbaijan', 'serhat tasdemir'),
	('Serhat Tasdemir', 'Azerbaijan', 'tasdemir'),
	('Andreas Hellum', 'Norway', 'andreas hellum'),
	('Andreas Hellum', 'Norway', 'hellum'),
	('Luke McNicholas', 'Republic of Ireland', 'luke mcnicholas'),
	('Luke McNicholas', 'Republic of Ireland', 'mcnicholas'),
	('César Ramos', 'Mexico', 'cesar ramos'),
	('César Ramos', 'Mexico', 'ramos'),
	('Alex Cochrane', 'England', 'cochrane'),
	('Alex Cochrane', 'England', 'alex cochrane'),
	('Jak Hickman', 'England', 'hickman'),
	('Jak Hickman', 'England', 'jak hickman'),
	('Rico Richards', 'England', 'richards'),
	('Rico Richards', 'England', 'rico richards'),
	('David Ochoa', 'United States', 'ochoa'),
	('David Ochoa', 'United States', 'david ochoa'),
	('Fredrik Hammar', 'Sweden', 'fredrik hammar'),
	('Fredrik Hammar', 'Sweden', 'hammar'),
	('Ángel Luna', 'Uruguay', 'angel luna'),
	('Ángel Luna', 'Uruguay', 'luna'),
	('Gard Thomas', 'Norway', 'gard thomas'),
	('Gard Thomas', 'Norway', 'thomas'),
	('Seo Ju Hwan', 'Korea Republic', 'hwan'),
	('Seo Ju Hwan', 'Korea Republic', 'seo ju hwan'),
	('Yannick Marchand', 'Switzerland', 'yannick marchand'),
	('Yannick Marchand', 'Switzerland', 'marchand'),
	('Oliver Crankshaw', 'England', 'oliver crankshaw'),
	('Oliver Crankshaw', 'England', 'crankshaw'),
	('Eddy Mejía', 'Ecuador', 'eddy mejia'),
	('Eddy Mejía', 'Ecuador', 'mejia'),
	('Samuel Folarin', 'England', 'samuel folarin'),
	('Samuel Folarin', 'England', 'folarin'),
	('Imanol Enríquez', 'Argentina', 'imanol enriquez'),
	('Imanol Enríquez', 'Argentina', 'enriquez'),
	('Marcos Olmedo', 'Ecuador', 'olmedo'),
	('Marcos Olmedo', 'Ecuador', 'marcos olmedo'),
	('Mohamed Adam', 'Sudan', 'mohamed adam'),
	('Mohamed Adam', 'Sudan', 'adam'),
	('Mark Coyle', 'Republic of Ireland', 'coyle'),
	('Mark Coyle', 'Republic of Ireland', 'mark coyle'),
	('Adem Doğan', 'Turkey', 'dogan'),
	('Adem Doğan', 'Turkey', 'adem dogan'),
	('Adonis Ajeti', 'Switzerland', 'ajeti'),
	('Adonis Ajeti', 'Switzerland', 'adonis ajeti'),
	('Marcel Elva-Fountaine', 'England', 'marcel elvafountaine'),
	('Marcel Elva-Fountaine', 'England', 'elvafountaine'),
	('Matthias Heiland', 'Germany', 'heiland'),
	('Matthias Heiland', 'Germany', 'matthias heiland'),
	('Aymen Boutoutaou', 'France', 'aymen boutoutaou'),
	('Aymen Boutoutaou', 'France', 'boutoutaou'),
	('Rolando Arrasco', 'Peru', 'rolando arrasco'),
	('Rolando Arrasco', 'Peru', 'arrasco'),
	('Benjamin Kimpioka', 'Sweden', 'benjamin kimpioka'),
	('Benjamin Kimpioka', 'Sweden', 'kimpioka'),
	('Aiden Walker', 'England', 'aiden walker'),
	('Aiden Walker', 'England', 'walker'),
	('Ren Wei', 'China PR', 'ren wei'),
	('Ren Wei', 'China PR', 'wei'),
	('Joshua Render', 'England', 'render'),
	('Joshua Render', 'England', 'joshua render'),
	('Jay Barnett', 'Australia', 'barnett'),
	('Jay Barnett', 'Australia', 'jay barnett'),
	('Víctor González', 'Chile', 'gonzalez'),
	('Víctor González', 'Chile', 'victor gonzalez'),
	('Ryan Shanley', 'Scotland', 'ryan shanley'),
	('Ryan Shanley', 'Scotland', 'shanley'),
	('Souleymane Anne', 'Mauritania', 'souleymane anne'),
	('Souleymane Anne', 'Mauritania', 'anne'),
	('Cho Yoon Sung', 'Korea Republic', 'cho yoon sung'),
	('Cho Yoon Sung', 'Korea Republic', 'sung'),
	('Hüseyin Altıntaş', 'Turkey', 'altntas'),
	('Hüseyin Altıntaş', 'Turkey', 'huseyin altntas'),
	('Tom Hendriks', 'Netherlands', 'hendriks'),
	('Tom Hendriks', 'Netherlands', 'tom hendriks'),
	('Alex González', 'Paraguay', 'alex gonzalez'),
	('Alex González', 'Paraguay', 'gonzalez'),
	('Ntazana Mayembe', 'England', 'ntazana mayembe'),
	('Ntazana Mayembe', 'England', 'mayembe'),
	('Christian Sosa', 'Paraguay', 'sosa'),
	('Christian Sosa', 'Paraguay', 'christian sosa'),
	('Silvan Wallner', 'Switzerland', 'silvan wallner'),
	('Silvan Wallner', 'Switzerland', 'wallner'),
	('Brice Verkerken', 'Belgium', 'verkerken'),
	('Brice Verkerken', 'Belgium', 'brice verkerken'),
	('Christian Pastina', 'Italy', 'christian pastina'),
	('Christian Pastina', 'Italy', 'pastina'),
	('Vladislav Molchan', 'Russia', 'vladislav molchan'),
	('Vladislav Molchan', 'Russia', 'molchan'),
	('Sebastián Uzcátegui', 'Venezuela', 'uzcategui'),
	('Sebastián Uzcátegui', 'Venezuela', 'sebastian uzcategui'),
	('Piao Taoyu', 'China PR', 'piao taoyu'),
	('Piao Taoyu', 'China PR', 'taoyu'),
	('Bogdan Jica', 'Romania', 'bogdan jica'),
	('Bogdan Jica', 'Romania', 'jica'),
	('Tim Möller', 'Germany', 'moller'),
	('Tim Möller', 'Germany', 'tim moller'),
	('Tom Collins', 'England', 'collins'),
	('Tom Collins', 'England', 'tom collins'),
	('Kristoffer Gunnarshaug', 'Norway', 'gunnarshaug'),
	('Kristoffer Gunnarshaug', 'Norway', 'kristoffer gunnarshaug'),
	('Nick Suman', 'Australia', 'suman'),
	('Nick Suman', 'Australia', 'nick suman'),
	('Taiga Hata', 'Japan', 'taiga hata'),
	('Taiga Hata', 'Japan', 'hata'),
	('Nader Al Sharari', 'Saudi Arabia', 'nader al sharari'),
	('Nader Al Sharari', 'Saudi Arabia', 'sharari'),
	('Ben Hughes', 'England', 'hughes'),
	('Ben Hughes', 'England', 'ben hughes'),
	('Jack Skahan', 'United States', 'jack skahan'),
	('Jack Skahan', 'United States', 'skahan'),
	('Paolo Alcocer', 'Bolivia', 'paolo alcocer'),
	('Paolo Alcocer', 'Bolivia', 'alcocer'),
	('Sigitas Olberkis', 'Lithuania', 'olberkis'),
	('Sigitas Olberkis', 'Lithuania', 'sigitas olberkis'),
	('Jamie-Liam Shalom', 'Germany', 'shalom'),
	('Jamie-Liam Shalom', 'Germany', 'jamieliam shalom'),
	('James Gomez', 'Gambia', 'gomez'),
	('James Gomez', 'Gambia', 'james gomez'),
	('Fabio Solimando', 'Switzerland', 'fabio solimando'),
	('Fabio Solimando', 'Switzerland', 'solimando'),
	('Dennis Waidner', 'Germany', 'waidner'),
	('Dennis Waidner', 'Germany', 'dennis waidner'),
	('Oliver Cooper', 'Wales', 'oliver cooper'),
	('Oliver Cooper', 'Wales', 'cooper'),
	('Simon Gefvert', 'Sweden', 'simon gefvert'),
	('Simon Gefvert', 'Sweden', 'gefvert'),
	('Mauricio Matzuda', 'Peru', 'mauricio matzuda'),
	('Mauricio Matzuda', 'Peru', 'matzuda'),
	('Matthew Blake', 'Wales', 'matthew blake'),
	('Matthew Blake', 'Wales', 'blake'),
	('Max Hunt', 'England', 'max hunt'),
	('Max Hunt', 'England', 'hunt'),
	('Tariq Uwakwe', 'England', 'uwakwe'),
	('Tariq Uwakwe', 'England', 'tariq uwakwe'),
	('Nicholas Slonina', 'United States', 'nicholas slonina'),
	('Nicholas Slonina', 'United States', 'slonina'),
	('Nawaf Al Habashi', 'Saudi Arabia', 'habashi'),
	('Nawaf Al Habashi', 'Saudi Arabia', 'nawaf al habashi'),
	('Juan Briones', 'Ecuador', 'juan briones'),
	('Juan Briones', 'Ecuador', 'briones'),
	('Laurenz Beckemeyer', 'Germany', 'laurenz beckemeyer'),
	('Laurenz Beckemeyer', 'Germany', 'beckemeyer'),
	('Jung Min Woo', 'Korea Republic', 'jung min woo'),
	('Jung Min Woo', 'Korea Republic', 'woo'),
	('James Olayinka', 'England', 'olayinka'),
	('James Olayinka', 'England', 'james olayinka'),
	('Jakob Odehnal', 'Austria', 'odehnal'),
	('Jakob Odehnal', 'Austria', 'jakob odehnal'),
	('Kevin Alaníz', 'Uruguay', 'kevin alaniz'),
	('Kevin Alaníz', 'Uruguay', 'alaniz'),
	('Juan Camilo Moreno', 'Colombia', 'moreno'),
	('Juan Camilo Moreno', 'Colombia', 'juan camilo moreno'),
	('Daniel Obbekjær', 'Denmark', 'obbekjr'),
	('Daniel Obbekjær', 'Denmark', 'daniel obbekjr'),
	('Edvin Crona', 'Sweden', 'crona'),
	('Edvin Crona', 'Sweden', 'edvin crona'),
	('Fabio Tavares', 'England', 'fabio tavares'),
	('Fabio Tavares', 'England', 'tavares'),
	('Sun Kai', 'China PR', 'kai'),
	('Sun Kai', 'China PR', 'sun kai'),
	('Lundrim Hetemi', 'Albania', 'lundrim hetemi'),
	('Lundrim Hetemi', 'Albania', 'hetemi'),
	('Abdullah Al Hassan', 'Saudi Arabia', 'abdullah al hassan'),
	('Abdullah Al Hassan', 'Saudi Arabia', 'hassan'),
	('Benedict Hollerbach', 'Germany', 'hollerbach'),
	('Benedict Hollerbach', 'Germany', 'benedict hollerbach'),
	('Alidu Seidu', 'Ivory Coast', 'alidu seidu'),
	('Alidu Seidu', 'Ivory Coast', 'seidu'),
	('Eddie Munjoma', 'United States', 'munjoma'),
	('Eddie Munjoma', 'United States', 'eddie munjoma'),
	('Yackson Rivas', 'Venezuela', 'yackson rivas'),
	('Yackson Rivas', 'Venezuela', 'rivas'),
	('Qi Yuxi', 'China PR', 'yuxi'),
	('Qi Yuxi', 'China PR', 'qi yuxi'),
	('Zhang Gong', 'China PR', 'zhang gong'),
	('Zhang Gong', 'China PR', 'gong'),
	('Billy Chadwick', 'England', 'billy chadwick'),
	('Billy Chadwick', 'England', 'chadwick'),
	('Leon Pöhls', 'Germany', 'leon pohls'),
	('Leon Pöhls', 'Germany', 'pohls'),
	('Francisco Duclós', 'Peru', 'francisco duclos'),
	('Francisco Duclós', 'Peru', 'duclos'),
	('Oliver Daedlow', 'Germany', 'daedlow'),
	('Oliver Daedlow', 'Germany', 'oliver daedlow'),
	('Dominique Youfeigane', 'France', 'youfeigane'),
	('Dominique Youfeigane', 'France', 'dominique youfeigane'),
	('Kit Elliott', 'England', 'kit elliott'),
	('Kit Elliott', 'England', 'elliott'),
	('Nikola Tavares', 'Croatia', 'nikola tavares'),
	('Nikola Tavares', 'Croatia', 'tavares'),
	('Lleyton Brooks', 'Australia', 'lleyton brooks'),
	('Lleyton Brooks', 'Australia', 'brooks'),
	('Nawaf Al Ghamdi', 'Saudi Arabia', 'ghamdi'),
	('Nawaf Al Ghamdi', 'Saudi Arabia', 'nawaf al ghamdi'),
	('Keaton Ward', 'England', 'ward'),
	('Keaton Ward', 'England', 'keaton ward'),
	('Lewis Freestone', 'England', 'freestone'),
	('Lewis Freestone', 'England', 'lewis freestone'),
	('Kristoffer Stephensen', 'Norway', 'kristoffer stephensen'),
	('Kristoffer Stephensen', 'Norway', 'stephensen'),
	('Daiki Mitsui', 'Japan', 'mitsui'),
	('Daiki Mitsui', 'Japan', 'daiki mitsui'),
	('Michael Wagner', 'Germany', 'michael wagner'),
	('Michael Wagner', 'Germany', 'wagner'),
	('Reece Staunton', 'Republic of Ireland', 'staunton'),
	('Reece Staunton', 'Republic of Ireland', 'reece staunton'),
	('Marley Marshall-Miranda', 'England', 'marley marshallmiranda'),
	('Marley Marshall-Miranda', 'England', 'marshallmiranda'),
	('Bjørn Mæland', 'Norway', 'bjrn mland'),
	('Bjørn Mæland', 'Norway', 'mland'),
	('Lirik Vishi', 'Switzerland', 'lirik vishi'),
	('Lirik Vishi', 'Switzerland', 'vishi'),
	('Matthew Sutton', 'Australia', 'sutton'),
	('Matthew Sutton', 'Australia', 'matthew sutton'),
	('Andreas Nyhagen', 'Norway', 'andreas nyhagen'),
	('Andreas Nyhagen', 'Norway', 'nyhagen'),
	('Billy Mitchell', 'England', 'mitchell'),
	('Billy Mitchell', 'England', 'billy mitchell'),
	('Muhammadu Faal', 'England', 'faal'),
	('Muhammadu Faal', 'England', 'muhammadu faal'),
	('Brad Binns', 'England', 'brad binns'),
	('Brad Binns', 'England', 'binns'),
	('Franco Medina', 'Peru', 'medina'),
	('Franco Medina', 'Peru', 'franco medina'),
	('Jordan Helliwell', 'England', 'helliwell'),
	('Jordan Helliwell', 'England', 'jordan helliwell'),
	('Adam Randell', 'England', 'randell'),
	('Adam Randell', 'England', 'adam randell'),
	('Rumarn Burrell', 'England', 'rumarn burrell'),
	('Rumarn Burrell', 'England', 'burrell'),
	('Sonny Graham', 'England', 'sonny graham'),
	('Sonny Graham', 'England', 'graham'),
	('Elias Skogvoll', 'Norway', 'skogvoll'),
	('Elias Skogvoll', 'Norway', 'elias skogvoll'),
	('Josh Neufville', 'England', 'neufville'),
	('Josh Neufville', 'England', 'josh neufville'),
	('Juan Nieva', 'Colombia', 'juan nieva'),
	('Juan Nieva', 'Colombia', 'nieva'),
	('Henry Jon Crosthwaite', 'Germany', 'henry jon crosthwaite'),
	('Henry Jon Crosthwaite', 'Germany', 'crosthwaite'),
	('Alfonso Ocampo-Chavez', 'United States', 'ocampochavez'),
	('Alfonso Ocampo-Chavez', 'United States', 'alfonso ocampochavez'),
	('Hong Si Hoo', 'Korea Republic', 'hong si hoo'),
	('Hong Si Hoo', 'Korea Republic', 'hoo'),
	('Hassan Al Slais', 'Saudi Arabia', 'slais'),
	('Hassan Al Slais', 'Saudi Arabia', 'hassan al slais'),
	('Mario Barbery', 'Bolivia', 'barbery'),
	('Mario Barbery', 'Bolivia', 'mario barbery'),
	('Jai Rowe', 'England', 'rowe'),
	('Jai Rowe', 'England', 'jai rowe'),
	('Terry Taylor', 'Wales', 'taylor'),
	('Terry Taylor', 'Wales', 'terry taylor'),
	('Jorge Echeverría', 'Venezuela', 'echeverria'),
	('Jorge Echeverría', 'Venezuela', 'jorge echeverria'),
	('Aaron Dobbs', 'Republic of Ireland', 'dobbs'),
	('Aaron Dobbs', 'Republic of Ireland', 'aaron dobbs'),
	('Tim Schreiber', 'Germany', 'schreiber'),
	('Tim Schreiber', 'Germany', 'tim schreiber'),
	('Mason O''Malley', 'Republic of Ireland', 'mason omalley'),
	('Mason O''Malley', 'Republic of Ireland', 'omalley'),
	('Santiago Zamora', 'Ecuador', 'zamora'),
	('Santiago Zamora', 'Ecuador', 'santiago zamora'),
	('Justin Butler', 'United States', 'justin butler'),
	('Justin Butler', 'United States', 'butler'),
	('Drake Callender', 'United States', 'drake callender'),
	('Drake Callender', 'United States', 'callender'),
	('George Harmon', 'England', 'george harmon'),
	('George Harmon', 'England', 'harmon'),
	('Matteo Regillo', 'Switzerland', 'matteo regillo'),
	('Matteo Regillo', 'Switzerland', 'regillo'),
	('Gion Fadri Chande', 'Switzerland', 'gion fadri chande'),
	('Gion Fadri Chande', 'Switzerland', 'chande')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';