INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Isak Dybvik Määttä', 'Norway', 'player'),
	('Ryohei Yamazaki', 'Japan', 'player'),
	('Kastriot Imeri', 'Switzerland', 'player'),
	('Harvey White', 'England', 'player'),
	('Mattéo Ahlinvi', 'France', 'player'),
	('Josef Bursik', 'England', 'player'),
	('Pedro Azogue', 'Bolivia', 'player'),
	('Matt Green', 'England', 'player'),
	('Luis Carbonell', 'Spain', 'player'),
	('Assan Ceesay', 'Gambia', 'player'),
	('Diego Fuoli', 'Spain', 'player'),
	('Marcelo Molinas', 'Paraguay', 'player'),
	('Kevin Díaz', 'Venezuela', 'player'),
	('Brandon Wilson', 'Australia', 'player'),
	('Miguel Reisinho', 'Portugal', 'player'),
	('Jakub Bednarczyk', 'Poland', 'player'),
	('Răzvan Onea', 'Romania', 'player'),
	('Tom Dallison', 'England', 'player'),
	('Jordan Murray', 'Australia', 'player'),
	('Romain Sans', 'France', 'player'),
	('Muhannad Fallatah', 'Saudi Arabia', 'player'),
	('Michee Ngalina', 'DR Congo', 'player'),
	('Uriarte', 'Spain', 'player'),
	('Ally Gilchrist', 'Scotland', 'player'),
	('Şahverdi Çetin', 'Germany', 'player'),
	('Rayhaan Tulloch', 'England', 'player'),
	('Lee Hee Kyun', 'Korea Republic', 'player'),
	('Pedro Galindo', 'Bolivia', 'player'),
	('Robbie Burton', 'Wales', 'player'),
	('Ștefan Baiaram', 'Romania', 'player'),
	('Cameron John', 'England', 'player'),
	('Genaro', 'Spain', 'player'),
	('Yesid Diaz', 'Colombia', 'player'),
	('Marco Olivieri', 'Italy', 'player'),
	('Yuan Mincheng', 'China PR', 'player'),
	('Scott Tiffoney', 'Scotland', 'player'),
	('Mohammad Awad', 'Israel', 'player'),
	('Faris Pemi Moumbagna', 'Cameroon', 'player'),
	('Gustav Isaksen', 'Denmark', 'player'),
	('Marco Frediani', 'Italy', 'player'),
	('David Cardoso', 'Macau', 'player'),
	('Ronal de Jesús', 'Ecuador', 'player'),
	('Juan Pablo Plada', 'Uruguay', 'player'),
	('Jacopo Furlan', 'Italy', 'player'),
	('Osman Kakay', 'Sierra Leone', 'player'),
	('Gianni Mollo', 'Italy', 'player'),
	('Fabiano Parisi', 'Italy', 'player'),
	('Lewis Thomas', 'Wales', 'player'),
	('Hamad Al Juhayyim', 'Saudi Arabia', 'player'),
	('Brian Leizza', 'Argentina', 'player'),
	('Ian Bermingham', 'Republic of Ireland', 'player'),
	('Leander Siemann', 'Germany', 'player'),
	('Nikolai Baden Frederiksen', 'Denmark', 'player'),
	('Osama Malik', 'Australia', 'player'),
	('Andrea Maccoppi', 'Italy', 'player'),
	('Conor McCarthy', 'Republic of Ireland', 'player'),
	('Nicolas Bruneel', 'France', 'player'),
	('Marco Ehmann', 'Romania', 'player'),
	('Capita', 'Angola', 'player'),
	('Alejandro González', 'Venezuela', 'player'),
	('Zhong Jinbao', 'China PR', 'player'),
	('Sean Nealis', 'United States', 'player'),
	('Chris Odoi-Atsem', 'United States', 'player'),
	('Jobi McAnuff', 'Jamaica', 'player'),
	('Görkem Can', 'Turkey', 'player'),
	('Lee Desmond', 'Republic of Ireland', 'player'),
	('Norberto Palmieri', 'Argentina', 'player'),
	('Juan Brunet', 'Argentina', 'player'),
	('Tommy Doyle', 'England', 'player'),
	('José Neris', 'Uruguay', 'player'),
	('Anton Tanghe', 'Belgium', 'player'),
	('José Fontán', 'Spain', 'player'),
	('Davy van den Berg', 'Netherlands', 'player'),
	('Andrei Șerban', 'Romania', 'player'),
	('Nsima Peter', 'Nigeria', 'player'),
	('Marcos Celorrio', 'Spain', 'player'),
	('Uziel García', 'Mexico', 'player'),
	('Jordan Lawrence-Gabriel', 'England', 'player'),
	('Ionuț Stoica', 'Romania', 'player'),
	('Emmanuel Dieseruvwe', 'England', 'player'),
	('Hugo Rojas', 'Bolivia', 'player'),
	('Telmo Arcanjo', 'Portugal', 'player'),
	('Ben Barclay', 'England', 'player'),
	('Juan Pablo Meza', 'Mexico', 'player'),
	('Ashley Nadesan', 'England', 'player'),
	('Marco Dulca', 'Romania', 'player'),
	('Hasan Ayaroğlu', 'Turkey', 'player'),
	('Hwang ByeongGeun', 'Korea Republic', 'player'),
	('Christian Kouakou', 'Sweden', 'player'),
	('Michael Seaton', 'Jamaica', 'player'),
	('Segundo Portocarrero', 'Ecuador', 'player'),
	('Simon Madden', 'Republic of Ireland', 'player'),
	('Javier Altamirano', 'Chile', 'player'),
	('Marvin Tshibuabua', 'France', 'player'),
	('Nicolas Andermatt', 'Switzerland', 'player'),
	('Isak Magnusson', 'Sweden', 'player'),
	('Sondre Liseth', 'Norway', 'player'),
	('Tony Gallacher', 'Scotland', 'player'),
	('Davor Matijaš', 'Croatia', 'player'),
	('José Urbina', 'Spain', 'player'),
	('Shawn McCoulsky', 'England', 'player'),
	('Abdourahmane Ndiaye', 'Senegal', 'player'),
	('Paul Marie', 'France', 'player'),
	('Liu Yi', 'China PR', 'player'),
	('Njabulo Blom', 'South Africa', 'player'),
	('Kevin De La Hoz', 'Venezuela', 'player'),
	('David Seger', 'Sweden', 'player'),
	('Lee Woo Hyeok', 'Korea Republic', 'player'),
	('Juan Eduardo Fierro', 'Bolivia', 'player'),
	('Agustín Cardozo', 'Argentina', 'player'),
	('Ryan Clampin', 'England', 'player'),
	('Zhang Lingfeng', 'China PR', 'player'),
	('Jamie Turley', 'England', 'player'),
	('Oskar Buur Rasmussen', 'Denmark', 'player'),
	('John Tolkin', 'United States', 'player'),
	('Mazen Abu Shararah', 'Saudi Arabia', 'player'),
	('Matias David Maidana', 'Argentina', 'player'),
	('Adrian Oeynhausen', 'Germany', 'player'),
	('Alexander Burgstaller', 'Austria', 'player'),
	('Bryan Chahuaylla', 'Peru', 'player'),
	('Doğucan Haspolat', 'Netherlands', 'player'),
	('Darlin Leiton', 'Ecuador', 'player'),
	('Gus Ushler', 'Australia', 'player'),
	('Ryan Taylor', 'England', 'player'),
	('Jaouen Hadjam', 'France', 'player'),
	('Rubén Escobar', 'Paraguay', 'player'),
	('Matías Arezo', 'Uruguay', 'player'),
	('Ruvira', 'Spain', 'player'),
	('Lukas Schöfl', 'Austria', 'player'),
	('Nando Pijnaker', 'New Zealand', 'player'),
	('Mike Cevallos', 'Ecuador', 'player'),
	('Sander van Looy', 'Netherlands', 'player'),
	('Leonardo Urapuca', 'Bolivia', 'player'),
	('Leon Davies', 'England', 'player'),
	('Couhaib Driouech', 'Netherlands', 'player'),
	('Marcelo Lopes', 'Portugal', 'player'),
	('Max Sheaf', 'England', 'player'),
	('David Loera', 'United States', 'player'),
	('Liam McAlinden', 'Republic of Ireland', 'player'),
	('Josh Falkingham', 'England', 'player'),
	('Jannick', 'Equatorial Guinea', 'player'),
	('Edgar Pérez', 'Venezuela', 'player'),
	('Dayne St. Clair', 'Canada', 'player'),
	('Germán Chanchamire', 'Venezuela', 'player'),
	('Braian Maidana', 'Argentina', 'player'),
	('Aleksander Komor', 'Poland', 'player'),
	('Daniel Margush', 'Australia', 'player'),
	('Realdo Fili', 'Albania', 'player'),
	('Ahmed Ba Masoud', 'Saudi Arabia', 'player'),
	('Cesar Ibañez', 'Argentina', 'player'),
	('Benjamin Hjertstrand', 'Sweden', 'player'),
	('Sergej Schmik', 'Germany', 'player'),
	('Meseguer', 'Spain', 'player'),
	('Ba Dun', 'China PR', 'player'),
	('Felix Mambimbi', 'Switzerland', 'player'),
	('Masaaki Goto', 'Japan', 'player'),
	('Jonathan Acasiete', 'Peru', 'player'),
	('Mohammed Al Dhaw', 'Sudan', 'player'),
	('Matt Butcher', 'England', 'player'),
	('Idris Kanu', 'England', 'player'),
	('Alexandru Greab', 'Romania', 'player'),
	('Ivan Mesík', 'Slovakia', 'player'),
	('Levi Sutton', 'England', 'player'),
	('Viedma', 'Spain', 'player'),
	('Kaique Rocha', 'Brazil', 'player'),
	('Ali Al Asmari', 'Saudi Arabia', 'player'),
	('Zhang Lu', 'China PR', 'player'),
	('Danny Grant', 'Republic of Ireland', 'player'),
	('Abdulrahman Al Dawsari', 'Saudi Arabia', 'player'),
	('Joel Dixon', 'England', 'player'),
	('Andrés Borge', 'Spain', 'player'),
	('Stefan Radulovic', 'Austria', 'player'),
	('Ben Fox', 'England', 'player'),
	('Aldo Pérez', 'Paraguay', 'player'),
	('Jairo Mungaray', 'Mexico', 'player'),
	('Anıl Koç', 'Turkey', 'player'),
	('Kevin Bemanga', 'France', 'player'),
	('Jamille Matt', 'Jamaica', 'player'),
	('Javier Maldonado', 'Venezuela', 'player'),
	('Samuel Alabi', 'Ghana', 'player'),
	('Xavier Amaechi', 'England', 'player'),
	('David Tutonda', 'DR Congo', 'player'),
	('José Carlos Robles', 'Mexico', 'player'),
	('Manuel Semedo', 'Portugal', 'player'),
	('Efe Binici', 'Turkey', 'player'),
	('Matteo Cortesi', 'Italy', 'player'),
	('Lisandru Tramoni', 'France', 'player'),
	('Cheye Alexander', 'England', 'player'),
	('Joe Ironside', 'England', 'player'),
	('Éder Hermoza', 'Peru', 'player'),
	('Oliver Sail', 'New Zealand', 'player'),
	('Brahima Doukansy', 'France', 'player'),
	('Ronan Coughlan', 'Republic of Ireland', 'player'),
	('Javier Izquierdo', 'Spain', 'player'),
	('Richard Sila', 'France', 'player'),
	('Eliano Reijnders', 'Netherlands', 'player'),
	('Bevis Mugabi', 'Uganda', 'player'),
	('Sebastián Meza', 'Argentina', 'player'),
	('Kachi', 'Nigeria', 'player'),
	('Tomislav Krizmanić', 'Croatia', 'player'),
	('Germán Rivero', 'Argentina', 'player'),
	('Eric Meza', 'Argentina', 'player'),
	('Callum Slattery', 'England', 'player'),
	('Diego Pineda', 'Mexico', 'player'),
	('Roberto de la Rosa', 'Mexico', 'player'),
	('Juan José Cáceres', 'Argentina', 'player'),
	('Alexis Gamboa', 'Costa Rica', 'player'),
	('Walter Ortíz', 'Argentina', 'player'),
	('Daan Huisman', 'Netherlands', 'player'),
	('Bernard Kyere', 'Ghana', 'player'),
	('Katsuya Iwatake', 'Japan', 'player'),
	('Bartłomiej Żynel', 'Poland', 'player'),
	('Jasin Khayat', 'Morocco', 'player'),
	('Adam Ryczkowski', 'Poland', 'player'),
	('Ali Ibrahimaj', 'Germany', 'player'),
	('Callum Hendry', 'Scotland', 'player'),
	('Nicolas Gétaz', 'Switzerland', 'player'),
	('Boubacar Traorè', 'Senegal', 'player'),
	('Tomás Reymão', 'Portugal', 'player'),
	('Juan Pablo Krilanovich', 'Argentina', 'player'),
	('Daichi Akiyama', 'Japan', 'player'),
	('Josué Reyes', 'Mexico', 'player'),
	('Jack Powell', 'England', 'player'),
	('David Kasumu', 'Nigeria', 'player'),
	('Iván Moreno', 'Mexico', 'player'),
	('Christoph Klarer', 'Austria', 'player'),
	('Mor Talla Nguer', 'Senegal', 'player'),
	('Teddy Boulhendi', 'France', 'player'),
	('Edin Julardžija', 'Croatia', 'player'),
	('Cole Stockton', 'England', 'player'),
	('Ernesto Álvarez', 'Paraguay', 'player'),
	('Alex Timossi Andersson', 'Sweden', 'player'),
	('Marco Bleve', 'Italy', 'player'),
	('Leon Klassen', 'Russia', 'player'),
	('Akram Tsague', 'France', 'player'),
	('André Ribeiro', 'Portugal', 'player'),
	('Richard Figueroa', 'Venezuela', 'player'),
	('Simeon Akinola', 'Nigeria', 'player'),
	('Daniel Rojano', 'Colombia', 'player'),
	('Didier Desprez', 'France', 'player'),
	('Adnan Ugur', 'Belgium', 'player'),
	('Benjamin Leneis', 'Germany', 'player'),
	('Martin Spelmann', 'Denmark', 'player'),
	('Juan Manuel Cuesta', 'Colombia', 'player'),
	('Mohammed Majrashi', 'Saudi Arabia', 'player'),
	('Mete Kaan Demir', 'Turkey', 'player'),
	('Haroune Camara', 'Saudi Arabia', 'player'),
	('Jorge Palacios', 'Ecuador', 'player'),
	('Lorenzo Soares', 'Cape Verde', 'player'),
	('Dylan Esmel', 'Ivory Coast', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Isak Dybvik Määttä', 'Norway', 'maatta'),
	('Isak Dybvik Määttä', 'Norway', 'isak dybvik maatta'),
	('Ryohei Yamazaki', 'Japan', 'ryohei yamazaki'),
	('Ryohei Yamazaki', 'Japan', 'yamazaki'),
	('Kastriot Imeri', 'Switzerland', 'imeri'),
	('Kastriot Imeri', 'Switzerland', 'kastriot imeri'),
	('Harvey White', 'England', 'harvey white'),
	('Harvey White', 'England', 'white'),
	('Mattéo Ahlinvi', 'France', 'matteo ahlinvi'),
	('Mattéo Ahlinvi', 'France', 'ahlinvi'),
	('Josef Bursik', 'England', 'josef bursik'),
	('Josef Bursik', 'England', 'bursik'),
	('Pedro Azogue', 'Bolivia', 'azogue'),
	('Pedro Azogue', 'Bolivia', 'pedro azogue'),
	('Matt Green', 'England', 'matt green'),
	('Matt Green', 'England', 'green'),
	('Luis Carbonell', 'Spain', 'carbonell'),
	('Luis Carbonell', 'Spain', 'luis carbonell'),
	('Assan Ceesay', 'Gambia', 'ceesay'),
	('Assan Ceesay', 'Gambia', 'assan ceesay'),
	('Diego Fuoli', 'Spain', 'fuoli'),
	('Diego Fuoli', 'Spain', 'diego fuoli'),
	('Marcelo Molinas', 'Paraguay', 'molinas'),
	('Marcelo Molinas', 'Paraguay', 'marcelo molinas'),
	('Kevin Díaz', 'Venezuela', 'kevin diaz'),
	('Kevin Díaz', 'Venezuela', 'diaz'),
	('Brandon Wilson', 'Australia', 'brandon wilson'),
	('Brandon Wilson', 'Australia', 'wilson'),
	('Miguel Reisinho', 'Portugal', 'miguel reisinho'),
	('Miguel Reisinho', 'Portugal', 'reisinho'),
	('Jakub Bednarczyk', 'Poland', 'jakub bednarczyk'),
	('Jakub Bednarczyk', 'Poland', 'bednarczyk'),
	('Răzvan Onea', 'Romania', 'razvan onea'),
	('Răzvan Onea', 'Romania', 'onea'),
	('Tom Dallison', 'England', 'tom dallison'),
	('Tom Dallison', 'England', 'dallison'),
	('Jordan Murray', 'Australia', 'jordan murray'),
	('Jordan Murray', 'Australia', 'murray'),
	('Romain Sans', 'France', 'sans'),
	('Romain Sans', 'France', 'romain sans'),
	('Muhannad Fallatah', 'Saudi Arabia', 'fallatah'),
	('Muhannad Fallatah', 'Saudi Arabia', 'muhannad fallatah'),
	('Michee Ngalina', 'DR Congo', 'ngalina'),
	('Michee Ngalina', 'DR Congo', 'michee ngalina'),
	('Uriarte', 'Spain', 'uriarte'),
	('Ally Gilchrist', 'Scotland', 'gilchrist'),
	('Ally Gilchrist', 'Scotland', 'ally gilchrist'),
	('Şahverdi Çetin', 'Germany', 'cetin'),
	('Şahverdi Çetin', 'Germany', 'sahverdi cetin'),
	('Rayhaan Tulloch', 'England', 'rayhaan tulloch'),
	('Rayhaan Tulloch', 'England', 'tulloch'),
	('Lee Hee Kyun', 'Korea Republic', 'lee hee kyun'),
	('Lee Hee Kyun', 'Korea Republic', 'kyun'),
	('Pedro Galindo', 'Bolivia', 'pedro galindo'),
	('Pedro Galindo', 'Bolivia', 'galindo'),
	('Robbie Burton', 'Wales', 'robbie burton'),
	('Robbie Burton', 'Wales', 'burton'),
	('Ștefan Baiaram', 'Romania', 'baiaram'),
	('Ștefan Baiaram', 'Romania', 'stefan baiaram'),
	('Cameron John', 'England', 'john'),
	('Cameron John', 'England', 'cameron john'),
	('Genaro', 'Spain', 'genaro'),
	('Yesid Diaz', 'Colombia', 'yesid diaz'),
	('Yesid Diaz', 'Colombia', 'diaz'),
	('Marco Olivieri', 'Italy', 'olivieri'),
	('Marco Olivieri', 'Italy', 'marco olivieri'),
	('Yuan Mincheng', 'China PR', 'yuan mincheng'),
	('Yuan Mincheng', 'China PR', 'mincheng'),
	('Scott Tiffoney', 'Scotland', 'scott tiffoney'),
	('Scott Tiffoney', 'Scotland', 'tiffoney'),
	('Mohammad Awad', 'Israel', 'mohammad awad'),
	('Mohammad Awad', 'Israel', 'awad'),
	('Faris Pemi Moumbagna', 'Cameroon', 'faris pemi moumbagna'),
	('Faris Pemi Moumbagna', 'Cameroon', 'moumbagna'),
	('Gustav Isaksen', 'Denmark', 'gustav isaksen'),
	('Gustav Isaksen', 'Denmark', 'isaksen'),
	('Marco Frediani', 'Italy', 'frediani'),
	('Marco Frediani', 'Italy', 'marco frediani'),
	('David Cardoso', 'Macau', 'david cardoso'),
	('David Cardoso', 'Macau', 'cardoso'),
	('Ronal de Jesús', 'Ecuador', 'ronal de jesus'),
	('Ronal de Jesús', 'Ecuador', 'jesus'),
	('Juan Pablo Plada', 'Uruguay', 'plada'),
	('Juan Pablo Plada', 'Uruguay', 'juan pablo plada'),
	('Jacopo Furlan', 'Italy', 'furlan'),
	('Jacopo Furlan', 'Italy', 'jacopo furlan'),
	('Osman Kakay', 'Sierra Leone', 'kakay'),
	('Osman Kakay', 'Sierra Leone', 'osman kakay'),
	('Gianni Mollo', 'Italy', 'gianni mollo'),
	('Gianni Mollo', 'Italy', 'mollo'),
	('Fabiano Parisi', 'Italy', 'fabiano parisi'),
	('Fabiano Parisi', 'Italy', 'parisi'),
	('Lewis Thomas', 'Wales', 'thomas'),
	('Lewis Thomas', 'Wales', 'lewis thomas'),
	('Hamad Al Juhayyim', 'Saudi Arabia', 'hamad al juhayyim'),
	('Hamad Al Juhayyim', 'Saudi Arabia', 'juhayyim'),
	('Brian Leizza', 'Argentina', 'leizza'),
	('Brian Leizza', 'Argentina', 'brian leizza'),
	('Ian Bermingham', 'Republic of Ireland', 'ian bermingham'),
	('Ian Bermingham', 'Republic of Ireland', 'bermingham'),
	('Leander Siemann', 'Germany', 'siemann'),
	('Leander Siemann', 'Germany', 'leander siemann'),
	('Nikolai Baden Frederiksen', 'Denmark', 'nikolai baden frederiksen'),
	('Nikolai Baden Frederiksen', 'Denmark', 'frederiksen'),
	('Osama Malik', 'Australia', 'osama malik'),
	('Osama Malik', 'Australia', 'malik'),
	('Andrea Maccoppi', 'Italy', 'maccoppi'),
	('Andrea Maccoppi', 'Italy', 'andrea maccoppi'),
	('Conor McCarthy', 'Republic of Ireland', 'conor mccarthy'),
	('Conor McCarthy', 'Republic of Ireland', 'mccarthy'),
	('Nicolas Bruneel', 'France', 'bruneel'),
	('Nicolas Bruneel', 'France', 'nicolas bruneel'),
	('Marco Ehmann', 'Romania', 'marco ehmann'),
	('Marco Ehmann', 'Romania', 'ehmann'),
	('Capita', 'Angola', 'capita'),
	('Alejandro González', 'Venezuela', 'alejandro gonzalez'),
	('Alejandro González', 'Venezuela', 'gonzalez'),
	('Zhong Jinbao', 'China PR', 'zhong jinbao'),
	('Zhong Jinbao', 'China PR', 'jinbao'),
	('Sean Nealis', 'United States', 'nealis'),
	('Sean Nealis', 'United States', 'sean nealis'),
	('Chris Odoi-Atsem', 'United States', 'chris odoiatsem'),
	('Chris Odoi-Atsem', 'United States', 'odoiatsem'),
	('Jobi McAnuff', 'Jamaica', 'jobi mcanuff'),
	('Jobi McAnuff', 'Jamaica', 'mcanuff'),
	('Görkem Can', 'Turkey', 'gorkem can'),
	('Görkem Can', 'Turkey', 'can'),
	('Lee Desmond', 'Republic of Ireland', 'desmond'),
	('Lee Desmond', 'Republic of Ireland', 'lee desmond'),
	('Norberto Palmieri', 'Argentina', 'palmieri'),
	('Norberto Palmieri', 'Argentina', 'norberto palmieri'),
	('Juan Brunet', 'Argentina', 'brunet'),
	('Juan Brunet', 'Argentina', 'juan brunet'),
	('Tommy Doyle', 'England', 'tommy doyle'),
	('Tommy Doyle', 'England', 'doyle'),
	('José Neris', 'Uruguay', 'jose neris'),
	('José Neris', 'Uruguay', 'neris'),
	('Anton Tanghe', 'Belgium', 'tanghe'),
	('Anton Tanghe', 'Belgium', 'anton tanghe'),
	('José Fontán', 'Spain', 'jose fontan'),
	('José Fontán', 'Spain', 'fontan'),
	('Davy van den Berg', 'Netherlands', 'berg'),
	('Davy van den Berg', 'Netherlands', 'davy van den berg'),
	('Andrei Șerban', 'Romania', 'andrei serban'),
	('Andrei Șerban', 'Romania', 'serban'),
	('Nsima Peter', 'Nigeria', 'peter'),
	('Nsima Peter', 'Nigeria', 'nsima peter'),
	('Marcos Celorrio', 'Spain', 'marcos celorrio'),
	('Marcos Celorrio', 'Spain', 'celorrio'),
	('Uziel García', 'Mexico', 'uziel garcia'),
	('Uziel García', 'Mexico', 'garcia'),
	('Jordan Lawrence-Gabriel', 'England', 'jordan lawrencegabriel'),
	('Jordan Lawrence-Gabriel', 'England', 'lawrencegabriel'),
	('Ionuț Stoica', 'Romania', 'stoica'),
	('Ionuț Stoica', 'Romania', 'ionut stoica'),
	('Emmanuel Dieseruvwe', 'England', 'dieseruvwe'),
	('Emmanuel Dieseruvwe', 'England', 'emmanuel dieseruvwe'),
	('Hugo Rojas', 'Bolivia', 'hugo rojas'),
	('Hugo Rojas', 'Bolivia', 'rojas'),
	('Telmo Arcanjo', 'Portugal', 'arcanjo'),
	('Telmo Arcanjo', 'Portugal', 'telmo arcanjo'),
	('Ben Barclay', 'England', 'ben barclay'),
	('Ben Barclay', 'England', 'barclay'),
	('Juan Pablo Meza', 'Mexico', 'meza'),
	('Juan Pablo Meza', 'Mexico', 'juan pablo meza'),
	('Ashley Nadesan', 'England', 'nadesan'),
	('Ashley Nadesan', 'England', 'ashley nadesan'),
	('Marco Dulca', 'Romania', 'marco dulca'),
	('Marco Dulca', 'Romania', 'dulca'),
	('Hasan Ayaroğlu', 'Turkey', 'hasan ayaroglu'),
	('Hasan Ayaroğlu', 'Turkey', 'ayaroglu'),
	('Hwang ByeongGeun', 'Korea Republic', 'byeonggeun'),
	('Hwang ByeongGeun', 'Korea Republic', 'hwang byeonggeun'),
	('Christian Kouakou', 'Sweden', 'kouakou'),
	('Christian Kouakou', 'Sweden', 'christian kouakou'),
	('Michael Seaton', 'Jamaica', 'michael seaton'),
	('Michael Seaton', 'Jamaica', 'seaton'),
	('Segundo Portocarrero', 'Ecuador', 'segundo portocarrero'),
	('Segundo Portocarrero', 'Ecuador', 'portocarrero'),
	('Simon Madden', 'Republic of Ireland', 'madden'),
	('Simon Madden', 'Republic of Ireland', 'simon madden'),
	('Javier Altamirano', 'Chile', 'altamirano'),
	('Javier Altamirano', 'Chile', 'javier altamirano'),
	('Marvin Tshibuabua', 'France', 'tshibuabua'),
	('Marvin Tshibuabua', 'France', 'marvin tshibuabua'),
	('Nicolas Andermatt', 'Switzerland', 'nicolas andermatt'),
	('Nicolas Andermatt', 'Switzerland', 'andermatt'),
	('Isak Magnusson', 'Sweden', 'isak magnusson'),
	('Isak Magnusson', 'Sweden', 'magnusson'),
	('Sondre Liseth', 'Norway', 'liseth'),
	('Sondre Liseth', 'Norway', 'sondre liseth'),
	('Tony Gallacher', 'Scotland', 'gallacher'),
	('Tony Gallacher', 'Scotland', 'tony gallacher'),
	('Davor Matijaš', 'Croatia', 'matijas'),
	('Davor Matijaš', 'Croatia', 'davor matijas'),
	('José Urbina', 'Spain', 'jose urbina'),
	('José Urbina', 'Spain', 'urbina'),
	('Shawn McCoulsky', 'England', 'shawn mccoulsky'),
	('Shawn McCoulsky', 'England', 'mccoulsky'),
	('Abdourahmane Ndiaye', 'Senegal', 'abdourahmane ndiaye'),
	('Abdourahmane Ndiaye', 'Senegal', 'ndiaye'),
	('Paul Marie', 'France', 'marie'),
	('Paul Marie', 'France', 'paul marie'),
	('Liu Yi', 'China PR', 'liu yi'),
	('Liu Yi', 'China PR', 'yi'),
	('Njabulo Blom', 'South Africa', 'blom'),
	('Njabulo Blom', 'South Africa', 'njabulo blom'),
	('Kevin De La Hoz', 'Venezuela', 'hoz'),
	('Kevin De La Hoz', 'Venezuela', 'kevin de la hoz'),
	('David Seger', 'Sweden', 'seger'),
	('David Seger', 'Sweden', 'david seger'),
	('Lee Woo Hyeok', 'Korea Republic', 'hyeok'),
	('Lee Woo Hyeok', 'Korea Republic', 'lee woo hyeok'),
	('Juan Eduardo Fierro', 'Bolivia', 'fierro'),
	('Juan Eduardo Fierro', 'Bolivia', 'juan eduardo fierro'),
	('Agustín Cardozo', 'Argentina', 'agustin cardozo'),
	('Agustín Cardozo', 'Argentina', 'cardozo'),
	('Ryan Clampin', 'England', 'clampin'),
	('Ryan Clampin', 'England', 'ryan clampin'),
	('Zhang Lingfeng', 'China PR', 'zhang lingfeng'),
	('Zhang Lingfeng', 'China PR', 'lingfeng'),
	('Jamie Turley', 'England', 'turley'),
	('Jamie Turley', 'England', 'jamie turley'),
	('Oskar Buur Rasmussen', 'Denmark', 'rasmussen'),
	('Oskar Buur Rasmussen', 'Denmark', 'oskar buur rasmussen'),
	('John Tolkin', 'United States', 'tolkin'),
	('John Tolkin', 'United States', 'john tolkin'),
	('Mazen Abu Shararah', 'Saudi Arabia', 'mazen abu shararah'),
	('Mazen Abu Shararah', 'Saudi Arabia', 'shararah'),
	('Matias David Maidana', 'Argentina', 'maidana'),
	('Matias David Maidana', 'Argentina', 'matias david maidana'),
	('Adrian Oeynhausen', 'Germany', 'oeynhausen'),
	('Adrian Oeynhausen', 'Germany', 'adrian oeynhausen'),
	('Alexander Burgstaller', 'Austria', 'alexander burgstaller'),
	('Alexander Burgstaller', 'Austria', 'burgstaller'),
	('Bryan Chahuaylla', 'Peru', 'chahuaylla'),
	('Bryan Chahuaylla', 'Peru', 'bryan chahuaylla'),
	('Doğucan Haspolat', 'Netherlands', 'haspolat'),
	('Doğucan Haspolat', 'Netherlands', 'dogucan haspolat'),
	('Darlin Leiton', 'Ecuador', 'leiton'),
	('Darlin Leiton', 'Ecuador', 'darlin leiton'),
	('Gus Ushler', 'Australia', 'ushler'),
	('Gus Ushler', 'Australia', 'gus ushler'),
	('Ryan Taylor', 'England', 'taylor'),
	('Ryan Taylor', 'England', 'ryan taylor'),
	('Jaouen Hadjam', 'France', 'hadjam'),
	('Jaouen Hadjam', 'France', 'jaouen hadjam'),
	('Rubén Escobar', 'Paraguay', 'ruben escobar'),
	('Rubén Escobar', 'Paraguay', 'escobar'),
	('Matías Arezo', 'Uruguay', 'matias arezo'),
	('Matías Arezo', 'Uruguay', 'arezo'),
	('Ruvira', 'Spain', 'ruvira'),
	('Lukas Schöfl', 'Austria', 'lukas schofl'),
	('Lukas Schöfl', 'Austria', 'schofl'),
	('Nando Pijnaker', 'New Zealand', 'pijnaker'),
	('Nando Pijnaker', 'New Zealand', 'nando pijnaker'),
	('Mike Cevallos', 'Ecuador', 'mike cevallos'),
	('Mike Cevallos', 'Ecuador', 'cevallos'),
	('Sander van Looy', 'Netherlands', 'looy'),
	('Sander van Looy', 'Netherlands', 'sander van looy'),
	('Leonardo Urapuca', 'Bolivia', 'urapuca'),
	('Leonardo Urapuca', 'Bolivia', 'leonardo urapuca'),
	('Leon Davies', 'England', 'davies'),
	('Leon Davies', 'England', 'leon davies'),
	('Couhaib Driouech', 'Netherlands', 'driouech'),
	('Couhaib Driouech', 'Netherlands', 'couhaib driouech'),
	('Marcelo Lopes', 'Portugal', 'lopes'),
	('Marcelo Lopes', 'Portugal', 'marcelo lopes'),
	('Max Sheaf', 'England', 'max sheaf'),
	('Max Sheaf', 'England', 'sheaf'),
	('David Loera', 'United States', 'david loera'),
	('David Loera', 'United States', 'loera'),
	('Liam McAlinden', 'Republic of Ireland', 'mcalinden'),
	('Liam McAlinden', 'Republic of Ireland', 'liam mcalinden'),
	('Josh Falkingham', 'England', 'josh falkingham'),
	('Josh Falkingham', 'England', 'falkingham'),
	('Jannick', 'Equatorial Guinea', 'jannick'),
	('Edgar Pérez', 'Venezuela', 'edgar perez'),
	('Edgar Pérez', 'Venezuela', 'perez'),
	('Dayne St. Clair', 'Canada', 'clair'),
	('Dayne St. Clair', 'Canada', 'dayne st clair'),
	('Germán Chanchamire', 'Venezuela', 'german chanchamire'),
	('Germán Chanchamire', 'Venezuela', 'chanchamire'),
	('Braian Maidana', 'Argentina', 'braian maidana'),
	('Braian Maidana', 'Argentina', 'maidana'),
	('Aleksander Komor', 'Poland', 'aleksander komor'),
	('Aleksander Komor', 'Poland', 'komor'),
	('Daniel Margush', 'Australia', 'daniel margush'),
	('Daniel Margush', 'Australia', 'margush'),
	('Realdo Fili', 'Albania', 'realdo fili'),
	('Realdo Fili', 'Albania', 'fili'),
	('Ahmed Ba Masoud', 'Saudi Arabia', 'masoud'),
	('Ahmed Ba Masoud', 'Saudi Arabia', 'ahmed ba masoud'),
	('Cesar Ibañez', 'Argentina', 'ibanez'),
	('Cesar Ibañez', 'Argentina', 'cesar ibanez'),
	('Benjamin Hjertstrand', 'Sweden', 'hjertstrand'),
	('Benjamin Hjertstrand', 'Sweden', 'benjamin hjertstrand'),
	('Sergej Schmik', 'Germany', 'schmik'),
	('Sergej Schmik', 'Germany', 'sergej schmik'),
	('Meseguer', 'Spain', 'meseguer'),
	('Ba Dun', 'China PR', 'dun'),
	('Ba Dun', 'China PR', 'ba dun'),
	('Felix Mambimbi', 'Switzerland', 'felix mambimbi'),
	('Felix Mambimbi', 'Switzerland', 'mambimbi'),
	('Masaaki Goto', 'Japan', 'masaaki goto'),
	('Masaaki Goto', 'Japan', 'goto'),
	('Jonathan Acasiete', 'Peru', 'acasiete'),
	('Jonathan Acasiete', 'Peru', 'jonathan acasiete'),
	('Mohammed Al Dhaw', 'Sudan', 'mohammed al dhaw'),
	('Mohammed Al Dhaw', 'Sudan', 'dhaw'),
	('Matt Butcher', 'England', 'butcher'),
	('Matt Butcher', 'England', 'matt butcher'),
	('Idris Kanu', 'England', 'kanu'),
	('Idris Kanu', 'England', 'idris kanu'),
	('Alexandru Greab', 'Romania', 'alexandru greab'),
	('Alexandru Greab', 'Romania', 'greab'),
	('Ivan Mesík', 'Slovakia', 'ivan mesik'),
	('Ivan Mesík', 'Slovakia', 'mesik'),
	('Levi Sutton', 'England', 'sutton'),
	('Levi Sutton', 'England', 'levi sutton'),
	('Viedma', 'Spain', 'viedma'),
	('Kaique Rocha', 'Brazil', 'kaique rocha'),
	('Kaique Rocha', 'Brazil', 'rocha'),
	('Ali Al Asmari', 'Saudi Arabia', 'ali al asmari'),
	('Ali Al Asmari', 'Saudi Arabia', 'asmari'),
	('Zhang Lu', 'China PR', 'zhang lu'),
	('Zhang Lu', 'China PR', 'lu'),
	('Danny Grant', 'Republic of Ireland', 'danny grant'),
	('Danny Grant', 'Republic of Ireland', 'grant'),
	('Abdulrahman Al Dawsari', 'Saudi Arabia', 'abdulrahman al dawsari'),
	('Abdulrahman Al Dawsari', 'Saudi Arabia', 'dawsari'),
	('Joel Dixon', 'England', 'dixon'),
	('Joel Dixon', 'England', 'joel dixon'),
	('Andrés Borge', 'Spain', 'borge'),
	('Andrés Borge', 'Spain', 'andres borge'),
	('Stefan Radulovic', 'Austria', 'stefan radulovic'),
	('Stefan Radulovic', 'Austria', 'radulovic'),
	('Ben Fox', 'England', 'ben fox'),
	('Ben Fox', 'England', 'fox'),
	('Aldo Pérez', 'Paraguay', 'aldo perez'),
	('Aldo Pérez', 'Paraguay', 'perez'),
	('Jairo Mungaray', 'Mexico', 'jairo mungaray'),
	('Jairo Mungaray', 'Mexico', 'mungaray'),
	('Anıl Koç', 'Turkey', 'koc'),
	('Anıl Koç', 'Turkey', 'anl koc'),
	('Kevin Bemanga', 'France', 'kevin bemanga'),
	('Kevin Bemanga', 'France', 'bemanga'),
	('Jamille Matt', 'Jamaica', 'matt'),
	('Jamille Matt', 'Jamaica', 'jamille matt'),
	('Javier Maldonado', 'Venezuela', 'maldonado'),
	('Javier Maldonado', 'Venezuela', 'javier maldonado'),
	('Samuel Alabi', 'Ghana', 'samuel alabi'),
	('Samuel Alabi', 'Ghana', 'alabi'),
	('Xavier Amaechi', 'England', 'xavier amaechi'),
	('Xavier Amaechi', 'England', 'amaechi'),
	('David Tutonda', 'DR Congo', 'tutonda'),
	('David Tutonda', 'DR Congo', 'david tutonda'),
	('José Carlos Robles', 'Mexico', 'jose carlos robles'),
	('José Carlos Robles', 'Mexico', 'robles'),
	('Manuel Semedo', 'Portugal', 'manuel semedo'),
	('Manuel Semedo', 'Portugal', 'semedo'),
	('Efe Binici', 'Turkey', 'efe binici'),
	('Efe Binici', 'Turkey', 'binici'),
	('Matteo Cortesi', 'Italy', 'matteo cortesi'),
	('Matteo Cortesi', 'Italy', 'cortesi'),
	('Lisandru Tramoni', 'France', 'tramoni'),
	('Lisandru Tramoni', 'France', 'lisandru tramoni'),
	('Cheye Alexander', 'England', 'alexander'),
	('Cheye Alexander', 'England', 'cheye alexander'),
	('Joe Ironside', 'England', 'ironside'),
	('Joe Ironside', 'England', 'joe ironside'),
	('Éder Hermoza', 'Peru', 'hermoza'),
	('Éder Hermoza', 'Peru', 'eder hermoza'),
	('Oliver Sail', 'New Zealand', 'oliver sail'),
	('Oliver Sail', 'New Zealand', 'sail'),
	('Brahima Doukansy', 'France', 'brahima doukansy'),
	('Brahima Doukansy', 'France', 'doukansy'),
	('Ronan Coughlan', 'Republic of Ireland', 'coughlan'),
	('Ronan Coughlan', 'Republic of Ireland', 'ronan coughlan'),
	('Javier Izquierdo', 'Spain', 'javier izquierdo'),
	('Javier Izquierdo', 'Spain', 'izquierdo'),
	('Richard Sila', 'France', 'sila'),
	('Richard Sila', 'France', 'richard sila'),
	('Eliano Reijnders', 'Netherlands', 'reijnders'),
	('Eliano Reijnders', 'Netherlands', 'eliano reijnders'),
	('Bevis Mugabi', 'Uganda', 'mugabi'),
	('Bevis Mugabi', 'Uganda', 'bevis mugabi'),
	('Sebastián Meza', 'Argentina', 'meza'),
	('Sebastián Meza', 'Argentina', 'sebastian meza'),
	('Kachi', 'Nigeria', 'kachi'),
	('Tomislav Krizmanić', 'Croatia', 'tomislav krizmanic'),
	('Tomislav Krizmanić', 'Croatia', 'krizmanic'),
	('Germán Rivero', 'Argentina', 'rivero'),
	('Germán Rivero', 'Argentina', 'german rivero'),
	('Eric Meza', 'Argentina', 'meza'),
	('Eric Meza', 'Argentina', 'eric meza'),
	('Callum Slattery', 'England', 'callum slattery'),
	('Callum Slattery', 'England', 'slattery'),
	('Diego Pineda', 'Mexico', 'pineda'),
	('Diego Pineda', 'Mexico', 'diego pineda'),
	('Roberto de la Rosa', 'Mexico', 'rosa'),
	('Roberto de la Rosa', 'Mexico', 'roberto de la rosa'),
	('Juan José Cáceres', 'Argentina', 'caceres'),
	('Juan José Cáceres', 'Argentina', 'juan jose caceres'),
	('Alexis Gamboa', 'Costa Rica', 'alexis gamboa'),
	('Alexis Gamboa', 'Costa Rica', 'gamboa'),
	('Walter Ortíz', 'Argentina', 'ortiz'),
	('Walter Ortíz', 'Argentina', 'walter ortiz'),
	('Daan Huisman', 'Netherlands', 'daan huisman'),
	('Daan Huisman', 'Netherlands', 'huisman'),
	('Bernard Kyere', 'Ghana', 'bernard kyere'),
	('Bernard Kyere', 'Ghana', 'kyere'),
	('Katsuya Iwatake', 'Japan', 'iwatake'),
	('Katsuya Iwatake', 'Japan', 'katsuya iwatake'),
	('Bartłomiej Żynel', 'Poland', 'bartomiej zynel'),
	('Bartłomiej Żynel', 'Poland', 'zynel'),
	('Jasin Khayat', 'Morocco', 'khayat'),
	('Jasin Khayat', 'Morocco', 'jasin khayat'),
	('Adam Ryczkowski', 'Poland', 'ryczkowski'),
	('Adam Ryczkowski', 'Poland', 'adam ryczkowski'),
	('Ali Ibrahimaj', 'Germany', 'ali ibrahimaj'),
	('Ali Ibrahimaj', 'Germany', 'ibrahimaj'),
	('Callum Hendry', 'Scotland', 'hendry'),
	('Callum Hendry', 'Scotland', 'callum hendry'),
	('Nicolas Gétaz', 'Switzerland', 'getaz'),
	('Nicolas Gétaz', 'Switzerland', 'nicolas getaz'),
	('Boubacar Traorè', 'Senegal', 'traore'),
	('Boubacar Traorè', 'Senegal', 'boubacar traore'),
	('Tomás Reymão', 'Portugal', 'tomas reymao'),
	('Tomás Reymão', 'Portugal', 'reymao'),
	('Juan Pablo Krilanovich', 'Argentina', 'juan pablo krilanovich'),
	('Juan Pablo Krilanovich', 'Argentina', 'krilanovich'),
	('Daichi Akiyama', 'Japan', 'daichi akiyama'),
	('Daichi Akiyama', 'Japan', 'akiyama'),
	('Josué Reyes', 'Mexico', 'josue reyes'),
	('Josué Reyes', 'Mexico', 'reyes'),
	('Jack Powell', 'England', 'jack powell'),
	('Jack Powell', 'England', 'powell'),
	('David Kasumu', 'Nigeria', 'david kasumu'),
	('David Kasumu', 'Nigeria', 'kasumu'),
	('Iván Moreno', 'Mexico', 'moreno'),
	('Iván Moreno', 'Mexico', 'ivan moreno'),
	('Christoph Klarer', 'Austria', 'klarer'),
	('Christoph Klarer', 'Austria', 'christoph klarer'),
	('Mor Talla Nguer', 'Senegal', 'mor talla nguer'),
	('Mor Talla Nguer', 'Senegal', 'nguer'),
	('Teddy Boulhendi', 'France', 'boulhendi'),
	('Teddy Boulhendi', 'France', 'teddy boulhendi'),
	('Edin Julardžija', 'Croatia', 'edin julardzija'),
	('Edin Julardžija', 'Croatia', 'julardzija'),
	('Cole Stockton', 'England', 'stockton'),
	('Cole Stockton', 'England', 'cole stockton'),
	('Ernesto Álvarez', 'Paraguay', 'alvarez'),
	('Ernesto Álvarez', 'Paraguay', 'ernesto alvarez'),
	('Alex Timossi Andersson', 'Sweden', 'alex timossi andersson'),
	('Alex Timossi Andersson', 'Sweden', 'andersson'),
	('Marco Bleve', 'Italy', 'marco bleve'),
	('Marco Bleve', 'Italy', 'bleve'),
	('Leon Klassen', 'Russia', 'leon klassen'),
	('Leon Klassen', 'Russia', 'klassen'),
	('Akram Tsague', 'France', 'akram tsague'),
	('Akram Tsague', 'France', 'tsague'),
	('André Ribeiro', 'Portugal', 'ribeiro'),
	('André Ribeiro', 'Portugal', 'andre ribeiro'),
	('Richard Figueroa', 'Venezuela', 'figueroa'),
	('Richard Figueroa', 'Venezuela', 'richard figueroa'),
	('Simeon Akinola', 'Nigeria', 'simeon akinola'),
	('Simeon Akinola', 'Nigeria', 'akinola'),
	('Daniel Rojano', 'Colombia', 'daniel rojano'),
	('Daniel Rojano', 'Colombia', 'rojano'),
	('Didier Desprez', 'France', 'didier desprez'),
	('Didier Desprez', 'France', 'desprez'),
	('Adnan Ugur', 'Belgium', 'ugur'),
	('Adnan Ugur', 'Belgium', 'adnan ugur'),
	('Benjamin Leneis', 'Germany', 'benjamin leneis'),
	('Benjamin Leneis', 'Germany', 'leneis'),
	('Martin Spelmann', 'Denmark', 'spelmann'),
	('Martin Spelmann', 'Denmark', 'martin spelmann'),
	('Juan Manuel Cuesta', 'Colombia', 'juan manuel cuesta'),
	('Juan Manuel Cuesta', 'Colombia', 'cuesta'),
	('Mohammed Majrashi', 'Saudi Arabia', 'mohammed majrashi'),
	('Mohammed Majrashi', 'Saudi Arabia', 'majrashi'),
	('Mete Kaan Demir', 'Turkey', 'demir'),
	('Mete Kaan Demir', 'Turkey', 'mete kaan demir'),
	('Haroune Camara', 'Saudi Arabia', 'camara'),
	('Haroune Camara', 'Saudi Arabia', 'haroune camara'),
	('Jorge Palacios', 'Ecuador', 'jorge palacios'),
	('Jorge Palacios', 'Ecuador', 'palacios'),
	('Lorenzo Soares', 'Cape Verde', 'lorenzo soares'),
	('Lorenzo Soares', 'Cape Verde', 'soares'),
	('Dylan Esmel', 'Ivory Coast', 'esmel'),
	('Dylan Esmel', 'Ivory Coast', 'dylan esmel')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';