INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Pedro Capó', 'Spain', 'player'),
	('Tomáš Vestenický', 'Slovakia', 'player'),
	('Liam Reddy', 'Australia', 'player'),
	('Jacobo', 'Spain', 'player'),
	('Lee Novak', 'England', 'player'),
	('Shamit Shome', 'Canada', 'player'),
	('Anthony Bedoya', 'Ecuador', 'player'),
	('Julien Ponceau', 'France', 'player'),
	('Miguel Baeza', 'Spain', 'player'),
	('Joe Shaughnessy', 'Republic of Ireland', 'player'),
	('Ollie Banks', 'England', 'player'),
	('Javier Sanguinetti', 'Argentina', 'player'),
	('Thomas Isherwood', 'Sweden', 'player'),
	('Robin Tranberg', 'Sweden', 'player'),
	('Raí', 'Brazil', 'player'),
	('Vetle Dragsnes', 'Norway', 'player'),
	('Thomas Haas', 'Germany', 'player'),
	('Abo Eisa', 'Sudan', 'player'),
	('Zé Carlos', 'Portugal', 'player'),
	('Jack Fitzwater', 'England', 'player'),
	('Steven Rivadeneyra', 'Peru', 'player'),
	('Juan Diego Gutiérrez', 'Peru', 'player'),
	('Jürgen Heil', 'Austria', 'player'),
	('Manuel Capasso', 'Argentina', 'player'),
	('Grzegorz Sandomierski', 'Poland', 'player'),
	('Anderson Rey', 'Bolivia', 'player'),
	('Abdullah Al Fahad', 'Saudi Arabia', 'player'),
	('Rayan Al Mousa', 'Saudi Arabia', 'player'),
	('Daniel Harvie', 'Scotland', 'player'),
	('Josh Wright', 'England', 'player'),
	('Ronny König', 'Germany', 'player'),
	('Michael Marrone', 'Australia', 'player'),
	('Theodosis Machairas', 'Greece', 'player'),
	('Tatsuya Yamashita', 'Japan', 'player'),
	('Huang Zichang', 'China PR', 'player'),
	('Robert Müller', 'Germany', 'player'),
	('Renan Oliveira', 'Brazil', 'player'),
	('Alan', 'Brazil', 'player'),
	('José Torres', 'Venezuela', 'player'),
	('Samuel Portugal', 'Brazil', 'player'),
	('Cebrail Karayel', 'Turkey', 'player'),
	('Ammar Al Najjar', 'Saudi Arabia', 'player'),
	('Miguel Rubio', 'Spain', 'player'),
	('Christian Maghoma', 'DR Congo', 'player'),
	('Gorostidi', 'Spain', 'player'),
	('Carlos Rosel', 'Mexico', 'player'),
	('Kim Joon Hyeong', 'Korea Republic', 'player'),
	('Agustín Aleo', 'Argentina', 'player'),
	('Adnan Aganović', 'Croatia', 'player'),
	('Joseph Mensah', 'Ghana', 'player'),
	('Epifanio García', 'Paraguay', 'player'),
	('Anis Slimane', 'Denmark', 'player'),
	('Joaquin Verdugo', 'Chile', 'player'),
	('Michael Gardyne', 'Scotland', 'player'),
	('Sylwester Lusiusz', 'Poland', 'player'),
	('Ki-Jana Hoever', 'Netherlands', 'player'),
	('Marc-Francois Enoumba', 'Cameroon', 'player'),
	('Jonathan Lindseth', 'Norway', 'player'),
	('Robbie McKenzie', 'England', 'player'),
	('Ron Schallenberg', 'Germany', 'player'),
	('André Paulo', 'Portugal', 'player'),
	('Adam Thompson', 'Northern Ireland', 'player'),
	('Joakim Lindner', 'Sweden', 'player'),
	('John Mountney', 'Republic of Ireland', 'player'),
	('Jovanie Tchouatcha', 'Cameroon', 'player'),
	('Oumar Gonzalez', 'Cameroon', 'player'),
	('Diego Conde', 'Spain', 'player'),
	('Gustavo Páez', 'Venezuela', 'player'),
	('Handwalla Bwana', 'Kenya', 'player'),
	('Mikael Mandron', 'France', 'player'),
	('Roman Tugarev', 'Russia', 'player'),
	('Marcinho', 'Brazil', 'player'),
	('Vincent Gembalies', 'Germany', 'player'),
	('Anton Kralj', 'Sweden', 'player'),
	('Dillon Powers', 'United States', 'player'),
	('Oliver Hawkins', 'England', 'player'),
	('Cho Young Wook', 'Korea Republic', 'player'),
	('Daniel Butterworth', 'England', 'player'),
	('Andrew Gutman', 'United States', 'player'),
	('Malte Kiilerich', 'Denmark', 'player'),
	('Leonardo Sernicola', 'Italy', 'player'),
	('Budimir Janošević', 'Serbia', 'player'),
	('Brent Gabriël', 'Belgium', 'player'),
	('Paul Downing', 'England', 'player'),
	('Din Sula', 'Albania', 'player'),
	('Jordan O''Doherty', 'Australia', 'player'),
	('Willian Candia', 'Paraguay', 'player'),
	('Omar Rekik', 'Netherlands', 'player'),
	('Alex Rodman', 'England', 'player'),
	('Patrick Banggaard', 'Denmark', 'player'),
	('Yuta Goke', 'Japan', 'player'),
	('Li Hang', 'China PR', 'player'),
	('Ricardo Escobar', 'Chile', 'player'),
	('David Cornell', 'Wales', 'player'),
	('Jorge Ordóñez', 'Ecuador', 'player'),
	('Ebrima Colley', 'Gambia', 'player'),
	('Giuseppe Caso', 'Italy', 'player'),
	('Loïc Poujol', 'France', 'player'),
	('Mickaël Latour', 'France', 'player'),
	('Andreas Skovgaard', 'Denmark', 'player'),
	('So Fujitani', 'Japan', 'player'),
	('Clément Vidal', 'France', 'player'),
	('Mike Könnecke', 'Germany', 'player'),
	('Pablo Gavilán', 'Paraguay', 'player'),
	('Nicolai Geertsen', 'Denmark', 'player'),
	('René Guder', 'Germany', 'player'),
	('Yusuke Kobayashi', 'Japan', 'player'),
	('Yang Sang Min', 'Korea Republic', 'player'),
	('Edgar Zaracho', 'Paraguay', 'player'),
	('Álex Blesa', 'Spain', 'player'),
	('Steffen Lie Skålevik', 'Norway', 'player'),
	('Hiroto Nakagawa', 'Japan', 'player'),
	('Osman Hadžikić', 'Austria', 'player'),
	('Timothée Pembélé', 'France', 'player'),
	('Djed Spence', 'England', 'player'),
	('Erik Lira', 'Mexico', 'player'),
	('Giannis Papanikolaou', 'Greece', 'player'),
	('Michael Brouwer', 'Netherlands', 'player'),
	('Albert Ejupi', 'Sweden', 'player'),
	('Amir Nouri', 'France', 'player'),
	('Thomas Rotter', 'Austria', 'player'),
	('Charles Vernam', 'England', 'player'),
	('Woyo Coulibaly', 'France', 'player'),
	('Louis Appéré', 'Scotland', 'player'),
	('Janik Jesgarzewski', 'Germany', 'player'),
	('Jesús Fernández', 'Spain', 'player'),
	('Scott Flinders', 'England', 'player'),
	('François-Xavier Fumu Tamuzo', 'France', 'player'),
	('Lee Sang Min', 'Korea Republic', 'player'),
	('Rewan Amin', 'Netherlands', 'player'),
	('Nikolai Rehnen', 'Germany', 'player'),
	('Rollin Menayese', 'Wales', 'player'),
	('Peter Clarke', 'England', 'player'),
	('Kevin Arias', 'Ecuador', 'player'),
	('Tobias Heintz', 'Norway', 'player'),
	('Ibrahima Kébé', 'Mali', 'player'),
	('Jeremy Salas', 'Peru', 'player'),
	('Paolo Reyna', 'Peru', 'player'),
	('Yang Jun A', 'Korea Republic', 'player'),
	('Luther James-Wildin', 'Antigua & Barbuda', 'player'),
	('Miguel Suárez', 'Bolivia', 'player'),
	('Vedad Radonja', 'Bosnia Herzegovina', 'player'),
	('Vladislavs Gutkovskis', 'Latvia', 'player'),
	('Theo Archibald', 'Scotland', 'player'),
	('Seny Dieng', 'Senegal', 'player'),
	('Bilal Benkhedim', 'France', 'player'),
	('Victor Dávalos', 'Paraguay', 'player'),
	('Pau Víctor', 'Spain', 'player'),
	('Dominik Reimann', 'Germany', 'player'),
	('Choi Oh Back', 'Korea Republic', 'player'),
	('Ahmed Al Zain', 'Saudi Arabia', 'player'),
	('Fernando Coniglio', 'Argentina', 'player'),
	('Philippe Paulin Keny', 'Senegal', 'player'),
	('Fatih Kaya', 'Germany', 'player'),
	('Daniel Jarl', 'Sweden', 'player'),
	('Robby McCrorie', 'Scotland', 'player'),
	('Caner Hüseyin Bağ', 'Turkey', 'player'),
	('Wilfredo Soleto', 'Bolivia', 'player'),
	('Deyver Vega', 'Costa Rica', 'player'),
	('Ayman Azhil', 'Germany', 'player'),
	('Deniz Hümmet', 'Turkey', 'player'),
	('Hernán Lópes', 'Argentina', 'player'),
	('Mohammed Bu Sanda', 'United Arab Emirates', 'player'),
	('Hikmet Çiftçi', 'Turkey', 'player'),
	('Anton Wede', 'Sweden', 'player'),
	('Alan Dzabana', 'France', 'player'),
	('Ivan Ostojić', 'Serbia', 'player'),
	('Naoki Ishikawa', 'Japan', 'player'),
	('James Clarke', 'England', 'player'),
	('Jordi Sánchez', 'Spain', 'player'),
	('Nicolas Feldhahn', 'Germany', 'player'),
	('Jordan Maguire-Drew', 'England', 'player'),
	('Takeshi Kanamori', 'Japan', 'player'),
	('Mynor Escoe', 'Costa Rica', 'player'),
	('Mustafa Eskihellaç', 'Turkey', 'player'),
	('Martin Ramsland', 'Norway', 'player'),
	('Tom Pope', 'England', 'player'),
	('Kornelius N. Hansen', 'Norway', 'player'),
	('Song Jin Hyung', 'Korea Republic', 'player'),
	('Ulrich Bapoh', 'Germany', 'player'),
	('Nick Bätzner', 'Germany', 'player'),
	('Thibaud Verlinden', 'Belgium', 'player'),
	('Kilian Fischer', 'Germany', 'player'),
	('Óscar Clemente', 'Spain', 'player'),
	('Raphael Obermair', 'Germany', 'player'),
	('Kalle Joelsson', 'Sweden', 'player'),
	('Oscar Schönfelder', 'Germany', 'player'),
	('Franco Paredes', 'Argentina', 'player'),
	('Marco Wolff', 'Argentina', 'player'),
	('Reece Grego-Cox', 'Republic of Ireland', 'player'),
	('Lewis Banks', 'England', 'player'),
	('Villalón', 'Spain', 'player'),
	('Anton Donkor', 'Germany', 'player'),
	('Jiang Tao', 'China PR', 'player'),
	('Mohammed Helal', 'United Arab Emirates', 'player'),
	('Daniel Nussbaumer', 'Austria', 'player'),
	('Lewis Alessandra', 'England', 'player'),
	('Eren Dinkçi', 'Germany', 'player'),
	('Braian Galván', 'Argentina', 'player'),
	('Ezequiel Rodríguez', 'Argentina', 'player'),
	('Arbenit Xhemajli', 'Kosovo', 'player'),
	('Federico Versaci', 'Argentina', 'player'),
	('Jordan Lyden', 'Australia', 'player'),
	('Alex Iacovitti', 'Scotland', 'player'),
	('Mohamed Amissi', 'Burundi', 'player'),
	('Francisco Parra', 'Paraguay', 'player'),
	('Octavian Ursu', 'Romania', 'player'),
	('Morten Sætra', 'Norway', 'player'),
	('Kentaro Seki', 'Japan', 'player'),
	('Mamadou Doucouré', 'France', 'player'),
	('Jack McMillan', 'Scotland', 'player'),
	('Naif Mousa', 'Saudi Arabia', 'player'),
	('Omar Muzayil', 'Saudi Arabia', 'player'),
	('Corey O''Keeffe', 'Republic of Ireland', 'player'),
	('Callum Morris', 'Northern Ireland', 'player'),
	('Matt Palmer', 'England', 'player'),
	('César Huerta', 'Mexico', 'player'),
	('Calvin Bassey', 'England', 'player'),
	('Emanuel Maciel', 'Argentina', 'player'),
	('Lars Bünning', 'Germany', 'player'),
	('Alexander Aravena', 'Chile', 'player'),
	('Ferhat Görgülü', 'Netherlands', 'player'),
	('Alejandro Zendejas', 'Mexico', 'player'),
	('Gonzalo Casazza', 'Argentina', 'player'),
	('Felipe Galvis', 'Spain', 'player'),
	('Harvey Knibbs', 'England', 'player'),
	('Matías Borgogno', 'Argentina', 'player'),
	('Robin Brüseke', 'Germany', 'player'),
	('Eirik Haugan', 'Norway', 'player'),
	('David Salazar', 'Mexico', 'player'),
	('Daniel Björnquist', 'Sweden', 'player'),
	('Mohammed Al Baqawi', 'Saudi Arabia', 'player'),
	('Scott Robertson', 'Scotland', 'player'),
	('Robbe Quirynen', 'Belgium', 'player'),
	('Jerell Sellars', 'England', 'player'),
	('Awadh Khrees', 'Saudi Arabia', 'player'),
	('Alfredo Pussetto', 'Argentina', 'player'),
	('George Tanner', 'England', 'player'),
	('Matej Rodin', 'Bosnia Herzegovina', 'player'),
	('Paudie O''Connor', 'Republic of Ireland', 'player'),
	('Iván Cazal', 'Paraguay', 'player'),
	('Omar Jaiteh', 'Gambia', 'player'),
	('Xu Xin', 'China PR', 'player'),
	('Carl Tremarco', 'England', 'player'),
	('Masood Bakhit', 'Saudi Arabia', 'player'),
	('Yasin Çakaloğlu', 'Turkey', 'player'),
	('Samson Okikiola Tijani', 'Nigeria', 'player'),
	('Jesús Carrillo', 'Spain', 'player'),
	('William Kurtović', 'Sweden', 'player'),
	('Sam Stubbs', 'England', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Pedro Capó', 'Spain', 'pedro capo'),
	('Pedro Capó', 'Spain', 'capo'),
	('Tomáš Vestenický', 'Slovakia', 'tomas vestenicky'),
	('Tomáš Vestenický', 'Slovakia', 'vestenicky'),
	('Liam Reddy', 'Australia', 'reddy'),
	('Liam Reddy', 'Australia', 'liam reddy'),
	('Jacobo', 'Spain', 'jacobo'),
	('Lee Novak', 'England', 'lee novak'),
	('Lee Novak', 'England', 'novak'),
	('Shamit Shome', 'Canada', 'shamit shome'),
	('Shamit Shome', 'Canada', 'shome'),
	('Anthony Bedoya', 'Ecuador', 'anthony bedoya'),
	('Anthony Bedoya', 'Ecuador', 'bedoya'),
	('Julien Ponceau', 'France', 'ponceau'),
	('Julien Ponceau', 'France', 'julien ponceau'),
	('Miguel Baeza', 'Spain', 'baeza'),
	('Miguel Baeza', 'Spain', 'miguel baeza'),
	('Joe Shaughnessy', 'Republic of Ireland', 'shaughnessy'),
	('Joe Shaughnessy', 'Republic of Ireland', 'joe shaughnessy'),
	('Ollie Banks', 'England', 'banks'),
	('Ollie Banks', 'England', 'ollie banks'),
	('Javier Sanguinetti', 'Argentina', 'javier sanguinetti'),
	('Javier Sanguinetti', 'Argentina', 'sanguinetti'),
	('Thomas Isherwood', 'Sweden', 'isherwood'),
	('Thomas Isherwood', 'Sweden', 'thomas isherwood'),
	('Robin Tranberg', 'Sweden', 'tranberg'),
	('Robin Tranberg', 'Sweden', 'robin tranberg'),
	('Raí', 'Brazil', 'rai'),
	('Vetle Dragsnes', 'Norway', 'dragsnes'),
	('Vetle Dragsnes', 'Norway', 'vetle dragsnes'),
	('Thomas Haas', 'Germany', 'thomas haas'),
	('Thomas Haas', 'Germany', 'haas'),
	('Abo Eisa', 'Sudan', 'eisa'),
	('Abo Eisa', 'Sudan', 'abo eisa'),
	('Zé Carlos', 'Portugal', 'ze carlos'),
	('Zé Carlos', 'Portugal', 'carlos'),
	('Jack Fitzwater', 'England', 'jack fitzwater'),
	('Jack Fitzwater', 'England', 'fitzwater'),
	('Steven Rivadeneyra', 'Peru', 'rivadeneyra'),
	('Steven Rivadeneyra', 'Peru', 'steven rivadeneyra'),
	('Juan Diego Gutiérrez', 'Peru', 'gutierrez'),
	('Juan Diego Gutiérrez', 'Peru', 'juan diego gutierrez'),
	('Jürgen Heil', 'Austria', 'heil'),
	('Jürgen Heil', 'Austria', 'jurgen heil'),
	('Manuel Capasso', 'Argentina', 'manuel capasso'),
	('Manuel Capasso', 'Argentina', 'capasso'),
	('Grzegorz Sandomierski', 'Poland', 'sandomierski'),
	('Grzegorz Sandomierski', 'Poland', 'grzegorz sandomierski'),
	('Anderson Rey', 'Bolivia', 'rey'),
	('Anderson Rey', 'Bolivia', 'anderson rey'),
	('Abdullah Al Fahad', 'Saudi Arabia', 'abdullah al fahad'),
	('Abdullah Al Fahad', 'Saudi Arabia', 'fahad'),
	('Rayan Al Mousa', 'Saudi Arabia', 'mousa'),
	('Rayan Al Mousa', 'Saudi Arabia', 'rayan al mousa'),
	('Daniel Harvie', 'Scotland', 'daniel harvie'),
	('Daniel Harvie', 'Scotland', 'harvie'),
	('Josh Wright', 'England', 'josh wright'),
	('Josh Wright', 'England', 'wright'),
	('Ronny König', 'Germany', 'konig'),
	('Ronny König', 'Germany', 'ronny konig'),
	('Michael Marrone', 'Australia', 'marrone'),
	('Michael Marrone', 'Australia', 'michael marrone'),
	('Theodosis Machairas', 'Greece', 'machairas'),
	('Theodosis Machairas', 'Greece', 'theodosis machairas'),
	('Tatsuya Yamashita', 'Japan', 'yamashita'),
	('Tatsuya Yamashita', 'Japan', 'tatsuya yamashita'),
	('Huang Zichang', 'China PR', 'zichang'),
	('Huang Zichang', 'China PR', 'huang zichang'),
	('Robert Müller', 'Germany', 'muller'),
	('Robert Müller', 'Germany', 'robert muller'),
	('Renan Oliveira', 'Brazil', 'oliveira'),
	('Renan Oliveira', 'Brazil', 'renan oliveira'),
	('Alan', 'Brazil', 'alan'),
	('José Torres', 'Venezuela', 'torres'),
	('José Torres', 'Venezuela', 'jose torres'),
	('Samuel Portugal', 'Brazil', 'samuel portugal'),
	('Samuel Portugal', 'Brazil', 'portugal'),
	('Cebrail Karayel', 'Turkey', 'karayel'),
	('Cebrail Karayel', 'Turkey', 'cebrail karayel'),
	('Ammar Al Najjar', 'Saudi Arabia', 'najjar'),
	('Ammar Al Najjar', 'Saudi Arabia', 'ammar al najjar'),
	('Miguel Rubio', 'Spain', 'rubio'),
	('Miguel Rubio', 'Spain', 'miguel rubio'),
	('Christian Maghoma', 'DR Congo', 'maghoma'),
	('Christian Maghoma', 'DR Congo', 'christian maghoma'),
	('Gorostidi', 'Spain', 'gorostidi'),
	('Carlos Rosel', 'Mexico', 'carlos rosel'),
	('Carlos Rosel', 'Mexico', 'rosel'),
	('Kim Joon Hyeong', 'Korea Republic', 'kim joon hyeong'),
	('Kim Joon Hyeong', 'Korea Republic', 'hyeong'),
	('Agustín Aleo', 'Argentina', 'agustin aleo'),
	('Agustín Aleo', 'Argentina', 'aleo'),
	('Adnan Aganović', 'Croatia', 'adnan aganovic'),
	('Adnan Aganović', 'Croatia', 'aganovic'),
	('Joseph Mensah', 'Ghana', 'mensah'),
	('Joseph Mensah', 'Ghana', 'joseph mensah'),
	('Epifanio García', 'Paraguay', 'garcia'),
	('Epifanio García', 'Paraguay', 'epifanio garcia'),
	('Anis Slimane', 'Denmark', 'anis slimane'),
	('Anis Slimane', 'Denmark', 'slimane'),
	('Joaquin Verdugo', 'Chile', 'joaquin verdugo'),
	('Joaquin Verdugo', 'Chile', 'verdugo'),
	('Michael Gardyne', 'Scotland', 'michael gardyne'),
	('Michael Gardyne', 'Scotland', 'gardyne'),
	('Sylwester Lusiusz', 'Poland', 'lusiusz'),
	('Sylwester Lusiusz', 'Poland', 'sylwester lusiusz'),
	('Ki-Jana Hoever', 'Netherlands', 'kijana hoever'),
	('Ki-Jana Hoever', 'Netherlands', 'hoever'),
	('Marc-Francois Enoumba', 'Cameroon', 'enoumba'),
	('Marc-Francois Enoumba', 'Cameroon', 'marcfrancois enoumba'),
	('Jonathan Lindseth', 'Norway', 'lindseth'),
	('Jonathan Lindseth', 'Norway', 'jonathan lindseth'),
	('Robbie McKenzie', 'England', 'robbie mckenzie'),
	('Robbie McKenzie', 'England', 'mckenzie'),
	('Ron Schallenberg', 'Germany', 'schallenberg'),
	('Ron Schallenberg', 'Germany', 'ron schallenberg'),
	('André Paulo', 'Portugal', 'andre paulo'),
	('André Paulo', 'Portugal', 'paulo'),
	('Adam Thompson', 'Northern Ireland', 'thompson'),
	('Adam Thompson', 'Northern Ireland', 'adam thompson'),
	('Joakim Lindner', 'Sweden', 'lindner'),
	('Joakim Lindner', 'Sweden', 'joakim lindner'),
	('John Mountney', 'Republic of Ireland', 'john mountney'),
	('John Mountney', 'Republic of Ireland', 'mountney'),
	('Jovanie Tchouatcha', 'Cameroon', 'jovanie tchouatcha'),
	('Jovanie Tchouatcha', 'Cameroon', 'tchouatcha'),
	('Oumar Gonzalez', 'Cameroon', 'oumar gonzalez'),
	('Oumar Gonzalez', 'Cameroon', 'gonzalez'),
	('Diego Conde', 'Spain', 'diego conde'),
	('Diego Conde', 'Spain', 'conde'),
	('Gustavo Páez', 'Venezuela', 'paez'),
	('Gustavo Páez', 'Venezuela', 'gustavo paez'),
	('Handwalla Bwana', 'Kenya', 'handwalla bwana'),
	('Handwalla Bwana', 'Kenya', 'bwana'),
	('Mikael Mandron', 'France', 'mikael mandron'),
	('Mikael Mandron', 'France', 'mandron'),
	('Roman Tugarev', 'Russia', 'tugarev'),
	('Roman Tugarev', 'Russia', 'roman tugarev'),
	('Marcinho', 'Brazil', 'marcinho'),
	('Vincent Gembalies', 'Germany', 'vincent gembalies'),
	('Vincent Gembalies', 'Germany', 'gembalies'),
	('Anton Kralj', 'Sweden', 'kralj'),
	('Anton Kralj', 'Sweden', 'anton kralj'),
	('Dillon Powers', 'United States', 'dillon powers'),
	('Dillon Powers', 'United States', 'powers'),
	('Oliver Hawkins', 'England', 'oliver hawkins'),
	('Oliver Hawkins', 'England', 'hawkins'),
	('Cho Young Wook', 'Korea Republic', 'wook'),
	('Cho Young Wook', 'Korea Republic', 'cho young wook'),
	('Daniel Butterworth', 'England', 'daniel butterworth'),
	('Daniel Butterworth', 'England', 'butterworth'),
	('Andrew Gutman', 'United States', 'gutman'),
	('Andrew Gutman', 'United States', 'andrew gutman'),
	('Malte Kiilerich', 'Denmark', 'kiilerich'),
	('Malte Kiilerich', 'Denmark', 'malte kiilerich'),
	('Leonardo Sernicola', 'Italy', 'leonardo sernicola'),
	('Leonardo Sernicola', 'Italy', 'sernicola'),
	('Budimir Janošević', 'Serbia', 'budimir janosevic'),
	('Budimir Janošević', 'Serbia', 'janosevic'),
	('Brent Gabriël', 'Belgium', 'brent gabriel'),
	('Brent Gabriël', 'Belgium', 'gabriel'),
	('Paul Downing', 'England', 'paul downing'),
	('Paul Downing', 'England', 'downing'),
	('Din Sula', 'Albania', 'sula'),
	('Din Sula', 'Albania', 'din sula'),
	('Jordan O''Doherty', 'Australia', 'jordan odoherty'),
	('Jordan O''Doherty', 'Australia', 'odoherty'),
	('Willian Candia', 'Paraguay', 'willian candia'),
	('Willian Candia', 'Paraguay', 'candia'),
	('Omar Rekik', 'Netherlands', 'omar rekik'),
	('Omar Rekik', 'Netherlands', 'rekik'),
	('Alex Rodman', 'England', 'alex rodman'),
	('Alex Rodman', 'England', 'rodman'),
	('Patrick Banggaard', 'Denmark', 'patrick banggaard'),
	('Patrick Banggaard', 'Denmark', 'banggaard'),
	('Yuta Goke', 'Japan', 'yuta goke'),
	('Yuta Goke', 'Japan', 'goke'),
	('Li Hang', 'China PR', 'li hang'),
	('Li Hang', 'China PR', 'hang'),
	('Ricardo Escobar', 'Chile', 'escobar'),
	('Ricardo Escobar', 'Chile', 'ricardo escobar'),
	('David Cornell', 'Wales', 'cornell'),
	('David Cornell', 'Wales', 'david cornell'),
	('Jorge Ordóñez', 'Ecuador', 'jorge ordonez'),
	('Jorge Ordóñez', 'Ecuador', 'ordonez'),
	('Ebrima Colley', 'Gambia', 'colley'),
	('Ebrima Colley', 'Gambia', 'ebrima colley'),
	('Giuseppe Caso', 'Italy', 'caso'),
	('Giuseppe Caso', 'Italy', 'giuseppe caso'),
	('Loïc Poujol', 'France', 'poujol'),
	('Loïc Poujol', 'France', 'loic poujol'),
	('Mickaël Latour', 'France', 'latour'),
	('Mickaël Latour', 'France', 'mickael latour'),
	('Andreas Skovgaard', 'Denmark', 'andreas skovgaard'),
	('Andreas Skovgaard', 'Denmark', 'skovgaard'),
	('So Fujitani', 'Japan', 'so fujitani'),
	('So Fujitani', 'Japan', 'fujitani'),
	('Clément Vidal', 'France', 'vidal'),
	('Clément Vidal', 'France', 'clement vidal'),
	('Mike Könnecke', 'Germany', 'konnecke'),
	('Mike Könnecke', 'Germany', 'mike konnecke'),
	('Pablo Gavilán', 'Paraguay', 'pablo gavilan'),
	('Pablo Gavilán', 'Paraguay', 'gavilan'),
	('Nicolai Geertsen', 'Denmark', 'geertsen'),
	('Nicolai Geertsen', 'Denmark', 'nicolai geertsen'),
	('René Guder', 'Germany', 'rene guder'),
	('René Guder', 'Germany', 'guder'),
	('Yusuke Kobayashi', 'Japan', 'yusuke kobayashi'),
	('Yusuke Kobayashi', 'Japan', 'kobayashi'),
	('Yang Sang Min', 'Korea Republic', 'yang sang min'),
	('Yang Sang Min', 'Korea Republic', 'min'),
	('Edgar Zaracho', 'Paraguay', 'edgar zaracho'),
	('Edgar Zaracho', 'Paraguay', 'zaracho'),
	('Álex Blesa', 'Spain', 'blesa'),
	('Álex Blesa', 'Spain', 'alex blesa'),
	('Steffen Lie Skålevik', 'Norway', 'skalevik'),
	('Steffen Lie Skålevik', 'Norway', 'steffen lie skalevik'),
	('Hiroto Nakagawa', 'Japan', 'nakagawa'),
	('Hiroto Nakagawa', 'Japan', 'hiroto nakagawa'),
	('Osman Hadžikić', 'Austria', 'osman hadzikic'),
	('Osman Hadžikić', 'Austria', 'hadzikic'),
	('Timothée Pembélé', 'France', 'pembele'),
	('Timothée Pembélé', 'France', 'timothee pembele'),
	('Djed Spence', 'England', 'djed spence'),
	('Djed Spence', 'England', 'spence'),
	('Erik Lira', 'Mexico', 'erik lira'),
	('Erik Lira', 'Mexico', 'lira'),
	('Giannis Papanikolaou', 'Greece', 'papanikolaou'),
	('Giannis Papanikolaou', 'Greece', 'giannis papanikolaou'),
	('Michael Brouwer', 'Netherlands', 'michael brouwer'),
	('Michael Brouwer', 'Netherlands', 'brouwer'),
	('Albert Ejupi', 'Sweden', 'albert ejupi'),
	('Albert Ejupi', 'Sweden', 'ejupi'),
	('Amir Nouri', 'France', 'amir nouri'),
	('Amir Nouri', 'France', 'nouri'),
	('Thomas Rotter', 'Austria', 'rotter'),
	('Thomas Rotter', 'Austria', 'thomas rotter'),
	('Charles Vernam', 'England', 'vernam'),
	('Charles Vernam', 'England', 'charles vernam'),
	('Woyo Coulibaly', 'France', 'woyo coulibaly'),
	('Woyo Coulibaly', 'France', 'coulibaly'),
	('Louis Appéré', 'Scotland', 'appere'),
	('Louis Appéré', 'Scotland', 'louis appere'),
	('Janik Jesgarzewski', 'Germany', 'jesgarzewski'),
	('Janik Jesgarzewski', 'Germany', 'janik jesgarzewski'),
	('Jesús Fernández', 'Spain', 'fernandez'),
	('Jesús Fernández', 'Spain', 'jesus fernandez'),
	('Scott Flinders', 'England', 'flinders'),
	('Scott Flinders', 'England', 'scott flinders'),
	('François-Xavier Fumu Tamuzo', 'France', 'francoisxavier fumu tamuzo'),
	('François-Xavier Fumu Tamuzo', 'France', 'tamuzo'),
	('Lee Sang Min', 'Korea Republic', 'lee sang min'),
	('Lee Sang Min', 'Korea Republic', 'min'),
	('Rewan Amin', 'Netherlands', 'amin'),
	('Rewan Amin', 'Netherlands', 'rewan amin'),
	('Nikolai Rehnen', 'Germany', 'rehnen'),
	('Nikolai Rehnen', 'Germany', 'nikolai rehnen'),
	('Rollin Menayese', 'Wales', 'rollin menayese'),
	('Rollin Menayese', 'Wales', 'menayese'),
	('Peter Clarke', 'England', 'clarke'),
	('Peter Clarke', 'England', 'peter clarke'),
	('Kevin Arias', 'Ecuador', 'kevin arias'),
	('Kevin Arias', 'Ecuador', 'arias'),
	('Tobias Heintz', 'Norway', 'heintz'),
	('Tobias Heintz', 'Norway', 'tobias heintz'),
	('Ibrahima Kébé', 'Mali', 'kebe'),
	('Ibrahima Kébé', 'Mali', 'ibrahima kebe'),
	('Jeremy Salas', 'Peru', 'salas'),
	('Jeremy Salas', 'Peru', 'jeremy salas'),
	('Paolo Reyna', 'Peru', 'reyna'),
	('Paolo Reyna', 'Peru', 'paolo reyna'),
	('Yang Jun A', 'Korea Republic', 'yang jun a'),
	('Luther James-Wildin', 'Antigua & Barbuda', 'jameswildin'),
	('Luther James-Wildin', 'Antigua & Barbuda', 'luther jameswildin'),
	('Miguel Suárez', 'Bolivia', 'suarez'),
	('Miguel Suárez', 'Bolivia', 'miguel suarez'),
	('Vedad Radonja', 'Bosnia Herzegovina', 'radonja'),
	('Vedad Radonja', 'Bosnia Herzegovina', 'vedad radonja'),
	('Vladislavs Gutkovskis', 'Latvia', 'vladislavs gutkovskis'),
	('Vladislavs Gutkovskis', 'Latvia', 'gutkovskis'),
	('Theo Archibald', 'Scotland', 'theo archibald'),
	('Theo Archibald', 'Scotland', 'archibald'),
	('Seny Dieng', 'Senegal', 'seny dieng'),
	('Seny Dieng', 'Senegal', 'dieng'),
	('Bilal Benkhedim', 'France', 'benkhedim'),
	('Bilal Benkhedim', 'France', 'bilal benkhedim'),
	('Victor Dávalos', 'Paraguay', 'davalos'),
	('Victor Dávalos', 'Paraguay', 'victor davalos'),
	('Pau Víctor', 'Spain', 'pau victor'),
	('Pau Víctor', 'Spain', 'victor'),
	('Dominik Reimann', 'Germany', 'reimann'),
	('Dominik Reimann', 'Germany', 'dominik reimann'),
	('Choi Oh Back', 'Korea Republic', 'choi oh back'),
	('Choi Oh Back', 'Korea Republic', 'back'),
	('Ahmed Al Zain', 'Saudi Arabia', 'zain'),
	('Ahmed Al Zain', 'Saudi Arabia', 'ahmed al zain'),
	('Fernando Coniglio', 'Argentina', 'coniglio'),
	('Fernando Coniglio', 'Argentina', 'fernando coniglio'),
	('Philippe Paulin Keny', 'Senegal', 'keny'),
	('Philippe Paulin Keny', 'Senegal', 'philippe paulin keny'),
	('Fatih Kaya', 'Germany', 'fatih kaya'),
	('Fatih Kaya', 'Germany', 'kaya'),
	('Daniel Jarl', 'Sweden', 'daniel jarl'),
	('Daniel Jarl', 'Sweden', 'jarl'),
	('Robby McCrorie', 'Scotland', 'mccrorie'),
	('Robby McCrorie', 'Scotland', 'robby mccrorie'),
	('Caner Hüseyin Bağ', 'Turkey', 'caner huseyin bag'),
	('Caner Hüseyin Bağ', 'Turkey', 'bag'),
	('Wilfredo Soleto', 'Bolivia', 'wilfredo soleto'),
	('Wilfredo Soleto', 'Bolivia', 'soleto'),
	('Deyver Vega', 'Costa Rica', 'deyver vega'),
	('Deyver Vega', 'Costa Rica', 'vega'),
	('Ayman Azhil', 'Germany', 'azhil'),
	('Ayman Azhil', 'Germany', 'ayman azhil'),
	('Deniz Hümmet', 'Turkey', 'hummet'),
	('Deniz Hümmet', 'Turkey', 'deniz hummet'),
	('Hernán Lópes', 'Argentina', 'lopes'),
	('Hernán Lópes', 'Argentina', 'hernan lopes'),
	('Mohammed Bu Sanda', 'United Arab Emirates', 'sanda'),
	('Mohammed Bu Sanda', 'United Arab Emirates', 'mohammed bu sanda'),
	('Hikmet Çiftçi', 'Turkey', 'hikmet ciftci'),
	('Hikmet Çiftçi', 'Turkey', 'ciftci'),
	('Anton Wede', 'Sweden', 'anton wede'),
	('Anton Wede', 'Sweden', 'wede'),
	('Alan Dzabana', 'France', 'alan dzabana'),
	('Alan Dzabana', 'France', 'dzabana'),
	('Ivan Ostojić', 'Serbia', 'ostojic'),
	('Ivan Ostojić', 'Serbia', 'ivan ostojic'),
	('Naoki Ishikawa', 'Japan', 'naoki ishikawa'),
	('Naoki Ishikawa', 'Japan', 'ishikawa'),
	('James Clarke', 'England', 'clarke'),
	('James Clarke', 'England', 'james clarke'),
	('Jordi Sánchez', 'Spain', 'jordi sanchez'),
	('Jordi Sánchez', 'Spain', 'sanchez'),
	('Nicolas Feldhahn', 'Germany', 'feldhahn'),
	('Nicolas Feldhahn', 'Germany', 'nicolas feldhahn'),
	('Jordan Maguire-Drew', 'England', 'maguiredrew'),
	('Jordan Maguire-Drew', 'England', 'jordan maguiredrew'),
	('Takeshi Kanamori', 'Japan', 'kanamori'),
	('Takeshi Kanamori', 'Japan', 'takeshi kanamori'),
	('Mynor Escoe', 'Costa Rica', 'escoe'),
	('Mynor Escoe', 'Costa Rica', 'mynor escoe'),
	('Mustafa Eskihellaç', 'Turkey', 'eskihellac'),
	('Mustafa Eskihellaç', 'Turkey', 'mustafa eskihellac'),
	('Martin Ramsland', 'Norway', 'ramsland'),
	('Martin Ramsland', 'Norway', 'martin ramsland'),
	('Tom Pope', 'England', 'tom pope'),
	('Tom Pope', 'England', 'pope'),
	('Kornelius N. Hansen', 'Norway', 'kornelius n hansen'),
	('Kornelius N. Hansen', 'Norway', 'hansen'),
	('Song Jin Hyung', 'Korea Republic', 'song jin hyung'),
	('Song Jin Hyung', 'Korea Republic', 'hyung'),
	('Ulrich Bapoh', 'Germany', 'ulrich bapoh'),
	('Ulrich Bapoh', 'Germany', 'bapoh'),
	('Nick Bätzner', 'Germany', 'nick batzner'),
	('Nick Bätzner', 'Germany', 'batzner'),
	('Thibaud Verlinden', 'Belgium', 'verlinden'),
	('Thibaud Verlinden', 'Belgium', 'thibaud verlinden'),
	('Kilian Fischer', 'Germany', 'kilian fischer'),
	('Kilian Fischer', 'Germany', 'fischer'),
	('Óscar Clemente', 'Spain', 'clemente'),
	('Óscar Clemente', 'Spain', 'oscar clemente'),
	('Raphael Obermair', 'Germany', 'raphael obermair'),
	('Raphael Obermair', 'Germany', 'obermair'),
	('Kalle Joelsson', 'Sweden', 'joelsson'),
	('Kalle Joelsson', 'Sweden', 'kalle joelsson'),
	('Oscar Schönfelder', 'Germany', 'schonfelder'),
	('Oscar Schönfelder', 'Germany', 'oscar schonfelder'),
	('Franco Paredes', 'Argentina', 'franco paredes'),
	('Franco Paredes', 'Argentina', 'paredes'),
	('Marco Wolff', 'Argentina', 'wolff'),
	('Marco Wolff', 'Argentina', 'marco wolff'),
	('Reece Grego-Cox', 'Republic of Ireland', 'reece gregocox'),
	('Reece Grego-Cox', 'Republic of Ireland', 'gregocox'),
	('Lewis Banks', 'England', 'banks'),
	('Lewis Banks', 'England', 'lewis banks'),
	('Villalón', 'Spain', 'villalon'),
	('Anton Donkor', 'Germany', 'anton donkor'),
	('Anton Donkor', 'Germany', 'donkor'),
	('Jiang Tao', 'China PR', 'jiang tao'),
	('Jiang Tao', 'China PR', 'tao'),
	('Mohammed Helal', 'United Arab Emirates', 'mohammed helal'),
	('Mohammed Helal', 'United Arab Emirates', 'helal'),
	('Daniel Nussbaumer', 'Austria', 'nussbaumer'),
	('Daniel Nussbaumer', 'Austria', 'daniel nussbaumer'),
	('Lewis Alessandra', 'England', 'lewis alessandra'),
	('Lewis Alessandra', 'England', 'alessandra'),
	('Eren Dinkçi', 'Germany', 'dinkci'),
	('Eren Dinkçi', 'Germany', 'eren dinkci'),
	('Braian Galván', 'Argentina', 'braian galvan'),
	('Braian Galván', 'Argentina', 'galvan'),
	('Ezequiel Rodríguez', 'Argentina', 'rodriguez'),
	('Ezequiel Rodríguez', 'Argentina', 'ezequiel rodriguez'),
	('Arbenit Xhemajli', 'Kosovo', 'xhemajli'),
	('Arbenit Xhemajli', 'Kosovo', 'arbenit xhemajli'),
	('Federico Versaci', 'Argentina', 'federico versaci'),
	('Federico Versaci', 'Argentina', 'versaci'),
	('Jordan Lyden', 'Australia', 'jordan lyden'),
	('Jordan Lyden', 'Australia', 'lyden'),
	('Alex Iacovitti', 'Scotland', 'alex iacovitti'),
	('Alex Iacovitti', 'Scotland', 'iacovitti'),
	('Mohamed Amissi', 'Burundi', 'mohamed amissi'),
	('Mohamed Amissi', 'Burundi', 'amissi'),
	('Francisco Parra', 'Paraguay', 'francisco parra'),
	('Francisco Parra', 'Paraguay', 'parra'),
	('Octavian Ursu', 'Romania', 'octavian ursu'),
	('Octavian Ursu', 'Romania', 'ursu'),
	('Morten Sætra', 'Norway', 'morten stra'),
	('Morten Sætra', 'Norway', 'stra'),
	('Kentaro Seki', 'Japan', 'kentaro seki'),
	('Kentaro Seki', 'Japan', 'seki'),
	('Mamadou Doucouré', 'France', 'doucoure'),
	('Mamadou Doucouré', 'France', 'mamadou doucoure'),
	('Jack McMillan', 'Scotland', 'mcmillan'),
	('Jack McMillan', 'Scotland', 'jack mcmillan'),
	('Naif Mousa', 'Saudi Arabia', 'mousa'),
	('Naif Mousa', 'Saudi Arabia', 'naif mousa'),
	('Omar Muzayil', 'Saudi Arabia', 'muzayil'),
	('Omar Muzayil', 'Saudi Arabia', 'omar muzayil'),
	('Corey O''Keeffe', 'Republic of Ireland', 'okeeffe'),
	('Corey O''Keeffe', 'Republic of Ireland', 'corey okeeffe'),
	('Callum Morris', 'Northern Ireland', 'callum morris'),
	('Callum Morris', 'Northern Ireland', 'morris'),
	('Matt Palmer', 'England', 'matt palmer'),
	('Matt Palmer', 'England', 'palmer'),
	('César Huerta', 'Mexico', 'cesar huerta'),
	('César Huerta', 'Mexico', 'huerta'),
	('Calvin Bassey', 'England', 'bassey'),
	('Calvin Bassey', 'England', 'calvin bassey'),
	('Emanuel Maciel', 'Argentina', 'maciel'),
	('Emanuel Maciel', 'Argentina', 'emanuel maciel'),
	('Lars Bünning', 'Germany', 'bunning'),
	('Lars Bünning', 'Germany', 'lars bunning'),
	('Alexander Aravena', 'Chile', 'alexander aravena'),
	('Alexander Aravena', 'Chile', 'aravena'),
	('Ferhat Görgülü', 'Netherlands', 'ferhat gorgulu'),
	('Ferhat Görgülü', 'Netherlands', 'gorgulu'),
	('Alejandro Zendejas', 'Mexico', 'zendejas'),
	('Alejandro Zendejas', 'Mexico', 'alejandro zendejas'),
	('Gonzalo Casazza', 'Argentina', 'gonzalo casazza'),
	('Gonzalo Casazza', 'Argentina', 'casazza'),
	('Felipe Galvis', 'Spain', 'galvis'),
	('Felipe Galvis', 'Spain', 'felipe galvis'),
	('Harvey Knibbs', 'England', 'harvey knibbs'),
	('Harvey Knibbs', 'England', 'knibbs'),
	('Matías Borgogno', 'Argentina', 'borgogno'),
	('Matías Borgogno', 'Argentina', 'matias borgogno'),
	('Robin Brüseke', 'Germany', 'bruseke'),
	('Robin Brüseke', 'Germany', 'robin bruseke'),
	('Eirik Haugan', 'Norway', 'haugan'),
	('Eirik Haugan', 'Norway', 'eirik haugan'),
	('David Salazar', 'Mexico', 'salazar'),
	('David Salazar', 'Mexico', 'david salazar'),
	('Daniel Björnquist', 'Sweden', 'daniel bjornquist'),
	('Daniel Björnquist', 'Sweden', 'bjornquist'),
	('Mohammed Al Baqawi', 'Saudi Arabia', 'mohammed al baqawi'),
	('Mohammed Al Baqawi', 'Saudi Arabia', 'baqawi'),
	('Scott Robertson', 'Scotland', 'robertson'),
	('Scott Robertson', 'Scotland', 'scott robertson'),
	('Robbe Quirynen', 'Belgium', 'robbe quirynen'),
	('Robbe Quirynen', 'Belgium', 'quirynen'),
	('Jerell Sellars', 'England', 'sellars'),
	('Jerell Sellars', 'England', 'jerell sellars'),
	('Awadh Khrees', 'Saudi Arabia', 'awadh khrees'),
	('Awadh Khrees', 'Saudi Arabia', 'khrees'),
	('Alfredo Pussetto', 'Argentina', 'pussetto'),
	('Alfredo Pussetto', 'Argentina', 'alfredo pussetto'),
	('George Tanner', 'England', 'george tanner'),
	('George Tanner', 'England', 'tanner'),
	('Matej Rodin', 'Bosnia Herzegovina', 'matej rodin'),
	('Matej Rodin', 'Bosnia Herzegovina', 'rodin'),
	('Paudie O''Connor', 'Republic of Ireland', 'paudie oconnor'),
	('Paudie O''Connor', 'Republic of Ireland', 'oconnor'),
	('Iván Cazal', 'Paraguay', 'cazal'),
	('Iván Cazal', 'Paraguay', 'ivan cazal'),
	('Omar Jaiteh', 'Gambia', 'jaiteh'),
	('Omar Jaiteh', 'Gambia', 'omar jaiteh'),
	('Xu Xin', 'China PR', 'xin'),
	('Xu Xin', 'China PR', 'xu xin'),
	('Carl Tremarco', 'England', 'carl tremarco'),
	('Carl Tremarco', 'England', 'tremarco'),
	('Masood Bakhit', 'Saudi Arabia', 'masood bakhit'),
	('Masood Bakhit', 'Saudi Arabia', 'bakhit'),
	('Yasin Çakaloğlu', 'Turkey', 'yasin cakaloglu'),
	('Yasin Çakaloğlu', 'Turkey', 'cakaloglu'),
	('Samson Okikiola Tijani', 'Nigeria', 'samson okikiola tijani'),
	('Samson Okikiola Tijani', 'Nigeria', 'tijani'),
	('Jesús Carrillo', 'Spain', 'jesus carrillo'),
	('Jesús Carrillo', 'Spain', 'carrillo'),
	('William Kurtović', 'Sweden', 'william kurtovic'),
	('William Kurtović', 'Sweden', 'kurtovic'),
	('Sam Stubbs', 'England', 'stubbs'),
	('Sam Stubbs', 'England', 'sam stubbs')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';