INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Ryo Nagai', 'Japan', 'player'),
	('Argyris Kampetsis', 'Greece', 'player'),
	('Fatai Alashe', 'United States', 'player'),
	('Leonardo Mifflin', 'Peru', 'player'),
	('Luca Plogmann', 'Germany', 'player'),
	('Nicolás Sessa', 'Germany', 'player'),
	('Stephen Odey', 'Nigeria', 'player'),
	('Omar Yaisien', 'Egypt', 'player'),
	('Tom Lowery', 'England', 'player'),
	('Mario González', 'Spain', 'player'),
	('Scott Fox', 'Scotland', 'player'),
	('Kevin Lankford', 'Germany', 'player'),
	('Robert Jendrusch', 'Germany', 'player'),
	('Mehdi Jeannin', 'Algeria', 'player'),
	('Jonas Grønner', 'Norway', 'player'),
	('Boris Babić', 'Switzerland', 'player'),
	('Abou Ouattara', 'Burkina Faso', 'player'),
	('Markus Nakkim', 'Norway', 'player'),
	('Milan van Ewijk', 'Netherlands', 'player'),
	('Helge Sandvik', 'Norway', 'player'),
	('Jordy Candia', 'Bolivia', 'player'),
	('Abdulrahman Al Barakah', 'Saudi Arabia', 'player'),
	('Tom Eastman', 'England', 'player'),
	('Damien Furtado', 'France', 'player'),
	('Floriano Vanzo', 'Belgium', 'player'),
	('Ryu Takao', 'Japan', 'player'),
	('Matt Done', 'England', 'player'),
	('Tiago Banega', 'Argentina', 'player'),
	('Luis Delgado', 'Colombia', 'player'),
	('Emilio Sánchez', 'Mexico', 'player'),
	('Luka Šušnjara', 'Slovenia', 'player'),
	('Andrea D''Errico', 'Italy', 'player'),
	('Bernardo Cuesta', 'Argentina', 'player'),
	('James Brophy', 'England', 'player'),
	('Moses Opondo', 'Uganda', 'player'),
	('Shota Kobayashi', 'Japan', 'player'),
	('John Kitolano', 'Norway', 'player'),
	('Benjamín Garré', 'Argentina', 'player'),
	('Omran Haydary', 'Afghanistan', 'player'),
	('Iván Márquez', 'Spain', 'player'),
	('Rasmus Lindkvist', 'Sweden', 'player'),
	('Emil Nielsen', 'Denmark', 'player'),
	('Nicolas Kocik', 'France', 'player'),
	('Kang Ji Hoon', 'Korea Republic', 'player'),
	('Łukasz Sierpina', 'Poland', 'player'),
	('Keaghan Jacobs', 'South Africa', 'player'),
	('Aboubacar Keita', 'United States', 'player'),
	('Saad Abdul-Salaam', 'United States', 'player'),
	('Samu Casado', 'Spain', 'player'),
	('Filip Jagiełło', 'Poland', 'player'),
	('Samy Bourard', 'Belgium', 'player'),
	('Joaquín Zeballos', 'Uruguay', 'player'),
	('Leandrinho', 'Brazil', 'player'),
	('Ghazi Ayadi', 'Tunisia', 'player'),
	('Bilal Boutobba', 'France', 'player'),
	('Petar Mamić', 'Croatia', 'player'),
	('Jordan Thompson', 'Northern Ireland', 'player'),
	('Korbinian Vollmann', 'Germany', 'player'),
	('Amine Adli', 'France', 'player'),
	('Stephen Humphrys', 'England', 'player'),
	('Anyelo Campos', 'Peru', 'player'),
	('Christoph Hemlein', 'Germany', 'player'),
	('Show', 'Angola', 'player'),
	('Florian Carstens', 'Germany', 'player'),
	('Juan Camilo Salazar', 'Colombia', 'player'),
	('Toni Herrero', 'Spain', 'player'),
	('Adam Jahn', 'United States', 'player'),
	('Lars Lokotsch', 'Germany', 'player'),
	('Magnus Lekven', 'Norway', 'player'),
	('Ariel Lassiter', 'Costa Rica', 'player'),
	('Berkay Dabanlı', 'Germany', 'player'),
	('Mamadou Coulibaly', 'Senegal', 'player'),
	('Facundo García', 'Argentina', 'player'),
	('Miłosz Szczepański', 'Poland', 'player'),
	('Dionicio Escalante', 'Mexico', 'player'),
	('Gastón Comas', 'Argentina', 'player'),
	('Felipe López', 'Mexico', 'player'),
	('Jerry Yates', 'England', 'player'),
	('Callum Brittain', 'England', 'player'),
	('Thore Jacobsen', 'Germany', 'player'),
	('Christian Schneuwly', 'Switzerland', 'player'),
	('Richard Celis', 'Venezuela', 'player'),
	('Fanol Përdedaj', 'Kosovo', 'player'),
	('Chema Núñez', 'Spain', 'player'),
	('Florian Chabrolle', 'France', 'player'),
	('Rachid Bouhenna', 'Algeria', 'player'),
	('Jonathan Obika', 'England', 'player'),
	('Lasse Fosgaard', 'Denmark', 'player'),
	('Christopher Missilou', 'Congo', 'player'),
	('Marcos López', 'Peru', 'player'),
	('Carlos Núñez', 'Uruguay', 'player'),
	('Juanma Bravo', 'Spain', 'player'),
	('Aiyegun Tosin', 'Nigeria', 'player'),
	('Song Ju Hun', 'Korea Republic', 'player'),
	('Thijmen Nijhuis', 'Netherlands', 'player'),
	('Tony Craig', 'England', 'player'),
	('Alexi Gómez', 'Peru', 'player'),
	('Rami Kaib', 'Sweden', 'player'),
	('David Edwards', 'Wales', 'player'),
	('Roy Beerens', 'Netherlands', 'player'),
	('Saeed Al Rubaie', 'Saudi Arabia', 'player'),
	('Ovidiu Bic', 'Romania', 'player'),
	('Juan Cruz Mascia', 'Uruguay', 'player'),
	('George Merloi', 'Romania', 'player'),
	('Uche Ikpeazu', 'Uganda', 'player'),
	('Trevor Clarke', 'Republic of Ireland', 'player'),
	('Lilian Brassier', 'France', 'player'),
	('Regalón', 'Spain', 'player'),
	('Joey O''Brien', 'Republic of Ireland', 'player'),
	('Joel Sánchez', 'Peru', 'player'),
	('Luke Prosser', 'England', 'player'),
	('Marc Endres', 'Germany', 'player'),
	('Bai Jiajun', 'China PR', 'player'),
	('Rémy Boissier', 'France', 'player'),
	('Lee Jin Hyun', 'Korea Republic', 'player'),
	('Yunus Musah', 'England', 'player'),
	('Emil Jonassen', 'Norway', 'player'),
	('Samy Benchama', 'France', 'player'),
	('Dame Diop', 'Senegal', 'player'),
	('Hirofumi Watanabe', 'Japan', 'player'),
	('Samuel Mensiro', 'Ghana', 'player'),
	('Florin Iacob', 'Romania', 'player'),
	('Jeppe Simonsen', 'Denmark', 'player'),
	('Carlos Alves', 'Portugal', 'player'),
	('Kyle Dempsey', 'England', 'player'),
	('Louis Fenton', 'New Zealand', 'player'),
	('Piotr Malarczyk', 'Poland', 'player'),
	('Orlando Gaona Lugo', 'Paraguay', 'player'),
	('Vegard Bergan', 'Norway', 'player'),
	('Ben Kantarovski', 'Australia', 'player'),
	('Marco Holz', 'Germany', 'player'),
	('Marko Roginić', 'Croatia', 'player'),
	('Caolan Lavery', 'Northern Ireland', 'player'),
	('Kaan Kurt', 'Germany', 'player'),
	('Yoshiki Takahashi', 'Japan', 'player'),
	('Fabian de Keijzer', 'Netherlands', 'player'),
	('Eris Abedini', 'Kosovo', 'player'),
	('André Dej', 'Poland', 'player'),
	('Juan Manuel Gutiérrez', 'Uruguay', 'player'),
	('Konrad de la Fuente', 'United States', 'player'),
	('Oğuz Yılmaz', 'Turkey', 'player'),
	('Nahuel Banegas', 'Argentina', 'player'),
	('Bünyamin Balcı', 'Turkey', 'player'),
	('Ammar Helac', 'Austria', 'player'),
	('Edu Espiau', 'Spain', 'player'),
	('Stefanos Evangelou', 'Greece', 'player'),
	('Ramón ten Hove', 'Netherlands', 'player'),
	('Aaron Hayden', 'England', 'player'),
	('Alhaji Gero', 'Nigeria', 'player'),
	('Hugo Vandermersch', 'France', 'player'),
	('Umaru Bangura', 'Sierra Leone', 'player'),
	('Daniel Maderner', 'Austria', 'player'),
	('Joe Mason', 'Republic of Ireland', 'player'),
	('Marcel Canadi', 'Austria', 'player'),
	('Eddie Nolan', 'Republic of Ireland', 'player'),
	('Mike Jones', 'England', 'player'),
	('Frank Nouble', 'England', 'player'),
	('Joaquin García', 'Argentina', 'player'),
	('Bernd Gschweidl', 'Austria', 'player'),
	('Erik Hurtado', 'United States', 'player'),
	('Johan Hammar', 'Sweden', 'player'),
	('Lucas Brochero', 'Argentina', 'player'),
	('Sphephelo Sithole', 'South Africa', 'player'),
	('Luca Netz', 'Germany', 'player'),
	('Kamil Biliński', 'Poland', 'player'),
	('Kyosuke Tagawa', 'Japan', 'player'),
	('Pape Ndiaga Yade', 'Senegal', 'player'),
	('Fabrizio Brignani', 'Italy', 'player'),
	('Marius Mihalache', 'Romania', 'player'),
	('Albert Stahl', 'Romania', 'player'),
	('Gabriel Mutombo', 'France', 'player'),
	('Dani Cárdenas', 'Spain', 'player'),
	('Cyrill Akono', 'Germany', 'player'),
	('Gabriel Matei', 'Romania', 'player'),
	('Felix Michel', 'Lebanon', 'player'),
	('Dawid Szymonowicz', 'Poland', 'player'),
	('Ciprian Rus', 'Romania', 'player'),
	('François Marquet', 'Belgium', 'player'),
	('Mansour Hamzi', 'Saudi Arabia', 'player'),
	('Patrick Schikowski', 'Poland', 'player'),
	('Álex Domínguez', 'Spain', 'player'),
	('Sergio Benito', 'Spain', 'player'),
	('Yohei Toyoda', 'Japan', 'player'),
	('Steven Vitória', 'Canada', 'player'),
	('Jorge Mier', 'Spain', 'player'),
	('Grant Lillard', 'United States', 'player'),
	('Ayo Simon Okosun', 'Denmark', 'player'),
	('Liao Junjian', 'China PR', 'player'),
	('Oh Beom Seok', 'Korea Republic', 'player'),
	('Darío Sarmiento', 'Argentina', 'player'),
	('Mariusz Malec', 'Poland', 'player'),
	('Niall Canavan', 'Republic of Ireland', 'player'),
	('Callum Morton', 'England', 'player'),
	('Arthur Silva', 'Brazil', 'player'),
	('Ulises Abreliano', 'Argentina', 'player'),
	('Ballou Tabla', 'Canada', 'player'),
	('Luke Leahy', 'England', 'player'),
	('Ramón Enríquez', 'Spain', 'player'),
	('Fahad Hadid', 'United Arab Emirates', 'player'),
	('Nikola Kuveljić', 'Serbia', 'player'),
	('Yang Hyung Mo', 'Korea Republic', 'player'),
	('Marcus Maier', 'Austria', 'player'),
	('Regan Poole', 'Wales', 'player'),
	('Lucas Schoofs', 'Belgium', 'player'),
	('Luís Silva', 'Portugal', 'player'),
	('Mehmet Erdem Uğurlu', 'Turkey', 'player'),
	('Dylan Wenzel-Halls', 'Australia', 'player'),
	('Daryl Dike', 'United States', 'player'),
	('Diego González', 'Mexico', 'player'),
	('Hugo Rama', 'Spain', 'player'),
	('Kevin Luckassen', 'Netherlands', 'player'),
	('Jairsinho González', 'Peru', 'player'),
	('Slobodan Tedić', 'Serbia', 'player'),
	('Luka Štor', 'Slovenia', 'player'),
	('Pelayo Morilla', 'Spain', 'player'),
	('Menno Koch', 'Netherlands', 'player'),
	('Alexander Schmidt', 'Austria', 'player'),
	('Ryota Hayasaka', 'Japan', 'player'),
	('Raffaele De Vita', 'Italy', 'player'),
	('Luke Varney', 'England', 'player'),
	('Joackim Jørgensen', 'Norway', 'player'),
	('Marius Tomozei', 'Romania', 'player'),
	('Alfredo', 'Spain', 'player'),
	('Kewin', 'Brazil', 'player'),
	('Iñaki Astiz', 'Spain', 'player'),
	('Hólguer Matamoros', 'Ecuador', 'player'),
	('Wang Wei', 'China PR', 'player'),
	('Prince Osei Owusu', 'Germany', 'player'),
	('Lamine Diabyfadiga', 'France', 'player'),
	('Carl Piergianni', 'England', 'player'),
	('Hendrik Hansen', 'Germany', 'player'),
	('Alfie Jones', 'England', 'player'),
	('George Johnston', 'Scotland', 'player'),
	('Víctor Fernández', 'Spain', 'player'),
	('Jordan Clarke', 'England', 'player'),
	('Florin Ilie', 'Romania', 'player'),
	('Nick Gillekens', 'Belgium', 'player'),
	('Keiya Shiihashi', 'Japan', 'player'),
	('Svante Ingelsson', 'Sweden', 'player'),
	('Rui Pires', 'Portugal', 'player'),
	('Djibril Dianessy', 'France', 'player'),
	('Marcos Enrique', 'Argentina', 'player'),
	('Isaac Vassell', 'England', 'player'),
	('Ryo Shinzato', 'Japan', 'player'),
	('Stefan Mauk', 'Australia', 'player'),
	('Billy McKay', 'Northern Ireland', 'player'),
	('Soma Novothny', 'Hungary', 'player'),
	('Renzo Tesuri', 'Argentina', 'player'),
	('John Akinde', 'England', 'player'),
	('Justin Dhillon', 'United States', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Ryo Nagai', 'Japan', 'nagai'),
	('Ryo Nagai', 'Japan', 'ryo nagai'),
	('Argyris Kampetsis', 'Greece', 'argyris kampetsis'),
	('Argyris Kampetsis', 'Greece', 'kampetsis'),
	('Fatai Alashe', 'United States', 'alashe'),
	('Fatai Alashe', 'United States', 'fatai alashe'),
	('Leonardo Mifflin', 'Peru', 'mifflin'),
	('Leonardo Mifflin', 'Peru', 'leonardo mifflin'),
	('Luca Plogmann', 'Germany', 'luca plogmann'),
	('Luca Plogmann', 'Germany', 'plogmann'),
	('Nicolás Sessa', 'Germany', 'nicolas sessa'),
	('Nicolás Sessa', 'Germany', 'sessa'),
	('Stephen Odey', 'Nigeria', 'stephen odey'),
	('Stephen Odey', 'Nigeria', 'odey'),
	('Omar Yaisien', 'Egypt', 'yaisien'),
	('Omar Yaisien', 'Egypt', 'omar yaisien'),
	('Tom Lowery', 'England', 'lowery'),
	('Tom Lowery', 'England', 'tom lowery'),
	('Mario González', 'Spain', 'mario gonzalez'),
	('Mario González', 'Spain', 'gonzalez'),
	('Scott Fox', 'Scotland', 'scott fox'),
	('Scott Fox', 'Scotland', 'fox'),
	('Kevin Lankford', 'Germany', 'lankford'),
	('Kevin Lankford', 'Germany', 'kevin lankford'),
	('Robert Jendrusch', 'Germany', 'jendrusch'),
	('Robert Jendrusch', 'Germany', 'robert jendrusch'),
	('Mehdi Jeannin', 'Algeria', 'jeannin'),
	('Mehdi Jeannin', 'Algeria', 'mehdi jeannin'),
	('Jonas Grønner', 'Norway', 'jonas grnner'),
	('Jonas Grønner', 'Norway', 'grnner'),
	('Boris Babić', 'Switzerland', 'boris babic'),
	('Boris Babić', 'Switzerland', 'babic'),
	('Abou Ouattara', 'Burkina Faso', 'abou ouattara'),
	('Abou Ouattara', 'Burkina Faso', 'ouattara'),
	('Markus Nakkim', 'Norway', 'nakkim'),
	('Markus Nakkim', 'Norway', 'markus nakkim'),
	('Milan van Ewijk', 'Netherlands', 'milan van ewijk'),
	('Milan van Ewijk', 'Netherlands', 'ewijk'),
	('Helge Sandvik', 'Norway', 'helge sandvik'),
	('Helge Sandvik', 'Norway', 'sandvik'),
	('Jordy Candia', 'Bolivia', 'candia'),
	('Jordy Candia', 'Bolivia', 'jordy candia'),
	('Abdulrahman Al Barakah', 'Saudi Arabia', 'abdulrahman al barakah'),
	('Abdulrahman Al Barakah', 'Saudi Arabia', 'barakah'),
	('Tom Eastman', 'England', 'eastman'),
	('Tom Eastman', 'England', 'tom eastman'),
	('Damien Furtado', 'France', 'damien furtado'),
	('Damien Furtado', 'France', 'furtado'),
	('Floriano Vanzo', 'Belgium', 'floriano vanzo'),
	('Floriano Vanzo', 'Belgium', 'vanzo'),
	('Ryu Takao', 'Japan', 'takao'),
	('Ryu Takao', 'Japan', 'ryu takao'),
	('Matt Done', 'England', 'done'),
	('Matt Done', 'England', 'matt done'),
	('Tiago Banega', 'Argentina', 'banega'),
	('Tiago Banega', 'Argentina', 'tiago banega'),
	('Luis Delgado', 'Colombia', 'luis delgado'),
	('Luis Delgado', 'Colombia', 'delgado'),
	('Emilio Sánchez', 'Mexico', 'emilio sanchez'),
	('Emilio Sánchez', 'Mexico', 'sanchez'),
	('Luka Šušnjara', 'Slovenia', 'susnjara'),
	('Luka Šušnjara', 'Slovenia', 'luka susnjara'),
	('Andrea D''Errico', 'Italy', 'andrea derrico'),
	('Andrea D''Errico', 'Italy', 'derrico'),
	('Bernardo Cuesta', 'Argentina', 'bernardo cuesta'),
	('Bernardo Cuesta', 'Argentina', 'cuesta'),
	('James Brophy', 'England', 'james brophy'),
	('James Brophy', 'England', 'brophy'),
	('Moses Opondo', 'Uganda', 'moses opondo'),
	('Moses Opondo', 'Uganda', 'opondo'),
	('Shota Kobayashi', 'Japan', 'shota kobayashi'),
	('Shota Kobayashi', 'Japan', 'kobayashi'),
	('John Kitolano', 'Norway', 'kitolano'),
	('John Kitolano', 'Norway', 'john kitolano'),
	('Benjamín Garré', 'Argentina', 'benjamin garre'),
	('Benjamín Garré', 'Argentina', 'garre'),
	('Omran Haydary', 'Afghanistan', 'haydary'),
	('Omran Haydary', 'Afghanistan', 'omran haydary'),
	('Iván Márquez', 'Spain', 'ivan marquez'),
	('Iván Márquez', 'Spain', 'marquez'),
	('Rasmus Lindkvist', 'Sweden', 'rasmus lindkvist'),
	('Rasmus Lindkvist', 'Sweden', 'lindkvist'),
	('Emil Nielsen', 'Denmark', 'emil nielsen'),
	('Emil Nielsen', 'Denmark', 'nielsen'),
	('Nicolas Kocik', 'France', 'nicolas kocik'),
	('Nicolas Kocik', 'France', 'kocik'),
	('Kang Ji Hoon', 'Korea Republic', 'kang ji hoon'),
	('Kang Ji Hoon', 'Korea Republic', 'hoon'),
	('Łukasz Sierpina', 'Poland', 'sierpina'),
	('Łukasz Sierpina', 'Poland', 'ukasz sierpina'),
	('Keaghan Jacobs', 'South Africa', 'jacobs'),
	('Keaghan Jacobs', 'South Africa', 'keaghan jacobs'),
	('Aboubacar Keita', 'United States', 'aboubacar keita'),
	('Aboubacar Keita', 'United States', 'keita'),
	('Saad Abdul-Salaam', 'United States', 'abdulsalaam'),
	('Saad Abdul-Salaam', 'United States', 'saad abdulsalaam'),
	('Samu Casado', 'Spain', 'samu casado'),
	('Samu Casado', 'Spain', 'casado'),
	('Filip Jagiełło', 'Poland', 'jagieo'),
	('Filip Jagiełło', 'Poland', 'filip jagieo'),
	('Samy Bourard', 'Belgium', 'samy bourard'),
	('Samy Bourard', 'Belgium', 'bourard'),
	('Joaquín Zeballos', 'Uruguay', 'joaquin zeballos'),
	('Joaquín Zeballos', 'Uruguay', 'zeballos'),
	('Leandrinho', 'Brazil', 'leandrinho'),
	('Ghazi Ayadi', 'Tunisia', 'ghazi ayadi'),
	('Ghazi Ayadi', 'Tunisia', 'ayadi'),
	('Bilal Boutobba', 'France', 'boutobba'),
	('Bilal Boutobba', 'France', 'bilal boutobba'),
	('Petar Mamić', 'Croatia', 'petar mamic'),
	('Petar Mamić', 'Croatia', 'mamic'),
	('Jordan Thompson', 'Northern Ireland', 'thompson'),
	('Jordan Thompson', 'Northern Ireland', 'jordan thompson'),
	('Korbinian Vollmann', 'Germany', 'vollmann'),
	('Korbinian Vollmann', 'Germany', 'korbinian vollmann'),
	('Amine Adli', 'France', 'adli'),
	('Amine Adli', 'France', 'amine adli'),
	('Stephen Humphrys', 'England', 'humphrys'),
	('Stephen Humphrys', 'England', 'stephen humphrys'),
	('Anyelo Campos', 'Peru', 'anyelo campos'),
	('Anyelo Campos', 'Peru', 'campos'),
	('Christoph Hemlein', 'Germany', 'hemlein'),
	('Christoph Hemlein', 'Germany', 'christoph hemlein'),
	('Show', 'Angola', 'show'),
	('Florian Carstens', 'Germany', 'carstens'),
	('Florian Carstens', 'Germany', 'florian carstens'),
	('Juan Camilo Salazar', 'Colombia', 'juan camilo salazar'),
	('Juan Camilo Salazar', 'Colombia', 'salazar'),
	('Toni Herrero', 'Spain', 'toni herrero'),
	('Toni Herrero', 'Spain', 'herrero'),
	('Adam Jahn', 'United States', 'adam jahn'),
	('Adam Jahn', 'United States', 'jahn'),
	('Lars Lokotsch', 'Germany', 'lokotsch'),
	('Lars Lokotsch', 'Germany', 'lars lokotsch'),
	('Magnus Lekven', 'Norway', 'lekven'),
	('Magnus Lekven', 'Norway', 'magnus lekven'),
	('Ariel Lassiter', 'Costa Rica', 'ariel lassiter'),
	('Ariel Lassiter', 'Costa Rica', 'lassiter'),
	('Berkay Dabanlı', 'Germany', 'berkay dabanl'),
	('Berkay Dabanlı', 'Germany', 'dabanl'),
	('Mamadou Coulibaly', 'Senegal', 'coulibaly'),
	('Mamadou Coulibaly', 'Senegal', 'mamadou coulibaly'),
	('Facundo García', 'Argentina', 'garcia'),
	('Facundo García', 'Argentina', 'facundo garcia'),
	('Miłosz Szczepański', 'Poland', 'miosz szczepanski'),
	('Miłosz Szczepański', 'Poland', 'szczepanski'),
	('Dionicio Escalante', 'Mexico', 'dionicio escalante'),
	('Dionicio Escalante', 'Mexico', 'escalante'),
	('Gastón Comas', 'Argentina', 'gaston comas'),
	('Gastón Comas', 'Argentina', 'comas'),
	('Felipe López', 'Mexico', 'lopez'),
	('Felipe López', 'Mexico', 'felipe lopez'),
	('Jerry Yates', 'England', 'jerry yates'),
	('Jerry Yates', 'England', 'yates'),
	('Callum Brittain', 'England', 'callum brittain'),
	('Callum Brittain', 'England', 'brittain'),
	('Thore Jacobsen', 'Germany', 'thore jacobsen'),
	('Thore Jacobsen', 'Germany', 'jacobsen'),
	('Christian Schneuwly', 'Switzerland', 'christian schneuwly'),
	('Christian Schneuwly', 'Switzerland', 'schneuwly'),
	('Richard Celis', 'Venezuela', 'celis'),
	('Richard Celis', 'Venezuela', 'richard celis'),
	('Fanol Përdedaj', 'Kosovo', 'fanol perdedaj'),
	('Fanol Përdedaj', 'Kosovo', 'perdedaj'),
	('Chema Núñez', 'Spain', 'nunez'),
	('Chema Núñez', 'Spain', 'chema nunez'),
	('Florian Chabrolle', 'France', 'chabrolle'),
	('Florian Chabrolle', 'France', 'florian chabrolle'),
	('Rachid Bouhenna', 'Algeria', 'rachid bouhenna'),
	('Rachid Bouhenna', 'Algeria', 'bouhenna'),
	('Jonathan Obika', 'England', 'obika'),
	('Jonathan Obika', 'England', 'jonathan obika'),
	('Lasse Fosgaard', 'Denmark', 'lasse fosgaard'),
	('Lasse Fosgaard', 'Denmark', 'fosgaard'),
	('Christopher Missilou', 'Congo', 'missilou'),
	('Christopher Missilou', 'Congo', 'christopher missilou'),
	('Marcos López', 'Peru', 'lopez'),
	('Marcos López', 'Peru', 'marcos lopez'),
	('Carlos Núñez', 'Uruguay', 'nunez'),
	('Carlos Núñez', 'Uruguay', 'carlos nunez'),
	('Juanma Bravo', 'Spain', 'bravo'),
	('Juanma Bravo', 'Spain', 'juanma bravo'),
	('Aiyegun Tosin', 'Nigeria', 'aiyegun tosin'),
	('Aiyegun Tosin', 'Nigeria', 'tosin'),
	('Song Ju Hun', 'Korea Republic', 'song ju hun'),
	('Song Ju Hun', 'Korea Republic', 'hun'),
	('Thijmen Nijhuis', 'Netherlands', 'nijhuis'),
	('Thijmen Nijhuis', 'Netherlands', 'thijmen nijhuis'),
	('Tony Craig', 'England', 'tony craig'),
	('Tony Craig', 'England', 'craig'),
	('Alexi Gómez', 'Peru', 'gomez'),
	('Alexi Gómez', 'Peru', 'alexi gomez'),
	('Rami Kaib', 'Sweden', 'kaib'),
	('Rami Kaib', 'Sweden', 'rami kaib'),
	('David Edwards', 'Wales', 'edwards'),
	('David Edwards', 'Wales', 'david edwards'),
	('Roy Beerens', 'Netherlands', 'roy beerens'),
	('Roy Beerens', 'Netherlands', 'beerens'),
	('Saeed Al Rubaie', 'Saudi Arabia', 'saeed al rubaie'),
	('Saeed Al Rubaie', 'Saudi Arabia', 'rubaie'),
	('Ovidiu Bic', 'Romania', 'ovidiu bic'),
	('Ovidiu Bic', 'Romania', 'bic'),
	('Juan Cruz Mascia', 'Uruguay', 'mascia'),
	('Juan Cruz Mascia', 'Uruguay', 'juan cruz mascia'),
	('George Merloi', 'Romania', 'george merloi'),
	('George Merloi', 'Romania', 'merloi'),
	('Uche Ikpeazu', 'Uganda', 'uche ikpeazu'),
	('Uche Ikpeazu', 'Uganda', 'ikpeazu'),
	('Trevor Clarke', 'Republic of Ireland', 'clarke'),
	('Trevor Clarke', 'Republic of Ireland', 'trevor clarke'),
	('Lilian Brassier', 'France', 'lilian brassier'),
	('Lilian Brassier', 'France', 'brassier'),
	('Regalón', 'Spain', 'regalon'),
	('Joey O''Brien', 'Republic of Ireland', 'joey obrien'),
	('Joey O''Brien', 'Republic of Ireland', 'obrien'),
	('Joel Sánchez', 'Peru', 'joel sanchez'),
	('Joel Sánchez', 'Peru', 'sanchez'),
	('Luke Prosser', 'England', 'luke prosser'),
	('Luke Prosser', 'England', 'prosser'),
	('Marc Endres', 'Germany', 'endres'),
	('Marc Endres', 'Germany', 'marc endres'),
	('Bai Jiajun', 'China PR', 'bai jiajun'),
	('Bai Jiajun', 'China PR', 'jiajun'),
	('Rémy Boissier', 'France', 'boissier'),
	('Rémy Boissier', 'France', 'remy boissier'),
	('Lee Jin Hyun', 'Korea Republic', 'lee jin hyun'),
	('Lee Jin Hyun', 'Korea Republic', 'hyun'),
	('Yunus Musah', 'England', 'musah'),
	('Yunus Musah', 'England', 'yunus musah'),
	('Emil Jonassen', 'Norway', 'jonassen'),
	('Emil Jonassen', 'Norway', 'emil jonassen'),
	('Samy Benchama', 'France', 'benchama'),
	('Samy Benchama', 'France', 'samy benchama'),
	('Dame Diop', 'Senegal', 'diop'),
	('Dame Diop', 'Senegal', 'dame diop'),
	('Hirofumi Watanabe', 'Japan', 'watanabe'),
	('Hirofumi Watanabe', 'Japan', 'hirofumi watanabe'),
	('Samuel Mensiro', 'Ghana', 'samuel mensiro'),
	('Samuel Mensiro', 'Ghana', 'mensiro'),
	('Florin Iacob', 'Romania', 'iacob'),
	('Florin Iacob', 'Romania', 'florin iacob'),
	('Jeppe Simonsen', 'Denmark', 'jeppe simonsen'),
	('Jeppe Simonsen', 'Denmark', 'simonsen'),
	('Carlos Alves', 'Portugal', 'alves'),
	('Carlos Alves', 'Portugal', 'carlos alves'),
	('Kyle Dempsey', 'England', 'kyle dempsey'),
	('Kyle Dempsey', 'England', 'dempsey'),
	('Louis Fenton', 'New Zealand', 'louis fenton'),
	('Louis Fenton', 'New Zealand', 'fenton'),
	('Piotr Malarczyk', 'Poland', 'piotr malarczyk'),
	('Piotr Malarczyk', 'Poland', 'malarczyk'),
	('Orlando Gaona Lugo', 'Paraguay', 'lugo'),
	('Orlando Gaona Lugo', 'Paraguay', 'orlando gaona lugo'),
	('Vegard Bergan', 'Norway', 'vegard bergan'),
	('Vegard Bergan', 'Norway', 'bergan'),
	('Ben Kantarovski', 'Australia', 'ben kantarovski'),
	('Ben Kantarovski', 'Australia', 'kantarovski'),
	('Marco Holz', 'Germany', 'marco holz'),
	('Marco Holz', 'Germany', 'holz'),
	('Marko Roginić', 'Croatia', 'marko roginic'),
	('Marko Roginić', 'Croatia', 'roginic'),
	('Caolan Lavery', 'Northern Ireland', 'lavery'),
	('Caolan Lavery', 'Northern Ireland', 'caolan lavery'),
	('Kaan Kurt', 'Germany', 'kurt'),
	('Kaan Kurt', 'Germany', 'kaan kurt'),
	('Yoshiki Takahashi', 'Japan', 'yoshiki takahashi'),
	('Yoshiki Takahashi', 'Japan', 'takahashi'),
	('Fabian de Keijzer', 'Netherlands', 'fabian de keijzer'),
	('Fabian de Keijzer', 'Netherlands', 'keijzer'),
	('Eris Abedini', 'Kosovo', 'eris abedini'),
	('Eris Abedini', 'Kosovo', 'abedini'),
	('André Dej', 'Poland', 'dej'),
	('André Dej', 'Poland', 'andre dej'),
	('Juan Manuel Gutiérrez', 'Uruguay', 'gutierrez'),
	('Juan Manuel Gutiérrez', 'Uruguay', 'juan manuel gutierrez'),
	('Konrad de la Fuente', 'United States', 'konrad de la fuente'),
	('Konrad de la Fuente', 'United States', 'fuente'),
	('Oğuz Yılmaz', 'Turkey', 'ylmaz'),
	('Oğuz Yılmaz', 'Turkey', 'oguz ylmaz'),
	('Nahuel Banegas', 'Argentina', 'banegas'),
	('Nahuel Banegas', 'Argentina', 'nahuel banegas'),
	('Bünyamin Balcı', 'Turkey', 'bunyamin balc'),
	('Bünyamin Balcı', 'Turkey', 'balc'),
	('Ammar Helac', 'Austria', 'helac'),
	('Ammar Helac', 'Austria', 'ammar helac'),
	('Edu Espiau', 'Spain', 'edu espiau'),
	('Edu Espiau', 'Spain', 'espiau'),
	('Stefanos Evangelou', 'Greece', 'stefanos evangelou'),
	('Stefanos Evangelou', 'Greece', 'evangelou'),
	('Ramón ten Hove', 'Netherlands', 'hove'),
	('Ramón ten Hove', 'Netherlands', 'ramon ten hove'),
	('Aaron Hayden', 'England', 'hayden'),
	('Aaron Hayden', 'England', 'aaron hayden'),
	('Alhaji Gero', 'Nigeria', 'gero'),
	('Alhaji Gero', 'Nigeria', 'alhaji gero'),
	('Hugo Vandermersch', 'France', 'vandermersch'),
	('Hugo Vandermersch', 'France', 'hugo vandermersch'),
	('Umaru Bangura', 'Sierra Leone', 'bangura'),
	('Umaru Bangura', 'Sierra Leone', 'umaru bangura'),
	('Daniel Maderner', 'Austria', 'daniel maderner'),
	('Daniel Maderner', 'Austria', 'maderner'),
	('Joe Mason', 'Republic of Ireland', 'mason'),
	('Joe Mason', 'Republic of Ireland', 'joe mason'),
	('Marcel Canadi', 'Austria', 'marcel canadi'),
	('Marcel Canadi', 'Austria', 'canadi'),
	('Eddie Nolan', 'Republic of Ireland', 'eddie nolan'),
	('Eddie Nolan', 'Republic of Ireland', 'nolan'),
	('Mike Jones', 'England', 'jones'),
	('Mike Jones', 'England', 'mike jones'),
	('Frank Nouble', 'England', 'nouble'),
	('Frank Nouble', 'England', 'frank nouble'),
	('Joaquin García', 'Argentina', 'garcia'),
	('Joaquin García', 'Argentina', 'joaquin garcia'),
	('Bernd Gschweidl', 'Austria', 'bernd gschweidl'),
	('Bernd Gschweidl', 'Austria', 'gschweidl'),
	('Erik Hurtado', 'United States', 'hurtado'),
	('Erik Hurtado', 'United States', 'erik hurtado'),
	('Johan Hammar', 'Sweden', 'hammar'),
	('Johan Hammar', 'Sweden', 'johan hammar'),
	('Lucas Brochero', 'Argentina', 'brochero'),
	('Lucas Brochero', 'Argentina', 'lucas brochero'),
	('Sphephelo Sithole', 'South Africa', 'sphephelo sithole'),
	('Sphephelo Sithole', 'South Africa', 'sithole'),
	('Luca Netz', 'Germany', 'luca netz'),
	('Luca Netz', 'Germany', 'netz'),
	('Kamil Biliński', 'Poland', 'bilinski'),
	('Kamil Biliński', 'Poland', 'kamil bilinski'),
	('Kyosuke Tagawa', 'Japan', 'kyosuke tagawa'),
	('Kyosuke Tagawa', 'Japan', 'tagawa'),
	('Pape Ndiaga Yade', 'Senegal', 'yade'),
	('Pape Ndiaga Yade', 'Senegal', 'pape ndiaga yade'),
	('Fabrizio Brignani', 'Italy', 'brignani'),
	('Fabrizio Brignani', 'Italy', 'fabrizio brignani'),
	('Marius Mihalache', 'Romania', 'mihalache'),
	('Marius Mihalache', 'Romania', 'marius mihalache'),
	('Albert Stahl', 'Romania', 'stahl'),
	('Albert Stahl', 'Romania', 'albert stahl'),
	('Gabriel Mutombo', 'France', 'gabriel mutombo'),
	('Gabriel Mutombo', 'France', 'mutombo'),
	('Dani Cárdenas', 'Spain', 'dani cardenas'),
	('Dani Cárdenas', 'Spain', 'cardenas'),
	('Cyrill Akono', 'Germany', 'akono'),
	('Cyrill Akono', 'Germany', 'cyrill akono'),
	('Gabriel Matei', 'Romania', 'gabriel matei'),
	('Gabriel Matei', 'Romania', 'matei'),
	('Felix Michel', 'Lebanon', 'felix michel'),
	('Felix Michel', 'Lebanon', 'michel'),
	('Dawid Szymonowicz', 'Poland', 'szymonowicz'),
	('Dawid Szymonowicz', 'Poland', 'dawid szymonowicz'),
	('Ciprian Rus', 'Romania', 'rus'),
	('Ciprian Rus', 'Romania', 'ciprian rus'),
	('François Marquet', 'Belgium', 'marquet'),
	('François Marquet', 'Belgium', 'francois marquet'),
	('Mansour Hamzi', 'Saudi Arabia', 'mansour hamzi'),
	('Mansour Hamzi', 'Saudi Arabia', 'hamzi'),
	('Patrick Schikowski', 'Poland', 'schikowski'),
	('Patrick Schikowski', 'Poland', 'patrick schikowski'),
	('Álex Domínguez', 'Spain', 'dominguez'),
	('Álex Domínguez', 'Spain', 'alex dominguez'),
	('Sergio Benito', 'Spain', 'benito'),
	('Sergio Benito', 'Spain', 'sergio benito'),
	('Yohei Toyoda', 'Japan', 'toyoda'),
	('Yohei Toyoda', 'Japan', 'yohei toyoda'),
	('Steven Vitória', 'Canada', 'vitoria'),
	('Steven Vitória', 'Canada', 'steven vitoria'),
	('Jorge Mier', 'Spain', 'jorge mier'),
	('Jorge Mier', 'Spain', 'mier'),
	('Grant Lillard', 'United States', 'grant lillard'),
	('Grant Lillard', 'United States', 'lillard'),
	('Ayo Simon Okosun', 'Denmark', 'okosun'),
	('Ayo Simon Okosun', 'Denmark', 'ayo simon okosun'),
	('Liao Junjian', 'China PR', 'liao junjian'),
	('Liao Junjian', 'China PR', 'junjian'),
	('Oh Beom Seok', 'Korea Republic', 'seok'),
	('Oh Beom Seok', 'Korea Republic', 'oh beom seok'),
	('Darío Sarmiento', 'Argentina', 'dario sarmiento'),
	('Darío Sarmiento', 'Argentina', 'sarmiento'),
	('Mariusz Malec', 'Poland', 'malec'),
	('Mariusz Malec', 'Poland', 'mariusz malec'),
	('Niall Canavan', 'Republic of Ireland', 'niall canavan'),
	('Niall Canavan', 'Republic of Ireland', 'canavan'),
	('Callum Morton', 'England', 'callum morton'),
	('Callum Morton', 'England', 'morton'),
	('Arthur Silva', 'Brazil', 'arthur silva'),
	('Arthur Silva', 'Brazil', 'silva'),
	('Ulises Abreliano', 'Argentina', 'ulises abreliano'),
	('Ulises Abreliano', 'Argentina', 'abreliano'),
	('Ballou Tabla', 'Canada', 'ballou tabla'),
	('Ballou Tabla', 'Canada', 'tabla'),
	('Luke Leahy', 'England', 'leahy'),
	('Luke Leahy', 'England', 'luke leahy'),
	('Ramón Enríquez', 'Spain', 'enriquez'),
	('Ramón Enríquez', 'Spain', 'ramon enriquez'),
	('Fahad Hadid', 'United Arab Emirates', 'hadid'),
	('Fahad Hadid', 'United Arab Emirates', 'fahad hadid'),
	('Nikola Kuveljić', 'Serbia', 'kuveljic'),
	('Nikola Kuveljić', 'Serbia', 'nikola kuveljic'),
	('Yang Hyung Mo', 'Korea Republic', 'mo'),
	('Yang Hyung Mo', 'Korea Republic', 'yang hyung mo'),
	('Marcus Maier', 'Austria', 'marcus maier'),
	('Marcus Maier', 'Austria', 'maier'),
	('Regan Poole', 'Wales', 'poole'),
	('Regan Poole', 'Wales', 'regan poole'),
	('Lucas Schoofs', 'Belgium', 'schoofs'),
	('Lucas Schoofs', 'Belgium', 'lucas schoofs'),
	('Luís Silva', 'Portugal', 'silva'),
	('Luís Silva', 'Portugal', 'luis silva'),
	('Mehmet Erdem Uğurlu', 'Turkey', 'mehmet erdem ugurlu'),
	('Mehmet Erdem Uğurlu', 'Turkey', 'ugurlu'),
	('Dylan Wenzel-Halls', 'Australia', 'dylan wenzelhalls'),
	('Dylan Wenzel-Halls', 'Australia', 'wenzelhalls'),
	('Daryl Dike', 'United States', 'daryl dike'),
	('Daryl Dike', 'United States', 'dike'),
	('Diego González', 'Mexico', 'diego gonzalez'),
	('Diego González', 'Mexico', 'gonzalez'),
	('Hugo Rama', 'Spain', 'hugo rama'),
	('Hugo Rama', 'Spain', 'rama'),
	('Kevin Luckassen', 'Netherlands', 'kevin luckassen'),
	('Kevin Luckassen', 'Netherlands', 'luckassen'),
	('Jairsinho González', 'Peru', 'jairsinho gonzalez'),
	('Jairsinho González', 'Peru', 'gonzalez'),
	('Slobodan Tedić', 'Serbia', 'tedic'),
	('Slobodan Tedić', 'Serbia', 'slobodan tedic'),
	('Luka Štor', 'Slovenia', 'stor'),
	('Luka Štor', 'Slovenia', 'luka stor'),
	('Pelayo Morilla', 'Spain', 'morilla'),
	('Pelayo Morilla', 'Spain', 'pelayo morilla'),
	('Menno Koch', 'Netherlands', 'koch'),
	('Menno Koch', 'Netherlands', 'menno koch'),
	('Alexander Schmidt', 'Austria', 'schmidt'),
	('Alexander Schmidt', 'Austria', 'alexander schmidt'),
	('Ryota Hayasaka', 'Japan', 'ryota hayasaka'),
	('Ryota Hayasaka', 'Japan', 'hayasaka'),
	('Raffaele De Vita', 'Italy', 'vita'),
	('Raffaele De Vita', 'Italy', 'raffaele de vita'),
	('Luke Varney', 'England', 'luke varney'),
	('Luke Varney', 'England', 'varney'),
	('Joackim Jørgensen', 'Norway', 'jrgensen'),
	('Joackim Jørgensen', 'Norway', 'joackim jrgensen'),
	('Marius Tomozei', 'Romania', 'marius tomozei'),
	('Marius Tomozei', 'Romania', 'tomozei'),
	('Alfredo', 'Spain', 'alfredo'),
	('Kewin', 'Brazil', 'kewin'),
	('Iñaki Astiz', 'Spain', 'astiz'),
	('Iñaki Astiz', 'Spain', 'inaki astiz'),
	('Hólguer Matamoros', 'Ecuador', 'matamoros'),
	('Hólguer Matamoros', 'Ecuador', 'holguer matamoros'),
	('Wang Wei', 'China PR', 'wang wei'),
	('Wang Wei', 'China PR', 'wei'),
	('Prince Osei Owusu', 'Germany', 'owusu'),
	('Prince Osei Owusu', 'Germany', 'prince osei owusu'),
	('Lamine Diabyfadiga', 'France', 'lamine diabyfadiga'),
	('Lamine Diabyfadiga', 'France', 'diabyfadiga'),
	('Carl Piergianni', 'England', 'piergianni'),
	('Carl Piergianni', 'England', 'carl piergianni'),
	('Hendrik Hansen', 'Germany', 'hendrik hansen'),
	('Hendrik Hansen', 'Germany', 'hansen'),
	('Alfie Jones', 'England', 'alfie jones'),
	('Alfie Jones', 'England', 'jones'),
	('George Johnston', 'Scotland', 'george johnston'),
	('George Johnston', 'Scotland', 'johnston'),
	('Víctor Fernández', 'Spain', 'victor fernandez'),
	('Víctor Fernández', 'Spain', 'fernandez'),
	('Jordan Clarke', 'England', 'clarke'),
	('Jordan Clarke', 'England', 'jordan clarke'),
	('Florin Ilie', 'Romania', 'ilie'),
	('Florin Ilie', 'Romania', 'florin ilie'),
	('Nick Gillekens', 'Belgium', 'nick gillekens'),
	('Nick Gillekens', 'Belgium', 'gillekens'),
	('Keiya Shiihashi', 'Japan', 'shiihashi'),
	('Keiya Shiihashi', 'Japan', 'keiya shiihashi'),
	('Svante Ingelsson', 'Sweden', 'ingelsson'),
	('Svante Ingelsson', 'Sweden', 'svante ingelsson'),
	('Rui Pires', 'Portugal', 'pires'),
	('Rui Pires', 'Portugal', 'rui pires'),
	('Djibril Dianessy', 'France', 'djibril dianessy'),
	('Djibril Dianessy', 'France', 'dianessy'),
	('Marcos Enrique', 'Argentina', 'marcos enrique'),
	('Marcos Enrique', 'Argentina', 'enrique'),
	('Isaac Vassell', 'England', 'vassell'),
	('Isaac Vassell', 'England', 'isaac vassell'),
	('Ryo Shinzato', 'Japan', 'ryo shinzato'),
	('Ryo Shinzato', 'Japan', 'shinzato'),
	('Stefan Mauk', 'Australia', 'stefan mauk'),
	('Stefan Mauk', 'Australia', 'mauk'),
	('Billy McKay', 'Northern Ireland', 'billy mckay'),
	('Billy McKay', 'Northern Ireland', 'mckay'),
	('Soma Novothny', 'Hungary', 'soma novothny'),
	('Soma Novothny', 'Hungary', 'novothny'),
	('Renzo Tesuri', 'Argentina', 'renzo tesuri'),
	('Renzo Tesuri', 'Argentina', 'tesuri'),
	('John Akinde', 'England', 'john akinde'),
	('John Akinde', 'England', 'akinde'),
	('Justin Dhillon', 'United States', 'justin dhillon'),
	('Justin Dhillon', 'United States', 'dhillon')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';