INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Adolfo Muñoz', 'Ecuador', 'player'),
	('Miguel Ibarra', 'United States', 'player'),
	('William Togui', 'Ivory Coast', 'player'),
	('Crislan', 'Brazil', 'player'),
	('Gabriel Costa', 'Peru', 'player'),
	('Temma Matsuda', 'Japan', 'player'),
	('Leonardo Lopes', 'Portugal', 'player'),
	('Josh Onomah', 'England', 'player'),
	('Alejandro Meleán', 'Bolivia', 'player'),
	('José Quintero', 'Ecuador', 'player'),
	('Francis Mac Allister', 'Argentina', 'player'),
	('Viljar Vevatne', 'Norway', 'player'),
	('Fraizer Campbell', 'England', 'player'),
	('Jukka Raitala', 'Finland', 'player'),
	('Vitaliy Lystsov', 'Russia', 'player'),
	('Jonatan Álvez', 'Uruguay', 'player'),
	('Lucas Áfrico', 'Brazil', 'player'),
	('Junya Tanaka', 'Japan', 'player'),
	('Alex Castro', 'Colombia', 'player'),
	('Quentin Lecoeuche', 'France', 'player'),
	('Jaume Grau', 'Spain', 'player'),
	('Gu Chao', 'China PR', 'player'),
	('Charlie Goode', 'England', 'player'),
	('Ramiro Ballivián', 'Bolivia', 'player'),
	('Carlos Ross', 'Chile', 'player'),
	('Anders Lindegaard', 'Denmark', 'player'),
	('Vurnon Anita', 'Netherlands', 'player'),
	('Alexander Ludwig', 'Denmark', 'player'),
	('Kevin Fickentscher', 'Switzerland', 'player'),
	('Carlos Neumann', 'Paraguay', 'player'),
	('Maximilian Sauer', 'Germany', 'player'),
	('Claudio Sepúlveda', 'Chile', 'player'),
	('Iván Ochoa', 'Mexico', 'player'),
	('Tim Breukers', 'Netherlands', 'player'),
	('Yann-Erik de Lanlay', 'Norway', 'player'),
	('Miguel Herrera', 'Mexico', 'player'),
	('Mauricio Caranta', 'Argentina', 'player'),
	('George Boyd', 'Scotland', 'player'),
	('Mathias Wittek', 'Germany', 'player'),
	('Alex Gorrín', 'Spain', 'player'),
	('Loris Brogno', 'Belgium', 'player'),
	('Ewoud Pletinckx', 'Belgium', 'player'),
	('Cristian Arango', 'Colombia', 'player'),
	('Miquel Parera', 'Spain', 'player'),
	('Jordan Smith', 'England', 'player'),
	('Maximiliano Lugo', 'Paraguay', 'player'),
	('Ramon Pascal Lundqvist', 'Sweden', 'player'),
	('Marco Thiede', 'Germany', 'player'),
	('Anthony Stewart', 'England', 'player'),
	('Zakaria Diallo', 'France', 'player'),
	('Oleksandr Andrievskyi', 'Ukraine', 'player'),
	('Feiver Mercado', 'Colombia', 'player'),
	('Dejan Kerkez', 'Serbia', 'player'),
	('Tomáš Petrášek', 'Czech Republic', 'player'),
	('Miquel Nelom', 'Netherlands', 'player'),
	('Kai Eisele', 'Germany', 'player'),
	('Nils Seufert', 'Germany', 'player'),
	('Felipe Araruna', 'Brazil', 'player'),
	('Nicolás Maturana', 'Chile', 'player'),
	('Matteo Lovato', 'Italy', 'player'),
	('Chuks Aneke', 'England', 'player'),
	('Caniggia Elva', 'Canada', 'player'),
	('Felix Luckeneder', 'Austria', 'player'),
	('Mallik Wilks', 'England', 'player'),
	('Shi Ke', 'China PR', 'player'),
	('Bjørn Paulsen', 'Denmark', 'player'),
	('Laurent Henkinet', 'Belgium', 'player'),
	('Fernando Fernández', 'Paraguay', 'player'),
	('Andrija Pavlović', 'Serbia', 'player'),
	('Matheus Rossetto', 'Brazil', 'player'),
	('Shinya Yajima', 'Japan', 'player'),
	('Ben Motshwari', 'South Africa', 'player'),
	('Dai Lin', 'China PR', 'player'),
	('Patrick Hoban', 'Republic of Ireland', 'player'),
	('Leon Clarke', 'England', 'player'),
	('Jeffry Fortes', 'Cape Verde', 'player'),
	('Kazuki Kozuka', 'Japan', 'player'),
	('Giuseppe Mastinu', 'Italy', 'player'),
	('Rui Correia', 'Portugal', 'player'),
	('Markus Ballmert', 'Germany', 'player'),
	('Frédéric Brillant', 'France', 'player'),
	('Oh Ban Suk', 'Korea Republic', 'player'),
	('Ko Matsubara', 'Japan', 'player'),
	('Gaëtan Coucke', 'Belgium', 'player'),
	('Luca Orellano', 'Argentina', 'player'),
	('Robert Herrmann', 'Germany', 'player'),
	('Juan Daniel Roa', 'Colombia', 'player'),
	('Ricardo Mangas', 'Portugal', 'player'),
	('Jimmy Dunne', 'Republic of Ireland', 'player'),
	('Frederik Tingager', 'Denmark', 'player'),
	('Luke O''Nien', 'England', 'player'),
	('Deni Alar', 'Austria', 'player'),
	('Jann George', 'Germany', 'player'),
	('Jeff Attinella', 'United States', 'player'),
	('Maximilian Beister', 'Germany', 'player'),
	('Petr Schwarz', 'Czech Republic', 'player'),
	('Philipp Hosiner', 'Austria', 'player'),
	('Burak Süleyman', 'Turkey', 'player'),
	('Oriol Busquets', 'Spain', 'player'),
	('Matías Pellegrini', 'Argentina', 'player'),
	('Marcello Gazzola', 'Italy', 'player'),
	('Christian Schwegler', 'Switzerland', 'player'),
	('Andy Polo', 'Peru', 'player'),
	('Hiroki Fujiharu', 'Japan', 'player'),
	('Hugo Martínez', 'Paraguay', 'player'),
	('Toshiyuki Takagi', 'Japan', 'player'),
	('Mo Eisa', 'Sudan', 'player'),
	('Andreaw Gravillon', 'France', 'player'),
	('Callum O''Hare', 'England', 'player'),
	('Ryan Hedges', 'Wales', 'player'),
	('Glenn Whelan', 'Republic of Ireland', 'player'),
	('Kenyu Sugimoto', 'Japan', 'player'),
	('Joe Edwards', 'England', 'player'),
	('Oleksiy Dytyatev', 'Ukraine', 'player'),
	('Joseph Lopy', 'Senegal', 'player'),
	('Sam Gallagher', 'England', 'player'),
	('Bruno Andrade', 'Portugal', 'player'),
	('Buatu', 'Angola', 'player'),
	('Tommaso Pobega', 'Italy', 'player'),
	('Sofiane Diop', 'France', 'player'),
	('Li Shuai', 'China PR', 'player'),
	('Ola Brynhildsen', 'Norway', 'player'),
	('Joe Abrigo', 'Chile', 'player'),
	('Abdul Mumin', 'Ghana', 'player'),
	('Adrien Monfray', 'France', 'player'),
	('Yoël Armougom', 'France', 'player'),
	('Jamie Allen', 'England', 'player'),
	('Kengo Kitazume', 'Japan', 'player'),
	('Giorgi Aburjania', 'Georgia', 'player'),
	('Lawrence Shankland', 'Scotland', 'player'),
	('Josh Earl', 'England', 'player'),
	('Danny Andrew', 'England', 'player'),
	('Salim Khelifi', 'Tunisia', 'player'),
	('Chris Cadden', 'Scotland', 'player'),
	('David Mitov Nilsson', 'North Macedonia', 'player'),
	('Julien Fabri', 'France', 'player'),
	('Clavería', 'Spain', 'player'),
	('Agustín Oliveros', 'Uruguay', 'player'),
	('Marko Ilic', 'Serbia', 'player'),
	('Maryan Shved', 'Ukraine', 'player'),
	('Josep Señé', 'Spain', 'player'),
	('Maurice Multhaup', 'Germany', 'player'),
	('Antonio Romero', 'Spain', 'player'),
	('Jefferson', 'Brazil', 'player'),
	('Felix Beijmo', 'Sweden', 'player'),
	('Christophe Lepoint', 'Belgium', 'player'),
	('Bruce Bvuma', 'South Africa', 'player'),
	('Tyrese Campbell', 'England', 'player'),
	('Johan Martial', 'France', 'player'),
	('Gastón Olveira', 'Uruguay', 'player'),
	('Agustín González', 'Uruguay', 'player'),
	('Derrick Jones', 'United States', 'player'),
	('Niklas Castro', 'Chile', 'player'),
	('Akim Zedadka', 'France', 'player'),
	('Sheldon Bateau', 'Trinidad & Tobago', 'player'),
	('Ulises Cardona', 'Mexico', 'player'),
	('Mario Maloča', 'Croatia', 'player'),
	('Agustín Almendra', 'Argentina', 'player'),
	('Horacio Tijanovich', 'Argentina', 'player'),
	('Perry Ng', 'England', 'player'),
	('Chris Maguire', 'Scotland', 'player'),
	('Gakuto Notsuda', 'Japan', 'player'),
	('Federico Bonazzoli', 'Italy', 'player'),
	('Hussain Al Moqahwi', 'Saudi Arabia', 'player'),
	('Kemal Ademi', 'Switzerland', 'player'),
	('Niko Hämäläinen', 'Finland', 'player'),
	('David Ramírez', 'Mexico', 'player'),
	('Sebastian Ernst', 'Germany', 'player'),
	('Andrea Favilli', 'Italy', 'player'),
	('Dávid Ivan', 'Slovakia', 'player'),
	('Alberto Contrera', 'Paraguay', 'player'),
	('Franco Russo', 'Argentina', 'player'),
	('Marius Martac', 'Romania', 'player'),
	('Jason Steele', 'England', 'player'),
	('Nicolás Rodríguez', 'Uruguay', 'player'),
	('Alexander Jeremejeff', 'Sweden', 'player'),
	('James Norwood', 'England', 'player'),
	('Adri Cuevas', 'Spain', 'player'),
	('Naomichi Ueda', 'Japan', 'player'),
	('Raymon Gaddis', 'United States', 'player'),
	('Dani Romera', 'Spain', 'player'),
	('Rafik Zekhnini', 'Norway', 'player'),
	('James Troisi', 'Australia', 'player'),
	('Andreas Lienhart', 'Austria', 'player'),
	('Yushi Hasegawa', 'Japan', 'player'),
	('Zhang Chengdong', 'China PR', 'player'),
	('Johan Kappelhof', 'Netherlands', 'player'),
	('Thomas Ebner', 'Austria', 'player'),
	('Rei Matsumoto', 'Japan', 'player'),
	('Jack Rodwell', 'England', 'player'),
	('Agustín Rogel', 'Uruguay', 'player'),
	('Hernán Galíndez', 'Argentina', 'player'),
	('Gary Correa', 'Peru', 'player'),
	('Stefan Thesker', 'Germany', 'player'),
	('Dylan Bahamboula', 'Congo', 'player'),
	('Harisson Marcelin', 'France', 'player'),
	('Kosei Shibasaki', 'Japan', 'player'),
	('Samba Camara', 'France', 'player'),
	('Chris Martin', 'Scotland', 'player'),
	('Paul Coutts', 'Scotland', 'player'),
	('Ben Purrington', 'England', 'player'),
	('Frederic Ananou', 'Germany', 'player'),
	('Alfonso Luna', 'Mexico', 'player'),
	('Kazuaki Mawatari', 'Japan', 'player'),
	('Linus Wahlqvist', 'Sweden', 'player'),
	('Kik Pierie', 'Netherlands', 'player'),
	('Pichu Atienza', 'Spain', 'player'),
	('Shun Nagasawa', 'Japan', 'player'),
	('Jorge Fellipe', 'Brazil', 'player'),
	('Kazuki Fukai', 'Japan', 'player'),
	('Adil Aouchiche', 'France', 'player'),
	('Roberto Ramírez', 'Argentina', 'player'),
	('Víctor Dávila', 'Chile', 'player'),
	('Manu Fuster', 'Spain', 'player'),
	('Wang Gang', 'China PR', 'player'),
	('Carlo Holse', 'Denmark', 'player'),
	('Etienne Amenyido', 'Germany', 'player'),
	('Alessandro Tuia', 'Italy', 'player'),
	('Kazunari Ichimi', 'Japan', 'player'),
	('Jorge Arias', 'Colombia', 'player'),
	('Sauli Väisänen', 'Finland', 'player'),
	('Tom Weilandt', 'Germany', 'player'),
	('Yukiya Sugita', 'Japan', 'player'),
	('Takuma Arano', 'Japan', 'player'),
	('Keanu Staude', 'Germany', 'player'),
	('Jordan Silva', 'Mexico', 'player'),
	('Tobias Sana', 'Sweden', 'player'),
	('Campabadal', 'Spain', 'player'),
	('Funso Ojo', 'Belgium', 'player'),
	('Albert Bunjaku', 'Kosovo', 'player'),
	('Jalil Anibaba', 'United States', 'player'),
	('Federico Pérez', 'Uruguay', 'player'),
	('Jeison Chalá', 'Ecuador', 'player'),
	('Christos Tzolis', 'Greece', 'player'),
	('Danny Wilson', 'Scotland', 'player'),
	('Chris Maxwell', 'Wales', 'player'),
	('Leonel López', 'Mexico', 'player'),
	('Julien Dacosta', 'France', 'player'),
	('Bram Castro', 'Belgium', 'player'),
	('Pablo Trigueros', 'Spain', 'player'),
	('Juan Carlos Espinoza', 'Chile', 'player'),
	('Danny Fox', 'Scotland', 'player'),
	('Mike Wunderlich', 'Germany', 'player'),
	('Liam Grimshaw', 'England', 'player'),
	('Carlos Sierra', 'Colombia', 'player'),
	('Carlos Ruiz', 'Spain', 'player'),
	('Rémy Descamps', 'France', 'player'),
	('Simon Olsson', 'Sweden', 'player'),
	('Drew Moor', 'United States', 'player'),
	('Diego Garcia', 'Uruguay', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Adolfo Muñoz', 'Ecuador', 'adolfo munoz'),
	('Adolfo Muñoz', 'Ecuador', 'munoz'),
	('Miguel Ibarra', 'United States', 'ibarra'),
	('Miguel Ibarra', 'United States', 'miguel ibarra'),
	('William Togui', 'Ivory Coast', 'togui'),
	('William Togui', 'Ivory Coast', 'william togui'),
	('Crislan', 'Brazil', 'crislan'),
	('Gabriel Costa', 'Peru', 'gabriel costa'),
	('Gabriel Costa', 'Peru', 'costa'),
	('Temma Matsuda', 'Japan', 'matsuda'),
	('Temma Matsuda', 'Japan', 'temma matsuda'),
	('Leonardo Lopes', 'Portugal', 'leonardo lopes'),
	('Leonardo Lopes', 'Portugal', 'lopes'),
	('Josh Onomah', 'England', 'onomah'),
	('Josh Onomah', 'England', 'josh onomah'),
	('Alejandro Meleán', 'Bolivia', 'alejandro melean'),
	('Alejandro Meleán', 'Bolivia', 'melean'),
	('José Quintero', 'Ecuador', 'quintero'),
	('José Quintero', 'Ecuador', 'jose quintero'),
	('Francis Mac Allister', 'Argentina', 'allister'),
	('Francis Mac Allister', 'Argentina', 'francis mac allister'),
	('Viljar Vevatne', 'Norway', 'viljar vevatne'),
	('Viljar Vevatne', 'Norway', 'vevatne'),
	('Fraizer Campbell', 'England', 'campbell'),
	('Fraizer Campbell', 'England', 'fraizer campbell'),
	('Jukka Raitala', 'Finland', 'jukka raitala'),
	('Jukka Raitala', 'Finland', 'raitala'),
	('Vitaliy Lystsov', 'Russia', 'vitaliy lystsov'),
	('Vitaliy Lystsov', 'Russia', 'lystsov'),
	('Jonatan Álvez', 'Uruguay', 'jonatan alvez'),
	('Jonatan Álvez', 'Uruguay', 'alvez'),
	('Lucas Áfrico', 'Brazil', 'africo'),
	('Lucas Áfrico', 'Brazil', 'lucas africo'),
	('Junya Tanaka', 'Japan', 'junya tanaka'),
	('Junya Tanaka', 'Japan', 'tanaka'),
	('Alex Castro', 'Colombia', 'castro'),
	('Alex Castro', 'Colombia', 'alex castro'),
	('Quentin Lecoeuche', 'France', 'lecoeuche'),
	('Quentin Lecoeuche', 'France', 'quentin lecoeuche'),
	('Jaume Grau', 'Spain', 'jaume grau'),
	('Jaume Grau', 'Spain', 'grau'),
	('Gu Chao', 'China PR', 'gu chao'),
	('Gu Chao', 'China PR', 'chao'),
	('Charlie Goode', 'England', 'charlie goode'),
	('Charlie Goode', 'England', 'goode'),
	('Ramiro Ballivián', 'Bolivia', 'ramiro ballivian'),
	('Ramiro Ballivián', 'Bolivia', 'ballivian'),
	('Carlos Ross', 'Chile', 'ross'),
	('Carlos Ross', 'Chile', 'carlos ross'),
	('Anders Lindegaard', 'Denmark', 'anders lindegaard'),
	('Anders Lindegaard', 'Denmark', 'lindegaard'),
	('Vurnon Anita', 'Netherlands', 'anita'),
	('Vurnon Anita', 'Netherlands', 'vurnon anita'),
	('Alexander Ludwig', 'Denmark', 'alexander ludwig'),
	('Alexander Ludwig', 'Denmark', 'ludwig'),
	('Kevin Fickentscher', 'Switzerland', 'kevin fickentscher'),
	('Kevin Fickentscher', 'Switzerland', 'fickentscher'),
	('Carlos Neumann', 'Paraguay', 'carlos neumann'),
	('Carlos Neumann', 'Paraguay', 'neumann'),
	('Maximilian Sauer', 'Germany', 'maximilian sauer'),
	('Maximilian Sauer', 'Germany', 'sauer'),
	('Claudio Sepúlveda', 'Chile', 'claudio sepulveda'),
	('Claudio Sepúlveda', 'Chile', 'sepulveda'),
	('Iván Ochoa', 'Mexico', 'ochoa'),
	('Iván Ochoa', 'Mexico', 'ivan ochoa'),
	('Tim Breukers', 'Netherlands', 'breukers'),
	('Tim Breukers', 'Netherlands', 'tim breukers'),
	('Yann-Erik de Lanlay', 'Norway', 'lanlay'),
	('Yann-Erik de Lanlay', 'Norway', 'yannerik de lanlay'),
	('Miguel Herrera', 'Mexico', 'herrera'),
	('Miguel Herrera', 'Mexico', 'miguel herrera'),
	('Mauricio Caranta', 'Argentina', 'caranta'),
	('Mauricio Caranta', 'Argentina', 'mauricio caranta'),
	('George Boyd', 'Scotland', 'boyd'),
	('George Boyd', 'Scotland', 'george boyd'),
	('Mathias Wittek', 'Germany', 'mathias wittek'),
	('Mathias Wittek', 'Germany', 'wittek'),
	('Alex Gorrín', 'Spain', 'gorrin'),
	('Alex Gorrín', 'Spain', 'alex gorrin'),
	('Loris Brogno', 'Belgium', 'loris brogno'),
	('Loris Brogno', 'Belgium', 'brogno'),
	('Ewoud Pletinckx', 'Belgium', 'pletinckx'),
	('Ewoud Pletinckx', 'Belgium', 'ewoud pletinckx'),
	('Cristian Arango', 'Colombia', 'cristian arango'),
	('Cristian Arango', 'Colombia', 'arango'),
	('Miquel Parera', 'Spain', 'parera'),
	('Miquel Parera', 'Spain', 'miquel parera'),
	('Jordan Smith', 'England', 'smith'),
	('Jordan Smith', 'England', 'jordan smith'),
	('Maximiliano Lugo', 'Paraguay', 'lugo'),
	('Maximiliano Lugo', 'Paraguay', 'maximiliano lugo'),
	('Ramon Pascal Lundqvist', 'Sweden', 'ramon pascal lundqvist'),
	('Ramon Pascal Lundqvist', 'Sweden', 'lundqvist'),
	('Marco Thiede', 'Germany', 'marco thiede'),
	('Marco Thiede', 'Germany', 'thiede'),
	('Anthony Stewart', 'England', 'stewart'),
	('Anthony Stewart', 'England', 'anthony stewart'),
	('Zakaria Diallo', 'France', 'zakaria diallo'),
	('Zakaria Diallo', 'France', 'diallo'),
	('Oleksandr Andrievskyi', 'Ukraine', 'andrievskyi'),
	('Oleksandr Andrievskyi', 'Ukraine', 'oleksandr andrievskyi'),
	('Feiver Mercado', 'Colombia', 'mercado'),
	('Feiver Mercado', 'Colombia', 'feiver mercado'),
	('Dejan Kerkez', 'Serbia', 'kerkez'),
	('Dejan Kerkez', 'Serbia', 'dejan kerkez'),
	('Tomáš Petrášek', 'Czech Republic', 'tomas petrasek'),
	('Tomáš Petrášek', 'Czech Republic', 'petrasek'),
	('Miquel Nelom', 'Netherlands', 'miquel nelom'),
	('Miquel Nelom', 'Netherlands', 'nelom'),
	('Kai Eisele', 'Germany', 'kai eisele'),
	('Kai Eisele', 'Germany', 'eisele'),
	('Nils Seufert', 'Germany', 'nils seufert'),
	('Nils Seufert', 'Germany', 'seufert'),
	('Felipe Araruna', 'Brazil', 'felipe araruna'),
	('Felipe Araruna', 'Brazil', 'araruna'),
	('Nicolás Maturana', 'Chile', 'maturana'),
	('Nicolás Maturana', 'Chile', 'nicolas maturana'),
	('Matteo Lovato', 'Italy', 'lovato'),
	('Matteo Lovato', 'Italy', 'matteo lovato'),
	('Chuks Aneke', 'England', 'chuks aneke'),
	('Chuks Aneke', 'England', 'aneke'),
	('Caniggia Elva', 'Canada', 'caniggia elva'),
	('Caniggia Elva', 'Canada', 'elva'),
	('Felix Luckeneder', 'Austria', 'felix luckeneder'),
	('Felix Luckeneder', 'Austria', 'luckeneder'),
	('Mallik Wilks', 'England', 'mallik wilks'),
	('Mallik Wilks', 'England', 'wilks'),
	('Shi Ke', 'China PR', 'ke'),
	('Shi Ke', 'China PR', 'shi ke'),
	('Bjørn Paulsen', 'Denmark', 'paulsen'),
	('Bjørn Paulsen', 'Denmark', 'bjrn paulsen'),
	('Laurent Henkinet', 'Belgium', 'henkinet'),
	('Laurent Henkinet', 'Belgium', 'laurent henkinet'),
	('Fernando Fernández', 'Paraguay', 'fernandez'),
	('Fernando Fernández', 'Paraguay', 'fernando fernandez'),
	('Andrija Pavlović', 'Serbia', 'andrija pavlovic'),
	('Andrija Pavlović', 'Serbia', 'pavlovic'),
	('Matheus Rossetto', 'Brazil', 'rossetto'),
	('Matheus Rossetto', 'Brazil', 'matheus rossetto'),
	('Shinya Yajima', 'Japan', 'shinya yajima'),
	('Shinya Yajima', 'Japan', 'yajima'),
	('Ben Motshwari', 'South Africa', 'ben motshwari'),
	('Ben Motshwari', 'South Africa', 'motshwari'),
	('Dai Lin', 'China PR', 'dai lin'),
	('Dai Lin', 'China PR', 'lin'),
	('Patrick Hoban', 'Republic of Ireland', 'patrick hoban'),
	('Patrick Hoban', 'Republic of Ireland', 'hoban'),
	('Leon Clarke', 'England', 'clarke'),
	('Leon Clarke', 'England', 'leon clarke'),
	('Jeffry Fortes', 'Cape Verde', 'jeffry fortes'),
	('Jeffry Fortes', 'Cape Verde', 'fortes'),
	('Kazuki Kozuka', 'Japan', 'kozuka'),
	('Kazuki Kozuka', 'Japan', 'kazuki kozuka'),
	('Giuseppe Mastinu', 'Italy', 'mastinu'),
	('Giuseppe Mastinu', 'Italy', 'giuseppe mastinu'),
	('Rui Correia', 'Portugal', 'rui correia'),
	('Rui Correia', 'Portugal', 'correia'),
	('Markus Ballmert', 'Germany', 'markus ballmert'),
	('Markus Ballmert', 'Germany', 'ballmert'),
	('Frédéric Brillant', 'France', 'brillant'),
	('Frédéric Brillant', 'France', 'frederic brillant'),
	('Oh Ban Suk', 'Korea Republic', 'oh ban suk'),
	('Oh Ban Suk', 'Korea Republic', 'suk'),
	('Ko Matsubara', 'Japan', 'ko matsubara'),
	('Ko Matsubara', 'Japan', 'matsubara'),
	('Gaëtan Coucke', 'Belgium', 'coucke'),
	('Gaëtan Coucke', 'Belgium', 'gaetan coucke'),
	('Luca Orellano', 'Argentina', 'luca orellano'),
	('Luca Orellano', 'Argentina', 'orellano'),
	('Robert Herrmann', 'Germany', 'herrmann'),
	('Robert Herrmann', 'Germany', 'robert herrmann'),
	('Juan Daniel Roa', 'Colombia', 'roa'),
	('Juan Daniel Roa', 'Colombia', 'juan daniel roa'),
	('Ricardo Mangas', 'Portugal', 'mangas'),
	('Ricardo Mangas', 'Portugal', 'ricardo mangas'),
	('Jimmy Dunne', 'Republic of Ireland', 'dunne'),
	('Jimmy Dunne', 'Republic of Ireland', 'jimmy dunne'),
	('Frederik Tingager', 'Denmark', 'tingager'),
	('Frederik Tingager', 'Denmark', 'frederik tingager'),
	('Luke O''Nien', 'England', 'luke onien'),
	('Luke O''Nien', 'England', 'onien'),
	('Deni Alar', 'Austria', 'alar'),
	('Deni Alar', 'Austria', 'deni alar'),
	('Jann George', 'Germany', 'george'),
	('Jann George', 'Germany', 'jann george'),
	('Jeff Attinella', 'United States', 'jeff attinella'),
	('Jeff Attinella', 'United States', 'attinella'),
	('Maximilian Beister', 'Germany', 'maximilian beister'),
	('Maximilian Beister', 'Germany', 'beister'),
	('Petr Schwarz', 'Czech Republic', 'schwarz'),
	('Petr Schwarz', 'Czech Republic', 'petr schwarz'),
	('Philipp Hosiner', 'Austria', 'hosiner'),
	('Philipp Hosiner', 'Austria', 'philipp hosiner'),
	('Burak Süleyman', 'Turkey', 'burak suleyman'),
	('Burak Süleyman', 'Turkey', 'suleyman'),
	('Oriol Busquets', 'Spain', 'busquets'),
	('Oriol Busquets', 'Spain', 'oriol busquets'),
	('Matías Pellegrini', 'Argentina', 'pellegrini'),
	('Matías Pellegrini', 'Argentina', 'matias pellegrini'),
	('Marcello Gazzola', 'Italy', 'marcello gazzola'),
	('Marcello Gazzola', 'Italy', 'gazzola'),
	('Christian Schwegler', 'Switzerland', 'schwegler'),
	('Christian Schwegler', 'Switzerland', 'christian schwegler'),
	('Andy Polo', 'Peru', 'polo'),
	('Andy Polo', 'Peru', 'andy polo'),
	('Hiroki Fujiharu', 'Japan', 'hiroki fujiharu'),
	('Hiroki Fujiharu', 'Japan', 'fujiharu'),
	('Hugo Martínez', 'Paraguay', 'martinez'),
	('Hugo Martínez', 'Paraguay', 'hugo martinez'),
	('Toshiyuki Takagi', 'Japan', 'takagi'),
	('Toshiyuki Takagi', 'Japan', 'toshiyuki takagi'),
	('Mo Eisa', 'Sudan', 'mo eisa'),
	('Mo Eisa', 'Sudan', 'eisa'),
	('Andreaw Gravillon', 'France', 'andreaw gravillon'),
	('Andreaw Gravillon', 'France', 'gravillon'),
	('Callum O''Hare', 'England', 'callum ohare'),
	('Callum O''Hare', 'England', 'ohare'),
	('Ryan Hedges', 'Wales', 'ryan hedges'),
	('Ryan Hedges', 'Wales', 'hedges'),
	('Glenn Whelan', 'Republic of Ireland', 'whelan'),
	('Glenn Whelan', 'Republic of Ireland', 'glenn whelan'),
	('Kenyu Sugimoto', 'Japan', 'sugimoto'),
	('Kenyu Sugimoto', 'Japan', 'kenyu sugimoto'),
	('Joe Edwards', 'England', 'joe edwards'),
	('Joe Edwards', 'England', 'edwards'),
	('Oleksiy Dytyatev', 'Ukraine', 'oleksiy dytyatev'),
	('Oleksiy Dytyatev', 'Ukraine', 'dytyatev'),
	('Joseph Lopy', 'Senegal', 'joseph lopy'),
	('Joseph Lopy', 'Senegal', 'lopy'),
	('Sam Gallagher', 'England', 'sam gallagher'),
	('Sam Gallagher', 'England', 'gallagher'),
	('Bruno Andrade', 'Portugal', 'andrade'),
	('Bruno Andrade', 'Portugal', 'bruno andrade'),
	('Buatu', 'Angola', 'buatu'),
	('Tommaso Pobega', 'Italy', 'pobega'),
	('Tommaso Pobega', 'Italy', 'tommaso pobega'),
	('Sofiane Diop', 'France', 'diop'),
	('Sofiane Diop', 'France', 'sofiane diop'),
	('Li Shuai', 'China PR', 'li shuai'),
	('Li Shuai', 'China PR', 'shuai'),
	('Ola Brynhildsen', 'Norway', 'ola brynhildsen'),
	('Ola Brynhildsen', 'Norway', 'brynhildsen'),
	('Joe Abrigo', 'Chile', 'joe abrigo'),
	('Joe Abrigo', 'Chile', 'abrigo'),
	('Abdul Mumin', 'Ghana', 'abdul mumin'),
	('Abdul Mumin', 'Ghana', 'mumin'),
	('Adrien Monfray', 'France', 'monfray'),
	('Adrien Monfray', 'France', 'adrien monfray'),
	('Yoël Armougom', 'France', 'armougom'),
	('Yoël Armougom', 'France', 'yoel armougom'),
	('Jamie Allen', 'England', 'jamie allen'),
	('Jamie Allen', 'England', 'allen'),
	('Kengo Kitazume', 'Japan', 'kitazume'),
	('Kengo Kitazume', 'Japan', 'kengo kitazume'),
	('Giorgi Aburjania', 'Georgia', 'aburjania'),
	('Giorgi Aburjania', 'Georgia', 'giorgi aburjania'),
	('Lawrence Shankland', 'Scotland', 'shankland'),
	('Lawrence Shankland', 'Scotland', 'lawrence shankland'),
	('Josh Earl', 'England', 'josh earl'),
	('Josh Earl', 'England', 'earl'),
	('Danny Andrew', 'England', 'andrew'),
	('Danny Andrew', 'England', 'danny andrew'),
	('Salim Khelifi', 'Tunisia', 'khelifi'),
	('Salim Khelifi', 'Tunisia', 'salim khelifi'),
	('Chris Cadden', 'Scotland', 'cadden'),
	('Chris Cadden', 'Scotland', 'chris cadden'),
	('David Mitov Nilsson', 'North Macedonia', 'david mitov nilsson'),
	('David Mitov Nilsson', 'North Macedonia', 'nilsson'),
	('Julien Fabri', 'France', 'fabri'),
	('Julien Fabri', 'France', 'julien fabri'),
	('Clavería', 'Spain', 'claveria'),
	('Agustín Oliveros', 'Uruguay', 'agustin oliveros'),
	('Agustín Oliveros', 'Uruguay', 'oliveros'),
	('Marko Ilic', 'Serbia', 'ilic'),
	('Marko Ilic', 'Serbia', 'marko ilic'),
	('Maryan Shved', 'Ukraine', 'shved'),
	('Maryan Shved', 'Ukraine', 'maryan shved'),
	('Josep Señé', 'Spain', 'sene'),
	('Josep Señé', 'Spain', 'josep sene'),
	('Maurice Multhaup', 'Germany', 'maurice multhaup'),
	('Maurice Multhaup', 'Germany', 'multhaup'),
	('Antonio Romero', 'Spain', 'antonio romero'),
	('Antonio Romero', 'Spain', 'romero'),
	('Jefferson', 'Brazil', 'jefferson'),
	('Felix Beijmo', 'Sweden', 'beijmo'),
	('Felix Beijmo', 'Sweden', 'felix beijmo'),
	('Christophe Lepoint', 'Belgium', 'christophe lepoint'),
	('Christophe Lepoint', 'Belgium', 'lepoint'),
	('Bruce Bvuma', 'South Africa', 'bruce bvuma'),
	('Bruce Bvuma', 'South Africa', 'bvuma'),
	('Tyrese Campbell', 'England', 'tyrese campbell'),
	('Tyrese Campbell', 'England', 'campbell'),
	('Johan Martial', 'France', 'johan martial'),
	('Johan Martial', 'France', 'martial'),
	('Gastón Olveira', 'Uruguay', 'gaston olveira'),
	('Gastón Olveira', 'Uruguay', 'olveira'),
	('Agustín González', 'Uruguay', 'gonzalez'),
	('Agustín González', 'Uruguay', 'agustin gonzalez'),
	('Derrick Jones', 'United States', 'derrick jones'),
	('Derrick Jones', 'United States', 'jones'),
	('Niklas Castro', 'Chile', 'castro'),
	('Niklas Castro', 'Chile', 'niklas castro'),
	('Akim Zedadka', 'France', 'zedadka'),
	('Akim Zedadka', 'France', 'akim zedadka'),
	('Sheldon Bateau', 'Trinidad & Tobago', 'bateau'),
	('Sheldon Bateau', 'Trinidad & Tobago', 'sheldon bateau'),
	('Ulises Cardona', 'Mexico', 'ulises cardona'),
	('Ulises Cardona', 'Mexico', 'cardona'),
	('Mario Maloča', 'Croatia', 'mario maloca'),
	('Mario Maloča', 'Croatia', 'maloca'),
	('Agustín Almendra', 'Argentina', 'almendra'),
	('Agustín Almendra', 'Argentina', 'agustin almendra'),
	('Horacio Tijanovich', 'Argentina', 'horacio tijanovich'),
	('Horacio Tijanovich', 'Argentina', 'tijanovich'),
	('Perry Ng', 'England', 'ng'),
	('Perry Ng', 'England', 'perry ng'),
	('Chris Maguire', 'Scotland', 'chris maguire'),
	('Chris Maguire', 'Scotland', 'maguire'),
	('Gakuto Notsuda', 'Japan', 'notsuda'),
	('Gakuto Notsuda', 'Japan', 'gakuto notsuda'),
	('Federico Bonazzoli', 'Italy', 'federico bonazzoli'),
	('Federico Bonazzoli', 'Italy', 'bonazzoli'),
	('Hussain Al Moqahwi', 'Saudi Arabia', 'moqahwi'),
	('Hussain Al Moqahwi', 'Saudi Arabia', 'hussain al moqahwi'),
	('Kemal Ademi', 'Switzerland', 'kemal ademi'),
	('Kemal Ademi', 'Switzerland', 'ademi'),
	('Niko Hämäläinen', 'Finland', 'niko hamalainen'),
	('Niko Hämäläinen', 'Finland', 'hamalainen'),
	('David Ramírez', 'Mexico', 'david ramirez'),
	('David Ramírez', 'Mexico', 'ramirez'),
	('Sebastian Ernst', 'Germany', 'sebastian ernst'),
	('Sebastian Ernst', 'Germany', 'ernst'),
	('Andrea Favilli', 'Italy', 'favilli'),
	('Andrea Favilli', 'Italy', 'andrea favilli'),
	('Dávid Ivan', 'Slovakia', 'ivan'),
	('Dávid Ivan', 'Slovakia', 'david ivan'),
	('Alberto Contrera', 'Paraguay', 'contrera'),
	('Alberto Contrera', 'Paraguay', 'alberto contrera'),
	('Franco Russo', 'Argentina', 'russo'),
	('Franco Russo', 'Argentina', 'franco russo'),
	('Marius Martac', 'Romania', 'marius martac'),
	('Marius Martac', 'Romania', 'martac'),
	('Jason Steele', 'England', 'jason steele'),
	('Jason Steele', 'England', 'steele'),
	('Nicolás Rodríguez', 'Uruguay', 'rodriguez'),
	('Nicolás Rodríguez', 'Uruguay', 'nicolas rodriguez'),
	('Alexander Jeremejeff', 'Sweden', 'alexander jeremejeff'),
	('Alexander Jeremejeff', 'Sweden', 'jeremejeff'),
	('James Norwood', 'England', 'norwood'),
	('James Norwood', 'England', 'james norwood'),
	('Adri Cuevas', 'Spain', 'adri cuevas'),
	('Adri Cuevas', 'Spain', 'cuevas'),
	('Naomichi Ueda', 'Japan', 'ueda'),
	('Naomichi Ueda', 'Japan', 'naomichi ueda'),
	('Raymon Gaddis', 'United States', 'raymon gaddis'),
	('Raymon Gaddis', 'United States', 'gaddis'),
	('Dani Romera', 'Spain', 'dani romera'),
	('Dani Romera', 'Spain', 'romera'),
	('Rafik Zekhnini', 'Norway', 'rafik zekhnini'),
	('Rafik Zekhnini', 'Norway', 'zekhnini'),
	('James Troisi', 'Australia', 'james troisi'),
	('James Troisi', 'Australia', 'troisi'),
	('Andreas Lienhart', 'Austria', 'andreas lienhart'),
	('Andreas Lienhart', 'Austria', 'lienhart'),
	('Yushi Hasegawa', 'Japan', 'yushi hasegawa'),
	('Yushi Hasegawa', 'Japan', 'hasegawa'),
	('Zhang Chengdong', 'China PR', 'zhang chengdong'),
	('Zhang Chengdong', 'China PR', 'chengdong'),
	('Johan Kappelhof', 'Netherlands', 'johan kappelhof'),
	('Johan Kappelhof', 'Netherlands', 'kappelhof'),
	('Thomas Ebner', 'Austria', 'ebner'),
	('Thomas Ebner', 'Austria', 'thomas ebner'),
	('Rei Matsumoto', 'Japan', 'rei matsumoto'),
	('Rei Matsumoto', 'Japan', 'matsumoto'),
	('Jack Rodwell', 'England', 'rodwell'),
	('Jack Rodwell', 'England', 'jack rodwell'),
	('Agustín Rogel', 'Uruguay', 'agustin rogel'),
	('Agustín Rogel', 'Uruguay', 'rogel'),
	('Hernán Galíndez', 'Argentina', 'galindez'),
	('Hernán Galíndez', 'Argentina', 'hernan galindez'),
	('Gary Correa', 'Peru', 'gary correa'),
	('Gary Correa', 'Peru', 'correa'),
	('Stefan Thesker', 'Germany', 'thesker'),
	('Stefan Thesker', 'Germany', 'stefan thesker'),
	('Dylan Bahamboula', 'Congo', 'dylan bahamboula'),
	('Dylan Bahamboula', 'Congo', 'bahamboula'),
	('Harisson Marcelin', 'France', 'marcelin'),
	('Harisson Marcelin', 'France', 'harisson marcelin'),
	('Kosei Shibasaki', 'Japan', 'kosei shibasaki'),
	('Kosei Shibasaki', 'Japan', 'shibasaki'),
	('Samba Camara', 'France', 'samba camara'),
	('Samba Camara', 'France', 'camara'),
	('Chris Martin', 'Scotland', 'chris martin'),
	('Chris Martin', 'Scotland', 'martin'),
	('Paul Coutts', 'Scotland', 'coutts'),
	('Paul Coutts', 'Scotland', 'paul coutts'),
	('Ben Purrington', 'England', 'purrington'),
	('Ben Purrington', 'England', 'ben purrington'),
	('Frederic Ananou', 'Germany', 'ananou'),
	('Frederic Ananou', 'Germany', 'frederic ananou'),
	('Alfonso Luna', 'Mexico', 'luna'),
	('Alfonso Luna', 'Mexico', 'alfonso luna'),
	('Kazuaki Mawatari', 'Japan', 'mawatari'),
	('Kazuaki Mawatari', 'Japan', 'kazuaki mawatari'),
	('Linus Wahlqvist', 'Sweden', 'wahlqvist'),
	('Linus Wahlqvist', 'Sweden', 'linus wahlqvist'),
	('Kik Pierie', 'Netherlands', 'pierie'),
	('Kik Pierie', 'Netherlands', 'kik pierie'),
	('Pichu Atienza', 'Spain', 'atienza'),
	('Pichu Atienza', 'Spain', 'pichu atienza'),
	('Shun Nagasawa', 'Japan', 'shun nagasawa'),
	('Shun Nagasawa', 'Japan', 'nagasawa'),
	('Jorge Fellipe', 'Brazil', 'fellipe'),
	('Jorge Fellipe', 'Brazil', 'jorge fellipe'),
	('Kazuki Fukai', 'Japan', 'kazuki fukai'),
	('Kazuki Fukai', 'Japan', 'fukai'),
	('Adil Aouchiche', 'France', 'adil aouchiche'),
	('Adil Aouchiche', 'France', 'aouchiche'),
	('Roberto Ramírez', 'Argentina', 'roberto ramirez'),
	('Roberto Ramírez', 'Argentina', 'ramirez'),
	('Víctor Dávila', 'Chile', 'victor davila'),
	('Víctor Dávila', 'Chile', 'davila'),
	('Manu Fuster', 'Spain', 'fuster'),
	('Manu Fuster', 'Spain', 'manu fuster'),
	('Wang Gang', 'China PR', 'wang gang'),
	('Wang Gang', 'China PR', 'gang'),
	('Carlo Holse', 'Denmark', 'carlo holse'),
	('Carlo Holse', 'Denmark', 'holse'),
	('Etienne Amenyido', 'Germany', 'amenyido'),
	('Etienne Amenyido', 'Germany', 'etienne amenyido'),
	('Alessandro Tuia', 'Italy', 'tuia'),
	('Alessandro Tuia', 'Italy', 'alessandro tuia'),
	('Kazunari Ichimi', 'Japan', 'ichimi'),
	('Kazunari Ichimi', 'Japan', 'kazunari ichimi'),
	('Jorge Arias', 'Colombia', 'jorge arias'),
	('Jorge Arias', 'Colombia', 'arias'),
	('Sauli Väisänen', 'Finland', 'sauli vaisanen'),
	('Sauli Väisänen', 'Finland', 'vaisanen'),
	('Tom Weilandt', 'Germany', 'tom weilandt'),
	('Tom Weilandt', 'Germany', 'weilandt'),
	('Yukiya Sugita', 'Japan', 'yukiya sugita'),
	('Yukiya Sugita', 'Japan', 'sugita'),
	('Takuma Arano', 'Japan', 'arano'),
	('Takuma Arano', 'Japan', 'takuma arano'),
	('Keanu Staude', 'Germany', 'staude'),
	('Keanu Staude', 'Germany', 'keanu staude'),
	('Jordan Silva', 'Mexico', 'jordan silva'),
	('Jordan Silva', 'Mexico', 'silva'),
	('Tobias Sana', 'Sweden', 'tobias sana'),
	('Tobias Sana', 'Sweden', 'sana'),
	('Campabadal', 'Spain', 'campabadal'),
	('Funso Ojo', 'Belgium', 'funso ojo'),
	('Funso Ojo', 'Belgium', 'ojo'),
	('Albert Bunjaku', 'Kosovo', 'albert bunjaku'),
	('Albert Bunjaku', 'Kosovo', 'bunjaku'),
	('Jalil Anibaba', 'United States', 'jalil anibaba'),
	('Jalil Anibaba', 'United States', 'anibaba'),
	('Federico Pérez', 'Uruguay', 'federico perez'),
	('Federico Pérez', 'Uruguay', 'perez'),
	('Jeison Chalá', 'Ecuador', 'chala'),
	('Jeison Chalá', 'Ecuador', 'jeison chala'),
	('Christos Tzolis', 'Greece', 'christos tzolis'),
	('Christos Tzolis', 'Greece', 'tzolis'),
	('Danny Wilson', 'Scotland', 'danny wilson'),
	('Danny Wilson', 'Scotland', 'wilson'),
	('Chris Maxwell', 'Wales', 'chris maxwell'),
	('Chris Maxwell', 'Wales', 'maxwell'),
	('Leonel López', 'Mexico', 'lopez'),
	('Leonel López', 'Mexico', 'leonel lopez'),
	('Julien Dacosta', 'France', 'julien dacosta'),
	('Julien Dacosta', 'France', 'dacosta'),
	('Bram Castro', 'Belgium', 'castro'),
	('Bram Castro', 'Belgium', 'bram castro'),
	('Pablo Trigueros', 'Spain', 'trigueros'),
	('Pablo Trigueros', 'Spain', 'pablo trigueros'),
	('Juan Carlos Espinoza', 'Chile', 'espinoza'),
	('Juan Carlos Espinoza', 'Chile', 'juan carlos espinoza'),
	('Danny Fox', 'Scotland', 'danny fox'),
	('Danny Fox', 'Scotland', 'fox'),
	('Mike Wunderlich', 'Germany', 'wunderlich'),
	('Mike Wunderlich', 'Germany', 'mike wunderlich'),
	('Liam Grimshaw', 'England', 'liam grimshaw'),
	('Liam Grimshaw', 'England', 'grimshaw'),
	('Carlos Sierra', 'Colombia', 'carlos sierra'),
	('Carlos Sierra', 'Colombia', 'sierra'),
	('Carlos Ruiz', 'Spain', 'ruiz'),
	('Carlos Ruiz', 'Spain', 'carlos ruiz'),
	('Rémy Descamps', 'France', 'remy descamps'),
	('Rémy Descamps', 'France', 'descamps'),
	('Simon Olsson', 'Sweden', 'simon olsson'),
	('Simon Olsson', 'Sweden', 'olsson'),
	('Drew Moor', 'United States', 'drew moor'),
	('Drew Moor', 'United States', 'moor'),
	('Diego Garcia', 'Uruguay', 'garcia'),
	('Diego Garcia', 'Uruguay', 'diego garcia')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';