INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Edgar Games', 'Mexico', 'player'),
	('Fabian Brosowski', 'Germany', 'player'),
	('Ivo Vázquez', 'Mexico', 'player'),
	('Guillermo Tegue', 'Colombia', 'player'),
	('Harry Perritt', 'England', 'player'),
	('Lukas Schleimer', 'Germany', 'player'),
	('Silvano Estacio', 'Ecuador', 'player'),
	('Robert Riza', 'Romania', 'player'),
	('Joe Gauci', 'Australia', 'player'),
	('Trae Coyle', 'England', 'player'),
	('Pedro Ibáñez', 'Peru', 'player'),
	('Mauricio Márquez', 'Venezuela', 'player'),
	('Joe Leesley', 'England', 'player'),
	('Alex Bradley', 'Finland', 'player'),
	('Rafael Tapia', 'Colombia', 'player'),
	('Marian Târșă', 'Romania', 'player'),
	('Richard Taylor', 'England', 'player'),
	('Kim Woo Suk', 'Korea Republic', 'player'),
	('Marcus Dinanga', 'England', 'player'),
	('Estiven Pérez', 'Paraguay', 'player'),
	('Santiago Pierotti', 'Argentina', 'player'),
	('Jackson Longridge', 'Scotland', 'player'),
	('Yuta Matsumura', 'Japan', 'player'),
	('Georgi Tunjov', 'Estonia', 'player'),
	('Dylan McGlade', 'Republic of Ireland', 'player'),
	('Boubacari Doucouré', 'France', 'player'),
	('John Mero', 'Ecuador', 'player'),
	('Akın Alkan', 'Turkey', 'player'),
	('Runar Hauge', 'Norway', 'player'),
	('Anthony Uzodimma', 'Nigeria', 'player'),
	('Melker Nilsson', 'Sweden', 'player'),
	('Pablo Ortiz', 'Colombia', 'player'),
	('Nick Sullivan', 'Australia', 'player'),
	('Joshua Cavallo', 'Australia', 'player'),
	('Jonathan Perez', 'Mexico', 'player'),
	('Ricardo German', 'England', 'player'),
	('Mads Hermansen', 'Denmark', 'player'),
	('Thomas Roberts', 'United States', 'player'),
	('Jefferson de Souza', 'Norway', 'player'),
	('Joe Thomson', 'Scotland', 'player'),
	('Abdullah Al Qahtani', 'Saudi Arabia', 'player'),
	('Kodai Dohi', 'Japan', 'player'),
	('Lee Ho In', 'Korea Republic', 'player'),
	('Tomás Fernández', 'Argentina', 'player'),
	('Jordy Schelfhout', 'Belgium', 'player'),
	('Sosuke Shibata', 'Japan', 'player'),
	('Oskar Opsahl', 'Norway', 'player'),
	('Han Jiaqi', 'China PR', 'player'),
	('Felix Kerber', 'Austria', 'player'),
	('Maxim Deman', 'Belgium', 'player'),
	('Frank Stople', 'Norway', 'player'),
	('Adam Long', 'England', 'player'),
	('Orges Bunjaku', 'Switzerland', 'player'),
	('Caolán Boyd-Munce', 'Northern Ireland', 'player'),
	('Faiz Mattoir', 'France', 'player'),
	('Lorenz Otto', 'Germany', 'player'),
	('Hazaa Assiri', 'Saudi Arabia', 'player'),
	('Daylam Meddah', 'France', 'player'),
	('Lei Wenjie', 'China PR', 'player'),
	('Jordan Thomas', 'England', 'player'),
	('Davide Luzi', 'Venezuela', 'player'),
	('Jamie Semple', 'Scotland', 'player'),
	('Shun Ayukawa', 'Japan', 'player'),
	('Facundo Farías', 'Argentina', 'player'),
	('Rahmat Akbari', 'Australia', 'player'),
	('Ryan Sandford', 'England', 'player'),
	('Ramiro Ruiz', 'Argentina', 'player'),
	('Chris Merrie', 'England', 'player'),
	('Robert Slevin', 'Republic of Ireland', 'player'),
	('Feng Boxuan', 'China PR', 'player'),
	('Johan Lara', 'Ecuador', 'player'),
	('Mark Harris', 'Wales', 'player'),
	('Marcus Dewhurst', 'England', 'player'),
	('Alan Reyes', 'Mexico', 'player'),
	('Bernardo Rosa', 'Brazil', 'player'),
	('Jeremy Kelly', 'Czech Republic', 'player'),
	('Cătălin Barbu', 'Romania', 'player'),
	('Jorge Davidson', 'Venezuela', 'player'),
	('Mohammed Al Mahasna', 'Saudi Arabia', 'player'),
	('Luis Peña', 'Venezuela', 'player'),
	('Nelson Orozco', 'Bolivia', 'player'),
	('Huang Xiyang', 'China PR', 'player'),
	('Hassan Al Shamrani', 'Saudi Arabia', 'player'),
	('Warren Bondo', 'France', 'player'),
	('Jake Hutchinson', 'England', 'player'),
	('Fisayo Dele-Bashiru', 'Nigeria', 'player'),
	('Mustapha Fofana', 'Norway', 'player'),
	('Ross Tierney', 'Republic of Ireland', 'player'),
	('Koki Harada', 'Japan', 'player'),
	('Elías Oyola', 'Uruguay', 'player'),
	('Phillip Ejimadu', 'United States', 'player'),
	('Gao Tianyi', 'China PR', 'player'),
	('Mustafa Burak Bozan', 'Turkey', 'player'),
	('Yílmar Velásquez', 'Colombia', 'player'),
	('Cem Sabanci', 'Germany', 'player'),
	('Jake Lawlor', 'England', 'player'),
	('Tunji Akinola', 'England', 'player'),
	('Mohammad Al Thani', 'Saudi Arabia', 'player'),
	('Kim Min Duk', 'Korea Republic', 'player'),
	('Federico Ravaglia', 'Italy', 'player'),
	('Emmanuel Samba', 'France', 'player'),
	('Agustín Suárez', 'Uruguay', 'player'),
	('Marc Tsoungui', 'Switzerland', 'player'),
	('Ronaldo Andía', 'Peru', 'player'),
	('Tyler Frost', 'England', 'player'),
	('Carlos Daniel Castro', 'Colombia', 'player'),
	('Enock Mawete Mwimba', 'Norway', 'player'),
	('Florentin Bloch', 'France', 'player'),
	('Taylor Silverholt', 'Sweden', 'player'),
	('Berke Gürbüz', 'Turkey', 'player'),
	('Kang Yun Koo', 'Korea Republic', 'player'),
	('Lewis Gard', 'England', 'player'),
	('Bojan Radulović', 'Serbia', 'player'),
	('Sigurd Tafjord', 'Norway', 'player'),
	('Michael Carcelén', 'Ecuador', 'player'),
	('Juan Carlos Diaz', 'Colombia', 'player'),
	('José Contreras', 'Venezuela', 'player'),
	('Dragoș Gheorghe', 'Romania', 'player'),
	('Harm Dieker', 'Netherlands', 'player'),
	('Erdem Canpolat', 'Germany', 'player'),
	('Lewis Jamieson', 'Scotland', 'player'),
	('Rocco Romeo', 'Canada', 'player'),
	('Henri Koide', 'Switzerland', 'player'),
	('Ryan Campbell-Gordon', 'England', 'player'),
	('Thorben Deters', 'Germany', 'player'),
	('Sandro Theler', 'Switzerland', 'player'),
	('Ervin Montero', 'Bolivia', 'player'),
	('Ruairí Harkin', 'Republic of Ireland', 'player'),
	('Vlad Mitrea', 'Romania', 'player'),
	('Josh Flanagan', 'England', 'player'),
	('Mateusz Bartolewski', 'Poland', 'player'),
	('Abdulelah Al Burayh', 'Saudi Arabia', 'player'),
	('Ryo Ishii', 'Japan', 'player'),
	('Idrissa Dioh', 'France', 'player'),
	('Connor Sparrow', 'United States', 'player'),
	('Geani Crețu', 'Romania', 'player'),
	('Abdullah Al Bahri', 'Saudi Arabia', 'player'),
	('Jaime Ortíz', 'Ecuador', 'player'),
	('Conor Davis', 'Republic of Ireland', 'player'),
	('Agustín Álvarez Wallace', 'Uruguay', 'player'),
	('Benny Igiehon', 'Switzerland', 'player'),
	('Harry Seaden', 'England', 'player'),
	('Ryotaro Ishida', 'Japan', 'player'),
	('Jair González', 'Mexico', 'player'),
	('Adam Pavlesic', 'Australia', 'player'),
	('Tyrone O''Neill', 'England', 'player'),
	('Ștefan Rusu', 'Romania', 'player'),
	('Max Dyche', 'England', 'player'),
	('Osman Can Cötür', 'Turkey', 'player'),
	('Diego Ramírez', 'Peru', 'player'),
	('Alexandru Ilie', 'Romania', 'player'),
	('Alexandru Stoica', 'Romania', 'player'),
	('Kaloyan Kostadinov', 'Norway', 'player'),
	('Oğuzhan Çapar', 'Turkey', 'player'),
	('Edson Pires', 'Guinea Bissau', 'player'),
	('Angelo Campos', 'Switzerland', 'player'),
	('Valentin Lamprecht', 'Austria', 'player'),
	('Paul Cleary', 'Republic of Ireland', 'player'),
	('Denis Rusu', 'Romania', 'player'),
	('Alexis Antunes', 'Switzerland', 'player'),
	('Lars Dendoncker', 'Belgium', 'player'),
	('Blondy Nna Noukeu', 'Cameroon', 'player'),
	('Bogdan Balint', 'Romania', 'player'),
	('Aleksander Pawlak', 'Poland', 'player'),
	('Ben Dempsey', 'England', 'player'),
	('Mauro Rodrigues', 'Portugal', 'player'),
	('Miles Mitchell-Nelson', 'England', 'player'),
	('Tom Amos', 'Sweden', 'player'),
	('Jacob Ramsey', 'England', 'player'),
	('David Longe-King', 'England', 'player'),
	('Jordon Thompson', 'England', 'player'),
	('Jamie Roche', 'Sweden', 'player'),
	('Taylor Curran', 'England', 'player'),
	('Nahum Melvin-Lambert', 'England', 'player'),
	('Azad Toptik', 'Turkey', 'player'),
	('Marius Pahonțu', 'Romania', 'player'),
	('Matthew Garbett', 'New Zealand', 'player'),
	('Isak Helstad Amundsen', 'Norway', 'player'),
	('Rio Adebisi', 'England', 'player'),
	('Abdullah Nasser', 'Saudi Arabia', 'player'),
	('Saleh Al Nashmi', 'Saudi Arabia', 'player'),
	('Colin McCabe', 'Republic of Ireland', 'player'),
	('Konrad Sieracki', 'Poland', 'player'),
	('Josh Key', 'England', 'player'),
	('Dennis Collander', 'Sweden', 'player'),
	('Ibrahim Al Baraka', 'Saudi Arabia', 'player'),
	('Cameron Gregory', 'England', 'player'),
	('Trey Muse', 'United States', 'player'),
	('Halil İbrahim Sevinç', 'Turkey', 'player'),
	('Scott Twine', 'England', 'player'),
	('Zhao Yingjie', 'China PR', 'player'),
	('Tanner Beason', 'United States', 'player'),
	('Yuan Ye', 'China PR', 'player'),
	('Cosmin Atanase', 'Romania', 'player'),
	('Haji Mnoga', 'England', 'player'),
	('Henry Ochieng', 'Kenya', 'player'),
	('Kieron Evans', 'Wales', 'player'),
	('Ronan Hurley', 'Republic of Ireland', 'player'),
	('Shi Chenglong', 'China PR', 'player'),
	('Andrés Llinás', 'Colombia', 'player'),
	('Ashvin Balaruban', 'Switzerland', 'player'),
	('Ryan Burke', 'Republic of Ireland', 'player'),
	('Brandon Lauton', 'Australia', 'player'),
	('Matthew Alexander', 'England', 'player'),
	('Juan Diego Ospina', 'Colombia', 'player'),
	('Abduhamit Abdugheni', 'China PR', 'player'),
	('Gerson Vázquez', 'Mexico', 'player'),
	('Aygün Duman', 'Turkey', 'player'),
	('Kim Jae Woo', 'Korea Republic', 'player'),
	('Finn Azaz', 'England', 'player'),
	('Fidel Ambríz', 'Mexico', 'player'),
	('Phoenix Missi Tomp', 'Cameroon', 'player'),
	('Abdoul Yoda', 'Burkina Faso', 'player'),
	('Choe Pil Soo', 'Korea Republic', 'player'),
	('Ionuț Rus', 'Romania', 'player'),
	('Fabricio Correa', 'Uruguay', 'player'),
	('Job Froeling', 'Netherlands', 'player'),
	('Taylor Perry', 'England', 'player'),
	('Yusong Ni', 'China PR', 'player'),
	('Ferddy Roca', 'Bolivia', 'player'),
	('Carlo Armiento', 'Australia', 'player'),
	('Novem Baumann', 'Switzerland', 'player'),
	('Carlos Cortes', 'Colombia', 'player'),
	('Josh Atencio', 'United States', 'player'),
	('Lee Joon Suk', 'Korea Republic', 'player'),
	('Alex Perry', 'England', 'player'),
	('Sam Bowen', 'Wales', 'player'),
	('Jairo Uscamayta', 'Peru', 'player'),
	('Jake Dunwoody', 'Northern Ireland', 'player'),
	('Daniel Björkman', 'Sweden', 'player'),
	('Jiang Wenjun', 'China PR', 'player'),
	('Wojciech Błyszko', 'Poland', 'player'),
	('Peter Urminsky', 'Slovakia', 'player'),
	('Sagir Arce', 'United States', 'player'),
	('Mirza Muratovic', 'Australia', 'player'),
	('Park Jae Hun', 'Korea Republic', 'player'),
	('Hussain Salem', 'Saudi Arabia', 'player'),
	('Simon Gollnack', 'Germany', 'player'),
	('Jordan Gibson', 'England', 'player'),
	('Lorcan Fitzgerald', 'Republic of Ireland', 'player'),
	('Lee Joon Hee', 'Korea Republic', 'player'),
	('Yahya Kalley', 'Sweden', 'player'),
	('Ísak Óli Ólafsson', 'Iceland', 'player'),
	('Torben Rhein', 'Germany', 'player'),
	('Omar Reyes', 'Peru', 'player'),
	('Adrian Delap', 'Republic of Ireland', 'player'),
	('Goh Young Jun', 'Korea Republic', 'player'),
	('Zhou Junchen', 'China PR', 'player'),
	('Martin Majnovics', 'Hungary', 'player'),
	('Mariusz Fornalczyk', 'Poland', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Edgar Games', 'Mexico', 'games'),
	('Edgar Games', 'Mexico', 'edgar games'),
	('Fabian Brosowski', 'Germany', 'brosowski'),
	('Fabian Brosowski', 'Germany', 'fabian brosowski'),
	('Ivo Vázquez', 'Mexico', 'vazquez'),
	('Ivo Vázquez', 'Mexico', 'ivo vazquez'),
	('Guillermo Tegue', 'Colombia', 'guillermo tegue'),
	('Guillermo Tegue', 'Colombia', 'tegue'),
	('Harry Perritt', 'England', 'perritt'),
	('Harry Perritt', 'England', 'harry perritt'),
	('Lukas Schleimer', 'Germany', 'lukas schleimer'),
	('Lukas Schleimer', 'Germany', 'schleimer'),
	('Silvano Estacio', 'Ecuador', 'silvano estacio'),
	('Silvano Estacio', 'Ecuador', 'estacio'),
	('Robert Riza', 'Romania', 'robert riza'),
	('Robert Riza', 'Romania', 'riza'),
	('Joe Gauci', 'Australia', 'gauci'),
	('Joe Gauci', 'Australia', 'joe gauci'),
	('Trae Coyle', 'England', 'coyle'),
	('Trae Coyle', 'England', 'trae coyle'),
	('Pedro Ibáñez', 'Peru', 'ibanez'),
	('Pedro Ibáñez', 'Peru', 'pedro ibanez'),
	('Mauricio Márquez', 'Venezuela', 'mauricio marquez'),
	('Mauricio Márquez', 'Venezuela', 'marquez'),
	('Joe Leesley', 'England', 'joe leesley'),
	('Joe Leesley', 'England', 'leesley'),
	('Alex Bradley', 'Finland', 'alex bradley'),
	('Alex Bradley', 'Finland', 'bradley'),
	('Rafael Tapia', 'Colombia', 'rafael tapia'),
	('Rafael Tapia', 'Colombia', 'tapia'),
	('Marian Târșă', 'Romania', 'tarsa'),
	('Marian Târșă', 'Romania', 'marian tarsa'),
	('Richard Taylor', 'England', 'taylor'),
	('Richard Taylor', 'England', 'richard taylor'),
	('Kim Woo Suk', 'Korea Republic', 'suk'),
	('Kim Woo Suk', 'Korea Republic', 'kim woo suk'),
	('Marcus Dinanga', 'England', 'marcus dinanga'),
	('Marcus Dinanga', 'England', 'dinanga'),
	('Estiven Pérez', 'Paraguay', 'estiven perez'),
	('Estiven Pérez', 'Paraguay', 'perez'),
	('Santiago Pierotti', 'Argentina', 'pierotti'),
	('Santiago Pierotti', 'Argentina', 'santiago pierotti'),
	('Jackson Longridge', 'Scotland', 'longridge'),
	('Jackson Longridge', 'Scotland', 'jackson longridge'),
	('Yuta Matsumura', 'Japan', 'matsumura'),
	('Yuta Matsumura', 'Japan', 'yuta matsumura'),
	('Georgi Tunjov', 'Estonia', 'tunjov'),
	('Georgi Tunjov', 'Estonia', 'georgi tunjov'),
	('Dylan McGlade', 'Republic of Ireland', 'dylan mcglade'),
	('Dylan McGlade', 'Republic of Ireland', 'mcglade'),
	('Boubacari Doucouré', 'France', 'doucoure'),
	('Boubacari Doucouré', 'France', 'boubacari doucoure'),
	('John Mero', 'Ecuador', 'john mero'),
	('John Mero', 'Ecuador', 'mero'),
	('Akın Alkan', 'Turkey', 'akn alkan'),
	('Akın Alkan', 'Turkey', 'alkan'),
	('Runar Hauge', 'Norway', 'hauge'),
	('Runar Hauge', 'Norway', 'runar hauge'),
	('Anthony Uzodimma', 'Nigeria', 'anthony uzodimma'),
	('Anthony Uzodimma', 'Nigeria', 'uzodimma'),
	('Melker Nilsson', 'Sweden', 'nilsson'),
	('Melker Nilsson', 'Sweden', 'melker nilsson'),
	('Pablo Ortiz', 'Colombia', 'ortiz'),
	('Pablo Ortiz', 'Colombia', 'pablo ortiz'),
	('Nick Sullivan', 'Australia', 'nick sullivan'),
	('Nick Sullivan', 'Australia', 'sullivan'),
	('Joshua Cavallo', 'Australia', 'cavallo'),
	('Joshua Cavallo', 'Australia', 'joshua cavallo'),
	('Jonathan Perez', 'Mexico', 'jonathan perez'),
	('Jonathan Perez', 'Mexico', 'perez'),
	('Ricardo German', 'England', 'ricardo german'),
	('Ricardo German', 'England', 'german'),
	('Mads Hermansen', 'Denmark', 'mads hermansen'),
	('Mads Hermansen', 'Denmark', 'hermansen'),
	('Thomas Roberts', 'United States', 'thomas roberts'),
	('Thomas Roberts', 'United States', 'roberts'),
	('Jefferson de Souza', 'Norway', 'souza'),
	('Jefferson de Souza', 'Norway', 'jefferson de souza'),
	('Joe Thomson', 'Scotland', 'joe thomson'),
	('Joe Thomson', 'Scotland', 'thomson'),
	('Abdullah Al Qahtani', 'Saudi Arabia', 'abdullah al qahtani'),
	('Abdullah Al Qahtani', 'Saudi Arabia', 'qahtani'),
	('Kodai Dohi', 'Japan', 'dohi'),
	('Kodai Dohi', 'Japan', 'kodai dohi'),
	('Lee Ho In', 'Korea Republic', 'lee ho in'),
	('Lee Ho In', 'Korea Republic', 'in'),
	('Tomás Fernández', 'Argentina', 'fernandez'),
	('Tomás Fernández', 'Argentina', 'tomas fernandez'),
	('Jordy Schelfhout', 'Belgium', 'schelfhout'),
	('Jordy Schelfhout', 'Belgium', 'jordy schelfhout'),
	('Sosuke Shibata', 'Japan', 'sosuke shibata'),
	('Sosuke Shibata', 'Japan', 'shibata'),
	('Oskar Opsahl', 'Norway', 'oskar opsahl'),
	('Oskar Opsahl', 'Norway', 'opsahl'),
	('Han Jiaqi', 'China PR', 'jiaqi'),
	('Han Jiaqi', 'China PR', 'han jiaqi'),
	('Felix Kerber', 'Austria', 'kerber'),
	('Felix Kerber', 'Austria', 'felix kerber'),
	('Maxim Deman', 'Belgium', 'deman'),
	('Maxim Deman', 'Belgium', 'maxim deman'),
	('Frank Stople', 'Norway', 'stople'),
	('Frank Stople', 'Norway', 'frank stople'),
	('Adam Long', 'England', 'long'),
	('Adam Long', 'England', 'adam long'),
	('Orges Bunjaku', 'Switzerland', 'orges bunjaku'),
	('Orges Bunjaku', 'Switzerland', 'bunjaku'),
	('Caolán Boyd-Munce', 'Northern Ireland', 'caolan boydmunce'),
	('Caolán Boyd-Munce', 'Northern Ireland', 'boydmunce'),
	('Faiz Mattoir', 'France', 'mattoir'),
	('Faiz Mattoir', 'France', 'faiz mattoir'),
	('Lorenz Otto', 'Germany', 'otto'),
	('Lorenz Otto', 'Germany', 'lorenz otto'),
	('Hazaa Assiri', 'Saudi Arabia', 'assiri'),
	('Hazaa Assiri', 'Saudi Arabia', 'hazaa assiri'),
	('Daylam Meddah', 'France', 'daylam meddah'),
	('Daylam Meddah', 'France', 'meddah'),
	('Lei Wenjie', 'China PR', 'wenjie'),
	('Lei Wenjie', 'China PR', 'lei wenjie'),
	('Jordan Thomas', 'England', 'jordan thomas'),
	('Jordan Thomas', 'England', 'thomas'),
	('Davide Luzi', 'Venezuela', 'luzi'),
	('Davide Luzi', 'Venezuela', 'davide luzi'),
	('Jamie Semple', 'Scotland', 'semple'),
	('Jamie Semple', 'Scotland', 'jamie semple'),
	('Shun Ayukawa', 'Japan', 'shun ayukawa'),
	('Shun Ayukawa', 'Japan', 'ayukawa'),
	('Facundo Farías', 'Argentina', 'farias'),
	('Facundo Farías', 'Argentina', 'facundo farias'),
	('Rahmat Akbari', 'Australia', 'rahmat akbari'),
	('Rahmat Akbari', 'Australia', 'akbari'),
	('Ryan Sandford', 'England', 'sandford'),
	('Ryan Sandford', 'England', 'ryan sandford'),
	('Ramiro Ruiz', 'Argentina', 'ruiz'),
	('Ramiro Ruiz', 'Argentina', 'ramiro ruiz'),
	('Chris Merrie', 'England', 'chris merrie'),
	('Chris Merrie', 'England', 'merrie'),
	('Robert Slevin', 'Republic of Ireland', 'robert slevin'),
	('Robert Slevin', 'Republic of Ireland', 'slevin'),
	('Feng Boxuan', 'China PR', 'boxuan'),
	('Feng Boxuan', 'China PR', 'feng boxuan'),
	('Johan Lara', 'Ecuador', 'lara'),
	('Johan Lara', 'Ecuador', 'johan lara'),
	('Mark Harris', 'Wales', 'mark harris'),
	('Mark Harris', 'Wales', 'harris'),
	('Marcus Dewhurst', 'England', 'marcus dewhurst'),
	('Marcus Dewhurst', 'England', 'dewhurst'),
	('Alan Reyes', 'Mexico', 'reyes'),
	('Alan Reyes', 'Mexico', 'alan reyes'),
	('Bernardo Rosa', 'Brazil', 'bernardo rosa'),
	('Bernardo Rosa', 'Brazil', 'rosa'),
	('Jeremy Kelly', 'Czech Republic', 'kelly'),
	('Jeremy Kelly', 'Czech Republic', 'jeremy kelly'),
	('Cătălin Barbu', 'Romania', 'catalin barbu'),
	('Cătălin Barbu', 'Romania', 'barbu'),
	('Jorge Davidson', 'Venezuela', 'jorge davidson'),
	('Jorge Davidson', 'Venezuela', 'davidson'),
	('Mohammed Al Mahasna', 'Saudi Arabia', 'mahasna'),
	('Mohammed Al Mahasna', 'Saudi Arabia', 'mohammed al mahasna'),
	('Luis Peña', 'Venezuela', 'pena'),
	('Luis Peña', 'Venezuela', 'luis pena'),
	('Nelson Orozco', 'Bolivia', 'nelson orozco'),
	('Nelson Orozco', 'Bolivia', 'orozco'),
	('Huang Xiyang', 'China PR', 'xiyang'),
	('Huang Xiyang', 'China PR', 'huang xiyang'),
	('Hassan Al Shamrani', 'Saudi Arabia', 'hassan al shamrani'),
	('Hassan Al Shamrani', 'Saudi Arabia', 'shamrani'),
	('Warren Bondo', 'France', 'bondo'),
	('Warren Bondo', 'France', 'warren bondo'),
	('Jake Hutchinson', 'England', 'jake hutchinson'),
	('Jake Hutchinson', 'England', 'hutchinson'),
	('Fisayo Dele-Bashiru', 'Nigeria', 'delebashiru'),
	('Fisayo Dele-Bashiru', 'Nigeria', 'fisayo delebashiru'),
	('Mustapha Fofana', 'Norway', 'mustapha fofana'),
	('Mustapha Fofana', 'Norway', 'fofana'),
	('Ross Tierney', 'Republic of Ireland', 'ross tierney'),
	('Ross Tierney', 'Republic of Ireland', 'tierney'),
	('Koki Harada', 'Japan', 'koki harada'),
	('Koki Harada', 'Japan', 'harada'),
	('Elías Oyola', 'Uruguay', 'oyola'),
	('Elías Oyola', 'Uruguay', 'elias oyola'),
	('Phillip Ejimadu', 'United States', 'ejimadu'),
	('Phillip Ejimadu', 'United States', 'phillip ejimadu'),
	('Gao Tianyi', 'China PR', 'gao tianyi'),
	('Gao Tianyi', 'China PR', 'tianyi'),
	('Mustafa Burak Bozan', 'Turkey', 'mustafa burak bozan'),
	('Mustafa Burak Bozan', 'Turkey', 'bozan'),
	('Yílmar Velásquez', 'Colombia', 'yilmar velasquez'),
	('Yílmar Velásquez', 'Colombia', 'velasquez'),
	('Cem Sabanci', 'Germany', 'sabanci'),
	('Cem Sabanci', 'Germany', 'cem sabanci'),
	('Jake Lawlor', 'England', 'jake lawlor'),
	('Jake Lawlor', 'England', 'lawlor'),
	('Tunji Akinola', 'England', 'akinola'),
	('Tunji Akinola', 'England', 'tunji akinola'),
	('Mohammad Al Thani', 'Saudi Arabia', 'mohammad al thani'),
	('Mohammad Al Thani', 'Saudi Arabia', 'thani'),
	('Kim Min Duk', 'Korea Republic', 'duk'),
	('Kim Min Duk', 'Korea Republic', 'kim min duk'),
	('Federico Ravaglia', 'Italy', 'federico ravaglia'),
	('Federico Ravaglia', 'Italy', 'ravaglia'),
	('Emmanuel Samba', 'France', 'samba'),
	('Emmanuel Samba', 'France', 'emmanuel samba'),
	('Agustín Suárez', 'Uruguay', 'agustin suarez'),
	('Agustín Suárez', 'Uruguay', 'suarez'),
	('Marc Tsoungui', 'Switzerland', 'marc tsoungui'),
	('Marc Tsoungui', 'Switzerland', 'tsoungui'),
	('Ronaldo Andía', 'Peru', 'ronaldo andia'),
	('Ronaldo Andía', 'Peru', 'andia'),
	('Tyler Frost', 'England', 'frost'),
	('Tyler Frost', 'England', 'tyler frost'),
	('Carlos Daniel Castro', 'Colombia', 'castro'),
	('Carlos Daniel Castro', 'Colombia', 'carlos daniel castro'),
	('Enock Mawete Mwimba', 'Norway', 'enock mawete mwimba'),
	('Enock Mawete Mwimba', 'Norway', 'mwimba'),
	('Florentin Bloch', 'France', 'bloch'),
	('Florentin Bloch', 'France', 'florentin bloch'),
	('Taylor Silverholt', 'Sweden', 'taylor silverholt'),
	('Taylor Silverholt', 'Sweden', 'silverholt'),
	('Berke Gürbüz', 'Turkey', 'berke gurbuz'),
	('Berke Gürbüz', 'Turkey', 'gurbuz'),
	('Kang Yun Koo', 'Korea Republic', 'koo'),
	('Kang Yun Koo', 'Korea Republic', 'kang yun koo'),
	('Lewis Gard', 'England', 'gard'),
	('Lewis Gard', 'England', 'lewis gard'),
	('Bojan Radulović', 'Serbia', 'bojan radulovic'),
	('Bojan Radulović', 'Serbia', 'radulovic'),
	('Sigurd Tafjord', 'Norway', 'tafjord'),
	('Sigurd Tafjord', 'Norway', 'sigurd tafjord'),
	('Michael Carcelén', 'Ecuador', 'carcelen'),
	('Michael Carcelén', 'Ecuador', 'michael carcelen'),
	('Juan Carlos Diaz', 'Colombia', 'juan carlos diaz'),
	('Juan Carlos Diaz', 'Colombia', 'diaz'),
	('José Contreras', 'Venezuela', 'jose contreras'),
	('José Contreras', 'Venezuela', 'contreras'),
	('Dragoș Gheorghe', 'Romania', 'gheorghe'),
	('Dragoș Gheorghe', 'Romania', 'dragos gheorghe'),
	('Harm Dieker', 'Netherlands', 'harm dieker'),
	('Harm Dieker', 'Netherlands', 'dieker'),
	('Erdem Canpolat', 'Germany', 'erdem canpolat'),
	('Erdem Canpolat', 'Germany', 'canpolat'),
	('Lewis Jamieson', 'Scotland', 'lewis jamieson'),
	('Lewis Jamieson', 'Scotland', 'jamieson'),
	('Rocco Romeo', 'Canada', 'rocco romeo'),
	('Rocco Romeo', 'Canada', 'romeo'),
	('Henri Koide', 'Switzerland', 'koide'),
	('Henri Koide', 'Switzerland', 'henri koide'),
	('Ryan Campbell-Gordon', 'England', 'campbellgordon'),
	('Ryan Campbell-Gordon', 'England', 'ryan campbellgordon'),
	('Thorben Deters', 'Germany', 'thorben deters'),
	('Thorben Deters', 'Germany', 'deters'),
	('Sandro Theler', 'Switzerland', 'sandro theler'),
	('Sandro Theler', 'Switzerland', 'theler'),
	('Ervin Montero', 'Bolivia', 'ervin montero'),
	('Ervin Montero', 'Bolivia', 'montero'),
	('Ruairí Harkin', 'Republic of Ireland', 'harkin'),
	('Ruairí Harkin', 'Republic of Ireland', 'ruairi harkin'),
	('Vlad Mitrea', 'Romania', 'vlad mitrea'),
	('Vlad Mitrea', 'Romania', 'mitrea'),
	('Josh Flanagan', 'England', 'flanagan'),
	('Josh Flanagan', 'England', 'josh flanagan'),
	('Mateusz Bartolewski', 'Poland', 'bartolewski'),
	('Mateusz Bartolewski', 'Poland', 'mateusz bartolewski'),
	('Abdulelah Al Burayh', 'Saudi Arabia', 'abdulelah al burayh'),
	('Abdulelah Al Burayh', 'Saudi Arabia', 'burayh'),
	('Ryo Ishii', 'Japan', 'ishii'),
	('Ryo Ishii', 'Japan', 'ryo ishii'),
	('Idrissa Dioh', 'France', 'idrissa dioh'),
	('Idrissa Dioh', 'France', 'dioh'),
	('Connor Sparrow', 'United States', 'sparrow'),
	('Connor Sparrow', 'United States', 'connor sparrow'),
	('Geani Crețu', 'Romania', 'cretu'),
	('Geani Crețu', 'Romania', 'geani cretu'),
	('Abdullah Al Bahri', 'Saudi Arabia', 'bahri'),
	('Abdullah Al Bahri', 'Saudi Arabia', 'abdullah al bahri'),
	('Jaime Ortíz', 'Ecuador', 'ortiz'),
	('Jaime Ortíz', 'Ecuador', 'jaime ortiz'),
	('Conor Davis', 'Republic of Ireland', 'conor davis'),
	('Conor Davis', 'Republic of Ireland', 'davis'),
	('Agustín Álvarez Wallace', 'Uruguay', 'wallace'),
	('Agustín Álvarez Wallace', 'Uruguay', 'agustin alvarez wallace'),
	('Benny Igiehon', 'Switzerland', 'igiehon'),
	('Benny Igiehon', 'Switzerland', 'benny igiehon'),
	('Harry Seaden', 'England', 'harry seaden'),
	('Harry Seaden', 'England', 'seaden'),
	('Ryotaro Ishida', 'Japan', 'ishida'),
	('Ryotaro Ishida', 'Japan', 'ryotaro ishida'),
	('Jair González', 'Mexico', 'jair gonzalez'),
	('Jair González', 'Mexico', 'gonzalez'),
	('Adam Pavlesic', 'Australia', 'adam pavlesic'),
	('Adam Pavlesic', 'Australia', 'pavlesic'),
	('Tyrone O''Neill', 'England', 'tyrone oneill'),
	('Tyrone O''Neill', 'England', 'oneill'),
	('Ștefan Rusu', 'Romania', 'stefan rusu'),
	('Ștefan Rusu', 'Romania', 'rusu'),
	('Max Dyche', 'England', 'dyche'),
	('Max Dyche', 'England', 'max dyche'),
	('Osman Can Cötür', 'Turkey', 'osman can cotur'),
	('Osman Can Cötür', 'Turkey', 'cotur'),
	('Diego Ramírez', 'Peru', 'diego ramirez'),
	('Diego Ramírez', 'Peru', 'ramirez'),
	('Alexandru Ilie', 'Romania', 'alexandru ilie'),
	('Alexandru Ilie', 'Romania', 'ilie'),
	('Alexandru Stoica', 'Romania', 'alexandru stoica'),
	('Alexandru Stoica', 'Romania', 'stoica'),
	('Kaloyan Kostadinov', 'Norway', 'kaloyan kostadinov'),
	('Kaloyan Kostadinov', 'Norway', 'kostadinov'),
	('Oğuzhan Çapar', 'Turkey', 'capar'),
	('Oğuzhan Çapar', 'Turkey', 'oguzhan capar'),
	('Edson Pires', 'Guinea Bissau', 'edson pires'),
	('Edson Pires', 'Guinea Bissau', 'pires'),
	('Angelo Campos', 'Switzerland', 'angelo campos'),
	('Angelo Campos', 'Switzerland', 'campos'),
	('Valentin Lamprecht', 'Austria', 'lamprecht'),
	('Valentin Lamprecht', 'Austria', 'valentin lamprecht'),
	('Paul Cleary', 'Republic of Ireland', 'cleary'),
	('Paul Cleary', 'Republic of Ireland', 'paul cleary'),
	('Denis Rusu', 'Romania', 'denis rusu'),
	('Denis Rusu', 'Romania', 'rusu'),
	('Alexis Antunes', 'Switzerland', 'alexis antunes'),
	('Alexis Antunes', 'Switzerland', 'antunes'),
	('Lars Dendoncker', 'Belgium', 'lars dendoncker'),
	('Lars Dendoncker', 'Belgium', 'dendoncker'),
	('Blondy Nna Noukeu', 'Cameroon', 'blondy nna noukeu'),
	('Blondy Nna Noukeu', 'Cameroon', 'noukeu'),
	('Bogdan Balint', 'Romania', 'bogdan balint'),
	('Bogdan Balint', 'Romania', 'balint'),
	('Aleksander Pawlak', 'Poland', 'aleksander pawlak'),
	('Aleksander Pawlak', 'Poland', 'pawlak'),
	('Ben Dempsey', 'England', 'dempsey'),
	('Ben Dempsey', 'England', 'ben dempsey'),
	('Mauro Rodrigues', 'Portugal', 'rodrigues'),
	('Mauro Rodrigues', 'Portugal', 'mauro rodrigues'),
	('Miles Mitchell-Nelson', 'England', 'miles mitchellnelson'),
	('Miles Mitchell-Nelson', 'England', 'mitchellnelson'),
	('Tom Amos', 'Sweden', 'tom amos'),
	('Tom Amos', 'Sweden', 'amos'),
	('Jacob Ramsey', 'England', 'jacob ramsey'),
	('Jacob Ramsey', 'England', 'ramsey'),
	('David Longe-King', 'England', 'david longeking'),
	('David Longe-King', 'England', 'longeking'),
	('Jordon Thompson', 'England', 'jordon thompson'),
	('Jordon Thompson', 'England', 'thompson'),
	('Jamie Roche', 'Sweden', 'roche'),
	('Jamie Roche', 'Sweden', 'jamie roche'),
	('Taylor Curran', 'England', 'taylor curran'),
	('Taylor Curran', 'England', 'curran'),
	('Nahum Melvin-Lambert', 'England', 'melvinlambert'),
	('Nahum Melvin-Lambert', 'England', 'nahum melvinlambert'),
	('Azad Toptik', 'Turkey', 'toptik'),
	('Azad Toptik', 'Turkey', 'azad toptik'),
	('Marius Pahonțu', 'Romania', 'marius pahontu'),
	('Marius Pahonțu', 'Romania', 'pahontu'),
	('Matthew Garbett', 'New Zealand', 'matthew garbett'),
	('Matthew Garbett', 'New Zealand', 'garbett'),
	('Isak Helstad Amundsen', 'Norway', 'amundsen'),
	('Isak Helstad Amundsen', 'Norway', 'isak helstad amundsen'),
	('Rio Adebisi', 'England', 'adebisi'),
	('Rio Adebisi', 'England', 'rio adebisi'),
	('Abdullah Nasser', 'Saudi Arabia', 'nasser'),
	('Abdullah Nasser', 'Saudi Arabia', 'abdullah nasser'),
	('Saleh Al Nashmi', 'Saudi Arabia', 'saleh al nashmi'),
	('Saleh Al Nashmi', 'Saudi Arabia', 'nashmi'),
	('Colin McCabe', 'Republic of Ireland', 'mccabe'),
	('Colin McCabe', 'Republic of Ireland', 'colin mccabe'),
	('Konrad Sieracki', 'Poland', 'sieracki'),
	('Konrad Sieracki', 'Poland', 'konrad sieracki'),
	('Josh Key', 'England', 'key'),
	('Josh Key', 'England', 'josh key'),
	('Dennis Collander', 'Sweden', 'dennis collander'),
	('Dennis Collander', 'Sweden', 'collander'),
	('Ibrahim Al Baraka', 'Saudi Arabia', 'baraka'),
	('Ibrahim Al Baraka', 'Saudi Arabia', 'ibrahim al baraka'),
	('Cameron Gregory', 'England', 'gregory'),
	('Cameron Gregory', 'England', 'cameron gregory'),
	('Trey Muse', 'United States', 'trey muse'),
	('Trey Muse', 'United States', 'muse'),
	('Halil İbrahim Sevinç', 'Turkey', 'sevinc'),
	('Halil İbrahim Sevinç', 'Turkey', 'halil ibrahim sevinc'),
	('Scott Twine', 'England', 'twine'),
	('Scott Twine', 'England', 'scott twine'),
	('Zhao Yingjie', 'China PR', 'yingjie'),
	('Zhao Yingjie', 'China PR', 'zhao yingjie'),
	('Tanner Beason', 'United States', 'beason'),
	('Tanner Beason', 'United States', 'tanner beason'),
	('Yuan Ye', 'China PR', 'ye'),
	('Yuan Ye', 'China PR', 'yuan ye'),
	('Cosmin Atanase', 'Romania', 'atanase'),
	('Cosmin Atanase', 'Romania', 'cosmin atanase'),
	('Haji Mnoga', 'England', 'mnoga'),
	('Haji Mnoga', 'England', 'haji mnoga'),
	('Henry Ochieng', 'Kenya', 'henry ochieng'),
	('Henry Ochieng', 'Kenya', 'ochieng'),
	('Kieron Evans', 'Wales', 'kieron evans'),
	('Kieron Evans', 'Wales', 'evans'),
	('Ronan Hurley', 'Republic of Ireland', 'hurley'),
	('Ronan Hurley', 'Republic of Ireland', 'ronan hurley'),
	('Shi Chenglong', 'China PR', 'shi chenglong'),
	('Shi Chenglong', 'China PR', 'chenglong'),
	('Andrés Llinás', 'Colombia', 'llinas'),
	('Andrés Llinás', 'Colombia', 'andres llinas'),
	('Ashvin Balaruban', 'Switzerland', 'ashvin balaruban'),
	('Ashvin Balaruban', 'Switzerland', 'balaruban'),
	('Ryan Burke', 'Republic of Ireland', 'ryan burke'),
	('Ryan Burke', 'Republic of Ireland', 'burke'),
	('Brandon Lauton', 'Australia', 'lauton'),
	('Brandon Lauton', 'Australia', 'brandon lauton'),
	('Matthew Alexander', 'England', 'alexander'),
	('Matthew Alexander', 'England', 'matthew alexander'),
	('Juan Diego Ospina', 'Colombia', 'ospina'),
	('Juan Diego Ospina', 'Colombia', 'juan diego ospina'),
	('Abduhamit Abdugheni', 'China PR', 'abdugheni'),
	('Abduhamit Abdugheni', 'China PR', 'abduhamit abdugheni'),
	('Gerson Vázquez', 'Mexico', 'vazquez'),
	('Gerson Vázquez', 'Mexico', 'gerson vazquez'),
	('Aygün Duman', 'Turkey', 'duman'),
	('Aygün Duman', 'Turkey', 'aygun duman'),
	('Kim Jae Woo', 'Korea Republic', 'woo'),
	('Kim Jae Woo', 'Korea Republic', 'kim jae woo'),
	('Finn Azaz', 'England', 'finn azaz'),
	('Finn Azaz', 'England', 'azaz'),
	('Fidel Ambríz', 'Mexico', 'fidel ambriz'),
	('Fidel Ambríz', 'Mexico', 'ambriz'),
	('Phoenix Missi Tomp', 'Cameroon', 'tomp'),
	('Phoenix Missi Tomp', 'Cameroon', 'phoenix missi tomp'),
	('Abdoul Yoda', 'Burkina Faso', 'yoda'),
	('Abdoul Yoda', 'Burkina Faso', 'abdoul yoda'),
	('Choe Pil Soo', 'Korea Republic', 'soo'),
	('Choe Pil Soo', 'Korea Republic', 'choe pil soo'),
	('Ionuț Rus', 'Romania', 'rus'),
	('Ionuț Rus', 'Romania', 'ionut rus'),
	('Fabricio Correa', 'Uruguay', 'fabricio correa'),
	('Fabricio Correa', 'Uruguay', 'correa'),
	('Job Froeling', 'Netherlands', 'froeling'),
	('Job Froeling', 'Netherlands', 'job froeling'),
	('Taylor Perry', 'England', 'taylor perry'),
	('Taylor Perry', 'England', 'perry'),
	('Yusong Ni', 'China PR', 'yusong ni'),
	('Yusong Ni', 'China PR', 'ni'),
	('Ferddy Roca', 'Bolivia', 'ferddy roca'),
	('Ferddy Roca', 'Bolivia', 'roca'),
	('Carlo Armiento', 'Australia', 'armiento'),
	('Carlo Armiento', 'Australia', 'carlo armiento'),
	('Novem Baumann', 'Switzerland', 'baumann'),
	('Novem Baumann', 'Switzerland', 'novem baumann'),
	('Carlos Cortes', 'Colombia', 'carlos cortes'),
	('Carlos Cortes', 'Colombia', 'cortes'),
	('Josh Atencio', 'United States', 'atencio'),
	('Josh Atencio', 'United States', 'josh atencio'),
	('Lee Joon Suk', 'Korea Republic', 'lee joon suk'),
	('Lee Joon Suk', 'Korea Republic', 'suk'),
	('Alex Perry', 'England', 'alex perry'),
	('Alex Perry', 'England', 'perry'),
	('Sam Bowen', 'Wales', 'bowen'),
	('Sam Bowen', 'Wales', 'sam bowen'),
	('Jairo Uscamayta', 'Peru', 'uscamayta'),
	('Jairo Uscamayta', 'Peru', 'jairo uscamayta'),
	('Jake Dunwoody', 'Northern Ireland', 'dunwoody'),
	('Jake Dunwoody', 'Northern Ireland', 'jake dunwoody'),
	('Daniel Björkman', 'Sweden', 'bjorkman'),
	('Daniel Björkman', 'Sweden', 'daniel bjorkman'),
	('Jiang Wenjun', 'China PR', 'jiang wenjun'),
	('Jiang Wenjun', 'China PR', 'wenjun'),
	('Wojciech Błyszko', 'Poland', 'wojciech byszko'),
	('Wojciech Błyszko', 'Poland', 'byszko'),
	('Peter Urminsky', 'Slovakia', 'urminsky'),
	('Peter Urminsky', 'Slovakia', 'peter urminsky'),
	('Sagir Arce', 'United States', 'sagir arce'),
	('Sagir Arce', 'United States', 'arce'),
	('Mirza Muratovic', 'Australia', 'muratovic'),
	('Mirza Muratovic', 'Australia', 'mirza muratovic'),
	('Park Jae Hun', 'Korea Republic', 'park jae hun'),
	('Park Jae Hun', 'Korea Republic', 'hun'),
	('Hussain Salem', 'Saudi Arabia', 'salem'),
	('Hussain Salem', 'Saudi Arabia', 'hussain salem'),
	('Simon Gollnack', 'Germany', 'simon gollnack'),
	('Simon Gollnack', 'Germany', 'gollnack'),
	('Jordan Gibson', 'England', 'gibson'),
	('Jordan Gibson', 'England', 'jordan gibson'),
	('Lorcan Fitzgerald', 'Republic of Ireland', 'lorcan fitzgerald'),
	('Lorcan Fitzgerald', 'Republic of Ireland', 'fitzgerald'),
	('Lee Joon Hee', 'Korea Republic', 'hee'),
	('Lee Joon Hee', 'Korea Republic', 'lee joon hee'),
	('Yahya Kalley', 'Sweden', 'kalley'),
	('Yahya Kalley', 'Sweden', 'yahya kalley'),
	('Ísak Óli Ólafsson', 'Iceland', 'isak oli olafsson'),
	('Ísak Óli Ólafsson', 'Iceland', 'olafsson'),
	('Torben Rhein', 'Germany', 'rhein'),
	('Torben Rhein', 'Germany', 'torben rhein'),
	('Omar Reyes', 'Peru', 'omar reyes'),
	('Omar Reyes', 'Peru', 'reyes'),
	('Adrian Delap', 'Republic of Ireland', 'delap'),
	('Adrian Delap', 'Republic of Ireland', 'adrian delap'),
	('Goh Young Jun', 'Korea Republic', 'goh young jun'),
	('Goh Young Jun', 'Korea Republic', 'jun'),
	('Zhou Junchen', 'China PR', 'zhou junchen'),
	('Zhou Junchen', 'China PR', 'junchen'),
	('Martin Majnovics', 'Hungary', 'martin majnovics'),
	('Martin Majnovics', 'Hungary', 'majnovics'),
	('Mariusz Fornalczyk', 'Poland', 'mariusz fornalczyk'),
	('Mariusz Fornalczyk', 'Poland', 'fornalczyk')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';