INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Nahuel Yeri', 'Argentina', 'player'),
	('Jesús Arrieta', 'Colombia', 'player'),
	('Lukas Spalvis', 'Lithuania', 'player'),
	('Anthony Ralston', 'Scotland', 'player'),
	('Aristote Nsiala', 'DR Congo', 'player'),
	('Daniel Morales', 'Peru', 'player'),
	('Scott Fraser', 'Scotland', 'player'),
	('Lorenzo Rajot', 'France', 'player'),
	('Javi Mier', 'Spain', 'player'),
	('Alexander Faltsetas', 'Sweden', 'player'),
	('Jordan Elsey', 'Australia', 'player'),
	('Ramiro Macagno', 'Argentina', 'player'),
	('Robert Gojani', 'Sweden', 'player'),
	('Gaztañaga', 'Spain', 'player'),
	('Rob Hall', 'England', 'player'),
	('Eriq Zavaleta', 'United States', 'player'),
	('Edinson Chávez', 'Peru', 'player'),
	('Tomáš Černý', 'Czech Republic', 'player'),
	('Jim-Patrick Müller', 'Germany', 'player'),
	('Will Smallbone', 'Republic of Ireland', 'player'),
	('Marco Lund', 'Denmark', 'player'),
	('Ryo Germain', 'Japan', 'player'),
	('Daniel Powell', 'England', 'player'),
	('Nicolás Albarracín', 'Uruguay', 'player'),
	('Cole Bassett', 'United States', 'player'),
	('Queensy Menig', 'Netherlands', 'player'),
	('Daisuke Suzuki', 'Japan', 'player'),
	('Mark Little', 'England', 'player'),
	('Nicklas Bärkroth', 'Sweden', 'player'),
	('Enzo Martínez', 'Uruguay', 'player'),
	('Luke Murphy', 'England', 'player'),
	('Won Du Jae', 'Korea Republic', 'player'),
	('Daniel Schütz', 'Austria', 'player'),
	('Jin Taiyan', 'China PR', 'player'),
	('George Cox', 'England', 'player'),
	('Abdulmalek Al Khaibari', 'Saudi Arabia', 'player'),
	('Harry Anderson', 'England', 'player'),
	('Abdullah Al Hafith', 'Saudi Arabia', 'player'),
	('Jason Lowe', 'England', 'player'),
	('Vesel Demaku', 'Austria', 'player'),
	('Samu Pérez', 'Spain', 'player'),
	('Christian Sánchez', 'Cuba', 'player'),
	('Agustín Canobbio', 'Uruguay', 'player'),
	('Andy Boyle', 'Republic of Ireland', 'player'),
	('Talal Al Absi', 'Saudi Arabia', 'player'),
	('Fernando Bersano', 'Argentina', 'player'),
	('Kevin Escamilla', 'Mexico', 'player'),
	('Stefan Rakowitz', 'Austria', 'player'),
	('Carrillo', 'Spain', 'player'),
	('Jakub Rzeźniczak', 'Poland', 'player'),
	('Lü Wenjun', 'China PR', 'player'),
	('Stefan Silva', 'Sweden', 'player'),
	('Brandt Bronico', 'United States', 'player'),
	('Patrick Weihrauch', 'Germany', 'player'),
	('Martin Röser', 'Germany', 'player'),
	('Dimitri Boudaud', 'France', 'player'),
	('Jorge Silva', 'Portugal', 'player'),
	('Lee Myung Jae', 'Korea Republic', 'player'),
	('Léo Sena', 'Brazil', 'player'),
	('Edgar Castillo', 'United States', 'player'),
	('Nnamdi Ofoborh', 'Nigeria', 'player'),
	('Andújar', 'Spain', 'player'),
	('Darren Maatsen', 'Netherlands', 'player'),
	('Julián Benítez', 'Paraguay', 'player'),
	('Amir Kurdi', 'Saudi Arabia', 'player'),
	('Matty Blair', 'England', 'player'),
	('Mike-Steven Bähre', 'Germany', 'player'),
	('Christian Schoissengeyr', 'Austria', 'player'),
	('Jean Cléber', 'Brazil', 'player'),
	('Facundo Pérez', 'Argentina', 'player'),
	('Ryan Williams', 'Australia', 'player'),
	('Johan Hove', 'Norway', 'player'),
	('Yamato Machida', 'Japan', 'player'),
	('Jorge Corrales', 'Cuba', 'player'),
	('Omar Arellano', 'Mexico', 'player'),
	('Tachi', 'Spain', 'player'),
	('Nassim Boujellab', 'Morocco', 'player'),
	('Salvatore Molina', 'Italy', 'player'),
	('Sam Kersten', 'Netherlands', 'player'),
	('Javier Rojas', 'Bolivia', 'player'),
	('Jake Hessenthaler', 'England', 'player'),
	('Bjørn Inge Utvik', 'Norway', 'player'),
	('Ro-Shaun Williams', 'England', 'player'),
	('Facundo Kidd', 'Uruguay', 'player'),
	('Adrian Lis', 'Poland', 'player'),
	('Nam Joon Jae', 'Korea Republic', 'player'),
	('Aaron Berzel', 'Germany', 'player'),
	('Nick Bakker', 'Netherlands', 'player'),
	('Sebastián Galindo', 'Bolivia', 'player'),
	('Darron Gibson', 'Republic of Ireland', 'player'),
	('Tarsis Bonga', 'Germany', 'player'),
	('Youssouph Badji', 'Senegal', 'player'),
	('Ilya Shkurin', 'Belarus', 'player'),
	('Shaquille Pinas', 'Netherlands', 'player'),
	('Zachary Brault-Guillard', 'Canada', 'player'),
	('Özer Özdemir', 'Turkey', 'player'),
	('Emyr Huws', 'Wales', 'player'),
	('Nathanaël Mbuku', 'France', 'player'),
	('Andrew Nabbout', 'Australia', 'player'),
	('Valdet Rama', 'Albania', 'player'),
	('Max Ehmer', 'Germany', 'player'),
	('Timo Kern', 'Germany', 'player'),
	('Viv Solomon-Otabor', 'Nigeria', 'player'),
	('Roman Kerschbaum', 'Austria', 'player'),
	('Matteo Fedele', 'Switzerland', 'player'),
	('Liao Lisheng', 'China PR', 'player'),
	('Luis Pavia', 'Bolivia', 'player'),
	('Andy Cannon', 'England', 'player'),
	('Ricardo Andreutti', 'Venezuela', 'player'),
	('Aygün Yildirim', 'Germany', 'player'),
	('Dong Xuesheng', 'China PR', 'player'),
	('Callum Booth', 'Scotland', 'player'),
	('Juande', 'Spain', 'player'),
	('Olivier Myny', 'Belgium', 'player'),
	('Ricardinho', 'Portugal', 'player'),
	('Yorwin Lobo', 'Venezuela', 'player'),
	('Kamil Piątkowski', 'Poland', 'player'),
	('Fu Huan', 'China PR', 'player'),
	('Shunsuke Nakamura', 'Japan', 'player'),
	('Oshiro Takeuchi', 'Peru', 'player'),
	('Jorge Padilla', 'Spain', 'player'),
	('Omar Haktab Traoré', 'Germany', 'player'),
	('Seth Sinovic', 'United States', 'player'),
	('Damian Michalski', 'Poland', 'player'),
	('Luke Woolfenden', 'England', 'player'),
	('Abdullah Al Shamekh', 'Saudi Arabia', 'player'),
	('Sascha Kotysch', 'Germany', 'player'),
	('Maximilian Wolfram', 'Germany', 'player'),
	('Nicolas Kühn', 'Germany', 'player'),
	('Finn Ole Becker', 'Germany', 'player'),
	('Sören Bertram', 'Germany', 'player'),
	('Will Norris', 'England', 'player'),
	('Kristoffer Klaesson', 'Norway', 'player'),
	('Omenuke Mfulu', 'DR Congo', 'player'),
	('Viðar Ari Jónsson', 'Iceland', 'player'),
	('Christoph Greger', 'Germany', 'player'),
	('Germán Guiffrey', 'Argentina', 'player'),
	('Lucas Da Cunha', 'France', 'player'),
	('Martín Rabuñal', 'Uruguay', 'player'),
	('Milson', 'Angola', 'player'),
	('Scotty Sadzoute', 'France', 'player'),
	('Christian Beck', 'Germany', 'player'),
	('Ryan Haynes', 'England', 'player'),
	('Hazaa Al Hazaa', 'Saudi Arabia', 'player'),
	('Adrián Luna', 'Uruguay', 'player'),
	('Ronan', 'Brazil', 'player'),
	('Fabian Holthaus', 'Germany', 'player'),
	('Daniel Batz', 'Germany', 'player'),
	('Gabriel Risso Patrón', 'Argentina', 'player'),
	('Alessandro Albanese', 'Belgium', 'player'),
	('Tom James', 'Wales', 'player'),
	('Ashley Hunter', 'England', 'player'),
	('Maximiliano Caufriez', 'Belgium', 'player'),
	('Kosuke Shirai', 'Japan', 'player'),
	('Sotillos', 'Spain', 'player'),
	('Damian Zbozień', 'Poland', 'player'),
	('Lucas Rougeaux', 'France', 'player'),
	('Oniel Fisher', 'Jamaica', 'player'),
	('Ajdin Hasić', 'Bosnia Herzegovina', 'player'),
	('Mario-Jason Kikonda', 'France', 'player'),
	('Sindrit Guri', 'Albania', 'player'),
	('Alexis Hinestroza', 'Colombia', 'player'),
	('Michael Jakobsen', 'Denmark', 'player'),
	('Cristian Núñez', 'Paraguay', 'player'),
	('Tom Anderson', 'England', 'player'),
	('Emanuel Ojeda', 'Argentina', 'player'),
	('Javier Iritier', 'Argentina', 'player'),
	('Michel Niemeyer', 'Germany', 'player'),
	('Jorge Luis Aguilar', 'Paraguay', 'player'),
	('Iñaki Peña', 'Spain', 'player'),
	('Emiliano Mozzone', 'Uruguay', 'player'),
	('Felix Dornebusch', 'Germany', 'player'),
	('Edson Gutiérrez', 'Mexico', 'player'),
	('Song Min Kyu', 'Korea Republic', 'player'),
	('Cordero', 'Spain', 'player'),
	('Amine Benchaib', 'Belgium', 'player'),
	('He Guan', 'China PR', 'player'),
	('Pius Dorn', 'Germany', 'player'),
	('Alexandru Tudorie', 'Romania', 'player'),
	('Peter Vindahl Jensen', 'Denmark', 'player'),
	('Julian Faye Lund', 'Norway', 'player'),
	('James Talbot', 'Republic of Ireland', 'player'),
	('Ebenezer Assifuah', 'Ghana', 'player'),
	('Macauley Bonne', 'Zimbabwe', 'player'),
	('Hans Nunoo Sarpei', 'Ghana', 'player'),
	('Damien Dussaut', 'France', 'player'),
	('Enrique Palos', 'Mexico', 'player'),
	('Hendrick Zuck', 'Germany', 'player'),
	('Jamie Hanson', 'England', 'player'),
	('Jaime Arrascaita', 'Bolivia', 'player'),
	('Leonardo Campana', 'Ecuador', 'player'),
	('Robin Jansson', 'Sweden', 'player'),
	('Gabriel Compagnucci', 'Argentina', 'player'),
	('Liam Shephard', 'Wales', 'player'),
	('Jamie Robson', 'Scotland', 'player'),
	('Valdo', 'Brazil', 'player'),
	('Tsiy-William Ndenge', 'Germany', 'player'),
	('Tonny Brochmann', 'Denmark', 'player'),
	('Maguinho', 'Brazil', 'player'),
	('Franco Costa', 'Argentina', 'player'),
	('Julian Araujo', 'United States', 'player'),
	('Takuo Okubo', 'Japan', 'player'),
	('Gabriel Debeljuh', 'Croatia', 'player'),
	('Claude Gonçalves', 'Portugal', 'player'),
	('Cristhian Machado', 'Bolivia', 'player'),
	('Tosin Kehinde', 'Nigeria', 'player'),
	('Sebastian Bösel', 'Germany', 'player'),
	('Alfonso Trezza', 'Uruguay', 'player'),
	('Alexis Messidoro', 'Argentina', 'player'),
	('Ryo Okui', 'Japan', 'player'),
	('Gilbert Álvarez', 'Bolivia', 'player'),
	('Carlos Isaac', 'Spain', 'player'),
	('Lee Nicholls', 'England', 'player'),
	('Andrei Cristea', 'Romania', 'player'),
	('Luis Mena', 'Colombia', 'player'),
	('Thomas Mikkelsen', 'Denmark', 'player'),
	('Kai Shibato', 'Japan', 'player'),
	('Eoghan O''Connell', 'Republic of Ireland', 'player'),
	('Simone Lo Faso', 'Italy', 'player'),
	('Mukhtar Ali', 'Saudi Arabia', 'player'),
	('Jake Buxton', 'England', 'player'),
	('Aaron McGowan', 'England', 'player'),
	('Miro Muheim', 'Switzerland', 'player'),
	('Theofanis Mavrommatis', 'Greece', 'player'),
	('Jaden Brown', 'England', 'player'),
	('Jeremy Márquez', 'Mexico', 'player'),
	('Valera', 'Spain', 'player'),
	('Meschack Elia', 'DR Congo', 'player'),
	('Koo Dae Young', 'Korea Republic', 'player'),
	('Clément Diop', 'Senegal', 'player'),
	('Sebastián Gorga', 'Uruguay', 'player'),
	('Ismaila Coulibaly', 'Mali', 'player'),
	('José Yegüez', 'Venezuela', 'player'),
	('Anthony van den Hurk', 'Curacao', 'player'),
	('Wang Tong', 'China PR', 'player'),
	('Mohammed Qasem', 'Saudi Arabia', 'player'),
	('Ângelo Taveira', 'Portugal', 'player'),
	('Ángel García', 'Spain', 'player'),
	('Derrick Etienne Jr.', 'Haiti', 'player'),
	('Kennedy Boateng', 'Ghana', 'player'),
	('Djihad Bizimana', 'Rwanda', 'player'),
	('Agustín Ale', 'Uruguay', 'player'),
	('Benedikt Röcker', 'Germany', 'player'),
	('Juan Sánchez Sotelo', 'Argentina', 'player'),
	('Wesley Jobello', 'France', 'player'),
	('Cheick Timite', 'Ivory Coast', 'player'),
	('Vladimir Golemić', 'Serbia', 'player'),
	('Sercan Sararer', 'Turkey', 'player'),
	('Samuel Galindo', 'Bolivia', 'player'),
	('Yhonathan Yustiz', 'Venezuela', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Nahuel Yeri', 'Argentina', 'nahuel yeri'),
	('Nahuel Yeri', 'Argentina', 'yeri'),
	('Jesús Arrieta', 'Colombia', 'jesus arrieta'),
	('Jesús Arrieta', 'Colombia', 'arrieta'),
	('Lukas Spalvis', 'Lithuania', 'spalvis'),
	('Lukas Spalvis', 'Lithuania', 'lukas spalvis'),
	('Anthony Ralston', 'Scotland', 'ralston'),
	('Anthony Ralston', 'Scotland', 'anthony ralston'),
	('Aristote Nsiala', 'DR Congo', 'nsiala'),
	('Aristote Nsiala', 'DR Congo', 'aristote nsiala'),
	('Daniel Morales', 'Peru', 'daniel morales'),
	('Daniel Morales', 'Peru', 'morales'),
	('Scott Fraser', 'Scotland', 'scott fraser'),
	('Scott Fraser', 'Scotland', 'fraser'),
	('Lorenzo Rajot', 'France', 'rajot'),
	('Lorenzo Rajot', 'France', 'lorenzo rajot'),
	('Javi Mier', 'Spain', 'mier'),
	('Javi Mier', 'Spain', 'javi mier'),
	('Alexander Faltsetas', 'Sweden', 'alexander faltsetas'),
	('Alexander Faltsetas', 'Sweden', 'faltsetas'),
	('Jordan Elsey', 'Australia', 'elsey'),
	('Jordan Elsey', 'Australia', 'jordan elsey'),
	('Ramiro Macagno', 'Argentina', 'ramiro macagno'),
	('Ramiro Macagno', 'Argentina', 'macagno'),
	('Robert Gojani', 'Sweden', 'gojani'),
	('Robert Gojani', 'Sweden', 'robert gojani'),
	('Gaztañaga', 'Spain', 'gaztanaga'),
	('Rob Hall', 'England', 'rob hall'),
	('Rob Hall', 'England', 'hall'),
	('Eriq Zavaleta', 'United States', 'eriq zavaleta'),
	('Eriq Zavaleta', 'United States', 'zavaleta'),
	('Edinson Chávez', 'Peru', 'edinson chavez'),
	('Edinson Chávez', 'Peru', 'chavez'),
	('Tomáš Černý', 'Czech Republic', 'cerny'),
	('Tomáš Černý', 'Czech Republic', 'tomas cerny'),
	('Jim-Patrick Müller', 'Germany', 'muller'),
	('Jim-Patrick Müller', 'Germany', 'jimpatrick muller'),
	('Will Smallbone', 'Republic of Ireland', 'smallbone'),
	('Will Smallbone', 'Republic of Ireland', 'will smallbone'),
	('Marco Lund', 'Denmark', 'marco lund'),
	('Marco Lund', 'Denmark', 'lund'),
	('Ryo Germain', 'Japan', 'ryo germain'),
	('Ryo Germain', 'Japan', 'germain'),
	('Daniel Powell', 'England', 'powell'),
	('Daniel Powell', 'England', 'daniel powell'),
	('Nicolás Albarracín', 'Uruguay', 'nicolas albarracin'),
	('Nicolás Albarracín', 'Uruguay', 'albarracin'),
	('Cole Bassett', 'United States', 'bassett'),
	('Cole Bassett', 'United States', 'cole bassett'),
	('Queensy Menig', 'Netherlands', 'menig'),
	('Queensy Menig', 'Netherlands', 'queensy menig'),
	('Daisuke Suzuki', 'Japan', 'daisuke suzuki'),
	('Daisuke Suzuki', 'Japan', 'suzuki'),
	('Mark Little', 'England', 'mark little'),
	('Mark Little', 'England', 'little'),
	('Nicklas Bärkroth', 'Sweden', 'nicklas barkroth'),
	('Nicklas Bärkroth', 'Sweden', 'barkroth'),
	('Enzo Martínez', 'Uruguay', 'martinez'),
	('Enzo Martínez', 'Uruguay', 'enzo martinez'),
	('Luke Murphy', 'England', 'murphy'),
	('Luke Murphy', 'England', 'luke murphy'),
	('Won Du Jae', 'Korea Republic', 'won du jae'),
	('Won Du Jae', 'Korea Republic', 'jae'),
	('Daniel Schütz', 'Austria', 'daniel schutz'),
	('Daniel Schütz', 'Austria', 'schutz'),
	('Jin Taiyan', 'China PR', 'jin taiyan'),
	('Jin Taiyan', 'China PR', 'taiyan'),
	('George Cox', 'England', 'george cox'),
	('George Cox', 'England', 'cox'),
	('Abdulmalek Al Khaibari', 'Saudi Arabia', 'abdulmalek al khaibari'),
	('Abdulmalek Al Khaibari', 'Saudi Arabia', 'khaibari'),
	('Harry Anderson', 'England', 'harry anderson'),
	('Harry Anderson', 'England', 'anderson'),
	('Abdullah Al Hafith', 'Saudi Arabia', 'abdullah al hafith'),
	('Abdullah Al Hafith', 'Saudi Arabia', 'hafith'),
	('Jason Lowe', 'England', 'jason lowe'),
	('Jason Lowe', 'England', 'lowe'),
	('Vesel Demaku', 'Austria', 'demaku'),
	('Vesel Demaku', 'Austria', 'vesel demaku'),
	('Samu Pérez', 'Spain', 'perez'),
	('Samu Pérez', 'Spain', 'samu perez'),
	('Christian Sánchez', 'Cuba', 'christian sanchez'),
	('Christian Sánchez', 'Cuba', 'sanchez'),
	('Agustín Canobbio', 'Uruguay', 'canobbio'),
	('Agustín Canobbio', 'Uruguay', 'agustin canobbio'),
	('Andy Boyle', 'Republic of Ireland', 'boyle'),
	('Andy Boyle', 'Republic of Ireland', 'andy boyle'),
	('Talal Al Absi', 'Saudi Arabia', 'talal al absi'),
	('Talal Al Absi', 'Saudi Arabia', 'absi'),
	('Fernando Bersano', 'Argentina', 'bersano'),
	('Fernando Bersano', 'Argentina', 'fernando bersano'),
	('Kevin Escamilla', 'Mexico', 'escamilla'),
	('Kevin Escamilla', 'Mexico', 'kevin escamilla'),
	('Stefan Rakowitz', 'Austria', 'stefan rakowitz'),
	('Stefan Rakowitz', 'Austria', 'rakowitz'),
	('Carrillo', 'Spain', 'carrillo'),
	('Jakub Rzeźniczak', 'Poland', 'jakub rzezniczak'),
	('Jakub Rzeźniczak', 'Poland', 'rzezniczak'),
	('Lü Wenjun', 'China PR', 'lu wenjun'),
	('Lü Wenjun', 'China PR', 'wenjun'),
	('Stefan Silva', 'Sweden', 'silva'),
	('Stefan Silva', 'Sweden', 'stefan silva'),
	('Brandt Bronico', 'United States', 'bronico'),
	('Brandt Bronico', 'United States', 'brandt bronico'),
	('Patrick Weihrauch', 'Germany', 'patrick weihrauch'),
	('Patrick Weihrauch', 'Germany', 'weihrauch'),
	('Martin Röser', 'Germany', 'roser'),
	('Martin Röser', 'Germany', 'martin roser'),
	('Dimitri Boudaud', 'France', 'dimitri boudaud'),
	('Dimitri Boudaud', 'France', 'boudaud'),
	('Jorge Silva', 'Portugal', 'silva'),
	('Jorge Silva', 'Portugal', 'jorge silva'),
	('Lee Myung Jae', 'Korea Republic', 'jae'),
	('Lee Myung Jae', 'Korea Republic', 'lee myung jae'),
	('Léo Sena', 'Brazil', 'leo sena'),
	('Léo Sena', 'Brazil', 'sena'),
	('Edgar Castillo', 'United States', 'edgar castillo'),
	('Edgar Castillo', 'United States', 'castillo'),
	('Nnamdi Ofoborh', 'Nigeria', 'nnamdi ofoborh'),
	('Nnamdi Ofoborh', 'Nigeria', 'ofoborh'),
	('Andújar', 'Spain', 'andujar'),
	('Darren Maatsen', 'Netherlands', 'darren maatsen'),
	('Darren Maatsen', 'Netherlands', 'maatsen'),
	('Julián Benítez', 'Paraguay', 'julian benitez'),
	('Julián Benítez', 'Paraguay', 'benitez'),
	('Amir Kurdi', 'Saudi Arabia', 'kurdi'),
	('Amir Kurdi', 'Saudi Arabia', 'amir kurdi'),
	('Matty Blair', 'England', 'blair'),
	('Matty Blair', 'England', 'matty blair'),
	('Mike-Steven Bähre', 'Germany', 'mikesteven bahre'),
	('Mike-Steven Bähre', 'Germany', 'bahre'),
	('Christian Schoissengeyr', 'Austria', 'christian schoissengeyr'),
	('Christian Schoissengeyr', 'Austria', 'schoissengeyr'),
	('Jean Cléber', 'Brazil', 'cleber'),
	('Jean Cléber', 'Brazil', 'jean cleber'),
	('Facundo Pérez', 'Argentina', 'facundo perez'),
	('Facundo Pérez', 'Argentina', 'perez'),
	('Ryan Williams', 'Australia', 'ryan williams'),
	('Ryan Williams', 'Australia', 'williams'),
	('Johan Hove', 'Norway', 'johan hove'),
	('Johan Hove', 'Norway', 'hove'),
	('Yamato Machida', 'Japan', 'yamato machida'),
	('Yamato Machida', 'Japan', 'machida'),
	('Jorge Corrales', 'Cuba', 'jorge corrales'),
	('Jorge Corrales', 'Cuba', 'corrales'),
	('Omar Arellano', 'Mexico', 'arellano'),
	('Omar Arellano', 'Mexico', 'omar arellano'),
	('Tachi', 'Spain', 'tachi'),
	('Nassim Boujellab', 'Morocco', 'nassim boujellab'),
	('Nassim Boujellab', 'Morocco', 'boujellab'),
	('Salvatore Molina', 'Italy', 'salvatore molina'),
	('Salvatore Molina', 'Italy', 'molina'),
	('Sam Kersten', 'Netherlands', 'sam kersten'),
	('Sam Kersten', 'Netherlands', 'kersten'),
	('Javier Rojas', 'Bolivia', 'javier rojas'),
	('Javier Rojas', 'Bolivia', 'rojas'),
	('Jake Hessenthaler', 'England', 'hessenthaler'),
	('Jake Hessenthaler', 'England', 'jake hessenthaler'),
	('Bjørn Inge Utvik', 'Norway', 'bjrn inge utvik'),
	('Bjørn Inge Utvik', 'Norway', 'utvik'),
	('Ro-Shaun Williams', 'England', 'roshaun williams'),
	('Ro-Shaun Williams', 'England', 'williams'),
	('Facundo Kidd', 'Uruguay', 'kidd'),
	('Facundo Kidd', 'Uruguay', 'facundo kidd'),
	('Adrian Lis', 'Poland', 'adrian lis'),
	('Adrian Lis', 'Poland', 'lis'),
	('Nam Joon Jae', 'Korea Republic', 'nam joon jae'),
	('Nam Joon Jae', 'Korea Republic', 'jae'),
	('Aaron Berzel', 'Germany', 'aaron berzel'),
	('Aaron Berzel', 'Germany', 'berzel'),
	('Nick Bakker', 'Netherlands', 'bakker'),
	('Nick Bakker', 'Netherlands', 'nick bakker'),
	('Sebastián Galindo', 'Bolivia', 'sebastian galindo'),
	('Sebastián Galindo', 'Bolivia', 'galindo'),
	('Darron Gibson', 'Republic of Ireland', 'gibson'),
	('Darron Gibson', 'Republic of Ireland', 'darron gibson'),
	('Tarsis Bonga', 'Germany', 'bonga'),
	('Tarsis Bonga', 'Germany', 'tarsis bonga'),
	('Youssouph Badji', 'Senegal', 'youssouph badji'),
	('Youssouph Badji', 'Senegal', 'badji'),
	('Ilya Shkurin', 'Belarus', 'shkurin'),
	('Ilya Shkurin', 'Belarus', 'ilya shkurin'),
	('Shaquille Pinas', 'Netherlands', 'shaquille pinas'),
	('Shaquille Pinas', 'Netherlands', 'pinas'),
	('Zachary Brault-Guillard', 'Canada', 'braultguillard'),
	('Zachary Brault-Guillard', 'Canada', 'zachary braultguillard'),
	('Özer Özdemir', 'Turkey', 'ozdemir'),
	('Özer Özdemir', 'Turkey', 'ozer ozdemir'),
	('Emyr Huws', 'Wales', 'huws'),
	('Emyr Huws', 'Wales', 'emyr huws'),
	('Nathanaël Mbuku', 'France', 'nathanael mbuku'),
	('Nathanaël Mbuku', 'France', 'mbuku'),
	('Andrew Nabbout', 'Australia', 'nabbout'),
	('Andrew Nabbout', 'Australia', 'andrew nabbout'),
	('Valdet Rama', 'Albania', 'valdet rama'),
	('Valdet Rama', 'Albania', 'rama'),
	('Max Ehmer', 'Germany', 'ehmer'),
	('Max Ehmer', 'Germany', 'max ehmer'),
	('Timo Kern', 'Germany', 'timo kern'),
	('Timo Kern', 'Germany', 'kern'),
	('Viv Solomon-Otabor', 'Nigeria', 'viv solomonotabor'),
	('Viv Solomon-Otabor', 'Nigeria', 'solomonotabor'),
	('Roman Kerschbaum', 'Austria', 'kerschbaum'),
	('Roman Kerschbaum', 'Austria', 'roman kerschbaum'),
	('Matteo Fedele', 'Switzerland', 'fedele'),
	('Matteo Fedele', 'Switzerland', 'matteo fedele'),
	('Liao Lisheng', 'China PR', 'liao lisheng'),
	('Liao Lisheng', 'China PR', 'lisheng'),
	('Luis Pavia', 'Bolivia', 'luis pavia'),
	('Luis Pavia', 'Bolivia', 'pavia'),
	('Andy Cannon', 'England', 'andy cannon'),
	('Andy Cannon', 'England', 'cannon'),
	('Ricardo Andreutti', 'Venezuela', 'andreutti'),
	('Ricardo Andreutti', 'Venezuela', 'ricardo andreutti'),
	('Aygün Yildirim', 'Germany', 'yildirim'),
	('Aygün Yildirim', 'Germany', 'aygun yildirim'),
	('Dong Xuesheng', 'China PR', 'dong xuesheng'),
	('Dong Xuesheng', 'China PR', 'xuesheng'),
	('Callum Booth', 'Scotland', 'booth'),
	('Callum Booth', 'Scotland', 'callum booth'),
	('Juande', 'Spain', 'juande'),
	('Olivier Myny', 'Belgium', 'olivier myny'),
	('Olivier Myny', 'Belgium', 'myny'),
	('Ricardinho', 'Portugal', 'ricardinho'),
	('Yorwin Lobo', 'Venezuela', 'lobo'),
	('Yorwin Lobo', 'Venezuela', 'yorwin lobo'),
	('Kamil Piątkowski', 'Poland', 'piatkowski'),
	('Kamil Piątkowski', 'Poland', 'kamil piatkowski'),
	('Fu Huan', 'China PR', 'huan'),
	('Fu Huan', 'China PR', 'fu huan'),
	('Shunsuke Nakamura', 'Japan', 'shunsuke nakamura'),
	('Shunsuke Nakamura', 'Japan', 'nakamura'),
	('Oshiro Takeuchi', 'Peru', 'takeuchi'),
	('Oshiro Takeuchi', 'Peru', 'oshiro takeuchi'),
	('Jorge Padilla', 'Spain', 'padilla'),
	('Jorge Padilla', 'Spain', 'jorge padilla'),
	('Omar Haktab Traoré', 'Germany', 'traore'),
	('Omar Haktab Traoré', 'Germany', 'omar haktab traore'),
	('Seth Sinovic', 'United States', 'sinovic'),
	('Seth Sinovic', 'United States', 'seth sinovic'),
	('Damian Michalski', 'Poland', 'michalski'),
	('Damian Michalski', 'Poland', 'damian michalski'),
	('Luke Woolfenden', 'England', 'luke woolfenden'),
	('Luke Woolfenden', 'England', 'woolfenden'),
	('Abdullah Al Shamekh', 'Saudi Arabia', 'abdullah al shamekh'),
	('Abdullah Al Shamekh', 'Saudi Arabia', 'shamekh'),
	('Sascha Kotysch', 'Germany', 'sascha kotysch'),
	('Sascha Kotysch', 'Germany', 'kotysch'),
	('Maximilian Wolfram', 'Germany', 'wolfram'),
	('Maximilian Wolfram', 'Germany', 'maximilian wolfram'),
	('Nicolas Kühn', 'Germany', 'nicolas kuhn'),
	('Nicolas Kühn', 'Germany', 'kuhn'),
	('Finn Ole Becker', 'Germany', 'becker'),
	('Finn Ole Becker', 'Germany', 'finn ole becker'),
	('Sören Bertram', 'Germany', 'bertram'),
	('Sören Bertram', 'Germany', 'soren bertram'),
	('Will Norris', 'England', 'norris'),
	('Will Norris', 'England', 'will norris'),
	('Kristoffer Klaesson', 'Norway', 'kristoffer klaesson'),
	('Kristoffer Klaesson', 'Norway', 'klaesson'),
	('Omenuke Mfulu', 'DR Congo', 'mfulu'),
	('Omenuke Mfulu', 'DR Congo', 'omenuke mfulu'),
	('Viðar Ari Jónsson', 'Iceland', 'jonsson'),
	('Viðar Ari Jónsson', 'Iceland', 'viar ari jonsson'),
	('Christoph Greger', 'Germany', 'greger'),
	('Christoph Greger', 'Germany', 'christoph greger'),
	('Germán Guiffrey', 'Argentina', 'guiffrey'),
	('Germán Guiffrey', 'Argentina', 'german guiffrey'),
	('Lucas Da Cunha', 'France', 'cunha'),
	('Lucas Da Cunha', 'France', 'lucas da cunha'),
	('Martín Rabuñal', 'Uruguay', 'martin rabunal'),
	('Martín Rabuñal', 'Uruguay', 'rabunal'),
	('Milson', 'Angola', 'milson'),
	('Scotty Sadzoute', 'France', 'sadzoute'),
	('Scotty Sadzoute', 'France', 'scotty sadzoute'),
	('Christian Beck', 'Germany', 'christian beck'),
	('Christian Beck', 'Germany', 'beck'),
	('Ryan Haynes', 'England', 'haynes'),
	('Ryan Haynes', 'England', 'ryan haynes'),
	('Hazaa Al Hazaa', 'Saudi Arabia', 'hazaa al hazaa'),
	('Hazaa Al Hazaa', 'Saudi Arabia', 'hazaa'),
	('Adrián Luna', 'Uruguay', 'adrian luna'),
	('Adrián Luna', 'Uruguay', 'luna'),
	('Ronan', 'Brazil', 'ronan'),
	('Fabian Holthaus', 'Germany', 'fabian holthaus'),
	('Fabian Holthaus', 'Germany', 'holthaus'),
	('Daniel Batz', 'Germany', 'daniel batz'),
	('Daniel Batz', 'Germany', 'batz'),
	('Gabriel Risso Patrón', 'Argentina', 'patron'),
	('Gabriel Risso Patrón', 'Argentina', 'gabriel risso patron'),
	('Alessandro Albanese', 'Belgium', 'alessandro albanese'),
	('Alessandro Albanese', 'Belgium', 'albanese'),
	('Tom James', 'Wales', 'tom james'),
	('Tom James', 'Wales', 'james'),
	('Ashley Hunter', 'England', 'hunter'),
	('Ashley Hunter', 'England', 'ashley hunter'),
	('Maximiliano Caufriez', 'Belgium', 'maximiliano caufriez'),
	('Maximiliano Caufriez', 'Belgium', 'caufriez'),
	('Kosuke Shirai', 'Japan', 'shirai'),
	('Kosuke Shirai', 'Japan', 'kosuke shirai'),
	('Sotillos', 'Spain', 'sotillos'),
	('Damian Zbozień', 'Poland', 'zbozien'),
	('Damian Zbozień', 'Poland', 'damian zbozien'),
	('Lucas Rougeaux', 'France', 'lucas rougeaux'),
	('Lucas Rougeaux', 'France', 'rougeaux'),
	('Oniel Fisher', 'Jamaica', 'oniel fisher'),
	('Oniel Fisher', 'Jamaica', 'fisher'),
	('Ajdin Hasić', 'Bosnia Herzegovina', 'ajdin hasic'),
	('Ajdin Hasić', 'Bosnia Herzegovina', 'hasic'),
	('Mario-Jason Kikonda', 'France', 'kikonda'),
	('Mario-Jason Kikonda', 'France', 'mariojason kikonda'),
	('Sindrit Guri', 'Albania', 'sindrit guri'),
	('Sindrit Guri', 'Albania', 'guri'),
	('Alexis Hinestroza', 'Colombia', 'alexis hinestroza'),
	('Alexis Hinestroza', 'Colombia', 'hinestroza'),
	('Michael Jakobsen', 'Denmark', 'jakobsen'),
	('Michael Jakobsen', 'Denmark', 'michael jakobsen'),
	('Cristian Núñez', 'Paraguay', 'cristian nunez'),
	('Cristian Núñez', 'Paraguay', 'nunez'),
	('Tom Anderson', 'England', 'tom anderson'),
	('Tom Anderson', 'England', 'anderson'),
	('Emanuel Ojeda', 'Argentina', 'emanuel ojeda'),
	('Emanuel Ojeda', 'Argentina', 'ojeda'),
	('Javier Iritier', 'Argentina', 'iritier'),
	('Javier Iritier', 'Argentina', 'javier iritier'),
	('Michel Niemeyer', 'Germany', 'niemeyer'),
	('Michel Niemeyer', 'Germany', 'michel niemeyer'),
	('Jorge Luis Aguilar', 'Paraguay', 'jorge luis aguilar'),
	('Jorge Luis Aguilar', 'Paraguay', 'aguilar'),
	('Iñaki Peña', 'Spain', 'pena'),
	('Iñaki Peña', 'Spain', 'inaki pena'),
	('Emiliano Mozzone', 'Uruguay', 'mozzone'),
	('Emiliano Mozzone', 'Uruguay', 'emiliano mozzone'),
	('Felix Dornebusch', 'Germany', 'felix dornebusch'),
	('Felix Dornebusch', 'Germany', 'dornebusch'),
	('Edson Gutiérrez', 'Mexico', 'edson gutierrez'),
	('Edson Gutiérrez', 'Mexico', 'gutierrez'),
	('Song Min Kyu', 'Korea Republic', 'song min kyu'),
	('Song Min Kyu', 'Korea Republic', 'kyu'),
	('Cordero', 'Spain', 'cordero'),
	('Amine Benchaib', 'Belgium', 'benchaib'),
	('Amine Benchaib', 'Belgium', 'amine benchaib'),
	('He Guan', 'China PR', 'guan'),
	('He Guan', 'China PR', 'he guan'),
	('Pius Dorn', 'Germany', 'pius dorn'),
	('Pius Dorn', 'Germany', 'dorn'),
	('Alexandru Tudorie', 'Romania', 'tudorie'),
	('Alexandru Tudorie', 'Romania', 'alexandru tudorie'),
	('Peter Vindahl Jensen', 'Denmark', 'jensen'),
	('Peter Vindahl Jensen', 'Denmark', 'peter vindahl jensen'),
	('Julian Faye Lund', 'Norway', 'julian faye lund'),
	('Julian Faye Lund', 'Norway', 'lund'),
	('James Talbot', 'Republic of Ireland', 'talbot'),
	('James Talbot', 'Republic of Ireland', 'james talbot'),
	('Ebenezer Assifuah', 'Ghana', 'ebenezer assifuah'),
	('Ebenezer Assifuah', 'Ghana', 'assifuah'),
	('Macauley Bonne', 'Zimbabwe', 'macauley bonne'),
	('Macauley Bonne', 'Zimbabwe', 'bonne'),
	('Hans Nunoo Sarpei', 'Ghana', 'hans nunoo sarpei'),
	('Hans Nunoo Sarpei', 'Ghana', 'sarpei'),
	('Damien Dussaut', 'France', 'damien dussaut'),
	('Damien Dussaut', 'France', 'dussaut'),
	('Enrique Palos', 'Mexico', 'palos'),
	('Enrique Palos', 'Mexico', 'enrique palos'),
	('Hendrick Zuck', 'Germany', 'zuck'),
	('Hendrick Zuck', 'Germany', 'hendrick zuck'),
	('Jamie Hanson', 'England', 'hanson'),
	('Jamie Hanson', 'England', 'jamie hanson'),
	('Jaime Arrascaita', 'Bolivia', 'jaime arrascaita'),
	('Jaime Arrascaita', 'Bolivia', 'arrascaita'),
	('Leonardo Campana', 'Ecuador', 'leonardo campana'),
	('Leonardo Campana', 'Ecuador', 'campana'),
	('Robin Jansson', 'Sweden', 'robin jansson'),
	('Robin Jansson', 'Sweden', 'jansson'),
	('Gabriel Compagnucci', 'Argentina', 'gabriel compagnucci'),
	('Gabriel Compagnucci', 'Argentina', 'compagnucci'),
	('Liam Shephard', 'Wales', 'shephard'),
	('Liam Shephard', 'Wales', 'liam shephard'),
	('Jamie Robson', 'Scotland', 'jamie robson'),
	('Jamie Robson', 'Scotland', 'robson'),
	('Valdo', 'Brazil', 'valdo'),
	('Tsiy-William Ndenge', 'Germany', 'tsiywilliam ndenge'),
	('Tsiy-William Ndenge', 'Germany', 'ndenge'),
	('Tonny Brochmann', 'Denmark', 'tonny brochmann'),
	('Tonny Brochmann', 'Denmark', 'brochmann'),
	('Maguinho', 'Brazil', 'maguinho'),
	('Franco Costa', 'Argentina', 'franco costa'),
	('Franco Costa', 'Argentina', 'costa'),
	('Julian Araujo', 'United States', 'julian araujo'),
	('Julian Araujo', 'United States', 'araujo'),
	('Takuo Okubo', 'Japan', 'okubo'),
	('Takuo Okubo', 'Japan', 'takuo okubo'),
	('Gabriel Debeljuh', 'Croatia', 'debeljuh'),
	('Gabriel Debeljuh', 'Croatia', 'gabriel debeljuh'),
	('Claude Gonçalves', 'Portugal', 'goncalves'),
	('Claude Gonçalves', 'Portugal', 'claude goncalves'),
	('Cristhian Machado', 'Bolivia', 'cristhian machado'),
	('Cristhian Machado', 'Bolivia', 'machado'),
	('Tosin Kehinde', 'Nigeria', 'kehinde'),
	('Tosin Kehinde', 'Nigeria', 'tosin kehinde'),
	('Sebastian Bösel', 'Germany', 'sebastian bosel'),
	('Sebastian Bösel', 'Germany', 'bosel'),
	('Alfonso Trezza', 'Uruguay', 'alfonso trezza'),
	('Alfonso Trezza', 'Uruguay', 'trezza'),
	('Alexis Messidoro', 'Argentina', 'messidoro'),
	('Alexis Messidoro', 'Argentina', 'alexis messidoro'),
	('Ryo Okui', 'Japan', 'ryo okui'),
	('Ryo Okui', 'Japan', 'okui'),
	('Gilbert Álvarez', 'Bolivia', 'alvarez'),
	('Gilbert Álvarez', 'Bolivia', 'gilbert alvarez'),
	('Carlos Isaac', 'Spain', 'isaac'),
	('Carlos Isaac', 'Spain', 'carlos isaac'),
	('Lee Nicholls', 'England', 'lee nicholls'),
	('Lee Nicholls', 'England', 'nicholls'),
	('Andrei Cristea', 'Romania', 'cristea'),
	('Andrei Cristea', 'Romania', 'andrei cristea'),
	('Luis Mena', 'Colombia', 'mena'),
	('Luis Mena', 'Colombia', 'luis mena'),
	('Thomas Mikkelsen', 'Denmark', 'thomas mikkelsen'),
	('Thomas Mikkelsen', 'Denmark', 'mikkelsen'),
	('Kai Shibato', 'Japan', 'shibato'),
	('Kai Shibato', 'Japan', 'kai shibato'),
	('Eoghan O''Connell', 'Republic of Ireland', 'eoghan oconnell'),
	('Eoghan O''Connell', 'Republic of Ireland', 'oconnell'),
	('Simone Lo Faso', 'Italy', 'simone lo faso'),
	('Simone Lo Faso', 'Italy', 'faso'),
	('Mukhtar Ali', 'Saudi Arabia', 'mukhtar ali'),
	('Mukhtar Ali', 'Saudi Arabia', 'ali'),
	('Jake Buxton', 'England', 'buxton'),
	('Jake Buxton', 'England', 'jake buxton'),
	('Aaron McGowan', 'England', 'aaron mcgowan'),
	('Aaron McGowan', 'England', 'mcgowan'),
	('Miro Muheim', 'Switzerland', 'muheim'),
	('Miro Muheim', 'Switzerland', 'miro muheim'),
	('Theofanis Mavrommatis', 'Greece', 'mavrommatis'),
	('Theofanis Mavrommatis', 'Greece', 'theofanis mavrommatis'),
	('Jaden Brown', 'England', 'brown'),
	('Jaden Brown', 'England', 'jaden brown'),
	('Jeremy Márquez', 'Mexico', 'jeremy marquez'),
	('Jeremy Márquez', 'Mexico', 'marquez'),
	('Valera', 'Spain', 'valera'),
	('Meschack Elia', 'DR Congo', 'elia'),
	('Meschack Elia', 'DR Congo', 'meschack elia'),
	('Koo Dae Young', 'Korea Republic', 'koo dae young'),
	('Koo Dae Young', 'Korea Republic', 'young'),
	('Clément Diop', 'Senegal', 'clement diop'),
	('Clément Diop', 'Senegal', 'diop'),
	('Sebastián Gorga', 'Uruguay', 'gorga'),
	('Sebastián Gorga', 'Uruguay', 'sebastian gorga'),
	('Ismaila Coulibaly', 'Mali', 'coulibaly'),
	('Ismaila Coulibaly', 'Mali', 'ismaila coulibaly'),
	('José Yegüez', 'Venezuela', 'jose yeguez'),
	('José Yegüez', 'Venezuela', 'yeguez'),
	('Anthony van den Hurk', 'Curacao', 'hurk'),
	('Anthony van den Hurk', 'Curacao', 'anthony van den hurk'),
	('Wang Tong', 'China PR', 'wang tong'),
	('Wang Tong', 'China PR', 'tong'),
	('Mohammed Qasem', 'Saudi Arabia', 'mohammed qasem'),
	('Mohammed Qasem', 'Saudi Arabia', 'qasem'),
	('Ângelo Taveira', 'Portugal', 'taveira'),
	('Ângelo Taveira', 'Portugal', 'angelo taveira'),
	('Ángel García', 'Spain', 'garcia'),
	('Ángel García', 'Spain', 'angel garcia'),
	('Derrick Etienne Jr.', 'Haiti', 'jr'),
	('Derrick Etienne Jr.', 'Haiti', 'derrick etienne jr'),
	('Kennedy Boateng', 'Ghana', 'boateng'),
	('Kennedy Boateng', 'Ghana', 'kennedy boateng'),
	('Djihad Bizimana', 'Rwanda', 'djihad bizimana'),
	('Djihad Bizimana', 'Rwanda', 'bizimana'),
	('Agustín Ale', 'Uruguay', 'ale'),
	('Agustín Ale', 'Uruguay', 'agustin ale'),
	('Benedikt Röcker', 'Germany', 'rocker'),
	('Benedikt Röcker', 'Germany', 'benedikt rocker'),
	('Juan Sánchez Sotelo', 'Argentina', 'juan sanchez sotelo'),
	('Juan Sánchez Sotelo', 'Argentina', 'sotelo'),
	('Wesley Jobello', 'France', 'jobello'),
	('Wesley Jobello', 'France', 'wesley jobello'),
	('Cheick Timite', 'Ivory Coast', 'timite'),
	('Cheick Timite', 'Ivory Coast', 'cheick timite'),
	('Vladimir Golemić', 'Serbia', 'vladimir golemic'),
	('Vladimir Golemić', 'Serbia', 'golemic'),
	('Sercan Sararer', 'Turkey', 'sararer'),
	('Sercan Sararer', 'Turkey', 'sercan sararer'),
	('Samuel Galindo', 'Bolivia', 'samuel galindo'),
	('Samuel Galindo', 'Bolivia', 'galindo'),
	('Yhonathan Yustiz', 'Venezuela', 'yustiz'),
	('Yhonathan Yustiz', 'Venezuela', 'yhonathan yustiz')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';