INSERT INTO reference_entities (canonical_name, category, entity_type) VALUES
	('Younn Zahary', 'Comoros', 'player'),
	('Dragan Rosić', 'Serbia', 'player'),
	('Ariel Borysiuk', 'Poland', 'player'),
	('Baily Cargill', 'England', 'player'),
	('Gustavo Torres', 'Colombia', 'player'),
	('Aristóteles Romero', 'Venezuela', 'player'),
	('Jeka', 'Ukraine', 'player'),
	('Marcin Cebula', 'Poland', 'player'),
	('Migue', 'Spain', 'player'),
	('Tim Hall', 'Luxembourg', 'player'),
	('Yorkman Tello', 'Peru', 'player'),
	('Jacob Ericsson', 'Sweden', 'player'),
	('Raymundo Fulgencio', 'Mexico', 'player'),
	('Ben Wiles', 'England', 'player'),
	('Mark Marshall', 'Jamaica', 'player'),
	('Humberto Osorio', 'Colombia', 'player'),
	('Strefezza', 'Brazil', 'player'),
	('Adon Gomis', 'France', 'player'),
	('Rafał Janicki', 'Poland', 'player'),
	('Nicolás Thaller', 'Argentina', 'player'),
	('Tobias Mølgaard', 'Denmark', 'player'),
	('Mikhail Ignatov', 'Russia', 'player'),
	('Peter Nymann', 'Denmark', 'player'),
	('Blair Spittal', 'Scotland', 'player'),
	('Thomas Basila', 'France', 'player'),
	('Mohammed Jamal', 'United Arab Emirates', 'player'),
	('Jenthe Mertens', 'Belgium', 'player'),
	('Jhoao Rodríguez', 'Colombia', 'player'),
	('Josh Sheehan', 'Wales', 'player'),
	('Byron Saavedra', 'Chile', 'player'),
	('Edward Chilufya', 'Zambia', 'player'),
	('Steven Benda', 'Germany', 'player'),
	('Jodi Jones', 'England', 'player'),
	('Igor', 'Brazil', 'player'),
	('Octavian Vâlceanu', 'Romania', 'player'),
	('Gianluca Frabotta', 'Italy', 'player'),
	('Iñigo Muñoz', 'Spain', 'player'),
	('Aldo Vera', 'Paraguay', 'player'),
	('Manuel Wintzheimer', 'Germany', 'player'),
	('Fredrik P. Knudsen', 'Norway', 'player'),
	('Kévin Cabral', 'France', 'player'),
	('Sachiro Toshima', 'Japan', 'player'),
	('Felix Götze', 'Germany', 'player'),
	('Sultan Farhan', 'Saudi Arabia', 'player'),
	('Hassani Dotson', 'United States', 'player'),
	('Hiroshi Ibusuki', 'Japan', 'player'),
	('Eduardo Puña', 'Bolivia', 'player'),
	('Patric Pfeiffer', 'Germany', 'player'),
	('Jack Bonham', 'Republic of Ireland', 'player'),
	('Ahn Tae Hyun', 'Korea Republic', 'player'),
	('Amiran Sanaia', 'Georgia', 'player'),
	('Pablo Laredo', 'Bolivia', 'player'),
	('Makito Ito', 'Japan', 'player'),
	('Anthony Soubervie', 'France', 'player'),
	('Jacob Davenport', 'England', 'player'),
	('Sinaly Diomande', 'Ivory Coast', 'player'),
	('Mikael Dyrestam', 'Guinea', 'player'),
	('Vitinho', 'Brazil', 'player'),
	('Rayane Aabid', 'France', 'player'),
	('Alexander Brunst', 'Germany', 'player'),
	('Adil Taoui', 'France', 'player'),
	('Juhani Ojala', 'Finland', 'player'),
	('Mathias Dyngeland', 'Norway', 'player'),
	('Cyril Ngonge', 'Belgium', 'player'),
	('Damian Oko', 'Poland', 'player'),
	('Gladwin Shitolo', 'South Africa', 'player'),
	('Charlie Wyke', 'England', 'player'),
	('Afonso Taira', 'Portugal', 'player'),
	('Patrick Mullins', 'United States', 'player'),
	('Sergio Moreno', 'Spain', 'player'),
	('Miguel Quiroga', 'Bolivia', 'player'),
	('Muris Mešanović', 'Bosnia Herzegovina', 'player'),
	('Răzvan Dâlbea', 'Romania', 'player'),
	('Tony Figueroa', 'Mexico', 'player'),
	('Santy Ngom', 'Senegal', 'player'),
	('Yohann Thuram', 'France', 'player'),
	('Mihai Dobrescu', 'Romania', 'player'),
	('Soni Mustivar', 'Haiti', 'player'),
	('Christian Conteh', 'Germany', 'player'),
	('Brennan Dickenson', 'England', 'player'),
	('Chase Gasper', 'United States', 'player'),
	('Robert Ion', 'Romania', 'player'),
	('Korbinian Burger', 'Germany', 'player'),
	('Saúl Crespo', 'Spain', 'player'),
	('Björn Rother', 'Germany', 'player'),
	('Sofiane Daham', 'Algeria', 'player'),
	('Luis Amarilla', 'Paraguay', 'player'),
	('Pál Dárdai', 'Germany', 'player'),
	('Amine Khammas', 'Morocco', 'player'),
	('Gethin Jones', 'Wales', 'player'),
	('Sean Goss', 'England', 'player'),
	('Ali Yavuz Kol', 'Turkey', 'player'),
	('Lapeña', 'Spain', 'player'),
	('Josué Ayala', 'Argentina', 'player'),
	('Ian Poveda', 'England', 'player'),
	('Jonathan Bakali', 'France', 'player'),
	('Harouna Sy', 'Mauritania', 'player'),
	('David Alba', 'Spain', 'player'),
	('Justice Chabalala', 'South Africa', 'player'),
	('Dominic Baumann', 'Germany', 'player'),
	('Callum Harriott', 'Guyana', 'player'),
	('Ionuț Năstăsie', 'Romania', 'player'),
	('Márk Tamás', 'Hungary', 'player'),
	('Florian Michel', 'France', 'player'),
	('Heradi Rashidi', 'Sweden', 'player'),
	('Hendrik Bonmann', 'Germany', 'player'),
	('Martin Broberg', 'Sweden', 'player'),
	('Alain Wiss', 'Switzerland', 'player'),
	('Leonai', 'Brazil', 'player'),
	('Adrian Șut', 'Romania', 'player'),
	('Borja Garcés', 'Spain', 'player'),
	('George Bello', 'United States', 'player'),
	('Mehdi Zerkane', 'France', 'player'),
	('Sören Reddemann', 'Germany', 'player'),
	('Ali Eren İyican', 'Turkey', 'player'),
	('Yaseen Barnawi', 'Saudi Arabia', 'player'),
	('John Verhoek', 'Netherlands', 'player'),
	('Ole Martin Kolskogen', 'Norway', 'player'),
	('Brad Stuver', 'United States', 'player'),
	('Curtis Main', 'England', 'player'),
	('Alec Kann', 'United States', 'player'),
	('Corey Blackett-Taylor', 'England', 'player'),
	('Philipp Schmiedl', 'Austria', 'player'),
	('Curtis Good', 'Australia', 'player'),
	('Nathan Oduwa', 'Nigeria', 'player'),
	('Eric Miller', 'United States', 'player'),
	('Lars-Jørgen Salvesen', 'Norway', 'player'),
	('Mitsuki Saito', 'Japan', 'player'),
	('Bura', 'Guinea Bissau', 'player'),
	('Luke Le Roux', 'South Africa', 'player'),
	('Scott Cuthbert', 'Scotland', 'player'),
	('Yosuke Kawai', 'Japan', 'player'),
	('Delano van Crooij', 'Netherlands', 'player'),
	('Calvin Jong-A-Pin', 'Netherlands', 'player'),
	('Tim Luis Maciejewski', 'Germany', 'player'),
	('Dominic Maroh', 'Slovenia', 'player'),
	('Michael Lercher', 'Austria', 'player'),
	('Daníel Leó Grétarsson', 'Iceland', 'player'),
	('Aaron McEneff', 'Northern Ireland', 'player'),
	('Alexandru Buziuc', 'Romania', 'player'),
	('Bahadır Öztürk', 'Turkey', 'player'),
	('Matthias Verreth', 'Belgium', 'player'),
	('Simon Lorenz', 'Germany', 'player'),
	('Steve Kroll', 'Germany', 'player'),
	('Achille Anani', 'Ivory Coast', 'player'),
	('Jesper Daland', 'Norway', 'player'),
	('Tom Mickel', 'Germany', 'player'),
	('Hidekazu Otani', 'Japan', 'player'),
	('Omar Beckles', 'Grenada', 'player'),
	('Jan Löhmannsröben', 'Germany', 'player'),
	('Zvonimir Šarlija', 'Croatia', 'player'),
	('Marius Ștefănescu', 'Romania', 'player'),
	('Park Yi-Young', 'Korea Republic', 'player'),
	('Amadou Dante', 'Mali', 'player'),
	('Francisco Contreras', 'Mexico', 'player'),
	('Federico Girotti', 'Argentina', 'player'),
	('Zeli Ismail', 'England', 'player'),
	('Abdullah Al Salem', 'Saudi Arabia', 'player'),
	('Liam Craig', 'Scotland', 'player'),
	('Ron-Thorben Hoffmann', 'Germany', 'player'),
	('Florian Martin', 'France', 'player'),
	('Mamadou Kamissoko', 'France', 'player'),
	('Clint Essers', 'Netherlands', 'player'),
	('Yeo Reum', 'Korea Republic', 'player'),
	('Lion Schweers', 'Germany', 'player'),
	('Andrei Patache', 'Romania', 'player'),
	('Martin Kreuzriegler', 'Austria', 'player'),
	('João Felipe', 'Brazil', 'player'),
	('Francisco Mera', 'Ecuador', 'player'),
	('Stefan Hager', 'Austria', 'player'),
	('Metehan Güçlü', 'Turkey', 'player'),
	('Janek Sternberg', 'Germany', 'player'),
	('Amadou Bakayoko', 'Sierra Leone', 'player'),
	('Tim Söderström', 'Sweden', 'player'),
	('Jefferson Caicedo', 'Ecuador', 'player'),
	('Mauro Luna Diale', 'Argentina', 'player'),
	('Andrés García', 'Spain', 'player'),
	('Bradley Danger', 'France', 'player'),
	('Harold González', 'Ecuador', 'player'),
	('Eijiro Takeda', 'Japan', 'player'),
	('Kieron Morris', 'England', 'player'),
	('Dean Gerken', 'England', 'player'),
	('Manu Hernando', 'Spain', 'player'),
	('Liam Fraser', 'Canada', 'player'),
	('Edi Semedo', 'Portugal', 'player'),
	('Johan Lædre Bjørdal', 'Norway', 'player'),
	('Hokuto Shimoda', 'Japan', 'player'),
	('De la Fuente', 'Spain', 'player'),
	('Alex Gersbach', 'Australia', 'player'),
	('Mthokozisi Dube', 'South Africa', 'player'),
	('Eden Massouema', 'France', 'player'),
	('İlkay Durmuş', 'Turkey', 'player'),
	('Junior Messias', 'Brazil', 'player'),
	('Murat Şatin', 'Austria', 'player'),
	('Bubacar Djaló', 'Portugal', 'player'),
	('Yu Yang', 'China PR', 'player'),
	('Kgosi Ntlhe', 'South Africa', 'player'),
	('Marco Farfan', 'United States', 'player'),
	('Dirk Carlson', 'Luxembourg', 'player'),
	('Julián Navas', 'Argentina', 'player'),
	('Josh Clarke', 'England', 'player'),
	('Rico Preißinger', 'Germany', 'player'),
	('Wes McDonald', 'England', 'player'),
	('Bilal Ould-Chikh', 'Morocco', 'player'),
	('Leandro Vega', 'Argentina', 'player'),
	('Roberto Nurse', 'Panama', 'player'),
	('Berto', 'Spain', 'player'),
	('James Musa', 'New Zealand', 'player'),
	('Luca Horn', 'Germany', 'player'),
	('Berrocal', 'Spain', 'player'),
	('Tomás Conechny', 'Argentina', 'player'),
	('Christian Jakobsen', 'Denmark', 'player'),
	('Jake Caprice', 'England', 'player'),
	('Edwin Cerrillo', 'United States', 'player'),
	('Demba Thiam', 'France', 'player'),
	('Mehdi Chahiri', 'France', 'player'),
	('Gustav Henriksson', 'Sweden', 'player'),
	('Seigo Kobayashi', 'Japan', 'player'),
	('Adil Demirbağ', 'Turkey', 'player'),
	('Samuel Mráz', 'Slovakia', 'player'),
	('Khiry Shelton', 'United States', 'player'),
	('Lucas Marques', 'Brazil', 'player'),
	('Benítez', 'Spain', 'player'),
	('Rhys Marshall', 'Northern Ireland', 'player'),
	('Jorge Cuenca', 'Spain', 'player'),
	('Jens Jakob Thomasen', 'Denmark', 'player'),
	('Edanyilber Navas', 'Venezuela', 'player'),
	('Goran Karanović', 'Switzerland', 'player'),
	('Indy Groothuizen', 'Netherlands', 'player'),
	('Mitch Pinnock', 'England', 'player'),
	('Haris Radetinac', 'Serbia', 'player'),
	('Marcos Ovejero', 'Argentina', 'player'),
	('Sergio Barreto', 'Argentina', 'player'),
	('Ryan Inniss', 'England', 'player'),
	('Greg Kiltie', 'Scotland', 'player'),
	('Nikolas Nartey', 'Denmark', 'player'),
	('Maudo Lamine Jarjué', 'Gambia', 'player'),
	('Eirik Wichne', 'Norway', 'player'),
	('Răzvan Grădinaru', 'Romania', 'player'),
	('Mathias Greve', 'Denmark', 'player'),
	('Zhao Yuhao', 'China PR', 'player'),
	('Nicolae Carnat', 'Romania', 'player'),
	('Jan Bamert', 'Switzerland', 'player'),
	('Louis Thompson', 'Wales', 'player'),
	('Kevin Goden', 'Germany', 'player'),
	('Tito Valencia', 'Ecuador', 'player'),
	('Aldo Araujo', 'Argentina', 'player'),
	('Anthony Caceres', 'Australia', 'player'),
	('Camilo Mancilla', 'Colombia', 'player'),
	('John-Joe O''Toole', 'Republic of Ireland', 'player');

WITH v(name, cat, alias) AS (VALUES
	('Younn Zahary', 'Comoros', 'younn zahary'),
	('Younn Zahary', 'Comoros', 'zahary'),
	('Dragan Rosić', 'Serbia', 'rosic'),
	('Dragan Rosić', 'Serbia', 'dragan rosic'),
	('Ariel Borysiuk', 'Poland', 'borysiuk'),
	('Ariel Borysiuk', 'Poland', 'ariel borysiuk'),
	('Baily Cargill', 'England', 'baily cargill'),
	('Baily Cargill', 'England', 'cargill'),
	('Gustavo Torres', 'Colombia', 'torres'),
	('Gustavo Torres', 'Colombia', 'gustavo torres'),
	('Aristóteles Romero', 'Venezuela', 'aristoteles romero'),
	('Aristóteles Romero', 'Venezuela', 'romero'),
	('Jeka', 'Ukraine', 'jeka'),
	('Marcin Cebula', 'Poland', 'cebula'),
	('Marcin Cebula', 'Poland', 'marcin cebula'),
	('Migue', 'Spain', 'migue'),
	('Tim Hall', 'Luxembourg', 'hall'),
	('Tim Hall', 'Luxembourg', 'tim hall'),
	('Yorkman Tello', 'Peru', 'yorkman tello'),
	('Yorkman Tello', 'Peru', 'tello'),
	('Jacob Ericsson', 'Sweden', 'jacob ericsson'),
	('Jacob Ericsson', 'Sweden', 'ericsson'),
	('Raymundo Fulgencio', 'Mexico', 'fulgencio'),
	('Raymundo Fulgencio', 'Mexico', 'raymundo fulgencio'),
	('Ben Wiles', 'England', 'wiles'),
	('Ben Wiles', 'England', 'ben wiles'),
	('Mark Marshall', 'Jamaica', 'mark marshall'),
	('Mark Marshall', 'Jamaica', 'marshall'),
	('Humberto Osorio', 'Colombia', 'osorio'),
	('Humberto Osorio', 'Colombia', 'humberto osorio'),
	('Strefezza', 'Brazil', 'strefezza'),
	('Adon Gomis', 'France', 'gomis'),
	('Adon Gomis', 'France', 'adon gomis'),
	('Rafał Janicki', 'Poland', 'janicki'),
	('Rafał Janicki', 'Poland', 'rafa janicki'),
	('Nicolás Thaller', 'Argentina', 'nicolas thaller'),
	('Nicolás Thaller', 'Argentina', 'thaller'),
	('Tobias Mølgaard', 'Denmark', 'mlgaard'),
	('Tobias Mølgaard', 'Denmark', 'tobias mlgaard'),
	('Mikhail Ignatov', 'Russia', 'ignatov'),
	('Mikhail Ignatov', 'Russia', 'mikhail ignatov'),
	('Peter Nymann', 'Denmark', 'peter nymann'),
	('Peter Nymann', 'Denmark', 'nymann'),
	('Blair Spittal', 'Scotland', 'blair spittal'),
	('Blair Spittal', 'Scotland', 'spittal'),
	('Thomas Basila', 'France', 'basila'),
	('Thomas Basila', 'France', 'thomas basila'),
	('Mohammed Jamal', 'United Arab Emirates', 'jamal'),
	('Mohammed Jamal', 'United Arab Emirates', 'mohammed jamal'),
	('Jenthe Mertens', 'Belgium', 'mertens'),
	('Jenthe Mertens', 'Belgium', 'jenthe mertens'),
	('Jhoao Rodríguez', 'Colombia', 'rodriguez'),
	('Jhoao Rodríguez', 'Colombia', 'jhoao rodriguez'),
	('Josh Sheehan', 'Wales', 'sheehan'),
	('Josh Sheehan', 'Wales', 'josh sheehan'),
	('Byron Saavedra', 'Chile', 'byron saavedra'),
	('Byron Saavedra', 'Chile', 'saavedra'),
	('Edward Chilufya', 'Zambia', 'edward chilufya'),
	('Edward Chilufya', 'Zambia', 'chilufya'),
	('Steven Benda', 'Germany', 'steven benda'),
	('Steven Benda', 'Germany', 'benda'),
	('Jodi Jones', 'England', 'jones'),
	('Jodi Jones', 'England', 'jodi jones'),
	('Igor', 'Brazil', 'igor'),
	('Octavian Vâlceanu', 'Romania', 'octavian valceanu'),
	('Octavian Vâlceanu', 'Romania', 'valceanu'),
	('Gianluca Frabotta', 'Italy', 'frabotta'),
	('Gianluca Frabotta', 'Italy', 'gianluca frabotta'),
	('Iñigo Muñoz', 'Spain', 'munoz'),
	('Iñigo Muñoz', 'Spain', 'inigo munoz'),
	('Aldo Vera', 'Paraguay', 'vera'),
	('Aldo Vera', 'Paraguay', 'aldo vera'),
	('Manuel Wintzheimer', 'Germany', 'manuel wintzheimer'),
	('Manuel Wintzheimer', 'Germany', 'wintzheimer'),
	('Fredrik P. Knudsen', 'Norway', 'knudsen'),
	('Fredrik P. Knudsen', 'Norway', 'fredrik p knudsen'),
	('Kévin Cabral', 'France', 'kevin cabral'),
	('Kévin Cabral', 'France', 'cabral'),
	('Sachiro Toshima', 'Japan', 'toshima'),
	('Sachiro Toshima', 'Japan', 'sachiro toshima'),
	('Felix Götze', 'Germany', 'gotze'),
	('Felix Götze', 'Germany', 'felix gotze'),
	('Sultan Farhan', 'Saudi Arabia', 'farhan'),
	('Sultan Farhan', 'Saudi Arabia', 'sultan farhan'),
	('Hassani Dotson', 'United States', 'hassani dotson'),
	('Hassani Dotson', 'United States', 'dotson'),
	('Hiroshi Ibusuki', 'Japan', 'ibusuki'),
	('Hiroshi Ibusuki', 'Japan', 'hiroshi ibusuki'),
	('Eduardo Puña', 'Bolivia', 'eduardo puna'),
	('Eduardo Puña', 'Bolivia', 'puna'),
	('Patric Pfeiffer', 'Germany', 'patric pfeiffer'),
	('Patric Pfeiffer', 'Germany', 'pfeiffer'),
	('Jack Bonham', 'Republic of Ireland', 'bonham'),
	('Jack Bonham', 'Republic of Ireland', 'jack bonham'),
	('Ahn Tae Hyun', 'Korea Republic', 'ahn tae hyun'),
	('Ahn Tae Hyun', 'Korea Republic', 'hyun'),
	('Amiran Sanaia', 'Georgia', 'amiran sanaia'),
	('Amiran Sanaia', 'Georgia', 'sanaia'),
	('Pablo Laredo', 'Bolivia', 'pablo laredo'),
	('Pablo Laredo', 'Bolivia', 'laredo'),
	('Makito Ito', 'Japan', 'makito ito'),
	('Makito Ito', 'Japan', 'ito'),
	('Anthony Soubervie', 'France', 'soubervie'),
	('Anthony Soubervie', 'France', 'anthony soubervie'),
	('Jacob Davenport', 'England', 'jacob davenport'),
	('Jacob Davenport', 'England', 'davenport'),
	('Sinaly Diomande', 'Ivory Coast', 'diomande'),
	('Sinaly Diomande', 'Ivory Coast', 'sinaly diomande'),
	('Mikael Dyrestam', 'Guinea', 'mikael dyrestam'),
	('Mikael Dyrestam', 'Guinea', 'dyrestam'),
	('Vitinho', 'Brazil', 'vitinho'),
	('Rayane Aabid', 'France', 'aabid'),
	('Rayane Aabid', 'France', 'rayane aabid'),
	('Alexander Brunst', 'Germany', 'alexander brunst'),
	('Alexander Brunst', 'Germany', 'brunst'),
	('Adil Taoui', 'France', 'taoui'),
	('Adil Taoui', 'France', 'adil taoui'),
	('Juhani Ojala', 'Finland', 'ojala'),
	('Juhani Ojala', 'Finland', 'juhani ojala'),
	('Mathias Dyngeland', 'Norway', 'mathias dyngeland'),
	('Mathias Dyngeland', 'Norway', 'dyngeland'),
	('Cyril Ngonge', 'Belgium', 'ngonge'),
	('Cyril Ngonge', 'Belgium', 'cyril ngonge'),
	('Damian Oko', 'Poland', 'oko'),
	('Damian Oko', 'Poland', 'damian oko'),
	('Gladwin Shitolo', 'South Africa', 'gladwin shitolo'),
	('Gladwin Shitolo', 'South Africa', 'shitolo'),
	('Charlie Wyke', 'England', 'wyke'),
	('Charlie Wyke', 'England', 'charlie wyke'),
	('Afonso Taira', 'Portugal', 'taira'),
	('Afonso Taira', 'Portugal', 'afonso taira'),
	('Patrick Mullins', 'United States', 'patrick mullins'),
	('Patrick Mullins', 'United States', 'mullins'),
	('Sergio Moreno', 'Spain', 'moreno'),
	('Sergio Moreno', 'Spain', 'sergio moreno'),
	('Miguel Quiroga', 'Bolivia', 'quiroga'),
	('Miguel Quiroga', 'Bolivia', 'miguel quiroga'),
	('Muris Mešanović', 'Bosnia Herzegovina', 'muris mesanovic'),
	('Muris Mešanović', 'Bosnia Herzegovina', 'mesanovic'),
	('Răzvan Dâlbea', 'Romania', 'dalbea'),
	('Răzvan Dâlbea', 'Romania', 'razvan dalbea'),
	('Tony Figueroa', 'Mexico', 'figueroa'),
	('Tony Figueroa', 'Mexico', 'tony figueroa'),
	('Santy Ngom', 'Senegal', 'santy ngom'),
	('Santy Ngom', 'Senegal', 'ngom'),
	('Yohann Thuram', 'France', 'thuram'),
	('Yohann Thuram', 'France', 'yohann thuram'),
	('Mihai Dobrescu', 'Romania', 'mihai dobrescu'),
	('Mihai Dobrescu', 'Romania', 'dobrescu'),
	('Soni Mustivar', 'Haiti', 'soni mustivar'),
	('Soni Mustivar', 'Haiti', 'mustivar'),
	('Christian Conteh', 'Germany', 'christian conteh'),
	('Christian Conteh', 'Germany', 'conteh'),
	('Brennan Dickenson', 'England', 'brennan dickenson'),
	('Brennan Dickenson', 'England', 'dickenson'),
	('Chase Gasper', 'United States', 'gasper'),
	('Chase Gasper', 'United States', 'chase gasper'),
	('Robert Ion', 'Romania', 'robert ion'),
	('Robert Ion', 'Romania', 'ion'),
	('Korbinian Burger', 'Germany', 'korbinian burger'),
	('Korbinian Burger', 'Germany', 'burger'),
	('Saúl Crespo', 'Spain', 'saul crespo'),
	('Saúl Crespo', 'Spain', 'crespo'),
	('Björn Rother', 'Germany', 'rother'),
	('Björn Rother', 'Germany', 'bjorn rother'),
	('Sofiane Daham', 'Algeria', 'sofiane daham'),
	('Sofiane Daham', 'Algeria', 'daham'),
	('Luis Amarilla', 'Paraguay', 'amarilla'),
	('Luis Amarilla', 'Paraguay', 'luis amarilla'),
	('Pál Dárdai', 'Germany', 'dardai'),
	('Pál Dárdai', 'Germany', 'pal dardai'),
	('Amine Khammas', 'Morocco', 'amine khammas'),
	('Amine Khammas', 'Morocco', 'khammas'),
	('Gethin Jones', 'Wales', 'gethin jones'),
	('Gethin Jones', 'Wales', 'jones'),
	('Sean Goss', 'England', 'goss'),
	('Sean Goss', 'England', 'sean goss'),
	('Ali Yavuz Kol', 'Turkey', 'kol'),
	('Ali Yavuz Kol', 'Turkey', 'ali yavuz kol'),
	('Lapeña', 'Spain', 'lapena'),
	('Josué Ayala', 'Argentina', 'ayala'),
	('Josué Ayala', 'Argentina', 'josue ayala'),
	('Ian Poveda', 'England', 'poveda'),
	('Ian Poveda', 'England', 'ian poveda'),
	('Jonathan Bakali', 'France', 'jonathan bakali'),
	('Jonathan Bakali', 'France', 'bakali'),
	('Harouna Sy', 'Mauritania', 'sy'),
	('Harouna Sy', 'Mauritania', 'harouna sy'),
	('David Alba', 'Spain', 'david alba'),
	('David Alba', 'Spain', 'alba'),
	('Justice Chabalala', 'South Africa', 'chabalala'),
	('Justice Chabalala', 'South Africa', 'justice chabalala'),
	('Dominic Baumann', 'Germany', 'dominic baumann'),
	('Dominic Baumann', 'Germany', 'baumann'),
	('Callum Harriott', 'Guyana', 'callum harriott'),
	('Callum Harriott', 'Guyana', 'harriott'),
	('Ionuț Năstăsie', 'Romania', 'nastasie'),
	('Ionuț Năstăsie', 'Romania', 'ionut nastasie'),
	('Márk Tamás', 'Hungary', 'tamas'),
	('Márk Tamás', 'Hungary', 'mark tamas'),
	('Florian Michel', 'France', 'florian michel'),
	('Florian Michel', 'France', 'michel'),
	('Heradi Rashidi', 'Sweden', 'heradi rashidi'),
	('Heradi Rashidi', 'Sweden', 'rashidi'),
	('Hendrik Bonmann', 'Germany', 'hendrik bonmann'),
	('Hendrik Bonmann', 'Germany', 'bonmann'),
	('Martin Broberg', 'Sweden', 'broberg'),
	('Martin Broberg', 'Sweden', 'martin broberg'),
	('Alain Wiss', 'Switzerland', 'alain wiss'),
	('Alain Wiss', 'Switzerland', 'wiss'),
	('Leonai', 'Brazil', 'leonai'),
	('Adrian Șut', 'Romania', 'sut'),
	('Adrian Șut', 'Romania', 'adrian sut'),
	('Borja Garcés', 'Spain', 'garces'),
	('Borja Garcés', 'Spain', 'borja garces'),
	('George Bello', 'United States', 'george bello'),
	('George Bello', 'United States', 'bello'),
	('Mehdi Zerkane', 'France', 'zerkane'),
	('Mehdi Zerkane', 'France', 'mehdi zerkane'),
	('Sören Reddemann', 'Germany', 'reddemann'),
	('Sören Reddemann', 'Germany', 'soren reddemann'),
	('Ali Eren İyican', 'Turkey', 'iyican'),
	('Ali Eren İyican', 'Turkey', 'ali eren iyican'),
	('Yaseen Barnawi', 'Saudi Arabia', 'yaseen barnawi'),
	('Yaseen Barnawi', 'Saudi Arabia', 'barnawi'),
	('John Verhoek', 'Netherlands', 'verhoek'),
	('John Verhoek', 'Netherlands', 'john verhoek'),
	('Ole Martin Kolskogen', 'Norway', 'kolskogen'),
	('Ole Martin Kolskogen', 'Norway', 'ole martin kolskogen'),
	('Brad Stuver', 'United States', 'brad stuver'),
	('Brad Stuver', 'United States', 'stuver'),
	('Curtis Main', 'England', 'curtis main'),
	('Curtis Main', 'England', 'main'),
	('Alec Kann', 'United States', 'alec kann'),
	('Alec Kann', 'United States', 'kann'),
	('Corey Blackett-Taylor', 'England', 'corey blacketttaylor'),
	('Corey Blackett-Taylor', 'England', 'blacketttaylor'),
	('Philipp Schmiedl', 'Austria', 'schmiedl'),
	('Philipp Schmiedl', 'Austria', 'philipp schmiedl'),
	('Curtis Good', 'Australia', 'good'),
	('Curtis Good', 'Australia', 'curtis good'),
	('Nathan Oduwa', 'Nigeria', 'nathan oduwa'),
	('Nathan Oduwa', 'Nigeria', 'oduwa'),
	('Eric Miller', 'United States', 'eric miller'),
	('Eric Miller', 'United States', 'miller'),
	('Lars-Jørgen Salvesen', 'Norway', 'larsjrgen salvesen'),
	('Lars-Jørgen Salvesen', 'Norway', 'salvesen'),
	('Mitsuki Saito', 'Japan', 'mitsuki saito'),
	('Mitsuki Saito', 'Japan', 'saito'),
	('Bura', 'Guinea Bissau', 'bura'),
	('Luke Le Roux', 'South Africa', 'roux'),
	('Luke Le Roux', 'South Africa', 'luke le roux'),
	('Scott Cuthbert', 'Scotland', 'scott cuthbert'),
	('Scott Cuthbert', 'Scotland', 'cuthbert'),
	('Yosuke Kawai', 'Japan', 'kawai'),
	('Yosuke Kawai', 'Japan', 'yosuke kawai'),
	('Delano van Crooij', 'Netherlands', 'delano van crooij'),
	('Delano van Crooij', 'Netherlands', 'crooij'),
	('Calvin Jong-A-Pin', 'Netherlands', 'calvin jongapin'),
	('Calvin Jong-A-Pin', 'Netherlands', 'jongapin'),
	('Tim Luis Maciejewski', 'Germany', 'maciejewski'),
	('Tim Luis Maciejewski', 'Germany', 'tim luis maciejewski'),
	('Dominic Maroh', 'Slovenia', 'maroh'),
	('Dominic Maroh', 'Slovenia', 'dominic maroh'),
	('Michael Lercher', 'Austria', 'lercher'),
	('Michael Lercher', 'Austria', 'michael lercher'),
	('Daníel Leó Grétarsson', 'Iceland', 'gretarsson'),
	('Daníel Leó Grétarsson', 'Iceland', 'daniel leo gretarsson'),
	('Aaron McEneff', 'Northern Ireland', 'aaron mceneff'),
	('Aaron McEneff', 'Northern Ireland', 'mceneff'),
	('Alexandru Buziuc', 'Romania', 'alexandru buziuc'),
	('Alexandru Buziuc', 'Romania', 'buziuc'),
	('Bahadır Öztürk', 'Turkey', 'bahadr ozturk'),
	('Bahadır Öztürk', 'Turkey', 'ozturk'),
	('Matthias Verreth', 'Belgium', 'matthias verreth'),
	('Matthias Verreth', 'Belgium', 'verreth'),
	('Simon Lorenz', 'Germany', 'simon lorenz'),
	('Simon Lorenz', 'Germany', 'lorenz'),
	('Steve Kroll', 'Germany', 'steve kroll'),
	('Steve Kroll', 'Germany', 'kroll'),
	('Achille Anani', 'Ivory Coast', 'achille anani'),
	('Achille Anani', 'Ivory Coast', 'anani'),
	('Jesper Daland', 'Norway', 'daland'),
	('Jesper Daland', 'Norway', 'jesper daland'),
	('Tom Mickel', 'Germany', 'mickel'),
	('Tom Mickel', 'Germany', 'tom mickel'),
	('Hidekazu Otani', 'Japan', 'otani'),
	('Hidekazu Otani', 'Japan', 'hidekazu otani'),
	('Omar Beckles', 'Grenada', 'beckles'),
	('Omar Beckles', 'Grenada', 'omar beckles'),
	('Jan Löhmannsröben', 'Germany', 'jan lohmannsroben'),
	('Jan Löhmannsröben', 'Germany', 'lohmannsroben'),
	('Zvonimir Šarlija', 'Croatia', 'sarlija'),
	('Zvonimir Šarlija', 'Croatia', 'zvonimir sarlija'),
	('Marius Ștefănescu', 'Romania', 'marius stefanescu'),
	('Marius Ștefănescu', 'Romania', 'stefanescu'),
	('Park Yi-Young', 'Korea Republic', 'yiyoung'),
	('Park Yi-Young', 'Korea Republic', 'park yiyoung'),
	('Amadou Dante', 'Mali', 'dante'),
	('Amadou Dante', 'Mali', 'amadou dante'),
	('Francisco Contreras', 'Mexico', 'contreras'),
	('Francisco Contreras', 'Mexico', 'francisco contreras'),
	('Federico Girotti', 'Argentina', 'federico girotti'),
	('Federico Girotti', 'Argentina', 'girotti'),
	('Zeli Ismail', 'England', 'zeli ismail'),
	('Zeli Ismail', 'England', 'ismail'),
	('Abdullah Al Salem', 'Saudi Arabia', 'salem'),
	('Abdullah Al Salem', 'Saudi Arabia', 'abdullah al salem'),
	('Liam Craig', 'Scotland', 'liam craig'),
	('Liam Craig', 'Scotland', 'craig'),
	('Ron-Thorben Hoffmann', 'Germany', 'hoffmann'),
	('Ron-Thorben Hoffmann', 'Germany', 'ronthorben hoffmann'),
	('Florian Martin', 'France', 'florian martin'),
	('Florian Martin', 'France', 'martin'),
	('Mamadou Kamissoko', 'France', 'kamissoko'),
	('Mamadou Kamissoko', 'France', 'mamadou kamissoko'),
	('Clint Essers', 'Netherlands', 'clint essers'),
	('Clint Essers', 'Netherlands', 'essers'),
	('Yeo Reum', 'Korea Republic', 'yeo reum'),
	('Yeo Reum', 'Korea Republic', 'reum'),
	('Lion Schweers', 'Germany', 'schweers'),
	('Lion Schweers', 'Germany', 'lion schweers'),
	('Andrei Patache', 'Romania', 'patache'),
	('Andrei Patache', 'Romania', 'andrei patache'),
	('Martin Kreuzriegler', 'Austria', 'martin kreuzriegler'),
	('Martin Kreuzriegler', 'Austria', 'kreuzriegler'),
	('João Felipe', 'Brazil', 'felipe'),
	('João Felipe', 'Brazil', 'joao felipe'),
	('Francisco Mera', 'Ecuador', 'mera'),
	('Francisco Mera', 'Ecuador', 'francisco mera'),
	('Stefan Hager', 'Austria', 'hager'),
	('Stefan Hager', 'Austria', 'stefan hager'),
	('Metehan Güçlü', 'Turkey', 'guclu'),
	('Metehan Güçlü', 'Turkey', 'metehan guclu'),
	('Janek Sternberg', 'Germany', 'sternberg'),
	('Janek Sternberg', 'Germany', 'janek sternberg'),
	('Amadou Bakayoko', 'Sierra Leone', 'bakayoko'),
	('Amadou Bakayoko', 'Sierra Leone', 'amadou bakayoko'),
	('Tim Söderström', 'Sweden', 'tim soderstrom'),
	('Tim Söderström', 'Sweden', 'soderstrom'),
	('Jefferson Caicedo', 'Ecuador', 'jefferson caicedo'),
	('Jefferson Caicedo', 'Ecuador', 'caicedo'),
	('Mauro Luna Diale', 'Argentina', 'diale'),
	('Mauro Luna Diale', 'Argentina', 'mauro luna diale'),
	('Andrés García', 'Spain', 'andres garcia'),
	('Andrés García', 'Spain', 'garcia'),
	('Bradley Danger', 'France', 'danger'),
	('Bradley Danger', 'France', 'bradley danger'),
	('Harold González', 'Ecuador', 'gonzalez'),
	('Harold González', 'Ecuador', 'harold gonzalez'),
	('Eijiro Takeda', 'Japan', 'takeda'),
	('Eijiro Takeda', 'Japan', 'eijiro takeda'),
	('Kieron Morris', 'England', 'kieron morris'),
	('Kieron Morris', 'England', 'morris'),
	('Dean Gerken', 'England', 'gerken'),
	('Dean Gerken', 'England', 'dean gerken'),
	('Manu Hernando', 'Spain', 'hernando'),
	('Manu Hernando', 'Spain', 'manu hernando'),
	('Liam Fraser', 'Canada', 'fraser'),
	('Liam Fraser', 'Canada', 'liam fraser'),
	('Edi Semedo', 'Portugal', 'edi semedo'),
	('Edi Semedo', 'Portugal', 'semedo'),
	('Johan Lædre Bjørdal', 'Norway', 'johan ldre bjrdal'),
	('Johan Lædre Bjørdal', 'Norway', 'bjrdal'),
	('Hokuto Shimoda', 'Japan', 'hokuto shimoda'),
	('Hokuto Shimoda', 'Japan', 'shimoda'),
	('De la Fuente', 'Spain', 'fuente'),
	('De la Fuente', 'Spain', 'de la fuente'),
	('Alex Gersbach', 'Australia', 'alex gersbach'),
	('Alex Gersbach', 'Australia', 'gersbach'),
	('Mthokozisi Dube', 'South Africa', 'mthokozisi dube'),
	('Mthokozisi Dube', 'South Africa', 'dube'),
	('Eden Massouema', 'France', 'massouema'),
	('Eden Massouema', 'France', 'eden massouema'),
	('İlkay Durmuş', 'Turkey', 'ilkay durmus'),
	('İlkay Durmuş', 'Turkey', 'durmus'),
	('Junior Messias', 'Brazil', 'messias'),
	('Junior Messias', 'Brazil', 'junior messias'),
	('Murat Şatin', 'Austria', 'murat satin'),
	('Murat Şatin', 'Austria', 'satin'),
	('Bubacar Djaló', 'Portugal', 'djalo'),
	('Bubacar Djaló', 'Portugal', 'bubacar djalo'),
	('Yu Yang', 'China PR', 'yu yang'),
	('Yu Yang', 'China PR', 'yang'),
	('Kgosi Ntlhe', 'South Africa', 'kgosi ntlhe'),
	('Kgosi Ntlhe', 'South Africa', 'ntlhe'),
	('Marco Farfan', 'United States', 'marco farfan'),
	('Marco Farfan', 'United States', 'farfan'),
	('Dirk Carlson', 'Luxembourg', 'carlson'),
	('Dirk Carlson', 'Luxembourg', 'dirk carlson'),
	('Julián Navas', 'Argentina', 'navas'),
	('Julián Navas', 'Argentina', 'julian navas'),
	('Josh Clarke', 'England', 'clarke'),
	('Josh Clarke', 'England', 'josh clarke'),
	('Rico Preißinger', 'Germany', 'rico preiinger'),
	('Rico Preißinger', 'Germany', 'preiinger'),
	('Wes McDonald', 'England', 'wes mcdonald'),
	('Wes McDonald', 'England', 'mcdonald'),
	('Bilal Ould-Chikh', 'Morocco', 'ouldchikh'),
	('Bilal Ould-Chikh', 'Morocco', 'bilal ouldchikh'),
	('Leandro Vega', 'Argentina', 'vega'),
	('Leandro Vega', 'Argentina', 'leandro vega'),
	('Roberto Nurse', 'Panama', 'nurse'),
	('Roberto Nurse', 'Panama', 'roberto nurse'),
	('Berto', 'Spain', 'berto'),
	('James Musa', 'New Zealand', 'james musa'),
	('James Musa', 'New Zealand', 'musa'),
	('Luca Horn', 'Germany', 'horn'),
	('Luca Horn', 'Germany', 'luca horn'),
	('Berrocal', 'Spain', 'berrocal'),
	('Tomás Conechny', 'Argentina', 'tomas conechny'),
	('Tomás Conechny', 'Argentina', 'conechny'),
	('Christian Jakobsen', 'Denmark', 'jakobsen'),
	('Christian Jakobsen', 'Denmark', 'christian jakobsen'),
	('Jake Caprice', 'England', 'jake caprice'),
	('Jake Caprice', 'England', 'caprice'),
	('Edwin Cerrillo', 'United States', 'cerrillo'),
	('Edwin Cerrillo', 'United States', 'edwin cerrillo'),
	('Demba Thiam', 'France', 'demba thiam'),
	('Demba Thiam', 'France', 'thiam'),
	('Mehdi Chahiri', 'France', 'mehdi chahiri'),
	('Mehdi Chahiri', 'France', 'chahiri'),
	('Gustav Henriksson', 'Sweden', 'gustav henriksson'),
	('Gustav Henriksson', 'Sweden', 'henriksson'),
	('Seigo Kobayashi', 'Japan', 'seigo kobayashi'),
	('Seigo Kobayashi', 'Japan', 'kobayashi'),
	('Adil Demirbağ', 'Turkey', 'demirbag'),
	('Adil Demirbağ', 'Turkey', 'adil demirbag'),
	('Samuel Mráz', 'Slovakia', 'samuel mraz'),
	('Samuel Mráz', 'Slovakia', 'mraz'),
	('Khiry Shelton', 'United States', 'khiry shelton'),
	('Khiry Shelton', 'United States', 'shelton'),
	('Lucas Marques', 'Brazil', 'lucas marques'),
	('Lucas Marques', 'Brazil', 'marques'),
	('Benítez', 'Spain', 'benitez'),
	('Rhys Marshall', 'Northern Ireland', 'rhys marshall'),
	('Rhys Marshall', 'Northern Ireland', 'marshall'),
	('Jorge Cuenca', 'Spain', 'jorge cuenca'),
	('Jorge Cuenca', 'Spain', 'cuenca'),
	('Jens Jakob Thomasen', 'Denmark', 'thomasen'),
	('Jens Jakob Thomasen', 'Denmark', 'jens jakob thomasen'),
	('Edanyilber Navas', 'Venezuela', 'navas'),
	('Edanyilber Navas', 'Venezuela', 'edanyilber navas'),
	('Goran Karanović', 'Switzerland', 'karanovic'),
	('Goran Karanović', 'Switzerland', 'goran karanovic'),
	('Indy Groothuizen', 'Netherlands', 'groothuizen'),
	('Indy Groothuizen', 'Netherlands', 'indy groothuizen'),
	('Mitch Pinnock', 'England', 'pinnock'),
	('Mitch Pinnock', 'England', 'mitch pinnock'),
	('Haris Radetinac', 'Serbia', 'radetinac'),
	('Haris Radetinac', 'Serbia', 'haris radetinac'),
	('Marcos Ovejero', 'Argentina', 'marcos ovejero'),
	('Marcos Ovejero', 'Argentina', 'ovejero'),
	('Sergio Barreto', 'Argentina', 'sergio barreto'),
	('Sergio Barreto', 'Argentina', 'barreto'),
	('Ryan Inniss', 'England', 'ryan inniss'),
	('Ryan Inniss', 'England', 'inniss'),
	('Greg Kiltie', 'Scotland', 'greg kiltie'),
	('Greg Kiltie', 'Scotland', 'kiltie'),
	('Nikolas Nartey', 'Denmark', 'nartey'),
	('Nikolas Nartey', 'Denmark', 'nikolas nartey'),
	('Maudo Lamine Jarjué', 'Gambia', 'jarjue'),
	('Maudo Lamine Jarjué', 'Gambia', 'maudo lamine jarjue'),
	('Eirik Wichne', 'Norway', 'eirik wichne'),
	('Eirik Wichne', 'Norway', 'wichne'),
	('Răzvan Grădinaru', 'Romania', 'gradinaru'),
	('Răzvan Grădinaru', 'Romania', 'razvan gradinaru'),
	('Mathias Greve', 'Denmark', 'mathias greve'),
	('Mathias Greve', 'Denmark', 'greve'),
	('Zhao Yuhao', 'China PR', 'yuhao'),
	('Zhao Yuhao', 'China PR', 'zhao yuhao'),
	('Nicolae Carnat', 'Romania', 'nicolae carnat'),
	('Nicolae Carnat', 'Romania', 'carnat'),
	('Jan Bamert', 'Switzerland', 'jan bamert'),
	('Jan Bamert', 'Switzerland', 'bamert'),
	('Louis Thompson', 'Wales', 'thompson'),
	('Louis Thompson', 'Wales', 'louis thompson'),
	('Kevin Goden', 'Germany', 'kevin goden'),
	('Kevin Goden', 'Germany', 'goden'),
	('Tito Valencia', 'Ecuador', 'valencia'),
	('Tito Valencia', 'Ecuador', 'tito valencia'),
	('Aldo Araujo', 'Argentina', 'aldo araujo'),
	('Aldo Araujo', 'Argentina', 'araujo'),
	('Anthony Caceres', 'Australia', 'caceres'),
	('Anthony Caceres', 'Australia', 'anthony caceres'),
	('Camilo Mancilla', 'Colombia', 'mancilla'),
	('Camilo Mancilla', 'Colombia', 'camilo mancilla'),
	('John-Joe O''Toole', 'Republic of Ireland', 'johnjoe otoole'),
	('John-Joe O''Toole', 'Republic of Ireland', 'otoole')
)
INSERT INTO reference_entity_aliases (entity_id, alias)
SELECT re.id, v.alias FROM v
JOIN reference_entities re ON re.canonical_name = v.name AND re.category = v.cat AND re.entity_type = 'player';