#!/usr/bin/env python3
"""Derives club_badge_questions rows (see db/schema.sql) from the two
existing sources of a player's club history:

  - transfers: the 18 original batch-1 players (Messi, Ronaldo, ...) --
    chain from_club_id -> to_club_id ordered by transfer_date.
  - player_career_stats: the 103 batch1_remaining players -- resolved
    team_id values in row insertion order (mirrors the source Wikipedia
    infobox's top-to-bottom, i.e. chronological, order).

Mechanical derivation only, no judgment calls beyond the fixed rule below
-- same "objective, not ad-hoc" approach as the rest of data/research/.
A player is included only if they have >= 2 distinct resolved clubs after
de-duplication (a single-club "sequence" isn't a guessing game). No manual
per-player review: every player in these two source tables was already
curated once, for fame, when their batch was chosen (see
docs/stats-enrichment.md's scope section) -- this script's only job is
"can a club sequence be built from what's already there", not "is this
player interesting enough".

Usage: python3 data/research/build_club_badge_questions.py --db <path to local D1 sqlite file>
Writes data/research/club_badge_questions.sql.
"""
import argparse
import json
import sqlite3
import sys


def dedupe_ordered(seq):
    seen = set()
    out = []
    for x in seq:
        if x is None or x in seen:
            continue
        seen.add(x)
        out.append(x)
    return out


def from_transfers(conn):
    cur = conn.execute(
        "SELECT player_id, from_club_id, to_club_id FROM transfers ORDER BY player_id, transfer_date"
    )
    by_player = {}
    for player_id, from_id, to_id in cur.fetchall():
        chain = by_player.setdefault(player_id, [])
        if not chain:
            chain.append(from_id)
        chain.append(to_id)
    results = []
    for player_id, chain in by_player.items():
        clubs = dedupe_ordered(chain)
        if len(clubs) >= 2:
            results.append((player_id, clubs, "transfers"))
    return results


def from_career_stats(conn):
    cur = conn.execute(
        "SELECT player_id, team_id FROM player_career_stats "
        "WHERE competition_type='club' ORDER BY player_id, id"
    )
    by_player = {}
    for player_id, team_id in cur.fetchall():
        by_player.setdefault(player_id, []).append(team_id)
    results = []
    for player_id, chain in by_player.items():
        clubs = dedupe_ordered(chain)
        if len(clubs) >= 2:
            results.append((player_id, clubs, "player_career_stats"))
    return results


def sql_str(s):
    return "'" + s.replace("'", "''") + "'"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", required=True, help="path to local D1 sqlite file (read-only)")
    parser.add_argument("--out", default="data/research/club_badge_questions.sql")
    args = parser.parse_args()

    conn = sqlite3.connect(f"file:{args.db}?mode=ro", uri=True)
    try:
        rows = from_transfers(conn) + from_career_stats(conn)
    finally:
        conn.close()

    rows.sort(key=lambda r: r[0])
    print(f"{len(rows)} players qualify (>= 2 distinct resolved clubs)", file=sys.stderr)

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("-- Generated by data/research/build_club_badge_questions.py -- do not hand-edit.\n")
        f.write("-- One row per player with a usable (>= 2 distinct resolved clubs) chronological\n")
        f.write("-- club sequence, derived from transfers/player_career_stats. Re-run and\n")
        f.write("-- regenerate this file if either source table changes materially (e.g. more\n")
        f.write("-- players researched) rather than hand-editing rows in here.\n\n")
        f.write(
            "INSERT INTO club_badge_questions (player_id, club_sequence, source) VALUES\n"
        )
        lines = []
        for player_id, clubs, source in rows:
            club_json = json.dumps(clubs)
            lines.append(f"({player_id}, {sql_str(club_json)}, {sql_str(source)})")
        f.write(",\n".join(lines))
        f.write(";\n")

    print(f"wrote {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
