#!/usr/bin/env python3
"""Derives teammate_questions rows (see db/schema.sql) from
player_career_stats -- a mystery player identified by three well-known
former teammates ("Who am I? I played with...").

FAIL-CLOSED BY DESIGN
--------------------
Two players count as teammates ONLY if all of the following hold, from the
data actually on record -- anything short of this is dropped, never guessed
(same "objective, not ad-hoc" rule as build_club_badge_questions.py, and
the user's explicit instruction 2026-09-10: "if there is doubt, then assume
that they didn't play together until better data becomes available"):

  1. Same club, resolved to the SAME entities.id (team_id NOT NULL on both
     player_career_stats rows). An unresolved club name can't be trusted to
     be the same club as another unresolved one.
  2. competition_type = 'club'. Being in the same 26-man national-team
     squad for a tournament is not "played with".
  3. Neither stint is a loan (team_name_raw not ending in "(loan)").
  4. Their listed year ranges overlap by at least one full shared season:
     min(end_a, end_b) - max(start_a, start_b) >= 1, where an open-ended
     range ("2021-") ends at the current year. That excludes the genuinely
     ambiguous handoff case (A "2016-2019", B "2019-2022" -> diff 0: A may
     have left exactly as B arrived). It does NOT fully rule out a
     transfer-window near-miss within a shared calendar year -- year
     granularity is the current ceiling. Exact transfer dates (transfers
     table, only 18 players today) would let this be tighter.

For every player left with >= 3 qualifying teammates, the 3 with the
LOWEST entity id are chosen as the clue set -- entity id ascending order is
the same manual fame ranking used for club-badge Sets (lower id was
curated as more globally recognizable), so this picks the three most
recognizable real teammates without a second fame judgment here.

Usage: python3 data/research/build_teammate_questions.py --db <path to local D1 sqlite file>
Writes data/research/teammate_questions.sql.
"""
import argparse
import json
import re
import sqlite3
import sys

CURRENT_YEAR = 2026


def parse_years(s):
    """'2018-2021' -> (2018, 2021); '2021-' -> (2021, CURRENT_YEAR);
    '2020' -> (2020, 2020); anything else -> None (dropped, not guessed)."""
    s = s.strip()
    m = re.match(r"^(\d{4})\s*[–—-]\s*(\d{4})?$", s)
    if m:
        start = int(m.group(1))
        end = int(m.group(2)) if m.group(2) else CURRENT_YEAR
        return (start, end) if end >= start else None
    m = re.match(r"^(\d{4})$", s)
    if m:
        return int(m.group(1)), int(m.group(1))
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", required=True)
    ap.add_argument("--out", default="data/research/teammate_questions.sql")
    ap.add_argument("--min-teammates", type=int, default=3)
    args = ap.parse_args()

    conn = sqlite3.connect(args.db)
    rows = conn.execute(
        """
        SELECT pcs.player_id, pcs.team_id, pcs.team_name_raw, pcs.years_display
        FROM player_career_stats pcs
        WHERE pcs.competition_type = 'club'
          AND pcs.team_id IS NOT NULL
          AND pcs.years_display IS NOT NULL
        """
    ).fetchall()

    # team_id -> list of (player_id, start, end), loans excluded
    by_team = {}
    dropped_unparseable = 0
    for player_id, team_id, raw, years_display in rows:
        if re.search(r"\(loan\)\s*$", raw or ""):
            continue
        yr = parse_years(years_display)
        if yr is None:
            dropped_unparseable += 1
            continue
        by_team.setdefault(team_id, []).append((player_id, yr[0], yr[1]))

    # teammate graph: undirected, player_id -> set(player_id)
    graph = {}
    for stints in by_team.values():
        for i in range(len(stints)):
            for j in range(i + 1, len(stints)):
                a_pid, a_s, a_e = stints[i]
                b_pid, b_s, b_e = stints[j]
                if a_pid == b_pid:
                    continue
                if min(a_e, b_e) - max(a_s, b_s) >= 1:  # >= 1 full shared season
                    graph.setdefault(a_pid, set()).add(b_pid)
                    graph.setdefault(b_pid, set()).add(a_pid)

    questions = []
    for player_id, mates in graph.items():
        if len(mates) < args.min_teammates:
            continue
        clue_ids = sorted(mates)[:3]  # lowest id = most famous
        questions.append((player_id, clue_ids))
    questions.sort()

    names = dict(
        conn.execute(
            "SELECT id, canonical_name FROM entities WHERE entity_type = 'player'"
        ).fetchall()
    )

    with open(args.out, "w") as f:
        f.write("-- Generated by data/research/build_teammate_questions.py -- do not hand-edit.\n")
        f.write("-- One row per mystery player with >= 3 fail-closed-verified former\n")
        f.write("-- teammates; teammate_ids is the 3 most recognizable (lowest entity id).\n")
        f.write("-- Regenerate if player_career_stats changes materially.\n\n")
        f.write("INSERT INTO teammate_questions (player_id, teammate_ids, source) VALUES\n")
        entries = []
        for player_id, clue_ids in questions:
            who = names.get(player_id, f"id {player_id}")
            mates = ", ".join(names.get(t, str(t)) for t in clue_ids)
            ids_json = json.dumps(clue_ids, separators=(",", ":"))
            # Comment on its OWN line above the tuple -- a trailing `--`
            # comment would swallow the `,` separator that follows it.
            entries.append(f"\t-- {who}: {mates}\n\t({player_id}, '{ids_json}', 'player_career_stats')")
        f.write(",\n".join(entries))
        f.write(";\n")

    print(f"{len(rows)} club stint rows, {dropped_unparseable} dropped (unparseable years)")
    print(f"{len(graph)} players have >=1 verified teammate; {len(questions)} have >= {args.min_teammates} -> written to {args.out}")


if __name__ == "__main__":
    main()
