-- Research output: per-team career stats, generated by scripts/research_player_stats.py.
-- Every row is a literal Wikipedia infobox club/international career-history row --
-- mechanical extraction, no LLM judgment, no estimates. The infobox's own separately-
-- maintained totalcaps/totalgoals 'Total' field is NOT used -- a player's career total
-- is a SUM() over these rows. Individual appearances/goals values are NULL wherever the
-- source itself doesn't state a number (never guessed/derived) -- a NULL just means that
-- field isn't usable in a total/category yet, not that the row is wrong.
-- verified_at = 2026-10-09 for all rows.
-- FOR HUMAN REVIEW BEFORE APPLYING. Not applied to any database by this script.

-- Francesco Pio Esposito (entity_id 1001) -- Wikipedia: "Pio Esposito"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1001, 231, 'Inter Milan', 'club', '2023–', 40, 9, NULL, 'English Wikipedia infobox, "Pio Esposito" article', '2026-10-09'),
(1001, 19092, '→ Spezia (loan)', 'club', '2023–2025', 73, 20, NULL, 'English Wikipedia infobox, "Pio Esposito" article', '2026-10-09'),
(1001, NULL, 'Italy U17', 'international', '2022', 4, 1, NULL, 'English Wikipedia infobox, "Pio Esposito" article', '2026-10-09'),
(1001, NULL, 'Italy U18', 'international', '2022–2023', 5, 1, NULL, 'English Wikipedia infobox, "Pio Esposito" article', '2026-10-09'),
(1001, NULL, 'Italy U19', 'international', '2023', 8, 2, NULL, 'English Wikipedia infobox, "Pio Esposito" article', '2026-10-09'),
(1001, NULL, 'Italy U20', 'international', '2023', 6, 1, NULL, 'English Wikipedia infobox, "Pio Esposito" article', '2026-10-09'),
(1001, NULL, 'Italy U21', 'international', '2023–2024', 11, 7, NULL, 'English Wikipedia infobox, "Pio Esposito" article', '2026-10-09'),
(1001, 445, 'Italy', 'international', '2025–', 13, 7, NULL, 'English Wikipedia infobox, "Pio Esposito" article', '2026-10-09');

-- Petar Sucic (entity_id 1002) -- Wikipedia: "Petar Sučić"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1002, 300, 'Dinamo Zagreb', 'club', '2022–2025', 51, 6, NULL, 'English Wikipedia infobox, "Petar Sučić" article', '2026-10-09'),
(1002, 19463, '→ Zrinjski Mostar (loan)', 'club', '2022–2023', 27, 0, NULL, 'English Wikipedia infobox, "Petar Sučić" article', '2026-10-09'),
(1002, 231, 'Inter Milan', 'club', '2025–', 38, 2, NULL, 'English Wikipedia infobox, "Petar Sučić" article', '2026-10-09'),
(1002, NULL, 'Bosnia and Herzegovina U19', 'international', '2021–2022', 16, 0, NULL, 'English Wikipedia infobox, "Petar Sučić" article', '2026-10-09'),
(1002, NULL, 'Bosnia and Herzegovina U21', 'international', '2022–2023', 8, 0, NULL, 'English Wikipedia infobox, "Petar Sučić" article', '2026-10-09'),
(1002, 429, 'Croatia', 'international', '2024–', 25, 2, NULL, 'English Wikipedia infobox, "Petar Sučić" article', '2026-10-09');

-- Mike Maignan (entity_id 1003) -- Wikipedia: "Mike Maignan"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1003, NULL, 'Paris Saint-Germain II', 'club', '2012–2015', 42, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09'),
(1003, NULL, 'Lille II', 'club', '2015–2017', 10, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09'),
(1003, 265, 'Lille', 'club', '2015–2021', 149, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09'),
(1003, 235, 'AC Milan', 'club', '2021–', 162, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09'),
(1003, NULL, 'France U16', 'international', '2010–2011', 10, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09'),
(1003, NULL, 'France U17', 'international', '2011–2012', 12, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09'),
(1003, NULL, 'France U18', 'international', '2012–2013', 5, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09'),
(1003, NULL, 'France U19', 'international', '2013', 3, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09'),
(1003, NULL, 'France U20', 'international', '2014', 1, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09'),
(1003, NULL, 'France U21', 'international', '2015–2016', 6, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09'),
(1003, 437, 'France', 'international', '2020–', 51, 0, NULL, 'English Wikipedia infobox, "Mike Maignan" article', '2026-10-09');

-- Christian Pulisic (entity_id 1004) -- Wikipedia: "Christian Pulisic"
-- SCOPE CAVEAT on club rows (infobox wikitext comment): <!--DOMESTIC LEAGUE APPEARANCES ONLY! -->
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1004, 244, 'Borussia Dortmund', 'club', '2016–2019', 90, 13, '<!--DOMESTIC LEAGUE APPEARANCES ONLY! -->', 'English Wikipedia infobox, "Christian Pulisic" article', '2026-10-09'),
(1004, 189, 'Chelsea', 'club', '2019–2023', 98, 20, '<!--DOMESTIC LEAGUE APPEARANCES ONLY! -->', 'English Wikipedia infobox, "Christian Pulisic" article', '2026-10-09'),
(1004, NULL, '(row 3)', 'club', NULL, NULL, NULL, '<!--DOMESTIC LEAGUE APPEARANCES ONLY! -->', 'English Wikipedia infobox, "Christian Pulisic" article', '2026-10-09'),
(1004, 235, 'AC Milan', 'club', '2023–', 102, 32, '<!--DOMESTIC LEAGUE APPEARANCES ONLY! -->', 'English Wikipedia infobox, "Christian Pulisic" article', '2026-10-09'),
(1004, NULL, 'United States U15', 'international', '2012–2013', 10, 2, NULL, 'English Wikipedia infobox, "Christian Pulisic" article', '2026-10-09'),
(1004, NULL, 'United States U17', 'international', '2013–2015', 34, 20, NULL, 'English Wikipedia infobox, "Christian Pulisic" article', '2026-10-09'),
(1004, NULL, 'United States', 'international', '2016–', 90, 33, NULL, 'English Wikipedia infobox, "Christian Pulisic" article', '2026-10-09');

-- Rafael Leao (entity_id 1005) -- Wikipedia: "Rafael Leão"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1005, NULL, 'Sporting CP B', 'club', '2017–2018', 12, 7, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09'),
(1005, 281, 'Sporting CP', 'club', '2017–2018', 4, 1, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09'),
(1005, 265, 'Lille', 'club', '2018–2019', 26, 8, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09'),
(1005, 235, 'AC Milan', 'club', '2019–2026', 227, 64, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09'),
(1005, 289, 'Galatasaray', 'club', '2026–', 2, 0, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09'),
(1005, NULL, 'Portugal U16', 'international', '2014–2016', 10, 2, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09'),
(1005, NULL, 'Portugal U17', 'international', '2015–2016', 11, 4, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09'),
(1005, NULL, 'Portugal U19', 'international', '2016–2017', 17, 5, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09'),
(1005, NULL, 'Portugal U20', 'international', '2017–2019', 8, 2, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09'),
(1005, NULL, 'Portugal U21', 'international', '2017–2021', 15, 1, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09'),
(1005, 461, 'Portugal', 'international', '2021–', 51, 6, NULL, 'English Wikipedia infobox, "Rafael Leão" article', '2026-10-09');

-- Theo Hernandez (entity_id 1006) -- Wikipedia: "Théo Hernandez"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1006, NULL, 'Atlético Madrid B', 'club', '2015–2017', 9, 0, NULL, 'English Wikipedia infobox, "Théo Hernandez" article', '2026-10-09'),
(1006, 203, '→ Alavés (loan)', 'club', '2016–2017', 32, 1, NULL, 'English Wikipedia infobox, "Théo Hernandez" article', '2026-10-09'),
(1006, 217, 'Real Madrid', 'club', '2017–2019', 13, 0, NULL, 'English Wikipedia infobox, "Théo Hernandez" article', '2026-10-09'),
(1006, 219, '→ Real Sociedad (loan)', 'club', '2018–2019', 24, 1, NULL, 'English Wikipedia infobox, "Théo Hernandez" article', '2026-10-09'),
(1006, 235, 'AC Milan', 'club', '2019–2025', 195, 31, NULL, 'English Wikipedia infobox, "Théo Hernandez" article', '2026-10-09'),
(1006, 328, 'Al Hilal', 'club', '2025–', 34, 6, NULL, 'English Wikipedia infobox, "Théo Hernandez" article', '2026-10-09'),
(1006, NULL, 'France U18', 'international', '2015', 4, 0, NULL, 'English Wikipedia infobox, "Théo Hernandez" article', '2026-10-09'),
(1006, NULL, 'France U19', 'international', '2015–2016', 9, 0, NULL, 'English Wikipedia infobox, "Théo Hernandez" article', '2026-10-09'),
(1006, NULL, 'France U20', 'international', '2016', 3, 1, NULL, 'English Wikipedia infobox, "Théo Hernandez" article', '2026-10-09'),
(1006, 437, 'France', 'international', '2021–', 49, 2, NULL, 'English Wikipedia infobox, "Théo Hernandez" article', '2026-10-09');

-- Fikayo Tomori (entity_id 1007) -- Wikipedia: "Fikayo Tomori"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1007, 189, 'Chelsea', 'club', '2016–2021', 17, 1, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09'),
(1007, 187, '→ Brighton & Hove Albion (loan)', 'club', '2017', 9, 0, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09'),
(1007, 322, '→ Hull City (loan)', 'club', '2017–2018', 25, 0, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09'),
(1007, 316, '→ Derby County (loan)', 'club', '2018–2019', 44, 1, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09'),
(1007, 235, '→ AC Milan (loan)', 'club', '2021', 17, 1, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09'),
(1007, 235, 'AC Milan', 'club', '2021–', 145, 5, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09'),
(1007, NULL, 'Canada U20', 'international', '2016', 3, 0, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09'),
(1007, NULL, 'England U19', 'international', '2016', 5, 0, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09'),
(1007, NULL, 'England U20', 'international', '2016–2017', 15, 0, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09'),
(1007, NULL, 'England U21', 'international', '2017–2019', 15, 0, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09'),
(1007, 433, 'England', 'international', '2019–', 6, 0, NULL, 'English Wikipedia infobox, "Fikayo Tomori" article', '2026-10-09');

-- Matteo Gabbia (entity_id 1008) -- Wikipedia: "Matteo Gabbia"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1008, 235, 'AC Milan', 'club', '2017–', 113, 4, NULL, 'English Wikipedia infobox, "Matteo Gabbia" article', '2026-10-09'),
(1008, NULL, '→ Lucchese (loan)', 'club', '2018–2019', 29, 1, NULL, 'English Wikipedia infobox, "Matteo Gabbia" article', '2026-10-09'),
(1008, 222, '→ Villarreal (loan)', 'club', '2023–2024', 7, 0, NULL, 'English Wikipedia infobox, "Matteo Gabbia" article', '2026-10-09'),
(1008, NULL, 'Italy U15', 'international', '2014', 3, 0, NULL, 'English Wikipedia infobox, "Matteo Gabbia" article', '2026-10-09'),
(1008, NULL, 'Italy U16', 'international', '2014–2015', 13, 3, NULL, 'English Wikipedia infobox, "Matteo Gabbia" article', '2026-10-09'),
(1008, NULL, 'Italy U17', 'international', '2015–2016', 17, 2, NULL, 'English Wikipedia infobox, "Matteo Gabbia" article', '2026-10-09'),
(1008, NULL, 'Italy U18', 'international', '2016–2017', 4, 4, NULL, 'English Wikipedia infobox, "Matteo Gabbia" article', '2026-10-09'),
(1008, NULL, 'Italy U19', 'international', '2016–2018', 21, 3, NULL, 'English Wikipedia infobox, "Matteo Gabbia" article', '2026-10-09'),
(1008, NULL, 'Italy U20', 'international', '2018–2019', 14, 0, NULL, 'English Wikipedia infobox, "Matteo Gabbia" article', '2026-10-09'),
(1008, NULL, 'Italy U21', 'international', '2019–2021', 7, 0, NULL, 'English Wikipedia infobox, "Matteo Gabbia" article', '2026-10-09');

-- Youssouf Fofana (entity_id 1009) -- Wikipedia: "Youssouf Fofana (footballer, born 1999)"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1009, NULL, 'Strasbourg B', 'club', '2017–2018', 34, 4, NULL, 'English Wikipedia infobox, "Youssouf Fofana (footballer, born 1999)" article', '2026-10-09'),
(1009, 269, 'Strasbourg', 'club', '2018–2020', 30, 3, NULL, 'English Wikipedia infobox, "Youssouf Fofana (footballer, born 1999)" article', '2026-10-09'),
(1009, 264, 'Monaco', 'club', '2020–2024', 143, 6, NULL, 'English Wikipedia infobox, "Youssouf Fofana (footballer, born 1999)" article', '2026-10-09'),
(1009, 235, 'AC Milan', 'club', '2024–', 68, 3, NULL, 'English Wikipedia infobox, "Youssouf Fofana (footballer, born 1999)" article', '2026-10-09'),
(1009, 220, '→ Sevilla (loan)', 'club', '2026–', 4, 1, NULL, 'English Wikipedia infobox, "Youssouf Fofana (footballer, born 1999)" article', '2026-10-09'),
(1009, NULL, 'France U19', 'international', '2018', 1, 0, NULL, 'English Wikipedia infobox, "Youssouf Fofana (footballer, born 1999)" article', '2026-10-09'),
(1009, NULL, 'France U20', 'international', '2018–2019', 9, 1, NULL, 'English Wikipedia infobox, "Youssouf Fofana (footballer, born 1999)" article', '2026-10-09'),
(1009, NULL, 'France U21', 'international', '2019', 1, 0, NULL, 'English Wikipedia infobox, "Youssouf Fofana (footballer, born 1999)" article', '2026-10-09'),
(1009, 437, 'France', 'international', '2022–2024', 25, 3, NULL, 'English Wikipedia infobox, "Youssouf Fofana (footballer, born 1999)" article', '2026-10-09');

-- Adrien Rabiot (entity_id 1010) -- Wikipedia: "Adrien Rabiot"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1010, NULL, 'Paris Saint-Germain II', 'club', '2012–2014', 9, 0, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, 261, 'Paris Saint-Germain', 'club', '2012–2019', 150, 13, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, NULL, '→ Toulouse II (loan)', 'club', '2013', 2, 1, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, 270, '→ Toulouse (loan)', 'club', '2013', 13, 1, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, 232, 'Juventus', 'club', '2019–2024', 157, 18, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, 262, 'Marseille', 'club', '2024–2025', 30, 9, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, 235, 'AC Milan', 'club', '2025–', 34, 8, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, NULL, 'France U16', 'international', '2010', 2, 0, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, NULL, 'France U17', 'international', '2011–2012', 5, 0, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, NULL, 'France U18', 'international', '2012', 1, 1, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, NULL, 'France U19', 'international', '2012–2013', 20, 4, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, NULL, 'France U20', 'international', '2014', 6, 0, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, NULL, 'France U21', 'international', '2013–2016', 19, 2, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09'),
(1010, 437, 'France', 'international', '2016–', 69, 7, NULL, 'English Wikipedia infobox, "Adrien Rabiot" article', '2026-10-09');

-- Santiago Gimenez (entity_id 1011) -- Wikipedia: "Santiago Giménez"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1011, 336, 'Cruz Azul', 'club', '2017–2022', 88, 20, NULL, 'English Wikipedia infobox, "Santiago Giménez" article', '2026-10-09'),
(1011, 285, 'Feyenoord', 'club', '2022–2025', 73, 45, NULL, 'English Wikipedia infobox, "Santiago Giménez" article', '2026-10-09'),
(1011, 235, 'AC Milan', 'club', '2025–', 30, 5, NULL, 'English Wikipedia infobox, "Santiago Giménez" article', '2026-10-09'),
(1011, 279, '→ Porto (loan)', 'club', '2026–', 2, 1, NULL, 'English Wikipedia infobox, "Santiago Giménez" article', '2026-10-09'),
(1011, NULL, 'Mexico U16', 'international', '2016', 3, 0, NULL, 'English Wikipedia infobox, "Santiago Giménez" article', '2026-10-09'),
(1011, NULL, 'Mexico', 'international', '2021–', 52, 6, NULL, 'English Wikipedia infobox, "Santiago Giménez" article', '2026-10-09');

-- Strahinja Pavlovic (entity_id 1012) -- Wikipedia: "Strahinja Pavlović"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1012, 19597, 'Partizan', 'club', '2019–2020', 37, 1, NULL, 'English Wikipedia infobox, "Strahinja Pavlović" article', '2026-10-09'),
(1012, 264, 'Monaco', 'club', '2020–2022', 8, 0, NULL, 'English Wikipedia infobox, "Strahinja Pavlović" article', '2026-10-09'),
(1012, 19001, '→ Cercle Brugge (loan)', 'club', '2021', 11, 1, NULL, 'English Wikipedia infobox, "Strahinja Pavlović" article', '2026-10-09'),
(1012, 19366, '→ Basel (loan)', 'club', '2022', 10, 0, NULL, 'English Wikipedia infobox, "Strahinja Pavlović" article', '2026-10-09'),
(1012, 294, 'Red Bull Salzburg', 'club', '2022–2024', 50, 4, NULL, 'English Wikipedia infobox, "Strahinja Pavlović" article', '2026-10-09'),
(1012, 235, 'AC Milan', 'club', '2024–', 63, 7, NULL, 'English Wikipedia infobox, "Strahinja Pavlović" article', '2026-10-09'),
(1012, NULL, 'Serbia U17', 'international', '2017', 2, 0, NULL, 'English Wikipedia infobox, "Strahinja Pavlović" article', '2026-10-09'),
(1012, NULL, 'Serbia U19', 'international', '2018–2019', 5, 0, NULL, 'English Wikipedia infobox, "Strahinja Pavlović" article', '2026-10-09'),
(1012, NULL, 'Serbia U21', 'international', '2019', 4, 0, NULL, 'English Wikipedia infobox, "Strahinja Pavlović" article', '2026-10-09'),
(1012, 467, 'Serbia', 'international', '2020–', 59, 5, NULL, 'English Wikipedia infobox, "Strahinja Pavlović" article', '2026-10-09');

-- Alexis Saelemaekers (entity_id 1013) -- Wikipedia: "Alexis Saelemaekers"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1013, 293, 'Anderlecht', 'club', '2018–2020', 57, 2, NULL, 'English Wikipedia infobox, "Alexis Saelemaekers" article', '2026-10-09'),
(1013, 235, '→ AC Milan (loan)', 'club', '2020', 13, 1, NULL, 'English Wikipedia infobox, "Alexis Saelemaekers" article', '2026-10-09'),
(1013, 235, 'AC Milan', 'club', '2020–', 138, 8, NULL, 'English Wikipedia infobox, "Alexis Saelemaekers" article', '2026-10-09'),
(1013, 224, '→ Bologna (loan)', 'club', '2023–2024', 30, 4, NULL, 'English Wikipedia infobox, "Alexis Saelemaekers" article', '2026-10-09'),
(1013, 239, '→ Roma (loan)', 'club', '2024–2025', 22, 7, NULL, 'English Wikipedia infobox, "Alexis Saelemaekers" article', '2026-10-09'),
(1013, NULL, 'Belgium U16', 'international', '2015', 1, 0, NULL, 'English Wikipedia infobox, "Alexis Saelemaekers" article', '2026-10-09'),
(1013, NULL, 'Belgium U19', 'international', '2017–2018', 4, 0, NULL, 'English Wikipedia infobox, "Alexis Saelemaekers" article', '2026-10-09'),
(1013, NULL, 'Belgium U21', 'international', '2018–2020', 12, 0, NULL, 'English Wikipedia infobox, "Alexis Saelemaekers" article', '2026-10-09'),
(1013, 426, 'Belgium', 'international', '2020–', 28, 3, NULL, 'English Wikipedia infobox, "Alexis Saelemaekers" article', '2026-10-09');

-- Ruben Loftus-Cheek (entity_id 1014) -- Wikipedia: "Ruben Loftus-Cheek"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1014, 189, 'Chelsea', 'club', '2014–2023', 103, 7, NULL, 'English Wikipedia infobox, "Ruben Loftus-Cheek" article', '2026-10-09'),
(1014, 190, '→ Crystal Palace (loan)', 'club', '2017–2018', 24, 2, NULL, 'English Wikipedia infobox, "Ruben Loftus-Cheek" article', '2026-10-09'),
(1014, 192, '→ Fulham (loan)', 'club', '2020–2021', 30, 1, NULL, 'English Wikipedia infobox, "Ruben Loftus-Cheek" article', '2026-10-09'),
(1014, 235, 'AC Milan', 'club', '2023–', 81, 9, NULL, 'English Wikipedia infobox, "Ruben Loftus-Cheek" article', '2026-10-09'),
(1014, NULL, 'England U16', 'international', '2011', 2, 1, NULL, 'English Wikipedia infobox, "Ruben Loftus-Cheek" article', '2026-10-09'),
(1014, NULL, 'England U17', 'international', '2012–2013', 8, 1, NULL, 'English Wikipedia infobox, "Ruben Loftus-Cheek" article', '2026-10-09'),
(1014, NULL, 'England U19', 'international', '2013–2015', 13, 6, NULL, 'English Wikipedia infobox, "Ruben Loftus-Cheek" article', '2026-10-09'),
(1014, NULL, 'England U21', 'international', '2015–2017', 17, 7, NULL, 'English Wikipedia infobox, "Ruben Loftus-Cheek" article', '2026-10-09'),
(1014, 433, 'England', 'international', '2017–', 11, 0, NULL, 'English Wikipedia infobox, "Ruben Loftus-Cheek" article', '2026-10-09');

-- Samuele Ricci (entity_id 1015) -- Wikipedia: "Samuele Ricci"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1015, 19088, 'Empoli', 'club', '2019–2022', 83, 3, NULL, 'English Wikipedia infobox, "Samuele Ricci" article', '2026-10-09'),
(1015, 241, '→ Torino (loan)', 'club', '2022', 12, 0, NULL, 'English Wikipedia infobox, "Samuele Ricci" article', '2026-10-09'),
(1015, 241, 'Torino', 'club', '2022–2025', 94, 4, NULL, 'English Wikipedia infobox, "Samuele Ricci" article', '2026-10-09'),
(1015, 235, 'AC Milan', 'club', '2025–', 31, 1, NULL, 'English Wikipedia infobox, "Samuele Ricci" article', '2026-10-09'),
(1015, 226, '→ Como (loan)', 'club', '2026–', 3, 0, NULL, 'English Wikipedia infobox, "Samuele Ricci" article', '2026-10-09'),
(1015, NULL, 'Italy U17', 'international', '2017–2018', 12, 3, NULL, 'English Wikipedia infobox, "Samuele Ricci" article', '2026-10-09'),
(1015, NULL, 'Italy U18', 'international', '2018–2019', 6, 1, NULL, 'English Wikipedia infobox, "Samuele Ricci" article', '2026-10-09'),
(1015, NULL, 'Italy U19', 'international', '2019–2020', 11, 0, NULL, 'English Wikipedia infobox, "Samuele Ricci" article', '2026-10-09'),
(1015, NULL, 'Italy U21', 'international', '2020–2023', 17, 1, NULL, 'English Wikipedia infobox, "Samuele Ricci" article', '2026-10-09'),
(1015, 445, 'Italy', 'international', '2022–', 11, 0, NULL, 'English Wikipedia infobox, "Samuele Ricci" article', '2026-10-09');

-- Michele Di Gregorio (entity_id 1016) -- Wikipedia: "Michele Di Gregorio"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1016, 231, 'Inter Milan', 'club', '2017–2022', 0, 0, NULL, 'English Wikipedia infobox, "Michele Di Gregorio" article', '2026-10-09'),
(1016, NULL, '→ Renate (loan)', 'club', '2017–2018', 33, 0, NULL, 'English Wikipedia infobox, "Michele Di Gregorio" article', '2026-10-09'),
(1016, 19097, '→ Novara (loan)', 'club', '2018–2019', 30, 0, NULL, 'English Wikipedia infobox, "Michele Di Gregorio" article', '2026-10-09'),
(1016, NULL, '→ Pordenone (loan)', 'club', '2019–2020', 33, 0, NULL, 'English Wikipedia infobox, "Michele Di Gregorio" article', '2026-10-09'),
(1016, NULL, '→ Monza (loan)', 'club', '2020–2022', 64, 0, NULL, 'English Wikipedia infobox, "Michele Di Gregorio" article', '2026-10-09'),
(1016, NULL, 'Monza', 'club', '2022–2025', 70, 0, NULL, 'English Wikipedia infobox, "Michele Di Gregorio" article', '2026-10-09'),
(1016, 232, '→ Juventus (loan)', 'club', '2024–2025', 33, 0, NULL, 'English Wikipedia infobox, "Michele Di Gregorio" article', '2026-10-09'),
(1016, 232, 'Juventus', 'club', '2025–', 30, 0, NULL, 'English Wikipedia infobox, "Michele Di Gregorio" article', '2026-10-09'),
(1016, 185, '→ Bournemouth (loan)', 'club', '2026–', 0, 0, NULL, 'English Wikipedia infobox, "Michele Di Gregorio" article', '2026-10-09'),
(1016, NULL, 'Italy U17', 'international', '2014', 1, 0, NULL, 'English Wikipedia infobox, "Michele Di Gregorio" article', '2026-10-09');

-- Gleison Bremer (entity_id 1017) -- Wikipedia: "Gleison Bremer"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1017, 38, 'Atlético Mineiro', 'club', '2017–2018', 25, 1, NULL, 'English Wikipedia infobox, "Gleison Bremer" article', '2026-10-09'),
(1017, 241, 'Torino', 'club', '2018–2022', 98, 11, NULL, 'English Wikipedia infobox, "Gleison Bremer" article', '2026-10-09'),
(1017, 232, 'Juventus', 'club', '2022–', 103, 13, NULL, 'English Wikipedia infobox, "Gleison Bremer" article', '2026-10-09'),
(1017, 19157, 'Brazil', 'international', '2022–', 8, 1, NULL, 'English Wikipedia infobox, "Gleison Bremer" article', '2026-10-09');

-- Pierre Kalulu (entity_id 1018) -- Wikipedia: "Pierre Kalulu"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1018, NULL, 'Lyon B', 'club', '2018–2020', 34, 0, NULL, 'English Wikipedia infobox, "Pierre Kalulu" article', '2026-10-09'),
(1018, 235, 'AC Milan', 'club', '2020–2025', 84, 3, NULL, 'English Wikipedia infobox, "Pierre Kalulu" article', '2026-10-09'),
(1018, 232, '→ Juventus (loan)', 'club', '2024–2025', 29, 1, NULL, 'English Wikipedia infobox, "Pierre Kalulu" article', '2026-10-09'),
(1018, 232, 'Juventus', 'club', '2025–', 37, 2, NULL, 'English Wikipedia infobox, "Pierre Kalulu" article', '2026-10-09'),
(1018, NULL, 'France U18', 'international', '2018', 5, 0, NULL, 'English Wikipedia infobox, "Pierre Kalulu" article', '2026-10-09'),
(1018, NULL, 'France U19', 'international', '2018–2019', 12, 0, NULL, 'English Wikipedia infobox, "Pierre Kalulu" article', '2026-10-09'),
(1018, NULL, 'France U20', 'international', '2019', 3, 0, NULL, 'English Wikipedia infobox, "Pierre Kalulu" article', '2026-10-09'),
(1018, NULL, 'France U21', 'international', '2021–2023', 19, 2, NULL, 'English Wikipedia infobox, "Pierre Kalulu" article', '2026-10-09'),
(1018, NULL, 'France Olympic', 'international', '2021', 4, 0, NULL, 'English Wikipedia infobox, "Pierre Kalulu" article', '2026-10-09'),
(1018, 437, 'France', 'international', '2025–', 5, 0, NULL, 'English Wikipedia infobox, "Pierre Kalulu" article', '2026-10-09');

-- Andrea Cambiaso (entity_id 1019) -- Wikipedia: "Andrea Cambiaso"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1019, 229, 'Genoa', 'club', '2017–2022', 26, 1, NULL, 'English Wikipedia infobox, "Andrea Cambiaso" article', '2026-10-09'),
(1019, NULL, '→ Albissola (loan)', 'club', '2017–2018', 21, 0, NULL, 'English Wikipedia infobox, "Andrea Cambiaso" article', '2026-10-09'),
(1019, NULL, '→ Savona (loan)', 'club', '2018–2019', 32, 2, NULL, 'English Wikipedia infobox, "Andrea Cambiaso" article', '2026-10-09'),
(1019, NULL, '→ Alessandria (loan)', 'club', '2019–2020', 17, 0, NULL, 'English Wikipedia infobox, "Andrea Cambiaso" article', '2026-10-09'),
(1019, 19088, '→ Empoli (loan)', 'club', '2020–2021', 7, 0, NULL, 'English Wikipedia infobox, "Andrea Cambiaso" article', '2026-10-09'),
(1019, 232, 'Juventus', 'club', '2022–', 103, 7, NULL, 'English Wikipedia infobox, "Andrea Cambiaso" article', '2026-10-09'),
(1019, 224, '→ Bologna (loan)', 'club', '2022–2023', 32, 0, NULL, 'English Wikipedia infobox, "Andrea Cambiaso" article', '2026-10-09'),
(1019, NULL, 'Italy U21', 'international', '2021–2023', 8, 0, NULL, 'English Wikipedia infobox, "Andrea Cambiaso" article', '2026-10-09'),
(1019, 445, 'Italy', 'international', '2024–', 19, 3, NULL, 'English Wikipedia infobox, "Andrea Cambiaso" article', '2026-10-09');

-- Manuel Locatelli (entity_id 1020) -- Wikipedia: "Manuel Locatelli"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1020, 235, 'AC Milan', 'club', '2016–2019', 48, 2, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09'),
(1020, 240, '→ Sassuolo (loan)', 'club', '2018–2019', 29, 2, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09'),
(1020, 240, 'Sassuolo', 'club', '2019–2023', 67, 4, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09'),
(1020, 232, '→ Juventus (loan)', 'club', '2021–2023', 63, 3, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09'),
(1020, 232, 'Juventus', 'club', '2023–', 111, 4, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09'),
(1020, NULL, 'Italy U15', 'international', '2013', 5, 0, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09'),
(1020, NULL, 'Italy U16', 'international', '2014', 2, 0, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09'),
(1020, NULL, 'Italy U17', 'international', '2013–2015', 25, 1, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09'),
(1020, NULL, 'Italy U19', 'international', '2015–2016', 16, 1, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09'),
(1020, NULL, 'Italy U21', 'international', '2017–2019', 23, 2, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09'),
(1020, 445, 'Italy', 'international', '2020–', 36, 3, NULL, 'English Wikipedia infobox, "Manuel Locatelli" article', '2026-10-09');

-- Khephren Thuram (entity_id 1021) -- Wikipedia: "Khéphren Thuram"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1021, NULL, 'Monaco B', 'club', '2018–2019', 14, 1, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, 264, 'Monaco', 'club', '2018–2019', 0, 0, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, NULL, 'Nice B', 'club', '2019–2020', 4, 0, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, 266, 'Nice', 'club', '2019–2024', 141, 9, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, 232, 'Juventus', 'club', '2024–', 70, 7, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, NULL, 'France U16', 'international', '2016–2017', 12, 1, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, NULL, 'France U17', 'international', '2017–2018', 6, 0, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, NULL, 'France U18', 'international', '2018–2019', 8, 0, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, NULL, 'France U19', 'international', '2019', 7, 1, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, NULL, 'France U21', 'international', '2021–2023', 18, 2, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, NULL, 'France Olympic', 'international', '2024', 2, 0, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09'),
(1021, 437, 'France', 'international', '2023–', 4, 0, NULL, 'English Wikipedia infobox, "Khéphren Thuram" article', '2026-10-09');

-- Teun Koopmeiners (entity_id 1022) -- Wikipedia: "Teun Koopmeiners"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1022, NULL, 'Jong AZ', 'club', '2016–2018', 25, 3, NULL, 'English Wikipedia infobox, "Teun Koopmeiners" article', '2026-10-09'),
(1022, 286, 'AZ', 'club', '2017–2021', 116, 35, NULL, 'English Wikipedia infobox, "Teun Koopmeiners" article', '2026-10-09'),
(1022, 223, 'Atalanta', 'club', '2021–2024', 97, 26, NULL, 'English Wikipedia infobox, "Teun Koopmeiners" article', '2026-10-09'),
(1022, 232, 'Juventus', 'club', '2024–', 61, 3, NULL, 'English Wikipedia infobox, "Teun Koopmeiners" article', '2026-10-09'),
(1022, NULL, 'Netherlands U17', 'international', '2015', 4, 0, NULL, 'English Wikipedia infobox, "Teun Koopmeiners" article', '2026-10-09'),
(1022, NULL, 'Netherlands U18', 'international', '2015–2016', 3, 0, NULL, 'English Wikipedia infobox, "Teun Koopmeiners" article', '2026-10-09'),
(1022, NULL, 'Netherlands U19', 'international', '2016–2017', 13, 0, NULL, 'English Wikipedia infobox, "Teun Koopmeiners" article', '2026-10-09'),
(1022, NULL, 'Netherlands U20', 'international', '2017–2018', 5, 0, NULL, 'English Wikipedia infobox, "Teun Koopmeiners" article', '2026-10-09'),
(1022, NULL, 'Netherlands U21', 'international', '2018–2021', 17, 4, NULL, 'English Wikipedia infobox, "Teun Koopmeiners" article', '2026-10-09'),
(1022, 456, 'Netherlands', 'international', '2020–', 33, 4, NULL, 'English Wikipedia infobox, "Teun Koopmeiners" article', '2026-10-09');

-- Kenan Yildiz (entity_id 1023) -- Wikipedia: "Kenan Yıldız"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1023, NULL, 'Juventus Next Gen', 'club', '2022–2023', 14, 2, NULL, 'English Wikipedia infobox, "Kenan Yıldız" article', '2026-10-09'),
(1023, 232, 'Juventus', 'club', '2023–', 99, 19, NULL, 'English Wikipedia infobox, "Kenan Yıldız" article', '2026-10-09'),
(1023, NULL, 'Turkey U17', 'international', '2021–2022', 10, 3, NULL, 'English Wikipedia infobox, "Kenan Yıldız" article', '2026-10-09'),
(1023, NULL, 'Turkey U21', 'international', '2022–2026', 8, 2, NULL, 'English Wikipedia infobox, "Kenan Yıldız" article', '2026-10-09'),
(1023, 473, 'Turkey', 'international', '2023–', 31, 5, NULL, 'English Wikipedia infobox, "Kenan Yıldız" article', '2026-10-09');

-- Dusan Vlahovic (entity_id 1024) -- Wikipedia: "Dušan Vlahović"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1024, 19597, 'Partizan', 'club', '2016–2018', 21, 1, NULL, 'English Wikipedia infobox, "Dušan Vlahović" article', '2026-10-09'),
(1024, 228, 'Fiorentina', 'club', '2018–2022', 98, 44, NULL, 'English Wikipedia infobox, "Dušan Vlahović" article', '2026-10-09'),
(1024, 232, 'Juventus', 'club', '2022–2026', 123, 50, NULL, 'English Wikipedia infobox, "Dušan Vlahović" article', '2026-10-09'),
(1024, NULL, 'Beşiktaş J.K.', 'club', '2026–', 4, 5, NULL, 'English Wikipedia infobox, "Dušan Vlahović" article', '2026-10-09'),
(1024, NULL, 'Serbia U19', 'international', '2016–2019', 8, 6, NULL, 'English Wikipedia infobox, "Dušan Vlahović" article', '2026-10-09'),
(1024, NULL, 'Serbia U21', 'international', '2019', 3, 0, NULL, 'English Wikipedia infobox, "Dušan Vlahović" article', '2026-10-09'),
(1024, 467, 'Serbia', 'international', '2020–', 41, 16, NULL, 'English Wikipedia infobox, "Dušan Vlahović" article', '2026-10-09');

-- Jonathan David (entity_id 1025) -- Wikipedia: "Jonathan David"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1025, 18997, 'KAA Gent', 'club', '2018–2020', 60, 30, NULL, 'English Wikipedia infobox, "Jonathan David" article', '2026-10-09'),
(1025, 265, 'Lille', 'club', '2020–2025', 178, 87, NULL, 'English Wikipedia infobox, "Jonathan David" article', '2026-10-09'),
(1025, 232, 'Juventus', 'club', '2025–', 36, 6, NULL, 'English Wikipedia infobox, "Jonathan David" article', '2026-10-09'),
(1025, 205, '→ Atlético Madrid (loan)', 'club', '2026–', 3, 3, NULL, 'English Wikipedia infobox, "Jonathan David" article', '2026-10-09'),
(1025, NULL, 'Canada U17', 'international', '2017', 3, 2, NULL, 'English Wikipedia infobox, "Jonathan David" article', '2026-10-09'),
(1025, NULL, 'Canada U21', 'international', '2018', 2, 0, NULL, 'English Wikipedia infobox, "Jonathan David" article', '2026-10-09'),
(1025, NULL, 'Canada', 'international', '2018–', 85, 43, NULL, 'English Wikipedia infobox, "Jonathan David" article', '2026-10-09');

-- Francisco Conceicao (entity_id 1026) -- Wikipedia: "Francisco Conceição"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1026, NULL, 'Porto B', 'club', '2020–2021', 20, 4, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, 279, 'Porto', 'club', '2021–2022', 39, 2, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, NULL, 'Jong Ajax', 'club', '2022–2023', 7, 5, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, 283, 'Ajax', 'club', '2022–2024', 19, 0, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, 279, '→ Porto (loan)', 'club', '2023–2024', 27, 5, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, 279, 'Porto', 'club', '2024–2025', 0, 0, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, 232, '→ Juventus (loan)', 'club', '2024–2025', 26, 3, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, 232, 'Juventus', 'club', '2025–', 36, 4, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, NULL, 'Portugal U16', 'international', '2018', 9, 1, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, NULL, 'Portugal U17', 'international', '2018', 3, 1, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, NULL, 'Portugal U18', 'international', '2019', 3, 1, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, NULL, 'Portugal U21', 'international', '2021–2023', 23, 6, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09'),
(1026, 461, 'Portugal', 'international', '2024–', 23, 4, NULL, 'English Wikipedia infobox, "Francisco Conceição" article', '2026-10-09');

-- Lois Openda (entity_id 1027) -- Wikipedia: "Loïs Openda"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1027, 292, 'Club Brugge', 'club', '2018–2022', 35, 4, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, 18972, '→ Vitesse (loan)', 'club', '2020–2022', 66, 28, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, 267, 'Lens', 'club', '2022–2023', 38, 21, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, 245, 'RB Leipzig', 'club', '2023–2026', 69, 33, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, 232, '→ Juventus (loan)', 'club', '2025–2026', 24, 1, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, 232, 'Juventus', 'club', '2026–', 0, 0, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, 263, '→ Lyon (loan)', 'club', '2026–', 4, 1, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, NULL, 'Belgium U15', 'international', '2015', 4, 0, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, NULL, 'Belgium U16', 'international', '2015', 4, 3, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, NULL, 'Belgium U17', 'international', '2016–2017', 17, 4, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, NULL, 'Belgium U18', 'international', '2017', 6, 1, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, NULL, 'Belgium U19', 'international', '2018–2019', 10, 7, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, NULL, 'Belgium U21', 'international', '2019–2023', 18, 13, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09'),
(1027, 426, 'Belgium', 'international', '2022–', 35, 3, NULL, 'English Wikipedia infobox, "Loïs Openda" article', '2026-10-09');

-- Edon Zhegrova (entity_id 1028) -- Wikipedia: "Edon Zhegrova"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1028, 18996, 'Genk', 'club', '2017–2019', 19, 2, NULL, 'English Wikipedia infobox, "Edon Zhegrova" article', '2026-10-09'),
(1028, 19366, 'Basel', 'club', '2019–2022', 60, 9, NULL, 'English Wikipedia infobox, "Edon Zhegrova" article', '2026-10-09'),
(1028, 265, 'Lille', 'club', '2022–2025', 80, 15, NULL, 'English Wikipedia infobox, "Edon Zhegrova" article', '2026-10-09'),
(1028, 232, 'Juventus', 'club', '2025–', 23, 2, NULL, 'English Wikipedia infobox, "Edon Zhegrova" article', '2026-10-09'),
(1028, 447, 'Kosovo', 'international', '2018–', 50, 6, NULL, 'English Wikipedia infobox, "Edon Zhegrova" article', '2026-10-09');

-- Federico Gatti (entity_id 1029) -- Wikipedia: "Federico Gatti"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1029, NULL, 'Alessandria', 'club', '2014–2017', 0, 0, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09'),
(1029, NULL, '→ Pavarolo (loan)', 'club', '2014–2016', 31, 3, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09'),
(1029, NULL, '→ Saluzzo (loan)', 'club', '2016–2017', 4, 0, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09'),
(1029, NULL, '→ Pavarolo (loan)', 'club', '2017', 15, 5, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09'),
(1029, NULL, 'Pavarolo', 'club', '2017–2018', 32, 7, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09'),
(1029, NULL, 'Verbania', 'club', '2018–2020', 51, 6, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09'),
(1029, NULL, 'Pro Patria', 'club', '2020–2021', 34, 1, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09'),
(1029, 19091, 'Frosinone', 'club', '2021–2022', 18, 3, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09'),
(1029, 232, 'Juventus', 'club', '2022–', 101, 7, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09'),
(1029, 19091, '→ Frosinone (loan)', 'club', '2022', 17, 2, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09'),
(1029, 445, 'Italy', 'international', '2022–', 8, 0, NULL, 'English Wikipedia infobox, "Federico Gatti" article', '2026-10-09');

-- Alex Meret (entity_id 1030) -- Wikipedia: "Alex Meret"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1030, 242, 'Udinese', 'club', '2015–2018', 0, 0, NULL, 'English Wikipedia infobox, "Alex Meret" article', '2026-10-09'),
(1030, NULL, '→ SPAL (loan)', 'club', '2016–2017', 30, 0, NULL, 'English Wikipedia infobox, "Alex Meret" article', '2026-10-09'),
(1030, NULL, '→ SPAL (loan)', 'club', '2017–2018', 13, 0, NULL, 'English Wikipedia infobox, "Alex Meret" article', '2026-10-09'),
(1030, 236, 'Napoli', 'club', '2018–', 178, 0, NULL, 'English Wikipedia infobox, "Alex Meret" article', '2026-10-09'),
(1030, NULL, 'Italy U16', 'international', '2012–2013', 4, 0, NULL, 'English Wikipedia infobox, "Alex Meret" article', '2026-10-09'),
(1030, NULL, 'Italy U17', 'international', '2013–2014', 13, 0, NULL, 'English Wikipedia infobox, "Alex Meret" article', '2026-10-09'),
(1030, NULL, 'Italy U18', 'international', '2014', 2, 0, NULL, 'English Wikipedia infobox, "Alex Meret" article', '2026-10-09'),
(1030, NULL, 'Italy U19', 'international', '2014–2016', 19, 0, NULL, 'English Wikipedia infobox, "Alex Meret" article', '2026-10-09'),
(1030, NULL, 'Italy U21', 'international', '2018–2019', 5, 0, NULL, 'English Wikipedia infobox, "Alex Meret" article', '2026-10-09'),
(1030, 445, 'Italy', 'international', '2019–2022', 3, 0, NULL, 'English Wikipedia infobox, "Alex Meret" article', '2026-10-09');

-- Vanja Milinkovic-Savic (entity_id 1031) -- Wikipedia: "Vanja Milinković-Savić"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1031, 196, 'Manchester United', 'club', '2014–2015', 0, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, NULL, '→ Vojvodina (loan)', 'club', '2014–2015', 17, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, NULL, 'Lechia Gdańsk', 'club', '2016–2017', 29, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, 241, 'Torino', 'club', '2017–2026', 144, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, NULL, '→ SPAL (loan)', 'club', '2018–2019', 2, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, 19609, '→ Ascoli (loan)', 'club', '2019', 8, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, 18995, '→ Standard Liège (loan)', 'club', '2019–2020', 0, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, 236, '→ Napoli (loan)', 'club', '2025–2026', 27, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, 236, 'Napoli', 'club', '2026–', 2, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, NULL, 'Serbia U17', 'international', '2013–2014', 6, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, NULL, 'Serbia U19', 'international', '2014–2016', 9, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, NULL, 'Serbia U20', 'international', '2014–2015', 3, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, NULL, 'Serbia U21', 'international', '2016–2017', 10, 1, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09'),
(1031, 467, 'Serbia', 'international', '2021–', 23, 0, NULL, 'English Wikipedia infobox, "Vanja Milinković-Savić" article', '2026-10-09');

-- Giovanni Di Lorenzo (entity_id 1032) -- Wikipedia: "Giovanni Di Lorenzo"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1032, 19081, 'Reggina', 'club', '2010–2015', 58, 0, NULL, 'English Wikipedia infobox, "Giovanni Di Lorenzo" article', '2026-10-09'),
(1032, NULL, '→ Cuneo (loan)', 'club', '2012–2013', 27, 0, NULL, 'English Wikipedia infobox, "Giovanni Di Lorenzo" article', '2026-10-09'),
(1032, NULL, 'Matera', 'club', '2015–2017', 58, 3, NULL, 'English Wikipedia infobox, "Giovanni Di Lorenzo" article', '2026-10-09'),
(1032, 19088, 'Empoli', 'club', '2017–2019', 73, 6, NULL, 'English Wikipedia infobox, "Giovanni Di Lorenzo" article', '2026-10-09'),
(1032, 236, 'Napoli', 'club', '2019–', 243, 16, NULL, 'English Wikipedia infobox, "Giovanni Di Lorenzo" article', '2026-10-09'),
(1032, NULL, 'Italy U20', 'international', '2013', 3, 0, NULL, 'English Wikipedia infobox, "Giovanni Di Lorenzo" article', '2026-10-09'),
(1032, NULL, 'Italy U21', 'international', '2013', 3, 0, NULL, 'English Wikipedia infobox, "Giovanni Di Lorenzo" article', '2026-10-09'),
(1032, 445, 'Italy', 'international', '2019–', 56, 5, NULL, 'English Wikipedia infobox, "Giovanni Di Lorenzo" article', '2026-10-09');

-- Amir Rrahmani (entity_id 1033) -- Wikipedia: "Amir Rrahmani"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1033, NULL, 'Drenica', 'club', '2011–2013', 40, 1, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09'),
(1033, NULL, 'Partizani', 'club', '2013–2015', 59, 3, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09'),
(1033, NULL, 'RNK Split', 'club', '2015–2016', 41, 1, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09'),
(1033, 300, 'Dinamo Zagreb', 'club', '2016–2019', 40, 4, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09'),
(1033, NULL, '→ Lokomotiva (loan)', 'club', '2016–2017', 28, 1, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09'),
(1033, 230, 'Hellas Verona', 'club', '2019–2020', 36, 0, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09'),
(1033, 236, 'Napoli', 'club', '2020–', 172, 13, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09'),
(1033, NULL, 'Albania U19', 'international', '2013', 1, 1, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09'),
(1033, NULL, 'Albania U21', 'international', '2013–2014', 9, 0, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09'),
(1033, 420, 'Albania', 'international', '2014–2015', 2, 1, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09'),
(1033, 447, 'Kosovo', 'international', '2014–2026', 67, 7, NULL, 'English Wikipedia infobox, "Amir Rrahmani" article', '2026-10-09');

-- Sam Beukema (entity_id 1034) -- Wikipedia: "Sam Beukema"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1034, 18977, 'Go Ahead Eagles', 'club', '2017–2021', 66, 9, NULL, 'English Wikipedia infobox, "Sam Beukema" article', '2026-10-09'),
(1034, 286, 'AZ', 'club', '2021–2023', 50, 5, NULL, 'English Wikipedia infobox, "Sam Beukema" article', '2026-10-09'),
(1034, 224, 'Bologna', 'club', '2023–2025', 65, 1, NULL, 'English Wikipedia infobox, "Sam Beukema" article', '2026-10-09'),
(1034, 236, 'Napoli', 'club', '2025–', 24, 2, NULL, 'English Wikipedia infobox, "Sam Beukema" article', '2026-10-09');

-- Stanislav Lobotka (entity_id 1035) -- Wikipedia: "Stanislav Lobotka"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1035, NULL, 'AS Trenčín', 'club', '2011–2015', 76, 3, NULL, 'English Wikipedia infobox, "Stanislav Lobotka" article', '2026-10-09'),
(1035, NULL, '→ Jong Ajax (loan)', 'club', '2013–2014', 30, 3, NULL, 'English Wikipedia infobox, "Stanislav Lobotka" article', '2026-10-09'),
(1035, 19536, 'Nordsjælland', 'club', '2015–2017', 61, 0, NULL, 'English Wikipedia infobox, "Stanislav Lobotka" article', '2026-10-09'),
(1035, 207, 'Celta Vigo', 'club', '2017–2020', 86, 0, NULL, 'English Wikipedia infobox, "Stanislav Lobotka" article', '2026-10-09'),
(1035, 236, 'Napoli', 'club', '2020–', 197, 4, NULL, 'English Wikipedia infobox, "Stanislav Lobotka" article', '2026-10-09'),
(1035, NULL, 'Slovakia U18', 'international', '2011–2012', 3, 1, NULL, 'English Wikipedia infobox, "Stanislav Lobotka" article', '2026-10-09'),
(1035, NULL, 'Slovakia U19', 'international', '2012–2013', 6, 1, NULL, 'English Wikipedia infobox, "Stanislav Lobotka" article', '2026-10-09'),
(1035, NULL, 'Slovakia U20', 'international', '2015', 1, 0, NULL, 'English Wikipedia infobox, "Stanislav Lobotka" article', '2026-10-09'),
(1035, NULL, 'Slovakia U21', 'international', '2013–2017', 27, 2, NULL, 'English Wikipedia infobox, "Stanislav Lobotka" article', '2026-10-09'),
(1035, 468, 'Slovakia', 'international', '2016–', 76, 4, NULL, 'English Wikipedia infobox, "Stanislav Lobotka" article', '2026-10-09');

-- Andre-Frank Zambo Anguissa (entity_id 1036) -- Wikipedia: "Frank Anguissa"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1036, 262, 'Marseille', 'club', '2015–2018', 79, 0, NULL, 'English Wikipedia infobox, "Frank Anguissa" article', '2026-10-09'),
(1036, 192, 'Fulham', 'club', '2018–2022', 61, 0, NULL, 'English Wikipedia infobox, "Frank Anguissa" article', '2026-10-09'),
(1036, 222, '→ Villarreal (loan)', 'club', '2019–2020', 36, 2, NULL, 'English Wikipedia infobox, "Frank Anguissa" article', '2026-10-09'),
(1036, 236, '→ Napoli (loan)', 'club', '2021–2022', 25, 0, NULL, 'English Wikipedia infobox, "Frank Anguissa" article', '2026-10-09'),
(1036, 236, 'Napoli', 'club', '2022–', 127, 13, NULL, 'English Wikipedia infobox, "Frank Anguissa" article', '2026-10-09'),
(1036, 482, 'Cameroon', 'international', '2017–2026', 67, 5, NULL, 'English Wikipedia infobox, "Frank Anguissa" article', '2026-10-09');

-- Matteo Politano (entity_id 1037) -- Wikipedia: "Matteo Politano"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1037, 239, 'Roma', 'club', '2012–2013', 0, 0, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, 19083, '→ Perugia (loan)', 'club', '2012–2013', 28, 8, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, NULL, 'Pescara', 'club', '2013–2015', 72, 11, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, 240, 'Sassuolo', 'club', '2015–2019', 96, 20, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, 231, '→ Inter Milan (loan)', 'club', '2018–2019', 36, 5, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, 231, 'Inter Milan', 'club', '2019–2021', 11, 0, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, 236, '→ Napoli (loan)', 'club', '2020–2021', 52, 11, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, 236, 'Napoli', 'club', '2021–', 173, 20, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, NULL, 'Italy U19', 'international', '2011–2012', 3, 0, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, NULL, 'Italy U20', 'international', '2012–2014', 7, 3, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, NULL, 'Italy U21', 'international', '2013', 2, 0, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09'),
(1037, 445, 'Italy', 'international', '2018–', 20, 4, NULL, 'English Wikipedia infobox, "Matteo Politano" article', '2026-10-09');

-- David Neres (entity_id 1038) -- Wikipedia: "David Neres"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1038, 37, 'São Paulo', 'club', '2016', 8, 3, NULL, 'English Wikipedia infobox, "David Neres" article', '2026-10-09'),
(1038, NULL, 'Jong Ajax', 'club', '2017', 5, 3, NULL, 'English Wikipedia infobox, "David Neres" article', '2026-10-09'),
(1038, 283, 'Ajax', 'club', '2017–2022', 121, 37, NULL, 'English Wikipedia infobox, "David Neres" article', '2026-10-09'),
(1038, 295, 'Shakhtar Donetsk', 'club', '2022', 0, 0, NULL, 'English Wikipedia infobox, "David Neres" article', '2026-10-09'),
(1038, 280, 'Benfica', 'club', '2022–2024', 55, 11, NULL, 'English Wikipedia infobox, "David Neres" article', '2026-10-09'),
(1038, 236, 'Napoli', 'club', '2024–', 46, 5, NULL, 'English Wikipedia infobox, "David Neres" article', '2026-10-09'),
(1038, NULL, 'Brazil U20', 'international', '2017', 9, 0, NULL, 'English Wikipedia infobox, "David Neres" article', '2026-10-09'),
(1038, NULL, 'Brazil U23', 'international', '2020', 2, 0, NULL, 'English Wikipedia infobox, "David Neres" article', '2026-10-09'),
(1038, 19157, 'Brazil', 'international', '2019–2023', 8, 1, NULL, 'English Wikipedia infobox, "David Neres" article', '2026-10-09');

-- Romelu Lukaku (entity_id 1039) -- Wikipedia: "Romelu Lukaku"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1039, 293, 'Anderlecht', 'club', '2009–2011', 73, 33, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 189, 'Chelsea', 'club', '2011–2014', 10, 0, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 317, '→ West Bromwich Albion (loan)', 'club', '2012–2013', 35, 17, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 191, '→ Everton (loan)', 'club', '2013–2014', 31, 15, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 191, 'Everton', 'club', '2013–2017', 110, 53, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 196, 'Manchester United', 'club', '2017–2019', 66, 28, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 231, 'Inter Milan', 'club', '2019–2021', 72, 47, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 189, 'Chelsea', 'club', '2021–2024', 26, 8, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 231, '→ Inter Milan (loan)', 'club', '2022–2023', 25, 10, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 239, '→ Roma (loan)', 'club', '2023–2024', 32, 13, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 236, 'Napoli', 'club', '2024–2026', 41, 15, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 290, 'Fenerbahçe', 'club', '2026–', 5, 0, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, NULL, 'Belgium U15', 'international', '2008', 4, 1, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, NULL, 'Belgium U18', 'international', '2011', 1, 0, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, NULL, 'Belgium U21', 'international', '2009', 5, 1, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09'),
(1039, 426, 'Belgium', 'international', '2010–', 135, 94, NULL, 'English Wikipedia infobox, "Romelu Lukaku" article', '2026-10-09');

-- Noa Lang (entity_id 1040) -- Wikipedia: "Noa Lang"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1040, NULL, 'Jong Ajax', 'club', '2017–2021', 47, 12, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, 283, 'Ajax', 'club', '2019–2021', 9, 4, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, 18971, '→ Twente (loan)', 'club', '2019–2020', 7, 1, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, 292, '→ Club Brugge (loan)', 'club', '2020–2021', 29, 16, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, 292, 'Club Brugge', 'club', '2021–2023', 70, 16, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, 284, 'PSV', 'club', '2023–2025', 40, 15, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, 236, 'Napoli', 'club', '2025–', 22, 1, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, 289, '→ Galatasaray (loan)', 'club', '2026', 13, 0, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, NULL, 'Netherlands U16', 'international', '2014–2015', 6, 0, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, NULL, 'Netherlands U18', 'international', '2017–2018', 2, 3, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, NULL, 'Netherlands U19', 'international', '2017–2019', 6, 3, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, NULL, 'Netherlands U20', 'international', '2018–2019', 8, 2, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, NULL, 'Netherlands U21', 'international', '2019–2021', 8, 1, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09'),
(1040, 456, 'Netherlands', 'international', '2021–', 19, 3, NULL, 'English Wikipedia infobox, "Noa Lang" article', '2026-10-09');

-- Paulo Dybala (entity_id 1041) -- Wikipedia: "Paulo Dybala"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1041, 29, 'Instituto', 'club', '2011–2012', 38, 17, NULL, 'English Wikipedia infobox, "Paulo Dybala" article', '2026-10-09'),
(1041, 19054, 'Palermo', 'club', '2012–2015', 89, 21, NULL, 'English Wikipedia infobox, "Paulo Dybala" article', '2026-10-09'),
(1041, 232, 'Juventus', 'club', '2015–2022', 210, 82, NULL, 'English Wikipedia infobox, "Paulo Dybala" article', '2026-10-09'),
(1041, 239, 'Roma', 'club', '2022–', 104, 33, NULL, 'English Wikipedia infobox, "Paulo Dybala" article', '2026-10-09'),
(1041, 19155, 'Argentina', 'international', '2015–', 40, 4, NULL, 'English Wikipedia infobox, "Paulo Dybala" article', '2026-10-09');

-- Gianluca Mancini (entity_id 1042) -- Wikipedia: "Gianluca Mancini"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1042, 19083, 'Perugia', 'club', '2015–2017', 25, 1, NULL, 'English Wikipedia infobox, "Gianluca Mancini" article', '2026-10-09'),
(1042, 223, 'Atalanta', 'club', '2017–2020', 41, 6, NULL, 'English Wikipedia infobox, "Gianluca Mancini" article', '2026-10-09'),
(1042, 239, '→ Roma (loan)', 'club', '2019–2020', 32, 1, NULL, 'English Wikipedia infobox, "Gianluca Mancini" article', '2026-10-09'),
(1042, 239, 'Roma', 'club', '2020–', 213, 15, NULL, 'English Wikipedia infobox, "Gianluca Mancini" article', '2026-10-09'),
(1042, NULL, 'Italy U21', 'international', '2017–2019', 13, 0, NULL, 'English Wikipedia infobox, "Gianluca Mancini" article', '2026-10-09'),
(1042, 445, 'Italy', 'international', '2019–', 22, 2, NULL, 'English Wikipedia infobox, "Gianluca Mancini" article', '2026-10-09');

-- Evan Ndicka (entity_id 1043) -- Wikipedia: "Evan Ndicka"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1043, 273, 'Auxerre', 'club', '2017–2018', 14, 0, NULL, 'English Wikipedia infobox, "Evan Ndicka" article', '2026-10-09'),
(1043, 248, 'Eintracht Frankfurt', 'club', '2018–2023', 134, 10, NULL, 'English Wikipedia infobox, "Evan Ndicka" article', '2026-10-09'),
(1043, 239, 'Roma', 'club', '2023–', 97, 3, NULL, 'English Wikipedia infobox, "Evan Ndicka" article', '2026-10-09'),
(1043, NULL, 'France U16', 'international', '2014–2015', 5, 0, NULL, 'English Wikipedia infobox, "Evan Ndicka" article', '2026-10-09'),
(1043, NULL, 'France U17', 'international', '2016', 1, 0, NULL, 'English Wikipedia infobox, "Evan Ndicka" article', '2026-10-09'),
(1043, NULL, 'France U18', 'international', '2017', 2, 0, NULL, 'English Wikipedia infobox, "Evan Ndicka" article', '2026-10-09'),
(1043, NULL, 'France U19', 'international', '2018', 1, 0, NULL, 'English Wikipedia infobox, "Evan Ndicka" article', '2026-10-09'),
(1043, NULL, 'France U20', 'international', '2017–2019', 10, 0, NULL, 'English Wikipedia infobox, "Evan Ndicka" article', '2026-10-09'),
(1043, NULL, 'France U21', 'international', '2019', 1, 0, NULL, 'English Wikipedia infobox, "Evan Ndicka" article', '2026-10-09'),
(1043, 500, 'Ivory Coast', 'international', '2023–', 28, 0, NULL, 'English Wikipedia infobox, "Evan Ndicka" article', '2026-10-09');

-- Bryan Cristante (entity_id 1044) -- Wikipedia: "Bryan Cristante"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1044, 235, 'AC Milan', 'club', '2011–2014', 3, 1, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, 280, 'Benfica', 'club', '2014–2018', 7, 0, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, 19054, '→ Palermo (loan)', 'club', '2016', 4, 0, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, NULL, '→ Pescara (loan)', 'club', '2016–2017', 16, 0, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, 223, '→ Atalanta (loan)', 'club', '2017–2018', 48, 12, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, 223, 'Atalanta', 'club', '2018–2019', 0, 0, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, 239, '→ Roma (loan)', 'club', '2018–2019', 35, 4, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, 239, 'Roma', 'club', '2019–', 237, 14, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, NULL, 'Italy U16', 'international', '2010', 2, 0, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, NULL, 'Italy U17', 'international', '2011–2012', 10, 0, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, NULL, 'Italy U18', 'international', '2012–2013', 6, 3, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, NULL, 'Italy U19', 'international', '2013–2014', 9, 4, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, NULL, 'Italy U20', 'international', '2014', 1, 0, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, NULL, 'Italy U21', 'international', '2016', 2, 0, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09'),
(1044, 445, 'Italy', 'international', '2017–', 48, 2, NULL, 'English Wikipedia infobox, "Bryan Cristante" article', '2026-10-09');

-- Manu Kone (entity_id 1045) -- Wikipedia: "Manu Koné"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1045, NULL, 'Toulouse B', 'club', '2018–2020', 19, 1, NULL, 'English Wikipedia infobox, "Manu Koné" article', '2026-10-09'),
(1045, 270, 'Toulouse', 'club', '2019–2021', 50, 3, NULL, 'English Wikipedia infobox, "Manu Koné" article', '2026-10-09'),
(1045, 254, 'Borussia Mönchengladbach', 'club', '2021–2025', 79, 4, NULL, 'English Wikipedia infobox, "Manu Koné" article', '2026-10-09'),
(1045, 239, '→ Roma (loan)', 'club', '2024–2025', 34, 2, NULL, 'English Wikipedia infobox, "Manu Koné" article', '2026-10-09'),
(1045, 239, 'Roma', 'club', '2025–', 34, 4, NULL, 'English Wikipedia infobox, "Manu Koné" article', '2026-10-09'),
(1045, NULL, 'France U18', 'international', '2018–2019', 5, 1, NULL, 'English Wikipedia infobox, "Manu Koné" article', '2026-10-09'),
(1045, NULL, 'France U19', 'international', '2019', 8, 0, NULL, 'English Wikipedia infobox, "Manu Koné" article', '2026-10-09'),
(1045, NULL, 'France U21', 'international', '2022–2023', 11, 0, NULL, 'English Wikipedia infobox, "Manu Koné" article', '2026-10-09'),
(1045, NULL, 'France Olympic', 'international', '2024', 9, 0, NULL, 'English Wikipedia infobox, "Manu Koné" article', '2026-10-09'),
(1045, 437, 'France', 'international', '2024–', 22, 0, NULL, 'English Wikipedia infobox, "Manu Koné" article', '2026-10-09');

-- Matias Soule (entity_id 1046) -- Wikipedia: "Matías Soulé"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1046, NULL, 'Juventus Next Gen ()', 'club', '2021–2023', 28, 3, NULL, 'English Wikipedia infobox, "Matías Soulé" article', '2026-10-09'),
(1046, 232, 'Juventus', 'club', '2021–2024', 15, 1, NULL, 'English Wikipedia infobox, "Matías Soulé" article', '2026-10-09'),
(1046, 19091, '→ Frosinone (loan)', 'club', '2023–2024', 36, 11, NULL, 'English Wikipedia infobox, "Matías Soulé" article', '2026-10-09'),
(1046, 239, 'Roma', 'club', '2024–', 65, 13, NULL, 'English Wikipedia infobox, "Matías Soulé" article', '2026-10-09'),
(1046, NULL, 'Argentina U16', 'international', '2019–2020', 3, 0, NULL, 'English Wikipedia infobox, "Matías Soulé" article', '2026-10-09'),
(1046, NULL, 'Argentina U20', 'international', '2022–2023', 7, 0, NULL, 'English Wikipedia infobox, "Matías Soulé" article', '2026-10-09'),
(1046, 19155, 'Argentina', 'international', '2026–', 1, 0, NULL, 'English Wikipedia infobox, "Matías Soulé" article', '2026-10-09');

-- Artem Dovbyk (entity_id 1047) -- Wikipedia: "Artem Dovbyk"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1047, NULL, 'Cherkaskyi Dnipro', 'club', '2014–2015', 20, 7, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, 19611, 'Dnipro', 'club', '2015–2018', 35, 18, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, NULL, '→ Zaria Bălți (loan)', 'club', '2016–2017', 3, 0, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, 19577, 'Midtjylland', 'club', '2018–2020', 18, 1, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, NULL, '→ Sønderjyske (loan)', 'club', '2019–2020', 18, 2, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, NULL, 'Dnipro-1', 'club', '2020–2023', 71, 44, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, 211, 'Girona', 'club', '2023–2024', 36, 24, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, 239, 'Roma', 'club', '2024–', 46, 15, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, 224, '→ Bologna (loan)', 'club', '2026–', 3, 1, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, NULL, 'Ukraine U18', 'international', '2015–2016', 2, 0, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, NULL, 'Ukraine U21', 'international', '2016–2018', 6, 1, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09'),
(1047, 474, 'Ukraine', 'international', '2021–', 41, 11, NULL, 'English Wikipedia infobox, "Artem Dovbyk" article', '2026-10-09');

-- Mile Svilar (entity_id 1048) -- Wikipedia: "Mile Svilar"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1048, 293, 'Anderlecht', 'club', '2016–2017', 0, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09'),
(1048, 280, 'Benfica', 'club', '2017–2022', 7, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09'),
(1048, NULL, 'Benfica B', 'club', '2018–2022', 56, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09'),
(1048, 239, 'Roma', 'club', '2022–', 99, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09'),
(1048, NULL, 'Belgium U15', 'international', '2014', 3, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09'),
(1048, NULL, 'Belgium U16', 'international', '2014–2015', 3, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09'),
(1048, NULL, 'Belgium U17', 'international', '2016', 7, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09'),
(1048, NULL, 'Belgium U18', 'international', '2016', 1, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09'),
(1048, NULL, 'Belgium U19', 'international', '2016–2017', 5, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09'),
(1048, NULL, 'Belgium U21', 'international', '2019–2020', 5, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09'),
(1048, 467, 'Serbia', 'international', '2021', 1, 0, NULL, 'English Wikipedia infobox, "Mile Svilar" article', '2026-10-09');

-- Lorenzo Pellegrini (entity_id 1049) -- Wikipedia: "Lorenzo Pellegrini"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1049, 239, 'Roma', 'club', '2014–2015', 1, 0, NULL, 'English Wikipedia infobox, "Lorenzo Pellegrini" article', '2026-10-09'),
(1049, 240, 'Sassuolo', 'club', '2015–2017', 47, 9, NULL, 'English Wikipedia infobox, "Lorenzo Pellegrini" article', '2026-10-09'),
(1049, 239, 'Roma', 'club', '2017–', 252, 40, NULL, 'English Wikipedia infobox, "Lorenzo Pellegrini" article', '2026-10-09'),
(1049, NULL, 'Italy U19', 'international', '2014–2015', 15, 1, NULL, 'English Wikipedia infobox, "Lorenzo Pellegrini" article', '2026-10-09'),
(1049, NULL, 'Italy U20', 'international', '2015', 2, 0, NULL, 'English Wikipedia infobox, "Lorenzo Pellegrini" article', '2026-10-09'),
(1049, NULL, 'Italy U21', 'international', '2016–2019', 14, 5, NULL, 'English Wikipedia infobox, "Lorenzo Pellegrini" article', '2026-10-09'),
(1049, 445, 'Italy', 'international', '2017–', 36, 6, NULL, 'English Wikipedia infobox, "Lorenzo Pellegrini" article', '2026-10-09');

-- Mattia Zaccagni (entity_id 1050) -- Wikipedia: "Mattia Zaccagni"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1050, NULL, 'Bellaria Igea', 'club', '2012–2014', 6, 0, NULL, 'English Wikipedia infobox, "Mattia Zaccagni" article', '2026-10-09'),
(1050, 230, '→ Hellas Verona (loan)', 'club', '2013–2014', 0, 0, NULL, 'English Wikipedia infobox, "Mattia Zaccagni" article', '2026-10-09'),
(1050, 230, 'Hellas Verona', 'club', '2014–2022', 137, 14, NULL, 'English Wikipedia infobox, "Mattia Zaccagni" article', '2026-10-09'),
(1050, 19089, '→ Venezia (loan)', 'club', '2014–2015', 33, 1, NULL, 'English Wikipedia infobox, "Mattia Zaccagni" article', '2026-10-09'),
(1050, NULL, '→ Cittadella (loan)', 'club', '2016', 12, 0, NULL, 'English Wikipedia infobox, "Mattia Zaccagni" article', '2026-10-09'),
(1050, 233, '→ Lazio (loan)', 'club', '2021–2022', 29, 4, NULL, 'English Wikipedia infobox, "Mattia Zaccagni" article', '2026-10-09'),
(1050, 233, 'Lazio', 'club', '2022–', 128, 28, NULL, 'English Wikipedia infobox, "Mattia Zaccagni" article', '2026-10-09'),
(1050, 445, 'Italy', 'international', '2022–', 13, 1, NULL, 'English Wikipedia infobox, "Mattia Zaccagni" article', '2026-10-09');
