-- Research output: per-team career stats, generated by scripts/research_player_stats.py.
-- Every row is a literal Wikipedia infobox club/international career-history row --
-- mechanical extraction, no LLM judgment, no estimates. The infobox's own separately-
-- maintained totalcaps/totalgoals 'Total' field is NOT used -- a player's career total
-- is a SUM() over these rows. Individual appearances/goals values are NULL wherever the
-- source itself doesn't state a number (never guessed/derived) -- a NULL just means that
-- field isn't usable in a total/category yet, not that the row is wrong.
-- verified_at = 2026-10-09 for all rows.
-- FOR HUMAN REVIEW BEFORE APPLYING. Not applied to any database by this script.

-- Franco Mastantuono (entity_id 951) -- Wikipedia: "Franco Mastantuono"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(951, 23, 'River Plate', 'club', '2024–2025', 45, 5, NULL, 'English Wikipedia infobox, "Franco Mastantuono" article', '2026-10-09'),
(951, 217, 'Real Madrid', 'club', '2025–', 23, 1, NULL, 'English Wikipedia infobox, "Franco Mastantuono" article', '2026-10-09'),
(951, 228, '→ Fiorentina (loan)', 'club', '2026–', 5, 3, NULL, 'English Wikipedia infobox, "Franco Mastantuono" article', '2026-10-09'),
(951, NULL, 'Argentina U17', 'international', '2022–2023', 9, 1, NULL, 'English Wikipedia infobox, "Franco Mastantuono" article', '2026-10-09'),
(951, NULL, 'Argentina U20', 'international', '2024–2025', 12, 2, NULL, 'English Wikipedia infobox, "Franco Mastantuono" article', '2026-10-09'),
(951, 19155, 'Argentina', 'international', '2025–', 6, 1, NULL, 'English Wikipedia infobox, "Franco Mastantuono" article', '2026-10-09');

-- Andriy Lunin (entity_id 952) -- Wikipedia: "Andriy Lunin"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(952, NULL, 'Dnipro', 'club', '2016–2017', 22, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, NULL, 'Zorya Luhansk', 'club', '2017–2018', 29, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, 217, 'Real Madrid', 'club', '2018–', 43, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, 412, '→ Leganés (loan)', 'club', '2018–2019', 5, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, 404, '→ Valladolid (loan)', 'club', '2019–2020', 0, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, NULL, '→ Oviedo (loan)', 'club', '2020', 20, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, NULL, 'Ukraine U16', 'international', '2014–2015', 5, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, NULL, 'Ukraine U17', 'international', '2015–2016', 9, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, NULL, 'Ukraine U18', 'international', '2016', 1, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, NULL, 'Ukraine U19', 'international', '2017', 3, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, NULL, 'Ukraine U20', 'international', '2019', 6, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, NULL, 'Ukraine U21', 'international', '2017–2018', 5, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09'),
(952, 474, 'Ukraine', 'international', '2018–', 16, 0, NULL, 'English Wikipedia infobox, "Andriy Lunin" article', '2026-10-09');

-- Joan Garcia (entity_id 953) -- Wikipedia: "Joan Garcia"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(953, NULL, 'Espanyol B', 'club', '2019–2021', 17, 0, NULL, 'English Wikipedia infobox, "Joan Garcia" article', '2026-10-09'),
(953, 209, 'Espanyol', 'club', '2021–2025', 55, 0, NULL, 'English Wikipedia infobox, "Joan Garcia" article', '2026-10-09'),
(953, 206, 'Barcelona', 'club', '2025–', 36, 0, NULL, 'English Wikipedia infobox, "Joan Garcia" article', '2026-10-09'),
(953, NULL, 'Spain U17', 'international', '2018', 2, 0, NULL, 'English Wikipedia infobox, "Joan Garcia" article', '2026-10-09'),
(953, NULL, 'Spain U18', 'international', '2018–2019', 4, 0, NULL, 'English Wikipedia infobox, "Joan Garcia" article', '2026-10-09'),
(953, NULL, 'Spain U19', 'international', '2019', 2, 0, NULL, 'English Wikipedia infobox, "Joan Garcia" article', '2026-10-09'),
(953, NULL, 'Spain U21', 'international', '2021–2022', 2, 0, NULL, 'English Wikipedia infobox, "Joan Garcia" article', '2026-10-09'),
(953, NULL, 'Catalonia', 'international', '2025–', 1, 0, NULL, 'English Wikipedia infobox, "Joan Garcia" article', '2026-10-09'),
(953, 470, 'Spain', 'international', '2026–', 2, 0, NULL, 'English Wikipedia infobox, "Joan Garcia" article', '2026-10-09');

-- Wojciech Szczesny (entity_id 954) -- Wikipedia: "Wojciech Szczęsny"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(954, 183, 'Arsenal', 'club', '2009–2017', 132, 0, NULL, 'English Wikipedia infobox, "Wojciech Szczęsny" article', '2026-10-09'),
(954, 186, '→ Brentford (loan)', 'club', '2009–2010', 28, 0, NULL, 'English Wikipedia infobox, "Wojciech Szczęsny" article', '2026-10-09'),
(954, 239, '→ Roma (loan)', 'club', '2015–2017', 72, 0, NULL, 'English Wikipedia infobox, "Wojciech Szczęsny" article', '2026-10-09'),
(954, 232, 'Juventus', 'club', '2017–2024', 200, 0, NULL, 'English Wikipedia infobox, "Wojciech Szczęsny" article', '2026-10-09'),
(954, 206, 'Barcelona', 'club', '2024–', 24, 0, NULL, 'English Wikipedia infobox, "Wojciech Szczęsny" article', '2026-10-09'),
(954, NULL, 'Poland U20', 'international', '2007–2010', 4, 0, NULL, 'English Wikipedia infobox, "Wojciech Szczęsny" article', '2026-10-09'),
(954, NULL, 'Poland U21', 'international', '2009–2012', 7, 0, NULL, 'English Wikipedia infobox, "Wojciech Szczęsny" article', '2026-10-09'),
(954, 460, 'Poland', 'international', '2009–2024', 84, 0, NULL, 'English Wikipedia infobox, "Wojciech Szczęsny" article', '2026-10-09');

-- Jules Kounde (entity_id 955) -- Wikipedia: "Jules Koundé"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(955, NULL, 'Bordeaux II', 'club', '2016–2017', 29, 1, NULL, 'English Wikipedia infobox, "Jules Koundé" article', '2026-10-09'),
(955, 19062, 'Bordeaux', 'club', '2017–2019', 55, 2, NULL, 'English Wikipedia infobox, "Jules Koundé" article', '2026-10-09'),
(955, 220, 'Sevilla', 'club', '2019–2022', 95, 5, NULL, 'English Wikipedia infobox, "Jules Koundé" article', '2026-10-09'),
(955, 206, 'Barcelona', 'club', '2022–', 130, 5, NULL, 'English Wikipedia infobox, "Jules Koundé" article', '2026-10-09'),
(955, NULL, 'France U20', 'international', '2018', 1, 0, NULL, 'English Wikipedia infobox, "Jules Koundé" article', '2026-10-09'),
(955, NULL, 'France U21', 'international', '2020–2021', 8, 1, NULL, 'English Wikipedia infobox, "Jules Koundé" article', '2026-10-09'),
(955, 437, 'France', 'international', '2021–', 58, 0, NULL, 'English Wikipedia infobox, "Jules Koundé" article', '2026-10-09');

-- Ronald Araujo (entity_id 956) -- Wikipedia: "Ronald Araújo"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(956, NULL, 'Rentistas', 'club', '2016–2017', 17, 7, NULL, 'English Wikipedia infobox, "Ronald Araújo" article', '2026-10-09'),
(956, 76, 'Boston River', 'club', '2017–2018', 27, 0, NULL, 'English Wikipedia infobox, "Ronald Araújo" article', '2026-10-09'),
(956, NULL, 'Barcelona B', 'club', '2018–2020', 42, 6, NULL, 'English Wikipedia infobox, "Ronald Araújo" article', '2026-10-09'),
(956, 206, 'Barcelona', 'club', '2019–', 143, 11, NULL, 'English Wikipedia infobox, "Ronald Araújo" article', '2026-10-09'),
(956, 194, '→ Liverpool (loan)', 'club', '2026–', 5, 0, NULL, 'English Wikipedia infobox, "Ronald Araújo" article', '2026-10-09'),
(956, NULL, 'Uruguay U18', 'international', '2017–2018', 6, 1, NULL, 'English Wikipedia infobox, "Ronald Araújo" article', '2026-10-09'),
(956, NULL, 'Uruguay U20', 'international', '2018–2019', 12, 2, NULL, 'English Wikipedia infobox, "Ronald Araújo" article', '2026-10-09'),
(956, 19156, 'Uruguay', 'international', '2020–', 29, 1, NULL, 'English Wikipedia infobox, "Ronald Araújo" article', '2026-10-09');

-- Pau Cubarsi (entity_id 957) -- Wikipedia: "Pau Cubarsí"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(957, NULL, 'Barcelona B', 'club', '2023–2024', 9, 0, NULL, 'English Wikipedia infobox, "Pau Cubarsí" article', '2026-10-09'),
(957, 206, 'Barcelona', 'club', '2023–', 90, 1, NULL, 'English Wikipedia infobox, "Pau Cubarsí" article', '2026-10-09'),
(957, NULL, 'Spain U15', 'international', '2021–2022', 6, 1, NULL, 'English Wikipedia infobox, "Pau Cubarsí" article', '2026-10-09'),
(957, NULL, 'Spain U16', 'international', '2022', 4, 1, NULL, 'English Wikipedia infobox, "Pau Cubarsí" article', '2026-10-09'),
(957, NULL, 'Spain U17', 'international', '2022–2023', 18, 0, NULL, 'English Wikipedia infobox, "Pau Cubarsí" article', '2026-10-09'),
(957, NULL, 'Spain U21', 'international', '2024', 2, 0, NULL, 'English Wikipedia infobox, "Pau Cubarsí" article', '2026-10-09'),
(957, NULL, 'Spain U23', 'international', '2024', 5, 0, NULL, 'English Wikipedia infobox, "Pau Cubarsí" article', '2026-10-09'),
(957, 470, 'Spain', 'international', '2024–', 23, 0, NULL, 'English Wikipedia infobox, "Pau Cubarsí" article', '2026-10-09');

-- Alejandro Balde (entity_id 958) -- Wikipedia: "Alejandro Balde"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(958, NULL, 'Barcelona B', 'club', '2020–2022', 29, 0, NULL, 'English Wikipedia infobox, "Alejandro Balde" article', '2026-10-09'),
(958, 206, 'Barcelona', 'club', '2021–', 117, 1, NULL, 'English Wikipedia infobox, "Alejandro Balde" article', '2026-10-09'),
(958, NULL, 'Spain U16', 'international', '2019', 6, 0, NULL, 'English Wikipedia infobox, "Alejandro Balde" article', '2026-10-09'),
(958, NULL, 'Spain U17', 'international', '2019–2020', 9, 0, NULL, 'English Wikipedia infobox, "Alejandro Balde" article', '2026-10-09'),
(958, NULL, 'Spain U18', 'international', '2019', 3, 0, NULL, 'English Wikipedia infobox, "Alejandro Balde" article', '2026-10-09'),
(958, NULL, 'Spain U19', 'international', '2021', 5, 0, NULL, 'English Wikipedia infobox, "Alejandro Balde" article', '2026-10-09'),
(958, NULL, 'Spain U21', 'international', '2022', 2, 0, NULL, 'English Wikipedia infobox, "Alejandro Balde" article', '2026-10-09'),
(958, 470, 'Spain', 'international', '2022–2023', 7, 0, NULL, 'English Wikipedia infobox, "Alejandro Balde" article', '2026-10-09');

-- Eric Garcia (entity_id 959) -- Wikipedia: "Eric Garcia (footballer, born 2001)"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(959, 195, 'Manchester City', 'club', '2018–2021', 19, 0, NULL, 'English Wikipedia infobox, "Eric Garcia (footballer, born 2001)" article', '2026-10-09'),
(959, 206, 'Barcelona', 'club', '2021–', 121, 4, NULL, 'English Wikipedia infobox, "Eric Garcia (footballer, born 2001)" article', '2026-10-09'),
(959, 211, '→ Girona (loan)', 'club', '2023–2024', 32, 5, NULL, 'English Wikipedia infobox, "Eric Garcia (footballer, born 2001)" article', '2026-10-09'),
(959, NULL, 'Spain U16', 'international', '2017', 9, 0, NULL, 'English Wikipedia infobox, "Eric Garcia (footballer, born 2001)" article', '2026-10-09'),
(959, NULL, 'Spain U17', 'international', '2017–2018', 9, 0, NULL, 'English Wikipedia infobox, "Eric Garcia (footballer, born 2001)" article', '2026-10-09'),
(959, NULL, 'Spain U19', 'international', '2019', 9, 0, NULL, 'English Wikipedia infobox, "Eric Garcia (footballer, born 2001)" article', '2026-10-09'),
(959, NULL, 'Spain U21', 'international', '2019', 5, 0, NULL, 'English Wikipedia infobox, "Eric Garcia (footballer, born 2001)" article', '2026-10-09'),
(959, NULL, 'Spain U23', 'international', '2021–2024', 12, 0, NULL, 'English Wikipedia infobox, "Eric Garcia (footballer, born 2001)" article', '2026-10-09'),
(959, 470, 'Spain', 'international', '2020–', 22, 0, NULL, 'English Wikipedia infobox, "Eric Garcia (footballer, born 2001)" article', '2026-10-09'),
(959, NULL, 'Catalonia', 'international', '2024–', 2, 0, NULL, 'English Wikipedia infobox, "Eric Garcia (footballer, born 2001)" article', '2026-10-09');

-- Frenkie de Jong (entity_id 960) -- Wikipedia: "Frenkie de Jong"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(960, 18974, 'Willem II', 'club', '2015', 1, 0, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09'),
(960, NULL, 'Jong Ajax', 'club', '2015–2017', 46, 8, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09'),
(960, 18974, '→ Willem II (loan)', 'club', '2015', 1, 0, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09'),
(960, 283, 'Ajax', 'club', '2016–2019', 57, 4, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09'),
(960, 206, 'Barcelona', 'club', '2019–', 202, 15, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09'),
(960, NULL, 'Netherlands U15', 'international', '2012', 1, 0, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09'),
(960, NULL, 'Netherlands U18', 'international', '2014–2015', 5, 1, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09'),
(960, NULL, 'Netherlands U19', 'international', '2015–2016', 8, 0, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09'),
(960, NULL, 'Netherlands U20', 'international', '2016', 2, 0, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09'),
(960, NULL, 'Netherlands U21', 'international', '2017', 6, 1, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09'),
(960, 456, 'Netherlands', 'international', '2018–', 70, 2, NULL, 'English Wikipedia infobox, "Frenkie de Jong" article', '2026-10-09');

-- Dani Olmo (entity_id 961) -- Wikipedia: "Dani Olmo"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(961, NULL, 'Dinamo Zagreb II', 'club', '2015–2017', 25, 3, NULL, 'English Wikipedia infobox, "Dani Olmo" article', '2026-10-09'),
(961, 300, 'Dinamo Zagreb', 'club', '2015–2020', 80, 20, NULL, 'English Wikipedia infobox, "Dani Olmo" article', '2026-10-09'),
(961, 245, 'RB Leipzig', 'club', '2020–2024', 107, 17, NULL, 'English Wikipedia infobox, "Dani Olmo" article', '2026-10-09'),
(961, 206, 'Barcelona', 'club', '2024–', 65, 17, NULL, 'English Wikipedia infobox, "Dani Olmo" article', '2026-10-09'),
(961, NULL, 'Spain U16', 'international', '2014', 3, 0, NULL, 'English Wikipedia infobox, "Dani Olmo" article', '2026-10-09'),
(961, NULL, 'Spain U17', 'international', '2015', 9, 1, NULL, 'English Wikipedia infobox, "Dani Olmo" article', '2026-10-09'),
(961, NULL, 'Spain U18', 'international', '2016', 3, 1, NULL, 'English Wikipedia infobox, "Dani Olmo" article', '2026-10-09'),
(961, NULL, 'Spain U21', 'international', '2018–2019', 14, 6, NULL, 'English Wikipedia infobox, "Dani Olmo" article', '2026-10-09'),
(961, NULL, 'Spain U23', 'international', '2021', 7, 1, NULL, 'English Wikipedia infobox, "Dani Olmo" article', '2026-10-09'),
(961, 470, 'Spain', 'international', '2019–', 61, 12, NULL, 'English Wikipedia infobox, "Dani Olmo" article', '2026-10-09');

-- Fermin Lopez (entity_id 962) -- Wikipedia: "Fermín López"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(962, NULL, 'Barcelona B', 'club', '2022–2023', 1, 0, NULL, 'English Wikipedia infobox, "Fermín López" article', '2026-10-09'),
(962, NULL, '→ Linares (loan)', 'club', '2022–2023', 37, 12, NULL, 'English Wikipedia infobox, "Fermín López" article', '2026-10-09'),
(962, 206, 'Barcelona', 'club', '2023–', 95, 24, NULL, 'English Wikipedia infobox, "Fermín López" article', '2026-10-09'),
(962, NULL, 'Spain U21', 'international', '2023–2025', 7, 1, NULL, 'English Wikipedia infobox, "Fermín López" article', '2026-10-09'),
(962, NULL, 'Spain U23', 'international', '2024', 6, 6, NULL, 'English Wikipedia infobox, "Fermín López" article', '2026-10-09'),
(962, 470, 'Spain', 'international', '2024–', 10, 0, NULL, 'English Wikipedia infobox, "Fermín López" article', '2026-10-09');

-- Ferran Torres (entity_id 963) -- Wikipedia: "Ferran Torres"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(963, NULL, 'Valencia Mestalla', 'club', '2016–2017', 12, 1, NULL, 'English Wikipedia infobox, "Ferran Torres" article', '2026-10-09'),
(963, 221, 'Valencia', 'club', '2017–2020', 71, 6, NULL, 'English Wikipedia infobox, "Ferran Torres" article', '2026-10-09'),
(963, 195, 'Manchester City', 'club', '2020–2022', 28, 9, NULL, 'English Wikipedia infobox, "Ferran Torres" article', '2026-10-09'),
(963, 206, 'Barcelona', 'club', '2022–2026', 140, 41, NULL, 'English Wikipedia infobox, "Ferran Torres" article', '2026-10-09'),
(963, 261, 'Paris Saint-Germain', 'club', '2026–', 5, 4, NULL, 'English Wikipedia infobox, "Ferran Torres" article', '2026-10-09'),
(963, NULL, 'Spain U17', 'international', '2016–2017', 24, 2, NULL, 'English Wikipedia infobox, "Ferran Torres" article', '2026-10-09'),
(963, NULL, 'Spain U19', 'international', '2018–2019', 17, 10, NULL, 'English Wikipedia infobox, "Ferran Torres" article', '2026-10-09'),
(963, NULL, 'Spain U21', 'international', '2019–2021', 6, 0, NULL, 'English Wikipedia infobox, "Ferran Torres" article', '2026-10-09'),
(963, 470, 'Spain', 'international', '2020–', 66, 25, NULL, 'English Wikipedia infobox, "Ferran Torres" article', '2026-10-09');

-- Alexander Sorloth (entity_id 964) -- Wikipedia: "Alexander Sørloth"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(964, NULL, 'Rosenborg 2', 'club', '2012–2015', 46, 18, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, NULL, 'Rosenborg', 'club', '2013–2015', 6, 0, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, NULL, '→ Bodø/Glimt (loan)', 'club', '2015', 26, 13, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, 18978, 'Groningen', 'club', '2016–2017', 38, 5, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, 19577, 'Midtjylland', 'club', '2017–2018', 19, 10, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, 190, 'Crystal Palace', 'club', '2018–2020', 16, 0, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, 18997, '→ Gent (loan)', 'club', '2019', 19, 4, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, 19003, '→ Trabzonspor (loan)', 'club', '2019–2020', 34, 24, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, 245, 'RB Leipzig', 'club', '2020–2023', 30, 5, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, 219, '→ Real Sociedad (loan)', 'club', '2021–2023', 67, 16, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, 222, 'Villarreal', 'club', '2023–2024', 34, 23, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, 205, 'Atlético Madrid', 'club', '2024–', 70, 33, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, NULL, 'Norway U16', 'international', '2011–2012', 3, 0, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, NULL, 'Norway U17', 'international', '2012–2013', 3, 0, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, NULL, 'Norway U18', 'international', '2013–2014', 11, 5, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, NULL, 'Norway U19', 'international', '2014–2015', 3, 1, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, NULL, 'Norway U21', 'international', '2015–2016', 10, 1, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09'),
(964, 459, 'Norway', 'international', '2016–', 77, 26, NULL, 'English Wikipedia infobox, "Alexander Sørloth" article', '2026-10-09');

-- Marcos Llorente (entity_id 965) -- Wikipedia: "Marcos Llorente"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(965, NULL, 'Real Madrid B', 'club', '2014–2016', 58, 3, NULL, 'English Wikipedia infobox, "Marcos Llorente" article', '2026-10-09'),
(965, 217, 'Real Madrid', 'club', '2015–2019', 22, 0, NULL, 'English Wikipedia infobox, "Marcos Llorente" article', '2026-10-09'),
(965, 203, '→ Alavés (loan)', 'club', '2016–2017', 32, 0, NULL, 'English Wikipedia infobox, "Marcos Llorente" article', '2026-10-09'),
(965, 205, 'Atlético Madrid', 'club', '2019–', 223, 24, NULL, 'English Wikipedia infobox, "Marcos Llorente" article', '2026-10-09'),
(965, NULL, 'Spain U19', 'international', '2014', 4, 0, NULL, 'English Wikipedia infobox, "Marcos Llorente" article', '2026-10-09'),
(965, NULL, 'Spain U21', 'international', '2016–2017', 9, 0, NULL, 'English Wikipedia infobox, "Marcos Llorente" article', '2026-10-09'),
(965, 470, 'Spain', 'international', '2020–2026', 27, 0, NULL, 'English Wikipedia infobox, "Marcos Llorente" article', '2026-10-09');

-- Rodrigo De Paul (entity_id 966) -- Wikipedia: "Rodrigo De Paul"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(966, 27, 'Racing Club', 'club', '2012–2014', 54, 6, NULL, 'English Wikipedia infobox, "Rodrigo De Paul" article', '2026-10-09'),
(966, 221, 'Valencia', 'club', '2014–2016', 34, 1, NULL, 'English Wikipedia infobox, "Rodrigo De Paul" article', '2026-10-09'),
(966, 27, '→ Racing Club (loan)', 'club', '2016', 11, 0, NULL, 'English Wikipedia infobox, "Rodrigo De Paul" article', '2026-10-09'),
(966, 242, 'Udinese', 'club', '2016–2021', 177, 33, NULL, 'English Wikipedia infobox, "Rodrigo De Paul" article', '2026-10-09'),
(966, 205, 'Atlético Madrid', 'club', '2021–2025', 134, 11, NULL, 'English Wikipedia infobox, "Rodrigo De Paul" article', '2026-10-09'),
(966, 331, '→ Inter Miami (loan)', 'club', '2025', 11, 0, NULL, 'English Wikipedia infobox, "Rodrigo De Paul" article', '2026-10-09'),
(966, 331, 'Inter Miami', 'club', '2026–', 22, 4, NULL, 'English Wikipedia infobox, "Rodrigo De Paul" article', '2026-10-09'),
(966, 19155, 'Argentina', 'international', '2018–', 95, 2, NULL, 'English Wikipedia infobox, "Rodrigo De Paul" article', '2026-10-09');

-- Koke (entity_id 967) -- Wikipedia: "Koke (footballer, born 1992)"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(967, NULL, 'Atlético Madrid B', 'club', '2008–2010', 66, 7, NULL, 'English Wikipedia infobox, "Koke (footballer, born 1992)" article', '2026-10-09'),
(967, 205, 'Atlético Madrid', 'club', '2009–', 526, 40, NULL, 'English Wikipedia infobox, "Koke (footballer, born 1992)" article', '2026-10-09'),
(967, NULL, 'Spain U16', 'international', '2008', 3, 0, NULL, 'English Wikipedia infobox, "Koke (footballer, born 1992)" article', '2026-10-09'),
(967, NULL, 'Spain U17', 'international', '2008–2009', 19, 0, NULL, 'English Wikipedia infobox, "Koke (footballer, born 1992)" article', '2026-10-09'),
(967, NULL, 'Spain U19', 'international', '2010–2011', 9, 0, NULL, 'English Wikipedia infobox, "Koke (footballer, born 1992)" article', '2026-10-09'),
(967, NULL, 'Spain U20', 'international', '2011', 5, 1, NULL, 'English Wikipedia infobox, "Koke (footballer, born 1992)" article', '2026-10-09'),
(967, NULL, 'Spain U21', 'international', '2011–2013', 12, 1, NULL, 'English Wikipedia infobox, "Koke (footballer, born 1992)" article', '2026-10-09'),
(967, NULL, 'Spain U23', 'international', '2012', 6, 1, NULL, 'English Wikipedia infobox, "Koke (footballer, born 1992)" article', '2026-10-09'),
(967, 470, 'Spain', 'international', '2013–2022', 70, 0, NULL, 'English Wikipedia infobox, "Koke (footballer, born 1992)" article', '2026-10-09');

-- Pablo Barrios (entity_id 968) -- Wikipedia: "Pablo Barrios (footballer)"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(968, NULL, 'Atlético Madrid B', 'club', '2022', 12, 1, NULL, 'English Wikipedia infobox, "Pablo Barrios (footballer)" article', '2026-10-09'),
(968, 205, 'Atlético Madrid', 'club', '2022–', 103, 2, NULL, 'English Wikipedia infobox, "Pablo Barrios (footballer)" article', '2026-10-09'),
(968, NULL, 'Spain U19', 'international', '2022', 3, 0, NULL, 'English Wikipedia infobox, "Pablo Barrios (footballer)" article', '2026-10-09'),
(968, NULL, 'Spain U21', 'international', '2023–2024', 8, 0, NULL, 'English Wikipedia infobox, "Pablo Barrios (footballer)" article', '2026-10-09'),
(968, NULL, 'Spain U23', 'international', '2024', 6, 0, NULL, 'English Wikipedia infobox, "Pablo Barrios (footballer)" article', '2026-10-09'),
(968, 470, 'Spain', 'international', '2024–', 4, 0, NULL, 'English Wikipedia infobox, "Pablo Barrios (footballer)" article', '2026-10-09');

-- Conor Gallagher (entity_id 969) -- Wikipedia: "Conor Gallagher"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(969, 189, 'Chelsea', 'club', '2019–2024', 72, 8, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, 366, '→ Charlton Athletic (loan)', 'club', '2019–2020', 26, 6, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, 321, '→ Swansea City (loan)', 'club', '2020', 19, 0, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, 317, '→ West Bromwich Albion (loan)', 'club', '2020–2021', 30, 2, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, 190, '→ Crystal Palace (loan)', 'club', '2021–2022', 34, 8, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, 205, 'Atlético Madrid', 'club', '2024–2026', 51, 5, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, 200, 'Tottenham Hotspur', 'club', '2026–', 19, 2, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, NULL, 'England U17', 'international', '2017–2018', 4, 0, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, NULL, 'England U18', 'international', '2018', 6, 0, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, NULL, 'England U19', 'international', '2018–2019', 9, 2, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, NULL, 'England U20', 'international', '2019', 4, 0, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, NULL, 'England U21', 'international', '2019–2022', 15, 3, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09'),
(969, 433, 'England', 'international', '2021–', 22, 1, NULL, 'English Wikipedia infobox, "Conor Gallagher" article', '2026-10-09');

-- Robin Le Normand (entity_id 970) -- Wikipedia: "Robin Le Normand"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(970, NULL, 'Brest II', 'club', '2013–2016', 39, 2, NULL, 'English Wikipedia infobox, "Robin Le Normand" article', '2026-10-09'),
(970, 272, 'Brest', 'club', '2016', 1, 0, NULL, 'English Wikipedia infobox, "Robin Le Normand" article', '2026-10-09'),
(970, NULL, 'Real Sociedad B', 'club', '2016–2019', 82, 4, NULL, 'English Wikipedia infobox, "Robin Le Normand" article', '2026-10-09'),
(970, 219, 'Real Sociedad', 'club', '2018–2024', 167, 4, NULL, 'English Wikipedia infobox, "Robin Le Normand" article', '2026-10-09'),
(970, 205, 'Atlético Madrid', 'club', '2024–', 59, 3, NULL, 'English Wikipedia infobox, "Robin Le Normand" article', '2026-10-09'),
(970, 470, 'Spain', 'international', '2023–', 28, 1, NULL, 'English Wikipedia infobox, "Robin Le Normand" article', '2026-10-09');

-- Jose Maria Gimenez (entity_id 971) -- Wikipedia: "José María Giménez"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(971, 68, 'Danubio', 'club', '2012–2013', 16, 0, NULL, 'English Wikipedia infobox, "José María Giménez" article', '2026-10-09'),
(971, 205, 'Atlético Madrid', 'club', '2013–', 270, 6, NULL, 'English Wikipedia infobox, "José María Giménez" article', '2026-10-09'),
(971, NULL, '→ Deportivo A Coruña (loan)', 'club', '2026–', 4, 0, NULL, 'English Wikipedia infobox, "José María Giménez" article', '2026-10-09'),
(971, NULL, 'Uruguay U20', 'international', '2013', 13, 0, NULL, 'English Wikipedia infobox, "José María Giménez" article', '2026-10-09'),
(971, 19156, 'Uruguay', 'international', '2013–', 101, 8, NULL, 'English Wikipedia infobox, "José María Giménez" article', '2026-10-09');

-- Clement Lenglet (entity_id 972) -- Wikipedia: "Clément Lenglet"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(972, NULL, 'Nancy B', 'club', '2012–2014', 33, 6, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, 19121, 'Nancy', 'club', '2013–2017', 77, 2, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, 220, 'Sevilla', 'club', '2017–2018', 52, 3, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, 206, 'Barcelona', 'club', '2018–2025', 105, 4, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, 200, '→ Tottenham Hotspur (loan)', 'club', '2022–2023', 26, 0, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, 184, '→ Aston Villa (loan)', 'club', '2023–2024', 14, 0, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, 205, '→ Atlético Madrid (loan)', 'club', '2024–2025', 23, 2, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, 205, 'Atlético Madrid', 'club', '2025–', 19, 0, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, 280, '→ Benfica (loan)', 'club', '2026–', 7, 1, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, NULL, 'France U16', 'international', '2010–2011', 6, 0, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, NULL, 'France U17', 'international', '2011–2012', 14, 0, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, NULL, 'France U18', 'international', '2012', 3, 0, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, NULL, 'France U19', 'international', '2013', 6, 0, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, NULL, 'France U20', 'international', '2014', 2, 0, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, NULL, 'France U21', 'international', '2015–2016', 10, 0, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09'),
(972, 437, 'France', 'international', '2019–', 16, 1, NULL, 'English Wikipedia infobox, "Clément Lenglet" article', '2026-10-09');

-- David Hancko (entity_id 973) -- Wikipedia: "Dávid Hancko"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(973, NULL, 'Žilina B', 'club', '2014–2018', 45, 11, NULL, 'English Wikipedia infobox, "Dávid Hancko" article', '2026-10-09'),
(973, NULL, 'Žilina', 'club', '2016–2018', 35, 3, NULL, 'English Wikipedia infobox, "Dávid Hancko" article', '2026-10-09'),
(973, 228, 'Fiorentina', 'club', '2018–2021', 5, 0, NULL, 'English Wikipedia infobox, "Dávid Hancko" article', '2026-10-09'),
(973, 302, '→ Sparta Prague (loan)', 'club', '2019–2021', 43, 7, NULL, 'English Wikipedia infobox, "Dávid Hancko" article', '2026-10-09'),
(973, 302, 'Sparta Prague', 'club', '2021–2022', 33, 7, NULL, 'English Wikipedia infobox, "Dávid Hancko" article', '2026-10-09'),
(973, 285, 'Feyenoord', 'club', '2022–2025', 97, 10, NULL, 'English Wikipedia infobox, "Dávid Hancko" article', '2026-10-09'),
(973, 205, 'Atlético Madrid', 'club', '2025–', 37, 0, NULL, 'English Wikipedia infobox, "Dávid Hancko" article', '2026-10-09'),
(973, NULL, 'Slovakia U19', 'international', '2015–2017', 8, 1, NULL, 'English Wikipedia infobox, "Dávid Hancko" article', '2026-10-09'),
(973, NULL, 'Slovakia U21', 'international', '2017–2018', 9, 0, NULL, 'English Wikipedia infobox, "Dávid Hancko" article', '2026-10-09'),
(973, 468, 'Slovakia', 'international', '2018–', 63, 9, NULL, 'English Wikipedia infobox, "Dávid Hancko" article', '2026-10-09');

-- Thiago Almada (entity_id 974) -- Wikipedia: "Thiago Almada"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(974, 6, 'Vélez Sarsfield', 'club', '2018–2022', 45, 10, NULL, 'English Wikipedia infobox, "Thiago Almada" article', '2026-10-09'),
(974, 19030, 'Atlanta United', 'club', '2022–2024', 77, 23, NULL, 'English Wikipedia infobox, "Thiago Almada" article', '2026-10-09'),
(974, 41, 'Botafogo', 'club', '2024–2025', 17, 1, NULL, 'English Wikipedia infobox, "Thiago Almada" article', '2026-10-09'),
(974, 263, '→ Lyon (loan)', 'club', '2025', 16, 1, NULL, 'English Wikipedia infobox, "Thiago Almada" article', '2026-10-09'),
(974, 205, 'Atlético Madrid', 'club', '2025–2026', 27, 3, NULL, 'English Wikipedia infobox, "Thiago Almada" article', '2026-10-09'),
(974, 23, 'River Plate', 'club', '2026–', 6, 2, NULL, 'English Wikipedia infobox, "Thiago Almada" article', '2026-10-09'),
(974, NULL, 'Argentina U20', 'international', '2019', 6, 1, NULL, 'English Wikipedia infobox, "Thiago Almada" article', '2026-10-09'),
(974, NULL, 'Argentina Olympic', 'international', '2021–2024', 13, 7, NULL, 'English Wikipedia infobox, "Thiago Almada" article', '2026-10-09'),
(974, 19155, 'Argentina', 'international', '2022–', 21, 5, NULL, 'English Wikipedia infobox, "Thiago Almada" article', '2026-10-09');

-- Alex Baena (entity_id 975) -- Wikipedia: "Álex Baena"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(975, NULL, 'Villarreal C', 'club', '2018–2019', 1, 0, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, NULL, 'Villarreal B', 'club', '2019–2020', 23, 0, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, 222, 'Villarreal', 'club', '2020–2025', 108, 15, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, 211, '→ Girona (loan)', 'club', '2021–2022', 38, 5, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, 205, 'Atlético Madrid', 'club', '2025–', 34, 6, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, NULL, 'Spain U16', 'international', '2017', 3, 2, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, NULL, 'Spain U17', 'international', '2017–2018', 11, 3, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, NULL, 'Spain U18', 'international', '2018–2019', 10, 3, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, NULL, 'Spain U19', 'international', '2019–2020', 7, 0, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, NULL, 'Spain U20', 'international', '2019', 5, 1, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, NULL, 'Spain U21', 'international', '2022–2023', 12, 2, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, NULL, 'Spain U23', 'international', '2024', 5, 2, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09'),
(975, 470, 'Spain', 'international', '2023–', 28, 4, NULL, 'English Wikipedia infobox, "Álex Baena" article', '2026-10-09');

-- Giacomo Raspadori (entity_id 976) -- Wikipedia: "Giacomo Raspadori"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(976, 240, 'Sassuolo', 'club', '2019–2023', 76, 18, NULL, 'English Wikipedia infobox, "Giacomo Raspadori" article', '2026-10-09'),
(976, 236, '→ Napoli (loan)', 'club', '2022–2023', 25, 2, NULL, 'English Wikipedia infobox, "Giacomo Raspadori" article', '2026-10-09'),
(976, 236, 'Napoli', 'club', '2023–2025', 63, 11, NULL, 'English Wikipedia infobox, "Giacomo Raspadori" article', '2026-10-09'),
(976, 205, 'Atlético Madrid', 'club', '2025–2026', 12, 0, NULL, 'English Wikipedia infobox, "Giacomo Raspadori" article', '2026-10-09'),
(976, 223, 'Atalanta', 'club', '2026–', 14, 4, NULL, 'English Wikipedia infobox, "Giacomo Raspadori" article', '2026-10-09'),
(976, NULL, 'Italy U17', 'international', '2016–2017', 9, 1, NULL, 'English Wikipedia infobox, "Giacomo Raspadori" article', '2026-10-09'),
(976, NULL, 'Italy U19', 'international', '2018–2019', 14, 4, NULL, 'English Wikipedia infobox, "Giacomo Raspadori" article', '2026-10-09'),
(976, NULL, 'Italy U20', 'international', '2019', 5, 1, NULL, 'English Wikipedia infobox, "Giacomo Raspadori" article', '2026-10-09'),
(976, NULL, 'Italy U21', 'international', '2020–2021', 8, 3, NULL, 'English Wikipedia infobox, "Giacomo Raspadori" article', '2026-10-09'),
(976, 445, 'Italy', 'international', '2021–', 47, 11, NULL, 'English Wikipedia infobox, "Giacomo Raspadori" article', '2026-10-09');

-- Mikel Oyarzabal (entity_id 977) -- Wikipedia: "Mikel Oyarzabal"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(977, NULL, 'Real Sociedad B', 'club', '2014–2015', 13, 3, NULL, 'English Wikipedia infobox, "Mikel Oyarzabal" article', '2026-10-09'),
(977, 219, 'Real Sociedad', 'club', '2015–', 356, 100, NULL, 'English Wikipedia infobox, "Mikel Oyarzabal" article', '2026-10-09'),
(977, NULL, 'Spain U18', 'international', '2015', 2, 0, NULL, 'English Wikipedia infobox, "Mikel Oyarzabal" article', '2026-10-09'),
(977, NULL, 'Spain U19', 'international', '2016', 4, 0, NULL, 'English Wikipedia infobox, "Mikel Oyarzabal" article', '2026-10-09'),
(977, NULL, 'Spain U21', 'international', '2017–2019', 25, 8, NULL, 'English Wikipedia infobox, "Mikel Oyarzabal" article', '2026-10-09'),
(977, NULL, 'Spain U23', 'international', '2021', 7, 3, NULL, 'English Wikipedia infobox, "Mikel Oyarzabal" article', '2026-10-09'),
(977, 470, 'Spain', 'international', '2016–', 64, 31, NULL, 'English Wikipedia infobox, "Mikel Oyarzabal" article', '2026-10-09'),
(977, NULL, 'Basque Country', 'international', '2016', 1, 1, NULL, 'English Wikipedia infobox, "Mikel Oyarzabal" article', '2026-10-09');

-- Nico Williams (entity_id 978) -- Wikipedia: "Nico Williams"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(978, NULL, 'Basconia', 'club', '2019–2020', 3, 0, NULL, 'English Wikipedia infobox, "Nico Williams" article', '2026-10-09'),
(978, NULL, 'Bilbao Athletic', 'club', '2020–2021', 24, 9, NULL, 'English Wikipedia infobox, "Nico Williams" article', '2026-10-09'),
(978, 204, 'Athletic Bilbao', 'club', '2021–', 163, 23, NULL, 'English Wikipedia infobox, "Nico Williams" article', '2026-10-09'),
(978, NULL, 'Spain U18', 'international', '2019–2021', 4, 2, NULL, 'English Wikipedia infobox, "Nico Williams" article', '2026-10-09'),
(978, NULL, 'Spain U21', 'international', '2021–2022', 5, 1, NULL, 'English Wikipedia infobox, "Nico Williams" article', '2026-10-09'),
(978, 470, 'Spain', 'international', '2022–', 38, 7, NULL, 'English Wikipedia infobox, "Nico Williams" article', '2026-10-09');

-- Inaki Williams (entity_id 979) -- Wikipedia: "Iñaki Williams"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(979, NULL, 'Basconia', 'club', '2013–2014', 18, 7, NULL, 'English Wikipedia infobox, "Iñaki Williams" article', '2026-10-09'),
(979, NULL, 'Bilbao Athletic', 'club', '2014–2015', 32, 21, NULL, 'English Wikipedia infobox, "Iñaki Williams" article', '2026-10-09'),
(979, 204, 'Athletic Bilbao', 'club', '2014–', 413, 86, NULL, 'English Wikipedia infobox, "Iñaki Williams" article', '2026-10-09'),
(979, NULL, 'Spain U21', 'international', '2015–2017', 17, 3, NULL, 'English Wikipedia infobox, "Iñaki Williams" article', '2026-10-09'),
(979, 470, 'Spain', 'international', '2016', 1, 0, NULL, 'English Wikipedia infobox, "Iñaki Williams" article', '2026-10-09'),
(979, NULL, 'Basque Country', 'international', '2018–2020', 2, 0, NULL, 'English Wikipedia infobox, "Iñaki Williams" article', '2026-10-09'),
(979, 497, 'Ghana', 'international', '2022–2026', 28, 2, NULL, 'English Wikipedia infobox, "Iñaki Williams" article', '2026-10-09');

-- Unai Simon (entity_id 980) -- Wikipedia: "Unai Simón"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(980, NULL, 'Basconia', 'club', '2014–2016', 36, 0, NULL, 'English Wikipedia infobox, "Unai Simón" article', '2026-10-09'),
(980, NULL, 'Athletic Bilbao B', 'club', '2016–2018', 58, 0, NULL, 'English Wikipedia infobox, "Unai Simón" article', '2026-10-09'),
(980, 204, 'Athletic Bilbao', 'club', '2018–', 243, 0, NULL, 'English Wikipedia infobox, "Unai Simón" article', '2026-10-09'),
(980, NULL, 'Spain U16', 'international', '2013', 1, 0, NULL, 'English Wikipedia infobox, "Unai Simón" article', '2026-10-09'),
(980, NULL, 'Spain U18', 'international', '2015', 3, 0, NULL, 'English Wikipedia infobox, "Unai Simón" article', '2026-10-09'),
(980, NULL, 'Spain U19', 'international', '2015–2016', 4, 0, NULL, 'English Wikipedia infobox, "Unai Simón" article', '2026-10-09'),
(980, NULL, 'Spain U21', 'international', '2017–2019', 10, 0, NULL, 'English Wikipedia infobox, "Unai Simón" article', '2026-10-09'),
(980, NULL, 'Spain U23', 'international', '2021', 7, 0, NULL, 'English Wikipedia infobox, "Unai Simón" article', '2026-10-09'),
(980, 470, 'Spain', 'international', '2020–', 69, 0, NULL, 'English Wikipedia infobox, "Unai Simón" article', '2026-10-09');

-- Aymeric Laporte (entity_id 981) -- Wikipedia: "Aymeric Laporte"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(981, NULL, 'Basconia', 'club', '2011–2012', 33, 2, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09'),
(981, NULL, 'Athletic Bilbao B', 'club', '2012–2013', 8, 0, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09'),
(981, 204, 'Athletic Bilbao', 'club', '2012–2018', 161, 7, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09'),
(981, 195, 'Manchester City', 'club', '2018–2023', 121, 8, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09'),
(981, 327, 'Al-Nassr', 'club', '2023–2025', 47, 8, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09'),
(981, 204, 'Athletic Bilbao', 'club', '2025–', 31, 0, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09'),
(981, NULL, 'France U17', 'international', '2011–2012', 11, 1, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09'),
(981, NULL, 'France U18', 'international', '2011–2012', 9, 0, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09'),
(981, NULL, 'France U19', 'international', '2012–2013', 12, 1, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09'),
(981, NULL, 'France U21', 'international', '2013–2016', 19, 1, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09'),
(981, 470, 'Spain', 'international', '2021–', 57, 2, NULL, 'English Wikipedia infobox, "Aymeric Laporte" article', '2026-10-09');

-- Alex Remiro (entity_id 982) -- Wikipedia: "Álex Remiro"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(982, NULL, 'Basconia', 'club', '2012–2014', 28, 0, NULL, 'English Wikipedia infobox, "Álex Remiro" article', '2026-10-09'),
(982, NULL, 'Bilbao Athletic', 'club', '2014–2016', 50, 0, NULL, 'English Wikipedia infobox, "Álex Remiro" article', '2026-10-09'),
(982, 204, 'Athletic Bilbao', 'club', '2016–2019', 0, 0, NULL, 'English Wikipedia infobox, "Álex Remiro" article', '2026-10-09'),
(982, 212, '→ Levante (loan)', 'club', '2016–2017', 4, 0, NULL, 'English Wikipedia infobox, "Álex Remiro" article', '2026-10-09'),
(982, 413, '→ Huesca (loan)', 'club', '2017–2018', 41, 0, NULL, 'English Wikipedia infobox, "Álex Remiro" article', '2026-10-09'),
(982, 219, 'Real Sociedad', 'club', '2019–', 252, 0, NULL, 'English Wikipedia infobox, "Álex Remiro" article', '2026-10-09'),
(982, NULL, 'Spain U19', 'international', '2013–2014', 5, 0, NULL, 'English Wikipedia infobox, "Álex Remiro" article', '2026-10-09'),
(982, 470, 'Spain', 'international', '2024–', 2, 0, NULL, 'English Wikipedia infobox, "Álex Remiro" article', '2026-10-09');

-- Isco (entity_id 983) -- Wikipedia: "Isco"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(983, NULL, 'Valencia B', 'club', '2009–2011', 52, 16, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, 221, 'Valencia', 'club', '2010–2011', 4, 0, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, 402, 'Málaga', 'club', '2011–2013', 69, 14, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, 217, 'Real Madrid', 'club', '2013–2022', 246, 37, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, 220, 'Sevilla', 'club', '2022', 12, 0, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, 216, 'Betis', 'club', '2023–', 66, 18, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, NULL, 'Spain U16', 'international', '2008', 3, 1, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, NULL, 'Spain U17', 'international', '2008–2009', 21, 6, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, NULL, 'Spain U18', 'international', '2010', 1, 1, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, NULL, 'Spain U19', 'international', '2010–2011', 12, 7, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, NULL, 'Spain U20', 'international', '2011', 6, 1, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, NULL, 'Spain U21', 'international', '2011–2014', 19, 14, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, NULL, 'Spain U23', 'international', '2012', 5, 0, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09'),
(983, 470, 'Spain', 'international', '2013–', 39, 12, NULL, 'English Wikipedia infobox, "Isco" article', '2026-10-09');

-- Giovani Lo Celso (entity_id 984) -- Wikipedia: "Giovani Lo Celso"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(984, 24, 'Rosario Central', 'club', '2015–2016', 27, 3, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09'),
(984, 261, 'Paris Saint-Germain', 'club', '2016–2019', 38, 4, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09'),
(984, 24, '→ Rosario Central (loan)', 'club', '2016', 9, 1, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09'),
(984, 216, '→ Betis (loan)', 'club', '2018–2019', 27, 8, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09'),
(984, 216, 'Betis', 'club', '2019–2020', 5, 1, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09'),
(984, 200, '→ Tottenham Hotspur (loan)', 'club', '2019–2020', 28, 0, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09'),
(984, 200, 'Tottenham Hotspur', 'club', '2020–2024', 49, 3, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09'),
(984, 222, '→ Villarreal (loan)', 'club', '2022–2023', 38, 3, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09'),
(984, 216, 'Betis', 'club', '2024–', 50, 10, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09'),
(984, NULL, 'Argentina Olympic', 'international', '2016', 3, 0, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09'),
(984, 19155, 'Argentina', 'international', '2017–', 68, 5, NULL, 'English Wikipedia infobox, "Giovani Lo Celso" article', '2026-10-09');

-- Antony (entity_id 985) -- Wikipedia: "Antony (footballer, born 2000)"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(985, 37, 'São Paulo', 'club', '2018–2020', 48, 6, NULL, 'English Wikipedia infobox, "Antony (footballer, born 2000)" article', '2026-10-09'),
(985, 283, 'Ajax', 'club', '2020–2022', 57, 18, NULL, 'English Wikipedia infobox, "Antony (footballer, born 2000)" article', '2026-10-09'),
(985, 196, 'Manchester United', 'club', '2022–2025', 62, 5, NULL, 'English Wikipedia infobox, "Antony (footballer, born 2000)" article', '2026-10-09'),
(985, 216, '→ Betis (loan)', 'club', '2025', 17, 5, NULL, 'English Wikipedia infobox, "Antony (footballer, born 2000)" article', '2026-10-09'),
(985, 216, 'Betis', 'club', '2025–', 39, 8, NULL, 'English Wikipedia infobox, "Antony (footballer, born 2000)" article', '2026-10-09'),
(985, NULL, 'Brazil U23', 'international', NULL, NULL, NULL, NULL, 'English Wikipedia infobox, "Antony (footballer, born 2000)" article', '2026-10-09'),
(985, 19157, 'Brazil', 'international', '2021–2023', 16, 2, NULL, 'English Wikipedia infobox, "Antony (footballer, born 2000)" article', '2026-10-09');

-- Gerard Moreno (entity_id 986) -- Wikipedia: "Gerard Moreno"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(986, NULL, 'Villarreal C', 'club', '2010–2011', 38, 34, NULL, 'English Wikipedia infobox, "Gerard Moreno" article', '2026-10-09'),
(986, NULL, 'Villarreal B', 'club', '2011–2013', 29, 13, NULL, 'English Wikipedia infobox, "Gerard Moreno" article', '2026-10-09'),
(986, 222, 'Villarreal', 'club', '2012–2015', 40, 10, NULL, 'English Wikipedia infobox, "Gerard Moreno" article', '2026-10-09'),
(986, 213, '→ Mallorca (loan)', 'club', '2013–2014', 31, 11, NULL, 'English Wikipedia infobox, "Gerard Moreno" article', '2026-10-09'),
(986, 209, 'Espanyol', 'club', '2015–2018', 107, 36, NULL, 'English Wikipedia infobox, "Gerard Moreno" article', '2026-10-09'),
(986, 222, 'Villarreal', 'club', '2018–', 216, 90, NULL, 'English Wikipedia infobox, "Gerard Moreno" article', '2026-10-09'),
(986, 470, 'Spain', 'international', '2019–2024', 18, 5, NULL, 'English Wikipedia infobox, "Gerard Moreno" article', '2026-10-09'),
(986, NULL, 'Catalonia', 'international', '2014–2016', 3, 1, NULL, 'English Wikipedia infobox, "Gerard Moreno" article', '2026-10-09');

-- Ayoze Perez (entity_id 987) -- Wikipedia: "Ayoze Pérez"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(987, NULL, 'Tenerife B', 'club', '2011–2013', 35, 11, NULL, 'English Wikipedia infobox, "Ayoze Pérez" article', '2026-10-09'),
(987, 417, 'Tenerife', 'club', '2012–2014', 50, 17, NULL, 'English Wikipedia infobox, "Ayoze Pérez" article', '2026-10-09'),
(987, 197, 'Newcastle United', 'club', '2014–2019', 179, 42, NULL, 'English Wikipedia infobox, "Ayoze Pérez" article', '2026-10-09'),
(987, 305, 'Leicester City', 'club', '2019–2023', 80, 12, NULL, 'English Wikipedia infobox, "Ayoze Pérez" article', '2026-10-09'),
(987, 216, '→ Betis (loan)', 'club', '2023', 19, 3, NULL, 'English Wikipedia infobox, "Ayoze Pérez" article', '2026-10-09'),
(987, 216, 'Betis', 'club', '2023–2024', 31, 9, NULL, 'English Wikipedia infobox, "Ayoze Pérez" article', '2026-10-09'),
(987, 222, 'Villarreal', 'club', '2024–', 55, 24, NULL, 'English Wikipedia infobox, "Ayoze Pérez" article', '2026-10-09'),
(987, NULL, 'Spain U21', 'international', '2014', 2, 0, NULL, 'English Wikipedia infobox, "Ayoze Pérez" article', '2026-10-09'),
(987, 470, 'Spain', 'international', '2024–', 5, 2, NULL, 'English Wikipedia infobox, "Ayoze Pérez" article', '2026-10-09');

-- Jose Gaya (entity_id 988) -- Wikipedia: "José Gayà"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(988, NULL, 'Valencia B', 'club', '2012–2014', 63, 3, NULL, 'English Wikipedia infobox, "José Gayà" article', '2026-10-09'),
(988, 221, 'Valencia', 'club', '2012–', 344, 9, NULL, 'English Wikipedia infobox, "José Gayà" article', '2026-10-09'),
(988, NULL, 'Spain U17', 'international', '2012', 2, 1, NULL, 'English Wikipedia infobox, "José Gayà" article', '2026-10-09'),
(988, NULL, 'Spain U18', 'international', '2013', 2, 0, NULL, 'English Wikipedia infobox, "José Gayà" article', '2026-10-09'),
(988, NULL, 'Spain U19', 'international', '2013–2014', 11, 1, NULL, 'English Wikipedia infobox, "José Gayà" article', '2026-10-09'),
(988, NULL, 'Spain U20', 'international', '2013', 4, 0, NULL, 'English Wikipedia infobox, "José Gayà" article', '2026-10-09'),
(988, NULL, 'Spain U21', 'international', '2014–2017', 15, 1, NULL, 'English Wikipedia infobox, "José Gayà" article', '2026-10-09'),
(988, 470, 'Spain', 'international', '2018–2023', 22, 3, NULL, 'English Wikipedia infobox, "José Gayà" article', '2026-10-09');

-- Hugo Duro (entity_id 989) -- Wikipedia: "Hugo Duro"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(989, NULL, 'Getafe B', 'club', '2017–2019', 69, 32, NULL, 'English Wikipedia infobox, "Hugo Duro" article', '2026-10-09'),
(989, 210, 'Getafe', 'club', '2017–2022', 26, 1, NULL, 'English Wikipedia infobox, "Hugo Duro" article', '2026-10-09'),
(989, NULL, '→ Real Madrid B (loan)', 'club', '2020–2021', 19, 12, NULL, 'English Wikipedia infobox, "Hugo Duro" article', '2026-10-09'),
(989, 217, '→ Real Madrid (loan)', 'club', '2021', 2, 0, NULL, 'English Wikipedia infobox, "Hugo Duro" article', '2026-10-09'),
(989, 221, '→ Valencia (loan)', 'club', '2021–2022', 30, 7, NULL, 'English Wikipedia infobox, "Hugo Duro" article', '2026-10-09'),
(989, 221, 'Valencia', 'club', '2022–', 134, 35, NULL, 'English Wikipedia infobox, "Hugo Duro" article', '2026-10-09'),
(989, NULL, 'Spain U21', 'international', '2020', 1, 1, NULL, 'English Wikipedia infobox, "Hugo Duro" article', '2026-10-09');

-- Santi Cazorla (entity_id 990) -- Wikipedia: "Santi Cazorla"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(990, NULL, 'Villarreal B', 'club', '2003–2004', 40, 4, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09'),
(990, 222, 'Villarreal', 'club', '2003–2006', 54, 2, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09'),
(990, 419, 'Recreativo', 'club', '2006–2007', 34, 5, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09'),
(990, 222, 'Villarreal', 'club', '2007–2011', 127, 23, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09'),
(990, 402, 'Málaga', 'club', '2011–2012', 38, 9, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09'),
(990, 183, 'Arsenal', 'club', '2012–2018', 129, 25, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09'),
(990, 222, 'Villarreal', 'club', '2018–2020', 70, 15, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09'),
(990, 19447, 'Al Sadd', 'club', '2020–2023', 55, 23, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09'),
(990, NULL, 'Oviedo', 'club', '2023–2026', 84, 3, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09'),
(990, NULL, 'Spain U21', 'international', '2004–2006', 7, 0, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09'),
(990, 470, 'Spain', 'international', '2008–2020', 81, 15, NULL, 'English Wikipedia infobox, "Santi Cazorla" article', '2026-10-09');

-- Yann Sommer (entity_id 991) -- Wikipedia: "Yann Sommer"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(991, NULL, 'FC Basel U21', 'club', '2005–2007', 42, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, NULL, 'FC Basel', 'club', '2007–2014', 113, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, NULL, '→ FC Vaduz (loan)', 'club', '2007–2009', 50, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, NULL, '→ Grasshoppers (loan)', 'club', '2009–2010', 33, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, 254, 'Borussia Mönchengladbach', 'club', '2014–2023', 272, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, 243, 'Bayern Munich', 'club', '2023', 19, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, 231, 'Inter Milan', 'club', '2023–2026', 100, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, 292, 'Club Brugge', 'club', '2026–', 7, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, NULL, 'Switzerland U16', 'international', '2003–2004', 6, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, NULL, 'Switzerland U17', 'international', '2003–2005', 10, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, NULL, 'Switzerland U19', 'international', '2005–2007', 18, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, NULL, 'Switzerland U21', 'international', '2007–2011', 31, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, NULL, 'Switzerland U20', 'international', '2009', 1, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09'),
(991, 472, 'Switzerland', 'international', '2012–2024', 94, 0, NULL, 'English Wikipedia infobox, "Yann Sommer" article', '2026-10-09');

-- Alessandro Bastoni (entity_id 992) -- Wikipedia: "Alessandro Bastoni"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(992, 223, 'Atalanta', 'club', '2016–2017', 3, 0, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, 231, 'Inter Milan', 'club', '2017–', 212, 6, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, 223, '→ Atalanta (loan)', 'club', '2017–2018', 4, 0, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, 237, '→ Parma (loan)', 'club', '2018–2019', 24, 1, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, NULL, '(row 5)', 'club', '2023—', 0, 0, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, NULL, 'Italy U15', 'international', '2014', 7, 0, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, NULL, 'Italy U16', 'international', '2014–2015', 15, 1, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, NULL, 'Italy U17', 'international', '2015–2016', 17, 0, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, NULL, 'Italy U18', 'international', '2016', 3, 0, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, NULL, 'Italy U19', 'international', '2017–2018', 9, 2, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, NULL, 'Italy U21', 'international', '2018–2019', 12, 1, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09'),
(992, 445, 'Italy', 'international', '2020–', 46, 5, NULL, 'English Wikipedia infobox, "Alessandro Bastoni" article', '2026-10-09');

-- Benjamin Pavard (entity_id 993) -- Wikipedia: "Benjamin Pavard"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(993, NULL, 'Lille II', 'club', '2014–2016', 20, 1, NULL, 'English Wikipedia infobox, "Benjamin Pavard" article', '2026-10-09'),
(993, 265, 'Lille', 'club', '2015–2016', 21, 0, NULL, 'English Wikipedia infobox, "Benjamin Pavard" article', '2026-10-09'),
(993, 247, 'VfB Stuttgart', 'club', '2016–2019', 84, 2, NULL, 'English Wikipedia infobox, "Benjamin Pavard" article', '2026-10-09'),
(993, 243, 'Bayern Munich', 'club', '2019–2023', 111, 8, NULL, 'English Wikipedia infobox, "Benjamin Pavard" article', '2026-10-09'),
(993, 231, 'Inter Milan', 'club', '2023–', 49, 0, NULL, 'English Wikipedia infobox, "Benjamin Pavard" article', '2026-10-09'),
(993, 262, '→ Marseille (loan)', 'club', '2025–2026', 27, 1, NULL, 'English Wikipedia infobox, "Benjamin Pavard" article', '2026-10-09'),
(993, NULL, 'France U19', 'international', '2015', 4, 0, NULL, 'English Wikipedia infobox, "Benjamin Pavard" article', '2026-10-09'),
(993, NULL, 'France U21', 'international', '2015–2017', 15, 0, NULL, 'English Wikipedia infobox, "Benjamin Pavard" article', '2026-10-09'),
(993, 437, 'France', 'international', '2017–', 55, 5, NULL, 'English Wikipedia infobox, "Benjamin Pavard" article', '2026-10-09');

-- Stefan de Vrij (entity_id 994) -- Wikipedia: "Stefan de Vrij"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(994, 285, 'Feyenoord', 'club', '2009–2014', 135, 7, NULL, 'English Wikipedia infobox, "Stefan de Vrij" article', '2026-10-09'),
(994, 233, 'Lazio', 'club', '2014–2018', 95, 8, NULL, 'English Wikipedia infobox, "Stefan de Vrij" article', '2026-10-09'),
(994, 231, 'Inter Milan', 'club', '2018–2026', 213, 12, NULL, 'English Wikipedia infobox, "Stefan de Vrij" article', '2026-10-09'),
(994, 298, 'Panathinaikos', 'club', '2026–', 5, 0, NULL, 'English Wikipedia infobox, "Stefan de Vrij" article', '2026-10-09'),
(994, NULL, 'Netherlands U16', 'international', '2007–2008', 3, 0, NULL, 'English Wikipedia infobox, "Stefan de Vrij" article', '2026-10-09'),
(994, NULL, 'Netherlands U17', 'international', '2008–2009', 18, 0, NULL, 'English Wikipedia infobox, "Stefan de Vrij" article', '2026-10-09'),
(994, NULL, 'Netherlands U19', 'international', '2010–2011', 9, 0, NULL, 'English Wikipedia infobox, "Stefan de Vrij" article', '2026-10-09'),
(994, NULL, 'Netherlands U20', 'international', '2012', 1, 0, NULL, 'English Wikipedia infobox, "Stefan de Vrij" article', '2026-10-09'),
(994, NULL, 'Netherlands U21', 'international', '2011–2013', 12, 0, NULL, 'English Wikipedia infobox, "Stefan de Vrij" article', '2026-10-09'),
(994, 456, 'Netherlands', 'international', '2012–', 79, 4, NULL, 'English Wikipedia infobox, "Stefan de Vrij" article', '2026-10-09');

-- Federico Dimarco (entity_id 995) -- Wikipedia: "Federico Dimarco"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(995, 231, 'Inter Milan', 'club', '2014–2017', 1, 0, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, NULL, '→ Ascoli (loan)', 'club', '2016', 15, 0, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, 19088, '→ Empoli (loan)', 'club', '2016–2017', 12, 0, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, 19534, 'Sion', 'club', '2017–2018', 9, 0, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, 231, 'Inter Milan', 'club', '2018–', 171, 22, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, 237, '→ Parma (loan)', 'club', '2018–2019', 13, 1, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, 230, '→ Hellas Verona (loan)', 'club', '2020–2021', 48, 5, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, NULL, 'Italy U15', 'international', '2012', 6, 1, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, NULL, 'Italy U16', 'international', '2012–2013', 5, 0, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, NULL, 'Italy U17', 'international', '2013–2014', 19, 1, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, NULL, 'Italy U18', 'international', '2014–2015', 9, 1, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, NULL, 'Italy U19', 'international', '2015–2016', 18, 6, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, NULL, 'Italy U20', 'international', '2016–2017', 11, 2, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, NULL, 'Italy U21', 'international', '2017–2019', 12, 1, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09'),
(995, 445, 'Italy', 'international', '2022–', 38, 3, NULL, 'English Wikipedia infobox, "Federico Dimarco" article', '2026-10-09');

-- Nicolo Barella (entity_id 996) -- Wikipedia: "Nicolò Barella"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(996, 225, 'Cagliari', 'club', '2015–2020', 105, 7, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, 226, '→ Como (loan)', 'club', '2016', 16, 0, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, 231, '→ Inter Milan (loan)', 'club', '2019–2020', 27, 1, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, 231, 'Inter Milan', 'club', '2020–', 216, 21, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, NULL, 'Italy U15', 'international', '2012', 5, 0, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, NULL, 'Italy U16', 'international', '2012–2013', 4, 0, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, NULL, 'Italy U17', 'international', '2013–2014', 5, 0, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, NULL, 'Italy U18', 'international', '2014–2015', 8, 0, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, NULL, 'Italy U19', 'international', '2015–2016', 16, 0, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, NULL, 'Italy U20', 'international', '2016–2017', 8, 0, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, NULL, 'Italy U21', 'international', '2017–2019', 9, 1, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09'),
(996, 445, 'Italy', 'international', '2018–', 73, 10, NULL, 'English Wikipedia infobox, "Nicolò Barella" article', '2026-10-09');

-- Hakan Calhanoglu (entity_id 997) -- Wikipedia: "Hakan Çalhanoğlu"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(997, NULL, 'Karlsruher', 'club', '2011–2013', 50, 17, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09'),
(997, 260, 'Hamburger SV', 'club', '2013–2014', 32, 11, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09'),
(997, 246, 'Bayer Leverkusen', 'club', '2014–2017', 79, 17, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09'),
(997, 235, 'AC Milan', 'club', '2017–2021', 135, 22, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09'),
(997, 231, 'Inter Milan', 'club', '2021–', 153, 39, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09'),
(997, NULL, 'Turkey U16', 'international', '2010', 6, 1, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09'),
(997, NULL, 'Turkey U17', 'international', '2010–2011', 11, 1, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09'),
(997, NULL, 'Turkey U19', 'international', '2011–2013', 15, 5, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09'),
(997, NULL, 'Turkey U20', 'international', '2012–2013', 9, 1, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09'),
(997, NULL, 'Turkey U21', 'international', '2012–2014', 2, 0, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09'),
(997, 473, 'Turkey', 'international', '2013–', 108, 22, NULL, 'English Wikipedia infobox, "Hakan Çalhanoğlu" article', '2026-10-09');

-- Henrikh Mkhitaryan (entity_id 998) -- Wikipedia: "Henrikh Mkhitaryan"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(998, NULL, 'Pyunik', 'club', '2006–2009', 70, 30, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, NULL, 'Metalurh Donetsk', 'club', '2009–2010', 37, 12, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, 295, 'Shakhtar Donetsk', 'club', '2010–2013', 72, 38, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, 244, 'Borussia Dortmund', 'club', '2013–2016', 90, 23, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, 196, 'Manchester United', 'club', '2016–2018', 39, 5, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, 183, 'Arsenal', 'club', '2018–2020', 39, 8, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, 239, '→ Roma (loan)', 'club', '2019–2020', 22, 9, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, 239, 'Roma', 'club', '2020–2022', 65, 18, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, 231, 'Inter Milan', 'club', '2022–', 130, 10, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, NULL, 'Armenia U17', 'international', '2006–2007', 5, 1, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, NULL, 'Armenia U19', 'international', '2007–2008', 6, 1, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, NULL, 'Armenia U21', 'international', '2008–2010', 13, 9, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09'),
(998, 422, 'Armenia', 'international', '2007–2021', 95, 32, NULL, 'English Wikipedia infobox, "Henrikh Mkhitaryan" article', '2026-10-09');

-- Piotr Zielinski (entity_id 999) -- Wikipedia: "Piotr Zieliński"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(999, 242, 'Udinese', 'club', '2012–2016', 19, 0, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09'),
(999, 19088, '→ Empoli (loan)', 'club', '2014–2016', 63, 5, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09'),
(999, 236, 'Napoli', 'club', '2016–2024', 281, 37, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09'),
(999, 231, 'Inter Milan', 'club', '2024–', 65, 9, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09'),
(999, NULL, 'Poland U15', 'international', '2009', 5, 1, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09'),
(999, NULL, 'Poland U16', 'international', '2009–2010', 6, 0, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09'),
(999, NULL, 'Poland U17', 'international', '2010–2011', 10, 1, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09'),
(999, NULL, 'Poland U18', 'international', '2012', 5, 1, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09'),
(999, NULL, 'Poland U19', 'international', '2011–2012', 15, 5, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09'),
(999, NULL, 'Poland U21', 'international', '2012–2013', 3, 1, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09'),
(999, 460, 'Poland', 'international', '2013–', 113, 18, NULL, 'English Wikipedia infobox, "Piotr Zieliński" article', '2026-10-09');

-- Marcus Thuram (entity_id 1000) -- Wikipedia: "Marcus Thuram"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(1000, NULL, 'Sochaux II', 'club', '2014–2017', 38, 6, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09'),
(1000, 19063, 'Sochaux', 'club', '2015–2017', 37, 1, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09'),
(1000, 19123, 'Guingamp', 'club', '2017–2019', 64, 12, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09'),
(1000, 254, 'Borussia Mönchengladbach', 'club', '2019–2023', 111, 34, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09'),
(1000, 231, 'Inter Milan', 'club', '2023–', 100, 42, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09'),
(1000, NULL, 'France U17', 'international', '2014', 4, 1, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09'),
(1000, NULL, 'France U18', 'international', '2014–2015', 5, 2, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09'),
(1000, NULL, 'France U19', 'international', '2015–2016', 15, 3, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09'),
(1000, NULL, 'France U20', 'international', '2016–2017', 11, 3, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09'),
(1000, NULL, 'France U21', 'international', '2019', 5, 0, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09'),
(1000, 437, 'France', 'international', '2020–', 35, 3, NULL, 'English Wikipedia infobox, "Marcus Thuram" article', '2026-10-09');
