-- Research output: per-team career stats, generated by scripts/research_player_stats.py.
-- Every row is a literal Wikipedia infobox club/international career-history row --
-- mechanical extraction, no LLM judgment, no estimates. The infobox's own separately-
-- maintained totalcaps/totalgoals 'Total' field is NOT used -- a player's career total
-- is a SUM() over these rows. Individual appearances/goals values are NULL wherever the
-- source itself doesn't state a number (never guessed/derived) -- a NULL just means that
-- field isn't usable in a total/category yet, not that the row is wrong.
-- verified_at = 2026-10-09 for all rows.
-- FOR HUMAN REVIEW BEFORE APPLYING. Not applied to any database by this script.

-- Jorgen Strand Larsen (entity_id 901) -- Wikipedia: "Jørgen Strand Larsen"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(901, NULL, 'Sarpsborg 08', 'club', '2017–2020', 48, 6, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, 18978, 'Groningen', 'club', '2020–2022', 67, 24, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, 207, 'Celta Vigo', 'club', '2022–2025', 69, 17, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, 202, '→ Wolverhampton Wanderers (loan)', 'club', '2024–2025', 35, 14, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, 202, 'Wolverhampton Wanderers', 'club', '2025–2026', 22, 1, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, 190, 'Crystal Palace', 'club', '2026–', 19, 4, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, NULL, 'Norway U16', 'international', '2016–2017', 12, 6, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, NULL, 'Norway U17', 'international', '2017', 9, 3, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, NULL, 'Norway U18', 'international', '2018', 12, 1, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, NULL, 'Norway U19', 'international', '2019', 7, 4, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, NULL, 'Norway U20', 'international', '2019', 1, 0, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, NULL, 'Norway U21', 'international', '2019–2022', 16, 11, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09'),
(901, 459, 'Norway', 'international', '2020–', 33, 6, NULL, 'English Wikipedia infobox, "Jørgen Strand Larsen" article', '2026-10-09');

-- Jose Sa (entity_id 902) -- Wikipedia: "José Sá"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(902, NULL, 'Marítimo B', 'club', '2012–2015', 74, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09'),
(902, 18986, 'Marítimo', 'club', '2013–2016', 16, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09'),
(902, NULL, 'Porto B', 'club', '2016', 16, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09'),
(902, 279, 'Porto', 'club', '2016–2019', 15, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09'),
(902, 297, '→ Olympiacos (loan)', 'club', '2018–2019', 21, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09'),
(902, 297, 'Olympiacos', 'club', '2019–2021', 62, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09'),
(902, 202, 'Wolverhampton Wanderers', 'club', '2021–', 163, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09'),
(902, NULL, 'Portugal U20', 'international', '2012–2013', 14, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09'),
(902, NULL, 'Portugal U21', 'international', '2013–2015', 16, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09'),
(902, NULL, 'Portugal U23', 'international', '2016', 1, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09'),
(902, 461, 'Portugal', 'international', '2023–', 5, 0, NULL, 'English Wikipedia infobox, "José Sá" article', '2026-10-09');

-- Marshall Munetsi (entity_id 903) -- Wikipedia: "Marshall Munetsi"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(903, NULL, 'Ubuntu Cape Town', 'club', '2015–2016', 22, 1, NULL, 'English Wikipedia infobox, "Marshall Munetsi" article', '2026-10-09'),
(903, NULL, 'Baroka', 'club', '2016–2017', 26, 2, NULL, 'English Wikipedia infobox, "Marshall Munetsi" article', '2026-10-09'),
(903, NULL, 'Orlando Pirates', 'club', '2017–2019', 28, 0, NULL, 'English Wikipedia infobox, "Marshall Munetsi" article', '2026-10-09'),
(903, 19129, 'Reims', 'club', '2019–2025', 148, 21, NULL, 'English Wikipedia infobox, "Marshall Munetsi" article', '2026-10-09'),
(903, 202, 'Wolverhampton Wanderers', 'club', '2025–', 28, 4, NULL, 'English Wikipedia infobox, "Marshall Munetsi" article', '2026-10-09'),
(903, 278, '→ Paris FC (loan)', 'club', '2026', 15, 4, NULL, 'English Wikipedia infobox, "Marshall Munetsi" article', '2026-10-09'),
(903, 529, 'Zimbabwe', 'international', '2018–', 43, 5, NULL, 'English Wikipedia infobox, "Marshall Munetsi" article', '2026-10-09');

-- Jean-Ricner Bellegarde (entity_id 904) -- Wikipedia: "Jean-Ricner Bellegarde"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(904, NULL, 'Lens B', 'club', '2015–2019', 38, 0, NULL, 'English Wikipedia infobox, "Jean-Ricner Bellegarde" article', '2026-10-09'),
(904, 267, 'Lens', 'club', '2016–2019', 55, 5, NULL, 'English Wikipedia infobox, "Jean-Ricner Bellegarde" article', '2026-10-09'),
(904, 269, 'Strasbourg', 'club', '2019–2023', 128, 7, NULL, 'English Wikipedia infobox, "Jean-Ricner Bellegarde" article', '2026-10-09'),
(904, 202, 'Wolverhampton Wanderers', 'club', '2023–', 84, 5, NULL, 'English Wikipedia infobox, "Jean-Ricner Bellegarde" article', '2026-10-09'),
(904, NULL, 'France U19', 'international', '2017', 1, 0, NULL, 'English Wikipedia infobox, "Jean-Ricner Bellegarde" article', '2026-10-09'),
(904, NULL, 'France U20', 'international', '2017–2018', 4, 0, NULL, 'English Wikipedia infobox, "Jean-Ricner Bellegarde" article', '2026-10-09'),
(904, NULL, 'France U21', 'international', '2019', 3, 0, NULL, 'English Wikipedia infobox, "Jean-Ricner Bellegarde" article', '2026-10-09'),
(904, NULL, 'Haiti', 'international', '2025–', 17, 1, NULL, 'English Wikipedia infobox, "Jean-Ricner Bellegarde" article', '2026-10-09');

-- Morgan Gibbs-White (entity_id 905) -- Wikipedia: "Morgan Gibbs-White"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(905, 202, 'Wolverhampton Wanderers', 'club', '2017–2022', 68, 1, NULL, 'English Wikipedia infobox, "Morgan Gibbs-White" article', '2026-10-09'),
(905, 321, '→ Swansea City (loan)', 'club', '2020–2021', 5, 1, NULL, 'English Wikipedia infobox, "Morgan Gibbs-White" article', '2026-10-09'),
(905, 308, '→ Sheffield United (loan)', 'club', '2021–2022', 35, 11, NULL, 'English Wikipedia infobox, "Morgan Gibbs-White" article', '2026-10-09'),
(905, 198, 'Nottingham Forest', 'club', '2022–', 148, 33, NULL, 'English Wikipedia infobox, "Morgan Gibbs-White" article', '2026-10-09'),
(905, NULL, 'England U16', 'international', '2016', 1, 1, NULL, 'English Wikipedia infobox, "Morgan Gibbs-White" article', '2026-10-09'),
(905, NULL, 'England U17', 'international', '2016–2017', 14, 4, NULL, 'English Wikipedia infobox, "Morgan Gibbs-White" article', '2026-10-09'),
(905, NULL, 'England U18', 'international', '2018', 2, 0, NULL, 'English Wikipedia infobox, "Morgan Gibbs-White" article', '2026-10-09'),
(905, NULL, 'England U19', 'international', '2018–2019', 10, 1, NULL, 'English Wikipedia infobox, "Morgan Gibbs-White" article', '2026-10-09'),
(905, NULL, 'England U21', 'international', '2019–2023', 18, 3, NULL, 'English Wikipedia infobox, "Morgan Gibbs-White" article', '2026-10-09'),
(905, 433, 'England', 'international', '2024–', 10, 0, NULL, 'English Wikipedia infobox, "Morgan Gibbs-White" article', '2026-10-09');

-- Chris Wood (entity_id 906) -- Wikipedia: "Chris Wood (footballer, born 1991)"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(906, NULL, 'Cambridge', 'club', '2006', NULL, NULL, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, NULL, 'Hamilton Wanderers', 'club', '2007', 17, 16, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, NULL, 'Waikato', 'club', '2007–2008', 5, 0, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 317, 'West Bromwich Albion', 'club', '2009–2013', 21, 1, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 346, '→ Barnsley (loan)', 'club', '2010', 7, 0, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 187, '→ Brighton & Hove Albion (loan)', 'club', '2010–2011', 29, 8, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 318, '→ Birmingham City (loan)', 'club', '2011–2012', 23, 9, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 340, '→ Bristol City (loan)', 'club', '2012', 19, 3, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 342, '→ Millwall (loan)', 'club', '2012', 19, 11, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 305, '→ Leicester City (loan)', 'club', '2013', 1, 2, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 305, 'Leicester City', 'club', '2013–2015', 52, 12, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 307, '→ Ipswich Town (loan)', 'club', '2015', 8, 0, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 193, 'Leeds United', 'club', '2015–2017', 83, 41, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 188, 'Burnley', 'club', '2017–2022', 144, 49, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 197, 'Newcastle United', 'club', '2022–2023', 35, 4, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 198, '→ Nottingham Forest (loan)', 'club', '2023', 7, 1, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, 198, 'Nottingham Forest', 'club', '2023–', 86, 37, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, NULL, 'New Zealand U17', 'international', '2007', 3, 0, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, NULL, 'New Zealand U23', 'international', '2012', 5, 1, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, NULL, 'New Zealand Olympic (O.P.)', 'international', '2021', 5, 3, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09'),
(906, NULL, 'New Zealand', 'international', '2009–', 95, 45, NULL, 'English Wikipedia infobox, "Chris Wood (footballer, born 1991)" article', '2026-10-09');

-- Callum Hudson-Odoi (entity_id 907) -- Wikipedia: "Callum Hudson-Odoi"
-- SCOPE CAVEAT on club rows (infobox wikitext comment): <!-- per http://www.englandfootballonline.com/MatchRsl/MatchRslTmU18pg7.html excludes eight appearances and one goal from the 2017 FIFA U-20 World Cup and a pre-tournament friendly, which England Football Online list on their under-18 page -->
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(907, 189, 'Chelsea', 'club', '2018–2023', 72, 4, '<!-- per http://www.englandfootballonline.com/MatchRsl/MatchRslTmU18pg7.html excludes eight appearances and one goal from the 2017 FIFA U-20 World Cup and a pre-tournament friendly, which England Football Online list on their under-18 page -->', 'English Wikipedia infobox, "Callum Hudson-Odoi" article', '2026-10-09'),
(907, 246, '→ Bayer Leverkusen (loan)', 'club', '2022–2023', 14, 0, '<!-- per http://www.englandfootballonline.com/MatchRsl/MatchRslTmU18pg7.html excludes eight appearances and one goal from the 2017 FIFA U-20 World Cup and a pre-tournament friendly, which England Football Online list on their under-18 page -->', 'English Wikipedia infobox, "Callum Hudson-Odoi" article', '2026-10-09'),
(907, 198, 'Nottingham Forest', 'club', '2023–', 91, 16, '<!-- per http://www.englandfootballonline.com/MatchRsl/MatchRslTmU18pg7.html excludes eight appearances and one goal from the 2017 FIFA U-20 World Cup and a pre-tournament friendly, which England Football Online list on their under-18 page -->', 'English Wikipedia infobox, "Callum Hudson-Odoi" article', '2026-10-09'),
(907, NULL, 'England U16', 'international', '2015–2016', 4, 0, NULL, 'English Wikipedia infobox, "Callum Hudson-Odoi" article', '2026-10-09'),
(907, NULL, 'England U17', 'international', '2016–2017', 23, 6, NULL, 'English Wikipedia infobox, "Callum Hudson-Odoi" article', '2026-10-09'),
(907, NULL, 'England U18', 'international', '2018', 2, 1, NULL, 'English Wikipedia infobox, "Callum Hudson-Odoi" article', '2026-10-09'),
(907, NULL, 'England U19', 'international', '2018', 7, 2, NULL, 'English Wikipedia infobox, "Callum Hudson-Odoi" article', '2026-10-09'),
(907, NULL, 'England U21', 'international', '2019–2021', 9, 4, NULL, 'English Wikipedia infobox, "Callum Hudson-Odoi" article', '2026-10-09'),
(907, 433, 'England', 'international', '2019', 3, 0, NULL, 'English Wikipedia infobox, "Callum Hudson-Odoi" article', '2026-10-09');

-- Ola Aina (entity_id 908) -- Wikipedia: "Ola Aina"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(908, 189, 'Chelsea', 'club', '2015–2019', 3, 0, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, 322, '→ Hull City (loan)', 'club', '2017–2018', 44, 0, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, 241, '→ Torino (loan)', 'club', '2018–2019', 30, 1, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, 241, 'Torino', 'club', '2019–2023', 72, 1, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, 192, '→ Fulham (loan)', 'club', '2020–2021', 31, 2, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, 198, 'Nottingham Forest', 'club', '2023–', 79, 3, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, NULL, 'England U16', 'international', '2011–2012', 6, 0, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, NULL, 'England U17', 'international', '2012–2013', 11, 0, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, NULL, 'England U18', 'international', '2013', 1, 0, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, NULL, 'England U19', 'international', '2013–2015', 13, 0, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, NULL, 'England U20', 'international', '2015–2016', 4, 0, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09'),
(908, 514, 'Nigeria', 'international', '2017–', 49, 0, NULL, 'English Wikipedia infobox, "Ola Aina" article', '2026-10-09');

-- Murillo (entity_id 909) -- Wikipedia: "Murillo (footballer)"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(909, 39, 'Corinthians', 'club', '2022–2023', 13, 0, NULL, 'English Wikipedia infobox, "Murillo (footballer)" article', '2026-10-09'),
(909, 198, 'Nottingham Forest', 'club', '2023–', 97, 3, NULL, 'English Wikipedia infobox, "Murillo (footballer)" article', '2026-10-09'),
(909, 19157, 'Brazil', 'international', '2025–', 1, 0, NULL, 'English Wikipedia infobox, "Murillo (footballer)" article', '2026-10-09');

-- Nikola Milenkovic (entity_id 910) -- Wikipedia: "Nikola Milenković"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(910, NULL, 'Partizan', 'club', '2015–2017', 36, 2, NULL, 'English Wikipedia infobox, "Nikola Milenković" article', '2026-10-09'),
(910, NULL, '→ Teleoptik (loan)', 'club', '2015–2016', 13, 0, NULL, 'English Wikipedia infobox, "Nikola Milenković" article', '2026-10-09'),
(910, 228, 'Fiorentina', 'club', '2017–2024', 216, 14, NULL, 'English Wikipedia infobox, "Nikola Milenković" article', '2026-10-09'),
(910, 198, 'Nottingham Forest', 'club', '2024–', 78, 5, NULL, 'English Wikipedia infobox, "Nikola Milenković" article', '2026-10-09'),
(910, NULL, 'Serbia U21', 'international', '2017–2019', 9, 0, NULL, 'English Wikipedia infobox, "Nikola Milenković" article', '2026-10-09'),
(910, 467, 'Serbia', 'international', '2018–', 71, 3, NULL, 'English Wikipedia infobox, "Nikola Milenković" article', '2026-10-09');

-- Matz Sels (entity_id 911) -- Wikipedia: "Matz Sels"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(911, NULL, 'Lierse', 'club', '2010–2014', 30, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09'),
(911, 18997, 'Gent', 'club', '2014–2016', 94, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09'),
(911, 197, 'Newcastle United', 'club', '2016–2018', 9, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09'),
(911, 293, '→ Anderlecht (loan)', 'club', '2017–2018', 32, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09'),
(911, 269, 'Strasbourg', 'club', '2018–2024', 164, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09'),
(911, 198, 'Nottingham Forest', 'club', '2024–', 90, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09'),
(911, NULL, 'Belgium U17', 'international', '2009', 2, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09'),
(911, NULL, 'Belgium U18', 'international', '2009–2010', 8, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09'),
(911, NULL, 'Belgium U19', 'international', '2010–2011', 5, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09'),
(911, NULL, 'Belgium U21', 'international', '2012–2014', 4, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09'),
(911, 426, 'Belgium', 'international', '2021–2026', 13, 0, NULL, 'English Wikipedia infobox, "Matz Sels" article', '2026-10-09');

-- Elliot Anderson (entity_id 912) -- Wikipedia: "Elliot Anderson"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(912, 197, 'Newcastle United', 'club', '2019–2024', 44, 0, NULL, 'English Wikipedia infobox, "Elliot Anderson" article', '2026-10-09'),
(912, NULL, '→ Bristol Rovers (loan)', 'club', '2022', 21, 7, NULL, 'English Wikipedia infobox, "Elliot Anderson" article', '2026-10-09'),
(912, 198, 'Nottingham Forest', 'club', '2024–2026', 75, 6, NULL, 'English Wikipedia infobox, "Elliot Anderson" article', '2026-10-09'),
(912, 195, 'Manchester City', 'club', '2026–', 5, 0, NULL, 'English Wikipedia infobox, "Elliot Anderson" article', '2026-10-09'),
(912, NULL, 'Scotland U16', 'international', '2018', 1, 0, NULL, 'English Wikipedia infobox, "Elliot Anderson" article', '2026-10-09'),
(912, NULL, 'Scotland U17', 'international', '2018–2019', 3, 0, NULL, 'English Wikipedia infobox, "Elliot Anderson" article', '2026-10-09'),
(912, NULL, 'Scotland U18', 'international', '2019–2021', 2, 0, NULL, 'English Wikipedia infobox, "Elliot Anderson" article', '2026-10-09'),
(912, NULL, 'Scotland U21', 'international', '2022', 1, 0, NULL, 'English Wikipedia infobox, "Elliot Anderson" article', '2026-10-09'),
(912, NULL, 'England U21', 'international', '2024–2025', 12, 2, NULL, 'English Wikipedia infobox, "Elliot Anderson" article', '2026-10-09'),
(912, 433, 'England', 'international', '2025–', 21, 0, NULL, 'English Wikipedia infobox, "Elliot Anderson" article', '2026-10-09');

-- Dan Ndoye (entity_id 913) -- Wikipedia: "Dan Ndoye"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(913, NULL, 'Lausanne-Sport II', 'club', '2018–2019', 21, 7, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, 19564, 'Lausanne-Sport', 'club', '2018–2020', 33, 8, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, 266, 'Nice', 'club', '2020–2022', 31, 1, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, 19564, '→ Lausanne-Sport (loan)', 'club', '2020', 12, 3, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, 19366, '→ Basel (loan)', 'club', '2021–2022', 29, 2, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, 19366, 'Basel', 'club', '2022–2023', 34, 5, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, 224, 'Bologna', 'club', '2023–2025', 62, 9, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, 198, 'Nottingham Forest', 'club', '2025–', 29, 2, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, NULL, 'Switzerland U18', 'international', '2017', 2, 0, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, NULL, 'Switzerland U19', 'international', '2018', 10, 3, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, NULL, 'Switzerland U21', 'international', '2019–2023', 26, 10, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09'),
(913, 472, 'Switzerland', 'international', '2022–', 41, 12, NULL, 'English Wikipedia infobox, "Dan Ndoye" article', '2026-10-09');

-- Omari Hutchinson (entity_id 914) -- Wikipedia: "Omari Hutchinson"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(914, 189, 'Chelsea', 'club', '2023–2024', 1, 0, NULL, 'English Wikipedia infobox, "Omari Hutchinson" article', '2026-10-09'),
(914, 307, '→ Ipswich Town (loan)', 'club', '2023–2024', 44, 10, NULL, 'English Wikipedia infobox, "Omari Hutchinson" article', '2026-10-09'),
(914, 307, 'Ipswich Town', 'club', '2024–2025', 31, 3, NULL, 'English Wikipedia infobox, "Omari Hutchinson" article', '2026-10-09'),
(914, 198, 'Nottingham Forest', 'club', '2025–', 31, 1, NULL, 'English Wikipedia infobox, "Omari Hutchinson" article', '2026-10-09'),
(914, 235, '→ AC Milan (loan)', 'club', '2026–', 1, 0, NULL, 'English Wikipedia infobox, "Omari Hutchinson" article', '2026-10-09'),
(914, NULL, 'England U17', 'international', '2020', 3, 0, NULL, 'English Wikipedia infobox, "Omari Hutchinson" article', '2026-10-09'),
(914, NULL, 'England U19', 'international', '2021', 1, 0, NULL, 'English Wikipedia infobox, "Omari Hutchinson" article', '2026-10-09'),
(914, NULL, 'Jamaica', 'international', '2023', 2, 0, NULL, 'English Wikipedia infobox, "Omari Hutchinson" article', '2026-10-09'),
(914, NULL, 'England U21', 'international', '2024–2025', 10, 3, NULL, 'English Wikipedia infobox, "Omari Hutchinson" article', '2026-10-09');

-- Illan Meslier (entity_id 915) -- Wikipedia: "Illan Meslier"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(915, NULL, 'Lorient II', 'club', '2017–2018', 17, 0, NULL, 'English Wikipedia infobox, "Illan Meslier" article', '2026-10-09'),
(915, 277, 'Lorient', 'club', '2018–2020', 28, 0, NULL, 'English Wikipedia infobox, "Illan Meslier" article', '2026-10-09'),
(915, 193, '→ Leeds United (loan)', 'club', '2019–2020', 10, 0, NULL, 'English Wikipedia infobox, "Illan Meslier" article', '2026-10-09'),
(915, 193, 'Leeds United', 'club', '2020–2026', 190, 0, NULL, 'English Wikipedia infobox, "Illan Meslier" article', '2026-10-09'),
(915, 183, 'Arsenal', 'club', '2026–', 0, 0, NULL, 'English Wikipedia infobox, "Illan Meslier" article', '2026-10-09'),
(915, NULL, 'France U18', 'international', '2018', 3, 0, NULL, 'English Wikipedia infobox, "Illan Meslier" article', '2026-10-09'),
(915, NULL, 'France U19', 'international', '2018', 5, 0, NULL, 'English Wikipedia infobox, "Illan Meslier" article', '2026-10-09'),
(915, NULL, 'France U20', 'international', '2019', 4, 0, NULL, 'English Wikipedia infobox, "Illan Meslier" article', '2026-10-09'),
(915, NULL, 'France U21', 'international', '2021–2023', 13, 0, NULL, 'English Wikipedia infobox, "Illan Meslier" article', '2026-10-09');

-- Wilfried Gnonto (entity_id 916) -- Wikipedia: "Wilfried Gnonto"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(916, NULL, 'Zürich II', 'club', '2020–2021', 3, 2, NULL, 'English Wikipedia infobox, "Wilfried Gnonto" article', '2026-10-09'),
(916, NULL, 'Zürich', 'club', '2020–2022', 65, 9, NULL, 'English Wikipedia infobox, "Wilfried Gnonto" article', '2026-10-09'),
(916, 193, 'Leeds United', 'club', '2022–', 126, 19, NULL, 'English Wikipedia infobox, "Wilfried Gnonto" article', '2026-10-09'),
(916, 228, '→ Fiorentina (loan)', 'club', '2026–', 3, 0, NULL, 'English Wikipedia infobox, "Wilfried Gnonto" article', '2026-10-09'),
(916, NULL, 'Italy U16', 'international', '2018–2019', 10, 1, NULL, 'English Wikipedia infobox, "Wilfried Gnonto" article', '2026-10-09'),
(916, NULL, 'Italy U17', 'international', '2019–2020', 10, 5, NULL, 'English Wikipedia infobox, "Wilfried Gnonto" article', '2026-10-09'),
(916, NULL, 'Italy U18', 'international', '2021', 1, 0, NULL, 'English Wikipedia infobox, "Wilfried Gnonto" article', '2026-10-09'),
(916, NULL, 'Italy U19', 'international', '2021–2022', 10, 5, NULL, 'English Wikipedia infobox, "Wilfried Gnonto" article', '2026-10-09'),
(916, NULL, 'Italy U21', 'international', '2023–2025', 17, 5, NULL, 'English Wikipedia infobox, "Wilfried Gnonto" article', '2026-10-09'),
(916, 445, 'Italy', 'international', '2022–2023', 13, 1, NULL, 'English Wikipedia infobox, "Wilfried Gnonto" article', '2026-10-09');

-- Ethan Ampadu (entity_id 917) -- Wikipedia: "Ethan Ampadu"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(917, 351, 'Exeter City', 'club', '2016–2017', 8, 0, NULL, 'English Wikipedia infobox, "Ethan Ampadu" article', '2026-10-09'),
(917, 189, 'Chelsea', 'club', '2017–2023', 1, 0, NULL, 'English Wikipedia infobox, "Ethan Ampadu" article', '2026-10-09'),
(917, 245, '→ RB Leipzig (loan)', 'club', '2019–2020', 3, 0, NULL, 'English Wikipedia infobox, "Ethan Ampadu" article', '2026-10-09'),
(917, 308, '→ Sheffield United (loan)', 'club', '2020–2021', 25, 0, NULL, 'English Wikipedia infobox, "Ethan Ampadu" article', '2026-10-09'),
(917, 19089, '→ Venezia (loan)', 'club', '2021–2022', 29, 0, NULL, 'English Wikipedia infobox, "Ethan Ampadu" article', '2026-10-09'),
(917, 19092, '→ Spezia (loan)', 'club', '2022–2023', 31, 0, NULL, 'English Wikipedia infobox, "Ethan Ampadu" article', '2026-10-09'),
(917, 193, 'Leeds United', 'club', '2023–', 113, 1, NULL, 'English Wikipedia infobox, "Ethan Ampadu" article', '2026-10-09'),
(917, NULL, 'Wales U17', 'international', '2015–2016', 6, 0, NULL, 'English Wikipedia infobox, "Ethan Ampadu" article', '2026-10-09'),
(917, NULL, 'Wales U19', 'international', '2016', 3, 0, NULL, 'English Wikipedia infobox, "Ethan Ampadu" article', '2026-10-09'),
(917, 475, 'Wales', 'international', '2017–', 67, 0, NULL, 'English Wikipedia infobox, "Ethan Ampadu" article', '2026-10-09');

-- Ao Tanaka (entity_id 918) -- Wikipedia: "Ao Tanaka"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(918, 19407, 'Kawasaki Frontale', 'club', '2017–2022', 79, 8, NULL, 'English Wikipedia infobox, "Ao Tanaka" article', '2026-10-09'),
(918, 19108, '→ Fortuna Düsseldorf (loan)', 'club', '2021–2022', 29, 1, NULL, 'English Wikipedia infobox, "Ao Tanaka" article', '2026-10-09'),
(918, 19108, 'Fortuna Düsseldorf', 'club', '2022–2024', 55, 8, NULL, 'English Wikipedia infobox, "Ao Tanaka" article', '2026-10-09'),
(918, 193, 'Leeds United', 'club', '2024–', 74, 8, NULL, 'English Wikipedia infobox, "Ao Tanaka" article', '2026-10-09'),
(918, NULL, 'Japan U23', 'international', '2019–2021', 18, 2, NULL, 'English Wikipedia infobox, "Ao Tanaka" article', '2026-10-09'),
(918, NULL, 'Japan', 'international', '2019–', 44, 8, NULL, 'English Wikipedia infobox, "Ao Tanaka" article', '2026-10-09');

-- Joel Piroe (entity_id 919) -- Wikipedia: "Joël Piroe"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(919, NULL, 'Jong PSV', 'club', '2016–2021', 54, 14, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, 284, 'PSV', 'club', '2019–2021', 11, 1, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, 18976, '→ Sparta Rotterdam (loan)', 'club', '2019–2020', 18, 2, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, 321, 'Swansea City', 'club', '2021–2023', 91, 41, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, 193, 'Leeds United', 'club', '2023–', 104, 32, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, 201, '→ West Ham United (loan)', 'club', '2026–', 7, 3, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, NULL, 'Netherlands U15', 'international', '2013–2014', 3, 0, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, NULL, 'Netherlands U16', 'international', '2015', 2, 1, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, NULL, 'Netherlands U18', 'international', '2016', 4, 0, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, NULL, 'Netherlands U19', 'international', '2017–2018', 13, 8, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, NULL, 'Netherlands U20', 'international', '2018–2019', 4, 1, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09'),
(919, NULL, 'Suriname', 'international', '2026–', 1, 0, NULL, 'English Wikipedia infobox, "Joël Piroe" article', '2026-10-09');

-- Dominic Calvert-Lewin (entity_id 920) -- Wikipedia: "Dominic Calvert-Lewin"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(920, 308, 'Sheffield United', 'club', '2014–2016', 11, 0, NULL, 'English Wikipedia infobox, "Dominic Calvert-Lewin" article', '2026-10-09'),
(920, NULL, '→ Stalybridge Celtic (loan)', 'club', '2014–2015', 5, 6, NULL, 'English Wikipedia infobox, "Dominic Calvert-Lewin" article', '2026-10-09'),
(920, 355, '→ Northampton Town (loan)', 'club', '2015–2016', 20, 5, NULL, 'English Wikipedia infobox, "Dominic Calvert-Lewin" article', '2026-10-09'),
(920, 191, 'Everton', 'club', '2016–2025', 239, 57, NULL, 'English Wikipedia infobox, "Dominic Calvert-Lewin" article', '2026-10-09'),
(920, 193, 'Leeds United', 'club', '2025–', 39, 17, NULL, 'English Wikipedia infobox, "Dominic Calvert-Lewin" article', '2026-10-09'),
(920, NULL, 'England U20', 'international', '2016–2017', 15, 6, NULL, 'English Wikipedia infobox, "Dominic Calvert-Lewin" article', '2026-10-09'),
(920, NULL, 'England U21', 'international', '2017–2019', 17, 7, NULL, 'English Wikipedia infobox, "Dominic Calvert-Lewin" article', '2026-10-09'),
(920, 433, 'England', 'international', '2020–', 14, 4, NULL, 'English Wikipedia infobox, "Dominic Calvert-Lewin" article', '2026-10-09');

-- Anton Stach (entity_id 921) -- Wikipedia: "Anton Stach"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(921, NULL, 'VfL Osnabrück II', 'club', '2017', 1, 0, NULL, 'English Wikipedia infobox, "Anton Stach" article', '2026-10-09'),
(921, NULL, 'SSV Jeddeloh', 'club', '2017–2018', 23, 4, NULL, 'English Wikipedia infobox, "Anton Stach" article', '2026-10-09'),
(921, NULL, 'VfL Wolfsburg II', 'club', '2018–2020', 40, 6, NULL, 'English Wikipedia infobox, "Anton Stach" article', '2026-10-09'),
(921, 19115, 'Greuther Fürth', 'club', '2020–2021', 30, 1, NULL, 'English Wikipedia infobox, "Anton Stach" article', '2026-10-09'),
(921, 252, 'Mainz 05', 'club', '2021–2023', 61, 2, NULL, 'English Wikipedia infobox, "Anton Stach" article', '2026-10-09'),
(921, 250, 'TSG Hoffenheim', 'club', '2023–2025', 61, 3, NULL, 'English Wikipedia infobox, "Anton Stach" article', '2026-10-09'),
(921, 193, 'Leeds United', 'club', '2025–', 30, 6, NULL, 'English Wikipedia infobox, "Anton Stach" article', '2026-10-09'),
(921, NULL, 'Germany U21', 'international', '2021', 5, 0, NULL, 'English Wikipedia infobox, "Anton Stach" article', '2026-10-09'),
(921, NULL, 'Germany Olympic', 'international', '2021', 3, 0, NULL, 'English Wikipedia infobox, "Anton Stach" article', '2026-10-09'),
(921, 439, 'Germany', 'international', '2022–', 5, 0, NULL, 'English Wikipedia infobox, "Anton Stach" article', '2026-10-09');

-- Lukas Nmecha (entity_id 922) -- Wikipedia: "Lukas Nmecha"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(922, 195, 'Manchester City', 'club', '2017–2021', 2, 0, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, 343, '→ Preston North End (loan)', 'club', '2018–2019', 41, 3, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, 256, '→ VfL Wolfsburg (loan)', 'club', '2019–2020', 6, 0, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, 312, '→ Middlesbrough (loan)', 'club', '2020', 11, 0, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, 293, '→ Anderlecht (loan)', 'club', '2020–2021', 37, 18, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, 256, 'VfL Wolfsburg', 'club', '2021–2025', 63, 16, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, 193, 'Leeds United', 'club', '2025–', 31, 6, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, NULL, 'England U16', 'international', '2013', 2, 0, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, NULL, 'England U17', 'international', '2014–2015', 10, 2, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, NULL, 'England U18', 'international', '2016', 4, 2, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, NULL, 'England U19', 'international', '2016–2017', 11, 3, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, NULL, 'England U20', 'international', '2018', 1, 1, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, NULL, 'England U21', 'international', '2018', 3, 0, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, NULL, 'Germany U21', 'international', '2019–2021', 20, 12, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09'),
(922, 439, 'Germany', 'international', '2021–2022', 7, 0, NULL, 'English Wikipedia infobox, "Lukas Nmecha" article', '2026-10-09');

-- Noah Okafor (entity_id 923) -- Wikipedia: "Noah Okafor"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(923, 19366, 'Basel', 'club', '2018–2020', 39, 3, NULL, 'English Wikipedia infobox, "Noah Okafor" article', '2026-10-09'),
(923, 294, 'Red Bull Salzburg', 'club', '2020–2023', 71, 25, NULL, 'English Wikipedia infobox, "Noah Okafor" article', '2026-10-09'),
(923, 235, 'AC Milan', 'club', '2023–2025', 39, 7, NULL, 'English Wikipedia infobox, "Noah Okafor" article', '2026-10-09'),
(923, 236, '→ Napoli (loan)', 'club', '2025', 4, 0, NULL, 'English Wikipedia infobox, "Noah Okafor" article', '2026-10-09'),
(923, 193, 'Leeds United', 'club', '2025–', 32, 9, NULL, 'English Wikipedia infobox, "Noah Okafor" article', '2026-10-09'),
(923, NULL, 'Switzerland U15', 'international', '2014–2015', 3, 0, NULL, 'English Wikipedia infobox, "Noah Okafor" article', '2026-10-09'),
(923, NULL, 'Switzerland U17', 'international', '2016–2017', 7, 3, NULL, 'English Wikipedia infobox, "Noah Okafor" article', '2026-10-09'),
(923, NULL, 'Switzerland U18', 'international', '2017–2018', 1, 0, NULL, 'English Wikipedia infobox, "Noah Okafor" article', '2026-10-09'),
(923, NULL, 'Switzerland U19', 'international', '2018–2019', 7, 1, NULL, 'English Wikipedia infobox, "Noah Okafor" article', '2026-10-09'),
(923, 472, 'Switzerland', 'international', '2019–2026', 26, 2, NULL, 'English Wikipedia infobox, "Noah Okafor" article', '2026-10-09');

-- Jayden Bogle (entity_id 924) -- Wikipedia: "Jayden Bogle"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(924, 316, 'Derby County', 'club', '2018–2020', 77, 3, NULL, 'English Wikipedia infobox, "Jayden Bogle" article', '2026-10-09'),
(924, 308, 'Sheffield United', 'club', '2020–2024', 88, 10, NULL, 'English Wikipedia infobox, "Jayden Bogle" article', '2026-10-09'),
(924, 193, 'Leeds United', 'club', '2024–', 82, 8, NULL, 'English Wikipedia infobox, "Jayden Bogle" article', '2026-10-09'),
(924, NULL, 'England U20', 'international', '2019', 4, 0, NULL, 'English Wikipedia infobox, "Jayden Bogle" article', '2026-10-09');

-- Pascal Struijk (entity_id 925) -- Wikipedia: "Pascal Struijk"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(925, 193, 'Leeds United', 'club', '2018–2026', 182, 12, NULL, 'English Wikipedia infobox, "Pascal Struijk" article', '2026-10-09'),
(925, 187, 'Brighton & Hove Albion', 'club', '2026–', 3, 0, NULL, 'English Wikipedia infobox, "Pascal Struijk" article', '2026-10-09'),
(925, NULL, 'Netherlands U17', 'international', '2016', 3, 0, NULL, 'English Wikipedia infobox, "Pascal Struijk" article', '2026-10-09');

-- Josh Cullen (entity_id 926) -- Wikipedia: "Josh Cullen (footballer, born 1996)"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(926, 201, 'West Ham United', 'club', '2015–2020', 3, 0, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, 348, '→ Bradford City (loan)', 'club', '2016', 15, 0, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, 348, '→ Bradford City (loan)', 'club', '2016–2017', 40, 1, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, 326, '→ Bolton Wanderers (loan)', 'club', '2017–2018', 12, 0, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, 366, '→ Charlton Athletic (loan)', 'club', '2018–2019', 29, 1, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, 366, '→ Charlton Athletic (loan)', 'club', '2019–2020', 34, 1, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, 293, 'Anderlecht', 'club', '2020–2022', 67, 1, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, 188, 'Burnley', 'club', '2022–', 130, 6, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, NULL, 'England U16', 'international', '2011', 1, 0, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, NULL, 'Republic of Ireland U19', 'international', '2014–2015', 3, 0, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, NULL, 'Republic of Ireland U21', 'international', '2015–2018', 19, 1, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09'),
(926, 462, 'Republic of Ireland', 'international', '2019–', 47, 0, NULL, 'English Wikipedia infobox, "Josh Cullen (footballer, born 1996)" article', '2026-10-09');

-- Zian Flemming (entity_id 927) -- Wikipedia: "Zian Flemming"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(927, NULL, 'Jong Ajax', 'club', '2017–2018', 25, 6, NULL, 'English Wikipedia infobox, "Zian Flemming" article', '2026-10-09'),
(927, 18982, 'PEC Zwolle', 'club', '2018–2020', 29, 2, NULL, 'English Wikipedia infobox, "Zian Flemming" article', '2026-10-09'),
(927, 18975, '→ NEC (loan)', 'club', '2019–2020', 24, 13, NULL, 'English Wikipedia infobox, "Zian Flemming" article', '2026-10-09'),
(927, 18980, 'Fortuna Sittard', 'club', '2020–2022', 61, 24, NULL, 'English Wikipedia infobox, "Zian Flemming" article', '2026-10-09'),
(927, 342, 'Millwall', 'club', '2022–2025', 89, 22, NULL, 'English Wikipedia infobox, "Zian Flemming" article', '2026-10-09'),
(927, 188, '→ Burnley (loan)', 'club', '2024–2025', 35, 12, NULL, 'English Wikipedia infobox, "Zian Flemming" article', '2026-10-09'),
(927, 188, 'Burnley', 'club', '2025–2026', 31, 13, NULL, 'English Wikipedia infobox, "Zian Flemming" article', '2026-10-09'),
(927, 307, 'Ipswich Town', 'club', '2026–', 2, 1, NULL, 'English Wikipedia infobox, "Zian Flemming" article', '2026-10-09');

-- Jaidon Anthony (entity_id 928) -- Wikipedia: "Jaidon Anthony"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(928, 185, 'Bournemouth', 'club', '2020–2025', 83, 10, NULL, 'English Wikipedia infobox, "Jaidon Anthony" article', '2026-10-09'),
(928, NULL, '→ Weymouth (loan)', 'club', '2020', 3, 0, NULL, 'English Wikipedia infobox, "Jaidon Anthony" article', '2026-10-09'),
(928, 193, '→ Leeds United (loan)', 'club', '2023–2024', 31, 1, NULL, 'English Wikipedia infobox, "Jaidon Anthony" article', '2026-10-09'),
(928, 188, '→ Burnley (loan)', 'club', '2024–2025', 43, 8, NULL, 'English Wikipedia infobox, "Jaidon Anthony" article', '2026-10-09'),
(928, 188, 'Burnley', 'club', '2025–2026', 37, 8, NULL, 'English Wikipedia infobox, "Jaidon Anthony" article', '2026-10-09'),
(928, 186, 'Brentford', 'club', '2026–', 5, 1, NULL, 'English Wikipedia infobox, "Jaidon Anthony" article', '2026-10-09');

-- Lyle Foster (entity_id 929) -- Wikipedia: "Lyle Foster"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(929, NULL, 'Orlando Pirates', 'club', '2017–2019', 11, 1, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, NULL, 'Monaco II', 'club', '2019', 8, 3, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, 264, 'Monaco', 'club', '2019–2020', 2, 0, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, 19001, '→ Cercle Brugge (loan)', 'club', '2019–2020', 18, 1, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, NULL, 'Vitória de Guimarães', 'club', '2020–2022', 5, 0, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, NULL, 'Vitória de Guimarães B', 'club', '2021', 4, 0, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, 19520, '→ Westerlo (loan)', 'club', '2021–2022', 23, 4, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, 19520, 'Westerlo', 'club', '2022–2023', 21, 8, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, 188, 'Burnley', 'club', '2023–', 89, 11, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, 19048, '→ Houston Dynamo (loan)', 'club', '2026–', 1, 0, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, NULL, 'South Africa U17', 'international', '2016', 4, 1, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, NULL, 'South Africa U20', 'international', '2017–2019', 7, 5, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, NULL, 'South Africa B', 'international', '2018', 3, 0, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, NULL, 'South Africa U23', 'international', '2019–2021', 6, 0, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09'),
(929, 521, 'South Africa', 'international', '2020–', 30, 11, NULL, 'English Wikipedia infobox, "Lyle Foster" article', '2026-10-09');

-- Martin Dubravka (entity_id 930) -- Wikipedia: "Martin Dúbravka"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(930, NULL, 'Žilina', 'club', '2007–2014', 97, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, NULL, 'Esbjerg', 'club', '2014–2016', 66, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, NULL, 'Slovan Liberec', 'club', '2016–2017', 28, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, 302, 'Sparta Prague', 'club', '2017–2018', 11, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, 197, '→ Newcastle United (loan)', 'club', '2018', 12, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, 197, 'Newcastle United', 'club', '2018–2025', 162, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, 196, '→ Manchester United (loan)', 'club', '2022–2023', 0, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, 188, 'Burnley', 'club', '2025–2026', 35, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, 200, 'Tottenham Hotspur', 'club', '2026–', 0, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, NULL, 'Slovakia U19', 'international', '2007–2008', 6, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, NULL, 'Slovakia U21', 'international', '2009–2010', 10, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09'),
(930, 468, 'Slovakia', 'international', '2014–', 61, 0, NULL, 'English Wikipedia infobox, "Martin Dúbravka" article', '2026-10-09');

-- Granit Xhaka (entity_id 931) -- Wikipedia: "Granit Xhaka"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(931, 19366, 'Basel', 'club', '2010–2012', 42, 1, NULL, 'English Wikipedia infobox, "Granit Xhaka" article', '2026-10-09'),
(931, 254, 'Borussia Mönchengladbach', 'club', '2012–2016', 108, 6, NULL, 'English Wikipedia infobox, "Granit Xhaka" article', '2026-10-09'),
(931, 183, 'Arsenal', 'club', '2016–2023', 225, 17, NULL, 'English Wikipedia infobox, "Granit Xhaka" article', '2026-10-09'),
(931, 246, 'Bayer Leverkusen', 'club', '2023–2025', 66, 5, NULL, 'English Wikipedia infobox, "Granit Xhaka" article', '2026-10-09'),
(931, 199, 'Sunderland', 'club', '2025–', 39, 1, NULL, 'English Wikipedia infobox, "Granit Xhaka" article', '2026-10-09'),
(931, NULL, 'Switzerland U17', 'international', '2008–2009', 13, 1, NULL, 'English Wikipedia infobox, "Granit Xhaka" article', '2026-10-09'),
(931, NULL, 'Switzerland U18', 'international', '2009–2010', 3, 2, NULL, 'English Wikipedia infobox, "Granit Xhaka" article', '2026-10-09'),
(931, NULL, 'Switzerland U19', 'international', '2010–2011', 12, 3, NULL, 'English Wikipedia infobox, "Granit Xhaka" article', '2026-10-09'),
(931, NULL, 'Switzerland U21', 'international', '2010–2011', 5, 0, NULL, 'English Wikipedia infobox, "Granit Xhaka" article', '2026-10-09'),
(931, 472, 'Switzerland', 'international', '2011–', 152, 18, NULL, 'English Wikipedia infobox, "Granit Xhaka" article', '2026-10-09');

-- Habib Diarra (entity_id 932) -- Wikipedia: "Habib Diarra"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(932, 269, 'Strasbourg', 'club', '2021–2025', 92, 9, NULL, 'English Wikipedia infobox, "Habib Diarra" article', '2026-10-09'),
(932, NULL, '→ Strasbourg B', 'club', '2021–2022', 7, 1, NULL, 'English Wikipedia infobox, "Habib Diarra" article', '2026-10-09'),
(932, 199, 'Sunderland', 'club', '2025–', 21, 2, NULL, 'English Wikipedia infobox, "Habib Diarra" article', '2026-10-09'),
(932, NULL, 'France U16', 'international', '2020', 3, 1, NULL, 'English Wikipedia infobox, "Habib Diarra" article', '2026-10-09'),
(932, NULL, 'France U18', 'international', '2021', 5, 1, NULL, 'English Wikipedia infobox, "Habib Diarra" article', '2026-10-09'),
(932, NULL, 'France U19', 'international', '2022', 3, 0, NULL, 'English Wikipedia infobox, "Habib Diarra" article', '2026-10-09'),
(932, NULL, 'France U21', 'international', '2023', 3, 0, NULL, 'English Wikipedia infobox, "Habib Diarra" article', '2026-10-09'),
(932, 517, 'Senegal', 'international', '2024–', 24, 6, NULL, 'English Wikipedia infobox, "Habib Diarra" article', '2026-10-09');

-- Wilson Isidor (entity_id 933) -- Wikipedia: "Wilson Isidor"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(933, NULL, 'Rennes II', 'club', '2017–2018', 4, 0, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, NULL, 'Monaco II', 'club', '2018–2022', 21, 5, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, 264, 'Monaco', 'club', '2018–2022', 5, 0, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, 19502, '→ Laval (loan)', 'club', '2019–2020', 14, 1, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, NULL, '→ Laval II (loan)', 'club', '2019–2020', 4, 3, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, NULL, '→ Bastia-Borgo (loan)', 'club', '2020–2021', 29, 15, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, 19507, 'Lokomotiv Moscow', 'club', '2022–2024', 35, 16, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, NULL, '→ Zenit Saint Petersburg (loan)', 'club', '2023–2024', 14, 2, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, NULL, 'Zenit Saint Petersburg', 'club', '2024–2025', 3, 1, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, 199, '→ Sunderland (loan)', 'club', '2024–2025', 26, 9, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, 199, 'Sunderland', 'club', '2025–', 54, 10, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, NULL, 'France U17', 'international', '2017', 6, 0, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, NULL, 'France U18', 'international', '2017–2018', 7, 4, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, NULL, 'France U19', 'international', '2018–2019', 8, 8, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, NULL, 'France U20', 'international', '2019', 2, 0, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09'),
(933, NULL, 'Haiti', 'international', '2026–', 11, 6, NULL, 'English Wikipedia infobox, "Wilson Isidor" article', '2026-10-09');

-- Eliezer Mayenda (entity_id 934) -- Wikipedia: "Eliezer Mayenda"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(934, 19063, 'Sochaux', 'club', '2021–2023', 15, 1, NULL, 'English Wikipedia infobox, "Eliezer Mayenda" article', '2026-10-09'),
(934, NULL, 'Sochaux B', 'club', '2022', 14, 4, NULL, 'English Wikipedia infobox, "Eliezer Mayenda" article', '2026-10-09'),
(934, 199, 'Sunderland', 'club', '2023–2026', 65, 10, NULL, 'English Wikipedia infobox, "Eliezer Mayenda" article', '2026-10-09'),
(934, 395, '→ Hibernian (loan)', 'club', '2024', 2, 0, NULL, 'English Wikipedia infobox, "Eliezer Mayenda" article', '2026-10-09'),
(934, 268, 'Rennes', 'club', '2026–', 0, 0, NULL, 'English Wikipedia infobox, "Eliezer Mayenda" article', '2026-10-09'),
(934, NULL, 'Spain U17', 'international', '2022', 3, 0, NULL, 'English Wikipedia infobox, "Eliezer Mayenda" article', '2026-10-09'),
(934, NULL, 'Spain U21', 'international', '2025–', 10, 2, NULL, 'English Wikipedia infobox, "Eliezer Mayenda" article', '2026-10-09');

-- Robin Roefs (entity_id 935) -- Wikipedia: "Robin Roefs"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(935, 18975, 'NEC', 'club', '2019–2025', 37, 0, NULL, 'English Wikipedia infobox, "Robin Roefs" article', '2026-10-09'),
(935, 199, 'Sunderland', 'club', '2025–', 40, 0, NULL, 'English Wikipedia infobox, "Robin Roefs" article', '2026-10-09'),
(935, NULL, 'Netherlands U16', 'international', '2019', 2, 0, NULL, 'English Wikipedia infobox, "Robin Roefs" article', '2026-10-09'),
(935, NULL, 'Netherlands U17', 'international', '2019', 3, 0, NULL, 'English Wikipedia infobox, "Robin Roefs" article', '2026-10-09'),
(935, NULL, 'Netherlands U19', 'international', '2020–2022', 7, 0, NULL, 'English Wikipedia infobox, "Robin Roefs" article', '2026-10-09'),
(935, NULL, 'Netherlands U21', 'international', '2024–2025', 11, 0, NULL, 'English Wikipedia infobox, "Robin Roefs" article', '2026-10-09'),
(935, 456, 'Netherlands', 'international', '2026–', 1, 0, NULL, 'English Wikipedia infobox, "Robin Roefs" article', '2026-10-09');

-- Reinildo (entity_id 936) -- Wikipedia: "Reinildo Mandava"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(936, NULL, 'Ferroviário da Beira', 'club', '2012–2014', NULL, NULL, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09'),
(936, NULL, 'GD Maputo', 'club', '2014–2015', NULL, NULL, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09'),
(936, NULL, 'Benfica B', 'club', '2015–2018', 1, 0, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09'),
(936, NULL, '→ Fafe (loan)', 'club', '2017', 16, 1, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09'),
(936, NULL, '→ Sporting Covilhã (loan)', 'club', '2017–2018', 30, 4, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09'),
(936, NULL, 'Belenenses SAD', 'club', '2018–2019', 16, 0, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09'),
(936, 265, '→ Lille (loan)', 'club', '2019', 3, 0, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09'),
(936, 265, 'Lille', 'club', '2019–2022', 63, 1, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09'),
(936, 205, 'Atlético Madrid', 'club', '2022–2025', 74, 2, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09'),
(936, 199, 'Sunderland', 'club', '2025–', 29, 0, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09'),
(936, 511, 'Mozambique', 'international', '2013–2026', 56, 5, NULL, 'English Wikipedia infobox, "Reinildo Mandava" article', '2026-10-09');

-- Omar Alderete (entity_id 937) -- Wikipedia: "Omar Alderete"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(937, 87, 'Cerro Porteño', 'club', '2016–2018', 17, 1, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, NULL, '→ Gimnasia y Esgrima (loan)', 'club', '2017–2018', 22, 1, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, 12, 'Huracán', 'club', '2018–2019', 8, 1, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, 19366, 'Basel', 'club', '2019–2020', 31, 2, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, 19058, 'Hertha BSC', 'club', '2020–2023', 17, 0, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, 221, '→ Valencia (loan)', 'club', '2021–2022', 29, 2, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, 210, '→ Getafe (loan)', 'club', '2022–2023', 25, 1, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, 210, 'Getafe', 'club', '2023–2025', 65, 1, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, 199, 'Sunderland', 'club', '2025–', 34, 1, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, NULL, 'Paraguay U17', 'international', '2013', 8, 0, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, NULL, 'Paraguay U20', 'international', '2015', 7, 0, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, NULL, 'Paraguay U23', 'international', '2016', 4, 2, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09'),
(937, 19159, 'Paraguay', 'international', '2018–', 42, 3, NULL, 'English Wikipedia infobox, "Omar Alderete" article', '2026-10-09');

-- Nordi Mukiele (entity_id 938) -- Wikipedia: "Nordi Mukiele"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(938, NULL, 'Laval B', 'club', '2014–2016', 24, 1, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, 19502, 'Laval', 'club', '2014–2017', 34, 2, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, 19120, 'Montpellier', 'club', '2017–2018', 50, 0, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, 245, 'RB Leipzig', 'club', '2018–2022', 100, 8, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, 261, 'Paris Saint-Germain', 'club', '2022–2025', 35, 0, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, 246, '→ Bayer Leverkusen (loan)', 'club', '2024–2025', 15, 1, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, 199, 'Sunderland', 'club', '2025–', 36, 3, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, NULL, 'France U18', 'international', '2015', 2, 0, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, NULL, 'France U19', 'international', '2016', 1, 0, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, NULL, 'France U20', 'international', '2016–2017', 6, 0, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, NULL, 'France U21', 'international', '2017–2019', 6, 0, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09'),
(938, 437, 'France', 'international', '2021', 1, 0, NULL, 'English Wikipedia infobox, "Nordi Mukiele" article', '2026-10-09');

-- Antonio Rudiger (entity_id 939) -- Wikipedia: "Antonio Rüdiger"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(939, NULL, 'VfB Stuttgart II', 'club', '2011–2015', 22, 3, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09'),
(939, 247, 'VfB Stuttgart', 'club', '2012–2016', 66, 2, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09'),
(939, 239, '→ Roma (loan)', 'club', '2015–2016', 30, 2, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09'),
(939, 239, 'Roma', 'club', '2016–2017', 26, 0, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09'),
(939, 189, 'Chelsea', 'club', '2017–2022', 133, 9, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09'),
(939, 217, 'Real Madrid', 'club', '2022–', 115, 3, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09'),
(939, NULL, 'Germany U18', 'international', '2010–2011', 8, 4, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09'),
(939, NULL, 'Germany U19', 'international', '2011–2012', 14, 1, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09'),
(939, NULL, 'Germany U20', 'international', '2012', 2, 0, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09'),
(939, NULL, 'Germany U21', 'international', '2012–2014', 10, 1, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09'),
(939, 439, 'Germany', 'international', '2014–2026', 86, 3, NULL, 'English Wikipedia infobox, "Antonio Rüdiger" article', '2026-10-09');

-- David Alaba (entity_id 940) -- Wikipedia: "David Alaba"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(940, NULL, 'Austria Wien II', 'club', '2007–2008', 5, 0, NULL, 'English Wikipedia infobox, "David Alaba" article', '2026-10-09'),
(940, NULL, 'Bayern Munich II', 'club', '2009–2010', 33, 1, NULL, 'English Wikipedia infobox, "David Alaba" article', '2026-10-09'),
(940, 243, 'Bayern Munich', 'club', '2010–2021', 281, 22, NULL, 'English Wikipedia infobox, "David Alaba" article', '2026-10-09'),
(940, 250, '→ TSG Hoffenheim (loan)', 'club', '2011', 17, 2, NULL, 'English Wikipedia infobox, "David Alaba" article', '2026-10-09'),
(940, 217, 'Real Madrid', 'club', '2021–2026', 85, 3, NULL, 'English Wikipedia infobox, "David Alaba" article', '2026-10-09'),
(940, 242, 'Udinese', 'club', '2026–', 0, 0, NULL, 'English Wikipedia infobox, "David Alaba" article', '2026-10-09'),
(940, NULL, 'Austria U17', 'international', '2007–2009', 20, 5, NULL, 'English Wikipedia infobox, "David Alaba" article', '2026-10-09'),
(940, NULL, 'Austria U19', 'international', '2010', 5, 1, NULL, 'English Wikipedia infobox, "David Alaba" article', '2026-10-09'),
(940, NULL, 'Austria U21', 'international', '2009–2010', 5, 0, NULL, 'English Wikipedia infobox, "David Alaba" article', '2026-10-09'),
(940, 423, 'Austria', 'international', '2009–2026', 117, 15, NULL, 'English Wikipedia infobox, "David Alaba" article', '2026-10-09');

-- Eder Militao (entity_id 941) -- Wikipedia: "Éder Militão"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(941, 37, 'São Paulo', 'club', '2017–2018', 49, 5, NULL, 'English Wikipedia infobox, "Éder Militão" article', '2026-10-09'),
(941, 279, 'Porto', 'club', '2018–2019', 29, 3, NULL, 'English Wikipedia infobox, "Éder Militão" article', '2026-10-09'),
(941, 217, 'Real Madrid', 'club', '2019–', 134, 10, NULL, 'English Wikipedia infobox, "Éder Militão" article', '2026-10-09'),
(941, NULL, 'Brazil U17', 'international', '2015', 5, 0, NULL, 'English Wikipedia infobox, "Éder Militão" article', '2026-10-09'),
(941, 19157, 'Brazil', 'international', '2018–', 38, 2, NULL, 'English Wikipedia infobox, "Éder Militão" article', '2026-10-09');

-- Ferland Mendy (entity_id 942) -- Wikipedia: "Ferland Mendy"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(942, NULL, 'Le Havre II', 'club', '2013–2016', 56, 1, NULL, 'English Wikipedia infobox, "Ferland Mendy" article', '2026-10-09'),
(942, 275, 'Le Havre', 'club', '2015–2017', 47, 2, NULL, 'English Wikipedia infobox, "Ferland Mendy" article', '2026-10-09'),
(942, 263, 'Lyon', 'club', '2017–2019', 57, 2, NULL, 'English Wikipedia infobox, "Ferland Mendy" article', '2026-10-09'),
(942, 217, 'Real Madrid', 'club', '2019–', 133, 4, NULL, 'English Wikipedia infobox, "Ferland Mendy" article', '2026-10-09'),
(942, 437, 'France', 'international', '2018–', 10, 0, NULL, 'English Wikipedia infobox, "Ferland Mendy" article', '2026-10-09');

-- Dani Carvajal (entity_id 943) -- Wikipedia: "Dani Carvajal"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(943, NULL, 'Real Madrid B', 'club', '2010–2012', 68, 3, NULL, 'English Wikipedia infobox, "Dani Carvajal" article', '2026-10-09'),
(943, 246, 'Bayer Leverkusen', 'club', '2012–2013', 32, 1, NULL, 'English Wikipedia infobox, "Dani Carvajal" article', '2026-10-09'),
(943, 217, 'Real Madrid', 'club', '2013–2026', 303, 10, NULL, 'English Wikipedia infobox, "Dani Carvajal" article', '2026-10-09'),
(943, NULL, 'Spain U19', 'international', '2010–2011', 11, 0, NULL, 'English Wikipedia infobox, "Dani Carvajal" article', '2026-10-09'),
(943, NULL, 'Spain U21', 'international', '2012–2014', 10, 1, NULL, 'English Wikipedia infobox, "Dani Carvajal" article', '2026-10-09'),
(943, 470, 'Spain', 'international', '2014–', 52, 1, NULL, 'English Wikipedia infobox, "Dani Carvajal" article', '2026-10-09');

-- Alvaro Carreras (entity_id 944) -- Wikipedia: "Álvaro Carreras"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(944, 196, 'Manchester United', 'club', '2022–2024', 0, 0, NULL, 'English Wikipedia infobox, "Álvaro Carreras" article', '2026-10-09'),
(944, 343, '→ Preston North End (loan)', 'club', '2022–2023', 39, 0, NULL, 'English Wikipedia infobox, "Álvaro Carreras" article', '2026-10-09'),
(944, 410, '→ Granada (loan)', 'club', '2023–2024', 13, 0, NULL, 'English Wikipedia infobox, "Álvaro Carreras" article', '2026-10-09'),
(944, 280, '→ Benfica (loan)', 'club', '2024', 11, 1, NULL, 'English Wikipedia infobox, "Álvaro Carreras" article', '2026-10-09'),
(944, 280, 'Benfica', 'club', '2024–2025', 32, 3, NULL, 'English Wikipedia infobox, "Álvaro Carreras" article', '2026-10-09'),
(944, 217, 'Real Madrid', 'club', '2025–', 32, 3, NULL, 'English Wikipedia infobox, "Álvaro Carreras" article', '2026-10-09'),
(944, NULL, 'Spain U19', 'international', '2021', 2, 0, NULL, 'English Wikipedia infobox, "Álvaro Carreras" article', '2026-10-09'),
(944, NULL, 'Spain U21', 'international', '2023–2024', 9, 0, NULL, 'English Wikipedia infobox, "Álvaro Carreras" article', '2026-10-09'),
(944, NULL, 'Galicia', 'international', '2024', 1, 0, NULL, 'English Wikipedia infobox, "Álvaro Carreras" article', '2026-10-09');

-- Aurelien Tchouameni (entity_id 945) -- Wikipedia: "Aurélien Tchouaméni"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(945, NULL, 'Bordeaux II', 'club', '2017–2018', 16, 3, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09'),
(945, 19062, 'Bordeaux', 'club', '2018–2020', 25, 0, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09'),
(945, 264, 'Monaco', 'club', '2020–2022', 74, 5, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09'),
(945, 217, 'Real Madrid', 'club', '2022–', 128, 4, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09'),
(945, NULL, 'France U16', 'international', '2015–2016', 11, 0, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09'),
(945, NULL, 'France U17', 'international', '2016–2017', 14, 0, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09'),
(945, NULL, 'France U18', 'international', '2017–2018', 11, 1, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09'),
(945, NULL, 'France U19', 'international', '2018', 7, 0, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09'),
(945, NULL, 'France U20', 'international', '2019', 5, 0, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09'),
(945, NULL, 'France U21', 'international', '2021', 4, 0, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09'),
(945, 437, 'France', 'international', '2021–', 50, 3, NULL, 'English Wikipedia infobox, "Aurélien Tchouaméni" article', '2026-10-09');

-- Eduardo Camavinga (entity_id 946) -- Wikipedia: "Eduardo Camavinga"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(946, NULL, 'Rennes II', 'club', '2018–2019', 13, 4, NULL, 'English Wikipedia infobox, "Eduardo Camavinga" article', '2026-10-09'),
(946, 268, 'Rennes', 'club', '2019–2021', 71, 2, NULL, 'English Wikipedia infobox, "Eduardo Camavinga" article', '2026-10-09'),
(946, 217, 'Real Madrid', 'club', '2021–', 148, 4, NULL, 'English Wikipedia infobox, "Eduardo Camavinga" article', '2026-10-09'),
(946, NULL, 'France U21', 'international', '2019–2022', 13, 2, NULL, 'English Wikipedia infobox, "Eduardo Camavinga" article', '2026-10-09'),
(946, 437, 'France', 'international', '2020–', 33, 2, NULL, 'English Wikipedia infobox, "Eduardo Camavinga" article', '2026-10-09');

-- Arda Guler (entity_id 947) -- Wikipedia: "Arda Güler"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(947, 290, 'Fenerbahçe', 'club', '2021–2023', 32, 7, NULL, 'English Wikipedia infobox, "Arda Güler" article', '2026-10-09'),
(947, 217, 'Real Madrid', 'club', '2023–', 78, 14, NULL, 'English Wikipedia infobox, "Arda Güler" article', '2026-10-09'),
(947, NULL, 'Turkey U17', 'international', '2021–2022', 10, 4, NULL, 'English Wikipedia infobox, "Arda Güler" article', '2026-10-09'),
(947, 473, 'Turkey', 'international', '2022–', 36, 7, NULL, 'English Wikipedia infobox, "Arda Güler" article', '2026-10-09');

-- Brahim Diaz (entity_id 948) -- Wikipedia: "Brahim Díaz"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(948, 195, 'Manchester City', 'club', '2016–2019', 5, 0, NULL, 'English Wikipedia infobox, "Brahim Díaz" article', '2026-10-09'),
(948, 217, 'Real Madrid', 'club', '2019–', 110, 14, NULL, 'English Wikipedia infobox, "Brahim Díaz" article', '2026-10-09'),
(948, 235, '→ AC Milan (loan)', 'club', '2020–2023', 91, 13, NULL, 'English Wikipedia infobox, "Brahim Díaz" article', '2026-10-09'),
(948, NULL, 'Spain U17', 'international', '2016–2017', 10, 3, NULL, 'English Wikipedia infobox, "Brahim Díaz" article', '2026-10-09'),
(948, NULL, 'Spain U19', 'international', '2016–2018', 10, 1, NULL, 'English Wikipedia infobox, "Brahim Díaz" article', '2026-10-09'),
(948, NULL, 'Spain U21', 'international', '2017–2021', 8, 2, NULL, 'English Wikipedia infobox, "Brahim Díaz" article', '2026-10-09'),
(948, 470, 'Spain', 'international', '2021', 1, 1, NULL, 'English Wikipedia infobox, "Brahim Díaz" article', '2026-10-09'),
(948, 510, 'Morocco', 'international', '2024–', 34, 15, NULL, 'English Wikipedia infobox, "Brahim Díaz" article', '2026-10-09');

-- Endrick (entity_id 949) -- Wikipedia: "Endrick"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(949, 30, 'Palmeiras', 'club', '2022–2024', 60, 15, NULL, 'English Wikipedia infobox, "Endrick" article', '2026-10-09'),
(949, 217, 'Real Madrid', 'club', '2024–', 24, 1, NULL, 'English Wikipedia infobox, "Endrick" article', '2026-10-09'),
(949, 263, '→ Lyon (loan)', 'club', '2026', 16, 5, NULL, 'English Wikipedia infobox, "Endrick" article', '2026-10-09'),
(949, NULL, 'Brazil U17', 'international', '2022', 4, 5, NULL, 'English Wikipedia infobox, "Endrick" article', '2026-10-09'),
(949, NULL, 'Brazil U23', 'international', '2024–', 7, 2, NULL, 'English Wikipedia infobox, "Endrick" article', '2026-10-09'),
(949, 19157, 'Brazil', 'international', '2023–', 24, 4, NULL, 'English Wikipedia infobox, "Endrick" article', '2026-10-09');

-- Gonzalo Garcia (entity_id 950) -- Wikipedia: "Gonzalo García (footballer, born 2004)"
INSERT INTO player_career_stats (player_id, team_id, team_name_raw, competition_type, years_display, appearances, goals, scope_note, source, verified_at) VALUES
(950, NULL, 'Real Madrid B', 'club', '2022–2025', 70, 30, NULL, 'English Wikipedia infobox, "Gonzalo García (footballer, born 2004)" article', '2026-10-09'),
(950, 217, 'Real Madrid', 'club', '2023–2026', 35, 6, NULL, 'English Wikipedia infobox, "Gonzalo García (footballer, born 2004)" article', '2026-10-09'),
(950, 192, 'Fulham', 'club', '2026–', 5, 1, NULL, 'English Wikipedia infobox, "Gonzalo García (footballer, born 2004)" article', '2026-10-09'),
(950, NULL, 'Spain U18', 'international', '2021', 3, 0, NULL, 'English Wikipedia infobox, "Gonzalo García (footballer, born 2004)" article', '2026-10-09'),
(950, NULL, 'Spain U19', 'international', '2023', 10, 0, NULL, 'English Wikipedia infobox, "Gonzalo García (footballer, born 2004)" article', '2026-10-09'),
(950, NULL, 'Spain U21', 'international', '2025–', 10, 8, NULL, 'English Wikipedia infobox, "Gonzalo García (footballer, born 2004)" article', '2026-10-09'),
(950, 470, 'Spain', 'international', '2026–', 1, 0, NULL, 'English Wikipedia infobox, "Gonzalo García (footballer, born 2004)" article', '2026-10-09');
