-- Generated by data/research/build_teammate_questions.py -- do not hand-edit.
-- One row per mystery player with >= 3 fail-closed-verified former
-- teammates; teammate_ids is the 3 most recognizable (lowest entity id).
-- Regenerate if player_career_stats changes materially.

INSERT INTO teammate_questions (player_id, teammate_ids, source) VALUES
	-- George Weah: Roberto Baggio, Andriy Shevchenko, Paolo Maldini
	(548, '[549,553,587]', 'player_career_stats'),
	-- Roberto Baggio: George Weah, Paolo Maldini, Alessandro Del Piero
	(549, '[548,587,588]', 'player_career_stats'),
	-- Michael Owen: Alan Shearer, Wayne Rooney, Ryan Giggs
	(550, '[551,552,573]', 'player_career_stats'),
	-- Wayne Rooney: Michael Owen, Ruud van Nistelrooy, Ryan Giggs
	(552, '[550,572,573]', 'player_career_stats'),
	-- Andriy Shevchenko: George Weah, Kaka, Rivaldo
	(553, '[548,556,557]', 'player_career_stats'),
	-- Pavel Nedved: Fabio Cannavaro, Gianluigi Buffon, Alessandro Del Piero
	(554, '[555,586,588]', 'player_career_stats'),
	-- Fabio Cannavaro: Pavel Nedved, Ruud van Nistelrooy, David Beckham
	(555, '[554,572,575]', 'player_career_stats'),
	-- Kaka: Andriy Shevchenko, Ruud van Nistelrooy, Sergio Ramos
	(556, '[553,572,582]', 'player_career_stats'),
	-- Rivaldo: Andriy Shevchenko, Xavi Hernandez, Carles Puyol
	(557, '[553,580,584]', 'player_career_stats'),
	-- Johan Cruyff: Marco van Basten, Ruud Gullit, Frank Rijkaard
	(561, '[568,569,570]', 'player_career_stats'),
	-- Marco van Basten: Johan Cruyff, Ruud Gullit, Frank Rijkaard
	(568, '[561,569,570]', 'player_career_stats'),
	-- Ruud Gullit: Johan Cruyff, Marco van Basten, Frank Rijkaard
	(569, '[561,568,570]', 'player_career_stats'),
	-- Frank Rijkaard: Johan Cruyff, Marco van Basten, Ruud Gullit
	(570, '[561,568,569]', 'player_career_stats'),
	-- Dennis Bergkamp: Marco van Basten, Frank Rijkaard, Edwin van der Sar
	(571, '[568,570,643]', 'player_career_stats'),
	-- Ruud van Nistelrooy: Wayne Rooney, Fabio Cannavaro, Kaka
	(572, '[552,555,556]', 'player_career_stats'),
	-- Ryan Giggs: Michael Owen, Wayne Rooney, Ruud van Nistelrooy
	(573, '[550,552,572]', 'player_career_stats'),
	-- Paul Scholes: Michael Owen, Wayne Rooney, Ruud van Nistelrooy
	(574, '[550,552,572]', 'player_career_stats'),
	-- David Beckham: Michael Owen, Fabio Cannavaro, Ruud van Nistelrooy
	(575, '[550,555,572]', 'player_career_stats'),
	-- Steven Gerrard: Michael Owen, Luis Suarez, Fernando Torres
	(576, '[550,594,605]', 'player_career_stats'),
	-- Frank Lampard: Andriy Shevchenko, John Terry, Rio Ferdinand
	(577, '[553,578,579]', 'player_career_stats'),
	-- John Terry: Andriy Shevchenko, Frank Lampard, Gianfranco Zola
	(578, '[553,577,591]', 'player_career_stats'),
	-- Rio Ferdinand: Michael Owen, Wayne Rooney, Ruud van Nistelrooy
	(579, '[550,552,572]', 'player_career_stats'),
	-- Xavi Hernandez: Rivaldo, Andres Iniesta, Gerard Pique
	(580, '[557,581,583]', 'player_career_stats'),
	-- Andres Iniesta: Xavi Hernandez, Gerard Pique, Carles Puyol
	(581, '[580,583,584]', 'player_career_stats'),
	-- Sergio Ramos: Fabio Cannavaro, Kaka, Ruud van Nistelrooy
	(582, '[555,556,572]', 'player_career_stats'),
	-- Gerard Pique: Wayne Rooney, Ruud van Nistelrooy, Ryan Giggs
	(583, '[552,572,573]', 'player_career_stats'),
	-- Carles Puyol: Rivaldo, Xavi Hernandez, Andres Iniesta
	(584, '[557,580,581]', 'player_career_stats'),
	-- Iker Casillas: Michael Owen, Fabio Cannavaro, Kaka
	(585, '[550,555,556]', 'player_career_stats'),
	-- Gianluigi Buffon: Pavel Nedved, Fabio Cannavaro, Alessandro Del Piero
	(586, '[554,555,588]', 'player_career_stats'),
	-- Paolo Maldini: George Weah, Roberto Baggio, Andriy Shevchenko
	(587, '[548,549,553]', 'player_career_stats'),
	-- Alessandro Del Piero: Roberto Baggio, Pavel Nedved, Fabio Cannavaro
	(588, '[549,554,555]', 'player_career_stats'),
	-- Andrea Pirlo: Roberto Baggio, Andriy Shevchenko, Kaka
	(590, '[549,553,556]', 'player_career_stats'),
	-- Gianfranco Zola: Fabio Cannavaro, Diego Maradona, Ruud Gullit
	(591, '[555,560,569]', 'player_career_stats'),
	-- Roberto Carlos: Michael Owen, Fabio Cannavaro, Rivaldo
	(592, '[550,555,557]', 'player_career_stats'),
	-- Cafu: Andriy Shevchenko, Kaka, Rivaldo
	(593, '[553,556,557]', 'player_career_stats'),
	-- Luis Suarez: Steven Gerrard, Xavi Hernandez, Andres Iniesta
	(594, '[576,580,581]', 'player_career_stats'),
	-- Edinson Cavani: Gianluigi Buffon, Zlatan Ibrahimovic, Marcus Rashford
	(595, '[586,599,626]', 'player_career_stats'),
	-- Radamel Falcao: James Rodriguez, Fabinho, Bernardo Silva
	(596, '[597,635,744]', 'player_career_stats'),
	-- James Rodriguez: Sergio Ramos, Iker Casillas, Radamel Falcao
	(597, '[582,585,596]', 'player_career_stats'),
	-- Diego Forlan: Ruud van Nistelrooy, Ryan Giggs, Paul Scholes
	(598, '[572,573,574]', 'player_career_stats'),
	-- Zlatan Ibrahimovic: Wayne Rooney, Pavel Nedved, Fabio Cannavaro
	(599, '[552,554,555]', 'player_career_stats'),
	-- Thomas Muller: Manuel Neuer, Toni Kroos, Xabi Alonso
	(600, '[601,602,606]', 'player_career_stats'),
	-- Manuel Neuer: Thomas Muller, Toni Kroos, Xabi Alonso
	(601, '[600,602,606]', 'player_career_stats'),
	-- Toni Kroos: Sergio Ramos, Iker Casillas, James Rodriguez
	(602, '[582,585,597]', 'player_career_stats'),
	-- Sergio Aguero: Frank Lampard, Diego Forlan, Fernando Torres
	(603, '[577,598,605]', 'player_career_stats'),
	-- David Villa: Frank Lampard, Xavi Hernandez, Andres Iniesta
	(604, '[577,580,581]', 'player_career_stats'),
	-- Fernando Torres: Steven Gerrard, Frank Lampard, John Terry
	(605, '[576,577,578]', 'player_career_stats'),
	-- Xabi Alonso: Kaka, Ruud van Nistelrooy, Steven Gerrard
	(606, '[556,572,576]', 'player_career_stats'),
	-- Wesley Sneijder: Fabio Cannavaro, Ruud van Nistelrooy, Sergio Ramos
	(607, '[555,572,582]', 'player_career_stats'),
	-- Arjen Robben: Andriy Shevchenko, Fabio Cannavaro, Ruud van Nistelrooy
	(608, '[553,555,572]', 'player_career_stats'),
	-- Marco Reus: Mario Gotze, Ilkay Gundogan, Ousmane Dembele
	(609, '[610,612,615]', 'player_career_stats'),
	-- Mario Gotze: Thomas Muller, Manuel Neuer, Toni Kroos
	(610, '[600,601,602]', 'player_career_stats'),
	-- Mesut Ozil: Kaka, Sergio Ramos, Iker Casillas
	(611, '[556,582,585]', 'player_career_stats'),
	-- Ilkay Gundogan: Sergio Aguero, Marco Reus, Mario Gotze
	(612, '[603,609,610]', 'player_career_stats'),
	-- N'Golo Kante: John Terry, Riyad Mahrez, Fabinho
	(613, '[578,616,635]', 'player_career_stats'),
	-- Antoine Griezmann: Gerard Pique, Luis Suarez, Fernando Torres
	(614, '[583,594,605]', 'player_career_stats'),
	-- Ousmane Dembele: Andres Iniesta, Gerard Pique, Luis Suarez
	(615, '[581,583,594]', 'player_career_stats'),
	-- Riyad Mahrez: Sergio Aguero, Ilkay Gundogan, N'Golo Kante
	(616, '[603,612,613]', 'player_career_stats'),
	-- Victor Osimhen: Ilkay Gundogan, Khvicha Kvaratskhelia, Scott McTominay
	(617, '[612,693,695]', 'player_career_stats'),
	-- Achraf Hakimi: Sergio Ramos, James Rodriguez, Toni Kroos
	(618, '[582,597,602]', 'player_career_stats'),
	-- Vinicius Junior: Sergio Ramos, James Rodriguez, Toni Kroos
	(619, '[582,597,602]', 'player_career_stats'),
	-- Jude Bellingham: Toni Kroos, Marco Reus, Vinicius Junior
	(620, '[602,609,619]', 'player_career_stats'),
	-- Pedri: Gerard Pique, Ilkay Gundogan, Antoine Griezmann
	(621, '[583,612,614]', 'player_career_stats'),
	-- Gavi: Gerard Pique, Ilkay Gundogan, Antoine Griezmann
	(622, '[583,612,614]', 'player_career_stats'),
	-- Bukayo Saka: Mesut Ozil, Declan Rice, Petr Cech
	(623, '[611,625,642]', 'player_career_stats'),
	-- Phil Foden: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(624, '[603,612,616]', 'player_career_stats'),
	-- Declan Rice: Bukayo Saka, Gabriel Jesus, Viktor Gyokeres
	(625, '[623,681,692]', 'player_career_stats'),
	-- Marcus Rashford: Wayne Rooney, Edinson Cavani, Zlatan Ibrahimovic
	(626, '[552,595,599]', 'player_career_stats'),
	-- Son Heung-min: Ruud van Nistelrooy, Hugo Lloris, Kyle Walker
	(627, '[572,674,758]', 'player_career_stats'),
	-- Kaoru Mitoma: Alexis Mac Allister, Leandro Trossard, Moises Caicedo
	(628, '[694,717,781]', 'player_career_stats'),
	-- Takefusa Kubo: Sergio Ramos, James Rodriguez, Toni Kroos
	(629, '[582,597,602]', 'player_career_stats'),
	-- Lautaro Martinez: Achraf Hakimi, Denzel Dumfries, Andre Onana
	(630, '[618,690,775]', 'player_career_stats'),
	-- Julian Alvarez: Ilkay Gundogan, Antoine Griezmann, Riyad Mahrez
	(631, '[612,614,616]', 'player_career_stats'),
	-- Rodrygo: Sergio Ramos, James Rodriguez, Toni Kroos
	(632, '[582,597,602]', 'player_career_stats'),
	-- Federico Valverde: Sergio Ramos, James Rodriguez, Diego Forlan
	(633, '[582,597,598]', 'player_career_stats'),
	-- Casemiro: Sergio Ramos, Iker Casillas, James Rodriguez
	(634, '[582,585,597]', 'player_career_stats'),
	-- Fabinho: Radamel Falcao, N'Golo Kante, Virgil van Dijk
	(635, '[596,613,636]', 'player_career_stats'),
	-- Virgil van Dijk: Fabinho, Alisson Becker, Roberto Firmino
	(636, '[635,637,682]', 'player_career_stats'),
	-- Alisson Becker: Francesco Totti, Diego Forlan, Fabinho
	(637, '[589,598,635]', 'player_career_stats'),
	-- Ederson: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(638, '[603,612,616]', 'player_career_stats'),
	-- Thibaut Courtois: Frank Lampard, John Terry, Sergio Ramos
	(639, '[577,578,582]', 'player_career_stats'),
	-- Jan Oblak: Luis Suarez, Fernando Torres, Antoine Griezmann
	(640, '[594,605,614]', 'player_career_stats'),
	-- David de Gea: Michael Owen, Wayne Rooney, Ryan Giggs
	(641, '[550,552,573]', 'player_career_stats'),
	-- Petr Cech: Andriy Shevchenko, Frank Lampard, John Terry
	(642, '[553,577,578]', 'player_career_stats'),
	-- Edwin van der Sar: Michael Owen, Wayne Rooney, Frank Rijkaard
	(643, '[550,552,570]', 'player_career_stats'),
	-- Oliver Kahn: Toni Kroos, Michael Ballack, Lothar Matthaus
	(644, '[602,650,651]', 'player_career_stats'),
	-- Peter Schmeichel: Ryan Giggs, Paul Scholes, David Beckham
	(645, '[573,574,575]', 'player_career_stats'),
	-- Fabien Barthez: Ruud van Nistelrooy, Ryan Giggs, Paul Scholes
	(649, '[572,573,574]', 'player_career_stats'),
	-- Michael Ballack: Andriy Shevchenko, Frank Lampard, John Terry
	(650, '[553,577,578]', 'player_career_stats'),
	-- Jurgen Klinsmann: Oliver Kahn, Lothar Matthaus, Lilian Thuram
	(652, '[644,651,668]', 'player_career_stats'),
	-- Peter Crouch: Michael Owen, Steven Gerrard, Fernando Torres
	(660, '[550,576,605]', 'player_career_stats'),
	-- Jamie Vardy: N'Golo Kante, Riyad Mahrez, Harry Maguire
	(661, '[613,616,764]', 'player_career_stats'),
	-- Sergio Busquets: Xavi Hernandez, Andres Iniesta, Gerard Pique
	(662, '[580,581,583]', 'player_career_stats'),
	-- Marc-Andre ter Stegen: Xavi Hernandez, Andres Iniesta, Gerard Pique
	(663, '[580,581,583]', 'player_career_stats'),
	-- Robert Pires: Dennis Bergkamp, Diego Forlan, Patrick Vieira
	(664, '[571,598,665]', 'player_career_stats'),
	-- Patrick Vieira: George Weah, Roberto Baggio, Pavel Nedved
	(665, '[548,549,554]', 'player_career_stats'),
	-- Claude Makelele: Andriy Shevchenko, Frank Lampard, John Terry
	(666, '[553,577,578]', 'player_career_stats'),
	-- Marcel Desailly: George Weah, Roberto Baggio, Marco van Basten
	(667, '[548,549,568]', 'player_career_stats'),
	-- Lilian Thuram: George Weah, Pavel Nedved, Fabio Cannavaro
	(668, '[548,554,555]', 'player_career_stats'),
	-- Youri Djorkaeff: George Weah, Roberto Baggio, Andrea Pirlo
	(669, '[548,549,590]', 'player_career_stats'),
	-- David Trezeguet: Pavel Nedved, Fabio Cannavaro, Gianluigi Buffon
	(670, '[554,555,586]', 'player_career_stats'),
	-- Nicolas Anelka: Andriy Shevchenko, Dennis Bergkamp, Frank Lampard
	(671, '[553,571,577]', 'player_career_stats'),
	-- William Gallas: George Weah, Frank Lampard, John Terry
	(672, '[548,577,578]', 'player_career_stats'),
	-- Bacary Sagna: Frank Lampard, Sergio Aguero, Mesut Ozil
	(673, '[577,603,611]', 'player_career_stats'),
	-- Hugo Lloris: Son Heung-min, William Gallas, Olivier Giroud
	(674, '[627,672,677]', 'player_career_stats'),
	-- Raphael Varane: Kaka, Sergio Ramos, Iker Casillas
	(675, '[556,582,585]', 'player_career_stats'),
	-- Paul Pogba: Michael Owen, Wayne Rooney, Ryan Giggs
	(676, '[550,552,573]', 'player_career_stats'),
	-- Olivier Giroud: Zlatan Ibrahimovic, Mesut Ozil, N'Golo Kante
	(677, '[599,611,613]', 'player_career_stats'),
	-- Alexandre Lacazette: Mesut Ozil, Bukayo Saka, Petr Cech
	(678, '[611,623,642]', 'player_career_stats'),
	-- Moussa Dembele: Alexandre Lacazette, Rayan Cherki, Malo Gusto
	(680, '[678,752,787]', 'player_career_stats'),
	-- Gabriel Jesus: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(681, '[603,612,616]', 'player_career_stats'),
	-- Roberto Firmino: Riyad Mahrez, Fabinho, Virgil van Dijk
	(682, '[616,635,636]', 'player_career_stats'),
	-- Diogo Jota: Fernando Torres, Antoine Griezmann, Fabinho
	(683, '[605,614,635]', 'player_career_stats'),
	-- Darwin Nunez: Fabinho, Virgil van Dijk, Alisson Becker
	(684, '[635,636,637]', 'player_career_stats'),
	-- Cody Gakpo: Mario Gotze, Virgil van Dijk, Alisson Becker
	(685, '[610,636,637]', 'player_career_stats'),
	-- Bruno Fernandes: Edinson Cavani, Marcus Rashford, Casemiro
	(686, '[595,626,634]', 'player_career_stats'),
	-- Rasmus Hojlund: Marcus Rashford, Casemiro, Raphael Varane
	(687, '[626,634,675]', 'player_career_stats'),
	-- Gianluigi Donnarumma: Sergio Ramos, Zlatan Ibrahimovic, Fernando Torres
	(688, '[582,599,605]', 'player_career_stats'),
	-- Desire Doue: Ousmane Dembele, Achraf Hakimi, Gianluigi Donnarumma
	(689, '[615,618,688]', 'player_career_stats'),
	-- Denzel Dumfries: Mario Gotze, Lautaro Martinez, Cody Gakpo
	(690, '[610,630,685]', 'player_career_stats'),
	-- Serhou Guirassy: Desire Doue, Jeremy Doku, Jamie Gittens
	(691, '[689,751,792]', 'player_career_stats'),
	-- Viktor Gyokeres: Bukayo Saka, Declan Rice, Gabriel Jesus
	(692, '[623,625,681]', 'player_career_stats'),
	-- Khvicha Kvaratskhelia: Ousmane Dembele, Victor Osimhen, Achraf Hakimi
	(693, '[615,617,618]', 'player_career_stats'),
	-- Alexis Mac Allister: Kaoru Mitoma, Virgil van Dijk, Alisson Becker
	(694, '[628,636,637]', 'player_career_stats'),
	-- Scott McTominay: Edinson Cavani, Zlatan Ibrahimovic, Victor Osimhen
	(695, '[595,599,617]', 'player_career_stats'),
	-- Nuno Mendes: Sergio Ramos, Ousmane Dembele, Achraf Hakimi
	(696, '[582,615,618]', 'player_career_stats'),
	-- Joao Neves: Ousmane Dembele, Achraf Hakimi, Gianluigi Donnarumma
	(697, '[615,618,688]', 'player_career_stats'),
	-- Michael Olise: Thomas Muller, Manuel Neuer, Eberechi Eze
	(698, '[600,601,725]', 'player_career_stats'),
	-- Cole Palmer: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(699, '[603,612,616]', 'player_career_stats'),
	-- Raphinha: Ilkay Gundogan, Ousmane Dembele, Pedri
	(700, '[612,615,621]', 'player_career_stats'),
	-- Fabian Ruiz: Sergio Ramos, Ousmane Dembele, Victor Osimhen
	(701, '[582,615,617]', 'player_career_stats'),
	-- Vitinha: Sergio Ramos, Iker Casillas, Ousmane Dembele
	(702, '[582,585,615]', 'player_career_stats'),
	-- Florian Wirtz: Virgil van Dijk, Alisson Becker, Cody Gakpo
	(703, '[636,637,685]', 'player_career_stats'),
	-- Lamine Yamal: Ilkay Gundogan, Pedri, Gavi
	(704, '[612,621,622]', 'player_career_stats'),
	-- David Raya: Bukayo Saka, Declan Rice, Gabriel Jesus
	(705, '[623,625,681]', 'player_career_stats'),
	-- William Saliba: Mesut Ozil, Bukayo Saka, Declan Rice
	(706, '[611,623,625]', 'player_career_stats'),
	-- Cristhian Mosquera: Edinson Cavani, Bukayo Saka, Declan Rice
	(707, '[595,623,625]', 'player_career_stats'),
	-- Gabriel Magalhaes: Mesut Ozil, Victor Osimhen, Bukayo Saka
	(709, '[611,617,623]', 'player_career_stats'),
	-- Martin Odegaard: Sergio Ramos, James Rodriguez, Toni Kroos
	(710, '[582,597,602]', 'player_career_stats'),
	-- Gabriel Martinelli: Mesut Ozil, Bukayo Saka, Declan Rice
	(711, '[611,623,625]', 'player_career_stats'),
	-- Jurrien Timber: Bukayo Saka, Declan Rice, Gabriel Jesus
	(712, '[623,625,681]', 'player_career_stats'),
	-- Kepa Arrizabalaga: N'Golo Kante, Bukayo Saka, Declan Rice
	(713, '[613,623,625]', 'player_career_stats'),
	-- Jakub Kiwior: Bukayo Saka, Declan Rice, Gabriel Jesus
	(714, '[623,625,681]', 'player_career_stats'),
	-- Christian Norgaard: Bukayo Saka, Declan Rice, Gabriel Jesus
	(715, '[623,625,681]', 'player_career_stats'),
	-- Leandro Trossard: Bukayo Saka, Declan Rice, Kaoru Mitoma
	(717, '[623,625,628]', 'player_career_stats'),
	-- Noni Madueke: Mario Gotze, Bukayo Saka, Declan Rice
	(718, '[610,623,625]', 'player_career_stats'),
	-- Mikel Merino: Marco Reus, Mario Gotze, Ousmane Dembele
	(719, '[609,610,615]', 'player_career_stats'),
	-- Kai Havertz: N'Golo Kante, Bukayo Saka, Declan Rice
	(720, '[613,623,625]', 'player_career_stats'),
	-- Riccardo Calafiori: Bukayo Saka, Declan Rice, Gabriel Jesus
	(721, '[623,625,681]', 'player_career_stats'),
	-- Martin Zubimendi: Bukayo Saka, Declan Rice, Takefusa Kubo
	(722, '[623,625,629]', 'player_career_stats'),
	-- Myles Lewis-Skelly: Bukayo Saka, Declan Rice, Gabriel Jesus
	(723, '[623,625,681]', 'player_career_stats'),
	-- Ethan Nwaneri: Bukayo Saka, Declan Rice, Gabriel Jesus
	(724, '[623,625,681]', 'player_career_stats'),
	-- Eberechi Eze: Bukayo Saka, Declan Rice, Gabriel Jesus
	(725, '[623,625,681]', 'player_career_stats'),
	-- Trent Alexander-Arnold: Vinicius Junior, Jude Bellingham, Rodrygo
	(726, '[619,620,632]', 'player_career_stats'),
	-- Andrew Robertson: Fabinho, Virgil van Dijk, Alisson Becker
	(727, '[635,636,637]', 'player_career_stats'),
	-- Ibrahima Konate: Fabinho, Virgil van Dijk, Alisson Becker
	(728, '[635,636,637]', 'player_career_stats'),
	-- Dominik Szoboszlai: Virgil van Dijk, Alisson Becker, Diogo Jota
	(729, '[636,637,683]', 'player_career_stats'),
	-- Ryan Gravenberch: Thomas Muller, Manuel Neuer, Virgil van Dijk
	(730, '[600,601,636]', 'player_career_stats'),
	-- Curtis Jones: Fabinho, Virgil van Dijk, Alisson Becker
	(731, '[635,636,637]', 'player_career_stats'),
	-- Luis Diaz: Iker Casillas, Manuel Neuer, Fabinho
	(732, '[585,601,635]', 'player_career_stats'),
	-- Federico Chiesa: Virgil van Dijk, Alisson Becker, Paul Pogba
	(733, '[636,637,676]', 'player_career_stats'),
	-- Hugo Ekitike: Mario Gotze, Ousmane Dembele, Achraf Hakimi
	(734, '[610,615,618]', 'player_career_stats'),
	-- Alexander Isak: Marco Reus, Mario Gotze, Virgil van Dijk
	(735, '[609,610,636]', 'player_career_stats'),
	-- Jeremie Frimpong: Virgil van Dijk, Alisson Becker, Cody Gakpo
	(736, '[636,637,685]', 'player_career_stats'),
	-- Milos Kerkez: Zlatan Ibrahimovic, Virgil van Dijk, Alisson Becker
	(737, '[599,636,637]', 'player_career_stats'),
	-- Giorgi Mamardashvili: Edinson Cavani, Virgil van Dijk, Alisson Becker
	(738, '[595,636,637]', 'player_career_stats'),
	-- Joe Gomez: Fabinho, Virgil van Dijk, Alisson Becker
	(739, '[635,636,637]', 'player_career_stats'),
	-- Wataru Endo: Virgil van Dijk, Alisson Becker, Diogo Jota
	(740, '[636,637,683]', 'player_career_stats'),
	-- Harvey Elliott: Fabinho, Virgil van Dijk, Alisson Becker
	(741, '[635,636,637]', 'player_career_stats'),
	-- Caoimhin Kelleher: Fabinho, Virgil van Dijk, Alisson Becker
	(742, '[635,636,637]', 'player_career_stats'),
	-- Rodri: Sergio Aguero, Ilkay Gundogan, Antoine Griezmann
	(743, '[603,612,614]', 'player_career_stats'),
	-- Bernardo Silva: Radamel Falcao, Sergio Aguero, Ilkay Gundogan
	(744, '[596,603,612]', 'player_career_stats'),
	-- Ruben Dias: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(745, '[603,612,616]', 'player_career_stats'),
	-- Josko Gvardiol: Ilkay Gundogan, Phil Foden, Julian Alvarez
	(746, '[612,624,631]', 'player_career_stats'),
	-- John Stones: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(747, '[603,612,616]', 'player_career_stats'),
	-- Nathan Ake: Frank Lampard, John Terry, Sergio Aguero
	(748, '[577,578,603]', 'player_career_stats'),
	-- Jack Grealish: John Terry, Ilkay Gundogan, Riyad Mahrez
	(749, '[578,612,616]', 'player_career_stats'),
	-- Savinho: Ilkay Gundogan, Phil Foden, Ederson
	(750, '[612,624,638]', 'player_career_stats'),
	-- Jeremy Doku: Ilkay Gundogan, Phil Foden, Julian Alvarez
	(751, '[612,624,631]', 'player_career_stats'),
	-- Rayan Cherki: Phil Foden, Alexandre Lacazette, Moussa Dembele
	(752, '[624,678,680]', 'player_career_stats'),
	-- Tijjani Reijnders: Phil Foden, Olivier Giroud, Gianluigi Donnarumma
	(753, '[624,677,688]', 'player_career_stats'),
	-- Omar Marmoush: Mario Gotze, Phil Foden, Gianluigi Donnarumma
	(754, '[610,624,688]', 'player_career_stats'),
	-- Matheus Nunes: Ilkay Gundogan, Phil Foden, Julian Alvarez
	(755, '[612,624,631]', 'player_career_stats'),
	-- Rico Lewis: Ilkay Gundogan, Riyad Mahrez, Phil Foden
	(756, '[612,616,624]', 'player_career_stats'),
	-- Nico Gonzalez: Gerard Pique, Antoine Griezmann, Ousmane Dembele
	(757, '[583,614,615]', 'player_career_stats'),
	-- Kyle Walker: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(758, '[603,612,616]', 'player_career_stats'),
	-- James Trafford: Ilkay Gundogan, Riyad Mahrez, Phil Foden
	(759, '[612,616,624]', 'player_career_stats'),
	-- Oscar Bobb: Ilkay Gundogan, Phil Foden, Julian Alvarez
	(760, '[612,624,631]', 'player_career_stats'),
	-- Abdukodir Khusanov: Phil Foden, Gianluigi Donnarumma, Rodri
	(761, '[624,688,743]', 'player_career_stats'),
	-- Matthijs de Ligt: Gianluigi Buffon, Thomas Muller, Manuel Neuer
	(762, '[586,600,601]', 'player_career_stats'),
	-- Lisandro Martinez: Marcus Rashford, Casemiro, David de Gea
	(763, '[626,634,641]', 'player_career_stats'),
	-- Harry Maguire: Edinson Cavani, Riyad Mahrez, Marcus Rashford
	(764, '[595,616,626]', 'player_career_stats'),
	-- Luke Shaw: Wayne Rooney, Edinson Cavani, Zlatan Ibrahimovic
	(765, '[552,595,599]', 'player_career_stats'),
	-- Diogo Dalot: Iker Casillas, Edinson Cavani, Marcus Rashford
	(766, '[585,595,626]', 'player_career_stats'),
	-- Noussair Mazraoui: Thomas Muller, Manuel Neuer, Marcus Rashford
	(767, '[600,601,626]', 'player_career_stats'),
	-- Kobbie Mainoo: Marcus Rashford, Casemiro, David de Gea
	(768, '[626,634,641]', 'player_career_stats'),
	-- Mason Mount: N'Golo Kante, Marcus Rashford, Casemiro
	(769, '[613,626,634]', 'player_career_stats'),
	-- Bryan Mbeumo: Marcus Rashford, Casemiro, Bruno Fernandes
	(770, '[626,634,686]', 'player_career_stats'),
	-- Matheus Cunha: Luis Suarez, Antoine Griezmann, Marcus Rashford
	(771, '[594,614,626]', 'player_career_stats'),
	-- Benjamin Sesko: Marcus Rashford, Casemiro, Bruno Fernandes
	(772, '[626,634,686]', 'player_career_stats'),
	-- Amad Diallo: Edinson Cavani, Marcus Rashford, Casemiro
	(773, '[595,626,634]', 'player_career_stats'),
	-- Alejandro Garnacho: Marcus Rashford, Casemiro, David de Gea
	(774, '[626,634,641]', 'player_career_stats'),
	-- Andre Onana: Marcus Rashford, Lautaro Martinez, Casemiro
	(775, '[626,630,634]', 'player_career_stats'),
	-- Leny Yoro: Marcus Rashford, Casemiro, Bruno Fernandes
	(776, '[626,634,686]', 'player_career_stats'),
	-- Joshua Zirkzee: Thomas Muller, Manuel Neuer, Marcus Rashford
	(777, '[600,601,626]', 'player_career_stats'),
	-- Patrick Dorgu: Marcus Rashford, Casemiro, Bruno Fernandes
	(778, '[626,634,686]', 'player_career_stats'),
	-- Senne Lammens: Marcus Rashford, Casemiro, Bruno Fernandes
	(779, '[626,634,686]', 'player_career_stats'),
	-- Enzo Fernandez: Julian Alvarez, Joao Neves, Cole Palmer
	(780, '[631,697,699]', 'player_career_stats'),
	-- Moises Caicedo: Kaoru Mitoma, Alexis Mac Allister, Cole Palmer
	(781, '[628,694,699]', 'player_career_stats'),
	-- Reece James: N'Golo Kante, Olivier Giroud, Cole Palmer
	(782, '[613,677,699]', 'player_career_stats'),
	-- Levi Colwill: N'Golo Kante, Cole Palmer, Kepa Arrizabalaga
	(783, '[613,699,713]', 'player_career_stats'),
	-- Wesley Fofana: N'Golo Kante, Jamie Vardy, Cole Palmer
	(784, '[613,661,699]', 'player_career_stats'),
	-- Trevoh Chalobah: N'Golo Kante, Olivier Giroud, Cole Palmer
	(785, '[613,677,699]', 'player_career_stats'),
	-- Marc Cucurella: Andres Iniesta, Gerard Pique, Luis Suarez
	(786, '[581,583,594]', 'player_career_stats'),
	-- Malo Gusto: Alexandre Lacazette, Moussa Dembele, Cole Palmer
	(787, '[678,680,699]', 'player_career_stats'),
	-- Robert Sanchez: Kaoru Mitoma, Viktor Gyokeres, Alexis Mac Allister
	(788, '[628,692,694]', 'player_career_stats'),
	-- Nicolas Jackson: Cole Palmer, Kepa Arrizabalaga, Noni Madueke
	(789, '[699,713,718]', 'player_career_stats'),
	-- Christopher Nkunku: Gianluigi Buffon, Edinson Cavani, Zlatan Ibrahimovic
	(790, '[586,595,599]', 'player_career_stats'),
	-- Pedro Neto: Diogo Jota, Cole Palmer, Kepa Arrizabalaga
	(791, '[683,699,713]', 'player_career_stats'),
	-- Jamie Gittens: Marco Reus, Jude Bellingham, Serhou Guirassy
	(792, '[609,620,691]', 'player_career_stats'),
	-- Joao Pedro: Kaoru Mitoma, Cole Palmer, Alejandro Garnacho
	(793, '[628,699,774]', 'player_career_stats'),
	-- Estevao: Cole Palmer, Alejandro Garnacho, Enzo Fernandez
	(794, '[699,774,780]', 'player_career_stats'),
	-- Romeo Lavia: Ilkay Gundogan, Riyad Mahrez, Phil Foden
	(795, '[612,616,624]', 'player_career_stats'),
	-- Liam Delap: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(796, '[603,612,616]', 'player_career_stats'),
	-- Tosin Adarabioyo: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(797, '[603,612,616]', 'player_career_stats'),
	-- Raheem Sterling: Steven Gerrard, Luis Suarez, Sergio Aguero
	(798, '[576,594,603]', 'player_career_stats'),
	-- Cesar Azpilicueta: Frank Lampard, John Terry, Fernando Torres
	(799, '[577,578,605]', 'player_career_stats'),
	-- Eden Hazard: Frank Lampard, John Terry, Sergio Ramos
	(800, '[577,578,582]', 'player_career_stats'),
	-- James Maddison: Son Heung-min, Jamie Vardy, Hugo Lloris
	(801, '[627,661,674]', 'player_career_stats'),
	-- Dejan Kulusevski: Gianluigi Buffon, Son Heung-min, Hugo Lloris
	(802, '[586,627,674]', 'player_career_stats'),
	-- Dominic Solanke: John Terry, Fernando Torres, N'Golo Kante
	(803, '[578,605,613]', 'player_career_stats'),
	-- Brennan Johnson: Son Heung-min, Hugo Lloris, James Maddison
	(804, '[627,674,801]', 'player_career_stats'),
	-- Richarlison: James Rodriguez, Son Heung-min, Hugo Lloris
	(805, '[597,627,674]', 'player_career_stats'),
	-- Destiny Udogie: Son Heung-min, Hugo Lloris, James Maddison
	(806, '[627,674,801]', 'player_career_stats'),
	-- Pedro Porro: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(807, '[603,612,616]', 'player_career_stats'),
	-- Micky van de Ven: Son Heung-min, Hugo Lloris, Omar Marmoush
	(808, '[627,674,754]', 'player_career_stats'),
	-- Cristian Romero: Gianluigi Buffon, Son Heung-min, Hugo Lloris
	(809, '[586,627,674]', 'player_career_stats'),
	-- Guglielmo Vicario: Son Heung-min, Hugo Lloris, Bruno Fernandes
	(810, '[627,674,686]', 'player_career_stats'),
	-- Yves Bissouma: Son Heung-min, Kaoru Mitoma, Hugo Lloris
	(811, '[627,628,674]', 'player_career_stats'),
	-- Pape Matar Sarr: Son Heung-min, Hugo Lloris, James Maddison
	(812, '[627,674,801]', 'player_career_stats'),
	-- Rodrigo Bentancur: Gianluigi Buffon, Son Heung-min, Hugo Lloris
	(813, '[586,627,674]', 'player_career_stats'),
	-- Wilson Odobert: Son Heung-min, Savinho, James Trafford
	(814, '[627,750,759]', 'player_career_stats'),
	-- Mathys Tel: Thomas Muller, Manuel Neuer, Serhou Guirassy
	(815, '[600,601,691]', 'player_career_stats'),
	-- Mohammed Kudus: Jurrien Timber, Ryan Gravenberch, Lisandro Martinez
	(816, '[712,730,763]', 'player_career_stats'),
	-- Xavi Simons: Sergio Ramos, Ousmane Dembele, Achraf Hakimi
	(817, '[582,615,618]', 'player_career_stats'),
	-- Randal Kolo Muani: Mario Gotze, Ousmane Dembele, Achraf Hakimi
	(818, '[610,615,618]', 'player_career_stats'),
	-- Archie Gray: Son Heung-min, James Maddison, Dejan Kulusevski
	(819, '[627,801,802]', 'player_career_stats'),
	-- Lucas Bergvall: Son Heung-min, James Maddison, Dejan Kulusevski
	(820, '[627,801,802]', 'player_career_stats'),
	-- Joao Palhinha: Thomas Muller, Manuel Neuer, Bruno Fernandes
	(821, '[600,601,686]', 'player_career_stats'),
	-- Bruno Guimaraes: Moussa Dembele, Alexander Isak, Rayan Cherki
	(822, '[680,735,752]', 'player_career_stats'),
	-- Sandro Tonali: Zlatan Ibrahimovic, Olivier Giroud, Alexander Isak
	(823, '[599,677,735]', 'player_career_stats'),
	-- Joelinton: Alexander Isak, Bruno Guimaraes, Sandro Tonali
	(824, '[735,822,823]', 'player_career_stats'),
	-- Anthony Gordon: Wayne Rooney, James Rodriguez, Alexander Isak
	(825, '[552,597,735]', 'player_career_stats'),
	-- Harvey Barnes: Riyad Mahrez, Jamie Vardy, Alexander Isak
	(826, '[616,661,735]', 'player_career_stats'),
	-- Jacob Murphy: Mikel Merino, Alexander Isak, James Maddison
	(827, '[719,735,801]', 'player_career_stats'),
	-- Nick Pope: Alexander Isak, Joe Gomez, Bruno Guimaraes
	(828, '[735,739,822]', 'player_career_stats'),
	-- Aaron Ramsdale: Bukayo Saka, Declan Rice, Alexandre Lacazette
	(829, '[623,625,678]', 'player_career_stats'),
	-- Sven Botman: Alexander Isak, Bruno Guimaraes, Sandro Tonali
	(830, '[735,822,823]', 'player_career_stats'),
	-- Fabian Schar: Alexander Isak, Bruno Guimaraes, Sandro Tonali
	(831, '[735,822,823]', 'player_career_stats'),
	-- Kieran Trippier: Luis Suarez, Sergio Aguero, Son Heung-min
	(832, '[594,603,627]', 'player_career_stats'),
	-- Dan Burn: Kaoru Mitoma, Moussa Dembele, Viktor Gyokeres
	(833, '[628,680,692]', 'player_career_stats'),
	-- Tino Livramento: Alexander Isak, Romeo Lavia, Bruno Guimaraes
	(834, '[735,795,822]', 'player_career_stats'),
	-- Nick Woltemade: Bruno Guimaraes, Sandro Tonali, Joelinton
	(835, '[822,823,824]', 'player_career_stats'),
	-- Yoane Wissa: David Raya, Christian Norgaard, Bryan Mbeumo
	(836, '[705,715,770]', 'player_career_stats'),
	-- Anthony Elanga: Edinson Cavani, Marcus Rashford, Casemiro
	(837, '[595,626,634]', 'player_career_stats'),
	-- Malick Thiaw: Zlatan Ibrahimovic, Olivier Giroud, Tijjani Reijnders
	(838, '[599,677,753]', 'player_career_stats'),
	-- Emiliano Martinez: Mesut Ozil, Bukayo Saka, Petr Cech
	(839, '[611,623,642]', 'player_career_stats'),
	-- Ollie Watkins: David Raya, Christian Norgaard, Jack Grealish
	(840, '[705,715,749]', 'player_career_stats'),
	-- Morgan Rogers: Sergio Aguero, Ilkay Gundogan, Riyad Mahrez
	(841, '[603,612,616]', 'player_career_stats'),
	-- Youri Tielemans: Radamel Falcao, Fabinho, Jamie Vardy
	(842, '[596,635,661]', 'player_career_stats'),
	-- John McGinn: Jack Grealish, Emiliano Martinez, Ollie Watkins
	(843, '[749,839,840]', 'player_career_stats'),
	-- Boubacar Kamara: Emiliano Martinez, Ollie Watkins, Morgan Rogers
	(844, '[839,840,841]', 'player_career_stats'),
	-- Amadou Onana: Anthony Gordon, Sven Botman, Emiliano Martinez
	(845, '[825,830,839]', 'player_career_stats'),
	-- Ezri Konsa: Jack Grealish, Emiliano Martinez, Ollie Watkins
	(846, '[749,839,840]', 'player_career_stats'),
	-- Pau Torres: Rodri, Nicolas Jackson, Emiliano Martinez
	(847, '[743,789,839]', 'player_career_stats'),
	-- Matty Cash: Jack Grealish, Brennan Johnson, Emiliano Martinez
	(848, '[749,804,839]', 'player_career_stats'),
	-- Lucas Digne: Andres Iniesta, Gerard Pique, Luis Suarez
	(849, '[581,583,594]', 'player_career_stats'),
	-- Emiliano Buendia: Emiliano Martinez, Ollie Watkins, Morgan Rogers
	(850, '[839,840,841]', 'player_career_stats'),
	-- Donyell Malen: Marco Reus, Mario Gotze, Jude Bellingham
	(851, '[609,610,620]', 'player_career_stats'),
	-- Evann Guessand: Emiliano Martinez, Ollie Watkins, Morgan Rogers
	(852, '[839,840,841]', 'player_career_stats'),
	-- Leon Bailey: Florian Wirtz, Leandro Trossard, Kai Havertz
	(853, '[703,717,720]', 'player_career_stats'),
	-- Jarrod Bowen: Declan Rice, Andrew Robertson, Harry Maguire
	(854, '[625,727,764]', 'player_career_stats'),
	-- Lucas Paqueta: Zlatan Ibrahimovic, Vinicius Junior, Declan Rice
	(855, '[599,619,625]', 'player_career_stats'),
	-- James Ward-Prowse: Virgil van Dijk, Luke Shaw, Romeo Lavia
	(856, '[636,765,795]', 'player_career_stats'),
	-- Niclas Fullkrug: Marco Reus, Jamie Gittens, Mohammed Kudus
	(857, '[609,792,816]', 'player_career_stats'),
	-- Max Kilman: Diogo Jota, Matheus Nunes, Matheus Cunha
	(858, '[683,755,771]', 'player_career_stats'),
	-- Jean-Philippe Mateta: Alexandre Lacazette, Michael Olise, Eberechi Eze
	(859, '[678,698,725]', 'player_career_stats'),
	-- Marc Guehi: N'Golo Kante, Olivier Giroud, Michael Olise
	(860, '[613,677,698]', 'player_career_stats'),
	-- Adam Wharton: Eberechi Eze, Jean-Philippe Mateta, Marc Guehi
	(861, '[725,859,860]', 'player_career_stats'),
	-- Daichi Kamada: Mario Gotze, Eberechi Eze, Randal Kolo Muani
	(862, '[610,725,818]', 'player_career_stats'),
	-- Ismaila Sarr: Eberechi Eze, Joao Pedro, Jean-Philippe Mateta
	(863, '[725,793,859]', 'player_career_stats'),
	-- Daniel Munoz: Eberechi Eze, Jean-Philippe Mateta, Marc Guehi
	(864, '[725,859,860]', 'player_career_stats'),
	-- Dean Henderson: Wayne Rooney, Edinson Cavani, Zlatan Ibrahimovic
	(865, '[552,595,599]', 'player_career_stats'),
	-- Jordan Pickford: Wayne Rooney, James Rodriguez, Richarlison
	(867, '[552,597,805]', 'player_career_stats'),
	-- Idrissa Gueye: Wayne Rooney, Sergio Ramos, Edinson Cavani
	(868, '[552,582,595]', 'player_career_stats'),
	-- Dwight McNeil: Anthony Gordon, Nick Pope, Amadou Onana
	(869, '[825,828,845]', 'player_career_stats'),
	-- Iliman Ndiaye: Aaron Ramsdale, Ismaila Sarr, Jordan Pickford
	(870, '[829,863,867]', 'player_career_stats'),
	-- Beto: Amadou Onana, Jordan Pickford, Idrissa Gueye
	(871, '[845,867,868]', 'player_career_stats'),
	-- James Tarkowski: Anthony Gordon, Nick Pope, Amadou Onana
	(872, '[825,828,845]', 'player_career_stats'),
	-- Jarrad Branthwaite: James Rodriguez, Richarlison, Anthony Gordon
	(873, '[597,805,825]', 'player_career_stats'),
	-- Bernd Leno: Mesut Ozil, Bukayo Saka, Son Heung-min
	(874, '[611,623,627]', 'player_career_stats'),
	-- Antonee Robinson: Wayne Rooney, John Stones, Tosin Adarabioyo
	(875, '[552,747,797]', 'player_career_stats'),
	-- Joachim Andersen: Moussa Dembele, Michael Olise, Eberechi Eze
	(876, '[680,698,725]', 'player_career_stats'),
	-- Emile Smith Rowe: Mesut Ozil, Bukayo Saka, Declan Rice
	(877, '[611,623,625]', 'player_career_stats'),
	-- Alex Iwobi: James Rodriguez, Mesut Ozil, Bukayo Saka
	(878, '[597,611,623]', 'player_career_stats'),
	-- Raul Jimenez: Antoine Griezmann, Ederson, Jan Oblak
	(879, '[614,638,640]', 'player_career_stats'),
	-- Harry Wilson: Steven Gerrard, Fabinho, Virgil van Dijk
	(880, '[576,635,636]', 'player_career_stats'),
	-- Bart Verbruggen: Kaoru Mitoma, Joao Pedro, Lewis Dunk
	(881, '[628,793,882]', 'player_career_stats'),
	-- Lewis Dunk: Kaoru Mitoma, Viktor Gyokeres, Alexis Mac Allister
	(882, '[628,692,694]', 'player_career_stats'),
	-- Jan Paul van Hecke: Kaoru Mitoma, Viktor Gyokeres, Alexis Mac Allister
	(883, '[628,692,694]', 'player_career_stats'),
	-- Carlos Baleba: Kaoru Mitoma, Leny Yoro, Joao Pedro
	(884, '[628,776,793]', 'player_career_stats'),
	-- Yasin Ayari: Kaoru Mitoma, Joao Pedro, Bart Verbruggen
	(885, '[628,793,881]', 'player_career_stats'),
	-- Georginio Rutter: Kaoru Mitoma, Serhou Guirassy, Jeremy Doku
	(886, '[628,691,751]', 'player_career_stats'),
	-- Danny Welbeck: Michael Owen, Wayne Rooney, Ryan Giggs
	(887, '[550,552,573]', 'player_career_stats'),
	-- Igor Thiago: Christian Norgaard, Caoimhin Kelleher, Bryan Mbeumo
	(888, '[715,742,770]', 'player_career_stats'),
	-- Mikkel Damsgaard: David Raya, Christian Norgaard, Caoimhin Kelleher
	(889, '[705,715,742]', 'player_career_stats'),
	-- Nathan Collins: David Raya, Christian Norgaard, Caoimhin Kelleher
	(890, '[705,715,742]', 'player_career_stats'),
	-- Keane Lewis-Potter: David Raya, Christian Norgaard, Caoimhin Kelleher
	(891, '[705,715,742]', 'player_career_stats'),
	-- Kevin Schade: David Raya, Christian Norgaard, Caoimhin Kelleher
	(892, '[705,715,742]', 'player_career_stats'),
	-- Antoine Semenyo: Milos Kerkez, Dominic Solanke, Justin Kluivert
	(893, '[737,803,894]', 'player_career_stats'),
	-- Justin Kluivert: Riccardo Calafiori, Milos Kerkez, Matthijs de Ligt
	(894, '[721,737,762]', 'player_career_stats'),
	-- Marcus Tavernier: Milos Kerkez, Dominic Solanke, Antoine Semenyo
	(895, '[737,803,893]', 'player_career_stats'),
	-- Ryan Christie: Moussa Dembele, Jeremie Frimpong, Milos Kerkez
	(896, '[680,736,737]', 'player_career_stats'),
	-- Adrien Truffert: Desire Doue, Serhou Guirassy, Jeremy Doku
	(897, '[689,691,751]', 'player_career_stats'),
	-- Djordje Petrovic: Cole Palmer, Kepa Arrizabalaga, Noni Madueke
	(898, '[699,713,718]', 'player_career_stats'),
	-- Ilya Zabarnyi: Ousmane Dembele, Achraf Hakimi, Desire Doue
	(899, '[615,618,689]', 'player_career_stats'),
	-- Dean Huijsen: Vinicius Junior, Jude Bellingham, Rodrygo
	(900, '[619,620,632]', 'player_career_stats');
